graylog2-web-interface/src/@types/graylog-web-plugin/index.d.ts, graylog2-web-interface/src/components/navigation/Navigation.test.tsx, graylog2-web-interface/src/components/navigation/Navigation.tsx, graylog2-web-interface/src/routing/AppRouter.test.tsx, graylog2-web-interface/src/routing/AppRouter.tsx
With this feature it will be possible to only register a specific plugin route or menu item when a defined feature flag is enabled.
Example for routes:
```
routes: [
{ path: '/the-path', component: TheComponent, requiredFeatureFlag: 'required_feature_flag' },
]
```
Example for menu items:
```
{ path: '/the-path', description: 'The Menu Item', permissions: '*', requiredFeatureFlag: 'required_feature_flag' }
```
Example for menu item which is a dropdown:
```
navigation: [
{
description: 'The Menu Item',
children: [
{ path: '/the-path', description: 'The Dropdown Item', permissions: '*', requiredFeatureFlag: 'required_feature_flag' },
]
}
];
```
If you need to hide a default non-plugin route behind a feature flag, you can just wrap the route component:
```
<IfFeatureEnabled …
```
=> Control registration of pluggable routes and navigation items depending on enabled feature flags.

graylog2-server/src/main/java/org/graylog2/search/SearchQueryParser.java, graylog2-server/src/test/java/org/graylog2/search/SearchQueryParserTest.java
SearchParser can now automatically prefix fields during parsing, which is useful for creating queries for nested/referenced Mongo documents.
I.e. if we have a document like that: 
```
{
search_id : "624ab333b99a6847d47bb8ee",
referencedViews : [
{
"title" : "Super-dashboard",
"type" : "DASHBOARD"
}
]
}
```
and we want to let our users filter referencedViews, user can write queries like "type:DASHBOARD" and SearchParser will be able to change field from "type" to "referencedViews.type" if created with "referencedViews." prefix.
I need this functionality for Search Filters Usage page, where I filter 2 joined collections of "views" and "searches". 
1. Unit tests have been added.
2. It has been manually tested with REST API browser.
=> Search parser can prefix fields for querying nested Mongo documents.

graylog2-web-interface/src/views/components/messagelist/MessageTableEntry.tsx, graylog2-web-interface/src/views/components/messagelist/MessageTableProviders.test.tsx, graylog2-web-interface/src/views/components/messagelist/MessageTableProviders.tsx, graylog2-web-interface/src/views/components/widgets/MessageTable.tsx, graylog2-web-interface/src/views/types.ts
Adds to the plugin system to allow for additional MessageTable contexts.
- Additional context to the MessageTable.
- Tests for the new MessageTableProviders component.
Need the ability to provide additional context to the MessageTable
Tested locally and unit tests have been run.
=> Message Table Context Providers

graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailSender.java, graylog2-server/src/main/java/org/graylog2/shared/email/EmailFactory.java
Pre 4.3, a NPE was also thrown when there was no sender in both the notifiation settings and the config. This is also now taken care of and a more verbose TransportConfigurationException is thrown. 
The possible NPE was introduced with https://github.com/Graylog2/graylog2-server/pull/12034 where the behavior was changed from first checking for a notification setting from address to first setting the config from address and overwriting it with the notification setting.
=> Fix NPE in email notification

graylog2-server/src/main/java/org/graylog2/rest/models/tools/responses/PageListResponse.java, graylog2-server/src/test/java/org/graylog2/rest/models/tools/responses/PageListResponseTest.java
PageListResponse class has a new method that can hide confidential data.
I need it for Search Filters Usage list, where some pieces of information need to be hidden if a user misses proper permissions.
With unit test.
=> PageListResponse can hide confidential data

graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/TokenCollectingQueryParser.java
fixes #13037
see the error description in the issue 
Our own Parser returned a result in `getBooleanQuery()` even if the superclass returns `null` in the same case. This PR fixes this behaviour.
**Note: backport to 4.3?**
=> TokenCollectingQueryParser.getBooleanQuery() is prone to create NPEs

graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java
Previously all Errors (Exceptions are handled) haven't been logged to
the log file but only STDERR. Not logging these errors can make
debugging harder if STDERR output and the log files are configured to
be in different places. (e.g., operating system packages with systemd)
=> Adjust server startup to log all throwables to the log file

graylog2-web-interface/src/components/common/PublicNotifications.test.tsx, graylog2-web-interface/src/components/common/PublicNotifications.tsx
Backport the bug fix https://github.com/Graylog2/graylog2-server/pull/12704 to consider the `isActive` attribute on notifications correctly.
Also back ported the Jest tests for this bug fix.
=> Backport the bugfix to consider active attribute on notification

graylog2-server/src/main/java/org/graylog/plugins/map/geoip/GeoIpResolverEngine.java, graylog2-server/src/test/java/org/graylog/plugins/map/geoip/GeoIpResolverEngineTest.java
Reverts to using pre-4.3 Geo IP processor logic if the GIM schema enforcement is disabled
4.3 introduced a breaking change to fields added by the Geo Location Processor. Fields had the GIM Geo-location subfield suffixes added even with the Graylog Schema enforcement disabled. Closes #12909 
Confirm that added IP fields have the original field name post-fixed with  `_country_code`, `_geolocation`, and `_city_name`  when Geo IP processor has GIM enforcement disabled and that the GIM fields are added if it is enabled.
`Enforce Graylog schema` disabled:
`Enforce Graylog schema` enabled:
=> Use legacy Geo IP fields if GIM schema enforcement is disabled

UPGRADING.md, graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java, graylog2-server/src/main/java/org/graylog2/migrations/V20220719130704_ImprovedDefaultProcessingOrderMigration.java
New Graylog Installations will have a new message processing
order:
The `Message Filter Chain` will run before the `Pipeline Processor`
This enables the more intuitive stream rules to assign messages to streams, before they
are passed to the pipeline interpreter.
Fixes #5040
=> Define a new improved default message processing order

graylog2-web-interface/src/views/components/searchbar/SearchBarAutocompletions.ts
_Please note, this is a backport of #12991 for 4.3_
With this PR we are now focusing the first suggestion in the query input autocompletion. With this change we are reenabling the default `react-ace` behaviour. This reduces the amount of click it takes to select a suggestion.
Related to: #6909
=> Auto focus first suggestion in query input autocompletion. (backport of #12991 for 4.3)

graylog2-web-interface/src/views/components/searchbar/SearchBarAutocompletions.ts
_Please note, this is a backport of #12991 for 4.2_
With this PR we are now focusing the first suggestion in the query input autocompletion. With this change we are reenabling the default `react-ace` behaviour. This reduces the amount of click it takes to select a suggestion.
Related to: #6909
=> Auto focus first suggestion in query input autocompletion. (backport of #12991 for 4.2)

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/searchfilters/db/SearchFilterVisibilityCheckStatus.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/searchfilters/db/SearchFilterVisibilityChecker.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewsResourceTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/searchfilters/db/SearchFilterVisibilityCheckerTest.java
Block create/update of a view if forbidden/hidden search filters are used.
When it comes to our UI, front-end will implement proper blocking.
The problem is that someone can still try to invoke creation/update of a view directly through our REST API.
This person can manipulate Search JSON so that it contains a Search Filter current user has no permissions for.
In this scenario creation/update should fail.
=> Block create/update of view if forbidden search filters are used

graylog2-web-interface/src/views/components/searchbar/completions/FieldValueCompletion.test.ts, graylog2-web-interface/src/views/components/searchbar/completions/FieldValueCompletion.ts, graylog2-web-interface/src/views/components/searchbar/queryinput/ace-types.ts
This PR is fixing an issue with the field value completions not working when the user is starting a field value with quoting, e.g. when the user types `field:""`, no completions appear.
This PR is fixing this and also retains quoting information, so when the user uses quoting, the value returned is not escaped, if the user is not using quoting, escaping is used.
=> Fix field value suggestions when quoting is used.

graylog2-web-interface/src/views/components/searchbar/SearchBarAutocompletions.ts, graylog2-web-interface/src/views/components/searchbar/completions/FieldValueCompletion.test.ts, graylog2-web-interface/src/views/components/searchbar/completions/FieldValueCompletion.ts, graylog2-web-interface/src/views/components/searchbar/queryinput/ace.ts, graylog2-web-interface/src/views/components/searchbar/queryinput/custom-lucene-mode.js
**Note:** This requires #13087 to merged before.
Prior to this PR, getting suggestions for a field value containing a slash did not work. This is related due to the tokenization logic of the lucene mode in the ace editor, which is treating it as a token separator, as it could potentially be part of a regex.
This PR is now doing the following to fix this:
- copy the existing lucene mode to allow customization
- including `\` and `/` in `term` tokens
- extend identifier regex which is used in ace to determine the boundary of the current input which is replaced by the selected completion with `\` and `/`
- escape completion captions if in unquoted context so matching completions are not filtered out
The drawback of this approach is that we now have to maintain the lucene mode ourselves, but …
=> Handle slashes in unquoted/escaped field values for completions.

graylog2-web-interface/src/logic/permissions/GRN.ts, graylog2-web-interface/src/routing/getShowRouteForEntity.test.ts, graylog2-web-interface/src/routing/getShowRouteForEntity.ts
With this PR we are simple extracting existing logic into a helper function.
The function provides the "show entity" based on the entity type and id. With this PR the logic can be reused outside of the GRN context.
=> Create helper function to get a "show entity" route based on an entity type and id.

graylog2-server/src/main/java/org/graylog2/migrations/V20220623125450_AddJobTypeToJobTrigger.java, graylog2-server/src/test/resources/org/graylog2/migrations/V20220623125450_AddJobTypeToJobTriggerTest.json
Mongo 3.6 does neither support $toString, nor $toObjectId
Thus we cannot use an aggregation to lookup the jobdefinition type.
We need to convert ObjectIds to Strings or vice versa to do the looukup.
Instead we are just fetching a map of all jobdefinition types.
Performance should still be okay, because we only expect lots of
JobTriggers, not JobDefinitions.
=> Fix AddJobTypeToJobTrigger migration with Mongo 3.6

graylog2-server/src/main/java/org/graylog2/Configuration.java, graylog2-server/src/main/java/org/graylog2/bootstrap/ServerBootstrap.java, misc/graylog.conf
Introduces a new configuration flag `ignore_migration_failures`. This provides an alternative to skipping all migrations via `run_migrations = false` when specific migrations are blocked.
Resolves Graylog2/graylog2-server#13053
=> add flag ignore_migration_failures

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/SetField.java
Extends parameter list of `set_field` by an optional default parameter. The default can be specified as a positional parameter (5th parameter value) or named as `default`. 
The default is assigned if 
- the primary value is null
- evaluation of the primary value throws an exception. In this case (provided the default is valid), the exception is suppressed. This is desired so we can specify a default when an array value is not present, resulting in _index out of bounds_ exception.
The default parameter value is assigned whenever the value parameter is null; or when an exception is encountered in evaluating the value parameter. 
See linked issue for details
Resolves #5911
=> Add default param to set_field function

graylog2-server/src/main/java/org/graylog/plugins/map/geoip/GeoIpDbFileChangeMonitorService.java
Updated GeoIpDbFileChangeMonitorService to cancel running refresh task and NOT reschedule if processor is disabled.
Disabling refresh scheduling when the processor is disabled keeps refresh attempts, in particular when the configuration does not yet have database files.
End-to-end testing.
=> Updated GeoIpDbFileChangeMonitorService Refresh scheduling

graylog2-server/src/main/java/org/graylog/events/rest/EventNotificationsResource.java, graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationFormContainer.jsx
Adds validation of email configuration in graylog.conf to EventNotificationResource.
Checks that email transport is enabled and that there is a sender set either in graylog.conf or the notification itself.
closes #13085
If sender isn't set in configuration and notification, a NPE is produced when trying to send the notification.
=> Added additional validation of email configuration

graylog2-server/src/test/resources/org/graylog/testing/graylognode/Dockerfile
The `openjdk` images are being retired/discontinued.  Since Eclipse Temurin (AdoptOpenJDK) was previously selected for other Graylog uses, it seems like a good pick for Graylog images.
Ubuntu Jammy, selected as the OS variant here (and by the Temurin project for non-specific tags), will have standard support until April 2027.
This also includes a fix for non-root SO loading that was being done in the 'openjdk' images, but isn't (currently) with Temurin.  Without it the following error will occur:
```
java: error while loading shared libraries: libjli.so: cannot open shared object file: No such file or directory
```
This is related to Graylog2/graylog-docker#213.
Closes #13114.
Refs:
* https://github.com/docker-library/openjdk/issues/505
* …
=> Switch from 'openjdk' to 'eclipse-temurin' for Graylog Server test image

graylog2-web-interface/src/views/components/actions/Action.test.tsx, graylog2-web-interface/src/views/components/actions/ActionDropdown.tsx, graylog2-web-interface/src/views/types.ts
The external actions plugin now returns a hook to give it more functionality.
- Update types to include the new typing for the external actions hook
plugin.
- Update ActionDropdown component to utilize the new plugin correctly
and fail gracefully if the plugin isn't present.
- Update tests to work with the new hook and test the component works
fine if the plugin is not present.
There was a requirement for more robust functionality when using the external actions plugin.
- Unit tests have been written, and it has been tested locally.
=> Updates the external actions plugin use to be hook based

graylog2-web-interface/src/components/bootstrap/Nav.jsx
This PR add styles for .nav-sm, .nav-xs and .nav-lg classes of Nav component. Now we can add props bsSize: sm | xs | lg | small | large to Nav component and we will have different sizes for navigation items
According to react-bootstrap documentation https://react-bootstrap-v3.netlify.app/components/navs/  we can add bsStyle one of: "lg", "large", "sm", "small" to change the size of the Navs. That doesn't work and also looks like a mistake in documentation because as bsStyle we use `pills`or  `tabs` to change the style for them.  
Adding bsSize props to `Nav` (like we usually do for other components) component adds an appropriate class to the component. But there are no written styles for these classes.
=> Add styles for different sizes of nav component

graylog2-server/src/main/java/org/graylog/events/processor/EventDefinitionHandler.java, graylog2-server/src/main/java/org/graylog/scheduler/DBJobTriggerService.java, graylog2-server/src/test/java/org/graylog/events/processor/EventDefinitionHandlerTest.java, graylog2-server/src/test/java/org/graylog/scheduler/DBJobTriggerServiceTest.java
So far our DBJobTriggerService allowed to get only one trigger for one job definition ID. This PR adds a call to obtain all triggers for the job ID.
Adding new method called `getAllForJob`, returning a list of available triggers. Additionally renaming `getForJob` to `getOneForJob`, returning an `Optional`, either empty or with a value. This method still throws an `IllegalStateException` if there are more triggers, in the same way the original call did.
The reporting migration to our generic scheduler needs more triggers for one job. One report is represented by one job, each delivery configuration is represented by its own trigger.
Added unit tests, adapted existing
=> Allow obtaining all triggers for one job definition ID

graylog2-web-interface/src/views/components/searchbar/completions/FieldValueCompletion.test.ts, graylog2-web-interface/src/views/components/searchbar/completions/FieldValueCompletion.ts, graylog2-web-interface/src/views/components/searchbar/queryinput/ace-types.ts
**Note:** This is a backport of #13087 to `4.3`.
This PR is fixing an issue with the field value completions not working when the user is starting a field value with quoting, e.g. when the user types `field:""`, no completions appear.
This PR is fixing this and also retains quoting information, so when the user uses quoting, the value returned is not escaped, if the user is not using quoting, escaping is used.
=> Fix field value suggestions when quoting is used. (`4.3`)

UPGRADING.md, graylog2-server/src/main/java/org/graylog2/configuration/HttpConfiguration.java, graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java, graylog2-server/src/main/java/org/graylog2/shared/rest/EmbeddingControlFilter.java, graylog2-server/src/test/java/org/graylog2/shared/rest/EmbeddingControlFilterTest.java
This PR is adding a configuration option `http_allow_embedding`, which is configuring if embedding the web frontend (or any other API request) is allowed or not. It defaults to `false`, disallowing embedding to prevent clickjacking. It can be set to `true`, which would allow embedding "as long as the site including it in a frame is the same as the one serving the page."[*]
This is a short-term solution to prevent clickjacking. It should be replaced at some point with a complete content security policy, particularly because the `X-Frame-Options` header is deprecated by the corresponding CSP directive.
Fixes Graylog2/graylog-plugin-enterprise#3884
[*]: <https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options#directives> "MDN Docs for `X-Frame-Options`"
=> Set `X-Frame-Options` header, disallow embedding by default.

graylog2-web-interface/src/components/lookup-tables/LUTTableEntry.jsx, graylog2-web-interface/src/components/lookup-tables/LookupTable.jsx
Now we are encoding the lookup table name before using it as route parameter and that is fixing the problem of using special characters like "#" or "/".
fix https://github.com/Graylog2/graylog2-server/issues/12916
=> Fix/#12916 Lookup table name is now encoded before being used as route param

UPGRADING.md, graylog2-server/src/main/java/org/graylog2/configuration/HttpConfiguration.java, graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java, graylog2-server/src/main/java/org/graylog2/shared/rest/EmbeddingControlFilter.java, graylog2-server/src/test/java/org/graylog2/shared/rest/EmbeddingControlFilterTest.java
**Note:** This is a backport of #13160 to `4.3`.
This PR is adding a configuration option `http_allow_embedding`, which is configuring if embedding the web frontend (or any other API request) is allowed or not. It defaults to `false`, disallowing embedding to prevent clickjacking. It can be set to `true`, which would allow embedding "as long as the site including it in a frame is the same as the one serving the page."[*]
This is a short-term solution to prevent clickjacking. It should be replaced at some point with a complete content security policy, particularly because the `X-Frame-Options` header is deprecated by the corresponding CSP directive.
Fixes Graylog2/graylog-plugin-enterprise#3884
[*]: <https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options#directives> "MDN …
=> Set `X-Frame-Options` header, disallow embedding by default. (`4.3`)

graylog2-server/src/main/antlr4/org/graylog/plugins/pipelineprocessor/parser/RuleLang.g4, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/ast/expressions/MessageRefExpression.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/debug/Debug.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/parser/PipelineRuleParser.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/debug.txt, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/fieldRenaming.txt
This extends the pipeline rule syntax to allow
passing the entire `$message` object as parameters.
A useful example of this would be
`debug($message);`
Other rule examples that are now possible:
`has_field("source", $message);`
`let foo = $message;`
=> Support $message expression in pipeline rules

graylog2-web-interface/src/components/common/HoverForHelp.tsx
Make `title` prop of `HoverForHelp` component optional. The title is not required to display the popover, the component is based on.
It can be helpful to display the help text without a title, when the explanation is comparable short.
=> Make `title` prop of `HoverForHelp` component optional.

UPGRADING.md, graylog2-server/src/main/java/org/graylog/events/EventsModule.java, graylog2-server/src/main/java/org/graylog2/plugin/PluginModule.java
Backport https://github.com/Graylog2/graylog2-server/pull/13171 to the `4.3` branch.
=> Backport: Properly register notification config entity subtypes

graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchJob.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/EngineBindings.java, graylog2-server/src/main/java/org/graylog2/lookup/LookupModule.java
Prior to this PR, setting up the injector could fail if running without plugins, due to:
- No post-validation search normalizer being bound
- No lookup table service factory annotated with `@SystemEntity` being bound
Guice works in different ways when the type of a multi-binder is supposed to be injected and no implementations are present:
- When the map/set-binder has never been instantiated, guice throws an injection error
- When the map/set-binder has been instantiated, but no implementation was bound, no error is raised and an empty collection is injected
So in order to fix the startup failure, this PR is calling just the binder of those two entities once, so instead of throwing an error, empty collections are injected.
=> Explicitly trigger binders once to avoid injection errors.

graylog2-web-interface/packages/jest-preset-graylog/src/setup-files/console-warnings-fail-tests.js
This PR fixes an error that can happen in tests, when a `console.error/warn` call is performed. This should cause a test failure, but we are ignoring some of the logged errors. In the code checking if the error should be ignored, we are unconditionally calling `includes` on the passed arguments. In some scenarios this can cause calling `undefined` as a function, when the argument is not an array.
This change is now using optional chaining to prevent this and fixes proper error logging in affected tests.
=> Avoid calling `undefined` when checking if error is ignored.

graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionsContainer.jsx
Event Definition find button is now working fine, before it was broken because fetchData static method was accessed with this. instead of className.
https://github.com/Graylog2/graylog2-server/issues/12971
=> Fix #12971 Event Definition broken find button

graylog2-web-interface/src/views/components/views/ViewPropertiesModal.test.tsx, graylog2-web-interface/src/views/components/views/ViewPropertiesModal.tsx
Prior to this PR, the `_onSave` function in the `ViewPropertiesModal` component used the view instance that was originally passed to the component when saving it instead of the updated one. This lead to updates to properties (title/description/etc.) not being propagated and new views failing backend validation due to not having a title, even if one was entered.
This PR is changing `_onSave` to use the `updatedView` instance.
Fixes #13223.
=> Using updated view when calling `onSave` in view properties modal.

graylog2-web-interface/src/components/rules/RuleContext.tsx, graylog2-web-interface/src/components/rules/RuleForm.jsx
As described in this issue https://github.com/Graylog2/graylog2-server/issues/11812 the description was not being saved when creating a pipeline rule but the real reason was testing with the same existing title. So in this PR the error is displayed in a readable way that the user will know why he couldn't create a new pipeline rule.
https://github.com/Graylog2/graylog2-server/issues/11812
=> Display error message when the pipeline rule title already exists

graylog2-server/src/main/java/org/graylog/api/GenerateApiDefinition.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/FailuresResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexSetsResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexTemplatesResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexerClusterResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexerOverviewResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndicesResource.java, graylog2-server/src/main/java/org/graylog2/shared/rest/documentation/generator/Generator.java, graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationBrowserResource.java, graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationResource.java, graylog2-server/src/main/resources/swagger/index.html.template, graylog2-server/src/test/java/org/graylog2/rest/documentation/generator/GeneratorTest.java, graylog2-web-interface/src/components/navigation/HelpMenu.jsx, graylog2-web-interface/src/routing/Routes.ts
Resolves Graylog2/graylog-plugin-cloud#1035
Enable API-Browser in Cloud context, while providing the ability to hide APIs that are not relevant or should not be exposed in Cloud. Visible APIs must be explicitly marked for Cloud by setting a specific `tags` value, e.g.:
`@Api(value = "MyCloudAPI", description = "Does something useful in Cloud", tags = {CLOUD_VISIBLE})`
By default, APIs are hidden in Cloud.
Currently the API Browser is accessible from the help menu.
=> Use @Api tags to control visibility API docs in cloud

graylog2-server/src/main/java/org/graylog/scheduler/schedule/CronJobSchedule.java, graylog2-server/src/test/java/org/graylog/scheduler/schedule/CronJobScheduleTest.java
Better `timezone` handling to prevent possible NPE in CronJobSchedule.
=> fixed possible NPE in CronJobSchedule

graylog2-web-interface/src/components/common/DataTable/DataTable.jsx, graylog2-web-interface/src/components/content-packs/ContentPackInstallations.jsx, graylog2-web-interface/src/components/content-packs/ContentPackVersions.jsx
As described in the issue https://github.com/Graylog2/graylog2-server/issues/13198 the content pack version list was sorted lexicographically now it is sorted numerically
https://github.com/Graylog2/graylog2-server/issues/13198
=> Fix 13198 Sort Content Pack version list numerically

graylog2-web-interface/packages/eslint-config-graylog/index.js, graylog2-web-interface/packages/eslint-config-graylog/package.json, graylog2-web-interface/packages/eslint-plugin-graylog/lib/index.js, graylog2-web-interface/packages/eslint-plugin-graylog/lib/rules/prefer-hook.js, graylog2-web-interface/packages/eslint-plugin-graylog/lib/rules/user-date-time-injection.js, graylog2-web-interface/packages/eslint-plugin-graylog/package.json, graylog2-web-interface/yarn.lock
With this PR we are adding a new package, which allows us to create custom ESLint rules.
It contains a first rule that suggests implementing the `useUserDateTime` context instead of consuming the `CurrentUserContext`.
Implementing a specific hook instead of consuming the context is a pattern we want to apply more in the future.
Since it is very easy to forget this pattern and consume the context directly, it is great to have an ESLint rule to avoid these mistakes.
I also considered implementing an auto fix suggestion, but the problem is, that running `eslint --fix` would then result in a problem, since we are not automatically adding the necessary import.
Please note I have not yet added tests for the new rule. 
To test this change you need to remove and reinstall the `node_modules`.
=> Create new package for custom ESLint rules.

graylog2-web-interface/src/components/common/ConfirmDialog.tsx, graylog2-web-interface/src/components/common/index.tsx
Backport for 4.3 with the fix in https://github.com/Graylog2/graylog2-server/pull/12480
=> Backport for 4.3: fix ConfirmDialog close behaviour via X button (or pressing ESC or clicking on the background)

graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/testing/ElasticsearchInstanceES6.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ElasticsearchInstanceES7.java
Reintroduce `create(SearchVersion searchVersion, Network network)` methods in ES instances, that are needed by our container matrix tests integration.
=> Reintroduce required create methods for ES instances

graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessor.java, graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationKeyResult.java, graylog2-server/src/main/java/org/graylog/events/processor/aggregation/PivotAggregationSearch.java, graylog2-server/src/test/java/org/graylog/events/processor/aggregation/AggregationEventProcessorTest.java, graylog2-server/src/test/java/org/graylog/events/processor/aggregation/PivotAggregationSearchTest.java
Resolves #13061 
During catch-up processing, aggregation events were being generated with the time range of the extended catch-up window, instead of the time range of the actual result bucket. 
We now add a `from` field to each `AggregationKeyResult` and use that to determine the event time range.
=> Return correct time range when creating aggregation events during catch-up processing

graylog2-web-interface/src/components/bootstrap/MenuItem.tsx, graylog2-web-interface/src/components/bootstrap/imports.js, graylog2-web-interface/src/components/bootstrap/index.js, graylog2-web-interface/src/components/bootstrap/styles/menuItem.js, graylog2-web-interface/src/components/common/TimeUnitInput.test.jsx, graylog2-web-interface/src/components/content-packs/ContentPackVersions.test.jsx, graylog2-web-interface/src/components/content-packs/ContentPacksList.test.jsx, graylog2-web-interface/src/views/components/DashboardActionsMenu.tsx, graylog2-web-interface/src/views/components/common/ActionDropdown.test.tsx, graylog2-web-interface/src/views/components/dashboard/BigDisplayModeConfiguration.tsx, graylog2-web-interface/src/views/components/dashboard/__snapshots__/BigDisplayModeConfiguration.test.tsx.snap, graylog2-web-interface/src/views/components/searchbar/saved-search/SearchActionsMenu.tsx, graylog2-web-interface/src/views/components/widgets/WidgetActionDropdown.test.tsx
There are a few cases where we display an icon for a dropdown menu item.
Saved search action dropdown (before)
Dashboard action dropdown (before)
With this PR we make it simpler to define an icon for the `MenuItem` component and we improve the positioning of icons and text.
Search action dropdown (after)
Dashboard action dropdown (after)
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/3966
=> Unify styling for dropdown menu items with icons.

graylog2-web-interface/src/views/components/messagelist/MessageTableEntry.tsx
_Please note this PR should be backported_
As described in https://github.com/Graylog2/graylog2-server/issues/13259 we currently toggle the message row details when selecting text in the message table. 
Example (before)
With this PR we are improving the behaviour, only a simple click will toggle the message row details.
Example (after)
One thing which may is not optimal, if you select a text and you click on the selected text it requires a second click to actually toggle the message details.
Fixes https://github.com/Graylog2/graylog2-server/issues/13259
=> Do not toggle message details in message table widget, when selecting text.

graylog2-web-interface/src/views/components/messagelist/MessageTableEntry.tsx
As described in https://github.com/Graylog2/graylog2-server/issues/13259 we currently toggle the message row details when selecting text in the message table. 
Example (before)
With this PR we are improving the behaviour, only a simple click will toggle the message row details.
Example (after)
One thing which may is not optimal, if you select a text and you click on the selected text it requires a second click to actually toggle the message details.
Related to https://github.com/Graylog2/graylog2-server/issues/13259
=> Do not toggle message details in message table widget, when selecting text. (backport of #13263 for 4.3)

graylog2-web-interface/src/views/components/messagelist/MessageTableEntry.tsx
As described in https://github.com/Graylog2/graylog2-server/issues/13259 we currently toggle the message row details when selecting text in the message table. 
Example (before)
With this PR we are improving the behaviour, only a simple click will toggle the message row details.
Example (after)
One thing which may is not optimal, if you select a text and you click on the selected text it requires a second click to actually toggle the message details.
Related to https://github.com/Graylog2/graylog2-server/issues/13259
=> Do not toggle message details in message table widget, when selecting text. (backport of #13263 for 4.2)

graylog2-server/src/test/java/org/graylog/testing/containermatrix/ContainerMatrixTestEngine.java
The "#discover()" method was running reflection on every call to find all
classes that are annotated with the "ContainerMatrixTestsConfiguration"
annotation. Since the "#discover()" method is called quite often during
test setup, we saw a long "pause" before the test execution started when
running "mvn test".
We now run the reflection in a "static" block and re-use the result for
each "#discover()" invocation.
The change improves running "mvn -Dskip.web.build clean test" in the
graylog2-server repository as follows:
Before: 05:10 min
After:  02:23 min
=> Improve performance of ContainerMatrixTestEngine

graylog2-web-interface/src/components/sidecars/administration/CollectorConfigurationSelector.jsx
As described in this issue https://github.com/Graylog2/graylog2-server/issues/13238 searching by configuration name in /system/sidecars/administration is not working when items are selected. this is because the search/filter logic works with IDs but in this case there is no reason to not work with names since they are unique.
https://github.com/Graylog2/graylog2-server/issues/13238
=> Fix 13238 filter by the unique configurationNames instead of configurationIds

graylog2-server/src/main/java/org/graylog2/buffers/processors/OutputBufferProcessor.java, graylog2-server/src/main/java/org/graylog2/messageprocessors/MessageFilterChainProcessor.java
Reduce the logging level for several per-message log entries to `trace`.
While investigating a customer issue and reviewing their server debug-level logs, I saw a large number of these log statements. I believe the usual pattern is to set per-log message logging statements to `trace`, so that it is possible to retrieve common debug level logs without being overwhelmed by too many log entries if the Graylog server is processing a large number of messages.
```
DEBUG [MessageFilterChainProcessor] Applying filter [Extractor] on message <message-id>
DEBUG [OutputBufferProcessor] Processing message <message-id> from OutputBuffer
```
No testing needed, just a log-level change.
=> Reduce logging level for per-message log statements

graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/MessageListEntity.java
Fix deserialization of TimeRange instances
```
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "type" (class org.graylog2.plugin.indexer.searches.timeranges.AutoValue_RelativeRange$Builder), not marked as ignorable (3 known properties: "from", "to", "range"])
at [Source: de.undercouch.bson4jackson.io.LittleEndianInputStream@3f73538b; pos: 485] (through reference chain: org.graylog.plugins.views.search.AutoValue_Search$Builder["queries"]->org.graylog.plugins.views.search.AutoValue_Query$Builder["search_types"]->java.util.HashSet[0]->org.graylog.plugins.enterprise.search.searchtypes.AutoValue_LogsList$Builder["timerange"]->org.graylog2.plugin.indexer.searches.timeranges.AutoValue_RelativeRange$Builder["type"])
```
Recently we have changed the …
=> Fixed timerange deserialization

graylog2-web-interface/src/components/common/Markdown.test.tsx, graylog2-web-interface/src/components/common/Markdown.tsx, graylog2-web-interface/src/components/common/index.tsx, graylog2-web-interface/src/components/content-packs/ContentPackDetails.jsx
This change is introducing a shared `Markdown` component, which solely renders markdown passed in the `text` prop to HTML and returns it. The reason for this is that we use this pattern repeatedly in an identical way, using `dompurify` as an XSS filter, which can be easily forgotten.  Also, we have to include `marked` & `dompurify` in each plugin that wants to do this.
=> Introduce shared `Markdown` component.

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/ESGeneratedQueryContext.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackend.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/ESEventList.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/ESMessageList.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/ESPivot.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendErrorHandlingTest.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendGeneratedRequestTestBase.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendMultiSearchTest.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendSearchTypeOverridesTest.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendSearchTypesWithStreamsOverridesTest.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendTest.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendUsingCorrectIndicesTest.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/searchtypes/ESMessageListTest.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivots/ESPivotTest.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/QueryBackend.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/QueryEngine.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/SearchTypeHandler.java
Removing unnecessary usage of SearchJob throughout the API.
When developing upgrades for query-aware field list, I'd like to execute single Query, without referencing Search.
This need made me realize that in many places in our code SearchJob is passed without any need, so I have cleaned it a little bit.
It turned out that we might have passed SearchJob around just because of its usage in ElasticsearchBackend#generateFilterClause() and this method ... was just pretending it needs this parameter, only passing it to recursive invocations, without any actual work on this param.
Even if it does not turn useful for my current task, this simplification probably deserves to be merged on its own.
By re-runing the tests.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#4030
=> Removing unnecessary usage of SearchJob throughout the API

graylog2-server/src/main/java/org/graylog2/indexer/MongoIndexSet.java
Calculate write index alias once, during MongoIndexSet creation.
It seems that > 5% of bulk request creation time has been spend on concatenating the same strings over and over again.
The screenshot shows that the whole section disappears from the execution after this change.
=> Calculate write index alias once, during MongoIndexSet creation.

graylog2-web-interface/src/views/components/DecoratorValue.tsx
Backport https://github.com/Graylog2/graylog2-server/pull/13351 to the `4.3` branch.
=> Open hyperlink decorator links in a new window (4.3 backport)

graylog2-server/src/main/java/org/graylog2/inputs/misc/jsonpath/JsonPathInput.java
Backport https://github.com/Graylog2/graylog2-server/pull/13439 to the `4.3` branch.
=> Adjust name of JSON path input (4.3 backport)

graylog2-web-interface/packages/eslint-config-graylog/index.js
Sometime we want to exclude, for example an attribute from the component props, before passing them to a child component.
`const Component = ({ exampleProp, ...props }) =>`
Currently this results an ESLint warning, because `exampleProp` is not being used.
With this PR it will be possible to avoid this warning by changing the variable name:
`const Component = ({ exampleProp: _exampleProp, ...props }) =>`
=> Add exception for ESLint rule `no-unused-vars`.

graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/DiskJournalPreflightCheck.java
Include the already used size of the journal directory into the size calcalation.
Fixes #13454
=> Fix DiskJournalPreflightCheck

graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/DiskJournalPreflightCheck.java
Include the already used size of the journal directory into the size calcalation.
Fixes #13454
(cherry picked from commit e323126580607873dd3541516721ddd108f13443)
=> Fix DiskJournalPreflightCheck (4.3 backport)

graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java
The `setupCoreConfigInjector()` method reqires the feature flags to be set up already.
=> Fix server --dump-default-config command

graylog2-web-interface/src/contexts/DefaultQueryClientProvider.tsx, graylog2-web-interface/src/views/components/Search.dashboard.test.tsx, graylog2-web-interface/src/views/components/searchbar/queryinput/QueryInput.test.tsx, graylog2-web-interface/src/views/components/widgets/Widget.aggregations.test.tsx, graylog2-web-interface/test/WrappingContainer.tsx
With this PR we are fixing a few flaky tests. They all have in common, that `react-query` was dealing with an unrelated error while the tests were running.
By default `react-query` is retrying a request three times before it errors. Because of this behaviour the tests were only failing when the retries finished before the test succeeded.   When a test succeeded before all retries finished, the retries got "canceled".
By disabling the retires for tests, they fail reliable. For example with the following error:
`response.map is not a function` 
This error occurs because we mock our `FetchProvider` in tests with the following default return value `{}`. This is problematic, when the expected return value is for example an array.
 
 /jenkins-pr-deps …
=> Disable `react-query` retries for tests.

graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/requests/BulkActionRequest.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/AdministrationResource.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/SidecarResource.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/ActionService.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/EtagService.java
The registration cache was using the sidecar "_id", while the ActionService was invalidating the sidecar "node_id".
Change the entire cache to using the "node_id"
=> Fix cache invalidation for collector actions

graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java
Backport of #13507 to fix `--dump-default-config` option for server command.
=> Fix server --dump-default-config command (#13507)

graylog2-web-interface/src/components/common/CustomFontAwesomeIcon.tsx, graylog2-web-interface/src/components/sidecars/common/OperatingSystemIcon.tsx
The Log Collectors management section of the sidecar management UI comes with a FreeBSD-config, but is lacking the corresponding icon. This PR is fixing that.
Before:
After:
=> Adding FreeBSD icon for sidecars.

full-backend-tests/src/test/java/org/graylog/plugins/views/ViewsResourceIT.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewsResourceTest.java
The views resource checks for missing elements but the parameters of Sets.difference was used wrong way around.
Note: backported from #13500 to 4.3 to help solving a customer issue.
=> fixing the directions, `Set.difference` is used (backport to 4.3 of #13500)

graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java, misc/graylog.conf
This PR sets the `elasticsearch_index_optimization_jobs` configuration value to 10 (originally 20), to avoid depleting all the elasticsearch/opensearch connections (`elasticsearch_max_total_connections_per_route`) available.
Fixes https://github.com/Graylog2/graylog2-server/issues/12025
With default 20 threads of `elasticsearch_index_optimization_jobs` and default 20 threads for search-server clients, it could easily happen that all client threads are blocked by the optimization and the graylog server stops indexing new messages, as observed in https://github.com/Graylog2/graylog2-server/issues/12025
When we decrease the default optimize threads to 10, there will be still 10 client threads available for ingestion and other tasks.
Tested by the cloud team, see …
=> Set elasticsearch_index_optimization_jobs default to 10

graylog2-web-interface/src/components/common/SourceCodeEditor.jsx
Adding the onBlur prop that is supported by the react-ace editor to be used in the new sigma rules editor. Related PR here: https://github.com/Graylog2/graylog-plugin-enterprise/pull/4094
=> Adding onBlur prop

graylog2-web-interface/src/views/components/TimeRangeValidation.ts, graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.relativeTimeRange.test.tsx, graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx
In the last weeks, the test for the `TimeRangeDropdown` component was running into timeouts repeatedly. In order to address this, the component itself was improved by usages of `useMemo`/`useCallback` in order to prevent unnecessary rerenders. On my local machine the test runtime was reduced from 1.2s to 600ms. In addition, a couple of typing issues were addressed.
=> Improving rendering of `TimeRangeDropdown` component.

graylog2-web-interface/src/views/components/widgets/MessageTable.tsx
When opening the message details of a message in the message table widget, they can scroll over the message table header:
This can be fixed easily by changing the header `z-index`.
=> Ensure message details do not scroll over message table header.

graylog2-web-interface/src/components/navigation/Navigation.tsx
This is a simple UI improvement when our mobile navigation menu is clicked it should auto-collapse.
- `Navbar` component was missing the collapseOnSelect Prop
- The `Nav` components had the `navbar` prop which is added by default when using `Nav` inside `Navbar`
Quality of life improvement.
This was tested locally.
=> Fix mobile menu collapse behavior

graylog2-server/src/main/java/org/graylog2/security/AESTools.java, graylog2-server/src/test/java/org/graylog2/security/AESToolsTest.java
Using the Bouncy Castle provider fixes problems in FIPS-enabled JVM environments where the "SunJCE" provider is not present, and the other available providers don't implement the "ISO10126Padding" transformation for "AES/CBC".
Fixes #13525
(cherry picked from commit 3703435c948f197e95d60ab94eddb828a16eb2bc)
=> Use BouncyCastle provider in AESTools (#13580)

graylog2-web-interface/src/theme/GlobalThemeStyles.js, graylog2-web-interface/src/theme/utils/opacify.ts
Issue #13101 Fix auto-complete/suggestions to be consistent in dark mode.
- Updated `GlobalThemeStyles.js` to override default styles and use our theme object
- Updated opacify util to function properly
- Removed unused type from Opacify (looked incorrect as it was)
Inconsistent UI in dark mode for our ACE editor auto-complete/suggestions
Tested locally
=> Fix auto completions for dark mode

graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorConfigurationFacade.java
Uses the database ID of the collector when recreating SidecarCollectorConfigurations from a Content Pack instead of the logical ID. 
Closes #12778
Followed steps to recreate the bug and was able to successfully install the referenced content pack after these changes. Installing this [content pack](https://github.com/Graylog2/graylog2-server/files/9736305/recreate-12778-content-pack.json.txt) should make the Sidecar config page inaccessible in the latest master code. After uninstalling the content pack, pulling these changes, and reinstalling the content pack, it should be back viewable.
=> Use collector DB ID instead of entity ID when creating Sidecar Configs

graylog2-server/src/main/java/org/graylog2/cluster/lock/LockServiceModule.java
LockServiceModule is required for backporting the fix for `cloud set-license` #1059.
=> Backport LockService dependency for issue #1059

graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/SidecarCollectorEntity.java
Sidecar Collector: Fix empty content pack export when optional fields are blank (Backport of #13645)
* Fixes empty content pack issue for collectors
* Add null checks when decoding entity
Also remove null support for the template. The frontend always leaves this field non-null.
=> Sidecar Collector: Fix empty content pack export when optional fields are blank (Backport of #13645)

graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetConfig.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/responses/IndexSetSummary.java, graylog2-server/src/main/java/org/graylog2/validation/SizeInBytes.java, graylog2-server/src/main/java/org/graylog2/validation/SizeInBytesValidator.java, graylog2-server/src/test/java/org/graylog2/validation/SizeInBytesValidatorTest.java
Both ES and OS require index name to have length (int bytes!) shorter than 255.
Validation has been added for index name prefix, so that it is shorter than 250 in bytes (5 bytes reserved for appended numbers).
Requires fixing #13657 to fully see the benefits of the change.
1. Index name prefix has not been validated so far.
2. Providing too long index prefix name will cause a lot of exceptions.
3. This change may limit a probability of seeing this bug once again - #10187
=> Validation of index prefix name length

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/series/ESLatestHandler.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/pivot/series/OSLatestHandler.java
This PR is fixing the `latest` aggregation for cases where no document with the field is present in the time range.
Code-wise, it checks if the list of hits returned has at least one element before trying to extract it.
Fixes #13593.
=> Fixing latest aggregation if field is not present in time range.

graylog2-web-interface/src/components/sidecars/sidecars/SidecarRow.jsx, graylog2-web-interface/src/routing/Routes.ts
Refactors the `Routes.search_with_query` function to correctly use `RoutesTimeRange` parameter as well as add support for streams. 
/jenkins-pr-deps Graylog2/graylog-plugin-collector#210
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#4170
Though the function parameters required a `RoutesTimeRange` object, the code itself was not using the object and just expecting a number to be passed in. The function also lacked support for streams, which are another valid search query param. 
local dev env using the new function
=> Use typed routes and add streams option to search query route

graylog2-web-interface/src/views/components/aggregationwizard/FieldSelect.tsx, graylog2-web-interface/src/views/components/aggregationwizard/metric/MetricConfiguration.tsx, graylog2-web-interface/src/views/components/sidebar/fields/FieldTypeIcon.tsx
Most of the metric functions of an aggregation require the target field to be numeric. If a non-numeric field is selected, the search is executed but returns an error. 
To aid the user in selecting a qualifying field, this PR is now
- graying out fields which are non-numeric if a numeric field is requested, but still allows the user to select them
- shows an icon next to the field name to indicate the field's type
=> Show in field select if fields are qualified for metric function.

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/series/ESLatestHandler.java
_Please note, this is a backport of #13640 for 4.3._
This PR is fixing the `latest` aggregation for cases where no document with the field is present in the time range.
Code-wise, it checks if the list of hits returned has at least one element before trying to extract it.
Fixes #13593.
=> Fixing latest aggregation if field is not present in time range. (backport of #13640 for 4.3)

graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.tsx
As requested in the issue https://github.com/Graylog2/graylog2-server/issues/13305, here are the options for pagination in Event Definitions adjusted to 10, 50 and 100.
Fix https://github.com/Graylog2/graylog2-server/issues/13305
=> Adjust page size for pagination on event definitions

pom.xml
which is the latest 2.x version.
This is needed for Java 17 support:
https://github.com/eclipse-ee4j/jersey/pull/4754
Without this change, starting the jersey service in the forwarder terminates with
`jersey.repackaged.org.objectweb.asm.ClassReader: Unsupported class file major version 61`
=> Update to jersey 2.37

full-backend-tests/pom.xml, graylog2-server/pom.xml, graylog2-server/src/main/java/org/graylog/plugins/beats/Beats2Codec.java, graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/ObjectMapperProvider.java, graylog2-server/src/test/java/org/graylog/events/contentpack/facade/EventDefinitionFacadeTest.java, graylog2-server/src/test/java/org/graylog/events/contentpack/facade/NotificationFacadeTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20200204122000_MigrateUntypedViewsToDashboardsTest.java, graylog2-server/src/test/java/org/graylog2/database/PaginatedDbServiceTest.java, graylog2-server/src/test/java/org/graylog2/jackson/MongoJodaDateTimeSerializerTest.java, graylog2-server/src/test/java/org/graylog2/jackson/MongoZonedDateTimeSerializerTest.java, graylog2-server/src/test/java/org/graylog2/plugin/MessageSummaryTest.java, graylog2-server/src/test/java/org/graylog2/security/encryption/EncryptedValueTest.java, pom.xml
Upgrade to the current Jackson version 2.13.4, while keeping everything else unchanged (as much as possible).
https://github.com/Graylog2/graylog-plugin-enterprise/issues/3674
**Details**
- If configuration of `ObjectMapper` is modified after first usage, changes may or may not take effect, and configuration calls themselves may fail [[link](https://fasterxml.github.io/jackson-databind/javadoc/2.13/com/fasterxml/jackson/databind/ObjectMapper.html)]. This behavior appears to have changed since version 2.9. It only affects a few tests which attempt to modify the mapper:
_graylog2-server/src/test/java/org/graylog/events/contentpack/facade/EventDefinitionFacadeTest.java
graylog2-server/src/test/java/org/graylog/events/contentpack/facade/NotificationFacadeTest.java_
- `DateTimeFormatter` now …
=> Update to jackson 2.13

graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodical.java, graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodicalTest.java
Prior to this change, when polling the field types of an index set took longer than 1 second, a second polling job was submitted to the executor, running in parallel. If it took longer than 2s, a third one is started, and so on.
In order to prevent this, a very simple locking mechanism is implemented, where a running polling job adds the current index set's id to a concurrent hash set, removing it when finished (or failing).
=> Preventing index field type polling running twice for the same index.

UPGRADING.md, graylog2-server/src/main/java/org/graylog2/Configuration.java
Added following config flags: default_archive_retention_time (to set retention time on new installations, 0 or no setting means feature is off)  & max_archive_retention_time (limit max retention time) 
Graylog2/graylog-plugin-enterprise#4113
With https://github.com/Graylog2/graylog-plugin-enterprise/issues/3514 we introduced a feature to set a retentionTime on archive configurations (per index set), to allow an automatic clean up of old archives.
What would be useful in addition is to support setting a default and a max retention value (in the server config), so that a Graylog administrator could set these.
The retentionTime value entered by the user in the UI (or via the API) should be validated against a configured max value.
Locally with max set, default set and later on overwritting …
=> default retention time & max value via config

graylog2-server/src/main/java/org/graylog/events/processor/EventDefinitionHandler.java
Resolves #10490 
The `{definitionId}/schedule` endpoint does not check whether an EventDefinition is
already enabled.
This will lead to additional jobdefinitions and triggers, which will break the UI.
Check for existing job and abort if detected.
=> Prevent scheduling duplicate event jobs

graylog2-web-interface/src/components/login/LoginBox.jsx, graylog2-web-interface/src/components/login/LoginHeader.tsx, graylog2-web-interface/src/components/login/__snapshots__/LoginBox.test.jsx.snap, graylog2-web-interface/src/pages/LoadingPage.tsx, graylog2-web-interface/src/pages/LoginPage.jsx
We recently changed the font family for h1 and h2. With this PR we are implementing the headline font for the login screen headline as well.
Before:
After:
=> Implement new headline font for login screen headline.

graylog2-web-interface/src/components/pipelines/ProcessingTimelineComponent.tsx
The bug was that the Pipelines don't get reloaded in case there was only one in the list, that is fixed now in this PR.
fixes #13731
=> Reload Pipelines after Delete

graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.jsx
Issue: https://github.com/Graylog2/graylog2-server/issues/13305
PR: https://github.com/Graylog2/graylog2-server/pull/13717
Backport adding more options for the pagination on Event Definitions
=> Backport adjust page sizes for Event Definitions

graylog2-web-interface/src/components/common/SearchForm.jsx, graylog2-web-interface/src/components/sidecars/administration/CollectorConfigurationModal.tsx
Before one shared prop **queryWidth** was used for both the input width and its container width which caused a bug in /alert page's search form. Now this PR fixes that by adding a different prop for the container's width: **queryContainerWidth**.
fixes #13752
=> Fix search form width bug

graylog2-web-interface/src/views/actions/QueriesActions.ts, graylog2-web-interface/src/views/components/AdaptableQueryTabs.test.tsx, graylog2-web-interface/src/views/components/AdaptableQueryTabs.tsx, graylog2-web-interface/src/views/components/AdaptableQueryTabsConfiguration.test.tsx, graylog2-web-interface/src/views/components/AdaptableQueryTabsConfiguration.tsx, graylog2-web-interface/src/views/stores/QueriesStore.ts, graylog2-web-interface/src/views/stores/ViewStatesStore.ts
This PR adds a Tabs Configuration component where users can reorder tabs as they like. In the future, we can add to this component more actions, like deleting tab or renaming tab e.t.c
As we have generic tab names for unnamed tabs ( `Page ${index}`) we have to keep old names after reordering. To solve this, we also set the generic names as static names after submitting the order. F.e. if the tab has the name `Page 1 `and then moved to position 4 it will have the name `Page 1 `
fix: https://github.com/Graylog2/graylog2-server/issues/7470
=> Reordering of tabs in dashboards

graylog2-web-interface/src/views/bindings.fieldActions.test.tsx, graylog2-web-interface/src/views/bindings.tsx
**Note:** This should be backported to `4.3`.
Prior to this PR, the `Show top values` action was disabled when the field it is triggered on is a compound field. This is too strict, because if all of the field types composing this compound field type are enumerable, then it is also possible to show the top values.
This PR is now changing the predicate to check if the field type is enumerable instead of if it is a compound type.
=> Allow `Show Top Values` action for enumerable compound fields.

graylog2-web-interface/src/components/bootstrap/NavDropdown.jsx, graylog2-web-interface/src/components/bootstrap/NavItem.tsx, graylog2-web-interface/src/components/bootstrap/Navbar.jsx, graylog2-web-interface/src/components/common/NavItemStateIndicator.tsx, graylog2-web-interface/src/components/common/PageNavigation.tsx, graylog2-web-interface/src/components/common/Wizard.test.jsx, graylog2-web-interface/src/components/navigation/Navigation.styles.jsx, graylog2-web-interface/src/components/navigation/SystemMenu.test.tsx
Currently the active state indicator in the navigation is not ideal, especially with the dark mode version. With this PR we are changing the way we display the active and hover state.
Before:
After:
Fixes: https://github.com/Graylog2/graylog2-server/issues/13773
=> Improve navigation active state indicator styles.

graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackService.java
refs #13398 
Old migrations are trying to install content packs. This happens before the migration that adds the events streams (`000000000000002`, `0000000000003`) has run. 
I think we can ignore this error for now. But maybe we should handle this a little better.
Fixes #13793
=> Remove erronous exception logging

full-backend-tests/src/test/java/org/graylog/plugins/views/SuggestionResourceIT.java, full-backend-tests/src/test/java/org/graylog/testing/utils/IndexSetUtils.java, full-backend-tests/src/test/java/org/graylog/testing/utils/StreamUtils.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/QuerySuggestionsES7.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/QuerySuggestionsOS2.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SuggestionsResource.java
**Note:** This PR needs to be backported to `4.3`.
Prior to this PR, the query suggestion endpoint checked permissions of the streams specified, but it did not generate a filter limiting the search to the specified streams. This could results in the disclosure of field values which are part of the same index set, but different streams.
=> Retrieve suggestions only for streams of request.

graylog2-web-interface/src/views/components/searchbar/PluggableSearchBarControls.test.tsx, graylog2-web-interface/src/views/components/searchbar/PluggableSearchBarControls.tsx
_Please note this PR should be backported for 4.4_
We want to render the pluggable search bar container only when it contains content. Currently this does not work on the dashboard, when no valid enterprise license is configured.
With this PR we are improving the related logic.
After:
=> Do not render pluggable search bar controls container, when it does not contain content.

graylog2-web-interface/src/views/bindings.fieldActions.test.tsx, graylog2-web-interface/src/views/bindings.tsx
**Note:** This is a backport of #13782 for 4.3
Prior to this PR, the `Show top values` action was disabled when the field it is triggered on is a compound field. This is too strict, because if all of the field types composing this compound field type are enumerable, then it is also possible to show the top values.
This PR is now changing the predicate to check if the field type is enumerable instead of if it is a compound type.
=> Allow `Show Top Values` action for enumerable compound fields. (backport of #13782 for 4.3)

graylog2-server/src/main/resources/org/graylog2/migrations/V20191219090834_AddSourcesPage_Content_Pack.json, graylog2-server/src/test/java/org/junit/platform/engine/support/hierarchical/ContainerMatrixHierarchicalTestEngine.java
fixes #13804
Default handling from the `HierarchicalTestEngine` from JUnit5 is to throw an Exception at the point of change.
This leads to a warning in the failsafe plugin, not an error. The assumption in JUnit5 is probably that no errors should occur at this point or that the problem is handled otherwise.
This fix fails hard with `System.exit(1);` so that mvn picks up the failure on Jenkins/Github Actions.
=> Fail IT tests if a container fails during startup

full-backend-tests/src/test/java/org/graylog/plugins/views/SuggestionResourceIT.java, full-backend-tests/src/test/java/org/graylog/testing/utils/IndexSetUtils.java, full-backend-tests/src/test/java/org/graylog/testing/utils/StreamUtils.java, graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/QuerySuggestionsES6.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/QuerySuggestionsES7.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SuggestionsResource.java
**Note:** This is a backport of #13817 to `4.3`.
Prior to this PR, the query suggestion endpoint checked permissions of the streams specified, but it did not generate a filter limiting the search to the specified streams. This could results in the disclosure of field values which are part of the same index set, but different streams.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#4287
=> Retrieve suggestions only for streams of request. (`4.3`)

graylog2-web-interface/src/views/components/aggregationwizard/grouping/GroupingsConfiguration.tsx
**Note:** This is based on #13855 and requires it to be merged first.
This PR is improving the styling of the global row/column limit inputs.  It wraps them in a single settings box, together with the rollup checkbox.
=> Improve styling of row/column limit settings.

graylog2-web-interface/src/views/components/searchbar/TimeRangeDisplay.tsx
With this PR we are removing the mono font from the search bar time range. This way we unify it with most other elements in the search bar and the preview in the time range picker.
Instead of highlighting the description `From` and `To` we are now highlighting the actual time, similar to the time range preview in the time range picker.
Before:
After:
=> Improve search bar time range font style.

graylog2-web-interface/src/components/configurations/SidecarConfig.jsx, graylog2-web-interface/src/components/configurations/SidecarConfig.test.tsx
In #13513, the `setState`-call of the `_onUpdate` function was extended to use a callback instead of a value. Extracting the new value from the event was also moved into the `setState`-callback. Unfortunately, at this point the event is already synthesized for performance reasons and target value extraction fails.
This PR is now moving target value extraction out of the scope of the `setState`-call to fix this.
Fixes #13867.
=> Extract updated value from target before it is synthesized.

changelog/unreleased/issue-13819.toml, graylog2-server/src/main/java/org/graylog2/streams/matchers/AlwaysMatcher.java, graylog2-server/src/test/java/org/graylog2/streams/matchers/AlwaysMatcherTest.java
Prior to this PR, the "Always match" rule always matched, regardless if it was inverted or not. This change is now taking the value of the `inverted` field into account.
Fixes #13819.
=> Take into account if "Always match" rule is inverted.

graylog2-web-interface/src/components/common/LinkToNode.jsx
Hides the host name in the system messages log on the System Overview Page. 
No other occurences where this could be visible were found in cloud instances.
removes the host name in LinkToNode on cloud installations.
closes Graylog2/graylog-plugin-cloud#1040
Host name not shown in cloud installations, still shown in on prem installations (also for inputs etc)
=> feat: Hide Hostname on Cloud

graylog2-web-interface/src/components/common/LinkToNode.jsx
* feat: Hide Hostname on Cloud, refactor to use React.Component
closes graylog-plugin-cloud/#1040
* fix: switch to PureComponent
* refactor: change import to alias, use nodes instead of nodeStore directly
* fix: make nodes optional
(cherry picked from commit 09e8c90b7f851cc7a060408f1ff3100a30e40210)
=> backport: Hide Hostname on Cloud (#13234)

graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/ObjectMapperProvider.java
Resolves #13868
A bit puzzling, since at the time of #13541 we most definitely needed this in order to get unit tests to pass. I am guessing the Mongojack update made this setting unnecessary. 
For reference, here is a discussion of this setting:
https://github.com/FasterXML/jackson-modules-java8/pull/75
=> Revert WRITE_DURATIONS_AS_TIMESTAMPS serialization feature

graylog2-web-interface/src/views/components/aggregationwizard/AggregationElementSelect.test.tsx, graylog2-web-interface/src/views/components/aggregationwizard/AggregationElementSelect.tsx, graylog2-web-interface/src/views/components/aggregationwizard/AggregationElementType.ts, graylog2-web-interface/src/views/components/aggregationwizard/AggregationWizard.tsx, graylog2-web-interface/src/views/components/aggregationwizard/ElementsConfiguration.tsx, graylog2-web-interface/src/views/components/aggregationwizard/grouping/GroupingElement.ts, graylog2-web-interface/src/views/components/aggregationwizard/grouping/GroupingsConfiguration.tsx, graylog2-web-interface/src/views/components/aggregationwizard/metric/MetricElement.ts, graylog2-web-interface/src/views/components/aggregationwizard/sort/SortElement.ts, graylog2-web-interface/src/views/components/aggregationwizard/visualization/VisualizationElement.ts
Prior to this PR, when deleting the last grouping in the aggregation builder, the rollup checkbox was still shown. This PR is fixing this.
=> Hide rollup checkbox when groupings are deleted.

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/PipelineRestPermissions.java
Adds a new built-in role with the name "Pipelines Manager" and the following permissions assigned to it:
"pipeline:create",
"pipeline:read",
"pipeline:edit",
"pipeline:delete",
"pipeline_rule:create",
"pipeline_rule:read",
"pipeline_rule:edit",
"pipeline_rule:delete",
"pipeline_connection:read",
"pipeline_connection:edit"
Fixes #13251
=> Add new "Pipelines Manager" built-in role

graylog2-server/src/main/java/org/graylog/events/contentpack/facade/EventDefinitionFacade.java, graylog2-server/src/main/java/org/graylog/events/processor/EventProcessorConfig.java, graylog2-server/src/test/java/org/graylog/events/contentpack/facade/EventDefinitionFacadeTest.java
Enables controlling what Event Definition config types are able to be exported to a Content Pack.
Sigma Event Definition config specific changes are in: https://github.com/Graylog2/graylog-plugin-enterprise/pull/4304
With the introduction of Sigma Rule Event Definitions, there are some there are some types of Event Definitions that should not be able to be exported to Content Packs. This change creates an `isContentPackExportable()` function in the  `EventProcessorConfig` interface, which defaults to true but allows sub-classes to override to false. This is then checked in the `EventDefinitionFacade` when providing the list of exportable Event Definitions to the User.
Sigma Rule Event Definitions are not meant to be exportable to Content Packs as exporting Rules will be done using the …
=> Disallow exporting non-exportable Event Definitions in Content Packs

changelog/unreleased/issue-13254.toml, graylog2-server/src/main/java/org/graylog/plugins/beats/Beats2Codec.java, graylog2-server/src/test/java/org/graylog/plugins/beats/Beats2CodecTest.java, graylog2-server/src/test/resources/org/graylog/plugins/beats/packetbeat-mongodb-v8.json
In beats v8 the "agent.hostname" field got renamed to "agent.name".
Fixes #13254
=> Fix "source" field for beats version >= 8

graylog2-server/src/main/java/org/graylog2/inputs/transports/KafkaTransport.java, graylog2-server/src/main/java/org/graylog2/plugin/configuration/fields/TextField.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/AbstractInputsResource.java, graylog2-web-interface/src/components/configurationforms/ConfigurationWell.jsx, graylog2-web-interface/src/components/configurationforms/types.ts
Adds an `is_sensitive` attribute to hide input config in the same way as the `is_password` attribute. Enables masking of sensitive values not only for password fields.
Closes #13383 
Set `custom_properties` in Kafka input config and checked that
- it's shown in plaintext when editing the input
- it's shown as `********` on the inputs overview page
- when the user does not have the `inputs:edit` permission, the field's value is masked with `<value hidden>` in the response to `GET /api/system/inputs`
=> Add text field attribute to hide sensitive input config

graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/validators/UnknownFieldsValidator.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/validators/util/UnknownFieldsListLimiter.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/validation/validators/util/UnknownFieldsListLimiterTest.java
See #13818.
From now on, if there are multiple messages about the same unknown field:
1. If they have no associated token/positional info, only the first one will be returned.
2. If they have associated token/positional info, the ones without positional info will be filtered out.
In the second scenario, there is a place of further improvement on FE side -> FE could collect positional info from the messages, in order to underline unknown fields properly, but visualize only one message.
/nocl
A need to do something with #13818.
Unit tests have been added.
It was tested manually.
With original query example invented by Marco:
`((TargetFilename: ("\/etc\/cron.d\/"*) OR ("\/etc\/cron.daily\/"*) OR ("\/etc\/cron.hourly\/"*) OR ("\/etc\/cron.monthly\/"*) OR ("\/etc\/cron.weekly\/"*) OR …
=> Limits the number of unknown field validation messages

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/series/ESLatestHandler.java
Latest aggregation now fetches only single, needed, defined field, ignoring other fields of the message. They have not been used anyway.
/nocl
Before, the response from ES/OS contained results with all fields of a message, i.e.:
```"5ea433d2-54b2-4f78-97e9-4468a2fdf20b-series-latest(took_ms)" : {
"hits" : {
"total" : {
"value" : 141156,
"relation" : "eq"
},
"max_score" : null,
"hits" : [
{
"_index" : "graylog_5",
"_type" : "_doc",
"_id" : "078ddcf1-4edd-11ed-895d-a6a2a5c176fa",
"_score" : null,
"_source" : {
"sequence_nr" : 6901,
"ingest_time" : "2022-10-18T12:04:33.957Z",
"took_ms" : 61,
"source" : "example.org",
"ingest_time_minute" : 4,
"gl2_source_input" : "6225bcec9d44357e84102f4a",
"ingest_time_day" : 18,
"http_method" : "DELETE",
"ingest_time_hour" : 12,
"action" : "login", …
```
=> Latest aggregation fetches only needed field

graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionForm.jsx
This is a tiny cosmetic fix for the event definition wizard. Prior to this change, a bottom margin was missing, leading to buttons being tucked on top of each other.
/nocl
Before:
After:
=> Fixing bottom margin for event definition wizard.

graylog2-server/src/main/java/org/graylog2/jackson/JodaDurationCompatSerializer.java, graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/ObjectMapperProvider.java, graylog2-server/src/test/java/org/graylog2/shared/bindings/providers/ObjectMapperProviderTest.java
Add a  Joda DurationSerializer that ignores the `SerializationFeature.WRITE_DURATIONS_AS_TIMESTAMPS` setting and always serializes `org.joda.time.Duration` to milliseconds. This became necessary with the Jackson 2.13 update, which forced us to disable `WRITE_DURATIONS_AS_TIMESTAMPS` to have `java.time.Duration` objects serialized as strings.
#Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/4320
/nocl
=> Always serialize joda Durations as milliseconds

graylog2-server/src/test/java/org/graylog/security/authservice/ldap/UnboundLDAPConnectorTestTLSIT.java, graylog2-server/src/test/java/org/graylog/testing/ldap/OpenLDAPContainer.java, graylog2-server/src/test/resources/org/graylog/testing/ldap/ldif/nested-groups.ldif
By specifying the custom LDIF on container creation, tests can use different directory content instead of having the "nested groups" content hard coded.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#4307
/nocl
=> LDAP testcontainer: specify custom LDIF on container creation

graylog2-web-interface/src/views/components/searchbar/queryvalidation/QueryValidation.test.tsx, graylog2-web-interface/src/views/components/searchbar/queryvalidation/QueryValidation.tsx
This PR is improving the display of query validation warnings by showing only a single literal warning message for every unknown field.  Positional indicatiors (yellow dots below every usage of the unknown field) will still be present. This cleans up the list of validation messages, as there is no additional value in showing it for every usage.
/nocl
=> Deduplicating "Unknown field" warnings for search query.

changelog/unreleased/issue-13254.toml, graylog2-server/src/main/java/org/graylog/plugins/beats/Beats2Codec.java, graylog2-server/src/test/java/org/graylog/plugins/beats/Beats2CodecTest.java, graylog2-server/src/test/resources/org/graylog/plugins/beats/packetbeat-mongodb-v8.json
* Fix "source" field for beats version >= 8
In beats v8 the "agent.hostname" field got renamed to "agent.name".
Fixes #13254
* Add changelog entry
(cherry picked from commit 63bc4fe56844194969cfa9023d61e6ae9fbb9dfc)
=> Fix "source" field for beats version >= 8 (#13895)

changelog/unreleased/issue-12090.toml, graylog2-web-interface/src/components/configurations/PermissionsConfig.tsx
Hide the edit button for the permission config on the configuration page if the user does not have the required edit permission.
Fixes #12090
=> Conditionally hide edit button for permission config

.github/workflows/build.yml
It looks like we are running out of disk space in our Github Actions build. From the docs, only 14gb of disk space are guaranteed. There is a commonly-known hack to remove the Android and .NET SDKs to free up ~30gb of space, which is applied here.
Refs actions/runner-images#2606
/nocl
=> Freeing up disk space for Github Action by removing unused SDKs.

UPGRADING.md, changelog/unreleased/issue-13888.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/json/JsonFlatten.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/json/JsonUtils.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/JsonUtilsTest.java
Fixes #13888
Pipeline function `flatten_json` returns all of the extracted values as strings, regardless of original JSON type. 
We now honor the type.
See the associated issue for details and examples.
=> Preserve JSON types in flatten_json function

changelog/unreleased/pr-13943.toml, graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationForm.jsx
Changes the default values for `search_within_ms` and `execute_every_ms` from one minute to five minutes.
The previous default of one minute leads to a rather high frequency of event generation runs. A default of five minutes seems to be a good default for most users to start with.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/3740
=> Events: change default for `search_within_ms` and `execute_every_ms` to 5 mins

bin/graylogctl, graylog2-server/src/test/resources/org/graylog/testing/graylognode/Dockerfile
There are some cases where Java falls back to using the Serial GC instead of G1GC:
Less then 2GB of RAM or only one CPU.
This can be the case in some docker environments.
We always want to use G1GC, because it ensures that GC pauses are always short.
Also drop NewRatio=1 which was a tuning parameter used for the previously used GC.
The default from Java is better here.
ResizeTLAB is also on by default now, so no need to specify that option.
https://github.com/openjdk/jdk/blob/3121898c33fa3cc5a049977f8677105a84c3e50c/src/hotspot/share/runtime/os.cpp#L1673
/nocl
=> Enforce usage of G1GC

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/buckets/ESValuesHandler.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/pivot/buckets/OSValuesHandler.java
This PR is fixing an issue with the scripted terms aggregation we are generating. When multiple indices are involved, one (or more) might lack the field mapping for one (or more) of the pivot fields involved. This results in an exception like this one:
```
Elasticsearch exception [type=illegal_argument_exception, reason=No field found for [took_ms_int] in mapping with types []]
```
This PR is now adding a check (`doc.containsKey('field')`) for the field presence in the current document to avoid this.
/nocl
=> Check if field is present in document when aggregating.

UPGRADING.md, changelog/unreleased/pr-13971.toml, graylog2-server/src/main/java/org/graylog2/Configuration.java, graylog2-server/src/main/java/org/graylog2/buffers/processors/OutputBufferProcessor.java, misc/graylog.conf
The output buffer processor is using a `ThreadPoolExecutor` with
a practically unbounded queue (with `Integer.MAX_VALUE` capacity).
For this combination, the docs for the `ThreadPoolExecutor` state
the following:
> Using an unbounded queue (for example a LinkedBlockingQueue
> without a predefined capacity) will cause new tasks to wait
> in the queue when all corePoolSize threads are busy. Thus,
> no more than corePoolSize threads will ever be created.
> (And the value of the maximumPoolSize therefore doesn't
> have any effect.)
This PR removes the following obsolete settings:
- `outputbuffer_processor_threads_max_pool_size`
- `outputbuffer_processor_keep_alive_time`
=> Remove ineffective settings for output buffer processor thread pool

bin/graylogctl, changelog/unreleased/pr-13980.toml
This change let's `graylogctl` use a bundled JVM when no `JAVA_HOME` is defined and a bundled JVM is present.
=> Add support for a bundled JVM in bin/graylogctl

changelog/unreleased/pr-13960.toml, graylog2-server/src/main/java/org/graylog2/configuration/HttpConfiguration.java, graylog2-server/src/main/java/org/graylog2/plugin/BaseConfiguration.java, graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/ProxiedRequestsExecutorService.java, graylog2-server/src/main/resources/prometheus-exporter.yml, misc/graylog.conf
The default value for `http_thread_pool_size` is 16, which is pretty low.
16 concurrent requests to `api/cluster/metrics/multiple` on a node will exhaust resources because each request triggers (among others) a subsequent request to the node itself.
As a quick fix, this PR sets the default pool size to 64. This can only really serve as a band-aid to avoid users running into that situation easily because it moves the breaking point to ~64 concurrent requests. We are currently investigating a more sustainable solution.
We are also increasing the default value for `proxied_requests_thread_pool_size` from 32 to 64. The previous advisory of setting it to `http_thread_pool_size * average_cluster_size` has been removed from the example `graylog.conf` though, because that feels a bit excessive. …
=> Change default values for `http_thread_pool_size` and `proxied_requests_thread_pool_size`

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/ESPivot.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/pivot/OSPivot.java
Improves a lot in #13981.
The aggregations do not break now.
The problem is limited to missing values on (Empty value) bucket.
To improve the situation, eliminating the most nasty aspect of the bug, while we are searching for a complex solution.
/nocl
=> Partial fix for issue 13981

full-backend-tests/src/test/java/org/graylog/plugins/views/aggregations/SearchWithAggregationsSupportingMissingBucketsIT.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/ESPivot.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/pivot/OSPivot.java
This PR is changing the `pivot` search type so that it always generates series for the metrics aggregations returned by the bucket handler. This is necessary e.g. for the `values` bucketing, which uses a `filters` aggregation. For this, we need to generate metrics in the filters aggregation itself, so metrics are generated for the "other" bucket and not only for the buckets produced by the (scripted/multi) terms aggregation nested into it.
This change is fixing the issue described in #13981, as it generates the required metrics in the "other" bucket, so extraction does not fail anymore.
This only affects the generation of metrics. Extracting and including them is still affected by the `rollup` setting.
Fixes #13981.
/nocl
=> Always generate metrics for filters aggregation.

changelog/unreleased/pr-13955.toml, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackend.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/OpenSearchBackend.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/SearchTypeHandler.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/errors/SearchException.java
This PR makes sure that if an exception is being thrown during extracting the results for a search type, it will be caught, added as as earch type error to the search result and extraction for other search types will be continued (similar to what we do already during search _generation_).
This prevents the error being handled as a fatal one (affecting the complete search), so other results will still be returned.
Before:
After:
=> Isolate exceptions during search type result extraction.

changelog/unreleased/issue-13888.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/json/JsonFlatten.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/json/JsonUtils.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/JsonUtilsTest.java
Backport of #13947 
The code is identical except for one thing: The default value of optional `stringify` parameter is `true` to maintain compatibility. In 5.0 we switch that to `false`, since users generally prefer to maintain the original types.
=> Backport: Preserve JSON types in flatten_json function

full-backend-tests/src/test/java/org/graylog/plugins/views/ScriptingApiResourceIT.java
The latest aggregation depends on messages indexed in specific order, which may cause flaky tests.
/nocl
Replaced latest with max, which is not order dependent.
Adapted existing tests
=> replaced latest aggregation in tests with max

changelog/unreleased/issue-13306.toml, graylog2-server/src/main/java/org/graylog2/inputs/transports/UdpTransport.java, graylog2-server/src/test/java/org/graylog2/inputs/transports/UdpTransportTest.java
Don't allocate the size of the entire UDP socket buffer for each packet!
This has been wrong for a long time [1], but only came up as a regression when using Java > 9.
On newer Java versions Netty does not use direct buffers via "Unsafe" to allocate memory. It falls back to ByteBuffer.allocateDirect which has inferior performance[2].
This behavior could be restored by adding these JVM options:
```
-Dio.netty.tryReflectionSetAccessible=true
--add-opens=java.base/java.nio=ALL-UNNAMED
--add-opens=java.base/sun.nio.ch=ALL-UNNAMED
```
But since fixing the receive buffer size to 64k gives us the same performance boost [3], we can avoid using these hacks, and not having to rely on Unsafe is also a good idea.
Refs
https://github.com/netty/netty/pull/7650 …
=> Only allocate the maximum needed size for one UDP packet

changelog/unreleased/issue-13998.toml, graylog2-server/src/main/java/org/graylog2/lookup/adapters/HTTPJSONPathDataAdapter.java, graylog2-web-interface/src/components/lookup-tables/DataAdapterForm.jsx, graylog2-web-interface/src/components/lookup-tables/adapters/HTTPJSONPathAdapterDocumentation.jsx
Fix mainly toast error notifications when editing the HTTP JSONPath data adapter without valid lookup url.
Fix: https://github.com/Graylog2/graylog2-server/issues/13998
Fix also one warning:
And introduce spacing between the title and the form:
Before:
After:
=> Fix toast errors on data adapter HTTP JSONPath when editing the title

changelog/unreleased/issue-13306.toml, graylog2-server/src/main/java/org/graylog2/inputs/transports/UdpTransport.java, graylog2-server/src/test/java/org/graylog2/inputs/transports/UdpTransportTest.java
Don't allocate the size of the entire UDP socket buffer for each packet!
This has been wrong for a long time, but only came up as a regression when using Java > 9.
On newer Java versions Netty does not use direct buffers via "Unsafe" to allocate memory. It falls back to ByteBuffer.allocateDirect which has inferior performance.
This behavior could be restored by adding these JVM options:
```
-Dio.netty.tryReflectionSetAccessible=true
--add-opens=java.base/java.nio=ALL-UNNAMED
--add-opens=java.base/sun.nio.ch=ALL-UNNAMED
```
But since fixing the receive buffer size to 64k gives us the same performance boost, we can avoid using these hacks, and not having to rely on Unsafe is also a good idea.
Refs
https://github.com/netty/netty/pull/7650 …
=> Only allocate the maximum needed size for one UDP packet (#14005)

graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/MessagesAdapterES6.java, graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/MessagesBatchES6IT.java, graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/testing/ElasticsearchInstanceES6.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MessagesAdapterES7.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/MessagesBatchES7IT.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ElasticsearchInstanceES7.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/OpensearchInstance.java, graylog2-server/src/main/java/org/graylog2/indexer/messages/ChunkedBulkIndexer.java, graylog2-server/src/test/java/org/graylog/testing/elasticsearch/TestableSearchServerInstance.java, graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesBatchIT.java, graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesIT.java, graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesTestIndexSet.java
An elastic cluster might not have enough memory available to
accept a full bulk index request. It can reject it with
a HTTP/1.1 429 Too Many Requests exception.
We could handle this the same way we do with Request entity too large
errors. See https://github.com/Graylog2/graylog2-server/pull/7071
/nocl because of old backport pre-cl check
**Note: backport to 4.3 from #13113**
fixes #13997
=> Reduce the bulk indexing request size for 429 errors too (backport to 4.3 #13113)

changelog/unreleased/issue-12908.toml, graylog2-web-interface/src/views/components/aggregationwizard/sort/SortConfiguration.tsx
Fixes #12908 by removing "latest" metrics from the list of possible sorts.
=> No sorting on latest aggregation

full-backend-tests/src/test/java/org/graylog/plugins/views/ScriptingApiResourceIT.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/ScriptingApiResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/SearchTypeResultToTabularResponseMapper.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/response/ResponseEntryDataType.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/response/ResponseEntryType.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/response/ResponseSchemaEntry.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/scriptingapi/response/ResponseSchemaEntryTest.java
Slightly adapted the schema structure of the response. The name has now more human-readable format, there is a field providing the column type information (grouping or metric).
Existing tests + added unit tests
/nocl
=> make schema response part more readable and easier to process

graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config
This change is setting a default value for the `scripting_api_preview` feature flag, suppressing a warning during startup that is shown otherwise.
/nocl
=> Set default value for scripting API feature flag.

full-backend-tests/src/test/java/org/graylog/plugins/views/aggregations/SearchAggregationsIT.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/ESPivot.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/pivot/OSPivot.java
This PR is fixing an issue with top-level metrics (metrics with no row/column pivots in place) when `rollup` is `false`. Before this change, it resulted in series aggregations not being generated. Now, they are explicitly generated when now row/column pivots exist.
/nocl
=> Fixing handling of top-level series when rollup is disabled.

changelog/unreleased/issue-13973.toml, graylog2-web-interface/src/components/lookup-tables/LookupTableView.test.tsx, graylog2-web-interface/src/components/lookup-tables/LookupTableView.tsx
Before we were only allowing word-characters in lookup tables key field, in this PR we fixed that.
#13973
=> Allow non-word-characters in lookup tables key field

full-backend-tests/src/test/java/org/graylog/plugins/views/ScriptingApiResourceIT.java, full-backend-tests/src/test/java/org/graylog/plugins/views/aggregations/SearchAggregationsIT.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/ESGeneratedQueryContext.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/AggTypes.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/ESPivot.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/OSGeneratedQueryContext.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/pivot/AggTypes.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/pivot/OSPivot.java
Prior to this PR, when a user specifies multiple series with identical functions/fields, search query generation would fail because multiple aggregations with the same id are generated.
This change is now making sure that only _distinct_ elements of the series list are generating aggregations. Due to identical series resulting in identical aggregation names, one aggregation can be used by multiple series handlers to extract values. This effectively results in a deduplication of series aggregations.
/nocl
=> Allow specifying multiple identical series in aggregation.

graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
This allows running old sidecars with the
default configuration templates.
For review check
https://github.com/Graylog2/graylog2-server/pull/13433/files#diff-9d89b33907b4f4cca49850a7559fcdab7bdcdd79feaf285bb0acf828f306e39f
https://freemarker.apache.org/docs/dgui_template_exp.html#dgui_template_exp_missing_default
/nocl
Fixes #14040
=> Add default values for ${sidecar.spoolDir}

graylog2-web-interface/src/components/common/SortableList/List.tsx, graylog2-web-interface/src/components/common/SortableList/ListItem.tsx, graylog2-web-interface/src/components/common/SortableList/SortableList.tsx, graylog2-web-interface/src/components/common/SortableList/SortableListItem.tsx, graylog2-web-interface/src/views/actions/QueriesActions.ts, graylog2-web-interface/src/views/components/AdaptableQueryTabs.test.tsx, graylog2-web-interface/src/views/components/AdaptableQueryTabs.tsx, graylog2-web-interface/src/views/components/AdaptableQueryTabsConfiguration.test.tsx, graylog2-web-interface/src/views/components/AdaptableQueryTabsConfiguration.tsx, graylog2-web-interface/src/views/components/QueryBar.tsx, graylog2-web-interface/src/views/components/QueryTabs.tsx, graylog2-web-interface/src/views/components/queries/QueryTitle.tsx, graylog2-web-interface/src/views/logic/views/ConfirmDeletingDashboardPage.ts, graylog2-web-interface/src/views/logic/views/FindNewActiveQuery.ts, graylog2-web-interface/src/views/stores/QueriesStore.ts, graylog2-web-interface/src/views/stores/ViewStatesStore.ts
With https://github.com/Graylog2/graylog2-server/pull/13744 we implemented a dashboard pages configuration modal which allows reordering the dashboard pages. With this PR we are extending the modal to allow deleting and renaming pages.
Fixes:  #13772
=> Support deleting and renaming dashboard pages inside pages configuration modal.

graylog2-web-interface/src/components/common/LinkContainer.test.jsx, graylog2-web-interface/src/components/common/LinkContainer.test.tsx, graylog2-web-interface/src/components/common/router.tsx
When wrapping a `Button` or `MenuItem` with `LinkContainer`, the `LinkContainer` defines an href for the child. Previously it was still possible to click on the link, even when the child (e.g. the `Button`) is disabled. 
With this PR we no longer deine the `href` for the children, if it is disabled.
/nocl
=> Do not implement link for `LinkContainer` children, when child is disabled.

graylog2-server/src/main/java/org/graylog2/shared/bindings/RestApiBindings.java
We don't bind any JobResourceHandler classes in Graylog Open, so we have to make sure we create the binding.
This PR changes the RestApiBindings to extend PluginModule instead of Graylog2Module to get access to the `jobResourceHandlerBinder()` method.
Fixes a Jersey injection error when navigating to "System/Overview" in a pure-open Graylog instance.
/nocl
*Notice:* This needs a backport to the 5.0 branch.
=> Ensure Guice binder creation for the JobResourceHandler interface

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/AggregationSpecToPivotMapper.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/MetricToSeriesSpecMapper.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/QueryParamsToFullRequestSpecificationMapper.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/SearchTypeResultToTabularResponseMapper.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/request/Metric.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/request/MetricConfiguration.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/request/PercentileConfiguration.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/validation/MetricValidator.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/MetricToSeriesSpecMapperTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/QueryParamsToFullRequestSpecificationMapperTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/scriptingapi/request/MetricTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/scriptingapi/validation/MetricValidatiorTest.java
Metrics that require additional configuration can be used from now on
/nocl
Currently we have one metric (percentile), that needs more configuration required than just function_name and field_name.
=> Metrics that require additional configuration can be used from now on

graylog2-web-interface/package.json, graylog2-web-interface/packages/graylog-web-plugin/src/PluginManifest.js, graylog2-web-interface/webpack.config.js
This reverts commit 3e7dd9329aafff4e6a78ebffcf1810897293ecff.
After merging #13886, we discovered two regressions:
- The production build does not work due to an exception being thrown:
```
plugin.org.graylog.plugins.threatintel.ThreatIntelPlugin.971cbda67668c6ebb98f.js:1 Uncaught TypeError: Cannot convert undefined or null to object
at hasOwnProperty (<anonymous>)
at bn (plugin.org.graylog.plugins.threatintel.ThreatIntelPlugin.971cbda67668c6ebb98f.js:1:363)
at J.build (FetchProvider.ts:189:9)
at z._validateSession (SessionStore.ts:107:10)
at z.validate (SessionStore.ts:83:28)
at r.n (vendor.de83b0a6424b4ec14331.js:2:911149)
at r.emit (vendor.de83b0a6424b4ec14331.js:2:56458)
at Function.trigger (vendor.de83b0a6424b4ec14331.js:2:912030)
at vendor.de83b0a6424b4ec14331.js:2:912135
at …
```
=> Revert "Use `esbuild` to transpile frontend assets. (#13886)"

changelog/unreleased/pr-14063.toml, changelog/unreleased/pr-14067.toml, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/ClusterAdapterOS2.java
The connectivity check for ES [Edit: *and OpenSearch*] was handling the wrong exception so that all calls to `#isConnected` would result in an exception when the ES cluster was not reachable. ~~This only affected Elasticsearch, not OpenSearch.~~
This PR fixes that by catching the correct exception type.
To see the effect, sever the connection to ES while the server is running.
Before the change, the server log will be filled with a lot messages from the `IndexFieldTypePollerPeriodical` like these: 
```
2022-11-25 17:23:26,792 ERROR: org.graylog2.indexer.fieldtypes.IndexFieldTypePollerPeriodical - Uncaught exception in Periodical
org.graylog.shaded.elasticsearch7.org.elasticsearch.ElasticsearchException: An error occurred: 
at org.graylog.storage.elasticsearch7.ElasticsearchClient.exception …
```
=> Fix indexer connectivity check by catching the correct exception type

graylog2-server/src/main/java/org/graylog2/inputs/transports/HttpTransport.java
Removes duplicate logic that adds the same `HttpHandler` definition both when the `Enable Bulk Receiving` option is enabled and disabled. Although a different name was used for both instances, adding the same handler in two places is unnecessary.
/nocl
Cleaner more concise code.
Noticed this as I was looking into https://github.com/Graylog2/graylog2-server/issues/13959. Although this has no affect on the issue, I wanted to clean it up.
Manual testing when the `Enable Bulk Receiving` option is enabled and disabled and verifying that bulk messages are correctly when enabled, and not when disabled.
See the original PR that added this feature for info on testing it: https://github.com/Graylog2/graylog2-server/pull/11529
=> Remove duplicate HttpHandler filter logic

graylog2-web-interface/package.json, graylog2-web-interface/packages/graylog-web-plugin/src/PluginManifest.js, graylog2-web-interface/src/components/authentication/BackendCreate/ServiceSelect.test.tsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionSummary.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldsForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionDescription.jsx, graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionsContainer.jsx, graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationFormContainer.jsx, graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotificationsContainer.jsx, graylog2-web-interface/src/components/events/events/EventsContainer.jsx, graylog2-web-interface/src/components/indices/rotation/TimeBasedRotationStrategySummary.jsx, graylog2-web-interface/src/components/lookup-tables/adapters/index.js, graylog2-web-interface/src/components/lookup-tables/index.js, graylog2-web-interface/src/components/nodes/JournalDetails.jsx, graylog2-web-interface/src/pages/AuthenticationBackendCreatePage.tsx, graylog2-web-interface/src/pages/AuthenticationBackendDetailsPage.tsx, graylog2-web-interface/src/pages/AuthenticationBackendEditPage.tsx, graylog2-web-interface/src/pages/AuthenticationCreatePage.tsx, graylog2-web-interface/src/pages/AuthenticationOverviewPage.tsx, graylog2-web-interface/src/pages/AuthenticationPage.tsx, graylog2-web-interface/src/pages/ShowEventNotificationPage.jsx, graylog2-web-interface/src/util/ISODurationUtils.js, graylog2-web-interface/webpack.config.js
**Note:** This is a reissue of #13886, which contained issues, as explained in #14068. This PR is fixing them, by a) fixing up imports for side-effects and b) using the same, consistent target specification for minification.
This PR is implementing `esbuild-loader` so we can make use of the improved performance of `esbuild` during bundling.
```
yarn build  192.80s user 3.71s system 296% cpu 1:06.38 total
```
```
yarn build  38.77s user 1.81s system 156% cpu 25.961 total
```
The `target` specification is what `browserslist` generates for the `defaults` setting right now as a start. There is no direct integration for it in `esbuild-loader` yet, but writing one is a simple task for a follow-up PR.
Another follow-up could be removing `babel-loader` etc. if we decide that we do not need it …
=> Use `esbuild` to transpile frontend assets. (Take II)

changelog/unreleased/issue-14086.toml, graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
Reduce the log level for bulk indexing retry attempts from `error` to `warning`, since they sometimes indicate a temporary condition, which will resolve with time.
Closes #14086
=> Change bulk indexing retry failure log level to warn

graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
For some reaseon Freemarker needs
escaped backslashes, when used within a variable.
/nocl
=> Fix collector templates on Windows

changelog/unreleased/issue-14086.toml
Fix Opensearch word typo and mention both Opensearch/Elasticsearch in change log introduced in https://github.com/Graylog2/graylog2-server/pull/14088.
See initial discussion: https://github.com/Graylog2/graylog2-server/pull/14088#discussion_r1035653494
=> Issue 14086 change log: Fix Opensearch typo, mention both indexers

graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/FieldTypesLookup.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/ScriptingApiResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/MessagesTabularResponseCreator.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/request/AggregationRequestSpec.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/request/MessagesRequestSpec.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/request/SearchRequestSpec.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/response/ResponseEntryDataType.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/response/ResponseSchemaEntry.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/FieldTypesLookupTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/scriptingapi/request/MessagesRequestSpecTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/scriptingapi/response/ResponseEntryDataTypeTest.java
Messages endpoint gives field type information in schema
/nocl
Fields have more rich typing than groupings (field names - always strings) and metrics (either string or numeric).
We need to use our "field types lookup" to provide this information in order to create proper schema part of the response.
Unit tests have been added.
=> Messages endpoint gives field type information in schema

graylog2-web-interface/src/components/common/PublicNotifications.test.tsx, graylog2-web-interface/src/components/common/PublicNotifications.tsx
When the enterprise plugin is not installed, the list of public notifications can be `undefined`. In this case an exception is thrown when the `PublicNotifications` component is rendered.
This PR is making access of notifications more lenient by using optional chaining.
/nocl
=> Fix public notifications for open core.

graylog2-web-interface/src/components/common/PublicNotifications.test.tsx, graylog2-web-interface/src/components/common/PublicNotifications.tsx
**Note:** This is a backport of #14087 to `4.3`.
When the enterprise plugin is not installed, the list of public notifications can be undefined. In this case an exception is thrown when the PublicNotifications component is rendered.
This PR is making access of notifications more lenient by using optional chaining.
/nocl
=> Fix public notifications for open core. (`4.3`)

graylog2-web-interface/src/components/common/PublicNotifications.test.tsx, graylog2-web-interface/src/components/common/PublicNotifications.tsx
**Note:** This is a backport of #14087 to `5.0`.
When the enterprise plugin is not installed, the list of public notifications can be undefined. In this case an exception is thrown when the PublicNotifications component is rendered.
This PR is making access of notifications more lenient by using optional chaining.
/nocl
=> Fix public notifications for open core. (`5.0`)

changelog/unreleased/issue-9461.toml, graylog2-server/src/main/java/org/graylog2/configuration/ExposedConfiguration.java
Add `output_batch_size` to the values returned in the `system/configuration` API
Resolves #9461
=> Expose batchSize read-only in API

changelog/unreleased/pr-14171.toml, graylog2-web-interface/src/pages/ShowMessagePage.test.tsx, graylog2-web-interface/src/views/components/contexts/DefaultFieldTypesProvider.test.tsx, graylog2-web-interface/src/views/components/contexts/DefaultFieldTypesProvider.tsx, graylog2-web-interface/src/views/logic/fieldtypes/useFieldTypes.ts
**Note:** This needs a backport to `4.3` and `5.0`.
This change is reimplementing a missing refetching of field types when the search is refreshed. This helps users to synchronize the field types they see in the UI while new fields are being ingested.
Refs #13279.
=> Trigger refetching fields on search refresh.

full-backend-tests/src/test/java/org/graylog/plugins/views/ScriptingApiResourceIT.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/ScriptingApiResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/MessagesSpecToMessageListMapper.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/QueryParamsToFullRequestSpecificationMapper.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/request/MessagesRequestSpec.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/SortSpec.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/QueryParamsToFullRequestSpecificationMapperTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/scriptingapi/request/MessagesRequestSpecTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/scriptingapi/validation/MetricValidatorTest.java
Messages endpoint of Scripting API was missing sorting functionality. It has been added.
If no sorting provided, or raw "timestamp" sorting is used, the sorting will automatically switch to "timestamp + gl2_message_id" approach, introduced by @mpfz0r 
/nocl
With new tests.
=> Sorting of messages in Scripting API

UPGRADING.md, changelog/unreleased/issue-14074.toml, graylog2-server/src/main/java/org/graylog2/inputs/misc/jsonpath/JsonPathInput.java
The `JSON path value from HTTP API` input will now only run on the leader node,
if the `Global` option has been selected in the input configuration.
Previously, the input was started on all nodes in the cluster.
Fixes #14074 
Smoke test in a two-node cluster
=> Start global JSON path input on leader node only

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/QuerySuggestionsES7.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/QuerySuggestionsOS2.java
Filter should be in theory faster than must clause, we don't care about scoring as we are running an aggregation anyway.
/nocl
=> Query suggestions use filter instead of must, should speed up responses

changelog/unreleased/pr-14097.toml, graylog2-server/src/main/java/org/graylog2/system/shutdown/GracefulShutdownService.java, graylog2-server/src/test/java/org/graylog2/system/shutdown/GracefulShutdownServiceTest.java
The GracefulShutdownService used a SynchronousQueue with a fixed capacity. If all threads were busy, the executor would reject additional tasks.
We fix this by using an unbounded blocking queue for the executor. We still limit the number of concurrently run hooks but allow additional hooks to be queued for execution.
To reproduce the problem, assign > 10 outputs to an active stream and then shut down the server. Before aplpying the fix, you should see a `RejectedExecutionException` in the server log. After applying the fix, shutdown should proceed as planned.
=> Support more than 10 shutdown hooks in graceful shutdown service

changelog/unreleased/issue-14153.toml, graylog2-server/src/main/java/org/graylog2/security/AESTools.java, graylog2-server/src/test/java/org/graylog2/security/AESToolsTest.java
If Graylog is run in an FIPS environment there is no crypto provider available that supports `AES/CBC/ISO10126Padding`. This is likely because this padding standard was withdrawn from ISO in 2007.
It is considered a bad practice to leave a subliminal channel in the padding.
We tried to workaround this by explicitly using BouncyCastle for the encryption/decryption.
This however creates problems with Oracle Java, because we strip the signature off the bouncy castle jar while repackaging it into our Uber-Jar.
In contrast to OpenJDK, Oracle Java does not allow the use of unsigned Security Providers.
Solution:
Change our secret encryption to using `PKCS5Padding` instead. There is a FIPS compatible provider `SunPKCS11-NSS-FIPS` available which supports `AES/CBC/PKCS5Padding`.
For backwards …
=> Use PKCS5Padding instead of ISO10126Padding for secrets encryption

changelog/unreleased/issue-14153.toml, graylog2-server/src/main/java/org/graylog2/security/AESTools.java, graylog2-server/src/test/java/org/graylog2/security/AESToolsTest.java
If Graylog is run in an FIPS environment there is no crypto provider available that supports "AES/CBC/ISO10126Padding". This is likely because this padding standard was withdrawn from ISO in 2007.
It is considered bad practice to leave a subliminal channel in the padding.
We tried to workaround this by explicitly using BouncyCastle for the encryption/decryption.
This however creates problems with Oracle Java, because we strip the signature off the bouncy castle jar while repackaging it into our Uber-Jar.
In contrast to OpenJDK, Oracle Java does not allow the use of unsigned Security Providers.
Solution:
Change our secret encryption to using PKCS5Padding instead. There is a FIPS compatible provider "SunPKCS11-NSS-FIPS" available which supports "AES/CBC/PKCS5Padding".
For backwards …
=> Use PKCS5 instead of ISO10126 padding for secrets encryption (4.3 backport)

changelog/unreleased/issue-14153.toml, graylog2-server/src/main/java/org/graylog2/security/AESTools.java, graylog2-server/src/test/java/org/graylog2/security/AESToolsTest.java
If Graylog is run in an FIPS environment there is no crypto provider available that supports "AES/CBC/ISO10126Padding". This is likely because this padding standard was withdrawn from ISO in 2007.
It is considered bad practice to leave a subliminal channel in the padding.
We tried to workaround this by explicitly using BouncyCastle for the encryption/decryption.
This however creates problems with Oracle Java, because we strip the signature off the bouncy castle jar while repackaging it into our Uber-Jar.
In contrast to OpenJDK, Oracle Java does not allow the use of unsigned Security Providers.
Solution:
Change our secret encryption to using PKCS5Padding instead. There is a FIPS compatible provider "SunPKCS11-NSS-FIPS" available which supports "AES/CBC/PKCS5Padding".
For backwards …
=> Use PKCS5 instead of ISO10126 padding for secrets encryption (5.0 backport)

graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchesList.tsx, graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchesModal.test.tsx
Previously we were rendering the title of a saved search in the saved searches overview as a button.
With this PR we are rendering the title as a link instead.
It has a few benefits, it reflect the actual intention of the element, it unifies the title element with similar cases like the dashboards overview and users able to see the URL of the saved search and can copy it.
/nocl
=> Display saved search title as anchor instead of button.

changelog/unreleased/pr-14239.toml, graylog2-web-interface/src/views/components/DashboardSearchBar.tsx, graylog2-web-interface/src/views/components/SearchBar.tsx, graylog2-web-interface/src/views/components/WidgetQueryControls.tsx, graylog2-web-interface/src/views/components/searchbar/queryinput/BasicQueryInput.tsx, graylog2-web-interface/src/views/components/searchbar/queryinput/PluggableCommands.test.tsx, graylog2-web-interface/src/views/components/searchbar/queryinput/PluggableCommands.tsx, graylog2-web-interface/src/views/components/searchbar/queryinput/QueryInput.test.tsx, graylog2-web-interface/src/views/components/searchbar/queryinput/QueryInput.tsx, graylog2-web-interface/src/views/components/searchbar/queryinput/StyledAceEditor.tsx, graylog2-web-interface/src/views/components/searchbar/queryinput/ace-types.ts, graylog2-web-interface/src/views/components/searchbar/queryinput/types.ts, graylog2-web-interface/src/views/components/searchbar/queryinput/usePluggableCommands.tsx, graylog2-web-interface/src/views/types.ts
This PR  is adding a new frontend plugin API that allows plugins to contribute custom commands to the query input. It allows to provide two different entities:
- a command definition (`views.queryInput.commands`) specifying a usage scope, name, mac/windows key bindings as well as a function that is being executed, which gets an `Editor` instance as well as a `CustomCommandContext` object
- a context provider (`views.queryInput.commandContextProviders`) which allows a plugin to extend the `CustomCommandContext` object which is supplied
Part of the context is the `usage`, which specifies the scope the query input is currently running in. It can be one of `'search_query' | 'widget_query' | 'global_override_query'` currently. This `usage` scope can be specified when binding the command to …
=> Support providing custom commands for query input component.

graylog2-server/src/test/java/org/graylog2/outputs/BlockingBatchedESOutputTest.java
The test was [failing on our CI infrastructure](https://github.com/Graylog2/graylog2-server/actions/runs/3738414885/jobs/6344478855).
Slightly rework the test and adjust timeouts.
/nocl
=> Attempt to fix failing ES output test

graylog2-server/src/test/java/org/graylog2/system/shutdown/GracefulShutdownServiceTest.java
It's not a critical test so I think it's OK to disable it.
Could probably be fixed by adjusting the timeouts but that would potentially increase test runtime even more and is also guesswork.
/nocl
=> Disable GracefulShutdownService test which is flaky on Jenkins

full-backend-tests/src/test/java/org/graylog/plugins/views/ScriptingApiResourceIT.java
Some of the scripting api integration tests are flaky. The assumption is that there may be a problem/async/timing issue between stream and stream rule creation and message ingestion. In the moment the message is ingested, the stream could be not fully initialized yet. 
This test verifies that all messages are routed to correct streams by aggregating by stream ID. 
/nocl
=> Added test to aggregate messages by streams

graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
Unit test for date conversion should not use `now()`, as this may cause problems depending on when the test is executed.
/nocl
=> Fix unit test to avoid issues with day boundary or DST

changelog/unreleased/pr-14262.toml, full-backend-tests/src/test/java/org/graylog2/streams/StreamsIT.java, graylog2-server/src/main/java/org/graylog2/streams/PaginatedStreamService.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/Streams.java
Prior to this PR, sorting streams by title/description/... sorted them lexicographically, but case-sensitive. This is most probably not what users are expecting.
This change is now adding functionality which is lower-casing the sort field before applying the sort to it.
=> Sort streams case-insensitive in API.

changelog/unreleased/pr-14277.toml, graylog2-web-interface/src/views/components/aggregationwizard/grouping/configuration/Direction.tsx
**Note:** This needs to be backported to `4.3` and `5.0`.
This PR is using the `checked` instead of the `defaultChecked` prop for the radio input of the grouping directions.
This avoids the phenomenon that the radio input is becoming unchecked when a grouping is dragged, although the state stays consistent.
=> Avoid vanishing grouping direction when dragged.

graylog2-web-interface/src/views/components/visualizations/__tests__/XYPlot.test.tsx, graylog2-web-interface/src/views/components/visualizations/area/__tests__/AreaVisualization.test.tsx, graylog2-web-interface/src/views/components/visualizations/heatmap/__tests__/HeatmapVisualization.test.tsx, graylog2-web-interface/src/views/components/visualizations/worldmap/__tests__/WorldMapVisualization.test.tsx
Since we included the `UserDateTimeProvider` in the `WrappingContainer`, which we render for every test, we do not have to render the `UserDateTimeProvider` in test manually anymore.
/nocl
=> Remove not needed usage of `UserDateTimeProvider` in tests.

changelog/unreleased/issue-11183.toml, graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailSender.java, graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java, graylog2-server/src/main/java/org/graylog2/bindings/providers/HtmlSafeJmteEngineProvider.java, graylog2-server/src/test/java/org/graylog/events/notifications/types/EmailSenderTest.java
* replace Jmte Engine instance with JmteEngineProvider
plugins can add NamedRenderer to engine
add HtmlSafeRenderer to engine by default
* Add EmailJmteEngineProvider, always escape values
* Apply html escape to new event notification emails
The legacy email notification was plaintext only
and does not need to be escaped.
Also simplify escaping a bit and don't escape the email Subject.
* Add EmailSenderTest
* add changelog
* remove unneded multibinder
* revert test notification title change
* keep singleton binding for regular template engine
Co-authored-by: 朱穆穆 <mumu.zhu@feat.com>
(cherry picked from commit 29a4c31682274c252b7a95a355b2361966611471)
=> Escape Event content in HTML email notifications (#14286) (4.3)

changelog/unreleased/issue-11183.toml, graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailSender.java, graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java, graylog2-server/src/main/java/org/graylog2/bindings/providers/HtmlSafeJmteEngineProvider.java, graylog2-server/src/test/java/org/graylog/events/notifications/types/EmailSenderTest.java
* replace Jmte Engine instance with JmteEngineProvider
plugins can add NamedRenderer to engine
add HtmlSafeRenderer to engine by default
* Add EmailJmteEngineProvider, always escape values
* Apply html escape to new event notification emails
The legacy email notification was plaintext only
and does not need to be escaped.
Also simplify escaping a bit and don't escape the email Subject.
* Add EmailSenderTest
* add changelog
* remove unneded multibinder
* revert test notification title change
* keep singleton binding for regular template engine
Co-authored-by: 朱穆穆 <mumu.zhu@feat.com>
(cherry picked from commit 29a4c31682274c252b7a95a355b2361966611471)
=> Escape Event content in HTML email notifications (#14286) (5.0)

changelog/unreleased/pr-14277.toml, graylog2-web-interface/src/views/components/aggregationwizard/grouping/configuration/Direction.tsx
**Note:** This is a backport of #14277 for  4.3
This PR is using the `checked` instead of the `defaultChecked` prop for the radio input of the grouping directions.
This avoids the phenomenon that the radio input is becoming unchecked when a grouping is dragged, although the state stays consistent.
=> Avoid vanishing grouping direction when dragged. (Backport of #14277 for 4.3)

changelog/unreleased/pr-14277.toml, graylog2-web-interface/src/views/components/aggregationwizard/grouping/configuration/Direction.tsx
**Note:** This is a backport of #14277 for  5.0
This PR is using the `checked` instead of the `defaultChecked` prop for the radio input of the grouping directions.
This avoids the phenomenon that the radio input is becoming unchecked when a grouping is dragged, although the state stays consistent.
=> Avoid vanishing grouping direction when dragged. (Backport of #14277 for 5.0) #14281

changelog/unreleased/pr-14269.toml, graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/AreaVisualizationConfigDTO.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/BarVisualizationConfigDTO.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/LineVisualizationConfigDTO.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/ScatterVisualizationConfigDTO.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/XYVisualizationConfig.java, graylog2-web-interface/src/views/Constants.ts, graylog2-web-interface/src/views/bindings.tsx, graylog2-web-interface/src/views/components/MigrateFieldCharts.tsx, graylog2-web-interface/src/views/components/__tests__/MigrateFieldCharts.test.tsx, graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.corevisualizations.test.tsx, graylog2-web-interface/src/views/components/visualizations/GenericPlot.tsx, graylog2-web-interface/src/views/components/visualizations/XYPlot.tsx, graylog2-web-interface/src/views/components/visualizations/__tests__/XYPlot.test.tsx, graylog2-web-interface/src/views/components/visualizations/area/AreaVisualization.tsx, graylog2-web-interface/src/views/components/visualizations/area/bindings.tsx, graylog2-web-interface/src/views/components/visualizations/bar/BarVisualization.tsx, graylog2-web-interface/src/views/components/visualizations/bar/bindings.tsx, graylog2-web-interface/src/views/components/visualizations/line/LineVisualization.tsx, graylog2-web-interface/src/views/components/visualizations/line/bindings.tsx, graylog2-web-interface/src/views/components/visualizations/scatter/ScatterVisualization.tsx, graylog2-web-interface/src/views/components/visualizations/scatter/bindings.tsx, graylog2-web-interface/src/views/logic/aggregationbuilder/visualizations/AreaVisualizationConfig.ts, graylog2-web-interface/src/views/logic/aggregationbuilder/visualizations/BarVisualizationConfig.ts, graylog2-web-interface/src/views/logic/aggregationbuilder/visualizations/LineVisualizationConfig.ts, graylog2-web-interface/src/views/logic/aggregationbuilder/visualizations/ScatterVisualizationConfig.ts, graylog2-web-interface/src/views/logic/aggregationbuilder/visualizations/XYVisualization.ts, graylog2-web-interface/src/views/types.ts
This PR is adding the option to switch the Y Axis of an X/Y-Chart (currently Area, Bar, Line & Scatter charts) to a logarithmic scale. The default is still a linear scale though.
=> Adding logarithmic scale for X/Y charts.

graylog2-web-interface/src/components/bootstrap/DropdownButton.jsx, graylog2-web-interface/src/components/common/OverlayDropdown.tsx, graylog2-web-interface/src/components/common/OverlayDropdownButton.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/StreamActions.tsx, graylog2-web-interface/src/views/components/actions/Action.tsx
The new layout for the streams overview scroll horizontally when there is not enough space. This resulted in a problem with the more actions dropdown, under some circumstances
With this PR we are using a portal for the dropdown to fix the overflow problem
/nocl
=> Fix overflow of more actions dropdown in streams overview.

UPGRADING.md, changelog/unreleased/issue-14074.toml, graylog2-server/src/main/java/org/graylog2/inputs/misc/jsonpath/JsonPathInput.java
4.3 backport for #14186 PR / #14074 issue.
=>  Start global JSON path input on leader node only (#14186) 4.3 backport

UPGRADING.md, changelog/unreleased/issue-14074.toml, graylog2-server/src/main/java/org/graylog2/inputs/misc/jsonpath/JsonPathInput.java
5.0 backport for #14186 PR / #14074 issue.
=> Start global JSON path input on leader node only (#14186) 5.0 backport

changelog/unreleased/issue-14268.toml, graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchQueryString.java, graylog2-server/src/test/java/org/graylog/events/processor/aggregation/AggregationEventProcessorTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchQueryStringTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/engine/ValidationRequestTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/export/CommandFactoryTest.java
**Note:** This is a backport of #14284 to `4.3`.
This PR is fixing an issue related to exporting a search type. When both the search type and the query contain query strings, they are being concatenated, by simply combining them with an AND. For simple query strings this works, but it changes the logic for more complicated ones (e.g. when query string1 is foo OR bar and the second is also foo OR bar, the resulting query string foo OR bar AND foo bar has a different meaning, due to the stronger binding of the logical AND.
With this PR, concatenating two query strings wraps them in braces too, so foo OR bar concatenated to itself ends up as (foo OR bar) AND (foo or BAR), which returns the same, correct results.
Fixes #14268.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#4514
=> Concatenate query strings of queries/search types properly when exporting. (`4.3`)

changelog/unreleased/issue-14268.toml, graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchQueryString.java, graylog2-server/src/test/java/org/graylog/events/processor/aggregation/AggregationEventProcessorTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchQueryStringTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/engine/ValidationRequestTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/export/CommandFactoryTest.java
**Note:** This is a backport of #14284 to `5.0`.
This PR is fixing an issue related to exporting a search type. When both the search type and the query contain query strings, they are being concatenated, by simply combining them with an AND. For simple query strings this works, but it changes the logic for more complicated ones (e.g. when query string1 is foo OR bar and the second is also foo OR bar, the resulting query string foo OR bar AND foo bar has a different meaning, due to the stronger binding of the logical AND.
With this PR, concatenating two query strings wraps them in braces too, so foo OR bar concatenated to itself ends up as (foo OR bar) AND (foo or BAR), which returns the same, correct results.
Fixes #14268.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#4513
=> Concatenate query strings of queries/search types properly when exporting. (`5.0`)

changelog/unreleased/issue-14140.toml, graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/SavedSearchService.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewDTO.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/views/ViewServiceTest.java
Saved searches can be sorted by 3 additional fields: owner, description and summary.
Proper indexes prepared in Mongo DB for sortable fields.
Fixes #14140.
See #14140.
Manually and with additional integration test.
=> Saved searches can be sorted by 3 additional fields

changelog/unreleased/pr-14370.toml, graylog2-server/src/main/java/org/graylog2/shared/metrics/CustomMemoryUsageGaugeSet.java, graylog2-server/src/main/java/org/graylog2/shared/metrics/MetricRegistryFactory.java
Single quotes are removed from all jvm.memory.* metric names because they make it difficult to design a match_pattern for 
Prometheus Exporter Custom Mappings. 
fixes Graylog2/graylog-plugin-enterprise#4394
=> remove single-quotes from jvm.memory metric names

graylog2-server/src/main/java/org/graylog2/rest/models/tools/responses/PageListResponse.java, graylog2-server/src/test/java/org/graylog2/rest/models/tools/responses/PageListResponseTest.java
PageListResponse receives fields for attributes and defaults.
It is a first step to make it a reusable type of response for all entities migrated to new entity list approach.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#4556
/nocl
So far moving to new entity list approach was achieved by creating new type of response in the BE. Those types of responses were almost identical. It's time to unify the code, this is the first step in this process.
Unit tests have been modified and run.
Tested manually on SearchFiltersUsage (see corresponding enterprise PR).
=> PageListResponse receives fields for attributes and defaults

graylog2-server/src/main/java/org/graylog/events/processor/systemnotification/SystemNotificationRenderService.java, graylog2-server/src/main/java/org/graylog2/notifications/NotificationImpl.java
Otherwise Notification.getNodeId() is returning nil
Improve SystemNotificationRenderService render exception message.
I stumbled over these while testing with an `An input has failed to start` notification.
Relates to #14399
/nocl
=> Update the node_id field on Notification.addNode()

changelog/unreleased/issue-12857.toml, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java, graylog2-server/src/main/java/org/graylog2/streams/StreamServiceImpl.java
Leading and trailing whitespaces are removed on stream names while saving, creating or cloning a stream.
fixes #12857
=> Trim whitespace characters on stream names

graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx
Set the default `grace_period` in Event definition's notification setting to `5mn`.
/nocl
fix Graylog2/graylog-plugin-enterprise#3741
=> Set default grace_period to 5mn in Event Definition

graylog2-web-interface/src/theme/GlobalThemeStyles.js
The button border radius is now part of the `bootstrap-config.json` and no longer required in the `GlobalThemeStyles`.
/nocl
=> Remove not needed button styling in `GlobalThemeStyles`.

changelog/unreleased/pr-14331.toml, graylog2-web-interface/src/components/common/ReactGridContainer.tsx, graylog2-web-interface/src/views/bindings.tsx, graylog2-web-interface/src/views/components/CreateNewWidgetModal.tsx, graylog2-web-interface/src/views/components/GridGaps.test.ts, graylog2-web-interface/src/views/components/GridGaps.ts, graylog2-web-interface/src/views/components/NewWidgetPlaceholder.test.tsx, graylog2-web-interface/src/views/components/NewWidgetPlaceholder.tsx, graylog2-web-interface/src/views/components/WidgetGrid.tsx, graylog2-web-interface/src/views/components/sidebar/create/AddWidgetButton.tsx, graylog2-web-interface/src/views/logic/creatoractions/AddCustomAggregation.ts, graylog2-web-interface/src/views/logic/fieldactions/AddMessageCountActionHandler.ts, graylog2-web-interface/src/views/logic/fieldactions/AddMessageTableActionHandler.ts, graylog2-web-interface/src/views/stores/CurrentViewStateStore.ts, graylog2-web-interface/src/views/stores/ViewStore.ts, graylog2-web-interface/src/views/types.ts
This PR is adding a feature that adds widget placeholders in empty slots on the widget grid, allowing the user to create widgets in these spots. This removes the need for the user to create a widget and then move it to the desired spot.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#4510
=> Showing widget placeholders allowing inline widget creation.

graylog2-web-interface/src/components/configurationforms/ConfigurationForm.jsx
These changes update the Input configuration form to use the state to control the Bootstrap Modal. 
/nocl
fix #14438
=> Update Input configuration form to use controlled Modal

graylog2-web-interface/src/views/components/aggregationwizard/FieldSelect.tsx
This PR is fixing a styling problem in the fields select in the aggregations builder.
Before:
After:
The styling / scrolling behaviour is now similar to 4.3.
/nocl
=> Fix line break in field select options.

changelog/unreleased/issue-14280.toml, graylog2-server/src/main/java/org/graylog2/indexer/indices/util/NumberBasedIndexNameComparator.java, graylog2-server/src/main/java/org/graylog2/rest/models/system/indexer/responses/IndexInfo.java, graylog2-server/src/main/java/org/graylog2/rest/models/system/indexer/responses/IndexSummary.java, graylog2-server/src/main/java/org/graylog2/rest/models/system/indexer/responses/IndexerOverview.java, graylog2-server/src/main/java/org/graylog2/rest/models/system/indexer/responses/OpenIndicesInfo.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexerOverviewResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndicesResource.java, graylog2-server/src/test/java/org/graylog2/indexer/indices/util/NumberBasedIndexNameComparatorTest.java, graylog2-web-interface/src/components/indices/IndicesOverview.jsx, graylog2-web-interface/src/components/indices/IndicesOverview.tsx, graylog2-web-interface/src/pages/IndexSetPage.tsx, graylog2-web-interface/src/stores/indexers/IndexerOverviewStore.ts, graylog2-web-interface/src/stores/indices/IndicesStore.ts
Fixes #14280. See the issue for details.
For the indices list we are now using an array instead of an object to preserve the sorting.
See  #14280.
Unit tests have been added.
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/4539
=> Sorting of indices inside an index set is based on their numbers, descending

graylog2-web-interface/src/components/common/PaginatedList.test.tsx, graylog2-web-interface/src/components/common/PaginatedList.tsx, graylog2-web-interface/src/components/pipelines/ProcessingTimelineComponent.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/StreamsOverview.tsx, graylog2-web-interface/src/hooks/usePaginationQueryParameter.test.tsx, graylog2-web-interface/src/hooks/usePaginationQueryParameter.ts, graylog2-web-interface/src/pages/RulesPage.tsx
With this PR we are simplifying the state management in the `PaginatedList` component. The component can maintain the state for the active page and page size in two different ways:
1. It can have its own react state
2. Or It can use the URL query params to maintain the state
Before this PR the component contained all necessary logic for both use cases. Even when the state was based on the URL query params it still maintained its own state. This resulted in a comparable complex state management.
The `PaginatedList` component now contains the stateless `ListBase` component which receives the active page and page size. 
In case 1 we render a wrapper component which maintains a state for the active page and page size and passes it to the `ListBase` component.
In case 2 we render a wrapper …
=> Separate concerns in `PaginatedList` to simplify state management.

changelog/unreleased/pr-14409.toml, graylog2-server/src/main/java/org/graylog2/streams/StreamRouterEngine.java, graylog2-server/src/main/resources/prometheus-exporter.yml, graylog2-server/src/test/java/org/graylog2/streams/StreamRouterEngineTest.java
Implements the following:
1) Reduce logging level for warning from `warn` to `trace`, to not show the warning unless `trace` logging is explicitly enabled:
> Couldn't remove default stream [stream-id] from message [message-id]
2) Add a metric, so that the condition can be monitored, if desired:
`counter org.graylog2.streams.StreamRouterEngine.cannotRemoveDefault`
`stream_router_cannot_remove_default`
Closes https://github.com/Graylog2/graylog-plugin-enterprise/issues/3481
This warning is logged when a previously executed message processor (or Illuminate) has already removed the default stream from the message (Illuminate does this by default for all messages currently). Once the message exits the first processor, it then enters the Graylog MessageFilterChain and is offered up for matching …
=> Reduce logging and add metric for stream warning

changelog/unreleased/pr-14409.toml, graylog2-server/src/main/java/org/graylog2/streams/StreamRouterEngine.java, graylog2-server/src/main/resources/prometheus-exporter.yml, graylog2-server/src/test/java/org/graylog2/streams/StreamRouterEngineTest.java
Backport https://github.com/Graylog2/graylog2-server/pull/14409 to 4.3.
=> Reduce logging and add metric for stream warning (4.3)

graylog2-server/src/main/java/org/graylog/scheduler/clock/JobSchedulerClock.java, graylog2-server/src/main/java/org/graylog/scheduler/clock/JobSchedulerSystemClock.java, graylog2-server/src/main/java/org/graylog2/indexer/TestIndexSet.java, graylog2-server/src/main/java/org/graylog2/indexer/retention/strategies/AbstractIndexRetentionStrategy.java, graylog2-server/src/main/java/org/graylog2/indexer/retention/strategies/ClosingRetentionStrategy.java, graylog2-server/src/main/java/org/graylog2/indexer/retention/strategies/DeletionRetentionStrategy.java, graylog2-server/src/main/java/org/graylog2/indexer/retention/strategies/NoopRetentionStrategy.java, graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingStrategy.java, graylog2-server/src/test/java/org/graylog/events/JobSchedulerTestClock.java, graylog2-server/src/test/java/org/graylog2/indexer/retention/strategies/AbstractIndexRetentionStrategyTest.java, graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingRotationAndRetentionTest.java, graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingStrategyTest.java
This test creates indices, forwards the clock,
calls the rotations and retentions and asserts that the list of open indices gets modified accordingly.
Use the JobSchedulerClock which can be used forward the time. Extend the JobSchedulerClock to support java.time Instant and ZonedDateTime.
/nocl
=> Add TimeBasedSizeOptimizingRotationAndRetentionTest

graylog2-web-interface/src/views/components/aggregationwizard/FieldSelect.tsx
_Please note, this is a backport of #14418 for 5.0_
This PR is fixing a styling problem in the fields select in the aggregations builder.
Before:
After:
The styling / scrolling behaviour is now similar to 4.3.
/nocl
=> Fix line break in field select options. (Backport of #14418 for 5.0)

graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexSetValidator.java, graylog2-server/src/main/java/org/graylog2/indexer/retention/strategies/AbstractIndexRetentionStrategy.java, graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/AbstractRotationStrategy.java, graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingStrategy.java, graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingStrategyConfig.java, graylog2-server/src/test/java/org/graylog2/configuration/ElasticsearchConfigurationTest.java, graylog2-server/src/test/java/org/graylog2/indexer/retention/strategies/AbstractIndexRetentionStrategyTest.java, graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingRotationAndRetentionTest.java, graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingStrategyTest.java
While the default should be good enough,
add a new config option:
`time_size_optimizing_rotation_period = 1d`
`time_size_optimizing_rotation_min_size = 20gb`
`time_size_optimizing_rotation_max_size = 50gb`
We also convert `java.time.Period` back to `org.joda.time.Period` since it allows smaller durations
which is helpful for testing and needs less conversions
/nocl
=> Make the rotation period and sizes customizable

graylog2-server/src/main/java/org/graylog2/bindings/PersistenceServicesBindings.java, graylog2-server/src/main/java/org/graylog2/rest/resources/RestResourcesModule.java, graylog2-server/src/main/java/org/graylog2/rest/resources/entities/preferences/EntityListPreferencesResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/entities/preferences/model/EntityListPreferences.java, graylog2-server/src/main/java/org/graylog2/rest/resources/entities/preferences/model/StoredEntityListPreferences.java, graylog2-server/src/main/java/org/graylog2/rest/resources/entities/preferences/model/StoredEntityListPreferencesId.java, graylog2-server/src/main/java/org/graylog2/rest/resources/entities/preferences/service/EntityListPreferencesService.java, graylog2-server/src/main/java/org/graylog2/rest/resources/entities/preferences/service/InMemoryEntityListPreferencesService.java
Entity list preferences resource, so that FE can save preferences per user/entity list type pair.
The decisions about exact storage method have not been made yet - resource uses in-memory storage for now.
The decisions about exact schema of preferences have not been made yet - EntityListPreferences class will be almost for sure a subject of change in the future.
/nocl
Provide alpha version of resource for the FE to allow FE development in the preferences area and provide some first feedback for decision making process.
=> Entity list preferences resource, part 1: inmemory storage and retrieval

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/IndicesAdapterOS2.java, graylog2-server/src/main/java/org/graylog2/indexer/SetIndexReadOnlyJob.java, graylog2-server/src/main/java/org/graylog2/indexer/retention/strategies/AbstractIndexRetentionStrategy.java, graylog2-server/src/test/java/org/graylog2/indexer/retention/strategies/AbstractIndexRetentionStrategyTest.java, graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingRotationAndRetentionTest.java
After the index rotation, we asynchronously start the
`SetIndexReadOnlyJob`, which will flush the index, set the index read only and
then set the closing Date.
This means that there is a time frame, where we can have rotated indices
that still haven't received their closing Date.
The retention strategy would falsely assume that it is missing and
fallback to using the creation date.
Avoid this by fetching the `IndicesBlockStatus` and use it to filter
only indices that are read only ("index.blocks.write")
Add a test for the backwards compatible retention without a closing date.
/nocl
=> Retention improvements

graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexSetValidator.java, graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingStrategy.java, graylog2-server/src/test/java/org/graylog2/indexer/IndexSetValidatorTest.java, graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingRotationAndRetentionTest.java
- Add validation for minimum required leeway
index_liftime_soft == index_liftime_hard would result in a leeway of 0.
Having a leeway of zero means that we effectivly cannot store any data
in the index. We cannot meet both requirements: the minimum retention 
(soft) and the maximum retention (hard) would contradict each other.
- Don't add rotation period to leeway computation
This was a mistake made earlier, when I was still under the assumption
that a leeway of zero is a valid possible configuration.
/nocl
=> Fix rotation leeway computation

changelog/unreleased/issue-14404.toml, graylog2-web-interface/src/views/components/WidgetComponent.tsx, graylog2-web-interface/src/views/components/WidgetGrid.tsx, graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.groupBy.test.tsx, graylog2-web-interface/src/views/components/aggregationwizard/grouping/configuration/FieldComponent.tsx, graylog2-web-interface/src/views/components/widgets/Widget.aggregations.test.tsx, graylog2-web-interface/src/views/components/widgets/Widget.test.tsx, graylog2-web-interface/src/views/components/widgets/Widget.tsx
_Please note, this PR requires a backport for 4.2, 4.3 and 5.0._
As described in #14404 an error can occur when creating a grouping for a field which only exists in the following streams: `All Events`, `All System Events` or `Processing and Indexing Failures`.
The error occurred because the field type only exists in the fields list of the current query, but the code implemented in the list for all field types, where the field type is not part of. That the field is not part of this list is correct, please have a look at https://github.com/Graylog2/graylog2-server/pull/11405 for more information.
=> Fix grouping in aggregation builder for fields which only exist in event streams.

graylog2-server/src/main/java/org/graylog2/audit/AuditActor.java, graylog2-server/src/main/java/org/graylog2/audit/jersey/ResponseEntityConverter.java, graylog2-server/src/main/java/org/graylog2/rest/bulk/BulkExecutor.java, graylog2-server/src/test/java/org/graylog2/audit/jersey/ResponseEntityConverterTest.java, graylog2-server/src/test/java/org/graylog2/rest/bulk/BulkExecutorTest.java
ResponseEntityConverter is moved to graylog2-server so that it can be reused in both modules.
Unknown username for Audit Log purposes is made a constant instead of magic string.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#4626
/nocl
=> Refactoring around audit log codebase

graylog2-server/src/main/java/org/graylog/events/rest/EventDefinitionsResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java, graylog2-server/src/main/java/org/graylog2/rest/bulk/SequentialBulkExecutor.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java, graylog2-server/src/test/java/org/graylog2/rest/bulk/SequentialBulkExecutorTest.java
Response code changes in bulk removal, as requested by FE
/nocl
FE wants 400 response code for general errors related to the whole bulk removal.
FE wants 200 response code even if some/all entities in the bulk were not removed successfully. "Failures" part is used by FE to provide detailed notification if needed.
Manually and with changed unit tests.
=> Response code changes in bulk removal, as requested by FE

changelog/unreleased/issue-14404.toml, graylog2-web-interface/src/views/components/WidgetComponent.tsx, graylog2-web-interface/src/views/components/WidgetGrid.tsx, graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.groupBy.test.tsx, graylog2-web-interface/src/views/components/aggregationwizard/grouping/configuration/FieldComponent.tsx, graylog2-web-interface/src/views/components/widgets/Widget.aggregations.test.tsx, graylog2-web-interface/src/views/components/widgets/Widget.test.tsx, graylog2-web-interface/src/views/components/widgets/Widget.tsx
_Please note, this is a backport of https://github.com/Graylog2/graylog2-server/pull/14387 for 5.0_
As described in #14404 an error can occur when creating a grouping for a field which only exists in the following streams: `All Events`, `All System Events` or `Processing and Indexing Failures`.
The error occurred because the field type only exists in the fields list of the current query, but the code implemented in the list for all field types, where the field type is not part of. That the field is not part of this list is correct, please have a look at https://github.com/Graylog2/graylog2-server/pull/11405 for more information.
=> Fix grouping in aggregation builder for fields which only exist in event streams. (`5.0`)

graylog2-web-interface/src/components/streams/StreamsOverview/BulkActions.test.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/BulkActions.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/StreamsOverview.test.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/StreamsOverview.tsx, graylog2-web-interface/src/routing/ApiRoutes.ts
This PR is implementing the new API endpoint for stream bulk delete which we added with https://github.com/Graylog2/graylog2-server/pull/14476.
Fixes https://github.com/Graylog2/graylog2-server/issues/14013
/nocl
=> FE: Make use of new API endpoint for stream bulk delete.

changelog/unreleased/issue-14404.toml, graylog2-web-interface/src/views/components/WidgetComponent.tsx, graylog2-web-interface/src/views/components/WidgetGrid.tsx, graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.groupBy.test.tsx, graylog2-web-interface/src/views/components/aggregationwizard/grouping/configuration/FieldComponent.tsx, graylog2-web-interface/src/views/components/widgets/Widget.aggregations.test.tsx, graylog2-web-interface/src/views/components/widgets/Widget.test.tsx, graylog2-web-interface/src/views/components/widgets/Widget.tsx
_Please note, this is a backport of https://github.com/Graylog2/graylog2-server/pull/14387 for 4.3_
As described in #14404 an error can occur when creating a grouping for a field which only exists in the following streams: `All Events`, `All System Events` or `Processing and Indexing Failures`.
The error occurred because the field type only exists in the fields list of the current query, but the code implemented in the list for all field types, where the field type is not part of. That the field is not part of this list is correct, please have a look at https://github.com/Graylog2/graylog2-server/pull/11405 for more information.
=> Fix grouping in aggregation builder for fields which only exist in event streams. (`4.3`)

changelog/unreleased/pr-14575.toml, graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/KeywordSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/RelativeSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/SearchResource.java
The offset parameter was not used at all any more. This PR fixes it.
fixes #14571 
Manual testing via the API browser.
=> Fixing missing offset handling in Legacy Searches

changelog/unreleased/pr-14575.toml, graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/KeywordSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/RelativeSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/SearchResource.java
The offset parameter was not used at all any more. This PR fixes it.
**backport from #14575** 
Manual testing via the API browser.
=> Fixing missing offset handling in Legacy Searches (Backport to 4.3)

changelog/unreleased/pr-14575.toml, graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/KeywordSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/RelativeSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/SearchResource.java
The offset parameter was not used at all any more. This PR fixes it.
**backport from https://github.com/Graylog2/graylog2-server/pull/14575**
Manual testing via the API browser.
=> Fixing missing offset handling in Legacy Searches (backport to 5.0)

graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java, graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingStrategy.java, graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingRotationAndRetentionTest.java, graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingStrategyTest.java
The optimal index size needs to take into account how many shards have been configured.
Thus we change the size definition from per index to per shard:
`time_size_optimizing_rotation_min_size` -> `time_size_optimizing_rotation_min_shard_size`
/nocl
=> Optimum index size should be based on shards

graylog2-server/src/main/java/org/graylog2/rest/resources/entities/preferences/EntityListPreferencesResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/entities/preferences/model/SingleFieldSortPreferences.java, graylog2-server/src/main/java/org/graylog2/rest/resources/entities/preferences/model/SortPreferences.java, graylog2-server/src/test/java/org/graylog2/rest/resources/entities/preferences/service/EntityListPreferencesServiceImplTest.java
Sorting can be persisted in Entity List preferences.
Two additional micro-changes have been added:
1. Sorting order uses enum (as requested by Tomas).
2. If entity list preference is not present, return 204 (No Content) instead of 404 (Not found).
/nocl
Needed by FE.
=> Sorting can be persisted in Entity List preferences

graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java, graylog2-server/src/main/java/org/graylog2/rest/resources/entities/preferences/listeners/EntityListPreferencesCleanerOnUserDeletion.java, graylog2-server/src/main/java/org/graylog2/rest/resources/entities/preferences/model/StoredEntityListPreferencesId.java, graylog2-server/src/main/java/org/graylog2/rest/resources/entities/preferences/service/EntityListPreferencesService.java, graylog2-server/src/main/java/org/graylog2/rest/resources/entities/preferences/service/EntityListPreferencesServiceImpl.java, graylog2-server/src/main/java/org/graylog2/users/UserManagementServiceImpl.java, graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java, graylog2-server/src/test/java/org/graylog2/rest/resources/entities/preferences/listeners/EntityListPreferencesCleanerOnUserDeletionTest.java, graylog2-server/src/test/java/org/graylog2/users/UserServiceImplTest.java
Preferences removal on user removal.
/nocl
When user is gone, his/her entity list preferences need to be removed as well.
Manually.
Existing tests have been adapted to test that part as well.
=> Preferences removal on user removal

graylog2-server/src/main/java/org/graylog/plugins/views/favorites/FavoritesService.java, graylog2-server/src/main/java/org/graylog/plugins/views/startpage/lastOpened/LastOpenedService.java, graylog2-server/src/main/java/org/graylog/plugins/views/startpage/recentActivities/RecentActivityService.java, graylog2-server/src/main/java/org/graylog/plugins/views/startpage/recentActivities/RecentActivityUpdatesListener.java, graylog2-server/src/test/java/org/graylog/plugins/views/favorites/FavoriteServiceTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/startpage/StartPageServiceTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/startpage/lastOpened/LastOpenedServiceTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/startpage/recentActivities/RecentActivityServiceTest.java
When an entity is deleted, preceding events in Recent Activity can no longer be displayed correctly and are removed now.
Also, deleted entities can no longer be a favorite or in the Last Opened list.
If a user is deleted, the Favorite & Last Opened collections for this user get removed, too.
/nocl
fixes https://github.com/Graylog2/graylog2-server/issues/14553 
fixes https://github.com/Graylog2/graylog2-server/issues/14403
cleanup
manual testing, TODO: create tests
=> StartPage, cleanup/removal of collection items after entity deletion

changelog/unreleased/issue-14428.toml, graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java, graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java
https://ciphersuite.info/cs/TLS_RSA_WITH_AES_128_GCM_SHA256/
https://ciphersuite.info/cs/TLS_RSA_WITH_AES_256_GCM_SHA384/
This causes no change in the compatibility test when using `testssl.sh`
```
Running client simulations (HTTP) via sockets 
Android 6.0                  TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256, 256 bit ECDH (P-256)
Android 7.0 (native)         TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 256 bit ECDH (P-256)
Android 8.1 (native)         TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 253 bit ECDH (X25519)
Android 9.0 (native)         TLSv1.3 TLS_AES_256_GCM_SHA384, 253 bit ECDH (X25519)
Android 10.0 (native)        TLSv1.3 TLS_AES_256_GCM_SHA384, 253 bit ECDH (X25519)
Android 11 (native)          TLSv1.3 TLS_AES_256_GCM_SHA384, 253 bit ECDH (X25519)
Android 12 (native)          TLSv1.3 …
```
=> Disable more weak TLS ciphers by default

graylog2-web-interface/src/hooks/usePaginationQueryParameter.test.ts, graylog2-web-interface/src/hooks/usePaginationQueryParameter.ts
It is currently possible (in the development version) that the page size URL query param is `NaN`. If you go to the streams overview and you execute a search, the URL query params look like this `?page=1&pageSize=NaN`. This PR is fixing the behaviour.
/nocl
=> Enusure URL query param for page size is never NAN.

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
Views resolved by a View Resolver (e.g. Security Views) should not create an entry in Last Opened. 
Because these entities are not really anchored in the Catalog yet, and the way to do it needs discussion.
/nocl
=> Don't add a LastOpenedEntry for Security Views

graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java, graylog2-server/src/main/java/org/graylog2/shared/rest/OptionalResponseFilter.java, graylog2-server/src/test/java/org/graylog2/shared/rest/OptionalResponseFilterTest.java
204 (No content) status is returned on empty Optionals in REST.
/nocl
So far 200(OK) was returned when endpoint returned empty Optional.
Imho 204 is much more appropriate status code for that situation.
Manually and with new unit test.
=> 204 (No content) is returned on empty Optionals

graylog2-web-interface/src/views/components/WidgetComponent.tsx, graylog2-web-interface/src/views/components/WidgetGrid.test.tsx, graylog2-web-interface/src/views/components/WidgetGrid.tsx
Prior to this PR, a race condition existed that resulted in wrong widget dimensions being used after switching dashboard tabs.
This change is now extracting widgets and positions directly from the `ViewStore`, to avoid race conditions when the `activeQuery` is changed, but the changed widgets/positions have not been propagated to other stores yet.
Fixes #14478.
/nocl
=> Retrieving widgets/positions from `ViewStore` to avoid race condition.

graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java, graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingStrategy.java, graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingStrategyConfig.java, graylog2-server/src/main/java/org/graylog2/migrations/MaintenanceStrategiesHelper.java, graylog2-server/src/test/java/org/graylog2/configuration/ElasticsearchConfigurationTest.java, misc/graylog.conf
And make the default values configurable via server.conf
/nocl
=> Make "time-size-optimzing" the new default rotation strategy

graylog2-server/src/main/java/org/graylog2/inputs/misc/jsonpath/JsonPathInput.java, graylog2-server/src/main/java/org/graylog2/inputs/random/FakeHttpMessageInput.java, graylog2-server/src/main/java/org/graylog2/plugin/inputs/MessageInput.java
* Make inputs *not* cloud compatible by default
* Enable JSON Path Input in cloud
* Enable Random HTTP Input in cloud
/nocl
=> Enable first inputs for cloud usage

graylog-project-parent/pom.xml, pom.xml
Fixes an issue in development when two different netty-tcnative versions are present in the classpath. The change also ensures that we use consistent Netty versions across all transitive dependencies.
Fixes #14602
Obsoletes https://github.com/Graylog2/graylog-plugin-enterprise-integrations/pull/991
/nocl
=> Move managed Netty dependencies to top level pom.xml

.github/workflows/fix-linter-hints.yml
This PR is extending the "Fix linter hints" workflow in a way that it is running `mvn compile` before running the linter. This way, the backend API types are generated before linting, allowing the linter to pick them up and e.g. reflect their priority in the order of imports correctly.
/nocl
=> Running build before linting.

changelog/unreleased/issue-6527.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/NormalizeFields.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/normalizeFields.txt
Adds a `normalize_fields()` function for pipeline rules.
This function will convert all message field names to lower case. 
closes #6527
Tested in pipeline rule for messages with mixed case fields.
Unit tests provided.
=> Add normalize function

.github/workflows/fix-linter-hints.yml
In #14630 we added an additional step to run a build before linting. For this, we scoped individual steps to subdirectories. Unfortunately, we left in the default workdir, leading to errors when running `run` steps before the checkout.
This change is now removing the default workdir for steps.
/nocl
=> Removing default workdir for linter job.

graylog2-server/src/main/java/org/graylog2/database/filtering/DbFilterParser.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java, graylog2-server/src/main/java/org/graylog2/search/SearchQuery.java, graylog2-server/src/main/java/org/graylog2/streams/PaginatedStreamService.java, graylog2-server/src/test/java/org/graylog2/database/filtering/DbFilterParserTest.java
Stream pagination extended with simple filter expressions.
For now, single-value filters are supported. More complex filters, as well as possible refactoring, will come in next PRs.
Implements basic BE part for issue #13852
/nocl
FE needs a way to use filters created by users in Entity List to restrict results obtained from DB.
Unit tests have been added.
=> Stream pagination extended with simple filter expressions

graylog2-server/src/main/java/org/graylog/events/processor/EventProcessorEngine.java, graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessor.java, graylog2-server/src/main/java/org/graylog/events/processor/aggregation/PivotAggregationSearch.java, graylog2-server/src/test/java/org/graylog/events/processor/aggregation/AggregationEventProcessorTest.java
Resolves #14375 
/nocl
Catch exceptions related to invalid grouping and rethrow with a more actionable message.
=> Better messaging for grouping errors

changelog/unreleased/pr-14692.toml, graylog2-web-interface/src/views/logic/queries/QueryHelper.test.ts, graylog2-web-interface/src/views/logic/queries/QueryHelper.ts
**Note:** This needs a backport to `5.0`.
Prior to this change, when a field value contains one or more `$` and the `Add to query`/`Exclude from results` value action were used, the `$` were not escaped. This could lead to parts of the query being mistaken as a parameter erroneously.
This change is now making sure that `$` as part of the value are escaped.
=> Quote $ when escaping field values.

changelog/unreleased/pr-14692.toml, graylog2-web-interface/src/views/logic/queries/QueryHelper.test.ts, graylog2-web-interface/src/views/logic/queries/QueryHelper.ts
_Please note, this is a backport of #14692 for 5.0_
Prior to this change, when a field value contains one or more `$` and the `Add to query`/`Exclude from results` value action were used, the `$` were not escaped. This could lead to parts of the query being mistaken as a parameter erroneously.
This change is now making sure that `$` as part of the value are escaped.
=> Quote $ when escaping field values. (backport of #14692 for 5.0)

changelog/unreleased/pr-14692.toml, graylog2-web-interface/src/views/logic/queries/QueryHelper.test.ts, graylog2-web-interface/src/views/logic/queries/QueryHelper.ts
_Please note, this is a backport of #14692 for 4.3_
Prior to this change, when a field value contains one or more `$` and the `Add to query`/`Exclude from results` value action were used, the `$` were not escaped. This could lead to parts of the query being mistaken as a parameter erroneously.
This change is now making sure that `$` as part of the value are escaped.
=> Quote $ when escaping field values. (backport of #14692 for 4.3)

graylog2-web-interface/src/views/components/searchbar/saved-search/SearchActionsMenu.tsx, graylog2-web-interface/src/views/components/views/ViewHeader.tsx, graylog2-web-interface/src/views/logic/slices/viewSlice.ts, graylog2-web-interface/src/views/logic/views/OnSaveNewDashboard.ts, graylog2-web-interface/src/views/logic/views/OnSaveViewAction.ts
Prior to this PR, in some cases updating the view did not result insetting the `dirty` flag. This change is fixing that by clearly separating actions for:
- loading a view initially (`loadView`)
- updating a previously loaded view (`updateView`)
the latter is now setting the dirty flag.
/nocl
=> Fixup handling of dirty flag for views.

changelog/unreleased/issue-14164.toml, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/cat/AliasSummaryResponse.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/cat/CatApi.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/cat/IndexSummaryResponse.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7Test.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/ClusterAdapterOS2.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/cat/AliasSummaryResponse.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/cat/CatApi.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/cat/IndexSummaryResponse.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/ClusterAdapterOS2Test.java, graylog2-server/src/main/java/org/graylog2/indexer/cluster/Cluster.java, graylog2-server/src/main/java/org/graylog2/indexer/cluster/ClusterAdapter.java, graylog2-server/src/test/java/org/graylog2/indexer/cluster/ClusterIT.java
**Note:** This is a backport of #14177 to `5.0`.
Prior to this change, retrieving the cluster/deflector health relied on Elasticsearch/Opensearch endpoints taking a list of indices as a query parameter and we passed e.g. the list of all existing index wildcards to this. This can lead to a request being generated that has a query string that is too big, if a high number of index sets exist, as seen in #14164.
Unfortunately, there are no endpoints for this taking the list of indices outside of a query parameter. Therefore this PR is now doing two things to fix this:
- General cluster health is retrieved with the generic cluster health endpoint without passing index names. This returns a health status (red, yellow, green) in the same way, but is not specific to the indices used by Graylog.
- …
=> Avoiding `GET` APIs for cluster/deflector health. (`5.0`)

changelog/unreleased/pr-14654.toml, graylog2-web-interface/src/views/components/datatable/Headers.tsx
**Note:** This also needs a backport to `5.0`.
This small change is hiding the sort/pin icons in the data table component when the current context is a non-interactive one, so they do not show up e.g. in reports.
=> Do not show sort/pin icons in data table when non-interactive.

graylog2-server/src/main/java/org/graylog/events/contentpack/entities/EventDefinitionEntity.java, graylog2-server/src/main/java/org/graylog/events/processor/DBEventDefinitionService.java, graylog2-server/src/main/java/org/graylog/events/processor/EventDefinition.java, graylog2-server/src/main/java/org/graylog/events/processor/EventDefinitionDto.java, graylog2-server/src/main/java/org/graylog2/database/entities/ScopedDbService.java
Event definitions store last update time.
Service storing event definitions ensures that proper date is stored in "updated_at" field of "event_definitions" collection.
/nocl
It is required by FE to proceed with changes related to "Basic Alerting Integration" topic.
Manually.
=> Event definitions store last update time

graylog2-web-interface/src/components/configurationforms/ConfigurationForm.jsx, graylog2-web-interface/src/components/configurationforms/ConfigurationForm.test.tsx
This PR is fixing the bug described in https://github.com/Graylog2/graylog2-server/issues/14619. We are now closing the `ConfigurationForm` modal on save. The component is being used for the input configuration.
Fixes https://github.com/Graylog2/graylog2-server/issues/14619
/nocl
=> Close `ConfigurationForm` modal on save.

changelog/unreleased/pr-14654.toml, graylog2-web-interface/src/views/components/datatable/Headers.tsx
This small change is hiding the sort/pin icons in the data table component when the current context is a non-interactive one, so they do not show up e.g. in reports.
=> Do not show sort/pin icons in data table when non-interactive. (`5.0`)

graylog2-web-interface/src/views/components/DashboardActionsMenu.tsx
In #14707, editing metadata for a saved search was changed in a way that it does not automatically persist changes and instead relies on the saved search being saved afterwards.
This PR is doing the same for dashboards, fixing an issue where changing the view title through "Edit Metadata" is now reflected correctly afterwards.
/nocl
=> Fixing editing metadata for dashboards.

changelog/unreleased/pr-14720.toml, graylog2-web-interface/src/views/stores/RefreshStore.ts
**Note:** This needs a backport to `5.0`.
This tiny PR is changing the default interval for the auto-refresh from one second to five seconds. Many users are used to implicitly using the default interval which is chosen when a user clicks on the play button without explicitly selecting an interval. A one second interval might be too aggressive, causing too many searches to be executed. For long time ranges it might even cause long-running searches to pile up.
This is a low-hanging fruit, aiming to improve the situation. A follow-up will include making sure that no searches are executed when an existing search is still running.
Fixes Graylog2/graylog-plugin-enterprise#4567.
=> Changing default refresh interval to five seconds.

graylog2-server/src/main/java/org/graylog2/migrations/V20230113095300_MigrateGlobalPivotLimitsToGroupingsInViews.java, graylog2-server/src/main/java/org/graylog2/migrations/V20230113095301_MigrateGlobalPivotLimitsToGroupingsInSearches.java
This change adds a missing return statement when checking if the migration had already run. 
Before the change, it checked for an existing run but did not skip execution and ran again.
This creates no problems but additional runs are still unwanted/unnecessary.
/nocl
=> Add missing return statement in Migration for Aggregations/Pivots

changelog/unreleased/pr-14723.toml, graylog2-web-interface/src/views/components/Search.tsx, graylog2-web-interface/src/views/components/searchbar/RefreshControls.test.tsx, graylog2-web-interface/src/views/components/searchbar/RefreshControls.tsx, graylog2-web-interface/src/views/components/searchbar/useRefreshConfig.ts, graylog2-web-interface/src/views/stores/RefreshStore.test.ts, graylog2-web-interface/src/views/stores/RefreshStore.ts
**Note:** This needs a backport to `5.0`.
This PR is changing the auto-refresh logic in a way that the next auto-refresh will be scheduled when the most recent one has completed.  This avoids the scenario that when the time a search execution takes exceeds the auto-refresh interval, that new search executions are triggered while there are still one or more in progress, leading to piling up search executions needlessly.
Fixes Graylog2/graylog-plugin-enterprise#3642.
=> Scheduling next search refresh only after current one completed.

changelog/unreleased/pr-14688.toml, graylog2-web-interface/supportedBrowsers.js, graylog2-web-interface/webpack.config.js
**Note:** This needs a backport to `5.0`.
This change is extending our browser support to go back to Chrome 68 in order to support outdated browser versions commonly found e.g. on smart TVs. The cut is made at Chrome 67 in order to support at least the [last three versions of webOS](https://webostv.developer.lge.com/develop/specifications/web-api-and-web-engine).
Fixes #14677.
=> Extend browser support back to Chrome 68.

graylog2-web-interface/src/views/logic/slices/viewSlice.ts
Prior to this PR, removing a dashboard page was done in the following order:
- remove the corresponding view state
- switch the active query
This could lead to widgets being loaded for the previous active query after it has been removed and before a new active query is selected, resulting in an exception.
This PR is now making sure that a new active query is selected before the removal of the current one.
/nocl
=> Selecting new dashboard page before removing current one.

changelog/unreleased/pr-14720.toml, graylog2-web-interface/src/views/stores/RefreshStore.ts
**Note:** This is a backport of #14720 to `5.0`.
This tiny PR is changing the default interval for the auto-refresh from one second to five seconds. Many users are used to implicitly using the default interval which is chosen when a user clicks on the play button without explicitly selecting an interval. A one second interval might be too aggressive, causing too many searches to be executed. For long time ranges it might even cause long-running searches to pile up.
This is a low-hanging fruit, aiming to improve the situation. A follow-up will include making sure that no searches are executed when an existing search is still running.
Fixes Graylog2/graylog-plugin-enterprise#4567.
=> Changing default refresh interval to five seconds. (`5.0`)

changelog/unreleased/pr-14745.toml, graylog2-web-interface/packages/babel-preset-graylog/index.js, graylog2-web-interface/webpack.config.js
This change is extending our browser support to go back to Chrome 68 in order to support outdated browser versions commonly found e.g. on smart TVs. The cut is made at Chrome 68 in order to support at least the [last three version of webOS](https://webostv.developer.lge.com/develop/specifications/web-api-and-web-engine).
Fixes #14677.
=> Extend browser support back to Chrome 68. (`5.0`)

graylog2-web-interface/src/views/Constants.ts, graylog2-web-interface/src/views/components/datatable/Headers.tsx, graylog2-web-interface/src/views/components/widgets/MessageTable.tsx
With this PR we are unifying the height of the data table and message table header.
Before:
After:
/nocl
=> Unify height of data table and message table header.

graylog2-web-interface/src/components/common/DataTable/DataTable.jsx, graylog2-web-interface/src/components/common/NoEntitiesExist.tsx, graylog2-web-interface/src/components/common/NoSearchResult.tsx, graylog2-web-interface/src/components/content-packs/ContentPacksList.jsx, graylog2-web-interface/src/components/grok-patterns/GrokPatterns.jsx, graylog2-web-interface/src/components/pipelines/ProcessingTimelineComponent.tsx, graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchesList.tsx
This PR is a follow-up for https://github.com/Graylog2/graylog2-server/pull/13683. It is improving the alerts we show if an overview does not contain an entity.
We are showing two different alerts. One in case no entities exists on the system an one i case no entites exists for the currently applied filter.
Before:
After:
/nocl
=> Improve "no entities found" alters for entity overviews.

graylog2-web-interface/src/components/common/EntityDataTable/ColumnsVisibilitySelect.tsx, graylog2-web-interface/src/components/common/EntityDataTable/EntityDataTable.test.tsx, graylog2-web-interface/src/components/common/EntityDataTable/EntityDataTable.tsx, graylog2-web-interface/src/components/common/PageSizeSelect.tsx, graylog2-web-interface/src/components/common/PaginatedList.test.tsx, graylog2-web-interface/src/components/common/PaginatedList.tsx, graylog2-web-interface/src/components/content-packs/ContentPacksList.jsx, graylog2-web-interface/src/components/permissions/GranteesList.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/StreamsOverview.tsx, graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardsOverview.tsx, graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchesList.tsx
With this PR we are changing the way we display the page size select for entity data tables.
Before:
After:
We are now grouping the elements which allow configuring the table layout. Changing the element of the page size select from an input to a button also effects all other places where we use the page size select component. We could create a new component for the entity data table, but I see a benefit in unifying the styles.
/nocl
=> Integrate page size select in entity data table.

changelog/unreleased/pr-14768.toml, pom.xml
Upgrade json-path 2.7.0. Implicitly this also upgrades json-smart to 2.4.7.
json-path is mainly used in testing, as well as JSONpath Codec and HTTPJsonPath data adapter.
Resolves Graylog2/graylog-plugin-enterprise#3674
=> Bump version of json-path to 2.7.0

graylog2-server/src/main/java/org/graylog2/lookup/adapters/CSVFileDataAdapter.java
Small fix for mistake in https://github.com/Graylog2/graylog2-server/pull/14670. I had intended to import the Apache `StringUtils` instead of the version from Cronutils. The same fix is already added to the corresponding backports.
/nocl
=> Fix CSV adapter StringUtils import

graylog2-web-interface/src/views/components/contexts/WidgetFocusContext.tsx, graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.test.tsx, graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.tsx
This change is preventing one unneeded search execution when starting a new search. It is caused by the widget focus provider which compares the current focus state (which is initially `undefined`) with the next one when syncing with query parameters. At this point, the next one can also be `{ editing: false, focusing: false, id: undefined }`, what is semantically identical, but not equal to `undefined`, causing a state change.
Therefore, this change is now making sure that if the current focus state is `undefined`, the initial object `{ editing: false, focusing: false, id: undefined }` will be used for the equality check instead.
/nocl
=> Prevent unneeded search execution when opening new search.

changelog/unreleased/pr-14723.toml, graylog2-web-interface/src/views/components/searchbar/RefreshControls.test.tsx, graylog2-web-interface/src/views/components/searchbar/RefreshControls.tsx, graylog2-web-interface/src/views/components/searchbar/useRefreshConfig.ts, graylog2-web-interface/src/views/pages/ShowDashboardInBigDisplayMode.test.tsx, graylog2-web-interface/src/views/stores/RefreshStore.ts
**Note:** This is a backport of #14723 to `5.0`.
This PR is changing the auto-refresh logic in a way that the next auto-refresh will be scheduled when the most recent one has completed.  This avoids the scenario that when the time a search execution takes exceeds the auto-refresh interval, that new search executions are triggered while there are still one or more in progress, leading to piling up search executions needlessly.
Fixes Graylog2/graylog-plugin-enterprise#3642.
=> Scheduling next search refresh only after current one completed. (`5.0`)

changelog/unreleased/issue-14787.toml, graylog2-web-interface/src/views/components/aggregationwizard/ElementConfigurationContainer.tsx
_Please note, this PR needs a backport for 5.0_
As described in https://github.com/Graylog2/graylog2-server/issues/14787 we do no display fields with long names well in the aggregation grouping configuration.
Before:
After:
Fixes https://github.com/Graylog2/graylog2-server/issues/14787
=> Fix the way we display long field names in aggregation grouping configuration.

changelog/unreleased/issue-14787.toml, graylog2-web-interface/src/views/components/aggregationwizard/ElementConfigurationContainer.tsx
**Note:** This is a backport of #14789 to `5.0`.
As described in https://github.com/Graylog2/graylog2-server/issues/14787 we do no display fields with long names well in the aggregation grouping configuration.
Before:
After:
Fixes #14787.
=> Fix the way we display long field names in aggregation grouping configuration. (`5.0`)

graylog2-server/src/main/java/org/graylog2/inputs/InputService.java, graylog2-server/src/main/java/org/graylog2/inputs/InputServiceImpl.java, graylog2-server/src/test/java/org/graylog2/inputs/InputServiceImplTest.java
A new method `InputService#allByType` has been added in https://github.com/Graylog2/graylog2-server/pull/14515 after implementing support for encrypted values has been started in #14459. Thus, the new method was not covered in  #14459 and now doesn't return encrypted values as expected.
This PR fixes this.
Also, I added a default implementation to the `InputSerfvice` interface so that other implementations don't break.
/nocl
=> Support encrypted values in new method InputService#allByType

graylog2-server/src/main/java/org/graylog2/inputs/InputService.java
Add default `InputService.allByType()` method to allow backwards-compatibility. Existing implementations of InputService will not need to define the method.
Backports the default method portion from the original implementation in https://github.com/Graylog2/graylog2-server/pull/14804.
/nocl
The original introduction of the `InputService.findByType()` method in https://github.com/Graylog2/graylog2-server/pull/14671 was not backwards-compatible. Such breaking API changes should be avoided in minor bug fix releases. This change assures backwards-compatibility and does not break existing usages of the `InputService` (such as the Forwarder, for example).
- Verified that the existing usage of the method in `AzureCheckpointStoreCleanupService` continues to function correctly. 
- Checked out this …
=> Add default InputService.allByType() method (5.0)

graylog2-web-interface/src/components/common/PaginatedList.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/StreamsOverview.tsx, graylog2-web-interface/src/hooks/usePaginationQueryParameter.test.ts, graylog2-web-interface/src/hooks/usePaginationQueryParameter.ts, graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardsOverview.tsx
Before this change there was a problem with the pagination on the streams and dashboards overview.
To reproduce the problem you need:
- 15 entities
- an initial page size of 10, when you open the page
- change the page size to 50
- change the page size to 10
Now you will no longer see the pagination. We mainly make sure `usePaginationQueryParameter` is returning the correct page size and we also no longer sync the page size with the URL since it is saved as a user setting.
Longterm we should change the way we maintain the currently selected page and page size.
/nocl
=> Fix page size handling for dashboards and streams overview.

changelog/unreleased/pr-14805.toml, graylog2-web-interface/src/components/bootstrap/Table.jsx, graylog2-web-interface/src/views/components/datatable/MessagesTable.tsx
**Note:** This PR requires a backport to `5.0`.
This PR is changing the layout of table headers/cells for print media to add a) word breaks and b) remove existing min widths. This is supposed to prevent any scrollbars showing up for print media, so no columns are hidden because they are overflowing the container.
Fixes Graylog2/graylog-plugin-enterprise#4761.
=> Adding word wrap for header columns of tables in print.

changelog/unreleased/pr-14805.toml, changelog/unreleased/pr-14822.toml, graylog2-web-interface/src/components/bootstrap/Table.jsx, graylog2-web-interface/src/views/components/datatable/MessagesTable.tsx
**Note:** This is a backport of #14805 to `5.0`.
This PR is changing the layout of table headers/cells for print media to add a) word breaks and b) remove existing min widths. This is supposed to prevent any scrollbars showing up for print media, so no columns are hidden because they are overflowing the container.
Fixes Graylog2/graylog-plugin-enterprise#4761.
=> Adding word wrap for header columns of tables in print. (`5.0`)

changelog/unreleased/issue-13596.toml, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/series/ESLatestHandler.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/pivot/series/OSLatestHandler.java
**Note:** This PR requires a backport to `5.0`.
Prior to this change, the `latest(field)` metric did assume that `field` is present in all documents of the result, otherwise it returns `N/A`.  This change is now adding a filter aggregation before the metric, so it filters documents for the existence of the specified filter first and returns the latest value found in the result set.
Fixes #13596.
=> Wrapping `latest` metric with filter clause for existence of field.

.gitignore, data-node-distribution/src/main/assembly/datanode.xml
Keeping the download itself is necessary for now to build the docker-containers in IT tests. 
But it should not be included in our tarballs.
Also, added the bin dir to `.gitignore`
/nocl
=> DataNode: exclude downloads from assembly

graylog2-web-interface/src/components/bootstrap/ListGroupItem.jsx, graylog2-web-interface/src/components/common/SelectableList.jsx, graylog2-web-interface/src/components/pipelines/Stage.tsx
This PR is unifying the button variants on the pipeline page.
Before:
After:
/nocl
=> Unify button variants for pipeline configuration.

pom.xml
The referenced issue is still open, so we use a new cache directory to avoid any compatibility problems with previous versions.
/nocl
=> Update download-maven-plugin version to 1.6.8

graylog2-server/src/main/java/org/graylog2/configuration/IndexSetsDefaultConfigurationFactory.java, graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetConfig.java, graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetConfigFactory.java
In #13018, the default field type refresh interval was accidentally changed from 5s to 5m, due to using the `index_field_type_periodical_full_refresh_interval` configuration setting for the new default. This setting means something else, it is used in _addition_ to the field type refresh interval to determine when a _full_ refresh should be run.
This PR is changing back the default field type refresh interval to 5
seconds.
/nocl
=> Changing back default field type refresh interval.

graylog2-web-interface/src/components/streams/StreamsOverview/StreamActions.tsx
With this PR we are slightly improving the order of actions in the stream action menu by grouping them.
Before:
After:
/nocl
=> Improve order of actions in stream actions menu.

graylog2-server/src/main/java/org/graylog/plugins/views/search/searchfilters/model/InlineQueryStringSearchFilter.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/searchfilters/model/ReferencedQueryStringSearchFilter.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/searchfilters/model/UsedSearchFilter.java
This PR is adding an optional `id` attribute to inline search filters, allowing the consumer to specify the attribute in order to make locating inline search filters by reference possible.
/nocl
=> Allow specifying optional `id` for inline search filters.

changelog/unreleased/pr-14823.toml, graylog2-web-interface/src/views/components/widgets/MessageTable.tsx
_This is a backport of https://github.com/Graylog2/graylog2-server/pull/14823 for `5.0`_
This is a follow-up for https://github.com/Graylog2/graylog2-server/pull/14805. With this PR we are fixing the described problem for the message list widget. Please have a look at the mentioned PR for more information.
Related to https://github.com/Graylog2/graylog-plugin-enterprise/issues/4761
/nocl
=> Adding word wrap for header columns of message table in print. (backport for 5.0)

UPGRADING.md
/nocl
See Graylog2/graylog-plugin-enterprise#3071
=> Add missing information on unique archive naming scheme 

graylog2-server/src/main/java/org/graylog2/plugin/inputs/MessageInput.java, graylog2-server/src/main/java/org/graylog2/shared/inputs/InputDescription.java
Adds a boolean `isForwarderCompatible` method to mark inputs as not being compatible with Forwarders.
Prerequisite for https://github.com/Graylog2/graylog-plugin-enterprise/pull/4818
/nocl
=> Introduce flag to mark inputs as not compatible with forwarder

graylog2-web-interface/src/components/common/EntityDataTable/BulkActionsDropdown.tsx, graylog2-web-interface/src/components/common/EntityDataTable/BulkActionsRow.tsx, graylog2-web-interface/src/components/common/EntityDataTable/EntityDataTable.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/BulkActions.test.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/BulkActions.tsx, graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/BulkActions.test.tsx, graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/BulkActions.tsx, graylog2-web-interface/src/views/components/searchbar/saved-search/BulkActions.test.tsx, graylog2-web-interface/src/views/components/searchbar/saved-search/BulkActions.tsx
With this PR we are changing the way we display bulk actions for the entity data table.
Before:
After:
The new layout has a few benefits:
- it scales better, there are cases where we might will have over 10 bulk actions
- it looks cleaner, especially with many bulk actions
- it is easier to style the surrounding layout, because the bulk actions button width will not change a lot
- we unify the UI with similar cases in the application
Please note, one behaviour is not perfect. when a `Menuitem` is wrapped with another component like `IfPermitted`, we do not close the dropdown immediately on select. I prefer fixing this behaviour globally for `DropdownButton` in another PR.
=> Display entity data table bulk actions as dropdown.

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/DashboardsResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SavedSearchesResource.java, graylog2-server/src/main/java/org/graylog2/database/filtering/DbFilterExpressionParser.java, graylog2-server/src/main/java/org/graylog2/database/filtering/Filter.java, graylog2-server/src/main/java/org/graylog2/database/filtering/RangeFilter.java, graylog2-server/src/main/java/org/graylog2/database/filtering/SingleValueFilter.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java, graylog2-server/src/main/java/org/graylog2/search/SearchQueryField.java, graylog2-server/src/test/java/org/graylog2/database/filtering/DbFilterExpressionParserTest.java
Filters used in paginated endpoints for Streams, Dashboards and Saved Searches have been upgraded, so that they can accept ranges for dates and numbers.
Example range filter looks like that:
`created_at:2022-07-03><2023-03-03`
Created_at attribute has been changes to "filterable", so that it can be now used to filter paginated results.
BE part for #14828.
/nocl
FE wants to filter results by date in Entity List.
Unit tests have been expanded.
=> Range filters for Entity Lists. Creation date is filterable.

changelog/unreleased/pr-14884.toml, graylog2-server/pom.xml
Enable the Multi-Release flag for the ManifestResourceTransformer in the shade plugin. Without this, the JVM cannot take advantage of the class files for newer JVM versions and hence logs the warning because slower compatibility clases will be used at runtime.
Fixes the following warning on server startup:
WARNING: sun.reflect.Reflection.getCallerClass is not supported.
This will impact performance.
See: https://openjdk.org/jeps/238
Refs #7223
Refs #9802
Refs #11634
=> Fix sun.reflect.Reflection.getCallerClass warning with Java >= 9

graylog2-server/src/main/java/org/graylog2/plugin/IOState.java
Introducing a new IOState on Forwarder Inputs that the server does not understand will lead to failing ReportState grpc calls.
Unknown enums are converted to UNRECOGNIZED by protobuf. Having this state, allows us to keep compatibility with newer forwarders.
/nocl
=> Improve forwarder compatibility

graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java, graylog2-server/src/main/java/org/graylog2/bindings/PersistenceServicesBindings.java, graylog2-server/src/main/java/org/graylog2/database/suggestions/EntitySuggestion.java, graylog2-server/src/main/java/org/graylog2/database/suggestions/EntitySuggestionResponse.java, graylog2-server/src/main/java/org/graylog2/database/suggestions/EntitySuggestionService.java, graylog2-server/src/main/java/org/graylog2/database/suggestions/MongoEntitySuggestionService.java, graylog2-server/src/main/java/org/graylog2/rest/resources/suggestions/EntitySuggestionResource.java
General endpoint for providing entity suggestions.
Part of BE implementation of [#14827](https://github.com/Graylog2/graylog2-server/issues/14827)
/nocl
Introduction of filters in Entity Lists creates a need for suggesting related entities in filters.
I.e. we want to filter streams by index_sets. In order to achieve it, we need to be able to provide a list of existing index_sets in the system. 
There is no need to provide full information about index_sets -> their ids and textual representations are absolutely enough for filter suggestions.
There is also a strong preference towards single, general suggestion endpoint, so that BE does not have to implement a new one for each type of entity.
=> General endpoint for providing entity suggestions

changelog/unreleased/issue-6867.toml, full-backend-tests/src/test/java/org/graylog/plugins/views/SearchSyncIT.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/Query.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/Search.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ExecutionStateGlobalOverride.java, graylog2-web-interface/src/views/components/QueryBar.test.tsx, graylog2-web-interface/src/views/components/dashboard/bigdisplay/CycleQueryTab.test.tsx, graylog2-web-interface/src/views/components/queries/QueryTitle.tsx, graylog2-web-interface/src/views/logic/search/GlobalOverride.ts, graylog2-web-interface/src/views/logic/slices/executeSearch.ts, graylog2-web-interface/src/views/logic/slices/searchExecutionSlice.ts, graylog2-web-interface/src/views/logic/slices/viewSlice.ts
This PR is adding a performance optimization so that only the widgets for the current dashboard page are being executed. For searches, this does not make any difference, as there is always a single page only. For dashboards with lots of widgets (or long time ranges), this can make a big difference regarding search execution times, as widgets which are not currently visible will not be executed.
To achieve this, the following is done in this PR:
- A parameter `keep_queries` is added to the global override, which
can be used to select queries which are executed only
- In the frontend, the currently active query id will always be put
into the `keep_queries` parameter in the global override
Fixes #6867.
=> Limit search execution to current (dashboard) page.

graylog2-web-interface/src/components/common/EntityDataTable/DefaultColumnRenderers.tsx, graylog2-web-interface/src/components/common/EntityDataTable/EntityDataTable.test.tsx, graylog2-web-interface/src/components/common/EntityDataTable/EntityDataTable.tsx, graylog2-web-interface/src/components/common/EntityDataTable/TableCell.tsx, graylog2-web-interface/src/components/common/EntityDataTable/TableHead.tsx, graylog2-web-interface/src/components/common/EntityDataTable/TableRow.tsx, graylog2-web-interface/src/components/common/EntityDataTable/hooks/useColumnsWidth.test.tsx, graylog2-web-interface/src/components/common/EntityDataTable/hooks/useColumnsWidths.ts, graylog2-web-interface/src/components/common/EntityDataTable/types.ts, graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionsContainer.tsx, graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotificationsContainer.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/ColumnRenderers.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/StreamsOverview.tsx, graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardsOverview.tsx, graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/useColumnRenderers.tsx, graylog2-web-interface/src/views/components/searchbar/saved-search/useColumnRenderes.tsx
This PR is improving the rendering of columns in the entity data table. We are now
- Handing entities with camel case attributes correctly. The column meta data is defined in snake case, but some entities like saved searches and dashboards have camel case attributes. We are now transforming the camel case attributes to snake case to fix the mapping.
- It is now possible to define a column renderer for attributes types. Columns have a type like `DATE`, since we often want to render e.g. date times the same way, it makes sense to define the column renderers per type. Otherwise we would have to define the same logic for each date attribute.
/nocl
=> Improve column rendering in entity data table (handle camel case attributes, allow defining column render for attribute types)

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ExecutionState.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/contexts/SearchUserFactory.java
Prior to this PR, in the constructed `SearchUser` instance, the subject was resolved for every call. This lead to the `SearchUser` being unusable in other threads than the one of the request, because for resolving the subject the `ThreadContext` is required.
This PR is now resolving the subject upon construction and keeps the reference to it in the `SearchUser` instance. This has the potential to change the behavior in a subtle way, because due to a single reference being kept instead of resolving the subject for each call, the subject might have changed before between calls and does not do anymore. The behavior now is potentially more consistent for short-running tasks, because the subject is consistent for a single request.
/nocl
=> Retrieve subject initially when constructing `SearchUser`.

graylog2-server/src/main/java/org/graylog2/shared/security/ShiroAuthenticationFilter.java
We included the `.info()` in #14863 in one line to find an error - but the log-output also now logs an Exception that is actually part of the auth-process. It's ok to see this during debug but not during normal operation.
So this is changed back to `.debug()` so it's not polluting the logs.
/nocl
=> ShiroAuthFilter log back to .info()

changelog/unreleased/pr-14742.toml, graylog2-server/src/main/java/org/graylog2/indexer/searches/SearchesClusterConfig.java, graylog2-web-interface/src/components/configurations/SearchesConfig.tsx, graylog2-web-interface/src/components/configurations/TimeRangeOptionsForm.tsx, graylog2-web-interface/src/components/configurations/TimeRangeOptionsSummary.tsx, graylog2-web-interface/src/components/search/SearchConfig.ts, graylog2-web-interface/src/components/search/SurroundingSearchButton.test.tsx, graylog2-web-interface/src/components/search/SurroundingSearchButton.tsx, graylog2-web-interface/src/util/ObjectUtils.ts, graylog2-web-interface/src/views/components/messagelist/MessageActions.test.tsx, graylog2-web-interface/src/views/components/searchbar/RefreshControls.test.tsx, graylog2-web-interface/src/views/components/searchbar/RefreshControls.tsx, graylog2-web-interface/src/views/stores/RefreshStore.ts, graylog2-web-interface/test/fixtures/searchClusterConfig.ts
**Note:** This PR requires #14723 to be merged before.
This PR is extending the search config in a way that the user can define which interval options are being presented. The current options (1s, 2s, 5s, 30s, 1m, 5m) are kept in a way that they are now the default options available.
=> Allow user-configurable auto-refresh settings & default interval.

changelog/unreleased/pr-14925.toml, graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministration.tsx
* fix: clear selected before pagination
(cherry picked from commit 751f73740f0716b8af1c9f732c6e909a0871f1de)
closes #14924 , backport for #14925
=> Backport - Navigation in Sidecar Admin broken if collector is selected (#14925)

changelog/unreleased/pr-14926.toml, graylog2-server/src/main/java/org/graylog2/bindings/PersistenceServicesBindings.java, graylog2-server/src/main/java/org/graylog2/security/AccessTokenServiceImpl.java
resolves https://github.com/Graylog2/graylog-plugin-enterprise/issues/4850
Makes `AccessTokenServiceImpl` a singleton to create index only once on startup.
createIndex for AccessToken was reportedly called >1000 times in 30 minutes, leading to database load.
Can be seen by adding a breakpoint into the constructor.
=> Avoid excessive index creation for AccessToken

changelog/unreleased/issue-14952.toml, graylog2-server/src/main/java/org/graylog2/inputs/persistence/MongoInputStatusService.java
4.3 Backport of: https://github.com/Graylog2/graylog2-server/pull/14954
Updated the `MongoInputStatusService` import for `@Subscribe` to use `com.google.common.eventbus.Subscribe` instead of `org.apache.shiro.event.Subscribe`.
The `handleInputDeleted` method was never being called because of the incorrect import for the `@Subscribe` annotation. Because of this an input's entries in the `input_status` MongoDB collection were never removed after an input was deleted.
Resolves: https://github.com/Graylog2/graylog2-server/issues/14952
Locally in development environment.
=> (Backport 4.3) - Updated MongoInputStatusService to use correct Subscribe import

graylog2-server/src/main/java/org/graylog2/shared/rest/resources/ProxiedResource.java, graylog2-server/src/test/java/org/graylog2/rest/resources/cluster/ClusterLookupTableResourceTest.java
Make authentication token handling for proxied resources a bit more obvious:
- Add explaining JavaDoc
- Explicitly don't add an authentication token to forwarded requests if the original request was unauthenticated
/nocl
=> Improve auth token handling for proxied resources

graylog2-server/src/main/java/org/graylog/events/rest/EventDefinitionsResource.java, graylog2-server/src/main/java/org/graylog2/plugin/rest/ValidationFailureException.java
/nocl
#14792 detects dependencies when deleting event definitions and returns a corresponding `ValidationFailureException`.  
However, the error message does not make it to the UI when this is performed via bulk execution, because it is only being returned in the `errors` list, and not in the exception's detail message. But it is the latter that is used:
https://github.com/Graylog2/graylog2-server/blob/7f51399fa2477fa7580409cd7ed11fe4e53707c2/graylog2-server/src/main/java/org/graylog2/rest/bulk/SequentialBulkExecutor.java#L100-L101
=> Return validation failure message string

changelog/unreleased/pr-14926.toml, graylog2-server/src/main/java/org/graylog2/security/AccessTokenServiceImpl.java
* fix: make AccessTokenServiceImpl a singleton
* changelog
(cherry picked from commit 69943053d97247a469540581661c9b4d4a525347)
=> Backport 4.3 - Avoid excessive index creation for AccessToken (#14926)

changelog/unreleased/pr-14974.toml, graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java, graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationForm.jsx
Users with role "Event Notification Creator" got an error when trying to create a email notification.
This was caused by the user selection dropdown in that notification type's form checking if the user has the permission `users:list` and returning undefined. The permission check was moved into the form and prevents the whole field from showing when the user does not have the permission.
Additionally, the permission was added to the role "User inspector", which only had `users:read` previously to be able to assign a sensible role which actually has this permission.
closes https://github.com/Graylog2/graylog-plugin-enterprise/issues/4886
=> Fix permission checks for role "Event Notification Creator"

changelog/unreleased/pr-14965.toml, graylog2-server/src/main/java/org/graylog2/bindings/PersistenceServicesBindings.java, graylog2-server/src/main/java/org/graylog2/indexer/ranges/MongoIndexRangeService.java, graylog2-server/src/main/java/org/graylog2/notifications/NotificationServiceImpl.java, graylog2-server/src/main/java/org/graylog2/system/activities/SystemMessageServiceImpl.java, graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java
make sure all bindings which use `createIndex()` in the constructor are threadsafe and make them a singleton.
Also use `asEagerSingleton()` and annotation for all singletons.
resolves https://github.com/Graylog2/graylog-plugin-enterprise/issues/4862
`createIndex` makes unnecessary calls to mongoDB.
Eager instantiation helps in finding binding bugs, since they will show up immediately at startup.
=> Optimize service bindings in PersistenceServiceBindings

changelog/unreleased/pr-14978.toml, graylog2-server/src/main/java/org/graylog2/rest/GraylogErrorPageGenerator.java, graylog2-server/src/main/resources/error.html.template
Resolves Graylog2/graylog-plugin-enterprise#4891
Remove stack trace from server error page.
=> Remove stacktrace from error page

changelog/unreleased/pr-14926.toml, graylog2-server/src/main/java/org/graylog2/security/AccessTokenServiceImpl.java
* fix: make AccessTokenServiceImpl a singleton
* changelog
(cherry picked from commit 69943053d97247a469540581661c9b4d4a525347)
=> Backport 5.0 - Avoid excessive index creation for AccessToken (#14926)

changelog/unreleased/pr-14978.toml, graylog2-server/src/main/java/org/graylog2/rest/GraylogErrorPageGenerator.java, graylog2-server/src/main/resources/error.html.template
Backport - see issue https://github.com/Graylog2/graylog-plugin-enterprise/issues/4891
=> Backport to 5.0: Remove stacktrace from error page (#14978)

graylog2-server/src/test/java/org/graylog2/shared/bindings/providers/ParameterizedHttpClientProviderTest.java
It has shown random test failures on jenkins and github.
Maybe for the same reason we disabled the
OkHttpClientProviderTest (#7799)
/nocl
=> Disable ParameterizedHttpClientProviderTest

changelog/unreleased/pr-14987.toml, graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java, graylog2-server/src/main/java/org/graylog2/shared/rest/ContentTypeOptionFilter.java
Adding new Filter thats sending new header on server response X-Content-Type-Options:nosniff
fixes Graylog2/graylog-plugin-enterprise#4890
Locally, check header responses in the webinterface
=> add content type option filter

graylog2-web-interface/src/pages/LUTDataAdaptersPage.jsx
In #12911, the `withHistory` HOC was introduced. Unfortunately in the same PR it was applied in the wrong way to a component, mixing up the bracing of the `connect(withHistory(...` calls. This PR is fixing this.
/nocl
=> Fixing data adapters page by correcting usage of `withHistory`.

changelog/unreleased/pr-15009.toml, graylog2-server/src/main/java/org/graylog/events/processor/aggregation/PivotAggregationSearch.java
One line fix for an off by one error in aggregation search.
This is a backport of a fix that was unrelated to, but included with #14746.
=> Backport 4.3: Fix off by one error in aggregation search

changelog/unreleased/pr-15008.toml, graylog2-server/src/main/java/org/graylog/events/processor/aggregation/PivotAggregationSearch.java
One line fix for an off by one error in aggregation search.
This is a backport of a fix that was unrelated to, but included with #14746.
=> Backport 5.0: Fix off by one error in aggregation search

data-node/pom.xml, data-node/src/main/java/org/graylog/datanode/bindings/PeriodicalBindings.java, data-node/src/main/java/org/graylog/datanode/management/OpensearchProcess.java, data-node/src/main/java/org/graylog/datanode/management/OpensearchProcessImpl.java, data-node/src/main/java/org/graylog/datanode/periodicals/NodePingPeriodical.java, data-node/src/test/java/org/graylog/datanode/periodicals/NodePingPeriodicalTest.java, graylog2-server/src/main/java/org/graylog2/cluster/NodeService.java, graylog2-server/src/main/java/org/graylog2/cluster/NodeServiceImpl.java, graylog2-server/src/main/java/org/graylog2/periodical/NodePingThread.java, graylog2-server/src/test/java/org/graylog2/cluster/NodeServiceImplTest.java
Added missing node ping for datanode 
Additionally there is a small refactoring included, that removes the need to query Node from the DB before we can trigger markAsAlive. This saves one mongodb query every second on each node. The newly created markAsAlive method also prepares a bit of infrastructure for the usage of the `$currentDate`. This will help us to use the mongodb time and avoid out-of-sync clock of different nodes. But the full implementation will have to happen in a separate PR. It's too invasive and requires backwards compatibility changes.
/nocl
Needed to keep overview over active nodes connected to the graylog server.
Manually
=> Datanode periodical for NodeService pings

changelog/unreleased/pr-14762.toml, changelog/unreleased/pr-14992.toml, graylog2-web-interface/src/views/components/messagelist/NodeName.tsx
**Note:** This is a backport of #14762 to `5.0`.
Prior to this PR, clicking on the link to a node did open its details page after doing a full page refresh. This is inconsistent with other parts of the product and disrupts the user flow due to a longer loading time.
This change is now making sure that we are using the internal router to get to the new page.
=> Avoid opening node details in new tab. (`5.0`)

changelog/unreleased/pr-15018.toml, graylog2-server/src/main/java/org/graylog2/cluster/NodeImpl.java, graylog2-server/src/main/java/org/graylog2/cluster/NodeService.java, graylog2-server/src/main/java/org/graylog2/cluster/NodeServiceImpl.java, graylog2-server/src/test/java/org/graylog2/cluster/NodeServiceImplTest.java
This PR is a refactoring of the queries used for:
- registering new nodes
- sending the heartbeat/marking nodes as alive
- finding alive/dead nodes
The improvement is that the DB time is used for the timestamps instead of the node's clock. This is achieved by using `$currentDate` for registering/updating a node entry and a `$where` JS fragment using `new Date()` for finding dead/alive nodes.
The benefit of this is that there is no need for a very exact clock synchronization of the noeds anymore. In the past, if a node clock was late by more than 2 seconds (or the non-default ping timeout), then a node would always be marked as dead.
=> Using database time for node heartbeats.

changelog/unreleased/pr-15058.toml, graylog2-server/src/main/java/org/graylog2/lookup/adapters/CSVFileDataAdapter.java
https://github.com/Graylog2/graylog2-server/pull/14670 introduced some improvements for CSV File adapter error handling, but, it added a check that erroneously verified file write access instead of just read access on file refreshes. This PR fixes that, and changes the check to only verify that read access is present. 
Fixes #14998
Remove write access to the CSV file that a CSV File adapter instance is using (for example `chmod -w my-lookup-file.csv`). Verify that the adapter starts up and refreshes successfully when the refresh interval passes. A lower refresh interval can be set to test his more quickly.
=> Only check read access in the CSV File adapter

changelog/unreleased/pr-15058.toml, graylog2-server/src/main/java/org/graylog2/lookup/adapters/CSVFileDataAdapter.java
Backport https://github.com/Graylog2/graylog2-server/pull/15058 to the `5.0` branch.
=> Only check read access in the CSV File adapter (5.0)

changelog/unreleased/pr-15070.toml, data-node/src/main/java/org/graylog/datanode/Configuration.java, data-node/src/main/java/org/graylog/datanode/configuration/ConfigurationProvider.java
On macOS, the OpenSearch bootstrap checks might fail (missing JNA etc.) so we have to enforce a single-node configuration. I did this as an explicit switch because we have to refactor this part of the config anyway during the preflight-config regarding eventual cluster-specfic config.
=> DataNode: config option to enforce single-node type

graylog2-web-interface/src/pages/LoggedInPage.tsx, graylog2-web-interface/src/routing/AppRouter.test.tsx, graylog2-web-interface/src/routing/AppRouter.tsx
This change is pulling down the `GlobalContextProviders` component to render the defined providers below the configured router instead of on top of it. This leads to avoiding issues where components rendered from the provider require access to the router context.
/nocl
=> Pull down global context providers to be wrapped in router.

changelog/unreleased/pr-15141.toml, data-node/src/main/java/org/graylog/datanode/bootstrap/ServerBootstrap.java, graylog2-server/src/main/java/org/graylog2/bootstrap/ServerBootstrap.java, graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/MongoDBPreflightCheck.java, graylog2-server/src/test/java/org/graylog2/bootstrap/preflight/MongoDBPreflightCheckTest.java, graylog2-server/src/test/resources/org/graylog2/bootstrap/preflight/MongoDBPreflightCheckTest.json
With the introduction of Datanodes and Preflight UI, we have also enabled hearthbeat checks that persist some data into the nodes collection. These entries could break the `isFreshInstallation` flag in the graylog server, if the datanode starts before the graylog server.
This PR changes the `isFreshInstallation` logic, which is now based on the existence of the `cluster_config` collection.
Adapted existing unit tests
=> Fix isFreshInstallation preflight check

changelog/unreleased/issue-14767.toml, graylog2-web-interface/src/components/configurationforms/BooleanField.tsx, graylog2-web-interface/src/components/configurationforms/ConfigurationForm.tsx, graylog2-web-interface/src/components/configurationforms/ConfigurationFormField.tsx, graylog2-web-interface/src/components/configurationforms/DropdownField.tsx, graylog2-web-interface/src/components/configurationforms/EncryptedInlineBinaryField.tsx, graylog2-web-interface/src/components/configurationforms/ListField.tsx, graylog2-web-interface/src/components/configurationforms/NumberField.tsx, graylog2-web-interface/src/components/configurationforms/TextField.tsx, graylog2-web-interface/src/components/configurationforms/TitleField.tsx
Part of https://github.com/Graylog2/graylog2-server/issues/14764
This PR adds an undo reset button to encrypted form fields.
Related: https://github.com/Graylog2/graylog-plugin-enterprise/pull/4964
The "Undo Reset" button is only shown on encrypted text fields and inline binary file uploads after the user clicks "reset".
When editing encrypting fields, the user wants to be able to undo an accidental reset of the field.
=> Add undo reset button to encrypted form fields

graylog2-web-interface/src/components/configurationforms/ConfigurationForm.tsx
Fixes https://github.com/Graylog2/graylog2-server/issues/14955
This PR fixes the bug by making sure that the title is only set to `initialTitle` when `initialTitle` changes or the modal closes/opens. 
Previously it was also reset when other props like `configFields` changed.
=> Input form: Only reset title when initial title changes or modal is closed

data-node-distribution/src/main/assembly/datanode.xml, data-node/pom.xml
We tried to use fileSet/fileMode to make the OpenSearch config permissions work when running OpenSearch with a different user.
That didn't work because the fileMode changed all files and removed the executable bit from all executable scripts.
Now we use the Maven antrun plugin to set the permissions on the OpenSearch files right after extraction.
=> Fix OpenSearch permissions in data node tarball

graylog2-server/src/main/java/org/graylog2/cluster/NodeServiceImpl.java
This PR is refactoring the node heartbeats to replace the usage of the `$where`-clause (which requires server-side scripting) with an aggregation pipeline using date arithmetics using the `$$NOW` global variable.
Due to the lack of type coercion, it is not backwards compatible with the previous format of the `last_seen` field.
/nocl
=> Implement node heartbeats without server-side scripting.

changelog/unreleased/pr-15187.toml, pom.xml
Release notes:
- https://shiro.apache.org/blog/2023/01/13/apache-shiro-1110-released.html
- https://shiro.apache.org/blog/2022/11/19/apache-shiro-1101-released.html
- https://shiro.apache.org/blog/2022/10/10/apache-shiro-1100-released.html
- https://shiro.apache.org/blog/2022/06/28/apache-shiro-191-released.html
- https://shiro.apache.org/blog/2022/03/22/apache-shiro-190-released.html
- https://shiro.apache.org/blog/2021/v1.8.0.html
- https://shiro.apache.org/blog/2021/v1.7.1.html
- https://shiro.apache.org/blog/2020/v1.7.0.html
- https://shiro.apache.org/blog/2020/v1.6.0.html
- https://shiro.apache.org/blog/2020/05/03/apache-shiro-1.5.3-released.html
Fixed CVEs:
- CVE-2022-32532 - Doesn't affect Graylog because we don't run in a servlet container
- CVE-2022-40664 - Doesn't affect Graylog …
=> Security update to shiro-core 1.11.0

changelog/unreleased/pr-15186.toml, pom.xml
netty-tcnative from 2.0.54 to 2.0.59
Fixed CVEs
HAProxyMessageDecoder Stack Exhaustion DoS ([CVE-2022-41881](https://github.com/netty/netty/security/advisories/GHSA-fx2c-96vj-985v))
HTTP Response splitting from assigning header value iterator ([CVE-2022-41915](https://github.com/netty/netty/security/advisories/GHSA-hh82-3pmq-7frp))
=> Update netty from 4.1.84 to 4.1.91

changelog/unreleased/pr-15190.toml, pom.xml
Fixes CVE-2023-1370 in the json-smart transitive dependency.
=> Update json-path to 2.8.0 to fix a security issue in json-smart

changelog/unreleased/pr-15195.toml, graylog2-server/src/main/java/org/graylog2/shared/system/stats/os/OshiOsProbe.java
Fixed calculation and expression of CPU load in OshiProbe to be consistent in OsStats.
It's related to https://github.com/Graylog2/graylog2-server/pull/15183
=> Fixed calculation and expression of CPU load in OshiProbe to be consistent in OsStats

changelog/unreleased/issue-15073.toml, graylog2-web-interface/src/views/components/AdaptableQueryTabs.tsx
_Please note, this is a backport of #15091 for 5.0_
As described in https://github.com/Graylog2/graylog2-server/issues/15073 the "more dashboard tabs" dropdown can be displayed behind the data table header.
The fix suggested by @drewmiranda-gl works well. I tested it with all widget types and did not found a problem.
Fixes #15073
=> Fix z-index of dashboard tabs dropdown. (backport of #15091 for 5.0)

changelog/unreleased/issue-15073.toml, graylog2-web-interface/src/views/components/AdaptableQueryTabs.tsx
_Please note, this is a backport of #15091 for 4.3_
As described in https://github.com/Graylog2/graylog2-server/issues/15073 the "more dashboard tabs" dropdown can be displayed behind the data table header.
The fix suggested by @drewmiranda-gl works well. I tested it with all widget types and did not found a problem.
Fixes #15073
=> Fix z-index of dashboard tabs dropdown. (backport of #15091 for 4.3)

changelog/unreleased/issue-15013.toml, graylog2-server/src/main/java/org/graylog2/security/AccessTokenService.java, graylog2-server/src/main/java/org/graylog2/security/AccessTokenServiceImpl.java, graylog2-server/src/test/java/org/graylog2/security/AccessTokenServiceImplTest.java
Resolves #15013 
Introduce a cache for last access time. Items expire after a set duration, ensuring that they stay reasonably fresh without being refreshed more often than is useful.
See linked issue for details.
=> Cache last access time of authentication tokens

graylog2-web-interface/src/components/event-definitions/event-definitions/SchedulingCell.tsx
Scheduling information in the event definitions table is mixed up. "search within ms" and "execute every ms" need to be permutated.
This PR does that.
/nocl
=> Fix mixed-up event scheduling information

changelog/unreleased/pr-15216.toml, data-node/src/main/java/org/graylog/datanode/Configuration.java, data-node/src/main/java/org/graylog/datanode/OpensearchDistribution.java, data-node/src/main/java/org/graylog/datanode/OpensearchDistributionProvider.java, data-node/src/main/java/org/graylog/datanode/bindings/OpensearchDistributionBindings.java, data-node/src/main/java/org/graylog/datanode/bootstrap/OpensearchBinPreflightCheck.java, data-node/src/main/java/org/graylog/datanode/bootstrap/ServerBootstrap.java, data-node/src/main/java/org/graylog/datanode/configuration/ConfigurationProvider.java, data-node/src/test/java/org/graylog/datanode/OpensearchDistributionTest.java, data-node/src/test/java/org/graylog/datanode/testinfra/DatanodeContainerizedBackend.java, misc/datanode.conf
This PR removes the need to provide exact path to the opensearch distribution and opensearch version. We can autodetect both from the root distribution directory.
Before this PR it was needed to point to the exact opensearch distribution directory in the datanode.conf. But adding this full path in the configuration would prevent us from updating to a newer version of opensearch - the user would have to change the path every time. 
With autodetection we only need a base directory that will hold opensearch distribution. The rest - opensearch location, version and architecture can be autodetected during runtime. 
The autodetection handles 3 typical cases, all of them dealing with different `opensearch_location` target:
- The property points to a directory that holds different distributions …
=> Opensearch dist dir autodetection

graylog2-server/src/test/java/org/graylog/events/conditions/BooleanNumberConditionsVisitorTest.java, graylog2-server/src/test/java/org/graylog2/inputs/codecs/EncodingTest.java
The "BooleanNumberConditionsVisitorTest" test was globally modifying the configuration of the json-path library.
Since we are using two forked JVMs to run the tests, the changed json-path configuration sometimes affected the "EncodingTest" test class. That dependend on the distribution of the test files over the forked JVMs and the order the tests are executed.
With surefire 2.22.1 the problem never showed up for some reason. With surefire 3.0.0 the problem showed up more often that it did not. This is probably due to the fork runner implementation changes in vesion 3.0.0.
This change also restores the trailing comma in the JSON example in "EncodingTest" that got removed in the surefire update.
/nocl
=> Fix global json-path library config modification in test class

graylog2-server/src/main/java/org/graylog2/bootstrap/ServerBootstrap.java
Fix resetting guice injection holder when preflight feature flag is set but the preflight is already configured/skipped. 
/nocl
Manually
=> Fix resetting GuiceInjectorHolder during preflight web

graylog2-server/src/main/java/org/graylog2/shared/rest/resources/annotations/CSP.java
/nocl Fix for an unreleased feature 
Telemetry and auth need to connect to external targets. 
As an interim solution, we allow all external connections.
=> Add wild card connect-src to CSP for telemetry and auth

graylog2-web-interface/src/logic/telemetry/TelemetryInit.tsx
An error in the condition of the `TelemetryInit` component lead to telemetry initialization when telemetry settings have not been loaded yet, even though it is disabled.
This change is now fixing, avoiding telemetry initialization in case of the settings not being loaded yet.
/nocl
=> Avoid telemetry initialization when settings are missing.

changelog/unreleased/issue-15244.toml, graylog2-web-interface/src/components/users/UserDetails/UserDetails.tsx, graylog2-web-interface/src/logic/telemetry/TelemetrySettingsConfig.tsx
This change adds telemetry setting form to the user profile view for built-in admin user.
fix #15244
=> show edit  telemetry setting for builtin admin

changelog/unreleased/pr-15270.toml, graylog2-web-interface/src/components/events/events/EventFields.tsx, graylog2-web-interface/src/components/events/events/types.ts, graylog2-web-interface/src/views/logic/queries/QueryHelper.test.ts, graylog2-web-interface/src/views/logic/queries/QueryHelper.ts, graylog2-web-interface/src/views/logic/valueactions/createEventDefinition/hooks/useUrlConfigData.test.tsx, graylog2-web-interface/src/views/logic/views/UseCreateViewForEvent.ts, graylog2-web-interface/test/helpers/mocking/EventAndEventDefinitions_mock.ts
This pr:
- for event add `group by fields` as part of the search query
- update concat query string helper function
fix: [14813](https://github.com/Graylog2/graylog2-server/issues/14813)
/nocl
=> Fix: replay search on event definitions should honor event keys

graylog2-server/src/main/java/org/graylog2/decorators/DecoratorImpl.java
This PR is fixing up nested deserialization of decorators in saved searches/dashboards. When including the `favorite` flag, a pipeline is being used to enrich the documents with the flag instead of retrieving documents directly. This alters deserialization bypassing MongoJack partially and therefore not transforming the `_id` field of nested documents to `id`.
Therefore, this change is now making sure that deserialization of decorators support both `_id` and `id` fields.
Fixes #15086.
/nocl
=> Fixing nested deserialization of decorators from views.

changelog/unreleased/issue-14885.toml, graylog2-web-interface/src/views/components/contexts/DrilldownContext.tsx, graylog2-web-interface/src/views/components/contexts/DrilldownContextProvider.test.tsx, graylog2-web-interface/src/views/components/contexts/DrilldownContextProvider.tsx
_Please note this PR needs a backport for 4.3 and 5.0_
Widgets have an action called replay search. It will open a new search with the same search query, streams and time range like the widget. On a dashboard, when there is a dashboard query filter, we combine the dashboard query and widget query. This was not reflected in the replay search functionality. By default we used the widget query, but when a dashboard query filter was present we were only using the dashboard query filter.
With this PR we are also combining the queries when replaying the search for a dashboard widget.
Please have a look at https://github.com/Graylog2/graylog2-server/issues/14885 for more information.
Fixes https://github.com/Graylog2/graylog2-server/issues/14885
=> Combine dashboard and widget query when replaying search for dashboard widget

changelog/unreleased/issue-15277.toml, graylog2-server/src/main/java/org/graylog2/shared/inputs/InputRegistry.java, graylog2-server/src/test/java/org/graylog2/shared/inputs/InputRegistryTest.java
Make `InputRegistry` threadsafe by delegating methods to a threadsafe collection instead of directly extending `HashSet`.
Note: I couldn't reproduce #15277, but I've seen the error myself at least once before. However, the `InputRegistry` was not threadsafe, and it's reasonable to assume this is causing issues.
Fixes #15277
=> Make InputRegistry threadsafe

graylog2-web-interface/src/views/logic/queries/QueryHelper.test.ts, graylog2-web-interface/src/views/logic/queries/QueryHelper.ts
Prior to this PR, an exception was thrown when creating a message table widget on a dashboard with a global override query being set. This is caused by the query string concatenation function not handling `undefined` properly.
This PR is fixing this, by treating `undefined`/`null` as query strings identical to blank query strings.
Fixes #15304.
/nocl
=> Handle `undefined`/`null` when concatenating query strings.

changelog/unreleased/issue-13872.toml, graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategy.java, graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategyTest.java
**Note:** This needs to be backported to `5.0`.
Prior to this PR, when an index set had configured a time-based rotation strategy and at least one index matching its naming scheme existed which was closed, the rotation check failed. This was because initially a check was performed if the index set is empty. This was done by checking all existing indices matching the naming scheme of the index set for their size, failing with an exception for closed indices.
This change is now filtering out closed indices in that check, treating them as if they are empty. This avoids the exception being thrown, allowing rotation (checks) to continue.
Fixes #13872.
Fixes Graylog2/graylog-plugin-enterprise#4908.
=> Only check size of indices which are open during rotation.

graylog2-server/src/main/java/org/graylog2/rest/RemoteInterfaceProvider.java
There is a conversion error when reading the `proxied_requests_default_call_timeout` setting. For some calls, the actual timeout being used was higher by a factor of 1000.
I noticed this when looking at requests like the following:
```
http://localhost:8080/api/cluster/aaa02d2d-1c2c-426b-9dca-daa2a38c828a/metrics/namespace/org
```
/nocl
=> Fix wrong conversion of default timeout for proxied resources

changelog/unreleased/pr-15306.toml, graylog2-web-interface/src/views/components/searchbar/queryinput/custom-lucene-mode.js
The integrated lucene mode of ace is broken regarding regex handling. It is forwarding to a missing `no_regex` state when regexes are ending, resulting in an exception being thrown when parsing a regex in a query string.
This PR is fixing this, by forwarding to the `start` state after a regex has ended.
Fixes Graylog2/graylog-plugin-enterprise#5014.
=> Fix query parser's tokenizer state after regex has ended.

changelog/unreleased/issue-14939.toml, graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministration.tsx
fixes https://github.com/Graylog2/graylog2-server/issues/14939
=> Fix sidecar process button position issue on safari

graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardActions.test.tsx, graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardActions.tsx
Before this change the delete buttons in the dashboards overview were always visible even when the user only had read permissions for a dashboard.
Fixes https://github.com/Graylog2/graylog2-server/issues/15261
/nocl
=> Only display dashboard delete action when user has the required permissions.

graylog2-web-interface/src/views/components/datatable/DataTableEntry.tsx
In the previous version, in the code, we expect only 2 items [k, v] in the translated path, but in fact, we had 2xN items. This PR handle case when we have several pairs of [k, v]
fix: https://github.com/Graylog2/graylog2-server/issues/15125
/nocl
=> Add handler for more than 2 items in translatedPath for creating valuePath

UPGRADING.md, full-backend-tests/src/test/java/org/graylog/testing/fullbackend/FiltersIT.java, graylog2-server/src/main/java/org/graylog/security/authservice/AuthServiceBackendConfig.java, graylog2-server/src/main/java/org/graylog/security/authservice/backend/ADAuthServiceBackendConfig.java, graylog2-server/src/main/java/org/graylog/security/authservice/backend/LDAPAuthServiceBackendConfig.java, graylog2-server/src/main/java/org/graylog2/shared/rest/resources/csp/CSP.java, graylog2-server/src/main/java/org/graylog2/shared/rest/resources/csp/CSPServiceImpl.java, graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationResource.java
/nocl Minor change to existing feature that has a CL
Resolves #15344 
An interim solution for Content Security Policy, while we work on dynamically populating the `connect-src`  (#15305). 
This PR retains code for a CSP service developed to date, to facilitate further development. Also include the interface change for `AuthServiceBackendConfig`, so 5.2 will not need to break compatibility with 5.1.
Locally tested these scenarios:
- regular UI
- API browser
- login with DB and Okta
- world map widget
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#5085
=> Revert connect-src to wildcard

graylog2-server/src/main/java/org/graylog2/database/dbcatalog/DbEntitiesCatalog.java, graylog2-server/src/main/java/org/graylog2/database/dbcatalog/DbEntitiesScanner.java, graylog2-server/src/main/java/org/graylog2/database/dbcatalog/impl/ClassGraphDbEntitiesScanningMethod.java, graylog2-server/src/main/java/org/graylog2/database/dbcatalog/impl/DbEntitiesScanningMethod.java, graylog2-server/src/main/java/org/graylog2/database/dbcatalog/impl/ReflectionsDbEntitiesScanningMethod.java, graylog2-server/src/test/java/org/graylog2/database/dbcatalog/DbEntitiesScannerTest.java, pom.xml
DbEntityScanner now uses ClassGraph instead of Reflections.
ClassGraph library has been updated to the latest version.
/nocl
Reflections based scanning took too much time on certain AWS environments.
=> Moving from Reflections to ClassGraph when scanning for DB enities

graylog2-web-interface/src/components/common/OverlayDropdownButton.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/StreamActions.tsx, graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardActions.tsx
With https://github.com/Graylog2/graylog2-server/pull/15350 we unified the name of the "More actions" dropdown in the saved searches, dashboards and streams overview. The title is now just "More". With this PR we are defining a `title` and `aria-label` as well ("More Actions") to improve the accessibility.
/nocl
=> Add title for more actions dropdown in streams and dashboards overview for better accessibility

graylog2-server/src/main/java/org/graylog2/shared/rest/resources/csp/CSP.java
/nocl change to an unreleased feature
Resolves #15344 
Use wildcard for the image source in CSP, while we implement a more configurable solution for the next release.
=> Use wildcard for CSP img-src

graylog2-web-interface/src/views/logic/views/OnSaveNewDashboard.test.ts, graylog2-web-interface/src/views/logic/views/OnSaveNewDashboard.ts
This PR is making sure that the dirty flag of a dashboard is set to `false` after it was saved as (or initially) and before redirecting to the new dashboard id.
This prevents the confirmation prompt showing up needlessly indicating that the current dashboard has been changed and that these changes will be lost.
Fixes #15345.
/nocl Fixing a regression which was introduced in 5.1 development.
=> Set dashboard not dirty after first save.

changelog/unreleased/pr-15400.toml, graylog2-server/src/main/java/org/graylog2/system/jobs/SystemJobManager.java, graylog2-server/src/test/java/org/graylog2/system/jobs/SystemJobManagerTest.java
The SystemJobManager is checking and preventing unwanted concurrent tasks. But the implementation was not bulletproof and it was possible to run more tasks even if the concurrency was disabled for them.
The `jobs` map is a ConcurrentHashMap, but this is not enough to prevent two tasks starting in the same time. The concurrency check and putting a task into this map happens not atomically and any delay between these two operation would allow starting another task.
The easiest and reliable solution is to mark the whole `submitWithDelay` as _synchronized_. 
Addapted the existing concurrency test to actually start tasks concurrently, set to 100 repetitions of the test, verified before and after the _synchronized_ fix.
=> Fix concurrency issue in SystemJobManager

graylog2-web-interface/src/components/common/InputDescription.tsx, graylog2-web-interface/src/theme/GlobalThemeStyles.js
With https://github.com/Graylog2/graylog2-server/pull/14756 we changed the padding for input descriptions.
It looked good for forms with the class `form-horizontal`, but it looked bad in other cases.
For example for the index set form:
With this change we fix the padding for all cases:
/nocl
=> Fix padding for form input descriptions.

graylog2-web-interface/src/components/search/MessageDetailsTitle.jsx, graylog2-web-interface/src/views/components/messagelist/MessageActions.tsx, graylog2-web-interface/src/views/components/messagelist/MessageDetail.tsx
Small fix to improve the responsiveness  of the message details title and actions.
Before (with a small resolution): 
After (with a small resolution):
/nocl
=> Improve responsiveness of message details header.

changelog/unreleased/pr-15329.toml, graylog2-server/src/main/java/org/graylog2/shared/security/ShiroSecurityContextFilter.java
This change is making sure that cookie auth has precedence over basic auth during the authentication process of the REST API. This allows us to put a proxy in front of Graylog that does basic auth separately, without the need of user databases being in sync with Graylog's user database.
What this does not solve is API access through tokens as basic auth headers. This needs a separate fix and will most probably require an additional, separate header being user for the token.
Fixes #6831.
Caddy, configured with basic auth was used to reverse proxy the Graylog frontend/API. General functionality tests were performed with it.
=> Let cookie auth take precedence over basic auth.

data-node/src/main/java/org/graylog/datanode/bootstrap/Main.java, graylog2-server/src/main/java/org/graylog/security/certutil/CertutilCsr.java, graylog2-server/src/main/java/org/graylog/security/certutil/csr/CsrFileStorage.java, graylog2-server/src/main/java/org/graylog/security/certutil/csr/CsrStorage.java, graylog2-server/src/main/java/org/graylog/security/certutil/privatekey/PrivateKeyEncryptedFileStorage.java, graylog2-server/src/main/java/org/graylog/security/certutil/privatekey/PrivateKeyEncryptedStorage.java, graylog2-server/src/test/java/org/graylog/security/certutil/csr/CsrFileStorageTest.java, graylog2-server/src/test/java/org/graylog/security/certutil/privatekey/PrivateKeyEncryptedFileStorageTest.java
CSR command with code generating sample CSR.
It does the following things:
1. Generate public/private key file.
2. Stores private key so that it can be used after certificate eventually gets signed.
3. Creates CSR.
4. Stores CSR in the file.
It is not a final solution, but rather a step in the proper direction.
Further development will need to be postponed untill the start of next shape-up cycle.
/nocl
With new unit tests and manually.
=> CSR command with code generating sample CSR

changelog/unreleased/issue-13872.toml, graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategy.java, graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategyTest.java
**Note:** This is a backport of #15326 to `5.0`.
Prior to this PR, when an index set had configured a time-based rotation strategy and at least one index matching its naming scheme existed which was closed, the rotation check failed. This was because initially a check was performed if the index set is empty. This was done by checking all existing indices matching the naming scheme of the index set for their size, failing with an exception for closed indices.
This change is now filtering out closed indices in that check, treating them as if they are empty. This avoids the exception being thrown, allowing rotation (checks) to continue.
Fixes #13872.
Fixes Graylog2/graylog-plugin-enterprise#4908.
=> Only check size of indices which are open during rotation. (`5.0`)

changelog/unreleased/issue-13872.toml, graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategy.java, graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategyTest.java
**Note:** This is a backport of #15326 to `4.3`.
Prior to this PR, when an index set had configured a time-based rotation strategy and at least one index matching its naming scheme existed which was closed, the rotation check failed. This was because initially a check was performed if the index set is empty. This was done by checking all existing indices matching the naming scheme of the index set for their size, failing with an exception for closed indices.
This change is now filtering out closed indices in that check, treating them as if they are empty. This avoids the exception being thrown, allowing rotation (checks) to continue.
Fixes #13872.
Fixes Graylog2/graylog-plugin-enterprise#4908.
=> Only check size of indices which are open during rotation. (`4.3`)

graylog2-web-interface/src/components/events/events/EventDetails.tsx, graylog2-web-interface/src/views/components/messagelist/MessageActions.tsx, graylog2-web-interface/src/views/components/searchbar/saved-search/SearchActionsMenu.tsx, graylog2-web-interface/src/views/types.ts
_Please note this PR needs to be merged together with https://github.com/Graylog2/graylog-plugin-enterprise/pull/5133._
Before this change rendering the investigation plugins throw a warning in the console:
`Warning: Each child in a list should have a unique "key" prop.`
With this PR we are defining a key when rendering plugins. This can be tested by e.g. opening the message details in the message table widget.
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/5133
/nocl
=> Fix uniq key react warning for investigation plugins.

UPGRADING.md
5.1 changes how Sigma rules can be imported from Git by adding the option to import rules from repositories other than the official Sigma HQ repo. This information should prepare users for these changes. backport of #15427
/nocl
=> Backport 5.1: Add Sigma Repository information to UPGRADING.md (#15427)

changelog/unreleased/pr-15280.toml, graylog2-web-interface/src/components/configurations/DecoratorsConfig.tsx
Prior to this PR, in the `System` -> `Configuration` -> `Decorators` dialog, we were only showing streams as options if they have any decorators configured. This could lead to the default option (`All Messages` stream) being shown with its numeric id only.
This change is now showing all streams as options, regardless if they have decorators configured or not. This fixes the display problem and avoids confusion for the user because streams do not show up.
Fixes #13465.
Fixes #13467.
Refs #14546.
=> Showing all streams in decorator configuration.

graylog2-web-interface/src/hooks/useEventDefinition.tsx, graylog2-web-interface/src/views/logic/views/UseCreateViewForEvent.test.ts, graylog2-web-interface/src/views/logic/views/UseCreateViewForEvent.ts, graylog2-web-interface/test/helpers/mocking/EventAndEventDefinitions_mock.ts
Note: This is a backport of https://github.com/Graylog2/graylog2-server/pull/15418 to 5.1.
In the case with no pivot fields, fn pivotForField runs with an empty array. As a result, it creates a pivot without a field that the widget does not expect. This PR fixes this problem. In case of no pivot fields we return an empty array as rowPivots
fix: https://github.com/Graylog2/graylog2-server/issues/15413
/nocl
=> Do not run pivotForField with empty array in UseCreateViewForEvent

graylog2-web-interface/src/views/pages/StreamSearchPage.test.tsx, graylog2-web-interface/src/views/pages/StreamSearchPage.tsx
**Note:** This requires a backport to `5.1`.
In #15437 creating a search for a new saved search/dashboard was made explicit. Unfortunately, creating the search for a new stream search (a saved search scoped to a specific stream) was not adjusted, leading to the stream search page not loading properly.
This PR is changing this by making search creation explicit for the stream search page as well.
/nocl Fixing a regression introduced in development.
=> Create search before loading stream search page.

graylog2-web-interface/src/components/common/withModalTelemetry.tsx, graylog2-web-interface/src/components/common/withPopoverTelemetry.tsx
This change removes the pathname from withModalTelemetry. 
Fix #15455
/nocl
=> Fix issue when loading modal out of router context

data-node/src/main/java/org/graylog/datanode/management/Environment.java, data-node/src/test/java/org/graylog/datanode/management/EnvironmentTest.java
The provided environment was completely ignored due to the usage of the wrong variable. 
/nocl
Extended unit test to verify that valid keys are actually propagated.
=> Fixed env propagation for datanodes opensearch

graylog2-server/src/main/resources/log4j2.xml
This is the de-facto standard anyways, because during server startup we are modifying the root logger level with "info" being the default. This happens in `CmdLineTool`.
Before this change, commands that don't inherit from `CmdLineTool` had to perform the same kind of log level change. Now, they can just run with the default "info" level which is what we probably want most of the time.
/nocl (shouldn't be noticeable when running the server or any of the existing commands)
=> Change log level of root logger to "info"

changelog/unreleased/pr-15465.toml, graylog2-web-interface/src/stores/cluster/ClusterOverviewStore.js
**Note:** This needs a backport to `5.0` & `5.1`.
Prior to this PR, any page that loads the `ClusterOverviewStore` would trigger a permanent session extension. This happens because the store is listening to `NodesStore.list`, calling `cluster()` for every update.  This function is doing a fetch in turn, which is not disabling session extension.
This PR is fixing this by using `fetchPeriodically` for the cluster overview call.
Fixes Graylog2/graylog-plugin-enterprise#5158.
=> Do not extend session when fetching cluster overview.

changelog/unreleased/issue-15259.toml, graylog2-web-interface/src/components/event-definitions/event-definitions/BulkActions.tsx
backport https://github.com/Graylog2/graylog2-server/pull/15384
fixes https://github.com/Graylog2/graylog2-server/issues/15259
=> Backport (5.1): Fix BulkActions dialog not closing after clicking on Confirm (#15384)

graylog2-server/src/test/java/org/graylog/testing/completebackend/ContainerizedGraylogBackend.java, graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerConfig.java, graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerFactory.java, graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeInstance.java, graylog2-server/src/test/java/org/junit/platform/engine/support/hierarchical/ContainerMatrixHierarchicalTestEngine.java
This change allows passing a non-default timeout for proxied requests to the Graylog server started from full backend tests. This allows mitigation of overly slow/overloaded environments resulting in test failures due to timeouts of proxied API requests.
/nocl
=> Allow configuring proxied requests timeout in full backend tests.

changelog/unreleased/pr-15505.toml, graylog2-web-interface/src/components/indexers/IndexerClusterHealth.tsx
_This PR needs a backport for `5.0` and `5.1`._
This is a follow-up for https://github.com/Graylog2/graylog2-server/pull/15465. 
With this PR we make sure we do not extend the session when fetching indexer cluster health periodically.
Please have a look at https://github.com/Graylog2/graylog2-server/pull/15465 for more information.
=> Do not extend session when fetching indexer cluster health.

graylog2-server/src/test/java/org/graylog/testing/completebackend/TimeoutHelpers.java
Like for the frontend tests, there might be scenarios where we want to
apply environment-specific multiplier to timeouts in tests. For slower
environments, we can set a higher multiplier to avoid test failures
under load.
This PR is adding a `TimeoutHelpers.applyTimeoutMultiplier` method,
which is taking the `TIMEOUT_MULTIPLIER` setting from the environment
and applying it to the given number. If the environment variable is not
set, `1.0` will be used.
/nocl
=> Provide method for applying timeout multiplier.

changelog/unreleased/pr-15508.toml, graylog2-web-interface/src/stores/cluster/ClusterOverviewStore.js
**Note:** This is a backport of #15465 to `5.0`.
Prior to this PR, any page that loads the `ClusterOverviewStore` would trigger a permanent session extension. This happens because the store is listening to `NodesStore.list`, calling `cluster()` for every update.  This function is doing a fetch in turn, which is not disabling session extension.
This PR is fixing this by using `fetchPeriodically` for the cluster overview call.
Fixes Graylog2/graylog-plugin-enterprise#5158.
=> Do not extend session when fetching cluster overview. (`5.0`)

graylog-project-parent/pom.xml, graylog2-server/pom.xml, pom.xml
Move zstd-jni from graylog-project-parent to graylog-parent because some transitive plugin dependencies are using it.
Add version property for the latest commons-lang3 dependency.
/nocl
=> Manage zstd-jni and commons-lang3 dependencies in graylog-parent

changelog/unreleased/pr-15505.toml, graylog2-web-interface/src/components/indexers/IndexerClusterHealth.tsx
_This is a backport of #15505 for `5.0`_
This is a follow-up for https://github.com/Graylog2/graylog2-server/pull/15465. 
With this PR we make sure we do not extend the session when fetching indexer cluster health periodically.
Please have a look at https://github.com/Graylog2/graylog2-server/pull/15465 for more information.
=> Do not extend session when fetching indexer cluster health. (backport of #15505 for 5.0)

changelog/unreleased/pr-15505.toml, graylog2-web-interface/src/components/indexers/IndexerClusterHealth.tsx
_This is a backport of #15505 for `5.1`_
This is a follow-up for https://github.com/Graylog2/graylog2-server/pull/15465. 
With this PR we make sure we do not extend the session when fetching indexer cluster health periodically.
Please have a look at https://github.com/Graylog2/graylog2-server/pull/15465 for more information.
=> Do not extend session when fetching indexer cluster health. (backport of #15505 for 5.1)

graylog2-web-interface/src/components/search/MessageDetailsTitle.jsx, graylog2-web-interface/src/views/components/messagelist/MessageActions.tsx, graylog2-web-interface/src/views/components/messagelist/MessageDetail.tsx
_Please note, this is a backport of #15359 for 5.0_
Small fix to improve the responsiveness  of the message details title and actions.
Before (with a small resolution): 
After (with a small resolution):
/nocl
=> Improve responsiveness of message details header. (Backport of #15359 for 5.0)

graylog2-web-interface/src/components/common/InputDescription.tsx, graylog2-web-interface/src/theme/GlobalThemeStyles.js
_Please note, this is a backport of https://github.com/Graylog2/graylog2-server/pull/15360 for 5.0_
_This PR needs to be merged together with https://github.com/Graylog2/graylog-plugin-enterprise/pull/5122_
With https://github.com/Graylog2/graylog2-server/pull/14756 we changed the padding for input descriptions.
It looked good for forms with the class `form-horizontal`, but it looked bad in other cases.
For example for the index set form:
With this change we fix the padding for all cases:
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/5122
/nocl
=> Fix padding for form input descriptions. (Backport of #15360 for 5.0)

data-node/src/main/java/org/graylog/datanode/bootstrap/preflight/DataNodePreflightGeneratePeriodical.java, graylog2-server/src/main/java/org/graylog/security/certutil/cert/storage/CertMongoStorage.java, graylog2-server/src/main/java/org/graylog/security/certutil/cert/storage/CertStorage.java, graylog2-server/src/main/java/org/graylog/security/certutil/csr/CertificateAndPrivateKeyMerger.java, graylog2-server/src/main/java/org/graylog/security/certutil/csr/storage/CsrFileStorage.java, graylog2-server/src/main/java/org/graylog/security/certutil/csr/storage/CsrMongoStorage.java, graylog2-server/src/main/java/org/graylog/security/certutil/keystore/storage/KeystoreMongoStorage.java, graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/GraylogPreflightGeneratePeriodical.java, graylog2-server/src/main/java/org/graylog2/cluster/NodePreflightConfig.java, graylog2-server/src/main/java/org/graylog2/cluster/NodePreflightConfigService.java, graylog2-server/src/main/java/org/graylog2/cluster/certificates/CertificatesService.java, graylog2-server/src/main/java/org/graylog2/cluster/certificates/NodeCertificate.java, graylog2-server/src/test/java/org/graylog/security/certutil/csr/storage/CsrFileStorageTest.java, graylog2-server/src/test/java/org/graylog/security/certutil/csr/storage/CsrTestTools.java
PKCS12 keystore file, with certificate and password, is stored in Mongo.
It is protected with keystore password and additionally encrypted. Significant part of the communication between data-node and GL server, related to certificates, works as expected in main scenario.
/nocl
Provide more building blocks to reach "happy path" implementation.
Only manually.
=> PKCS12 keystore file, with certificate and password, is stored in Mongo.

changelog/unreleased/pr-15351.toml, graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchList.test.tsx, graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchList.tsx
Before this change the delete buttons in the saved searches overview were always visible, even when the user only had read permissions for a saved search.
=> Only display delete icon for saved searches when user has required permissions. (4.3)

graylog2-server/src/test/java/org/graylog/testing/mongodb/MongoJackExtension.java
This change adds support for injecting CommonMongoJackObjectMapperProvider when using the MongoJackExtension for JUnit.
/nocl
=> Add CommonMongoJackObjectMapperProvider injection to MongoJackExtension

misc/graylog.conf
Fix small typo in graylog.conf file.
/nocl
=> Fix small typo

graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/GraylogPreflightGeneratePeriodical.java
The periodical that checks for work on the Graylog Server side throws an exception if there is no ca-file. A warning makes more sense for now. It's only preliminary anyway and solved differently with #15546
/nocl
=> DataNode: Print warning if keystore file does not exist

graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/web/resources/PreflightResource.java
Fix state change method in generate API call in PreflightResource.
/nocl
Previous version tries to store a new document in the collection, instead of updating an old one, which is wrong and causes:
`E11000 duplicate key error collection: graylog.node_preflight_config`.
Will be necessary to fix quickly for the FE.
Manually, with curl.
=> Fix state change method in generate API call in PreflightResource

changelog/unreleased/issue-15536.toml, graylog2-web-interface/src/routing/AppRouter.tsx
**Note:** This needs a backport to `5.1`.
While migrating to `react-router` v6, a programmatic error sneaked in that prevents the root path to be properly suffixed if the user configures a custom path suffix (either through the config file or an HTTP header).
This PR is now making sure that the router's root path is also suffixed with the custom path, preventing the error to show up.
Fixes #15536.
=> Properly prefix frontend route path if custom path suffix is configured.

graylog2-server/src/main/java/org/graylog/schema/VendorFields.java
Add vendor_subtype GIM schema field constant.
/nocl
Allows common constant to be used in https://github.com/Graylog2/graylog-plugin-enterprise-integrations/pull/1058
N/A
=> Add vendor_subtype GIM schema field

changelog/unreleased/pr-15539.toml, graylog2-server/src/main/java/org/graylog/plugins/views/search/Search.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/SearchEntity.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/SearchTest.java, graylog2-web-interface/src/components/PluggableStoreProvider.tsx, graylog2-web-interface/src/views/hooks/useQueryIds.test.tsx, graylog2-web-interface/src/views/hooks/useQueryIds.ts, graylog2-web-interface/src/views/logic/slices/viewSlice.ts
**Note:** This PR needs to be backported to `5.1`, parts of it need to be backported to `5.0`.
This PR is a follow-up to #15352. In this PR, we changed the query order in the frontend to be derived from the order of view states in the view object, in an attempt to fix issues with views being exported to content packs showing the wrong tab order. This has proven wrong, as it introduces other regressions. The actual issue that needed to be addressed was that content packs exporting saved searches/dashboards are not keeping the query order in the associated search object.
This PR is therefore reverting #15341 and instead fixing the content pack export to keep queries in order when exporting a search.
Fixes #15528.
Refs #15341.
=> Making sure that query order is kept when exporting view to content pack.

changelog/unreleased/pr-15545.toml, graylog2-web-interface/src/views/components/GridGaps.test.ts, graylog2-web-interface/src/views/components/GridGaps.ts, graylog2-web-interface/src/views/components/WidgetGrid.tsx
**Note:** This requires a backport to `5.1`.
This PR is implementing a different approach for detecting gaps in the widget grid in order to create placeholders for inline widget creation.
Instead of detecting leading, trailing and intermediate gaps by comparing widgets to the boundaries of the grid and itself, it fills a m x n grid with markers for existing widgets. After that, it tries to fill rectangles of the biggest possible size in the unfilled spaces. It avoids creating placeholders for rectangles with a width lower than 2, as well as skipping empty rows between widgets.
This is supposed to avoid placement problems that we have seen in #15308 & #15538.
Fixes #15308.
Fixes #15538.
=> Use grid-based gap detection for placeholder creation.

changelog/unreleased/pr-15545.toml, changelog/unreleased/pr-15585.toml, graylog2-web-interface/src/views/components/GridGaps.test.ts, graylog2-web-interface/src/views/components/GridGaps.ts, graylog2-web-interface/src/views/components/WidgetGrid.tsx
**Note:** This is a backport of #15545 of `5.1`.
This PR is implementing a different approach for detecting gaps in the widget grid in order to create placeholders for inline widget creation.
Instead of detecting leading, trailing and intermediate gaps by comparing widgets to the boundaries of the grid and itself, it fills a m x n grid with markers for existing widgets. After that, it tries to fill rectangles of the biggest possible size in the unfilled spaces. It avoids creating placeholders for rectangles with a width lower than 2, as well as skipping empty rows between widgets.
This is supposed to avoid placement problems that we have seen in #15308 & #15538.
Fixes #15308.
Fixes #15538.
=> Use grid-based gap detection for placeholder creation. (`5.1`)

graylog2-web-interface/src/views/logic/slices/viewSlice.ts
This PR makes sure that when queries are reordered, the search is
persisted with a new id. This prevents other dashboards referencing the
original search to be affected by the change.
/nocl
=> Assign search new id when reordering queries.

changelog/unreleased/issue-15536.toml, graylog2-web-interface/src/routing/AppRouter.tsx
**Note:** This is a backport of #15540 to `5.1`.
While migrating to `react-router` v6, a programmatic error sneaked in that prevents the root path to be properly suffixed if the user configures a custom path suffix (either through the config file or an HTTP header).
This PR is now making sure that the router's root path is also suffixed with the custom path, preventing the error to show up.
Fixes #15536.
=> Properly prefix frontend route path if custom path suffix is configured. (`5.1`)

graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/PivotEntity.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/SearchEntity.java
This is a follow-up to #15539, which took care of keeping the order of queries when _exporting_ content packs. This PR is making sure that the order is kept when _importing_ content packs, as well as fixing the import of row/column limits for pivot aggregations, where previously a `null` value was interpreted as `0`.
Refs #15528.
/nocl
=> Keep order and pivot limits when importing content packs.

changelog/unreleased/issue-15547.toml, graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardsOverview.test.tsx, graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardsOverview.tsx
_Please note, this PR needs a backport for 5.1_
This PR is fixing a problem with the dashboards overview. Before this change we were not using the search query provided by the URL params for the search input. The URL params were already being updated when changing the value of the search input.
Fixes https://github.com/Graylog2/graylog2-server/issues/15547
=> Use search query from URL params for dashboard page search input.

changelog/unreleased/issue-15547.toml, graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardsOverview.test.tsx, graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardsOverview.tsx
_Please note, this is a backport of #15589 for 5.1_
This PR is fixing a problem with the dashboards overview. Before this change we were not using the search query provided by the URL params for the search input. The URL params were already being updated when changing the value of the search input.
Fixes https://github.com/Graylog2/graylog2-server/issues/15547
=> Use search query from URL params for dashboard page search input. (backport of #15589 for 5.1)

changelog/unreleased/pr-15539.toml, graylog2-server/src/main/java/org/graylog/plugins/views/search/Search.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/SearchEntity.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/SearchTest.java, graylog2-web-interface/src/components/PluggableStoreProvider.tsx, graylog2-web-interface/src/views/hooks/useQueryIds.test.tsx, graylog2-web-interface/src/views/hooks/useQueryIds.ts, graylog2-web-interface/src/views/logic/slices/viewSlice.ts
**Note:** This is a backport of #15539 to `5.1`.
This PR is a follow-up to #15352. In this PR, we changed the query order in the frontend to be derived from the order of view states in the view object, in an attempt to fix issues with views being exported to content packs showing the wrong tab order. This has proven wrong, as it introduces other regressions. The actual issue that needed to be addressed was that content packs exporting saved searches/dashboards are not keeping the query order in the associated search object.
This PR is therefore reverting #15341 and instead fixing the content pack export to keep queries in order when exporting a search.
Fixes #15528.
Refs #15341.
=> Making sure that query order is kept when exporting view to content pack. (`5.1`)

changelog/unreleased/issue-15509.toml, graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/buckets/Values.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/AggregationConfigDTO.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/PivotDTO.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/ValueConfigDTO.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/dashboardV1/EntityConverter.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/PivotEntity.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/ViewEntity.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/WidgetEntity.java
**Note:** This is a backport of #15523 to `5.1`.
This PR is adding the required changes to make sure that if a previous row/column limit is existing in saved search/dashboard of a content pack, this limit will be applied to value pivots. This makes sure that content packs created from pre-5.1 versions containing saved searches/dashboards are installed correctly.
Fixes #15509.
Fixes Graylog2/graylog-plugin-enterprise#5205.
=> Apply previous row/column limits to pivots when installing from content pack. (`5.1`)

changelog/unreleased/issue-15519.toml, graylog2-web-interface/src/views/logic/slices/viewSlice.ts
**Note:** This PR needs a backport to `5.1`.
This PR is fixing an issue where using the "Add to query"/"Exclude from query" value actions are not executing the search when used on dashboards.
This is being fixed by making sure that the `updateQueryString` is consistent in that it executes the search regardless if it is being called on a saved search or a dashboard.
Fixes #15519.
=> Execute search when global query override is set.

changelog/unreleased/pr-15539.toml, changelog/unreleased/pr-15584.toml, graylog2-server/src/main/java/org/graylog/plugins/views/search/Search.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/SearchEntity.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/SearchTest.java
**Note:** This is a backport of #15539 to `5.0`.
This PR fixing that content packs exporting saved searches/dashboards are not keeping the query order in the associated search object.
Fixes #15528.
=> Making sure that query order is kept when exporting view to content pack. (`5.0`)

graylog2-server/src/main/java/org/graylog/schema/VendorFields.java
Backport https://github.com/Graylog2/graylog2-server/pull/15535 to the `5.1` branch.
/nocl
=> Define vendor_subtype GIM field (5.1)

graylog2-server/src/main/java/org/graylog/schema/VendorFields.java
Backport https://github.com/Graylog2/graylog2-server/pull/15535 to the `5.0` branch.
/nocl
=> Define vendor_subtype GIM field (5.0)

data-node/src/main/java/org/graylog/datanode/management/CommandLineProcess.java, data-node/src/main/java/org/graylog/datanode/management/ManagableProcess.java, data-node/src/main/java/org/graylog/datanode/management/OpensearchDynamicConfiguration.java, data-node/src/main/java/org/graylog/datanode/management/OpensearchProcessImpl.java, data-node/src/main/java/org/graylog/datanode/management/OpensearchProcessService.java, data-node/src/main/java/org/graylog/datanode/management/ProcessWatchdog.java, data-node/src/main/java/org/graylog/datanode/periodicals/OpensearchNodeHeartbeat.java, data-node/src/main/java/org/graylog/datanode/process/ProcessState.java, data-node/src/main/java/org/graylog/datanode/process/ProcessStateMachine.java, data-node/src/main/java/org/graylog/datanode/rest/StatusController.java, data-node/src/test/java/org/graylog/datanode/management/ProcessWatchdogTest.java, data-node/src/test/java/org/graylog/datanode/management/TestableProcess.java, data-node/src/test/java/org/graylog/datanode/process/ProcessStateMachineTest.java
/nocl
This PR add a `startWithConfig` method that will start the opensearch process. The start may be delayed or triggered anytime, based on configuration change.
Needed for postponing opensearch startup till the TLS configuration is available.
=> Delay opensearch start till configuration is available

changelog/unreleased/issue-9917.toml, graylog2-server/src/main/java/org/graylog2/outputs/GelfOutput.java, graylog2-server/src/main/java/org/graylog2/outputs/OutputRegistry.java, graylog2-server/src/test/java/org/graylog2/outputs/GelfOutputTest.java, graylog2-server/src/test/java/org/graylog2/outputs/OutputRegistryTest.java
Switch from GelfTransport#send() to GelfTransport#trySend() to avoid blocking output threads. We retry the send operation as long as the output is running.
This fixes an issue where removing an output from a stream or deleting it doesn't unblock processing. (with a slow output target)
A race condition in OutputRegistry was contributing to the problem.
When the OutputRegistry didn't have a cached output instance, we loaded the output configuration from the database and started the output. The problem is that each message holds a stream object that might be outdated because the output could have been removed since adding the stream object to the message object.
So instead of just starting an output, we need to check if the output is still assigned to the stream.
Fixes #9917
Fixes …
=> Fix GELF output blocking and output processing race condition

changelog/unreleased/pr-15504.toml, changelog/unreleased/pr-15651.toml, graylog2-server/src/main/java/org/graylog2/rest/resources/system/SlidingExpirationCookieFilter.java, graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java
**Note:** This is a backport of #15504 to `5.0`.
Prior to this PR, the `authentication` cookie set when authenticating via `POST /api/system/sessions` had a max-age defined by the session lifetime of the user. This max-age was unfortunately not extended by subsequent request, leading to early logout (due to the browser invalidating the cookie) in the frontend, although the session was still valid, unless the user performed a full-page refresh.
This PR is changing this by adding a sliding expiration mechanism extending the max-age of the cookie on every request that does not disable session extension.
Fixes #15502.
=> Sliding expiration for authentication cookie. (`5.0`)

graylog2-server/src/main/java/org/graylog/security/certutil/CertutilCa.java, graylog2-server/src/main/java/org/graylog/security/certutil/csr/CertificateAndPrivateKeyMerger.java, graylog2-server/src/main/java/org/graylog/security/certutil/keystore/storage/KeystoreFileStorage.java, graylog2-server/src/main/java/org/graylog/security/certutil/keystore/storage/KeystoreMongoStorage.java, graylog2-server/src/main/java/org/graylog/security/certutil/keystore/storage/KeystoreStorage.java, graylog2-server/src/main/java/org/graylog/security/certutil/keystore/storage/SmartKeystoreStorage.java, graylog2-server/src/main/java/org/graylog/security/certutil/keystore/storage/location/KeystoreFileLocation.java, graylog2-server/src/main/java/org/graylog/security/certutil/keystore/storage/location/KeystoreLocation.java, graylog2-server/src/main/java/org/graylog/security/certutil/keystore/storage/location/KeystoreMongoCollection.java, graylog2-server/src/main/java/org/graylog/security/certutil/keystore/storage/location/KeystoreMongoCollections.java, graylog2-server/src/main/java/org/graylog/security/certutil/keystore/storage/location/KeystoreMongoLocation.java, graylog2-server/src/main/java/org/graylog2/cluster/certificates/CertificatesService.java, graylog2-server/src/test/java/org/graylog2/cluster/certificates/CertificatesServiceTest.java
Refactoring keystore storage.
1. Client code does not have to pick KeystoreStorage implementation, instead location object for storage is created and passed to SmartKeystoreStorage, which can pick proper implementation by itself.
2. CertificateService becomes more universal (and who knows, maybe it can be made even more universal than that...).
/nocl
=> Refactoring keystore storage

changelog/unreleased/pr-15504.toml, changelog/unreleased/pr-15650.toml, graylog2-server/src/main/java/org/graylog2/rest/resources/system/SlidingExpirationCookieFilter.java, graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java
**Note:** This is a backport of #15504 to `5.1`.
Prior to this PR, the `authentication` cookie set when authenticating via `POST /api/system/sessions` had a max-age defined by the session lifetime of the user. This max-age was unfortunately not extended by subsequent request, leading to early logout (due to the browser invalidating the cookie) in the frontend, although the session was still valid, unless the user performed a full-page refresh.
This PR is changing this by adding a sliding expiration mechanism extending the max-age of the cookie on every request that does not disable session extension.
Fixes #15502.
=> Sliding expiration for authentication cookie. (`5.1`)

changelog/unreleased/issue-15642.toml, graylog2-web-interface/src/views/hooks/BindSearchParamsFromQuery.test.ts, graylog2-web-interface/src/views/hooks/BindSearchParamsFromQuery.ts
**Note:** This PR requires a backport to `5.1`.
Prior to this PR, when manipulating the query of a saved search through URL parameters did not work. The reason for this is that the in-memory query was manipulated, but the search was not saved.
This PR is now making sure that if the query is manipulated through URL parameters, a new search will be created and saved.
Fixes #15642.
=> Save modified search when query is changed through URL parameters.

changelog/unreleased/issue-15652.toml, graylog2-server/src/main/java/org/graylog/security/authservice/backend/ADAuthServiceBackend.java
Use `mail` as the hardcoded email attribute for AD user sync. This is the behavior through version 5.0 and was inadvertently broken in 5.1.
See linked issue for details.
Fixed #15652
=> Use correct email attribute for AD users

data-node/src/main/java/org/graylog/datanode/bindings/ServerBindings.java, data-node/src/main/java/org/graylog/datanode/bootstrap/preflight/DataNodePreflightGeneratePeriodical.java, data-node/src/main/java/org/graylog/datanode/configuration/certificates/KeystoreReEncryption.java, data-node/src/test/java/org/graylog/datanode/configuration/TruststoreCreatorTest.java, graylog2-server/src/main/java/org/graylog/security/certutil/CertutilCa.java, graylog2-server/src/main/java/org/graylog/security/certutil/keystore/storage/KeystoreContentMover.java, graylog2-server/src/main/java/org/graylog/security/certutil/keystore/storage/KeystoreFileStorage.java, graylog2-server/src/main/java/org/graylog/security/certutil/keystore/storage/KeystoreMongoStorage.java, graylog2-server/src/main/java/org/graylog/security/certutil/keystore/storage/KeystoreStorage.java, graylog2-server/src/main/java/org/graylog/security/certutil/keystore/storage/PrivateKeyEntryOnlyKeystoreContentMover.java, graylog2-server/src/main/java/org/graylog/security/certutil/keystore/storage/SmartKeystoreStorage.java, graylog2-server/src/test/java/org/graylog/security/certutil/keystore/storage/KeystoreFileStorageTest.java
Works on some assumptions:
- password for keystore and private keys are the same,
- keystore contains only private-key entries (PK with cert. chain)
Significant change: when writing keystore, you have to provide both original and new password.
The problem with old approach was that it kept old password for PK, and changed password for keystore only.
Now we have a class that moves keystore entries as well, changing their passwords in the process.
/nocl
=> OTR Reencryption and Key Storage refactoring for password change

changelog/unreleased/issue-15638.toml, graylog2-server/src/main/java/org/graylog/plugins/views/favorites/FavoritesService.java, graylog2-server/src/main/java/org/graylog/plugins/views/startpage/lastOpened/LastOpenedService.java, graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java, graylog2-server/src/main/java/org/graylog2/migrations/V20230531135500_MigrateRemoveObsoleteItemsFromGrantsCollection.java, graylog2-server/src/test/java/org/graylog/plugins/views/favorites/FavoriteServiceTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/startpage/StartPageServiceTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/startpage/lastOpened/LastOpenedServiceTest.java, graylog2-server/src/test/java/org/graylog2/migrations/V20230531135500_MigrateRemoveObsoleteItemsFromGrantsCollectionTest.java, graylog2-server/src/test/resources/org/graylog2/migrations/V20230531135500_MigrateRemoveObsoleteItemsFromGrantsCollectionTest_noElements.json, graylog2-server/src/test/resources/org/graylog2/migrations/V20230531135500_MigrateRemoveObsoleteItemsFromGrantsCollectionTests.json
Favorite and LastOpened were registered as full entities, which led to errors on the "shared items" list for users because they are no real manageable entities and have no routes in the FE to be edited. 
Solution is: not register these items as full entities.
** backport to 5.1 from #15658 **
fixes #15574 #15638
=> Fixed LastOpened and Favorite items to not show up in internal entity lists (backport 5.1)

changelog/unreleased/issue-15638.toml, graylog2-server/src/main/java/org/graylog/plugins/views/favorites/FavoritesService.java, graylog2-server/src/main/java/org/graylog/plugins/views/startpage/lastOpened/LastOpenedService.java, graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java, graylog2-server/src/main/java/org/graylog2/migrations/V20230531135500_MigrateRemoveObsoleteItemsFromGrantsCollection.java, graylog2-server/src/test/java/org/graylog/plugins/views/favorites/FavoriteServiceTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/startpage/StartPageServiceTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/startpage/lastOpened/LastOpenedServiceTest.java, graylog2-server/src/test/java/org/graylog2/migrations/V20230531135500_MigrateRemoveObsoleteItemsFromGrantsCollectionTest.java, graylog2-server/src/test/resources/org/graylog2/migrations/V20230531135500_MigrateRemoveObsoleteItemsFromGrantsCollectionTest_noElements.json, graylog2-server/src/test/resources/org/graylog2/migrations/V20230531135500_MigrateRemoveObsoleteItemsFromGrantsCollectionTests.json
Favorite and LastOpened were registered as full entities, which led to errors on the "shared items" list for users because they are no real manageable entities and have no routes in the FE to be edited. 
Solution is: not register these items as full entities.
**Note: needs backport to 5.1**
fixes #15574 #15638
=> Fixed LastOpened and Favorite items to not show up in internal entity lists

graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/MongoDBPreflightCheck.java
Adds a missing `implements PreflightCheck` to `MongoDBPreflightCheck`
/nocl
=> Let MongoDBPreflightCheck implement PreflightCheck interface

changelog/unreleased/issue-15642.toml, graylog2-web-interface/src/views/hooks/BindSearchParamsFromQuery.test.ts, graylog2-web-interface/src/views/hooks/BindSearchParamsFromQuery.ts
**Note:** This is a backport of #15653 to `5.1`.
Prior to this PR, when manipulating the query of a saved search through URL parameters did not work. The reason for this is that the in-memory query was manipulated, but the search was not saved.
This PR is now making sure that if the query is manipulated through URL parameters, a new search will be created and saved.
Fixes #15642.
=> Save modified search when query is changed through URL parameters. (`5.1`)

graylog2-server/src/main/java/org/graylog/plugins/map/geoip/GeoLocationInformation.java
Adds AutoValue.Builder to GeoLocationInformation.
/nocl as current behavior is unchanged
Builder is needed elsewhere in code to serialize GeoLocationInformation objects
=> Add Builder for GeoLocationInformation class

graylog2-web-interface/src/components/common/EntityDataTable/contexts/ExpandedSectionsProvider.tsx
When using an expanded section with a name different than `rules`, it is not displayed. this was caused by the `rules` name being hardcoded in the `ExpandedSectionsProvider`. This PR is fixing that.
/nocl
=> Fix Entity Datable expanded section 

data-node/pom.xml, graylog2-server/pom.xml
Fix problems using the graylog2-tests.jar in the data node.
/nocl
=> Fixing the lifecycle phase for antrun in DataNode so that the test-jar is not pulled in during the wrong phase

graylog2-server/src/main/java/org/graylog2/security/MongoDbSession.java, graylog2-server/src/main/java/org/graylog2/security/MongoDbSessionDAO.java
A customer had problems logging in and found the following constellation in MongoDB for a session:
`
{
"attributes" : {
},
}
`
instead of `"attributes" : BinData(0, "rO0ABXNyABFqYXZhLnV...`
This created problems during login:
```cluster-graylog3-1     | 2023-06-19 11:44:42,787 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
cluster-graylog3-1     | java.lang.ClassCastException: class com.mongodb.BasicDBObject cannot be cast to class [B (com.mongodb.BasicDBObject is in unnamed module of loader 'app'; [B is in module java.base of loader 'bootstrap')
cluster-graylog3-1     | 	at org.graylog2.security.MongoDbSession.getAttributes(MongoDbSession.java:69) ~[graylog.jar:?]
cluster-graylog3-1     | 	at …
```
=> Fix wrong attribute in session

graylog2-web-interface/src/components/bootstrap/Tooltip.jsx, graylog2-web-interface/src/components/common/DataTable/DataTable.jsx, graylog2-web-interface/src/components/common/ExpandableList.tsx
This PR is fixing a few cases where `className` is used in a template string, but could be undefined.
We ensure it no longer can be undefined. This is a good practice since `${undefined}` result in the following string: `undefined`.
/nocl
=> Ensure className prop is not undefined when using it in template string.

graylog2-web-interface/package.json, graylog2-web-interface/packages/jest-preset-graylog/package.json
With this PR we are moving the `@testing-library/user-event` dependency into the `jest-preset-graylog` package, since the package contains all test related dependencies.
/nocl
=> Move `@testing-library/user-event` into `jest-preset-graylog` package.

changelog/unreleased/issue-14661.toml, full-backend-tests/src/test/java/org/graylog/plugins/views/aggregations/SearchAggregationsIT.java, full-backend-tests/src/test/resources/org/graylog/plugins/views/aggregations/random-http-logs.json, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/pivot/buckets/OSValuesHandler.java
**Note:** This needs a backport to `5.0` and `5.1`.
Prior to this PR, in aggregations on Opensearch 2.4+, boolean field values were returned as [`1` or `0` instead of `true` or `false`](https://opensearch.org/docs/2.3/opensearch/supported-field-types/boolean/#boolean-values-in-aggregations-and-scripts). This is related to the way extraction of keys from multi-terms aggregations was implemented. This PR is fixing this and making sure that `Bucket#getKeyAsString` is used.
Fixes #14661.
=> Make sure that `boolean` fields are returned as `true`|`false` in aggregations.

changelog/unreleased/issue-14661.toml, full-backend-tests/src/test/java/org/graylog/plugins/views/aggregations/SearchAggregationsIT.java, full-backend-tests/src/test/resources/org/graylog/plugins/views/aggregations/random-http-logs.json, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/pivot/buckets/OSValuesHandler.java
**Note:** This is a backport of #15809 to `5.1`
Prior to this PR, in aggregations on Opensearch 2.4+, boolean field values were returned as [`1` or `0` instead of `true` or `false`](https://opensearch.org/docs/2.3/opensearch/supported-field-types/boolean/#boolean-values-in-aggregations-and-scripts). This is related to the way extraction of keys from multi-terms aggregations was implemented. This PR is fixing this and making sure that `Bucket#getKeyAsString` is used.
Fixes #14661.
=> Make sure that `boolean` fields are returned as `true`|`false` in aggregations. (`5.1`)

graylog2-server/src/main/java/org/graylog2/bindings/MessageOutputBindings.java
Use an optional binding for the default output so that plugins can specify their own binding.
/nocl
=> Use optional binding for default message output

graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerFactory.java
This change lets tests fail early on guice errors instead of waiting for the timeout.
/nocl
=> Let server container fail on guice errors

graylog2-web-interface/docs/StyleGuideWrapper.tsx
Previously, the router wrapping components in the frontend component gallery had only a single route with a static path (`/`) configured, leading to errors with components when deployed, as the path is different (`/frontend-documentation`). This PR is adding an optional path suffix to the route.
/nocl
=> Make path suffix optional in frontend gallery router.

changelog/unreleased/issue-11868.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/Join.java
We cannot use `end` because it's a reserved keyword in the pipeline language and causes a syntax error.
Instead of adding special handling for the `end` keyword to the pipeline rule language we just rename the parameter to `endIndex`.
This shouldn't break existing rules, because they could've never been saved.
Fixes #11868
The substring function got already fixed by #15470 and should be included in a backport.
=> Fix join pipeline function parameter name

changelog/unreleased/issue-15884.toml, graylog2-web-interface/src/components/login/LoginChrome.tsx
**Note:** This is a backport of #15887 to `5.1`.
This PR is decreasing the z-index of the login background so it does not cover the public notifications shown on the login page.
Fixes #15884.
=> Decreasing z-index of login background. (`5.1`)

changelog/unreleased/issue-12165.toml, graylog2-web-interface/src/views/components/searchbar/queryinput/QueryInput.tsx, graylog2-web-interface/src/views/components/searchbar/queryinput/ace-types.ts
**Please note:** this  PR needs a backport for `5.0` and `5.1`.
Before this change we were showing the query input suggestions on every `tokenizerUpdate`. This event will be triggered even when we extend the query by using the "Add to query" field value action.
With this change we also consider if the query input is focussed and only show suggestions in this case.
Fixes https://github.com/Graylog2/graylog2-server/issues/12165
=> Only display query input suggestions while input has focus.

changelog/unreleased/issue-15084.toml, graylog2-web-interface/src/views/components/visualizations/GenericPlot.tsx
**Please note:** This PR needs a backport for 5.0 and 5.1
Before this change the hover labels in aggregations were sometimes hard to read.
Before:
After:
Fixes https://github.com/Graylog2/graylog2-server/issues/15084
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/4337
=> Improve readability of hover legend in aggregations.

graylog2-web-interface/src/views/components/aggregationbuilder/EmptyAggregationContent.tsx, graylog2-web-interface/src/views/components/aggregationwizard/ElementsConfigurationActions.tsx, graylog2-web-interface/src/views/components/widgets/SaveOrCancelButtons.tsx
As described in https://github.com/Graylog2/graylog2-server/issues/10921 the info we display for empty aggregations contained outdated button names. This PR is updating the text.
Fixes https://github.com/Graylog2/graylog2-server/issues/10921
/nocl
=> Update info text for empty aggregations.

changelog/unreleased/issue-12165.toml, graylog2-web-interface/src/views/components/searchbar/queryinput/QueryInput.tsx, graylog2-web-interface/src/views/components/searchbar/queryinput/ace-types.ts
**Please note:** this is a backport of #15885 for `5.1`.
Before this change we were showing the query input suggestions on every `tokenizerUpdate`. This event will be triggered even when we extend the query by using the "Add to query" field value action.
With this change we also consider if the query input is focussed and only show suggestions in this case.
Fixes https://github.com/Graylog2/graylog2-server/issues/12165
=> Only display query input suggestions while input has focus (backport of #15885 for `5.1`).

changelog/unreleased/issue-12165.toml, graylog2-web-interface/src/views/components/searchbar/queryinput/QueryInput.tsx, graylog2-web-interface/src/views/components/searchbar/queryinput/ace-types.ts
**Please note:** this is a backport of #15885 for `5.0`.
Before this change we were showing the query input suggestions on every `tokenizerUpdate`. This event will be triggered even when we extend the query by using the "Add to query" field value action.
With this change we also consider if the query input is focussed and only show suggestions in this case.
Fixes https://github.com/Graylog2/graylog2-server/issues/12165
=> Only display query input suggestions while input has focus (backport of #15885 for `5.0`).

changelog/unreleased/issue-15084.toml, graylog2-web-interface/src/views/components/visualizations/GenericPlot.tsx
**Please note:** This is a backport of #15888 for `5.1`.
Before this change the hover labels in aggregations were sometimes hard to read.
Before:
After:
Fixes https://github.com/Graylog2/graylog2-server/issues/15084
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/4337
=> Improve readability of hover legend in aggregations. (backport of #15888 for `5.1`)

changelog/unreleased/issue-15084.toml, graylog2-web-interface/src/views/components/visualizations/GenericPlot.tsx
**Please note:** This is a backport of #15888 for `5.0`.
Before this change the hover labels in aggregations were sometimes hard to read.
Before:
After:
Fixes https://github.com/Graylog2/graylog2-server/issues/15084
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/4337
=> Improve readability of hover legend in aggregations. (backport of #15888 for `5.0`)

changelog/unreleased/issue-11868.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/Join.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/Substring.java
We cannot use `end` because it's a reserved keyword in the pipeline language and causes a syntax error.
Instead of adding special handling for the `end` keyword to the pipeline rule language we just rename the parameter to `indexEnd`.
This shouldn't break existing rules, because they could've never been saved.
Fixes #11868
(cherry picked from commit af1a0879f75f93e605c2adf1e239dacc8dd097c4)
=> Fix join / substring pipeline function parameter name (#15891)

changelog/unreleased/issue-15778.toml, graylog2-web-interface/src/views/components/Value.tsx, graylog2-web-interface/src/views/components/visualizations/PlotLegend.tsx
**Note:** This is a backport of #15864 to `5.1`.
This PR is fixing an issue when the `Value` component is used in non-interactive modes (e.g. full screen mode). The underlying reason is that the `Value` component is not passing the `render` prop when in non-interactive, leading to type/user-specific formattings being skipped.
Fixes #15778.
=> Making value rendering consistent. (`5.1`)

changelog/unreleased/issue-15913.toml, graylog2-web-interface/src/contexts/DefaultQueryClientProvider.tsx, graylog2-web-interface/src/contexts/LoginQueryClientProvider.tsx, graylog2-web-interface/test/DefaultQueryClientProvider.tsx
**Note:** This needs a backport to `5.0` & `5.1`.
This PR is setting the default [Network Mode](https://tanstack.com/query/v4/docs/react/guides/network-mode) to `always` for TanStack Query. This disables pausing of requests when offline detection kicks in. Offline detection kicking in although not desired has been reported for users on isolated networks using Firefox.
Fixes #15913.
=> Setting `networkMode` to `always` for TanStack Query.

changelog/unreleased/issue-15913.toml, graylog2-web-interface/src/contexts/DefaultQueryClientProvider.tsx, graylog2-web-interface/src/contexts/LoginQueryClientProvider.tsx
**Note:** This is a backport of #15914 to `5.0`.
This PR is setting the default [Network Mode](https://tanstack.com/query/v4/docs/react/guides/network-mode) to `always` for TanStack Query. This disables pausing of requests when offline detection kicks in. Offline detection kicking in although not desired has been reported for users on isolated networks using Firefox.
Fixes #15913.
=> Setting `networkMode` to `always` for TanStack Query. (`5.0`)

changelog/unreleased/issue-15913.toml, graylog2-web-interface/src/contexts/DefaultQueryClientProvider.tsx, graylog2-web-interface/src/contexts/LoginQueryClientProvider.tsx, graylog2-web-interface/test/DefaultQueryClientProvider.tsx
**Note:** This is a backport of #15914 to `5.1`.
This PR is setting the default [Network Mode](https://tanstack.com/query/v4/docs/react/guides/network-mode) to `always` for TanStack Query. This disables pausing of requests when offline detection kicks in. Offline detection kicking in although not desired has been reported for users on isolated networks using Firefox.
Fixes #15913.
=> Setting `networkMode` to `always` for TanStack Query. (`5.1`)

graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailEventNotificationConfig.java, graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationForm.jsx
With this PR we are fixing an error which slipped in with https://github.com/Graylog2/graylog2-server/pull/15922. Since the `http_external_uri` always ends with a slash, we do not need to include in the altert replay URL.
/nocl
=> Fix link for alert replay in mail notification template.

changelog/unreleased/issue-15718.toml, graylog2-web-interface/src/views/components/searchbar/queryinput/QueryInput.tsx, graylog2-web-interface/src/views/components/searchbar/queryinput/ace-types.ts
**Please note:** This PR needs a backport for `5.0` and `5.1`.
As described in #15718 it is possible that the focus for an option in the query input autocompletion gets lost.
This problem occurs because we triggered `editor.execCommand('startAutocomplete');`, even when the autocompletion popover is already visible. Related to https://github.com/Graylog2/graylog2-server/pull/14233.
Fixes #15718
=> Only trigger query input autocompletion popover when it is hidden.

data-node/src/main/java/org/graylog/datanode/bootstrap/ServerBootstrap.java, graylog2-server/src/main/java/org/graylog2/bootstrap/ServerBootstrap.java, graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/MongoDBPreflightCheck.java, graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/PreflightWebModule.java, graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/web/resources/CertificateRenewalPolicyResource.java, graylog2-server/src/main/java/org/graylog2/plugin/certificates/RenewalPolicy.java, graylog2-web-interface/package.json, graylog2-web-interface/src/preflight/Constants.ts, graylog2-web-interface/src/preflight/components/ConfigurationWizard/ConfigurationWizard.tsx, graylog2-web-interface/src/preflight/components/ConfigurationWizard/RenewalPolicyConfiguration.tsx, graylog2-web-interface/src/preflight/components/common/Select.tsx, graylog2-web-interface/src/preflight/components/common/index.ts, graylog2-web-interface/src/preflight/components/common/mantine/imports.ts, graylog2-web-interface/src/preflight/hooks/useConfigurationStep.test.tsx, graylog2-web-interface/src/preflight/hooks/useConfigurationStep.tsx, graylog2-web-interface/src/preflight/hooks/useRenewalPolicy.ts, graylog2-web-interface/src/preflight/types.ts, graylog2-web-interface/yarn.lock
This PR is adding the UI & backend capabilities to configure a simple renewal policy for certificates during certificate provisioning in the pre-flight UI. Currently, it requires configuring:
- a renewal mode: automatic or manual
- the certificate lifetime
/nocl
=> Add renewal policy configuration to pre-flight UI.

changelog/unreleased/issue-15718.toml, graylog2-web-interface/src/views/components/searchbar/queryinput/QueryInput.tsx, graylog2-web-interface/src/views/components/searchbar/queryinput/ace-types.ts
**Please note:** This is a backport of #15933 for `5.0`.
As described in #15718 it is possible that the focus for an option in the query input autocompletion gets lost.
This problem occurs because we triggered `editor.execCommand('startAutocomplete');`, even when the autocompletion popover is already visible. Related to https://github.com/Graylog2/graylog2-server/pull/14233.
Fixes #15718
=> Only trigger query input autocompletion popover when it is hidden. (`5.0`)

graylog2-web-interface/src/components/common/TimeUnitInput.jsx, graylog2-web-interface/src/components/configurations/CertificateRenewalPolicyConfig.tsx, graylog2-web-interface/src/components/configurations/ConfigurationTypes.ts, graylog2-web-interface/src/pages/ConfigurationsPage.tsx
**Note:** This PR is based on #15882, which should be merged first.
This PR is adding a configlet that allows the user to configure the current certificate renewal policy.
/nocl
=> Allow configuring certificate renewal policy through system configurations.

graylog2-server/src/main/java/org/graylog2/plugin/Message.java
Return the more specific collection type. This is a non-breaking change and allows us to use the returned Set without casting or copying.
/nocl
=> Return Set instead of Collection from Message#getStreamIds

graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ClientES7.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/testing/ClientOS2.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/testing/OpenSearchInstance.java, graylog2-server/src/test/java/org/graylog/testing/containermatrix/SearchServer.java, graylog2-server/src/test/java/org/graylog/testing/elasticsearch/Client.java, graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesIT.java
In order to successfully release the cluster index create block, we need to decrease `cluster.routing.allocation.disk.reroute_interval` for Opensearch 2.6+. 
With this minimal change, we are now able to run all the integration tests with OS 2.6 and 2.8. 
Opensearch 2.8. becomes our default OS version for integration tests.
/nocl
Existing set of ITs.
=> Update opensearch to 2.8, adapt to cluster block settings

changelog/unreleased/issue-15472.toml, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TimeRangePicker.test.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TimeRangePicker.tsx
**Please note:** this PR requires a backport for `5.0` and `5.1`
Before this change a keyword time range in the search bar form could have not needed `from` and `to` attributes. These attributes:
- change when you reopen and submit the time range dropdown
- are not expected in the search bar form and will be removed from the form state in some cases
As a result the search bar form button was incorrectly displayed as dirty, in some cases (see https://github.com/Graylog2/graylog2-server/issues/15472)
Fixes: https://github.com/Graylog2/graylog2-server/issues/15471
Fixes: https://github.com/Graylog2/graylog2-server/issues/15472
=> Correctly normalize keyword time range for search bar form when selecting keyword time range.

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/buckets/ESTimeHandler.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/pivot/buckets/OSTimeHandler.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/views/searchtypes/pivot/buckets/OSTimeHandlerTest.java
Fixes #14906.
Current approach did not work well with auto interval and long time ranges (like "All time"), especially for relatively fresh systems.
The biggest interval was 1 month, while "All time" means around 50 years in GL... So all data used to land in 1 bucket.
The implementation has been changed, so that AutoDateHistogramAggregationBuilder is used. We allow ES/OS to select interval, do not do it ourselves for auto interval, just providing some clue for number of expected buckets, using `scaling` field.
/nocl
See #14906.
=> Better auto interval handling

data-node/src/test/java/org/graylog/datanode/integration/DatanodeSecuritySetupIT.java, graylog2-server/src/main/java/org/graylog/security/certutil/CertutilCert.java, graylog2-server/src/main/java/org/graylog/security/certutil/CertutilHttp.java
/nocl
Fixing following problem:
```
2023-07-21T13:17:01.916Z] 2023-07-21 15:17:00,549 ERROR: 🐳 [local/graylog-datanode:latest] - Could not start container
[2023-07-21T13:17:01.916Z] com.github.dockerjava.api.exception.ConflictException: Status 409: {"message":"Conflict. The container name \"/graylog-datanode-host\" is already in use by container \"e92dade34bbad3e1acb520f2cd17a7dec6a0f9db4eb9ccf235579f3b5ccfefcb\". You have to remove (or rename) that container to be able to reuse that name."}
[2023-07-21T13:17:01.916Z] 
[2023-07-21T13:17:01.916Z] 	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:245) ~[testcontainers-1.17.6.jar:1.17.6]
```
Existing integration tests
=> Add suffix to docker datanode container name, for parallel runs

changelog/unreleased/issue-15472.toml, graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.test.tsx, graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx
**Please note:** this is a backport of 15938 for `5.0`.
Before this change a keyword time range in the search bar form could have not needed `from` and `to` attributes. These attributes:
- change when you reopen and submit the time range dropdown
- are not expected in the search bar form and will be removed from the form state in some cases
As a result the search bar form button was incorrectly displayed as dirty, in some cases (see https://github.com/Graylog2/graylog2-server/issues/15472)
Fixes: https://github.com/Graylog2/graylog2-server/issues/15471
Fixes: https://github.com/Graylog2/graylog2-server/issues/15472
=> Correctly normalize keyword time range for search bar form when selecting keyword (`5.0`)

changelog/unreleased/issue-15472.toml, graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.test.tsx, graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx
**Please note:** this is a backport of #15938 for `5.1`
Before this change a keyword time range in the search bar form could have not needed `from` and `to` attributes. These attributes:
- change when you reopen and submit the time range dropdown
- are not expected in the search bar form and will be removed from the form state in some cases
As a result the search bar form button was incorrectly displayed as dirty, in some cases (see https://github.com/Graylog2/graylog2-server/issues/15472)
Fixes: https://github.com/Graylog2/graylog2-server/issues/15471
Fixes: https://github.com/Graylog2/graylog2-server/issues/15472
=> Correctly normalize keyword time range for search bar form when selecting keyword time range. (`5.1`)

graylog2-web-interface/src/components/common/EntityDataTable/Constants.ts, graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionActions.tsx, graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotificationActions.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/StreamActions.tsx, graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardActions.tsx
In the past we had the problem that the naming of the "More action" button in entity lists varied.
With this PR we are creating a constant which can be reused in suitable lists.
/nocl
=> Implement constant for more actions title in entity lists.

changelog/unreleased/pr-16050.toml, graylog2-server/src/main/java/org/graylog/plugins/views/favorites/FavoritesService.java, graylog2-server/src/test/java/org/graylog/plugins/views/favorites/FavoritesServiceTest.java
When entity was added to the favorites, it was added to the end of the list. It meant that top of the favorites' list contained entities that had been added first to the list. It seemed wrong. From now on, the newly added entity will be shown on the top of the favorites' list.
As described in description section.
Manually.
=> Favorites sorting changed, newest favorites go first

graylog2-web-interface/src/components/errors/ReportedErrorBoundary.tsx, graylog2-web-interface/src/preflight/App.tsx, graylog2-web-interface/src/preflight/components/ErrorBoundary.tsx
With this PR we are implementing a simple error boundary for JS runtime error in the preflight UI.
Fixes: https://github.com/Graylog2/graylog2-server/issues/15867
/nocl
=> Create simple error boundary for preflight UI.

graylog2-web-interface/src/views/components/sidebar/NavItem.tsx, graylog2-web-interface/src/views/components/sidebar/Sidebar.test.tsx, graylog2-web-interface/src/views/components/sidebar/Sidebar.tsx, graylog2-web-interface/src/views/components/sidebar/SidebarNavigation.tsx
With this PR we are removing the search sidebar toggle, since there are many other ways to close the sidebar, like clicking on the section icon, the search title or (when not pinned) the transparent overlay.
Before:
After:
/nocl
=> Remove not needed search sidebar toggle.

graylog2-web-interface/src/components/common/ReactGridContainer.tsx, graylog2-web-interface/src/components/navigation/ThemeModeToggle.tsx, graylog2-web-interface/src/components/sidecars/common/ColorLabel.tsx, graylog2-web-interface/src/preflight/navigation/NavigationBrand.tsx, graylog2-web-interface/src/preflight/navigation/ThemeModeToggle.tsx
With this small refactoring we are replacing `withTheme` with `useTheme` where possible. Using the `useTheme` hook simplifies the code and we do not have to rely on `styled-components` type definitions regarding the component props.
/nocl
=> Replace `styled-components` `withTheme` with `useTheme` where possible.

data-node/src/main/java/org/graylog/datanode/management/OpensearchCommandLineProcess.java
If you want to start the DataNode/OpenSearch on macOS, you have to link the jdk.app into the OpenSearch folder so it can start. This modification takes care of it.
/nocl
=> DataNode: Fix to start DataNode inside IntelliJ on macOS

graylog2-server/src/main/java/org/graylog/security/certutil/CaServiceImpl.java, graylog2-server/src/main/java/org/graylog/security/certutil/keystore/storage/KeystoreFileStorage.java, graylog2-server/src/main/java/org/graylog/security/certutil/keystore/storage/KeystoreMongoStorage.java, graylog2-server/src/main/java/org/graylog/security/certutil/keystore/storage/KeystoreStorage.java, graylog2-server/src/main/java/org/graylog/security/certutil/keystore/storage/SmartKeystoreStorage.java, graylog2-server/src/main/java/org/graylog2/cluster/certificates/CertificatesService.java, graylog2-server/src/test/java/org/graylog2/cluster/certificates/CertificatesServiceTest.java
If we press the restart button in the UI, we want to remove the CA from MongoDB.
We do not remove a CA from the filesystem because that was configured manually by the user - so it should remain.
/nocl
=> DataNode: Remove CA from MongoDB on startover

changelog/unreleased/issue-15958.toml, graylog2-web-interface/src/views/components/useWidgetResults.ts, graylog2-web-interface/src/views/components/widgets/ErrorWidget.test.tsx, graylog2-web-interface/src/views/components/widgets/Widget.test.tsx, graylog2-web-interface/src/views/components/widgets/WidgetPropTypes.tsx, graylog2-web-interface/src/views/logic/SearchResult.ts, graylog2-web-interface/src/views/logic/slices/executeSearch.ts
**Please note**: this PR needs a backport for `5.0` and `5.1`
As described in #15958 we currently just show a loading spinner when loading a saved search or dashboard  which exceeds the query limit. With this PR we are showing the error message again.
Fix #15958
=> Show errors again when loading a saved search or dashboard which exceeds the query limit

graylog2-server/src/main/java/org/graylog/plugins/views/favorites/FavoritesService.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewResolverDecoder.java, graylog2-server/src/main/java/org/graylog/plugins/views/startpage/StartPageService.java, graylog2-server/src/main/java/org/graylog/plugins/views/startpage/title/StartPageItemTitleRetriever.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/permissions/SearchUserTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewsResourceTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/views/ViewResolverDecoderTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/startpage/StartPageServiceTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/startpage/title/StartPageItemTitleRetrieverTest.java
Separator for "resolvable"/"special" view IDs has been changed, so that it does not break GRN rules.
Security Views are registered in Favorite and Last Opened lists.
Their titles are obtained in a direct way, bypassing Catalog, where they are not registered.
Links from Favorite and Last Opened lists point to Security Views.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#5527
/nocl
See https://github.com/Graylog2/graylog-plugin-enterprise/issues/5145
Manually.
=> Security Views can be added to favourites

changelog/unreleased/issue-16076.toml, graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java, graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java
Revert
https://github.com/Graylog2/graylog2-server/pull/14592
and allow
https://ciphersuite.info/cs/TLS_RSA_WITH_AES_128_GCM_SHA256/ https://ciphersuite.info/cs/TLS_RSA_WITH_AES_256_GCM_SHA384/
by default again.
This should fix comptibility issues with Windows Server 2019 and older OS.
(cherry picked from commit 03e93946c4cec8370bbdab140e434b156a43a38f)
=> Re-enable weak TLS ciphers for backwards compatibility (5.1 backport)

changelog/unreleased/pr-16019.toml, graylog2-server/src/main/java/org/graylog2/rest/models/roles/responses/RoleResponse.java
Resolves #16019 
Mark required fields in `JsonCreator` of class `RoleResponse`. Otherwise they show up as optional in Swagger, which is confusing and wrong.
=> Mark required fields in RoleResponse

changelog/unreleased/pr-16092.toml, graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterLoggersResource.java
Requests to the cluster logger-level endpoint `/cluster/system/loggers/{loggerName}/level/{level}` report a 500 error status (but still execute successfully) unless the request includes the `Accept: application/json` header to clarify to Jersey which content type should be used for the response. 
In the server log, the following error is logged when the `500` is logged.
> ERROR [WriterInterceptorExecutor] MessageBodyWriter not found for media type=text/plain, type=class java.util.HashMap, genericType=java.util.Map<java.lang.String, org.graylog2.shared.rest.resources.ProxiedResource$CallResult<java.lang.Void>>
This PR adds the `@Produces` annotation to provide some advice to Jersey on which content type is being returned.
Closes https://github.com/Graylog2/graylog2-server/issues/14256 …
=> Avoid 500 error for cluster logger level API requests

changelog/unreleased/issue-15841.toml, graylog2-server/src/main/java/org/graylog2/contentpacks/NativeEntityConverter.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/EventListEntity.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/MessageListEntity.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/PivotEntity.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/QueryEntity.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/WidgetEntity.java, graylog2-server/src/test/java/org/graylog2/contentpacks/NativeEntityConverterTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/model/entities/QueryEntityTest.java
Fixes #15841.
When creating a new `Content Pack` with an entity that references a `Search Filter` and later on installing this `Content Pack` on a new machine, we will find out that referenced `Search Filter` is missing on a new machine.
It may lead to problems later on, i.e. during `Search Filter` edit attempts, as described in #15841.
While long-term solution is possible, making `Search Filters` part of the `Content Pack`, it may require complex implementation and still lead to many problems (`Search Filters` are hidden under license, permissions considerations etc.).
The simpler solution of the problem is to inline `Search Filters`, so that they are no longer referenced and can be safely edited locally.
The decision was made to keep existing representation of `Search Filters` in the …
=> Referenced search filters are inlined when fetched from Content Packs

changelog/unreleased/pr-16051.toml, graylog2-web-interface/src/components/event-definitions/hooks/useEventDefinitionConfigFromLocalStorage.ts, graylog2-web-interface/src/views/components/widgets/ReplaySearchButton.tsx, graylog2-web-interface/src/views/components/widgets/WidgetActionsMenu.tsx, graylog2-web-interface/src/views/logic/slices/searchExecutionSlice.ts, graylog2-web-interface/src/views/logic/valueactions/createEventDefinition/CreateEventDefinitionModal.tsx, graylog2-web-interface/src/views/logic/views/UseCreateSavedSearch.ts, graylog2-web-interface/src/views/logic/views/ViewGenerator.ts, graylog2-web-interface/src/views/pages/NewDashboardPage.tsx, graylog2-web-interface/src/views/pages/NewSearchPage.test.tsx, graylog2-web-interface/src/views/pages/NewSearchPage.tsx, graylog2-web-interface/src/views/pages/StreamSearchPage.test.tsx, graylog2-web-interface/src/views/pages/StreamSearchPage.tsx
Before this change we were not including parameters when replaying the search for a dashboard widget.
Fixes: https://github.com/Graylog2/graylog-plugin-enterprise/issues/4576
=> Include parameters when replaying search for dashboard widget.

graylog2-web-interface/src/components/common/OverlayDropdownButton.tsx, graylog2-web-interface/src/components/configurations/QuickAccessTimeRangeForm.test.tsx, graylog2-web-interface/src/components/configurations/QuickAccessTimeRangeForm.tsx, graylog2-web-interface/src/components/configurations/SearchesConfig.tsx, graylog2-web-interface/src/components/configurations/TimeRangePresetForm.test.tsx, graylog2-web-interface/src/components/configurations/TimeRangePresetForm.tsx, graylog2-web-interface/src/components/configurations/TimeRangePresetOptionSummary.tsx, graylog2-web-interface/src/views/components/DashboardSearchBarForm.tsx, graylog2-web-interface/src/views/components/TimerangeForForm.ts, graylog2-web-interface/src/views/components/contexts/TimeRangeInputSettingsContext.ts, graylog2-web-interface/src/views/components/searchbar/SearchBarForm.tsx, graylog2-web-interface/src/views/components/searchbar/completions/FieldValueCompletion.ts, graylog2-web-interface/src/views/components/searchbar/queryvalidation/validateQuery.ts, graylog2-web-interface/src/views/components/searchbar/time-range-filter/TimeRangeFilter.test.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/TimeRangeFilterButtons.test.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/TimeRangeFilterButtons.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/TimeRangePresetDropdown.test.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/TimeRangePresetDropdown.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TabAbsoluteTimeRange.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TabKeywordTimeRange.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TabRelativeTimeRange.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TimeRangeAddToQuickListButton.test.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TimeRangeAddToQuickListButton.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TimeRangePicker.test.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TimeRangePicker.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TimeRangePickerTabs.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TimeRangePresetRow.tsx, graylog2-web-interface/src/views/logic/queries/NormalizeTimeRange.ts
With this PR we are moving the time range preset dropdown button in the time range picker next to the save preset button.
We are also:
- Using a name for the save preset button instead of just an icon
- Improving the data fetching logic. We are doing a request to check if a keyword time range is in the query time range limit. Before this PR we were doing the requests every time you open the search page. Now we are doing these requests only when opening the dropdown.
- Fixing a problem with saving `relative` time ranges.
- No longer displaying the `All times` preset, when a query time range limit is defined
- Unifying the naming of time range presets
Fixes https://github.com/Graylog2/graylog2-server/issues/16000
/jpd https://github.com/Graylog2/graylog-plugin-enterprise/pull/5554
/nocl
=> Move time range preset select to header of time range picker.

graylog2-server/src/test/java/org/graylog/testing/completebackend/ContainerizedGraylogBackend.java
/nocl
Sometimes the Graylog Container for full backend tests is failing to start but the problem is probably in the Search Server container. So we log the logs of the other container additionally for now until we find the real problem.
=> Additional Logging of SearchServer logs if the GL container fails to start due to timeouts.

changelog/unreleased/issue-11465.toml, graylog2-web-interface/src/views/Constants.ts, graylog2-web-interface/src/views/components/searchbar/time-range-filter/TimeRangeFilter.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/TimeRangeFilterButtons.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/AbsoluteCalendar.test.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/AbsoluteCalendar.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/AbsoluteTimestamp.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/RelativeRangeSelect.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TabAbsoluteTimeRange.test.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TabAbsoluteTimeRange.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TabKeywordTimeRange.test.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TabKeywordTimeRange.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TabRelativeTimeRange.test.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TabRelativeTimeRange.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TimeRangeAddToQuickListButton.test.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TimeRangeAddToQuickListButton.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TimeRangePicker.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TimeRangePickerTabs.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TimeRangePresetRow.tsx, graylog2-web-interface/src/views/logic/queries/NormalizeTimeRange.ts, graylog2-web-interface/src/views/logic/queries/Query.ts, graylog2-web-interface/src/views/typeGuards/timeRange.ts
**Please note:** This PR is based on https://github.com/Graylog2/graylog2-server/pull/16063 which needs to be merged first.
With this change we are memorising the state of time range tabs. As described in #11465 the current behaviour can be problematic in some scenarios. For example when you have a search with an absolute time range, you open the time range picker, switch to the relative tab and go back to the absolute tab. In this case the previous state of the absolute tab has not been memorised.
With this PR the state will be memorised, until you close the time range picker. 
Fixes: #11465
=> Memorize state of time range tabs in time range picker.

graylog2-web-interface/src/logic/telemetry/TelemetrySettingsConfig.tsx
With these changes, we send a custom `opt_out` event when opting out users. This is necessary because Posthog sends only `opt_in` events. 
fix Graylog2/graylog-plugin-enterprise#5545
/nocl
=> Send custom oupt_out telemetry event 

graylog2-web-interface/src/preflight/App.test.tsx, graylog2-web-interface/src/preflight/components/ConfigurationWizard/ConfigurationWizard.test.tsx, graylog2-web-interface/src/preflight/components/ConfigurationWizard/ConfigurationWizard.tsx, graylog2-web-interface/src/preflight/components/Setup/DataNodesOverview.test.tsx, graylog2-web-interface/src/preflight/components/Setup/DataNodesOverview.tsx, graylog2-web-interface/src/preflight/components/Setup/Setup.tsx, graylog2-web-interface/src/preflight/components/common/Section.tsx, graylog2-web-interface/src/preflight/hooks/useConfigurationStep.test.tsx, graylog2-web-interface/src/preflight/hooks/useConfigurationStep.tsx, graylog2-web-interface/src/preflight/hooks/useDataNodes.ts, graylog2-web-interface/src/preflight/hooks/useDataNodesCA.ts, graylog2-web-interface/src/preflight/hooks/useRenewalPolicy.ts
In the preflight UI we need to perform multiple fetch requests. Before this change we are not showing related errors in the UI properly. In some cases we did not show any error, in other cases the error message flashed every few seconds.
/nocl
=> Improve the way we display fetch errors in the preflight UI.

changelog/unreleased/issue-15035.toml, graylog2-web-interface/src/views/components/visualizations/ChartData.ts, graylog2-web-interface/src/views/components/visualizations/PlotLegend.tsx, graylog2-web-interface/src/views/components/visualizations/heatmap/HeatmapVisualization.tsx, graylog2-web-interface/src/views/components/visualizations/heatmap/__tests__/HeatmapVisualization.test.tsx
This PR is fixing the heatmap colorbar font color for dark mode. Please have a look at https://github.com/Graylog2/graylog2-server/issues/15035 for more information.
Fixes https://github.com/Graylog2/graylog2-server/issues/15035
=> Fix heatmap colorbar font color for dark mode.

graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/RelativeTimeRangeClassifiedHelper.ts
This PR is fixing a runtime error which occurred in the following scenario:
1. configure a keyword time range for a search
2. open the time range picker
3. select the relative tab
4. select "All time" for "From"
/nocl
=> Fixing error which could occur after selecting all time range.

UPGRADING.md
Add missing new endpoints and deprecation notice for event definition and event notification api to upgrade notes.
/nocl
=> add new endpoints and deprecation notice to upgrade notes

changelog/unreleased/pr-16095.toml, graylog2-web-interface/src/views/components/sidebar/highlighting/ColorPreview.tsx, graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRule.tsx, graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRules.tsx, graylog2-web-interface/src/views/logic/slices/highlightActions.ts
With this PR we are implementing the option to sort highlighting rules. Sorting can be helpful when multiple rules relate to the same field, in this cases their order effects the resulting highlight.
=> Implement option to change order of search highlighting rules.

changelog/unreleased/issue-8128.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/RemoveField.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/removeField.txt
Resolves #8128 
Introduce an optional flag `invert` to `remove_field` function. When `true`, remove all fields except those those that match the given name / regex.
=> Add an optional flag to invert remove_field condition

changelog/unreleased/pr-16166.toml, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/responses/IndexSetSummary.java
make `creation_date` optional when creating index sets using `/api/system/indices/index_sets`
if none is provided, the current server time will be used.
resolves #4709
create index set using api without/with `creation_date`
=> make `creation_date` optional

changelog/unreleased/pr-16184.toml, graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java, graylog2-server/src/main/java/org/graylog2/migrations/MigrationHelpers.java
We shouldn't log messages with ERROR level in situations where we immediately fix the problem in the next step.
Fixes logs like the following on initial server startup:
```
2023-08-16 10:16:41,705 ERROR: org.graylog2.migrations.MigrationHelpers - Invalid user 'graylog-report', fixing it.
2023-08-16 10:16:41,705 INFO : org.graylog2.migrations.MigrationHelpers - graylog-report user is missing or invalid, re-adding it as a built-in user.
2023-08-16 10:16:41,770 ERROR: org.graylog.plugins.sidecar.migrations.V20180212165000_AddDefaultCollectors - Couldn't find collector 'filebeat on linux' fixing it.
2023-08-16 10:16:41,771 INFO : org.graylog.plugins.sidecar.migrations.V20180212165000_AddDefaultCollectors - filebeat collector on linux is missing, adding it.
```
With this PR applied we only log …
=> Change log level for some migration messages from ERROR to DEBUG

graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/MessagesBatchOS2IT.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/SearchServerBuilder.java
This is a tiny refactoring removing the need for type-casts when using `OpenSearchInstanceBuilder` (or any subclass of `SearchServerBuilder`.
/nocl
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#5615
=> Fixing type casts for `SearchServerBuilder`.

changelog/unreleased/pr-16161.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreter.java
includes pipeline name and stage to log message when an exception occurs in the pipeline interpreter
resolves #8627
- create a rule action throwing an exception (i.e. parse_date with invalid pattern)
- check that log warning contains pipeline name and stage
- do the same for a rule condition throwing an exception
=> add pipeline and stage to log output on exception

changelog/unreleased/issue-14793.toml, graylog2-web-interface/src/theme/GlobalThemeStyles.js, graylog2-web-interface/src/views/components/searchbar/queryinput/QueryInput.tsx, graylog2-web-interface/src/views/components/searchbar/queryinput/ace-types.ts
With #6909 we received the feedback that it would be useful to only press `Tab` once to insert the first autocomplete suggestion (instead of pressing it twice). As result we implemented a change to automatically focus the first suggestion. This led to a problem in a different use case. When you search for a custom value like `ssh login` the autocomplete suggested field names for `login` and pressing `Return` did not execute the search but inserted the first suggestion.
We are now no longer focusing the first suggestion and adjusting the behaviour for `Tab` key. When pressing `Tab` while no suggestion is focused we select and insert the first entry.
This way it is possible to press `Return` when searching for a custom value and it still requires only one press to insert the first …
=> Adjust keybindings for query input autocompletion.

graylog2-server/src/main/java/org/graylog2/database/entities/ScopedDbService.java
Adds a `forceSave` option in the ScopedDbService to allow for migrations to modify otherwise immutable DB entities
/nocl
Migrations for entities intended to be immutable through the UI
=> Add forceSave method to bypass mutability checks

graylog2-web-interface/src/components/event-definitions/replay-search/AggreagtionConditions.tsx, graylog2-web-interface/src/components/event-definitions/replay-search/EventInfoBar.tsx, graylog2-web-interface/src/views/logic/ExpressionConditionMappers.tsx, graylog2-web-interface/src/views/logic/views/UseCreateViewForEvent.test.ts, graylog2-web-interface/src/views/logic/views/UseCreateViewForEvent.ts, graylog2-web-interface/src/views/logic/views/UseCreateViewForEventDefinition.test.ts, graylog2-web-interface/test/helpers/mocking/EventAndEventDefinitions_mock.ts
This bug happens because we run at the same time 2 action functions to change the view state (normalize position and set highlights). This pr adds highlights on the stage when we generate a view for the View component 
fix: #15715
/nocl
=> Define highlights on view generation for event and event definition replay

graylog2-web-interface/src/util/AppConfig.ts
This way, a plugin can access their specific UI settings without the need to add a plugin-specific accessor method to AppConfig every time.
I'm making use of it [here](https://github.com/Graylog2/graylog-plugin-enterprise/pull/5636/files#diff-1e06d2ba6e00c8269ad66e51b3cb7923afdc02de27d9fd6bba3b722096de3cbd).
/nocl
=> Expose generic plugin UI settings

graylog2-web-interface/src/preflight/components/common/Alert.tsx, graylog2-web-interface/src/preflight/components/common/Menu.tsx, graylog2-web-interface/src/preflight/components/common/Select.tsx, graylog2-web-interface/src/preflight/theme/PreflightThemeProvider.tsx, graylog2-web-interface/src/preflight/theme/ThemeWrapper.tsx
This PR contains a small refactoring to use `useTheme` from `styled-components` instead of `useContext(ThemeContext)`.
/nocl
=> Use `useTheme` from `styled-components` where possible.

data-node/src/main/java/org/graylog/datanode/configuration/variants/KeystoreInformation.java, data-node/src/test/java/org/graylog/datanode/integration/DatanodeClusterIT.java, data-node/src/test/java/org/graylog/datanode/integration/DatanodeSecuritySetupIT.java, data-node/src/test/java/org/graylog/datanode/integration/DatanodeSecurityTestUtils.java, graylog2-server/src/main/java/org/graylog/security/certutil/CertutilCert.java, graylog2-server/src/test/java/org/graylog2/security/CustomCAX509TrustManagerTest.java, graylog2-server/src/test/java/org/graylog2/security/certutil/CertutilCertTest.java
This PR extends our existing security integration tests for the Datanode. The cluster formation test now uses the full certificate setup on all nodes. Fixed passwords were removed and are autogenerated now, to ensure that they are all actually used and we don't rely on any internal password knowledge. The truststores are generated from the CA only, not using the HTTP certificate anymore (not needed).
/nocl
Extended tests so we can rely more on the security refactorings we do in the Datanode
By the tests itself.
=> Adapt DatanodeClusterIT for full cert setup of all nodes

changelog/unreleased/issue-15095.toml, graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionsContainer.tsx, graylog2-web-interface/src/components/event-definitions/event-definitions/StatusCell.tsx
Added capability to Enable/Disable EventDefinition status when clicking on status badge, similar to the streams overview.
fixes https://github.com/Graylog2/graylog2-server/issues/15095
=> Enable/Disable EventDefinition status when clicking on status badge

graylog2-web-interface/packages/eslint-config-graylog/index.js
This PR is disabling the `testing-library/await-async-events` ESLint rule. It was introduced through #16261 in an update of `eslint-plugin-testing-library`. It only makes sense when used in conjunction with `user-event` v14+, which we are not currently using yet.
Using the rule leads to all usages of `userEvent.(click|type|...)` to be used with `await`. Unfortunately with `userEvent` v13 this will lead to test errors, so we are disabling this rule until we are using v14+.
/nocl
=> Disabling `testing-library/await-async-events` for now.

changelog/unreleased/issue-10682.toml, graylog2-web-interface/src/views/components/DashboardActionsMenu.tsx, graylog2-web-interface/src/views/components/searchbar/SaveViewButton.tsx, graylog2-web-interface/src/views/components/searchbar/saved-search/SearchActionsMenu.tsx
**Please note:** This is a backport of #16122 for 5.1
With this PR we are unifying the behaviour of the "save" icon on the search and dashboard page. Before this change the dashboard save icon did not indicate unsaved changes.
Fixes #10682
=> Display indicator when dashboard has unsaved changes. (5.1)

changelog/unreleased/issue-15035.toml, graylog2-web-interface/src/views/components/visualizations/ChartData.ts, graylog2-web-interface/src/views/components/visualizations/PlotLegend.tsx, graylog2-web-interface/src/views/components/visualizations/heatmap/HeatmapVisualization.tsx, graylog2-web-interface/src/views/components/visualizations/heatmap/__tests__/HeatmapVisualization.test.tsx
**Please note**: This is a backport of #16129 for 5.0
This PR is fixing the heatmap colorbar font color for dark mode. Please have a look at https://github.com/Graylog2/graylog2-server/issues/15035 for more information.
Fixes https://github.com/Graylog2/graylog2-server/issues/15035
=> Fix heatmap colorbar font color for dark mode. (5.0)

changelog/unreleased/issue-14793.toml, graylog2-web-interface/src/theme/GlobalThemeStyles.js, graylog2-web-interface/src/views/components/searchbar/queryinput/QueryInput.tsx, graylog2-web-interface/src/views/components/searchbar/queryinput/ace-types.ts
**Please note:** This is a backport of https://github.com/Graylog2/graylog2-server/pull/16162 for 5.1
With #6909 we received the feedback that it would be useful to only press `Tab` once to insert the first autocomplete suggestion (instead of pressing it twice). As result we implemented a change to automatically focus the first suggestion. This led to a problem in a different use case. When you search for a custom value like `ssh login` the autocomplete suggested field names for `login` and pressing `Return` did not execute the search but inserted the first suggestion.
We are now no longer focusing the first suggestion and adjusting the behaviour for `Tab` key. When pressing `Tab` while no suggestion is focused we select and insert the first entry.
This way it is possible to press …
=> Adjust keybindings for query input autocompletion. (5.1)

changelog/unreleased/issue-15035.toml, graylog2-web-interface/src/views/components/visualizations/ChartData.ts, graylog2-web-interface/src/views/components/visualizations/PlotLegend.tsx, graylog2-web-interface/src/views/components/visualizations/heatmap/HeatmapVisualization.tsx, graylog2-web-interface/src/views/components/visualizations/heatmap/__tests__/HeatmapVisualization.test.tsx
**Please note**: This is a backport of #16129 for 5.1
This PR is fixing the heatmap colorbar font color for dark mode. Please have a look at https://github.com/Graylog2/graylog2-server/issues/15035 for more information.
Fixes https://github.com/Graylog2/graylog2-server/issues/15035
=> Fix heatmap colorbar font color for dark mode. (5.1)

changelog/unreleased/issue-14793.toml, graylog2-web-interface/src/theme/GlobalThemeStyles.js, graylog2-web-interface/src/views/components/searchbar/queryinput/QueryInput.tsx, graylog2-web-interface/src/views/components/searchbar/queryinput/ace-types.ts
**Please note:** This is a backport of https://github.com/Graylog2/graylog2-server/pull/16162 for 5.0
With #6909 we received the feedback that it would be useful to only press `Tab` once to insert the first autocomplete suggestion (instead of pressing it twice). As result we implemented a change to automatically focus the first suggestion. This led to a problem in a different use case. When you search for a custom value like `ssh login` the autocomplete suggested field names for `login` and pressing `Return` did not execute the search but inserted the first suggestion.
We are now no longer focusing the first suggestion and adjusting the behaviour for `Tab` key. When pressing `Tab` while no suggestion is focused we select and insert the first entry.
This way it is possible to press …
=> Adjust keybindings for query input autocompletion. (5.0)

graylog2-web-interface/src/components/event-definitions/replay-search/AggreagtionConditions.tsx, graylog2-web-interface/src/components/event-definitions/replay-search/EventInfoBar.tsx, graylog2-web-interface/src/views/logic/ExpressionConditionMappers.tsx, graylog2-web-interface/src/views/logic/views/UseCreateViewForEvent.test.ts, graylog2-web-interface/src/views/logic/views/UseCreateViewForEvent.ts, graylog2-web-interface/src/views/logic/views/UseCreateViewForEventDefinition.test.ts, graylog2-web-interface/test/helpers/mocking/EventAndEventDefinitions_mock.ts
Please note: This is a backport of https://github.com/Graylog2/graylog2-server/pull/16222 for 5.1
This bug happens because we run at the same time 2 action functions to change the view state (normalize position and set highlights). This pr adds highlights on the stage when we generate a view for the View component 
fix: #15715
/nocl
=> Define highlights on view generation for event and event definition replay (5.1)

changelog/unreleased/pr-16251.toml, graylog2-server/src/main/java/org/graylog/events/processor/EventDefinitionHandler.java, graylog2-server/src/main/java/org/graylog/events/rest/EventDefinitionsResource.java, graylog2-server/src/test/java/org/graylog/events/processor/EventDefinitionHandlerTest.java, graylog2-web-interface/src/stores/event-definitions/EventDefinitionsStore.js
With #16035 we try to enforce a new default event limit, without breaking backwards compatibility.
The validations are making an exemption if an existing event definition is being edited which doesn't have an event limit yet (limit of 0)
Duplicating event definitions was done in the frontend, followed by creating a new one.
This makes it impossible to differentiate between copy and create in the backend.
- Create a new `/events/definitions/{definitionId}/duplicate` endpoint. Which creates a copy without performing a validation.
- Also correctly set the state for unscheduled event defintions. This got missed with #15558
Refs #16035
=> Allow duplicating event definitions with a limit of 0

data-node/src/test/java/org/graylog/datanode/integration/DatanodeClusterIT.java, data-node/src/test/java/org/graylog/datanode/testinfra/DatanodeContainerizedBackend.java
/nocl
This PR adds a datanode integration tests that adds and removes a datanode to the cluster. The test verifies that the opensearch cluster is green before, during and after, with expected count of connected nodes.
=> add datanode IT to verify cluster add/remove

full-backend-tests/src/test/java/org/graylog/testing/fullbackend/FiltersIT.java, graylog2-server/src/main/java/org/graylog2/shared/rest/resources/csp/CSPServiceImpl.java
/nocl
Add Graylog content stream endpoint to CSP-Header
```
Path parts in the CSP that end in / match any path they are a prefix of. 
For example, example.com/api/ will match URLs like example.com/api/users/new.
```
See section Hosts values https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
=> add content stream to csp default headers

graylog2-server/src/main/java/org/graylog2/indexer/messages/MessageWithIndex.java, graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java, graylog2-server/src/main/java/org/graylog2/outputs/BlockingBatchedESOutput.java, graylog2-server/src/main/java/org/graylog2/outputs/ElasticSearchOutput.java, graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesBatchIT.java, graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesBulkIndexRetryingTest.java, graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesIT.java, graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesTest.java, graylog2-server/src/test/java/org/graylog2/outputs/BlockingBatchedESOutputTest.java
This simplifies tons code using
`List<Map.Entry<IndexSet, Message>> messages`
to
`List<MessageWithIndex> messages`
/nocl
/jpd https://github.com/Graylog2/graylog-plugin-enterprise/pull/5679
=> Replace Map.Entry a simple MessageWithIndex record

changelog/unreleased/pr-15088.toml
Fixes the following linter error:
```
$ graylog-project cl lint changelog/unreleased/
Linted 110 snippet file(s) - ok=109 error=1
linter error in file changelog/unreleased/pr-15088.toml: at least one issue or pull request number needs to be present
detected errors in 1 file(s)
```
The broken entry got added before we ran the linter for every PR.
=> Fix changelog entry pr-15088.toml

data-node/src/test/java/org/graylog/datanode/integration/DatanodeSecuritySetupIT.java, graylog2-server/src/test/java/org/graylog/testing/mongodb/MongoDBContainer.java
/nocl
Opened networks and containers can exhaust docker resources even before testcontainers run the cleanup during the jvm shutdown. We should close everything that we create and don't need anymore as soon as possible.
=> close networks and containers in tests

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MessagesAdapterES7.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/MessagesAdapterOS2.java, graylog2-server/src/main/java/org/graylog/failure/FailureSubmissionService.java, graylog2-server/src/main/java/org/graylog2/indexer/messages/ChunkedBulkIndexer.java, graylog2-server/src/main/java/org/graylog2/indexer/messages/IndexingError.java, graylog2-server/src/main/java/org/graylog2/indexer/messages/IndexingResult.java, graylog2-server/src/main/java/org/graylog2/indexer/messages/IndexingResults.java, graylog2-server/src/main/java/org/graylog2/indexer/messages/IndexingSuccess.java, graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java, graylog2-server/src/main/java/org/graylog2/outputs/BlockingBatchedESOutput.java, graylog2-server/src/main/java/org/graylog2/outputs/ElasticSearchOutput.java, graylog2-server/src/test/java/org/graylog/failure/FailureSubmissionServiceTest.java, graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesBatchIT.java, graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesBulkIndexRetryingTest.java, graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesIT.java, graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesTest.java
Bulk index requests were only returning errors so far.
Introduce a new value class: `IndexingResults` which
contains bulk indexing `errors()` and `successes()`
This allows bulk index callers to see into which
actual index a message has been ingested.
/nocl
/jpd https://github.com/Graylog2/graylog-plugin-enterprise/pull/5700
=> Introduce IndexingResults class

graylog2-server/src/test/java/org/graylog/testing/completebackend/ContainerizedGraylogBackend.java
The DataNode relies on Mongo, too - so we have to stop it before we stop Mongo.
/nocl
=> DataNode: stopping SearchServer before Mongo in container tests

.github/workflows/build.yml
The default github hosted runner has only 14gb of disk space. This is already not sufficient enough anymore and causes builds to fail in tests.
This PR is now using the next largest runner (`ubuntu-latest-4-cores`), which offers 150gb of disk space, which is plenty for our use case.
/nocl
=> Using larger runner for more disk space.

.github/workflows/build.yml
Should fix the following issue on GitHub Actions:
```
The value of "length" is out of range. It must be >= 0 && <= 2147483647.
```
Relevant item from the actions/cache changelog:
> Fixed download issue for files > 2GB during restore.
/nocl
=> Bump actions/checkout and actions/cache to fix cache restore issue

.github/workflows/fix-linter-hints.yml, .github/workflows/reviewbot.yml, .github/workflows/update-browserslist-db.yml, .github/workflows/updating-lockfile.yml
- Update actions/checkout to v4
- Update actions/setup-java to v3
- Remove yarn caching because restoring the cache is slower than downloading all dependencies
Refs #16411
/nocl
=> Update workflows to use new action versions

changelog/unreleased/pr-16456.toml, pom.xml
Fixes [CVE-2022-36944](https://nvd.nist.gov/vuln/detail/CVE-2022-36944)
=> Bump scala version to 2.13.12

changelog/unreleased/pr-16475.toml, graylog2-server/src/main/java/org/graylog2/lookup/adapters/dnslookup/DnsResolverPool.java
The value of dns_lookup_adapter_resolver_pool_size in the warning message for when this value should be increased should be dynamic and based on the actual value configured in server.conf. Previously, it was hard-coded to the default of "10".
Fixes inaccurate feedback to user who has modified the dns_lookup_adapter_resolver_pool_size value. Now the user will at least receive acknowledgement that their modified value is in use by Graylog.
Not tested unfortunately as I do not have the knowledge/ability to. However this being a very minor change, I felt it appropriate to submit this PR anyway and welcome someone to test it who has the ability to.
=> converted dns_lookup_adapter_resolver_pool_size warning message to use dynamic value instead of hard-coded value (10)

graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20230502164900_AddSidecarManagerAndReaderRole.java
In #15380, the sidecar manager and reader role was introduced, but the duplicate timestamp in the migration sometimes causes the migration to be ignored.
/nocl
=> fix timestamp of sidecar roles migration

changelog/unreleased/pr-16481.toml, graylog2-server/src/main/java/org/graylog2/periodical/IndexerClusterCheckerThread.java
**Note:** This needs a backport to `5.1` and `5.0`.
Previously, we were seeing issues in containerized integration tests where the Graylog container did not come up properly and container startup timed out. In its logs, we were always seeing something like this:
```
2023-09-14 08:26:13,464 INFO : org.graylog2.indexer.MongoIndexSet - Did not find a deflector alias. Setting one up now.
2023-09-14 08:26:13,474 INFO : org.graylog2.periodical.IndexRetentionThread - Skipping index retention checks because the Elasticsearch cluster is unhealthy: Green, Index Registry is up: false
2023-09-14 08:26:13,482 INFO : org.graylog2.indexer.MongoIndexSet - There is no index target to point to. Creating one now.
2023-09-14 08:26:13,490 INFO : org.graylog2.indexer.MongoIndexSet - Cycling from <none> to …
```
=> Delaying start of `IndexerClusterCheckerThread` to avoid deadlock.

changelog/unreleased/pr-16481.toml, graylog2-server/src/main/java/org/graylog2/periodical/IndexerClusterCheckerThread.java
**Note:** This is a backport of #16481 to `5.1`.
Previously, we were seeing issues in containerized integration tests where the Graylog container did not come up properly and container startup timed out. In its logs, we were always seeing something like this:
```
2023-09-14 08:26:13,464 INFO : org.graylog2.indexer.MongoIndexSet - Did not find a deflector alias. Setting one up now.
2023-09-14 08:26:13,474 INFO : org.graylog2.periodical.IndexRetentionThread - Skipping index retention checks because the Elasticsearch cluster is unhealthy: Green, Index Registry is up: false
2023-09-14 08:26:13,482 INFO : org.graylog2.indexer.MongoIndexSet - There is no index target to point to. Creating one now.
2023-09-14 08:26:13,490 INFO : org.graylog2.indexer.MongoIndexSet - Cycling from <none> to …
```
=> Delaying start of `IndexerClusterCheckerThread` to avoid deadlock. (`5.1`)

changelog/unreleased/pr-16481.toml, graylog2-server/src/main/java/org/graylog2/periodical/IndexerClusterCheckerThread.java
**Note:** This is a backport of #16481 to `5.0`.
* Delaying start of `IndexerClusterCheckerThread` to avoid deadlock.
* Adding changelog snippet.
Previously, we were seeing issues in containerized integration tests where the Graylog container did not come up properly and container startup timed out. In its logs, we were always seeing something like this:
```
2023-09-14 08:26:13,464 INFO : org.graylog2.indexer.MongoIndexSet - Did not find a deflector alias. Setting one up now.
2023-09-14 08:26:13,474 INFO : org.graylog2.periodical.IndexRetentionThread - Skipping index retention checks because the Elasticsearch cluster is unhealthy: Green, Index Registry is up: false
2023-09-14 08:26:13,482 INFO : org.graylog2.indexer.MongoIndexSet - There is no index target to point to. Creating one now. …
```
=> Delaying start of `IndexerClusterCheckerThread` to avoid deadlock. (`5.0`)

changelog/unreleased/issue-16447.toml, data-node/src/main/java/org/graylog/datanode/Configuration.java, data-node/src/main/java/org/graylog/datanode/initializers/JerseyService.java, data-node/src/test/java/org/graylog/datanode/DatanodeRestApiWait.java, data-node/src/test/java/org/graylog/datanode/integration/DatanodeClusterIT.java, data-node/src/test/java/org/graylog/datanode/integration/DatanodeSecuritySetupIT.java, data-node/src/test/java/org/graylog/datanode/testinfra/DatanodeContainerizedBackend.java, data-node/src/test/java/org/graylog/datanode/testinfra/DatanodeDevContainerBuilder.java, graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/PreflightJerseyService.java, graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/web/BasicAuthFilter.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/ContainerizedGraylogBackend.java
In case the datanode is secured with a http certificates, we also enable basic auth for all datanode REST APIs. 
Fixes https://github.com/Graylog2/graylog2-server/issues/16447
=> basic auth for datanode rest api if security enabled

changelog/unreleased/issue-16392.toml, graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexSetValidator.java, graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingStrategy.java, graylog2-server/src/main/java/org/graylog2/migrations/MaintenanceStrategiesHelper.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indices/RotationStrategyResource.java, graylog2-server/src/test/java/org/graylog2/indexer/IndexSetValidatorTest.java, misc/graylog.conf
Backporting #16392 
Refers to Graylog2/graylog-plugin-enterprise#5685
=> Backport 5.1: Account for leeway in validating retention period for time-size-optimizing retention

graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/GraylogApis.java
The variable was named `response` - but it's a request at that point.
/nocl
=> Fixed variable naming in methods - it's a request, not a response

graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexSetValidator.java, graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingStrategy.java, graylog2-server/src/main/java/org/graylog2/migrations/MaintenanceStrategiesHelper.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indices/RotationStrategyResource.java, graylog2-server/src/test/java/org/graylog2/indexer/IndexSetValidatorTest.java
/nocl no user-visible changes
#16448 included some renaming for better consistency; but the corresponding change in Cloud repo was missing. For simplicity, this PR reverts the rename in the 5.1 branch.
=> Revert rename rotation->retention to avoid incompatibility with Cloud

changelog/unreleased/pr-16503.toml, graylog2-server/src/main/java/org/graylog2/indexer/retention/strategies/AbstractIndexRetentionStrategy.java
Resolves #5722
Time/size optimizing Rotation strategy (TSO) was filtering for indices that had the write block set when running retention. If it was not present (i.e. setting the write block had failed), then those indices were not being retained. There are legitimate scenarios where we want to delete archives anyway, e.g. if we are in a high watermark situation and indices have `read_only_allow_delete` block set.
None of the other rotation strategies performs this test, so it is consistent to do the same for TSO. This also avoids lots of downstream issues when indices are unexpectedly not being retained and piling up.
=> Remove check for write block for TSO rotation strategy

changelog/unreleased/issue-16440.toml, graylog2-web-interface/src/views/components/views/ViewHeader.test.tsx, graylog2-web-interface/src/views/components/views/ViewHeader.tsx
**Note:** This PR is a backport of #16441 to `5.1`.
This PR is fixing an issue described in #16440, where changing the title of a dashboard was not properly saved. This is due to the save view action being called with the original dashboard and not the updated one.
Fixes #16440.
=> Save & reload updated dashboard after changing title. (`5.1`)

changelog/unreleased/pr-16503.toml, graylog2-server/src/main/java/org/graylog2/indexer/retention/strategies/AbstractIndexRetentionStrategy.java
Resolves https://github.com/Graylog2/graylog2-server/issues/5722
Time/size optimizing Rotation strategy (TSO) was filtering for indices that had the write block set when running retention. If it was not present (i.e. setting the write block had failed), then those indices were not being retained. There are legitimate scenarios where we want to delete indices anyway, e.g. if we are in a high watermark situation and indices have read_only_allow_delete block set.
None of the other rotation strategies performs this test, so it is consistent to do the same for TSO. This also avoids lots of downstream issues when indices are unexpectedly not being retained and piling up.
(cherry picked from commit 44059ebfd5fa416afbe6ee52dc756bb50242d8cd)
=> Remove check for write block for TSO rotation strategy (5.1 backport)

full-backend-tests/pom.xml
We skip the datanode build in the cloud plugin, so we can't have the dependencies in the integration tests in the cloud build. As we don't run the tests, only the artefacts are built. Which is fine because the dependencies are only needed at runtime.
/nocl
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/5811
=> DataNode: Fixed dependency for IT tests if we skip the datanode in cloud builds

changelog/unreleased/pr-16476.toml, data-node/pom.xml, full-backend-tests/pom.xml, graylog-project-parent/pom.xml, graylog2-server/pom.xml, pom.xml
Updates various backend dependencies:
- kafka `3.4.0` -> `3.5.1`
- scala-library (*removed*)
- snappy-java `1.1.8.3` -> `1.1.10.3`
- grpc `1.48.1` -> `1.58.0`
- protobuf `3.17.3` -> `3.24.3`
- commons-validator `1.6` -> `1.7`
- cron-utils `9.1.6` -> `9.2.1`
- commons-io `2.6` -> `2.13.0`
- okhttp `3.14.6` -> `4.11.0`
- netty `4.1.91` -> `4.1.97`
- bouncycastle `1.69` -> `1.76`
- hibernate-validator `6.1.2.Final` -> `6.2.5.Final`
- commons-net `3.6` -> `3.9.0`
- guava `31.0.1-jre` -> `32.1.2-jre`
Refs https://github.com/Graylog2/graylog-plugin-enterprise/issues/4306
/jpd https://github.com/Graylog2/graylog-plugin-enterprise/pull/5795
=> Update various backend dependencies

changelog/unreleased/issue-16474.toml, graylog2-server/src/main/java/org/graylog2/streams/StreamDTO.java
**Note:** This needs a backport to `5.1`.
This PR is fixing an issue which was introduced in #14085. A slightly different code path is introduced for the paginated streams endpoint, which led to streams missing the `matching_type` field to fail deserializing, because the default for `matching_type` is not applied and a `null` value is passed instead to the builder method. 
Fixes #16474.
=> Make sure default for `matching_type` is applied for paginated streams endpoint too.

data-node/src/main/java/org/graylog/datanode/Configuration.java, data-node/src/main/java/org/graylog/datanode/configuration/OpensearchConfigurationProvider.java
As far as I understand the docs (and my own tests), the single-node setting is necessary for single-node installations that only bind to localhost so that inter-cluster communication for leader-election etc. is not possible.
In the context of the DataNode, this does not make sense, we bind to the real network interface, so this setting was removed.
/nocl
=> DataNode: Removing obsolete single-node setting

changelog/unreleased/issue-16474.toml, graylog2-server/src/main/java/org/graylog2/streams/StreamDTO.java
**Note:** This PR is a backport of #16522 to `5.1`.
This PR is fixing an issue which was introduced in #14085. A slightly different code path is introduced for the paginated streams endpoint, which led to streams missing the `matching_type` field to fail deserializing, because the default for `matching_type` is not applied and a `null` value is passed instead to the builder method. 
Fixes #16474.
=> Make sure default for matching_type is applied for paginated streams endpoint too. (`5.1`)

graylog2-web-interface/webpack.preflight.ts
Before this change you could open a route like `/test` and the preflight UI rendered, but it did not worked correctly, because the UI does not expect a route other than `/`.
With this change we are adjusting the webpack config. When you open a route like `/test` you will see an error.
/nocl
=> Disable `historyApiFallback` in preflight UI webpack dev config.

graylog2-server/src/main/java/org/graylog2/rest/resources/system/field_types/FieldTypeMappingsResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexSetsMappingResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/requests/FieldTypeSummaryRequest.java
Prior to this PR, the `streams` field of the request when retrieving field mappings for index sets was mandatory. With this PR it can be skipped (or set to an empty set), so all streams available to the user will be used.
/nocl
=> Allow skipping streams when retrieving type mappings.

graylog2-web-interface/src/@types/mantine/index.d.ts
With this change the mantine theme type includes the custom data we define for the theme, like `theme.others.colors.global`.
/nocl
=> Extend mantine theme type to include custom data.

changelog/unreleased/pr-16514.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/SetField.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/SetFields.java, graylog2-server/src/main/java/org/graylog2/plugin/Message.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/java/org/graylog2/plugin/MessageTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/setField.txt, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/setFields.txt
Add optional parameters to the following pipeline functions that can be used to replace invalid field name characters with underscores. Both default to `false`.
* `set_field` pipeline function: New parameter: `clean_field`
* `set_fields` pipeline function: New parameter: `clean_fields`
**`set_field` example**
```
rule "set_field"
when true
then
set_field(field: "has space chars", value: "value", clean_field: true);
end
```
In this example, the field `has_space_chars` will be added to the message with the value `value`.
**`set_fields` example**
Given a message with a `json_map` field containing the following value:
```
{
"key_1": "value 1",
"has space chars": "value"
}
```
And the following rule:
```
rule "set_fields"
when true
then
let cleanFieldValue = …
```
=> Add ability to clean field names for set_field and set_fields pipeline functions

graylog2-server/src/test/java/org/graylog2/contentpacks/jersey/ModelIdParamConverterTest.java
Copied from here:
https://github.com/Graylog2/graylog2-server/blob/f35df42e165ac570b8b27de3f8eeac85e74ed610/graylog2-server/src/test/java/org/graylog2/rest/GenericErrorCsvWriterTest.java#L46
/nocl
=> Use random port for test container in ModelIdParamConverterTest

changelog/unreleased/pr-16514.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/SetField.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/SetFields.java, graylog2-server/src/main/java/org/graylog2/plugin/Message.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/java/org/graylog2/plugin/MessageTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/setField.txt, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/setFields.txt
Backport https://github.com/Graylog2/graylog2-server/pull/16514 to the `5.1` branch.
=> Add ability to clean field names for set_field and set_fields pipeline functions (5.1)

pom.xml
Remove management for unused `org.apache.httpcomponents:httpasyncclient` dependency
The dependency doesn't appear in the output of `mvn dependency:tree`.
/nocl
=> Remove management for unused httpasyncclient dependency

.github/workflows/fix-linter-hints.yml, .github/workflows/reviewbot.yml, .github/workflows/update-browserslist-db.yml, .github/workflows/updating-lockfile.yml
- Update actions/checkout to v4
- Update actions/setup-java to v3
- Remove yarn caching because restoring the cache is slower than downloading all dependencies
Refs #16411
Co-authored-by: Dennis Oelkers <dennis@graylog.com>
(cherry picked from commit b626e4a6ab0e0c8188690edfd0d8749da8205c07)
/nocl
=> Update workflows to use new action versions (#16418)

graylog2-web-interface/packages/graylog-web-plugin/package.json, graylog2-web-interface/src/components/bootstrap/Alert.md, graylog2-web-interface/src/components/bootstrap/Alert.tsx, graylog2-web-interface/yarn.lock
With this PR we are:
- Fixing the alert headline color
- change default alert background color to default
- Upgrading to sawmill 2.0.6
- Fixing color of alert close icon 
- Adding border for alert to fix contrast problem with "default" background-color in dark mode.
Fixes https://github.com/Graylog2/graylog2-server/issues/16521
/nocl
=> Further improvements for new alert styling

graylog2-server/src/main/java/org/graylog/security/certutil/CaServiceImpl.java
We saved the CA per node - which was not correct as we only want one CA per cluster. As all the cert services etc are also used in different contexts, I included a default CA name instead of refactoring all the services into two separate versions.
/nocl
=> don't save a CA per node, we want only a single one

.github/workflows/build.yml
Backport of https://github.com/Graylog2/graylog2-server/pull/16411
/nocl
=> Backport: Bump actions/checkout and actions/cache to fix cache restore issue to 5.1

graylog2-web-interface/src/components/configurations/PluginsConfig.tsx, graylog2-web-interface/src/pages/ConfigurationsPage.test.tsx, graylog2-web-interface/src/pages/ConfigurationsPage.tsx, graylog2-web-interface/src/routing/AppRouter.tsx, graylog2-web-interface/webpack.vendor.ts
Prior to this PR, it was not possible to deep-link configuration sections, a user always had to go through the navigation.
This PR is now adding nested routers for the configuration/plugin sections, so individual sections can be deep-linked.
**Note:** A change to the `webpack-dev-server` config was required, because previously URLs with a dot did not work.
/nocl
=> Use nested router on `ConfigurationsPage` to deep-link section.

pom.xml
Guice 7.0.0 is already available, but we can't update to that version yet, because it doesn't support the old "java.inject.*" namespace anymore.
See: https://github.com/google/guice/wiki/Guice600#jee-jakarta-transition
We can update to 7.x when we do the Jakarta transition for all of our dependencies.
Changes:
- 5.1.0: https://github.com/google/guice/wiki/Guice510#changes-since-guice-501
- 6.0.0: https://github.com/google/guice/wiki/Guice600#changes-since-guice-510
/nocl
=> Update guice to 6.0.0

graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/SaveTimeRangeAsPresetButton.test.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/SaveTimeRangeAsPresetButton.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TimeRangeAddToQuickListButton.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TimeRangePresetRow.tsx
With this PR we are making the time range preset form in the time range picker an actual `form`, mainly to be able to submit the form by pressing the return key.
/nocl
=> Make time range preset form in time picker an actual form

changelog/unreleased/pr-16668.toml, graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRules.tsx
**Please note**: this PR needs a backport for 5.1
With this PR we are fixing the description for the scenario that one term or value has multiple matching highlighting rules.
Before the description said: "If a term or a value has more than one rule, the last matching rule is used."
Now it says "...the first matching rule is used."
Here is an example:
=> Fix description for multiple matching highlighting rules.

graylog2-server/src/main/java/org/graylog2/bootstrap/ServerBootstrap.java
Problems occurred in a multi-node cluster when all the GL nodes resumed the preflight at the same moment. All nodes tried to create collections at the same time which resulted in Exceptions that were not caught but could be ignored in the future. As this would be a larger refactoring, we opt for delaying all nodes that are not the leader node, so that the leader takes care of creating the collections first.
/nocl
=> DataNode: Delay resume for non leader nodes

pom.xml
Revert upgrade from `4.1.97.Final` to `4.1.98.Final` from https://github.com/Graylog2/graylog2-server/pull/16699.
This update appears to cause a runtime issue on Mac systems. On my M1 Mac, when starting Graylog, the following error occurs. The same issue affects the recent `5.2.0-alpha.1` build. 
> dyld[3001]: missing symbol called
From testing reversion of various commits, I was able to narrow it down to this specific commit causing the issue (when reverted, the error does not occur).
An issue has been raised with Netty for the same error on Mac systems within the last week with several thumbs-ups:
https://github.com/netty/netty/issues/13632
I think we should wait until the issue is addressed by Netty in a subsequent version before updating the dependency. 
/nocl
On an M1 Mac, start the …
=> Revert "Bump io.netty:netty-bom from 4.1.97.Final to 4.1.98.Final"

graylog-plugin-parent/pom.xml
Breaks IntelliJ.
This reverts commit 8ab78cbc4bd8e4d1f8d1919d88d7177a3466cb10.
=> Revert "Bump org.codehaus.mojo:rpm-maven-plugin from 2.2.0 to 2.3.0"

graylog2-server/pom.xml
This avoids including them in the shaded artifact. The scopes got lost when we switched to the bom dependency management.
/nocl
=> Add missing test scope to junit and awaitility dependencies

pom.xml
We only use it in the enterprise repository since we merged our plugins.
/nocl
/jpd https://github.com/Graylog2/graylog-plugin-enterprise/pull/5878
=> Remove okta-sdk.version property

graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java, graylog2-server/src/main/java/org/graylog2/shared/plugins/PluginLoader.java
allow setting a custom `PluginLoader` in `CmdLineTools` and make methods visible for overriding
needed for skipping loading of plugins in forwarder after merging enterprise-integrations plugin into enterprise
/nocl
=> allow overriding`PluginLoader`

changelog/unreleased/pr-16722.toml, graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config
This PR is toggling the preflight UI feature flag to be turned on by default, enabling it for general usage.
The pre-flight UI is a special mode of the Graylog server which is activated at the first start on fresh installs. It is supposed to help with setting up new clusters. In this first version, it helps with setting up Data Nodes (a drop-in replacement for OpenSearch) as well as CA certificate management and provisioning of Data Nodes with matching certificates.
After the initial setup/provisioning, regular operation of Graylog server continues.
Fixes #16602.
=> Toggle preflight feature flag.

changelog/unreleased/issue-16634.toml, graylog2-web-interface/src/views/components/AdaptableQueryTabs.tsx, graylog2-web-interface/src/views/components/AdaptableQueryTabsConfiguration.test.tsx, graylog2-web-interface/src/views/components/AdaptableQueryTabsConfiguration.tsx, graylog2-web-interface/src/views/components/QueryBar.tsx, graylog2-web-interface/src/views/components/queries/QueryTitle.test.tsx, graylog2-web-interface/src/views/components/queries/QueryTitle.tsx, graylog2-web-interface/src/views/logic/slices/viewSlice.ts, graylog2-web-interface/src/views/logic/views/FindNewActiveQuery.test.ts, graylog2-web-interface/src/views/logic/views/FindNewActiveQuery.ts
**Please note:** this PR needs a backport for 5.1
This PR is fixing the bug described in https://github.com/Graylog2/graylog2-server/issues/16634. Before this change a dashboard could not be saved after deleting a dashboard page in the pages configuration modal.
Fixes #16634
=> Remove query from view state when removing a page in the pages configuration modal.

graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetFieldTypeSummaryService.java, graylog2-web-interface/src/views/logic/fieldactions/ChangeFieldType/ChangeFieldTypeModal.tsx, graylog2-web-interface/src/views/logic/fieldactions/ChangeFieldType/hooks/useColumnRenderers.tsx
This PR is adding minor visual improvements for the Field Type Change modal:
- The new field type select got a label
- Field types are sorted lexicographically
- The modal title got a beta label
- The Field Type History column was renamed to `Current Types`
- Stream titles are rendered so they are joined using `,` and shown
completely
/nocl
Before:
After:
=> Visual improvements for Field Type Change modal.

changelog/unreleased/pr-16668.toml, graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRules.tsx
**Please note**: this is a backport of #16668 for 5.0
With this PR we are fixing the description for the scenario that one term or value has multiple matching highlighting rules.
Before the description said: "If a term or a value has more than one rule, the last matching rule is used."
Now it says "...the first matching rule is used."
Here is an example:
=> Fix description for multiple matching highlighting rules. (`5.0`)

changelog/unreleased/pr-16668.toml, graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRules.tsx
**Please note**: this is a backport of #16668 for 5.1
With this PR we are fixing the description for the scenario that one term or value has multiple matching highlighting rules.
Before the description said: "If a term or a value has more than one rule, the last matching rule is used."
Now it says "...the first matching rule is used."
Here is an example:
=> Fix description for multiple matching highlighting rules. (`5.1`)

changelog/unreleased/issue-16634.toml, graylog2-web-interface/src/views/components/AdaptableQueryTabs.tsx, graylog2-web-interface/src/views/components/AdaptableQueryTabsConfiguration.tsx, graylog2-web-interface/src/views/components/QueryBar.tsx, graylog2-web-interface/src/views/components/queries/QueryTitle.test.tsx, graylog2-web-interface/src/views/components/queries/QueryTitle.tsx, graylog2-web-interface/src/views/logic/slices/viewSlice.ts, graylog2-web-interface/src/views/logic/views/FindNewActiveQuery.test.ts, graylog2-web-interface/src/views/logic/views/FindNewActiveQuery.ts
**Please note:** this is a backport of https://github.com/Graylog2/graylog2-server/pull/16674 for `5.1`.
This PR is fixing the bug described in https://github.com/Graylog2/graylog2-server/issues/16634. Before this change a dashboard could not be saved after deleting a dashboard page in the pages configuration modal.
Fixes #16634
=> Remove query from view state when removing a page in the pages configuration modal (`5.1`)

pom.xml
Disable patterns we don't need because we are not runnig on that platform (Android), or we don't use the libraries. (Flogger, JUnit3)
Change the following patterns from WARN (default) to ERROR:
- DefaultCharset
- DoubleCheckedLocking
- InconsistentHashCode
- IncrementInForLoopAndHeader
- NonAtomicVolatileUpdate
- PrimitiveAtomicReference
/nocl
=> Update Error Prone bug patterns

graylog2-server/src/main/java/org/graylog2/bootstrap/ServerBootstrap.java
Use the LeaderElectionService to check if nodes are not leaders and delay them after preflight
/nocl
fixes  #16794
=> Use LeaderElectionService during preflight procedure

graylog2-web-interface/src/contexts/HotkeysContext.tsx, graylog2-web-interface/src/contexts/HotkeysProvider.tsx, graylog2-web-interface/src/views/components/DashboardActionsMenu.tsx, graylog2-web-interface/src/views/components/searchbar/SaveAsDashboardButton.tsx, graylog2-web-interface/src/views/components/searchbar/SaveDashboardButton.tsx
This PR is improving the hotkeys for dashboards by:
- fixing an error which occurred when pressing "ctrl + s" on `/dashboards/new`
- adding a hotkey for "save as new", similar to the search page
- making sure we open the "save as new" modal when pressing "ctrl + s" on `/dashboards/new`
- making sure we do not offer the "save" hotkey on security pages.
Fixes: https://github.com/Graylog2/graylog2-server/issues/16797
/nocl
=> Improve keyboard shortcuts for dashboards.

graylog2-server/src/main/java/org/graylog2/indexer/retention/strategies/AbstractIndexRetentionStrategy.java
Log output example:
`
2023-10-05 14:43:07,188 DEBUG : org.graylog2.indexer.retention.strategies.AbstractIndexRetentionStrategy - Nothing to retain for indexSet <graylog>: (min P30D, max P40D) details: <{graylog_1={closingDate=Optional.empty, hasCurrentWriteAlias=true, creationDate=Optional[2023-10-05T13:27:28.099Z], isReopened=false, exceedsAgeLimit=false}, graylog_0={closingDate=Optional[2023-10-05T13:27:58.615Z], hasCurrentWriteAlias=false, creationDate=Optional[2023-08-08T08:34:57.906Z], isReopened=false, exceedsAgeLimit=false}}>
`
/nocl
=> Add debugging log for TSO retain strategy (5.1)

data-node/src/main/java/org/graylog/datanode/OpensearchDistribution.java, data-node/src/test/java/org/graylog/datanode/OpensearchDistributionTest.java
Fixes https://github.com/Graylog2/graylog2-server/issues/16826
The new error message looks like this:
/nocl
```
java.lang.IllegalArgumentException: Failed to list content of provided directory. Directory used for Opensearch detection: /tmp/junit10789252857559246705/nonexistent. Please configure opensearch_location to a directory that contains an opensearch distribution for your architecture x64. You can download Opensearch from https://opensearch.org/downloads.html . Please extract the downloaded distribution and point opensearch_location configuration option to that directory.
```
Let's make our error message as helpful as possible
Added unit tests
=> better error message with instructions for problems with opensearch distribution location

graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/PreflightJerseyService.java, graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/web/resources/PreflightResource.java, graylog2-web-interface/src/preflight/components/ConfigurationWizard/CAUpload.test.tsx, graylog2-web-interface/src/preflight/components/ConfigurationWizard/CAUpload.tsx
This change is improving error handling in the CA upload of the preflight UI by:
- Returning structured error message when reading CA bundle failed
- Adding general exception handler to preflight API
- Use async mutation so "Upload CA" button does not stay disabled
after error
/nocl
=> Improve error handling when uploading CA bundle in preflight UI.

graylog2-web-interface/src/preflight/components/ConfigurationWizard/CACreateForm.tsx, graylog2-web-interface/src/preflight/components/ConfigurationWizard/RenewalPolicyConfiguration.tsx
This PR contains an improvement for the preflight UI form submits. By using `mutateAsync` form `useMutation` we are actually returning a promise, which will be used by formik to update `isSubmitting`.
/nocl
=> Handle promises correctly for form submits in preflight UI.

data-node/src/main/java/org/graylog/datanode/Configuration.java, data-node/src/main/java/org/graylog/datanode/OpensearchDistribution.java, data-node/src/main/java/org/graylog/datanode/bindings/DatanodeConfigurationBindings.java, data-node/src/main/java/org/graylog/datanode/bindings/GenericInitializerBindings.java, data-node/src/main/java/org/graylog/datanode/bootstrap/preflight/OpensearchBinPreflightCheck.java, data-node/src/main/java/org/graylog/datanode/configuration/DatanodeConfiguration.java, data-node/src/main/java/org/graylog/datanode/configuration/DatanodeConfigurationProvider.java, data-node/src/main/java/org/graylog/datanode/configuration/OpensearchArchitecture.java, data-node/src/main/java/org/graylog/datanode/configuration/OpensearchConfigurationProvider.java, data-node/src/main/java/org/graylog/datanode/configuration/OpensearchDistributionProvider.java, data-node/src/main/java/org/graylog/datanode/rest/StatusController.java, data-node/src/test/java/org/graylog/datanode/bootstrap/OpensearchBinPreflightCheckTest.java, data-node/src/test/java/org/graylog/datanode/configuration/OpensearchArchitectureTest.java, data-node/src/test/java/org/graylog/datanode/configuration/OpensearchDistributionProviderTest.java, data-node/src/test/java/org/graylog/datanode/testinfra/DatanodeDevContainerBuilder.java
/nocl
- OpensearchArchitecture refactored to its own enum
- OpensearchDistributionProvider handles all detection and logic
- OpensearchDistribution is now a simple record only
- Detection moved from injection time to runtime, will be first triggered by the opensearch bin preflight check, actually the ideal place to do such detection
Code cleanup
Existing and new unit tests and existing integration tests
=> datanode distribution provider refactoring

graylog2-server/src/main/java/org/graylog2/Configuration.java, graylog2-server/src/main/java/org/graylog2/rest/resources/datanodes/DataNodeApiProxyResource.java, graylog2-server/src/main/java/org/graylog2/storage/VersionAwareProvider.java, graylog2-server/src/main/java/org/graylog2/storage/providers/ProxyRequestAdapterProvider.java
This PR is adding a `datanode_proxy_api_allowlist` config setting (`true` by default), which allows adventurous users to disable the allow list for the data node proxy API endpoint. It should not be used under normal circumstances, but only for debugging purposes during e.g. an incident. Instead, any endpoints which serve useful and are safe to use should be added to the allow list. As this is not possible without a new release and a redeployment, the config setting was introduced as a temporary measure.
/nocl
=> Allow disabling allowlist for data node proxy API.

changelog/unreleased/pr-16902.toml, pom.xml
Fixes the recently revealed HTTP/2 Rapid Reset Attack.
- https://github.com/netty/netty/security/advisories/GHSA-xpw8-rcwv-8f8p
- https://www.cve.org/CVERecord?id=CVE-2023-44487
- https://netty.io/news/2023/10/10/4-1-100-Final.html
=> Security update to Netty 4.1.100

changelog/unreleased/pr-16902.toml, pom.xml
Backport of #16902 
Fixes the recently revealed HTTP/2 Rapid Reset Attack.
[GHSA-xpw8-rcwv-8f8p](https://github.com/netty/netty/security/advisories/GHSA-xpw8-rcwv-8f8p)
https://www.cve.org/CVERecord?id=CVE-2023-44487
https://netty.io/news/2023/10/10/4-1-100-Final.html
=> Security update to Netty 4.1.100 (Backport to 5.1)

changelog/unreleased/pr-16902.toml, pom.xml
Fixes the recently revealed HTTP/2 Rapid Reset Attack.
- https://github.com/netty/netty/security/advisories/GHSA-xpw8-rcwv-8f8p
- https://www.cve.org/CVERecord?id=CVE-2023-44487
- https://netty.io/news/2023/10/10/4-1-100-Final.html
* Add changelog
(cherry picked from commit bfb002b24816cd19146923740799da07228105b5)
=> Security update to Netty 4.1.100 (#16902)

data-node/src/main/resources/opensearch/config/opensearch-security/config.yml
Disable the now unused internal user DB. This leaves JWT auth to be the only enabled auth method.
This PR should probably not get merged before we add an additional way to access OpenSearch from within GL.
/nocl
- [] Refactoring (non-breaking change)
=> DataNode: Disabling unused auth methods

data-node/src/main/java/org/graylog/datanode/Configuration.java, data-node/src/main/java/org/graylog/datanode/OpensearchDistribution.java, data-node/src/main/java/org/graylog/datanode/bindings/DatanodeConfigurationBindings.java, data-node/src/main/java/org/graylog/datanode/bindings/PreflightChecksBindings.java, data-node/src/main/java/org/graylog/datanode/bindings/ServerBindings.java, data-node/src/main/java/org/graylog/datanode/bootstrap/preflight/DataNodeConfigurationPeriodical.java, data-node/src/main/java/org/graylog/datanode/bootstrap/preflight/DatanodeDirectoriesCheck.java, data-node/src/main/java/org/graylog/datanode/bootstrap/preflight/DatanodeDirectoryException.java, data-node/src/main/java/org/graylog/datanode/bootstrap/preflight/OpensearchBinPreflightCheck.java, data-node/src/main/java/org/graylog/datanode/bootstrap/preflight/OpensearchConfigSync.java, data-node/src/main/java/org/graylog/datanode/configuration/DatanodeConfiguration.java, data-node/src/main/java/org/graylog/datanode/configuration/DatanodeConfigurationProvider.java, data-node/src/main/java/org/graylog/datanode/configuration/DatanodeDirectories.java, data-node/src/main/java/org/graylog/datanode/configuration/OpensearchConfigurationProvider.java, data-node/src/main/java/org/graylog/datanode/configuration/variants/MongoCertSecureConfiguration.java, data-node/src/main/java/org/graylog/datanode/configuration/variants/OpensearchSecurityConfiguration.java, data-node/src/main/java/org/graylog/datanode/configuration/variants/SecureConfiguration.java, data-node/src/main/java/org/graylog/datanode/configuration/variants/UploadedCertFilesSecureConfiguration.java, data-node/src/main/java/org/graylog/datanode/management/OpensearchCommandLineProcess.java, data-node/src/main/java/org/graylog/datanode/management/OpensearchProcessImpl.java, data-node/src/main/java/org/graylog/datanode/process/OpensearchConfiguration.java, data-node/src/test/java/org/graylog/datanode/bootstrap/preflight/DatanodeDirectoriesCheckTest.java, data-node/src/test/java/org/graylog/datanode/bootstrap/preflight/OpensearchBinPreflightCheckTest.java
Refactor all usages and pointers of datanode and managed-opensearch directories. All are now handled on one place only (DatanodeDirectories class), properly resolved, **using nodeId as a subdir** to avoid configuration collisions. Added javadoc for all methods to make clear what are our expectations and usages of these directories.
Additionally we now check the presence and permissions to each of the directories in advance, during preflight checks. This should reveal any possible problems significantly sooner than during runtime later.
/nocl
Added unit tests, existing set of integration tests.
=> Refactored all usages of directories used by datanode and managed opensearch

changelog/unreleased/issue-14373.toml, graylog2-web-interface/src/components/lookup-tables/LookupTableView.tsx
Fixes: https://github.com/Graylog2/graylog2-server/issues/14373
The test look up for look up tables would manually override uppercase characters to lowercase.
This has be removed in this PR in order to allow looking up keys with uppercase characters.
=> Allow uppercase characters for lookup table test lookup

graylog2-web-interface/src/preflight/components/ConfigurationWizard/CAConfiguration.tsx
This PR is reordering the CA creation/upload tabs in the preflight UI and sets the CA creation tab as default when opening it.
This promotes the least complex option for new users to get up and running as quick as possible.
/nocl
=> Reordering CA creation/upload tabs in preflight UI.

graylog2-web-interface/src/components/common/LoadingIndicator.tsx
This PR is fixing the opacity of the loading indicator for the dark mode.
Before:
After
I considered changing the background of the alert component, but adding a container for the loading indicator is the more pragmatic approach.
Fixes: https://github.com/Graylog2/graylog2-server/issues/16831
/nocl
=> Remove opacity of search loading indicator.

changelog/unreleased/issue-16893.toml, graylog2-web-interface/src/views/components/searchbar/RefreshControls.test.tsx, graylog2-web-interface/src/views/components/searchbar/RefreshControls.tsx
As described in https://github.com/Graylog2/graylog-plugin-enterprise/issues/5896 the behaviour of the search auto-refresh can be confusing.
1. When you make a change, do not submit the form and start the auto-refresh, the search does not contain the latest change.
2. When you make a change while the auto-refresh is active, the search does not contain the latest change
With this PR we are now:
- In case 1 submitting the change when starting the auto-refresh
- in case 2 stoping the auto-refresh, when making changes while it is active. This way the behaviour is unified with similar cases. We also tested submitting the changes in this case, but always ran into issues with this approach.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/5896
=> Unify auto-refresh behaviour by disabling auto-refresh on search bar form changes

graylog2-web-interface/src/pages/ConfigurationsPage.tsx
With this change we hide the menu item for data node configuration page (on System -> Configurations) in cloud deployments.
Fixes: https://github.com/Graylog2/graylog-plugin-enterprise/issues/5982
/nocl
=> Hide menu item for data node configuration page in cloud deployments.

changelog/unreleased/issue-16913.toml, graylog2-web-interface/src/components/content-packs/ContentPackVersions.jsx
Fixes error where only the most recent revision of a content pack could be installed.
All revision modals were being displayed with the latest revision modal on top. This introduces an extra state variable to track which single revision modal should be visible and used to install the appropriate revision.
closes #16913 
dev env
=> Only show selected revision's installation modal

graylog2-server/src/main/java/org/graylog2/configuration/retrieval/SingleConfigurationValueRetriever.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/ConfigurationResource.java, graylog2-server/src/test/java/org/graylog2/configuration/retrieval/SingleConfigurationValueRetrieverTest.java
Retrieval of single config property from exposed config.
/nocl
We do not want to provide all config properties to the FE if only one property is needed.
Manually.
=> Retrieval of single config property from exposed config

changelog/unreleased/pr-16999.toml, graylog2-server/src/main/java/org/graylog2/shared/rest/resources/ProxiedResource.java
The `ProxiedResource` superclass used by REST resources which forward requests to other Graylog nodes in the cluster is providing logic to extract the authentication info of the current user in order to add it to the request sent to another Graylog node.
Prior to this PR, the extraction logic is operating in this order, returning early when the first one succeeds:
- Extracting the `Authorization` header if present
- Extracting a session cookie if present
For our general authentication logic, this order is reversed. This is a problem when a request has both, the `Authorization`-header as well as a session cookie.
This PR is now aligning the logic of the `ProxiedResource` with the general authentication logic, assigning precedence to the session cookie over the `Authorization` header.
Fixes …
=> Fixing extraction order of auth infos in proxied resources.

changelog/unreleased/pr-17012.toml, graylog2-server/src/main/java/org/graylog2/rest/resources/system/logs/LoggersResource.java
modify loggers for indexer subsytem to output sensible data
fixes #17011
=> change loggers for indexer subsystem

data-node/src/main/java/org/graylog/datanode/bootstrap/ServerBootstrap.java, data-node/src/main/java/org/graylog/datanode/management/StateMachineTransitionLogger.java
This avoids constant logging of identical states every 10s:
```
2023-10-20 12:04:06,253 DEBUG: org.graylog.datanode.management.StateMachineTransitionLogger - Triggered HEALTH_CHECK_OK, source state: AVAILABLE, destination: AVAILABLE
2023-10-20 12:04:16,252 DEBUG: org.graylog.datanode.management.StateMachineTransitionLogger - Triggered HEALTH_CHECK_OK, source state: AVAILABLE, destination: AVAILABLE
[...]
```
/nocl
=> Data Node: Do not log state transition when src/dst are identical.

data-node/src/main/java/org/graylog/datanode/periodicals/NodePingPeriodical.java, data-node/src/test/java/org/graylog/datanode/periodicals/NodePingPeriodicalTest.java
To ensure that we always use the hostname that a user has specified.
favoring this over #17004 
/nocl
=> DataNode: Always using the hostname from the configuration in the NodePingPeriodical

graylog2-server/src/main/java/org/graylog/scheduler/DBJobTriggerService.java, graylog2-server/src/main/java/org/graylog/scheduler/JobTriggerDto.java, graylog2-server/src/main/java/org/graylog/scheduler/rest/JobResourceHandlerService.java, graylog2-server/src/main/java/org/graylog2/rest/models/system/SystemJobSummary.java, graylog2-web-interface/src/components/systemjobs/SystemJob.tsx
The duration info will be displayed as a tool-tip on the status badge. Knowing how long it took a job (e.g. archive restore) to complete can be helpful.
Furthermore, this info is persisted with the trigger in the DB, so we could also build something like: show me the (current) slowest running event definition.
/nocl
=> Add execution duration to jobs overview

graylog2-server/src/main/java/org/graylog2/indexer/searches/timerangepresets/conversion/PeriodToRelativeRangeConverter.java, graylog2-server/src/test/java/org/graylog2/indexer/searches/timerangepresets/conversion/PeriodToRelativeRangeConverterTest.java
The migration does not work for months/years, so we have to convert those values into days assuming a standard length of 30 days for a month/365 days for a year first.
**backport into 5.2 from #17054**
fixes #17045 
/nocl
=> Timerange conversion fix for months/years - backport to 5.2

changelog/unreleased/issue-16988.toml, graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailSender.java
A system notification is created when an Email Notification is fired without any recipients. This change adds the Alert Notification ID to the system notification so that users will know what config needs to be updated.
Closes #16988
Locally in dev environment.
One way to reproduce:
1. Create a user 
2. Delete created users email address (I did this manually in MongoDB)
3. Create an email Notification and add the above user as the sole recipient
4. Attach above notification to an Alert
5. Cause the above alert to trigger
=> Add Alert Notification ID to System Notification for Missing Email Recipients

graylog2-web-interface/src/components/rules/rule-builder/helpers.ts
if the value part of a field in the map syntax contains a colon, the fields are now set correctly.
fixes #16983
/nocl
=> allow colon in field values

UPGRADING.md
Removes the `Java API Changes` section from the `5.2` upgrade notes because it only contains a placeholder.
/nocl
=> Remove placeholder for Java API changes from upgrade notes

changelog/unreleased/issue-16096.toml, graylog2-web-interface/src/components/common/DatePicker.test.tsx, graylog2-web-interface/src/components/common/DatePicker.tsx, graylog2-web-interface/src/util/DateTime.ts, graylog2-web-interface/src/views/components/WidgetQueryControls.test.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/AbsoluteDatePicker.tsx
**Please note**, this PR needs a backport for `5.0` and `5.1`
As described in https://github.com/Graylog2/graylog2-server/issues/16096 the highlight for the selected date in the date picker can be wrong for a date time like `2023-10-17 00:00:00`. In this case it displayed the previous day as active.
The reason is that the date time does not contain a time zone information and `moment()` still uses the estimated user time zone internally. For example when your browser timezone is `Europe/Paris` the UTC time for `2023-10-17 00:00:00` is `2023-10-16 22:00:00`.
We are now:
- using `moment.utc()` instead of `moment()` to make it's behaviour predictable for date times without a time zone.
This only effects few cases, because usually timestamps in the frontend have a timezone.
- considering the …
=> Correctly highlight selected day in date picker.

graylog2-web-interface/src/views/logic/slices/viewSlice.ts, graylog2-web-interface/src/views/logic/views/FindNewActiveQuery.test.ts, graylog2-web-interface/src/views/logic/views/FindNewActiveQuery.ts
**Note:** This needs to be backported to `5.2`.
Prior to this PR, the `FindNewActiveQueryId` function is not passed the list of removed tabs when a user removes a dashboard tab. This leads to an error when the first dashboard tab is active and removed.
Fixes #16964.
/nocl
=> Properly select new active dashboard tab when tab is removed.

changelog/unreleased/issue-16096.toml, graylog2-web-interface/src/components/common/DatePicker.test.tsx, graylog2-web-interface/src/components/common/DatePicker.tsx, graylog2-web-interface/src/util/DateTime.ts, graylog2-web-interface/src/views/components/WidgetQueryControls.test.tsx, graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteDatePicker.tsx
**Please note**, this PR is a backport of #16973 for `5.1`.
As described in https://github.com/Graylog2/graylog2-server/issues/16096 the highlight for the selected date in the date picker can be wrong for a date time like `2023-10-17 00:00:00`. In this case it displayed the previous day as active.
The reason is that the date time does not contain a time zone information and `moment()` still uses the estimated user time zone internally. For example when your browser timezone is `Europe/Paris` the UTC time for `2023-10-17 00:00:00` is `2023-10-16 22:00:00`.
We are now:
- using `moment.utc()` instead of `moment()` to make it's behaviour predictable for date times without a time zone.
This only effects few cases, because usually timestamps in the frontend have a timezone.
- considering the …
=> Correctly highlight selected day in date picker. (`5.1`)

graylog2-web-interface/src/views/logic/slices/viewSlice.ts, graylog2-web-interface/src/views/logic/views/FindNewActiveQuery.test.ts, graylog2-web-interface/src/views/logic/views/FindNewActiveQuery.ts
**Note:** This is a backport of #17081 for `5.1`.
Prior to this PR, the `FindNewActiveQueryId` function is not passed the list of removed tabs when a user removes a dashboard tab. This leads to an error when the first dashboard tab is active and removed.
Fixes #16964.
/nocl
=> Properly select new active dashboard tab when tab is removed. (`5.1`)

changelog/unreleased/issue-16096.toml, graylog2-web-interface/src/components/common/DatePicker.test.tsx, graylog2-web-interface/src/components/common/DatePicker.tsx, graylog2-web-interface/src/util/DateTime.ts, graylog2-web-interface/src/views/components/WidgetQueryControls.test.tsx, graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteDatePicker.tsx
**Please note**, this PR is a backport of #16973 for `5.0`.
As described in https://github.com/Graylog2/graylog2-server/issues/16096 the highlight for the selected date in the date picker can be wrong for a date time like `2023-10-17 00:00:00`. In this case it displayed the previous day as active.
The reason is that the date time does not contain a time zone information and `moment()` still uses the estimated user time zone internally. For example when your browser timezone is `Europe/Paris` the UTC time for `2023-10-17 00:00:00` is `2023-10-16 22:00:00`.
We are now:
- using `moment.utc()` instead of `moment()` to make it's behaviour predictable for date times without a time zone.
This only effects few cases, because usually timestamps in the frontend have a timezone.
- considering the …
=> Correctly highlight selected day in date picker. (`5.0`)

changelog/unreleased/issue-16988.toml, graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailSender.java
Backport https://github.com/Graylog2/graylog2-server/pull/17061 to the 5.1 branch.
=> (Backport 5.1) - Add Alert Notification ID to System Notification for Missing Email Recipients

changelog/unreleased/issue-16988.toml, graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailSender.java
Backport https://github.com/Graylog2/graylog2-server/pull/17061 to the 5.2 branch.
=> (Backport 5.2) - Add Alert Notification ID to System Notification for Missing Email Recipients

changelog/unreleased/pr-17059.toml, data-node/src/main/java/org/graylog/datanode/bootstrap/preflight/FullDirSync.java, data-node/src/main/java/org/graylog/datanode/management/OpensearchCommandLineProcess.java, data-node/src/main/java/org/graylog/datanode/management/OpensearchProcessImpl.java, data-node/src/test/java/org/graylog/datanode/bootstrap/preflight/FullDirSyncTest.java
This PR adapts permissions of opensearch configuration files that we sync(=copy and generate) during each datanode startup.
**needs a backport to 5.2**
We should fix not just key material permissions as requested in https://github.com/Graylog2/graylog2-server/issues/17009 but all config files used by the embedded OS.
Added unit test
=> Fix opensearch configuration sync permissions

graylog2-web-interface/src/views/logic/slices/viewSlice.ts, graylog2-web-interface/src/views/logic/views/FindNewActiveQuery.test.ts, graylog2-web-interface/src/views/logic/views/FindNewActiveQuery.ts
**Note:** This is a backport of #17081 for `5.2`.
Prior to this PR, the `FindNewActiveQueryId` function is not passed the list of removed tabs when a user removes a dashboard tab. This leads to an error when the first dashboard tab is active and removed.
Fixes #16964.
/nocl
=> Properly select new active dashboard tab when tab is removed. (`5.2`)

graylog2-web-interface/src/components/perspectives/DefaultBrand.tsx, graylog2-web-interface/src/components/perspectives/bindings.ts, graylog2-web-interface/src/components/perspectives/contexts/PerspectivesContext.ts, graylog2-web-interface/src/components/perspectives/contexts/PerspectivesProvider.tsx, graylog2-web-interface/src/components/perspectives/hooks/useActivePerspective.test.tsx, graylog2-web-interface/src/components/perspectives/hooks/useActivePerspective.ts, graylog2-web-interface/src/components/perspectives/index.d.ts, graylog2-web-interface/src/components/perspectives/types.ts, graylog2-web-interface/src/index.tsx, graylog2-web-interface/src/pages/LoggedInPage.tsx
With this PR we are adding a `PerspectivesProvider`, the `useActivePerspective` hook and a default perspective plugin in preparation for the UI perspectives feature.
/nocl
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/6080
=> Create context provider for UI perspectives

graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/web/resources/PreflightStatusResource.java, graylog2-web-interface/src/preflight/App.test.tsx, graylog2-web-interface/src/preflight/components/ResumeStartupButton.tsx
In the preflight UI, the preflight configuration state is now set to `SKIPPED` if "resume startup" was clicked and there were no data nodes available.
/nocl
In the `SKIPPED` state, Graylog will fall back to using localhost:9200 in the IndexerDiscoveryProvider.
Before, it was always set to `FINISHED`, whether there were data nodes available or not, causing the server to fail at startup with an `IllegalStateException`
fixes #17117
=> set state to SKIPPED if "resume startup" is called with no data nodes

changelog/unreleased/pr-17087.toml, changelog/unreleased/pr-99999.toml, graylog2-server/src/main/java/org/graylog/events/processor/EventStreamService.java, graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessor.java, graylog2-server/src/test/java/org/graylog/events/processor/aggregation/AggregationEventProcessorTest.java
Relates to Graylog2/graylog-plugin-enterprise#6042
When no source stream is given for an event definition we use all streams in the ES/OS search query. We now exclude all non-message streams. 
Users cannot select non-message streams as a source stream in the event definition. But these were still being included in the search when no source stream had been explicitly defined. This is unnecessary, inconsistent, and hurts performance. It may also push the search URI over the length limit, when there is a large number of streams.
=> Exclude non-message streams from search in aggregation events

changelog/unreleased/issue-16096.toml, graylog2-web-interface/src/components/common/DatePicker.test.tsx, graylog2-web-interface/src/components/common/DatePicker.tsx, graylog2-web-interface/src/util/DateTime.ts, graylog2-web-interface/src/views/components/WidgetQueryControls.test.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/AbsoluteDatePicker.tsx
**Please note**, this PR is a backport of #16973 for `5.2`.
As described in https://github.com/Graylog2/graylog2-server/issues/16096 the highlight for the selected date in the date picker can be wrong for a date time like `2023-10-17 00:00:00`. In this case it displayed the previous day as active.
The reason is that the date time does not contain a time zone information and `moment()` still uses the estimated user time zone internally. For example when your browser timezone is `Europe/Paris` the UTC time for `2023-10-17 00:00:00` is `2023-10-16 22:00:00`.
We are now:
- using `moment.utc()` instead of `moment()` to make it's behaviour predictable for date times without a time zone.
This only effects few cases, because usually timestamps in the frontend have a timezone.
- considering the …
=> Correctly highlight selected day in date picker. (`5.2`)

data-node/pom.xml, pom.xml
The caching in the latest upstream version is completely broken since April 2023 and the maintainers are currently unresponsive.
Our fork is based on version 1.6.8 and fixes the excessive download progress logging which is a problem with the log size limit on GitHub Actions.
/jpd https://github.com/Graylog2/graylog-plugin-enterprise/pull/6131
/nocl
=> Update download-maven-plugin to our fork

pom.xml
We backport this update to fix build errors due to corrupted downloads that happen from time to time.
Bumps [com.github.eirslett:frontend-maven-plugin](https://github.com/eirslett/frontend-maven-plugin) from 1.14.0 to 1.14.2.
- [Changelog](https://github.com/eirslett/frontend-maven-plugin/blob/master/CHANGELOG.md)
- [Commits](https://github.com/eirslett/frontend-maven-plugin/compare/frontend-plugins-1.14.0...frontend-plugins-1.14.2)
---
updated-dependencies:
- dependency-name: com.github.eirslett:frontend-maven-plugin dependency-type: direct:production update-type: version-update:semver-patch ...
Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
(cherry picked from commit …
=> Bump com.github.eirslett:frontend-maven-plugin from 1.14.0 to 1.14.2

graylog2-server/src/main/java/org/graylog2/database/filtering/Filter.java, graylog2-server/src/main/java/org/graylog2/database/filtering/RangeFilter.java, graylog2-server/src/main/java/org/graylog2/database/filtering/SingleValueFilter.java, graylog2-server/src/main/java/org/graylog2/database/filtering/inmemory/InMemoryFilterExpressionParser.java, graylog2-server/src/main/java/org/graylog2/database/filtering/inmemory/InMemoryFilterable.java, graylog2-server/src/main/java/org/graylog2/database/filtering/inmemory/SingleFilterParser.java, graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypesListService.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexSetsMappingResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/responses/IndexSetFieldType.java, graylog2-server/src/test/java/org/graylog2/database/filtering/DbFilterExpressionParserTest.java, graylog2-server/src/test/java/org/graylog2/database/filtering/SingleValueFilterTest.java, graylog2-server/src/test/java/org/graylog2/database/filtering/inmemory/InMemoryFilterExpressionParserTest.java, graylog2-server/src/test/java/org/graylog2/database/filtering/inmemory/SingleFilterParserTest.java, graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypesListServiceTest.java
Field type list pagination with querying and filtering.
Support for querying and filtering on Entity Table even if it is not used for Mongo-backed entity, but rather for in-memory object.
/nocl
Required for Field Type Management page.
=> Field type list pagination with querying and filtering.

graylog2-web-interface/src/components/navigation/Navigation.tsx, graylog2-web-interface/src/components/perspectives/PerspectivesSwitcher.tsx, graylog2-web-interface/src/components/perspectives/contexts/PerspectivesProvider.tsx, graylog2-web-interface/src/contexts/ThemeAndUserProvider.tsx, graylog2-web-interface/src/stores/users/PreferencesStore.ts
This PR is adding functionality to persist the current perspective, when it is changed. The way it works is the same as for the current theme:
- when the current user is read-only, the setting is persisted in local storage
- when the current user is read-writable, the setting is persisted in the user preferences
As this is very similar to theming, an abstract `usePersistedSetting` hook is introduced, but inside the `PerspectiveProvider` module. A follow-up PR is already prepared which extracts and reuses it from within `usePreferredColorScheme`.
Fixes Graylog2/graylog-plugin-enterprise#6103.
/nocl
=> Persist currently selected perspective in user preferences.

graylog2-server/src/main/resources/swagger/css/screen.css, graylog2-web-interface/src/views/components/aggregationbuilder/FullSizeContainer.tsx, graylog2-web-interface/src/views/components/datatable/DataTable.css, graylog2-web-interface/src/views/components/sidebar/ContentColumn.tsx, graylog2-web-interface/src/views/components/sidebar/fields/FieldsOverview.tsx
With this PR we are removing no longer needed CSS prefixes. We can remove these because all related styles are well supported, by the browsers we support.
https://developer.mozilla.org/en-US/docs/Glossary/Vendor_Prefix
/nocl
=> Remove no longer needed CSS prefixes.

graylog2-server/src/main/java/org/graylog2/audit/AuditEventTypes.java, graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/mapping/FieldTypeMappingsService.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/field_types/CustomFieldMappingRemovalRequest.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/field_types/FieldTypeMappingsResource.java
Custom mapping removal, capable of removing multiple mappings with one call.
Basic - some complex discussions are ongoing and we are about to decide and implement more complex solution in next PR (i.e. we have not decided how to inform about partial removal success, do we want to raise an error if client asks for removal of non-custom field or will we just silently ignore it... etc.)
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/6152
/nocl
Provide removal tool for FE as quickly as possible.
=> Custom mapping removal (basic)

.github/workflows/dispatch-pr-build.yml, graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config
/nocl
The edit event can detect whether the pr-deps comment has changed and will retrigger the build automatically:
=> Move pull request string extraction to gpi and add autodetection for pr-deps comment change

changelog/unreleased/issue-17285.toml, graylog2-web-interface/src/components/indices/IndexSetFieldTypesList.test.tsx, graylog2-web-interface/src/components/indices/IndexSetFieldTypesList.tsx, graylog2-web-interface/src/hooks/useIndexSetFieldType.ts
This PR adds an option to filtrate field types by field name, type, is custom, or is reserved
for proper work of  is custom and is reserved filtration [PR-17340](https://github.com/Graylog2/graylog2-server/pull/17340) has to be merged 
fix: #17285
=> Add filtering to index field types page

graylog2-web-interface/packages/jest-preset-graylog/jest-preset.js, graylog2-web-interface/packages/jest-preset-graylog/lib/setup-files/mock-ResizeObserver.js, graylog2-web-interface/packages/jest-preset-graylog/package.json, graylog2-web-interface/src/components/bootstrap/Menu.tsx, graylog2-web-interface/src/components/bootstrap/NavDropdown.tsx, graylog2-web-interface/src/components/navigation/HelpMenu.tsx, graylog2-web-interface/src/components/navigation/Navigation.tsx, graylog2-web-interface/src/components/navigation/NavigationLink.test.tsx, graylog2-web-interface/src/components/navigation/NavigationLink.tsx, graylog2-web-interface/src/components/navigation/SystemMenu.test.tsx, graylog2-web-interface/src/components/navigation/SystemMenu.tsx, graylog2-web-interface/src/components/navigation/UserMenu.tsx, graylog2-web-interface/src/routing/AppRouter.test.tsx
This PR is reimplementing the `NavDropdown` & `NavigationLink` components using Mantine. This is one of the requirements for migrating to React 18, as the `react-bootstrap` is not working on React 18.
/nocl
=> Implementing navigation dropdown with Mantine.

changelog/unreleased/issue-14691.toml, graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotification.java, graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationConfig.java, graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationConfigV2.java, graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationV2.java, graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPNotification.java, graylog2-web-interface/src/components/event-notifications/event-notification-details/HttpNotificationDetails.jsx, graylog2-web-interface/src/components/event-notifications/event-notification-details/HttpNotificationDetailsV2.tsx, graylog2-web-interface/src/components/event-notifications/event-notification-types/HttpNotificationForm.jsx, graylog2-web-interface/src/components/event-notifications/event-notification-types/HttpNotificationFormV2.tsx, graylog2-web-interface/src/components/event-notifications/types.d.ts
Adds ability to send the API key/secret as either an HTTP header or query param (as it does now). Just finished up the new Custom HTTP Notification and found this issue on the backlog. Figured I'd preemptively clean it up for the new notification as well as the existing one. 
closes #14691
=> Add option to send HTTP notification API key/secret as header

changelog/unreleased/issue-14691.toml, graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotification.java, graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationConfig.java, graylog2-web-interface/src/components/event-notifications/event-notification-details/HttpNotificationDetails.jsx, graylog2-web-interface/src/components/event-notifications/event-notification-types/HttpNotificationForm.jsx
=> Backport 5.1: Add option to send HTTP notification API Key/Value as header

changelog/unreleased/issue-14691.toml, graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotification.java, graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationConfig.java, graylog2-web-interface/src/components/event-notifications/event-notification-details/HttpNotificationDetails.jsx, graylog2-web-interface/src/components/event-notifications/event-notification-types/HttpNotificationForm.jsx
=> Backport 5.2: Add option to send HTTP notification API Key/Value as header

graylog2-web-interface/src/components/event-definitions/event-definition-form/AddNotificationForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldsList.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationList.jsx
This PR contains a small improvement to unify the styling and naming of buttons in the event definition wizard.
/nocl
=> Unify styling of buttons in event definition wizard.

graylog2-web-interface/src/components/common/PaginatedList.test.tsx, graylog2-web-interface/src/components/errors/ReportedErrorBoundary.tsx, graylog2-web-interface/src/components/navigation/Navigation.test.tsx, graylog2-web-interface/src/components/navigation/Navigation.tsx, graylog2-web-interface/src/components/navigation/SystemMenu.test.tsx, graylog2-web-interface/src/components/navigation/SystemMenu.tsx, graylog2-web-interface/src/hooks/useAlertAndEventDefinitionData.test.tsx, graylog2-web-interface/src/hooks/useAlertAndEventDefinitionData.tsx, graylog2-web-interface/src/hooks/useLocationSearchPagination.test.ts, graylog2-web-interface/src/hooks/useLocationSearchPagination.ts, graylog2-web-interface/src/hooks/usePaginationQueryParameter.test.ts, graylog2-web-interface/src/hooks/usePaginationQueryParameter.ts, graylog2-web-interface/src/routing/useQuery.ts, graylog2-web-interface/src/routing/withLocation.tsx, graylog2-web-interface/src/views/components/contexts/DashboardPageContextProvider.test.tsx, graylog2-web-interface/src/views/components/contexts/DashboardPageContextProvider.tsx, graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.test.tsx
With this PR we are replacing the remaining direct imports of `useLocation` from `react-router-dom` with our own abstraction.
/nocl
=> Always use own abstraction for `useLocation`.

graylog2-web-interface/packages/stylelint-config-graylog/index.js
With this PR we are disabling to rules:
- `media-query-no-invalid`. We are always defining media queries using breakpoints from the theme and the rule throws an error in this case.
- `selector-class-pattern`. When we use classes as selectors in our CSS, we want to override the styling of a library like the ACE editor. In these cases we have no control over the way the classes are named.
/nocl
=> Disable `media-query-no-invalid` and `selector-class-pattern` rules.

changelog/unreleased/pr-17362.toml, graylog2-web-interface/src/components/common/EntityFilters/CreateFilterDropdown.tsx, graylog2-web-interface/src/components/common/EntityFilters/EntityFilters.test.tsx, graylog2-web-interface/src/components/common/EntityFilters/FilterConfiguration/FilterConfiguration.tsx, graylog2-web-interface/src/components/common/EntityFilters/FilterConfiguration/StaticOptionsList.tsx
This PR is fixing two bugs with the entity data table filter select.
1. Before it was possible to create multiple filters for boolean values. Now it is no longer possible to create another filter for a boolean value, when a filter already exists:
2. We are now also making sure it is not possible to select the same static filter option multiple times:
=> Prevent adding same entity data table filter multiple times.

UPGRADING.md, graylog2-web-interface/src/@types/graylog-web-plugin/index.d.ts
This PR is a follow-up for https://github.com/Graylog2/graylog2-server/pull/17309. Since we removed the `systemnavigation` plugin we had to extend the upgrade notes and remove the related types.
/nocl
=> Extend upgrade notes and remove types for `systemnavigation` plugin.

changelog/unreleased/pr-17362.toml, graylog2-web-interface/src/components/common/EntityFilters/CreateFilterDropdown.tsx, graylog2-web-interface/src/components/common/EntityFilters/EntityFilters.test.tsx, graylog2-web-interface/src/components/common/EntityFilters/FilterConfiguration/FilterConfiguration.tsx, graylog2-web-interface/src/components/common/EntityFilters/FilterConfiguration/StaticOptionsList.tsx
**Please note**: This is a backport of #17362 for 5.1
This PR is fixing two bugs with the entity data table filter select.
1. Before it was possible to create multiple filters for boolean values. Now it is no longer possible to create another filter for a boolean value, when a filter already exists:
2. We are now also making sure it is not possible to select the same static filter option multiple times:
=> Prevent adding same entity data table filter multiple times. (`5.1`)

changelog/unreleased/pr-17362.toml, graylog2-web-interface/src/components/common/EntityFilters/CreateFilterDropdown.tsx, graylog2-web-interface/src/components/common/EntityFilters/EntityFilters.test.tsx, graylog2-web-interface/src/components/common/EntityFilters/FilterConfiguration/FilterConfiguration.tsx, graylog2-web-interface/src/components/common/EntityFilters/FilterConfiguration/StaticOptionsList.tsx
**Please note**: This is a backport of #17362 for 5.2
This PR is fixing two bugs with the entity data table filter select.
1. Before it was possible to create multiple filters for boolean values. Now it is no longer possible to create another filter for a boolean value, when a filter already exists:
2. We are now also making sure it is not possible to select the same static filter option multiple times:
=> Prevent adding same entity data table filter multiple times. (`5.2`)

changelog/unreleased/pr-17449.toml, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/OpenSearchClient.java
The dynamic batch size of archiving depends on catching these exceptions
and then retrying the scroll query with a smaller batch size.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/3318
Tested with ES/OS containers with  `http.max_content_length=10mb`  env.
ES:
```
docker run --name elasticsearch -e "http.host=0.0.0.0" -p 9200:9200 -e "xpack.security.enabled=false" -e "http.max_content_length=10mb" -e "discovery.type=single-node" -e "action.auto_create_index=.watches,.triggered_watches,.watcher-history-*"   docker.elastic.co/elasticsearch/elasticsearch:7.10.2
```
OS:
```
docker run -d --name opensearch -p 9200:9200 -p 9600:9600 -e "http.max_content_length=10mb" -e "discovery.type=single-node" -e "DISABLE_INSTALL_DEMO_CONFIG=true" -e "DISABLE_SECURITY_PLUGIN=true" -e …
```
=> Wrap ContentTooLongException into a BatchSizeTooLargeException
