changelog/unreleased/issue-15841.toml
graylog2-server/src/main/java/org/graylog2/contentpacks/NativeEntityConverter.java
graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/EventListEntity.java
graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/MessageListEntity.java
graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/PivotEntity.java
graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/QueryEntity.java
graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/WidgetEntity.java
graylog2-server/src/test/java/org/graylog2/contentpacks/NativeEntityConverterTest.java
graylog2-server/src/test/java/org/graylog2/contentpacks/model/entities/QueryEntityTest.java

Backporting https://github.com/Graylog2/graylog2-server/pull/16085 to 5.0

Referenced search filters are inlined when fetched from Content Packs

---

graylog2-web-interface/src/views/logic/valueactions/createEventDefinition/CreateEventDefinitionModal.tsx

Fix double stringify for event definition creation from value

---

graylog2-server/src/test/java/org/graylog/testing/completebackend/ContainerizedGraylogBackend.java

quick addition too #16117: re-throw the exception after logging. we don't want to swallow it.
/nocl

Re-throw exception after logging search server logs

---

graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/testing/OpenSearchInstance.java

the flag was removed through a different set of changes.
/nocl

Re-adding auto_create_index false

---

graylog2-web-interface/src/logic/telemetry/TelemetrySettingsConfig.tsx

Backport send custom oupt_out event (#16128)

---

graylog2-server/src/test/java/org/graylog/testing/kafka/KafkaContainer.java

The newer images don't use the KAFKA_CFG_ADVERTISED_LISTENERS_FILE
environment anymore, so we have to export the KAFKA_CFG_ADVERTISED_LISTENERS
manually in the command script.
/nocl

Fix KafkaContainer class to work with newer bitnami/kafka images

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java
graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/ClusterAdapterOS2.java
graylog2-server/src/main/java/org/graylog2/indexer/cluster/Cluster.java
graylog2-server/src/main/java/org/graylog2/periodical/IndexRangesCleanupPeriodical.java
graylog2-server/src/main/java/org/graylog2/periodical/IndexRetentionThread.java
graylog2-server/src/test/java/org/graylog/testing/kafka/KafkaContainer.java

To track down some errors with containers in IT tests, I enabled more logging.
/nocl

Added additional logging for IT tests

---

graylog2-web-interface/src/components/common/SourceCodeEditor.tsx

This PR is migrating the `SourceCodeEditor` component to TS.
/nocl

Migrating `SourceCodeEditor` to TS.

---

graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TabKeywordTimeRange.tsx
graylog2-web-interface/src/views/components/sidebar/NavItem.tsx

This PR contains two small styling improvements for the search page.
/nocl

Small styling improvements for search page (sidebar and time range picker keyword tab)

---

changelog/unreleased/pr-16195.toml
graylog2-web-interface/src/components/event-definitions/constants.ts
graylog2-web-interface/src/components/event-definitions/event-definitions-types.ts
graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionsContainer.tsx

Added a new Event Definition column: Last Matched.
fixes https://github.com/Graylog2/graylog2-server/issues/15751

EventDefinition new column: Last Matched

---

.github/scripts/web-code-quality.sh
.github/workflows/fix-linter-hints.yml

Prior to this PR, we were already collecting the number of linter hints present in the code base through the job which is fixing auto-fixable linters hints.
This PR is now extending the workflow to collect additional metrics:
- Usages of `createReactClass`
- Usages of `Reflux`
- Tests using `enzyme` vs `testing-library`
- JS(X) files vs TS(X) files
/nocl

Adding more code quality metrics.

---

graylog2-web-interface/src/theme/docs/Colors.md

Before this change the colors overview in the style guide did not rendered because of an error.
/nocl

Fix colors overview in style guide.

---

graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/OpenSearch13Instance.java
graylog2-server/src/test/java/org/graylog/testing/elasticsearch/TestableSearchServerInstance.java

Disable demo certs for OS1.3 in matrix tests, better logging from containers

---

.github/workflows/fix-linter-hints.yml

This PR is fixing the changes performed in #16240 by making sure that `curl` is reading the body from STDIN.
/nocl

Read metrics from stdin when posting to endpoint.

---

data-node/src/test/java/org/graylog/datanode/integration/DatanodeSecurityTestUtils.java
graylog2-server/src/main/java/org/graylog/security/certutil/CertutilCa.java
graylog2-server/src/main/java/org/graylog/security/certutil/CertutilCert.java
graylog2-server/src/main/java/org/graylog/security/certutil/CertutilCsr.java
graylog2-server/src/main/java/org/graylog/security/certutil/CertutilCsrSign.java
graylog2-server/src/main/java/org/graylog/security/certutil/CertutilHttp.java
graylog2-server/src/main/java/org/graylog/security/certutil/console/CommandLineConsole.java
graylog2-server/src/main/java/org/graylog/security/certutil/console/SystemConsole.java
graylog2-server/src/main/java/org/graylog/security/certutil/console/TestableConsole.java
graylog2-server/src/test/java/org/graylog2/security/CustomCAX509TrustManagerTest.java
graylog2-server/src/test/java/org/graylog2/security/certutil/CertutilCaTest.java
graylog2-server/src/test/java/org/graylog2/security/certutil/CertutilCertTest.java
graylog2-server/src/test/java/org/graylog2/security/certutil/CertutilHttpTest.java

/nocl
Typesafe and standardized approach to handling prompt questions in command line console usages.
Existing set of tests

typesafe handling of prompts in command line console usages

---

.github/dependabot.yml

This PR is making sure that dependabot updates font awesome dependencies together.
/nocl

Grouping font awesome dependencies.

---

graylog2-server/src/test/java/org/graylog/testing/containermatrix/SearchServer.java

Update opensearch 1.3 in matrix tests to 1.3.12

---

changelog/unreleased/issue-integrations-1341.toml
changelog/unreleased/pr-integrations-1340.toml
changelog/unreleased/pr-integrations-1348.toml

In #16274 we merged the integrations plugin into core. Unfortunately, some changelog snippets were forgotten. This PR is adding them back and rewriting their issue/PR references when necessary.

Adding unreleased changelog snippets from integrations plugin.

---

data-node/src/main/java/org/graylog/datanode/bootstrap/preflight/DataNodeConfigurationPeriodical.java
graylog2-server/src/main/java/org/graylog/security/certutil/CertutilCsr.java
graylog2-server/src/main/java/org/graylog/security/certutil/PathConverter.java
graylog2-server/src/main/java/org/graylog/security/certutil/PathTypeConverterProvider.java
graylog2-server/src/main/java/org/graylog/security/certutil/privatekey/PrivateKeyEncryptedFileStorage.java
graylog2-server/src/test/java/org/graylog/security/certutil/privatekey/PrivateKeyEncryptedFileStorageTest.java

Writing the PK to a location that is writable in docker.
/nocl

DataNode: writing the PK to a writeable location

---

data-node/src/main/java/org/graylog/datanode/OpensearchDistribution.java
data-node/src/test/java/org/graylog/datanode/testinfra/DatanodeContainerizedBackend.java

Fix to use the correct jar corresponding to the system architecture in tests.
/nocl

DataNode: Use the correct architecture for the distribution jar in tests

---

graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java
graylog2-server/src/main/java/org/graylog2/migrations/V20230904073300_MigrateThemePreferences.java
graylog2-server/src/test/java/org/graylog2/migrations/V20230904073300_MigrateThemePreferencesTest.java
graylog2-server/src/test/resources/org/graylog2/migrations/V20230904073300_MigrateThemePreferences/no_users_with_theme_preferences.json
graylog2-server/src/test/resources/org/graylog2/migrations/V20230904073300_MigrateThemePreferences/users_with_theme_preferences.json
graylog2-web-interface/src/theme/UseCurrentThemeMode.ts
graylog2-web-interface/src/theme/constants.ts

This PR is adding a migration which is changing user theme mode preferences from the old naming (`teint`/`noir`) to new, common one (`light`/`dark`).
/nocl

Migrating `teint`/`noir` theme names to `light`/`dark` in user prefs.

---

graylog2-server/src/test/java/org/graylog/testing/mongodb/MongoDBContainer.java
graylog2-server/src/test/java/org/graylog/testing/mongodb/MongoDBExtension.java
graylog2-server/src/test/java/org/graylog/testing/mongodb/MongoDBTestService.java

This PR ensures that networks created by the `MongoDBExtension` are closed after use.
/nocl

Making sure `Network` instance is closed for `MongoDBExtension`.

---

data-node/pom.xml

update opensearch rest client to 2.9.0-1

---

data-node/src/main/java/org/graylog/datanode/process/OpensearchConfiguration.java

This PR is disabling index auto-creation for the data node.
/nocl

Disabling auto-creation for data node.

---

graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/web/resources/PreflightAssetsResource.java

This PR is fixing up the paths for the preflight assets resource. Prior to this PR, a warning was emitted that an empty path is used for the resource class.
/nocl

Fixing up preflight asset resource method paths.

---

data-node/src/main/java/org/graylog/datanode/configuration/variants/OpensearchSecurityConfiguration.java

disable opensearch auditlog inside datanode

---

changelog/unreleased/pr-16407.toml
graylog2-server/src/main/java/org/graylog2/bindings/PeriodicalBindings.java
graylog2-server/src/main/java/org/graylog2/periodical/LeaderPresenceCheckPeriodical.java
graylog2-server/src/main/java/org/graylog2/periodical/NodePingThread.java

Backport: Extract "no leader node" notifications from NodePingThread

---

graylog2-web-interface/package.json
graylog2-web-interface/yarn.lock

This PR is removing pinned package versions which have become obsolete.
/nocl

Removing unused pinned package versions.

---

graylog-project-parent/pom.xml
pom.xml

- Manage the Scala dependencies
- Update kafka09 to 0.9.0.1-7 to fix a Scala dependency issue and a shading problem

Fix Scala dependency management

---

UPGRADING.md

Update UPGRADING.md to reflect Microsoft Defender for Endpoint Input parsing changes in https://github.com/Graylog2/graylog-plugin-enterprise/pull/5775
/nocl

Update UPGRADING.md to Reflect MS Defender for Endpoint Input Changes

---

changelog/unreleased/pr-15380.toml
graylog2-server/src/main/java/org/graylog/plugins/sidecar/SidecarModule.java
graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20230502164900_AddSidecarManagerAndReaderRole.java
graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/SidecarResource.java

create additional Sidecar roles(#15380) - backport 5.0

---

changelog/unreleased/pr-15380.toml
graylog2-server/src/main/java/org/graylog/plugins/sidecar/SidecarModule.java
graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20230502164900_AddSidecarManagerAndReaderRole.java
graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/SidecarResource.java

create additional Sidecar roles(#15380) - backport 5.1 

---

pom.xml

This reverts commit 3db66692be97b17f5a188167b378f49b473d0fe3.
The version of node.js being updated to is built against glibc 2.28,
which is not present on all of our CI workers.
/nocl

Revert "Bumping nodejs version used in build to most recent LTS. (#16467)"

---

full-backend-tests/src/test/java/org/graylog2/indexer/fieldtypes/FieldTypeMappingsIT.java

This PR is disabling `FieldTypeMappingsIT#changeFieldTypeFromStringToIp` as it has turned out to be flaky at the moment.
/nocl

Disabling field type mapping change integration test for now.

---

full-backend-tests/src/test/java/org/graylog2/indexer/fieldtypes/FieldTypeMappingsIT.java

This PR is improving the `FieldTypeMappingsIT` test. Previously, it was flaky because in some conditions the initial index allocation of the index set created in the test was not completed when the index rotation through the field type mapping change was triggered. This lead to the expected index `custom-mappings_1` to never appear, because the rotation triggered the creation of the initial one (`custom-mappings_0`).
This PR is now waiting for the initial index creation to synchronize all further steps.
/nocl

Waiting for initial index allocation in test.

---

.github/dependabot.yml

This PR is adding more dependency groups to the dependabot config, so related dependencies are grouped conveniently when updated.
/nocl

Adding more groups to dependabot config.

---

data-node/src/test/java/org/graylog/datanode/testinfra/DatanodeDevContainerBuilder.java
graylog2-server/src/test/java/org/graylog/testing/datanode/DatanodeDevContainerBuilder.java

- added the root user to the interface of the builder so that all 3elements (user, pass, secret) can be set
- removed obsolete old env vars 
/nocl

DataNode: small refactoring, added the root user to the interface, removed obsolete env vars

---

graylog2-web-interface/src/preflight/components/ConfigurationWizard/CACreateForm.test.tsx
graylog2-web-interface/src/preflight/components/ConfigurationWizard/CACreateForm.tsx
graylog2-web-interface/yarn.lock

With this PR we are removing two not needed inputs in the "Create CA" step of the preflight UI.
I did not removed the form element, to simplify future changes and because it is helpful for e.g. the loading state.
/nocl

Remove not needed inputs in create CA step of preflight UI.

---

graylog2-web-interface/src/logic/telemetry/TelemetryInfoText.tsx

Fix link to Privacy Policy in dialogue block
(cherry picked from commit 3a4eddbaeb5c845bb1a0935db06821621f2aaadc)
/nocl

Update TelemetryInfoText.tsx (#15663) (5.1 backport)

---

pom.xml

This PR is performing the same update for node.js which was already performed in #16467, but which was reverted after discovering that some jenkins workers do still run on Ubuntu 18.04, with a glibc which is too old to run modern `node` binaries.
Now that all jenkins workers are running Ubuntu 20.04 (thanks @bernd!), we can perform the update again.
This PR is updating node.js to the most recent LTS, as node 16 is EOL since september 11.
/nocl

Bumping nodejs version used in build to most recent LTS.

---

.github/dependabot.yml

Also, add a "maven" label to simplify filtering.
/nocl

Increase number of open Maven PRs

---

graylog2-web-interface/package.json
graylog2-web-interface/yarn.lock

Due to updates, the `buffer` dependency is not required explicitly anymore and can be removed.
/nocl

Remove unused `buffer` dependency.

---

graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/GraylogCertificateProvisioningPeriodical.java

There was the wrong event bus usage in the provisioning periodical.
/nocl

Datanode: Fixing eventbus usage

---

graylog-project-parent/pom.xml
pom.xml

Remove management of unused zookeeper and zkclient dependencies

---

graylog2-web-interface/src/util/DocsHelper.ts

This PR is typing and simplifying the `DocsHelper` module.
/nocl

Type and simplify `DocsHelper` module.

---

graylog-project-parent/pom.xml
pom.xml

- Remove management of unused elasticsearch-maven-plugin
- Remove nosqlunit-elasticsearch2 test dependency
Closes #16599
Closes #16593
/nocl

Remove unused elasticsearch plugin and test helper

---

graylog2-server/src/main/java/org/graylog/security/certutil/CertRenewalServiceImpl.java

Don't create a notification if the list of certificates that needs renewal is empty ;-)
/nocl

DataNode: Fix cert renewal notification

---

.github/workflows/build.yml

Backport of https://github.com/Graylog2/graylog2-server/pull/16411
/nocl

Backport: Bump actions/checkout and actions/cache to fix cache restore issue to 5.0

---

UPGRADING.md
graylog2-server/src/main/java/org/graylog/schema/VendorFields.java

Backport https://github.com/Graylog2/graylog2-server/pull/16169 to the `5.1` branch.
Core changes needed for https://github.com/Graylog2/graylog-plugin-enterprise-integrations/pull/1093.
/nocl

Add new GIM Schema fields, update UPGRADING.md (5.1)

---

graylog2-web-interface/src/components/configurations/DataNodeConfiguration/CertificateRenewal.tsx
graylog2-web-interface/src/components/configurations/DataNodeConfiguration/CertificateRenewalPolicyConfig.tsx
graylog2-web-interface/src/components/configurations/DataNodeConfiguration/DataNodeConfiguration.tsx
graylog2-web-interface/src/components/configurations/DataNodeConfiguration/index.tsx
graylog2-web-interface/src/pages/ConfigurationsPage.tsx
graylog2-web-interface/src/preflight/hooks/useConfigurationStep.test.tsx
graylog2-web-interface/src/preflight/types.ts
graylog2-web-interface/test/fixtures/dataNodes.ts

With this PR we implement an option to provision the certificate for data nodes in the core UI.
/nocl

Implement option to provision certificates for data nodes in the web interface

---

pom.xml

Changes:
- https://github.com/mojohaus/versions/releases/tag/versions-maven-plugin-2.12.0
- https://github.com/mojohaus/versions/releases/tag/2.13.0
- https://github.com/mojohaus/versions/releases/tag/2.14.0
- https://github.com/mojohaus/versions/releases/tag/2.14.1
- https://github.com/mojohaus/versions/releases/tag/2.14.2
- https://github.com/mojohaus/versions/releases/tag/2.15.0
- https://github.com/mojohaus/versions/releases/tag/2.16.0
- https://github.com/mojohaus/versions/releases/tag/2.16.1
/nocl

Update versions-maven-plugin to 2.16.1

---

data-node/pom.xml
graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/testing/OpenSearchInstance.java
graylog2-server/src/test/java/org/graylog/testing/containermatrix/SearchServer.java

This PR is updating the bundled OpenSearch in the Data Node as well as the one used in tests to `v2.10.0`.
/nocl

Bumping OpenSearch to `v2.10.0`.

---

data-node/src/main/java/org/graylog/datanode/bindings/GenericBindings.java
data-node/src/main/java/org/graylog/datanode/bindings/GenericInitializerBindings.java
data-node/src/main/java/org/graylog/datanode/configuration/OpensearchConfigurationProvider.java
data-node/src/main/java/org/graylog/datanode/management/OpensearchProcessImpl.java

- if we've configured the initial manager nodes  per env, use the setting, also after preflight
- else if we're in preflight, initially use all active datanodes, don't set the setting after preflight
/nocl

DataNode: Automatic initial manager nodes

---

graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/GraylogCertificateProvisioningPeriodical.java
graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/NullNotificationService.java
graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/PreflightWebModule.java
graylog2-server/src/main/java/org/graylog2/notifications/Notification.java
graylog2-server/src/main/resources/org/graylog2/freemarker/templates/HTML/data_node_needs_provisioning.ftl
graylog2-server/src/main/resources/org/graylog2/freemarker/templates/PLAINTEXT/data_node_needs_provisioning.ftl
graylog2-web-interface/src/logic/notifications/NotificationsFactory.jsx
graylog2-web-interface/src/logic/notifications/NotificationsFactory.tsx
graylog2-web-interface/src/routing/Routes.ts
graylog2-web-interface/src/stores/notifications/NotificationsStore.ts

This PR is creating a system notification when the periodical check finds out that there is a data node which is unprovisioned and the renewal policy is set to manual.
/nocl

Create notification if data node needs provisioning confirmation.

---

graylog2-web-interface/src/components/configurations/DataNodeConfiguration/CertificateRenewal.tsx
graylog2-web-interface/src/preflight/components/Setup/DataNodesOverview.tsx

This PR is improving the visual appearance of data nodes in both pre-flight and post-flight lists.
/nocl
Before:
After:
Before:
After:

Visually highlight data nodes by state.

---

data-node/src/main/java/org/graylog/datanode/bindings/GenericBindings.java
data-node/src/main/java/org/graylog/datanode/management/OpensearchProcess.java
data-node/src/main/java/org/graylog/datanode/management/OpensearchProcessImpl.java
data-node/src/main/java/org/graylog/datanode/periodicals/NodePingPeriodical.java
data-node/src/test/java/org/graylog/datanode/periodicals/NodePingPeriodicalTest.java
graylog2-server/src/main/java/org/graylog2/cluster/NodeService.java
graylog2-server/src/main/java/org/graylog2/cluster/NodeServiceImpl.java
graylog2-server/src/test/java/org/graylog2/cluster/TestNodeService.java

Simplification of the existing code, URIs are not needed. This is a follow-up PR.
/nocl

Datanode: setting initial master nodes simplification

---

graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/GraylogCertificateProvisioningPeriodical.java

This PR is lowering the log-level of diagnostic messages in the provisioning periodical in order to avoid spamming the server log.
/nocl

Lowering log-level in provisioning periodical.

---

data-node/src/main/java/org/graylog/datanode/bindings/GenericBindings.java
graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/ServerPreflightChecksModule.java
graylog2-server/src/main/java/org/graylog2/security/TrustManagerAndSocketFactoryProvider.java
graylog2-server/src/main/java/org/graylog2/shared/security/SecurityBindings.java

allow usage of default X509TrustManager in forwarder
/nocl

switch injection from implementation to interface

---

graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/web/resources/PreflightResource.java

This PR ensures that the certificate renewal policy is also reset, when a user decides to restart preflight setup.
/nocl

Reset renewal policy when restarting preflight mode.

---

data-node/src/main/java/org/graylog/datanode/Configuration.java
data-node/src/main/java/org/graylog/datanode/configuration/OpensearchConfigurationProvider.java
data-node/src/main/java/org/graylog/datanode/initializers/JerseyService.java

/nocl
- [x I have read the **CONTRIBUTING** document.

DataNode: Simplifying hostname usage Part 2

---

graylog2-web-interface/src/components/hotkeys/HotkeysModal.tsx

With this PR we are adding a missing title for the keyboard shortcuts modal, which is required for e2e tests.
/nocl

Add missing title for keyboard shortcuts modal.

---

changelog/unreleased/pr-16773.toml
graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config

This PR is toggling the field type management feature flag to be turned on by default, enabling it for general usage.

Toggle field type management feature flag.

---

graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/PreflightWebModule.java

Install missing lock service module in pre-flight module

---

data-node/src/main/java/org/graylog/datanode/configuration/variants/OpensearchSecurityConfiguration.java

/nocl
Fixes #16219
It removes possible security weaknes
Existing set of integration tests (Mainly the SSL enabled DatanodeClusterIT)

Re-enable hostname verification in opensearch

---

graylog2-web-interface/src/preflight/components/ConfigurationWizard/CAUpload.tsx

This change is improving the frontend for uploading a CA bundle by:
- Explaining better what format is expected
- Make sure that only a single file is uploaded
- Fixes removing of selected/dropped files
/nocl

Improving frontend for uploading CA bundle.

---

data-node/src/main/java/org/graylog/datanode/Configuration.java
misc/datanode.conf

Full example with all relevant config vars + explanations
TODO: maybe thinning out some more unused/unnecessary options?
fixes #16659 
/nocl

DataNode: full datanode.conf example

---

graylog2-server/src/main/java/org/graylog2/audit/AuditEventTypes.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/field_types/FieldTypeMappingsResource.java

This PR is adding audit event creation to functionality which is adding a new field type mapping.
/nocl

Adding audit event for field type mapping creation.

---

graylog2-web-interface/src/components/common/KeyCapture.test.tsx
graylog2-web-interface/src/components/common/KeyCapture.tsx
graylog2-web-interface/src/components/hotkeys/HotkeysModalContainer.tsx
graylog2-web-interface/src/contexts/HotkeysProvider.tsx
graylog2-web-interface/src/hooks/useHotkey.tsx
graylog2-web-interface/src/logic/telemetry/Constants.ts
graylog2-web-interface/src/views/components/searchbar/SaveAsDashboardButton.tsx
graylog2-web-interface/src/views/components/searchbar/SaveDashboardButton.tsx
graylog2-web-interface/src/views/components/searchbar/saved-search/SearchActionsMenu.tsx
graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TimeRangePicker.tsx
graylog2-web-interface/src/views/components/sidebar/redo/RedoNavItem.tsx
graylog2-web-interface/src/views/components/sidebar/undo/UndoNavItem.tsx

In this PR we are doing few improvements for `useHotkey` hook  
- Telemetry refactoring: _Using a new approach for `event_type`, removing `telemetryAppPathname` usage from unnecessary places and use location as by default_
- Refactoring of `KeyCapture` to use `useHotkey` instead of mousetrap
/nocl

Hotkey improvements

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Elasticsearch7Module.java
graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ProxyRequestAdapterES7.java
graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/OpenSearch2Module.java
graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/ProxyRequestAdapterOS2.java
graylog2-server/src/main/java/org/graylog2/audit/AuditEventTypes.java
graylog2-server/src/main/java/org/graylog2/indexer/datanode/ProxyRequestAdapter.java
graylog2-server/src/main/java/org/graylog2/rest/resources/RestResourcesModule.java
graylog2-server/src/main/java/org/graylog2/rest/resources/datanodes/DataNodeApiProxyResource.java
graylog2-server/src/main/java/org/graylog2/storage/VersionAwareStorageModule.java
graylog2-server/src/main/java/org/graylog2/storage/providers/ProxyRequestAdapterProvider.java

Introduce API resource allowing to query OpenSearch APIs of data nodes.

---

changelog/unreleased/issue-5793.toml
graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/export/ElasticsearchExportBackend.java
graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/export/ElasticsearchExportBackendIT.java
graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/export/OpenSearchExportBackend.java
graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/views/export/OpenSearchExportBackendIT.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/export/CommandFactory.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/export/ExportBackend.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/export/ExportMessagesCommand.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/export/CommandFactoryTest.java

Export problem fixed, some code duplication eliminated (#16896)

---

graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/GraylogCertificateProvisioningPeriodical.java
graylog2-server/src/main/java/org/graylog2/cluster/preflight/DataNodeProvisioningConfig.java

Prior to this PR, when connectivity checks for a data node failed after retrying, a very generic error message was shown, which does not help the user to fix the problem.
This PR is now making sure that the actual exception is propagated and the cause extracted when retrying fails.
/nocl
Before:
After:

Extract error after retrying failed.

---

data-node/src/main/java/org/graylog/datanode/configuration/variants/OpensearchSecurityConfiguration.java
graylog2-server/src/main/java/org/graylog/security/certutil/CaServiceImpl.java
graylog2-server/src/main/java/org/graylog/security/certutil/CertutilCa.java
graylog2-server/src/main/java/org/graylog/security/certutil/ca/CAKeyPair.java
graylog2-server/src/main/java/org/graylog/security/certutil/csr/CsrSigner.java

This PR is doing the following:
- Adding loopback (`localhost`, `127.0.0.1`, `::1`) addresses to the
SAN
- Adding the IP of the primary host name to the SAN, if it can be
resolved
- Reenabling hostname verification
/nocl

Adding loopback addresses & primary IP to cert.

---

graylog2-server/src/main/java/org/graylog/security/certutil/CertRenewalServiceImpl.java

After refactoring the certs, the "root" cert no longer exists and the code creates an NPE when the interval comes due.
/nocl

DataNode: Removing the cert check for "root" as this cert no longer exists

---

graylog2-server/src/main/java/org/graylog2/Configuration.java
graylog2-server/src/main/java/org/graylog2/configuration/ExposedConfiguration.java
graylog2-server/src/test/java/org/graylog2/configuration/ExposedConfigurationTest.java

`minimum_auto_refresh_interval` config setting added
/nocl
Needed to implement a solution for https://github.com/Graylog2/graylog-plugin-enterprise/issues/5138
Manually.

minimum_auto_refresh_interval config setting added

---

graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/mapping/FieldTypeMappingsService.java

This PR is making sure that any error during a field type change is propagated to the frontend.
Fixes #16978.
/nocl

Propagating error during field type change to frontend.

---

graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java
graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/mapping/FieldTypeMappingsService.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/field_types/FieldTypeMappingsResource.java
graylog2-web-interface/src/logic/message/MessageFieldsFilter.ts
graylog2-web-interface/src/views/Constants.ts
graylog2-web-interface/src/views/components/sidebar/fields/List.tsx
graylog2-web-interface/src/views/logic/IsFilteredField.ts
graylog2-web-interface/src/views/logic/IsReservedField.ts
graylog2-web-interface/src/views/logic/fieldactions/ChangeFieldType/ChangeFieldType.tsx

**Note:** Requires #17000 to be merged before.
This PR is preventing both API and frontend to attempt changing the field types of reserved fields.
On the side, it is performing some refactoring by migrating to TS, changing naming, consolidating lists of filtered/reserved fields.
Fixes #16979.
/nocl

Prevent changing field types of reserved fields.

---

graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/export/ElasticsearchExportBackendIT.java
graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/export/ElasticsearchExportITHelper.java
graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/views/export/OpenSearchExportBackendIT.java
graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/views/export/OpenSearchExportITHelper.java
graylog2-server/src/test/java/org/graylog/storage/views/export/ExportITHelper.java

Refactoring integration tests for Exports.
/nocl
1. Remove code duplication.
2. Make it possible to write tests in enterprise module, with enterprise features like "Search Filters".

Refactoring integration tests for Exports

---

changelog/unreleased/issue-16913.toml
graylog2-web-interface/src/components/content-packs/ContentPackVersions.jsx

Backport #16943 to 5.1 to fix #16913

Backport 5.1: Only show selected revision's installation modal (#16943)

---

data-node/src/main/java/org/graylog/datanode/Configuration.java
data-node/src/main/java/org/graylog/datanode/bootstrap/ServerBootstrap.java
data-node/src/main/java/org/graylog/datanode/commands/Server.java
data-node/src/main/java/org/graylog/datanode/configuration/OpensearchConfigurationProvider.java

Registering the node on startup so it can be found as an active node right away.
/nocl

DataNode: Node registration on startup

---

data-node/src/main/java/org/graylog/datanode/bootstrap/preflight/DataNodeConfigurationPeriodical.java
graylog2-server/src/main/java/org/graylog/security/certutil/CertRenewalServiceImpl.java
graylog2-server/src/main/java/org/graylog/security/certutil/csr/CsrGenerator.java
graylog2-server/src/main/java/org/graylog/security/certutil/csr/storage/CsrFileStorage.java
graylog2-server/src/main/java/org/graylog/security/certutil/csr/storage/CsrMongoStorage.java
graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/web/resources/PreflightResource.java
graylog2-server/src/main/java/org/graylog2/cluster/preflight/DataNodeProvisioningBusEvents.java
graylog2-server/src/main/java/org/graylog2/cluster/preflight/DataNodeProvisioningService.java
graylog2-server/src/main/java/org/graylog2/cluster/preflight/DataNodeProvisioningServiceImpl.java

On some distributions, `127.0.0.1` or `::1` might resolve to something else than `localhost`, so these need to be included in the SAN as well.  This PR is now trying to resolve both loopback-addresses and includes their reverse PTR in the CSR.
/nocl

Data Node: Add reverse lookups for local loopback-addresses as well.

---

graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetConfig.java

Removed unneeded comment and annotation.
/nocl
1 less TODO.

Removed unneeded comment and annotation

---

pom.xml

See https://square.github.io/okhttp/changelogs/changelog_4x/#version-4120
/nocl

Update okhttp to version 4.12.0

---

changelog/unreleased/pr-17025.toml

DataNode: Added missing changelog for PR #17025

---

.github/workflows/dispatch-pr-build.yml

Dispatch a PR build to graylog-project-internal.
Provide all the necessary informations so that the dispatched build can update the commit status on the calling PR.
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/6111
/nocl

Request a dispatched PR build

---

.github/workflows/changelog.yml
changelog/unreleased/pr-17202.toml

Add changelog check workflow

---

changelog/unreleased/pr-17233.toml
graylog2-web-interface/src/pages/EditContentPackPage.jsx

Fix contentPack create revision not redirecting after creation

---

changelog/unreleased/pr-17042.toml
graylog2-server/src/main/java/org/graylog2/telemetry/rest/TelemetryResponseFactory.java
graylog2-server/src/main/java/org/graylog2/telemetry/rest/TelemetryService.java
graylog2-server/src/test/java/org/graylog2/telemetry/rest/TelemetryServiceTest.java
graylog2-server/src/test/java/org/graylog2/telemetry/rest/TelemetryServiceWithDbTest.java
graylog2-server/src/test/java/org/graylog2/telemetry/rest/TelemetryTestHelper.java
graylog2-web-interface/src/logic/telemetry/TelemetryProvider.tsx
graylog2-web-interface/src/logic/telemetry/useTelemetryData.tsx

**Note:** This needs a backport to `5.2`.
This PR is extending current telemetry info with basic data node usage information (# of nodes).
/nocl

Include basic data node usage information in telemetry.

---

changelog/unreleased/pr-17042.toml
graylog2-server/src/main/java/org/graylog2/telemetry/rest/TelemetryResponseFactory.java
graylog2-server/src/main/java/org/graylog2/telemetry/rest/TelemetryService.java
graylog2-server/src/test/java/org/graylog2/telemetry/rest/TelemetryServiceTest.java
graylog2-server/src/test/java/org/graylog2/telemetry/rest/TelemetryServiceWithDbTest.java
graylog2-server/src/test/java/org/graylog2/telemetry/rest/TelemetryTestHelper.java
graylog2-web-interface/src/logic/telemetry/TelemetryProvider.tsx
graylog2-web-interface/src/logic/telemetry/useTelemetryData.tsx

**Note:** This is a backport of #17042 to `5.2`.
This PR is extending current telemetry info with basic data node usage information (# of nodes).
/nocl

Include basic data node usage information in telemetry. (`5.2`)

---

changelog/unreleased/issue-17040.toml
graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/models/Collector.java
graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/CollectorResource.java
graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/CollectorService.java
graylog2-server/src/test/java/org/graylog/plugins/sidecar/collectors/SidecarServiceTest.java

Backport of #17246
* add CRC for default template
* add hardcode prior version CRCs
* update CL
* Only update if different
* log if ignoring an unknown, old template
* more legacy CRCs
* review feedback fixes
* handle PUT and POST correctly
* remove redundant CRC in request
(cherry picked from commit 3657b944c2028ac113fc6abd5971fb26c50c44d7)

Add CRC to sidecar default template (#17246)

---

graylog2-server/src/main/java/org/graylog/events/notifications/EventBacklogService.java

Fix minor typo that I noticed.
/nocl

Fix typo in exception message

---

graylog2-web-interface/src/components/indices/IndexMaintenanceStrategiesConfiguration.tsx

Fix margin on index set configuration page.

---

changelog/unreleased/pr-17280.toml
graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.tsx

Fix Sidecar collector configuration form submit button not being clickable

---

.github/workflows/dispatch-main-build.yml

Add a dispatch workflow for main/master pushes

---

graylog2-web-interface/package.json
graylog2-web-interface/src/polyfill.js

This PR is removing the remaining IE11 polyfills. IE11 support has been dropped a while ago, so this is not a breaking change.
/nocl

Removing IE11 polyfills.

---

graylog2-server/src/main/java/org/graylog/events/contentpack/entities/HttpEventNotificationConfigV2Entity.java
graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationConfigV2.java

* Add missing headers to content pack
* Fix Time Zone export
/nocl

Fix Custom HTTP Notification content pack 

---

graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypesListService.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/responses/IndexSetFieldType.java

Filter options for is_custom and is_reserved fields.
Additionally, a small bug related to calculating total count has been fixed.
/nocl
Needed by FE.

Filter options for is_custom and is_reserved fields

---

changelog/unreleased/issue-17199.toml
graylog2-web-interface/changelog/unreleased/issue-17199.toml
graylog2-web-interface/src/components/events/events/Events.jsx
graylog2-web-interface/src/components/events/events/EventsSearchBar.jsx

Fixes https://github.com/Graylog2/graylog2-server/issues/17199 also for 5.1.
It was originally fixed by https://github.com/Graylog2/graylog2-server/pull/15357 in 5.2.
Backporting this PR is not straight forward as there have been multiple structural changes in this file (between those two commits) so I extracted the code part that fixed it instead.

Fix page size select not working on Alerts & Events page

---

changelog/unreleased/issue-6032.toml
graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java
graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/arrays/AbstractArrayFunction.java
graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/arrays/ArrayContains.java
graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/arrays/ArrayRemove.java
graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/arrays/StringArrayAdd.java
graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/lookup/LookupAll.java
graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/arrayContains.txt
graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/arrayRemove.txt
graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/lookupAll.txt
graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/stringArrayAdd.txt
graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/with-arrays.json

Backport of https://github.com/Graylog2/graylog2-server/pull/17205 to 5.2.
Companion PR to: https://github.com/Graylog2/graylog-plugin-enterprise/pull/6160
Closes: https://github.com/Graylog2/graylog-plugin-enterprise/issues/6032

Backport 5.2 (Open) - Make Illuminate Pipeline Functions Available for General Use

---

graylog2-web-interface/src/components/navigation/UserMenu.tsx

In #17344, the navigation dropdown component was replaced.  Unfortunately, this broke finding the user menu programmatically.
This PR is now adding a title prop to make the user menu findable again.
/nocl

Restore finding user menu in tests.

---

graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypesListService.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexSetsMappingResource.java
graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypesListServiceTest.java

Endpoint providing all field types for index set.
/nocl
FE want a list of all field as well, not only the paginated version.
With new unit tests and manually.

Endpoint for all fields

---

changelog/unreleased/pr-17012.toml
graylog2-server/src/main/java/org/graylog2/rest/resources/system/logs/LoggersResource.java

* change loggers for indexer subsystem
fixes #17011
* changelog
* use `graylog2` package
(cherry picked from commit 42aaebf2d0ef4b9d9b113f31615acad8fc118e17)

backport 5.1: change loggers for indexer subsystem (#17012)

---

changelog/unreleased/pr-17012.toml
graylog2-server/src/main/java/org/graylog2/rest/resources/system/logs/LoggersResource.java

* change loggers for indexer subsystem
fixes #17011
* changelog
* use `graylog2` package
(cherry picked from commit 42aaebf2d0ef4b9d9b113f31615acad8fc118e17)

backport 5.0: change loggers for indexer subsystem (#17012)

---

graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/mapping/FieldTypeMappingsService.java
graylog2-server/src/main/java/org/graylog2/rest/bulk/model/BulkOperationResponse.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/field_types/FieldTypeMappingsResource.java
graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/mapping/FieldTypeMappingsServiceTest.java

Complex response for field type removal. 
Unit tests for removal.
/nocl
Provide the client with the outcome of the operation. Especially important if a call was made directly through the API, without UI, as UI itself already prevents many errors on data that are sent with the request.

Complex response for field type removal. Unit tests for removal.

---

changelog/unreleased/issue-17385.toml
graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/web/BasicAuthFilter.java
graylog2-server/src/test/java/org/graylog2/bootstrap/preflight/web/BasicAuthFilterTest.java

This is a backport of [#17405](https://github.com/Graylog2/graylog2-server/pull/17405)

Backport: fix preflight basic auth when password is not entered

---

graylog2-web-interface/src/components/bootstrap/BootstrapModalConfirm.md
graylog2-web-interface/src/components/bootstrap/Label.md
graylog2-web-interface/src/components/bootstrap/Tabs.md
graylog2-web-interface/src/components/bootstrap/Tooltip.md
graylog2-web-interface/src/components/common/DataTable/DataTable.md
graylog2-web-interface/src/components/common/NoEntitiesExist.tsx
graylog2-web-interface/src/components/common/SortableList/SortableList.md
graylog2-web-interface/src/components/common/Timestamp.md
graylog2-web-interface/src/theme/docs/Fonts.md
graylog2-web-interface/src/theme/docs/Utilities.md
graylog2-web-interface/styleguide.config.js

This PR is fixing the console errors for the Graylog style guide. This way it will be simpler to check if changes and additions to the documentation contain errors.
/nocl

Fix console errors in style guide.

---

full-backend-tests/src/test/java/org/graylog/plugins/views/SuggestionResourceIT.java

/nocl
Fixes https://github.com/Graylog2/graylog2-server/issues/17509
The occasional test failure is most likely caused by other tests interferences. Switching test scope to CLASS should isolate it. 
The tests are flaky on CI.

Change scope of SuggestionResourceIT to CLASS

---

.github/workflows/changelog.yml
.github/workflows/dispatch-pr-build.yml

Add github action PR build for 5.2

---

.github/workflows/changelog.yml
.github/workflows/dispatch-pr-build.yml

Add github action PR build for 5.0

---

graylog2-web-interface/src/components/indices/IndexSetFieldTypes/IndexSetFieldTypesList.tsx

Fix typo in index field type management page

---

graylog2-web-interface/src/components/common/EntityDataTable/TableRow.tsx

This PR is fixing a visual regression introduced when migrating buttons
to Mantine, by letting action buttons in entity tables float right.
/nocl

Let action buttons in entity table float right.

---

graylog2-web-interface/packages/graylog-web-plugin/package.json
graylog2-web-interface/src/components/bootstrap/Button.tsx
graylog2-web-interface/yarn.lock

This PR is making use of the generated contrast colors in sawmill `v2.0.11` to correct the font color of buttons in light theme.
/nocl

Fixing button font color in light theme.

---

graylog2-web-interface/src/components/indices/IndexSetFieldTypes/IndexSetFieldTypesList.test.tsx
graylog2-web-interface/src/components/indices/IndexSetFieldTypes/IndexSetFieldTypesList.tsx
graylog2-web-interface/src/components/indices/IndexSetFieldTypes/hooks/useIndexSetFieldType.test.ts
graylog2-web-interface/src/pages/IndexSetFieldTypesPage.test.tsx
graylog2-web-interface/src/views/logic/fieldactions/ChangeFieldType/ChangeFieldTypeModal.tsx
graylog2-web-interface/src/views/logic/fieldactions/ChangeFieldType/hooks/useIndexSetFieldTypesAll.ts
graylog2-web-interface/test/fixtures/indexSetFieldTypes.ts

this PR fixes typos in variables names for index field type management page
/nocl

Fix typo in variables names for index field type management page

---

graylog2-server/src/main/java/org/graylog/schema/EventFields.java

Add GIM schema field needed for https://github.com/Graylog2/graylog-plugin-enterprise/pull/6247.
/nocl

Add event_source_input GIM schema field

---

changelog/unreleased/issue-17619.toml
graylog2-web-interface/src/views/pages/NewDashboardPage.tsx

fix: https://github.com/Graylog2/graylog2-server/issues/17619

Update search for widgets on new dashboard page

---

UPGRADING.md
graylog2-server/src/main/java/org/graylog/schema/VendorFields.java

Add GIM schema field needed for https://github.com/Graylog2/graylog-plugin-enterprise/pull/6294.
/nocl

Add vendor_event_type GIM schema field

---

graylog2-web-interface/src/components/welcome/LastOpenList.tsx
graylog2-web-interface/src/components/welcome/Welcome.test.tsx

This PR contains a little improvement for wording on the welcome page.
/nocl

Improve wording on welcome page.

---

changelog/unreleased/issue-17619.toml
graylog2-web-interface/src/views/pages/NewDashboardPage.tsx

Note: This is a backport of https://github.com/Graylog2/graylog2-server/pull/17621 to 5.2.
fix: https://github.com/Graylog2/graylog2-server/issues/17619

Update search for widgets on new dashboard page (5.2) (#17621)

---

changelog/unreleased/issue-17619.toml
graylog2-web-interface/src/views/pages/NewDashboardPage.tsx

Note: This is a backport of https://github.com/Graylog2/graylog2-server/pull/17621 to 5.1.
fix: https://github.com/Graylog2/graylog2-server/issues/17619

Update search for widgets on new dashboard page (5.1) (#17621)

---

UPGRADING.md
graylog2-server/src/main/java/org/graylog/schema/VendorFields.java

Add missing GIM field, update UPGRADING.md in preparation for AWS Security Lake Illuminate parsing.
/nocl

Add vendor_event_type GIM field, update UPGRADING.md for Security Lake

---

graylog2-web-interface/src/views/components/aggregationwizard/ElementsConfigurationActions.tsx

Fix position of `Update preview` button in aggregation builder.

---

misc/archiver.conf

This PR is fixing a little typo in the archiver config template.
/nocl

Fix typo in archiver config template.

---

.github/workflows/fix-linter-hints.yml
.github/workflows/update-browserslist-db.yml
.github/workflows/updating-lockfile.yml

This PR avoids dispatching builds when no PR was created/is existing.  Otherwise, extracting ref/sha afterwards will fail.
/nocl

Do not dispatch build when PR exists.

---

changelog/unreleased/pr-17752.toml
graylog2-web-interface/src/components/perspectives/PerspectivesSwitcher.tsx
graylog2-web-interface/src/components/perspectives/bindings.ts

Updates Perspective Switcher style
Security PR: https://github.com/Graylog2/graylog-plugin-enterprise/pull/6340
Issue: https://github.com/Graylog2/graylog-plugin-enterprise/issues/6303
/nocl
It removes the logo from the dropdown and changes the title to a shorter version
[Screencast from 12-19-2023 11:21:15 AM.webm](https://github.com/Graylog2/graylog2-server/assets/105670363/c9b059e4-4a36-4b96-b794-616fb45b94a3)

feat(6303): Updates Perspective Switcher style

---

graylog2-server/src/main/java/org/graylog2/audit/AuditEventTypes.java
graylog2-server/src/main/java/org/graylog2/indexer/indexset/profile/IndexFieldTypeProfile.java
graylog2-server/src/main/java/org/graylog2/indexer/indexset/profile/IndexFieldTypeProfileData.java
graylog2-server/src/main/java/org/graylog2/indexer/indexset/profile/IndexFieldTypeProfileService.java
graylog2-server/src/main/java/org/graylog2/rest/resources/RestResourcesModule.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexFieldTypeProfileResource.java

Index field type profiles - basic CRUD on profiles.
/jpd Graylog2/graylog-plugin-enterprise#6342
/nocl
First version of CRUD on profiles so that FE can start working with this new type of MongoDB documents.

Index field type profiles - basic CRUD on profiles

---

graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java
graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/mapping/FieldTypeMappingsService.java
graylog2-server/src/main/java/org/graylog2/indexer/indexset/CustomFieldMappings.java
graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetConfig.java
graylog2-server/src/main/java/org/graylog2/indexer/indexset/profile/IndexFieldTypeProfile.java
graylog2-server/src/main/java/org/graylog2/indexer/indexset/profile/IndexFieldTypeProfileData.java
graylog2-server/src/main/java/org/graylog2/indexer/indexset/profile/IndexFieldTypeProfileService.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/field_types/FieldTypeMappingsResource.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/field_types/FieldTypeProfileChangeRequest.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/field_types/FieldTypeProfileUnsetRequest.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexFieldTypeProfileResource.java
graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/mapping/FieldTypeMappingsServiceTest.java
graylog2-server/src/test/java/org/graylog2/indexer/indexset/CustomFieldMappingsTest.java
graylog2-server/src/test/java/org/graylog2/indexer/retention/strategies/AbstractIndexRetentionStrategyTest.java

Set and remove profile on index set level. Checks added and moved to the service layer.
This PR is only about setting the profile on the index set config level - using this profile to build a template will be a subject of a separate PR.
/nocl

Set and remove profile on index set level.

---

changelog/unreleased/issue-17464.toml
graylog2-web-interface/src/components/common/MessageDetailsDefinitionList.jsx
graylog2-web-interface/src/components/rules/rule-builder/RuleBuilder.test.tsx
graylog2-web-interface/src/components/rules/rule-builder/helpers.ts

fixes https://github.com/Graylog2/graylog2-server/issues/17464

Fix 17464: Pipeline rule simulator - JSON inside message

---

graylog2-server/src/main/java/org/graylog2/indexer/indexset/profile/IndexFieldTypeProfileService.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexFieldTypeProfileResource.java

Basic sorting and filtering in profile pagination.
/nocl

Basic sorting and filtering in profile pagination

---

graylog2-server/src/main/java/org/graylog2/indexer/BasicIndexTemplateProvider.java
graylog2-server/src/main/java/org/graylog2/indexer/EventIndexTemplateProvider.java
graylog2-server/src/main/java/org/graylog2/indexer/IndexTemplateProvider.java
graylog2-server/src/main/java/org/graylog2/indexer/MessageIndexTemplateProvider.java

Common version check in template providers.
So far this check was repeated in 3 classes, probably leading to an error in `FailureIndexTemplateProvider` (no DATA_NODE in check, as it was done in other places).
/jpd Graylog2/graylog-plugin-enterprise#6357
/nocl
DRY, fix potential bug.
By re-running the tests.

Common version check in template providers

---

graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/web/resources/CAResource.java

/nocl
Missing annotation caused invalid behaviour of the api
Manually

Fix password used for CA creation in graylog rest api

---

graylog2-server/src/main/java/org/graylog2/indexer/IndexSet.java
graylog2-server/src/main/java/org/graylog2/indexer/retention/executors/RetentionExecutor.java
graylog2-server/src/main/java/org/graylog2/indexer/retention/executors/TimeBasedRetentionExecutor.java
graylog2-server/src/test/java/org/graylog2/indexer/RetentionTestIndexSet.java
graylog2-server/src/test/java/org/graylog2/indexer/retention/executors/AbstractRetentionExecutorTest.java
graylog2-server/src/test/java/org/graylog2/indexer/retention/executors/CountBasedRetentionExecutorTest.java
graylog2-server/src/test/java/org/graylog2/indexer/retention/executors/TimeBasedRetentionExecutorTest.java
graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingRotationAndRetentionTest.java

Extract index sorting into a common Comparator
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/6366
/nocl

Add indexComparator

---

UPGRADING.md

Updates change log entry to cover fields removed from F5 input in https://github.com/Graylog2/graylog-plugin-enterprise/pull/6376.
/nocl

UPGRADING.md changes for F5 Input field removal

---

graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetService.java
graylog2-server/src/main/java/org/graylog2/indexer/indexset/MongoIndexSetService.java
graylog2-server/src/main/java/org/graylog2/indexer/indexset/profile/IndexFieldTypeProfileService.java
graylog2-server/src/test/java/org/graylog2/indexer/indexset/profile/IndexFieldTypeProfileServiceTest.java

When profile is removed, it is removed from index sets as well.
/nocl

When profile is removed, it is removed from index sets as well

---

graylog2-server/src/test/java/org/graylog2/indexer/indexset/profile/IndexFieldTypeProfileServiceTest.java

More tests for IndexFieldTypeProfileService.
/nocl

More tests for IndexFieldTypeProfileService

---

changelog/unreleased/pr-17909.toml
graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/arrays/AbstractArrayFunction.java
graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/arrays/ArrayContains.java
graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/arrayContains.txt
graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/with-arrays.json

Backport https://github.com/Graylog2/graylog2-server/pull/17909 to 5.2.

Array Contains function: Fix unhandled exception when passed null array (5.2)

---

graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.tsx

Refactor IndexSetConfigurationForm as functional component
/nocl

Refactor IndexSetConfigurationForm as functional component

---

graylog2-server/src/main/java/org/graylog2/indexer/indexset/profile/IndexFieldTypeProfileIdAndName.java
graylog2-server/src/main/java/org/graylog2/indexer/indexset/profile/IndexFieldTypeProfileService.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexFieldTypeProfileResource.java
graylog2-server/src/test/java/org/graylog2/indexer/indexset/profile/IndexFieldTypeProfileServiceTest.java

`All` endpoint for profile resource, enforced by technical debt on FE side.
/nocl
Current FE state does not allow to use paginated endpoint for some part of their functionality.
Manually and with new automatic test.

All endpoint for profile resource, enforced by technical debt on FE side.

---

changelog/unreleased/pr-17965.toml
graylog2-web-interface/package.json
graylog2-web-interface/src/@types/graylog-web-plugin/index.d.ts
graylog2-web-interface/src/components/navigation/UserMenu.tsx
graylog2-web-interface/src/hooks/useLogout.test.tsx
graylog2-web-interface/src/hooks/useLogout.ts
graylog2-web-interface/src/views/test/testPlugins.ts
graylog2-web-interface/yarn.lock

This PR is providing a `hooks.logout` hook, which can be used by plugins to execute a callback when the user logs out. This could be used e.g. for cleaning session data which would become stale when no user is logged in/a different user logs in.

Adding `hooks.logout` hook which is called upon user logout.

---

graylog2-web-interface/src/components/common/EntityDataTable/MoreActions.tsx
graylog2-web-interface/src/components/datanode/DataNodeList/DataNodeActions.tsx
graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionActions.tsx
graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotificationActions.tsx
graylog2-web-interface/src/components/streams/StreamsOverview/StreamActions.tsx
graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardActions.tsx

This PR is creating a common `MoreActions` component to consolidate this common pattern in entity lists and make its appearance consistent.
/nocl

Creating common `MoreActions` button for consistency.

---

graylog2-web-interface/src/components/login/LoginForm.tsx
graylog2-web-interface/src/components/users/UserEdit/PasswordSection.tsx

This PR is adding `autocomplete` properties to user/password fields to help password managers.
/nocl

Adding `autocomplete` ids to user/password fields.

---

changelog/unreleased/pr-17984.toml
graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/ProxyRequestAdapterOS2.java

Backport/Propagate proxied request body to opensearch 

---

graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/responses/IndexSetFieldType.java

Filtering by field name turned on in `System/IndexSets/Types`
/nocl
FE may eventually want to filter by that field.
Manually.

Filtering by field name turned on

---

graylog2-web-interface/packages/jest-preset-graylog/package.json
graylog2-web-interface/src/components/authentication/AuthenticatorsEdit/HTTPHeaderAuthConfigSection.test.tsx
graylog2-web-interface/src/components/bootstrap/DropdownButton.test.tsx
graylog2-web-interface/src/components/common/URLWhiteListFormModal.test.tsx
graylog2-web-interface/src/components/configurations/UrlWhiteListForm.test.tsx
graylog2-web-interface/src/components/users/UserEdit/SettingsSection.test.tsx
graylog2-web-interface/src/hooks/useLogout.test.tsx
graylog2-web-interface/src/stores/__tests__/connect.test.tsx
graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.corevisualizations.test.tsx
graylog2-web-interface/src/views/components/common/ActionDropdown.test.tsx
graylog2-web-interface/src/views/components/dashboard/BigDisplayModeConfiguration.test.tsx
graylog2-web-interface/src/views/components/queries/QueryTitleEditModal.test.tsx
graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/AbsoluteDateInput.test.tsx
graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TabAbsoluteTimeRange.test.tsx
graylog2-web-interface/src/views/components/widgets/CopyToDashboardForm.test.tsx
graylog2-web-interface/src/views/components/widgets/FieldSortIcon.test.tsx
graylog2-web-interface/src/views/components/widgets/WidgetActionDropdown.test.tsx
graylog2-web-interface/test/wrappedEnzyme.tsx

This PR is improving test reliability in preparation of migrating to React 18.
/nocl
/prd Graylog2/graylog-plugin-enterprise#6446

Improve test reliability in preparation of React 18.

---

graylog2-server/src/test/java/org/graylog/testing/kafka/KafkaContainer.java

We only reference the minor version `3.4` and pulled the latest version. `3.4.1` breaks the tests, so I changed the value to `3.4.0` but did not investigate the root cause so far.
/nocl

Setting the bugfix version for Kafka on the IT Tests

---

graylog2-server/src/main/java/org/graylog2/datatiering/DataTieringChecker.java
graylog2-server/src/main/java/org/graylog2/datatiering/DataTieringModule.java
graylog2-server/src/main/java/org/graylog2/indexer/IndexSetValidator.java
graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config
graylog2-server/src/test/java/org/graylog2/indexer/IndexSetValidatorTest.java

add feature flag for enabling datatiering on cloud 
/prd  https://github.com/Graylog2/graylog-plugin-enterprise/pull/6455
/nocl

add feature flag to for enabling datatiering on cloud later

---

graylog2-web-interface/src/components/common/SortableList/SortableList.test.tsx
graylog2-web-interface/src/components/rules/RuleForm.test.tsx
graylog2-web-interface/src/components/users/CreateTokenForm.tsx
graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.metric.test.tsx
graylog2-web-interface/src/views/components/export/ExportModal.test.tsx
graylog2-web-interface/src/views/components/export/ExportModal.tsx

Improving test reliability in preparation for React 18.

---

changelog/unreleased/issue-17958.toml
graylog2-server/src/main/java/org/graylog/events/rest/EventDefinitionsResource.java

Backport 5.2: Correctly set event definition state through rest api

---

.mvn/README.md
.mvn/wrapper/maven-wrapper.properties

Changelog: https://maven.apache.org/docs/3.9.6/release-notes.html
/nocl

Update Maven to 3.9.6

---

changelog/unreleased/pr-18091.toml
graylog2-web-interface/src/stores/indexers/IndexerOverviewStore.ts
graylog2-web-interface/src/stores/indices/IndicesStore.ts

backport #18091
fix https://github.com/Graylog2/graylog2-server/issues/18063

Backport -Prevent session extension on indexset details page (#18091)

---

data-node/src/main/java/org/graylog/datanode/bindings/ServerBindings.java
data-node/src/main/java/org/graylog/datanode/management/OpensearchProcessImpl.java
data-node/src/main/java/org/graylog/datanode/management/OpensearchProcessService.java
data-node/src/main/java/org/graylog/datanode/process/ProcessStateMachine.java
data-node/src/main/java/org/graylog/datanode/process/ProcessStateMachineProvider.java

Refactoring of the state machine. Creating a Provider so it can be injected into several places.
/nocl

DataNode: Process State Machine Refactoring

---

changelog/unreleased/issue-17523.toml
data-node/src/main/java/org/graylog/datanode/Configuration.java
graylog2-server/src/test/java/org/graylog/testing/completebackend/ContainerizedGraylogBackend.java

Datanode: ensure password_secret meets length requirement

---

graylog2-server/src/main/java/org/graylog2/indexer/indices/jobs/SetIndexReadOnlyAndCalculateRangeJob.java

Dont show SetIndexReadOnlyAndCalculateRangeJob as unknown

---

changelog/unreleased/pr-18113.toml
graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/PreflightJerseyService.java

Added link to preflight output so that the basic auth login dialog does not pop up.
**backport of #18113**

DataNode: Added link to preflight output - backport to 5.2 of #18113

---

graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/actions/MigrationActionsImpl.java

making all transition checks return true until we implement the real checks so that FE development is not held back
/nocl

DataNode: Migration State Machine checks to true

---

graylog2-web-interface/src/components/streams/hooks/useStream.ts
graylog2-web-interface/src/views/logic/fieldactions/ChangeFieldType/ChangeFieldTypeModal.tsx

Adds error handler for getting stream name and adds to change field type modal note that enterprise plugin is required for Processing and Indexing Failures overview 
fix: https://github.com/Graylog2/graylog2-server/issues/17743
/nocl

Handle getting Processing and Indexing Failures stream name for non enterprise version 

---

graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/actions/MigrationActionsImpl.java

DataNode: Migration Wizard checks for the state machine for ca and renewal policy

---

graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypesListService.java
graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetConfig.java
graylog2-server/src/main/java/org/graylog2/indexer/indexset/profile/IndexFieldTypeProfileService.java
graylog2-server/src/main/java/org/graylog2/indexer/indexset/profile/IndexFieldTypeProfileUsagesService.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/requests/IndexSetUpdateRequest.java
graylog2-server/src/main/java/org/graylog2/validation/ValidObjectId.java
graylog2-server/src/main/java/org/graylog2/validation/ValidObjectIdBytesValidator.java
graylog2-server/src/main/resources/ValidationMessages.properties
graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypesListServiceTest.java
graylog2-server/src/test/java/org/graylog2/indexer/indexset/profile/IndexFieldTypeProfileServiceTest.java
graylog2-server/src/test/java/org/graylog2/indexer/indexset/profile/IndexFieldTypeProfileUsagesServiceTest.java

Better verification that profile ID contains proper ObjectID.
/nocl

Better verification that profile ID contains proper ObjectID

---

changelog/unreleased/issue-17743.toml
graylog2-web-interface/src/components/streams/hooks/useStream.ts
graylog2-web-interface/src/views/logic/fieldactions/ChangeFieldType/ChangeFieldTypeModal.tsx

Backports https://github.com/Graylog2/graylog2-server/pull/18143 to 5.2

Handle getting Processing and Indexing Failures stream name for non enterprise version 5.2

---

graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/machine/MigrationStateMachineBuilder.java

Remove duplicated MigrationState.ASK_TO_SHUTDOWN_OLD_CLUSTER state

---

graylog2-server/src/main/java/org/graylog2/plugin/InputFailureRecorder.java

Change InputFailureRecorder to log failure warning each time an input triggers a failing condition. 
/nocl Seems not noteworthy enough to mention in the top-level change log.
Many inputs include retry logic, which pauses the input until the certain error conditions resolve (such as the remote host being unavailable). The retries occur indefinitely in many cases. Indeed, the input continues to mark the input as Failing, which shows up in the user interface. But, it would also be helpful to continue to log that reties are occurring in the server log, so there is a very clear indication in the log that an input continuing to fail (the absence of such messages seem to indicate that the input is working successfully).
Ran an input with an unreachable server host name and verified that the …

Log failure warning message even if input is already in Failing status

---

data-node/src/main/java/org/graylog/datanode/management/OpensearchProcessService.java
graylog2-server/src/main/java/org/graylog2/rest/resources/datanodes/DatanodeRestApiProxy.java

fall back to any data node if there is no leader node.
also fixes starting the rest api in UNCONFIGURED state
/nocl
fixes #18175

Make rest api available for UNCONFIGURED data node

---

graylog2-web-interface/src/components/users/UserCreate/UserCreate.test.tsx

This test seems to fail in some cases with the warning:
`Warning: The current testing environment is not configured to support act(...)`
Using `userEvent` improved the behaviour for me.
/nocl

Implement `userEvent` for `UserCreate` test.

---

graylog2-server/src/main/java/org/graylog/events/migrations/V20230629140000_RenameFieldTypeOfEventDefinitionSeries.java
graylog2-server/src/test/resources/org/graylog/events/migrations/V20230629140000_RenameFieldTypeOfEventDefinitionSeries/mixed_event_definitions-after.json
graylog2-server/src/test/resources/org/graylog/events/migrations/V20230629140000_RenameFieldTypeOfEventDefinitionSeries/mixed_event_definitions.json
graylog2-web-interface/src/logic/alerts/AggregationExpressionValidation.js

/nocl update to prior issue
#17819 was incomplete: it only added checks for a subset of the affected classes.
This PR adds checks for the remainder.

Add missing checks for series definitions with fields

---

graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/rest/MigrationStateResource.java
graylog2-server/src/test/java/org/graylog/plugins/views/storage/migration/state/rest/MigrationStateResourceTest.java

fixes an error when return CurrentStateInformation when triggering migration steps
/nocl

fix error when returning CurrentStateInformation

---

.github/workflows/reviewbot.yml

Convert yet another workflow to maven wrappers

---

graylog2-web-interface/src/components/common/Popover.tsx

This PR is increasing the z-Index of popovers so they are not covered by modals.
/nocl

Increasing z-Index for popovers to avoid them being hidden by modals.

---

graylog2-web-interface/src/logic/rest/FetchProvider.ts
graylog2-web-interface/src/views/components/DashboardSearchBar.tsx
graylog2-web-interface/src/views/components/SearchBar.tsx

fix: #18231 
This PR adds a loading state for the search button during the execution stage
/nocl

Prevent starting the search before the current search is finished

---

graylog2-web-interface/src/components/events/events/EventsSearchBar.jsx

This PR is adding a title to the events refresh button, which has an icon only, so we can find it properly in tests.
/nocl

Adding title to button with icon only.

---

graylog2-web-interface/src/views/components/DashboardSearchBar.tsx

Follow-up for https://github.com/Graylog2/graylog2-server/pull/18208
Before 
After
/nocl

Fix dashboard search button icon.

---

graylog2-web-interface/src/components/datanode/Constants.ts
graylog2-web-interface/src/components/datanode/migrations/MigrationWelcomeStep.tsx

Update datanode migration welcome documentation

---

data-node/pom.xml
data-node/src/main/java/org/graylog/datanode/management/opensearch/cli/OpensearchKeystoreCli.java
graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/actions/MigrationActionsImpl.java

/nocl
- Safer context handling in migration actions
- Respond yes when overriding opensearch keystore during datanode certificate provisioning (changes configuration in place, with possible existing keystore, the command line wrapper has to be able to respond to "really override" question)

Small datanode fixes for migration

---

graylog-plugin-parent/graylog-plugin-web-parent/pom.xml
graylog2-server/pom.xml

Let's see if this works better in our CI runs.
/nocl

Change Node.js download URL

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/ESEventList.java
graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/OSEventList.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/events/CommonEventSummary.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/events/EventList.java
graylog2-server/src/main/java/org/graylog2/database/filtering/AttributeFilter.java

This PR is extending the `events` search type with additional parameters:
- `attributes`: a list of attributes of events to filter down for, e.g.: 
- `"attributes": [{ "field": "event_definition_id", "value": ["foo", "bar"] }]`
- `"attributes": [{ "field": "priority", "value": "2" }]`
- `sort`: how the events list should be sorted, e.g.: `"sort": { "field": "priority", "direction": "DESC" }`
- `page`/`per_page`: page number and page size for pagination
/nocl

Extending `events` search type with filtering, sorting & pagination.

---

graylog2-web-interface/src/routing/Routes.ts

Add route for https://github.com/Graylog2/graylog-plugin-enterprise/pull/6682
/nocl

Add route for new security 'Activity' page

---

graylog2-web-interface/src/views/components/sidebar/create/AddWidgetButton.tsx
graylog2-web-interface/src/views/logic/fieldactions/AddMessageTableActionHandler.ts

_Please note_, to test these changes you need to enable the feature flag `SECURITY_SEARCH_WIDGETS`.
This PR adds a new section for investigation widgets in the widget creation section of the search sidebar.
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/6659
/nocl

Add new section for investigation widgets in search sidebar.

---

changelog/unreleased/pr-18465.toml
pom.xml

The 2.11 client is not compatible to 2.12 so we bump it here for general support but especially for the DataNode.

Bumping the OS client to 2.12

---

graylog2-web-interface/src/components/datanode/migrations/MigrationWelcomeStep.tsx
graylog2-web-interface/src/components/datanode/migrations/common/ImPlaceMigrationInfo.tsx
graylog2-web-interface/src/components/datanode/migrations/common/InPlaceMigrationInfo.tsx
graylog2-web-interface/src/components/datanode/migrations/in-place/Welcome.tsx

Add info about `opensearch_data_location` when doing In-Place migration
fix #18466
/nocl

Add in-place migration info to migration

---

changelog/unreleased/pr-18492.toml
graylog2-web-interface/src/components/datanode/hooks/useJournalDowntimeSize.ts
graylog2-web-interface/src/components/datanode/migrations/in-place/JournalDowntimeWarning.tsx

show Journal Size in In-Place Migration steps

---

jenkins.groovy

Remove unused Jenkins pipeline scripts

---

graylog2-web-interface/src/components/bootstrap/DropdownButton.tsx
graylog2-web-interface/src/views/components/aggregationwizard/AggregationElementSelect.tsx
graylog2-web-interface/src/views/components/searchbar/SearchButton.tsx
graylog2-web-interface/src/views/components/searchbar/time-range-filter/TimeRangeFilterButtons.tsx
graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TimeRangePickerButton.tsx
graylog2-web-interface/src/views/components/widgets/EditMessageList.tsx

This PR is a follow-up for the recent button and icon changes. Please have a look at the commits for more information.
/nocl

Fixing button styling on search page.

---

full-backend-tests/src/test/java/org/graylog/events/processor/aggregation/PivotAggregationSearchIT.java

/nocl
Assume there are always some http notifications, don't rely on any order or count, wait for one notification matching specific criteria.

Fix flaky integration test

---

graylog2-web-interface/src/components/content-packs/ContentPackEntitiesList.jsx
graylog2-web-interface/src/integrations/aws/cloudwatch/SidebarPermissions.jsx

Fixes https://github.com/Graylog2/graylog2-server/issues/18443
/nocl

Fixing icon on content pack parameter page.

---

graylog2-server/src/main/java/org/graylog2/rest/RestTools.java
graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java
graylog2-server/src/main/java/org/graylog2/rest/resources/search/KeywordSearchResource.java
graylog2-server/src/main/java/org/graylog2/rest/resources/search/RelativeSearchResource.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/debug/bundle/SupportBundleClusterResource.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/debug/bundle/SupportBundleResource.java

This PR is implementing a helper method `RestTools.respondWithFile` which aids in generating consistent responses returning file attachments to the caller. It makes use of it in places where headers were constructed manually before.
/nocl

Implementing helper method for generating file download responses.

---

.github/workflows/fix-linter-hints.yml

This PR is replacing the usage of `mvn` with the maven wrapper (`./mvnw`).
/nocl

Use maven wrapper for fixing linter hints.

---

graylog2-web-interface/yarn.lock

This PR is deduplicating our yarn lockfile to solve an issue related to ESLint, as described [here](https://stackoverflow.com/questions/77464177/how-to-solve-error-while-loading-rule-react-display-name-generatorstate/77538374).
/nocl

Deduplicating yarn lockfile.

---

data-node/pom.xml
pom.xml

Manage commons-exec dependency in parent pom.xml

---

graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/IndexToolsAdapterOS2.java

This PR is migrating the `IndexToolsAdapter` to the new Opensearch client.
/nocl

Migrating `IndexToolsAdapter` to new Opensearch client.

---

graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/searchtypes/eventlist/ESEventListTest.java
graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/views/searchtypes/eventlist/OSEventListTest.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/events/CommonEventSummary.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/events/EventSummary.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/searchtypes/eventlist/EventSummaryTest.java

This PR is changing the `events` search type to include priority and event keys for each event in results.
/prd Graylog2/graylog-plugin-enterprise#6758
/nocl

Include priority and event keys in events.

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/ESEventList.java
graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/searchtypes/eventlist/ESEventListTest.java
graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/OSEventList.java
graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/views/searchtypes/eventlist/OSEventListTest.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/events/EventList.java

/prd Graylog2/graylog-plugin-enterprise#6749
/nocl

Include total results in `events` search type.

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/ESEventList.java
graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/OSEventList.java

This PR is fixing a classic off-by-one error in the pagination of the `events` search type.
/nocl

Fix off-by-one error in `events` search type.

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/ESEventList.java
graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/searchtypes/eventlist/ESEventListTest.java
graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/OSEventList.java
graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/views/searchtypes/eventlist/OSEventListTest.java
graylog2-server/src/main/java/org/graylog/events/event/EventDto.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/events/CommonEventSummary.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/events/EventSummary.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/searchtypes/eventlist/EventSummaryTest.java

This PR is making sure that replay info is also included in events returned by `events` search type.
/prd Graylog2/graylog-plugin-enterprise#6767
/nocl

Include replay info for events in `events` search type.

---

graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/DataStreamAdapterOS2.java

If two or more datanodes start in the same moment, it can happen that both of them will try to create a metrics datastream. There is no locking or synchronization. Let's use the opensearch itself to handle concurrency, always try to create a datastream and catch/ignore resource_already_exists_exception
/nocl

Fix datastream concurrent creation

---

graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/web/resources/CAResource.java
graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java

Adding separate permissions for CA and clientcert generation.
/nocl

DataNode: Adding explicit permissions to CAResource

---

graylog2-web-interface/src/components/bootstrap/NavDropdown.tsx
graylog2-web-interface/src/components/bootstrap/Navbar.jsx
graylog2-web-interface/src/components/common/NavItemStateIndicator.tsx
graylog2-web-interface/src/components/navigation/InactiveNavItem.tsx
graylog2-web-interface/src/components/navigation/Navigation.styles.tsx
graylog2-web-interface/src/components/navigation/Navigation.tsx
graylog2-web-interface/src/components/navigation/ScratchpadToggle.tsx

Before:
After:
Fixes: https://github.com/Graylog2/graylog2-server/issues/18287
/nocl

Fixing styling of dropdowns in mobile navigation.

---

data-node/src/main/java/org/graylog/datanode/Configuration.java
data-node/src/main/java/org/graylog/datanode/configuration/OpensearchConfigurationProvider.java

/nocl
Belongs to the https://github.com/Graylog2/graylog2-server/pull/18357/ change.

make node roles configurable

---

graylog2-web-interface/src/components/event-definitions/event-definitions-types.ts

Fix event-definitions types imports.
/nocl

Fix event-deifnitions type import

---

graylog2-web-interface/src/components/indices/IndexSetFieldTypes/IndexSetCustomFieldTypeRemoveModal.tsx
graylog2-web-interface/src/views/logic/fieldactions/ChangeFieldType/ChangeFieldTypeModal.tsx

This PR removes no longer needed BetaBadge
/nocl

Remove BetaBadge from ChangeFieldTypeModal and Removal Modal

---

changelog/unreleased/pr-18750.toml
graylog2-web-interface/src/components/loggers/LogLevelDropdown.jsx

Fixes https://github.com/Graylog2/graylog2-server/issues/18676
/nocl

Fix log level not changeable 

---

graylog2-web-interface/src/views/components/views/ExecutionInfo.tsx

Fix search results `0` when first item in resultset does not contain a `total`

---

graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/events/EventsWidgetConfigDTO.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/events/Filter.java

Remove Events and Investigation widgets from report generation.
/nocl

Adding `EventWidgetConfigDTO` for persisting events widget config

---

data-node/src/main/java/org/graylog/datanode/configuration/OpensearchConfigurationProvider.java

`all_access` seems not enough, so we're explicitly adding admin access to the REST API.
/nocl
fixes https://github.com/Graylog2/graylog2-server/issues/18782
manually tested by executing a change like the one in the linked issue

DataNode: Adding admin access via the REST API

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/ESEventList.java
graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/OSEventList.java

**Note:** This requires #18826 to be merged before.
This PR is supporting subclasses of the `events` search type to override sort configuration.
/nocl

Support overriding sorts in `events` search type.

---

changelog/unreleased/issue-18718.toml
graylog2-web-interface/src/components/rules/RuleForm.tsx
graylog2-web-interface/src/hooks/usePreventAbandonPageConfirmation.ts

https://github.com/Graylog2/graylog2-server/issues/18718

Pipeline rule editor: Prevent Abandon Page Confirmation

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/validation/PluggableSearchValidation.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/validation/SearchValidation.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/validation/SearchValidator.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/validation/TimeRangeValidator.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/permissions/SearchUser.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/exceptionmappers/IllegalTimeRangeExceptionMapper.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/SearchExecutionGuardTest.java

This PR is a refactoring, extending the `SearchValidator` interface to take a `SearchUser` instance in validation checks. This allows us to perform permission checks in search validations.
/nocl

Pass `SearchUser` to search validators.

---

graylog2-web-interface/src/components/common/SourceCodeEditor.tsx
graylog2-web-interface/src/components/rules/RuleForm.tsx

Before these changes, we had issues with the active line background color. We also adjust the cursor color for other usage.
fix #18847 
fix #18717
/nocl

Adjust code editor active line background and cursor color.

---

graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config
graylog2-web-interface/src/components/datanode/DataNodePageNavigation.tsx
graylog2-web-interface/src/routing/AppRouter.tsx

add feature flag to disable data node migration in UI by default
/nocl
hide migration in RC1

add feature flag for data node migration

---

graylog2-web-interface/src/components/common/DropdownSubmenu.tsx

Fixing color issue with node actions dropdown.

---

UPGRADING.md
changelog/unreleased/pr-17483.toml

Adds missing changelog and upgrade notes for #17483

Add changelog + update notes for changes to trusted header auth

---

UPGRADING.md
changelog/unreleased/pr-17483.toml

Backport: Add changelog + update notes for changes to trusted header auth (#18892)

---

graylog2-server/src/main/java/org/graylog2/database/jackson/legacy/LegacyInsertManyResult.java
graylog2-server/src/main/java/org/graylog2/database/jackson/legacy/LegacyInsertOneResult.java
graylog2-server/src/main/java/org/graylog2/database/jackson/legacy/LegacyUpdateOneResult.java

Backport: Set readPreference=primary for reading back write results

---

graylog2-server/src/main/java/org/graylog/aws/inputs/cloudtrail/CloudTrailInput.java
graylog2-server/src/main/java/org/graylog/integrations/aws/inputs/AWSInput.java
graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackService.java
graylog2-server/src/main/java/org/graylog2/inputs/misc/jsonpath/JsonPathInput.java
graylog2-server/src/main/java/org/graylog2/inputs/random/FakeHttpMessageInput.java
graylog2-server/src/main/java/org/graylog2/plugin/inputs/CloudCompatible.java
graylog2-server/src/main/java/org/graylog2/plugin/inputs/MessageInput.java

/nocl bugfix for unreleased feature
/prd Graylog2/graylog-plugin-enterprise#7059
Backport fix for cloud compatibility check of content packs.
(cherry picked from commit fd427cd33f30d36bfd49a72edbdf3f747f682a6b)

Cloud compatibility annotation (#19054)

---

changelog/unreleased/pr-19039.toml
graylog2-web-interface/src/pages/DataNodesPage.tsx
graylog2-web-interface/src/preflight/App.tsx
graylog2-web-interface/src/preflight/components/Setup/Setup.tsx

backport for #19038 
---------
Co-authored-by: Tomas Dvorak <tomas.dvorak@graylog.com>
(cherry picked from commit 6fd21c3961b6bb1eafe13a8fd16517a4f6f2e50f)

Add data node beta banner (#19039)

---

graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/pivot/series/OSAverageHandler.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/series/Average.java

Supports rounding averages in OS query results. 
/nocl
Graylog2/graylog-plugin-enterprise#7014
local dev env. Change should not affect anything other than investigation metrics search

Support whole numbers on OpenSearch Average

---

graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/pivot/series/OSAverageHandler.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/series/Average.java

backport #19084 to 6.0 to fix blocker Graylog2/graylog-plugin-enterprise#7014
/nocl

Backport 6.0: Round investigation metrics

---

graylog2-web-interface/src/components/users/UserCreate/UserCreate.test.tsx
graylog2-web-interface/src/components/users/UserCreate/UserCreate.tsx

With this PR we:
- are making sure to disable the submit button, while the form is validating
- slightly changing the way we validate the username
/nocl

Disable submit button in user create form while form is validating.

---

graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/RemoteReindexingMigrationAdapterOS2.java
graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/TaskError.java
graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/GetTaskResponseTest.java

/nocl
- Safer deserialization of task errors in remote reindex migration
- Catching 404 exception in getting task status
Added unit test, existing set of integration tests

Better error handling for remote reindex migrations

---

graylog2-server/src/main/java/org/graylog2/configuration/MongoDbConfiguration.java

Fix mongodb configuration documentation wording

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/remote/SearchJobsStatusResource.java

SearchJobs endpoint - Swagger improvements
/nocl
Fixing minor problems Jan has found out why reviewing long running searches PR.
Manually.

SearchJobs endpoint - Swagger improvements

---

graylog2-server/src/main/java/org/graylog2/shared/bindings/ObjectMapperModule.java
graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/YamlMapperProvider.java

Add a binding for YamlMapperProvider.
/nocl
Original branch was merged to quickly to apply this fix. :)

Add a binding for YamlMapperProvider

---

changelog/unreleased/issue-19003.toml
data-node/config/log4j2.xml

Fix log4j memory appender config in datanode 

---

graylog2-web-interface/src/components/indices/data-tiering/DataTieringConfiguration.tsx

Backport of https://github.com/Graylog2/graylog2-server/pull/19206
Issue: https://github.com/Graylog2/graylog2-server/issues/19205 
/nocl

Backport: Move archive_before_deletion to hot_warm fields 

---

graylog-project-parent/pom.xml
pom.xml

Manage commons-csv dependency globally

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/export/AggregationWidgetExportResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/export/response/AggregationWidgetExportResponseWriter.java
graylog2-server/src/main/java/org/graylog2/rest/MoreMediaTypes.java

Adding XLSX export for aggregation widget - BE.
/nocl
Manually.

Adding XLSX export for aggregation widget - BE

---

changelog/unreleased/pr-19260.toml
graylog2-web-interface/src/components/inputs/InputListItem.jsx

Backport - Fix manage extractor link for local input  (#19260)

---

changelog/unreleased/pr-19225.toml

This PR is merely correcting the PR# in the changelog snippet of #19225.
/nocl

Correct PR# in changelog snippet for #19225.

---

graylog2-server/src/main/java/org/graylog2/rest/MoreMediaTypes.java

Adding MediaTypes for PDF and ZIP - both are used in reporting.
/nocl

Adding mediatypes for pdf and zip - as used in the reporting

---

changelog/unreleased/pr-19030.toml
graylog2-web-interface/src/components/indices/IndexSetDeletionForm.jsx
graylog2-web-interface/src/components/indices/IndexSetsComponent.tsx

Backport - Close IndexSet the delete modal and reload list after deleting. 

---

changelog/unreleased/issue-19270.toml
graylog2-web-interface/src/components/datanode/hooks/useJournalDowntimeSize.ts
graylog2-web-interface/src/components/datanode/migrations/in-place/JournalDowntimeWarning.tsx

fixes https://github.com/Graylog2/graylog2-server/issues/19270

Maximum downtime estimate during migration

---

graylog2-web-interface/src/pages/ShowMessagePage.tsx
graylog2-web-interface/src/views/components/messagelist/Types.ts
graylog2-web-interface/src/views/hooks/useMessage.ts

With this PR we are creating a separate file for the `useMessage` hook and implementing `useQuery` for it.
This way we can reuse the hook in multiple files.
/nocl

Create separate file for `useMessage` hook.

---

changelog/unreleased/issue-19098.toml
graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java
graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/RemoveMultipleFields.java
graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/RemoveSingleField.java
graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/removeFieldsByName.txt
graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/removeFieldsByRegex.txt
graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/removeSingleField.txt

6.0 backport of #19268
* new pipeline functions remove_single_field and remove_multiple_fields
* CL
* improve rulebuilder descriptions
* compile regex and other feedback changes
* pre-compile pattern
* UI string improvements
(cherry picked from commit 4a1cbb4dcb8563a6686e0709040dea75ed831359)

Backport 6.0: New pipeline functions `remove_single_field` and `remove_multiple_fields` 

---

changelog/unreleased/issue-19195.toml
graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java

6.0 backport for #19325
* add sidecar filebeat collector for windows
* add changelog
(cherry picked from commit c08d86a5945fd9a49602a15a5d9a8520d1f2b9f7)

Backport 6.0: add sidecar filebeat collector for windows again (#19325)

---

graylog2-server/src/main/java/org/graylog/plugins/formatting/units/fields/HardcodedFieldUnitObtainingMethod.java

This PR is fixing the unit (`B`) introduced in #19138 for byte fields, it should actually be `b`.
/nocl As changed feature was not shipped yet.

Use correct unit for byte fields.

---

graylog2-web-interface/src/components/common/Carousel/Carousel.tsx
graylog2-web-interface/src/components/common/Carousel/CarouselProvider.tsx
graylog2-web-interface/src/components/common/Carousel/CarouselSlide.tsx
graylog2-web-interface/src/components/common/Carousel/hooks/useCarouselActions.ts
graylog2-web-interface/src/components/common/Carousel/hooks/useSlidesInView.ts
graylog2-web-interface/src/components/common/Carousel/index.ts

This PR contains improvements for the `Carousel` component. We are:
- fixing a bug with the disable state of carousel navigation buttons
- adding a hook to receive all slides which have been in view
- creating a constant for the carousel container class
- improving the component comment
- adding the `options` prop for the `CarouselProvider`, to be able to configure the carousel
/nocl

Further improvements for `Carousel` component.

---

graylog2-web-interface/packages/graylog-web-plugin/package.json
graylog2-web-interface/yarn.lock

This PR updates sawmill to version `2.0.17`
/nocl

Update `@graylog/sawmill` to `2.0.17`.

---

full-backend-tests/src/test/java/org/graylog/datanode/DatanodeProvisioningIT.java

/nocl
tested with 
```
mvn package -DskipTests -Dskip.datanode=true
```
in the graylog2-server repo
Fails before the change, succeeds now.

Remove all dependencies to datanode package from DatanodeProvisioningIT

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/MayHaveUnit.java

/nocl
Fixed bug with storage in Mongo
Turns out missing JsonProperty annotation was very important.

Fixed bug with storage in Mongo

---

graylog2-web-interface/src/components/common/Section.tsx

Improve responsiveness of section component.

---

graylog2-web-interface/src/components/common/EntityDataTable/index.ts
graylog2-web-interface/src/components/datanode/DataNodeList/DataNodeActions.tsx
graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionActions.tsx
graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotificationActions.tsx
graylog2-web-interface/src/components/indices/IndexSetFieldTypeProfiles/ProfileActions.tsx
graylog2-web-interface/src/components/sidecars/configurations/CollectorRow.jsx
graylog2-web-interface/src/components/sidecars/configurations/ConfigurationRow.jsx
graylog2-web-interface/src/components/streams/StreamsOverview/StreamActions.tsx
graylog2-web-interface/src/components/users/TokenList.tsx
graylog2-web-interface/src/components/users/UsersOverview/UserOverviewItem/ActionsCell.tsx
graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardActions.tsx

The `MoreActions` component is being used for the "more actions" dropdown in tables. It ensures unified the styling and wording. With this PR we implement it for further tables.
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/7383
/nocl

Implement `MoreActions` component for further tables.

---

changelog/unreleased/pr-19439.toml
graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/arrays/StringArrayAdd.java
graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/stringArrayAdd.txt

Backport https://github.com/Graylog2/graylog2-server/pull/19439 to `6.0`.

Backport 6.0: string_array_add pipeline function: Add handling for null elements argument

---

changelog/unreleased/pr-19439.toml
graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/arrays/StringArrayAdd.java
graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/stringArrayAdd.txt

Backport https://github.com/Graylog2/graylog2-server/pull/19439 to `5.2`.

Backport 5.2: string_array_add pipeline function: Add handling for null elements argument

---

changelog/unreleased/issue-19486.toml
graylog2-web-interface/src/views/logic/widgets/events/EventsWidget.ts

**Please note**, this PR needs a backport for `6.0`.
Fixes the problem described in https://github.com/Graylog2/graylog2-server/issues/19486
Fixes https://github.com/Graylog2/graylog2-server/issues/19486

Fix widget query controls for events widget.

---

changelog/unreleased/issue-19486.toml
graylog2-web-interface/src/views/logic/widgets/events/EventsWidget.ts

**Please note**, this is a backport of https://github.com/Graylog2/graylog2-server/pull/19537 for `6.0`.
Fixes the problem described in https://github.com/Graylog2/graylog2-server/issues/19486
Fixes https://github.com/Graylog2/graylog2-server/issues/19486

Fix widget query controls for events widget. `6.0`

---

graylog2-web-interface/src/components/cluster/TrafficGraph.tsx
graylog2-web-interface/src/views/components/visualizations/GenericPlot.lazy.css
graylog2-web-interface/src/views/components/visualizations/GenericPlot.tsx
graylog2-web-interface/src/views/components/visualizations/XYPlot.tsx
graylog2-web-interface/src/views/components/visualizations/__tests__/GenericPlot.test.tsx
graylog2-web-interface/src/views/components/visualizations/bar/BarVisualization.tsx

This refactoring will be helpful for future improvements, like displaying a custom component when hovering over plot markers.
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/7444
/nocl

Migrate `GenericPlot` to functional component.

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/events/EventList.java

Make Event List exportable.
/nocl
Needed by FE to support exporting in Event List.

Make Event List exportable

---

changelog/unreleased/pr-19487.toml
graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministration.tsx
graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministrationActions.tsx

BACKPORT 5.2 - Fix sidecar undefined error (#19487)

---

graylog2-web-interface/src/components/search/MessageDetail.jsx
graylog2-web-interface/src/components/search/MessageDetail.tsx
graylog2-web-interface/src/views/components/common/MessagePermalinkButton.tsx
graylog2-web-interface/src/views/components/messagelist/MessageActions.tsx
graylog2-web-interface/src/views/components/messagelist/Types.ts

This PR creates a component for the message permalink button.
/nocl

Create component for message permalink button.

---

graylog2-web-interface/src/components/common/Spoiler.md
graylog2-web-interface/src/components/common/Spoiler.tsx
graylog2-web-interface/src/components/common/index.tsx

This PR is adding a simple spoiler component based on https://mantine.dev/core/spoiler/.
/nocl

Add spoiler component.

---

graylog2-web-interface/src/components/common/PaginatedEntityTable/PaginatedEntityTable.tsx
graylog2-web-interface/src/components/indices/IndexSetFieldTypeProfiles/ProfilesList.tsx
graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardActions.test.tsx
graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardActions.tsx
graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardsOverview.test.tsx
graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardsOverview.tsx

In #19415, we migrated usages of the entity table to the streamlined paginated entity table component. This PR is fixing some minor issues discovered through E2E-Tests:
- Fixing refetching of dashboards after dashboard deletion
- Allowing to pass custom search form placeholder

Fixing fallout from migration to paginated entity table component.

---

graylog2-web-interface/src/hooks/useDebouncedValue.ts

This PR is exposing the `useDebouncedValue` hook from core, which utilizes the hook from mantine to simplify debouncing updates of a state value.

Expose `useDebouncedValue` hook.

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/export/ElasticsearchExportBackend.java
graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/export/OpenSearchExportBackend.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/export/CommandFactory.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/export/ExportMessagesCommand.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/events/EventList.java
graylog2-server/src/main/java/org/graylog2/database/filtering/HasAttributeFilter.java

Export support attribute filters.
/nocl
Events and investigation list have this special type of filter.
We want to take it into consideration when exporting those search types.
Manually.

Export support attribute filters

---

graylog2-web-interface/src/components/common/Drawer.md
graylog2-web-interface/src/components/common/Drawer.tsx

This PR is introducing a `Drawer` component, which can be used as an overlay component coming in from the side, offering a good amount of space (in contrast to e.g. a `Popover`) for forms/screens requiring more space than a regular modal.

Introduce `Drawer` component.

---

changelog/unreleased/issue-19562.toml
graylog2-web-interface/src/components/sidecars/failure-tracking/SidecarFailureTrackingRows.tsx

fixes https://github.com/Graylog2/graylog2-server/issues/19562

fix sidecar failure tracking page error

---

graylog2-web-interface/package.json
graylog2-web-interface/yarn.lock

Update sawmill version to 2.0.18
/nocl

Update sawmill version to 2.0.18

---

graylog2-server/src/main/java/org/graylog2/database/filtering/DbQueryCreator.java
graylog2-server/src/main/java/org/graylog2/search/SearchQuery.java
graylog2-server/src/main/java/org/graylog2/search/SearchQueryParser.java

These are just some minor cleanups for the classes related to entity
search query parsing.

Minor cleanups for search query parsing classes.

---

changelog/unreleased/pr-19750.toml
graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IpInfoIpAsnResolver.java
graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IpInfoLocationResolver.java

Backport of #19750 
See original issue and PR for details

Add missing exception handling for IpInfo*Resolver (#19750)

---

graylog2-web-interface/package.json
graylog2-web-interface/yarn.lock

Update sawmill to version 2.0.19
/nocl

Update sawmill to version 2.0.19

---

graylog2-web-interface/src/components/common/EntityFilters/ActiveFilter.tsx
graylog2-web-interface/src/components/common/EntityFilters/EntityFilters.tsx
graylog2-web-interface/src/components/common/QueryHelper.tsx

These are minor entity table fixes:
- Increasing z-index for filter select dropdown
- Supporting object id fields for attribute types
- Improving wording in query helper by using actual entity name

Minor entity table fixes/enhancements.

---

graylog2-server/src/main/java/org/graylog2/database/suggestions/MongoEntitySuggestionService.java
graylog2-server/src/test/java/org/graylog2/database/suggestions/MongoEntitySuggestionServiceTest.java
graylog2-server/src/test/resources/org/graylog2/database/suggestions/simple-fixtures.json

This PR is implementing functionality to support returning titles for collections, where a user has access only to a subset of documents.

Supporting partial permissions in entity title service.

---

graylog2-web-interface/src/components/bootstrap/ListGroup.md
graylog2-web-interface/src/components/bootstrap/ListGroup.tsx
graylog2-web-interface/src/components/bootstrap/ListGroupItem.tsx
graylog2-web-interface/src/components/common/SortableList/ListItem.tsx

Update `ListGroup` style.

---

graylog2-web-interface/src/components/bootstrap/ListGroupItem.tsx

Update theme usage in `ListGroupItem`.
/nocl

Update theme usage in `ListGroupItem`.

---

graylog2-web-interface/package.json
graylog2-web-interface/yarn.lock

Update sawmill to version `2.0.21`.
/nocl

Update sawmill to version `2.0.21`

---

graylog2-web-interface/src/components/common/RingProgress.md
graylog2-web-interface/src/components/common/RingProgress.tsx
graylog2-web-interface/src/components/common/index.tsx

Add simple ring progress component based on https://mantine.dev/core/ring-progress.
/nocl

Add ring progress component.

---

graylog2-server/src/test/java/org/graylog/testing/containermatrix/SearchServer.java

This PR is bumping the OpenSearch version used in tests to `2.15.0`.
/nocl

Testing OpenSearch 2.15

---

graylog2-web-interface/src/components/common/Drawer.tsx

This PR is adjusting the `Drawer` component's styling to make use of flex so that its body is using up available space.
/nocl

Using flex to grow drawer body.

---

changelog/unreleased/pr-19630.toml
graylog2-server/src/main/java/org/graylog2/plugin/DocsHelper.java

Before this change, `DocHelper` pointed to the outdated `docs.graylog.org`, now it points to `go2docs.graylog.org` and includes pointing to the current version.
The anchor for the `OpenSearch` config is missing, I already created an Asana request for that.

Updating DocHelper

---

graylog2-web-interface/src/components/bootstrap/Button.md
graylog2-web-interface/src/components/bootstrap/Button.tsx
graylog2-web-interface/src/components/common/PageNavigation.tsx

This is a follow-up for https://github.com/Graylog2/graylog2-server/pull/19817
Before:
After:
/nocl

Fix page navigation styling

---

changelog/unreleased/issue-19790.toml
graylog2-web-interface/src/components/datanode/DataNodeConfiguration/CAUpload.tsx
graylog2-web-interface/src/preflight/components/ConfigurationWizard/CAUpload.tsx

fixes https://github.com/Graylog2/graylog2-server/issues/19790

Fix CA upload delete icon XMARK not found

---

graylog2-web-interface/src/components/cluster/types.d.ts

Remove license status hooks

---

graylog2-web-interface/packages/graylog-web-plugin/package.json
graylog2-web-interface/yarn.lock

Update `@graylog/sawmill` to version `2.0.22`.
/nocl

Update `@graylog/sawmill` to version `2.0.22`.

---

changelog/unreleased/issue-19822.toml
graylog2-web-interface/src/components/scratchpad/Scratchpad.test.tsx
graylog2-web-interface/src/components/scratchpad/ScratchpadModal.tsx
graylog2-web-interface/yarn.lock

This PR is performing the required changes to adjust #19665 so that it works without #18874 being merged to `6.0` before. This fixes the `Copy`-button in the scratchpad modal.
Fixes #19822.

Fixing up copy button in scratchpad modal (`6.0`).

---

changelog/unreleased/pr-19830.toml
graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20240704100700_DashboardAddLastUpdated.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/DashboardsResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SavedSearchesResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewDTO.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewSummaryDTO.java
graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/Constants.ts
graylog2-web-interface/src/views/components/searchbar/saved-search/Constants.ts
graylog2-web-interface/src/views/hooks/useFetchView.test.ts
graylog2-web-interface/src/views/logic/views/View.ts
graylog2-web-interface/src/views/logic/views/__snapshots__/ViewTransformer.test.ts.snap
graylog2-web-interface/src/views/pages/ShowViewPage.test.tsx

This PR adds a lastUpdated attribute to views/dashboards and fills them initially with the last updated attribute of the associated search.

Adding lastUpdated to Dashboards

---

changelog/unreleased/pr-19824.toml
graylog2-server/src/main/java/org/graylog2/rest/models/system/indexer/responses/ClusterInfo.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexerClusterResource.java
graylog2-web-interface/src/components/indexers/IndexerClusterHealth.tsx
graylog2-web-interface/src/components/indexers/IndexerClusterHealthError.tsx
graylog2-web-interface/src/components/indexers/IndexerClusterHealthSummary.tsx
graylog2-web-interface/src/routing/ApiRoutes.ts

Shows the correct distribution name on indices page cluster health box
#19805

fix indexer cluster health to use correct distribution name

---

graylog2-server/src/main/java/org/graylog2/rest/models/tools/responses/PageListResponse.java

Constants in PageListResponse.
/nocl
Side quest of one of the former PRs. ;)

Constants in PageListResponse

---

changelog/unreleased/pr-19857.toml
graylog2-web-interface/src/views/components/visualizations/GenericPlot.tsx
graylog2-web-interface/src/views/components/visualizations/PlotLegend.tsx
graylog2-web-interface/src/views/components/widgets/MessageTable.tsx

This PR is doing some changes to reflect a non-interactive context in widgets:
- Disabling expanding messages in message table widget
- Disabling color popover in plot legend
- Disabling hover in timeline charts

Reflect interactive context in widgets.

---

graylog2-web-interface/src/components/streams/StreamDetails/output-filter/Constants.ts
graylog2-web-interface/src/components/streams/StreamDetails/output-filter/FilterRuleForm.tsx
graylog2-web-interface/src/components/streams/StreamDetails/output-filter/FilterRuleList.tsx
graylog2-web-interface/src/components/streams/StreamDetails/output-filter/FilterStatusCell.tsx
graylog2-web-interface/src/components/streams/StreamDetails/output-filter/Types.ts

fix Graylog2/graylog-plugin-enterprise#7730
/nocl

Add status field to Stream output rule list and form 

---

graylog2-server/src/main/java/org/graylog2/notifications/Notification.java
graylog2-server/src/main/resources/org/graylog2/freemarker/templates/HTML/drawdown_license_error.ftl
graylog2-server/src/main/resources/org/graylog2/freemarker/templates/PLAINTEXT/drawdown_license_error.ftl

add drawdown license notification type and templates
/nocl

add drawdown license error notification

---

graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config

threat_coverage flag explicitly set to `off`
/nocl
Avoiding warning in the logs.

threat_coverage flag explicitly set to off

---

graylog2-web-interface/packages/graylog-web-plugin/package.json
graylog2-web-interface/yarn.lock

Update sawmill to version `2.0.23`
/nocl

Update sawmill to version `2.0.23`.

---

graylog2-web-interface/src/views/logic/fieldtypes/useFieldTypes.ts

In some cases, we need an enabled parameter in useFieldTypes. For example, when exporting a widget into PDF we need to get field types only in case when we don't have them in the widget data
/nocl

Add enabled parameter to useFieldTypes

---

graylog2-web-interface/src/views/components/messagelist/MessageTableEntry.tsx

To be able to rewrite some styles in this table on the widget export render page we need to add some classes  to cells and rows.
/nocl

Add class name to FieldsRow and TableDataCell in MessageTable

---

graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config

Add Investigation report by AI feature flag

---

graylog2-web-interface/src/views/logic/fieldtypes/useFieldTypes.ts

In some cases, f.e. when we are using `enabled` flag, we need `isFetching` flag as well 
/nocl

Add isFetching flag to useFieldTypes hook

---

graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/Sharing.java
graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/Users.java

Adding more users, the report entity and convenience methods to IT test base classes. Used in the Reporting IT tests  in enterprise.
/nocl because only used in tests

Adding more users and entity type/convenience methods

---

changelog/unreleased/issue-19977.toml
graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/RemoteReindexRunning.tsx

fixes https://github.com/Graylog2/graylog2-server/issues/19977

Display timestamp in datanode migration logs

---

graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationV2.java

* Improve system error notification message for failed CustomHTTPNotifiations
/nocl error message improvement

Backport 6.0: Improve system error notification message for failed CustomHTTPNotifions (#19998)

---

changelog/unreleased/issue-19871.toml
graylog2-web-interface/src/components/datanode/DataNodePageNavigation.tsx
graylog2-web-interface/src/components/datanode/hooks/useShowDatanodeMigration.ts

fixes https://github.com/Graylog2/graylog2-server/issues/19871

Disable data node migration wizard on installations using data node

---

changelog/unreleased/pr-20042.toml
graylog2-web-interface/src/components/datanode/hooks/useShowDatanodeMigration.ts

fixes https://github.com/Graylog2/graylog2-server/issues/19871

only hide DatanodeMigration if state 'FINISHED' and datanode is configured

---

graylog2-server/src/main/java/org/graylog2/indexer/MongoIndexSet.java
graylog2-server/src/test/java/org/graylog2/indexer/MongoIndexSetTest.java

/nocl
companion PR https://github.com/Graylog2/graylog-plugin-enterprise/pull/8112

add warm infix remove helper method

---

changelog/unreleased/pr-20103.toml
graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/UnsupportedRemoteReindexingMigrationAdapterES7.java
graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/RemoteReindexingMigrationAdapterOS2.java
graylog2-server/src/main/java/org/graylog2/indexer/datanode/MigrationConfiguration.java
graylog2-server/src/main/java/org/graylog2/indexer/datanode/RemoteReindexMigrationService.java
graylog2-server/src/main/java/org/graylog2/indexer/datanode/RemoteReindexMigrationServiceImpl.java
graylog2-server/src/main/java/org/graylog2/indexer/datanode/RemoteReindexingMigrationAdapter.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/debug/bundle/SupportBundleService.java
graylog2-server/src/main/java/org/graylog2/shared/rest/resources/system/RemoteDataNodeStatusResource.java
graylog2-server/src/test/java/org/graylog2/indexer/datanode/RemoteReindexMigrationServiceImplTest.java

This PR adds the Opensearch logs from the data nodes as well as logs and info from remote reindexing migrations (if present) to the support bundle.
closes https://github.com/Graylog2/graylog-plugin-enterprise/issues/7964

Add datanode logs to support bundle

---

data-node/src/main/java/org/graylog/datanode/rest/IndicesDirectoryController.java

Wrap all exceptions that occur during check in response instead of returning a 500 for unexpected exceptions.
/nocl
solves #20138

Better error handling in data node directory compatibility check

---

graylog2-web-interface/src/components/cluster/GraylogClusterOverview.tsx
graylog2-web-interface/src/components/common/Graph/TrafficGraphWithDaySelect.tsx
graylog2-web-interface/src/components/common/Graph/contexts/GraphDaysContext.ts
graylog2-web-interface/src/components/common/Graph/contexts/GraphDaysContextProvider.tsx
graylog2-web-interface/src/components/common/Graph/contexts/useGraphDays.tsx
graylog2-web-interface/src/components/common/Graph/types.ts

Part of https://github.com/Graylog2/graylog-plugin-enterprise/issues/7837
/jpd Graylog2/graylog-plugin-enterprise#8161
/nocl

Add provider to share graph days

---

graylog2-server/src/main/java/org/graylog2/notifications/Notification.java
graylog2-server/src/main/resources/org/graylog2/freemarker/templates/HTML/data_tiering_rollover_error.ftl
graylog2-server/src/main/resources/org/graylog2/freemarker/templates/PLAINTEXT/data_tiering_rollover_error.ftl

This PR adds a data tiering rollover notification template that can be used to display multiple errors
/nocl

add data tiering notification template

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/export/XLSXWriter.java

Fixing NPE in XLSXWriter. Adding missing else clauses.
/nocl
Fixes #8206.
Blank values in aggregations were not handled properly because of the bug in XLSXWriter class.
Manually.

Fixing NPE in XLSXWriter. Adding missing else clauses.

---

graylog2-web-interface/src/components/event-definitions/event-definition-form/AddNotificationForm.jsx

Closes https://github.com/Graylog2/graylog-plugin-enterprise/issues/7813
/nocl

Change `menuPlacement` prop to prevent menu from being cut off

---

graylog2-web-interface/src/components/bootstrap/Table.jsx
graylog2-web-interface/src/components/common/EntityDataTable/EntityDataTable.tsx
graylog2-web-interface/src/components/common/EntityDataTable/TableRow.tsx

This PR is slightly improving the table border styling, so they look more like the related mockups in the style guide.
Before:
After:
/nocl

Improve styling of table borders.

---

graylog2-web-interface/src/components/common/IconButton.tsx

/nocl
/jpd https://github.com/Graylog2/graylog-plugin-enterprise/pull/8283

Add size prop to IconButton

---

graylog2-web-interface/src/theme/GraylogThemeProvider.tsx
graylog2-web-interface/src/theme/hooks/useThemes.ts

This PR implements a hook to setup the mantine and styled components theme.
/nocl

Implement hook to setup mantine and styled components theme.

---

graylog2-web-interface/src/@types/graylog-web-plugin/index.d.ts
graylog2-web-interface/src/components/streams/StreamDetails/StreamDataRoutingProcessing.tsx
graylog2-web-interface/src/components/streams/StreamDetails/StreamDetails.tsx

/nocl
/jpd Graylog2/graylog-plugin-enterprise#8219

Show stream illuminate processing section only for Ilumminate stream

---

graylog2-web-interface/src/@types/graylog-web-plugin/index.d.ts
graylog2-web-interface/src/components/streams/StreamDetails/StreamDetails.tsx

This PR allow filtering DWH jobs by stream.
/nocl
/jpd Graylog2/graylog-plugin-enterprise#8246

Filter job with streamId

---

graylog2-server/src/main/java/org/graylog2/rest/models/PaginatedResponse.java

Added a way to reach PaginatedList from PaginatedResponse.
/nocl
Needed to work with the results of security app services, that often return PaginatedResponse.

Added a way to reach PaginatedList from PaginatedResponse

---

changelog/unreleased/pr-20263.toml
graylog2-server/src/main/java/org/graylog2/grok/GrokPatternRegistry.java
graylog2-server/src/test/java/org/graylog2/grok/GrokPatternRegistryTest.java

Backport 6.0: Fix grok_exists pipeline rule (#20263)

---

changelog/unreleased/pr-20263.toml
graylog2-server/src/main/java/org/graylog2/grok/GrokPatternRegistry.java
graylog2-server/src/test/java/org/graylog2/grok/GrokPatternRegistryTest.java

Backport 5.2: Fix grok_exists pipeline rule (#20263)

---

changelog/unreleased/pr-20244.toml
changelog/unreleased/pr-20265.toml
graylog2-server/src/main/java/org/graylog/plugins/views/search/views/WidgetDTO.java
graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackPersistenceService.java
graylog2-server/src/main/java/org/graylog2/contentpacks/facades/StreamReferenceFacade.java
graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackPersistenceServiceTest.java
graylog2-server/src/test/resources/org/graylog2/contentpacks/content_pack_with_dashboard_with_stream.json
graylog2-server/src/test/resources/org/graylog2/contentpacks/content_pack_with_dashboard_with_stream_reference.json

Backport the following dashboard and stream fixes to the `6.0` branch. 
https://github.com/Graylog2/graylog2-server/pull/20244
https://github.com/Graylog2/graylog2-server/pull/20265
https://github.com/Graylog2/graylog2-server/pull/20288

Backport 6.0: Dashboard stream/title content pack fixes

---

changelog/unreleased/pr-20244.toml
changelog/unreleased/pr-20265.toml
graylog2-server/src/main/java/org/graylog/plugins/views/search/views/WidgetDTO.java
graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackPersistenceService.java
graylog2-server/src/main/java/org/graylog2/contentpacks/facades/StreamReferenceFacade.java
graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackPersistenceServiceTest.java
graylog2-server/src/test/resources/org/graylog2/contentpacks/content_pack_with_dashboard_with_stream.json
graylog2-server/src/test/resources/org/graylog2/contentpacks/content_pack_with_dashboard_with_stream_reference.json

Backport the following dashboard and stream fixes to the `5.2` branch. 
https://github.com/Graylog2/graylog2-server/pull/20244
https://github.com/Graylog2/graylog2-server/pull/20265
https://github.com/Graylog2/graylog2-server/pull/20288

Backport 5.2: Dashboard stream/title content pack fixes

---

graylog2-web-interface/packages/eslint-config-graylog/package.json

This reverts commit 89fb6f190d8550c24170ab0f50b7d1421084f2a9 / #20337.
The update is introducing a regression for us, trying to fix quoted strings in props in invalid way (see 748e1bf587a593febae9d699dc6e51cf75144c75).

Revert "Bump eslint-plugin-react (#20337)"

---

graylog2-web-interface/src/components/streams/StreamDetails/StreamDetails.tsx

- Add throughput counter to stream detail
- Add description for each stream details section
/nocl
resolves Graylog2/graylog-plugin-enterprise#7818 Graylog2/graylog-plugin-enterprise#8403

Add throughput and description to stream details 

---

pom.xml

This PR is bumping the node version used for building to v20 (current lts).

Bumping to Node 20 (lts/iron).

---

changelog/unreleased/pr-20110.toml

Add newly merged PRs to the original Stream Category changelog.

Add relevant PRs to original Stream Category CL

---

graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config

Turn flags on for alpha build.
/nocl

Turn flags on for alpha build

---

graylog2-web-interface/packages/eslint-config-graylog/index.js

This PR adjusts our ESLint rules to avoid warnings for code like:
```jsx
const Strong = ({ strong, text }: { strong: boolean, text: string }) => strong 
? <b>{text}</b> 
: <>{text}</>;
```
We need to wrap `text` in a fragment here, as `string` is not part of the `JSX.Element` type that should be required by a JSX component. Without `allowExpressions`, the `react/jsx-no-useless-fragment` rule will complain in this case, because the fragment is technical unnecessary.

Allow expressions in JSX fragments.

---

graylog2-web-interface/src/components/indices/IndexSetTemplates/SelectIndexSetTemplateModal.tsx

Closes https://github.com/Graylog2/graylog-plugin-enterprise/issues/8541
/nocl unreleased feature

Adjust copy in Index Template modal

---

graylog2-server/src/test/java/org/graylog/testing/containermatrix/SearchServer.java

**Note:** This will fail for now, because `2.17.0` is not released yet.
This PR is bumping OpenSearch used in tests to `2.17.0`.

Testing against OpenSearch `2.17.0`.

---

graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/Users.java

adding the reader role to the default additional user in IT tests to make it more like a simple standard user 
/nocl, no user facing changes

Adding reader role for simple user in IT tests

---

changelog/unreleased/issue-20448.toml
graylog2-web-interface/src/components/datanode/migrations/in-place/RestartGraylog.tsx
graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/ExistingDataMigrationQuestion.tsx

server.conf instead of graylog.conf

---

changelog/unreleased/issue-20409.toml
graylog2-web-interface/src/views/components/searchbar/queryvalidation/QueryValidation.tsx

Check query validation status info for the Info error icon.
resolve #20409

Check info status before displaying info icon in search bar

---

changelog/unreleased/issue-19240.toml
graylog2-web-interface/src/components/configurations/SidecarConfig.tsx

Resolves #19240 
Backport fix for validation issue. See linked issue for details.

Backport52/issue 16829: Backport fix for sidecar config validation 

---

changelog/unreleased/issue-20481.toml
graylog2-web-interface/src/components/datanode/DataNodeList/DataNodeActions.tsx
graylog2-web-interface/src/components/datanode/DataNodeList/DataNodeBulkActions.tsx
graylog2-web-interface/src/components/datanode/DataNodeList/DataNodeList.tsx
graylog2-web-interface/src/components/datanode/hooks/useDataNodes.ts
graylog2-web-interface/src/logic/sleep.ts

In this PR we fixed issues introduced by #19415:
- added back bulk actions
- unselect datanodes after a successful bulk action
- refetch interval for datanode list
- refetch datanode list on row actions and bulk actions
fixes [#20481](https://github.com/Graylog2/graylog2-server/issues/20481)

Fix new Datanode EntityDataTable issues

---

changelog/unreleased/issue-20515.toml
graylog2-web-interface/src/components/streams/StreamsOverview/StreamsOverview.tsx

Increase stream list actionsCellWidth

---

graylog2-server/src/main/java/org/graylog2/indexer/indexset/template/IndexSetTemplateService.java
graylog2-server/src/main/resources/org/graylog2/indexer/indexset/template/on_prem_templates.json
graylog2-web-interface/src/pages/IndexSetTemplatesPage.tsx

/nocl
closes Graylog2/graylog-plugin-enterprise#8557
the PR also updates the index template descriptions

hide built-in templates in table view

---

graylog2-web-interface/src/views/components/visualizations/utils/__tests__/fixtures.ts
graylog2-web-interface/src/views/components/visualizations/utils/chartLayoutGenerators.ts

This PR adds `ticklabelposition` for the 4th axis. That aligns the axis labels closer to the chart. This fix overlapping in most cases and also removes unnecessary black space between chart and axis labels  
Before:
After:
We still might have overlapping when the user makes the widget narrow, but in most of cases widgets with 4 axes will be wider 
We can consider future improvements to fix that in all possible cases. Possible solutions might be:
1. reduce chart width increasing the place for the labels
2. Write logic for the custom tick labels for the % and numbers. That would help us control label distribution along the axis and prevent them from crossing. 
fix: #20044 
/nocl

Add ticklabelposition parameter to the 4th axis

---

graylog2-web-interface/src/views/components/searchbar/queryvalidation/QueryValidation.tsx

fix Graylog2/graylog-plugin-enterprise#8409
/nocl

Add shake animation highlight to Query validation Icon when status is Info

---

graylog2-server/src/main/java/org/graylog2/periodical/ThrottleStateUpdaterThread.java
graylog2-server/src/main/java/org/graylog2/shared/journal/Journal.java
graylog2-server/src/main/java/org/graylog2/shared/journal/LocalKafkaJournal.java
graylog2-server/src/main/java/org/graylog2/shared/journal/NoopJournal.java
graylog2-server/src/test/java/org/graylog2/shared/journal/LocalKafkaJournalTest.java

/nocl part of unreleased featured
Add a method to LocalKafkaJournal for reporting journal utilization

Added method to get current jornal utilization

---

graylog2-web-interface/src/components/common/Section.tsx
graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/DestinationIndexSetSection.tsx
graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/DestinationOutputs.tsx
graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/DestinationSwitch.tsx

/nocl unreleased feature
fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/8460 https://github.com/Graylog2/graylog-plugin-enterprise/issues/8566
/jpd Graylog2/graylog-plugin-enterprise#8777

Disable outputs and index set switch and stop propagation for left header in section component

---

graylog2-web-interface/src/components/common/InputList/InputList.test.tsx
graylog2-web-interface/src/integrations/event-notifications/event-notification-details/SlackNotificationDetails.tsx
graylog2-web-interface/src/integrations/event-notifications/event-notification-details/TeamsNotificationDetails.tsx
graylog2-web-interface/src/integrations/event-notifications/event-notification-details/TeamsNotificationV2Details.tsx
graylog2-web-interface/src/views/components/widgets/WidgetColorContext.test.tsx

This PR removes the explicit usage of the `React.FC` type, which is not needed in almost all cases.

Removing usage of `React.FC` type.

---

changelog/unreleased/pr-20608.toml
graylog2-web-interface/src/components/navigation/bindings.ts

fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/8779

added datanode permissions

---

graylog2-web-interface/src/pages/EnterprisePage.tsx

Fixes https://github.com/Graylog2/graylog2-server/issues/19230
/nocl

Rename Graylog Operations to Enterprise on Overview page

---

graylog2-web-interface/src/views/components/searchbar/queryvalidation/QueryValidation.test.tsx
graylog2-web-interface/src/views/components/searchbar/queryvalidation/QueryValidation.tsx

closes https://github.com/Graylog2/graylog-plugin-enterprise/issues/8553
/nocl

Improve title of search validation icon

---

graylog2-server/src/main/java/org/graylog/grn/GRNTypes.java
graylog2-server/src/main/java/org/graylog/grn/GRNTypesModule.java

This was part of an entity collection that was never finished and is not in use.
/nocl Removing unused code.
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/8864

Remove GRN types for collections

---

data-node/src/main/java/org/graylog/datanode/Configuration.java
data-node/src/main/java/org/graylog/datanode/bindings/DatanodeConfigurationBindings.java
data-node/src/main/java/org/graylog/datanode/configuration/OpensearchConfigurationService.java
data-node/src/main/java/org/graylog/datanode/configuration/variants/OpensearchSecurityConfiguration.java
data-node/src/main/java/org/graylog/datanode/initializers/JerseyService.java
data-node/src/main/java/org/graylog/datanode/initializers/JwtTokenAuthFilter.java
data-node/src/test/java/org/graylog/datanode/initializers/JwtTokenAuthFilterTest.java
data-node/src/test/java/org/graylog/datanode/testinfra/DatanodeContainerizedBackend.java
full-backend-tests/src/test/java/org/graylog/datanode/DatanodeProvisioningIT.java
graylog2-server/src/main/java/org/graylog2/configuration/IndexerDiscoveryModule.java
graylog2-server/src/main/java/org/graylog2/security/IndexerJwtAuthTokenProvider.java
graylog2-server/src/main/java/org/graylog2/security/JwtSecret.java
graylog2-server/src/main/java/org/graylog2/security/JwtSecretProvider.java
graylog2-server/src/test/java/org/graylog2/security/JwtSecretProviderTest.java

Backport of https://github.com/Graylog2/graylog2-server/pull/20656
/nocl

Explicit type for JwtSecret data, password handling (#20656)

---

graylog2-web-interface/package.json
graylog2-web-interface/yarn.lock

Updating `typescript` to `5.6`.

---

changelog/unreleased/issue-20800.toml
graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/pivot/EffectiveTimeRangeExtractor.java
graylog2-server/src/main/java/org/graylog2/plugin/indexer/searches/timeranges/RelativeRange.java

**Note:** This needs a backport to `6.1`.
This PR is fixing up the extraction of effective time ranges for async searches, by correcting and consolidating the time range of the search type with an all time range.
Fixes #20800.

Fixing up extraction of effective time range for async searches.

---

graylog2-server/src/main/java/org/graylog2/cluster/nodes/DataNodeDto.java
graylog2-server/src/test/java/org/graylog2/cluster/nodes/DataNodeDtoTest.java

Ignore build version number when checking datanode compatibility

---

graylog2-web-interface/src/components/common/Section.tsx
graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/AddOutputButton.tsx

fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/8807
main pr https://github.com/Graylog2/graylog-plugin-enterprise/pull/8954/
/nocl

Data warehouse UI improvements

---

graylog2-web-interface/src/components/configurationforms/ConfigurationForm.tsx

This PR fixes an issue which is resulting from the refactorings in #20696. In there, complex values have been assigned as default arguments in the `ConfigurationForm` component. This leads to a constant update of child components due to new references being passed.
This PR fixes this by using constant values for complex default arguments. It also cleans up a minor typing issue.
/nocl Changed code was not released.

Fixing output creation form.

---

graylog2-web-interface/src/components/common/DataTable/DataTable.test.tsx
graylog2-web-interface/src/components/common/Delayed.test.tsx
graylog2-web-interface/src/components/common/LoadingIndicator.test.tsx
graylog2-web-interface/src/components/common/Spinner.test.tsx
graylog2-web-interface/src/components/content-packs/ContentPackInstall.test.jsx
graylog2-web-interface/src/components/content-packs/ContentPackSelection.test.jsx
graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/NumberRefExpression.test.jsx
graylog2-web-interface/src/components/permissions/EntityShareModal.test.tsx
graylog2-web-interface/src/views/components/SearchResult.test.tsx
graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TabKeywordTimeRange.test.tsx

This PR is fixing up the imports for `act` related to the upcoming changes in React 19, according to [the migration guide](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-react-dom-test-utils).

Fixing up import of `act`.

---

graylog2-web-interface/packages/graylog-web-plugin/package.json
graylog2-web-interface/src/components/bootstrap/BootstrapModalConfirm.md
graylog2-web-interface/src/components/common/ColorPicker.md
graylog2-web-interface/src/components/common/ColorPickerPopover.md
graylog2-web-interface/src/components/common/ControlledTableList.md
graylog2-web-interface/src/components/common/ExpandableList.md
graylog2-web-interface/src/components/common/PaginatedList.md
graylog2-web-interface/src/components/common/ReactGridContainer.md
graylog2-web-interface/src/components/common/SearchForm.md
graylog2-web-interface/src/components/common/Select.md
graylog2-web-interface/src/components/common/SelectPopover.md
graylog2-web-interface/src/components/common/SelectableList.md
graylog2-web-interface/src/components/common/SortableList/SortableList.md
graylog2-web-interface/src/components/common/SourceCodeEditor.md
graylog2-web-interface/src/components/common/TableList.md
graylog2-web-interface/src/components/common/TimeUnitInput.md
graylog2-web-interface/src/components/common/TimezoneSelect.md
graylog2-web-interface/src/components/common/TypeAheadDataFilter.md
graylog2-web-interface/src/components/common/TypeAheadInput.md
graylog2-web-interface/src/components/common/Wizard.md
graylog2-web-interface/vendor.modules.js

This PR is removing the remaining usages of `createReactClass` from code snippets in docs and removes the package.

Removing `createReactClass` usages from docs and package.

---

changelog/unreleased/issue-20800.toml
graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/pivot/EffectiveTimeRangeExtractor.java
graylog2-server/src/main/java/org/graylog2/plugin/indexer/searches/timeranges/RelativeRange.java

This PR is fixing up the extraction of effective time ranges for async searches, by correcting and consolidating the time range of the search type with an all time range.
Fixes #20800.

Fixing up extraction of effective time range for async searches. (`6.1`)

---

.github/workflows/notify-upgrade-notes.yml

Add workflow to send a Slack notification when UPGRADING.md changes

---

UPGRADING.md

Rotate UPGRADING.md for 6.2

---

UPGRADING.md

Add configuration file changes section to UPGRADING.md

---

.github/workflows/notify-upgrade-notes.yml

[skip ci]
/nocl No product change

Update formatting in notify-upgrade-notes.yml workflow

---

graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config

Default value for DW preview f.flag.
/nocl
Get rid of a warning in the logs.
Manually.

Default value for DW preview f.flag

---

graylog2-web-interface/src/pages/PipelineDetailsPage.tsx

- This PR fixes an issue with pipeline creation.
- Before, when attempting to create a pipline, it would show an error (see screen recording).
- Likely this bug was introduced just lately by migrating the component: https://github.com/Graylog2/graylog2-server/pull/20818
/nocl No released bug
https://github.com/user-attachments/assets/7d5355e2-2401-4c43-b1dd-826ebaf8a130

Use form pipeline object for pipeline creation

---

graylog2-web-interface/src/pages/ShowContentPackPage.tsx

This PR is fixing an issue which is the fallout of a recent refactoring (#20818). During this refactoring, it was overseen that the `selectedVersion` variable is coming both from state and the `ContentPacksStore`.
Fixes #20900.
/nocl No published regression.

Fixing usage of current version on Content Pack details page.

---

graylog2-web-interface/src/components/common/Section.test.tsx
graylog2-web-interface/src/components/common/Section.tsx

Before these changes, there was no way to react to Collapse action for the Section component.
/nocl

Add callback to Section component.

---

graylog2-web-interface/src/pages/PipelineDetailsPage.tsx

Fixes https://github.com/Graylog2/graylog2-server/issues/20927
/nocl No released bug

Fix pipeline stage updates not being persisted

---

.github/workflows/notify-upgrade-notes.yml

Fix quoting in notify-upgrade-notes.yml workflow

---

changelog/unreleased/issue-15301.toml
graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java
graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/MultiGrokMatch.java
graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/multiGrok.txt

Backports #20924 to 6.0 so the SecCon team can use the function in content sooner.

Backport 6.0: Add multi_grok pipeline function

---

graylog2-server/src/main/java/org/graylog/security/authservice/rest/AuthServiceBackendsResource.java
graylog2-server/src/main/java/org/graylog/security/authzroles/AuthzRolesResource.java
graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
graylog2-server/src/main/java/org/graylog2/users/PaginatedUserService.java
graylog2-server/src/main/java/org/graylog2/users/UserOverviewDTO.java

/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/9224
/nocl

Refactor PaginatedUserService to use new MongoDB API

---

graylog2-server/src/main/java/org/graylog2/indexer/indexset/profile/IndexFieldTypeProfileService.java
graylog2-server/src/test/java/org/graylog2/indexer/indexset/profile/IndexFieldTypeProfileServiceTest.java

Refactor IndexFieldTypeProfileService to no longer extend PaginatedDbService

---

graylog2-server/src/main/java/org/graylog2/database/PaginatedDbService.java

Deprecate PaginatedDbService

---

full-backend-tests/src/test/java/org/graylog/datanode/ClientCertResourceIT.java

/nocl
Integration test checking that generation of client certificates is working correctly and they can be used to access the opensearch inside the datanode.

Added integration test for client certificates

---

graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java
graylog2-server/src/main/java/org/graylog2/streams/PaginatedStreamService.java
graylog2-server/src/main/java/org/graylog2/streams/StreamDTO.java

Use new MongoDB API in PaginatedStreamService

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java
graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/IndicesAdapterOS2.java
graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java
graylog2-server/src/main/java/org/graylog2/indexer/IndexMappingTemplate.java
graylog2-server/src/main/java/org/graylog2/indexer/indices/IndexSettings.java
graylog2-server/src/main/java/org/graylog2/indexer/indices/IndexSettingsHelper.java
graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java
graylog2-server/src/main/java/org/graylog2/indexer/indices/IndicesAdapter.java

Backport for #21054
/nocl
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#9288
(cherry picked from commit 28d53dafbae522be56983fa518a5198df021fb82)

implement option to get and apply index settings (#21054) (6.1)

---

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/db/mongodb/PaginatedMongoDbPipelineService.java
graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/db/mongodb/PaginatedMongoDbRuleService.java

A tiny refactoring because we are moving away from the `PaginatedDbService`.
/nocl

Refactor paginated pipeline services to no longer extend PaginatedDbService

---

graylog2-server/src/main/java/org/graylog/events/notifications/DBNotificationGracePeriodService.java
graylog2-server/src/main/java/org/graylog/events/notifications/EventNotificationStatus.java

Refactor DBNotificationGracePeriodService to no longer extend PaginatedDbService

---

changelog/unreleased/pr-21103.toml
graylog2-web-interface/src/logic/telemetry/TelemetryInit.tsx

Backport disable cross_subdomain_cookie (#20702)

---

changelog/unreleased/pr-21031.toml
data-node/src/main/java/org/graylog/datanode/Configuration.java
data-node/src/main/java/org/graylog/datanode/bindings/OpensearchProcessBindings.java
data-node/src/main/java/org/graylog/datanode/configuration/OpensearchConfigurationService.java
data-node/src/main/java/org/graylog/datanode/configuration/variants/OpensearchSecurityConfiguration.java
data-node/src/main/java/org/graylog/datanode/opensearch/cli/OpensearchCommandLineProcess.java
data-node/src/main/java/org/graylog/datanode/opensearch/cli/OpensearchKeystoreCli.java
data-node/src/main/java/org/graylog/datanode/opensearch/configuration/OpensearchConfiguration.java
data-node/src/main/java/org/graylog/datanode/opensearch/configuration/OpensearchUsableSpace.java
data-node/src/main/java/org/graylog/datanode/opensearch/configuration/OpensearchUsableSpaceProvider.java
data-node/src/main/java/org/graylog/datanode/opensearch/configuration/beans/OpensearchConfigurationBean.java
data-node/src/main/java/org/graylog/datanode/opensearch/configuration/beans/OpensearchConfigurationPart.java
data-node/src/main/java/org/graylog/datanode/opensearch/configuration/beans/impl/SearchableSnapshotsConfigurationBean.java
data-node/src/test/java/org/graylog/datanode/opensearch/configuration/beans/OpensearchConfigurationPartTest.java
data-node/src/test/java/org/graylog/datanode/opensearch/configuration/beans/impl/SearchableSnapshotsConfigurationBeanTest.java

Backport of #21031
fixes https://github.com/Graylog2/graylog2-server/issues/20859

Backport: Unified snapshots configuration for datanode 

---

.mvn/wrapper/maven-wrapper.properties
mvnw
pom.xml

/nocl
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/9330

Update Maven to 3.9.9

---

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/PipelineResource.java

/nocl change to unreleased feature
#21014 introduced the system/pipelines/pipeline/routing API.
This PR makes the `remove_from_default` parameter optional. If it is not specified, the value is based on the configuration of the target stream.

Make routing parameter remove_from_default optional

---

full-backend-tests/src/test/java/org/graylog/pipelines/StreamsPipelinesIT.java
graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java

This PR is fixing an issue related to #21081 by handling missing pipeline connections properly, avoiding a 500.
/nocl Fixing an issue that was not released yet.

Fix handling of missing pipeline connection.

---

changelog/unreleased/pr-21056.toml
graylog2-server/src/main/java/org/graylog/events/processor/EventDefinition.java
graylog2-server/src/main/java/org/graylog/events/rest/EventsResource.java
graylog2-server/src/main/java/org/graylog/events/search/EventsSearchFilter.java
graylog2-server/src/main/java/org/graylog/events/search/EventsSearchService.java
graylog2-server/src/main/java/org/graylog2/plugin/indexer/searches/timeranges/TimeRange.java
graylog2-web-interface/src/components/common/EntityFilters/EntityFilters.test.tsx
graylog2-web-interface/src/components/common/EntityFilters/FilterConfiguration/FilterConfiguration.tsx
graylog2-web-interface/src/components/common/EntityFilters/FilterConfiguration/GenericFilterInput.tsx
graylog2-web-interface/src/components/events/Constants.ts
graylog2-web-interface/src/components/events/EventsEntityTable.tsx
graylog2-web-interface/src/components/events/FilterValueRenderers.tsx
graylog2-web-interface/src/components/events/events/PriorityName.tsx
graylog2-web-interface/src/components/events/fetchEvents.ts

This PR is providing functionality to filter alerts/events based on:
- Event Definition
- Priority
- Key
- Aggregation Timerange
Refs #21055.

Adding additional filters to alerts & events list.

---

graylog2-web-interface/src/@types/graylog-web-plugin/index.d.ts
graylog2-web-interface/src/components/streams/MatchingTypeSwitcher.tsx
graylog2-web-interface/src/components/streams/StreamDetails/DestinationPermissionAlert.tsx
graylog2-web-interface/src/components/streams/StreamDetails/StreamDataRoutingDestinations.tsx
graylog2-web-interface/src/components/streams/StreamDetails/StreamDetails.tsx
graylog2-web-interface/src/components/streams/StreamDetails/output-filter/FilterRuleList.tsx
graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/DestinationIndexSetSection.tsx
graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/IndexSetFilters.tsx
graylog2-web-interface/src/components/streams/StreamsOverview/StreamActions.tsx

Add missing stream details permissions and update types
/nocl
/jpd Graylog2/graylog-plugin-enterprise#9275

Update dwh types

---

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/PipelineResource.java

/nocl part of new feature
relates to #20568
Instead of returning the pipeline source from `PUT system/pipelines/pipeline/routing` we now return the ID of the new routing rule.
Caller has no use for the pipeline source.
The rule ID can be used to delete the rule, if rollback is requested.

Modify routing API return value

---

graylog2-server/src/main/java/org/graylog/events/processor/DBEventDefinitionService.java
graylog2-server/src/main/java/org/graylog/events/search/EventsSearchService.java
graylog2-web-interface/src/components/common/PaginatedEntityTable/parseTimerangeFilter.ts
graylog2-web-interface/src/components/events/events/ColumnRenderers.tsx
graylog2-web-interface/src/components/events/fetchEvents.ts

This PR is supporting events refactorings by improving events services typings/interfaces:
- Utilizing bulk loading in `EventsSearchService` to avoid multiple DB roundtrips
- Widening parameter type for `DBEventDefinitionService#getByIds`
- Extracting `parseTimerangeFilters` for reuse in security events

Improving Events Services.

---

graylog2-server/src/main/java/org/graylog2/plugin/inputs/codecs/Codec.java

add javadoc for decodeSafe method

---

graylog2-web-interface/src/components/common/EntityFilters/hooks/useUrlQueryFilters.test.tsx
graylog2-web-interface/src/components/indices/IndexSetFieldTypeProfiles/ProfilesList.test.tsx
graylog2-web-interface/src/components/indices/IndexSetFieldTypes/IndexSetFieldTypesList.test.tsx
graylog2-web-interface/src/components/indices/IndexSetFieldTypes/SetProfileModal.test.tsx
graylog2-web-interface/src/components/streams/StreamsOverview/StreamsOverview.test.tsx
graylog2-web-interface/src/pages/IndexSetFieldTypesPage.test.tsx
graylog2-web-interface/src/routing/App.tsx
graylog2-web-interface/src/routing/DefaultQueryParamProvider.tsx
graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardsOverview.test.tsx
graylog2-web-interface/src/views/pages/DashboardsPage.test.tsx

This PR contains a refactoring to centralise the setup of the `QueryParamProvider` in one component.
This allows removing redundant code and simplifies related changes in the future.
/nocl

Implement `DefaultQueryParamProvider`.

---

graylog2-web-interface/src/views/logic/views/UseCreateViewForEvent.ts

This PR is fixing an issue for the "Replay Search" functionality for security events, which failed with an exception after refactorings for the Paginated Data Table.
/nocl Is fixing an unreleased issue.

Fixing exception when replaying search for security event.

---

graylog2-server/src/test/java/org/graylog2/security/encryption/EncryptedValueTest.java

Remove `PaginatedDbService` usage from `EncryptedValueTest`

---

graylog2-web-interface/src/components/common/EntityDataTable/hooks/useTableEventHandlers.ts
graylog2-web-interface/src/logic/telemetry/Constants.ts

Previously we use 
```
TELEMETRY_EVENT_TYPE.EVENTDEFINITION_LIST.SORT_CHANGED
TELEMETRY_EVENT_TYPE.EVENTDEFINITION_LIST.COLUMNS_CHANGED
TELEMETRY_EVENT_TYPE.EVENTDEFINITION_LIST.PAGE_SIZE_CHANGED
```
As not all tables relate to EVENTDEFINITION_LIST those event types might be confusing. 
This PR changes the event type name to more general  `...ENTITY_DATA_TABLE... `
/nocl

Fix telemetry event type for entity data table

---

graylog2-web-interface/src/views/components/widgets/FieldsConfiguration.tsx
graylog2-web-interface/src/views/components/widgets/SelectedFieldsList.tsx

This PR is a follow-up for https://github.com/Graylog2/graylog2-server/pull/20843. It allows defining a custom field select for the `SelectedFieldsList` component.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/9506
/nocl

Make field select in `SelectedFieldsList` configurable.

---

graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config

This PR adds feature flag to show and hide executive dashboard
/nocl
/jpd https://github.com/Graylog2/graylog-plugin-enterprise/pull/9513

Add a feature flag which hides the Executive Dashboard from the user.

---

changelog/unreleased/pr-21367.toml
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/ScriptingApiResource.java

Adding missing API description parameters for methods in the Simple Scripting API.
fixes #20821

Adding missing API descriptions for Simple Scripting API

---

graylog2-web-interface/src/components/events/events/BulkActions.test.tsx
graylog2-web-interface/src/components/events/events/BulkActions.tsx
graylog2-web-interface/src/components/events/events/hooks/useSendEventActionTelemetry.ts

Add bulk replay search telemetry

---

graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypesDTO.java
graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypesService.java
graylog2-server/src/main/java/org/graylog2/indexer/ranges/IndexRangeService.java
graylog2-server/src/main/java/org/graylog2/indexer/ranges/MongoIndexRangeService.java
graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypesServiceTest.java
graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/MongoFieldTypeLookupTest.java
graylog2-server/src/test/java/org/graylog2/indexer/ranges/MongoIndexRangeServiceTest.java

Remove `JacksonDBCollection` usage from `indexer` package

---

graylog2-server/src/main/java/org/graylog2/grok/GrokPattern.java
graylog2-server/src/main/java/org/graylog2/grok/MongoDbGrokPatternService.java
graylog2-server/src/test/java/org/graylog2/grok/MongoDbGrokPatternServiceTest.java

Remove usage of `JacksonDBCollection` from `MongoDbGrokPatternService`

---

README.markdown

This PR is removing the build badge from the Readme, as it points towards an action which is not used to build the default branch anymore, but results in pointing to the last PR build, which is kinda random and shows build failures often.
/nocl

Remove build badge from Readme.

---

graylog2-web-interface/packages/stylelint-config-graylog/index.js
graylog2-web-interface/packages/stylelint-config-graylog/package.json

This PR is removing all formatting options from our stylelint config, as these [have been removed](https://stylelint.io/migration-guide/to-15/). Future formatting will be handled solely through prettier.

Removing formatting options from stylelint config.

---

graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchJobIdentifier.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/jobs/SearchJobState.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/jobs/SearchJobStateService.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/jobs/SearchJobStatus.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/jobs/SearchJobType.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/jobs/periodical/SearchJobStateCleanupPeriodical.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/jobs/SearchJobStateServiceTest.java

Initial version of SearchJobState object to be stored in MongoDB.
A new service with most important CRUD methods.
A new periodical to remove and expired old/outdated jobs.
/nocl
See https://github.com/Graylog2/graylog-plugin-enterprise/issues/9312
and https://github.com/Graylog2/graylog-plugin-enterprise/issues/9312
With new unit tests and manually.

Search job state storage for Data Lake Preview queries

---

graylog2-web-interface/src/components/bootstrap/Well.md
graylog2-web-interface/src/components/bootstrap/Well.tsx
graylog2-web-interface/src/components/configurationforms/ConfigurationWell.tsx
graylog2-web-interface/src/components/inputs/InputListItem.tsx
graylog2-web-interface/src/stores/inputs/InputTypesStore.ts
graylog2-web-interface/src/theme/GlobalThemeStyles.ts

This PR is migrating the `Well` component from bootstrap to Mantine.

Migrating `Well` component from bootstrap to Mantine.

---

graylog2-web-interface/src/components/datanode/ClusterManagement/ClusterManagementTeaserSearch.tsx
graylog2-web-interface/src/components/datanode/ClusterManagement/sample-dashboards/overview_search.json
graylog2-web-interface/src/components/security/pages/Anomalies.tsx
graylog2-web-interface/src/components/security/pages/HostActivity.tsx
graylog2-web-interface/src/components/security/pages/NetworkActivity.tsx
graylog2-web-interface/src/components/security/pages/Overview.tsx
graylog2-web-interface/src/components/security/pages/UserActivity.tsx
graylog2-web-interface/src/components/security/teaser/sample-dashboards/anomalies_search.json
graylog2-web-interface/src/components/security/teaser/sample-dashboards/host_activity_search.json
graylog2-web-interface/src/components/security/teaser/sample-dashboards/network_activity_search.json
graylog2-web-interface/src/components/security/teaser/sample-dashboards/overview_search.json
graylog2-web-interface/src/components/security/teaser/sample-dashboards/user_activity_search.json
graylog2-web-interface/src/views/components/visualizations/__tests__/XYPlot.test.tsx
graylog2-web-interface/src/views/logic/queries/Query.ts
graylog2-web-interface/src/views/logic/queries/SearchType.ts

This PR improves the TypeScript typing in the `Query` class by getting rid of must `any` usages.
/nocl

Reduce usage of `any` type in `Query` class.

---

graylog2-web-interface/src/components/inputs/InputThroughput.test.tsx
graylog2-web-interface/src/components/inputs/InputThroughput.tsx

This PR is fixing with an event handler that had no proper scope for `this`, therefore failing to expand the input's metrics details.
Fixes https://github.com/Graylog2/graylog2-server/issues/21682
/nocl Fixing unreleased change.

Fixing event handler in input metrics details component.

---

changelog/unreleased/issue-21408.toml
graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java
graylog2-server/src/main/java/org/graylog2/plugin/Message.java
graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java
graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/TimeStampConfig.java
graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerIT.java
graylog2-server/src/test/java/org/graylog2/plugin/MessageTest.java
graylog2-server/src/test/java/org/graylog2/shared/buffers/processors/MessageTimestampTest.java
graylog2-server/src/test/resources/org/graylog2/indexer/expected_template7.json
graylog2-web-interface/src/components/configurations/ConfigurationTypes.ts
graylog2-web-interface/src/components/configurations/MessageProcessorsConfig.test.tsx
graylog2-web-interface/src/components/configurations/MessageProcessorsConfig.tsx
graylog2-web-interface/src/components/configurations/message-processors/GlobalProcessingView.tsx
graylog2-web-interface/src/components/configurations/message-processors/MessageProcessorStatusFormGroup.tsx
graylog2-web-interface/src/components/configurations/message-processors/ProcessingConfigModalForm.test.tsx
graylog2-web-interface/src/components/configurations/message-processors/ProcessingConfigModalForm.tsx
graylog2-web-interface/src/components/configurations/message-processors/Types.ts

Backport Normalize timestamps in ingested messages to current time if in the future 

---

graylog2-web-interface/src/components/common/EntityFilters/EntityFilters.test.tsx
graylog2-web-interface/src/components/common/EntityFilters/FilterConfiguration/DateRangeForm.tsx
graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/AbsoluteCalendar.tsx
graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/DateTimePicker.tsx

This PR is improving the date/time picker for time range filters in the paginated data table by replacing the plain string input with the component that we are using for absolute time ranges in search as well.
Fixes #21489.
/nocl Improving an unreleased feature.
Before:
After:

Improving date/time picker for time range filters in paginated data table.

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/jobs/SearchJobStateService.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/jobs/SearchJobStateServiceTest.java

Service method to change progress, for changing progress alone, or progress together with state and partial results.
/nocl
With new unit tests.

Service method to change progress

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchJobDTO.java

Progress in SearchJob.
/nocl
Needed to proceed with : https://github.com/Graylog2/graylog-plugin-enterprise/pull/9800

Progress in SearchJob

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/QueryResult.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/jobs/SearchJobStateService.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/jobs/periodical/SearchJobStateCleanupPeriodical.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/jobs/SearchJobStateServiceTest.java

Search Job cleaning improvements.
Modified when job is removed according to pitch (from 48h to 7 days).
Expiration removes results as well.
Already expired jobs are not expired once again.
/nocl
With modified unit tests.

Search Job cleaning improvements

---

graylog2-server/src/main/java/org/graylog2/rest/MoreMediaTypes.java

Add missing MediaType constant for `application/vnd.ms-excel`

---

graylog2-web-interface/src/views/components/widgets/SearchQueryExecutionInfoHelper.tsx
graylog2-web-interface/src/views/logic/QueryResult.ts
graylog2-web-interface/src/views/logic/queries/SearchType.ts
graylog2-web-interface/src/views/types.ts

This PR mainly creates a `SearchTypeResult` type which is a union type based on the values of the pluggable `SearchTypeResultTypes` type. 
/nocl

Create `SearchTypeResult` union type which reflects different search type result types.

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchJobDTO.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/remote/RemoteSearchJobsStatusInterface.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/remote/SearchJobsStatusResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/results/PaginableResults.java

Support of Search API status call with a selected page of results.
/nocl
Requited to support FE with a tool to chose selected part of the results with a status call - for a Data Lake preview needs.

Support of Search API status call with selected page of results

---

graylog2-web-interface/src/components/bootstrap/NavDropdown.tsx
graylog2-web-interface/src/components/navigation/MainNavbar.tsx
graylog2-web-interface/src/components/navigation/NavigationItem.tsx
graylog2-web-interface/src/components/navigation/NavigationLink.tsx

With this PR we are slightly improving the code related to navigation items (links and dropdowns), by 
- moving the code into a separate component
- creating helper functions for redundant logic
- restructuring the code to make it easier to read
/nocl

Create separate component for `NavigationItem`s to simplify code.

---

.github/workflows/dispatch-main-build.yml

This will give us snapshot builds for stable branches.
/nocl Infrastructure change

Dispatch main builds for stable branches

---

graylog2-web-interface/src/views/logic/slices/searchExecutionSlice.ts

Ensure that `cancelExecutedJob` in `searchExecutionSlice` returns a promise.
/nocl

Ensure that `cancelExecutedJob` in `searchExecutionSlice` returns a promise.

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchMetadataResource.java

Only , OS/ES searches use query parser to get search metadata.
Data Lake searches return empty metadata, this endpoint does not have a reason for them.
/nocl Fixing bug in non-released functionality.
Fix a bug found in th FE.
Manually.

Only , OS/ES searches use query parser to get search metadata

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/db/InMemorySearchJobService.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/db/SearchJobService.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/jobs/periodical/SearchJobStateCleanupOnStartup.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchJobDTO.java

/jpd Graylog2/graylog-plugin-enterprise#9810
/nocl

gl-server changes needed for DataLakeSearchJobService modifications

---

graylog2-server/src/main/java/org/graylog/events/search/EventsFilterBuilder.java
graylog2-server/src/main/java/org/graylog/events/search/EventsSearchService.java

This PR is extracting an `EventsFilterBuilder` class which builds a query string based on the properties of the events search parameters passed in. This is extracted from the `EventsSearchService` and allows reusing the code e.g. for working with security events.
/nocl Internal Refactoring.

Extracting class to build events search filters.

---

changelog/unreleased/pr-21811.toml
graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/MoreSearchAdapterOS2.java
graylog2-web-interface/src/components/common/PaginatedEntityTable/PaginatedEntityTable.tsx
graylog2-web-interface/src/components/common/PaginatedEntityTable/parseTimerangeFilter.ts
graylog2-web-interface/src/components/events/EventsEntityTable.tsx
graylog2-web-interface/src/components/events/EventsHistogram.tsx
graylog2-web-interface/src/components/events/fetchEvents.ts

This PR is making use of the newly introduced events histogram endpoint (#21750) to display a line chart of events/alerts over time on the alerts page:
The chart data depends on the filters configured. The default time range is six months. Zooming on the chart creates a timestamp filter or updates an existing one.

Adding alerts & events histogram to alerts page.

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/errors/SearchError.java

prior to this change a search error could not be deserialised because the type was passed on into deserialisation but is not a valid property. this PR removes the propagation of the type field.
/nocl

Remove visibility of type from deserialisation

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java
graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/MoreSearchAdapterOS2.java
graylog2-server/src/main/java/org/graylog/events/search/EventsSearchFilter.java
graylog2-server/src/main/java/org/graylog/events/search/MoreSearch.java
graylog2-server/src/main/java/org/graylog/events/search/MoreSearchAdapter.java
graylog2-web-interface/src/components/events/fetchEvents.ts

This is an extension to our backend `MoreSearch` service, by adding the option to provide "extra" filters which go beyond the basic data model of events. These can be used e.g. in plugins to search for more specific events.

Support extra filters in event search.

---

graylog2-web-interface/src/components/events/EventsHistogram.tsx
graylog2-web-interface/src/components/events/fetchEvents.ts

This PR allows customizing the fetcher method used for fetching alerts/events in the histogram widget. In addition, it exports the `parseFilters` function, which lends itself for reuse in a custom fetcher function.
/nocl WIP Feature.

Support custom fetcher method for events histogram widget.

---

graylog2-web-interface/src/@types/graylog-web-plugin/index.d.ts
graylog2-web-interface/src/components/inputs/InputSetupWizard/InputSetupWizard.StartInput.test.tsx
graylog2-web-interface/src/components/inputs/InputSetupWizard/Wizard.tsx
graylog2-web-interface/src/components/inputs/InputSetupWizard/constants.ts
graylog2-web-interface/src/components/inputs/InputSetupWizard/contexts/InputSetupWizardProvider.tsx
graylog2-web-interface/src/components/inputs/InputSetupWizard/contexts/InputSetupWizardStepsProvider.tsx
graylog2-web-interface/src/components/inputs/InputSetupWizard/helpers/stepHelper.test.ts
graylog2-web-interface/src/components/inputs/InputSetupWizard/helpers/stepHelper.ts
graylog2-web-interface/src/components/inputs/InputSetupWizard/hooks/useInputSetupWizardSteps.ts
graylog2-web-interface/src/components/inputs/InputSetupWizard/hooks/useInputSetupWizardStepsHelper.ts
graylog2-web-interface/src/components/inputs/InputSetupWizard/hooks/useSetupInputMutations.ts
graylog2-web-interface/src/components/inputs/InputSetupWizard/index.ts
graylog2-web-interface/src/components/inputs/InputSetupWizard/steps/SetupRoutingStep.tsx
graylog2-web-interface/src/components/inputs/InputSetupWizard/steps/StartInputStep.tsx
graylog2-web-interface/src/components/inputs/InputSetupWizard/steps/components/CreateStreamForm.tsx
graylog2-web-interface/src/components/inputs/InputSetupWizard/steps/components/ProgressMessage.tsx
graylog2-web-interface/src/components/inputs/InputSetupWizard/types.ts

/nocl
part of https://github.com/Graylog2/graylog-plugin-enterprise/issues/9556
part of https://github.com/Graylog2/graylog-plugin-enterprise/issues/9640
/jpd Graylog2/graylog-plugin-enterprise#9855

ISW - Add illuminate to start input step

---

data-node/src/main/java/org/graylog/datanode/commands/Datanode.java

The MongoDBModule now only contains the DBEntitiesCatalog which is unused by data node and can therefore be removed.
/nocl 
code cleanup
locally, integration tests

Remove unnecessary bindings for data node.

---

UPGRADING.md
changelog/unreleased/pr-21755.toml
graylog2-server/src/main/java/org/graylog/integrations/aws/resources/AWSResource.java
graylog2-server/src/main/java/org/graylog/integrations/aws/service/AWSService.java
graylog2-server/src/test/java/org/graylog/integrations/aws/service/AWSServiceTest.java
graylog2-web-interface/src/integrations/aws/cloudwatch/SidebarPermissions.jsx
graylog2-web-interface/src/integrations/aws/common/Routes.ts

Backport https://github.com/Graylog2/graylog2-server/pull/21755 to the `6.0` branch.

AWS Kinesis/Cloudwatch input: Refer to official docs site for permissions (6.0)

---

full-backend-tests/src/test/java/org/graylog2/inputs/InputCreationIT.java
graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config
graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/inputs/GelfInputApi.java
graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/inputs/Inputs.java

enable setup mode feature flag by default

---

changelog/unreleased/pr-21858.toml
graylog2-server/src/main/java/org/graylog/security/certutil/CaPersistenceService.java
graylog2-server/src/main/java/org/graylog/security/certutil/ca/CA.java
graylog2-server/src/main/java/org/graylog/security/certutil/ca/PemCaReader.java
graylog2-server/src/test/java/org/graylog/security/certutil/ca/CATest.java
graylog2-server/src/test/java/org/graylog/security/certutil/ca/PemCaReaderTest.java

Add sorting and validation for provided CA certificate chains
Backport for #21858

Backport 6.1: certificate chain validation

---

graylog2-server/src/main/java/org/graylog/events/search/EventsFilterBuilder.java

This PR is doing a minor fix to the events filter builder class, by including the query passed in the request object to be part of the generated query string as well.
/nocl Fixing unreleased code.

Including query in events filter builder.

---

graylog2-web-interface/src/components/inputs/CreateInputControl.tsx
graylog2-web-interface/src/logic/telemetry/Constants.ts

fix Graylog2/graylog-plugin-enterprise#9691
/nocl

Remove find more inputs link from Input button

---

graylog2-web-interface/src/components/events/Constants.ts
graylog2-web-interface/src/components/events/EventsEntityTable.tsx
graylog2-web-interface/src/components/events/EventsWidgets.tsx

This PR enables export for alerts & events widgets by providing a `events.metrics.actions` plugin hook that renders a component overlaying the top right of the widget.
/nocl WIP Feature

Enabling export for alerts & events histogram widget.

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/QueryEngine.java
graylog2-server/src/main/java/org/graylog2/Configuration.java
misc/graylog.conf

Separate executor for Data Lake jobs in QueryEngine.
/jpd Graylog2/graylog-plugin-enterprise#9952
/nocl
See https://github.com/Graylog2/graylog-plugin-enterprise/issues/9926, mainly final decision: https://github.com/Graylog2/graylog-plugin-enterprise/issues/9926#issuecomment-2713451481

Separate executor for Data Lake jobs in QueryEngine

---

graylog2-web-interface/src/views/components/searchbar/time-range-filter/TimeRangeFilter.tsx
graylog2-web-interface/src/views/components/searchbar/time-range-filter/TimeRangeFilterButtons.tsx

This PR adds flag to define if we should submit the search form after preset change
/nocl

Add flag to submit search form on time range preset 

---

graylog2-web-interface/src/components/inputs/InputDiagnosis/DiagnosisHelp.tsx
graylog2-web-interface/src/components/inputs/InputDiagnosis/DiagnosisMessageErrors.tsx
graylog2-web-interface/src/pages/InputDiagnosisPage.tsx

fix [#21946](https://github.com/Graylog2/graylog2-server/issues/21946)
For the errors, we moved the Tooltip to the title and kept the link to the search on the counts.
/nocl

ISW Input diagnosis page improvement

---

graylog2-web-interface/src/views/components/widgets/Widget.tsx
graylog2-web-interface/src/views/components/widgets/telemety.ts

This PR extracts some widget telemetry actions into a separate file to improve their reusability.
/nocl

Improve reusability of widget telemetry events.

---

graylog2-web-interface/src/components/inputs/InputSetupWizard/InputSetupWizard.StartInput.test.tsx
graylog2-web-interface/src/components/inputs/InputSetupWizard/steps/SetupRoutingStep.tsx
graylog2-web-interface/src/components/inputs/InputSetupWizard/steps/StartInputStep.tsx

part of https://github.com/Graylog2/graylog2-server/issues/21175
/nocl

ISW - Adjustments for e2e tests

---

graylog2-web-interface/src/pages/InputDiagnosisPage.tsx

This PR improves the grid layout but making sure the spacings are consistent as well as the height of the boxes.
/nocl

Improve grid layout of diagnosis page

---

graylog2-web-interface/src/components/configurations/UserConfig.tsx

/nocl
It's about creating tokens, not about using them :slightly_smiling_face:

It's not about using tokens, but about creating them.

---

graylog2-web-interface/src/components/inputs/InputSetupWizard/InputSetupWizard.SetupRouting.test.tsx
graylog2-web-interface/src/components/inputs/InputSetupWizard/steps/components/InputInUseAlert.tsx

/nocl
fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/10046

ISW - Update copy in already in use alert

---

graylog2-web-interface/src/pages/InputDiagnosisPage.tsx

/nocl
fixes https://github.com/Graylog2/graylog2-server/issues/22016

Input Diagnosis Page: Fix stream links not prefixed

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/Search.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/EngineBindings.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/QueryEngine.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/validation/DataLakeSearchValidator.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchMetadataResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/DataLakeSearchType.java

Replacing  `Warehouse` with `Lake`, adding a little bit more validation.
/jpd Graylog2/graylog-plugin-enterprise#10076
/nocl

Replacing  Warehouse with Lake, adding a little bit more validation

---

graylog2-web-interface/src/util/DocsHelper.ts

This PR implements a link to the data lake preview docs page.
/nocl

Extend docs helper with link for data lake preview page.

---

changelog/unreleased/issue-22004.toml
graylog2-web-interface/src/pages/DataNodeUpgradePage.tsx

fixes https://github.com/Graylog2/graylog2-server/issues/22004

Show the datanode upgrade list when we wait for a node to be upgraded

---

graylog2-web-interface/packages/graylog-web-plugin/package.json

This PR updates sawmill to version `2.0.24`. The version is just fixing a small typing issue.
/nocl

Update sawmill to version`2.0.24`.

---

graylog2-web-interface/src/components/common/Section/SectionComponent.tsx

This PR makes Col component which we use in markup as a styled component. That allows us to import it in a place where we use SectionComponent and style it according to our needs 
we need this change to finish [10079](https://github.com/Graylog2/graylog-plugin-enterprise/pull/10079)
/nocl

Add Col as a styled component to be able styled it on usage

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/validation/DataLakeSearchValidator.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/engine/validation/DataLakeSearchValidatorTest.java

Validation improvements. Unit tests.
/nocl

Validation improvements. Unit tests.

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/validation/DataLakeSearchValidator.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/engine/validation/DataLakeSearchValidatorTest.java

More checks, minor refactoring, comments corrections.
/nocl

More checks, minor refactoring, comments corrections

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchJob.java

Possibly fixes https://github.com/Graylog2/graylog2-server/issues/22084
/nocl

Fixing cancellation flag on search job execution field

---

graylog2-web-interface/src/routing/AppRouter.tsx

fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/10132
/nocl

Fix Input Diagnosis page not working on cloud

---

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/PipelineResource.java
graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java
graylog2-server/src/main/java/org/graylog2/migrations/V20250327120900_RenameDefaultPipeline.java
graylog2-server/src/test/java/org/graylog2/contentpacks/facades/PipelineFacadeTest.java
graylog2-server/src/test/java/org/graylog2/inputs/routing/InputRoutingServiceTest.java
graylog2-server/src/test/resources/org/graylog2/contentpacks/facades/PipelineFacadeTest/pipelines.json

/nocl
Resolves #22145
- Change the pipeline name when creating a new pipeline or interacting with the routing pipeline
- Migrate an existing "All Messages Routing" pipeline 
See linked issue

Rename default routing pipeline

---

changelog/unreleased/pr-22088.toml

add changelog for https://github.com/Graylog2/graylog2-server/pull/22088

add changelog for PR 22088

---

changelog/unreleased/issue-22152.toml
graylog2-web-interface/src/pages/LoggedInPage.tsx
graylog2-web-interface/src/routing/SuggestReloadIfVersionChanged.test.tsx
graylog2-web-interface/src/routing/SuggestReloadIfVersionChanged.tsx
graylog2-web-interface/src/routing/useServerVersion.ts
graylog2-web-interface/src/stores/sessions/ServerAvailabilityStore.ts

This PR is implementing monitoring of the version of the Graylog server the frontend is running against and warns the user if the version has changed, suggesting a reload of the page.
Fixes #22152.
Fixes #5588.
A [caddy](https://github.com/caddyserver/caddy) was used to proxy between the frontend and the server, with the following config:
```
:2016
handle_path /* {
respond /api/ 200 {
body <<RESPONSE
{
"cluster_id":"43fdbc38-37fe-442c-94e7-d51782632fc7",
"node_id":"3b37ead8-ff96-4af3-a1e1-97b07d8241c1",
"version":"6.2.0-SNAPSHOT",
"tagline":"Manage your logs in the dark and have lasers going and make it look like you're from space!"
}
RESPONSE
}
reverse_proxy localhost:9000 {
header_up X-Graylog-Server-URL http://localhost:2016/ 
}
}
```
The server was started with `caddy run -w`, so it …

Suggest a reload when Graylog server version changed.

---

graylog2-web-interface/src/components/common/Section.test.tsx
graylog2-web-interface/src/components/common/Section.tsx
graylog2-web-interface/src/components/common/StatusColorIndicator.tsx
graylog2-web-interface/src/components/inputs/InputDiagnosis/Constants.ts
graylog2-web-interface/src/components/inputs/InputDiagnosis/DiagnosisHelp.tsx
graylog2-web-interface/src/components/inputs/InputDiagnosis/DiagnosisMessageErrors.tsx
graylog2-web-interface/src/pages/InputDiagnosisPage.test.tsx
graylog2-web-interface/src/pages/InputDiagnosisPage.tsx

Closes https://github.com/Graylog2/graylog-plugin-enterprise/issues/10172
/nocl

ISW - UI improvements

---

changelog/unreleased/issue-21726.toml
graylog2-server/src/main/java/org/graylog/events/processor/aggregation/PivotAggregationSearch.java
graylog2-server/src/test/java/org/graylog/events/processor/aggregation/PivotAggregationSearchTest.java

Backport https://github.com/Graylog2/graylog2-server/pull/22100 to `6.1`.

Add support for Search Filters in Aggregation events (6.1)

---

changelog/unreleased/issue-21726.toml
graylog2-server/src/main/java/org/graylog/events/processor/aggregation/PivotAggregationSearch.java
graylog2-server/src/test/java/org/graylog/events/processor/aggregation/PivotAggregationSearchTest.java

Backport https://github.com/Graylog2/graylog2-server/pull/22100 to `6.0`.

Add support for Search Filters in Aggregation events (6.0)

---

changelog/unreleased/pr-22117.toml
graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config

Enabling the feature flag for the Enterprise Feature.

Enabling the feature flag for the data lake preview

---

.github/dependabot.yml

Fix dependabot ignore rule for Lucene dependency

---

graylog2-web-interface/src/util/DocsHelper.ts

This PR adds a link to the search filters documentation
fix: https://github.com/Graylog2/graylog2-server/issues/16824
/nocl

Fix search filters documentation link

---

graylog2-web-interface/src/components/users/CreateTokenForm.tsx

fix Graylog2/graylog-plugin-enterprise#10350
/nocl

Add token ttl field examples

---

graylog2-server/src/test/java/org/graylog/testing/completebackend/MavenProjectDirProviderWithFrontend.java

Prior to this PR, the provider created/used for FE tests used the same ID than the regular one. By doing so, tests went missing.
/nocl because it's IT tests and not customer facing functionality
manual testing with debugger

ContainerMatrixTests: fix provider ID

---

full-backend-tests/pom.xml
full-backend-tests/src/test/java/org/graylog2/web/customization/CustomizationConfigIT.java
full-backend-tests/src/test/resources/org/graylog2/web/customization/invalid-customization-config.json
full-backend-tests/src/test/resources/org/graylog2/web/customization/valid-customization-config.json
graylog2-server/src/test/java/org/graylog/testing/completebackend/ContainerizedGraylogBackend.java
graylog2-server/src/test/java/org/graylog/testing/completebackend/GraylogBackend.java
graylog2-server/src/test/java/org/graylog/testing/completebackend/RunningGraylogBackend.java
graylog2-server/src/test/java/org/graylog/testing/mongodb/MongoDBInstance.java
pom.xml

This PR is fixing up the `CustomizationConfigIT` by:
- Fixing annotation so it actually runs
- Use GraalVM's JS interpreter to validate returned response
- Make sure that `cluster_config` collection is dropped between runs to avoid index collisions
Due to the endpoint for `/config.js` not returning plain JSON but JavaScript, we need to utilize the GraalVM JS engine to evaluate the response in order to make assertions (and ensure that it is correct JavaScript).

Finishing test suite that is validating correctness of `/config.js` returned.

---

graylog2-server/src/main/java/org/graylog2/web/ProductionIndexHtmlGenerator.java
graylog2-server/src/main/java/org/graylog2/web/customization/Config.java
graylog2-server/src/main/java/org/graylog2/web/customization/CustomizationConfigProvider.java

This PR is using the customization config to adjust the title of the generated HTML for the web interface.
/nocl WIP Feature

Customizing initial title of generated HTML.

---

graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config

Feature flag added, to hide Trino-related implementation during development.
/nocl

Feature flag added

---

full-backend-tests/src/test/java/org/graylog2/web/customization/CustomizationConfigIT.java

Disabling the test until the reason is found/fixed.
/nocl

Disabling CustomizationConfigIT because of errors

---

full-backend-tests/src/test/java/org/graylog2/web/customization/CustomizationConfigIT.java
graylog2-server/src/main/java/org/graylog2/shared/bindings/RestApiBindings.java
graylog2-server/src/main/java/org/graylog2/web/customization/ConfigProvider.java
graylog2-server/src/main/java/org/graylog2/web/customization/CustomizationConfig.java

This PR is fixing and reenabling the `CustomizationConfigIT` test.

Fix and reenable `CustomizationConfigIT`.

---

graylog2-server/src/main/resources/log4j2.xml

Filtering an error message that has no relevance in the DataLake context as we want to cancel/abort and the Exception is fine but the warning clutters up the log.
fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/10360
/nocl unreleased feature

Filter iceberg log message that has no relevance

---

graylog2-web-interface/src/components/login/LoginChrome.tsx

This PR is making use of the customization config to change the background and the logo image of the login page.
/nocl WIP Feature.

Utilize customization config to adjust login page.

---

graylog2-server/src/main/java/org/graylog2/plugin/DocsHelper.java

**Note:** This needs a backport to `6.2`.
This PR is removing the version from docs links generated in the backend.

Removing version from docs links generated from backend.

---

graylog2-web-interface/src/theme/types.ts

This PR is fixing theming types in the frontend by:
- Renaming `types.d.ts` to `types.ts` to enable type checking
- Fix types used in file
/nocl Internal refactoring

Fix theming types in frontend.

---

graylog2-web-interface/src/views/components/visualizations/number/Trend.tsx

This PR is fixing a warning from `styled-components` about an unknown `trend` prop being passed to a DOM element.

Fix warning about unknown `trend` prop in `Trend` component.

---

UPGRADING.md

Rotate UPGRADING.md for Graylog 6.3

---

graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionSummary.tsx

Closes #22427
Fixes the summary page for event definition being broken by #22297 .
/nocl

Fix default value for props

---

graylog2-web-interface/src/brand-customization/useNavigationCustomization.ts
graylog2-web-interface/src/components/bootstrap/NavDropdown.tsx
graylog2-web-interface/src/components/navigation/HelpMenu.tsx
graylog2-web-interface/src/components/navigation/NavIcon.tsx
graylog2-web-interface/src/components/navigation/Navigation.tsx
graylog2-web-interface/src/components/navigation/ScratchpadToggle.tsx
graylog2-web-interface/src/components/navigation/UserMenu.tsx
graylog2-web-interface/src/util/AppConfig.ts

With this PR we are utilizing the customization config to change the icons in the navigation.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/10505
/nocl

Utilize customization config to adjust navigation.

---

graylog2-web-interface/src/components/authentication/AuthenticatorsEdit/HTTPHeaderAuthConfigSection.tsx
graylog2-web-interface/src/components/authentication/directoryServices/activeDirectory/BackendCreate.tsx
graylog2-web-interface/src/components/authentication/directoryServices/activeDirectory/WizardPageHeader.tsx
graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendCreate.tsx
graylog2-web-interface/src/components/authentication/directoryServices/ldap/WizardPageHeader.tsx
graylog2-web-interface/src/pages/AuthenticationBackendDetailsPage.tsx
graylog2-web-interface/src/pages/AuthenticationCreatePage.tsx
graylog2-web-interface/src/pages/AuthenticationOverviewPage.tsx
graylog2-web-interface/src/pages/AuthenticationPage.tsx

This is a follow-up for https://github.com/Graylog2/graylog2-server/pull/22284. Please have a look at this PR for more information.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/10347
/nocl

Generalise descriptions in authentication components

---

graylog2-web-interface/src/brand-customization/useFooterCustomization.ts
graylog2-web-interface/src/components/layout/PageContentLayout.tsx

This PR adds an option to hide footer by using flag from collection 
fix: https://github.com/Graylog2/graylog-plugin-enterprise/issues/10489
/nocl

Add footer customization

---

graylog2-server/src/main/java/org/graylog2/web/customization/Config.java
graylog2-web-interface/src/brand-customization/useResourceCustomization.ts
graylog2-web-interface/src/components/support/MarketplaceLink.tsx
graylog2-web-interface/src/pages/ContentPacksPage.tsx
graylog2-web-interface/src/pages/CreateContentPackPage.tsx
graylog2-web-interface/src/pages/EditContentPackPage.tsx
graylog2-web-interface/src/pages/ExportExtractorsPage.tsx
graylog2-web-interface/src/pages/ImportExtractorsPage.tsx
graylog2-web-interface/src/pages/ShowContentPackPage.tsx
graylog2-web-interface/src/pages/StreamOutputsPage.tsx
graylog2-web-interface/src/pages/SystemOutputsPage.tsx
graylog2-web-interface/src/util/AppConfig.ts

This PR:
- Adds new branding resource item
-  Replace mentions of the Graylog marketplace with Marketplace component. This component helps to track if we should show link or not depend on branding settings
fix: https://github.com/Graylog2/graylog-plugin-enterprise/issues/10500
/nocl

Add marketplace brand resource

---

changelog/unreleased/pr-22426.toml
full-backend-tests/src/test/java/org/graylog/plugins/views/aggregations/SearchAggregationsIT.java
graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/ESPivot.java
graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/pivot/OSPivot.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/export/ExportTabularResultResponse.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/PivotResult.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/export/response/ExportTabularResultResponseTest.java
graylog2-server/src/test/resources/org/graylog/plugins/views/search/rest/export/response/sample_pivot_result.json

Add missing column names on tabular export of widgets (CSV etc.)
TODO: if the solution is sound, it needs to be ported to `ESPivot`, also better tests
fixes #22074

Adding field names as column names on CSV export

---

graylog2-server/src/main/java/org/graylog2/web/customization/Config.java

This PR is making sure that the customization config just skips entries in nested structures when they are empty.
/nocl

Cleanup customization config for nested structures.

---

graylog2-server/src/main/java/org/graylog2/migrations/V20190705071400_AddEventIndexSetsMigration.java

This PR is removing the product name from events streams & index sets.

Removing product name from events streams & index sets.

---

graylog2-web-interface/src/pages/RuleDetailsPage.tsx

The logic for the loading state on rules details page was not correct after replacing the pipelines store with a query. This caused E2E tests to fail.
/nocl bug related to unreleased change

Correctly set loading state on rule details page

---

graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java
graylog2-server/src/main/java/org/graylog2/configuration/HttpConfiguration.java
graylog2-server/src/main/java/org/graylog2/jersey/PrefixAddingModelProcessor.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/CookieFactory.java
graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java
graylog2-server/src/main/java/org/graylog2/shared/plugins/ContextClassLoaderSwitcher.java
graylog2-server/src/main/java/org/graylog2/shared/plugins/LoggingClassLoader.java
graylog2-server/src/main/java/org/graylog2/shared/rest/NonApiResource.java
graylog2-server/src/main/java/org/graylog2/shared/rest/SkipCSRFProtection.java
graylog2-server/src/main/java/org/graylog2/shared/rest/VerboseCsrfProtectionFilter.java
graylog2-server/src/main/java/org/graylog2/web/resources/AppConfigResource.java
graylog2-server/src/main/java/org/graylog2/web/resources/WebInterfaceAssetsResource.java
graylog2-server/src/test/java/org/graylog2/jersey/PrefixAddingModelProcessorTest.java
graylog2-web-interface/src/@types/graylog-web-plugin/index.d.ts
graylog2-web-interface/src/components/configurationforms/types.ts
graylog2-web-interface/src/pages/LoginPage.tsx
graylog2-web-interface/webpack.vendor.ts

This PR collects a few changes that we need to implement a SAML authentication backend.
Please check the individual commits.
/nocl Internal refactoring and improvement

Improve authentication infrastructure

---

graylog2-web-interface/src/integrations/aws/cloudwatch/CloudWatch.tsx

This is a small cleanup to remove the `.js` file extension from imports.
/nocl

Remove not needed extension from imports.

---

graylog2-web-interface/src/aws/components/AWSPluginConfiguration.tsx
graylog2-web-interface/src/logic/telemetry/TelemetryInfoText.tsx

This PR is just removing two not needed dollar signs in text.
/nocl

Remove not needed usage of `$` in JSX.

---

pom.xml

Release notes:
- https://netty.io/news/2025/04/23/4-1-120-Final.html
- https://netty.io/news/2025/04/24/4-1-121-Final.html
/nocl

Update to Netty 4.1.121

---

graylog2-server/src/main/java/org/graylog2/security/AccessTokenServiceImpl.java
graylog2-server/src/test/java/org/graylog2/security/AccessTokenServiceImplTest.java
graylog2-server/src/test/resources/org/graylog2/security/findOrphanedTokens_twoOrphanedWithAdmin.json

removes admin tokens from list of orphaned tokens
/jpd https://github.com/Graylog2/graylog-plugin-enterprise/pull/10620
/nocl fix for unreleased change
fixes #22529 
manually

fix removal of admin tokens

---

graylog2-web-interface/src/util/DocsHelper.ts

- Adds urls for Data Tiering docs (no issue)
/nocl

Add url for data tiering docs

---

graylog2-server/src/main/java/org/graylog2/lookup/adapters/CSVFileDataAdapter.java
graylog2-web-interface/src/pages/SidecarsPage.tsx

This PR is removing unneeded mentions of product name in the codebase:
- Use better default for CSV data adapter file name
- Use actual name of sidecar user when generating link to it

Fixing minor unneeded mentions of product names.

---

graylog2-server/src/test/java/org/graylog/plugins/views/search/jobs/SearchJobStateServiceTest.java

Improvement of flaky test

---

graylog2-server/src/test/java/org/graylog/plugins/views/search/jobs/SearchJobStateServiceTest.java

Removing update time check

---

graylog2-web-interface/src/components/inputs/InputForm.tsx

This PR is fixing fallout from #22559, where a wrong default value for a prop lead to the title input not being shown by default in the input form.
/nocl Fixing an unreleased change.

Restore missing title input in input creation form.

---

changelog/unreleased/pr-22571.toml
graylog2-web-interface/src/integrations/event-notifications/event-notification-types/TeamsNotificationV2Form.tsx

Note: This is a backport of https://github.com/Graylog2/graylog2-server/pull/22571 to `6.1`.
Set the default schema version of the `Microsoft Teams Notification V2` AdaptiveCard to the most recent supported version 1.5. 1.6 is not currently fully supported in Teams.
A user pointed out that schema version 1.6 AdaptiveCard was not being displayed properly in their Teams messages. Reverting the schema version to 1.5 resolved the issue. After investigation, [Microsoft Teams currently supports schema version 1.5](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#adaptive-card) fully so this change is to allow new notifications to work out of the box.

Default to AdaptiveCard Schema v1.5 in TeamsNotificationV2 (`6.1`)

---

UPGRADING.md

I added the text for the introduction of a report creator role to Upgrading.md as it's a breaking change.
see: https://github.com/Graylog2/graylog-plugin-enterprise/pull/10344
/nocl because it's in the changelog for the enterprise PR
- [] New feature (non-breaking change which adds functionality)

Adding change with report creator role to upgrading doc

---

changelog/unreleased/issue-enterprise-9163.toml
graylog2-server/src/main/java/org/graylog/events/procedures/Link.java

Adds Link type Action Event Procedure step that the front end expects.
/nocl - Updated in Enterprise PR
Front end expects a Link type action step but this had not yet been implemented in the backend.
Locally un dev environment.

Add link event procedure step to backend

---

graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionForm.tsx

fix Graylog2/graylog-plugin-enterprise#10713
/nocl

Error when changing step when editing Event Definition

---

graylog2-server/src/main/java/org/graylog/security/BuiltinCapabilities.java
graylog2-server/src/main/java/org/graylog/security/CapabilityPermissions.java
graylog2-server/src/main/java/org/graylog/security/DefaultBuiltinCapabilities.java
graylog2-server/src/main/java/org/graylog/security/SecurityModule.java
graylog2-server/src/main/java/org/graylog/security/shares/EntitySharesService.java
graylog2-server/src/test/java/org/graylog/security/entities/EntityDependencyPermissionCheckerTest.java
graylog2-server/src/test/java/org/graylog/security/shares/EntitySharesServiceTest.java

The enterprise module has to be able to add capabilities in the permission system, this change is preparatory.
see the linked enterprise dependency for more info about the changes in the enterprise module - see: 
/jpd https://github.com/Graylog2/graylog-plugin-enterprise/pull/10744
/nocl because it's the internal permission system and no change for users

Refactoring of capabilities

---

data-node/src/main/java/org/graylog/datanode/opensearch/cli/OpensearchCommandLineProcess.java

Now that we explicitly set `OPENSEARCH_JAVA_HOME`, we can use this for setting OS' jdk on Mac in development instead of symlinking.
/nocl refactoring for development only
start Datanode in IntelliJ on Mac

Datanode (development): Set OPENSEARCH_JAVA_HOME to system jdk

---

graylog2-web-interface/src/components/gcs/GCSSetupInfo.tsx
graylog2-web-interface/src/components/maps/configurations/GeoIpResolverConfig.tsx

- Add GCS Setup info implemented in https://github.com/Graylog2/graylog-plugin-enterprise/pull/10708 to Geo ip config form
Part of https://github.com/Graylog2/graylog-plugin-enterprise/issues/10697
/nocl

Add gcs info to geo ip config

---

graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/views/export/OpenSearchExportBackendIT.java

This PR is disabling the `OpenSearchExportBackendIT` due to its recent
flakiness.

Disabling `OpenSearchExportBackendIT` due to recent flakiness.

---

graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/ServerConfigStep.tsx

fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/7252
/nocl

Make System User DN a required field

---

changelog/unreleased/pr-22470.toml
graylog2-web-interface/src/views/components/visualizations/utils/__tests__/fixtures.ts
graylog2-web-interface/src/views/components/visualizations/utils/__tests__/unitConverters.test.ts
graylog2-web-interface/src/views/components/visualizations/utils/chartLayoutGenerators.ts
graylog2-web-interface/src/views/components/visualizations/utils/formatValueWithUnitLabel.ts
graylog2-web-interface/src/views/components/visualizations/utils/unitConverters.ts

This PR rounds the y-axis values on widget charts. From now for values less than 10, we do integer ceil round. For the values more then 10 we ceil to the nearest 5 multiplier (14-> 15,  17->20 etc) 
BEFORE
AFTER
fix: https://github.com/Graylog2/graylog-plugin-enterprise/issues/8898

Round chart label values

---

graylog2-web-interface/src/components/events/EventsPageNavigation.tsx

Hide the Event Procedures tab behind `event_procedures:read` permission
/nocl

Hide tab if permission is missing

---

graylog2-web-interface/src/threatintel/components/ThreatIntelPluginConfig.tsx

fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/10785
/nocl

make Threat Intelligence Lookup Modal closable

---

graylog2-web-interface/src/integrations/aws/context/AdvancedOptions.tsx
graylog2-web-interface/src/integrations/aws/context/Api.tsx
graylog2-web-interface/src/integrations/aws/context/FormData.tsx
graylog2-web-interface/src/integrations/aws/context/Sidebar.tsx
graylog2-web-interface/src/integrations/aws/context/Steps.tsx

There were a few cases were we should memorize the React context value.
/nocl

Memorize React context values.

---

UPGRADING.md

Add upgrade notes about custom MongoDB collection interface

---

graylog2-web-interface/src/components/bootstrap/Badge.tsx
graylog2-web-interface/src/components/bootstrap/FormGroup.tsx
graylog2-web-interface/src/components/bootstrap/ListGroupItem.tsx
graylog2-web-interface/src/components/common/CopyToClipboardCapture.tsx
graylog2-web-interface/src/components/common/CountBadge.tsx
graylog2-web-interface/src/components/common/IconButton.tsx
graylog2-web-interface/src/components/common/OverlayTrigger.tsx
graylog2-web-interface/src/components/common/SortableList/ListItem.tsx
graylog2-web-interface/src/components/configurationforms/ConfigurationForm.tsx
graylog2-web-interface/src/components/extractors/extractors_configuration/RegexExtractorConfiguration.tsx
graylog2-web-interface/src/components/nodes/InputTypesDataTable.tsx
graylog2-web-interface/src/preflight/components/common/Button.tsx
graylog2-web-interface/src/views/components/NewWidgetPlaceholder.tsx
graylog2-web-interface/src/views/components/WidgetContainer.tsx
graylog2-web-interface/src/views/components/aggregationwizard/ElementConfigurationContainer.tsx
graylog2-web-interface/src/views/components/searchbar/SaveViewButton.tsx
graylog2-web-interface/src/views/components/searchbar/ViewsQueryInput.tsx
graylog2-web-interface/src/views/components/sidebar/highlighting/ColorPreview.tsx
graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRule.tsx
graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRules.tsx

This PR is fixing ESLint hints related to missing default props in components which use `forwardRef`.
Please note, there are some ESLint hints in the changes files, which will be addressed in follow-up PRs.
/nocl

Fixing ESLint hints related to missing default props, mainly in components which use `forwardRef`.

---

graylog2-web-interface/src/components/common/Pluralize.tsx
graylog2-web-interface/src/components/event-definitions/event-definition-form/field-value-providers/LookupTableFieldValueProviderSummary.tsx
graylog2-web-interface/src/components/event-definitions/event-definition-form/field-value-providers/TemplateFieldValueProviderSummary.tsx
graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationSummary.tsx
graylog2-web-interface/src/components/extractors/extractors_configuration/CopyInputExtractorConfiguration.jsx
graylog2-web-interface/src/components/indexers/IndexerFailure.tsx
graylog2-web-interface/src/components/indexers/IndexerFailuresList.tsx
graylog2-web-interface/src/components/indices/IndexRangeSummary.tsx
graylog2-web-interface/src/components/indices/IndexSizeSummary.tsx
graylog2-web-interface/src/components/loggers/LoggingSubsystem.tsx
graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterDocumentation.jsx
graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterSummary.tsx
graylog2-web-interface/src/components/nodes/NodeListItem.tsx
graylog2-web-interface/src/components/nodes/NodeMaintenanceDropdown.tsx
graylog2-web-interface/src/components/systemmessages/SystemMessage.tsx
graylog2-web-interface/src/integrations/dataadapters/GreyNoiseAdapterDocumentation.jsx
graylog2-web-interface/src/threatintel/components/adapters/abusech/AbuseChRansomAdapterSummary.tsx
graylog2-web-interface/src/threatintel/components/adapters/otx/OTXAdapterDocumentation.jsx
graylog2-web-interface/src/threatintel/components/adapters/otx/OTXAdapterFieldSet.tsx
graylog2-web-interface/src/threatintel/components/adapters/otx/OTXAdapterSummary.tsx
graylog2-web-interface/src/threatintel/components/adapters/whois/WhoisAdapterFieldSet.tsx

This PR is fixing ESLint hints related to the `react/state-in-constructor` rule.
/nocl

Migrate simple react class components to functional components

---

graylog2-web-interface/src/components/cluster-configuration/useClusterNodes.ts

This PR is removing the unnecessary usage of the product name in node types on the cluster config page.
Fixes Graylog2/graylog-plugin-enterprise#10942.

Using neutral name for server nodes.

---

graylog2-web-interface/src/components/streams/StreamsOverview/StreamActions.tsx

fixes https://github.com/Graylog2/graylog2-server/issues/19948
/nocl

fix cloning a stream does not populate the form fields

---

graylog2-server/src/main/java/org/graylog/events/procedures/Action.java
graylog2-server/src/main/java/org/graylog/events/procedures/ActionDto.java
graylog2-server/src/test/java/org/graylog/events/procedures/EventProcedureStepTest.java

Decided that Action Title is redundant since steps already have a title and actions cannot exist outside of steps.
/nocl
/prd Graylog2/graylog-plugin-enterprise#11003

Remove step action title

---

graylog2-server/src/main/java/org/graylog2/contentpacks/model/ModelTypes.java

Add EventProcedureStep model type to support content pack export/import
/nocl
fix step imports in content packs

Add EventProcedureStep model type

---

graylog2-web-interface/src/components/grok-patterns/GrokPatternFilter.test.tsx
graylog2-web-interface/src/components/grok-patterns/GrokPatternInput.test.tsx
graylog2-web-interface/src/components/users/TokenList.test.tsx
graylog2-web-interface/src/components/users/TokenList.tsx

This PR is cleaning up some tests picked up along the way, mostly related to unnecessary `waitFor` usages and direct node access instead of using `userEvent`.

Minor test cleanups refactored along the way.

---

graylog2-web-interface/src/components/bootstrap/SplitButton.tsx

This change will improve testing 
/nocl

Add data test id prop to split button component

---

graylog2-server/src/main/java/org/graylog2/shared/users/UserService.java
graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java
graylog2-server/src/test/java/org/graylog/testing/TestUserService.java
graylog2-server/src/test/java/org/graylog2/users/UserServiceImplTest.java

Adds a method to look up a user by their external auth service user ID.
/nocl

Add method to load user by auth service uid

---

graylog2-web-interface/src/util/DocsHelper.ts

Placeholder to add later the url to event procedures docs
/nocl

fix: Added event procedures docs placeholder

---

graylog2-server/src/main/java/org/graylog/integrations/ipfix/IpfixParser.java
graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java
graylog2-server/src/test/java/org/graylog/security/entities/EntityDependencyResolverTest.java
graylog2-web-interface/src/routing/hooks/useShowRouteForEntity.ts
graylog2-web-interface/src/util/getTitleForEntityType.ts

Add Event Procedure and Event Procedure Step entity types
/nocl
adding Event Procedures to entity sharing model

Add event procedure and step entity types

---

graylog2-web-interface/src/components/login/LoginChrome.tsx

This PR makes sure that a custom background image does not contain unwanted SVG markup.
/nocl Extending unreleased functionality.

Sanitizing custom background SVG.

---

graylog2-web-interface/src/components/notifications/useNotificationDelete.ts

This PR is fixing a minor issue where system notifications without a key (they do not relate to a specific node/entity) cannot be dismissed.
Fixes #22891.
/nocl Fixes unreleased change.

Dismiss notifications without key properly.

---

graylog2-web-interface/src/components/configurations/UserConfig.tsx

fixes https://github.com/Graylog2/graylog2-server/issues/22017
/nocl

Fix misaligned users configuration details

---

changelog/unreleased/pr-22942.toml
graylog2-web-interface/src/components/common/MarkdownEditor/Preview.tsx
graylog2-web-interface/src/views/components/AsideElements.tsx
graylog2-web-interface/src/views/components/Search.tsx
graylog2-web-interface/src/views/types.ts

This PR is implementing support for pluggable "aside" elements, which can be used to e.g. implement a right sidebar on search/dashboard pages.

Support pluggable "aside" elements for searches/dashboards.

---

graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/AggregatedConnectionResponse.java

Use a standard hexadecimal tool in AggregatedConnectionResponse

---

graylog2-web-interface/src/components/maps/configurations/GeoIpResolverConfig.tsx

fixes https://github.com/Graylog2/graylog2-server/issues/22575
/nocl

make pull_from_cloud dropdown optional

---

graylog2-web-interface/src/components/maps/configurations/GeoIpResolverConfig.tsx

Backport 6.3 (https://github.com/Graylog2/graylog2-server/pull/23063)
/nocl

Backport 6.3 #23063

---

graylog2-web-interface/src/util/DocsHelper.ts

Updated event procedure docs url in docshelper
/nocl

fix(): Updated event procedures docs url

---

graylog2-server/src/main/java/org/graylog2/web/customization/Config.java
graylog2-web-interface/src/components/login/LoginChrome.tsx
graylog2-web-interface/src/util/AppConfig.ts

This PR is extending the customization config to allow disabling the logo on the login page, just showing the background in this case.
/nocl

Allow turning off logo on login page via customization config.

---

changelog/unreleased/issue-23172.toml
graylog2-server/src/main/java/org/graylog/plugins/views/search/db/SearchDbService.java

Replaces `SearchDbService.delete` method's `getById` call to `deleteById`.
Closes https://github.com/Graylog2/graylog2-server/issues/23172
Locally in dev environment.

Update SearchDbService.delete method to delete documents

---

graylog2-server/src/main/java/org/graylog2/web/customization/Config.java
graylog2-web-interface/src/components/login/LoginChrome.tsx
graylog2-web-interface/src/util/AppConfig.ts

**Note:** This is a backport of #23166 to `6.3`.
This PR is extending the customization config to allow disabling the logo on the login page, just showing the background in this case.
/nocl

Allow turning off logo on login page via customization config. (`6.3`)

---

graylog2-web-interface/packages/graylog-web-plugin/package.json
graylog2-web-interface/yarn.lock

This PR updates sawmill to version `2.0.28`.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/5137
/nocl - changelog is part of https://github.com/Graylog2/graylog-plugin-enterprise/pull/11340

Update sawmill to version `2.0.28`

---

graylog2-web-interface/src/components/bootstrap/HelpBlock.tsx
graylog2-web-interface/src/components/common/PageNavigation.tsx
graylog2-web-interface/src/components/streams/StreamsOverview/cells/TitleCell.tsx
graylog2-web-interface/src/theme/GlobalThemeStyles.ts

With this PR we replace custom text colors with our default text colors in a few cases.
/nocl

Small collection of text color improvements

---

graylog2-web-interface/packages/eslint-config-graylog/index.js

This PR is declaring the [utils module](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/migration-guides/v4.md#testing-libraryutils-module) for the testing-library eslint plugin. This is required to avoid re-exported utilities like `fireEvent` to be flagged as direct node access.

Declaring utils module for testing-library eslint plugin.

---

graylog2-web-interface/src/views/components/widgets/ExportWidgetAction/ExportWidgetActionDelegate.tsx
graylog2-web-interface/src/views/components/widgets/ExtraDropdownWidgetActions.test.tsx
graylog2-web-interface/src/views/components/widgets/ExtraDropdownWidgetActions.tsx
graylog2-web-interface/src/views/components/widgets/ExtraMenuWidgetActions.test.tsx
graylog2-web-interface/src/views/components/widgets/ExtraMenuWidgetActions.tsx
graylog2-web-interface/src/views/components/widgets/Types.ts
graylog2-web-interface/src/views/components/widgets/WidgetActionsMenu.tsx
graylog2-web-interface/src/views/components/widgets/useWidgetExportActionComponent.ts

This PR is extending the pluggable widget dropdown actions to support components (e.g. for modals) as well.
/nocl Internal extension.

Supporting components for pluggable widget dropdown actions.

---

changelog/unreleased/pr-23291.toml
graylog2-web-interface/src/components/loggers/useLoggers.ts
graylog2-web-interface/src/components/loggers/useSubsystems.ts

Update hooks to use the new TanStack query syntax.
fix Graylog2/graylog-plugin-enterprise#11431

Fix Logging section just shows a loading spinner

---

UPGRADING.md
graylog2-web-interface/packages/graylog-web-plugin/package.json
graylog2-web-interface/yarn.lock

This PR update the `@graylog/sawmill` package to version `4.0.0`.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/11515
/nocl - added with https://github.com/Graylog2/graylog-plugin-enterprise/pull/11516

Upgrade sawmill to version `4.0.0`.

---

graylog2-web-interface/src/util/DocsHelper.ts

Extend docs helper with link to data lake page.
/nocl.- no visible change

Extend docs helper with link to data lake page.

---

graylog2-web-interface/src/components/users/UserDetails/UserDetails.test.tsx
graylog2-web-interface/src/components/users/UserDetails/UserDetails.tsx
graylog2-web-interface/src/components/users/navigation/UserActionLinks.tsx
graylog2-web-interface/src/pages/UserDetailsPage.tsx
graylog2-web-interface/src/pages/UserEditPage.tsx
graylog2-web-interface/src/pages/UserTokensEditPage.tsx

Closes https://github.com/Graylog2/graylog2-server/issues/23383
Closes https://github.com/Graylog2/graylog-plugin-enterprise/issues/11589
/nocl

Refactor user details and edit permissions

---

changelog/unreleased/issue-23106.toml
graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministrationContainer.tsx

fixes https://github.com/Graylog2/graylog2-server/issues/23106
fixes https://github.com/Graylog2/graylog2-server/issues/23358

Fix Sidecar Administration Page Searchfield

---

changelog/unreleased/issue-4203.toml
graylog2-server/src/main/java/org/graylog2/lookup/adapters/CSVFileDataAdapter.java
graylog2-server/src/test/java/org/graylog2/lookup/adapters/CSVFileDataAdapterTest.java

Realized these changes were left out of the original changeset. 
fix multivalue CSV previews and lookups after a file refresh.
unit tests

Account for multivalue lookups in doRefresh and getPreview

---

pom.xml

Widen the forbiddenapis rule for "autovalue.shaded" imports

---

graylog2-server/src/test/java/org/graylog/testing/kafka/KafkaContainer.java
graylog2-server/src/test/java/org/graylog2/shared/buffers/processors/MessageTimestampTest.java

Please merge the PR with "rebase and merge" so we can keep the individual commits.
/nocl Fixing test issues

Fix several test issues in 6.2

---

graylog2-server/src/test/java/org/graylog/testing/kafka/KafkaContainer.java
graylog2-server/src/test/java/org/graylog2/shared/buffers/processors/MessageTimestampTest.java

Please merge the PR with "rebase and merge" so we can keep the individual commits.
/nocl Fixing test issues

Fix several test issues in 6.1

---

graylog2-server/src/main/java/org/graylog2/streams/StreamDTO.java

Merged the Scoped stream PR before fixing the ScopedEntity abstract class -> interface refactoring
/nocl

Fix StreamDTO ScopedEntity implementation

---

graylog2-web-interface/package.json
graylog2-web-interface/src/components/bootstrap/Menu.tsx
graylog2-web-interface/src/components/content-packs/ContentPackEntitiesList.tsx
graylog2-web-interface/src/views/components/AdaptableQueryTabs.test.tsx
graylog2-web-interface/src/views/components/DashboardSearchBar.test.tsx
graylog2-web-interface/src/views/components/common/ActionDropdown.test.tsx
graylog2-web-interface/src/views/components/searchbar/saved-search/SearchActionsMenu.test.tsx
graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/SaveTimeRangeAsPresetButton.test.tsx
graylog2-web-interface/src/views/components/widgets/ExportWidgetAction/ExportWidgetActionDelegate.test.tsx
graylog2-web-interface/src/views/components/widgets/Widget.aggregations.test.tsx
graylog2-web-interface/test/DefaultProviders.tsx
graylog2-web-interface/test/WrappingContainer.tsx
graylog2-web-interface/yarn.lock

This PR is updating to Mantine 8. It is based on a [dependabot PR](https://github.com/Graylog2/graylog2-server/pull/22497), please check this PR for the changelog/release notes.
The update required some changes to tests/components, namely:
- Using the `test` env for the `MantineThemeProvider` in test
- Fixing DOM validation errors:
- Moving modals within `tr` elements to the corresponding `td` elements (`ContentPackEntitiesList`)
- Suppressing error for nested forms in cases where the fix would be
too heavy (`DashboardSearchBar`/`ActionDropdown`/`Widget.aggregations`)
- Fixing usages of `waitForElementToBeRemoved` in cases where Mantine behavior has changed (removed elements are not visible before anymore)
/prd …

Updating to Mantine 8.

---

graylog2-web-interface/CONTRIBUTING.md

This PR is extending our best practices section in the contribution guide to reference testing-library guides.
/nocl Changing internal documentation only.
[skip ci]

Documenting/referencing best practices for `testing-library`.

---

graylog2-web-interface/src/components/common/EntityDataTable/BulkActionsRow.tsx

Small change to allow extending styles of `BulkActionsRow` component.
/nocl

Allow extending styles of `BulkActionsRow` component.

---

graylog2-web-interface/src/components/streams/StreamDetails/StreamDataRoutingProcessing.tsx

/nocl 
closes https://github.com/Graylog2/graylog-plugin-enterprise/issues/10654

Only show edit pipeline connections button for editable stream

---

graylog2-server/src/main/java/org/graylog2/users/UserImpl.java

This is a follow-up to #23552. This PR was breaking `User` deserialization for older instances of it, which had `startpage` set to `{}` (most probably because an existing start page setting had been removed), leading to a deserialization error during login.
/nocl Fixing unreleased change.

Fixing `User`/`Startpage` deserialization if start page is empty.

---

graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/GraylogApis.java
graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/Search.java

This PR is consolidating helpers in full backend tests related to waiting for messages to be ingested. Previously, different timeouts were used for different helpers, leading to potentially different behavior.

Consolidating message waiters in full backend tests.

---

changelog/unreleased/pr-23688.toml
graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config

set feature flag to `on` by default 
resolves https://github.com/Graylog2/graylog-plugin-enterprise/issues/11933
manually

Enable external_data_lake_search by default

---

graylog2-web-interface/src/components/bootstrap/ListGroupItem.tsx

Improve hover styles for ListGroupItem

---

graylog2-server/src/main/java/org/graylog/events/procedures/ActionConfig.java
graylog2-server/src/main/java/org/graylog/events/procedures/ExecuteNotification.java
graylog2-server/src/main/java/org/graylog/events/procedures/GoToDashboard.java
graylog2-server/src/main/java/org/graylog/events/procedures/Link.java
graylog2-server/src/main/java/org/graylog/events/procedures/PerformSearch.java

Add backend validation methods for `EventProcedureStep.AtionDto.ActionConfig`
/nocl enterprise CL will include this PR

Add validation methods for EventProcedureStep.Actions
