Graylog2/graylog2-server

graylog2-web-interface/src/components/perspectives/ActivePerspectiveBrand.tsx, graylog2-web-interface/src/components/perspectives/PerspectivesSwitcher.test.tsx, graylog2-web-interface/src/components/perspectives/PerspectivesSwitcher.tsx, graylog2-web-interface/src/components/perspectives/bindings.ts, graylog2-web-interface/src/components/perspectives/hooks/usePerspectives.test.tsx, graylog2-web-interface/src/components/perspectives/types.ts, graylog2-web-interface/src/routing/AppRouter.test.tsx
With this PR we are adding another attribute for perspective plugins called `brandLink`. It will be used for the link which wraps the perspective brand component. The user will also be redirected to the link target when selecting a perspective.
/jpd https://github.com/Graylog2/graylog-plugin-enterprise/pull/6194
/nocl
=> Implement brand link for perspectives.

changelog/unreleased/pr-17449.toml, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/OpenSearchClient.java
* Wrap ContentTooLongException into an BatchSizeTooLargeException
The dynamic batch size of archiving depends on catching these exceptions and then retrying the scroll query with a smaller batch size.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/3318
* Add changelog
(cherry picked from commit 32cf4375adcc794f953c027a4b7a44963b34159f)
=> Wrap ContentTooLongException into a BatchSizeTooLargeException (5.2)

changelog/unreleased/pr-17449.toml, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/OpenSearchClient.java
* Wrap ContentTooLongException into an BatchSizeTooLargeException
The dynamic batch size of archiving depends on catching these exceptions and then retrying the scroll query with a smaller batch size.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/3318
* Add changelog
(cherry picked from commit 32cf4375adcc794f953c027a4b7a44963b34159f)
=> Wrap ContentTooLongException into a BatchSizeTooLargeException (5.1)

changelog/unreleased/pr-17368.toml, changelog/unreleased/pr-17442.toml, graylog2-web-interface/src/theme/UseCurrentThemeMode.ts
With `5.2` we renamed the theme modes `teint` and `noir` to `dark` and `light`. With this change make sure read-only users do not face a problem when downgrading Graylog from `5.2` to a previous version.
To test this change, checkout the branch, open the web interface, login with the system admin user, configure e.g. `themeMode: "dark"` in the local storage.
=> Return default theme mode when theme mode in local storage does not match expected format (`5.0`).

graylog2-server/pom.xml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/parser/PipelineRuleParser.java, graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodical.java
Adjust `PipelineRuleParser` and `IndexFieldTypePollerPeriodical` to use an `IdentityHashMap` and `ConcurrentHashMap` instead of classes from mina-core.
Moving the `api-all` dependency to the "test" scope removes `mina-core` from the "compile" scope. The `IdentityHashSet` and `ConcurrentHashSet` classes from `mina-core` are basically small wrappers around `IdentityHashMap` and `ConcurrentHashMap`. It's not worth including the `mina-core` dependency just for those.
/nocl
=> Move org.apache.directory.api:api-all into test scope

graylog2-web-interface/src/components/PluggableStoreProvider.tsx, graylog2-web-interface/src/store.ts, graylog2-web-interface/src/views/components/Search.tsx, graylog2-web-interface/src/views/components/contexts/SearchExecutorsContext.tsx, graylog2-web-interface/src/views/components/contexts/useSearchExecutors.ts, graylog2-web-interface/src/views/components/widgets/reexecuteSearchTypes.ts, graylog2-web-interface/src/views/logic/aggregationbuilder/AggregationWidgetConfig.ts, graylog2-web-interface/src/views/logic/slices/searchExecutionSlice.ts, graylog2-web-interface/src/views/logic/slices/searchMetadataSlice.ts, graylog2-web-interface/src/views/pages/SearchPage.tsx, graylog2-web-interface/src/views/test/mockDispatch.ts, graylog2-web-interface/src/views/types.ts, graylog2-web-interface/src/views/viewsReducers.ts
This PR is extending the search store and actions in the following ways:
- Search parsing/execution can be customized using the `SearchExecutorsContext`
- The `PluggableStoreProvider` takes a static search result in its `result` prop
In combination, these changes allow reusing the search components with static result data and/or using different means to retrieve search results.
/nocl
=> Support passing static search results/customizing search execution.

graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ElasticsearchInstanceES7.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/OpenSearch13Instance.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/testing/DatanodeInstance.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/testing/OpenSearchInstance.java
Unlike Jenkins, Github Actions does not provide a BUILD_ID env variable. Using CI should work with both, since this was already used in BlockingBatchedESOutputTest.
/nocl
=> Switch "CI" detection to a common variable.

changelog/unreleased/pr-17477.toml, graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterMetricsResource.java
Workaround to fail fast with a 401 when an authenticated metrics request can't be forwarded properly because the auth token can't be extracted.
This is a band-aid to silence the log. It is kept simple to allow for easy backporting to versions `5.2` and `5.1`. I'm planning to implement a proper fix targeting version `6.0` in a separate PR.
Fixes spamming the server log file with warnings of the following kind:
```
2023-11-27 10:13:58,527 WARN : org.graylog2.shared.rest.resources.ProxiedResource - Failed to call API on node <c017185d-cc34-48a1-9e29-ac713d47470c>, cause: HTTP 401 Unauthorized (duration: 0 ms)
```
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/5971
Tested by following the steps to reproduce as documented …
=> Fail proxied metrics requests fast when auth info is missing

changelog/unreleased/issue-17430.toml, data-node/src/main/java/org/graylog/datanode/bootstrap/preflight/OpenSearchPreconditionsCheck.java
- Read the "max_map_count" from the /proc system instead of calling the /sbin/sysctl command
- Only run check on Linux operating systems (avoids warning on FreeBSD)
- Throw "PreflightCheckException" instead of "RuntimeException"
- Don't use "System.out.println()" for logging
- Enhance changelog entry to help users to understand the fix
Refs https://github.com/Graylog2/graylog2-server/pull/17436
**NOTE:** This needs a backport to the `5.2` branch.
=> Fix Data Node system parameters pre-flight check

changelog/unreleased/pr-17477.toml, graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterMetricsResource.java
Backport of #17477 
* Fail proxied metrics requests fast when auth info is missing
* Add changelog
(cherry picked from commit af4c9085b1f72ec77996b5117e06f9b85fcc2790)
=> Backport to 5.2: Fail proxied metrics requests fast when auth info is missing (#17477)

graylog2-web-interface/src/views/components/DashboardActionsMenu.test.tsx, graylog2-web-interface/src/views/components/DashboardActionsMenu.tsx, graylog2-web-interface/src/views/components/Search.tsx, graylog2-web-interface/src/views/components/contexts/SearchPageLayoutContext.tsx, graylog2-web-interface/src/views/components/contexts/SearchPageLayoutProvider.tsx, graylog2-web-interface/src/views/pages/EventDefinitionReplaySearchPage.tsx, graylog2-web-interface/src/views/pages/EventReplaySearchPage.tsx, graylog2-web-interface/src/views/pages/SearchPage.tsx, graylog2-web-interface/src/views/types.ts
With this refactoring we are now storing the `SearchAreaContainer` and `InfoBar` in the `SearchPageLayoutContext`, instead of passing them as props to the `Search` component.
/nocl
/jpd https://github.com/Graylog2/graylog-plugin-enterprise/pull/6197
=> Store `SearchAreaContainer` and `InfoBar` in `SearchPageLayoutContext`.

changelog/unreleased/issue-17430.toml, data-node/src/main/java/org/graylog/datanode/bootstrap/preflight/OpenSearchPreconditionsCheck.java
Backport from #17497 
- Read the "max_map_count" from the /proc system instead of calling the /sbin/sysctl command
- Only run check on Linux operating systems (avoids warning on FreeBSD)
- Throw "PreflightCheckException" instead of "RuntimeException"
- Don't use "System.out.println()" for logging
- Enhance changelog entry to help users to understand the fix
Refs https://github.com/Graylog2/graylog2-server/pull/17436
(cherry picked from commit 28f59c326f2ca50f1de03a23cf14119ba5fb49a2)
=> Fix Data Node system parameters pre-flight check (#17497)

changelog/unreleased/issue-13856.toml, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/validators/UnknownFieldsValidator.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/validation/validators/UnknownFieldsValidatorTest.java
Fixes #[13856](https://github.com/Graylog2/graylog2-server/issues/13856)
Query Validation never treats special GL fields as unknown.
See #[13856](https://github.com/Graylog2/graylog2-server/issues/13856)
Manually and with new unit test.
=> Query Validation never treats special GL fields as unknown

changelog/unreleased/pr-17435.toml, graylog2-server/src/main/java/org/graylog/events/processor/EventDefinitionHandler.java
* Fix saving of system notification event definition
On save, the UI is passing back the "scheduled=false" param from the context.
There's several ways we could fix this, but it's probably easiest to not throw an exception, but just ignore the unschedule call.
This probably got broken with #14502
* changelog
(cherry picked from commit d1b77ed1ec9bcce422114112797b39720e7a598d)
=> Fix saving of system notification event definition (5.2)

changelog/unreleased/pr-17435.toml, graylog2-server/src/main/java/org/graylog/events/processor/EventDefinitionHandler.java
On save, the UI is passing back the "scheduled=false" param from the context.
There's several ways we could fix this, but it's probably easiest to not throw an exception, but just ignore the unschedule call.
This probably got broken with #14502
cherry-picked from d1b77ed
=> Fix saving of system notification event definition (5.1)

UPGRADING.md, changelog/unreleased/pr-17552.toml, misc/graylog.conf
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/5888
Adding to #16927 we now also disable retention strategy `close` in example configuration to be used by new installations.
=> Disable retention strategy `close` for new installs

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ElasticsearchInstanceES7.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/OpenSearch13Instance.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/RunningElasticsearchInstanceES7.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/OpenSearchClient.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/OpenSearchExceptionTest.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/testing/OpenSearchInstance.java, graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchClientConfiguration.java
**Note:** This needs a backport to `5.2`.
This PR is adding settings for globally configuring max concurrent searches/shard requests for multi-search requests.
/nocl
=> Adding global settings for max concurrent searches/shard requests.

jenkins.groovy
We no longer use Jenkins to run builds for pull requests and
regular snapshots.
/nocl
=> Remove Jenkins build configuration

changelog/unreleased/pr-15682.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/ShannonEntropy.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/StringEntropy.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/strings/ShannonEntropyTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/stringEntropy.txt
Backport https://github.com/Graylog2/graylog2-server/pull/15682 to the `5.1` branch. 
Content that uses this function is being worked on in https://github.com/Graylog2/graylog-project-illuminate/issues/1676, and it would be helpful to include this function in 5.1 as well for backwards compatibility for those using that version.
=> Add string_entropy pipeline function (5.1)

graylog2-web-interface/src/components/bootstrap/Button.tsx, graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchForm.test.tsx
When migrating `Button` components over to Mantine, we broke displaying inline hover/tooltip-components in the button's caption when the button is disabled.
This PR is fixing this, by enabling pointer events when disabling the button.
/nocl
=> Enabling mouse events for disabled buttons.

graylog2-server/src/main/java/org/graylog/schema/EventFields.java
Fix incorrect name/order of `event_source_input` GIM schema field. It was erroneously named `event_input_source` (transposed last two words) before. 
/nocl
=> Fix incorrect name for event_source_input field

changelog/unreleased/pr-17611.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/arrays/ArrayContains.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/arrayContains.txt, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/with-arrays.json
Add support for JSON nodes in `array_contains` pipeline function. 
When array elements are selected from the `json_path` pipeline function, the array will include Jackson `JsonNode` elements containing the actual object values within. When passed to the `array_contains` pipeline function, the function will fail to detect that a string or number is present in the array due to the JSON objects. This fix includes support for the string, number, and boolean data types.
Well-covered with unit tests and manual testing was performed. See PR unit tests for examples.
=> Add handling for JSON arrays in array_contains function

full-backend-tests/src/test/java/org/graylog/testing/fullbackend/AutomaticLeaderElectionStartupIT.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/ContainerizedGraylogBackend.java, graylog2-server/src/test/java/org/graylog/testing/containermatrix/ContainerMatrixTestEngine.java, graylog2-server/src/test/java/org/graylog/testing/containermatrix/annotations/ContainerMatrixTestsConfiguration.java, graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerConfig.java, graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerFactory.java, graylog2-server/src/test/java/org/junit/jupiter/engine/descriptor/ContainerMatrixTestsDescriptor.java, graylog2-server/src/test/java/org/junit/jupiter/engine/descriptor/ContainerMatrixTestsDescriptorTest.java, graylog2-server/src/test/java/org/junit/platform/engine/support/hierarchical/ContainerMatrixHierarchicalTestEngine.java
Adds a `@ContainerMatrixTestsConfiguration.ConfigurationParameter` key-value array to the `@ContainerMatrixTestsConfiguration`
These values will override configuration parameters for the Graylog container started in full backend tests.
/nocl
Adds an `AutomaticLeaderElectionStartupIT` which uses this to start a Graylog with `leader_election_mode=automatic` to check if startup works since there were binding issues in this case from time to time.
=> allow generic overriding of config params in full backend tests

graylog2-server/src/main/java/org/graylog2/security/realm/HTTPHeaderAuthenticationRealm.java, graylog2-server/src/main/java/org/graylog2/shared/rest/resources/ProxiedResource.java, graylog2-server/src/main/java/org/graylog2/shared/security/PossibleTrustedHeaderToken.java, graylog2-server/src/main/java/org/graylog2/shared/security/ShiroSecurityContextFilter.java, graylog2-server/src/test/java/org/graylog2/shared/security/ShiroSecurityContextFilterTest.java
Only allow trusted header auth for the SessionsResource.
/nocl
Trusted header auth is only used until a session has been created for the user. From then on, if a session cookie is set on a request, it takes precedence over trusted headers to authenticate a request.
This was causing issues for proxied requests when a session expired. Our authentication chain would fail to authenticate the session cookie, because it was expired, and would then fall back to the next authentication method in the chain, which was trusted header auth. When trying to forward the request to other servers, we failed to extract an authentication token from the original request and caused the forwarded request to fail because it was unauthenticated.
With this fix, we are only allowing trusted header authentication …
=> Reduce scope of trusted header auth

changelog/unreleased/issue-17526.toml, graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/models/Collector.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/CollectorResource.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/CollectorService.java, graylog2-server/src/test/java/org/graylog/plugins/sidecar/collectors/SidecarServiceTest.java
* Refactor sidecar default collector migration
Refactoring of #17246
Fixes https://github.com/Graylog2/graylog2-server/issues/17526
Move the state of known default template checksums into the cluster config. This makes it easier to use the checksum for configurations and collectors alike.
* Fix up known configurations
* add comment about OLD_CHECKSUMS
* changelog
* Fix wrong yml path not paths
* Extend checksum entries with collector name and version
(cherry picked from commit 32e19492411eed4131fe2cba465286fa354d5fb5)
=> Refactor sidecar default collector migration (5.2 backport)

graylog2-web-interface/src/components/navigation/MainNavbar.tsx
It is possible to extend e.g. the system menu dropdown by registering an entry to the plugin system like
```
{
description: 'System',
children: {...}
}
```
This entry will be merged with the existing entry from core, which contains all other menu items. It also includes the position info for the dropdown. Before this change it was possible that the position info got lost when merging the items, depending on the order of entities in the plugin store.
/nocl
=> Retain position of navigation items when merging duplicate dropdowns.

UPGRADING.md, graylog2-server/src/main/java/org/graylog/schema/EventFields.java, graylog2-server/src/main/java/org/graylog/schema/VendorFields.java
Backport to 5.2 of `event_source_input` and `vendor_event_type` GIM fields added for input parsing adjustments and UNPRADING.md updates:
- https://github.com/Graylog2/graylog2-server/pull/17554
- https://github.com/Graylog2/graylog2-server/pull/17622
- https://github.com/Graylog2/graylog2-server/pull/17651
- https://github.com/Graylog2/graylog2-server/pull/17571
/nocl
=> (Backport 5.1) - Illuminate parsing updates

graylog2-web-interface/src/components/bootstrap/Button.tsx, graylog2-web-interface/src/components/common/PageNavigation.tsx
Before this change the active state for page navigation items was not being displayed. This is related to recent changes we made for the button component.
Now we display the active state again:
/nocl
=> Fixing style of active state for page navigation items.

changelog/unreleased/pr-17678.toml, graylog2-web-interface/src/views/components/highlighting/Highlight.tsx
**Note:** This is a backport of #17678 to `5.2`.
This PR is fixing up the text alignment of numbers in data tables which is usually right, but changed to be left-aligned when the number is highlighted.
=> Fixing text alignment for highlighted numbers. (`5.2`)

graylog2-web-interface/src/components/common/DatePicker.test.tsx, graylog2-web-interface/src/components/common/DatePicker.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/AbsoluteDatePicker.tsx
Before this change the `DatePicker` component allowed any date time as input for the selected date. It could be a moment date or a string like `2023-10-17T01:00:00.000Z`.
Since the date could include a time we had to consider the user time zone when highlighting the selected day.
With this PR we are simplifying the related logic, the component now expects the provided selected date to have the following format: `YYYY-MM-DD`. `onChange` it now also just provides a date with this format.
/nocl
=> Simplify state of `DatePicker` component.

changelog/unreleased/pr-17642.toml, graylog2-web-interface/src/views/components/datatable/MessagesTable.tsx, graylog2-web-interface/src/views/components/widgets/MessageTable.tsx
Note: This is a backport of https://github.com/Graylog2/graylog2-server/pull/17642 to 5.1.
This pr removes min-width 0 style from td in printing mode 
fix: https://github.com/Graylog2/graylog-plugin-enterprise/issues/6158
=> Fix Reporting erroneous distribution of table column width 5.1

changelog/unreleased/pr-17642.toml, graylog2-web-interface/src/views/components/datatable/MessagesTable.tsx, graylog2-web-interface/src/views/components/widgets/MessageTable.tsx
Note: This is a backport of https://github.com/Graylog2/graylog2-server/pull/17642 to 5.2.
This pr removes min-width 0 style from td in printing mode 
fix: https://github.com/Graylog2/graylog-plugin-enterprise/issues/6158
=> Fix Reporting erroneous distribution of table column width 5.2

changelog/unreleased/issue-17647.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/json/SelectJsonPath.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/jsonpathFromMessageField.txt
Previously `select_jsonpath` could only be used with a parsed `JsonNode` object (e.g. the direct output of `parse_json` within the same rule).
This update allows the `select_jsonpath` function to accept a JSON String as the `json` parameter as well.
Closes: https://github.com/Graylog2/graylog2-server/issues/17647
As it stands:
We can use `parse_json` and `select_jsonpath` to work with JSON, but currently, the `select_jsonpath` function only works within the same rule where `parse_json` was originally used.  If the output from `parse_json` is saved as a field on the message, `select_jsonpath` calls in subsequent rules on that field will fail.
This update allows a saved JSON message field to be used as the `select_jsonpath` `json` parameter.
Locally in dev environment and unit tests.
=> Update select_jsonpath to accept strings of JSON in addition to JsonNode objects

changelog/unreleased/issue-17523.toml, data-node/src/main/java/org/graylog/datanode/Configuration.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/ContainerizedGraylogBackend.java
Resolves #17523 
Update validation for `password_secret` to ensure it meets minimum length requirement.
=> Datanode: ensure `password_secret` meets length requirement

changelog/unreleased/pr-17368.toml, graylog2-web-interface/src/theme/UseCurrentThemeMode.ts
With `5.2` we renamed the theme modes `teint` and `noir` to `dark` and `light`. With this change make sure read-only users do not face a problem when downgrading Graylog from `5.2` to a previous version.
To test this change, checkout the branch, open the web interface, login with the system admin user, configure e.g. `themeMode: "dark"` in the local storage.
=> Return default theme mode when theme mode in local storage does not match expected format (`5.1`).

graylog2-web-interface/src/components/navigation/MainNavbar.tsx, graylog2-web-interface/src/components/perspectives/ActivePerspectiveBrand.tsx, graylog2-web-interface/src/components/perspectives/PerspectivesSwitcher.test.tsx, graylog2-web-interface/src/components/perspectives/PerspectivesSwitcher.tsx, graylog2-web-interface/src/components/perspectives/bindings.ts, graylog2-web-interface/src/components/perspectives/contexts/PerspectivesContext.ts, graylog2-web-interface/src/components/perspectives/contexts/PerspectivesProvider.tsx, graylog2-web-interface/src/components/perspectives/hooks/useActivePerspective.test.tsx, graylog2-web-interface/src/components/perspectives/hooks/usePerspectives.test.tsx, graylog2-web-interface/src/components/perspectives/types.ts, graylog2-web-interface/src/pages/StartPage.tsx, graylog2-web-interface/src/routing/AppRouter.test.tsx, graylog2-web-interface/test/fixtures/perspectives.tsx
Before this change the following scenario resulted in a problem:
1. A user selects a perspective from a plugin
2. The perspective becomes unavailable, e.g. because a required licence or permissions are missing
3. The user logs in again
Before this change the previously selected perspective was still the active one. Now we are considering if the selected perspective is actually available.
When testing this locally please test these changes together with https://github.com/Graylog2/graylog-plugin-enterprise/pull/6320 and https://github.com/Graylog2/graylog-plugin-enterprise/pull/6309
/jpd https://github.com/Graylog2/graylog-plugin-enterprise/pull/6320
/nocl
=> Consider availability for initially selected perspective.

changelog/unreleased/pr-17758.toml, graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchClientConfiguration.java, graylog2-server/src/main/java/org/graylog2/configuration/IndexerDiscoveryProvider.java, graylog2-server/src/test/java/org/graylog2/configuration/IndexerDiscoveryProviderTest.java, misc/graylog.conf
Similarly as with elastic/opensearch, graylog server now waits for an available datanode. Number of attempts and their delay is configurable, reusing `elasticsearch_version_probe_attempts` and `elasticsearch_version_probe_delay`, which will be most likely renamed in 6.0.
Without the waiting logic, users need to start datanode first and then graylog server, otherwise the server immediately crashes with exception.
Existing set of unit tests, manually tested starts
=> Wait till datanode becomes available during startup

changelog/unreleased/issue-17728.toml, graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java, graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypesListService.java, graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/mapping/FieldTypeMappingsService.java, graylog2-server/src/main/java/org/graylog2/plugin/Message.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/field_types/FieldTypeMappingsResource.java, graylog2-server/src/test/java/org/graylog2/indexer/IndexMappingTest.java
New reserved field (gl2_message_id). 
More safe custom mapping handling (you cannot change reserved field by manually playing with MongoDB). 
New unit tests.
Fixes #17728.
See #17728.
With new unit tests.
=> New reserved field. More safe custom mapping handling. New unit tests.

changelog/unreleased/issue-17649.toml, graylog2-server/src/main/java/org/graylog2/lookup/adapters/HTTPJSONPathDataAdapter.java
Resolves #17649
Error messages do not provide enough information to identify which adapter is failing, when there are many of them.
We now include the adapter name and URL.
=> More verbose error messaging in HTTP JSONPath data adapter

changelog/unreleased/pr-17602.toml, graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.tsx
We don't support legacy Sidecar collectors and their migrations in 5.2 anymore.
Minimal backport version of PR #17589
=> Remove Sidecar migration hint on config page

UPGRADING.md, full-backend-tests/src/test/java/org/graylog2/indexer/indices/IndicesIT.java, graylog2-server/src/main/java/org/graylog2/indexer/EventsIndexMapping.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping7.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexMappingTemplate.java, graylog2-server/src/main/java/org/graylog2/indexer/indexset/TemplateIndexSetConfig.java, graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java, graylog2-server/src/test/java/org/graylog2/indexer/EventsIndexMappingTest.java, graylog2-server/src/test/java/org/graylog2/indexer/IndexMappingTest.java, graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerIT.java, graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesGetAllMessageFieldsIT.java, graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesTest.java
Profiles are used to construct templates.
/jpd Graylog2/graylog-plugin-enterprise#6355
/nocl
Profiles that are set on index set level are not used to construct templates.
=> Profiles are used to construct templates

graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetConfig.java, graylog2-server/src/main/java/org/graylog2/indexer/indexset/profile/IndexFieldTypeProfile.java, graylog2-server/src/main/java/org/graylog2/indexer/indexset/profile/IndexFieldTypeProfileService.java, graylog2-server/src/main/java/org/graylog2/indexer/indexset/profile/IndexFieldTypeProfileUsagesService.java, graylog2-server/src/main/java/org/graylog2/indexer/indexset/profile/IndexFieldTypeProfileWithUsages.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexFieldTypeProfileResource.java, graylog2-server/src/test/java/org/graylog2/indexer/indexset/profile/IndexFieldTypeProfileUsagesServiceTest.java
Profile usages are fetched as part of response in `System/IndexSets/FieldTypeProfiles` endpoint.
/nocl
Needed by FE for profile summary page implementation.
Manually and with unit automatic tests.
=> Profile usages are fetched as part of response

graylog2-web-interface/src/components/bootstrap/Button.tsx
Before this change, buttons with an `href` displayed some link related style on hover:
Now they look like other buttons:
/nocl
=> Do not display link styles for button with href.

graylog2-web-interface/src/components/navigation/NavigationLink.tsx
Recently, we migrated the navigation dropdown components from react-bootstrap to mantine. One result was that the dropdown options were rendered as buttons. With this PR we are rendering them as anchors again.
/nocl
=> Render navigation dropdown options as anchors instead of buttons.

graylog2-web-interface/src/components/navigation/NavigationLink.tsx
With this PR we are fixing the active state for navigation items on sub pages. This problem does not occur in released versions.
Before:
After:
/nocl
=> Display active state for navigation items on sub pages.

changelog/unreleased/issue-17815.toml, full-backend-tests/src/test/java/org/graylog2/periodical/IndexRangesCleanUpIT.java, graylog2-server/src/main/java/org/graylog2/indexer/ranges/MongoIndexRangeService.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/Indices.java, graylog2-server/src/test/java/org/graylog2/indexer/ranges/MongoIndexRangeServiceTest.java
fixes #17815
Allow deletion of index ranges that are no longer managed by an index set
Its possible to delete index set without deleting the underlying index. 
Those ranges are never delete from the mongo db collection. 
Locally + added integration test that triggers the clean up periodical
=> allow deletion of index ranges that are no longer manged

graylog2-web-interface/yarn.lock
**Note:** This reverts commit 9c43b0291cd96287a1e26e12fc22fa15ace9fc37.
This PR is reverting an update for `react-hotkeys-hook` which introduced
a regression, the hotkeys functionality is not working anymore.
/nocl
=> Revert "Bump react-hotkeys-hook from 4.4.1 to 4.4.3 in /graylog2-web-interface (#17885)"

changelog/unreleased/issue-17647.toml, changelog/unreleased/pr-17820.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/json/SelectJsonPath.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/lookup/LookupAll.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/jsonpathFromMessageField.txt, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/lookupAll.txt
Backport to 5.2 of:
- https://github.com/Graylog2/graylog2-server/pull/17683
- https://github.com/Graylog2/graylog2-server/pull/17820
=> (Backport 5.2) - Pipeline function json handling improvements

changelog/unreleased/issue-17647.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/json/SelectJsonPath.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/jsonpathFromMessageField.txt
Backport to 5.1 of https://github.com/Graylog2/graylog2-server/pull/17683
=> (Backport 5.1) - Update select_jsonpath to accept strings of JSON in addition to JsonNode objects

changelog/unreleased/issue-17882.toml, graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java, graylog2-server/src/test/java/org/graylog/security/entities/EntityDependencyResolverTest.java
Backport of https://github.com/Graylog2/graylog2-server/pull/17891 to 5.2.
=> (Backport 5.2) - Handle Stream reference dependencies for entity sharing

changelog/unreleased/pr-17909.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/arrays/AbstractArrayFunction.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/arrays/ArrayContains.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/arrayContains.txt, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/with-arrays.json
When the `array_contains` pipeline function was passed a null array (for example through selecting a non-existent path through `json_path`), the function would internally throw an exception and return null. This fix resolves that, and correctly returns `false` since a null array cannot contain an values.
Needed for Illuminate processing content. 
Well-covered with unit tests.
=> Array Contains function: Fix unhandled exception when passed null array

graylog2-web-interface/src/components/bootstrap/Button.tsx
This is a follow-up for https://github.com/Graylog2/graylog2-server/pull/17862 and improving the way we define the button hover styles.
It looks like the button style specificity changed and there were some cases where `color: inherit` no longer had the desired effect.
/nocl
=> Fix button hover color.

graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardActions.test.tsx
Since a refactoring of the dropdown component (https://github.com/Graylog2/graylog2-server/pull/17527) one dashboard became flaky. This PR disables the test, to make sure this test does not block other PR's, until we have a proper solution.
/nocl
=> Disable flaky `DashboardActions` test.

graylog2-server/src/main/java/org/graylog2/datatiering/rotation/DataTierRotation.java, graylog2-server/src/main/java/org/graylog2/indexer/rotation/common/IndexRotator.java, graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/MessageCountRotationStrategy.java, graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/SizeBasedRotationStrategy.java, graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategy.java, graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingStrategy.java
This got changed by refactorings and was logging audit events for rotation with
strategy "org.graylog2.indexer.rotation.common.IndexRotator"
regardless of the actual rotation.
/nocl
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/6091
=> Log actual rotation class in audit events

graylog2-web-interface/src/components/bootstrap/Menu.tsx, graylog2-web-interface/src/components/common/EntityFilters/CreateFilterDropdown.tsx, graylog2-web-interface/src/components/common/OverlayDropdown.tsx, graylog2-web-interface/src/components/common/OverlayDropdownButton.tsx
This is a follow-up for https://github.com/Graylog2/graylog2-server/pull/17527. With this PR we are now using the `Menu` component from `components/bootstrap` instead of `@mantine/core` in the `OverlayDropdown` component. By using our abstraction we only have to adjust e.g. the menu styles in one place.
/nocl
=> Implement custom abstraction of `Menu` component for `OverlayDropdown`.

graylog2-web-interface/src/contexts/CurrentUserPreferencesProvider.test.tsx, graylog2-web-interface/src/contexts/CurrentUserProvider.test.tsx, graylog2-web-interface/src/contexts/CurrentUserProvider.tsx
In some scenarios, for example sometimes after the login, the following error occurs:
`useCurrentUser hook needs to be used inside CurrentUserContext.Provider`
This most likely happened because we were only rendering the `CurrentUserProvider` once the current user has been loaded, otherwise we were rendering its children. I only saw this error during development.
We are now just rendering a spinner while the current user is being loaded. This is possible, because we only implement the `CurrentUserProvider` on pages where we load the current user. 
/nocl
=> Only render children of `CurrentUserProvider` when current user has been loaded.

graylog2-web-interface/src/components/event-definitions/event-definitions/BulkActions.tsx, graylog2-web-interface/src/components/indices/IndexSetFieldTypes/BulkActions.tsx
Since we refactored the dropdown button component with https://github.com/Graylog2/graylog2-server/pull/17527 the dropdown options are now only being rendered when the dropdown is actually open.
This resulted in a bug with the modal for the field type removal and event definitions enable / disable bulk action, because the modal disappeared after clicking on the dropdown option.
Fixes https://github.com/Graylog2/graylog2-server/issues/17970
/nocl
=> Fix event definition and field type reset bulk action.

graylog2-web-interface/src/components/events/events/EventDetails.tsx, graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardActions.test.tsx, graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardActions.tsx, graylog2-web-interface/src/views/components/messagelist/MessageActions.tsx, graylog2-web-interface/src/views/components/searchbar/saved-search/SearchActionsMenu.tsx, graylog2-web-interface/src/views/types.ts
**Please note**, this PR needs to be merged together with https://github.com/Graylog2/graylog-plugin-enterprise/pull/6438
Before this change it was possible that users have no required permissions for any actions in the "More" dropdown.
This occurs for example for reader users who have only read access for a dashboard
With this change we are now hiding the dropdown button:
To make this possible we had to adjust the pluggable actions.
This change also improves the flaky test mentioned in https://github.com/Graylog2/graylog2-server/pull/17954
/nocl
/jpd https://github.com/Graylog2/graylog-plugin-enterprise/pull/6438
=> Display dashboard actions dropdown button in dashboards overview only when it contains actions.

graylog2-web-interface/src/views/components/DashboardActionsMenu.tsx
With the migration of dropdowns to Mantine, the content of dropdowns is now not rendered anymore by default, when they are not open. This leads to the "Full Screen" mode configuration modal closing immediately after the menu item has been clicked, due to the dropdown content (which is containing the modal) unmounting immediately.
This PR is fixing this by adding the `keepMounted` prop to ensure that the content of the dropdown is rendered even if it's not open.
This is fallout from a change that is previously unreleased, so no active version of the product is affected.
Fixes #17978.
/nocl
=> Keeping "More Actions" menu mounted to allow rendering of "Full Screen" mode modal.

graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.test.tsx, graylog2-web-interface/src/views/components/Value.test.tsx, graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.groupBy.test.tsx, graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.metric.test.tsx, graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.sort.test.tsx, graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/BulkActions.test.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/TimeRangePresetDropdown.test.tsx, graylog2-web-interface/src/views/components/visualizations/pie/__tests__/PieVisualization.test.tsx
This PR is a follow-up for https://github.com/Graylog2/graylog2-server/pull/17527. It should improve the behaviour of related flaky frontend tests.
With this PR we are waiting in tests for the dropdown menu to mount after opening it and to unmount after closing it.
/nocl
=> Improve dropdown related tests, by waiting for menu to be mounted and unmounted

changelog/unreleased/pr-18001.toml, data-node/pom.xml, full-backend-tests/src/test/java/org/graylog/datanode/RemoteReindexingMigrationIT.java, graylog-project-parent/pom.xml, graylog2-server/pom.xml, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/DatanodeMigrationBindings.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/RemoteReindexResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/actions/MigrationActions.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/actions/MigrationActionsImpl.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/machine/DatanodeMigrationPersistanceTrace.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/machine/MigrationState.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/machine/MigrationStateMachine.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/machine/MigrationStateMachineBuilder.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/machine/MigrationStateMachineImpl.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/machine/MigrationStateMachineProvider.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/machine/MigrationStep.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/persistence/DatanodeMigrationConfiguration.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/persistence/DatanodeMigrationConfigurationImpl.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/persistence/DatanodeMigrationPersistence.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/rest/CurrentStateInformation.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/rest/MigrationStateResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/rest/MigrationStepRequest.java, graylog2-server/src/main/java/org/graylog2/commands/Server.java, graylog2-server/src/main/java/org/graylog2/rest/resources/RestResourcesModule.java, graylog2-server/src/test/java/org/graylog/plugins/views/storage/migration/state/InMemoryStateMachinePersistence.java, graylog2-server/src/test/java/org/graylog/plugins/views/storage/migration/state/MigrationStateMachineTest.java, pom.xml
This PR creates infrastructure for controlled datanode migration. It introduces a state machine that will be used by frontend in the migration wizard. Transitions have guards and actions, which should do all the migration tasks. 
For the frontend, there are 2 new API endpoints:
GET `/api/migration/state`
```
{
"state": "REMOTE_REINDEX_WELCOME",
"next_steps": [
"DISCOVER_NEW_DATANODES"
]
}
```
The `state` is the db-persisted state of the migration. Frontend should be able to display a wizard page corresponding to this state. The `next_steps` array delivers possible steps/transitions that the user can trigger.
POST `http://localhost:9000/api/migration/trigger`
```
{
"step":"DISCOVER_NEW_DATANODES"
}
```
Performs the requested transition. We can extend the request with some additional …
=> State machine and rest api for datanode migration

graylog2-server/src/main/java/org/graylog2/bindings/PersistenceServicesBindings.java, graylog2-server/src/main/java/org/graylog2/notifications/DeletedStreamNotificationListener.java, graylog2-server/src/main/java/org/graylog2/streams/StreamServiceImpl.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/StreamCatalogTest.java, graylog2-server/src/test/java/org/graylog2/notifications/DeletedStreamNotificationListenerTest.java, graylog2-server/src/test/java/org/graylog2/streams/StreamServiceImplTest.java
/nocl
This PR fights dependency obesity. We don't need the notification service in the streams service. It has been used only to delete notifications related to streams that are being deleted. For that, we have the StreamDeletedEvent already in place. We just need a listener that removes related notifications. 
This simplifies dependencies of the heavily used StreamService and reduces complexity in it. 
Datanode server doesn't use full set of dependencies. Every additional dependency complicates creation of injectors.
Added unit test
=> Remove direct notifications dependency from StreamService, use events instead

graylog2-web-interface/src/views/components/searchbar/saved-search/SearchActionsMenu.tsx, graylog2-web-interface/src/views/types.ts
Fix flashing modals when trying to add a saved search as evidence for an investigation
/nocl
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/6466
There was a change on how the dropdown menu works on buttons, which was causing the modals to add a saved search for an investigation to show up only for an instant. With this PR the investigations search plugin follows the same pattern as the dashboard solution allowing to put the modal views outside the dropdown menu component.
Bug found with E2E
=> fix: Add saved searches and new searches working again

changelog/unreleased/pr-18022.toml, graylog2-server/src/main/java/org/graylog2/lookup/adapters/HTTPJSONPathDataAdapter.java
Resolves Graylog2/graylog-plugin-enterprise#6292
Trigger system notification when HTTP data adapater lookup throws an IO exception.
=> Trigger notification for IO exception in HTTP data adapter lookup

graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/querystrings/LastUsedQueryStringsService.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/querystrings/MongoLastUsedQueryStringsService.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/querystrings/QueryString.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/querystrings/QueryStringForUser.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/QueryStringUsedDTO.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/QueryStringsResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SuggestionsResource.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/querystrings/MongoLastUsedQueryStringsServiceTest.java
This PR is providing endpoints to record/retrieve last used query strings for auto-completion in the query input.
API endpoints provided are:
- `POST /search/query_strings`: record a query string (body is `{ "query_string": "..." }`)
- `GET /search/suggest/query_strings`: retrieve last used query strings (optional query parameter `limit`, defaulting to 10), ordered by time of last use
The persistence behind this is ensuring that:
- users can only see their last used query strings
- number of query strings is bounded (defaulting to 100)
- query strings are deleted when user is deleted
- query strings are deduplicated (right now in the simplest way)
Fixes #17946.
/nocl
=> Provide API endpoints to record/retrieve last used query strings.

changelog/unreleased/issue-17367.toml, graylog2-server/src/main/java/org/graylog/events/migrations/V20230629140000_RenameFieldTypeOfEventDefinitionSeries.java, graylog2-server/src/main/java/org/graylog2/notifications/Notification.java, graylog2-server/src/main/resources/org/graylog2/freemarker/templates/HTML/generic_with_link.ftl, graylog2-server/src/main/resources/org/graylog2/freemarker/templates/PLAINTEXT/generic_with_link.ftl, graylog2-server/src/test/java/org/graylog/events/migrations/V20230629140000_RenameFieldTypeOfEventDefinitionSeriesTest.java, graylog2-server/src/test/resources/org/graylog/events/migrations/V20230629140000_RenameFieldTypeOfEventDefinitionSeries/mixed_event_definitions-after.json, graylog2-server/src/test/resources/org/graylog/events/migrations/V20230629140000_RenameFieldTypeOfEventDefinitionSeries/mixed_event_definitions.json, graylog2-web-interface/src/logic/alerts/AggregationExpressionValidation.js
Backport of https://github.com/Graylog2/graylog2-server/pull/17819
* Improve error handling for missing field value
* limit to max, card, percentile functions
* refactor and add unit test
* publish notification for disabled definitions
* add link to event definition
(cherry picked from commit a310be13c1ab928b55689370dedfafe9a037b06b)
=> Improve error handling for event definition with missing field value (#17819)

graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/requests/IndexSetUpdateRequest.java
Cust. mappings are not lost on ind. set update anymore.
/nocl
Fix a bug when transforming one data object into another.
Manually.
=> Cust. mappings are not lost on ind. set update anymore

changelog/unreleased/issue-18002.toml, graylog2-server/src/main/java/org/graylog/events/search/MoreSearch.java
More search does not explode when affected indices are null or empty.
It returns empty result instead, with empty `used_indices` indicating that there was no index that could be queried.
Fixes #18002.
/nocl
Related to HS-2268747609.
If you have a fresh installation (or let someone delete your documents in `index_ranges` collection), you may encounter ugly errors in the UI before the first even is ingested, and first index range is calculated.
Manually, on fresh Mongo DB and with index_ranges for `gl_events` / `gl_system_events` removed by hand.
=> More search does not explode when affected indices are null or empty.

graylog2-web-interface/src/components/common/OverlayTrigger.tsx, graylog2-web-interface/src/components/configurations/TimeRangePresetForm.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/TimeRangeFilter.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TimeRangePicker.tsx
This PR is fixing an issue introduced in #18033. The time range preset picker on the configurations -> search -> time range presets page is not working, due to losing its form when rendered in a portal.
This PR is fixing this by allowing to pass a `withinPortal` prop to the time range picker which can be set to `false` on the search configuration page.
/nocl
=> Make rendering time range preset picket in portal optional.

graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessorConfig.java
While reviewing https://github.com/Graylog2/graylog-plugin-enterprise/pull/6492, I noticed that the `filters()` for aggregation events are set twice (once in `Builder.create()` and again in the root builder method that calls `create`). Cleaning that up at the same time. 
/nocl
=> Remove duplicate filters Aggregation event config builder

graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/actions/MigrationActions.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/actions/WithArgs.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/machine/MigrationStateMachine.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/machine/MigrationStateMachineBuilder.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/machine/MigrationStateMachineImpl.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/machine/MigrationStateMachineProvider.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/rest/MigrationStateResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/rest/MigrationStepRequest.java, graylog2-server/src/test/java/org/graylog/plugins/views/storage/migration/state/MigrationStateMachineTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/storage/migration/state/machine/MigrationActionsAdapter.java
/nocl
Support parameters for migration actions
Some migration state machine transition actions require user-entered parameters (think url and credentials of remotely reindexed cluster). This PR adds support for these:
POST: /api/migration/trigger
```
{
"step": "MIGRATE_INDEX_TEMPLATES",
"args": {
"foo":"bar",
"lorem":"ipsum"
}
}
```
Added unit test
=> Support migration action request arguments

graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetConfigFactory.java
this was missed when adjusting the index set defaults migration
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/6091
/nocl
=> Apply data tiering defaults to new Index sets

changelog/unreleased/pr-18028.toml, graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java
* Fix legacy TLS for LDAP / AD authentication
The Unbound ldapsdk update from 5.1.1 to 6.0.10
https://github.com/Graylog2/graylog2-server/pull/16624
Introduced a change which restricts the default ciphers of the Unbound TLS implementation.
https://github.com/pingidentity/ldapsdk/commit/837b8f0fe2947e64fcee0209e9b8ef713028515e
If `enabled_tls_protocols` with TLS <= 1.1 is configured, manually enable all known ciphers for Unbound using their SSLUtil restores support for legacy implementations.
This can be tested by running the LDAP Test server connection feature against  tls-v1-1.badssl.com:1011
* readme
---------
Co-authored-by: Patrick Mann <patrickmann@users.noreply.github.com>
(cherry picked from commit 50c7ee4fb69174bcad17322e1111950942c99d5b)
=> Fix legacy TLS for LDAP / AD authentication (#18028)

graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessorConfig.java, graylog2-server/src/test/java/org/graylog/events/processor/aggregation/AggregationEventProcessorConfigTest.java
Validation of series specs without required fields in Event Definitions
/nocl
Is a fix for #18034 together with [#17819.](https://github.com/Graylog2/graylog2-server/pull/17819)
#18034
#17367
=> Validation of series specs without required fields in Event Definitions

graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexSetsMappingResource.java
Bring back old  param name, to have consistent naming in FE
/nocl
Manually.
=> Bring back old  param name, to have consistent naming in FE

graylog2-web-interface/src/components/login/LoginForm.tsx
React seems to expect the following spelling `autoComplete`, white we were using `autocomplete` in this case. This does not affect the functionalty.
/nocl
=> Fix `autocomplete` attribute spelling in login form.

graylog2-server/src/main/java/org/graylog2/configuration/IndexSetsDefaultConfiguration.java, graylog2-server/src/main/java/org/graylog2/datatiering/fallback/PlaceholderDataTieringConfig.java, graylog2-server/src/main/java/org/graylog2/migrations/V202211021200_CreateDefaultIndexDefaultsConfig.java
Since the `data_tiering` field in the `IndexSetsDefaultConfiguration` cannot be null, a placeholder implementation is now used if the field does not exist in the database.
/nocl
=> fix data tiering in default index set config migration

UPGRADING.md, changelog/unreleased/issue-18032.toml, graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/suggestions/FieldValueSuggestionMode.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/suggestions/FieldValueSuggestionModeConverter.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SuggestionsResource.java, graylog2-server/src/main/java/org/graylog2/Configuration.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/engine/suggestions/FieldValueSuggestionModeConverterTest.java, misc/graylog.conf
Backporting #18095 to 5.2
---------
Co-authored-by: Tomas Dvorak <tomas.dvorak@graylog.com>
(cherry picked from commit 50f40fab244e3861b99dfb0acfce5e7cd5d7aaea)
=> Field value suggestions are configurable (5.2)

changelog/unreleased/pr-18130.toml, graylog2-web-interface/src/components/event-definitions/event-definition-form/EventConditionForm.tsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionForm.tsx, graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterForm.jsx
Enable condition form in event definitions when editing an Illuminate event
/nocl
With this modifications users will be able to add search-filters to Illuminate event definitions. The rest of the form is disabled so the only changes that can be done to this type of events are, add filters and notifications.
=> feat: Enable filters when editing an Illuminate event definition

graylog2-web-interface/src/views/components/WidgetContainer.tsx
Before this change the following error was displayed in the browser console,  when opening on the search page, during development.
```
Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `ForwardRef`, expected a single ReactElement.
```
/nocl
=> Fixing `PropTypes` error on search page.

graylog2-web-interface/src/views/components/searchbar/queryinput/QueryInput.tsx
Recently we made sure we show the query input keyboard shortcuts in the shortcuts overview. The challenge was to show the hotkeys in the overview, without providing a callback, because the ace editor takes care of registering the keyboard shortcuts.
With this PR we ensure the keyboard shortcuts are only active when the input is focused.
/nocl
=> Disable query input keyboard shortcuts outside of query input.

changelog/unreleased/issue-18000.toml, graylog2-web-interface/src/components/events/events/EventsContainer.jsx, graylog2-web-interface/src/stores/events/EventsStore.js
Please note, this is a backport of https://github.com/Graylog2/graylog2-server/pull/18000 for `5.2`.
It is possible that the request `/api/events/search` for the alerts overview throws an error like:
`Unable to perform search query[]\n\nIndex not found for query: . Try recalculating your index ranges.`
In case of an error response we are using the default query params in the UI. Before this change there was no default value for the time range. Since the frontend expects a time range it threw the following error:
I was able to reproduce this with a fresh system and we will improve the `Index not found` error in a different PR.
We are now using the same default time range like the backend and we are displaying a user notification in case of an error.
Fixes …
=> Define default time range in frontend for alerts overview request. (`5.2`)

changelog/unreleased/issue-18000.toml, graylog2-web-interface/src/components/events/events/EventsContainer.jsx, graylog2-web-interface/src/stores/events/EventsStore.js
Please note, this is a backport of https://github.com/Graylog2/graylog2-server/pull/18000 for `5.1`.
It is possible that the request `/api/events/search` for the alerts overview throws an error like:
`Unable to perform search query[]\n\nIndex not found for query: . Try recalculating your index ranges.`
In case of an error response we are using the default query params in the UI. Before this change there was no default value for the time range. Since the frontend expects a time range it threw the following error:
I was able to reproduce this with a fresh system and we will improve the `Index not found` error in a different PR.
We are now using the same default time range like the backend and we are displaying a user notification in case of an error.
Fixes …
=> Define default time range in frontend for alerts overview request. (`5.1`)

changelog/unreleased/pr-18174.toml, graylog2-server/src/main/java/org/graylog2/rest/resources/system/debug/bundle/SupportBundleService.java
Changes permissions for support bundle files from `-rw-r--r--` to `rw-------`.  
Previously, support bundle files were created with `-rw-r--r--` permissions.
The enclosing support bundle directory has `drwx------` permissions, so files were not accessible to anyone other than the user running Graylog. But it is probably still a good idea to create the files with more restrictive permissions.
=> More restrictive file permissions for support bundle files

changelog/unreleased/pr-18165.toml, data-node/src/main/java/org/graylog/datanode/Configuration.java, graylog2-server/src/main/java/org/graylog2/Configuration.java, graylog2-server/src/main/java/org/graylog2/cluster/ClusterConfigServiceImpl.java, graylog2-server/src/main/java/org/graylog2/events/ClusterEventPeriodical.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/ClusterConfigResource.java, graylog2-server/src/main/java/org/graylog2/security/RestrictedChainingClassLoader.java, graylog2-server/src/main/java/org/graylog2/security/SafeClasses.java, graylog2-server/src/main/java/org/graylog2/security/UnsafeClassLoadingAttemptException.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/views/ViewServiceTest.java, graylog2-server/src/test/java/org/graylog2/cluster/ClusterConfigServiceImplTest.java, graylog2-server/src/test/java/org/graylog2/events/ClusterEventPeriodicalTest.java, graylog2-server/src/test/java/org/graylog2/indexer/indexset/MongoIndexSetServiceTest.java, graylog2-server/src/test/java/org/graylog2/migrations/V20161215163900_MoveIndexSetDefaultConfigTest.java, graylog2-server/src/test/java/org/graylog2/migrations/V20170110150100_FixAlertConditionsMigrationTest.java, graylog2-server/src/test/java/org/graylog2/rest/resources/system/ClusterConfigResourceTest.java
Add a new `safe_classes` configuration option to restrict the classes allowed to be used as cluster config and event types.
The configuration option allows to specify a comma-separated set of prefixes matched against the fully qualified class name.
For now, the default value for the configuration is `org.graylog.,org.graylog2.`, which will allow all classes that are maintained by Graylog.
This should work out of the box for almost all setups. Changing the default value might only be necessary if external plugins require cluster config or event types outside the `org.graylog.` or `org.graylog2.` namespace. If that is the case, the configuration setting can be adjusted to cover this use case, e.b. by setting it to
```
safe_classes = org.graylog.,org.graylog2.,custom.plugin.namespace.
```
if …
=> Restrict classes allowed for cluster config and event types

changelog/unreleased/pr-18177.toml, graylog2-server/src/main/java/org/graylog2/rest/resources/system/contentpacks/ContentPackResource.java
Fixes a missing permission check for fetching "uninstall details" of installed content packs.
Previously, uninstall details could be fetched from the API even when the basic `contentpack:read` permission was missing.
If the content pack ID and installation ID were known, a request like the following would return results for any registered Graylog user:
http://localhost:8080/api/system/content_packs/5408f50a-b2fb-4430-977f-1351577e2841/installations/659bbce0057e576276644765/uninstall_details
With this change, the user needs to have at least `contentpack:read` permission (scoped by content pack ID) for the call to succeed.
=> Add permission check for displaying content pack uninstall details

changelog/unreleased/pr-18165.toml, data-node/src/main/java/org/graylog/datanode/Configuration.java, graylog2-server/src/main/java/org/graylog2/Configuration.java, graylog2-server/src/main/java/org/graylog2/cluster/ClusterConfigServiceImpl.java, graylog2-server/src/main/java/org/graylog2/events/ClusterEventPeriodical.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/ClusterConfigResource.java, graylog2-server/src/main/java/org/graylog2/security/RestrictedChainingClassLoader.java, graylog2-server/src/main/java/org/graylog2/security/SafeClasses.java, graylog2-server/src/main/java/org/graylog2/security/UnsafeClassLoadingAttemptException.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/views/ViewServiceTest.java, graylog2-server/src/test/java/org/graylog2/cluster/ClusterConfigServiceImplTest.java, graylog2-server/src/test/java/org/graylog2/events/ClusterEventPeriodicalTest.java, graylog2-server/src/test/java/org/graylog2/indexer/indexset/MongoIndexSetServiceTest.java, graylog2-server/src/test/java/org/graylog2/migrations/V20161215163900_MoveIndexSetDefaultConfigTest.java, graylog2-server/src/test/java/org/graylog2/migrations/V20170110150100_FixAlertConditionsMigrationTest.java, graylog2-server/src/test/java/org/graylog2/rest/resources/system/ClusterConfigResourceTest.java
Add a new safe_classes configuration option to restrict the classes allowed to be used as cluster config and event types.
The configuration option allows to specify a comma-separated set of prefixes matched against the fully qualified class name.
For now, the default value for the configuration is org.graylog.,org.graylog2., which will allow all classes that Graylog maintains.
This should work out of the box for almost all setups. Changing the default value might only be necessary if external plugins require cluster config or event types outside the "org.graylog." or "org.graylog2." namespaces. If that is the case, the configuration setting can be adjusted to cover this use case, e.b. by setting it to
safe_classes = org.graylog.,org.graylog2.,custom.plugin.namespace.
if said classes are …
=> Restrict classes allowed for cluster config and event types (#18165)

changelog/unreleased/issue-5620.toml, graylog2-web-interface/src/components/inputs/InputListItem.jsx, graylog2-web-interface/src/components/sidecars/sidecars/SidecarRow.jsx, graylog2-web-interface/src/util/TimeRangeHelper.ts, graylog2-web-interface/src/views/logic/TimeRange.ts
Defaulting to search in all messages is expensive and might trigger
OOM scenarios much easier.
Instead of searching all messages, we are searching only
messages in a range of past and future 26 hours.
26 hours because that's the largest possible timezone mistake a user can make.
Fixes #5620
=> Reduce time range on 'Show received messages' button

graylog2-server/src/main/java/org/graylog2/plugin/InputFailureRecorder.java
Reverts https://github.com/Graylog2/graylog2-server/pull/18148. We already capture when inputs enter the `failing` state and again enter the `running` state in the server log. For any in-between error messages, the system notification can be referenced, or debug logging for a specific input can be enabled. Also see conversion on the above PR for more info.
/nocl
=> Revert: Log failure warning message even if input is already failing

changelog/unreleased/issue-18127.toml, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/PaginationES7.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/PaginationResultES7.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Scroll.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ScrollResultES7.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackend.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/IndexToolsAdapterOS2.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/IndicesAdapterOS2.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/MoreSearchAdapterOS2.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/PaginationOS2.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/PaginationResultOS2.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/Scroll.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/ScrollResultOS2.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/OpenSearchBackend.java, graylog2-server/src/main/java/org/graylog2/indexer/results/ChunkedQueryResult.java, graylog2-server/src/main/java/org/graylog2/indexer/results/ChunkedResult.java, graylog2-server/src/test/java/org/graylog/events/search/MoreSearchAdapterIT.java, graylog2-server/src/test/java/org/graylog2/indexer/results/ChunkedQueryResultTest.java
Backport for issue #18127 
* set option ignore_unavailable
* CL
* suppress missing index exception in event query
* unit tests
* ignore failing scroll request
* more strict index options
* add comments
* use symbolic constants
* No exception when search request returns no scrollID value and there are no available indices
* annotate nullable
---------
Co-authored-by: luk-kaminski <lukasz.kaminski@graylog.com>
(cherry picked from commit 7acdc1ddc8baaa1bf030c2d49da5dedb4580d935)
When issuing a simple search query we now set option ignoreUnavailable=true and allowNoIndices=true. This serves to suppress the exception in case of missing indices, but otherwise leaves behavior unaltered.
=> Set option ignore_unavailable for querying (#18146)

changelog/unreleased/pr-18219.toml, graylog2-server/src/main/java/org/graylog2/bootstrap/ServerBootstrap.java, graylog2-server/src/main/java/org/graylog2/plugin/system/FilePersistedNodeIdProvider.java
The server's node ID is currently logged multiple times during server startup because we use different startup stages. (e.g., pre-flight)
=> Log node ID only once

graylog2-server/src/main/java/org/graylog/schema/GraylogSchemaFields.java, graylog2-server/src/main/java/org/graylog/schema/SecurityFields.java, graylog2-server/src/main/java/org/graylog2/plugin/Message.java
Moves the `FIELD_ASSOCIATED_ASSETS` variable to a non-deprecated fields class.
/nocl
/prd Graylog2/graylog-plugin-enterprise#6579
=> Refactor associated_assets field from deprecated class

graylog2-server/src/main/java/org/graylog/plugins/views/search/export/ExportJob.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/export/ExportJobServiceTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/export/ExportJobTest.java
Trying to deserialise export jobs from MongoDB fails with an error like the following:
```
com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'AutoValue_SearchTypeExportJob' as a subtype of `org.graylog.plugins.views.search.export.ExportJob`: known type ids = []
at [Source: (String); byte offset: #UNKNOWN]
```
This can be reproduced by navigating to `/search` and then exporting the search results.
The root cause lies in the `@JsonTypeInfo` annotation in the `JobExport` class. It is missing an `include = JsonTypeInfo.As.EXISTING_PROPERTY` attribute. This will cause Jackson to include an additional `type` field in the serialised JSON, even though a `type` property is also explicitly defined on the concrete classes which implement the `JobExport` interface. …
=> Fix deserialisation error of export jobs

graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/OpenSearchClientProvider.java
OpenSearchClientProvider should be a singleton.
/nocl
OpenSearchClientProvider is not constructed before each request to provide a client, new RestClientTransport instance is not constructed with every call to provide.
Manually.
Should we at all used provider for OpenSearchClients?
If yes, shouldn't we use a trick with memoize(), as in RestHighLevelClientProvider, to have only one instance of OpenSearchClient?
=> OpenSearchClientProvider should be a singleton

graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/SaveTimeRangeAsPresetButton.tsx
In https://github.com/Graylog2/graylog2-server/pull/18230 we were fixing the form submit for nested forms.
The time range picker form currently uses the `NestedForm` component which implements `onSubmitCapture`. This does not seems to work well, when the `NestedForm` contains another nested form, no matter if this form is being displayed in a portal or implements the `NestedForm` component as well. In this case the inner nested form will still submit the parent form.
This is currently the case for the time range preset form in the time range picker.
With this PR we are fixing the problem by not using a button with type "submit" in the time range preset form.
Another solution could be
- implementing the `NestedForm` for the time range preset form
- implementing the `NestedForm` for the …
=> Fix time range preset creation on search page.

graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.tsx
Currently, on cloud with the data tiering feature disabled it is not able to create a new index set due to incorrect data sent.
With this change it should be possible to create index sets
- on cloud with Data Tiering disabled
- on cloud with Data Tiering enabled and Data Tiering config
- on cloud with Data Tiering enabled and Legacy config
- on prem with Data Tiering config
- on prem with Legacy config
/nocl
=> Make sure to use legacy config for cloud with data tiering disabled

graylog2-web-interface/docs/StyleGuideWrapper.tsx, graylog2-web-interface/src/contexts/ThemeAndUserProvider.tsx, graylog2-web-interface/src/index.tsx, graylog2-web-interface/src/routing/AppFacade.tsx, graylog2-web-interface/src/theme/GraylogThemeProvider.tsx, graylog2-web-interface/src/theme/hooks/usePreferredColorScheme.ts
This is a follow-up for https://github.com/Graylog2/graylog2-server/pull/18185.
Before this change we were using the color scheme, saved in local storage, for the login screen. With this PR we are now  using the browser color scheme preference for the login page instead.
These changes include another improvement, we now do not render the `GraylogThemeProvider` twice.
/nocl
=> Use browser color scheme preference for login screen.

graylog2-web-interface/src/views/logic/views/OnSaveNewDashboard.ts
Since the update to React 18, state updates will be batched automatically. This leads to the dirty flag which is updated through `dispatch(setIsDirty(false))` after saving a new dashboard not being propagated to the `WindowLeaveMessage` component, before the redirect to the saved dashboard is happening.
This PR is now wrapping the store updates with `flushSync`, enforcing a rerender before the redirect. This is a workaround used to fix the regression asap, but the underlying problem indicating a code smell should be addressed too in a future PR.
Fixes #18279.
/nocl
=> Use `flushSync` to force propagation of dirty flag.

graylog2-web-interface/src/pages/IndexSetFieldTypesPage.tsx
With this PR we are unifying the page navigation of the index set field types overview page with the page navigation on other indices related pages.
/nocl
=> Unify page navigation for index set field types overview page.

graylog2-web-interface/src/components/users/UserCreate/UserCreate.test.tsx
This is a follow-up for https://github.com/Graylog2/graylog2-server/pull/18190.
The `UserCreate` test failed sometimes with the warning:
```
[INFO] FAIL src/components/users/UserCreate/UserCreate.test.tsx (13.998 s)
[INFO]   ● <UserCreate /> › should create user
[INFO] 
[INFO]     Warning: The current testing environment is not configured to support act(...)
[INFO] 
[INFO]       at console.<anonymous> (node_modules/jest-preset-graylog/lib/setup-files/console-warnings-fail-tests.js:49:11)
[INFO]       at printWarning (node_modules/react-dom/cjs/react-dom.development.js:86:30)
[INFO]       at error (node_modules/react-dom/cjs/react-dom.development.js:60:7)
[INFO]       at isConcurrentActEnvironment (node_modules/react-dom/cjs/react-dom.development.js:25260:7)
[INFO]       at …
```
=> Mock debounce in `UserCreate` test to make test less flaky.

.github/workflows/build.yml, pom.xml
=> Enforce that the build uses the maven version that is defined in the wrapper

graylog2-web-interface/src/components/common/DatePicker.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/AbsoluteDatePicker.tsx
The bug happens because during editing the `Timestamp` input (from or to) on the Absolute tab, the user might type an invalid date format, and `DatePicker`  throws an error in this case. 
This PR removes throwing errors in case of an invalid date. 
Also, PR fixes another problem. When the user typed an invalid date in the timestamp, it was impossible to rewrite the date using DatePicker (by clicking on some date). Now, in the case of date selection, we are taking the selected date and current time 
fix: https://github.com/Graylog2/graylog2-server/issues/18200
/nocl
=> Fix throwing error on editing timestamp date on timerange popover

changelog/unreleased/pr-18343.toml, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TabKeywordTimeRange.test.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TabKeywordTimeRange.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TimeRangePicker.test.tsx
When defining a keyword time range in the time range picker, the keyword is being validated in the backend.
With this PR we are debouncing the request. We also make sure that the validation does not run another time, after the request finished.
These changes also slightly improve the validation, before you could have an initial value like "Last five minutes" and see no validation error when removing the last two characters.
=> Debounce keyword validation request.

changelog/unreleased/pr-18339.toml, changelog/unreleased/pr-18342.toml, data-node/src/main/java/org/graylog/datanode/Configuration.java, data-node/src/main/java/org/graylog/datanode/configuration/OpensearchConfigurationProvider.java, data-node/src/test/java/org/graylog/datanode/integration/DataNodePluginsIT.java, data-node/src/test/java/org/graylog/datanode/integration/DatanodeClusterIT.java, data-node/src/test/java/org/graylog/datanode/testinfra/DatanodeDevContainerBuilder.java, misc/datanode.conf
OpenSearch renamed cluster.initial_master_nodes to initial_cluster_manager_nodes, which was not reflected yet and is a possible cause of startup bugs.
https://github.com/opensearch-project/OpenSearch/issues/2769
=> DataNode: rename cluster manager property

UPGRADING.md, changelog/unreleased/pr-18328.toml, graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationBrowserResource.java, graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationResource.java, graylog2-server/src/main/resources/swagger/index.html.template
Previously, the API browser could be accessed without any restrictions. A user only had to provide credentials when executing API requests through the API browser, which required an authenticated user to succeed.
With this change, a user has to log in before visiting the API browser. It is sufficient to log in with any user known to Graylog. No particular permissions are required.
The username/password field has been removed from the header of the API browser because a valid user is now required. If users want to perform API requests with different credentials, they now have to log out of Graylog and re-login again with a different user.
When users navigate to the API browser at `/api/api-browser` (or the cluster-global version) directly, without first logging into Graylog, they will be …
=> Require authentication to visit API browser

data-node/src/main/java/org/graylog/datanode/configuration/OpensearchConfigurationProvider.java
The initial premise was, that this setting should only be set once during the first start of the OpenSearch cluster and not on subsequent starts because it is transferred into the database.
The current implementation creates problems when migrating to the DataNode and first time startup.
After some testing, it seems that we can safely include this setting always so the guard that only writes the setting (unless manually set in the config file) during preflight can be removed so we always write the list of active nodes.
/nocl
=> DataNode: initial cluster manager setting - always set either active nodes or the config setting

graylog2-web-interface/src/components/bootstrap/Button.tsx
With the introduction of Mantine 7.5.2, a loader element was added to buttons, which is rendered even if the `loading` prop is `false`. This element was falsely detected by cypress to cover up the button, leading to e2e test failures.
This PR is now setting the CSS visibility of that element to `hidden`, making cypress able to detect it is not actually covering up the button element.
/nocl
=> Make Mantine loader element invisible.

graylog2-web-interface/src/components/indices/IndexSetFieldTypeProfiles/CreateProfile.tsx
Go back in history instead of jumping to field types profile overview when cancelling field type profile creation step.
This avoids ending up in a different place when opening the dialog from the bulk actions on the index field types page.
/nocl
=> Go back when cancelling field type profile creation.

changelog/unreleased/pr-18241.toml, graylog2-web-interface/src/views/components/WidgetQueryControls.test.tsx, graylog2-web-interface/src/views/components/WidgetQueryControls.tsx
Before this change it was possible to see the following info for the dashboard query filter in the aggregation builder for widgets.
This happened when you
1. go to a dashboard
2. click on the search button, while the query input is empty
3. edit a widget
=> Do not display info for dashboard query filter in aggregation builder, when dashboard query is empty

changelog/unreleased/pr-18124.toml, graylog2-server/src/main/java/org/graylog/plugins/map/config/GeoIpProcessorConfig.java, graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IPinfoIPLocationDatabaseAdapter.java, graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IpInfoIpAsnResolver.java, graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IpInfoIpResolver.java, graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IpInfoLocationResolver.java, graylog2-server/src/main/java/org/graylog/plugins/map/geoip/MaxmindDataAdapter.java, graylog2-server/src/test/java/org/graylog/plugins/map/geoip/MaxmindDataAdapterTest.java, graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterFieldSet.tsx
* Allow more db types for IPinfo mmdb files
IPinfo recently changed the info in their metadata.
old
```
mmdbctl metadata 24/asn.mmdb
- Binary Format 2.0
- Database Type ipinfo asn.mmdb
```
new
```
mmdbctl metadata newest/asn.mmdb
- Binary Format 2.0
- Database Type ipinfo generic_asn_mmdb_v4.mmdb
```
This is likely because they changed something
in their release process, because the db type is just their import filename:
https://github.com/ipinfo/mmdbctl/blob/master/lib/cmd_import.go#L269
Relax our db type match to support this.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/6436
* Changelog
* Allow selecting IPinfo DB types in Data Adapters
This probably got broken with PR #13911
* Add config to disable IPinfo database type check
The database type check is only a …
=> Allow more db types for IPinfo mmdb files / reenable IPinfo in data adapter UI (5.2)

graylog2-server/src/main/java/org/graylog2/indexer/datastream/policy/actions/RolloverAction.java
When creating a data stream on versions of OpenSearch earlier than 2.11, the following error occurs:
> “illegal_argument_exception”,“reason”:“Invalid field: [copy_alias] found in RolloverAction.”
This is because the `copy_alias` property was not supported until OpenSearch 2.11. See https://opensearch.org/docs/2.12/im-plugin/ism/policies/
This PR removes the property. With this change, I am able to create data streams successfully back to version `2.0.1`.
/nocl
=> Metrics data streams: Prevent error when creating data stream < OS 2.11

graylog2-server/src/main/java/org/graylog2/shared/rest/resources/ProxiedResource.java
ProxiedResource can direct a call to any single node.
/nocl
With this change, it would be possible to cancel a long-running async task started on a particular node by directing a separate cancel call to that node.
=> ProxiedResource can direct a call to any single node

graylog2-web-interface/src/components/support/DocumentationLink.tsx
=> Improve styling of documentation links on hover.

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchTypeExecutionState.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/events/EventList.java
This PR is adding `page`/`per_page` parameters to the execution state and uses them in the `event` search type if present.
/nocl
=> Allow overriding `events` search type pagination through execution state.

graylog2-web-interface/src/components/common/Timestamp.md, graylog2-web-interface/src/components/common/Timestamp.test.tsx, graylog2-web-interface/src/components/common/Timestamp.tsx
Before this change the `Timestamp` component displayed the current date, when the `dateTime` prop is not defined.
With this PR we are now displaying nothing, when the `dateTime` prop is empty. If you want to display the current date, you need to define it explicitly. In case you want to display a specific timestamp, which can be `undefined`, you now no longer end up in a state where you display the current time accidentally.
There are few cases where we actually want to display the current timestamp in these cases we already define `new Date()` for the `dateTime` prop.
/nocl
=> Make `Timestamp` `dateTime` prop more explicit.

graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/DataStreamAdapterOS2.java
When ISM policies are created, an existing policy with the given id will be loaded first. If this is present, it is removed from the data stream and deleted before the new policy is created and applied.
If the policy cannot be read, e.g. due to data model changes, the new policy won't be applied.
This PR tries to delete also policies which can't be read.
/nocl
change to RolloverAction caused existing ISM policies in the data node to not be read.
=> delete ism policy if an error occurs on reading

changelog/unreleased/issue-18053.toml, graylog2-web-interface/src/views/components/searchbar/queryinput/QueryInput.tsx, graylog2-web-interface/src/views/components/searchbar/queryinput/StyledAceEditor.tsx
As reported in https://github.com/Graylog2/graylog2-server/issues/18053 and https://github.com/Graylog2/graylog-plugin-enterprise/issues/6627 the search bar can disappear when deleting the query input and triggering the "Add to query" action, multiple times.
The reason seems to be: We are using styled-components to style the editor, styled-components defines a CSS `class` for the main editor DOM element. Since the component styling implements the editor value (as a boolean), styled-components generates a new CSS `class` once the editor value gets defined or is being cleared.
Changing the editor CSS classes seems to be problematic for the `react-ace` component. https://github.com/securingsincity/react-ace/issues/823 
It can result in an essential ace-editor CSS `class` being removed, which …
=> Fixing problem with query input which can make the search bar disappear

changelog/unreleased/pr-18467.toml, graylog2-web-interface/package.json, graylog2-web-interface/packages/jest-preset-graylog/jest-preset.js, graylog2-web-interface/src/views/logic/debounceWithPromise.test.ts, graylog2-web-interface/yarn.lock
**Note:** This is a backport of #18450 to `5.1`.
This PR is fixing the debounceWithPromise function. Previously, it was using lodash/debounce to promisify debouncing async functions. Unfortunately, due to limitations of lodash/debounce, it will lead to first invocations of the function that is debounced to return promises which are never resolved, leading to suble bugs like #16883.
This PR is solving this using p-debounce, which is tailored for debouncing async functions and does not have the same limitations as lodash/debounce.
Fixes #16883.
=> Fix debouncing async functions. (`5.1`)

changelog/unreleased/pr-18461.toml, graylog2-web-interface/package.json, graylog2-web-interface/packages/jest-preset-graylog/jest-preset.js, graylog2-web-interface/src/views/logic/debounceWithPromise.test.ts, graylog2-web-interface/yarn.lock
**Note:** This is a backport of #18450 to `5.2`.
This PR is fixing the debounceWithPromise function. Previously, it was using lodash/debounce to promisify debouncing async functions. Unfortunately, due to limitations of lodash/debounce, it will lead to first invocations of the function that is debounced to return promises which are never resolved, leading to suble bugs like #16883.
This PR is solving this using p-debounce, which is tailored for debouncing async functions and does not have the same limitations as lodash/debounce.
Fixes #16883.
=> Fix debouncing async functions. (`5.2`)

graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/MessageList.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/events/EventList.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/PivotResult.java
SearchType.Result implementations have to support deserialization.
/nocl
Because of a need to use those classes in a remote calls, they have to support not only serialization, but deserialization as well.
=> SearchType.Result implementations have to support deserialization

changelog/unreleased/issue-18053.toml, graylog2-web-interface/src/views/components/searchbar/queryinput/QueryInput.tsx, graylog2-web-interface/src/views/components/searchbar/queryinput/StyledAceEditor.tsx
_Please note_: This is a backport of #18470 for `5.2`
As reported in https://github.com/Graylog2/graylog2-server/issues/18053 and https://github.com/Graylog2/graylog-plugin-enterprise/issues/6627 the search bar can disappear when deleting the query input and triggering the "Add to query" action, multiple times.
The reason seems to be: We are using styled-components to style the editor, styled-components defines a CSS `class` for the main editor DOM element. Since the component styling implements the editor value (as a boolean), styled-components generates a new CSS `class` once the editor value gets defined or is being cleared.
Changing the editor CSS classes seems to be problematic for the `react-ace` component. https://github.com/securingsincity/react-ace/issues/823 
It can result in an …
=> Fixing problem with query input which can make the search bar disappear (`5.2`)

graylog2-web-interface/src/components/bootstrap/MenuItem.tsx, graylog2-web-interface/src/components/common/EntityList.md, graylog2-web-interface/src/components/event-definitions/event-definitions/BulkActions.tsx, graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionEntry.tsx, graylog2-web-interface/src/components/event-notifications/event-notifications/BulkActions.tsx, graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotificationActions.tsx, graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotifications.jsx, graylog2-web-interface/src/components/indices/IndexSetsComponent.tsx, graylog2-web-interface/src/components/rules/rule-builder/RuleBlockDisplay.tsx, graylog2-web-interface/src/components/sidecars/configurations/CollectorRow.jsx, graylog2-web-interface/src/components/sidecars/configurations/ConfigurationRow.jsx
With this PR we are creating a danger variant for the `MenuItem` component. In many cases the menu contains a `Delete` action. With the danger variant we can unify the styling.
/nocl
=> Create danger variant of menu item.

graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/FieldTypeMapper.java, graylog2-server/src/main/java/org/graylog2/plugin/Message.java
This PR set failed_message_streams type as `stream`. This helps FE to show values properly. 
before 
after
fix: https://github.com/Graylog2/graylog2-server/issues/17754 
/nocl
=> Set failed_message_streams type as stream

changelog/unreleased/pr-18472.toml, graylog2-server/src/main/java/org/graylog2/rest/resources/system/CookieFactory.java, graylog2-server/src/main/java/org/graylog2/shared/bindings/RestApiBindings.java, graylog2-server/src/test/java/org/graylog2/rest/resources/system/CookieFactoryTest.java
Changes which path is chosen to populate the `Path` attribute in the authentication cookie.
Previously, the path was chosen as follows, highest priority first:
1. The path from the URL in the `X-Graylog-Server-URL` request header
2. The path from the `Origin` request header
3. `/`
With this PR, the value will be chosen as follows:
1. The path from the URL in the `X-Graylog-Server-URL` request header
2. The path from the `http_external_uri` configuration setting
3. `/`
The `Origin` header does not contain a path. See [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin):
> The Origin header is similar to the [Referer](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer) header, but does not disclose the path, and may be null.
It was therefore removed as a …
=> Consider `http_external_uri` when setting the cookie path

pom.xml
Fixes CVE-2024-21634
Note for the kind reviewer:
I didn't read through the changelog and only tested the CloudTrail input to see if it could still fetch messages from AWS. IMHO, if the build passes, that should be good enough.
/nocl
=> Bump aws-java-sdk-1.version from 1.12.607 to 1.12.675

graylog2-web-interface/src/components/systemjobs/SystemJob.tsx
/nocl
Two jobs, one without the other with progress after this change:
=> Dont show a bar if a job doesn't have a progress

graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/events/EventList.java
This PR is fixing the deserialization of the `events` search type from MongoDB. Prior to this PR, instances which had a `null` `page` or `per_page` property, had a `page`/`per_page` attribute of `0` afterwards, due to `null` being deserialized as `0` for `int` attributes.
/nocl
=> Fixing deserialization of `events` search type with empty `page`.

changelog/unreleased/issue-13499.toml, graylog2-server/src/main/java/org/graylog/failure/ProcessingFailureCause.java, graylog2-server/src/main/java/org/graylog2/streams/StreamRouterEngine.java
Resolves #13499
Adds a processing error to the message when a stream rule fails to match - both for normal conditions and regex matching.
Force an exception and check processing errors stream messages for the new error message.
=> Verbose processing error when streamrule fails

data-node/src/test/java/org/graylog/datanode/testinfra/DatanodeDevContainerBuilder.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/ContainerizedGraylogBackend.java, graylog2-server/src/test/java/org/graylog/testing/containermatrix/ContainerMatrixTestEngine.java, graylog2-server/src/test/java/org/graylog/testing/containermatrix/SearchServer.java, graylog2-server/src/test/java/org/graylog/testing/containermatrix/annotations/ContainerMatrixTestsConfiguration.java, graylog2-server/src/test/java/org/graylog/testing/containermatrix/discovery/IsContainerMatrixTestClass.java, graylog2-server/src/test/java/org/graylog/testing/elasticsearch/TestableSearchServerInstance.java, graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerConfig.java, graylog2-server/src/test/java/org/junit/jupiter/engine/descriptor/ContainerMatrixTestWithRunningESMongoTestsDescriptor.java, graylog2-server/src/test/java/org/junit/jupiter/engine/descriptor/ContainerMatrixTestsDescriptor.java, graylog2-server/src/test/java/org/junit/jupiter/engine/discovery/ContainerMatrixClassSelectorResolver.java, graylog2-server/src/test/java/org/junit/platform/engine/support/hierarchical/ContainerMatrixHierarchicalTestEngine.java
The existing implementation collected all the feature flags, mongodb resources and additional configuration parameters into one bucket and every instance got this bucket. One configuration change in any of the test (ContainerMatrixTestConfiguration) would change configuration for all tests everywhere. 
This PR changes that and fixes problems where test configurations go against each other (changing the same property).  Additionally it simplifies the code a bit, removes duplicities and places needed to adapt when new ContainerMatrixTestConfiguration option will be added.
The performance of the whole setup seems to be better now, even if we now have more possible combinations of containers and their configuration. But we are now starting some containers (mailserver, http notification …
=> Fix matrix tests configurations, calculate unique variants for flags and additional params

misc/graylog.conf
The port in the comment was 19200, which was likely a typo, and this caused some confusion as to why the port was different.
/nocl
- [-] I have added tests to cover my changes.
=> De-confuse port in elasticsearch_hosts comment

graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/RemoteReindexingMigrationAdapterOS2.java
For DataNode remote-reindex migration:
If an index already exist in the new indexer, it must have been created by graylog itself - which is fine. So we can happily migrate data into it instead of failing the index.
/nocl
=> DataNode: Remote-Reindexing - don't fail index if it already exists in new indexer

graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config, graylog2-web-interface/src/components/perspectives/PerspectivesSwitcher.test.tsx, graylog2-web-interface/src/components/perspectives/PerspectivesSwitcher.tsx
In preparation for the `6.0` release and for testing testing, remove the `frontend_perspectives` feature flag and enable perspective switching by default.
/nocl
Verify that the perspective switching option is available when additional perspectives are available.
=> Enable frontend perspectives without feature flag

changelog/unreleased/pr-18609.toml, graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java, graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingStrategyTest.java, graylog2-web-interface/src/components/indices/IndexMaintenanceStrategiesConfiguration.tsx
Change default value for `TIME_SIZE_OPTIMIZING_ROTATION_MAX_SHARD_SIZE` to 20GB
See linked issue for discussion.
Resolves Graylog2/graylog-plugin-enterprise#6611
Cloud has been operating with min==max shard size for some time.
=> Change default TIME_SIZE_OPTIMIZING_ROTATION_MAX_SHARD_SIZE

graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/ClusterAdapterOS2.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/ClusterAdapterOS2Test.java
This PR is fixing an issue that can occur during retrieval of watermark settings from OpenSearch. Prior to this PR, retrieval was succeeding either when no disk allocation settings were present at all, or when they were complete, including watermark settings. When an intermediate key was missing, extraction of settings failed.
This PR is fixing this, returning `null` for these cases and adding test.
Fixes #18623.
/nocl
=> Fix parsing of missing watermark settings.

graylog2-web-interface/src/views/Constants.ts
=> Hide gl2_processing_duration_ms field by default

graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/RemoteReindexingMigrationAdapterOS2.java
Skip indices that start with `.` during re-index migrations. 
/nocl
=> DataNode: Skip system indices during reindex migration

graylog2-server/src/main/java/org/graylog/security/certutil/audit/CaAuditEventTypes.java
Fix for the following error:
```
2024-03-14 10:14:44,562 ERROR: org.graylog.plugins.auditlog.jersey.AuditLogFilter - Error building audit event from REST request: POST http://localhost:8080/api/ca/create
java.lang.IllegalArgumentException: Type string needs to be in the following format: <namespace>:<object>:<action> - given string: ca:create
at org.graylog2.audit.AuditEventType.create(AuditEventType.java:95) ~[classes/:?]
```
/nocl
=> Fixing wrong audit type namespace usage for Graylog CA

changelog/unreleased/issue-18633.toml, graylog2-web-interface/src/components/event-definitions/event-definitions/SchedulingCell.tsx
fixing #18633 
Fix when having queued events, while fixing the event definition  overview page, the clearNotifications page gets triggered automatically after page render.
=> fix functional component triggering on page render

graylog-plugin-parent/graylog-plugin-web-parent/pom.xml, graylog-plugin-parent/pom.xml
As a backend developer I sometimes need to rebuild the backend code but I would like to skip rebuilding the frontend code. I can do this with providing `-Dskip.web.build=true` to the maven command, like so:
```
./mvnw clean test-compile -Dskip.web.build=true -Dmaven.javadoc.skip=true -Dforbiddenapis.skip=true
```
However, this will also clean the node modules from the plugins without rebuilding them. So after executing the command, the development web server won't work anymore until I trigger installing the modules again.
With this change, the `maven-clean-plugin` will only clean the node modules from plugins, if the web build is *not* skipped. That's in line with how this was already handled for graylog2-server.
This allows me to cleanly rebuild the backend without breaking my frontend …
=> Skip cleaning of node_modules in plugins on `-Dskip.web.build=true`

graylog-storage-opensearch2/assembly.xml, graylog-storage-opensearch2/pom.xml, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/ClusterAdapterOS2.java, graylog-storage-opensearch2/src/main/java/org/opensearch/client/opensearch/_types/NodeRole.java, graylog-storage-opensearch2/src/main/java/org/opensearch/client/opensearch/nodes/info/NodeInfoAction.java, graylog-storage-opensearch2/src/main/java/org/opensearch/client/opensearch/nodes/info/NodeInfoBootstrap.java, graylog2-server/src/main/java/org/graylog2/system/stats/elasticsearch/NodeInfo.java
This PR is doing some monkey-patching to fix parsing of the `search` role for OpenSearch nodes. This is required due to a lack of support for this in the OpenSearch Java client (bug filed [here](opensearch-project/opensearch-java#893)) and should be removed after the bug was fixed upstream.
Refs #14788.
/nocl
/jpd https://github.com/Graylog2/graylog-plugin-enterprise/pull/6803
=> Monkey-patching `NodeRole` class to avoid role parsing bug.

changelog/unreleased/pr-18688.toml, full-backend-tests/src/test/java/org/graylog/datanode/DatanodeOpensearchProxyDisabledAllowlistIT.java, full-backend-tests/src/test/java/org/graylog/datanode/DatanodeOpensearchProxyIT.java, graylog2-server/src/main/java/org/graylog2/rest/resources/datanodes/DataNodeApiProxyResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/datanodes/DataNodeRestApiProxyResource.java, graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java
Specify rest permissions for datanode proxies. Rename opensearch proxy path from 
`/datanodes/{hostname}/request/{path: .*}` to `/datanodes/{hostname}/opensearch/{path: .*}`
Add explicit REST permissions for the proxy endpoints. Rename paths from /request/ to /opensearch/, to avoid any confusion. 
Fixes partially https://github.com/Graylog2/graylog2-server/issues/18687
Existing and new integration tests
=> Specify permissions for datanode proxy resources, rename request paths

graylog2-web-interface/src/components/bootstrap/Button.tsx
With this PR we are reimplementing the `active` state styling for the button component.
This styling got lost, while implementing the mantine button.
Before we were using the `:active` styling for the active element.
It is currently not easily possible to also use the styling of the pseudo class when the `active` prop is true.
Now we are just using a different variant instead.
Fixes https://github.com/Graylog2/graylog2-server/issues/18360
/nocl
=> Reimplement active state styling for buttons.

graylog2-web-interface/src/hooks/useHotkey.tsx
Currently you can't enter a `?` in an input, because it will open the shortcuts overview.
I remember enabling this feature to be able to trigger keyboard shortcuts while the search query input is focused. Now where we use the `react-ace` commands to listen for the keyboard shortcuts this is no longer necessary.
it is still possible to overwrite this behaviour for an individual shortcut.
Fixes https://github.com/Graylog2/graylog2-server/issues/18699
/nocl
=> Do not listen for keyboard shortcuts in inputs, by default.

graylog2-web-interface/src/views/components/widgets/MessageTable.tsx
This PR removes the sort icon for compound fields
fix: https://github.com/Graylog2/graylog2-server/issues/18696
/nocl
=> Remove sorting for compound fields

changelog/unreleased/pr-18754.toml, graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/MigrateExistingData.tsx
In this PR we:
- Display the total number of available indices
- Increase the number of indices shown in the valid connection box
- Made scroll-bar always visible
fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/6844
=> improve Remote Reindex Migration Indices display UX

graylog2-server/src/main/java/org/graylog2/indexer/IndexSetValidator.java, graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/mapping/FieldTypeMappingsService.java, graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetConfig.java, graylog2-server/src/test/java/org/graylog2/indexer/IndexSetValidatorTest.java, graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/mapping/FieldTypeMappingsServiceTest.java, graylog2-server/src/test/java/org/graylog2/indexer/indexset/IndexSetConfigTest.java
Additional validation - profile and custom mappings changes are impossible on `failure` and `event` indices.
This fix is independent, but complementary to FE fix: https://github.com/Graylog2/graylog2-server/pull/18490
/nocl
See #17839.
=> Additional validation - profile and custom mappings changes

data-node/src/main/java/org/graylog/datanode/management/OpensearchProcessImpl.java, data-node/src/main/java/org/graylog/datanode/management/OpensearchProcessService.java, data-node/src/main/java/org/graylog/datanode/metrics/ConfigureMetricsIndexSettings.java
This is a workaround to not startup up a second instance/gracefully shutting down the running instance of OpenSearch in the data node.
Data node configuration change handling needs to be reworked and worked into the state machine to properly address this in the future (see #18013 )
/nocl
On configuration change (e.g. cert renewal), the existing OS instance didn't get shutdown properly, leading to a second instance being started with error.
- renew data node certificate
=> fix duplicate startup of data node

changelog/unreleased/pr-18802.toml, data-node/src/main/java/org/graylog/datanode/management/OpensearchProcessImpl.java, graylog2-server/src/main/java/org/graylog2/configuration/IndexerDiscoveryProvider.java, graylog2-server/src/test/java/org/graylog2/configuration/IndexerDiscoveryProviderTest.java
When there are several datanodes available, one configured and one not yet configured, the IndexerDiscoveryProvider will see both, one with valid transport address and one with empty. We have to filter out the empty one, otherwise it will break opensearch clients.
=> Remove empty indexer tranport addresses in IndexerDiscoveryProvider

changelog/unreleased/pr-18787.toml, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/export/ElasticsearchExportBackend.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/export/ExportClient.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/export/SearchAfter.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/export/ElasticsearchExportBackendIT.java, graylog-storage-elasticsearch7/src/test/resources/org/graylog/storage/elasticsearch7/views/export/messages-with-old-field-types.json, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/export/ExportClient.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/export/OpenSearchExportBackend.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/export/SearchAfter.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/views/export/OpenSearchExportBackendIT.java, graylog-storage-opensearch2/src/test/resources/org/graylog/storage/opensearch2/views/export/messages-with-old-field-types.json, graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java, graylog2-server/src/test/java/org/graylog/testing/elasticsearch/ElasticsearchBaseTest.java
- The export client did not report any errors if only individual shards fail.
- The default sort order was wrong.
We did sort by "timestamp.ASC, timestamp.DESC, gl2_second_sort_field.DESC"
Change this to: "timestamp.ASC, gl2_second_sort_field.ASC"
- The ExportBackendIT tests were producing errors because the templates
were applied for '*' which included the ism indices and their
compound templates. Maybe we can use `graylog_*` for all tests, but
for now make the wildcard configurable for each test.
- Add proper cleanup between each ExportBackendIT test
- Add missing mocking. some tests were running against all indices
which is something that never happens in the real world.
- Add test for the missing sort field (gl2_second_sort_field) fix
- Add test for reporting individual shard failures …
=> Fix several search export client issues

graylog2-server/src/main/java/org/graylog2/rest/resources/system/SearchVersionResource.java, graylog2-web-interface/src/hooks/useSearchVersionCheck.ts
Update the supported search values in the `/system/searchVersion` API endpoint error messages to use supported enum values instead of hard-coded values. Recently, the `DATANODE` search version was added but was not added to the error messages in the SearchVersionResource. This change should future-proof the error messages by using the actual enum values.
Also add `datanode` as supported argument in the `useSearchVersionCheck` component.
/nocl
=> Add support for Data Node in search version checking API endpoints and component

data-node/src/main/java/org/graylog/datanode/configuration/OpensearchConfigurationProvider.java, data-node/src/main/java/org/graylog/datanode/management/OpensearchCommandLineProcess.java, data-node/src/main/java/org/graylog/datanode/management/OpensearchProcessService.java, data-node/src/main/java/org/graylog/datanode/process/OpensearchConfiguration.java
to support structured objects (lists etc.) in `opensearch.yml` config generation, we have to change the map values from String to Object
Has been manually tested with `path_repo` setting:
`path_repo = /tmp/dir1,/tmp/dir2` was converted to 
```
path.repo:
- /tmp/dir1
- /tmp/dir2
```
and OpenSearch started successfully
/nocl
=> DataNode: fix for path_repo / support Lists etc. in opensearch.yml generation

graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterForm.tsx
Previously, when creating or editing a Filter & Aggregation event definition, on the Condition page if the "Enable" checkbox is toggled there is a page error. See issue for more details: https://github.com/Graylog2/graylog2-server/issues/18786.
This looks to have been introduced in https://github.com/Graylog2/graylog2-server/pull/18742.
/nocl
See https://github.com/Graylog2/graylog2-server/issues/18786.
Locally in dev environment.
=> Update handling of Event Definition enable field to prevent errors

changelog/unreleased/pr-18825.toml, full-backend-tests/src/test/java/org/graylog/datanode/RemoteReindexingMigrationIT.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/RemoteReindexingMigrationAdapterES7.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/RemoteReindexNotAllowedException.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/RemoteReindexingMigrationAdapterOS2.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/RemoteReindexParams.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/RemoteReindexResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/actions/MigrationActionsImpl.java, graylog2-server/src/main/java/org/graylog2/indexer/datanode/RemoteReindexRequest.java, graylog2-server/src/main/java/org/graylog2/indexer/datanode/RemoteReindexingMigrationAdapter.java, graylog2-server/src/main/java/org/graylog2/indexer/migration/LogEntry.java, graylog2-server/src/main/java/org/graylog2/indexer/migration/LogLevel.java, graylog2-server/src/main/java/org/graylog2/indexer/migration/RemoteReindexIndex.java, graylog2-server/src/main/java/org/graylog2/indexer/migration/RemoteReindexMigration.java, graylog2-server/src/main/java/org/graylog2/indexer/migration/TaskStatus.java
Changes in this PR:
- The remote reindex migration now supports only async reindex, sync removed
- Migration is task based, we submit tasks and monitor them regularly
- There is now `threads` (int) param, which  configures how many tasks are running in parallel (uses Executors.newFixedThreadPool)
- The overall status of the migration is now computed from states of indices => single source of truth
- We have more information about finished index migrations. How many batches and documents, duration, problems... We can display this
- Support for logs view - latest 50 logs from migration. With log level, timestamp and message. For advanced view like in installation wizards.
Solve timeouts problems during the long running migration, increase stability, add users more control over performance. …
=> Refactor remote reindex migration to use tasks

graylog2-web-interface/src/views/components/searchbar/saved-search/SearchActionsMenu.tsx
Prior to this PR, the current title of the saved search is memoized in the `SavedSearchForm` component's state. Due to a refactoring around popovers, we are not remounting the component anymore when the saved search changes. Due to this, this PR is now forcing a remount (through changing the component's `key`) when the title changes.
Fixes #18832.
/nocl Regression was introduced after last release.
=> Ensure that search dialog for saved search is remounted.

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/MoreSearchAdapterOS2.java, graylog2-server/src/main/java/org/graylog/events/search/EventsSearchParameters.java, graylog2-server/src/main/java/org/graylog/events/search/MoreSearch.java, graylog2-server/src/main/java/org/graylog2/indexer/searches/Sorting.java
Add optional support for sorting Events by unmapped fields. For example, individual event.scores values.
/nocl
https://github.com/Graylog2/graylog-plugin-enterprise/pull/6893
Adds similar capability as was added for Events List widget in https://github.com/Graylog2/graylog2-server/pull/18826.
=> Add optional support for sorting Events by unmapped fields

data-node/src/main/java/org/graylog/datanode/configuration/OpensearchConfigurationProvider.java, data-node/src/main/java/org/graylog/datanode/management/OpensearchProcessService.java
In several places, we rely on `Preflight.FINISHED` so we have to make sure that it has been written during an insecure startup. Because in that case we don't do a preflight.
This is only a temp fix that should be replaced in the future.
/nocl
fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/6835
=> DataNode: on insecure startup, always assume that preflight is finished

data-node/src/main/java/org/graylog/datanode/Configuration.java, data-node/src/main/java/org/graylog/datanode/configuration/DatanodeConfiguration.java, data-node/src/main/java/org/graylog/datanode/configuration/DatanodeConfigurationProvider.java, data-node/src/main/java/org/graylog/datanode/configuration/variants/OpensearchSecurityConfiguration.java, data-node/src/main/java/org/graylog/datanode/process/OpensearchConfiguration.java
You can specify the Java heap setting for OpenSearch now. It's only one config setting as both (initial and max) have to be the same size otherwise the OpenSearch boot fails.
/nocl
=> DataNode: Added OpenSearch heap setting

graylog2-server/src/main/java/org/graylog2/configuration/IndexSetsDefaultConfiguration.java, graylog2-server/src/main/java/org/graylog2/configuration/IndexSetsDefaultConfigurationFactory.java, graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetConfigFactory.java, graylog2-server/src/main/java/org/graylog2/migrations/MaintenanceStrategiesHelper.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexSetDefaultsResource.java, graylog2-server/src/test/java/org/graylog2/migrations/V202211021200_CreateDefaultIndexDefaultsConfigTest.java
For existing Graylog installations the legacy rotation and retention default configuration is used if configured. Otherwise the data tiering default configuration will be used. This is important for index sets created by Illuminate.
fixes Graylog2/graylog-plugin-enterprise#6889
/nocl
=> use legacy default rotation/retention config for existing installations

changelog/unreleased/pr-18769.toml, graylog2-server/src/main/java/org/graylog/aws/inputs/cloudtrail/CloudTrailInput.java, graylog2-server/src/main/java/org/graylog/integrations/aws/inputs/AWSInput.java, graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackService.java, graylog2-server/src/main/java/org/graylog2/inputs/misc/jsonpath/JsonPathInput.java, graylog2-server/src/main/java/org/graylog2/inputs/random/FakeHttpMessageInput.java, graylog2-server/src/main/java/org/graylog2/plugin/inputs/MessageInput.java, graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackServiceTest.java, graylog2-server/src/test/java/org/graylog2/migrations/V20230601104500_AddSourcesPageV2Test.java, graylog2-server/src/test/java/org/graylog2/rest/resources/system/contentpacks/CatalogResourceTest.java
/prd Graylog2/graylog-plugin-enterprise#6854
When installing a contentpack in cloud environment, ignore any inputs that are not cloud-compatible.
Method `MessageInput.Descriptor:isCloudCompatible()` is changed to be a static method. We can then use reflection prior to instantiating the class to validate that the class is cloud-compatible.
See Graylog2/graylog-plugin-enterprise#5997
Local testing and unit test
=> Check inputs for cloud compatibility when installing content pack

graylog2-web-interface/src/components/indices/data-tiering/DataTieringConfiguration.tsx
Part of https://github.com/Graylog2/graylog-plugin-enterprise/issues/6916
/nocl
/jpd Graylog2/graylog-plugin-enterprise#6933
Move the _Archive before Deletion_ checkbox out of the warm tiering config.
This should be configurable when the enterprise plugin is installed, even if the warm tier is not ready to be configured.
=> Display archive before deletion checkbox independent of warm tier config

graylog2-web-interface/src/components/navigation/MainNavbar.tsx, graylog2-web-interface/src/components/security/teaser/TeaserPageLayout.tsx
Adds security license check for security drop-down nav items. In this way the application mounts the list of security features that have available a teaser page.
/nocl
/jenkis-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/6938
=> fix(6811): Add condition to navigation items to check for license

graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java
/nocl
I think the small code change is self explanatory.
Fixes #18856 
Before it was not possible to change the (optional) description of a Stream to an empty string.
I cherry picked the change to the 5.2 branch and updated the corresponding .jar file on my server. Subsequently, I successfully modified the description to an empty string.
I also made a second test, where I removed the description field from the body of the http request.
It's worth noting that I haven't yet verified these modifications on the master branch. 
With the jar from the master branch it did not start on my server, which is running 5.2.
=> Always set stream description on edit

UPGRADING.md, changelog/unreleased/pr-17483.toml
This reverts commit 1d0e3a25a7ec631c96619cae9d5d0beba27fb2eb.
This is an edge case where the change was actually not required in master but only in the 6.0 branch.
/nocl
=> Revert "Add changelog + update notes for changes to trusted header auth (#18892)"

graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.tsx
Back port fix to not show warning when submitting the form to create a new event definition
/nocl
=> fix(18771): BP set IsDerty to false on submit

changelog/unreleased/issue-18288.toml, graylog2-web-interface/src/views/components/searchbar/completions/FieldValueCompletion.test.ts, graylog2-web-interface/src/views/components/searchbar/completions/FieldValueCompletion.ts
Please note: This PR needs a backport for `5.2` and `6.0`.
As described in https://github.com/Graylog2/graylog2-server/issues/18288 the field value suggestions are currently not being displayed when the field name is in the middle of a query. This PR is fixing this problem.
Fixes #18288
=> Display field value suggestions when field name is in the middle of the search query.

changelog/unreleased/issue-18915.toml, graylog2-web-interface/src/views/components/widgets/events/EventsList/EventsList.test.tsx, graylog2-web-interface/src/views/components/widgets/events/EventsList/EventsList.tsx, graylog2-web-interface/src/views/components/widgets/events/EventsList/RowActions.tsx
Please note, this is a backport of https://github.com/Graylog2/graylog2-server/pull/18945 for `6.0`.
This PR contains some improvements for the events widget pagination logic.
We are unifying the behaviour with the message list widget. We are now:
- resetting the pagination when the search is being executed
- stopping the auto refresh when using the pagination
- displaying errors which can occur when reexecuting the search.
Fixes https://github.com/Graylog2/graylog2-server/issues/18915
=> Reset events widget pagination when executing search. `6.0`

changelog/unreleased/issue-18915.toml, graylog2-web-interface/src/views/components/widgets/events/EventsList/EventsList.test.tsx, graylog2-web-interface/src/views/components/widgets/events/EventsList/EventsList.tsx, graylog2-web-interface/src/views/components/widgets/events/EventsList/RowActions.tsx
This PR contains some improvements for the events widget pagination logic.
We are unifying the behaviour with the message list widget. We are now:
- resetting the pagination when the search is being executed
- stopping the auto refresh when using the pagination
- displaying errors which can occur when reexecuting the search.
Fixes https://github.com/Graylog2/graylog2-server/issues/18915
=> Reset events widget pagination when executing search.

changelog/unreleased/pull-18954.toml, graylog2-web-interface/src/views/logic/widgets/events/EventsWidget.ts
**Note:** This needs a backport to `6.0`.
This PR is reverting an implementation detail where we configured an explicit "All Time" timerange for the events widget, which lead to problems and confusion. With this PR, it is consistent with the search/widget's configured time range.
Fixes #18914.
=> Tieing events widget to configured time range.

changelog/unreleased/pr-18907.toml, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/RemoteReindexingMigrationAdapterOS2.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/TaskError.java
Support caused_by field in task errors during remote reindex migration
=> Backport: Support caused_by field in task errors during remote reindex migration

changelog/unreleased/pull-18954.toml, graylog2-web-interface/src/views/logic/widgets/events/EventsWidget.ts
**Note:** This is a backport of https://github.com/Graylog2/graylog2-server/pull/18954 for `6.0`.
This PR is reverting an implementation detail where we configured an explicit "All Time" timerange for the events widget, which lead to problems and confusion. With this PR, it is consistent with the search/widget's configured time range.
Fixes #18914.
=> Tieing events widget to configured time range. `6.0`

changelog/unreleased/issue-18949.toml, graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionLink.tsx, graylog2-web-interface/src/components/events/events/hooks/useEventDefinition.tsx, graylog2-web-interface/src/views/components/widgets/events/EventsList/EventDetails.test.tsx, graylog2-web-interface/src/views/components/widgets/events/EventsList/EventDetails.tsx, graylog2-web-interface/src/views/components/widgets/events/EventsList/EventsTable.tsx, graylog2-web-interface/src/views/components/widgets/events/EventsList/EventsTableRow.test.tsx, graylog2-web-interface/src/views/components/widgets/events/EventsList/EventsTableRow.tsx, graylog2-web-interface/src/views/components/widgets/events/EventsList/RowActions.tsx, graylog2-web-interface/src/views/components/widgets/events/filters/EventDefinitionName.tsx, graylog2-web-interface/src/views/components/widgets/events/types.ts, graylog2-web-interface/test/helpers/mocking/EventAndEventDefinitions_mock.ts
With this PR we are fixing the permissions checks for the events widget. We are now:
- Only displaying the event definitions name in the events widget, when the user has the required permissions.
- Only showing the replay search action when the user has the required permissions for the related event definition
- Only fetching the event definition for the event details when the user has the required permissions
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/7001
Fixes https://github.com/Graylog2/graylog2-server/issues/18949
=> Only fetch event definitions in events widget, when user has required permissions

graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.tsx, graylog2-web-interface/src/views/components/widgets/TimerangeInfo.tsx, graylog2-web-interface/src/views/components/widgets/Widget.tsx, graylog2-web-interface/src/views/logic/widgets/Widget.ts
This PR contains changes required for https://github.com/Graylog2/graylog-plugin-enterprise/pull/7003. Before it was possible that a widget had fixed filters and returned all available records, but the widget time range info still referred to the search time range.
/nocl
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/7003
=> Fix widget time range info when widget has fixed filters and returns all records. `6.0`

changelog/unreleased/issue-18949.toml, graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionLink.tsx, graylog2-web-interface/src/components/events/events/hooks/useEventDefinition.tsx, graylog2-web-interface/src/views/components/widgets/events/EventsList/EventDetails.test.tsx, graylog2-web-interface/src/views/components/widgets/events/EventsList/EventDetails.tsx, graylog2-web-interface/src/views/components/widgets/events/EventsList/EventsTable.tsx, graylog2-web-interface/src/views/components/widgets/events/EventsList/EventsTableRow.test.tsx, graylog2-web-interface/src/views/components/widgets/events/EventsList/EventsTableRow.tsx, graylog2-web-interface/src/views/components/widgets/events/EventsList/RowActions.tsx, graylog2-web-interface/src/views/components/widgets/events/filters/EventDefinitionName.tsx, graylog2-web-interface/src/views/components/widgets/events/types.ts, graylog2-web-interface/test/helpers/mocking/EventAndEventDefinitions_mock.ts
**Please note**, this is a backport of https://github.com/Graylog2/graylog2-server/pull/18953 for `6.0`
With this PR we are fixing the permissions checks for the events widget. We are now:
- Only displaying the event definitions name in the events widget, when the user has the required permissions.
- Only showing the replay search action when the user has the required permissions for the related event definition
- Only fetching the event definition for the event details when the user has the required permissions
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/7004
Fixes https://github.com/Graylog2/graylog2-server/issues/18949
=> Only fetch event definitions in events widget, when user has required permissions `6.0`

changelog/unreleased/issue-18975.toml, graylog2-web-interface/src/views/components/aggregationwizard/FieldSelect.tsx
Please note, this is a backport of https://github.com/Graylog2/graylog2-server/pull/18976 for 6.0
**Before**
light mode:
dark mode:
**After**
light mode:
dark mode:
Fixes #18975
=> Fixing text color for unqualified fields in field select. `6.0`

changelog/unreleased/pr-19056.toml, data-node/src/main/java/org/graylog/datanode/management/OpensearchCommandLineProcess.java
Actively wait for opensearch process termination in the datanode
Sometimes during certificate provisioning and/or data migrations we encountered an opensearch process that has not been properly terminated, but we have already started a new one. This leads to occupied ports and everything falls apart. Let's rather actively wait for the termination, count and log all attempts and only then continue.
:
=> Wait for opensearch process termination

graylog2-server/src/main/java/org/graylog/aws/inputs/cloudtrail/CloudTrailInput.java, graylog2-server/src/main/java/org/graylog/integrations/aws/inputs/AWSInput.java, graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackService.java, graylog2-server/src/main/java/org/graylog2/inputs/misc/jsonpath/JsonPathInput.java, graylog2-server/src/main/java/org/graylog2/inputs/random/FakeHttpMessageInput.java, graylog2-server/src/main/java/org/graylog2/plugin/inputs/CloudCompatible.java, graylog2-server/src/main/java/org/graylog2/plugin/inputs/MessageInput.java
/nocl (bug in unreleased change)
/prd Graylog2/graylog-plugin-enterprise#7054
Relates to Graylog2/graylog-plugin-enterprise#7019
Graylog2/graylog2-server#18769 changed the signature of `MessageInput.Descriptor` methods to be static, to support pre-install compatibility checks for content packs. However, other parts of the code rely on dynamic overriding of these methods. 
Instead we introduce a class annotation `@CloudCompatible` to indicate that an input class is compatible with Cloud.
- Can create inputs in Cloud and on-prem
- Cloud only shows cloud-compatible inputs; on-prem shows all
- Cloud-incompatible inputs are ignored when importing a content pack in Cloud
Note: an exception is thrown when uninstalling a content pack. It is related to audit logging and is not relevant to this …
=> Cloud compatibility annotation

graylog2-server/src/main/java/org/graylog2/database/jackson/legacy/LegacyInsertManyResult.java, graylog2-server/src/main/java/org/graylog2/database/jackson/legacy/LegacyInsertOneResult.java, graylog2-server/src/main/java/org/graylog2/database/jackson/legacy/LegacyUpdateOneResult.java
We added a compatibility layer to emulate the deprecated Mongojack 2.x API. Under the hood, it reads back written documents right after writing to return them when a user calls `org.mongojack.WriteResult#getSavedObject`.
As a safety net to prevent this from failing if users configure a non-default MongoDB read preference, we force the fetch operations to be executed with read preference `primary`.
Even though it's not supported, users might have configured a non-default [read preference](https://www.mongodb.com/docs/manual/core/read-preference/) in their MongoDB connection string. A read preference of `secondaryPreferred` or `secondary` will probably have caused issues in Graylog before, but it might have worked well enough for users to tolerate.
With the move away from Mongojack 2 in 6.0 …
=> Set readPreference=primary for reading back write results

graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerFactory.java
Adding a preflight check for the reporting binaries so that we fail more early than during report generation needs linking the binaries instead of copying them after container start. see https://github.com/Graylog2/graylog-plugin-enterprise/pull/6988
/nocl
=> Linking reporting binaries into the TestContainer

graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchJob.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchJobDTO.java
Wrong check for execution completion fixed.
It was implemented properly for "cancel" status, improperly for "done" status.
/nocl
This error caused executions on empty search types (i.e. with fresh new Dashboards, Dashboard pages with no widgets) to never return "Done" status. Because of that, FE was asking for status infinitely.
Manually.
=> Wrong check for execution completion fixed

changelog/unreleased/issue-18288.toml, graylog2-web-interface/src/views/components/searchbar/completions/FieldValueCompletion.test.ts, graylog2-web-interface/src/views/components/searchbar/completions/FieldValueCompletion.ts
Please note: This PR is a backport of https://github.com/Graylog2/graylog2-server/pull/18952 for `5.2`.
As described in https://github.com/Graylog2/graylog2-server/issues/18288 the field value suggestions are currently not being displayed when the field name is in the middle of a query. This PR is fixing this problem.
Fixes #18288
=> Display field value suggestions when field name is in the middle of the search query. `5.2`

changelog/unreleased/issue-19012.toml, graylog2-web-interface/src/components/sidecars/sidecars/SidecarRow.jsx
**Please note**, this is a backport of https://github.com/Graylog2/graylog2-server/pull/19128 for `6.0`.
This PR is fixing an error which has been introduced with https://github.com/Graylog2/graylog2-server/pull/18558 when renaming theme variables. It occurred when the overview contains inactive sidecars.
=> Fixing "unknown format" error on sidecar overview page `6.0`.

graylog2-web-interface/src/components/configurations/SidecarConfig.tsx
/nocl Just a change in wording
Resolves #16325 
Improve wording for error message, when sidecar config Update interval is set too high.
=> Improve wording of error message in sidecar config

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/export/response/AggregationWidgetExportResponse.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/export/response/AggregationWidgetExportResponseWriter.java, graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/ObjectMapperProvider.java, graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/XmlMapperProvider.java, graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/YamlMapperProvider.java, graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/config/ObjectMapperConfiguration.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/export/response/AggregationWidgetExportResponseTest.java
ObjectMappers' config unification - they all get the same settings.
Data is not stored in strings anymore (as was initially done because of csv format), but can be exported in different formats.
/nocl
Manually.
=> ObjectMappers' config unification

changelog/unreleased/pr-19241.toml, data-node/src/main/java/org/graylog/datanode/metrics/ConfigureMetricsIndexSettings.java, data-node/src/main/java/org/graylog/datanode/opensearch/OpensearchProcess.java, data-node/src/main/java/org/graylog/datanode/opensearch/OpensearchProcessImpl.java, data-node/src/main/java/org/graylog/datanode/periodicals/MetricsCollector.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/DataStreamAdapterOS2.java
Fixes generation of data stream system indices with a wrong number of replicas on single-node setups (fixes #19010) 
and generation of metrics data stream and ism settings only from the leader node (fixes #18830)
fixes #18830
fixes #19010
=> Fix data node metrics data stream generation

changelog/unreleased/issue-19007.toml, graylog2-server/src/main/java/org/graylog/events/processor/DBEventDefinitionService.java
Returns to using `PaginatedDBService.findPaginatedWithQueryFilterAndSort` when searching event definitions. Event definition configs are then repopulated with any associated Search Filters after the filter has been applied. 
closes #19007 
local dev testing
=> Use filter when searching DB for event definitions

graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/db/SearchDbService.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/db/SearchesCleanUpJob.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/db/StaticReferencedSearch.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/db/StaticSearchLoader.java, graylog2-server/src/main/java/org/graylog2/plugin/PluginModule.java, graylog2-server/src/main/java/org/graylog2/plugin/inject/Graylog2Module.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/db/SearchesCleanUpJobTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/db/SearchesCleanUpJobWithDBServicesTest.java
The `SearchCleanupJob` previously used a fixed previous duration (set at in constructor at injection time), which resulted in the periodical only ever cleaning up expired searches once at server startup time (thanks to @ryan-carroll-graylog  for noticing this). The migration is intended to perform the cleanup once per hour. This PR fixes that, so that the expired reports threshold `mustBeOlderThan` is recalculated on each run, which allows newly expired non-referenced searches to be deleted each time the job runs.
Also adds support for not deleting static referenced search ids. See https://github.com/Graylog2/graylog-plugin-enterprise/pull/7107 for context.
/nocl fixes/adjusts backend process that does not affect visible user functionality
Manual testing by overriding the initial delay …
=> Search Cleanup Job: Fix interval checking, skip static referenced searches

changelog/unreleased/pr-19225.toml, changelog/unreleased/pr-19276.toml, graylog2-web-interface/src/components/bootstrap/MenuItem.tsx
**Note:** This is a backport of #19225 to `6.0`.
With the migration of the `MenuItem` component to Mantine, we introduced a regression leading to client-side routing (rendering a new page without a full page refresh) not working when an `href` prop is passed to the `MenuItem` component.
This PR is now fixing this by using the `Link`-component instead of a n `a`-element when the `href` prop is specified, is a relative URL and `target`/`rel` are not specified.
=> Fix client-side routing in `MenuItem` component. (`6.0`)

changelog/unreleased/pr-19271.toml, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/rest/JournalEstimate.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/rest/MigrationStateResource.java, graylog2-server/src/test/java/org/graylog/plugins/views/storage/migration/state/rest/MigrationStateResourceTest.java
calculate estimated possible downtime based on journal size and current throughput
backend for #19270 
in-place migration / endpoint
=> datanode: add possible downtime estimate

changelog/unreleased/issue-19272.toml, graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/GraylogCertificateProvisioningPeriodical.java
This PR removes http client per datanode for preflight connections checks. Instead, it reuses one shared client, which is created only when needed. Additionally we don't propagate the http response through the whole retryer logic, as we can't guarantee that it will be closed. So we rather extract the needed information during each call, close the response and propagate only a record with status and message. 
Fixes https://github.com/Graylog2/graylog2-server/issues/19272
Existing provisioning integration test
=> Reuse http client for all preflight connection checks

graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/db/SearchDbService.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/db/SearchesCleanUpJob.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/db/StaticReferencedSearch.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/db/StaticSearchLoader.java, graylog2-server/src/main/java/org/graylog2/plugin/PluginModule.java, graylog2-server/src/main/java/org/graylog2/plugin/inject/Graylog2Module.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/db/SearchesCleanUpJobTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/db/SearchesCleanUpJobWithDBServicesTest.java
Backport https://github.com/Graylog2/graylog2-server/pull/19117 to `6.0`.
/nocl
=> Backport 6.0: Search Cleanup Job: Fix interval checking, skip static referenced searches

changelog/unreleased/issue-18288.toml, graylog2-web-interface/src/views/components/searchbar/completions/FieldValueCompletion.test.ts, graylog2-web-interface/src/views/components/searchbar/completions/FieldValueCompletion.ts
Please note: This PR is a backport of https://github.com/Graylog2/graylog2-server/pull/18952 for `6.0`.
As described in https://github.com/Graylog2/graylog2-server/issues/18288 the field value suggestions are currently not being displayed when the field name is in the middle of a query. This PR is fixing this problem.
Fixes #18288
=> Display field value suggestions when field name is in the middle of the search query. `6.0`

changelog/unreleased/issue-19092.toml, graylog2-web-interface/src/components/common/HoverForHelp.tsx
**Please note**, this is a backport of https://github.com/Graylog2/graylog2-server/pull/19093 for `6.0`.
This PR is fixing the problem described in https://github.com/Graylog2/graylog2-server/issues/19092
Fixes https://github.com/Graylog2/graylog2-server/issues/19092
=> Fix display tooltip for help icons in disabled menu items. `6.0`

changelog/unreleased/issue-19014.toml, graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationFormContainer.jsx
**Please note**, this is a backport of https://github.com/Graylog2/graylog2-server/pull/19073 for `6.0`
Before this change, when you create or update an event notification, you will see the following confirm dialog on submit. 
This PR is fixing the bug by implementing a fix similar to https://github.com/Graylog2/graylog2-server/pull/18880
Please keep in mind while testing, that the confirm dialog is not showing up in development mode, by default.
=> Do not show confirm dialog when saving event notification. `6.0`

graylog2-web-interface/src/components/datanode/DataNodeList/DataNodeList.tsx, graylog2-web-interface/src/pages/DataNodePage.tsx
/nocl
The datanode doesn't use leader flags anymore. It shouldn't be visible anywhere in the UI.
=> Removed references to leader datanodes in UI

changelog/unreleased/issue-19195.toml, graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
=> add sidecar filebeat collector for windows again

changelog/unreleased/issue-18809.toml, graylog2-web-interface/src/views/components/DashboardSearchBarForm.tsx, graylog2-web-interface/src/views/components/TimeRangeValidation.test.ts, graylog2-web-interface/src/views/components/TimeRangeValidation.ts, graylog2-web-interface/src/views/components/searchbar/SearchBarForm.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/TimeRangeFilter.test.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TabKeywordTimeRange.test.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TabKeywordTimeRange.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TimeRangePicker.relativeTimeRange.test.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TimeRangePicker.test.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TimeRangePicker.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TimeRangePickerTabs.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/migrateTimeRangeToNewType.ts, graylog2-web-interface/src/views/components/searchbar/validate.ts, graylog2-web-interface/src/views/components/widgets/Widget.aggregations.test.tsx
**Please note:** This is a backport of https://github.com/Graylog2/graylog2-server/pull/18879 for `6.0`
With this PR we are separating the time range validation from time range preview in time keyword tab of the range picker.
This approach has multiple advantages
- We are no longer using the `validate` prop of the keyword formik field and have all the validation in the form validate function
- We no longer need to maintain the `validatingKeyword` state to disable the submit button while the keyword is being validated
- The keyword preview and validation logic is a lot simpler and less error-prone
The main disadvantage:
- we are currently doing two requests to test the keyword time range in the date time picker, on change. One for the validation and one for the preview.
This restructuring …
=> Decouple keyword time range validation from keyword time range preview in time range picker. `6.0`

graylog2-web-interface/src/components/bootstrap/SegmentedControl.md, graylog2-web-interface/src/components/bootstrap/SegmentedControl.tsx, graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.tsx
Please note: This PR is required for https://github.com/Graylog2/graylog-plugin-enterprise/pull/7240
This PR contains a small refactoring for the `SegmentedControl` component. We are:
- renaming the `handleChange` prop to `onChange` to follow our naming convention and we are simplifying the related type.
- implementing a generic type for the value options, to avoid the need to use `as` when providing the `onChange` function
- removing the `Array<string>` for the `data` prop. It is being supported by the mantine `SegmentedControl` component, but having a look at the `Select` component, future maintenance will be easier if we allow only one format for these options.
/nocl
=> Small refactoring for `SegmentedControl` component.

graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/BaseParserTest.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/messages/MessageCreationLoopPreventionTest.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/parser/PipelineRuleParserTest.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/parser/PrecedenceTest.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/rulebuilder/db/migrations/V20220522125200_AddSetGrokToFieldsExtractorFragmentsTest.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/rulebuilder/db/migrations/V20230720161500_AddExtractorFragmentsTest.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/rulebuilder/db/migrations/V20230724092100_AddFieldConditionsTest.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/rulebuilder/db/migrations/V20230915095200_AddSimpleRegexTest.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/rulebuilder/parser/BaseFragmentTest.java
I was experimenting with tests in another PR so I thought I could as well convert the existing tests to Junit 5 while I'm at it.
/nocl
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/7270
=> Convert pipeline parser tests to Junit 5

graylog2-web-interface/src/components/common/Card.tsx
With this PR is will be possible to define  a `tabIndex` for the `Card` component, this allows users to focus the card. By default it will not be possible to focus a card.
/nocl
=> Make `Card` component focusable.

graylog2-web-interface/packages/jest-preset-graylog/lib/setup-files/mock-IntersectionObserver.js
This this PR we are extending the `IntersectionObserver` mock with the `disconnect` method. This is required for testing the `Carousel` component.
/nocl
=> Extend mock for `IntersectionObserver` with `disconnect` method.

graylog2-web-interface/src/util/DateTime.ts
This PR adds a new date time format `YYYY-MM-DD HH:mm` for the `DateTime` utils. `YYYY-MM-DD HH:mm:ss` is the default format in the Ui and we try to limit the amount of date time formats we display, but in some cases the seconds are not that relevant and not displaying them looks cleaner.
/nocl
=> Add new date time format `YYYY-MM-DD HH:mm` for `DateTime` utils.

graylog2-web-interface/src/pages/ShowMessagePage.test.tsx, graylog2-web-interface/src/pages/ShowMessagePage.tsx, graylog2-web-interface/src/views/hooks/useMessage.ts
This PR is Implementing `Messages.search` from `@graylog/server-api` for the `useMessage` hook. In a follow-up PR I will replace the remaining usages of `MessagesActions.loadMessage` with the `useMessage` hook.
/nocl
=> Implement `Messages.search` from `@graylog/server-api` for `useMessage` hook.

graylog2-server/src/main/java/org/graylog2/configuration/HttpConfiguration.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/CookieFactory.java, graylog2-server/src/test/java/org/graylog2/rest/resources/system/CookieFactoryTest.java
Set this value for training instances. See [slack discussion in dev](https://graylog.slack.com/archives/C024KUJUB/p1715800811349729) for context. 
/nocl
=> Conditionally set authentication cookie sameSite for training instances

graylog2-server/src/main/java/org/graylog2/configuration/HttpConfiguration.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/CookieFactory.java
* Conditionally set authentication cookie sameSite value based on config values
backport #19356 to 6.0 so Training/ProServe can have it in a stable build.
/nocl
=> Backport 6.0: Conditionally set authentication cookie sameSite for training instances

changelog/unreleased/issue-18932.toml, graylog2-web-interface/src/components/simulator/SimulationResults.jsx
This PR is fixing the problem described in https://github.com/Graylog2/graylog2-server/issues/18932.
The issue is related to the refactoring we did for the `Menu` component. The `Menu` no longer supports the `onSelect` prop. This is the only case where we made use of it.
Fixes https://github.com/Graylog2/graylog2-server/issues/18932
=> Fix selecting option in more results select on pipeline simulator page.

changelog/unreleased/issue-18932.toml, graylog2-web-interface/src/components/simulator/SimulationResults.jsx
Please note, this is a backport of https://github.com/Graylog2/graylog2-server/pull/19413 for `6.0`
This PR is fixing the problem described in https://github.com/Graylog2/graylog2-server/issues/18932.
The issue is related to the refactoring we did for the `Menu` component. The `Menu` no longer supports the `onSelect` prop. This is the only case where we made use of it.
=> Fix selecting option in more results select on pipeline simulator page. (`6.0`)

changelog/unreleased/pr-19404.toml, graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionActions.tsx
Removes `Duplicate` and disables `Delete` action menu options for sigma event definitions.
Deleting or duplicating a sigma event definition from the event definition UI does not delete or copy the parent sigma rule, causing confusion and unexpected results.
=> Disable sigma event definition duplicate and delete options

graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerFactory.java
`container.withStartupTimeout()` works (according to the code) by retrieving the waiting strategy and setting the timeout on the resulting object. If we set another waiting strategy  later (as we do before this fix), I am of the opinion, that the timeout falls back to the default - which is probably 30sec and makes sometimes fail the startup.
/nocl
=> IT Test fix: setting the timeout after setting the waiting strategy

graylog2-web-interface/src/components/common/Spinner.tsx
This PR adds a container for the `Spinner` component. This makes the component a bit more independent of the parent element styling.
I noticed one case which previously looked like this, because of the parent element styling:
Now it looks like this:
/nocl
=> Add container for `Spinner` component.

graylog2-server/src/main/java/org/graylog/plugins/views/search/views/WidgetConfigDTO.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/units/WithConfigurableUnits.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/AggregationConfigDTO.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/events/EventsWidgetConfigDTO.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/messagelist/MessageListConfigDTO.java
Units are stored in views.
/jpd Graylog2/graylog-plugin-enterprise#7379
/nocl
It was decided that we do not want to store units in searches, but in views instead. This PR covers that : https://github.com/Graylog2/graylog2-server/pull/19458
It was identified that units are a feature of fields, not metrics.
Even if FE uses units on the metric level, they have to be stored as a field->unit mapping.
=> Units are stored in views

graylog2-web-interface/src/components/common/IconButton.tsx, graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministration.tsx, graylog2-web-interface/src/views/components/searchbar/QueryHistoryButton.tsx, graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRules.tsx, graylog2-web-interface/src/views/components/widgets/ReplaySearchButton.test.tsx, graylog2-web-interface/src/views/components/widgets/ReplaySearchButton.tsx
With this PR we are requiring the `title` prop for the `IconButton` component. The component just renders a button with an icon and should always have a title. I only found one case where it is wrapped with a link, which already has a title. In this case the `IconButton` does not need a title, but in my opinion it still makes sense to require the title in general.
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/7376
/nocl
=> Require `title` for `IconButton`.

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/export/ElasticsearchExportBackend.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/export/ElasticsearchExportBackendIT.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/export/OpenSearchExportBackend.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/views/export/OpenSearchExportBackendIT.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/export/ExportMessagesCommand.java
Fetch only fields needed by export.
/nocl
Performance - do not get what you don't need from the search engine.
Maybe be useful for future development of [#5616.](https://github.com/Graylog2/graylog-plugin-enterprise/issues/5616)
Manually and with existing tests re-run.
=> Fetch only fields needed by export

graylog2-server/src/main/java/org/graylog/plugins/views/search/Search.java
There a was name conflict between `ImmutableSet#of` and `ParameterProvider#of`. Even though the compiler appears to have coped with it, Intellij Idea was complaining about it.
/nocl
=> Fix conflicting static import of ImmutableSet#of

graylog2-server/src/main/java/org/graylog/events/processor/EventDefinitionDto.java
Clarify invalid message field error on event definition fields by adding accepted characters and spaces aren't allowed.
/nocl just clarifying an error message
closes #13974
=> Clarify invalid message field error on event definition fields

graylog2-web-interface/src/logic/rest/FetchProvider.ts, graylog2-web-interface/src/util/FileDownloadUtils.ts
This PR adds utils to download binary files. In this case, we are using `response.blob() ` method instead of `response.text()` to represent response data in correct binary format 
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/7355
/nocl
=> Add util to download binary files

changelog/unreleased/issue-19098.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/RemoveMultipleFields.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/RemoveSingleField.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/removeField.txt, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/removeFieldsByName.txt, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/removeFieldsByRegex.txt, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/removeSingleField.txt
5.2 backport of #19268
* new pipeline functions remove_single_field and remove_multiple_fields
* CL
* improve rulebuilder descriptions
* compile regex and other feedback changes
* pre-compile pattern
* UI string improvements
(cherry picked from commit https://github.com/Graylog2/graylog2-server/commit/4a1cbb4dcb8563a6686e0709040dea75ed831359)
=> Backport 5.1: New pipeline functions remove_single_field and remove_multiple_fields

changelog/unreleased/issue-19098.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/RemoveMultipleFields.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/RemoveSingleField.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/removeFieldsByName.txt, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/removeFieldsByRegex.txt, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/removeSingleField.txt
5.2 backport of #19268
* new pipeline functions remove_single_field and remove_multiple_fields
* CL
* improve rulebuilder descriptions
* compile regex and other feedback changes
* pre-compile pattern
* UI string improvements
(cherry picked from commit https://github.com/Graylog2/graylog2-server/commit/4a1cbb4dcb8563a6686e0709040dea75ed831359)
=> Backport 5.2: New pipeline functions remove_single_field and remove_multiple_fields

changelog/unreleased/pr-19629.toml, pom.xml
Backport of #19256
Several projects reported memory issues related to Jackson version 2.17.0. See e.g. [here](https://github.com/opensearch-project/OpenSearch/issues/13927) and [here](https://github.com/trinodb/trino/issues/21356).
The issue has been [fixed in Jackson version 2.17.1](https://github.com/FasterXML/jackson-core/issues/1256).
We haven't received any reports of Graylog being affected, but as a safety measure, we are backporting the Jackson update to the fixed version.
Bumps [com.fasterxml.jackson:jackson-bom](https://github.com/FasterXML/jackson-bom) from 2.17.0 to 2.17.1.
=> Backport: Bump com.fasterxml.jackson:jackson-bom from 2.17.0 to 2.17.1 (#19256)

changelog/unreleased/pr-19598.toml, graylog2-server/src/main/java/org/graylog2/rest/resources/search/SearchResource.java
Before this change, errors that occurred in queries in the legacy searches were not shown in the API response. Now these errors are propagated into an exception that shows in the response.
fixes #14646
=> Propagate errors in legacy searches

graylog2-web-interface/src/components/common/PageHeader.tsx
This PR is a follow-up for https://github.com/Graylog2/graylog-plugin-enterprise/pull/7283. It removes the no longer needed usage of the `Tooltip` component when used in combination with the `OverlayTrigger`.
/nocl
=> Remove no longer needed usage of tooltip component.

changelog/unreleased/issue-19643.toml, graylog2-web-interface/src/components/common/ClipboardButton.tsx
**Note:** This needs a backport to `6.0`.
This PR is restoring `ClipboardButton`'s functionality to work in non-secure context. In a previous refactoring (#17472), the component was made to use `CopyButton` from Mantine, which works only in secure contexts (+ `localhost`), unfortunately. This PR is now restoring it by removing the usage of Mantine's `CopyButton` and implements an own component for this, which uses our own `copyToClipboard` abstraction, which falls back to a legacy approach in non-secure contexts.
Fixes #19643.
=> Restore `ClipboardButton` to work in non-secure contexts.

changelog/unreleased/issue-19643.toml, graylog2-web-interface/src/components/common/ClipboardButton.tsx
**Note:** This is a backport of #19654 to `6.0`.
This PR is restoring ClipboardButton's functionality to work in non-secure context. In a previous refactoring (#17472), the component was made to use CopyButton from Mantine, which works only in secure contexts (+ localhost), unfortunately. This PR is now restoring it by removing the usage of Mantine's CopyButton and implements an own component for this, which uses our own copyToClipboard abstraction, which falls back to a legacy approach in non-secure contexts.
Fixes #19643.
=> Restore `ClipboardButton` to work in non-secure contexts. (`6.0`)

changelog/unreleased/issue-7370.toml, graylog2-web-interface/src/components/navigation/Navigation.tsx, graylog2-web-interface/src/routing/AppRouter.test.tsx, graylog2-web-interface/src/views/spec/CreateNewDashboard.it.tsx
Make home nav icon navigate to the active perspective Welcome page.
closes: Graylog2/graylog-plugin-enterprise#7370
Before the icon was navigating to the General UI welcome page since the route was hard-coded. With this PR we use the useActivePerspective hook to get the active perspective Welcome page URL.
Updated unit test to account for the hook
=> fix(7370): Updated home nav icon to open active perspective welcome page

graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/events/EventList.java
Event list can accept ex. state with limit instead of page/perpage.
/nocl
Currently, when we want to get some number of top elements for different document-based search types (messages, events, investigation lists), we have to express that need with different execution state objects for each of them.
So, request like "give me first 42 documents" translates to this execution state object in case of messages
```
"search_types" :
{
"9602cdb3-528d-4f1f-852c-5a0021c92dfd" : {
"limit" : 42
}
}
```
and this in case of events:
```
"search_types" :
{
"9602cdb3-528d-4f1f-852c-5a0021c92dfd" : {
"page": 1,
"per_page": 42
}
}
```
I'd like to avoid a need to make this choice and be able to use `limit` everywhere for this use case.
If this gets accepted, similar change will be made for investigation …
=> Event list can accept ex. state with limit instead of page/perpage

changelog/unreleased/pr-19600.toml, graylog2-web-interface/src/pages/ShowMessagePage.tsx
Before this change the field types were missing for the message fields on the message details page (`/messages/index-set-id/message-id`).
This is just a simple fix. The proper way to provide field types for these components requires a bigger refactoring https://github.com/Graylog2/graylog2-server/issues/16308.
Before (date is just a string and does not consider user time zone):
After:
=> Fix missing field types problem on message details page.

graylog2-web-interface/package.json, graylog2-web-interface/src/components/configurationforms/ConfigurationForm.test.tsx, graylog2-web-interface/src/components/configurationforms/ConfigurationForm.tsx, graylog2-web-interface/src/views/components/messagelist/decorators/AddDecoratorButton.tsx, graylog2-web-interface/src/views/components/messagelist/decorators/DecoratorSummary.tsx, graylog2-web-interface/src/views/components/messagelist/decorators/InlineForm.tsx, graylog2-web-interface/tsconfig.json, graylog2-web-interface/yarn.lock
Previously, the `postcss-styled-syntax` was shadowing our own `typescript` dependency, causing in being stuck on 5.3.x. This PR is now pinning our desired version and fixes the typing fallout.
=> Pinning `typescript` to `5.5.2` and fixing type fallout.

changelog/unreleased/pr-19750.toml, graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IpInfoIpAsnResolver.java, graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IpInfoLocationResolver.java
Resolves Graylog2/graylog-plugin-enterprise#7602
`IpInfo*Resolver` classes only handle a specific set of exception types. Unknown exceptions bubble up, leading to processing failure.
Extend exception handling to cover all types of exceptions. 
When an IP address cannot be resolved against the IPInfo DB, we may receive a `com.maxmind.db.DeserializationException` from `IPinfoIPLocationDatabaseAdapter`. 
This may occur in 2 places:
- `MaxmindDataAdapter`: this class handles any exceptions in lookup.
- `IpInfoIpAsnResolver` and `IpInfoLocationResolver`: these classes only handle a subset of exception types, resulting in an unexpected exception and failure to process messages when an unknown exception is encountered.
This affects all versions that support IPInfo DBs, i.e. 5.1 and up.
=> Add missing exception handling for IpInfo*Resolver

graylog2-web-interface/src/components/streams/StreamDetails/StreamDataRoutingDestinations.tsx, graylog2-web-interface/src/components/streams/StreamDetails/StreamDetails.tsx
This fix stream details page is not loading when the Plugin is not present because it is disabled.
/nocl
/jpd Graylog2/graylog-plugin-enterprise#7623
=> Check for plugin presence in Stream-details page

graylog2-web-interface/src/components/common/Carousel/CarouselProvider.tsx, graylog2-web-interface/src/components/common/Carousel/hooks/useSlidesInView.ts
This PR extends the `Carousel` `useSlidesInView` hook. The hook can now be used to receive the slides which are currently visible or all slides which have been visible at least once.
/nocl
=> Add option for `useSlidesInView` to memorize which slides have been visible already.

graylog2-server/src/main/java/org/graylog2/rest/resources/entities/EntityAttribute.java, graylog2-web-interface/src/components/common/Drawer.tsx, graylog2-web-interface/src/components/common/EntityFilters/CreateFilterDropdown.tsx, graylog2-web-interface/src/components/common/EntityFilters/FilterConfiguration/SuggestionsList.tsx, graylog2-web-interface/src/components/common/EntityFilters/hooks/useFilterValueSuggestions.ts, graylog2-web-interface/src/stores/PaginationTypes.ts
This PR is extending the properties of attributes for paginated endpoints so that a column can be specified which is used to retrieve the title for suggestions.
=> Support defining column for related collections suggestions.

graylog2-web-interface/src/components/common/Carousel/CarouselProvider.tsx
Disabling dragging is required for use cases when it is important that text inside slides can be copied.
/nocl
=> Allow disabling dragging for carousel.

graylog2-server/src/main/java/org/graylog/events/event/Event.java, graylog2-server/src/main/java/org/graylog/events/event/EventDto.java, graylog2-server/src/main/java/org/graylog/events/event/EventImpl.java, graylog2-server/src/main/java/org/graylog2/indexer/EventsIndexMapping.java, graylog2-server/src/test/java/org/graylog2/indexer/EventsIndexMappingTest.java
Add support for the `associated_assets` (string id array) field to Events. Also updates the event mapping accordingly. This field needs to be present at the top-level of the Event, since (similar to the `Message` object), it must be an array in order to support effective/efficient search filtering. 
Server changes needed for https://github.com/Graylog2/graylog-plugin-enterprise/issues/7475
Corresponding Enterprise PR: https://github.com/Graylog2/graylog-plugin-enterprise/pull/7603
Verified that the new events mapping is applied successfully when the Graylog Events index is rotated. Subsequent events index successfully. See additional testing notes in corresponding PR.
/nocl
=> Add associated_assets field to Events

graylog2-web-interface/package.json, graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/Sidebar.tsx, graylog2-web-interface/src/components/bootstrap/Table.jsx, graylog2-web-interface/src/components/common/EntityDataTable/EntityDataTable.tsx, graylog2-web-interface/src/components/common/PaginatedItemOverview/PaginatedItem.tsx, graylog2-web-interface/src/components/datanode/migrations/InPlaceMigration.tsx, graylog2-web-interface/src/components/datanode/migrations/RemoteReindexingMigration.tsx, graylog2-web-interface/src/components/permissions/GranteesList.tsx, graylog2-web-interface/src/components/rules/rule-builder/RuleBuilder.tsx, graylog2-web-interface/src/views/components/datatable/TableHeaderCell.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/TimeRangeDisplay.tsx, graylog2-web-interface/src/views/components/widgets/MessageTable.tsx, graylog2-web-interface/src/views/components/widgets/events/EventsList/EventsTableRow.tsx, graylog2-web-interface/yarn.lock
Update sawmill to version 2.0.20  and update table colors and theme tokens.
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/7639
/nocl
=> Update sawmill to version 2.0.20.

changelog/unreleased/issue-19207.toml, data-node/src/main/java/org/graylog/datanode/bootstrap/CmdLineTool.java
This PR changes the way how we handle configuration errors during startup. The original logic stopped on first encountered error, forcing user to fix it and try again, which could repeat several times and leads to tiresome process. The new logic discovers and reports all problems at once, making it easy to fix in one go.  
Removed duplicated configuration processing during the datanode startup, which I assume, was a copy-paste error.
See https://github.com/Graylog2/JadConfig/pull/127
Fixes https://github.com/Graylog2/graylog2-server/issues/19207
Manually
Before, stopping at the first error:
```
2024-07-02 09:19:25,504 ERROR: org.graylog.datanode.bootstrap.CmdLineTool - Invalid configuration
com.github.joschi.jadconfig.ParameterException: Required parameter "opensearch_data_location" not …
```
=> Lazy configuration processing, printing all errors at once

graylog2-server/src/main/java/org/graylog2/database/dbcatalog/DbEntitiesCatalog.java, graylog2-server/src/test/java/org/graylog2/database/dbcatalog/DbEntitiesCatalogTest.java, graylog2-server/src/test/java/org/graylog2/database/dbcatalog/DbEntitiesScannerTest.java
This PR is a follow-up to #19761, removing the unused `getByModelClass` method and references to it in tests. Referencing entities by class name is not a good pattern, as it uses implementation details. In this case, the major drawback is that it is not working with multiple `@DbEntity` annotations. Fortunately, this method was not used outside of tests anyway, so it gets removed with this PR.
=> Removing ability to look up entity by class name.

graylog2-web-interface/src/components/bootstrap/Button.md, graylog2-web-interface/src/components/bootstrap/Button.tsx, graylog2-web-interface/src/components/bootstrap/types.ts
With this PR we display `<Button bsStyle="link">` buttons as actual links. Before they still used the button padding, hover styles, vertical alignment etc.
Before:
After: 
/nocl
=> Display buttons with link variant as actual links.

graylog2-web-interface/package.json, graylog2-web-interface/packages/graylog-web-plugin/package.json, graylog2-web-interface/yarn.lock
The `@graylog/sawmill` dependency has been accidentally added to two `package.json` files. With this PR we only maintain it in the `graylog-web-plugin` `package.json`.
/nocl
=> Only maintain `@graylog/sawmill` dependency in `graylog-web-plugin`.

graylog2-web-interface/src/views/custom-plotly.ts
With this PR we import another plotly visualization, the scatterpolar. This allows using the visualization type when rendering a plotly chart.
/nocl
=> Import scatterpolar from plotly.

changelog/unreleased/pr-19865.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/conversion/CsvMapConversion.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/csvMap.txt
Add a new optional `ignoreExtraFieldNames (boolean)` parameter to the `csv_to_map` pipeline function. The adds flexibility to the function, so that more `fieldNames` values can be provided than csv values. This allows a pipeline function to statically include the maximum number of possible field name and successfully parse messages containing any number of of them. 
CSV payloads are commonly extended in subsequent versions of products (by adding fields at the end). This change allows parsing of newer versions to be backwards compatible for messages that don't have the new fields. 
Added as a new parameter to retain previous default behavior where field names must match specified values.
=> Add optional ignoreExtraFieldNames parameter to csv_to_map pipeline function

changelog/unreleased/pr-19865.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/conversion/CsvMapConversion.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/csvMap.txt
Backport #19865 to the `6.0` branch.
=> Backport: Add optional ignoreExtraFieldNames parameter to csv_to_map pipeline function

graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/RemoteReindexingMigrationAdapterOS2.java, graylog2-server/src/main/java/org/graylog2/indexer/migration/IndexMigrationProgress.java, graylog2-server/src/test/java/org/graylog2/indexer/migration/IndexMigrationProgressTest.java, graylog2-server/src/test/java/org/graylog2/indexer/migration/RemoteReindexMigrationTest.java
Includes noops and version_conflicts documents in remote reindexing progress calculation.
Also adds these numbers to the logs (only if they occur)
/nocl
possible fix for #19875
=> fix remote reindex progress calculation

graylog2-web-interface/src/components/common/PaginatedEntityTable/PaginatedEntityTable.tsx, graylog2-web-interface/src/components/common/PaginatedEntityTable/useFetchEntities.ts
This PR allows supplying fetch options for paginated entity tables. A use case right now is specifying a `refetchInterval` to refetch entities periodically.
=> Allow supplying fetch options for paginated entity fetcher.

changelog/unreleased/pr-19921.toml, graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20240626143000_CreateDashboardsView.java
On setups which were already running Graylog before Views were introduced in `3.2.0`, a `dashboards` collection already exists. For these, we need to drop the collection before creating the `dashboards` view based on the `views` collection.
The `dashboards` collection was not dropped before, because it seemed to be safer to keep it in case the migration (from `dashboards` to `views`) contains errors. This is now roughly 5 years ago, so dropping it now should be safe™.
Fixes #19912.
=> Drop `dashboards` collection if migration if it exists.

graylog2-server/src/main/java/org/graylog2/indexer/IndexTemplateProvider.java, graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetConfig.java, graylog2-server/src/test/java/org/graylog2/indexer/indexset/IndexSetConfigTest.java
Block field type and profile changes in Illuminate index sets.
/nocl
Field type and profile changes in Illuminate do not take place anyway, are silently ignored.
We want to explicitly block them, so that no one is surprised by that.
Partially solves https://github.com/Graylog2/graylog2-server/issues/19766, but some FE blocks would make the solution even nicer.
=> Block field type changes in Illuminate index sets

graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/actions/MigrationActionsImpl.java
silently removes trailing slash from hostname
/nocl
fixes #19884
=> Datanode migration: fix invalid hostname

changelog/unreleased/pr-19947.toml, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/RemoteReindexAllowlist.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/RemoteReindexAllowlistTest.java
Fix parsing of opensearch allowlist value for remote reindex migrations. The server config value contains spaces that needs to be trimmed. 
Added unit test
=> Fix parsing of opensearch allowlist

changelog/unreleased/pr-19951.toml, graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationV2.java
Custom HTTP Notifications with JSON formatted payloads do not currently send strings with escaped double quote chars. This leads to improperly formatted JSON if any fields contain them and breaks the notification. Escaping double quote chars on strings containing them resolves this issue.
=> Escape quotes in Custom HTTP Notification JSON payload strings

changelog/unreleased/issue-19694.toml, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/responses/IndexSetFieldType.java, graylog2-server/src/test/java/org/graylog2/rest/resources/system/indexer/responses/IndexSetFieldTypeTest.java
Sorting of custom field types is null safe.
Fixes #19694
See #19694
=> Sorting of custom field types is null safe

changelog/unreleased/pr-19951.toml, graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationV2.java
=> Backport 6.0: Escape quotes in JSON payload strings (#19951)

changelog/unreleased/issue-19694.toml, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/responses/IndexSetFieldType.java, graylog2-server/src/test/java/org/graylog2/rest/resources/system/indexer/responses/IndexSetFieldTypeTest.java
Sorting of custom field types is null safe.
Fixes https://github.com/Graylog2/graylog2-server/issues/19694
Backported to 6.0, based on PR: https://github.com/Graylog2/graylog2-server/pull/19960
See https://github.com/Graylog2/graylog2-server/issues/19694
=> Sorting of custom field types is null safe (#19960)

changelog/unreleased/pr-19976.toml, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/RemoteReindexingMigrationAdapterOS2.java, graylog2-server/src/main/java/org/graylog2/indexer/migration/RemoteIndex.java, graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/MigrateExistingData.tsx
In the remote reindexing migration for data node, the connection check which retrieves the index list now also adds the information if the index is managed by Graylog in an index set.
If  not, this index is not selected by default in the migration and a warning with an appropriate tooltip will be displayed.
helps users to understand that some migrated indices will not be visible in Graylog
#19974
=> Mark unmanaged indices for remote reindexing

changelog/unreleased/pr-19981.toml, graylog2-server/src/main/java/org/graylog2/bindings/PeriodicalBindings.java, graylog2-server/src/main/java/org/graylog2/cluster/nodes/DataNodePaginatedService.java, graylog2-server/src/main/java/org/graylog2/cluster/nodes/NodeDto.java, graylog2-server/src/main/java/org/graylog2/periodical/DataNodeHousekeepingPeriodical.java, graylog2-server/src/main/java/org/graylog2/rest/resources/RestResourcesModule.java, graylog2-server/src/main/java/org/graylog2/rest/resources/datanodes/DatanodeResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/ClusterResource.java, graylog2-web-interface/src/components/datanode/DataNodeList/DataNodeList.tsx, graylog2-web-interface/src/components/datanode/hooks/useDataNodes.ts
- refactor data node discovery into its own resource, remove usage of PaginatedDbService, add column definitions in backend
- considers UNAVAILABLE data nodes in the migration wizard (e.g. data nodes with stopped OS)
- adds periodical to drop outdated data nodes to remove last remaining data node in cluster after stopping it
fixes #19980
fixes #19433
=> Fix removing of unavailable data nodes

changelog/unreleased/pr-20001.toml, graylog2-web-interface/src/components/bootstrap/Table.jsx, graylog2-web-interface/src/views/components/datatable/MessagesTable.tsx
**Please note**, this is a backport of https://github.com/Graylog2/graylog2-server/pull/20001 for `5.2`
Before:
After:
/nocl
=> Implement table rows border color with more contrast. (5.2)

pom.xml
This allows us to keep singatures for classes that are not present on the classpath. Keeping the signatures is useful if the class should come back at some point.
/nocl Code quality tooling change.
=> Set ignoreSignaturesOfMissingClasses for forbiddenapis

UPGRADING.md, graylog2-server/src/main/java/org/graylog2/migrations/V202211021200_CreateDefaultIndexTemplate.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/requests/IndexSetUpdateRequest.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/responses/IndexSetSummary.java, graylog2-server/src/main/resources/org/graylog2/indexer/indexset/template/on_prem_templates.json
changed:
- update built-in indexset template title/description (like discussed in Slack#index-templates)
- update default indexset template description (like discussed in Slack#index-templates)
- update Ugrading.md
- make useLegacyRotation optional to not break API
/nocl
=> update built-in indexset template title/description

graylog2-web-interface/src/views/components/visualizations/GenericPlot.tsx
The `onAfterPlot` prop allows defining a callback for the plot which is being called after the plot finished rendering.
/nocl
=> Add prop `onAfterPlot` prop for generic plot.

graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationSummary.tsx, graylog2-web-interface/src/components/event-definitions/types.d.ts
Added `definitionId` to FilterAggregationSummary to fix issue with replay search button
closes: graylog2/graylog-plugin-enterprise#8075
/nocl
The implementation of LinkToReplaySearch component changed. It uses URL params to get the event definition ID when the user tries to replay the search of an event definition.
This PR adds an optional property to the component to be able to pass the ID when the component is used in a view that doesn't have the definition ID as a parameter in the URL.
=> fix(8075): Added definitionId optional prop to FilterAggregationSummary

changelog/unreleased/pr-20001.toml, graylog2-web-interface/src/components/bootstrap/Table.jsx, graylog2-web-interface/src/views/components/datatable/TableHeaderCell.tsx
**Please note**, this is a backport of https://github.com/Graylog2/graylog2-server/pull/20001 for `6.0`
Before:
After:
/nocl
=> Implement table rows border color with more contrast. (6.0)

graylog2-web-interface/src/components/common/FormikInput.tsx
Input supports addonAfter, but the FormikInput didn't expose it in its properties. This Pr is adding that.
/nocl
=> add addonAfter for FormikInput

changelog/unreleased/issue-5254.toml, graylog2-server/src/main/java/org/graylog2/inputs/beats/kafka/BeatsKafkaInput.java, graylog2-server/src/main/java/org/graylog2/inputs/codecs/CodecsModule.java, graylog2-server/src/main/java/org/graylog2/shared/bindings/MessageInputBindings.java
1.Pulls the system logs from Kafka topic by using Filebeats configuration.
1.This change eliminates reading the file from remote systems to get system logs, instead we get this logs from kafka topic improving the performance.
1.Configured filebeats.yml file in remote system inside  same network.
2.Installed kafka,zookeeper and created topic with name configured in filebeats.yml.
3.Started Consumer console and able to see logs from the topic.
4.Created Kafka beats input and verified logs in conusmer console and graylog.
=> Kafka beats implementation

changelog/unreleased/pr-20097.toml, data-node/pom.xml, pom.xml
Bumping our OpenSearch usage to 2.15:
- client used to connect to OpenSearch (does in general not restrict the server version used)
- server inside the DataNode
Background is: the core team works on a feature that needs the fix in https://github.com/opensearch-project/OpenSearch/pull/12812 which is only available in the client from 2.15 on.
And in general, we tested 2.15 a bit more than other versions because 2.14 had some bugs so I think it's a good step to bump the versions from 2.12 to 2.15 so that it's clear that everyone should stay away from that buggy version.
=> Bumping the OpenSearch Client in general and the Server in the DataNode to 2.15

pom.xml
Earlier versions include a DoS vulnerability, so we want to ensure we
are using a fixed version.
Refs https://github.com/Graylog2/graylog2-server/security/dependabot/131
/nocl No user-visible change.
=> Manage org.json:json dependency to ensure consistent version

changelog/unreleased/pr-20090.toml, data-node/src/main/java/org/graylog/datanode/configuration/DatanodeDirectories.java, data-node/src/main/java/org/graylog/datanode/rest/DataNodeStatus.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/debug/bundle/SupportBundleService.java, graylog2-server/src/main/java/org/graylog2/shared/rest/resources/system/RemoteDataNodeStatusResource.java
This adds initial information about data nodes to the support bundle.
Information from the data nodes as stored in mongodb are provided in `datanodes.configured` and status information from the status endpoint of running data nodes is provided in `datanodes.running` in the generated `cluster.json`
Additionally, the status endpoint now return information about the operating system, java version and user running the data node as well as free disk space available for the configured data node directories.
resolves https://github.com/Graylog2/graylog-plugin-enterprise/issues/7966
manually by creating a support bundle in System/Logging
=> Add datanode information to support bundle

changelog/unreleased/pr-20001.toml, graylog2-web-interface/src/components/bootstrap/Table.jsx, graylog2-web-interface/src/views/components/datatable/TableHeaderCell.tsx
Please note, this PR needs a backport for 6.0 and 5.2
Before:
After:
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/6685
=> Implement table rows border color with more contrast.

changelog/unreleased/pr-20123.toml, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/RemoteReindexingMigrationAdapterOS2.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/actions/MigrationActions.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/actions/MigrationActionsImpl.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/machine/MigrationStateMachineBuilder.java, graylog2-server/src/main/java/org/graylog2/notifications/Notification.java, graylog2-server/src/main/resources/org/graylog2/freemarker/templates/HTML/remote_reindex_finished.ftl, graylog2-server/src/main/resources/org/graylog2/freemarker/templates/HTML/remote_reindex_running.ftl, graylog2-server/src/main/resources/org/graylog2/freemarker/templates/PLAINTEXT/remote_reindex_finished.ftl, graylog2-server/src/main/resources/org/graylog2/freemarker/templates/PLAINTEXT/remote_reindex_running.ftl, graylog2-server/src/test/java/org/graylog/plugins/views/storage/migration/state/machine/MigrationActionsAdapter.java, graylog2-server/src/test/java/org/graylog/plugins/views/storage/migration/state/machine/MigrationStateMachineBuilderTest.java, graylog2-web-interface/src/logic/notifications/NotificationsFactory.tsx
This adds a system notification that indicates that the remote reindexing migration is still going on. This is replaced by another notification showing the success status after remote reindexing has finished, pointing the user to finalize the migration in the wizard. This second notification will be cleared after finishing the migration wizard.
Feedback from testers
perform remote reindex migration
=> Show system notification while remote reindexing

graylog2-server/src/main/java/org/graylog2/telemetry/rest/TelemetryService.java, graylog2-server/src/test/java/org/graylog2/telemetry/rest/TelemetryServiceTest.java, graylog2-server/src/test/java/org/graylog2/telemetry/rest/TelemetryServiceWithDbTest.java
If running against data node, the `search_cluster_version` property in Posthog is replaced by `DataNode:<version>`
/nocl internal
resolves #https://github.com/Graylog2/graylog-plugin-enterprise/issues/6970
run Graylog configured with datanode, check Posthog entries
=> show datanode version in telemetry

full-backend-tests/src/test/java/org/graylog/events/processor/aggregation/PivotAggregationSearchIT.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/EventDefinitions.java
This PR is adding a test case that checks if event definition evaluation is working in a way that is isolating streams (if specified). This is validating that symptoms described in #20119 are not present.
/nocl
=> Adding test case for stream isolation in event definition evaluation.

graylog2-server/src/main/java/org/graylog/scheduler/JobExecutionEngine.java, graylog2-server/src/main/java/org/graylog/scheduler/JobSchedulerService.java, graylog2-server/src/main/java/org/graylog/scheduler/worker/JobWorkerPool.java, graylog2-server/src/test/java/org/graylog/scheduler/JobSchedulerServiceIT.java, graylog2-server/src/test/java/org/graylog/scheduler/worker/JobWorkerPoolTest.java
Let the JobSchedulerService register with the GracefulShutdownService to ensure a correct shutdown order of the job scheduler components.
Previously, only the JobWorkerPool was registered in the GracefulShutdownService. That caused the JobWorkerPool to be stopped *before* the JobSchedulerService.
The JobExecutionContext#isShuttingDown method only returned true when the JobSchedulerService was shut down. So jobs would only cancel their execution when the scheduler service is in shutdown mode.
When the jobs are not cancelled, the JobWorkerPool shutdown didn't finish and ran into a 60 second timeout. The JobSchedulerService was only shutdown after the JobWorkerPool timeout.
/nocl No user-visible change
=> Fix shutdown process of the job scheduler

changelog/unreleased/issue-19159.toml, graylog2-server/src/main/java/org/graylog2/lookup/caches/CaffeineLookupCache.java, graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupResult.java, graylog2-server/src/test/java/org/graylog2/lookup/CaffeineLookupCacheTest.java
Unmodified backport of #19670 
* bubble up lookup failures
* add unit test
* CL
---------
Co-authored-by: Tomas Dvorak <tomas.dvorak@graylog.com>
(cherry picked from commit ab31c69147f27363fb68e9d134fcb80bba81502a)
=> Lookup cache: bubble up error results without modifying (#19670)

full-backend-tests/src/test/java/org/graylog/events/processor/aggregation/PivotAggregationSearchIT.java, full-backend-tests/src/test/java/org/graylog/plugins/views/aggregations/CompoundFieldsAggregationIT.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/Indices.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/Streams.java
This PR is fixing the test introduced in #20154 so it tests also without a grouping, which triggers some issues with OS 2.16.0. It turns the existing test case with a grouping into an additional test case.
/nocl
=> Fixing up events aggregation integration test.

graylog2-web-interface/src/views/components/sidebar/highlighting/Scale.ts, graylog2-web-interface/src/views/logic/views/formatting/highlighting/HighlightingColor.ts
This PR is fixing imports for `chroma-js` from a wildcard import to a generic default import. This fixes warnings with webpack starting with `chroma-js` 2.6.0.
/nocl
=> Fixing `chroma-js` imports.

graylog2-server/src/main/java/org/graylog/scheduler/DBJobDefinitionService.java
Add method to stream job definitions with a filter by configuration field.
Needed for https://github.com/Graylog2/graylog-plugin-enterprise/pull/8251.
/nocl See corresponding enterprise PR for additional details.
=> Add method to stream job definitions by configuration field

graylog2-web-interface/src/views/logic/fieldactions/ChangeFieldType/ChangeFieldTypeModal.tsx, graylog2-web-interface/src/views/logic/fieldactions/ChangeFieldType/hooks/useInitialSelection.tsx
It is possible to change a field type by opening the search page and clicking on "Change field type" in the fiel name action of a field in the message table.
Before this fix there was a problem that the initial selection of index sets is empty (introduce with https://github.com/Graylog2/graylog2-server/pull/19936).
With this PR they are selected again:
/nocl
=> Fix initial selection of index sets in change field types modal.

graylog2-web-interface/src/components/common/ConfirmLeaveDialog.tsx
Using the `ConfirmLeaveDialog` component will show a confirm dialog when leaving the current page.
This PR allows defining routes which should be ignored on a route change. This can be helpful in case of a wizard form. 
/nocl
=> Allow ignoring routes in `ConfirmLeaveDialog` component.

changelog/unreleased/pr-20265.toml, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/WidgetDTO.java
For Dashboards exported to content packs the current logic attempts to resolve any Stream dependencies that are present in the saved Search that part of the view object.
However if a Dashboard containing a Widget with a Stream in imported via Content Pack, the Stream will not be present on the Search until the first time it is run.
This PR adds additional Stream dependency resolution logic to check for Streams on any widget objects that are part of the Dashboard.
A user can create or import a Dashboard, and immediately export it to a content pack before the Dashboard search is ever run. This will result in stream dependencies not being auto populated/exported for the Content Pack.
Locally in a development environment.
Steps to reproduce:
1. Create a Dashboard with a widget scoped to a …
=> Resolve widget streams for content pack entities

graylog2-server/src/main/java/org/graylog2/contentpacks/facades/StreamReferenceFacade.java
StreamReferenceFacade uses asString() without parameter mapping when retrieving the stream title from a content pack. This leads to the aforementioned exception, while installing a content pack containing a stream title with attached parameter.
Use the asString() variant that supports parameter lookups.
We want to use content packs containing adjustable stream titles. This is blocking us. 
Untested.
=> Fix "Expected value reference of type STRING but got PARAMETER" Exception when using a parameter for a stream title

changelog/unreleased/pr-20263.toml, graylog2-server/src/main/java/org/graylog2/grok/GrokPatternRegistry.java, graylog2-server/src/test/java/org/graylog2/grok/GrokPatternRegistryTest.java
`grok_exists` is supposed to return true only if the requested pattern exists in the list of Grok patterns. Right now it is returning true if any pattern contains the requested pattern as a substring. This changes to `contains` to an `equals` call to fix the issue and adds a simple unit test to prevent future issues.
closes #20264
=> Fix grok_exists pipeline rule

changelog/unreleased/issue-20208.toml, full-backend-tests/src/test/java/org/graylog/datanode/RemoteReindexingMigrationIT.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ClientES7.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/RemoteReindexingMigrationAdapterOS2.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/testing/ClientOS2.java, graylog2-server/src/test/java/org/graylog/testing/elasticsearch/Client.java, graylog2-server/src/test/java/org/graylog/testing/elasticsearch/IndexState.java
During the remote reindex migration we check if the source index is closed. If yes, we'll reopen it, migrate the data and close it again, together with closing the target index as well. But when somebody runs the migration for the second time (retry) it may happen that also the target index is already existing and is closed. Then we need to reopen it as well. 
Fixes [#20208](https://github.com/Graylog2/graylog2-server/issues/20208)
Extended integration test
=> Reopen closed local indices for remote reindex migration

changelog/unreleased/pr-20244.toml
Add change log for https://github.com/Graylog2/graylog2-server/pull/20244. Not a critical change to surface in the change log, but I figure it can't hurt to have the entry.
/nocl
=> Add change log for stream_title param fix

changelog/unreleased/pr-20265.toml, graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackPersistenceService.java, graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackPersistenceServiceTest.java, graylog2-server/src/test/resources/org/graylog2/contentpacks/content_pack_with_dashboard_with_stream.json, graylog2-server/src/test/resources/org/graylog2/contentpacks/content_pack_with_dashboard_with_stream_reference.json
In `ContentPackPersistenceService.filterMissingResourcesAndInsert()` there is logic to remove streams from some embedded dashboard search entities before a content pack is stored in MongoDB if the referenced stream cannot be found.
This logic was checking for Stream Entities but not Stream Reference Entities, resulting in stream references getting filtered out of the searches.
This PR updates the filter logic to include any Stream Reference Entities as valid streams to be included included in the content pack.
In some instances content packs with a Stream-scoped Dashboard Entity and Stream Title entity had searches that were not properly scoped to the referenced Stream. 
Locally in development environment and unit tests.
Steps to reproduce:
1. Create a Dashboard with Log View widget
2. …
=> Handle stream references in content pack persistence service filtering

graylog2-server/src/main/java/org/graylog2/database/pagination/DefaultMongoPaginationHelper.java, graylog2-server/src/main/java/org/graylog2/database/pagination/MongoPaginationHelper.java, graylog2-server/src/test/java/org/graylog2/database/pagination/DefaultMongoPaginationHelperTest.java
Projection functionality added to MongoPaginationHelper.
/nocl
Add a way to fetch multiple entities without optional fields of big size (for performance reasons).
The example of this need can be spotted in Investigations, where each Investigation can contain AI-generated report, which can be only needed when working with single Investigation, never when you paginate multiple ones.
With new unit tests.
=> Projection functionality added to MongoPaginationHelper

changelog/unreleased/pr-20272.toml, graylog2-web-interface/src/components/common/Tooltip.tsx
Use max z-index for Tooltip as it should be visible in overlays. Added it to the component directly as it got ignored on the styles.
Using a mantine z-index variable, which we should implement in other places as well to avoid these issues. Todo: Create issue for that.
See https://mantine.dev/styles/css-variables/#z-index-variables.
This fixes tooltips not being visible in Modals, e.g. the Copy to Clipboard button in AI Report modal (Security/Investivations).
=> Use max z-index in Tooltip

graylog2-web-interface/src/views/components/visualizations/utils/__tests__/chartLayoutGenerators.test.ts, graylog2-web-interface/src/views/components/visualizations/utils/chartLayoutGenerators.ts
This change is fixing an issue which results in an exception being thrown when a bar chart visualization in stack mode has no data.
/nocl No user-facing change yet.
=> Fixing exception in bar chart with stack mode when no data is present.

changelog/unreleased/pr-20287.toml, graylog2-server/src/main/java/org/graylog/scheduler/DBJobTriggerService.java, graylog2-server/src/test/java/org/graylog/scheduler/DBJobTriggerServiceTest.java, graylog2-server/src/test/resources/org/graylog/scheduler/stale-job-triggers.json
This is required for scheduled jobs which are cancelled. Otherwise, a cancelled scheduled job would always abort on next execution because it's cancelled.
=> Reset "is_cancelled" flag on job trigger release

changelog/unreleased/pr-19951.toml, graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationV2.java, graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java, graylog2-server/src/main/java/org/graylog2/bindings/providers/JsonSafeEngineProvider.java, graylog2-server/src/test/java/org/graylog/events/notifications/types/HTTPEventNotificationV2Test.java
The original fix for escaping double quotes in Custom HTTP Notifications fixed only top level strings in the model map. However, the backlog is a list of MessageSummary objects so the message.message fields were not properly being escaped. These changes add a `JsonSafeEngineProvider` which escapes all double quotes in String objects whenever they are substituted into a JSON formatted payload. This should handle all strings in the model, not just those that are top-level values.
Graylog2/support#69
local tests and unit tests
=> Escape double quotes in all strings, not just top level model strings

graylog2-web-interface/src/util/PaginationURL.test.ts, graylog2-web-interface/src/util/PaginationURL.ts
This PR is fixing an issue with the pagination helper doing URL-encoding of the `query` parameter twice, effectively turning `foo bar` into `foo%2520bar` on the wire and `foo%20bar` on the receiving end.
This most probably slipped in when `urijs` was introduced in this piece of code, forgetting that it is already doing URL-encoding.
=> Avoiding double encoding of `query` parameter.

graylog2-web-interface/src/components/indices/IndicesMaintenanceDropdown.tsx, graylog2-web-interface/src/components/indices/hooks/useDeleteFailedSnapshotMutation.tsx, graylog2-web-interface/src/routing/ApiRoutes.ts, graylog2-web-interface/src/stores/indices/IndexSetsStore.ts
Part of https://github.com/Graylog2/graylog-plugin-enterprise/issues/8233
- Adds a button to delete a failed snapshot to the maintenance dropdown on the index set page.
- Clicking the button shows a confirm modal with further information on the impact of this process.
This feature relies on the attributes as part of the response of `GET /system/indices/index_sets/ID`:
**Example response:**
``` json
{
id: "234asd2",
title: "foo",
index_prefix: "bar",
has_failed_snapshot: true,
failed_snapshot_name: "foor_warm"
}
```
- `has_failed_snapshot` (boolean) to determine whether to display the button
- `failed_snapshot_name` (optional string) to display the name of the index to delete in the confirm modal
It uses the following call to delete the snapshot:
`DELETE …
=> Add button to delete failed snapshot

graylog2-server/src/main/java/org/graylog2/indexer/messages/ImmutableMessage.java, graylog2-server/src/main/java/org/graylog2/indexer/messages/SerializationMemoizingMessage.java, graylog2-server/src/main/java/org/graylog2/outputs/IndexSetAwareMessageOutputBuffer.java, graylog2-server/src/test/java/org/graylog2/outputs/BatchedMessageFilterOutputTest.java
Implements two parts of #20071:
- Don't serialize messages early if count-based batch size is configured
- Make collection types explicitly immutable.
Part of #20071
/nocl internal refactoring
=> Optimize byte-size-based output batch handling

graylog2-web-interface/src/components/common/Section.tsx, graylog2-web-interface/src/components/streams/StreamDetails/StreamDataRoutingDestinations.tsx, graylog2-web-interface/src/components/streams/StreamDetails/routing-destination/DestinationIndexSetSection.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/StreamActions.tsx
fix Graylog2/graylog-plugin-enterprise#8384 Graylog2/graylog-plugin-enterprise#8147
/nocl
=> Make collapsed section header clickable

changelog/unreleased/issue-19354.toml, graylog2-server/src/main/java/org/graylog/events/search/EventsSearchResult.java, graylog2-server/src/main/java/org/graylog/events/search/EventsSearchService.java, graylog2-web-interface/src/components/events/events/EventDetails.tsx, graylog2-web-interface/src/components/events/events/types.ts
Backport of https://github.com/Graylog2/graylog2-server/pull/19853 to 6.0.
=> (Backport 6.0) - Return remediation steps with events

changelog/6.0.5/pr-19951.toml, graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationV2.java, graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java, graylog2-server/src/main/java/org/graylog2/bindings/providers/JsonSafeEngineProvider.java, graylog2-server/src/test/java/org/graylog/events/notifications/types/HTTPEventNotificationV2Test.java
=> Backport 6.0: Escape JSON in Custom HTTP Notifications

graylog2-server/src/main/java/org/graylog2/database/utils/MongoUtils.java, graylog2-server/src/test/java/org/graylog2/database/utils/MongoUtilsTest.java
we already have helpers for the _id field, but sometimes we store objectid 
references in other fields and it's unwieldy to create objectid instances all the time
/nocl helper methods
=> add two helper methods to build ObjectId related eq filters

changelog/unreleased/pr-20352.toml, graylog2-server/src/main/java/org/graylog2/rest/models/system/indexer/responses/IndexSummary.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexerOverviewResource.java, graylog2-web-interface/src/components/indices/IndexSection.tsx, graylog2-web-interface/src/components/indices/IndicesOverview.tsx, graylog2-web-interface/src/components/indices/index.tsx, graylog2-web-interface/src/stores/indexers/IndexerOverviewStore.ts
Resolves Graylog2/graylog-plugin-enterprise#8400
Extends the `GET /system/indexer/overview/${indexSetId}` API to provide tier type (`hot` or `warm`) and shard count for each index.
```
{
"deflector": {
...
},
"indexer_cluster": {
...
},
"counts": {
"events": 0
},
"indices": [
{
"index_name": "graylog_60",
"size": {
"events": 0,
"deleted": 0,
"bytes": 624
},
"range": {
"index_name": "graylog_60",
"begin": "1970-01-01T00:00:00.000Z",
"end": "1970-01-01T00:00:00.000Z",
"calculated_at": "2024-09-02T10:42:31.474Z",
"took_ms": 0
},
"tier": "hot",
"shard_count": 3,
"is_reopened": false,
"is_deflector": true,
"is_closed": false
}
]
}
```
=> Display indices in sections seperated by tier

graylog2-web-interface/src/components/common/EntityDataTable/ExpandedSections.tsx, graylog2-web-interface/src/components/common/EntityDataTable/types.ts
This PR allows disabling the header in expanded sections of the entity
data table by setting the `disableHeader` prop to `true` in the
definition of an expanded section renderer.
=> Allow disabling header in expanded sections.

changelog/unreleased/pr-20389.toml, graylog2-server/src/main/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotificationV2.java, graylog2-server/src/test/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotificationV2Test.java
Use JsonSafeEngine when creating TeamsNotificationV2 notifications
https://github.com/Graylog2/support/issues/69
=> Fix unescaped double quotes in nested event fields for TeamsNotificationV2

changelog/unreleased/pr-20379.toml, graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationBrowserResource.java
**Note:** This PR requires backports to `5.2` and `6.0`.
Use the external URI for the base URL of the API browser. This avoids leaking internal hostnames when an external URI is configured.
closes #20391
=> Use external URI for base URL of API browser.

changelog/unreleased/pr-20379.toml, graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationBrowserResource.java
**Note:** This is a backport of #20379 to `6.0`.
Use the external URI for the base URL of the API browser. This avoids leaking internal hostnames when an external URI is configured.
Fixes #20391
=> Use external URI for base URL of API browser. (`6.0`)

changelog/unreleased/pr-20379.toml, graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationBrowserResource.java
**Note:** This is a backport of #20379 to `5.2`.
Use the external URI for the base URL of the API browser. This avoids leaking internal hostnames when an external URI is configured.
Fixes #20391
=> Use external URI for base URL of API browser. (`5.2`)

changelog/unreleased/pr-20389.toml, graylog2-server/src/main/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotificationV2.java, graylog2-server/src/test/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotificationV2Test.java
=> Backport 6.0: Fix unescaped double quotes in nested event fields for TeamsNotificationV2 

changelog/unreleased/pr-20110.toml, graylog2-server/src/main/java/org/graylog/plugins/views/search/Query.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/ScriptingApiResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/QueryParamsToFullRequestSpecificationMapper.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/SearchRequestSpecToSearchMapper.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/request/AggregationRequestSpec.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/request/MessagesRequestSpec.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/request/SearchRequestSpec.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/QueryParamsToFullRequestSpecificationMapperTest.java, graylog2-web-interface/src/components/search/SurroundingSearchButton.tsx, graylog2-web-interface/src/routing/Routes.ts, graylog2-web-interface/src/views/components/SearchBar.tsx, graylog2-web-interface/src/views/components/contexts/DrilldownContext.tsx, graylog2-web-interface/src/views/components/contexts/DrilldownContextProvider.tsx, graylog2-web-interface/src/views/components/widgets/ReplaySearchButton.tsx, graylog2-web-interface/src/views/components/widgets/WidgetActionsMenu.tsx, graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.ts, graylog2-web-interface/src/views/logic/queries/Query.ts, graylog2-web-interface/src/views/logic/search/SearchLink.ts
Adds Stream Categories of searches to the URL and Search Replay logic
maintain stream categories when navigating through history like streams currently are
=> Add stream categories to search replay

graylog2-server/src/main/java/org/graylog2/indexer/indexset/template/IndexSetTemplateService.java
/nocl unreleased feature
Attribute `index_set_config` (title: `Custom Config`) is not intended to be displayed in the UI. Currently you can toggle it on in the indexset template list, resulting in an error message.
Add missing `hidden` annotation.
- Dropdown no longer displays this attribute
- All other columns can be toggled successfully
=> Hide Custom Config attribute in UI column dropdown

changelog/unreleased/issue-20434.toml, graylog2-web-interface/src/views/components/visualizations/area/AreaVisualization.tsx, graylog2-web-interface/src/views/components/visualizations/bar/BarVisualization.tsx, graylog2-web-interface/src/views/components/visualizations/hooks/useBarChartDataSettingsWithCustomUnits.ts, graylog2-web-interface/src/views/components/visualizations/hooks/useChartDataSettingsWithCustomUnits.test.ts, graylog2-web-interface/src/views/components/visualizations/hooks/useChartDataSettingsWithCustomUnits.ts, graylog2-web-interface/src/views/components/visualizations/hooks/usePieChartDataSettingsWithCustomUnits.ts, graylog2-web-interface/src/views/components/visualizations/line/LineVisualization.tsx, graylog2-web-interface/src/views/components/visualizations/pie/PieVisualization.tsx, graylog2-web-interface/src/views/components/visualizations/scatter/ScatterVisualization.tsx, graylog2-web-interface/src/views/components/visualizations/utils/__tests__/chartLayoutGenerators.test.ts, graylog2-web-interface/src/views/components/visualizations/utils/chartLayoutGenerators.ts
Previously we use originalName in hover templates, but in some cases they are only ids of the field with advanced field types. To fix this issue we have to use name instead 
fix: https://github.com/Graylog2/graylog2-server/issues/20434
=> Use name instead of originName in hover labels templates

graylog2-web-interface/src/views/components/aggregationwizard/units/FieldUnitPopover.tsx
The bug happens because we send an empty object as a cleared state. PR set unit to undefined on clear top fix this issue 
fix: https://github.com/Graylog2/graylog2-server/issues/20399
/nocl
=> Fix issue when Unable to save dashboard containing a formattable unit field

graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/actions/MigrationActionsImpl.java, graylog2-server/src/main/java/org/graylog2/cluster/nodes/DataNodeDto.java, graylog2-web-interface/src/components/datanode/Types.ts, graylog2-web-interface/src/components/datanode/migrations/MigrationDatanodeList.tsx
Adds a warning icon to any data nodes in the list of nodes in the migration wizard that are running incompatible versions (both on welcome page and corresponding lists in in-place and remote reindexing).
Also adds an alert above the list to make the user aware of the issue.
/nocl
fixes #20471
=> Show version compatibility in migration list

misc/graylog.conf
Restores the original  example config to 
```
output_batch_size = 500
```
to make sure that when the example config is merged during OS package updates, the previously configured value is kept as is. Otherwise it might have been overwritten with
```
output_batch_size = 10mb
```
and cause an unintended change.
/nocl
=> Restore original example config for output_batch_size

changelog/unreleased/pr-20426.toml, graylog2-web-interface/src/views/bindings.tsx, graylog2-web-interface/src/views/components/aggregationbuilder/AggregationBuilder.tsx, graylog2-web-interface/src/views/components/visualizations/ChartData.ts, graylog2-web-interface/src/views/components/visualizations/PlotLegend.test.tsx, graylog2-web-interface/src/views/components/visualizations/PlotLegend.tsx, graylog2-web-interface/src/views/components/visualizations/XYPlot.tsx, graylog2-web-interface/src/views/components/visualizations/__tests__/XYPlot.test.tsx, graylog2-web-interface/src/views/components/visualizations/area/AreaVisualization.tsx, graylog2-web-interface/src/views/components/visualizations/bar/BarVisualization.tsx, graylog2-web-interface/src/views/components/visualizations/heatmap/HeatmapVisualization.tsx, graylog2-web-interface/src/views/components/visualizations/line/LineVisualization.tsx, graylog2-web-interface/src/views/components/visualizations/number/NumberVisualization.tsx, graylog2-web-interface/src/views/components/visualizations/pie/PieVisualization.tsx, graylog2-web-interface/src/views/components/visualizations/scatter/ScatterVisualization.tsx, graylog2-web-interface/src/views/components/widgets/MessageList.test.tsx, graylog2-web-interface/src/views/components/widgets/Widget.tsx, graylog2-web-interface/src/views/components/widgets/WidgetRenderingContext.tsx, graylog2-web-interface/src/views/components/widgets/events/EventsList/EventsList.test.tsx, graylog2-web-interface/src/views/logic/aggregationbuilder/AggregationWidgetConfig.ts, graylog2-web-interface/src/views/types.ts
This PR is doing multiple things to prevent charts from being cut off:
- Using the `automargin` setting in charts to prevent labels from being cut off by scaling down the chart if necessary
- Using only "inside" labels in pie charts (avoiding labels outside of the pie chart with lines pointing to the slice, as they do lead to tiny charts with lots of slices
- Introducing `WidgetRenderingContext` which can specify if a widget has a limited height in the current context (i.e. on dashboards, a widget is constrained by the widget frame, while in reporting/export it is not). This can be used in widgets to have a different layout for these scenarios.
Refs Graylog2/graylog-plugin-enterprise#8248.
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/8605
=> Prevent charts from being cut off.

data-node/src/main/java/org/graylog/datanode/opensearch/OpensearchProcessImpl.java, data-node/src/test/java/org/graylog/datanode/opensearch/OpensearchProcessImplTest.java
Use the configuration getter for `node_name` config parameter instead of the named annotation.
`node_name` is optional and might not be set, the getter has the fallback to the hostname.
/nocl
fixes #20523
fixed unit test
=> Fix node name resolution in data node

changelog/unreleased/pr-20558.toml, graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
We are using the `list` method on the user resource in a context where a user can only have the Reader role. That role lacks the permission to list all users. In this case, we only want to return the user itself in the list.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/8692
=> User list endpoint returns current user only instead of error when permission is missing

graylog2-web-interface/src/views/components/messagelist/MessagePreview.tsx
Even if the showMessageRow is false we render the table row component. That caused the issue that we rendered an empty row. This PR set showMessageRow condition to the table, not to the content. That prevents rendering empty row which is later visible on PDF document
fix: https://github.com/Graylog2/graylog-plugin-enterprise/issues/8208
/nocl
=> Do not render table row when showMessageRow is false

graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationForm.tsx, graylog2-web-interface/src/components/events/events/types.ts, graylog2-web-interface/src/views/hooks/BindSearchParamsFromQuery.ts, graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.ts, graylog2-web-interface/src/views/logic/NormalizeSearchURLQueryParams.test.ts, graylog2-web-interface/src/views/logic/NormalizeSearchURLQueryParams.ts, graylog2-web-interface/src/views/logic/queries/Query.ts, graylog2-web-interface/src/views/logic/queries/QueryGenerator.ts, graylog2-web-interface/src/views/logic/views/UseCreateSavedSearch.ts, graylog2-web-interface/src/views/logic/views/UseCreateViewForEvent.ts, graylog2-web-interface/src/views/logic/views/UseCreateViewForEventDefinition.ts, graylog2-web-interface/src/views/logic/views/ViewGenerator.ts, graylog2-web-interface/src/views/logic/views/ViewStateGenerator.ts, graylog2-web-interface/src/views/pages/NewSearchPage.test.tsx, graylog2-web-interface/src/views/pages/NewSearchPage.tsx, graylog2-web-interface/test/fixtures/createEventDefinitionFromValue.ts, graylog2-web-interface/test/helpers/mocking/EventAndEventDefinitions_mock.ts
Include stream categories in Query.filter in the same way streams work
closes: Graylog2/graylog-plugin-enterprise#7926
/nocl
These are the required modifications to include the new stream categories in Query.filter object to complement with stream filters
Users now can execute searches using stream categories linked to multiple streams
=> feat: Include stream categories in Query.filter

graylog2-server/src/main/java/org/graylog2/outputs/BatchedMessageFilterOutput.java, graylog2-server/src/test/java/org/graylog2/outputs/BatchedMessageFilterOutputTest.java
/nocl part of unreleased featured
Registering a GracefullShutdownHook for the BatchedMessageOutput to make sure that we shut down this service first before other services get exterminated by the service manager
=> Register GracefullShutdownHook for BatchedFilteredMessageOutput

graylog2-web-interface/src/views/components/TypeSpecificValue.tsx, graylog2-web-interface/src/views/components/aggregationwizard/units/FieldUnitPopover.tsx, graylog2-web-interface/src/views/components/visualizations/hooks/useChartDataSettingsWithCustomUnits.test.ts, graylog2-web-interface/src/views/components/visualizations/utils/__tests__/chartLayoutGenerators.test.ts, graylog2-web-interface/src/views/components/visualizations/utils/__tests__/fixtures.ts, graylog2-web-interface/src/views/components/visualizations/utils/chartLayoutGenerators.ts, graylog2-web-interface/src/views/components/visualizations/utils/formatValueWithUnitLabel.ts, graylog2-web-interface/src/views/components/visualizations/utils/getUnitTextLabel.ts
As we already use `abbrev` param as a key we cant change it to fix the problem. Because of that, we add a new mapper for labels. 
fix: https://github.com/Graylog2/graylog2-server/issues/20518
/nocl
=> Add specific labels for sizes

graylog2-web-interface/src/views/components/visualizations/heatmap/HeatmapVisualization.tsx
By using the provided width we can ensure the desired width. In some cases the heatmap did not use the all the available space.
I tested this change with widgets on dashboards, the big display mode, the widget PDF export and reporting.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/8699
/nocl
=> Use provided with for heatmap visualization container.

graylog2-web-interface/src/contexts/DefaultQueryClientProvider.tsx
This PR sets the default parameter for DefaultQueryClientProvider to not rerun react query requests when there are client errors.
When we use react-query to get some data and requests fail, react-query retries this action several times (by default 3). Sometimes that doesn't make any sense, because the response is always the same. That happens mainly when we have missing data in the request body or an unauthorized user or any other client errors. All these errors have status 400-417. So it makes sense not to overload the server with unnecessary requests the response of which is already known and not to use rerun when we catch this kind of error for the first time. 
/nocl
=> Do not use retry in use-query on 4xx failure statuses

changelog/unreleased/issue-13822.toml, graylog2-web-interface/src/util/DocsHelper.ts, graylog2-web-interface/src/views/components/searchbar/queryvalidation/QueryValidation.test.tsx, graylog2-web-interface/src/views/components/searchbar/queryvalidation/QueryValidation.tsx
As described in https://github.com/Graylog2/graylog2-server/issues/13822 the documentation link for search errors only points to the search query documentation page.
Now it points to the error types section again.
We talked with the docs team about using error type specific links and they suggested to just link to the section, because:
- the section is small
- there are just a few error types
- it is at the end of the page and it wont make a difference to link to a specific error type.
Fixes: https://github.com/Graylog2/graylog2-server/issues/13822
=> Fix documentation link target for search query errors.

graylog2-server/src/main/resources/log4j2.xml
We're now using a more low-level protocol to render reports in enterprise. The used implementation is very chatty on `info` level, so we're setting it to `warn` per default.
We have no mechanism to do this in the Enterprise module, so this change has to be done in the regular Server module.
/nocl
=> Setting the log level for CDP to `warn` for Enterprise Reporting

changelog/unreleased/issue-20464..toml, graylog2-web-interface/src/views/components/messagelist/NodeName.tsx
Please note, this is a backport of https://github.com/Graylog2/graylog2-server/pull/20505 for `6.0`
With this PR we display only the node name instead of name with link in message details on the search page In cloud env.
=> Display only name instead of name with link for node in message details. `6.0`

changelog/unreleased/issue-20464.toml, graylog2-web-interface/src/views/components/messagelist/NodeName.tsx
Please note, this is a backport of https://github.com/Graylog2/graylog2-server/pull/20505 for `5.2`
With this PR we display only node name instead of name with link in message details on the search page In cloud env.
=> Display only name instead of name with link for node in message details. `5.2`

graylog2-server/src/main/java/org/graylog/plugins/map/config/GeoIpProcessorConfig.java, graylog2-server/src/main/java/org/graylog/scheduler/JobSchedulerConfiguration.java
If fields annotated with `@Parameter` are make final and then accessed through a method, e.g. a getter, the default value will be inlined by the Java compiler. Setting a differnet value via our configuration mechanism won't have any effect in that case, which is unexpected.
/nocl
=> Make config parameters not final

graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetFieldTypeSummaryService.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexSetsMappingResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/responses/IndexSetIdAndType.java, graylog2-server/src/test/java/org/graylog2/indexer/indexset/IndexSetFieldTypeSummaryServiceTest.java
New endpoint, filtering of index sets moved to BE.
/nocl
It is better to filter out index sets that cannot have their field types changes in the BE, instead of fighting with a way to disable them in the FE.
FE needs a way to figure out all index sets' IDs, not only the ones on the first page, so that field type can be changed everywhere.
Manually.
=> New endpoint, filtering of index sets moved to BE

graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/DatanodeMigrationBindings.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/machine/MigrationShutdownService.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/machine/MigrationStateMachineContext.java, graylog2-server/src/main/java/org/graylog/plugins/views/storage/migration/state/machine/MigrationStateMachineImpl.java, graylog2-server/src/main/java/org/graylog2/indexer/datanode/CurrentWriteIndices.java, graylog2-server/src/main/java/org/graylog2/indexer/datanode/RemoteReindexingMigrationAdapter.java, graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java, graylog2-server/src/main/java/org/graylog2/migrations/V20240927120300_DataNodeMigrationIndexSet.java, graylog2-server/src/test/java/org/graylog2/migrations/V20240927120300_DataNodeMigrationIndexSetTest.java
This PR stores the current write index into the migration state machine context when stopping Graylog and the migration state machine is in a matching state.
Upon startup, these indices are the restored for the corresponding index sets if they do not exist (i.e. in an empty data node) to make sure that data node starts indexing into the last known index instead of `_0` which causes problems that data might get lost. 
/nocl
see https://github.com/Graylog2/graylog-plugin-enterprise/issues/8367
manually, added unit test
=> fix write index in data node migration

graylog2-server/src/main/java/org/graylog2/streams/filters/StreamDestinationFilterService.java, graylog2-server/src/test/java/org/graylog2/streams/filters/StreamDestinationFilterServiceTest.java
/nocl unreleased
Resolves Graylog2/graylog-plugin-enterprise#7833 
Add handler for stream deletion to `StreamDestinationFilterService`
=> Delete stream destination filters when deleting a stream

graylog2-server/src/main/java/org/graylog/events/processor/DBEventProcessorStateService.java, graylog2-server/src/main/java/org/graylog2/database/MongoDBUpsertRetryer.java, graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypesService.java, graylog2-server/src/main/java/org/graylog2/system/processing/DBProcessingStatusService.java, graylog2-server/src/main/java/org/graylog2/users/RoleServiceImpl.java
The MongoDBUpsertRetryer was intended to fix issues with MongoDB upsert behaviour for MongoDB versions < 4.2. Graylog does not support MongoDB versions < 5.0 anymore, so we can deprecate the class and remove its usages.
see https://jira.mongodb.org/browse/SERVER-14322 and [the original issue](https://github.com/Graylog2/graylog2-server/issues/7258) which lead to the introduction of the class.
/nocl
=> Deprecate MongoDBUpsertRetryer and remove usages

graylog2-web-interface/src/logic/telemetry/TelemetryInit.tsx
This PR disables `cross_subdomain_cookie` for Posthog telemetry and sets default persistence to cookie.
/nocl
=> Disable cross_subdomain_cookie for telemetry

.github/dependabot.yml
See: https://lucene.apache.org/core/corenews.html#apache-lucenetm-1000-available
Refs #20700
/nocl
=> Let dependabot ignore Lucene versions >=10 until we update to JDK 21

graylog2-web-interface/src/routing/App.tsx
With this PR we register the `App` component as a `singleton`. This is necessary for reliable comparison checks. Currently a compression check happens in the `AppRouter` for plugin routes with a `parentComponent`. Defining the `App` as a parent component allows rendering the page independent of the `PageContentLayout`.
/nocl
=> Make `App` component a singleton.

graylog2-web-interface/src/views/components/searchbar/StreamsFilter.tsx, graylog2-web-interface/src/views/components/sidebar/NavItem.tsx, graylog2-web-interface/src/views/components/sidebar/SidebarNavigation.tsx, graylog2-web-interface/src/views/types.ts
This PR adds the option to render links in the search sidebar via the plugin system.
Hover styling:
Active styling:
/nocl
=> Implement option to display links in search sidebar.

changelog/unreleased/pr-20714.toml, graylog2-web-interface/src/components/streams/MatchingTypeSwitcher.tsx, graylog2-web-interface/src/components/streams/StreamDetails/StreamDataRoutingIntake.tsx
The issue was introduced with this PR: https://github.com/Graylog2/graylog2-server/pull/20678
=> Hide stream rule Matching-Type-Switcher when stream is not editable

graylog2-server/src/main/java/org/graylog2/search/SearchQueryField.java, graylog2-server/src/test/java/org/graylog2/database/filtering/DbFilterExpressionParserTest.java
Adds ability to supply a pagination request filter to the `SearchQueryParser` with a `double` value persisted in MongoDB.
For example:
```
SearchQueryField.create("my_field", SearchQueryField.Type.DOUBLE)
```
/nocl Provides needed server changes for https://github.com/Graylog2/graylog-plugin-enterprise/pull/8924.
=> Add ability to filter by double values within Mongo search queries

graylog2-web-interface/src/views/components/searchbar/StreamsFilter.tsx, graylog2-web-interface/src/views/components/searchbar/queryinput/QueryInput.tsx
This PR contains two small changes for the search bar components.
We:
- ensure `completers` prop of `QueryInput` can be not defined.
- ensure `clearable` props of `StreamsFilter` can be configured.
/nocl
=> Improve reusability of `QueryInput` and `StreamsFilter`.

graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationForm.tsx
Due to this change 
in https://github.com/Graylog2/graylog2-server/pull/20727, we are now returning `undefined` instead of an empty object, which led to the runtime error.
This error occurred when opening the create event notification form.
/nocl
=> Fix can not read `formComponent` of `undefined` error on create event notification page.

graylog2-web-interface/webpack/core.js
This PR fixes the error when starting the dev server caused by the javascript heap out of memory.
```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
RpcExitError: Process 7544 exited [SIGABRT]
Issues checking service aborted - probably out of memory. Check the `memoryLimit` option in the ForkTsCheckerWebpackPlugin configuration.
If increasing the memory doesn't solve the issue, it's most probably a bug in the TypeScript.
```
/nocl
=> Increase ForkTsCheckerWebpackPlugin memoryLimit

changelog/unreleased/issue-20738.toml, graylog2-server/src/main/java/org/graylog/security/certutil/CertificateGenerator.java, graylog2-server/src/test/java/org/graylog/security/certutil/CertificateGeneratorTest.java
Backport of https://github.com/graylog2/graylog2-server/pull/20745
=> Backport: Fix cname encoding in CertificateGenerator

graylog2-web-interface/src/components/common/Select/PaginatedSelect.tsx, graylog2-web-interface/src/components/users/UsersSelectField.tsx
This PR is improving the reusability of the `PaginatedSelect` component. Currently we are only using the select in the `UsersSelectField` component. When using it in more places, we have to repeat some of the logic in the `UsersSelectField` component. With this PR we are moving this logic (mainly the state management) into the `PaginatedSelect`, so we do not have to repeat it.
When using the `PaginatedSelect` you now just need to provide a function to fetch the data and the component will take care of the state management.
/nocl
=> Improve reusability of `PaginatedSelect`.

changelog/unreleased/issue-20738.toml, graylog2-server/src/main/java/org/graylog/security/certutil/CertificateGenerator.java, graylog2-server/src/test/java/org/graylog/security/certutil/CertificateGeneratorTest.java
Backport of https://github.com/graylog2/graylog2-server/pull/20745
=> 6.1 backport: Fix cname encoding in CertificateGenerator

graylog2-server/src/main/java/org/graylog/security/certutil/CertutilTruststore.java, graylog2-server/src/main/java/org/graylog2/bootstrap/Main.java, graylog2-server/src/test/java/org/graylog2/security/certutil/CertutilTruststoreTest.java
Forgot to link the truststore command in the graylog server, added now. Also added explicit handling of unknown CA file. 
/nocl
Manually
=> Add certutil truststore command to the graylog server commands

graylog2-web-interface/src/views/components/DashboardSearchBar.test.tsx, graylog2-web-interface/src/views/components/DashboardSearchBar.tsx, graylog2-web-interface/src/views/components/SearchBar.tsx, graylog2-web-interface/src/views/components/WidgetQueryControls.pluggableControls.test.tsx, graylog2-web-interface/src/views/components/WidgetQueryControls.test.tsx, graylog2-web-interface/src/views/components/WidgetQueryControls.tsx, graylog2-web-interface/src/views/components/searchbar/ViewsQueryInput.test.tsx, graylog2-web-interface/src/views/components/searchbar/ViewsQueryInput.tsx, graylog2-web-interface/src/views/components/searchbar/queryinput/QueryInput.tsx, graylog2-web-interface/src/views/components/widgets/Widget.test.tsx
With this PR we move all the views related code from the `QueryInput` component in to a new `ViewsQueryInput` component. This way we can reuse the `QueryInput` outside of the search page.
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/8995
/nocl
=> Improve reusability of query input component.

graylog2-web-interface/package.json, graylog2-web-interface/src/components/common/MarkdownEditor/Editor.tsx, graylog2-web-interface/src/components/common/MarkdownEditor/EditorModal.tsx, graylog2-web-interface/src/components/rules/RuleForm.tsx, graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.tsx, graylog2-web-interface/src/routing/loadAsync.tsx, graylog2-web-interface/src/views/types.ts, graylog2-web-interface/yarn.lock
This PR is bumping the React types package effectively to `18.3.12` due to the current need to set its version explicitly in the `resolutions` clause.
/prd Graylog2/graylog-plugin-enterprise#9000
=> Bumping `@types/react` effectively to `18.3.12`.

graylog2-web-interface/src/preflight/index.tsx
This PR is removing the usage of `ReactDOM.render` in the preflight UI, as according to the React 19 [migration notes](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-reactdom-render).
=> Removing usage of `ReactDOM.render` in preflight UI.

changelog/unreleased/pr-20788.toml, graylog2-server/src/main/java/org/graylog2/inputs/codecs/SyslogCodec.java, graylog2-server/src/test/java/org/graylog2/inputs/codecs/SyslogCodecTest.java
Backport https://github.com/Graylog2/graylog2-server/pull/20788 to the `6.1` branch.
=> Backport 6.1: Syslog inputs: Trim newlines for Fortigate messages

changelog/unreleased/pr-20847.toml, graylog2-web-interface/src/components/events/events/EventDetails.tsx
Fixes logic for displaying the pluggable event actions on the Events & Alerts page. Previously, some events did not have these actions which should have. This change correctly only completely hides the actions for system notification events.
For further context see the issue this fixes Graylog2/graylog-plugin-enterprise#8638
=> Fix logic for showing/hiding pluggable event actions

graylog2-web-interface/src/views/components/messagelist/Types.ts
With this PR we extend `BackendMessage` type with `timestamp` attribute. It is always part of the message, like the id.
/nocl
=> Extend `BackendMessage` type

changelog/unreleased/issue-20790.toml, graylog2-server/src/main/resources/prometheus-exporter.yml
**Note:** This PR requires a backport to `6.1`.
Previously, the output class name changed from `BlockingBatchedESOutput` to `BatchedMessageFilterOutput`, but this was not reflected in the prometheus exporter config. This PR fixes this.
Fixes #20790.
=> Adjusting output class name in prometheus config.

changelog/unreleased/issue-20876.toml, graylog2-web-interface/src/views/components/highlighting/CustomHighlighting.test.tsx, graylog2-web-interface/src/views/logic/views/formatting/highlighting/HighlightingColor.ts
This PR is fixing the `unknown format` error which can occur for widgets on the search page, when using a gradient highlight.
The error seems to happen since updating `chroma.js` from `2.4.2` to `2.6.0`.
We are using `chroma.js` to generate the highlight background color and a contrasting text color. Before this PR we were generating a chroma color object for the gradient highlight color. When generating the contrasting text color, chroma threw an error, because the highlighting color has no mode:
https://github.com/gka/chroma.js/blob/v2.6.0/dist/chroma.cjs#L182
The error message `unknown format: hex-color-value` is a bit misleading.
With this PR we are just generating a hex color for the highlight instead of a color object.
Fixes https://github.com/Graylog2/graylog2-server/issues/20876
=> Fixing `unknown format` issue when using gradient highlighting search page.

changelog/unreleased/issue-20876.toml, graylog2-web-interface/src/views/components/highlighting/CustomHighlighting.test.tsx, graylog2-web-interface/src/views/logic/views/formatting/highlighting/HighlightingColor.ts
Please note, this is a backport of https://github.com/Graylog2/graylog2-server/pull/20882 for `6.1`.
This PR is fixing the `unknown format` error which can occur for widgets on the search page, when using a gradient highlight.
The error seems to happen since updating `chroma.js` from `2.4.2` to `2.6.0`.
We are using `chroma.js` to generate the highlight background color and a contrasting text color. Before this PR we were generating a chroma color object for the gradient highlight color. When generating the contrasting text color, chroma threw an error, because the highlighting color has no mode:
https://github.com/gka/chroma.js/blob/v2.6.0/dist/chroma.cjs#L182
The error message `unknown format: hex-color-value` is a bit misleading.
With this PR we are just generating a hex color for the …
=> Fixing `unknown format` issue when using gradient highlighting on search page. (`6.1`)

changelog/unreleased/issue-20790.toml, graylog2-server/src/main/resources/prometheus-exporter.yml
**Note:** This is a backport of #20844 to `6.1`.
Previously, the output class name changed from `BlockingBatchedESOutput` to `BatchedMessageFilterOutput`, but this was not reflected in the prometheus exporter config. This PR fixes this.
Fixes #20790.
=> Adjusting output class name in prometheus config. (`6.1`)

graylog2-web-interface/packages/eslint-config-graylog/index.js
This PR adjusts the `@typescript-eslint/no-unused-vars` linter rule to accept variables starting with `ignored` to be unused.
=> Adding `ignored` as allowed unused variable name pattern.

changelog/unreleased/issue-15301.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/MultiGrokMatch.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/multiGrok.txt
Adds new `multi_grok` pipeline rule that takes a list of Grok patterns to process a string against and short-circuits on the first match and returns it. 
closes #15301
increase efficiency and reduce verbosity of pipeline rules that attempt to match a string to multiple Grok patterns.
local dev env in the pipeline rule simulator
```
rule "function test multigrok"
when
true
then
set_fields(
fields: multi_grok(
patterns: [
"^ABC %{IPORHOST:msg_ip}: %{GREEDYDATA:abc_message}",
"^123 %{IPORHOST:msg_ip}: %{GREEDYDATA:123_message}",
"^ABC2 %{IPORHOST:abc_ip}: %{GREEDYDATA:abc_message}"
],
value: to_string($message.message),
only_named_captures: true
)
);
end
```
=> Add multi_grok pipeline rule

changelog/unreleased/issue-20899.toml, graylog2-web-interface/src/logic/telemetry/useSendTelemetry.test.tsx, graylog2-web-interface/src/logic/telemetry/useSendTelemetry.tsx, graylog2-web-interface/src/util/URLUtils.test.ts, graylog2-web-interface/src/util/URLUtils.ts
**Note:** This is a backport of #20909 to `6.1`.
This PR is fixing an issue related to path prefix handling in the `useSendTelemetry` hook. When a path prefix is defined, that hook is preparing a function to send telemetry (regardless if telemetry is enabled or not) and pre-constructs a context including the pathname of the current page. Previously, the logic to strip the path prefix from the route was incorrect, in that it tries to remove it before matching it to routes instead of stripping it from the matched route. 
This PR is fixing this by changing the order in which the path prefix is stripped.
Fixes #20899.
Fixes #20837.
=> Fix handling of path prefix in `useSendTelemetry`. (`6.1`)

changelog/unreleased/pr-20910.toml, graylog2-web-interface/src/views/bindings.tsx
**Note:** This is a backport of #20910 to `6.1`.
This PR is fixing up routes for the "Replay Search" endpoints, which were previously qualified twice, leading to issues when a path prefix is configured.
=> Fixing replay search routes when path prefix is present. (`6.1`)

data-node/src/main/java/org/graylog/datanode/opensearch/configuration/OpensearchConfiguration.java
Calls to data node's Opensearch endpoint `_nodes` show a deprecation warning in the logs. This change removes this deprecation warning.
/nocl internal change
fixes #20759 
Startup data node without this change
-> any call to `_nodes` from Graylog will show warning in Graylog logs
alternatively, call `/api/datanodes/any/opensearch/_nodes` endpoint directly, check Graylog logs
Startup data node with change
-> no warning is shown
=> Fix deprecation warning in data node

changelog/unreleased/issue-20789.toml, graylog2-web-interface/src/views/components/visualizations/GenericPlot.tsx
Please note, this PR requires a backport for (only) `6.1`.
As described in https://github.com/Graylog2/graylog2-server/issues/20789 the label of a bar in the bar chart is not readable in the dark mode, when the label is displayed outside of the bar.
Before:
After:
Fixes https://github.com/Graylog2/graylog2-server/issues/20789
=> Fixing text color of bar labels in bar chart, which are displayed outside of a bar.

changelog/unreleased/issue-enterprise-6479.toml, full-backend-tests/src/test/java/org/graylog/plugins/views/aggregations/AggregationSortingIT.java, full-backend-tests/src/test/java/org/graylog/plugins/views/aggregations/SearchAggregationsIT.java, full-backend-tests/src/test/java/org/graylog/plugins/views/aggregations/SearchWithAggregationsSupportingMissingBucketsIT.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/ESPivotBucketSpecHandler.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/buckets/ESTimeHandler.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/buckets/ESValuesHandler.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/RunningElasticsearchInstanceES7.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/pivot/OSPivotBucketSpecHandler.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/pivot/buckets/OSTimeHandler.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/pivot/buckets/OSValuesHandler.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/FieldTypes.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/GraylogApis.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/Search.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/Streams.java
**Note:** This is a backport of #20918 to `6.1`.
This PR is fixing sorting for cases where a numeric pivot is configured as sort order for an aggregation. Previously, the values returned were order lexicographically. This PR makes use of a nested aggregation for sorting, that allows us to sort results numerically instead, if the underlying field type of the pivot is a numeric one.
Fixes Graylog2/graylog-plugin-enterprise#6479.
=> Sorting pivot values numerically when field is numeric. (`6.1`)

changelog/unreleased/issue-enterprise-6479.toml, full-backend-tests/src/test/java/org/graylog/plugins/views/aggregations/AggregationSortingIT.java, full-backend-tests/src/test/java/org/graylog/plugins/views/aggregations/SearchAggregationsIT.java, full-backend-tests/src/test/java/org/graylog/plugins/views/aggregations/SearchWithAggregationsSupportingMissingBucketsIT.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/ESPivotBucketSpecHandler.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/buckets/ESTimeHandler.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/buckets/ESValuesHandler.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/RunningElasticsearchInstanceES7.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/pivot/OSPivotBucketSpecHandler.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/pivot/buckets/OSTimeHandler.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/pivot/buckets/OSValuesHandler.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/FieldTypes.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/GraylogApis.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/Indices.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/Search.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/Streams.java
**Note:** This is a backport of #20918 to `6.0`.
This PR is fixing sorting for cases where a numeric pivot is configured as sort order for an aggregation. Previously, the values returned were order lexicographically. This PR makes use of a nested aggregation for sorting, that allows us to sort results numerically instead, if the underlying field type of the pivot is a numeric one.
Fixes Graylog2/graylog-plugin-enterprise#6479.
=> Sorting pivot values numerically when field is numeric. (`6.0`)

changelog/unreleased/pr-20969.toml, graylog2-web-interface/src/integrations/aws/AWSInputConfiguration.jsx, graylog2-web-interface/src/integrations/aws/common/Routes.ts, graylog2-web-interface/src/integrations/bindings.jsx
**Please note**, this PR is a backport of https://github.com/Graylog2/graylog2-server/pull/20969 for `6.1`.
When running Graylog with a path prefix (e.g. `http://localhost:9000/graylog`), a route in the AWs integration was broken, because it did not include the path prefix. This PR is fixing the issue by qualifying the related route properly.
Realted to: https://github.com/Graylog2/graylog-plugin-enterprise/issues/9148
=> Fixing AWS integration routes when path prefix is present. `6.1`

changelog/unreleased/issue-20789.toml, graylog2-web-interface/src/views/components/visualizations/GenericPlot.tsx
Please note, this PR is a backport of https://github.com/Graylog2/graylog2-server/pull/20948 for `6.1`.
As described in https://github.com/Graylog2/graylog2-server/issues/20789 the label of a bar in the bar chart is not readable in the dark mode, when the label is displayed outside of the bar.
Before:
After:
Fixes https://github.com/Graylog2/graylog2-server/issues/20789
=> Fixing text color of bar labels in bar chart, which are displayed outside of a bar. `6.1`

changelog/unreleased/issue-18388.toml, graylog2-web-interface/src/views/components/Value.tsx, graylog2-web-interface/src/views/components/messagelist/MessageFields.tsx
**Please note:** this PR is a backport of https://github.com/Graylog2/graylog2-server/pull/20921 for `6.1`.
Before this change the highlighting of field values in the message details of the message table widget was broken.
This happened because the whole field row (`dt`) was wrapped with `CustomHighlight`. As a result the font color got applied for both the field name and value. The background color also got applied for the whole row, but was not visible because of the related DOM structure.
For dark highlight colors a light font color will be generated and the row looked empty.
This PR is fixing the issue by only wrapping the field value with `CustomHighlight`.
I tested this change with decorators and extended our e2e tests.
Fixes: https://github.com/Graylog2/graylog2-server/issues/18388
=> Fix custom highlighting of field values in the message details of the message table widget. `6.1`

changelog/unreleased/issue-18388.toml, graylog2-web-interface/src/views/components/Value.tsx, graylog2-web-interface/src/views/components/messagelist/MessageFields.tsx
**Please note:** this PR is a backport of https://github.com/Graylog2/graylog2-server/pull/20921 for `6.1` and `6.0`.
Before this change the highlighting of field values in the message details of the message table widget was broken.
This happened because the whole field row (`dt`) was wrapped with `CustomHighlight`. As a result the font color got applied for both the field name and value. The background color also got applied for the whole row, but was not visible because of the related DOM structure.
For dark highlight colors a light font color will be generated and the row looked empty.
This PR is fixing the issue by only wrapping the field value with `CustomHighlight`.
I tested this change with decorators and extended our e2e tests.
Fixes: …
=> Fix custom highlighting of field values in the message details of the message table widget. `6.0`

changelog/unreleased/pr-20969.toml, graylog2-web-interface/src/integrations/aws/AWSInputConfiguration.jsx, graylog2-web-interface/src/integrations/aws/common/Routes.ts, graylog2-web-interface/src/integrations/bindings.jsx
**Please note**, this PR https://github.com/Graylog2/graylog2-server/pull/20969 is a backport of for `6.0`.
When running Graylog with a path prefix (e.g. `http://localhost:9000/graylog`), a route in the AWs integration was broken, because it did not include the path prefix. This PR is fixing the issue by qualifying the related route properly.
Realted to: https://github.com/Graylog2/graylog-plugin-enterprise/issues/9148
=> Fixing AWS integration routes when path prefix is present. `6.0`

changelog/unreleased/issue-15301.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/MultiGrokMatch.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/multiGrok.txt
Backports #20924 to 6.1 to allow SecCon team to utilize the new function in content sooner.
=> Backport 6.1: Add multi_grok pipeline function

graylog2-web-interface/src/components/sidecars/common/OperatingSystemIcon.test.tsx, graylog2-web-interface/src/components/sidecars/common/OperatingSystemIcon.tsx, graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.tsx, graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationVariablesHelper.tsx, graylog2-web-interface/src/components/sidecars/configurations/CollectorList.test.tsx, graylog2-web-interface/src/components/sidecars/configurations/CollectorList.tsx, graylog2-web-interface/src/components/sidecars/configurations/CollectorListContainer.tsx, graylog2-web-interface/src/components/sidecars/configurations/CollectorRow.tsx, graylog2-web-interface/src/components/sidecars/sidecars/SidecarListContainer.tsx, graylog2-web-interface/src/components/sidecars/types.ts, graylog2-web-interface/src/pages/SidecarEditConfigurationPage.tsx, graylog2-web-interface/src/stores/__tests__/connect.test.tsx, graylog2-web-interface/src/stores/connect.tsx, graylog2-web-interface/src/stores/sidecars/SidecarsStore.ts
This PR is fixing an issue on the sidecars page, where the missing `getInitialState` function of the `SidecarsStore` lead to an issue after switching over its usage to `useStore`.
This PR is fixing this issue with the store, but also the `useStore` function's handling of a missing `getInitialState` function.
Fixes #20873.
Fixes Graylog2/collector-sidecar#455.
/nocl Regression was not in a released version.
=> Fixing up store initialization on sidecars page.

changelog/unreleased/pr-20896.toml, changelog/unreleased/pr-20996.toml, graylog2-web-interface/src/components/common/CommonRefreshControls.tsx, graylog2-web-interface/src/components/common/RefreshControls.tsx, graylog2-web-interface/src/components/events/EventsEntityTable.tsx, graylog2-web-interface/src/components/events/events/EventsRefreshControls.tsx, graylog2-web-interface/src/logic/telemetry/Constants.ts, graylog2-web-interface/src/util/DateTime.ts, graylog2-web-interface/src/views/components/DashboardSearchBar.tsx, graylog2-web-interface/src/views/components/SearchBar.tsx, graylog2-web-interface/src/views/components/searchbar/ViewsRefreshControls.test.tsx, graylog2-web-interface/src/views/components/searchbar/ViewsRefreshControls.tsx, graylog2-web-interface/src/views/hooks/useDefaultIntervalForRefresh.ts
This PR refactor creates CommonRefreshControls components to reuse most of the logic in RefreshControls components.
Also, we add a refresh action to events page.
fix: https://github.com/Graylog2/graylog-plugin-enterprise/issues/8661
/jpd https://github.com/Graylog2/graylog-plugin-enterprise/pull/9269
=> Add auto refresh button to events page

data-node/pom.xml
This plugin is not used anyhow. Let's reduce distribution size, speed up startup of the opensearch and avoid possible problems during plugin init. 
/nocl
=> Remove opensearch observability plugin from datanode

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/IndicesAdapterOS2.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexMappingTemplate.java, graylog2-server/src/main/java/org/graylog2/indexer/indices/IndexSettings.java, graylog2-server/src/main/java/org/graylog2/indexer/indices/IndexSettingsHelper.java, graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java, graylog2-server/src/main/java/org/graylog2/indexer/indices/IndicesAdapter.java
With this PR we offer the option to retrieve settings for an index and also apply them during index creation. This is a companion PR to Graylog2/graylog-plugin-enterprise#9271, where we use this option for restoring archives.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#9271
/nocl
=> implement option to get and apply index settings

graylog2-server/src/main/java/org/graylog/scheduler/DBCustomJobDefinitionService.java, graylog2-server/src/main/java/org/graylog/scheduler/DBJobDefinitionService.java, graylog2-server/src/main/java/org/graylog/scheduler/JobDefinitionDto.java, graylog2-server/src/test/java/org/graylog/events/legacy/LegacyAlertConditionMigratorTest.java, graylog2-server/src/test/java/org/graylog/events/processor/EventDefinitionHandlerTest.java, graylog2-server/src/test/java/org/graylog/scheduler/DBJobDefinitionServiceTest.java, graylog2-server/src/test/java/org/graylog/scheduler/JobSchedulerServiceIT.java
Also strips the deprecated `DBCustomJobDefinitionService` down to a shallow wrapper and removes usages.
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/9243
/nocl
=> Refactor DBJobDefinitionService to use new MongoDB API

full-backend-tests/src/test/java/org/graylog/pipelines/StreamsPipelinesIT.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java
/nocl 
Improve access check and check if the authenticated user has access to the stream before returning the connected pipelines.
fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/9272
=> improve user access right check on stream getConnectedPipelines

graylog2-web-interface/src/components/authentication/BackendCreate/ServiceSelect.tsx, graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/UserSyncStep.tsx, graylog2-web-interface/src/components/common/Select/Select.test.jsx, graylog2-web-interface/src/components/common/Select/Select.tsx, graylog2-web-interface/src/components/indices/IndexSetFieldTypeProfiles/ProfileForm.tsx, graylog2-web-interface/src/components/indices/IndexSetFieldTypes/SetProfileModal.tsx, graylog2-web-interface/src/components/lookup-table-parameters/LookupTableParameterEdit.tsx, graylog2-web-interface/src/components/permissions/CapabilitySelect.tsx, graylog2-web-interface/src/components/permissions/GranteesSelector.tsx, graylog2-web-interface/src/components/permissions/RolesSelector.tsx, graylog2-web-interface/src/components/roles/RoleEdit/UsersSelector.tsx, graylog2-web-interface/src/components/rules/rule-builder/RuleBlockForm.tsx, graylog2-web-interface/src/components/streamrules/StreamRuleModal.tsx, graylog2-web-interface/src/components/streams/IndexSetSelect.tsx, graylog2-web-interface/src/components/users/TimeoutUnitSelect.tsx, graylog2-web-interface/src/views/components/aggregationwizard/visualization/configurationFields/MultiSelectField.tsx, graylog2-web-interface/src/views/components/searchbar/StreamCategoryFilter.tsx, graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingColorForm.tsx, graylog2-web-interface/src/views/logic/fieldactions/ChangeFieldType/ChangeFieldTypeModal.tsx, graylog2-web-interface/src/views/logic/fieldactions/ChangeFieldType/FieldSelect.tsx
With this PR we are:
- using the `Select` `placeholder` prop for the `Select` aria label, if no custom `aria-label` prop has been defined
- extending the `Select` `Props` type with the `aria-label` attribute.
- replacing usages of `inputProps={ 'aria-label': ... }` with `aria-label=...`
- removing the `aria-label` prop when it is identical to the `placeholder` prop
Defining the `aria-label` prop for the `Select` was possible before, but now we added proper types for this case and unified the usage.
I made this change because:
- The `Select` `placeholder` and `aria-label` were often identical
- There is no disadvantage in using the `placeholder` for the aria label.
- We often need to rely on the `Select` aria label in tests, because it is a reliable way to "find" the `Select`. For example …
=> Improve handling of `Select` `aria-label` prop.

full-backend-tests/src/test/java/org/graylog/datanode/ClientCertResourceIT.java
Adjust `ClientCertResourceIT` to match the generated expiration date.
/nocl
=> reflect client certificate expiry date test to reflect generated expiry

graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config
/nocl
`SETUP_MODE` feature flag exists to allow a preview of the Input Setup Wizard.
Set it to `off` in the config to avoid noisy warnings in the log file.
=> Add feature flag for setup mode

graylog2-server/src/main/java/org/graylog/events/processor/aggregation/PivotAggregationSearch.java, graylog2-server/src/main/java/org/graylog/events/search/MoreSearch.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/PermittedStreams.java, graylog2-server/src/test/java/org/graylog/events/processor/aggregation/PivotAggregationSearchTest.java
This PR is a refactoring attempting to reduce the `MoreSearch` class, which is a hacky workaround to implement searches in the events/alerting system. It duplicates multiple aspects of other classes and should be removed. This PR is focussing on fetching streams, replacing it with `StreamService#loadById` and `PermittedStreams`.
=> Trimming down `MoreSearch` class.

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/db/PipelineService.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/db/PipelineStreamConnectionsService.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/db/memory/InMemoryPipelineService.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/db/memory/InMemoryPipelineStreamConnectionsService.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/db/mongodb/MongoDbPipelineService.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/db/mongodb/MongoDbPipelineStreamConnectionsService.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java
This is a follow-up to #21057, avoiding an n+1 performance issue when retrieving pipeline connections for multiple streams. This change is now fetching the associated pipeline connections and referenced pipelines in single bulk requests instead of for each stream + for each connected pipeline.
=> Avoiding n+1 when retrieving bulk pipeline connections for streams.

graylog2-web-interface/packages/eslint-config-graylog/index.js
This PR is making sure that ESLint is grouping the generated API modules as `external` consistently.
Fixes Graylog2/graylog-plugin-enterprise#9294.
=> Grouping `@graylog/*-api` as external modules in ESLint.

UPGRADING.md, graylog2-web-interface/src/components/streams/StreamsOverview/StreamActions.tsx, graylog2-web-interface/src/views/components/aggregationwizard/AggregationWizard.test.tsx, graylog2-web-interface/src/views/components/aggregationwizard/AggregationWizard.tsx, graylog2-web-interface/src/views/components/aggregationwizard/ElementsConfiguration.tsx, graylog2-web-interface/src/views/components/aggregationwizard/FieldSelect.tsx, graylog2-web-interface/src/views/components/aggregationwizard/FieldSelectBase.tsx, graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.corevisualizations.test.tsx, graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.groupBy.test.tsx, graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.metric.test.tsx, graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.sort.test.tsx, graylog2-web-interface/src/views/components/common/EditableTitle.tsx, graylog2-web-interface/src/views/components/contexts/WidgetEditApplyAllChangesProvider.tsx, graylog2-web-interface/src/views/components/widgets/EditMessageList.tsx, graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.test.tsx, graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.tsx, graylog2-web-interface/src/views/components/widgets/FieldsConfiguration.tsx, graylog2-web-interface/src/views/components/widgets/SaveOrCancelButtons.tsx, graylog2-web-interface/src/views/components/widgets/Widget.tsx, graylog2-web-interface/src/views/components/widgets/WidgetHeader.tsx, graylog2-web-interface/src/views/components/widgets/events/EventsWidgetEdit.tsx, graylog2-web-interface/src/views/types.ts
This PR is improving the reusability of some widget related component, so they can be reused outside of the search page.
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/9261
/nocl
=> Improve reusability of widget edit components

changelog/unreleased/pr-21044.toml, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/MoreSearchAdapterOS2.java, graylog2-server/src/main/java/org/graylog/events/search/MoreSearch.java, graylog2-web-interface/src/components/events/Constants.ts, graylog2-web-interface/src/components/events/events/ColumnRenderers.tsx
This PR enables sorting alerts/events based on aggregation time range both in the front- and backend.
The sorting for this field needs to be created so that both `timerange_start` & `timerange_end` are taken into account.
=> Allow sorting events/alerts based on aggregation time range.

graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java
/nocl part of Input setup wizard
Relates to #20569 
Adds an API to return the list of all streams connected to a given index set ID
`GET /streams/byIndex/{indexSetId}`
=> New API streams/byIndex 

changelog/unreleased/issue-20785.toml, graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessor.java, graylog2-server/src/main/java/org/graylog2/notifications/Notification.java, graylog2-server/src/main/resources/org/graylog2/freemarker/templates/HTML/event_limit_reached.ftl, graylog2-server/src/main/resources/org/graylog2/freemarker/templates/PLAINTEXT/event_limit_reached.ftl, graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationForm.tsx
Resolves #20785 
Removes the system notification EVENT_LIMIT_REACHED. 
See linked issue for details.
In short: suppressing events that exceed the limit is the desired behavior, hence no notification or logging to alert the user.
=> Remove EVENT_LIMIT_REACHED notification

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ViewsESBackendModule.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/ViewsOSBackendModule.java, graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java, graylog2-server/src/main/java/org/graylog/plugins/views/ViewsModule.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/QueryEngine.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/normalization/DecorateQueryStringsNormalizer.java
always also bind backends in the generic map binder, even for versioned backends
in non-versioned backends, use the map binder directly so the engine can pick the correct backend based on the BackendQuery instance used
for query normalization, ignore non-elasticsearch based queries for now, we will need to address normalizers later to make them type safe (or just live with the instanceof check)
Simplified version of https://github.com/Graylog2/graylog2-server/pull/21073
The minimal version for making this work is in https://github.com/Graylog2/graylog-plugin-enterprise/pull/9343.
/nocl 
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/9343
=> Inject the backend query type map for pluggable backend selection

graylog2-web-interface/src/views/components/contexts/WidgetContext.tsx
This PR makes the `WidgetContext` a singleton, so it can be consumed in plugins.
/nocl
=> Make `WidgetContext` a singleton.

graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config, graylog2-web-interface/src/components/common/EntityDataTable/EntityDataTable.tsx, graylog2-web-interface/src/components/events/Constants.ts, graylog2-web-interface/src/components/events/ExpandedSection.tsx, graylog2-web-interface/src/components/events/events/ColumnRenderers.tsx, graylog2-web-interface/src/components/events/events/EventDefinitionLink.tsx, graylog2-web-interface/src/components/events/events/EventDetailsTable.tsx, graylog2-web-interface/src/components/events/events/GeneralEventDetailsTable.tsx, graylog2-web-interface/src/components/events/events/hooks/useNonDisplayedAttributes.ts, graylog2-web-interface/src/components/events/fetchEvents.ts, graylog2-web-interface/src/views/components/widgets/events/EventsList/DefaultDetails.tsx
This PR prepares existing code and adds some reusable parts to be able to use the entity data table on the security events page. Also, adds a feature flag 
/nocl
=> Add Entity data table to security events

graylog2-web-interface/src/components/common/EntityDataTable/hooks/useTableLayout.ts, graylog2-web-interface/src/components/common/EntityDataTable/types.ts, graylog2-web-interface/src/components/common/PaginatedEntityTable/PaginatedEntityTable.tsx, graylog2-web-interface/src/components/events/ExpandedSection.tsx, graylog2-web-interface/src/components/events/events/hooks/useTableComponents.tsx
This PR is a smaller cleanup PR, which introduces the `DefaultLayout` type which can be used instead of referencing `useTableLayout` parameters when working with the paginated data table.
=> Introducing and reusing `DefaultLayout` type.

pom.xml
This fixes issues with backports where the Maven version in the project parent is newer than in the server.
Require 3.9.6 as a minimum. That's what our stable branches currently use.
/nocl Infrastructure
=> Relax Maven version requirement

pom.xml
This fixes issues with backports where the Maven version in the project parent is newer than in the server.
(cherry picked from commit 1000827bdbc1b85b6dbe9ceb2b34726fafb5a53d)
/nocl Infrastructure
=> Relax Maven version requirement (#21171)

graylog2-web-interface/packages/eslint-config-graylog/index.js
This PR is fixing an issue with #21099: When API types have not been generated, the imports were not properly grouped, due to being excluded automatically. This is fixed by reducing the groups which are excluded from path grouping to `builtin` only (excluding `external`).
=> Fixing import order grouping.

full-backend-tests/src/test/java/org/graylog2/inputs/InputCreationIT.java, graylog2-server/src/main/java/org/graylog2/CommonNodeConfiguration.java, graylog2-server/src/main/java/org/graylog2/Configuration.java, graylog2-server/src/main/java/org/graylog2/GraylogNodeConfiguration.java, graylog2-server/src/main/java/org/graylog2/bindings/GraylogNodeModule.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/GraylogApis.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/inputs/Inputs.java, graylog2-server/src/test/java/org/graylog2/commands/MinimalNodeCommandTest.java
Fixes a regression introduced by https://github.com/Graylog2/graylog2-server/pull/20181 that produced an error when configuring inputs with encrypted configuration values.
This was caused by binding InputConfigurationBeanDeserializerModifier without config explicitly.
The change introduces a configuration parameter `withInputs()` that avoids the static binding for nodes which run inputs.
/nocl
- create AWS cloud trail input manually
- added IT which creates and tries to read the created input to ensure serialization/deserialization without errors
=> Fix input configuration encryption error

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackend.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/OpenSearchBackend.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchJob.java
/nocl
Proper cancellation for multi-query search.
As `SearchJob` is envisioned to be used not only in OS/ES, but possibly also with D.W., the naming has been changed a little bit to reflect that.
`SearchJob` class contains only one `Future` field, used for search execution cancellation.
It worked fine, but probably only because of the fact that we use `keep_queries` approach in both searches and dashboards, effectively limiting searches to a single query...
This field was replaced with query->future map.
When we cancel, we cancel on all futures.
When we check the status, we do it on all futures.
While this change may not be in fact fixing any bug existing right now, it should improve correctness of the approach for possible future use cases.
Manually.
=> Proper cancellation for multi-query search

changelog/unreleased/issue-18563.toml, graylog2-server/src/main/java/org/graylog2/indexer/MongoIndexSetRegistry.java, graylog2-server/src/test/java/org/graylog2/indexer/MongoIndexSetRegistryTest.java
Don't iterate over all IndexSets for a given indexName, instead use `getForIndex(String)` directly to avoid unnecessary calls. Also converted some loops to streaming for further cleanup of the code.
Fixes issue #18563.
There's an new test to simulate having 500 IndexSets and checking if only the one responsible for a given specific index is being called.
=> Improve performance for working with indices

changelog/unreleased/issue-21015.toml, full-backend-tests/src/test/java/org/graylog2/web/resources/WebInterfaceAssetsResourceBase.java, full-backend-tests/src/test/java/org/graylog2/web/resources/WebInterfaceAssetsResourceIT.java, full-backend-tests/src/test/java/org/graylog2/web/resources/WebInterfaceAssetsResourceWithPrefixIT.java, graylog2-server/src/main/java/org/graylog2/web/resources/WebInterfaceAssetsResource.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/MavenProjectDirProviderWithFrontend.java, graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerFactory.java
**Note:** This needs a backport to `6.0`, `6.1`.
This PR is making sure that if a path prefix is configured through the `http_publish_uri` (in contrast to through the `X-Graylog-Server-URL` header), it will be considered when looking up assets.
Fixes #21015.
It has been tested with configuring `http_publish_uri` with and without a path prefix, with a trailing slash and without it and without the directive at all.
=> Handle path prefix when serving web interface assets.

changelog/unreleased/pr-21206.toml, graylog2-server/src/main/java/org/graylog/events/processor/systemnotification/SystemNotificationEventProcessorConfig.java
Prior to this PR, a system event definition shows up in the list of exportable definitions for content packs. This leads to an error later on in content pack export. This PR filters the entities like with other definitions (anomaly etc.)
fixes #21166
solves customer issue
needs backport
Tested manually by trying to create a content pack and look at the list of event definitions.
=> Filter system event definitions from content pack generation

changelog/unreleased/pr-21197.toml, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/OpenSearchClient.java, graylog2-server/src/main/java/org/graylog2/indexer/MapperParsingException.java, graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java
Since this [PR](https://github.com/Graylog2/graylog-plugin-enterprise/pull/9271), we save the mapping in the `archive-metadata.json` file and use this mapping to create an index. The problem is that if a mapping contains field properties that reference a field from the index settings, this leads to an error. We have therefore started to also store the index settings in the `archive-metadata.json` and apply them during index creation. This has been done in this [PR](https://github.com/Graylog2/graylog-plugin-enterprise/pull/9271). Unfortunately, there is still an error case for archives that do not contain any settings. For this scenario, this PR implements a retry with default mappings/settings if such an error occurs.
companion PR:
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#9413
=> add archive restore retry on mapper parsing exception

graylog2-web-interface/src/components/common/EntityFilters/EntityFilters.test.tsx, graylog2-web-interface/src/components/common/EntityFilters/FilterConfiguration/FilterConfiguration.tsx, graylog2-web-interface/src/components/common/EntityFilters/FilterConfiguration/SuggestionsList.tsx, graylog2-web-interface/src/components/common/EntityFilters/FilterConfiguration/SuggestionsListFilter.tsx, graylog2-web-interface/src/components/common/EntityFilters/helpers/AttributeIdentification.ts, graylog2-web-interface/src/stores/PaginationTypes.ts
This PR is introducing the `filter_component` attribute for entities used by the paginated data table. This allows specifying custom components used for rendering a filter for this attribute. Obviously, this only works for attributes which are defined/extended in the frontend, not for backend definitions of attributes, as these cannot reference React components. The main use of this is to specify custom ways for filters in plugins.
/nocl Internal functionality.
=> Allow custom filter components for paginated data table.

changelog/unreleased/pr-21217.toml, graylog2-server/src/main/java/org/graylog2/inputs/InputServiceImpl.java, graylog2-server/src/test/java/org/graylog2/inputs/InputServiceImplTest.java
Remove `return` from for loop when iterating over input configuration values so that multiple `EncryptedValue` fields can be supported
The short-circuiting of this for-loop only allowed for one value in an input configuration to be an encrypted value. Any others would not be transformed and the input would fail to be saved to the DB.
Local dev env
=> Allow multiple encrypted values in Input configurations

changelog/unreleased/pr-21208.toml, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/blocks/BlockSettingsParser.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/IndicesAdapterOS2.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/blocks/BlockSettingsParser.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/blocks/BlockSettingsParserTest.java
Prior to this PR, a call to `getIndicesBlocksStatus()`  would exceed to URL maximum of 4096 bytes if the number of indices would be large. 
Tested manually by setting index.blocks on indices manually in OpenSearch and by reducing the threshold to a small amount that leads to reading all indices instead of only the list.
=> Fix to load indices status in batches so that the URL used to call OpenSearch does not exceed maximum length

changelog/unreleased/pr-21208.toml, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/blocks/BlockSettingsParser.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/IndicesAdapterOS2.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/blocks/BlockSettingsParser.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/blocks/BlockSettingsParserTest.java
Note: This is a backport of #21208 to `6.0`.
Prior to this PR, a call to `getIndicesBlocksStatus()`  would exceed to URL maximum of 4096 bytes if the number of indices would be large. 
Tested manually by setting index.blocks on indices manually in OpenSearch and by reducing the threshold to a small amount that leads to reading all indices instead of only the list.
=> Fix to load indices status in batches so that the URL used to call OpenSearch does not exceed maximum length (`6.0`)

full-backend-tests/src/test/java/org/graylog/datanode/DatanodeOpensearchProxyIT.java
Removes the check for an index which in some cases is not present yet.
This is presumably causing the build failures for https://github.com/Graylog2/graylog2-server/pull/21188
/nocl
=> Fix flaky DataNode proxy test

changelog/unreleased/pr-21286.toml, graylog2-server/src/main/java/org/graylog2/outputs/ElasticSearchOutput.java
Fixes the `org.graylog2.outputs.ElasticSearchOutput.writes` metric (Prometheus metric name: `gl_elasticsearch_output_writes_total`) which was counted twice.
=> Fix 'writes' metric for ElasticSearchOutput

changelog/unreleased/pr-21262.toml, graylog2-server/src/main/java/org/graylog/events/rest/EventsResource.java, graylog2-web-interface/src/components/common/IconButton.tsx, graylog2-web-interface/src/components/events/bulk-replay/BulkEventReplay.tsx, graylog2-web-interface/src/components/events/bulk-replay/EventListItem.tsx, graylog2-web-interface/src/components/events/bulk-replay/ReplaySearch.tsx, graylog2-web-interface/src/components/events/bulk-replay/__tests__/BulkEventReplay.test.tsx, graylog2-web-interface/src/components/events/bulk-replay/__tests__/events.fixtures.ts, graylog2-web-interface/src/components/events/bulk-replay/types.ts, graylog2-web-interface/src/components/events/bulk-replay/useSelectedEvents.ts, graylog2-web-interface/src/components/events/events/BulkActions.test.tsx, graylog2-web-interface/src/components/events/events/BulkActions.tsx, graylog2-web-interface/src/components/events/events/types.ts, graylog2-web-interface/src/components/indices/IndexSetFieldTypeProfiles/CreateProfile.tsx, graylog2-web-interface/src/hooks/useAlertAndEventDefinitionData.test.tsx, graylog2-web-interface/src/hooks/useAlertAndEventDefinitionData.tsx, graylog2-web-interface/src/routing/Routes.ts, graylog2-web-interface/src/routing/useHistory.ts, graylog2-web-interface/src/routing/useLocation.ts, graylog2-web-interface/src/views/bindings.tsx, graylog2-web-interface/src/views/components/Search.tsx, graylog2-web-interface/src/views/components/SynchronizeUrl.tsx, graylog2-web-interface/src/views/components/contexts/DashboardPageContextProvider.tsx, graylog2-web-interface/src/views/components/contexts/SearchPageLayoutContext.tsx, graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.test.tsx, graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.tsx, graylog2-web-interface/src/views/logic/views/Actions.ts, graylog2-web-interface/src/views/pages/BulkEventReplayPage.tsx, graylog2-web-interface/src/views/pages/NewDashboardPage.tsx, graylog2-web-interface/src/views/pages/index.ts
This PR is adding a bulk action that allows replaying searches for multiple alerts/events. This is targeted at analysts wanting to investigate multiple events closely, filtering out non-relevant events and performing actions on the ones remaining. To support this, this feature is building a stack of events, showing the on the left side of the screen, allowing the user to replay them one by one.
The user can now mark individual events as viewed, jumping to the next one which was not viewed yet. The user can also remove events which have turned out to be irrelevant. This allows the user to keep track of the progress and make sure that no event is missed. At the end, the user can perform further bulk actions on the events remaining in the stack.
=> Adding "Replay Search" bulk action for alerts/events.

pom.xml
Use version 2.2.4 to fix CVE-2024-52046.
We don't use mina-core in Graylog. Our automatic tests use Apache DS which uses mina-core.
/nocl Update of test dependency.
=> Manage mina-core transitive dependency

graylog2-web-interface/src/components/navigation/MainNavbar.test.tsx, graylog2-web-interface/src/components/navigation/MainNavbar.tsx
It is possible to merge navigation dropdowns, by using the same dropdown title. This way navigation dropdowns from core can be extended via plugins.
With this PR we are also considering the perspective when merging the dropdowns. They only get merged, when their assigned perspective matches. 
/nocl
=> Consider assigned perspective when merging navigation dropdowns.

graylog2-server/src/main/java/org/graylog/plugins/views/search/db/SearchesCleanUpJob.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewSummaryService.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/ViewFacade.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/db/SearchesCleanUpJobWithDBServicesTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/DashboardV1FacadeTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/ViewFacadeTest.java
`PaginatedDbService` is deprecated.
/nocl
=> Refactor ViewSummaryService to not extend PaginatedDbService

graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.tsx, graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.ts, graylog2-web-interface/src/views/pages/BulkEventReplayPage.tsx
This PR is making sure that no new history entry is pushed by URL<->parameter synchronization when the resulting URL is identical.
This fixes an issue for the embedded search (e.g. when replaying search) when the "Show Documents" action is used.
/nocl Fixes issue with unreleased feature.
=> Avoid pushing to history in `WidgetFocusProvider` when new query is identical.

graylog2-web-interface/src/views/logic/queries/QueryHelper.test.ts, graylog2-web-interface/src/views/logic/queries/QueryHelper.ts, graylog2-web-interface/src/views/logic/valueactions/AddToQueryHandler.ts, graylog2-web-interface/src/views/logic/valueactions/ExcludeFromQueryHandler.test.ts, graylog2-web-interface/src/views/logic/valueactions/ExcludeFromQueryHandler.ts, graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.ts, graylog2-web-interface/src/views/logic/views/UseCreateViewForEvent.ts
This PR is fixing the queries generated when replaying events for fields which contain the missing value bucket in their grouping fields. It also creates and reuses a common `predicate` helper for creating field/value-based lucene predicates.
/nocl Fixing unreleased code.
=> Fix query creation for missing bucket values.

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/db/mongodb/MongoDbPipelineStreamConnectionsService.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/PipelineConnections.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rulebuilder/db/MongoDBRuleFragmentService.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rulebuilder/db/RuleFragment.java, graylog2-server/src/main/java/org/mongojack/JacksonDBCollection.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/PipelineFacadeTest.java
Removes usages of `JacksonDBCollection`.
Unless I overlooked it, there is hardly any test coverage for the touched classes. I did a smoke test to verify that pipelines are still working as expected, but additional tests by the reviewer would be much appreciated.
/nocl
=> Remove usage of deprecated MongoDB API from pipelines

changelog/unreleased/issue-19975.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/GrokMatch.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/RegexMatch.java
Resolves #19975 
Catch `StackOverflowError` in grok pattern matching. Log the error and add message to failure index, if enabled.
Same applies to regex matching.
Catch `StackOverflowError` and throw an `IllegalStateException` instead.
The message processor catches exceptions but not virtual machine errors. Since `StackOverflowError` is not an `Exception`, it causes processing to fail silently: the message is not processed and no entry is written to the failures index. The only indication is the raw exception in the server log:
> 2025-01-08 14:46:42,668 WARN : org.graylog2.shared.buffers.ProcessBuffer - Unable to process event MessageEvent{raw=null, message=null, messages=null}, sequence 0
> java.lang.StackOverflowError: null
> 
- Create a pipeline with this rule:
> rule "groktest"
> when …
=> Catch stack overflow error in grok and regex pattern matching

graylog2-web-interface/src/views/components/fieldtypes/StreamsField.tsx
This PR contains a simple fix to get rid of the `Each child in a list should have a unique "key" prop.` warning for the `StreamsField` component.
/nocl
=> Fixing key warning for `StreamsField` component.

graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackInstallationPersistenceService.java, graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackPersistenceService.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/ContentPack.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/ContentPackInstallation.java, graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackInstallationPersistenceServiceTest.java, graylog2-server/src/test/java/org/graylog2/migrations/V20230601104500_AddSourcesPageV2Test.java
Removed usage of `JacksonDBCollection` because it's scheduled for removal.
/nocl
=> Remove `JacksonDBCollection` usage from content packs

graylog2-web-interface/src/components/common/EntityFilters/EntityFilters.test.tsx, graylog2-web-interface/src/components/common/EntityFilters/EntityFilters.tsx, graylog2-web-interface/src/components/common/PaginatedEntityTable/PaginatedEntityTable.tsx, graylog2-web-interface/src/logic/telemetry/Constants.ts
This PR adds telemetry for every filter change in entity data table 
```
FILTER_CREATED: 'Entity Data Table Filter Created',
FILTER_DELETED: 'Entity Data Table Filter Deleted',
FILTER_CHANGED: 'Entity Data Table Filter Changed',
```
to find out by which field was done filtration we can use `attribute_id` property 
/nocl
=> Add telemetry to every filter action in entity data table

graylog2-server/src/main/java/org/graylog2/contentpacks/model/ContentPack.java, graylog2-web-interface/src/components/common/router.tsx, graylog2-web-interface/src/components/content-packs/ContentPackInstallEntityList.tsx, graylog2-web-interface/src/components/content-packs/ContentPackInstallView.tsx, graylog2-web-interface/src/components/content-packs/Types.ts, graylog2-web-interface/src/components/content-packs/components/ContentPackListItem.test.tsx, graylog2-web-interface/src/components/content-packs/hooks/useContentPackInstallations.ts, graylog2-web-interface/src/components/content-packs/hooks/useContentPackRevisions.ts, graylog2-web-interface/src/components/content-packs/hooks/useContentPacks.ts, graylog2-web-interface/src/pages/ContentPacksPage.tsx, graylog2-web-interface/src/pages/ShowContentPackPage.tsx
This PR is fixing an issue with loading/refreshing content pack revisions/installations on the content pack details page by replacing the use of the Reflux store with `useQuery`.
Fixes #21122.
/nocl Fixes bug in unreleased change.
=> Replacing use of store with `useQuery` for content packs.

changelog/unreleased/issue-19058.toml, graylog2-web-interface/src/views/components/messagelist/MessageTableEntry.tsx
**Note:** This is a backport of #21389 to `6.0`.
This PR is fixing message highlighting by id in the message table, e.g. when using the "Show surrounding messages" functionality.
Previously, the css function was used inline, which generated invalid css for the left border color.
Fixes #19058.
=> Fixing highlighting of message in message table by id. (`6.0`)

changelog/unreleased/issue-21185.toml, graylog2-web-interface/src/util/NumberFormatting.test.ts, graylog2-web-interface/src/util/NumberFormatting.ts, graylog2-web-interface/src/views/components/fieldtypes/PercentageField.test.tsx, graylog2-web-interface/src/views/components/fieldtypes/PercentageField.tsx, graylog2-web-interface/src/views/components/messagelist/FormatNumber.ts
**Note:** This needs a backport to `6.0` & `6.1`.
This PR is fixing an issue where very small values are displayed as `NaN%` in aggregation widgets. This is related to a bug in the underlying library used for formatting numbers. Due to this library being abandoned, this PR is starting to implement an abstraction layer that utilizes the Intl API to format numbers.
Replacing all previous usages of `numeral` with it is too much for a bugfix PR that is supposed to be backported, but will be handled through follow-up PRs instead.
Fixes #21185.
=> Fix display of very small percentage values.

changelog/unreleased/issue-19058.toml, graylog2-web-interface/src/views/components/messagelist/MessageTableEntry.tsx
**Note:** This is a backport of #21389 to `6.1`.
This PR is fixing message highlighting by id in the message table, e.g. when using the "Show surrounding messages" functionality.
Previously, the css function was used inline, which generated invalid css for the left border color.
Fixes #19058.
=> Fixing highlighting of message in message table by id. (`6.1`)

changelog/unreleased/issue-21185.toml, graylog2-web-interface/src/util/NumberFormatting.test.ts, graylog2-web-interface/src/util/NumberFormatting.ts, graylog2-web-interface/src/views/components/fieldtypes/PercentageField.test.tsx, graylog2-web-interface/src/views/components/messagelist/FormatNumber.ts
**Note:** This is a backport of #21368 to `6.1`.
This PR is fixing an issue where very small values are displayed as NaN% in aggregation widgets. This is related to a bug in the underlying library used for formatting numbers. Due to this library being abandoned, this PR is starting to implement an abstraction layer that utilizes the Intl API to format numbers.
Replacing all previous usages of numeral with it is too much for a bugfix PR that is supposed to be backported, but will be handled through follow-up PRs instead.
Fixes #21185.
=> Fix display of very small percentage values. (`6.1`)

changelog/unreleased/issue-21185.toml, graylog2-web-interface/src/util/NumberFormatting.test.ts, graylog2-web-interface/src/util/NumberFormatting.ts, graylog2-web-interface/src/views/components/fieldtypes/PercentageField.test.tsx, graylog2-web-interface/src/views/components/messagelist/FormatNumber.ts
**Note:** This is a backport of #21368 to `6.0`.
This PR is fixing an issue where very small values are displayed as NaN% in aggregation widgets. This is related to a bug in the underlying library used for formatting numbers. Due to this library being abandoned, this PR is starting to implement an abstraction layer that utilizes the Intl API to format numbers.
Replacing all previous usages of numeral with it is too much for a bugfix PR that is supposed to be backported, but will be handled through follow-up PRs instead.
Fixes #21185.
=> Fix display of very small percentage values. (`6.0`)

changelog/unreleased/issue-21398.toml, graylog2-web-interface/src/views/components/aggregationwizard/units/FieldUnitPopover.tsx
This PR set unit settings to undefined on clear unit type. In this case instead of empty object we send undefined to BE and that fix an issue 
fix: #21398
=> Set unit settings to undefined on clear unit type

changelog/unreleased/issue-21398.toml, graylog2-web-interface/src/views/components/aggregationwizard/units/FieldUnitPopover.tsx
Note: This is a backport of #21399 to `6.1`
This PR set unit settings to undefined on clear unit type. In this case instead of empty object we send undefined to BE and that fix an issue 
fix: #21398
=> Set unit settings to undefined on clear unit type 6.1

graylog2-web-interface/src/views/components/searchbar/queryvalidation/QueryValidation.tsx
This PR adds `onChange` callback to the `QueryValidation` popover. That will help maintain to close it on outside click
fix: #20468 
/nocl
=> Close QueryValidation popover on outside click

graylog2-web-interface/packages/babel-preset-graylog/package.json, graylog2-web-interface/packages/eslint-config-graylog/package.json, graylog2-web-interface/packages/eslint-plugin-graylog/package.json, graylog2-web-interface/packages/graylog-web-plugin/package.json, graylog2-web-interface/packages/jest-preset-graylog/package.json, graylog2-web-interface/packages/stylelint-config-graylog/package.json
This PR is pinning `yarn` as package manager for the integrated packages, so dependabot does not fall back to `npm@6`, which has been [deprecated](https://github.blog/changelog/2025-01-20-dependabot-will-no-longer-support-npm-v6/#:~:text=As%20of%20January%2020th%2C%202025,a%20supported%20release%20of%20NPM.)
=> Pinning yarn as package manager for integrated packages.

changelog/unreleased/issue-21145.toml, graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config, graylog2-web-interface/src/views/components/widgets/WidgetHeader.tsx
fix: #21145 
we might need backports to 6.1
=> Fix when widget title input in widget edit mode looses cursor position on change

graylog2-server/src/main/java/org/graylog2/outputs/IndexSetAwareMessageOutputBuffer.java
Moves output batch size calculation out of a `synchronized` block.
Output batch size calculation happens in a hot code path where we should limit code execution within synchronized blocks.
It's probably a micro-optimization because the limiting operation will be batch flushing, but nevertheless, it's good practice.
/nocl
=> Move output batch size calculation out of synchronized block

graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.test.tsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDetailsForm.tsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldsForm.tsx, graylog2-web-interface/src/components/event-definitions/event-definitions-types.ts, graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionActions.tsx, graylog2-web-interface/src/components/event-definitions/event-definitions/StatusCell.tsx, graylog2-web-interface/src/components/events/ReplaySearch.tsx, graylog2-web-interface/src/pages/ViewEventDefinitionPage.tsx, graylog2-web-interface/src/views/pages/EventDefinitionReplaySearchPage.test.tsx
With this PR, bulk replaying system events will not lead to an error, due to not being able to reconstruct a proper search for it. Instead, a message will be shown that system events cannot be replayed.
/nocl Bug-fix for unreleased feature.
=> Prevent bulk replaying system events.

changelog/unreleased/pr-21454.toml, graylog2-server/src/main/java/org/graylog2/periodical/Periodicals.java, graylog2-server/src/main/java/org/graylog2/shared/bindings/SchedulerBindings.java, graylog2-server/src/main/resources/prometheus-exporter.yml
Instruments the shared "scheduler" and "daemonScheduler" thread pools to gather metrics.
This was a TODO in the code that I stumbled upon. There is no immediate need for this, but it might help to gain some insight into the runtime behaviour.
=> Gather metrics from shared scheduler thread pools

graylog2-web-interface/src/components/common/EntityFilters/hooks/useUrlQueryFilters.test.tsx, graylog2-web-interface/src/components/common/EntityFilters/hooks/useUrlQueryFilters.ts, graylog2-web-interface/src/components/common/PaginatedEntityTable/PaginatedEntityTable.tsx, graylog2-web-interface/src/components/datanode/migrations/RemoteReindexingMigration.test.tsx, graylog2-web-interface/src/components/datanode/migrations/remoteReindexing/RemoteReindexRunning.tsx, graylog2-web-interface/src/components/indices/IndexSetFieldTypes/IndexSetFieldTypesList.test.tsx, graylog2-web-interface/src/pages/IndexSetFieldTypesPage.test.tsx, graylog2-web-interface/src/routing/QueryParams.ts, graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardsOverview.test.tsx
This PR implements a simple abstraction for the usage of the `use-query-params` package.
The abstraction will make it easier to, for example, replace `use-query-params` with a different solution.
/nocl
=> Implement abstraction for `use-query-params` usage.

graylog2-web-interface/src/views/components/widgets/WidgetHorizontalStretch.tsx
This is a small follow-up for https://github.com/Graylog2/graylog2-server/pull/21482.
Before:
After:
/nocl
=> Improve position of widget stretch icon

changelog/unreleased/issue-20423.toml, graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config, graylog2-web-interface/src/components/hotkeys/HotkeyCollectionSection.tsx, graylog2-web-interface/src/contexts/HotkeysProvider.tsx, graylog2-web-interface/src/util/OSUtils.ts, graylog2-web-interface/src/views/components/searchbar/queryinput/QueryInput.tsx
This PR improves hotkeys for search query input. 
Now for win/linux we are using` ctrl+space` to show suggestions
Also this PR do some improvements: 
- add mapping with mac symbols for ctrl and option keys
- improve isMacOS function
fix: #20423 
we might need backports to 6.1 and 6.0
=> Improving Hotkeys for query input

changelog/unreleased/issue-20465.toml, graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config, graylog2-web-interface/src/views/logic/views/UseCreateSavedSearch.ts, graylog2-web-interface/src/views/pages/StreamSearchPage.test.tsx, graylog2-web-interface/src/views/pages/StreamSearchPage.tsx
Issue #20465 happens because the `useMemo` inside the `useCreateSavedSearch`  hook doesn't have dependencies of `streamId` in the dependencies array. That was done to not recreate the view when on the search page some parameters change (e.g. streams from query params). In the case of the streams search page we have to recreate the view when the stream id from params changes. To solve the issue we can add deps array to `useCreateSavedSearch`  hook  which we pass to `useMemo`
fix: #20465
=> Add dependency array to useCreateSavedSearch hook

changelog/unreleased/pr-21359.toml, graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionSummary.tsx
This PR adds the definition id as a prop to the summary component. That helps to create correct replay link and fix the issue 
fix: https://github.com/Graylog2/graylog-plugin-enterprise/issues/9289
=> Add definition id when render summaryComponent in event definition

changelog/unreleased/issue-21322.toml, graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java, graylog2-server/src/main/java/org/graylog2/users/UserConfiguration.java, graylog2-server/src/test/java/org/graylog2/rest/resources/users/UsersResourceTest.java
Fixes #21403 
Add a new configuration-entry to manage creation of access-tokens for external users.
The configuration's value is considered when a user wants to create a new access token. For internal users, it doesn't make a difference, for external ones, it would forbid creating a token if set to `false`. Otherwise, external users are also allowed to create access tokens.
Starting with graylog 6.2, the configuration is set to not allow external users creating an access token. Before that version, it is allowed, to prevent a breaking change.
There are test-cases covering all three options (internal user, external with setting being `true` and external user with setting being `false`).
=> New configuration to (dis-)allow external users create access tokens

changelog/unreleased/pr-21456.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/KeyValue.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/strings/KeyValueTest.java
Adds a new `use_escape_char` parameter that turns on escape character handling for values in the `key_value` pipeline function.
- Added this feature as an optional parameter to avoid changing any existing usages of the `key_value` function.
- Only works on the outer splitter to allow values to contain escaped delimiter chars - ie, trying to use an escape char in the key doesn't work. Not sure that use case would make sense anyway but open to feedback.
closes Graylog2/graylog-plugin-enterprise#9552
unit test
=> Add escape character handling to key_value pipeline function

changelog/unreleased/issue-20465.toml, graylog2-web-interface/src/views/logic/views/UseCreateSavedSearch.ts, graylog2-web-interface/src/views/pages/StreamSearchPage.test.tsx, graylog2-web-interface/src/views/pages/StreamSearchPage.tsx
NOTE: This PR is backport https://github.com/Graylog2/graylog2-server/pull/21338
Issue #20465 happens because the `useMemo` inside the `useCreateSavedSearch`  hook doesn't have dependencies of `streamId` in the dependencies array. That was done to not recreate the view when on the search page some parameters change (e.g. streams from query params). In the case of the streams search page we have to recreate the view when the stream id from params changes. To solve the issue we can add deps array to `useCreateSavedSearch`  hook  which we pass to `useMemo`
fix: #20465
=> Add dependency array to useCreateSavedSearch hook 6.1

changelog/unreleased/issue-20465.toml, graylog2-web-interface/src/views/logic/views/UseCreateSavedSearch.ts, graylog2-web-interface/src/views/pages/StreamSearchPage.test.tsx, graylog2-web-interface/src/views/pages/StreamSearchPage.tsx
NOTE: This PR is backport https://github.com/Graylog2/graylog2-server/pull/21338
Issue #20465 happens because the `useMemo` inside the `useCreateSavedSearch`  hook doesn't have dependencies of `streamId` in the dependencies array. That was done to not recreate the view when on the search page some parameters change (e.g. streams from query params). In the case of the streams search page we have to recreate the view when the stream id from params changes. To solve the issue we can add deps array to `useCreateSavedSearch`  hook  which we pass to `useMemo`
fix: #20465
=> Add dependency array to useCreateSavedSearch hook 6.0

changelog/unreleased/pr-21538.toml, pom.xml
Release Notes: https://github.com/awslabs/amazon-kinesis-client/releases/tag/v2.6.1
Refs #21451
Needs a backport to at least `6.1`.
=> Bump software.amazon.kinesis:amazon-kinesis-client from 2.6.0 to 2.6.1

graylog2-web-interface/src/components/bootstrap/Menu.tsx
Small fix to improve the text color and size of menu labels to differentiate them from the other menu items.
Before:
After:
/nocl
=> Improve menu label text color and size.

changelog/unreleased/pr-21538.toml, pom.xml
Note: this is a backport of #21538.
Release Notes: https://github.com/awslabs/amazon-kinesis-client/releases/tag/v2.6.1
Refs https://github.com/Graylog2/graylog2-server/issues/21451
=> Bump software.amazon.kinesis:amazon-kinesis-client from 2.6.0 to 2.6.1 (6.1)

changelog/unreleased/pr-21456.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/KeyValue.java, graylog2-server/src/main/resources/log4j2.xml
Register newly added `use_escape_char` parameter in the KeyValue function so it can be used.
=> Register useEscapeCharParam in key_value function descriptor

graylog2-server/src/main/resources/log4j2.xml
https://github.com/Graylog2/graylog-plugin-enterprise/pull/9544 updates the Azure SDK, and some additional internal unneeded SDK log messages (for `MessageFlux`) are now surfacing during successful multi-Graylog node partition load balancing operations. This PR silences those, since we have our own partition change logging. 
When starting up a second Graylog node and a partition is transitioned to that node:
```
2025-02-06 14:17:15,010 INFO : org.graylog.enterprise.integrations.azure.external.AzureLogsProcessor - Input [[Azure Event Hubs/Event Hubs/67a3eecc62e4bb171b9760dd]] is now receiving on partition [0].
2025-02-06 14:17:15,610 WARN : com.azure.core.amqp.implementation.MessageFlux - {"az.sdk.message":"Setting next mediator and waiting for …
```
=> Silence unneeded Azure SDK internal logging

changelog/unreleased/pr-21579.toml, graylog2-server/src/main/java/org/graylog/integrations/inputs/paloalto/PaloAltoTCPInput.java, graylog2-server/src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xInput.java
Mark Palo Alto version 8 and 9 inputs as deprecated.
Closes https://github.com/Graylog2/graylog-plugin-enterprise/issues/9629
Started input and verified `(deprecation)` appears in title. Note that I adjusted the title to avoid it wrapping and to two sets of parentheses.
=> Mark Palo Alto Networks v8 and v9 inputs as deprecated

graylog2-web-interface/src/components/event-definitions/replay-search/LinkToReplaySearch.tsx, graylog2-web-interface/src/components/events/events/hooks/useEventAction.tsx, graylog2-web-interface/src/views/components/widgets/ReplaySearchButton.tsx
This PR turns the simple `a`-element used for the menu item of the "Replay Search" action into a proper `MenuItem`-element with `href`/`onClick` props. This fixes issues with the action only being triggered when the text is clicked, but not when the rest of the hover area is clicked.
Fixes Graylog2/graylog-plugin-enterprise#9646
/nocl Fixes unreleased code.
=> Generate proper menu item for "Replay Search" event action.

graylog2-server/src/main/java/org/graylog/events/search/EventsSearchService.java
This PR is making sure that a priority filter for `critical` is parsed properly.
Fixes #21545.
/nocl Fixing unreleased code.
=> Properly parsing `critical` priority in filter.

changelog/unreleased/issue-21565.toml, graylog2-server/src/main/java/org/graylog2/search/SearchQueryParser.java, graylog2-server/src/test/java/org/graylog2/search/SearchQueryParserTest.java
Add support for quoted default search terms (those that don't specifically indicate a field name) when performing entity searches on various pages throughout the application where the MongoDB `SearchQueryParser` is used. The underlaying problem is explained in detail in the source issue https://github.com/Graylog2/graylog2-server/issues/21565. 
TLDR: When multi-word entity search terms are provided in quotes (e.g. `"My Event Definition"`), they will no longer be split into separate search terms by word. This prevents an excessive number of results from being returned, which can be confusing (and not what I think folks will expect). The words are still split into separate terms when no quotes are supplied. 
This also adds consistency with how field-specific terms work and respect quotes. …
=> Add support for quoted (default) MongoDB search term values in SearchQueryParser

graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/BackendWizard.tsx, graylog2-web-interface/src/components/common/Section.tsx, graylog2-web-interface/src/components/common/ace/theme-graylog.js, graylog2-web-interface/src/components/datanode/DataNodeList/DataNodeLogsDialog.tsx, graylog2-web-interface/src/components/grok-patterns/GrokPatterns.tsx, graylog2-web-interface/src/components/indices/IndicesMaintenanceDropdown.tsx, graylog2-web-interface/src/components/inputs/InputThroughput.tsx, graylog2-web-interface/src/components/nodes/NodesActions.tsx, graylog2-web-interface/src/components/permissions/EntityShareModal.tsx, graylog2-web-interface/src/components/security/SecurityPageEntry.tsx, graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.tsx, graylog2-web-interface/src/components/simulator/SimulationTrace.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/BulkActions/BulkActions.tsx, graylog2-web-interface/src/generator/emit.ts, graylog2-web-interface/src/preflight/components/ResumeStartupButton.tsx, graylog2-web-interface/src/util/NumberFormatting.test.ts, graylog2-web-interface/src/util/deprecationNotice.js, graylog2-web-interface/src/views/components/AdaptableQueryTabsConfiguration.tsx, graylog2-web-interface/src/views/components/HeaderElements.tsx, graylog2-web-interface/src/views/components/QueryBarElements.tsx, graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardActions.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TabKeywordTimeRange.test.tsx, graylog2-web-interface/src/views/components/visualizations/__tests__/GenericPlot.test.tsx, graylog2-web-interface/src/views/components/visualizations/number/Trend.tsx, graylog2-web-interface/src/views/components/visualizations/worldmap/MapVisualization.tsx, graylog2-web-interface/src/views/components/widgets/WidgetActionsMenu.tsx, graylog2-web-interface/src/views/components/widgets/useWidgetExportActionComponent.ts, graylog2-web-interface/src/views/logic/NormalizeSearchURLQueryParams.ts, graylog2-web-interface/src/views/logic/views/UseCreateViewForEvent.ts, graylog2-web-interface/src/views/logic/views/ViewStateGenerator.ts
In #21515, `prettier` was doing the initial reformatting of our code, leading to misplaced `eslint-disable` statements. Due to these being not effective at their new positions, the next automated linter fixing job (#21631) would remove them.
Therefore, this PR is placing these statements at their correct positions again, avoiding automated removal.
=> Placing eslint disable statements back at right positions.

changelog/unreleased/pr-21349.toml, graylog2-server/src/main/java/org/graylog/events/contentpack/entities/AggregationEventProcessorConfigEntity.java, graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessorConfig.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/Parameter.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupTableFacade.java
Prior to this PR, when exporting an event definition into a content pack, parameter definitions were missing from the content pack and so could not be restored on import. This PR fixes the bug.
fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/9274
This change also selects a dependent Lookup Table + Cache & Adapter 
/jpd https://github.com/Graylog2/graylog-plugin-enterprise/pull/9606
=> Fix missing Query Parameters in Event Definitions in Content Packs

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/db/PipelineService.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/db/memory/InMemoryPipelineService.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/db/mongodb/MongoDbPipelineService.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/PipelineResource.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/PipelineUtils.java, graylog2-server/src/main/java/org/graylog2/inputs/InputRoutingService.java
/nocl 
/prd Graylog2/graylog-plugin-enterprise#9735
Mutability checking for pipelines was too strict - we still need to be able to update the default pipeline when we add system-generated routing rules.
=> Bypass pipeline mutability check for default pipeline

changelog/unreleased/pr-21062.toml, data-node/src/main/java/org/graylog/datanode/configuration/variants/OpensearchSecurityConfiguration.java, data-node/src/test/java/org/graylog/datanode/configuration/TruststoreCreatorTest.java, graylog2-server/src/main/java/org/graylog/security/certutil/csr/InMemoryKeystoreInformation.java, graylog2-server/src/main/java/org/graylog/security/certutil/csr/KeystoreInformation.java, graylog2-server/src/main/java/org/graylog2/security/TruststoreCreator.java, graylog2-server/src/main/java/org/graylog2/security/TruststoreUtils.java, graylog2-server/src/test/java/org/graylog2/security/TruststoreCreatorTest.java
Backport of https://github.com/Graylog2/graylog2-server/pull/21062
=> Backport: better handling of intermediate CAs in datanode truststore

graylog2-server/src/main/java/org/graylog2/plugin/Message.java
/nocl fix to unreleased feature
Apply ES/OS formatter to `DateTime` value 
The default format of a Joda `DateTime` value is `uuuu-MM-ddTHH:mm:ss.SSSZ`
OS/ES expects `uuuu-MM-dd HH:mm:ss.SSS`
Apply `ES_DATE_FORMAT_FORMATTER` when assigning `DateTime` to a `Date` message field.
This was missing in timestamp normalization PR #21429 
Note: The problem may not manifest in testing until the indexset is rotated.
=> Apply OS formatter to new date field

graylog2-web-interface/src/views/components/searchbar/queryinput/QueryInput.tsx
The noop handler defined for `react-ace` in the `QueryInput` component was clashing with the newly defined `Ctrl-Space` hotkey on linux in #21336. This PR is removing it to unblock `Ctrl-Space` for the auto-completion on Linux.
/nocl Fixes unreleased change.
=> Removing `Ctrl-Space` from noop handler in query input.

graylog2-server/src/main/java/org/graylog2/plugin/Message.java, graylog2-server/src/test/java/org/graylog2/plugin/MessageTest.java
/nocl internal
Introduce a utility method for adding message fields of type `DateTime`.
It's easy to forget to format the `DateTime` value for OS/ES, since the existing `addField` method happily accepts the `DateTime`; and depending on how dynamic indexing is configured, it may not even show up in testing.
Functionally equivalent change.
=> Refactor timestamp formatting for maintainability

graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterForm.tsx, graylog2-web-interface/src/util/MessagesExportUtils.ts, graylog2-web-interface/src/views/components/WidgetQueryOverride.tsx, graylog2-web-interface/src/views/components/contexts/DrilldownContext.tsx, graylog2-web-interface/src/views/components/contexts/DrilldownContextProvider.test.tsx, graylog2-web-interface/src/views/components/export/ExportModal.test.tsx, graylog2-web-interface/src/views/components/searchbar/queryvalidation/validateQuery.ts, graylog2-web-interface/src/views/components/widgets/ReplaySearchButton.test.tsx, graylog2-web-interface/src/views/logic/NormalizeSearchURLQueryParams.ts, graylog2-web-interface/src/views/logic/aggregationbuilder/AggregationWidget.ts, graylog2-web-interface/src/views/logic/queries/Query.ts, graylog2-web-interface/src/views/logic/queries/QueryGenerator.ts, graylog2-web-interface/src/views/logic/queries/SearchType.ts, graylog2-web-interface/src/views/logic/queries/types.ts, graylog2-web-interface/src/views/logic/search/GlobalOverride.ts, graylog2-web-interface/src/views/logic/search/SearchLink.ts, graylog2-web-interface/src/views/logic/views/UseCreateSavedSearch.ts, graylog2-web-interface/src/views/logic/views/UseCreateViewForEvent.ts, graylog2-web-interface/src/views/logic/views/ViewGenerator.ts, graylog2-web-interface/src/views/logic/widgets/MessagesWidget.ts, graylog2-web-interface/src/views/logic/widgets/Widget.ts, graylog2-web-interface/src/views/logic/widgets/events/EventsWidget.ts
With this PR we are making it possible to extend the `QueryString` type.
The type is being used for the `query` attribute of the `Query` class.
Here is an example how to extend it:
```
declare module 'views/logic/queries/types' {
interface PluggableQueryString {
custom_type?: {
'type': 'custom_type';
'query_string': string;
};
}
}
```
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/9755
/nocl
=> Improve extendability of `QueryString` type.

graylog2-server/src/main/java/org/graylog/plugins/views/search/jobs/SearchJobStateService.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/jobs/SearchJobStateServiceTest.java
SearchJobStateService extended to allow reset of latest search job.
/nocl (new/unreleased functionality)
FE needs a way to reset latest search jobs
With new unit test and manually.
=> SearchJobStateService extended to allow reset of latest search job

changelog/unreleased/pr-21764.toml, graylog2-server/src/main/java/org/graylog2/inputs/transports/AmqpTransport.java
Log the root cause of an IOException in the AMQP Transport, if possible.
The root cause can provide essential information to troubleshoot an AMQP problem, e.g., if incompatible queue settings are being used (in which case the [new passive queue declaration option](https://github.com/Graylog2/graylog2-server/pull/20270) could be the solution).
Manually started an AMQP input against a local RabbitMQ, using various settings to provoke channel errors.
Example output:
```
Error while opening new AMQP connection: (channel error; protocol method: #method<channel.close> (reply-code=406, reply-text=PRECONDITION_FAILED - inequivalent arg 'x-max-length' for queue "log-messages' in vhost'/': received none but current is the value '10' of type 'long', class-id=50,
method-id=10))
```
=> AmqpTransport: Log root cause of IOException, if possible

graylog2-web-interface/src/components/common/Skeleton.md, graylog2-web-interface/src/components/common/Skeleton.tsx, graylog2-web-interface/src/components/common/index.tsx
This PR adds a simple skeleton component which can be used as placeholder for loading content.
It is based on https://mantine.dev/core/skeleton.
/nocl
=> Add basic skeleton component which can be used as placeholder for loading content.

graylog2-web-interface/src/views/components/searchbar/SearchButton.tsx
Adding an `onClick` handler to the `SearchButton` allows to prevent the submit event conditionally via `e.preventDefault();`.
/nocl
=> Allow defining `onClick` handler for search bar submit button.

UPGRADING.md, changelog/unreleased/pr-21755.toml, graylog2-server/src/main/java/org/graylog/integrations/aws/resources/AWSResource.java, graylog2-server/src/main/java/org/graylog/integrations/aws/service/AWSService.java, graylog2-server/src/test/java/org/graylog/integrations/aws/service/AWSServiceTest.java, graylog2-web-interface/src/integrations/aws/cloudwatch/SidebarPermissions.tsx, graylog2-web-interface/src/integrations/aws/common/Routes.ts
Remove inline permissions that were displayed on the right of the setup wizard for the AWS Kinesis/Cloudwatch input. The permissions were not fully correct (contained some extraneous permissions). This PR removes them and instead refers the user to the official Graylog docs (the preferred location for maintaining needed permissions and setup details). Additional permissions information will be added to the corresponding docs page in the 6.2 timeframe.
https://go2docs.graylog.org/current/getting_in_log_data/aws_kinesis_cloudwatch_input.html
Go to the first page of the AWS Kinesis/Cloudwatch input setup and verify that the new 
Previously, the permissions were explicitly listed as shown below. These were replaced with the above panel.
=> AWS Kinesis/Cloudwatch input: Refer to official docs site for needed permissions

graylog2-server/src/main/java/org/graylog/security/authservice/ldap/UnboundLDAPConnector.java
Add the ability for the `UnboundLDAPConnector` to paginate responses (new method accepting page size). We have found that some LDAP/AD providers may have a max response value sent and fail to respond if more than that number of entities (e.g. users) are found. 
See https://github.com/Graylog2/graylog-plugin-enterprise/pull/9845 for motivation and context.
/nocl No functionality change in the Graylog server core, just an additional method added to Java API.
=> Add support for paginating LDAP and AD search responses

graylog2-web-interface/src/components/permissions/EntityShareModal.test.tsx, graylog2-web-interface/src/components/roles/RolesOverview/ActionsCell.test.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/BulkActions/BulkActions.test.tsx, graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.test.tsx, graylog2-web-interface/src/preflight/App.test.tsx, graylog2-web-interface/src/preflight/components/Setup/DataNodesOverview.test.tsx, graylog2-web-interface/src/preflight/components/WaitingForStartup.test.tsx, graylog2-web-interface/src/views/components/AdaptableQueryTabsConfiguration.test.tsx, graylog2-web-interface/src/views/components/QueryBar.test.tsx, graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/BulkActions.test.tsx, graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardActions.test.tsx, graylog2-web-interface/src/views/components/searchbar/saved-search/BulkActions.test.tsx, graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchesModal/SavedSearchesModal.test.tsx, graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRule.test.tsx, graylog2-web-interface/src/views/components/widgets/WidgetActionsMenu.test.tsx, graylog2-web-interface/test/helpers/mocking/WindowMock.ts, graylog2-web-interface/test/helpers/mocking/useWindowConfirmMock.ts
This PR adds a `useWindowConfirm` helper function to easily and properly mock `window.confirm` in tests.
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/9858
/nocl
=> Implement helper function to mock `window.confirm` in tests.

graylog2-web-interface/src/components/rules/rule-builder/RuleBuilder.tsx, graylog2-web-interface/src/components/streams/StreamDetails/output-filter/FilterRulesFields.tsx, graylog2-web-interface/src/logic/generateObjectId.ts, graylog2-web-interface/src/views/components/DashboardActionsMenu.test.tsx, graylog2-web-interface/src/views/components/messagelist/decorators/AddDecoratorButton.tsx, graylog2-web-interface/src/views/components/searchbar/saved-search/SearchActionsMenu.test.tsx, graylog2-web-interface/src/views/logic/search/Search.ts, graylog2-web-interface/src/views/logic/views/CopyPageToDashboard.test.ts, graylog2-web-interface/src/views/logic/views/CopyWidgetToDashboard.test.ts, graylog2-web-interface/src/views/logic/views/MoveWidgetToTab.test.ts, graylog2-web-interface/src/views/logic/views/UpdateSearchForWidgets.test.ts, graylog2-web-interface/src/views/logic/views/UseCreateViewForEvent.test.ts, graylog2-web-interface/src/views/logic/views/UseCreateViewForEventDefinitions.test.ts, graylog2-web-interface/src/views/logic/views/View.ts
This PR creates the utility function `generateObjectId` to generate BSON ObjectIDs.
We can use the abstraction in the frontend instead of interacting with the library directly.
This approach is similar to the utility function `generateId`, which generates a `uuid`.
The abstraction makes it easier to mock the id generation in tests and it would make it easier to switch to a different library in the future.
When I tried to mock `bson-objectid` in tests for a plugin I got the following error `Cannot find module 'bson-objectid'`. Using utility function avoids this problem.
/nocl
=> Create a utility function for BSON ObjectID generation.

changelog/unreleased/issue-21833.toml, graylog2-web-interface/src/views/logic/fieldtypes/InferTypeForSeries.ts
This PR makes the `latest` metric preserve the type of the field it uses in the frontend. This fixes e.g. issues with timestamps not being formatted in the current user's timezone.
Fixes #21833
=> Make `latest` metric preserve type in frontend.

changelog/unreleased/pr-21795.toml, graylog2-server/src/main/resources/swagger/swagger-ui.js
In the API browser, response headers are displayed as JSON when a request was executed. If a response header contains HTML characters, it was potentially breaking the page.
We are now applying additional HTML escaping.
=> Escape response headers in API browser

changelog/unreleased/issue-21833.toml, graylog2-web-interface/src/views/logic/fieldtypes/InferTypeForSeries.ts
This PR makes the `latest` metric preserve the type of the field it uses in the frontend. This fixes e.g. issues with timestamps not being formatted in the current user's timezone.
Fixes #21833
=> Make `latest` metric preserve type in frontend. (`6.0`)

changelog/unreleased/issue-21833.toml, graylog2-web-interface/src/views/logic/fieldtypes/InferTypeForSeries.ts
**Note:** This is a backport of #21837 to `6.1`.
This PR makes the `latest` metric preserve the type of the field it uses in the frontend. This fixes e.g. issues with timestamps not being formatted in the current user's timezone.
Fixes #21833
=> Make `latest` metric preserve type in frontend. (`6.1`)

changelog/unreleased/issue-20571.toml, graylog2-server/src/main/java/org/graylog/plugins/threatintel/whois/ip/WhoisIpLookup.java, graylog2-server/src/main/java/org/graylog/plugins/threatintel/whois/ip/WhoisLookupException.java
Fix https://github.com/Graylog2/graylog2-server/issues/20571.
Fix over-reporting of error which occur during redirect chains. Previously, the `ERROR` log statement would be logged once for the erroring call, then it would be rethrown as the recursive call unwinded for every call below in the stack, resulting in extraneous error log statements. Now, the error logging is only being done once at the top-level for first erroring call.
For example:
> WhoisIpLookup - Could not lookup WHOIS information for [<IP>] at [LACNIC].
Also includes the proper lookup error in the look table response as well. 
```
{
"single_value": "Lookup Error: Could not lookup WHOIS information for [<IP>] at [LACNIC].",
"multi_value": {
"value": "Lookup Error: Could not lookup WHOIS information for [<IP>] at [LACNIC]." …
```
=> Fix overreporting of WhoIs redirect errors

graylog2-server/src/main/java/org/graylog2/database/PersistedServiceImpl.java, graylog2-server/src/main/java/org/graylog2/plugin/database/PersistedService.java
Deprecating `PersistedServiceImpl` to encourage developers to move away from it.
I decided against deprecating `PersistedService` itself because that would generate deprecation warnings for callers.
/nocl
=> Deprecate PersistedServiceImpl

changelog/unreleased/pr-21349.toml, graylog2-server/src/main/java/org/graylog/events/contentpack/entities/AggregationEventProcessorConfigEntity.java, graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessorConfig.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/Parameter.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupTableFacade.java
**backport of https://github.com/Graylog2/graylog2-server/pull/21349**
Prior to this PR, when exporting an event definition into a content pack, parameter definitions were missing from the content pack and so could not be restored on import. This PR fixes the bug.
fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/9274
This change also selects a dependent Lookup Table + Cache & Adapter 
/jpd https://github.com/Graylog2/graylog-plugin-enterprise/pull/9877
=> Fix missing Query Parameters in Event Definitions in Content Packs (6.0)

changelog/unreleased/pr-21349.toml, graylog2-server/src/main/java/org/graylog/events/contentpack/entities/AggregationEventProcessorConfigEntity.java, graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessorConfig.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/Parameter.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupTableFacade.java
**backport of https://github.com/Graylog2/graylog2-server/pull/21349**
Prior to this PR, when exporting an event definition into a content pack, parameter definitions were missing from the content pack and so could not be restored on import. This PR fixes the bug.
fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/9274
This change also selects a dependent Lookup Table + Cache & Adapter 
/jpd https://github.com/Graylog2/graylog-plugin-enterprise/pull/9743
=> Fix missing Query Parameters in Event Definitions in Content Packs (6.1)

changelog/unreleased/issue-20833.toml, graylog2-web-interface/src/views/components/visualizations/GenericPlot.tsx
This PR is hiding the notifier that is shown when zooming in on a graph.
Fixes #20833.
=> Hide plotly notifier when zooming.

changelog/unreleased/issue-20833.toml, graylog2-web-interface/src/views/components/visualizations/GenericPlot.tsx
**Note:** This is a backport of #21850 to `6.1`.
This PR is hiding the notifier that is shown when zooming in on a graph.
Fixes #20833.
=> Hide plotly notifier when zooming. (`6.1`)

changelog/unreleased/issue-21653.toml, graylog2-server/src/main/java/org/graylog2/rest/resources/messages/MessageResource.java, graylog2-web-interface/src/logic/errors/FetchError.ts, graylog2-web-interface/src/pages/ShowMessagePage.fixtures.ts, graylog2-web-interface/src/pages/ShowMessagePage.test.tsx, graylog2-web-interface/src/pages/ShowMessagePage.tsx, graylog2-web-interface/src/views/hooks/useMessage.ts
**Note:** This is a backport of #21663 to `6.1`.
Prior to this PR, the message permalink page was just showing a spinner when the referenced index was missing. This PR is fixing this by catching 404s and show a helpful message explaining the most probable cause.
Fixes #21653.
Before:
After:
=> Handle missing index/message on permalink page properly. (`6.1`)

graylog2-web-interface/src/components/navigation/DefaultEnterpriseNavItem.ts, graylog2-web-interface/src/components/navigation/MainNavbar.tsx, graylog2-web-interface/src/components/navigation/bindings.ts, graylog2-web-interface/src/components/security/bindings.ts, graylog2-web-interface/src/routing/Routes.ts
Currently the order of navigation items in the DOM is based on the order items get registered in the plugin store.
With this PR we are making use of the functionality added with https://github.com/Graylog2/graylog2-server/pull/21827 to define specific positions for the enterprise and security nav item.
/nocl
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/9887
=> Define position in navigation for enterprise and security nav item.

graylog2-web-interface/src/views/components/visualizations/XYPlot.tsx, graylog2-web-interface/src/views/components/visualizations/__tests__/XYPlot.test.tsx
This PR allows passing an `onClickMarker` prop to the `XYPlot` component which is passed through to `GenericPlot`, enabling a consumer of the component to define a callback that is called when an element in the chart is clicked.
/nocl Internal Refactoring.
=> Allow specifying `onClickMarker` for `XYPlot`.

graylog2-web-interface/src/components/common/EntityFilters/hooks/useFiltersWithTitle.ts
This is a small improvement for working with paginated entity data table, so that when an attribute filter is set, but when retrieving titles, the attribute id is not in the list of registered attributes, an error will be thrown. 
Previously, it was handled gracefully at this point, but threw a seemingly unrelated exception later. This is very confusing when the underlying error is e.g. a misspelling of the attribute name. Throwing an explicit error here makes debugging much easier.
/nocl Internal addition.
=> Throw error if attribute is not registered when fetching titles.

.github/workflows/fix-linter-hints.yml
This PR is adjusting the fix-linter-hints job to avoid using `-Dpedantic`. This avoids running into a recent issue with broken dependency resolution of the data node module.
=> Restoring fix linter hints job by disabling pedantic.

UPGRADING.md
Upgrade notes for changes to the Enterprise plugin in https://github.com/Graylog2/graylog-plugin-enterprise/pull/9808.
/nocl
=> Add upgrade notes for files API removal

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/MoreSearchAdapterOS2.java, graylog2-server/src/main/java/org/graylog/events/rest/EventsResource.java, graylog2-server/src/main/java/org/graylog/events/search/EventsHistogramResult.java, graylog2-server/src/main/java/org/graylog/events/search/EventsSearchService.java, graylog2-server/src/main/java/org/graylog/events/search/MoreSearch.java, graylog2-server/src/main/java/org/graylog/events/search/MoreSearchAdapter.java
This PR is implementing a backpoint (`/events/histogram`), which is expecting the same parameters as the paginated search endpoint for events, returning a histogram for the occurence of events & alerts over time. It returns a maximum of 30 buckets for the given time range, picking appropriate time units for bucket intervals, trying to align them with calendrical units.
/nocl Part of a unreleased feature.
=> Implementing endpoint for retrieving alerts/events histogram.

graylog2-web-interface/src/components/bootstrap/NavDropdown.tsx
This small fix unifies the line-height of links and dropdown buttons in the main navbar. Before this change the dropdown buttons had a slightly different line-height.
Before:
After:
/nocl
=> Fix line-height of dropdown buttons in main navbar.

changelog/unreleased/pr-21927.toml, graylog2-web-interface/src/components/configurationforms/ConfigurationWell.tsx
Fix the display of encrypted input values that also have the IS_PASSWORD attribute. We now first check if a field is an encrypted value before checking the IS_PASSWORD status.
This fixes an issue where an empty encrypted input value was shown as `****` instead of `<empty>` on the inputs page.
Also, add a space between the input label and the masked value for password fields.
Set and unset values look the same.
Unset value:
Set value:
=> Fix display of encrypted configuration values for inputs

graylog2-web-interface/src/components/common/PaginatedEntityTable/PaginatedEntityTable.tsx, graylog2-web-interface/src/components/common/PaginatedEntityTable/TableFetchContext.ts, graylog2-web-interface/src/components/common/PaginatedEntityTable/TableFetchContextProvider.tsx, graylog2-web-interface/src/pages/ClusterConfigurationPage.tsx, graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardActions.test.tsx
This PR is extending the `TableFetchContext` and its providers with the entity table id. This makes it easier to e.g. consume table preferences in child components of the paginated data table.
/prd Graylog2/graylog-plugin-enterprise#9939
=> Providing entity table id through table context.

changelog/unreleased/pr-21932.toml, graylog2-server/src/main/java/org/graylog/plugins/views/search/db/SearchJobService.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/db/InMemorySearchJobServiceTest.java
From now on, admin cannot cancel/load other users' jobs via Search API.
/jpd Graylog2/graylog-plugin-enterprise#9937
See https://github.com/Graylog2/graylog-plugin-enterprise/issues/9926
=> From now on, admin cannot cancel/load other users' jobs via Search API

graylog2-server/src/main/java/org/graylog2/rest/resources/entities/preferences/model/EntityListPreferences.java, graylog2-server/src/test/java/org/graylog2/rest/resources/entities/preferences/listeners/EntityListPreferencesCleanerOnUserDeletionTest.java, graylog2-server/src/test/java/org/graylog2/rest/resources/entities/preferences/service/EntityListPreferencesServiceImplTest.java, graylog2-web-interface/src/components/common/EntityDataTable/hooks/__mocks__/useUserLayoutPreferences.ts, graylog2-web-interface/src/components/common/EntityDataTable/hooks/useTableLayout.test.tsx, graylog2-web-interface/src/components/common/EntityDataTable/hooks/useUpdateUserLayoutPreferences.test.tsx, graylog2-web-interface/src/components/common/EntityDataTable/hooks/useUpdateUserLayoutPreferences.ts, graylog2-web-interface/src/components/common/EntityDataTable/hooks/useUserLayoutPreferences.ts, graylog2-web-interface/src/components/common/EntityDataTable/types.ts, graylog2-web-interface/src/components/indices/IndexSetFieldTypeProfiles/ProfilesList.test.tsx, graylog2-web-interface/src/components/indices/IndexSetFieldTypes/IndexSetFieldTypesList.test.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/StreamsOverview.test.tsx, graylog2-web-interface/src/pages/IndexSetFieldTypesPage.test.tsx, graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardsOverview.test.tsx, graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchesModal/SavedSearchesModal.test.tsx, graylog2-web-interface/src/views/logic/fieldactions/ChangeFieldType/ChangeFieldTypeModal.test.tsx
This PR is extending the user entity table prefences to allow frontend components to store arbitrary preferences for specific tables as well.
/nocl Internal extension.
/prd Graylog2/graylog-plugin-enterprise#9942
=> Allowing to pass and store custom entity table preferences.

graylog2-server/src/main/java/org/graylog/plugins/views/search/jobs/SearchJobStateService.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/jobs/SearchJobStatus.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/jobs/SearchJobStateServiceTest.java
Service method for execution state retrieval of active job for a user.
Additionally, unused state has been removed from `SearchJobStatus`.
/nocl
FE will need a new endpoint to provide this small piece of information, instead of fetching everything we know about the job.
Unit tests have been modified accordingly.
=> Service method for execution state retrieval of active job for a user

graylog2-web-interface/src/views/components/widgets/reexecuteSearchTypes.ts, graylog2-web-interface/src/views/logic/slices/executeJobResult.ts, graylog2-web-interface/src/views/logic/slices/searchExecutionSlice.ts, graylog2-web-interface/src/views/logic/slices/viewSlice.ts, graylog2-web-interface/src/views/stores/SearchJobs.ts
We recently extended the search job status endpoint with the option to add a `page` and `per_page` parameter https://github.com/Graylog2/graylog2-server/pull/21797. They can be added to query paginated results of message list search types.
With this PR we make use of these parameters in the frontend.
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/9847
/nocl
=> Allow calling search status endpoint with pagination parameters (FE).

changelog/unreleased/pr-21835.toml, graylog2-server/src/main/java/org/graylog/integrations/inputs/paloalto11/PaloAlto11xCodec.java, graylog2-server/src/main/java/org/graylog/integrations/inputs/paloalto9/PaloAlto9xCodec.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/ScriptingApiModule.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/ScriptingApiResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/ScriptingApiService.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/ScriptingApiServiceImpl.java, graylog2-server/src/main/java/org/graylog2/plugin/inputs/DefinesEventSourceProduct.java, graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config
Prior to this change, all Sigma Rules where shown with the given search parameters.
Now, we additionally filter to only list Sigma Rules that match the configured `event_source_product` field contents
- defined by an input
- defined by a static field on an input
- in messages indexed in the recent past in the indexer
So that in the FE we can only show the Sigma Rules to enable that make sense in context of your system configuration.
=> Threat Coverage Widget: searching for Sigma Rules filters for only potentially matching Rules

graylog2-web-interface/src/components/events/EventsEntityTable.tsx, graylog2-web-interface/src/components/events/EventsMetrics.tsx
This PR is adding a collapse/expand button for the Alerts & Events histogram widget, persisting the state in the current user's table preferences.
/nocl WIP Feature.
=> Make Alerts & Events histogram collapsible.

changelog/unreleased/pr-21959.toml, graylog2-web-interface/src/components/datanode/migrations/common/InPlaceMigrationInfo.tsx, graylog2-web-interface/src/components/datanode/migrations/in-place/StopMessageProcessing.tsx
Adds more information on when/how to change permissions for the OpenSearch data directory in the Data Node migration wizard. 
resolves https://github.com/Graylog2/graylog-plugin-enterprise/issues/9231
=> Add permission change information to data node migration

changelog/unreleased/pr-21943.toml, graylog2-server/src/main/java/org/graylog/security/certutil/CertificateGenerator.java
This extends the key size used in certificate generation to 4096 bits.
Additionally, the generated serial number is now derived from a UUID to better prevent possible collisions and lower predicability.
resolves https://github.com/Graylog2/graylog-plugin-enterprise/issues/9951 
Integration tests
=> Improve certificate generation

data-node/pom.xml
Only include "runtime" scope in copy-dependencies configuration.
This shaves 40 MB from the artifact.
/nocl
=> Don't include test dependencies in Data Node artifact

graylog2-web-interface/src/views/components/TypeSpecificValue.test.tsx, graylog2-web-interface/src/views/components/fieldtypes/FieldTypeValueRenderer.tsx, graylog2-web-interface/src/views/components/fieldtypes/InputField.tsx
This PR is fixing a regression introduced with https://github.com/Graylog2/graylog2-server/pull/21865, which displayed the field name instead of the input name for `gl2_source_input` field values.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/9980
/nocl
=> Fixing field type render for input and nodes field.

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchJobDTO.java
No need to verify existence of search related to search job.
/nocl
FE does not use search ID stored in search job to fetch a search.
Each execution results in the creation of a new search.
Even if the search job is linked to a search that is gone, we should not take any immediate actions, throw exceptions etc.
=> No need to verify existence of search related to search job

graylog2-web-interface/src/components/inputs/InputSetupWizard/steps/SetupRoutingStep.tsx, graylog2-web-interface/src/components/inputs/InputSetupWizard/steps/components/CreateStreamForm.tsx
/nocl
fixes https://github.com/Graylog2/graylog2-server/issues/22020
=> ISW - Fix new stream form values lost when going back

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/MoreSearchAdapterOS2.java, graylog2-server/src/main/java/org/graylog/events/search/MoreSearch.java, graylog2-server/src/main/java/org/graylog/events/search/MoreSearchAdapter.java, graylog2-web-interface/src/components/events/EventsHistogram.tsx
This PR is improving the Alerts & Events histogram in two ways:
- Always set range of graph to selected time range. This prevents a bug, where the removal of a time range filter does not reset the time range in the graph.
- Return empty buckets before and after first/last data present in aggregation
This provides a more consistent handling & presentation of the configured time range for the user.
/nocl Unreleased feature.
Range of Graph is zoomed in to the range where data is available
Range of Graph is still defaulting to six months even, when no early data is available
=> Consistent Time Range handling in Alerts & Events histogram.

graylog2-server/src/main/java/org/graylog2/bindings/GraylogNodeModule.java, graylog2-server/src/main/java/org/graylog2/commands/AbstractNodeCommand.java, graylog2-server/src/main/java/org/graylog2/shared/bindings/ObjectMapperModule.java
The ObjectMapperModule needs the chaining class loader to find classes from plugins.
This broke in the node types refactoring in pull request #20181. (commit b4e1e075f9a18382c55add16ad0bf1265c462fc3)
~Also, remove the unused no-argument constructor in `ObjectMapperModule` to avoid future accidents.~ The no-argument constructor is actually used in tests.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/9768
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/9996
/nocl Fixing unreleased refactoring
=> Add missing class loader to `ObjectMapperModule` creation

graylog2-web-interface/webpack.preflight.ts, graylog2-web-interface/webpack/core.js
s
This PR adds a `disable_tsc` environment variable for `yarn start`, which disables type-checking. This is useful, when `tsc` is used through the IDE or separately (e.g. using `tsc --watch`) and no double type-checking is wanted.
/nocl Relevant for dev only.
=> Allow disabling type checking in dev server to save memory.

graylog2-server/pom.xml, graylog2-server/src/main/java/org/graylog2/jackson/PeriodDurationDeserializer.java, graylog2-server/src/main/java/org/graylog2/jackson/PeriodDurationSerializer.java, graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java, graylog2-server/src/main/java/org/graylog2/security/AccessTokenService.java, graylog2-server/src/main/java/org/graylog2/security/AccessTokenServiceImpl.java, graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/config/ObjectMapperConfiguration.java, graylog2-server/src/main/java/org/graylog2/users/UserConfiguration.java, graylog2-server/src/test/java/org/graylog2/jackson/PeriodDurationDeserializerTest.java, graylog2-server/src/test/java/org/graylog2/jackson/PeriodDurationSerializerTest.java, graylog2-server/src/test/java/org/graylog2/migrations/V20250206105400_TokenManagementConfigurationTest.java, graylog2-server/src/test/java/org/graylog2/migrations/V20250219134200_DefaultTTLForNewTokensTest.java, graylog2-server/src/test/java/org/graylog2/rest/resources/users/UserResourceGenerateTokenAccessTest.java, graylog2-server/src/test/java/org/graylog2/rest/resources/users/UsersResourceTest.java, graylog2-server/src/test/java/org/graylog2/security/AccessTokenServiceImplTest.java, pom.xml
Fixes #22015.
When creating a token with a TTL specifying months or even years, the creation fails.
Before, the TTL was accepted as a `java.time.Duration`, which only handles durations up to days. It isn't made for anything coarser than that. So after checking with @bernd , the TTL is now accepted as `org.threeten.extra.PeriodDuration`, which allows any combination of time-units (year, month, day, hour, minute, second). So with this, the TTL's configuration became more flexible too.
There are unit-tests and I've also checked on my local server both via UI and curl.
/nocl
=> Allow longer TTL when creating a new token.

changelog/unreleased/pr-22095.toml, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/fieldtypes/streams/StreamsForFieldRetrieverES7.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/OpenSearchClient.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/fieldtypes/streams/StreamsForFieldRetrieverOS2.java
This PR is modifying low-level field types retrieval in a way that an individual error of the multi-search request does not result in a `NullPointerException`, but throws a proper exception before when the response is a failure.
=> Safer extraction of search response in field type retrieval.

graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/validation/TimeRangeValidator.java
Query time limit ignored for Data Lake search types.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/10122
/nocl
See https://github.com/Graylog2/graylog-plugin-enterprise/issues/10122
Manually.
=> Query time limit ignored for Data Lake search types

graylog2-server/src/main/java/org/graylog2/inputs/InputRoutingService.java
/nocl 
Resolves #22023
Update regex matching to handle special characters in the names of inputs and streams.
The handler for renamed/deleted inputs choked on input or stream names with special chars. This prevented proper updating of the related pipeline and routing rule.
=> Update regex to handle special chars

changelog/unreleased/pr-22155.toml, graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java
Previously, we retried index creation with the default index settings/mappings only when `MapperParsingException` was thrown. The error described in this issue(Graylog2/graylog-plugin-enterprise#10126) throws another exception so we now do the retry on any exception. The retry currently only takes place for archive restore and data lake retrieval.
closes Graylog2/graylog-plugin-enterprise#10126
=> always retry index creation with default settings/mappings

changelog/unreleased/issue-21896.toml, graylog2-server/src/main/java/org/graylog2/configuration/IndexerDiscoveryProvider.java
During opensearch startup in data nodes, there is a short phase where opensearch is already listening on 9200 port but returning plaintext error, telling it's starting now. If we read this page in VersionProbe, we'll fail to parse it as json and print ugly error message.
To prevent this, IndexerDiscoveryProvider will use only fully initialized datanodes, where opensearch is already fully started and returns valid responses. 
Fixes #21896
:
=> IndexerDiscoveryProvider will provide only AVAILABLE datanodes to prevent hitting starting indexers

graylog2-server/src/main/java/org/graylog2/periodical/ExpiredTokenCleaner.java, graylog2-server/src/main/java/org/graylog2/security/AccessTokenService.java, graylog2-server/src/main/java/org/graylog2/security/AccessTokenServiceImpl.java, graylog2-server/src/test/java/org/graylog2/periodical/ExpiredTokenCleanerTest.java, graylog2-server/src/test/java/org/graylog2/security/AccessTokenServiceImplTest.java, graylog2-server/src/test/resources/org/graylog2/security/findExpiredTokens_severalExpired.json
Also find/return/delete expired tokens for admin (which doesn't have an entry in the users-collection.
Fixes #22087
The `ExpiredTokenCleaner` didn't find tokens for the admin (which doesn't have an entry in the `users`-collection, so the "join" didn't return anything. The cleanup-job not cleaning up properly is not an option, otherwise we would have to rename it.
Finding expired tokens now also returns the entries without corresponding entries in the `users`-collection and adds the user-name on top of the user-id (which is nullable due to this) to the audit-context, so that it is still clean, whose token was deleted.
The existing unit-tests have been adapted accordingly and I've run the job locally several times.
/nocl
=> Improve ExpiredTokenCleaner

changelog/unreleased/pr-22095.toml, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/fieldtypes/streams/StreamsForFieldRetrieverES7.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/OpenSearchClient.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/fieldtypes/streams/StreamsForFieldRetrieverOS2.java
**Note:** This is a backport of #22095 to `6.1`.
This PR is modifying low-level field types retrieval in a way that an individual error of the multi-search request does not result in a `NullPointerException`, but throws a proper exception before when the response is a failure.
=> Safer extraction of search response in field type retrieval. (`6.1`)

changelog/unreleased/pr-22151.toml, graylog2-web-interface/src/pages/DelegatedSearchPage.jsx, graylog2-web-interface/src/views/components/aggregationwizard/AggregationWizard.tsx, graylog2-web-interface/src/views/components/aggregationwizard/grouping/GroupingsConfiguration.tsx, graylog2-web-interface/src/views/components/widgets/telemety.ts
**Note:** This needs a backport to `6.1`.
This PR is implementing a usage of `useMemo` to avoid a reset of the widget config when the component is rerendering before the config change has bubbled upwards to the state.
Fixes Graylog2/graylog-plugin-enterprise#6663
Fixes Graylog2/support#12
=> Memoize initial form values to avoid reset of widget config.

changelog/unreleased/pr-22151.toml, graylog2-web-interface/src/views/components/aggregationwizard/AggregationWizard.tsx
**Note:** This is a backport of #22151 to `6.1`.
This PR is implementing a usage of useMemo to avoid a reset of the widget config when the component is rerendering before the config change has bubbled upwards to the state.
Fixes Graylog2/graylog-plugin-enterprise#6663
Fixes Graylog2/support#12
=> Memoize initial form values to avoid reset of widget config. (`6.1`)

changelog/unreleased/ghsa-76vf-mpmx-777j.toml, graylog2-server/src/main/java/org/graylog2/contentpacks/model/ContentPackV1.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/LegacyContentPack.java, graylog2-web-interface/src/components/common/Markdown.tsx, graylog2-web-interface/src/components/common/MarkdownEditor/BaseEditor.tsx, graylog2-web-interface/src/components/common/MarkdownEditor/EditorModal.tsx
Fixed markdown view sanitation which was dropping all HTML generated from the markdown.
/nocl
/jpd https://github.com/Graylog2/graylog-plugin-enterprise/pull/9963
This PR fixes the sanitation of the markdown value passed to Markdown component and Preview. Also it takes care of fixing failing tests and unused import
=> Fixed markdown view sanitation

changelog/unreleased/ghsa-76vf-mpmx-777j.toml, graylog2-server/src/main/java/org/graylog2/contentpacks/model/ContentPackV1.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/LegacyContentPack.java, graylog2-web-interface/src/components/common/Markdown.tsx, graylog2-web-interface/src/components/common/MarkdownEditor/BaseEditor.tsx
Fixed markdown view sanitation which was dropping all HTML generated from the markdown.
Backports https://github.com/Graylog2/graylog2-server/pull/22211 to `6.1`
/jpd https://github.com/Graylog2/graylog-plugin-enterprise/pull/10193
/nocl
This PR fixes the sanitation of the markdown value passed to Markdown component and Preview. Also it takes care of fixing failing tests and unused import
=> Fixed markdown view sanitation (6.1)

changelog/unreleased/ghsa-76vf-mpmx-777j.toml, graylog2-server/src/main/java/org/graylog2/contentpacks/model/ContentPackV1.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/LegacyContentPack.java, graylog2-web-interface/src/components/common/Markdown.tsx, graylog2-web-interface/src/components/common/MarkdownEditor/BaseEditor.tsx
Fixed markdown view sanitation which was dropping all HTML generated from the markdown.
/nocl
This PR fixes the sanitation of the markdown value passed to Markdown component and Preview. Also it takes care of fixing failing tests and unused import
=> Fixed markdown view sanitation (6.0) 

graylog2-web-interface/src/components/navigation/MainNavbar.tsx
This PR is avoiding a warning logged due to using a custom hook in a `useMemo` clause:
<details>
```
Warning: Do not call Hooks inside useEffect(...), useMemo(...), or other built-in Hooks. You can only call Hooks at the top level of your React function. For more information, see https://reactjs.org/link/rules-of-hooks Error Component Stack
at MainNavbar (MainNavbar.tsx:140:1)
at div (<anonymous>)
at Transition (Transition.js:133:30)
at Collapse (Collapse.js:156:35)
at NavbarCollapse (NavbarCollapse.js:34:29)
at div (<anonymous>)
at Grid (Grid.js:49:29)
at nav (<anonymous>)
at Navbar (Navbar.js:155:30)
at UncontrolledComponent (uncontrollable.js:44:37)
at O (styled-components.browser.esm.js:32:23503)
at Navigation.tsx:43:1
at NavigationContainer (Navigation.tsx:97:1)
at div (<anonymous>) …
```
=> Avoid using hook in `useMemo`.

graylog2-web-interface/src/views/logic/widgets/events/EventsWidget.ts
This is a follow-up for https://github.com/Graylog2/graylog2-server/pull/22161. The comparison of `this._value[key]` and `other[key]` was not working, because  `this._value[key]` is referencing the internal state, while `other[key]` references the public methods and their keys vary.
Related to https://github.com/Graylog2/graylog2-server/issues/22153
/nocl - a change log is included in the original PR and its changes have not been released yet.
=> Do not use internal state for widget comparison in events widget.

graylog2-web-interface/src/components/inputs/InputSetupWizard/InputSetupWizard.SetupRouting.test.tsx, graylog2-web-interface/src/components/inputs/InputSetupWizard/steps/components/CreateStreamForm.tsx, graylog2-web-interface/src/components/inputs/InputSetupWizard/steps/components/SelectedIndexSetAlert.tsx, graylog2-web-interface/src/components/streams/IndexSetSelect.tsx
Part of https://github.com/Graylog2/graylog2-server/issues/22147
/nocl
As there is no easy fix to do this due to the way z-index works, especially with children & parents we decided to restructure the form instead.
With the new form structure it is easier to understand for the user and the button with the tooltip is placed above the select.
There is the edge case that when the height is too small, the tooltip overlay will still overlap with the select as it opens to the top instead.
I agreed with @tellistone that it is okay due to time constraint.
However, we should eventually look at issues like that and how we handle z-index in our code base (especially with the new mantine components).
=> ISW - Restructure create stream form to avoid tooltip overlap

graylog2-web-interface/src/components/configurations/TimeRangePresetForm.tsx, graylog2-web-interface/src/views/components/contexts/TimeRangeInputSettingsContext.ts, graylog2-web-interface/src/views/components/searchbar/time-range-filter/TimeRangeFilter.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/TimeRangeFilterButtons.test.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/TimeRangeFilterButtons.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/TimeRangePresetDropdown.test.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/TimeRangePresetDropdown.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TimeRangePicker.tsx, graylog2-web-interface/src/views/components/searchbar/time-range-filter/time-range-picker/TimeRangePresetRow.tsx
Before this change the query time range limit in the search date time picker was based on the `limitDuration` prop of the `TimeRangeFilter` component.
While the time range limit, which is being used to filter the preset dropdown was provided by the `useSearchConfig` hook.
We started using the time range picker on other pages were we want to ignore the search configuration. To achieve this we are now no longer consuming the `useSearchConfig` hook in the `RangePresetDropdown`, but the `limitDuration` prop from the parent `TimeRangeFilter` component.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/10198
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/10224
/nocl
=> Use time range limit defined in `TimeRangeFilter` props for time range preset dropdown.

graylog2-web-interface/src/components/events/EventsRefreshProvider.tsx, graylog2-web-interface/src/components/events/events/EventsRefreshControls.tsx
This PR is changing the auto-refresh on the Events/Security to start paused, requiring the user to explicitly enable it.
/nocl Changing unreleased feature.
=> Do not enable auto-refresh for events page by default.

changelog/unreleased/issue-22153.toml, graylog2-web-interface/src/views/logic/aggregationbuilder/AggregationWidget.ts, graylog2-web-interface/src/views/logic/widgets/MessagesWidget.ts, graylog2-web-interface/src/views/logic/widgets/Widget.ts, graylog2-web-interface/src/views/logic/widgets/events/EventsWidget.ts, graylog2-web-interface/src/views/stores/isEqualForSearch.ts
**Note:** This is a backport of #22161 & #22226 to `6.1`.
This PR fixes an issue with widgets, where resizing a widget resulted in an unnecessary search execution due to the widget comparison function returning a wrong result. This is related to the introduction of the `streamCategories` attribute, which is referenced incorrectly in the comparison function, due to different casing between the internal state and public methods of the class.
Fixes #22153.
/prd Graylog2/graylog-plugin-enterprise#10268
=> Fix comparison of messages widget to avoid unnecessary refresh. (`6.1`)

graylog2-server/src/main/java/org/graylog2/featureflag/ImmutableFeatureFlags.java
Remove the warning that appears when checking if a feature flag is on in backend code (with `FeatureFlags.isOn()`). 
```
WARN: Feature flag 'my_feature_flag' is not set. Fall back to default value 'false'.
```
Closes https://github.com/Graylog2/graylog-plugin-enterprise/issues/10264
See https://github.com/Graylog2/graylog-plugin-enterprise/issues/10264 for additional motivation.
/nocl logging-level change
=> Remove warning when checking if a feature flag is on

graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java
Fixes halted server startup due to the below exception when the `root_timezone` server property is specified. The issue was introduced in https://github.com/Graylog2/graylog2-server/pull/22224, where a new `JadConfig` instance was constructed without adding the needed converters to support `DateTimeZone` and presumably other joda-related server config properties. 
The fix adds the required converters to the new instance as well.
Big thanks to @kingzacko1 for discovering the issue and helping to root it out.
```
2025-04-04 14:12:35,054 ERROR: org.graylog2.bootstrap.CmdLineTool - Invalid configuration
com.github.joschi.jadconfig.ParameterException: Couldn't set field rootTimeZone
at com.github.joschi.jadconfig.JadConfig.processClassField(JadConfig.java:202) ~[jadconfig-0.15.0.jar:?]
at …
```
=> Add missing JadConfig converters resulting in server startup failure.

graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java, graylog2-web-interface/src/components/datanode/DataNodeList/DataNodeActions.tsx, graylog2-web-interface/src/components/datanode/hooks/useMigrationState.ts, graylog2-web-interface/src/components/datanode/hooks/useShowDatanodeMigration.ts, graylog2-web-interface/src/components/datanode/migrations/common/CertificatesProvisioning.tsx, graylog2-web-interface/src/components/navigation/bindings.ts
Adds the `datanode:read` permission to the reader role and hides unavailable tabs and action items
/nocl regression introduced before release
fixes [#10340 ](https://github.com/Graylog2/graylog-plugin-enterprise/issues/10340)
=> Fix cluster management reader permissions

changelog/unreleased/pr-22162.toml, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/PaginationResultES7.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/PaginationResultOS2.java
Prior to this change, getting the next chunk would result in a GET call to the indexer which was error prone if the HTTP line (e.g. if there were many indices) got longer than the specification would allow. Wrapping this into the correct call that uses a `msearch` in the backend solves this.
fixes #21554
Manual test by hardcoding the batch size to 5 (instead of 500) and creating an Event. On triggering the event, checking the flow with the debugger.
=> Using msearch for Pagination

changelog/unreleased/pr-22343.toml, graylog2-web-interface/src/views/logic/views/UseCreateViewForEvent.ts, graylog2-web-interface/test/helpers/mocking/EventAndEventDefinitions_mock.ts
When running the event-replay function, fields were added to the group_by that were not supposed to be added there and resulted in a aggregation widget that did not show the correct results.
fixes #19862 
manually
=> Remove field that was added by error to group_by for event replay

changelog/unreleased/issue-18947.toml, graylog2-web-interface/src/views/components/widgets/reexecuteSearchTypes.ts, graylog2-web-interface/src/views/logic/SearchResult.ts
**Please note:** This PR needs a backport for `6.0` and `6.1`.
As described in https://github.com/Graylog2/graylog2-server/issues/18947 and https://github.com/Graylog2/graylog2-server/issues/20644 an error is currently not being shown in the message list widget, when it exceeds the search cluster result window. This happens when opening.a page with a number greater than 66. Instead the last valid page of messages is being displayed.
This PR is fixing the behaviour by displaying the error again.
Fixes https://github.com/Graylog2/graylog2-server/issues/18947
Fixes https://github.com/Graylog2/graylog2-server/issues/20644
=> Display error in message list widget when page exceeds search cluster result limit.

changelog/unreleased/pr-22343.toml, graylog2-web-interface/src/views/logic/views/UseCreateViewForEvent.ts, graylog2-web-interface/test/helpers/mocking/EventAndEventDefinitions_mock.ts
Note: This is a backport of #22343 to `6.1`.
When running the event-replay function, fields were added to the group_by that were not supposed to be added there and resulted in a aggregation widget that did not show the correct results.
fixes #19862 
manually
=> Remove field that was added by error to group_by for event replay (`6.1`)

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7Test.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/MoreSearchAdapterOS2.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/MoreSearchAdapterOS2Test.java
Add support for range queries in `MoreSearchAdapter`. 
Required server change to support https://github.com/Graylog2/graylog-plugin-enterprise/pull/10455. 
Closes https://github.com/Graylog2/graylog-plugin-enterprise/issues/10454.
Needs backport to 6.2 for 6.2.1 bug fix release.
/nocl Internal implementation change which does not affect visible functionality.
=> Add support for range queries in MoreSearchAdapter

changelog/unreleased/pr-22450.toml, pom.xml
Newer SDKs break compatibility with third-party S3-compatible services.
See: https://github.com/apache/iceberg/pull/12264
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/10504
=> Revert AWS SDK to 2.29.52

.github/dependabot.yml
Newer versions break compatibility with S3-compatible services.
See:
- https://github.com/apache/iceberg/pull/12264
- https://github.com/Graylog2/graylog-plugin-enterprise/issues/10504
/nocl
=> Restrict AWS SDK updates to version 2.29.x

graylog2-web-interface/src/components/bootstrap/NavDropdown.tsx, graylog2-web-interface/src/components/common/PageNavigation.tsx, graylog2-web-interface/src/components/navigation/Navigation.styles.tsx, graylog2-web-interface/src/components/navigation/ScratchpadToggle.tsx
Before this change it was possible that nav dropdown buttons in the navigation had the following styling after clicking them twice. The styling can be irritating, since the button is not actively focused.
With this PR we are implementing the `:focus-visible` selector, which makes sure we only display the focus styling when an element also has the browser focus styling:
/nocl
=> Improve focus styling for buttons in navigation.

graylog2-web-interface/src/components/common/Select/Select.tsx
With https://github.com/Graylog2/graylog-plugin-enterprise/pull/10452 we started displaying the select menu in a portal. This resulted in styling issues in popovers. This PR increases the menu z-index, to fix the issues.
/nocl
=> Increase z-index of select menu, to fix styling in popovers.

changelog/unreleased/issue-18947.toml, graylog2-web-interface/src/views/components/widgets/reexecuteSearchTypes.ts, graylog2-web-interface/src/views/logic/SearchResult.ts
**Please note:** This PR is a backport of https://github.com/Graylog2/graylog2-server/pull/22311 for `6.2`.
As described in https://github.com/Graylog2/graylog2-server/issues/18947 and https://github.com/Graylog2/graylog2-server/issues/20644 an error is currently not being shown in the message list widget, when it exceeds the search cluster result window. This happens when opening.a page with a number greater than 66. Instead the last valid page of messages is being displayed.
This PR is fixing the behaviour by displaying the error again.
Fixes https://github.com/Graylog2/graylog2-server/issues/18947
Fixes https://github.com/Graylog2/graylog2-server/issues/20644
=> Display error in message list widget when page exceeds search cluster result limit. `6.2`

changelog/unreleased/issue-18947.toml, graylog2-web-interface/src/views/components/widgets/reexecuteSearchTypes.ts, graylog2-web-interface/src/views/logic/SearchResult.ts
**Please note:** This PR is a backport of https://github.com/Graylog2/graylog2-server/pull/22311 for `6.1`.
As described in https://github.com/Graylog2/graylog2-server/issues/18947 and https://github.com/Graylog2/graylog2-server/issues/20644 an error is currently not being shown in the message list widget, when it exceeds the search cluster result window. This happens when opening.a page with a number greater than 66. Instead the last valid page of messages is being displayed.
This PR is fixing the behaviour by displaying the error again.
Fixes https://github.com/Graylog2/graylog2-server/issues/18947
Fixes https://github.com/Graylog2/graylog2-server/issues/20644
=> Display error in message list widget when page exceeds search cluster result limit. `6.1`

graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config
This PR removes the no longer used `new_report_creation` feature flag from the feature flag config.
Related to https://github.com/Graylog2/graylog-plugin-enterprise/pull/10568
/nocl
=> Remove no longer used `new_report_creation` feature flag from feature flag config.

graylog2-server/src/test/java/org/graylog/scheduler/DBJobTriggerServiceTest.java
We ran into CI issues on GitHub Actions where the #deleteCompleted test returned 0 instead of the expected 1. We couldn't reproduce it locally, but it might be related to time issues on the GitHub Action worker.
/nocl Internal refactoring
=> Use a fixed time in DBJobTriggerServiceTest

changelog/unreleased/pr-22531.toml, graylog2-server/src/main/java/org/graylog/plugins/views/search/searchfilters/model/ReferencedQueryStringSearchFilter.java
Prior to this PR, a global Search Filter on a Search that got inlined has no ID, which leads to problems removing/changing it in the FE. This PR fixes it by adding a newly created ID and not by taking the existing ID from the global filter because that could create problems with references.
fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/9719
manual testing
=> Creating an id for a global search filter that get's inlined

changelog/unreleased/issue-22168.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/ast/expressions/FunctionExpression.java
Resolves #22168
Reduce logging rate and add rule name.
Warnings about usage of deprecated pipeline functions are only output once a minute, instead of 5 times every 10 seconds.
We also include the rule name.
See linked issue for details
=> Improve deprecated function logging

changelog/unreleased/pr-22571.toml, graylog2-web-interface/src/integrations/event-notifications/event-notification-types/TeamsNotificationV2Form.tsx
Set the default schema version of the `Microsoft Teams Notification V2` AdaptiveCard to the most recent supported version 1.5. 1.6 is not currently fully supported in Teams.
A user pointed out that schema version 1.6 AdaptiveCard was not being displayed properly in their Teams messages. Reverting the schema version to 1.5 resolved the issue. After investigation, [Microsoft Teams currently supports schema version 1.5](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#adaptive-card) fully so this change is to allow new notifications to work out of the box.
=> Default to AdaptiveCard Schema v1.5 in TeamsNotificationV2

changelog/unreleased/issue-8844.toml, graylog2-server/src/main/java/org/graylog/plugins/cef/codec/CEFCodec.java, graylog2-server/src/test/java/org/graylog/plugins/cef/codec/CEFCodecTest.java
-> Updated Codec to fix the timestamp parsing for Netscaler WAF logs.
-> It handles the parsing of timestamp when log contains priority in the beginning.
-> Added test cases which parsed the timestamp value in log properly.
=> Fix timestamp parsing for Netscaler WAF logs

graylog2-web-interface/src/brand-customization/useProductName.ts, graylog2-web-interface/src/components/common/Icon/Icon.tsx, graylog2-web-interface/src/components/common/Icon/types.ts
This PR adds:
- More sizes for the Icon component. Now we will have a size up to `x10`
- default product name variable, which we can import in other places 
These changes we need to finish https://github.com/Graylog2/graylog-plugin-enterprise/issues/10582
/nocl
=> Extend Icons props and add the default product name variable

graylog2-web-interface/src/routing/hooks/useShowRouteForEntity.ts
Prior to this PR, the newly added entity sharing button for reports showed the wrong URL that can be used to directly link to the report.
/nocl as the sharing on reports is a new, unreleased feature
=> Fixing the url generation to the entity in the sharing modal for reports

graylog2-web-interface/src/components/permissions/EntityShareModal.tsx, graylog2-web-interface/src/domainActions/permissions/EntityShareDomain.ts
Prior to this change, the message shown when finishing sharing an object was wrong:
In place of the title, the entity type was printed and in place of the type was the entity name.
See https://github.com/Graylog2/graylog-plugin-enterprise/pull/10627#pullrequestreview-2836872800 for an example.
/nocl because it's a small change/fix that does not really impact anything
=> Fix Sharing notification message string

changelog/unreleased/pr-22571.toml, graylog2-web-interface/src/integrations/event-notifications/event-notification-types/TeamsNotificationV2Form.tsx
Note: This is a backport of #22571 to `6.0`.
Set the default schema version of the `Microsoft Teams Notification V2` AdaptiveCard to the most recent supported version 1.5. 1.6 is not currently fully supported in Teams.
A user pointed out that schema version 1.6 AdaptiveCard was not being displayed properly in their Teams messages. Reverting the schema version to 1.5 resolved the issue. After investigation, [Microsoft Teams currently supports schema version 1.5](https://learn.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#adaptive-card) fully so this change is to allow new notifications to work out of the box.
=> Default to AdaptiveCard Schema v1.5 in TeamsNotificationV2 (`6.0`)

graylog2-web-interface/src/components/enterprise/AdvertisementSection.tsx, graylog2-web-interface/src/components/enterprise/PluginList.tsx, graylog2-web-interface/src/pages/EnterprisePage.tsx
This PR removes mention of GL on the Enterprise Overview page and also hides the advertisement for the enterprise users 
fix: https://github.com/Graylog2/graylog-plugin-enterprise/issues/10591
/nocl
=> Remove GL mention on Enterprise page

graylog2-server/src/main/java/org/graylog/events/contentpack/facade/EventDefinitionFacade.java, graylog2-server/src/main/java/org/graylog/security/DBGrantService.java, graylog2-server/src/main/java/org/graylog/security/entities/EntityOwnershipService.java, graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackService.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/DashboardFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/EntityWithExcerptFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SearchFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/ViewFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/dashboardV1/DashboardV1Facade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/ContentPackUninstallation.java, graylog2-server/src/test/java/org/graylog/events/contentpack/facade/EventDefinitionFacadeTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackServiceTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/DashboardV1FacadeTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/ViewFacadeTest.java
Keeps track of grants that existed for deleted content pack entities during uninstalls
/prd Graylog2/graylog-plugin-enterprise#10658
/nocl will include PR in enterprise changelog
preserve entity sharing across Illuminate upgrades
see Graylog2/graylog-plugin-enterprise#10161
Local dev environment doing multiple Illuminate upgrades
=> Collect grants of deleted entities on Content Pack uninstall

changelog/unreleased/issue-8844.toml, graylog2-server/src/main/java/org/graylog/plugins/cef/codec/CEFCodec.java, graylog2-server/src/test/java/org/graylog/plugins/cef/codec/CEFCodecTest.java
Note: This is a backport of #22549 to `6.1`.
-> Updated Codec to fix the timestamp parsing for Netscaler WAF logs.
-> It handles the parsing of timestamp when log contains priority in the beginning.
-> Added test cases which parsed the timestamp value in log properly.
=> Fix timestamp parsing for Netscaler WAF logs (`6.1`)

graylog2-server/src/main/java/org/graylog/events/search/EventsSearchService.java
This PR fixes the necessity to share the Default Event stream (introduced by https://github.com/Graylog2/graylog2-server/pull/22488) which leads to full visibility of the whole stream to the user. This is no longer necessary with this PR.
For the System Event stream, this is still needed (sharing) and the assumption is, that if you want to see these in the Alerts & Events page, the user should also be able to search this stream with our regular functionality.
(Which is different from the Default Event stream handling then)
/nocl
=> Allow events search per default only on the default events stream

changelog/unreleased/issue-22618.toml, full-backend-tests/src/test/java/org/graylog/events/rest/EventsResourceIT.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java
**Note:** This needs to be backported to `6.2.0`.
This PR is fixing an issue as reported in #22618, where the Events histogram did not work on ES7, due to the result being casted to the wrong result class. This PR is now adding a test to reproduce this and fixes the class used for casting.
Fixes #22618.
=> Using correct class when casting alerts histogram result on ES7

changelog/unreleased/issue-22618.toml, full-backend-tests/src/test/java/org/graylog/events/rest/EventsResourceIT.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java
**Note:** This is a backport of #22622 to `6.2`.
This PR is fixing an issue as reported in #22618, where the Events histogram did not work on ES7, due to the result being casted to the wrong result class. This PR is now adding a test to reproduce this and fixes the class used for casting.
Fixes #22618.
=> Using correct class when casting alerts histogram result on ES7 (`6.2`)

changelog/unreleased/issue-22296.toml, graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java, graylog2-server/src/main/java/org/graylog2/bindings/providers/DefaultJmteEngineProvider.java, graylog2-server/src/main/java/org/graylog2/bindings/providers/JsonSafeEngineProvider.java, graylog2-server/src/main/java/org/graylog2/jmte/NamedDateRenderer.java, graylog2-server/src/test/java/org/graylog/events/notifications/types/HTTPEventNotificationV2Test.java
Note: This is a backport of #22632 to `6.1`.
Add `NamedDateRenderer` to JMTE Engine.
Allows use of custom date formatting inside of custom notification templates.
closes #22296 
closes Graylog2/support#210
local dev env, unit test
=> Support date formatting in jmte templates (`6.1`)

changelog/unreleased/pr-22715.toml, graylog2-server/src/main/java/org/graylog2/shared/journal/LocalKafkaJournal.java, graylog2-server/src/test/java/org/graylog2/shared/journal/LocalKafkaJournalTest.java
In 7a0b955f228e7b0f39ba2274e5c6af75532be691 we implemented a journal recovery mechanism that tries to read from truncated journals. We trigger the recovery when the #read() method returns an empty list.
The method can also return an empty list when the journal is in shutdown mode. In that case, we don't want to go into recovery mode.
=> Don't go into journal recovery when shutting down

graylog2-web-interface/src/components/extractors/EditExtractor.tsx, graylog2-web-interface/src/components/extractors/converters_configuration/CSVConverterConfiguration.tsx, graylog2-web-interface/src/components/extractors/converters_configuration/DateConverterConfiguration.tsx, graylog2-web-interface/src/components/extractors/converters_configuration/FlexdateConverterConfiguration.tsx, graylog2-web-interface/src/components/extractors/converters_configuration/HashConverterConfiguration.tsx, graylog2-web-interface/src/components/extractors/converters_configuration/IpAnonymizerConverterConfiguration.tsx, graylog2-web-interface/src/components/extractors/converters_configuration/LookupTableConverterConfiguration.tsx, graylog2-web-interface/src/components/extractors/converters_configuration/LowercaseConverterConfiguration.tsx, graylog2-web-interface/src/components/extractors/converters_configuration/NumericConverterConfiguration.tsx, graylog2-web-interface/src/components/extractors/converters_configuration/SplitAndCountConverterConfiguration.tsx, graylog2-web-interface/src/components/extractors/converters_configuration/SyslogPriFacilityConverterConfiguration.tsx, graylog2-web-interface/src/components/extractors/converters_configuration/SyslogPriLevelConverterConfiguration.tsx, graylog2-web-interface/src/components/extractors/converters_configuration/TokenizerConverterConfiguration.tsx, graylog2-web-interface/src/components/extractors/converters_configuration/UppercaseConverterConfiguration.tsx, graylog2-web-interface/src/components/extractors/extractors_configuration/GrokExtractorConfiguration.tsx, graylog2-web-interface/src/components/extractors/extractors_configuration/JSONExtractorConfiguration.tsx, graylog2-web-interface/src/components/extractors/extractors_configuration/LookupTableExtractorConfiguration.tsx, graylog2-web-interface/src/components/extractors/extractors_configuration/RegexExtractorConfiguration.tsx, graylog2-web-interface/src/components/extractors/extractors_configuration/RegexReplaceExtractorConfiguration.tsx, graylog2-web-interface/src/components/extractors/extractors_configuration/SplitAndIndexExtractorConfiguration.tsx, graylog2-web-interface/src/components/extractors/extractors_configuration/SubstringExtractorConfiguration.tsx
This PR is fixing ESLint hints related to the `import/no-named-as-default-member` rule.
Please note, there are some ESLint hints in the changed files, most of them will be addressed in follow-up PRs.
/nocl
=> Use named exports when importing `FormsUtils`.

changelog/unreleased/issue-22544.toml, data-node/src/main/java/org/graylog/datanode/Configuration.java
The `native_lib_dir` location in data node was previously set to `native_lib` which caused an error in the distribution packages as this will try to write it to `/native_lib`.
This PR creates the directory inside of the configured `opensearch_config_location` to make sure we have a writable directory.
fixes #22544 
locally, observe `native_lib` dir inside opensearch config directory.
=> Fix data node native lib dir location

changelog/unreleased/pr-22778.toml, graylog2-server/src/main/java/org/graylog/events/notifications/NotificationTestData.java, graylog2-server/src/main/java/org/graylog/events/processor/EventDefinitionDto.java, graylog2-server/src/main/java/org/graylog/events/processor/EventProcessorConfig.java, graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessorConfig.java, graylog2-server/src/main/java/org/graylog/events/processor/systemnotification/SystemNotificationEventProcessorConfig.java, graylog2-server/src/main/java/org/graylog/events/rest/EventDefinitionsResource.java, graylog2-server/src/test/java/org/graylog/events/TestEventProcessorConfig.java, graylog2-server/src/test/java/org/graylog/events/processor/EventDefinitionDtoTest.java, graylog2-server/src/test/java/org/graylog/events/processor/aggregation/AggregationEventProcessorConfigTest.java, graylog2-web-interface/src/components/event-definitions/event-definition-form/EventConditionForm.tsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.test.tsx
**Note:** This is based on #22771, which needs to be merged before.
This PR is making sure that if a user is creating an event definition, does not have the global `streams:read` permission and has an empty `streams` field in the event definition config, a validation error will be returned instead of a 403. This way, the frontend can handle it and show the user a helpful message in the event definition creation dialog instead of ending up on an error page.
Fixes Graylog2/graylog-plugin-enterprise#10869.
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/10970
=> Turn permission error into validation error for empty streams in event definition.

changelog/unreleased/issue-22373.toml, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/validators/UnknownFieldsValidator.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/validation/validators/UnknownFieldsValidatorTest.java
UnknownFieldsValidator without a warning for asterisk in field name.
Fixes #22373
See #22373
Manually and with a new unit test.
=> UnknownFieldsValidator without a warning for asterisk in field name

changelog/unreleased/pr-22835.toml, graylog2-server/src/main/java/org/graylog/integrations/ipfix/IpfixParser.java
When an IPFIX input has an incomplete `IPFIX field definitions` template, the following error is logged, which does not indicate which specific `element_id` is missing in the definitions file. This makes it difficult to fix the template to include the missing field. 
> ERROR [DecodingProcessor] Error processing message java.lang.NullPointerException: Cannot invoke "org.graylog.integrations.ipfix.InformationElementDefinition.dataType()" because "desc" is null
This PR adds logging to gracefully handle this condition and provide a helpful log message:
> ERROR: Unable to find info element definition due to incomplete field definitions: id [{}] PEN [{}]. To fix this error, update the IPFIX field definitions template file to include a definition for this ID.
=> Add logging for missing IPFIX template definition

changelog/unreleased/issue-22140.toml, graylog2-server/src/main/java/org/graylog/integrations/aws/service/KinesisService.java, graylog2-web-interface/src/integrations/aws/common/formDataAdapter.js, graylog2-web-interface/src/integrations/aws/common/formDataAdapter.test.js
While testing https://github.com/Graylog2/graylog2-server/pull/22825, I noticed the following error on one of our test instances. The error was intermittent and only occurred about 50% of the time. It turns out that it was only happening on the Graylog Follower node due to https://github.com/Graylog2/graylog-plugin-enterprise/issues/11075.
This PR removes the accidental inclusion of the `override_source` field in AWS Kinesis/CloudWatch input wizard requests (except for the final input save where it's needed).
=> Fix unrecognized `override_source` field error on follower

graylog2-web-interface/src/views/logic/fieldactions/ChangeFieldType/ChangeFieldTypeModal.tsx, graylog2-web-interface/src/views/logic/fieldactions/ChangeFieldType/IndexSetsTable.tsx
While working on the other task related to changing field type, I noticed a few bugs when there is no index sets to select
1. There is `0` under the No index sets have been found
2. we don't block submit button when there is no selected index sets
This PR fixes these issues
/nocl
=> Change field type modal improvements

pom.xml
We handle the Maven Central deployment separately in a later step of the release process.
/nocl Internal release process refactoring.
=> Deploy Maven artifacts to a local repository during the release build

graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterForm.tsx
Avoid `undefined` options when calling `flatMap` on a `stream.categories` value of `null`. 
/nocl
addresses Graylog2/graylog-plugin-enterprise#11022 possibly along with changes in #22853? Not 100% sure if we need that change as well.
eliminates the phantom category option in the select seen here:
could not repro in latest code, but I think this is likely the cause of the bug in 6.3-rc1
=> Correctly generate stream category select options

UPGRADING.md
Rotates UPGRADING.md for 7.0. Also adds a note about API change which restores enforcement of unknown JSON fields from https://github.com/Graylog2/graylog-plugin-enterprise/pull/11085.
/nocl Change log is present in https://github.com/Graylog2/graylog-plugin-enterprise/pull/11085.
=> Rotate UPGRADING.md for 7.0, Add note about ObjectMapper unknown properties change

graylog-project-parent/pom.xml
The dependency was added in e5e37e1ff95 without a version attribute.
/nocl
=> Add missing dependency management for guava-testlib

graylog2-web-interface/src/components/configurations/DecoratorsConfig.tsx
Fixed decorators query functions. The `queryFn` property was missing creating an unexpected state
closes: #22977 
/nocl
=> fix: Add queryFn object key

graylog2-web-interface/templates/index.html.template
This PR is making sure that the plugin loading order is aligned between development and production mode.
/nocl Only relevant for dev.
=> Aligning plugin loading order in development mode.

changelog/unreleased/pr-23014.toml, graylog2-web-interface/src/theme/z-indices.ts, graylog2-web-interface/src/views/components/sidebar/ContentColumn.tsx, graylog2-web-interface/src/views/components/sidebar/NavItem.tsx, graylog2-web-interface/src/views/components/sidebar/Sidebar.tsx, graylog2-web-interface/src/views/components/sidebar/SidebarNavigation.tsx
**Please note**, this PR needs a backport for `6.2` and `6.3`.
Before this PR a pinned search sidebar could overlap navigation dropdown menus.
Before: 
After:
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/11200
=> Display navigation dropdown menus over pinned search sidebar.

changelog/unreleased/issue-19329.toml, graylog2-web-interface/src/components/layout/PageContentLayout.tsx, graylog2-web-interface/src/util/UIUtils.js
**Please note**, for post `6.3` versions, the related bug has been fixed by refactoring the scroll hint implementation. See https://github.com/Graylog2/graylog2-server/pull/22928.
This PR is fixing the problem with the scroll hint on the search page, described in https://github.com/Graylog2/graylog2-server/issues/19329, by using the correct selector for the scroll container.)
=> Fix scroll on click behaviour for scroll hint on search page (`6.2`).

changelog/unreleased/issue-19329.toml, graylog2-web-interface/src/components/layout/PageContentLayout.tsx, graylog2-web-interface/src/util/UIUtils.js
**Please note**, for post `6.3` versions, the related bug has been fixed by refactoring the scroll hint implementation. See https://github.com/Graylog2/graylog2-server/pull/22928.
This PR is fixing the problem with the scroll hint on the search page, described in https://github.com/Graylog2/graylog2-server/issues/19329, by using the correct selector for the scroll container.)
=> Fix scroll on click behaviour for scroll hint on search page (`6.1`)

changelog/unreleased/issue-21900.toml, graylog2-web-interface/src/views/components/searchbar/queryinput/StyledAceEditor.tsx
Please note, this PR needs a backport for `6.1`, `6.2` and `6.3`.
This PR improves the background color of selected text in search query input by using the system default.
Before:
After:
Fixes #21900
=> Use system color to highlight selected text in search query input.

graylog2-server/src/main/java/org/graylog/events/processor/EventProcessorExecutionJob.java
Include the event definition ID in the one `ERROR` level log missing it in `EventProcessorExecutionJob`.
/nocl logging improvement
User was seeing this log message frequently but did not know how to trace it back to an event definition. While it is possible to do in Mongo using the trigger ID, we have the event definition ID handy in code so may as well make the log more immediately useful to users.
=> Include eventDefinitionId on EventProcessorExecutionJob error message

changelog/unreleased/pr-23111.toml, graylog2-server/src/main/java/org/graylog/plugins/views/startpage/recentActivities/RecentActivityService.java
Prior to this PR, there was the slight possibility for a race condition between the check for the existence of the collection and the creation because multiple instances of the service could be created. Now, as a singleton, the check/creation code should only run once per server. 
This problem should only occur with Mongo5&6 - re-creating collections with the same parameter set is idempotent in mongo7 (and probably upwards, have not tested later versions)
fixes #23092
=> Fix: avoid possible race condition on collection creation in `RecentActivityService` 

changelog/unreleased/issue-19329.toml, graylog2-web-interface/src/components/layout/PageContentLayout.tsx, graylog2-web-interface/src/util/UIUtils.js
**Please note**, for post `6.3` versions, the related bug has been fixed by refactoring the scroll hint implementation. See https://github.com/Graylog2/graylog2-server/pull/22928.
This PR is fixing the problem with the scroll hint on the search page, described in https://github.com/Graylog2/graylog2-server/issues/19329, by using the correct selector for the scroll container.
=> Fix scroll on click behaviour for scroll hint on search page (`6.3`).

changelog/unreleased/issue-19346.toml, graylog2-web-interface/src/components/common/SourceCodeEditor.tsx
**Please note**, in post `6.3` versions the fix for this issue is part of a refactoring https://github.com/Graylog2/graylog2-server/pull/23049
With this PR we are improving the color of comments in the pipeline editor. (related to https://github.com/Graylog2/graylog2-server/issues/19346 & https://github.com/Graylog2/graylog2-server/issues/19695)
Before light and dark mode
After light and dark mode:
We are also implementing the system color for the background of selected text.
=> Fix color of comments in pipeline rule editor. `6.3`

graylog2-server/src/main/java/org/graylog/plugins/map/geoip/GeoLocationInformation.java, graylog2-server/src/test/java/org/graylog/plugins/map/geoip/GeoLocationInformationTest.java
Closes https://github.com/Graylog2/graylog-plugin-enterprise/issues/11300
Fixes this NPE error when some Geo fields are null.
```
java.lang.NullPointerException
at java.base/java.util.Objects.requireNonNull(Objects.java:209)
at java.base/java.util.ImmutableCollections$MapN.<init>(ImmutableCollections.java:1186)
at java.base/java.util.Map.of(Map.java:1506)
at org.graylog.plugins.map.geoip.GeoLocationInformation.toIndexable(GeoLocationInformation.java:117)
```
Tests added to cover the null condition.
/nocl minor error handling for unreleased feature
=> Fix NPE for toIndexable method when geo info when some fields null

graylog2-web-interface/src/integrations/aws/common/AdditionalFields.tsx, graylog2-web-interface/src/integrations/aws/common/FormWrap.tsx
This PR is a small follow-up for https://github.com/Graylog2/graylog2-server/pull/22370 and implements some best practices:
1. In styled components we do not check if the dark mode is active, to display a different color. We point to a specific color in the theme, like `theme.colors.text.primary` and the theme will provide different colors depending on the selected theme mode (dark / light).
2. We avoid hard coded colors and only point to the theme, to be able to customize the colors easily.
3. When defining a prop, like `isDarkMode`, for a styled component we prefix it with a `$`, otherwise this will create an attribute for the DOM node. https://styled-components.com/docs/api#transient-props.
/nocl
=> Small refactoring related to styled-components in AWS integrations components.

graylog2-web-interface/src/views/components/widgets/TimerangeInfo.tsx, graylog2-web-interface/src/views/components/widgets/Widget.tsx, graylog2-web-interface/src/views/components/widgets/WidgetHeader.tsx
This PR is showing the widget description at the bottom-left of a widget when in non-interactive/full screen mode. This makes the widget description widget visible in contexts where the popover cannot be clicked/hovered.
/nocl Extending unreleased feature.
=> Show widget description inline in full screen mode.

changelog/unreleased/issue-19346.toml, graylog2-web-interface/src/components/common/SourceCodeEditor.tsx
**Please note**, in post `6.3` versions the fix for this issue is part of a refactoring https://github.com/Graylog2/graylog2-server/pull/23049
With this PR we are improving the color of comments in the pipeline editor. (related to https://github.com/Graylog2/graylog2-server/issues/19346 & https://github.com/Graylog2/graylog2-server/issues/19695)
Before light and dark mode
After light and dark mode:
We are also implementing the system color for the background of selected text.
=> Fix color of comments in pipeline rule editor.  `6.1`

changelog/unreleased/issue-19346.toml, graylog2-web-interface/src/components/common/SourceCodeEditor.tsx
**Please note**, in post `6.3` versions the fix for this issue is part of a refactoring https://github.com/Graylog2/graylog2-server/pull/23049
With this PR we are improving the color of comments in the pipeline editor. (related to https://github.com/Graylog2/graylog2-server/issues/19346 & https://github.com/Graylog2/graylog2-server/issues/19695)
Before light and dark mode
After light and dark mode:
We are also implementing the system color for the background of selected text.
=> Fix color of comments in pipeline rule editor. `6.2`

changelog/unreleased/pr-23181.toml, graylog2-web-interface/src/views/components/widgets/CopyToDashboardForm.tsx
**Please note**, this PR should be backported to `6.1`, `6.2` and `6.3`.
This PR fixes the header styling of the "copy widget to dashboard" modal, by adding a headline.
Before:
After:
=> Fix header styling of copy widget to dashboard modal.

changelog/unreleased/pr-23150.toml, graylog2-web-interface/src/components/bootstrap/Panel.tsx
**Please note**, in post `6.3` versions we improved the styles by unifying the `Alert` and `Panel` colors. https://github.com/Graylog2/graylog2-server/pull/23147
Before light mode:
Before dark mode:
After light mode:
After dark mode:
=> Fix panel colors for dark mode `6.3`

changelog/unreleased/issue-23031.toml, graylog2-web-interface/src/views/components/visualizations/XYPlot.tsx, graylog2-web-interface/src/views/components/visualizations/__tests__/XYPlot.test.tsx
Note: This is a backport of #23032 to `6.1`.
As described in #23031, selecting the axis type `logarithmic` has currently no effect. This PR is fixing this issue.
Fixes #23031
=> Display correct visualization for bar charts with logarithmic axis type (`6.1`)

changelog/unreleased/issue-20746.toml, graylog2-web-interface/src/components/bootstrap/Badge.md, graylog2-web-interface/src/components/bootstrap/Badge.tsx, graylog2-web-interface/src/components/streams/StreamCountBadge.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/cells/OutputsCell.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/cells/PipelinesCell.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/cells/StreamRulesCell.tsx
As described in https://github.com/Graylog2/graylog2-server/issues/20746 some badges in the streams overview are missing contrast in the dark mode.
This is how they look in the light mode:
This PR improves the styling by using the `gray` / `info` `Badge` variants instead of custom colors.
Dark mode
Light mode
Please note, we will improve the icon color issue, mentioned in https://github.com/Graylog2/graylog2-server/issues/20746, in a follow-up PR.
=> Improve colors of badges in streams overview.

changelog/unreleased/pr-23065.toml, graylog2-web-interface/src/views/components/DashboardSearchBar.tsx, graylog2-web-interface/src/views/components/SearchBar.tsx, graylog2-web-interface/src/views/components/WidgetQueryControls.tsx, graylog2-web-interface/src/views/components/searchbar/queryvalidation/QueryValidation.test.tsx, graylog2-web-interface/src/views/components/searchbar/queryvalidation/QueryValidation.tsx, graylog2-web-interface/src/views/components/searchbar/queryvalidation/ViewsQueryValidation.tsx, graylog2-web-interface/src/views/components/searchbar/queryvalidation/types.ts, graylog2-web-interface/src/views/types.ts
**Please note**, this is a backport of https://github.com/Graylog2/graylog2-server/pull/23065 to `6.2`.
The query input and query validation icon are not only implemented for the search bar on the search page, but also for the search filter form (enterprise feature).
Before this PR, the query validation consumed pluggable validation explanation components (plugin key `views.elements.validationErrorExplanation`). These components are views specific and consume the redux store. 
As a result, opening the query validation explanation on pages which do not implement the views specific redux store, caused an error (see https://github.com/Graylog2/graylog-plugin-enterprise/issues/10911).
This PR is improving this behaviour by only implementing the views specific validation explanations, for the …
=> Implement views specific query validation only for query validation in search bar. `6.2`

graylog2-server/src/main/java/org/graylog/security/shares/CollectionRequestHandler.java, graylog2-server/src/main/java/org/graylog/security/shares/GranteeSharesService.java, graylog2-server/src/test/java/org/graylog/security/shares/GranteeSharesServiceTest.java
/nocl
/jpd Graylog2/graylog-plugin-enterprise#11386
Grants of type COLLECTION and COLLECTION_ENTITIES should not be displayed when showing the list of entities that are shared with a user or team - we handle those elsewhere in the UI.
=> Filter collection entities in shares list

changelog/unreleased/pr-23276.toml, data-node/src/main/java/org/graylog/datanode/opensearch/configuration/beans/impl/OpensearchClusterConfigurationBean.java, data-node/src/main/java/org/graylog/datanode/opensearch/configuration/beans/impl/OpensearchCommonConfigurationBean.java, data-node/src/main/java/org/graylog/datanode/opensearch/configuration/beans/impl/OpensearchNodeRole.java, data-node/src/main/java/org/graylog/datanode/opensearch/configuration/beans/impl/SearchableSnapshotsConfigurationBean.java, data-node/src/test/java/org/graylog/datanode/opensearch/configuration/beans/impl/OpensearchClusterConfigurationBeanTest.java, data-node/src/test/java/org/graylog/datanode/opensearch/configuration/beans/impl/SearchableSnapshotsConfigurationBeanTest.java, graylog2-server/src/main/java/org/graylog2/cluster/nodes/DataNodeDto.java
This PR is fixing the generated `cluster.initial_cluster_manager_nodes` opensearch configuration in datanode, using only nodes that have the `cluster_manager` role.
**TODO** this would deserve at least 6.3 backport.
Problem as reported:
If you have a node with node_roles = search configured during Data Node cluster initialisation, the config generated will still prepopulate cluster.initial_cluster_manager_nodes including that node. Since it does not have cluster_manager as a role the cluster will not form.The workaround is to not start any node that does not have cluster_manager role configured (directly or automatically). You can add them to the cluster afterwards.The fix is to not add any nodes without the cluster_manager role to cluster.initial_cluster_manager_nodes during the initial …
=> Fix list of opensearch initial manager nodes in datanode

data-node/src/main/java/org/graylog/datanode/opensearch/configuration/beans/impl/OpensearchClusterConfigurationBean.java, data-node/src/test/java/org/graylog/datanode/opensearch/configuration/beans/impl/OpensearchClusterConfigurationBeanTest.java
The `cluster.initial_cluster_manager_nodes` is populated with nodes registered with the nodeService. 
It is possible that the node that is currently starting up has not sent a heartbeat yet and therefore might not be registered. For single node installations, this results in an empty string as `cluster.initial_cluster_manager_nodes`, causing Opensearch not being able to form a cluster.
/nocl fixes regression introduced during development
added unit tests / manual startup
=> Datanode: fix possible race condition when building iniital manager nodes

graylog2-server/src/main/java/org/graylog/security/entities/DefaultEntityDependencyResolver.java, graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackService.java, graylog2-server/src/test/java/org/graylog/security/entities/DefaultEntityDependencyResolverTest.java
Allow resolving **sharing** dependencies for multiple entities at once.
Before, it was only possible to resolve the dependencies of a single entity. So, for container entities, like collections (which is an enterprise feature), the content pack resolver and additional post-processing had to be executed in a loop for every entity in the container.
This PR deliberately avoids changing too many things at once. The dependency resolver for sharing will now operate on the dependency graph of the content pack resolver, which is exposed for that purpose. This way, the sharing resolver's additional filtering requirements will still work. Other parts, which could use refactoring, like resolving the titles of entities, are not touched.
There's still plenty of room for improvement, but with these …
=> Allow resolving dependencies for multiple entities at once

changelog/unreleased/pr-23283.toml, graylog2-web-interface/src/components/event-definitions/event-definition-form/ShareForm.tsx
During event definition creation, if one directly shares the event definition, the dependency check did not take the notifications into account as dependencies. This PR adds the missing grns to the check.
fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/11055
=> Add missing notification grns to sharing dependency check during event definition creation

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/conversion/AbstractConversion.java
Minor improvement for `defaultToNull` parameter description for conversion pipeline functions (introduced in https://github.com/Graylog2/graylog2-server/pull/22733). This is a common parameter to many functions, and some have an actual default configuration parameter, and some do not. Most have a value to that they default to (even if they don't have an actual configurable `default` param) such as `to_map` and `csv_to_map`. This adjustment generalizes the description to help it work for all functions.
Originated from docs improvements for https://github.com/Graylog2/graylog2-server/pull/22733.
/nocl minor wording change
=> Improve wording for conversion function defaultToNull parameter

changelog/unreleased/issue-20746.toml, graylog2-web-interface/src/components/bootstrap/Badge.md, graylog2-web-interface/src/components/bootstrap/Badge.tsx, graylog2-web-interface/src/components/streams/StreamCountBadge.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/cells/OutputsCell.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/cells/PipelinesCell.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/cells/StreamRulesCell.tsx
Note: This is a backport of #23211 to `6.2`.
As described in https://github.com/Graylog2/graylog2-server/issues/20746 some badges in the streams overview are missing contrast in the dark mode.
This is how they look in the light mode:
This PR improves the styling by using the `gray` / `info` `Badge` variants instead of custom colors.
Dark mode
Light mode
Please note, we will improve the icon color issue, mentioned in https://github.com/Graylog2/graylog2-server/issues/20746, in a follow-up PR.
=> Improve colors of badges in streams overview. (`6.2`)

graylog2-server/src/test/java/org/graylog2/commands/CommonNodeCommandTest.java, graylog2-server/src/test/java/org/graylog2/commands/MinimalNodeCommandTest.java, graylog2-server/src/test/resources/org/graylog2/commands/common-node.conf, graylog2-server/src/test/resources/org/graylog2/commands/minimal-node.conf
The common node test wrote a node ID file into the source directory. (`graylog2-server/node_id_file`)
Replace static config files with dynamically generated files that are written to a tmp directory.
/nocl Internal test refactoring
=> Don't let node command tests write into source directory

changelog/unreleased/issue-20746.toml, graylog2-web-interface/src/components/bootstrap/Badge.md, graylog2-web-interface/src/components/bootstrap/Badge.tsx, graylog2-web-interface/src/components/streams/StreamCountBadge.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/cells/OutputsCell.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/cells/PipelinesCell.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/cells/StreamRulesCell.tsx
Note: This is a backport of #23211 to `6.1`.
As described in https://github.com/Graylog2/graylog2-server/issues/20746 some badges in the streams overview are missing contrast in the dark mode.
This is how they look in the light mode:
This PR improves the styling by using the `gray` / `info` `Badge` variants instead of custom colors.
Dark mode
Light mode
Please note, we will improve the icon color issue, mentioned in https://github.com/Graylog2/graylog2-server/issues/20746, in a follow-up PR.
=> Improve colors of badges in streams overview. (`6.1`)

changelog/unreleased/issue-22321.toml, changelog/unreleased/issue-23002.toml, graylog2-web-interface/src/components/common/PaginatedList.tsx, graylog2-web-interface/src/components/common/Pagination.tsx, graylog2-web-interface/src/views/components/widgets/MessageList.test.tsx, graylog2-web-interface/src/views/components/widgets/MessageList.tsx, graylog2-web-interface/src/views/logic/SearchResult.ts
Note: This is a backport of https://github.com/Graylog2/graylog2-server/pull/23013 to `6.1`.
There are currently two issues with the message table pagination. https://github.com/Graylog2/graylog2-server/issues/23002 & https://github.com/Graylog2/graylog2-server/issues/22321
Both are related to the circumstance that the pagination is updated after the request for a page finished. The logic for the message table pagination is quite complex because
- the active page is maintained inside the `PaginatedList` and the `MessageList` component.
- the results are provided via the `MessageList` props and not via the response of `reexecuteSearchTypes`. Currently we can't identify the page a set of messages relate to.
- although all messages are provided via the props, their origin is not always the …
=> Improve updates of message table pagination. (`6.1`)

graylog2-web-interface/src/integrations/aws/StepAuthorize.tsx, graylog2-web-interface/src/integrations/aws/authentication/AWSAuthenticationTypes.tsx, graylog2-web-interface/src/integrations/aws/authentication/AWSCustomEndpoints.tsx, graylog2-web-interface/src/integrations/aws/cloudwatch/CloudWatch.test.jsx, graylog2-web-interface/src/integrations/aws/cloudwatch/CloudWatch.tsx, graylog2-web-interface/src/integrations/aws/cloudwatch/EmbeddedCloudWatchApp.tsx, graylog2-web-interface/src/integrations/aws/cloudwatch/FormAdvancedOptions.tsx, graylog2-web-interface/src/integrations/aws/cloudwatch/StepHealthCheck.tsx, graylog2-web-interface/src/integrations/aws/cloudwatch/StepReview.test.jsx, graylog2-web-interface/src/integrations/aws/cloudwatch/StepReview.tsx, graylog2-web-interface/src/integrations/aws/cloudwatch/kinesis/ExistingStreams.tsx, graylog2-web-interface/src/integrations/aws/cloudwatch/kinesis/SetupNewStream.tsx, graylog2-web-interface/src/integrations/aws/cloudwatch/kinesis/setup-steps/KinesisSetupSteps.tsx, graylog2-web-interface/src/integrations/aws/common/SkipHealthCheck.tsx, graylog2-web-interface/src/integrations/aws/common/hooks/useFetch.js, graylog2-web-interface/src/integrations/contexts/FormDataContext.tsx, graylog2-web-interface/src/integrations/contexts/FormDataProvider.tsx, graylog2-web-interface/src/integrations/types.ts
This PR creates a `FormDataContext` and `FormDataProvider` component and types, which can be used for all related inputs. The goal is to remove redundant code.
/prd https://github.com/Graylog2/graylog-plugin-enterprise/pull/11524
/nocl - no visible changes
=> Create `FormDataContext` and `FormDataProvider`, which can be used for all related inputs

changelog/unreleased/issue-11313.toml, graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotification.java, graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationV2.java, graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPNotification.java, graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPUtils.java, graylog2-server/src/test/java/org/graylog/events/notifications/types/HTTPUtilsTest.java
Add support for retrying retryable HTTP response codes in the HTTP and Custom HTTP notifications.
These codes are now retried (let me know if I missed any):
- All 5xx codes
- 408 (timeout), 429 (too many requests) 
HTTP notification portion of https://github.com/Graylog2/graylog-plugin-enterprise/issues/11313.
Any other relevant notifications will be taken care of in separate PRs. 
This test HTTP server (https://app.beeceptor.com/console/testserver98769869876789698) supports the following endpoints to respond with the corresponding codes. The notification can be tested with each to confirm that the `TemporaryEventNotificationException` is thrown to trigger retrying.
- 200 (success): https://testserver98769869876789698.free.beeceptor.com
- 400 (no retrying): …
=> Add retrying for retryable HTTP status codes in HTTP Noitifications

changelog/unreleased/pr-23351.toml, graylog2-web-interface/src/components/event-definitions/event-definition-form/ShareForm.tsx
The Event Definition create wizard sharing page was throwing errors for Event Definition config types that do not use streams (e.g. Asset Events).
This PR adds handling for that case.
https://github.com/user-attachments/assets/f4cdf454-4233-4798-8084-38e6f29e615e
/nocl - only affects unreleased feature.
See above video.
Locally in development environment by creating an Asset Events definition and progressing through the create wizard.
Reproduction Steps:
1. Create a new event definition
2. On Condition page select "Asset Events"
3. Click "Next" the "Share page is reached"
=> Fix errors on Event Definition create wizard sharing page when config does not have streams

data-node/src/main/java/org/graylog/datanode/Configuration.java, data-node/src/main/java/org/graylog/datanode/jwt/DatanodeJwtAuthTokenProvider.java, data-node/src/main/java/org/graylog/datanode/opensearch/configuration/beans/impl/OpensearchSecurityConfigurationBean.java, data-node/src/main/java/org/graylog/datanode/process/configuration/files/OpensearchSecurityConfigurationFile.java, data-node/src/test/java/org/graylog/datanode/initializers/JwtTokenAuthFilterTest.java, data-node/src/test/java/org/graylog/datanode/testinfra/DatanodeContainerizedBackend.java, full-backend-tests/src/test/java/org/graylog/searchbackend/datanode/DatanodeProvisioningIT.java, full-backend-tests/src/test/java/org/graylog/searchbackend/datanode/DatanodeSelfsignedStartupIT.java, graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchClientConfiguration.java, graylog2-server/src/main/java/org/graylog2/security/jwt/IndexerJwtAuthTokenProvider.java, graylog2-server/src/test/java/org/graylog2/security/jwt/IndexerIndexerJwtAuthTokenProviderTest.java, graylog2-server/src/test/java/org/graylog2/storage/versionprobe/VersionProbeImplTest.java
/nocl yet
Opensearch currently doesn't support clock skew tolerance setting for plain JWT auth, which we use between graylog server, datanode and opensearch. If the clock in the server is ahead of clock in datanode, it may happen that we'll generate tokens that are considered invalid in datanode/opensearch. 
This fix in opensearch is correcting the problem https://github.com/opensearch-project/security/pull/5506, but it will be available only in 3.2 and newer.
To work around this problem now, we can generate tokens with extended validity on both ends - *not before* and *expiration*, adding those default 30s. 
This should provide enough tolerance for systems slightly out of time sync. 
Manually + existing and extended unit tests
=> Workaround for broken clock skew tolerance in opensearch

graylog2-web-interface/src/components/indices/CreateIndexSet.tsx, graylog2-web-interface/src/pages/IndexSetCreationPage.tsx
Skip the template selection stage of creating a new index set when the 'indexset_templates:read' permission is not present.
/nocl
closes: #23394
=> Skip template selection on index set creation based on permission

graylog2-web-interface/packages/eslint-config-graylog/index.js
In https://github.com/Graylog2/graylog2-server/pull/22790 a custom regex has been added for the `assertFunctionNames` option of the ESLint Jest expect rule.
It currently throws an error when running ESLint:
`SyntaxError: Invalid regular expression: /^selectEvent\.assertOptionExists([a-z\d]*(\.|$)/iu: Unterminated group`
This PR fixes the error.
/nocl
=> Fix `assertFunctionNames` regex, related to ESLint Jest expect rule.

graylog-plugin-parent/graylog-plugin-web-parent/pom.xml, graylog2-server/pom.xml
We have to set skip.web.tests to false if skipTests is present. Otherwise, the web tests run even with skipTests present.
/nocl Build infrastructure
=> Fix -DskipTests for web tests

changelog/unreleased/pr-23505.toml, graylog2-web-interface/src/components/configurationforms/ConfigurationForm.tsx, graylog2-web-interface/src/components/outputs/EditOutputButton.test.tsx, graylog2-web-interface/src/components/outputs/EditOutputButton.tsx
Note: This is a backport of #23505 to `6.2`.
As described in https://github.com/Graylog2/graylog-plugin-enterprise/issues/8432, the `Edit` output button in the outputs list requires two clicks to open the edit modal.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/8432
=> Open output edit modal with first click on `Edit` button. (`6.2`)

full-backend-tests/pom.xml, full-backend-tests/src/test/java/org/graylog/plugins/views/ScriptingApiResourceIT.java, full-backend-tests/src/test/java/org/graylog/searchbackend/datanode/DatanodeOpensearchProxyIT.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/Indices.java
- Wrap test methods in awaitility in DatanodeOpensearchProxyIT
- In ScriptingApiResourceIT, wait for the actual messages to be present instead of relying on the message count which could be wrong depending on the order of other tests
- In AggregationSortingIT, waiting for the successful creation of the needed indices/index set was not safe enough regarding all the possible error conditions during waiting
The tests we see fail:
```
[INFO] Running org.graylog.searchbackend.datanode.DatanodeOpensearchProxyIT
Error:  Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.449 s <<< FAILURE! -- in org.graylog.searchbackend.datanode.DatanodeOpensearchProxyIT
Error:  org.graylog.searchbackend.datanode.DatanodeOpensearchProxyIT.testProxyPlaintextGet -- Time elapsed: 0.078 s <<< FAILURE! …
```
=> Improve some full-backed tests to be less flaky

.github/workflows/dispatch-pr-build.yml
Requires the following PRs to be merged first:
- https://github.com/Graylog2/graylog-project-internal/pull/184
- https://github.com/Graylog2/e2e-tests/pull/1272
/nocl CI changes
=> Trigger e2e-tests for PRs when labeled with the "e2e-tests" label

.github/workflows/dispatch-pr-build.yml
The PR dispatch workflow runs should not cancel each other! When opening a PR with labels (e.g., dependabot), we receive one "opened" and one or more "labeled" events. If we would cancel the workflow run for "opened" when receiving a "labeled", the PR build in graylog-project-internal would not be triggered.
/nocl CI infrastructure
=> Remove concurrency from dispatch-pr-build workflow

changelog/unreleased/pr-23677.toml, graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationFormContainer.tsx
Fixes issue causing event notifications to be uneditable and usable immediately after creation (until a page refresh) if the user only has the `eventnotifications:create` permissions for event notifications (no `eventnotifications:edit:*` permission).
This change refreshes user permissions (by fetching the current user and its permissions) right after adding a new notification. This allows the permission for the newly added notification to be seen by the frontend `isPermitted()` check, which allows the row contains a link to the view the notification details and Share/More actions menus all filled-out. 
Before:
After:
=> Fix issue displaying table row after adding notification

graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/Indices.java
This PR is making sure that a newly created test environment is waiting for the deflector to come up before continuing. This prevents situations where the tests are already trying to ingest messages while the deflector alias does not exist yet.
=> Waiting for deflector when creating index sets in tests.

graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/GraylogRestApi.java
The test below throws an `AssertionError` during the `waitFor` which is not an Exception, so we catch these also.
```
[INFO] Running org.graylog2.inputs.InputCreationIT
HTTP/1.1 404 Not Found
X-Content-Type-Options: nosniff
X-Graylog-Node-ID: 44206fb7-682e-44fb-8be9-479a23ee9181
X-Frame-Options: DENY
X-Runtime-Microseconds: 1161
Content-Type: application/json
Content-Length: 100
{
"type": "ApiError",
"message": "No input state for input id <68d3e074f6967d70af674328> on this node."
}
Error:  Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.225 s <<< FAILURE! -- in org.graylog2.inputs.InputCreationIT
Error:  org.graylog2.inputs.InputCreationIT.testHttpRandomInputCreation -- Time elapsed: 0.071 s <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status …
```
=> IT Tests: we also need to catch AssertionError and not only Exception in waitFor

graylog2-server/src/main/java/org/graylog2/web/customization/Config.java, graylog2-server/src/test/java/org/graylog/integrations/notifications/types/microsoftteams/TeamsEventNotificationTest.java, graylog2-web-interface/src/util/AppConfig.ts, graylog2-web-interface/src/util/DocsHelper.test.ts, graylog2-web-interface/src/util/DocsHelper.ts
**Note:** This is a backport of #23717 to `6.3`.
This PR allows overriding docs URLs individually per page.
/nocl Internal functionality.
=> Supporting overriding individual URLs for help pages. (`6.3`)

graylog2-server/src/main/java/org/graylog2/database/entities/source/DBEntitySourceService.java, graylog2-server/src/main/java/org/graylog2/database/entities/source/EntitySourceService.java, graylog2-server/src/main/java/org/graylog2/database/utils/SourcedMongoEntityUtils.java
Utility methods for filtering by EntitySource for components that do not yet use the common EntityTable component on the frontend.
/nocl included in enterprise CL
filtering content by source
local dev
=> Add methods to filter entity source for entities that do not currently use EntityTable

graylog2-web-interface/src/components/streams/StreamsOverview/StreamActions.tsx, graylog2-web-interface/src/pages/StreamsPage.tsx
This is a fix for the bug found by @AntonEbel where the actions on a newly created stream, for a user with only the stream:create permission, are missing or disabled until the page is reloaded.
/nocl
closes: #23305
=> Stream Action Update Bug Fix

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/ast/expressions/FunctionExpression.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/RouteToStream.java, graylog2-server/src/main/java/org/graylog2/plugin/utilities/ratelimitedlog/RateLimitedLogFactory.java, graylog2-server/src/main/java/org/graylog2/streams/StreamServiceImpl.java, graylog2-server/src/test/java/org/graylog2/streams/StreamServiceImplTest.java
Update/notify the `StreamCacheService` when new stream is created. Previously components using `StreamCacheService` would not successfully load new streams until the server was reloaded. 
This appears to be a regression in https://github.com/Graylog2/graylog2-server/pull/22313 (where the cluster event bus post was inadvertently lost), which was only introduced as part of Graylog 7.0, so there is no need for a backport or a change log.
Also adds rate limited logging when stream not found in cache to more loudly alert user to cause of issue. 
/nocl bug did not exist in previous stable releases, so no need for a change log.
/jpd https://github.com/Graylog2/graylog-plugin-enterprise/pull/12035
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/12028.
Added a unit test.
Manual …
=> Update event stream cache when stream is created

changelog/unreleased/pr-23795.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/PipelineConnectionsResource.java
In the dropdown to connect streams to pipelines, the user sees all streams that he has `read` permissions for.
When connecting them, we check for the `edit` permission for that stream, leading to inconsistent behavior.
Having `read` permission should be sufficient. This implies that users could potentially edit or route messages from streams. 
However, if you have access to edit pipelines, you are already performing an administrative task (and can already direct messages into any stream you choose using a pipeline rule). the pipeline subsystem is separate from the stream subsystem (pipelines relate to processing, while the stream subsystem relates to labelling and storage) and if you have permission to use it, it would follow that you should be able to administrate the processing of any …
=> Change precondition for connecting pipelines to streams
