Graylog2/graylog2-server

graylog2-web-interface/src/components/search/MessageTablePaginator.jsx
Fixes an issue when no "pageSize" prop is provided. This broke in #4160.
Before this fix:
This needs to be merged into the 2.4 branch as well!
=> Correctly initialize the "pageSize" prop in MessageTablePaginator

graylog2-web-interface/public/stylesheets/graylog2.less, graylog2-web-interface/src/components/dashboard/AddToDashboardMenu.jsx, graylog2-web-interface/src/components/field-analyzers/FieldQuickValues.jsx, graylog2-web-interface/src/components/field-analyzers/FieldStatistics.jsx, graylog2-web-interface/src/components/field-analyzers/LegacyFieldGraph.jsx
This change unifies the action components (buttons and dropdowns) of all field analyzer widgets we ship. Those components are found in the top right corner of each widget.
* The "Dismiss Widget" button is now always a close icon and on the far right of all actions. Before it was sometimes directly accessible and sometimes hidden behind a "Customize" drop-down. The change to a close _icon_ makes it stand out more and also saves real-estate. A margin to the left helps to identify it quickly and avoids accidental pressing of it.
* The "Add to dashboard" button has the same and less intrusive button across all widgets now.
* The new Quick Values configuration dialog is accessible directly without going through the "Customize" drop-down. In fact, the "Customize" drop-down only had "Customize" …
=> Unify action components of all field analyzers

graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexSetsResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/responses/IndexSetStats.java, graylog2-server/src/test/java/org/graylog2/rest/resources/system/indexer/IndexSetsResourceTest.java, graylog2-web-interface/src/actions/indices/IndexSetsActions.js, graylog2-web-interface/src/components/indices/IndexSetsComponent.jsx, graylog2-web-interface/src/routing/ApiRoutes.js, graylog2-web-interface/src/stores/indices/IndexSetsStore.jsx
Add information and stats about all indices on the "Index Sets" page without accounting for pagination. The reason for this is, that finding out the total size of all indices can be really annoying if you have a lot of index sets. See also #4204.
This change was initiated by customer request #1503. 
This introduces a new REST API endpoint at "/system/indices/index_sets/stats" to retrieve global, aggregated stats without pagination or other information about the index sets.
Tested on a local setup and also a v2.3.1 with about 500GB of data in over 400 indices and 3 index sets. The performance impact to calculate the stats with an initial concern but my benchmarks showed that it only adds about 300ms to the *Index Sets* page load time, which is acceptable IMO. Adding a caching layer or …
=> Show stats of all index sets without pagination

graylog2-web-interface/src/components/lookup-tables/CachesOverview.jsx, graylog2-web-interface/src/components/lookup-tables/DataAdaptersOverview.jsx, graylog2-web-interface/src/components/lookup-tables/LookupTablesOverview.jsx, graylog2-web-interface/src/components/lookup-tables/Overview.css
tweak CSS to avoid long descriptions collapsing the other columns too much
fixes #4172
=> set proper widths/max-widths for table columns in lookup table pages

graylog2-web-interface/src/legacy/Rickshaw.Graph.Graylog2Selector.js
the old jquery code could submit the search form directly when the alt key was pressed.
ever since moving to react this was broken because the code cannot submit the form anymore.
this removes the useless code to avoid a javascript error
fixes #4214
=> remove "alt key submits" functionality from histogram

graylog2-server/src/main/java/org/graylog2/bindings/WidgetStrategyBindings.java, graylog2-server/src/main/java/org/graylog2/dashboards/widgets/strategies/QuickvaluesBaseWidgetStrategy.java, graylog2-server/src/main/java/org/graylog2/dashboards/widgets/strategies/QuickvaluesHistogramWidgetStrategy.java, graylog2-server/src/main/java/org/graylog2/dashboards/widgets/strategies/QuickvaluesWidgetStrategy.java, graylog2-server/src/main/java/org/graylog2/indexer/results/HistogramResult.java, graylog2-server/src/main/java/org/graylog2/indexer/results/TermsHistogramResult.java, graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java, graylog2-server/src/main/java/org/graylog2/plugin/Tools.java, graylog2-server/src/main/java/org/graylog2/rest/models/search/responses/TermsHistogramResult.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/KeywordSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/RelativeSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/SearchResource.java, graylog2-server/src/main/java/org/graylog2/utilities/SearchUtils.java, graylog2-web-interface/src/actions/field-analyzers/FieldQuickValuesActions.js, graylog2-web-interface/src/components/field-analyzers/FieldQuickValues.jsx, graylog2-web-interface/src/components/field-analyzers/QuickValuesOptionsForm.jsx, graylog2-web-interface/src/components/visualizations/QuickValuesHistogramVisualization.jsx, graylog2-web-interface/src/components/visualizations/StackedChartVisualization.jsx, graylog2-web-interface/src/components/visualizations/index.jsx, graylog2-web-interface/src/components/widgets/configurations/QueryConfiguration.jsx, graylog2-web-interface/src/components/widgets/configurations/QuickValuesConfiguration.jsx, graylog2-web-interface/src/components/widgets/configurations/QuickValuesHistogramWidgetCreateConfiguration.jsx, graylog2-web-interface/src/components/widgets/configurations/QuickValuesHistogramWidgetEditConfiguration.jsx, graylog2-web-interface/src/components/widgets/configurations/QuickValuesWidgetEditConfiguration.jsx, graylog2-web-interface/src/components/widgets/configurations/index.js, graylog2-web-interface/src/components/widgets/types/index.js, graylog2-web-interface/src/routing/ApiRoutes.js, graylog2-web-interface/src/stores/field-analyzers/FieldQuickValuesStore.js, graylog2-web-interface/src/util/SearchUtils.js
This implements a new visualization to show quick values over time as a stacked bar chart.
Refs #4082
=> Implement QuickValues over time widget

graylog2-web-interface/src/components/field-analyzers/FieldQuickValues.jsx, graylog2-web-interface/src/components/visualizations/QuickValuesVisualization.jsx
Explicitly name the root field in the subtitle because "this field" becomes unclear once stacking is in use.
Fixes #4217
Note: This needs to be cherry picked into 2.4
=> Adjust QuickValues pie chart subtitle

graylog2-server/src/main/java/org/graylog2/indexer/IndexSetRegistry.java, graylog2-server/src/main/java/org/graylog2/indexer/MongoIndexSetRegistry.java, graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java, graylog2-server/src/test/java/org/graylog2/indexer/searches/SearchesIT.java, pom.xml
Scroll queries were broken for a number of different reasons:
* The fork of Jest used by Graylog had a bug regarding scroll queries (searchbox-io/Jest#489, searchbox-io/Jest#491)
* The Elasticsearch Multi Search API doesn't support scroll queries (elastic/elasticsearch#18454)
Due to the default HTTP request length limit of Elasticsearch, `Search#scroll()` resolves the affected index sets and uses the index wildcards instead of separate index names.
Fixes #4190
=> Fix scroll queries using Searches#scroll()

graylog2-server/src/main/java/org/graylog2/rest/resources/roles/RolesResource.java, graylog2-web-interface/src/components/users/RoleList.jsx
This change set fixes the handling of permissions for roles in the `/system/roles` resource of the Graylog REST API and only displays the "Edit" and "Delete" buttons in the role overview (System / Authentication / Roles) if the user has sufficient permissions.
Fixes #4254
=> Fix permission handling for editing/deleting roles

graylog2-server/src/main/java/org/graylog2/lookup/adapters/dsvhttp/DSVParser.java, graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupCache.java, graylog2-web-interface/src/components/lookup-tables/adapters/index.js
The DSV HTTP adapter used the wrong component in the frontend and its internal fields were a bit complicated.
Fix a gauge metric reregistration issue in LookupCaches.
=> Minor lookup table fixes

graylog2-web-interface/public/stylesheets/graylog2.less, graylog2-web-interface/src/components/dashboard/AddToDashboardMenu.css, graylog2-web-interface/src/components/dashboard/AddToDashboardMenu.jsx, graylog2-web-interface/src/components/field-analyzers/FieldQuickValues.jsx, graylog2-web-interface/src/components/field-analyzers/FieldStatistics.jsx, graylog2-web-interface/src/components/field-analyzers/LegacyFieldGraph.jsx
This PR fixes two issues with the new unified analyzer menus:
- Make menus look grouped, fixing issue #4230
- Set `pullRight` option to menus, so that they open to the left side, avoiding cropping menus too close to the window edge
=> Improvements in unified analyzer menus

.travis.yml, graylog2-server/pom.xml
The VersionEye SaaS is shutting down, so we should remove the integration with our build.
https://blog.versioneye.com/2017/10/19/versioneye-sunset-process/
=> Remove VersionEye

graylog2-server/src/main/java/org/graylog2/indexer/results/TermsHistogramResult.java, graylog2-server/src/main/java/org/graylog2/indexer/results/TermsResult.java, graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java, graylog2-server/src/main/java/org/graylog2/rest/models/search/responses/TermsResult.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/SearchResource.java, graylog2-server/src/main/java/org/graylog2/utilities/SearchUtils.java, graylog2-web-interface/src/components/visualizations/QuickValuesVisualization.jsx, graylog2-web-interface/src/stores/search/SearchStore.ts
This mapping can be used to construct correct ES queries when using the `QuickValues` widget with stacked fields.
Fixes #4216
Note: This needs to be merged into 2.4
=> Return additional field->value mapping for terms queries

graylog2-web-interface/README.md, graylog2-web-interface/package.json, graylog2-web-interface/webpack.config.js
Due to problems with the current webpack-dev-server setup and the number of plugins we use, this adds another option to run the development setup until we find a solution for the webpack-dev-server problem.
=> Add another way to run the development setup

graylog2-web-interface/src/components/alarmcallbacks/AlarmCallbackHistoryOverview.jsx, graylog2-web-interface/src/components/alerts/AlertTimeline.jsx, graylog2-web-interface/src/components/common/ReactGridContainer.jsx, graylog2-web-interface/src/components/visualizations/GraphVisualization.jsx, graylog2-web-interface/src/components/visualizations/HistogramVisualization.jsx, graylog2-web-interface/src/components/visualizations/NumericVisualization.css, graylog2-web-interface/src/components/visualizations/NumericVisualization.jsx, graylog2-web-interface/src/components/visualizations/QuickValuesVisualization.css, graylog2-web-interface/src/components/visualizations/QuickValuesVisualization.jsx, graylog2-web-interface/src/components/visualizations/RenderCompletionObserver.jsx, graylog2-web-interface/src/components/visualizations/StackedGraphVisualization.jsx, graylog2-web-interface/src/components/visualizations/index.jsx, graylog2-web-interface/src/components/widgets/Widget.jsx, graylog2-web-interface/src/util/SortUtils.js
As we were working on some 3.0 features for some time, there are a number of commits that were made in parallel to the master branch, but we didn't merged back yet. Here are some of the changes done:
- Add control over resize widget, even if grid is locked
- Add render complete callbacks to widgets, making it easier for consumers to execute some code when widgets are actually rendered. This is specially useful for widgets not rendered by react
- Improvements in display of numeric visualization
- Make widgets more printer friendly, by adding print styles and props to disable animations
- Encapsulate common sorting methods into `SortUtils`
=> 3.0 changes

graylog2-web-interface/src/routing/Routes.jsx, graylog2-web-interface/src/routing/Routes.test.jsx
Use `resource()` urijs method instead of `path()` when generating routes with prefixes. It also adds some tests to ensure this works in the future.
Fixes #4290.
=> Fix router for routes with query parameters

graylog2-server/src/main/java/org/graylog2/indexer/results/TermsHistogramResult.java, graylog2-server/src/main/java/org/graylog2/rest/models/search/responses/TermsHistogramResult.java, graylog2-server/src/main/java/org/graylog2/utilities/SearchUtils.java, graylog2-web-interface/src/components/field-analyzers/FieldQuickValues.jsx, graylog2-web-interface/src/components/visualizations/QuickValuesHistogramVisualization.jsx, graylog2-web-interface/src/components/visualizations/QuickValuesVisualization.jsx, graylog2-web-interface/src/stores/field-analyzers/FieldQuickValuesStore.js, graylog2-web-interface/src/stores/search/SearchStore.ts
Previously we showed the top/bottom N terms for every bucket in the histogram. That was hard to visualize because every bucket could contain completely different terms.
Now we changed the visualization to show *only* the top/bottom N terms from the regular QuickValues widget projected over time.
Fixes #4291
Note: This needs to be merged into 2.4 as well
=>  Change data that is shown by the QuickValues histogram

graylog2-web-interface/src/components/field-analyzers/LegacyFieldGraph.jsx, graylog2-web-interface/src/legacy/analyzers/fieldcharts.js, graylog2-web-interface/src/stores/field-analyzers/FieldGraphsStore.ts
This PR displays a loading spinner while we fetch data to update a field chart. This will be visible when the search is updated, a new statistical function is selected, and when the chart resolution changes.
Fixes #4295 and should be cherry-picked into 2.4.
=> Show loading indicator when reloading field chart data

graylog2-web-interface/src/components/dashboard/AddToDashboardMenu.jsx, graylog2-web-interface/src/components/widgets/WidgetCreationModal.jsx
Disable button and change the submit button text while we create the new widget. Reset the state once the promise is fulfilled or rejected.
Fixes #4318 and should be cherry-picked into 2.4.
=> Show feedback on create widget modal

graylog2-server/src/main/java/org/graylog2/system/stats/elasticsearch/ElasticsearchProbe.java, graylog2-server/src/main/java/org/graylog2/system/stats/elasticsearch/ElasticsearchStats.java, graylog2-web-interface/src/components/field-analyzers/FieldQuickValues.jsx, graylog2-web-interface/src/components/field-analyzers/QuickValuesOptionsForm.jsx, graylog2-web-interface/src/routing/ApiRoutes.js, graylog2-web-interface/src/stores/system/SystemStore.js
- Disable the stacked field form in QuickValues configuration when Elasticsearch version is < 5
- Reset loading state in case of an error so the user can change settings and try again
- Reset QuickValues visualization config to defaults when analyzing a new field
Closes #4289 
Note: This needs to go into the 2.4 branch as well
=> Improve robustness of QuickValues with stacked fields

graylog2-server/src/main/java/org/graylog2/shared/rest/resources/RestResource.java, graylog2-server/src/main/java/org/graylog2/shared/security/ShiroAuthorizationFilter.java, graylog2-server/src/test/java/org/graylog2/rest/resources/system/indexer/IndexSetsResourceTest.java
Instead of just providing the information that some HTTP request of a user failed due to insufficient permissions, Graylog now provides helpful hints which permission was missing to successfully fulfill the request.
Example responses:
```
HTTP/1.1 403 Forbidden
X-Graylog-Node-ID: cd03ee44-b2a7-4824-be16-bb7456149dbd
Content-Type: application/json
Date: Wed, 11 Oct 2017 09:44:14 GMT
Content-Length: 123
{"type":"ApiError","message":"Not authorized. User <username> is missing permissions [users:list] to perform <GET api/users>"}
```
```
HTTP/1.1 403 Forbidden
X-Graylog-Node-ID: cd03ee44-b2a7-4824-be16-bb7456149dbd
X-Runtime-Microseconds: 81841
Content-Type: application/json
Date: Wed, 11 Oct 2017 09:39:12 GMT
Content-Length: 91
{"type":"ApiError","message":"Not authorized. User <username> is …
```
=> Provide details about missing permissions when unauthorized

graylog2-web-interface/src/components/alertnotifications/CreateAlertNotificationInput.jsx, graylog2-web-interface/src/components/alerts/AlertsHeaderToolbar.jsx, graylog2-web-interface/src/components/alerts/index.jsx, graylog2-web-interface/src/components/lookup-tables/Cache.jsx, graylog2-web-interface/src/components/lookup-tables/DataAdapter.jsx, graylog2-web-interface/src/components/lookup-tables/LookupTable.jsx, graylog2-web-interface/src/pages/AlertConditionsPage.jsx, graylog2-web-interface/src/pages/AlertNotificationsPage.jsx, graylog2-web-interface/src/pages/AlertsPage.jsx, graylog2-web-interface/src/pages/EditAlertConditionPage.jsx, graylog2-web-interface/src/pages/LUTCachesPage.jsx, graylog2-web-interface/src/pages/LUTDataAdaptersPage.jsx, graylog2-web-interface/src/pages/LUTTablesPage.jsx, graylog2-web-interface/src/pages/NewAlertConditionPage.jsx, graylog2-web-interface/src/pages/NewAlertNotificationPage.jsx, graylog2-web-interface/src/pages/ShowAlertPage.jsx
@lennartkoopmann started unifying navigation buttons (e.g. https://github.com/Graylog2/graylog-plugin-pipeline-processor/pull/186), but alerts and lookup tables never got updated.
This PR takes care of those sections, by:
- Keeping same button layout when it makes sense
- Using `active` class to indicate the section currently opened
- Moving or changing some buttons, when there are many things to show in the navigation
=> Unify navigation

graylog2-web-interface/src/components/search/MessageTableEntry.jsx, graylog2-web-interface/src/components/search/ResultTable.jsx, graylog2-web-interface/src/components/visualizations/NumericVisualization.jsx, graylog2-web-interface/src/components/visualizations/RenderCompletionObserver.jsx
This PR takes care of a few missing usages of `React.PropTypes` that were in our code. The initial work was done in #4059.
This problem only triggers a warning in development mode, so no need to migrate it to 2.4.0.
=> Migrate usages of React.PropTypes to PropTypes

graylog2-web-interface/src/components/bootstrap/BootstrapModalForm.jsx, graylog2-web-interface/src/components/bootstrap/BootstrapModalWrapper.jsx, graylog2-web-interface/src/components/streams/MatchingTypeSwitcher.jsx
As ES6 React components are here to stay, update existing ES6 classes to ensure other people have a more or less good example to look at:
- Use arrow functions instead of manually binding functions in constructor
- Add `propTypes`, `defaultProps` and state directly inside the class, making components look more like those created with `createClass`. Unfortunately creating an ESLint rule for this requires more time that I'm willing to spend on it right now
- Use function `ref`s
- Remove superfluous functions
=> Update ES6 classes formatting

graylog2-web-interface/devServer.js, graylog2-web-interface/package.json, graylog2-web-interface/src/index.jsx, graylog2-web-interface/webpack.combined.config.js, graylog2-web-interface/webpack.config.js
Many of us (if not everyone) has problems running `webpack-dev-server` with many plugins, as the server keeps disconnecting from the web browser.
In order to solve that, but keeping the setup easy to install and start, this PR adds a custom express server, using `webpack-dev-middleware` and `webpack-hot-middleware` to achieve something similar to what we had before with the `start-nohmr` script. This works by enabling webpack hot module replacement, but not accepting any changes, forcing webpack to reload the page when a change is detected.
Apart from performing a full page reload on each change, the new setup also helps highlighting errors in files, producing a result like this:
Regarding build times, they seem to be roughly the same, but this needs more testing and also some external …
=> Replace webpack-dev-server with custom express server

graylog2-web-interface/webpack.config.js
Fixes an issue with running the production build.
=> Define REPLACE_MODULES in webpack production build as well

misc/graylog.conf
This PR adds more details about the `outputbuffer_processor_keep_alive_time`, `outputbuffer_processor_threads_core_pool_size`, and `outputbuffer_processor_threads_max_pool_size` settings based on the Javadoc for [`ThreadPoolExecutor`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ThreadPoolExecutor.html).
=> Add more details about outputbuffer_* settings

graylog2-server/src/main/java/org/graylog2/dashboards/widgets/strategies/QuickvaluesWidgetStrategy.java, graylog2-web-interface/src/components/visualizations/QuickValuesVisualization.jsx
- Return "terms_mapping" in QuickValuesWidgetStrategy. This ensures that we also use a more visible separator when using stacked fields.
-  Use a darker color for the QuickValues field separator. The previous one was too bright.
Fixes #4336 
Note: This needs to be cherry-picked into 2.4 as well
=> Fix QuickValues term separator rendering

graylog2-web-interface/src/components/authentication/AuthProvidersConfig.jsx
Update in this screen feels like there will be some configuration change happening once the button is pressed, but we use that button to open a modal where the user can actually change the configuration. I found it a bit confusing myself, and thought that "edit" would be more appropriate in this case.
Before:
After:
=> Change edit auth providers config button

graylog2-web-interface/src/components/users/__snapshots__/UserPreferencesButton.test.js.snap
Apparently there are some new props inside react-bootstrap that affect the `UserPreferencesButton` snapshot.
=> Fix test snapshot after updating react-bootstrap

graylog2-web-interface/src/routing/App.jsx, graylog2-web-interface/src/routing/AppGlobalNotifications.css, graylog2-web-interface/src/routing/AppGlobalNotifications.jsx
A plugin can register a "globalNotifications" UI extension that will be rendered into the global notification area on each page.
Note: This needs to be cherry-picked into 2.4
```jsx
import React from 'react';
import { Alert } from 'react-bootstrap';
const GlobalTestNotification = React.createClass({
render() {
return (
<Alert bsStyle="danger">
<h4><strong>Alert</strong></h4>
<p>This is an example alert.</p>
</Alert>
);
},
});
export default GlobalTestNotification;
```
```jsx
import packageJson from '../../package.json';
import { PluginManifest, PluginStore } from 'graylog-web-plugin/plugin';
import GlobalTestNotification from 'GlobalTestNotification';
PluginStore.register(new PluginManifest(packageJson, {
globalNotifications: [
{
key: 'org.graylog.plugins.test.GlobalTestNotification', …
```
=> Add pluggable global notification area to App component

graylog2-web-interface/src/components/indices/IndexSetsComponent.jsx
- Do not try to stop event propagation in MenuItem callback functions
- Fix eslint errors
- Let _formatStatsString handle undefined global stats
Fixes #4376
Note: This needs to be cherry-picked into the 2.4 branch
=> Fix changing the default index set from the UI

graylog2-web-interface/src/pages/GettingStartedPage.jsx, graylog2-web-interface/src/routing/ApiRoutes.js, graylog2-web-interface/src/routing/App.jsx, graylog2-web-interface/src/routing/AppRouter.jsx, graylog2-web-interface/src/routing/AppWithGlobalNotifications.jsx
Avoid displaying global notifications in the not found page. Other error pages do not need to be taken in consideration at this point, as they are rendered before react-router, and therefore do not render the global notifications component.
=> Do not show global notifications in 404 page

graylog-plugin-archetype/src/main/resources/archetype-resources/src/web/index.jsx, graylog2-web-interface/.babelrc, graylog2-web-interface/README.md, graylog2-web-interface/devServer.js, graylog2-web-interface/package.json, graylog2-web-interface/src/index.jsx, graylog2-web-interface/webpack.combined.config.js, graylog2-web-interface/webpack.config.js, graylog2-web-interface/yarn.lock
In the last few weeks we did quite a few changes in the development toolchain we use in the web interface, resulting in unfinished configurations, confusing scripts running different tools, and outdated documentation (or, let's say, even useless documentation).
This PR fixes at least some of those problems by:
- Letting users customise the port of the development server
- Use a random port when the first we try to use is taken (cc @lilliCao)
- Remove alternative dev setup introduced in #4294, since we already fixed the issues with the dev-server that lead to its creation
- Remove dev setup using react-hot-loader, as I could not find a way to fix it, and nobody seems to use it anyway. I wrote a bit more about the reasoning for this in the [commit …
=> Web dev improvements

graylog2-web-interface/src/components/alertnotifications/CreateAlertNotificationInput.jsx, graylog2-web-interface/src/components/common/ExternalLink.jsx, graylog2-web-interface/src/components/common/ExternalLink.md, graylog2-web-interface/src/components/common/ExternalLinkButton.jsx, graylog2-web-interface/src/components/common/ExternalLinkButton.md, graylog2-web-interface/src/components/common/index.jsx, graylog2-web-interface/src/components/inputs/CreateInputControl.jsx, graylog2-web-interface/src/components/navigation/HelpMenu.jsx, graylog2-web-interface/src/components/nodes/InputTypesDataTable.jsx, graylog2-web-interface/src/components/nodes/NodeMaintenanceDropdown.jsx, graylog2-web-interface/src/components/nodes/NodesActions.jsx, graylog2-web-interface/src/components/nodes/PluginsDataTable.jsx
They can be used to render links to external websites which should be decorated with an icon to make it visible that the user leaves the Graylog UI.
Also switch all external links in our codebase over to the new components.
Note: This needs to be **cherry-picked into 2.4** once it's merged
=> Add and use ExternalLink and ExternalLinkButton components

graylog2-server/src/main/java/org/graylog2/rest/resources/system/authentication/AuthenticationResource.java, graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java, graylog2-web-interface/src/components/authentication/AuthProvidersConfig.jsx, graylog2-web-interface/src/components/grok-patterns/GrokPatterns.jsx, graylog2-web-interface/src/components/loggers/NodeLoggers.jsx, graylog2-web-interface/src/pages/GrokPatternsPage.jsx
Hides various content when the user does not have the correct permission to avoid accidentally leaking information in the future.
Added a new `authentication:read` permission to disambiguate the `clusterconfigentry:read` check
fix #4407
=> Don't render partial page content when missing permissions

graylog2-web-interface/src/components/cluster/TrafficGraph.jsx, graylog2-web-interface/src/components/visualizations/HistogramVisualization.jsx
the default renderers can now be replaced individually by setting props
used in TrafficGraphs to display nicer values
fixes #4395
=> allow to pass custom renderers for key and value titles in histograms

UPGRADING.rst
Graylog needs ES version >=5.6.x now.
=> Add new Elasticsearch version requirement to UPGRADING

graylog2-web-interface/src/components/search/QueryInput.ts
The "_missing_" query has been removed in Elasticsearch 5.0:
https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_search_changes.html#_deprecated_queries_removed
Refs #4362
=> Replace "_missing_" query with "NOT _exists_"

graylog2-server/src/main/java/org/graylog2/Configuration.java
check node id file permissions as part of parameter validation, instead of failing during injection
doing IO during object construction is brittle and leads to unintelligible error messages
fixes #4410
=> check node id file permissions as part of parameter validation

graylog2-web-interface/src/components/visualizations/QuickValuesVisualization.jsx
otherwise the search store will end up searching for the unix timestamp which is not supported
fixes #4288
=> Convert timestamp quickvalues to formatted date

graylog2-server/src/main/java/org/graylog2/Configuration.java, graylog2-server/src/test/java/org/graylog2/ConfigurationTest.java
server start would fail if the node id was non-empty, but not writable.
this is a valid scenario where the node id is frozen by making the file read-only
added tests for various scenarios
fixes #4427
=> fix node id file permission checks

graylog2-server/src/main/java/org/graylog2/Configuration.java, graylog2-server/src/test/java/org/graylog2/ConfigurationTest.java
We revert this for 2.4 because we ran into issues and edge cases twice. So for the 2.4 release we don't want to risk any issues. We keep the changes in 3.0 and create another fix.
=> Revert node-id file validations

graylog2-server/src/test/java/org/graylog2/inputs/codecs/SyslogCodecTest.java
Set the year to 2017 to match test expectations.
This should also be merged into 2.4 to ensure the tests work in that branch too.
=> Fix SyslogCodecTest.testCiscoSyslogMessages

graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/InputStatesResource.java, graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java
Before this change, any user was able to start/stop inputs without the
possession of the required privileges. The `InputStatesResource` class
did not perform any permission checks for operations.
After this change, a user who starts/stops an input requires the newly
introduced `inputs:changestate` permission (consistent with permission
handling of indices/processing/streams) in order to perform these
state changes.
Fixes #4439.
=> Checking user privileges before performing Input State operations.

graylog2-server/src/main/java/org/graylog2/plugin/inject/Graylog2Module.java, graylog2-server/src/main/java/org/graylog2/shared/bindings/ObjectMapperModule.java, graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/ObjectMapperProvider.java
this allows registering multiple jackson subtypes with overlapping names, which jackson already handles correctly
fixes #4457
=> replace name, class map binder with NamedType set binder

.github/no-response.yml
This bot is automatically closing issues which are marked to be in need
for more information, but this information was not provided in a
reasonable time frame.
More information about the bot is provided here:
https://probot.github.io/apps/no-response/
=> Enabling No Response bot for repository.

graylog2-web-interface/package.json, graylog2-web-interface/src/components/common/ClipboardButton.jsx, graylog2-web-interface/src/components/common/SourceCodeEditor.css, graylog2-web-interface/src/components/common/SourceCodeEditor.jsx, graylog2-web-interface/src/components/common/SourceCodeEditor.md, graylog2-web-interface/src/components/common/index.jsx, graylog2-web-interface/yarn.lock
This PR moves the source code editor we used in the pipelines to the web interface, so other plugins can reuse it if they need it.
I manage to make a few improvements in there, hopefully they will improve the experience of using it:
- Updated to latest version of ReactAce
- Fixed issue with undo command after load: https://github.com/Graylog2/graylog-plugin-pipeline-processor/issues/224. I'm not fully satisfied with the fix, so I'll try to do a better fix and get it upstream
- Allow editor to be user-resizable, fixing https://github.com/Graylog2/graylog-plugin-pipeline-processor/issues/229
- Add read-only flag, so we can also pre-visualize code with the component
- Add toolbar to make more visibles some actions that can be done in the editor. For now only copying, pasting*, undo, and redo …
=> Add source editor component

graylog2-server/src/main/java/org/graylog2/rest/resources/streams/outputs/StreamOutputResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/outputs/OutputResource.java
**StreamOutputResource**:
* consistenly using `checkPermission()` instead of mixed usage of
`checkPermission()` and @RequiresPermission
* removing check for `stream_outputs:create` permission in `get()`,
this permission should not be required for retrieving stream output
list
* adding checks for stream editing permissions in `add` & `remove`
**OutputResource**:
* consistenly using `checkPermission()` instead of mixed usage of
`checkPermission()` and @RequiresPermission
* removing check for `stream_outputs:create` permission in `get()`,
this permission should not be required for retrieving system output
list
* changing permission of `available` from `streams:read` (sic!) to
`outputs:read`
* removing `@RequirePermission` in `delete` & `update`, as they were
redundant due to usages of …
=> Correcting required permissions for (Stream) Output Management.

graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java, graylog2-server/src/main/java/org/graylog2/security/realm/MongoDbAuthorizationRealm.java, graylog2-server/src/main/java/org/graylog2/users/UserPermissionsCleanupListener.java, graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java, graylog2-server/src/main/java/org/graylog2/users/events/UserChangedEvent.java, graylog2-server/src/test/java/org/graylog2/users/UserPermissionsCleanupListenerTest.java, graylog2-server/src/test/java/org/graylog2/users/UserServiceImplTest.java, graylog2-web-interface/src/routing/ApiRoutes.js, graylog2-web-interface/src/stores/streams/StreamsStore.ts
Before this change, a user with sufficient privileges to create a
stream could create one which is immediately inaccessible to the user
because the user is missing read/edit privileges to it. This change
checks for the required privileges and adds them to this specific
stream if necessary.
For non-admin users it is required to refresh user permissions both in
the frontend (using `CurrentUserStore.reload`) and the backend (by
invalidating the authorization cache, due to a race condition between
retrieving the list for the frontend and refreshing the authorization
cache) to be able to list the newly created stream.
Fixes #4450.
=> Adding privileges to user for created stream if not admin.

graylog2-web-interface/README.md
Here is a small update to the web interface readme file to include some steps on how to get to the frontend documentation site and how to run it locally.
=> Add frontend documentation and component gallery to readme

graylog2-server/src/main/java/org/graylog2/rest/RestTools.java, graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java, graylog2-server/src/main/java/org/graylog2/web/IndexHtmlGenerator.java, graylog2-server/src/main/resources/web-interface/index.html.template, graylog2-server/src/test/java/org/graylog2/rest/RestToolsTest.java, misc/graylog.conf
Due to changes in the http config handling, the ability to run behind a proxy with a custom path prefix was lost.
This PR restores the application prefix handling.
fixes #4315
=> Restore ability to run behind reverse proxy

graylog2-web-interface/src/components/users/PermissionSelector.jsx, graylog2-web-interface/src/components/users/PermissionSelector.test.jsx, graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
So I changed the label of the buttons from "Toggle" to
"Set" and "Clear" depending on which state the streams
permissions are. If all permissions are "Allow" the button
will read "Clear" and remove the permissions. If one or
more will have no "Allow" permission, the button will read
"Set" and will set the permission to "Allow" for all selected
streams.
After selecting two streams (or dashboards) in the Edit Role
view, two buttons appeared in the header of the table.
"Toggle read permissions" and "Toggle edit permissions"
which would invert the permissions of a selected streams.
The user would rather set or clear the permissions of the
selected streams.
Fixes #3210
=> Change Permission Buttons from Toggle to Set and Clear

graylog2-server/src/main/java/org/graylog2/rest/resources/system/authentication/AuthenticationResource.java, graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java
These changes allow the UI to request information about the auth realms without requiring a global permission to do so.
Each realm is check individually, and a user without any access to them gets an empty set instead of a permission error.
This allows the UI to avoid special handling for users editing their own profile information.
Also include the new authentication permissions in the meta resource.
This requires backporting to 2.4 once reviewed.
fixes #4420 
fixes #4442
=> Check auth realm access on instance level

graylog2-web-interface/npm-shrinkwrap.json
Due to a reflux peer dependency problem with react, we ran into an error
and couldn't create a shrinkwrap file for the 2.4.0 release in December.
We now ran into a compatibility problem with a plugin because of changed
dependencies and I tried to create a shrinkwrap file again. It worked
after manually modifying the react peer dependency in the installed
reflux module.
To make sure we have the correct dependency versions from the time of
the 2.4.0 release build, I used the Jenkins workspace directory - which
luckily still existed - to create the npm-shrinkwrap.json file.
=> Create npm-shrinkwrap.json files for the 2.4.0 release

graylog2-server/src/main/java/org/graylog2/rest/resources/system/authentication/AuthenticationResource.java, graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java
* include authentication permissions in meta resource
fixes #4442
* filter authentication provider information by realm names
instead of requiring a global permission, apply the permission check to each
realm to be returned.
this makes it possible to assign more finely grained access, but more importantly
allows the call to succeed even if the user cannot see any realm configuration
in that case the set is merely empty, but it is not a permission violation
this allows users to edit their own profile again
fixes #4420
(cherry picked from commit 5a4376dcae4f84e6e61ce736ecb948825faa1493)
=> Check auth realm access on instance level (#4488)

graylog2-web-interface/src/stores/search/SearchStore.test.jsx, graylog2-web-interface/src/stores/search/SearchStore.ts
The add search term button (eg. in the Quick Values view)
is adding search terms to the search bar. A search term
with spaces will be treated as a phrase and therefor will
only surrounded by double quotes. But those phrases did
not escape backslashes which is still needed to perform
the search.
Now phrases will also get the backslashes escaped.
Also: Add some tests for adding a search term.
Fixes #4111
=> Fix Backslash Escaping for Phrase Searches

graylog2-server/src/main/java/org/graylog2/shared/metrics/MetricUtils.java, graylog2-server/src/test/java/org/graylog2/shared/metrics/MetricUtilsTest.java
Lambda expressions in Java 8+ are synthetic classes and return that synthetic class when `#getClass()` is being used, so the "type discovery" in `MetricUtils#map()` didn't work as expected.
Also see https://stackoverflow.com/questions/16827262/how-will-java-lambda-functions-be-compiled and https://gist.github.com/dgageot/5840050 for an example.
Fixes #4493
=> Add support for Java 8 lambda expressions to MetricUtils#map()

graylog2-web-interface/package.json, graylog2-web-interface/src/components/widgets/Widget.jsx, graylog2-web-interface/src/components/widgets/Widget.test.jsx, graylog2-web-interface/src/components/widgets/WidgetFooter.jsx, graylog2-web-interface/src/components/widgets/WidgetFooter.test.jsx, graylog2-web-interface/src/components/widgets/__snapshots__/WidgetFooter.test.jsx.snap, graylog2-web-interface/test/helpers/mocking/c3_mock.jsx, graylog2-web-interface/test/setup-jest.jsx
A widget on a dashboard has a play button which directs the
user to the search on which the widget is based on.
If the user had no permission to look on the streams (no read
permission on the stream) he got the message:
'The stream is not available, cannot replay search.'
Some user thought that the button was broken, since they assumed
to trigger a update with this button.
To fix the problem we remove the button for users without
the necessary permissions.
Fixes #4120 
Fixes #1874
The tests generate snapshots which i diffed manually to ensure that
the expected result was rendered.
=> Hide replay button if user has no permission

graylog2-web-interface/README.md, graylog2-web-interface/devServer.js
Looking into the development server for the web interface, we saw that it was listening to all interfaces by default, so this PR changes that behaviour by:
- Using localhost as default
- Adding `--host` option to change the default host where the server should listen
- Documenting changes in README file
=> Allow customization of dev server host

graylog2-web-interface/src/components/dashboard/AddToDashboardMenu.jsx, graylog2-web-interface/src/components/dashboard/AddToDashboardMenu.test.jsx, graylog2-web-interface/src/stores/dashboards/DashboardsStore.js
This PR ensures users can only see dashboards with write permissions in the add to dashboard menu. Additionally it makes the state in `DashboardsStore.list()` consistent by using ImmutableJS in all its properties, and it ensures the permissions in `DashboardsStore` are set when the store is first initialized. I also added a couple of tests, to ensure all cases are doing what they should.
Fixes #4504
=> Only display dashboards with write permissions in add to dashboard menu

graylog2-web-interface/src/components/messageloaders/RecentMessageLoader.jsx
The RecentMessageLoader component is trying to limit the range of the
search request it used to get the last received message of an input to
the last hour. For this, it uses the `range` parameter. This is the
correct parameter name for the backend, but the web interface uses a
small conversion helper that expects the parameter to be named
`relative` for relative time ranges, according to the naming in the old
web interface.
To make the fix as small as possible for a point release, this change
just uses the `relative` parameter. For `master` and subsequent releases
we should either switch over to the `range` parameter or use it in case
the `relative` parameter is not present. This way we do not discourage
consumers of the `UniversalSearchStore` to use the actually correct
parameter naming. …
=> Fixing relative time range used by RecentMessageLoader.

graylog2-web-interface/src/components/field-analyzers/FieldQuickValues.jsx, graylog2-web-interface/src/components/visualizations/QuickValuesVisualization.jsx, graylog2-web-interface/src/stores/search/SearchStore.ts
In certain scenarios the timestamp field was not properly formatted when being used in stacked quickvalues.
If the timestamp field wasn't the first field of the stack, it failed to be formatted.
Additionally, adding it to the query either dropped later fields or misconverted the timezone.
Widget rendering was also affected, although there it cannot be added to a search query so the "Add to query" issue did not happen.
fixes #4509
=> Properly handle timestamp field in stacked quickvalues

graylog2-server/src/main/java/org/graylog2/plugin/Message.java
The `Message#isComplete()` function checks whether all mandatory message fields exist and aren't empty.
This change set adds useful debugging information on TRACE level about missing or empty mandatory fields.
Refs https://community.graylog.org/t/filebeat-logs-dropped-out/3929
=> Log reason for message being incomplete on TRACE

graylog2-web-interface/package.json, graylog2-web-interface/packages/graylog-web-plugin/package.json, graylog2-web-interface/packages/graylog-web-plugin/yarn.lock, graylog2-web-interface/src/components/common/TimezoneSelect.jsx, graylog2-web-interface/src/stores/tools/FocusStore.jsx, graylog2-web-interface/yarn.lock
Also bump dependencies relying on jQuery (currently only toastr has a new bugfix version).
As this is a long version jump and there are many changes in jQuery as you can see in the release notes for [3.0](https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/), [3.1](https://blog.jquery.com/2016/07/07/jquery-3-1-0-released-no-more-silent-errors/), [3.2](https://blog.jquery.com/2017/03/16/jquery-3-2-0-is-out/), and [3.3](https://blog.jquery.com/2018/01/19/jquery-3-3-0-a-fragrant-bouquet-of-deprecations-and-is-that-a-new-feature/).
Fortunately for us, 3.0 was developed with backwards compatibility in mind, so most of the changes that affect us are deprecations. On the other hand, most of the jQuery code we run is coming through 3rd party plugins, so we may have some problems to get …
=> Upgrade jQuery to 3.3.1

graylog2-web-interface/src/components/lookup-tables/DataAdapterCreate.jsx, graylog2-web-interface/src/components/lookup-tables/DataAdapterCreate.test.jsx, graylog2-web-interface/src/components/lookup-tables/__snapshots__/DataAdapterCreate.test.jsx.snap, graylog2-web-interface/test/helpers/mocking/MockComponent.jsx
If a data adapter is missing a frontend component definition, before
this change the data adapter creation page broke.
This change checks if the definition is there and if not the data
adapter type is disabled in the creation dialog and an error message is
logged.
Fixes #4528.
=> Disable data adapters in creation dialog missing frontend components.

graylog2-server/src/main/java/org/graylog2/lookup/caches/GuavaLookupCache.java, graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupCache.java, graylog2-web-interface/src/components/lookup-tables/CacheTableEntry.jsx
The way the `LookupCache#entryCount()` method signature was defined, caused implementers to write incorrect implementations.
For example `GuavaLookupCache#entryCount()` returned a constant `Gauge<Long>` on the first call (in the constructor of `LookupCache`) which was never updated.
The signature of `LookupCache#entryCount()` has been changed to prevent such incorrect usages and implementations by simply returning a `long` value and adding a dynamic `Gauge<Long>` in the constructor of `LookupCache`.
Additionally, the `CacheTableEntry` tried to access the entry count metric through an invalid object path which resulted in the metric always being displayed as "NaN" in the web interface.
Fixes #4540
=> Fix entry count metric for lookup caches

graylog2-server/src/main/java/org/graylog2/shared/security/ShiroSecurityContext.java, graylog2-server/src/main/java/org/graylog2/shared/security/ShiroSecurityContextFilter.java, graylog2-server/src/test/java/org/graylog2/shared/security/ShiroSecurityContextFilterTest.java
`ShiroSecurityContextFilter` incorrectly parsed the HTTP Basic Auth header and prevented users from using the colon character (":") in their passwords.
Refs https://community.graylog.org/t/graylog-behind-nginx-sub-directory-how-to-configure/3968
=> Allow using colon character (":") in password

graylog2-web-interface/src/pages/EditExtractorsPage.jsx
We recently fixed an issue in the RecentMessageLoader component to ensure the search of an example is restricted to the last hour (#4510). This change does the same for the edit extractor page.
Fixes #4553
The change should also be backported into 2.4.
=> Restrict search in edit extractor example

UPGRADING.rst
Users who use a proxy setup and are upgrading to 3.0 need to adjust the `X-Graylog-Server-URL` HTTP header config.
=> Add upgrading note for proxy setups using X-Graylog-Server-URL

graylog2-server/src/test/java/org/graylog2/ApacheDirectoryTestServiceFactory.java, graylog2-server/src/test/java/org/graylog2/security/ldap/LdapConnectorTest.java, graylog2-server/src/test/java/org/graylog2/security/realm/LdapUserAuthenticatorTest.java
The default LDAP server factory creates a storage location based on the CreateDS annotation name. This led to sporadic test failures in our CI environment when running the same job in parallel.
Example failure:
```
2018-02-02 11:51:34,106 ERROR: org.apache.directory.server.core.integ.FrameworkRunner - ERR_181 Failed to run the class org.graylog2.security.realm.LdapUserAuthenticatorTest
2018-02-02 11:51:34,108 ERROR: org.apache.directory.server.core.integ.FrameworkRunner - java.io.FileNotFoundException: /tmp/server-work-LdapUserAuthenticatorTest/partitions/system/2.5.4.0.lg (No such file or directory)
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 24.402 sec <<< FAILURE! - in org.graylog2.security.realm.LdapUserAuthenticatorTest …
```
=> Use a unique LDAP server storage location in tests

graylog2-web-interface/src/pages/EditExtractorsPage.jsx
We recently fixed an issue in the RecentMessageLoader component to
ensure the search of an example is restricted to the last hour. This
change does the same for the edit extractor page.
Fixes #4553
(cherry picked from commit 4e89b70b256079868ff7c496d493ffc7c3fcffad)
=> Restrict search in edit extractor example (#4554)

graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java, graylog2-server/src/main/java/org/graylog2/shared/security/Permissions.java, graylog2-server/src/test/java/org/graylog2/shared/security/PermissionsTest.java, graylog2-server/src/test/java/org/graylog2/users/UserServiceImplTest.java, graylog2-web-interface/src/components/authentication/AuthenticationComponent.jsx, graylog2-web-interface/src/components/common/TableList.jsx, graylog2-web-interface/src/components/users/PermissionSelector.test.jsx, graylog2-web-interface/src/components/users/TokenList.css, graylog2-web-interface/src/components/users/TokenList.jsx, graylog2-web-interface/src/components/users/TokenList.test.jsx, graylog2-web-interface/src/components/users/UserList.css, graylog2-web-interface/src/components/users/UserList.jsx, graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap, graylog2-web-interface/src/pages/EditTokensPage.jsx, graylog2-web-interface/src/routing/ApiRoutes.js, graylog2-web-interface/src/routing/AppRouter.jsx, graylog2-web-interface/src/routing/Routes.jsx, graylog2-web-interface/src/stores/users/UsersStore.ts, graylog2-web-interface/test/helpers/mocking/react-dom_mock.js
API Tokens are configurable via REST API but there is till now no way to
create, delete or list them in the web interface.
- I fixed the permissions handling for API Tokens which till now only worked, if the user requested his own tokens regardless of his role (like admin). That meant that even the admin could not alter the API Tokens. Now a normal user can only manage his own Tokens and a user with role *admin* can manage the tokens of other people additionally.
- Add a new TokenList Component which list, create and deletes tokens. I did not wire the UserStore into that component but rather gave handlers as arguments and implemented them by the caller. This is easier to test and easier to use IMHO.
To use tokens a user needed to use the REST API manually to create delete or list
them.
I …
=> Make API Tokens configurable in web interface

graylog2-web-interface/package.json, graylog2-web-interface/public/stylesheets/graylog2.less, graylog2-web-interface/src/components/common/ControlledTableList.jsx, graylog2-web-interface/src/components/common/ControlledTableList.md, graylog2-web-interface/src/components/common/ControlledTableListHeader.css, graylog2-web-interface/src/components/common/ControlledTableListHeader.jsx, graylog2-web-interface/src/components/common/ControlledTableListItem.jsx, graylog2-web-interface/src/components/common/TableList.css, graylog2-web-interface/src/components/common/TableList.jsx, graylog2-web-interface/src/components/common/TableList.md, graylog2-web-interface/src/components/common/index.jsx, graylog2-web-interface/src/components/users/PermissionSelector.jsx, graylog2-web-interface/src/components/users/TokenList.jsx, graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap, graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap, graylog2-web-interface/yarn.lock
This PR aims to fix some shortcomings on the `TableList` component. We need to do those in order to reuse the component in the new collector UI and to fix some old usability issues that have been there for a while now. These are the main changes:
- Introduce `ControlledTableList` component, that allows more flexibility to consumers that only want the basis of a `TableList` but nothing else. This component is now used by `TableList` itself
- Improve feedback when selecting one or more elements in the list to perform bulk actions
- Update selection when filter changes
- Update filtered items and selection when `items` prop changes
- Make bulk actions optional, by adding an `enableBulkActions` prop
- Simplify how to disable filtering, by adding an `enableFilter` prop
=> TableList improvements

graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupCacheKey.java, graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupResult.java, graylog2-server/src/test/java/org/graylog2/plugin/lookup/LookupResultTest.java
This commit adds a factory method to `LookupResult` which can be used by Jackson to deserialize an instance of `LookupResult` from JSON.
Additionally, the derived field "empty" (via `LookupResult#isEmpty()`) is being ignored and thus not part of the serialized or deserialized representation of `LookupResult`.
Fixes #4534
=> Add JSON factory method for `LookupResult`

graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupCacheKey.java, graylog2-server/src/test/java/org/graylog2/plugin/lookup/LookupCacheKeyTest.java
The derived `isPrefixOnly()` method should be ignored when the `LookupCacheKey` instance is being serialized.
Otherwise deserialization will fail due to the unknown "prefix_only" field.
=> Ignore `LookupCacheKey#isPrefixOnly()` when (de-) serializing with Jackson

graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java, graylog2-server/src/main/java/org/graylog2/users/UserImpl.java, graylog2-web-interface/src/components/search/MessageDetail.jsx, graylog2-web-interface/src/components/search/MessageField.jsx, graylog2-web-interface/src/components/search/MessageFieldDescription.jsx, graylog2-web-interface/src/components/search/MessageFields.jsx, graylog2-web-interface/src/components/search/MessageShow.jsx, graylog2-web-interface/src/components/search/MessageTableEntry.css, graylog2-web-interface/src/components/search/MessageTableEntry.jsx, graylog2-web-interface/src/components/search/MessageTableEntry.test.jsx, graylog2-web-interface/src/components/search/__snapshots__/MessageTableEntry.test.jsx.snap, graylog2-web-interface/src/logic/datetimes/DateTime.js
Display timestamps on the search page in the timezone of the user. The timezone of the user
is either the user setting or the timezone of the browser.
Additionally make it possible for a user to unset his timezone setting so the Graylog gui
can use the browser timezone.
The user saw timestamps in UTC even though he set his browser and user setting to
his timezone.
Started browser in timezone US Pacific with:
TZ="US/Pacific" google-chrome "--user-data-dir=$HOME/chrome-profile"
Set and unset the timezone of the user.
Partially Fixes #2689 
For the CSV Export I'll open an other issue.
=> Display Timestamp in User Timezone

graylog2-web-interface/webpack.combined.config.js
With a higher number (>5) of plugins in development, running yarn start takes
significant time during the globbing step which finds all webpack configs of
the installed plugins.
By using better glob options (ignoring the `node_modules` directories of
installed plugins and setting the working directory of the glob
explicitly instead of implicitly by including it in the glob pattern),
we are able to reduce globbing times by the factor of 100.
I wrote a small script[1] to compare the times for both options, its
results are (on my machine):
```
glob: 53.336s
glob w/ ignoring + cwd: 0.581s
```
[1]: https://gist.github.com/dennisoelkers/682b8fd25233ec0d2df03107b929e860
=> Reduce development startup time by improving globbing.

graylog2-server/src/main/java/org/graylog2/rest/models/system/ldap/requests/LdapSettingsRequest.java, graylog2-server/src/main/java/org/graylog2/rest/models/system/ldap/responses/LdapSettingsResponse.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/ldap/LdapResource.java, graylog2-server/src/main/java/org/graylog2/security/ldap/LdapSettingsImpl.java, graylog2-server/src/main/java/org/graylog2/shared/security/ldap/LdapSettings.java, graylog2-web-interface/src/components/ldap/LdapComponent.css, graylog2-web-interface/src/components/ldap/LdapComponent.jsx
The ldap configuration page was setting the input value of the
password field to the actuall password.
This change prevents reading the password via "inspect" in browser,
by hiding the password input field and instead show a string "Password is set".
If the user wants to set a new password he now needs to click the "Reset Password" button.
There is now no way anymore to clear the password anymore, since we drop empty
passwords now. That is needed since the GUI does not receive and therefore cannot send
the password any longer.
A attacker could read the ldap password, if he gained admin access to graylog.
Password set and updated and checked via inspect.
Fixes #3763
=> Prevent ldap server password leak

graylog2-web-interface/yarn.lock
The `yarn.lock` file needs an update after several plugins have been merged into the server.
=> Sync yarn.lock after plugin merges

graylog2-server/src/main/java/org/graylog/plugins/beats/Beats2Codec.java, graylog2-server/src/main/java/org/graylog/plugins/beats/Beats2Input.java, graylog2-server/src/main/java/org/graylog/plugins/beats/BeatsCodec.java, graylog2-server/src/main/java/org/graylog/plugins/beats/BeatsInput.java, graylog2-server/src/main/java/org/graylog/plugins/beats/BeatsInputPluginModule.java, graylog2-server/src/main/java/org/graylog/plugins/beats/MapUtils.java, graylog2-server/src/test/java/org/graylog/plugins/beats/Beats2CodecTest.java, graylog2-server/src/test/java/org/graylog/plugins/beats/Beats2InputDescriptorTest.java, graylog2-server/src/test/java/org/graylog/plugins/beats/BeatsCodecTest.java, graylog2-server/src/test/java/org/graylog/plugins/beats/BeatsInputDescriptorTest.java, graylog2-server/src/test/java/org/graylog/plugins/beats/LegacyConsolePrinter.java, graylog2-server/src/test/java/org/graylog/plugins/beats/MapUtilsTest.java
Instead of changing the behavior of the old Beats input (`BeatsCodec`), this change set reverts the changes of Graylog2/graylog-plugin-beats#29 and creates a new input ( `Beats2Input`, `Beats2Codec`) instead.
This way, existing users don't need to change anything and new users can use the new Beats input with the improved field handling introduces in Graylog2/graylog-plugin-beats#29.
Closes Graylog2/graylog-plugin-beats#33
=> Retain legacy behavior of Beats input

graylog2-web-interface/src/components/common/ReactGridContainer.css, graylog2-web-interface/src/components/common/ReactGridContainer.jsx
This PR makes some modifications in the web interface to be smarter calculating and updating dashboard positions:
1. Avoid callbacks when clicking on an action button in a widget. This is what made #4525 too likely to happen
2. Only compute layout when positions change, instead of doing it on every render
3. Ensure there are layout changes before calling the `onLayoutChange` callback, avoiding doing unnecessary updates in the server
In order to fix the issue in 2.4, I think we should only backport change number 1, avoiding to introduce any other potential issues in the stable release. I can take care of that once this PR is reviewed.
Before a solution for #4527 lands, these changes fix #4525.
=> Only update dashboard positions when necessary

pom.xml
This updates netty to the latest 4.1.x release.
I ran this in my test setup with NetFlow, Beats and GELF inputs for about 18 hours and didn't run into any issues.
- http://netty.io/news/2018/01/22/4-0-55-Final-4-1-20-Final.html
- http://netty.io/news/2018/02/05/4-0-56-Final-4-1-21-Final.html
- http://netty.io/news/2018/02/21/4-1-22-Final.html
=> Update to netty-4.1.22

UPGRADING.rst, graylog2-server/src/main/java/org/graylog/plugins/map/MapWidgetModule.java, graylog2-server/src/main/java/org/graylog/plugins/map/rest/MapDataResource.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/PipelineProcessorModule.java, graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java, graylog2-server/src/main/java/org/graylog2/plugin/inject/Graylog2Module.java, graylog2-server/src/main/java/org/graylog2/plugin/inject/RestControllerPackage.java, graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java, graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationResource.java, graylog2-web-interface/src/routing/ApiRoutes.js, graylog2-web-interface/src/stores/maps/MapsStore.js, graylog2-web-interface/src/stores/pipelines/PipelineConnectionsStore.js, graylog2-web-interface/src/stores/pipelines/PipelinesStore.js, graylog2-web-interface/src/stores/rules/RulesStore.js, graylog2-web-interface/src/stores/simulator/SimulatorStore.js
This moves the REST resources of the pipeline-processor and map-widget code out of the `/plugins/<package-name>` namespace into the regular server namespace.
The UI code has been adjusted and new entries in `ApiRoutes.js` created.
=> Move pipeline-processor and map-widget REST resources out of /plugins prefix

graylog2-web-interface/package.json, graylog2-web-interface/src/components/common/SelectPopover.css, graylog2-web-interface/src/components/common/SelectPopover.jsx, graylog2-web-interface/src/components/common/SelectPopover.md, graylog2-web-interface/yarn.lock
This PR introduces a `SelectPopover` component that we want to use on actions and filters in `TableList` components:
Some features of this component:
- Customise how to display elements via a function
- Consumers of this component can control its selected item and get notified when it changes
- Optional text filter element
- Scrollable list if there are more than 10 items
=> Add SelectPopover component

graylog2-server/src/main/java/org/graylog2/shared/utilities/ByteBufferUtils.java, graylog2-server/src/test/java/org/graylog2/shared/utilities/ByteBufferUtilsTest.java
The `ByteBufferUtils#readBytes(ByteBuf, int, int)` method failed for non-array-backed byte buffers whose reader index didn't start at index 0 and failed to mention side effects (e. g. consumption of the given `ByteBuffer`) in the Javadocs.
Additionally, the "optimization" in `ByteBufferUtils#readBytes(ByteBuf, int, int)` was unnecessary because the relevant `ByteBuffer` implementations are already using the backing array if available.
=> Simplify `ByteBufferUtils#readBytes()`, document side-effects, add tests

graylog2-web-interface/package.json, graylog2-web-interface/src/components/common/ColorPicker.jsx, graylog2-web-interface/src/components/common/ColorPicker.md, graylog2-web-interface/src/components/common/ColorPickerPopover.css, graylog2-web-interface/src/components/common/ColorPickerPopover.jsx, graylog2-web-interface/src/components/common/ColorPickerPopover.md, graylog2-web-interface/src/components/common/SelectPopover.css, graylog2-web-interface/src/components/common/SelectPopover.jsx, graylog2-web-interface/src/components/common/index.jsx, graylog2-web-interface/yarn.lock
This PR adds two colour picker components: `ColorPicker` and `ColorPickerPopover`. The first one is meant to display a colour picker in a UI with space and where displaying a list of colours would not be distracting. The latter is meant to use in UIs with less space, allowing the user to show or hide the colour picker by hovering or clicking in a trigger.
Additionally I added a couple of small fixes for the `SelectPopover` component, which would be a small change to create (and review) another PR.
=> Add colour picker components

graylog2-web-interface/src/components/common/DataTable.jsx
Responsive tables may clip dropdowns or other elements that overflow the container vertically, so this may not be something we want to use everywhere. The `useResponsiveTable` prop let us disable the responsive styles if we display dropdowns inside the table, or if the table is not expected to be too wide.
More information on `table-responsive`:
https://getbootstrap.com/docs/3.3/css/#tables-responsive
=> Let user of DataTable control if table is responsive

graylog2-server/src/main/java/org/graylog2/streams/StreamFaultManager.java, graylog2-web-interface/src/logic/notifications/NotificationsFactory.js
I add the stream title to the message to clearify which stream
is meant.
If a stream timesout to match a rule it will be shoutdown by
graylog leading to a notification for the user.
This notification only showed the stream id which was not
very helpful.
I let the notification be seen by hand.
=> Add stream title to notification

graylog2-server/pom.xml
To make sure the shade plugin runs before the assembly plugin in the
package phase, we have to move the assembly plugin definition after the
shade plugin definition in pom.xml.
=> Create assembly in package phase automatically

graylog2-server/pom.xml
To make sure the shade plugin runs before the assembly plugin in the
package phase, we have to move the assembly plugin definition after the
shade plugin definition in pom.xml.
(cherry picked from commit afa248bcb26eef902b41e2b34aaea1a1593d7ce2)
=> Create assembly in package phase automatically (#4644)

graylog2-web-interface/src/stores/widgets/WidgetsStore.ts, graylog2-web-interface/tsconfig.json
Before this change, ts-loader/tsc just included the node types
explicitly. This lead to problems with duplicate inclusions for plugins
which transitively depend on typings.
This PR changes this behavior to the more standard one of defining which
types to include instead of including the types file explicitly.
=> Fix the way TypeScript loads type definitions.

graylog-project-parent/pom.xml, pom.xml
The Cobertura Maven plugin (and Cobertura itself) doesn't support Java 8.
Additionally, code coverage metrics are currently not used anywhere in the build, so we can as well remove it.
Refs mojohaus/cobertura-maven-plugin#21
Refs cobertura/cobertura#166
=> Remove Cobertura Maven plugin

graylog2-server/src/test/java/org/graylog2/configuration/HttpConfigurationTest.java
Some tests of the HttpConfigurationTest suite keep on failing
unpredictably and have proven to be unreliable, causing the need to
manually restart tests on Travis or Jenkins.
(See https://travis-ci.org/Graylog2/graylog2-server/builds/352299567 as
an example)
Therefore, this PR disables these tests until they are fixed.
=> Disable unreliable tests.

graylog2-web-interface/src/components/common/ReactGridContainer.jsx
Before this change, it was only possible to move a widget by clicking
somewhere in the widget and drag it. For some use cases it is desirable
to have a fixed handle which allows dragging the widget. This PR allows
passing a CSS class which acts as drag handle.
=> Support drag handles in ReactGridContainer.

graylog-project-parent/pom.xml, graylog2-server/pom.xml
When running (Java) tests via Surefire or Failsafe, the window focus on Mac OS X is regularly "stolen" by a process named "ForkedBooter".
This change set adds parameters to the Maven Surefire and Failsafe plugins which start the JVM in headless mode and which prevent the "ForkedBooter" process from stealing the window focus on Mac OS X.
See also:
* https://somethingididnotknow.wordpress.com/2014/07/23/forkedbooter-steals-window-focus-on-mac-os-while-maven-is-running/
* https://apple.stackexchange.com/questions/100069/when-terminal-forks-process-current-app-loses-focus
=> Prevent ForkedBooter process from stealing window focus on Mac OS

graylog2-web-interface/src/routing/AppRouter.jsx
During initialization of the `AppRouter`, plugin routes are added by
iterating over a collection. During this step, `Route` components are
generated with a `key` based on the `displayName` property of a component,
which is `undefined` or non-unique in some cases.
This emits a warning generated by react and is prone to collisions preventing
individual routes to take effect.
This change is generating a key for each `Route` component consisting of
the plugin route component's `displayName` and its `path`. At least the
latter should be unique (otherwise one of the routes is shadowed
anyway).
=> Adding keys to plugin routes.

graylog-project-parent/pom.xml, graylog2-server/pom.xml, graylog2-server/src/main/java/org/graylog2/rest/models/PaginatedResponse.java, graylog2-server/src/test/java/org/graylog2/rest/models/PaginatedResponseTest.java, pom.xml
Don't put the pagination info inside a "data" object in the response.
For some reason JsonUnwrapped didn't work as expected.
=> Fix JSON serialization of PaginatedResponse

graylog2-web-interface/public/stylesheets/graylog2.less
After merging graylog-web interface into the server and React rewrite, the main navbar is not wrapped in `div#navigation-bar` anymore, so those CSS rules don't match. This triggers the default bootstrap rules with bigger font (14px vs 12px) and smaller paddings.
I've been in a long-term relationship with Graylog, so the first thing I noticed when we were finally able to upgrade, was the different dropdown appearance... this will make it beautiful again.
=> Fixed CSS rules for main-nav dropdown

graylog2-web-interface/src/stores/connect.jsx, graylog2-web-interface/src/stores/connect.test.jsx
This generator allows ES6 class components to be connected to stores,
although the current version of Reflux allows this only using a mixin,
which is not usable for ES6 classes.
The change provides a `connect()` function which takes the supplied
component class and wraps it in a generated component which connects
itself to the stores defined in the provided mapping. The state supplied
by the stores is then passed to the component as props.
=> Add HOC generator connecting ES6 class components to stores.

graylog2-web-interface/src/components/common/PaginatedList.jsx
Previously there was no way to control the active page from outside the component.
This also cleans up some strange code from the automatic create-react-class conversion and fixes some eslint errors.
=> Add activePage prop to PaginatedList.jsx

UPGRADING.rst, graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java, graylog2-server/src/main/java/org/graylog2/commands/journal/AbstractJournalCommand.java, graylog2-server/src/main/java/org/graylog2/commands/journal/JournalShow.java, graylog2-server/src/main/java/org/graylog2/configuration/ExposedConfiguration.java, graylog2-server/src/main/java/org/graylog2/configuration/PathConfiguration.java, graylog2-server/src/main/java/org/graylog2/plugin/BaseConfiguration.java, graylog2-server/src/main/java/org/graylog2/plugin/KafkaJournalConfiguration.java, graylog2-server/src/main/java/org/graylog2/shared/journal/KafkaJournal.java, graylog2-server/src/main/java/org/graylog2/shared/system/stats/fs/JmxFsProbe.java, graylog2-server/src/main/java/org/graylog2/shared/system/stats/fs/SigarFsProbe.java, graylog2-server/src/test/java/org/graylog2/configuration/ExposedConfigurationTest.java, graylog2-server/src/test/java/org/graylog2/shared/journal/KafkaJournalTest.java, misc/graylog.conf
The `data_dir` config setting can be usd by Graylog subsystems to store data instead of creating separate config settings for that.
Closes #2057
=> Add "bin_path" and "data_dir" settings

graylog2-web-interface/src/components/common/SelectPopover.jsx
- Fixes a bug in condition that updates the selected item when its prop changes
- Adds a disabled prop, that controls whether items in the SelectPopover are clickable or not
=> SelectPopover improvements

graylog2-web-interface/src/components/common/PaginatedList.jsx
This fixes a long standing issue with the SearchForm component where the query string disappears when a search doesn't return any results.
The problem was that we had a shortcut in the render function that returned only the children and no page selectors when there are no items to show. This apparently changed the DOM structure in a way that the children of the PaginatedList component have been replaced with new instances.
In the case of a SearchForm component as a PaginatedList child, this reset the query string.
=> Avoid DOM structure changes when there are no pages to show

graylog2-web-interface/src/components/common/SearchForm.jsx, graylog2-web-interface/src/components/common/SearchForm.md
- Fix eslint errors and fix deprecation warnings
- Fix potential race condition with the loading state update
- Don't reset loading indicatorin `componentWillReceiveProps()`. This fixes an issue where the loading indicator never showed up.
- Convert the query string input to a controlled component and add `query` and `onQueryChange` props
=> Some SearchForm.jsx improvements and fixes

graylog2-web-interface/src/components/common/ExpandableList.css, graylog2-web-interface/src/components/common/ExpandableList.jsx, graylog2-web-interface/src/components/common/ExpandableList.md, graylog2-web-interface/src/components/common/ExpandableList.test.jsx, graylog2-web-interface/src/components/common/ExpandableListItem.css, graylog2-web-interface/src/components/common/ExpandableListItem.jsx, graylog2-web-interface/src/components/common/__snapshots__/ExpandableList.test.jsx.snap, graylog2-web-interface/src/components/common/index.jsx
This change adds **ExpandableList** and **ExpandableListItem** from the enterprise plugin.
It also supplies documentation and tests for the components.
These components are needed for content selection in Content Pack.
I add new tests, and ensured that the reports content selection still worked.
=> Move expanded list from enterprise to server

graylog2-server/src/test/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransportTest.java
A test of the `AbstractTcpTransportTest` suite keeps failing, which is
now disabled until it is fixed.
(See https://jenkins.torch.sh/job/graylog2-server/1655/console as
an example)
=> Disabling unreliable AbstractTcpTransportTest test case.

graylog2-web-interface/src/components/common/SelectPopover.jsx
When `SelectPopover` is used as a single-option select, clicking on a selected option will deselect it (aka toggle it's select status). That behaviour is not consistent with other selects we use, and also doesn't provide much value (since we already have an option to clear the selection).
This PR changes that behaviour by treating a click on a selected option in the same way as a click in a not-selected option.
On multiselects, it is still possible to deselect a single selected option by clicking on it.
=> Change select behaviour in SelectPopover

graylog2-web-interface/src/components/common/ReactGridContainer.jsx
This PR introduces a new prop for the `ReactGridContainer` component
named `measureBeforeMount`, which is passed to the WidthProvider HOC. It
triggers that the width of the grid is measured before any widgets are
rendered, so the grid is initialized initially with the correct width
(instead of defaulting to 1280 for the first render).
Without using the prop, it defaults to `false` which was the case
before, so no existing code is affected by it.
=> Allow passing measureBeforeMount to ReactGridContainer.

graylog2-web-interface/src/util/UserNotification.js
Ensure text in notifications is properly escaped by toastr.
These changes should be backported into 2.4.
=> Properly escape text in toastr

graylog2-web-interface/src/pages/EditTokensPage.jsx
This PR is fixing a small typo in the prop types of the `EditTokensPage` component.
=> Fixing typo in proptypes.

graylog2-server/src/main/java/org/graylog2/search/SearchQueryField.java, graylog2-server/src/main/java/org/graylog2/search/SearchQueryParser.java, graylog2-server/src/test/java/org/graylog2/search/SearchQueryParserTest.java
This PR adds support for querying `int` values in `SearchQuery`, and adapts the default search operator, so that users can still find `int` and `Date` values even if they don't specify an operator.
With the changes, these are the default operators:
- `foo` -> Behaves like before the changes
- `string_field:foo` -> Behaves like before the changes
- `int_field:0` -> Uses an `equals` operator to find `0` in `int_field`
- `date_field:2018-04-18T12:15:00Z` -> Uses an `equals` operator to find `2018-04-18T12:15:00Z` in `date_field`
=> Add support for int values in SearchQuery

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/GrokMatch.java, graylog2-server/src/main/java/org/graylog2/grok/GrokPatternRegistry.java, graylog2-server/src/main/java/org/graylog2/grok/InMemoryGrokPatternService.java, graylog2-server/src/main/java/org/graylog2/grok/MongoDbGrokPatternService.java, graylog2-server/src/main/java/org/graylog2/inputs/extractors/GrokExtractor.java, graylog2-server/src/main/java/org/graylog2/plugin/Message.java, graylog2-server/src/main/java/org/graylog2/rest/resources/tools/GrokTesterResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/tools/responses/GrokTesterResponse.java, graylog2-server/src/test/java/org/graylog2/grok/GrokPatternRegistryTest.java, graylog2-server/src/test/java/org/graylog2/inputs/extractors/GrokExtractorTest.java, graylog2-server/src/test/java/org/graylog2/plugin/MessageTest.java, graylog2-server/src/test/java/org/graylog2/rest/resources/tools/GrokTesterResourceTest.java, graylog2-web-interface/src/components/extractors/extractors_configuration/GrokExtractorConfiguration.jsx, pom.xml
If a Grok pattern couldn't be resolved, the java-grok library emitted an error message which didn't include the name of the missing pattern.
After upgrading to the latest version of (our repackaged) java-grok, the error message includes the name of the missing Grok pattern to help users to solve the problem.
Fixes #3949
=> More detailed error message for missing Grok patterns

graylog-plugin-parent/pom.xml
This ensures that a "mvn clean" removes the `node_modules` folder in all plugins.
=> Cleanup node_modules in plugins like we do in the main web interface

graylog2-web-interface/src/components/dashboard/Dashboard.jsx, graylog2-web-interface/src/components/dashboard/EditDashboardModal.jsx, graylog2-web-interface/src/pages/ShowDashboardPage.jsx
Handle editing of dashboard title and description through React and Reflux, avoiding to use jquery for that task.
This change needs to be back-ported into 2.4.
=> Set dashboard title and description with React

graylog2-server/src/main/java/org/graylog2/decorators/DecoratorBindings.java, graylog2-server/src/main/java/org/graylog2/decorators/LinkFieldConverter.java, graylog2-server/src/main/java/org/graylog2/decorators/LinkFieldDecorator.java, graylog2-web-interface/src/components/search/MessageFieldDescription.jsx
This PR allows graylog to have hyperlinked search result fields. A user can create a decorator for a field that they want to allow to be a hyperlink.
Closes this issue/feature request: https://github.com/Graylog2/graylog2-server/issues/1914
I built graylog via `mvn compile`
I then ran the frontend and backend servers.
Tested saving config with several fields, not fields, etc.
Made sure that the search page details rendered accordingly.
=> Adding hyperlinked fields in search result details

graylog2-server/src/main/java/org/graylog2/bindings/providers/JestClientProvider.java, graylog2-server/src/main/java/org/graylog2/indexer/cluster/jest/GraylogJestRetryHandler.java, pom.xml
we include all SocketExceptions in the list of retriable errors
this way we will always pick a new server from the list when
there's underlying issues
simply retrying the HTTP request against the same server makes little
sense in a cluster, so we disable that in favor of picking a new host
requires unreleased Jest client (2.4.12-jackson)
=> Disable automatic retries and replace Jest retries

graylog2-web-interface/src/components/common/SearchForm.css, graylog2-web-interface/src/components/common/SearchForm.jsx, graylog2-web-interface/src/components/common/SearchForm.md
`SearchForm` is almost always used with some special query syntax that that users may not know, or may not always remember. That means that almost always there is a help button associated to the `SearchForm`. So far the help button was rendered outside the `SearchForm` component, usually too far away from the text input as to still remain some context.
This commit let us render a help button inside the text input, helping users to associate that help with the text that they are supposed to write in that input.
The prop is optional, so other consumers of `SearchForm` will work as they were working before.
=> Add prop to render help trigger in SearchForm component

graylog2-web-interface/src/components/search/SearchBar.jsx
Before this change, the saved search id which was selected on the search page was reset after the next search execution. This prevented any updates to saved searches, as updating the query took effect only after the next search execution.
With this change, a selected saved search id is added as a hidden field to the search query form, so it is maintained across search executions. This allows the user to select a saved search, modify the query and update the saved search afterwards.
Fixes #2285.
Needs to be merged into `master` as well.
Manual testing.
=> Maintaining saved search id across search execution.

graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java, graylog2-server/src/main/java/org/graylog2/bindings/providers/DefaultStreamProvider.java, graylog2-server/src/main/java/org/graylog2/streams/DefaultStreamChangeHandler.java, graylog2-server/src/main/java/org/graylog2/streams/StreamServiceImpl.java, graylog2-server/src/test/java/org/graylog2/streams/StreamServiceImplTest.java
Without this, changes to the default stream would not become active until a server restart because the default stream is only loaded once when it's first accessed. (see DefaultStreamProvider)
Fixes #4747
**Note:** This needs to be cherry picked into 2.4 once merged
=>  Make sure to reload the default stream if it has been changed

graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/OkHttpClientProvider.java, graylog2-server/src/test/java/org/graylog2/shared/bindings/providers/OkHttpClientProviderTest.java, misc/graylog.conf
This makes it possible to use a proxy server in `http_proxy_uri` that requires authentication.
Fixes #4594 
**Note:** This needs to be cherry picked into 2.4
=> Implement HTTP proxy server authentication in OkHttpClientProvider

graylog2-web-interface/src/components/configurationforms/ConfigurationForm.jsx
fixes #4745
#4745
Not at all. Unfortunately I couldn't build Graylog independent of my change.
N/A
=> Sort output config fields stably

graylog2-web-interface/.babelrc, graylog2-web-interface/package.json, graylog2-web-interface/packages/graylog-web-plugin/.babelrc, graylog2-web-interface/packages/graylog-web-plugin/package.json, graylog2-web-interface/packages/graylog-web-plugin/yarn.lock, graylog2-web-interface/yarn.lock
The babel team is recommending to switch to the `env` preset instead of
using the yearly presets (which also require continuous updates to the
config). According to the babel team the preset has: `By default, [...]
the same behavior as previous presets to compile ES2015+ to ES5.`
More information can be found [here](https://babeljs.io/env/).
Complete project build was cleaned and performed with these changes. Build succeeded, resulting artifacts were tested and worked.
=> Replacing babel es2015 preset with env preset.

graylog2-server/src/test/java/org/graylog2/inputs/extractors/GrokExtractorTest.java, pom.xml
Refs thekrakken/java-grok#97
Refs https://community.graylog.org/t/handling-comma-when-converting-extracted-data-to-date-type/5030
=> Upgrade to java-grok 0.1.9-graylog to allow commas in date patterns

graylog2-server/src/main/java/org/graylog2/inputs/converters/DateConverter.java, graylog2-server/src/test/java/org/graylog2/inputs/converters/DateConverterTest.java
The date converter should retain the timezone contained in the timestamp even if the users provided another (default) timezone in the configuration of the date converter.
=> Retain timezone if date pattern contains TZ

graylog2-web-interface/src/components/maps/configurations/GeoIpResolverConfig.jsx
In #4736, string refs have been replaced by callbacks. As a fallout of
this change, the map holding refs for inputs in `GeoIpResolverConfig`
was forgotten to initialize, breaking the Geo Ip Processor config modal.
This change is fixing this. Additionally, #4736 was checked again for
variables holding element refs in a nested way (like
`this.inputs[element]`) but no other occurrences where the holder was
not initialized were found.
*Update*: Also fixed linter hints in file.
=> Initializing map holding element refs in `GeoIpResolverConfig`.

graylog2-web-interface/src/components/common/FilterInput.jsx, graylog2-web-interface/src/components/common/FilterInput.md, graylog2-web-interface/src/components/common/FilterInput.test.jsx, graylog2-web-interface/src/components/common/__snapshots__/FilterInput.test.jsx.snap, graylog2-web-interface/src/components/common/index.jsx, graylog2-web-interface/src/components/rules/RuleHelper.jsx
I add a filter to make it easier to search for a specific pipeline
rule function. The filter will search for the function signature and the description of the function.
The Rule Helper displays a lot of documentation for pipeline rules.
Since it is tiresome to go through 10 pages of pipeline functions.
Searched for Pipeline Rules
=> Rule Helper Filter

graylog2-web-interface/src/components/common/SelectPopover.jsx
These changes allow us to maintain the `SelectPopover` filter after the component is hidden, so the filter state is consistent with the list of elements displayed.
Before:
After:
=> Do not reset SelectPopover filter on hide

graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/OkHttpClientProvider.java, graylog2-server/src/test/java/org/graylog2/shared/bindings/providers/OkHttpClientProviderTest.java
The original implementation of the `ProxyAuthenticator` in `OkHttpClientProvider` matched the authentication scheme in a case-sensitive way, which doesn't work with all HTTP proxy servers in the wild.
Fixes #4788
References:
[RFC 7235, section 2.1](https://tools.ietf.org/html/rfc7235#section-2.1)
> Authentication parameters are name=value pairs, where the name token
> is matched case-insensitively, and each parameter name MUST only
> occur once per challenge.
[RFC 2617, section 1.2](https://tools.ietf.org/html/rfc2617#section-1.2)
> It [the authentication mechanism] uses an extensible,
> case-insensitive token to identify the authentication scheme,
> followed by a comma-separated list of attribute-value pairs which
> carry the parameters necessary for achieving authentication via that
> …
=> Support case-insensitive auth-scheme token in proxy authentication

graylog2-web-interface/.babelrc, graylog2-web-interface/package.json, graylog2-web-interface/packages/graylog-web-plugin/package.json, graylog2-web-interface/packages/graylog-web-plugin/yarn.lock, graylog2-web-interface/yarn.lock
This allows e.g. plugin authors to use flow types in development and/or
leave flow type information in source while still being able to
transpile. It should not impact any existing code and/or the way code is
transpiled.
=> Stripping out flow types from JS files.

graylog2-web-interface/src/stores/connect.jsx, graylog2-web-interface/src/stores/connect.test.jsx
This PR is adding small improvements to the `connect` helper function
used to connect React components to Reflux stores:
* Adds a meaningful `displayName` to the generated wrapper component
which is visible in Chrome Devtools during debugging, including the name
of the wrapped component and the configured stores
* Allows passing a props mapper function to mangle props before
passing them to the component, which is helping to prevent unneeded re-rendering
* Corrects example in JSDoc
* Adds helpful error message which is printed to the console when one
of the passed stores is `undefined`
=> Improving stores/connect helper function.

pom.xml
Prevent logging of Elasticsearch node credentials on startup.
Fixes #4804
Refs searchbox-io/Jest#592
Refs graylog-labs/Jest@55ad3d51b7a4a73e6fa7c46e1957565e63bc423e
=> Upgrade to Jest 2.4.13+jackson

graylog2-web-interface/src/components/common/ReactGridContainer.css, graylog2-web-interface/src/components/common/ReactGridContainer.jsx
Clicking anywhere on an unlocked widget generates a drag event, which in our case ends up sending a request to the server to update widgets positions. This also affects buttons that are meant to do other actions (like delete or edit widgets), making #4525 more likely to appear.
This PR is a partial backport of #4530, only including changes to avoid calling drag callbacks when a user clicks on the edit or delete buttons for a widget, which mitigates #4525.
Fixes #4525
PS: The issue seems to be way more likely to occur in Google Chrome than other browsers, so it's easier to reproduce the issue in that browser.
=> Do not update positions after click in widget actions

graylog2-web-interface/src/components/bootstrap/Input.jsx, graylog2-web-interface/src/components/bootstrap/Input.test.jsx, graylog2-web-interface/src/components/bootstrap/__snapshots__/Input.test.jsx.snap
Since #3598 / bba0e6b components which are passed via the `buttonAfter` prop to the `Input` component are not rendered anymore, due to changes of the react-bootstrap API. This leads to inaccessible functionality as described in e.g. #4815.
This PR is reestablishing the used functionality.
Fixes #4815.
=> Add button after to input component again

graylog2-server/src/main/java/org/graylog2/periodical/ThrottleStateUpdaterThread.java, graylog2-server/src/main/java/org/graylog2/shared/events/DeadEventLoggingListener.java
This broke in PR #1948 where I refactored the cluster event handling and removed the throttle state publishing by accident.
Fixes #4321
Refs #1948
**Note:** This should be cherry-picked into 2.4 as well.
=>  Unbreak input throttling by publishing throttle state again

graylog2-server/src/main/java/org/graylog2/periodical/ThrottleStateUpdaterThread.java, graylog2-server/src/main/java/org/graylog2/shared/events/DeadEventLoggingListener.java
This broke in PR #1948 where I refactored the cluster event handling and removed the throttle state publishing by accident.
Fixes #4321
Refs #1948
(cherry picked from commit 060bd1552445737e773b10111a847193bf2f526e)
=> Unbreak input throttling by publishing throttle state again

graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPacksModule.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/CollectorConfigurationFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/CollectorFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/ModelTypes.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/CollectorConfigurationEntity.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/CollectorEntity.java
This PR adds the code needed to support exporting/importing collectors and collector configurations through content packs.
I'm unsure if the current code will properly handle the ID reference that configurations have on a collector when installing the content pack, so please review that carefully and let me know if there are any other changes to make there.
These two entities are the only that I think make sense to export/import from content packs, so I think this would wrap up the content packs support for sidecars at this point.
=> Add content packs support for collectors and collector configurations

graylog2-web-interface/src/components/common/Wizard.css, graylog2-web-interface/src/components/common/Wizard.jsx, graylog2-web-interface/src/components/common/Wizard.md, graylog2-web-interface/src/components/common/Wizard.test.jsx, graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap
Sometimes we want to provide a wizard having some extra width for rendering components, e.g. when rendering a wizard inside a modal. In these cases, it is good rendering our `Wizard` component in horizontal, allowing us to save some space. This PR adds support for that.
Vertical vs horizontal:
Additionally, I also added a change, making the `content` CSS class in the outer row of the `Wizard` component customisable, as we may not always want to draw a border around the wizard.
=> Add option to render Wizard in horizontal

graylog2-web-interface/src/components/common/Select.css, graylog2-web-interface/src/components/common/Select.jsx
Before this change, other elements (namely react-bootstrap input
components with addons) overlapped with `Select` inputs due to a higher
`z-index` of the first.
This change is increasing the `z-index` of the `Select`/`react-select`
menu to `3` (react-bootstrap input addons are on `2`) to prevent this.
Fixes #4769.
Should be backported to `2.4`.
Before:
After:
=> Preventing index size/time input to hide rotation strategy dropdown.

graylog2-server/src/main/java/org/graylog2/shared/rest/resources/system/SystemPluginResource.java
Before this change, the `SystemPluginResource` which returns the list of
installed plugins for this node, did not require any authentication at
all. This might lead to unnecessary disclosure of harmful information
and should be avoided.
Therefore this change adds the annotation which requires the caller of
the `SystemPluginResource` to be authenticated. If this is not
sufficient, a further check for a permission can be introduced.
Fixes #4863.
=> Requires user to be authenticated to retrieve plugin list.

graylog2-server/src/main/java/org/graylog2/rest/resources/system/logs/LoggersResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/tools/LookupTableTesterResource.java, graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java
This PR adds two missing permission checks to log messages and lookup table API endpoints.
Fixes #4861 
Fixes #4859 
**Note:** This should be cherry-picked into 2.4 once merged.
=> Add missing permission checks

graylog2-server/src/main/java/org/graylog2/shared/rest/resources/system/SystemPluginResource.java
Before this change, the `SystemPluginResource` which returns the list of
installed plugins for this node, did not require any authentication at
all. This might lead to unnecessary disclosure of harmful information
and should be avoided.
Therefore this change adds the annotation which requires the caller of
the `SystemPluginResource` to be authenticated. If this is not
sufficient, a further check for a permission can be introduced.
Fixes #4863.
(cherry picked from commit 267be4ae23b3ef163427bbc816dd2c7378f755e4)
=> Requires user to be authenticated to retrieve plugin list

graylog2-web-interface/src/components/common/Select.css, graylog2-web-interface/src/components/common/Select.jsx
* Increasing z-index of `Select` component to overlay other elements.
Before this change, other elements (namely react-bootstrap input
components with addons) overlapped with `Select` inputs due to a higher
`z-index` of the first.
This change is increasing the `z-index` of the `Select`/`react-select`
menu to `3` (react-bootstrap input addons are on `2`) to prevent this.
Fixes #4769.
* Increase z index of `Select` component's menu to 5.
This change is increasing the z-index of the dropdown menu of a `Select`
component even more, so it is on top of the gutter of an Ace editor
component.
(cherry picked from commit 39816860f86aa1a60a1bd4a8c7676b9daa4befea)
=> Preventing index size/time input to hide rotation strategy dropdown

graylog2-server/src/test/java/org/graylog2/rest/GenericErrorCsvWriterTest.java
By allocating a new port for each Jersey Test Container we avoid
`BindException`s being thrown for parallel tests because port 9998 is
already in use.
Fixes #4876.
=> Allocating unused port for Jersey Test Container.

graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/ActionResource.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/AdministrationResource.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/CollectorResource.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/ConfigurationResource.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/SidecarResource.java
While it's not an issue repeating the annotation for every resource
method, having it once at the class level prevents the accidental
introduction of unprotected endpoints in the future.
Fixes #4862
=> Move RequiresAuthentication annotation to the top of sidecar endpoints

graylog2-server/src/main/java/org/graylog2/grok/InMemoryGrokPatternService.java, graylog2-server/src/main/java/org/graylog2/grok/MongoDbGrokPatternService.java, graylog2-web-interface/src/components/bootstrap/BootstrapModalForm.jsx, graylog2-web-interface/src/components/bootstrap/BootstrapModalWrapper.jsx, graylog2-web-interface/src/components/grok-patterns/EditPatternModal.jsx, graylog2-web-interface/src/components/grok-patterns/GrokPatternInput.css, graylog2-web-interface/src/components/grok-patterns/GrokPatternInput.jsx, graylog2-web-interface/src/components/grok-patterns/GrokPatternInput.test.jsx, graylog2-web-interface/src/components/grok-patterns/GrokPatterns.jsx, graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap, graylog2-web-interface/src/components/users/__snapshots__/UserPreferencesButton.test.jsx.snap
Create a new grok input component which will help a user creating a new
grok input from existing ones.
A user can search via filter for grok patterns and add them to the
text field beside him. A grok pattern will be placed under the current
cursor position of the text field.
If you want to create a new grok pattern from existing ones you need to open a second
tap so you can search for the existing ones. To prevent such behavior we now have
the grok pattern filter which can also add the grok patterns to the text field.
Editing or creating a grok pattern and use the filter function to find a grok pattern and add it with 'Add' button.
=> New grok pattern input component

UPGRADING.rst, graylog2-server/src/main/java/org/graylog2/streams/StreamMetrics.java, graylog2-server/src/main/java/org/graylog2/streams/StreamRouterEngine.java, graylog2-server/src/test/java/org/graylog2/streams/StreamMetricsTest.java
The original metrics name didn't contain any information about the stream which the stream rule was part of.
This made it very hard to identify the stream which included the stream rule and was only possible by either querying MongoDB directly or take a look into each stream (brute force).
This change set changes the metrics name from
org.graylog2.plugin.streams.StreamRule.${stream-rule-id}.executionTime
to
org.graylog2.plugin.streams.Stream.${stream-id}.StreamRule.${stream-rule-id}.executionTime
Refs https://community.graylog.org/t/identify-stream-rule-from-metrics/5266
- Breaking change (fix or feature that would cause existing functionality to change)
=> Add stream ID to stream rule metrics name

graylog2-server/src/main/java/org/graylog2/alerts/AlertConditionFactory.java, graylog2-server/src/main/java/org/graylog2/plugin/configuration/ConfigurationRequest.java
Improve error and warning messages for alert conditions by always including the alert condition ID and the stream ID it's connected to.
Refs #4883
=> Improve log messages for alert conditions and configuration requests

graylog2-server/src/main/java/org/graylog/plugins/sidecar/filter/StatusAdministrationFilter.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/models/CollectorStatus.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/models/CollectorStatusList.java, graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministration.jsx, graylog2-web-interface/src/components/sidecars/sidecars/SidecarStatus.jsx
This fixes a problem when using a "." character in a collector backend
name. It also makes it easier to run MongoDB queries against collector
status objects.
Fixes #4885
=> Change collector status data from a map to a set of objects

graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/FieldTypeMapper.java, graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/FieldTypeMapperTest.java
Also add a TODO comment to revisit the ES 2.x "string" data type.
Fixes #4841
=> Make "keyword" field type enumerable instead of full-text searchable

graylog2-web-interface/src/components/common/TypeAheadInput.jsx, graylog2-web-interface/src/components/search/QueryInput.ts
Escape content of templates used to draw Typeahead suggestions.
This change needs to be backported to the 2.4 branch.
=> Escape Typeahead templates content

graylog2-server/src/main/java/org/graylog2/grok/MongoDbGrokPatternService.java, graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java, graylog2-server/src/main/java/org/graylog2/migrations/V2018070614390000_EnforceUniqueGrokPatterns.java, graylog2-server/src/test/java/org/graylog2/grok/MongoDbGrokPatternServiceTest.java, graylog2-server/src/test/java/org/graylog2/migrations/V2018070614390000_EnforceUniqueGrokPatternsTest.java
Up until now, it's possible to create Grok patterns with the same name, but different patterns.
This change set ensures that there are no duplicate Grok patterns by removing them in a migration and adding a unique index on the "name" field of the "grok_patterns" MongoDB collection.
Refs https://community.graylog.org/t/feature-import-grok-pattern-with-duplicate-management/5865
=> Avoid creating duplicate Grok patterns

graylog2-server/src/main/java/org/graylog2/plugin/indexer/searches/timeranges/AbsoluteRange.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/DecoratorResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/KeywordSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/RelativeSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/SavedSearchesResource.java, graylog2-server/src/test/java/org/graylog2/plugin/indexer/searches/timeranges/AbsoluteRangeTest.java
Mandatory query parameters in search resources, such as "from" and "to" in AbsoluteSearchResource, "range" in RelativeSearchResource, or "keyword" in KeywordSearchResource, weren't checked for basic validity (i. e. not null, empty, or negative) leading to unfriendly error messages for users sending invalid requests to one of these resources.
Refs https://community.graylog.org/t/api-search-universal-absolute-500-response-on-providing-query-in-params-field/5937
=> Ensure mandatory parameters in search resources are valid

graylog2-web-interface/src/components/common/ExpandableListItem.css
Add space between header and subheader.
Before:
After:
=> Add missing spacing in ExpandableListItem

graylog2-server/src/main/java/org/graylog/plugins/map/geoip/MaxmindDataAdapter.java, graylog2-server/src/main/java/org/graylog2/lookup/adapters/CSVFileDataAdapter.java, graylog2-server/src/main/java/org/graylog2/plugin/utilities/FileInfo.java, graylog2-server/src/test/java/org/graylog2/plugin/utilities/FileInfoTest.java
Make sure the "fileInfo" field is initialized with an empty FileInfo
object. Also catch all exceptions in FileInfo#forPath instead of
IOExceptions only.
Refs #4748
**Note:** This needs to be cherry-picked into 2.4 once merged
=> Fix potential NullPointerException in csv and maxmind data adapters

graylog2-server/src/main/java/org/graylog2/plugin/BaseConfiguration.java, graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/OkHttpClientProvider.java, graylog2-server/src/main/java/org/graylog2/utilities/ProxyHostsPattern.java, graylog2-server/src/main/java/org/graylog2/utilities/ProxyHostsPatternConverter.java, graylog2-server/src/test/java/org/graylog2/shared/bindings/providers/OkHttpClientProviderTest.java, graylog2-server/src/test/java/org/graylog2/utilities/ProxyHostsPatternConverterTest.java, graylog2-server/src/test/java/org/graylog2/utilities/ProxyHostsPatternTest.java, misc/graylog.conf
This can be used to bypass a configured proxy server for a list of
hostnames or IP addresses. It must be used if the inter-node
communication between graylog servers should not go through a configured
proxy server.
The matcher implementation for the "http_non_proxy_hosts" is similar to
the implementation that is used for the "http.nonProxyHosts" system
property. (only the delimiter is "," instead of "|" for consistency)
By using a similar implementation, it will be possible to also set the
system property in the future. (if needed - tbd)
Fixes #4905
Fixes #4392
(This needs to be cherry-picked into 2.4 once merged)
=> Add "http_non_proxy_hosts" configuration option

graylog2-web-interface/src/components/widgets/WidgetFooter.test.jsx
Before this change, `Date.now` returned the actual time of the test run
which cause the result to inevitably deviate from the snapshot over
time.
This change is mocking `Date.now` and returning a fixed date instead.
Fixes #4916.
=> Fixing `Date.now` for WidgetFooter tests.

graylog2-web-interface/test/helpers/mocking/MockComponent.jsx
This tiny change sets the `displayName` property for created mock
components used in react-based tests. This helps a lot to assert the
existence/quantity of mock components in the generated DOM tree.
This change affects only tests, not other code.
=> Set `displayName` for mocked components.

graylog2-web-interface/src/components/content-packs/ContentPackEntitiesList.css, graylog2-web-interface/src/components/content-packs/ContentPackEntitiesList.jsx, graylog2-web-interface/src/components/content-packs/ContentPackParameterList.css, graylog2-web-interface/src/components/content-packs/ContentPackParameterList.jsx, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntitiesList.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameterList.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameters.test.jsx.snap
Let title and description column break the word if to long.
Entities with a single-word long description (like a github url) overlap with table rows.
With a rather long description!
Fixes #4943
=> Fix overlapping rows with long descriptions

graylog2-server/src/main/java/org/graylog2/rest/models/system/contenpacks/responses/ContentPackInstallationsResponse.java, graylog2-server/src/main/java/org/graylog2/rest/models/system/contenpacks/responses/ContentPackList.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/contentpacks/ContentPackResource.java, graylog2-server/src/test/java/org/graylog2/rest/resources/system/contentpacks/ContentPackResourceTest.java
To match other api endpoints which might support
pagination ContentPackResources now has the total flag
All other endpoints which might support pagination in the future
have total attribute in the response.
Fixes #4947
=> Add total attribute of ContentPackList

graylog2-web-interface/src/components/content-packs/ContentPackEntitiesList.jsx, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntitiesList.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameters.test.jsx.snap
Previously some entities had no title but a description, that looked
strange.
Refs #4946
=> Use title or name for the entity when renderning entities in the UI

graylog2-server/src/main/java/org/graylog2/contentpacks/facades/DashboardFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/DashboardWidgetEntity.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/DashboardFacadeTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/jackson/ValueReferenceTypeIdResolverTest.java
Installing a dashboard through a content pack will reuse old widget IDs, ensuring references from other installed entities can still be used.
This is needed because dashboard widgets don't have their own `ModelType`, making it impossible to find the referenced widget during install. As widget IDs are embedded inside the dashboard document, potentially duplicating widget IDs should not be a problem.
=> Reuse old widget IDs when installing a dashboard from content packs

graylog2-server/src/main/java/org/graylog2/rest/RemoteInterfaceProvider.java, graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java, graylog2-server/src/main/java/org/graylog2/shared/rest/CORSFilter.java, graylog2-server/src/main/resources/swagger/index.html.template, graylog2-web-interface/src/logic/rest/FetchProvider.js
Improve our protection against CSRF by requiring a custom request header (`X-Requested-By`) in all non-GET requests sent to our API. This is mentioned as a way of CSRF prevention [1] and it is particularly suitable for REST APIs, since let requests to remain stateless.
1: https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Protecting_REST_Services:_Use_of_Custom_Request_Headers
=> Add custom request header to prevent CSRF

graylog2-server/src/main/java/org/graylog2/rest/resources/system/contentpacks/ContentPackResource.java, graylog2-server/src/test/java/org/graylog2/rest/resources/system/contentpacks/ContentPackResourceTest.java
Add content pack id to permission checks in the content pack resource.
Fixes #4948
To check content packs more fine granular (and to be consistent with other endpoints) 
I add the content pack id to the permission check. 
Add new role and manually add new content pack permission, assigned role to a user with only
reader permissions and tested with swagger to create a new version.
=> Use content pack id for fine granular permission check

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/KeyValue.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/keyValue.txt
Prevent splitting values if delimiter chars are found inside values
Fixes #4920
=> Fix KeyValue rule function to split entries once

graylog2-web-interface/test/helpers/mocking/StoreMock.js, graylog2-web-interface/test/helpers/mocking/StoreProviderMock.js, graylog2-web-interface/test/helpers/mocking/index.js
Add a new StoreProviderMock which can be used as a mock
for StoreProvider. It's a factory which takes a map of stores
with the store names as keys.
Also enhance StoreMock so it can add a custom function
in stead of jest.fn(). This is useful when the function
should return something specific or you want to add a
`expect` to the function outcome.
StoreProviderMock is needed to make a meaningful mock of StoreProvider
(just like CombinedProviderMock)
=> Add new StoreProviderMock and add custom Function to StoreMock

graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackService.java, graylog2-server/src/main/java/org/graylog2/contentpacks/constraints/ConstraintChecker.java, graylog2-server/src/main/java/org/graylog2/contentpacks/constraints/GraylogVersionConstraintChecker.java, graylog2-server/src/main/java/org/graylog2/contentpacks/constraints/PluginVersionConstraintChecker.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/ContentPack.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/constraints/Constraint.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/constraints/ConstraintCheckResult.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/constraints/GraylogVersionConstraint.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/constraints/PluginVersionConstraint.java, graylog2-server/src/main/java/org/graylog2/rest/models/system/contenpacks/responses/ContentPackResponse.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/contentpacks/ContentPackResource.java, graylog2-server/src/test/java/org/graylog2/contentpacks/constraints/GraylogVersionConstraintCheckerTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/constraints/PluginVersionConstraintCheckerTest.java, graylog2-server/src/test/java/org/graylog2/rest/resources/system/contentpacks/ContentPackResourceTest.java, graylog2-web-interface/src/components/content-packs/ContentPackConstraints.jsx, graylog2-web-interface/src/components/content-packs/ContentPackDetails.jsx, graylog2-web-interface/src/components/content-packs/ContentPackDownloadControl.jsx, graylog2-web-interface/src/pages/ShowContentPackPage.jsx, graylog2-web-interface/src/routing/ApiRoutes.js, graylog2-web-interface/src/stores/content-packs/ContentPacksStore.jsx
Add requirements check result to content pack response. 
We want to display if a requirement of a content pack is met by the server,
for that the server checkes if every constraint is met and adds the
information to the json result.
The frontend can now use the so send fulfilled flag to check if
the requirement is met
it's now green!
=> Check requirement fulfillment and show it on ShowContentPacksPage

graylog2-web-interface/src/components/content-packs/ContentPackEdit.jsx, graylog2-web-interface/src/components/content-packs/ContentPackEntitiesList.jsx, graylog2-web-interface/src/components/content-packs/ContentPackParameterList.jsx, graylog2-web-interface/src/components/content-packs/ContentPackPreview.jsx, graylog2-web-interface/src/components/content-packs/ContentPackSelection.jsx, graylog2-web-interface/src/components/content-packs/ContentPackSelection.test.jsx, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackPreview.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
A user new to the content packs might not understand what he
has to fill out to get to the next page. Now we show which fields
a necessay to complete the general information and content pack selection.
The preview of content pack edit/creation was wasting space.
Now all list are on the right side and all general information
are placed to the left.
It was hard for user to see when the next wizard step could be taken.
=> Add validation to mandatory fields and better arrange overview

graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/models/Collector.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/CollectorService.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/CollectorFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/CollectorEntity.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/CollectorFacadeTest.java, graylog2-server/src/test/resources/org/graylog2/contentpacks/sidecar_collectors.json, graylog2-web-interface/src/components/sidecars/configuration-forms/CollectorForm.jsx, graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.jsx
Currently we store the command arguments of a collector as a list of strings. This can lead to problems like described in #4889. This PR is changing the model in a way that it stores the argument as a simple string. The arguments need to be split up on the Sidecar side afterwards so this work depends  on https://github.com/Graylog2/collector-sidecar/pull/273
Fixes #4889
=> Store collector commend arguments as string

graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/NativeEntityDescriptor.java, graylog2-server/src/test/resources/org/graylog2/contentpacks/ContentPackInstallationPersistenceServiceTest.json
To clarify which id is which I rename entity_id to content_pack_entity_id
in NativeEntityDescriptor.
That way the entity_id from the content pack is
marked.
=> Rename entity_id to content_pack_entity_id

graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/CollectorResource.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/ConfigurationResource.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/responses/ConfigurationSidecarsResponse.java, graylog2-web-interface/src/actions/sidecars/CollectorConfigurationsActions.js, graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.jsx, graylog2-web-interface/src/logic/rest/FetchProvider.js, graylog2-web-interface/src/pages/SidecarEditConfigurationPage.jsx, graylog2-web-interface/src/stores/sidecars/CollectorConfigurationsStore.js, graylog2-web-interface/src/stores/sidecars/CollectorsStore.js
In order to avoid leaving Sidecars running in an unexpected state, this PR adds some restrictions on when it is possible to do certain actions:
- Deleting a Collector is only possible if there is not any Configurations using it
- Deleting a Configuration is only possible if there is not any Sidecars using it
- Changing the Collector associated to a Configuration is only possible if there are no Sidecars using that configuration
Fixes #5007
=> Improve entity consistency in sidecar

graylog2-web-interface/src/components/ldap/LdapComponent.jsx
Allows selecting custom roles as default roles for LDAP users. 
Only default (reader and administrator) roles were eligible from the list.
Implements #5000 
1. Create a custom role
2. Configure Graylog for LDAP authentication
3. In the LDAP settings, the new custom role appears in the list of Default Roles
=> Allow user created roles as default role for LDAP users

graylog2-web-interface/src/components/content-packs/ContentPackSelection.jsx
Sort the content pack entities by name when displaying them for creation or editing.
So user can easier find desired entities.
Fixes #4991
=> Sort content pack entities by name

graylog2-server/src/main/java/org/graylog2/contentpacks/model/constraints/GraylogVersionConstraint.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/constraints/PluginVersionConstraint.java
Relax server and plugin version requirements
Content packs created with a 3.0.0 server would not work with 4.0.0 any longer
and that for perhaps no reason at all.
=> Relax server and plugin version requirements

graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministration.jsx, graylog2-web-interface/src/stores/sidecars/SidecarsAdministrationStore.js
- Update selected collectors when the list of sidecars or collector changes, ensuring only available sidecars or collectors are selected
- Fix typo to keep filters when refreshing the sidecar list
=> Collector administration page fixes

ELASTICSEARCH_UPGRADES.md, graylog2-server/src/main/java/org/graylog2/bindings/providers/JestClientProvider.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping5.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping6.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexMappingFactory.java, graylog2-server/src/main/java/org/graylog2/indexer/cluster/jest/RequestResponseLogger.java, graylog2-server/src/main/java/org/graylog2/inputs/random/generators/FakeHttpRawMessageGenerator.java, graylog2-server/src/main/java/org/graylog2/migrations/V20170607164210_MigrateReopenedIndicesToAliases.java, graylog2-server/src/test/java/org/graylog2/indexer/IndexMappingFactoryTest.java, pom.xml
Primarily adapt index mapping template changes for 6.x backends.
Updated jest+jackson dependency for minor URL compatibility with 6.x servers.
Add elasticsearch request logger for debugging request/response layer: enable with `TRACE` on `org.graylog2.indexer.cluster.jest.RequestResponseLogger`
fixes #4957
=> Update to elasticsearch 6.x compatibility

graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/models/Collector.java, graylog2-web-interface/src/stores/sidecars/CollectorConfigurationsStore.js, graylog2-web-interface/src/stores/sidecars/CollectorsStore.js, graylog2-web-interface/src/stores/sidecars/SidecarsStore.js
This PR fixes #5046 by marking the optional collector fields as nullable.
As #5046 also described, the web interface rendered another page, once the form was submitted, even if the end result was an error coming from the server. The PR also changes how we add handlers to the promises in the sidecar stores, to ensure that an error in the backend will not call `then` handlers added to the action promise. More info on chaining handlers vs multiple handlers in https://javascript.info/promise-chaining.
=> Make optional collector fields nullable

graylog2-server/src/main/java/org/graylog2/audit/AuditEventTypes.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/contentpacks/CatalogResource.java
Remove audit log events from catalog resource
The resolve action of catalog resource does not need a audit log event, since it is only computing
and not altering the database.
=> Remove audit log from resolve action of catalog recource

graylog2-web-interface/src/components/extractors/extractors_configuration/GrokExtractorConfiguration.css, graylog2-web-interface/src/components/extractors/extractors_configuration/GrokExtractorConfiguration.jsx, graylog2-web-interface/src/components/grok-patterns/GrokPatternInput.jsx, graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap
Add the GrokPatternInput to the grok pattern extraction page.
Also fix some linter errors.
A user needed to know all his grok patterns to create a extractor.
Now he can search in grok pattern list.
=> Add GrokPatternInput to GrokExtractorConfiguration

graylog2-web-interface/src/pages/SidecarEditCollectorPage.jsx
Cleaning up linter errors on #5074, I accidentally deleted the call to load the collector on that page, resulting into a page that was stuck in the loading state. This PR corrects that mistake.
=> Fix loading of collector on edit collector page

graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministration.jsx, graylog2-web-interface/src/components/sidecars/common/CommonSidecarStyles.css, graylog2-web-interface/src/components/sidecars/sidecars/SidecarRow.css, graylog2-web-interface/src/components/sidecars/sidecars/SidecarRow.jsx
In a similar way of how we do it in the sidecar list page, display some indication that a sidecar is inactive in the administration page.
=> Mark inactive sidecars in administration page

graylog2-web-interface/src/components/content-packs/ContentPackSelection.test.jsx, graylog2-web-interface/src/pages/EditContentPackPage.jsx
* Fix revision bump when editing a new content pack revision
* Fix selection of entities from former content pack revision
* When a content pack was created from revision `1` but there was already a revision `2`, the create would fail, since the new content pack would have a content pack `1`,
* When editing a content pack the entities were not considering the new entity type format 
Edit a content pack
=> Fix editing of content packs

graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/ConfigurationResource.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/ConfigurationService.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/template/RenderTemplateException.java, graylog2-web-interface/src/stores/sidecars/CollectorConfigurationsStore.js
This PR adds template validation before a collector configuration is added to the database. To do the validation we render a preview of the template and see if there was any error. This will probably not catch all errors that may happen, but it will at least prevent some undefined variables to be used, and check some lexical errors in the configuration template.
Fixes #5042
=> Run template validation before saving collector configuration

graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackService.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/DashboardFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/EntityFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/GrokPatternFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/InputFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupCacheFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupDataAdapterFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupTableFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/OutputFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/PipelineFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/PipelineRuleFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/RootEntityFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorConfigurationFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/StreamFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/UnsupportedEntityFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/jackson/ReferenceConverter.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/ContentPackUninstallation.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/EntityV1.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/contentpacks/ContentPackResource.java, graylog2-server/src/test/java/org/graylog2/contentpacks/jackson/ReferenceConverterTest.java, graylog2-web-interface/src/components/content-packs/ContentPackConstraints.jsx
This PR implements content pack uninstallation.
- Content packs that create inputs might fail to start the input on installation due to the problem in https://github.com/Graylog2/graylog2-server/issues/5106
- Content packs with an input that uses a lookup table extractor or converter cannot be installed because the dependency resolution in the InputFacade is incomplete. See: https://github.com/Graylog2/graylog2-server/issues/5105
- The user should see the list of entities that will be removed when a content pack gets uninstalled (https://github.com/Graylog2/graylog2-server/issues/5111)
Refs #4780
=> Implement content pack uninstallation

graylog2-server/src/main/java/org/graylog2/plugin/indexer/searches/timeranges/TimeRange.java
Before:
```
"timerange": {
"type": "relative",
"type": "relative",
"range": 300
}
```
After:
```
"timerange": {
"type": "relative",
"range": 300
}
```
=> Not serializing `type` field twice for `TimeRange` instances.

graylog-plugin-parent/pom.xml, pom.xml
Fixes Graylog2/graylog-project-internal#19
**Notice:** This should be cherry-picked into 2.5 once merged
=> Make "license:check" and "license:format" work from the project root

graylog2-web-interface/webpack/UniqueChunkIdPlugin.js
Before this change, the chunk id of a webpack compilation was being
prefixed with a random, build-specific identifier. This happened for
every compilation, even partial ones (when changing a file during
webpack/webpack-dev-server watch mode). Unfortunately there was no check
if the prefix had already been added, so for every partial compilation
it was added all over again.
This PR introduces a check if the given chunk contains an id which is
already prefixed and skips prefixing it in this case.
=> Randomize chunk id only once.

graylog2-web-interface/src/components/common/PageHeader.jsx, graylog2-web-interface/src/components/common/PageHeader.md
`PageHeader` so far allowed us to set an `experimental` flag, that would show an indicator if the rendered page was still considered experimental.
This PR adds a `legacy` lifecycle stage as well, and makes setting lifecycles more generic, so we could add more in the future if needed.
This PR also adds the possibility to set custom lifecycle messages that will be displayed in the tooltip, so consumers of `PageHeader` can customise the default messages for the given lifecycle.
Refs https://github.com/Graylog2/graylog-plugin-collector/issues/90
=> Add more lifecycle indicators to `PageHeader`

misc/graylog.conf
In #5070 we removed the config options but forgot
the example config. This change removes the options
from the example config
Fixes #5119
=> Remove legacy config options from config example

graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java, graylog2-server/src/test/resources/org/graylog2/contentpacks/sidecar_collectors.json
The config path contains whitespaces and needs to be quoted.
Fixes https://github.com/Graylog2/collector-sidecar/issues/290
=> Add quotes to default winlogbeat collector parameter

graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/ConfigurationService.java, graylog2-server/src/test/java/org/graylog/plugins/sidecar/collectors/ConfigurationServiceTest.java
If a user entered a Sidecar configuration without an empty last line,
we would render the last configuration line without a newline terminator.
This might confuse some config parsers, looks weird when using `cat` and
is against my personal taste ;-)
Also add a small unit test for the ConfigurationService.
=> Enforce newlines at the end of rendered configurations

graylog2-web-interface/src/components/support/ContactUs.jsx, graylog2-web-interface/src/components/support/SupportSources.jsx, graylog2-web-interface/src/pages/ErrorPage.css, graylog2-web-interface/src/pages/ErrorPage.jsx, graylog2-web-interface/src/routing/App.jsx, graylog2-web-interface/src/routing/AppErrorBoundary.jsx, graylog2-web-interface/src/routing/AppErrorBoundary.test.jsx, graylog2-web-interface/src/routing/__snapshots__/AppErrorBoundary.test.jsx.snap, graylog2-web-interface/webpack.config.js
This change implements a error boundary component wrapping children of
the navigation bar in the `App` component.
Before this change, any errors in children components of the navigation
bar caused the application to malfunction, errors being shown on the
js console only and (for React 16) the DOM to be unmounted, requiring
the user to do a full page refresh to be able to work with the
application again.
After this change, errors occuring in components which are children of
the navigation bar leave the application in a functional state, while
showing the error message, stack trace and component tree in the
browser. Users are still able to navigate the application afterwards.
=> Implement Error Boundary for Navigation Bar children.

graylog2-web-interface/src/components/lookup-tables/__snapshots__/DataAdapterCreate.test.jsx.snap, graylog2-web-interface/test/helpers/mocking/MockComponent.jsx
This change is improving the `MockComponent` function which generates a
mock component usable in tests when rendering a subtree is not desired.
Before this change, `MockComponent` generated a component which renders
a series of `span` elements which were carrying the passed `props` to
it, so they show up in a snapshot. Unfortunately this fails when React
warnings fail tests, because those props were not accepted on `span`
elements.
After this change, `MockComponent` returns a component rendering a
custom element, which is named after the string parameter passed to it,
e.g. `MockComponent('FooMock')` returns a component rendering
```
<foo-mock {...props}>
{children>
</foo-mock>
```
which serves the purpose of creating a minimal element which carries all
props and children passed to it, so …
=> Improving MockComponent by rendering custom component.

graylog2-server/src/main/java/org/graylog2/inputs/transports/netty/ExceptionLoggingChannelHandler.java, graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java, graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/NettyTransport.java
To handle exceptions that happen in the server context,
we need to register our ExceptionLoggingChannelHandler as a childHandler.
In addition, make sure that the ExceptionLoggingChannelHandler is
always added to the top of the (bottom-up evaluated) pipeline.
Otherwise it might miss some exceptions.
Do not propagate the exception any further.
A full netty stacktrace does not help anyone.
One meaningful log message should be enough.
This last bit of the change fixes #5109
=> Catch Netty exceptions and avoid logging stacktraces

graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/CollectorResource.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/ConfigurationResource.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/SidecarResource.java, graylog2-web-interface/src/components/sidecars/configuration-forms/SourceViewModal.jsx, graylog2-web-interface/src/pages/SidecarEditCollectorPage.jsx, graylog2-web-interface/src/pages/SidecarEditConfigurationPage.jsx, graylog2-web-interface/src/pages/SidecarStatusPage.jsx, graylog2-web-interface/src/stores/sidecars/CollectorConfigurationsStore.js, graylog2-web-interface/src/stores/sidecars/CollectorsStore.js, graylog2-web-interface/src/stores/sidecars/SidecarsStore.js
These changes ensure we handle 404s when getting a sidecar, collector or configuration in a consistent way. Users will see an error informing that the entity is not there, and they will be also redirected when accessing an edit page for one of those entities.
=> Handle 404s in sidecar

graylog2-web-interface/src/components/common/ExpandableListItem.jsx, graylog2-web-interface/src/components/common/__snapshots__/ExpandableList.test.jsx.snap, graylog2-web-interface/src/components/content-packs/ContentPackInstall.jsx, graylog2-web-interface/src/components/content-packs/ContentPackParameterList.jsx, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
Small fixes regarding content packs.
* Allign Install form fields
The install form has a list of entities
which were unallgined to the form fields.
Fixes #5115
* Fix closing of ContentPackEditParameter modal
the modal did not close since it was a child of
the open button. A click on the close button bubbled up
to the open button which would than reopen the closed
modal. 
I moved out the modal as a child from the open button.
* Make click on ExpandleListItem select checkbox
We do not have label and checkboxes, since we do not have
ids for the ExpandleListItem. There for I add an click
handler to the header which will click on the
associated checkbox.  
Fixes #5114
=> Fixes for content packs

graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java, graylog2-server/src/main/java/org/graylog2/shared/rest/VerboseCsrfProtectionFilter.java
Before this change, the server returned a generic "Bad Request" error
message when a client queried the API without the required CSRF
protection header. This leaves the consumer confused, especially for
previous users of the API which now do not know what to change in their
request to make it work again.
This change now leaves the error code intact but adds a helpful message
telling the consumer what went wrong.
Fixes #5012.
=> Return helpful error message when CSRF protection fails.

graylog2-web-interface/src/components/bootstrap/BootstrapModalConfirm.jsx, graylog2-web-interface/src/components/sidecars/administration/CollectorProcessControl.jsx, graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministrationActions.jsx, graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministrationFilters.jsx, graylog2-web-interface/src/components/sidecars/common/StatusIndicator.css, graylog2-web-interface/src/components/sidecars/common/StatusIndicator.jsx
These changes try to improve the situation described in #5047 by:
- Swap actions, to show the configuration selector before the process control. This gives more visibility to the most used action (assign configurations)
- Add a warning when trying to manage collector processes, if some selected collectors are not configured yet
Besides that, the PR also contains a couple other minor UI fixes.
=> UI improvements for configuring and starting collectors

graylog2-server/src/main/java/org/graylog2/shared/rest/VerboseCsrfProtectionFilter.java
...who don't have the "X-Requested-By" header yet.
Simply accepting "X-Graylog-Collector-Version" serves the same purpose.
Relates to https://github.com/Graylog2/graylog2-server/pull/4987
=> Add CSRF backward compatibility for older Sidecars

graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java
If a Beats input is configured to mandatory "TLS client authentication",
but a user hasn't configured any certificates, we will create a warning.
Unfortunetly on systems with multiple Inputs, the user has no idea
on which input the error has occured.
Include the input's identifier in the log message.
=> Enrich client cert warning message with info about input

UPGRADING.rst
The drools plugin we have referenced is deleted by the user. So we remove this.
=> removed drools plugin

graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java, graylog2-server/src/main/java/org/graylog2/shared/rest/VerboseCsrfProtectionFilter.java
Port of https://github.com/Graylog2/graylog2-server/pull/5177 into 2.5.
=> Return helpful error message when CSRF protection fails. (#5177)

graylog2-server/src/main/java/org/graylog2/contentpacks/facades/DashboardFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/GrokPatternFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/InputFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupCacheFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupDataAdapterFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupTableFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/OutputFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/PipelineFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/PipelineRuleFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorConfigurationFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/StreamFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/NativeEntity.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/NativeEntityDescriptor.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/contentpacks/ContentPackResource.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/DashboardFacadeTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/GrokPatternFacadeTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/SidecarCollectorFacadeTest.java, graylog2-web-interface/src/components/content-packs/ContentPackInstallView.jsx, graylog2-web-interface/src/components/content-packs/ContentPackInstallations.test.jsx
Add title to `NativeEntityDescriptor` and show the title in the detail of the content pack installation.
Before a user wants to uninstall a content pack he might want to look what entities are
installed via a content pack.
Installed a content pack and looked at the installation details.
=> Show entities in details of a content pack installation

graylog2-server/src/main/java/org/graylog2/shared/system/stats/fs/FsStats.java, graylog2-server/src/main/java/org/graylog2/shared/system/stats/fs/SigarFsProbe.java
The type will show if the file system is a local or remote one and the
name will show the file system name. (e.g. ext4)
This will help debugging IO issues, especially for the journal
directory.
=> Add file system type and name to FsStats

graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java, graylog2-web-interface/src/components/sidecars/configuration-forms/FilebeatHelper.jsx, graylog2-web-interface/src/components/sidecars/configuration-forms/TemplatesHelper.jsx
Provide our users with a sensible default template for filebeat and winlogbeat.
Include a config preamble that is needed for the Graylog GUI to function.
Fixes https://github.com/Graylog2/collector-sidecar/issues/297
=> Add Beats default templates

graylog2-web-interface/src/components/common/IfPermitted.jsx, graylog2-web-interface/src/components/common/IfPermitted.test.jsx, graylog2-web-interface/src/components/navigation/Navigation.jsx, graylog2-web-interface/src/components/navigation/Navigation.test.jsx, graylog2-web-interface/src/components/navigation/NavigationLink.jsx, graylog2-web-interface/src/components/navigation/NavigationLink.test.jsx, graylog2-web-interface/src/components/navigation/SystemMenu.jsx, graylog2-web-interface/src/components/navigation/SystemMenu.test.jsx, graylog2-web-interface/src/util/PermissionsMixin.jsx
This change allows plugins to contribute dropdowns for the navigation bar instead of individual navigation elements. This allows plugins which contribute more than one navigational entrypoint to group them together in a single navigation element and occupy less space.
For this, the `Navigation` component was broken down into additional `SystemMenu` and `NavigationLink` components and tests for these individual components were added.
Additionally, `IfPermitted` was used whenever possible. For this, props passthrough was implement to support wrapping e.g. `MenuItem` components which get some properties passed in externally.
=> Support navigation dropdowns contributed by plugins.

graylog2-server/src/main/java/org/graylog/plugins/beats/BeatsCodec.java, graylog2-server/src/main/java/org/graylog/plugins/beats/BeatsInput.java, graylog2-server/src/main/java/org/graylog/plugins/beats/BeatsInputPluginModule.java, graylog2-server/src/test/java/org/graylog/plugins/beats/BeatsInputDescriptorTest.java, graylog2-server/src/test/java/org/graylog/plugins/beats/DeprecatedConsolePrinter.java
The former name suggested that it could be used to parse
an old version of the Beats protocol.
The new name is hopefully less confusing.
=> Rename "Beats Legacy" input to "Beats (deprecated)"

graylog2-web-interface/src/components/common/IfPermitted.jsx, graylog2-web-interface/src/components/common/IfPermitted.test.jsx
Since #5193, `IfPermitted` passes given props to children to allow it being used in
scopes where the wrapped child(ren) is/are supposed to follow directly
after a parent component.
Unfortunately this mechanic previously did not check if the passed
property is already present on the child. This lead to a regression
where event handlers where overwritten.
This change is now checking if the given prop is present on the child
before passing it.
=> Prevent overwriting children's props in `IfPermitted`.

graylog-plugin-archetype/src/main/resources/archetype-resources/package.json, graylog-plugin-archetype/src/main/resources/archetype-resources/pom.xml, graylog-plugin-parent/pom.xml
* Removing unneeded prefixes from tasks in `package.json` of generated plugin
* Using project parent in generated POM, so explicit versions can be removed
* Removing explicit, ancient webpack dependency from generated `package.json`
* Adding `AutoValue` dependency due  to configured annotation processor
With these changes it should be easier to keep a plugin POM in line with the changes we make in core, as the POM will take over versions and certain configurations from the `graylog-plugin-web-parent` module which is managed in core and used by our plugins as well.
To test the changes, please follow the [introductions](
https://github.com/Graylog2/graylog2-server/tree/master/graylog-plugin-archetype#development) on how to use a locally installed archetype.
=> Adapting plugin archetype to recent changes.

graylog2-web-interface/src/components/content-packs/ContentPackConstraints.jsx, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackConstraints.test.jsx.snap
Rename `plugin` column to `name` and default "Graylog" for the server-version.
The Constraints overview did have some ascetic drawbacks. The plugin column was always empty for the server.
Fixes #5217
=> Improve Content Pack Constraints Overview

graylog2-server/src/test/java/org/graylog2/plugin/inputs/util/ConnectionCounterTest.java, pom.xml
This updates netty to version 4.1.31.
Changelog: https://netty.io/news/2018/10/30/4-1-31-Final.html
We are currently running into the following test failure from time to time since we updated from 4.1.27 to 4.1.30.
```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.081 s <<< FAILURE! - in org.graylog2.plugin.inputs.util.ConnectionCounterTest
[ERROR] testConnectAndDisconnect(org.graylog2.plugin.inputs.util.ConnectionCounterTest)  Time elapsed: 1.077 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[1]L> but was:<[0]L>
at org.graylog2.plugin.inputs.util.ConnectionCounterTest.testConnectAndDisconnect(ConnectionCounterTest.java:87)
```
I hope this update with fix that. If not, we have to investigate.
=> Update netty to 4.1.31

graylog2-server/src/main/java/org/graylog2/rest/resources/system/contentpacks/ContentPackResource.java, graylog2-server/src/test/java/org/graylog2/rest/resources/system/contentpacks/ContentPackResourceTest.java, graylog2-web-interface/src/pages/ContentPacksPage.jsx, graylog2-web-interface/src/pages/ShowContentPackPage.jsx
Prevent deletion of content packs when installations of the content packs exists.
If the user deletes a content pack with installed entities, he will no be able to uninstall
the content pack entities after he deleted the content pack.
Created, installed, deleted (which failed), uninstalled, deleted.
=> Prevent content packs to be deleted if installations exists

graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/CollectorResource.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/CollectorService.java, graylog2-web-interface/src/components/sidecars/configuration-forms/CollectorForm.jsx, graylog2-web-interface/src/stores/sidecars/CollectorsStore.js
If a sidecar collector name is edited on an existing
collector and then changed back to its original name,
the validation would falsely claim that this collector
already exists.
We need to exclude ourself from the query.
=> Fix collector name validator when called on itself

graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodical.java
This change is logging the generic exception that is caught in the field types poller periodical, so a useful message is logged instead of a non-helpful one that signals an error, but does not explain what
happened.
=> Log exception when handling generic exception in field types poller.

graylog2-server/src/main/java/org/graylog2/alerts/AbstractAlertCondition.java, graylog2-server/src/main/java/org/graylog2/alerts/types/FieldContentValueAlertCondition.java, graylog2-server/src/main/java/org/graylog2/alerts/types/FieldValueAlertCondition.java, graylog2-server/src/main/java/org/graylog2/alerts/types/MessageCountAlertCondition.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/alerts/StreamAlertConditionResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/responses/AlertConditionTestResponse.java, graylog2-server/src/test/java/org/graylog2/alerts/AbstractAlertConditionTest.java, graylog2-server/src/test/java/org/graylog2/alerts/types/FieldContentValueAlertConditionTest.java
This exposes a new query config field in the alert condition
configuration. The value defaults to "*".
The query is used to build a filter string for the alert condition
search. We add the query string to the query filter for performance
reasons.
This PR also adds two API endpoints to test new and existing alert conditions.
Fixes #3966
**Attention:** This needs to be cherry-picked into 2.5 once merged
=> Make search query in alert conditions configurable in the UI

pom.xml
The netty update to 4.1.31 prevented TLS enabled inputs to start.
The newest netty-tcnative version fixes that.
Fixes #5263
Refs #5250
=> Update netty-tcnative to 2.0.19

graylog2-server/src/main/java/org/graylog2/alerts/AbstractAlertCondition.java, graylog2-server/src/main/java/org/graylog2/alerts/types/FieldContentValueAlertCondition.java, graylog2-server/src/main/java/org/graylog2/alerts/types/FieldValueAlertCondition.java, graylog2-server/src/main/java/org/graylog2/alerts/types/MessageCountAlertCondition.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/alerts/StreamAlertConditionResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/responses/AlertConditionTestResponse.java, graylog2-server/src/test/java/org/graylog2/alerts/AbstractAlertConditionTest.java, graylog2-server/src/test/java/org/graylog2/alerts/types/FieldContentValueAlertConditionTest.java
=> Make search query in alert conditions configurable in the UI (#5212)

graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/models/Collector.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/CollectorResource.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/CollectorService.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/SidecarCollectorEntity.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/SidecarCollectorFacadeTest.java, graylog2-server/src/test/resources/org/graylog2/contentpacks/sidecar_collectors.json, graylog2-web-interface/src/components/sidecars/configuration-forms/CollectorForm.jsx
Instead of a GUI option, we let the sidecar autogenerate the path
to ".../generated/<collector_name>.conf"
Add validations for the collector name, so it can be used as a filename.
=> Remove Sidecar collector configuration path

pom.xml
This updates the gelfclient version to latest 1.4.4 (includes Netty 4.1.31) in `master`.
=> Update gelfclient version to latest 1.4.4 (uses Netty 4.1.31)

graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/ThrottleableTransport.java
This change adds a few methods to ThrottlableTransport needed to support throttling in the AWS Log/FlowLogs inputs.
=> Add throttling to the AWS Flow Logs/Logs inputs

graylog2-web-interface/src/components/bootstrap/BootstrapModalForm.jsx, graylog2-web-interface/src/components/bootstrap/BootstrapModalForm.test.jsx, graylog2-web-interface/src/components/users/__snapshots__/UserPreferencesButton.test.jsx.snap
Before this change, the `BootstrapModalForm` component relied on the
consumer calling the `open`/`close` functions, which does not align well
with the way react is used declaratively.
This change leaves this functionality in place but also adds a `show`
property (being `false` by default) which allows to show a modal when
the property is `true`.
=> Allow showing/hiding BootstrapModalForm declaratively.

graylog2-server/src/main/java/org/graylog2/indexer/cluster/jest/RequestResponseLogger.java, graylog2-server/src/main/java/org/graylog2/indexer/cluster/jest/tasks/CancelTask.java, graylog2-server/src/main/java/org/graylog2/indexer/cluster/jest/tasks/GetTasks.java, graylog2-server/src/test/java/org/graylog2/ElasticsearchBase.java, graylog2-server/src/test/java/org/graylog2/ElasticsearchConfiguration.java, graylog2-server/src/test/java/org/graylog2/ElasticsearchRule.java, graylog2-server/src/test/java/org/graylog2/indexer/cluster/jest/tasks/GetTasksTest.java, graylog2-server/src/test/java/org/graylog2/indexer/cluster/jest/tasks/GetTasksTestIT.java, graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java, graylog2-server/src/test/java/org/graylog2/indexer/results/ScrollResultIT.java, graylog2-server/src/test/java/org/graylog2/indexer/searches/SearchesIT.java
In preparation to expose reindex capabilities, we need to be able to access the status of the long running tasks (to show progress) and also be able to cancel them.
related to #4958
=> Add Jest actions for use with ES Task API

graylog2-web-interface/src/components/content-packs/ContentPackSelection.jsx, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
Fix alignment of content pack selection by adding `lg` prop to all `Row`s.
The alignment of the input fields with the content pack selection was not proper.
=> Fix alignment of content pack selection

graylog2-web-interface/package.json, graylog2-web-interface/src/components/common/ClipboardButton.jsx, graylog2-web-interface/src/components/common/ClipboardButton.test.jsx, graylog2-web-interface/yarn.lock
Under some circumstances (e.g. when embedding a `ClipboardButton` in the
body of a modal dialog), copying a value does not work because it
requires the currently focussed container.
This change allows passing the current container to `ClipboardButton`,
therefore enabling it to work properly in e.g. modal dialogs.
=> Allow passing container prop to `ClipboardButton`.

graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/KeywordSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/RelativeSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/SearchResource.java
The default batch size in Elasticsearch is 10. We now use 500 as default
for the newly introduced "batch_size" parameter which we pass to the
search request as limit. (which is the batch size for scroll requests)
Previously we used the "limit" parameter for the batch size AND the
result limit. That was wrong and resulted in truncated results.
Fixes #5172
(cherry picked from commit a77756d54ce27bea15e921e0c75c0f34e19b1a40)
=> Fix slow CSV export by using a bigger default batch size

graylog2-server/src/main/java/org/graylog2/indexer/MongoIndexSet.java, graylog2-server/src/test/java/org/graylog2/indexer/MongoIndexSetTest.java
When updating to ES 6, user might have to reindex old indices which have
been created with ES 2. Since ES doesn't allow index renames, the
reindexed indices will have a different name that doesn't match the
current index patterns in the index set.
This change introduces another index name suffix that allows users to
reindex an old index and have the new index be detected as managed index
in the index set.
Users have to use the "_reindex_es<es-major-ver>" suffix when reindexing
into a new index.
Example: "graylog_0" becomes "graylog_0_reindex_es5" when the new index
is reindexed in ES 5.x.
Using the ES major version in the suffix allows users to reindex that
index again with a new ES major version.
=> Treat reindexed indices as managed indices in Graylog

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ips/IpAddressConversion.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/int2ipv4.txt
if the argument is a number, try to convert its intValue into an IP address
otherwise the previous behavior of taking the string value and converting that applies
fixes #5268
=> support for decimal IPv4 representation in to_ip

graylog2-web-interface/src/stores/search/SearchStore.test.jsx, graylog2-web-interface/src/stores/search/SearchStore.ts
The add search term button (eg. in the Quick Values view)
is adding search terms to the search bar. A search term
with spaces will be treated as a phrase and therefor will
only surrounded by double quotes. But those phrases did
not escape backslashes which is still needed to perform
the search.
Now phrases will also get the backslashes escaped.
Also: Add some tests for adding a search term.
Fixes #4111
Fixes #5266
(cherry picked from commit bfc4a9f8b325961c926ff51dfd2dc0972df21cec)
=> Fix Backslash Escaping for Phrase Searches (#4477)

graylog2-server/src/main/java/org/graylog2/audit/AuditEventTypes.java, graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexTemplatesResource.java
This might be used after an upgrade of Elasticsearch to ensure that the
latest index templates for the new Elasticsearch version get installed.
Needed when re-indexing old data in Elasticsearch.
=> Add API endpoint to get and update index templates in Elasticsearch

graylog2-web-interface/src/actions/alertconditions/AlertConditionsActions.jsx, graylog2-web-interface/src/components/alertconditions/AlertCondition.jsx, graylog2-web-interface/src/components/alertconditions/AlertConditionTestModal.css, graylog2-web-interface/src/components/alertconditions/AlertConditionTestModal.jsx, graylog2-web-interface/src/components/alertconditions/index.jsx, graylog2-web-interface/src/routing/ApiRoutes.js, graylog2-web-interface/src/stores/alertconditions/AlertConditionsStore.js
The last changes in the alerting API introduced an endpoint to test alert conditions. This PR adds UI for it, so users can test if a certain alert condition would trigger an alert or not at that point of time.
This needs to be cherry-picked into 2.5.
=> Add test button to alert conditions

graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/ThrottleableTransport.java
* Add blockUntilUnthrottled method with timeout
This allows an input to block while throttled during a timeout period. If the block latch is not cleared in the timeout period, the latch will expire and allow execution to proceed.
* Add throttled state change callback
* Document return for method ThrottleableTransport.blockUntilUnthrottled()
* Fixed documentation typo
(cherry picked from commit 72c6126d29ecb366a3f02a854362ec51c2a31c7c)
=> Add throttling to the AWS Flow Logs/Logs inputs (#5218)

graylog2-web-interface/src/actions/alertconditions/AlertConditionsActions.jsx, graylog2-web-interface/src/components/alertconditions/AlertCondition.jsx, graylog2-web-interface/src/components/alertconditions/AlertConditionTestModal.css, graylog2-web-interface/src/components/alertconditions/AlertConditionTestModal.jsx, graylog2-web-interface/src/components/alertconditions/index.jsx, graylog2-web-interface/src/routing/ApiRoutes.js, graylog2-web-interface/src/stores/alertconditions/AlertConditionsStore.js
* Add test button to alert conditions
* Add icon to easily see when alert would trigger
To help users easily see whether a condition would trigger the alert or
not, add a small icon that gives a visual hint to what would happen.
* Change dropdown menu text for consistency
(cherry picked from commit 2874b995b6f01aa4acb76e0265f8a6c36c92915a)
=> Add test button to alert conditions (#5316)

graylog2-server/src/test/java/org/graylog2/plugin/inputs/util/ConnectionCounterTest.java
Should fix a NullPointerException seen on Jenkins:
```
java.lang.NullPointerException
at org.graylog2.plugin.inputs.util.ConnectionCounterTest.testConnectAndDisconnect(ConnectionCounterTest.java:112)
```
=> Fix flaky ConnectionCounterTest by waiting for serverChannel to be set

graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
After #5079, only the system admin user was allowed to see all user
details.
This change also allows other admin users to do the same, while still
blocking regular users to see anything but their own user details.
Fixes #5325
Cherry pick from #5326
=> Add permissions to all admins to see user details (#5326)

graylog2-server/src/main/java/org/graylog2/indexer/MongoIndexSet.java, graylog2-server/src/test/java/org/graylog2/indexer/MongoIndexSetTest.java
This also includes the legacy "restored_archive" indices in the
automatic retention. That should be okay because archives are restored
into a separate index set for some time now.
Fixes #5337
=> Include re-indexed indices in index retention

graylog2-server/src/main/java/org/graylog2/indexer/MongoIndexSet.java, graylog2-server/src/test/java/org/graylog2/indexer/MongoIndexSetTest.java
This has some unintended consequences and we need a bigger change to
properly support re-indexed indices.
This reverts commit ccb2954ee043599dbfb238d467c9fe423cea0a91.
=> Revert "Include re-indexed indices in index retention (#5340)"

graylog2-web-interface/src/components/common/IfPermitted.test.jsx, graylog2-web-interface/src/util/PermissionsMixin.js, graylog2-web-interface/src/util/PermissionsMixin.test.js
Before this change, passing `undefined` for the permission set that
`isPermitted`/`isAnyPermitted` check against, both functions would throw
an exception.
After this change, both functions return proper results based on the set
of required permissions. If it is empty, the functions return `true`, if
it is non-empty, both return `false`.
Fixes #5193.
=> Guarding against `undefined` in `isPermitted`/`isAnyPermitted`.

misc/graylog.conf
Definition provided in context of web endpoint is vague as REST is not clarified.
We spent way too long chasing `rest_transport_uri` and `rest_listen_uri` as solutions to what controlled what was promoted into the browser for REST calls. Searching "REST" in the config misses `web_endpoint_uri`.
=> clarify definition of `web_endpoint_uri`

graylog2-server/src/main/java/org/graylog2/rest/resources/system/contentpacks/ContentPackResource.java, graylog2-web-interface/src/pages/ShowContentPackPage.jsx
If the user requests a content pack which is not there anymore we now redirect to the
content packs overview.
If a user deleted the last content pack the show content pack site was throwing an error.
Removing the last revision of an content pack.
=> Redirect to content pack overview if no content pack can be found

graylog2-web-interface/webpack.config.js
This makes it easier to grep for a certain style in our code.
See https://github.com/webpack-contrib/css-loader#localidentname
=> Use nicer local css style class names for development

graylog2-server/src/main/java/org/graylog2/contentpacks/facades/DashboardFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/GrokPatternFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/InputFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupCacheFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupDataAdapterFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupTableFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/OutputFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/PipelineFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/PipelineRuleFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorConfigurationFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/StreamFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/ModelId.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/EntityV1.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/DashboardFacadeTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/GrokPatternFacadeTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/InputFacadeTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/LookupCacheFacadeTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/LookupDataAdapterFacadeTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/LookupTableFacadeTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/OutputFacadeTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/PipelineFacadeTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/PipelineRuleFacadeTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/SidecarCollectorFacadeTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/StreamCatalogTest.java, graylog2-web-interface/webpack/vendor-module-ids.json
A Entity has now a complete random ID unrelated to the NativeEntity from which it was created.
That way it we must ensure that our code must work without any relation to the native entity.
The code relied on finding a matching entity id from the native entity id from the server. But
this can't work since the content pack could run on any system other then the one it was created
on.
I rebased the change to #5203 and created and edited a content pack.
=> Create random ids for Entities in Content Packs

graylog2-web-interface/src/components/common/ExpandableListItem.css, graylog2-web-interface/src/components/common/ExpandableListItem.jsx, graylog2-web-interface/src/components/common/__snapshots__/ExpandableList.test.jsx.snap, graylog2-web-interface/src/components/content-packs/ContentPackEdit.jsx, graylog2-web-interface/src/components/content-packs/ContentPackEntitiesList.jsx, graylog2-web-interface/src/components/content-packs/ContentPackParameters.test.jsx, graylog2-web-interface/src/components/content-packs/ContentPackSelection.css, graylog2-web-interface/src/components/content-packs/ContentPackSelection.jsx, graylog2-web-interface/src/components/content-packs/ContentPackSelection.test.jsx, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap, graylog2-web-interface/src/logic/content-packs/ContentPack.js, graylog2-web-interface/src/logic/content-packs/Entity.jsx, graylog2-web-interface/src/logic/content-packs/EntityIndex.js, graylog2-web-interface/src/pages/CreateContentPackPage.jsx, graylog2-web-interface/src/pages/EditContentPackPage.jsx, graylog2-web-interface/src/stores/content-packs/CatalogStore.jsx
When selecting the entities for a new version of a content pack, we now offer the previous entities of the
content pack. That way a user can modify the original content pack without having the original entities on his system.
When creating a new version of the content pack the user sees now icons behind the entities to distinguish between entities from the server (blue) and original entities from the content pack.
Before when editing a content pack you needed the original entities on your system other wise the
selection would not work, since Graylog could not find them in the database. 
Created a new content pack, and created a new version for it.
=> Keep Content Pack entities when creating a new version

graylog2-web-interface/webpack/vendor-module-ids.json
During two dependency updates (#5247 & #5380), a change to the vendor bundle module ids of our webpack build fell through. This change is updating it accordingly.
=> Updating module ids of vendor bundle.

graylog2-server/src/main/java/org/graylog2/contentpacks/facades/StreamFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/NativeEntityDescriptor.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/StreamAlarmCallbackEntity.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/StreamAlertConditionEntity.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/StreamEntity.java, graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackServiceTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/DashboardFacadeTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/StreamCatalogTest.java
Since both are bound to streams I decided to put them into the stream entity for now.
I also fixed the following smaller issues:
- Avoid NullPointerException for stream rule fileds
- Fix javadoc comment
Fixes #1758
=>  Include alert conditions and alarm callbacks in content packs

graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java, graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java, graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesIT.java
The parameter has been removed from Elasticsearch about 2.5 years ago
before the release of 5.0 and requests have it will fail.
This hasn't been noticed so far because it only happens when the
Indices#move() method runs. That method is only called by the
FixDeflectorByMoveJob periodical. The job doesn't run that often,
apparently.
Also the only test that is using it is the MessagesIT test and that is
using "assumeTrue()" so it doesn't fail but gets skipped.
=>  Remove nonexistent "consistency" parameter from index/bulk requests

graylog2-server/pom.xml, pom.xml
Having BC as a crypto provider offers several advantages over JCE.
Most importantly, it supports keys in PKCS#1 format, which is
still widely used, and the default output of `openssl genrsa`.
=> Add Bouncy Castle dependency

graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/ObjectMapperProvider.java, graylog2-server/src/test/java/org/graylog2/shared/bindings/providers/SerializeSubtypedOptionalPropertiesTest.java
This change allows deserializing classes which fulfill the following:
* They contain a property `V` which is subtyped
* They contain an additional property `T` defining the type of the
property `V` (and maybe the types of additional properties or of the
class itself)
* `V` is optional, so it might be present or not
* `T` is always present
The important point is the optionality of `V`. Jackson assumes that if a property that is used as an external property with `@JsonTypeInfo` is present, that the property annotated with `@JsonTypeInfo` must be present as well. This is not always the case, especially when `T` is used to indicate of the class itself and `V`'s type depends on `T` but the property itself is optional.
This change is disabling Jackson's …
=> Avoid failing JSON deser. if ext. type is present, but prop is not.

graylog2-server/src/main/java/org/graylog2/contentpacks/facades/GrokPatternFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/InputFacade.java, graylog2-server/src/main/java/org/graylog2/grok/GrokPatternService.java, graylog2-server/src/main/java/org/graylog2/inputs/InputServiceImpl.java, graylog2-server/src/main/java/org/graylog2/inputs/extractors/GrokExtractor.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/InputFacadeTest.java, graylog2-server/src/test/resources/org/graylog2/contentpacks/inputs.json
Add support to the InputFacade for resolving grok pattern extractors in inputs.
If a user wants to add a input to a content pack with a grok extractor he also wants the
grok extractor as part of the content pack.
Created a new content pack, edit it, installed and uninstalled it.
The Grok Patterns get uninstalled even though a installation exists. This will be
addressed by a different issue (Refs #5399)
Fixes: #5273
=> Content Pack Dependency Resolution for Grok Extractors in Inputs

graylog2-web-interface/package.json, graylog2-web-interface/yarn.lock
After a few months of waiting, Bootstrap 3.4.0 is out and fixes the XSS issues reported in #4603.
The list of changes is from the [release blog post](https://blog.getbootstrap.com/2018/12/13/bootstrap-3-4-0/) is:
>New: Added a .row-no-gutters class.
New: Added docs searching via Algolia.
Fixed: Resolved an XSS issue in Alert, Carousel, Collapse, Dropdown, Modal, and Tab components. See https://snyk.io/vuln/npm:bootstrap:20160627 for details.
Fixed: Added padding to .navbar-fixed-* on modal open
Fixed: Removed the double border on <abbr> elements.
Removed Gist creation in web-based Customizer since anonymous gists were disabled long ago by GitHub.
Removed drag and drop support from Customizer since it didn’t work anymore.
=> Upgrade to Bootstrap 3.4.0

pom.xml
Bugfix release. See changelog:
https://netty.io/news/2018/11/29/4-1-32-Final.html
=> Update to netty 4.1.32 and netty-tcnative-boringssl 2.0.20

pom.xml
Contains fixes for:
CVE-2018-14718
CVE-2018-14721
CVE-2018-19360
CVE-2018-19361
CVE-2018-19362
See the following page for details:
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8
=> Security update to jackson 2.8.11.3 (bom 2.8.11.20181123)

graylog2-server/src/main/java/org/graylog2/indexer/MongoIndexSet.java, graylog2-server/src/main/java/org/graylog2/indexer/NoTargetIndexException.java
Logging a NoTargetIndexException would throw a NullPointerException
because there is no message string.
=> Add message to NoTargetIndexException to avoid NPE in logging

graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.jsx
After merging PR #5376 the collectorId was not updated on the ConfigurationForm in the state anymore when a collector backend was selected in the drop-down. This leads to an error when a fresh configuration is created.
See also:
https://github.com/Graylog2/graylog2-server/pull/5376#discussion_r239521862
We dont exit the _onCollectorChange() function anymore before collectorId and template is updated.
=> Fix regression that came in with PR #5376

graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/InputsResource.java, graylog2-server/src/main/java/org/graylog2/shared/inputs/InputDescription.java, graylog2-server/src/test/java/org/graylog2/rest/resources/system/inputs/InputsResourceMaskingPasswordsTest.java
Before this change, input details returned by the REST API would contain
all configuration fields without any modification. This implies that
password fields are also contained using their original value, showing
configured password for inputs in clear text.
For users which are not allowed to edit an input, this change now iterates over configuration fields checking for the presence of password fields and replace their content with `<password set>` instead of the original value if they are not empty.
For users which possess the required permission to edit an input, the original value is returned as it is used to set the value of the password field and would be used for updating the input if left unchanged.
This is a middle ground between a quick fix improving the situation (not everybody …
=> Mask password fields of inputs returned by the REST API.

graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/InputsResource.java
This change is fixing an import in #5464 that was accidentally imported from a shaded dependency.
=> Fixing package name of incorrect import from shaded dependency.

graylog2-web-interface/src/components/enterprise/PluginList.css, graylog2-web-interface/src/components/enterprise/PluginList.jsx, graylog2-web-interface/src/pages/EnterprisePage.jsx
The plugin list in the _System -> Enterprise_ page was outdated, since we now ship all enterprise modules in a single plugin. This PR takes care of correcting that and fixes a few linter issues we had in there.
Fixes #4600
=> Update plugin list in System -> Enterprise page

graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/InputsResource.java, graylog2-server/src/main/java/org/graylog2/shared/inputs/InputDescription.java, graylog2-server/src/test/java/org/graylog2/rest/resources/system/inputs/InputsResourceMaskingPasswordsTest.java
Before this change, input details returned by the REST API would contain
all configuration fields without any modification. This implies that
password fields are also contained using their original value, showing
configured password for inputs in clear text.
For users which are not allowed to edit an input, this change now iterates over configuration fields checking for the presence of password fields and replace their content with `<password set>` instead of the original value if they are not empty.
For users which possess the required permission to edit an input, the original value is returned as it is used to set the value of the password field and would be used for updating the input if left unchanged.
This is a middle ground between a quick fix improving the situation (not everybody …
=> Mask password fields of inputs 3.0

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/SimulatorResource.java
This small change is correcting the import of the `Strings` helper class
used for the `isNullOrEmpty` method, which is incorrectly imported from
an elastic bundle instead of guava.
=> Fixing imports of `Strings.isNullOrEmpty`.

graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.jsx
The collectorId was not stored in the state anymore. (#5452)
This leads to an error when a fresh configuration is created.
(cherry picked from commit e3bab118317a9901f615d036065d6acbfc6dc50c)
=> Fix regression that came in with PR #5376.

graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationHelper.jsx
Make Runtime Variables the default tab as its filled with some data even on empty systems.
=> Change tab order on collector configuration page.

graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationHelper.jsx
Make Runtime Variables the default tab as its filled with some data even on empty systems.
=> Configuration tab order

graylog2-web-interface/src/components/content-packs/ContentPackEditParameter.jsx, graylog2-web-interface/src/components/content-packs/ContentPackEditParameter.test.jsx, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEditParameter.test.jsx.snap
Prior to this change, the type of a parameter could be changed
which led to problems if the parameter was already applied to
configuration values. Since the value type and the parameter type
must match.
This change will prevent the change of a parameter type. If the user
wishes the change of a parameter type, he has to delete and recreate
a parameter.
Fixes #5404 
Needs backport to [3.0](https://github.com/Graylog2/graylog2-server/milestone/57)
Edit a content pack with parameters and tried to change the type. Also I add a new
parameter where I was still able to change the parameter.
=> Disable content pack parameter type when editing

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/SimulatorResource.java
This small change is correcting the import of the `Strings` helper class
used for the `isNullOrEmpty` method, which is incorrectly imported from
an elastic bundle instead of guava.
(cherry picked from commit 1135db2aa6e67b6478f87200f0787a9d85bc32f5)
=> Fixing imports of `Strings.isNullOrEmpty`. (#5469)

graylog2-web-interface/src/components/content-packs/ContentPackEditParameter.jsx, graylog2-web-interface/src/components/content-packs/ContentPackEditParameter.test.jsx, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEditParameter.test.jsx.snap
Prior to this change, the type of a parameter could be changed
which led to problems if the parameter was already applied to
configuration values. Since the value type and the parameter type
must match.
This change will prevent the change of a parameter type. If the user
wishes the change of a parameter type, he has to delete and recreate
a parameter.
Fixes #5404 
(cherry picked from commit 2b661454ef392246bc18bdcfc7760b06cd54bf69)
=> Disable content pack parameter type when editing (#5460)

graylog2-web-interface/src/components/content-packs/ContentPackApplyParameter.jsx, graylog2-web-interface/src/components/content-packs/ContentPackApplyParameter.test.jsx, graylog2-web-interface/src/components/content-packs/ContentPackEntitiesList.css, graylog2-web-interface/src/components/content-packs/ContentPackEntitiesList.jsx, graylog2-web-interface/src/components/content-packs/ContentPackEntitiesList.test.jsx, graylog2-web-interface/src/components/content-packs/ContentPackParameterList.jsx, graylog2-web-interface/src/components/content-packs/ContentPackParameterList.test.jsx, graylog2-web-interface/src/components/content-packs/ContentPackParameters.jsx, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackApplyParameter.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntitiesList.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameterList.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameters.test.jsx.snap, graylog2-web-interface/src/logic/content-packs/ContentPack.js, graylog2-web-interface/src/logic/content-packs/Entity.jsx, graylog2-web-interface/src/pages/CreateContentPackPage.jsx, graylog2-web-interface/src/pages/EditContentPackPage.jsx
We now prevent clearing a parameter, when the parameter was applied in a former version
of the content pack.
Since we do not have the original value of the config key in the entity we can't replace a parameter.
In the future we might solve this by asking the user, but this is not as easy as it sounds without
confusing the user.
- Created a content pack with applied parameter
- Created a new version and tried to clear the parameter.
Prevent deletion of used parameters and display usage and origin of a parameter.
Fixes #5426
=> Prevent clearing of parameters origin from Content Pack

graylog2-web-interface/src/components/content-packs/ContentPackEntitiesList.jsx, graylog2-web-interface/src/components/content-packs/ContentPackInstall.jsx, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap
Prior this change, the title of an entity was missing
when clicking on install from content pack list.
This change will convert the content pack hash to
a content pack object to access the title easy
via getter.
Fixes: #5423
=> Display entity title in installation modal

graylog2-server/src/main/java/org/graylog/plugins/beats/Beats2Codec.java, graylog2-server/src/test/java/org/graylog/plugins/beats/Beats2CodecTest.java
This field got inherited from the legacy Beats input.
Since the new input is breaking backwards compat anyway, this is a good
time to remove it.
There are enough metadata fields sent by beats, which makes that field
quite redundant.
Fixes #5421
=> Stop autofilling 'facility' field in new Beats input

graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
We don't ship filebeat in the linux sidecar packages anymore.
Adopt the path to the elastic beats package.
Refs https://github.com/Graylog2/collector-sidecar/pull/326
=> Change default linux filebeat path

graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/responses/RegistrationResponse.java
The response returned the SidecarRegistrationConfiguration as
`collector_registration_configuration` while the sidecar
expects this as `configuration`
Fixes #5487
=> Add correct @JsonProperty for RegistrationResponse

graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/responses/RegistrationResponse.java
* Add correct @JsonProperty for RegistrationResponse
The response returned the SidecarRegistrationConfiguration as
`collector_registration_configuration` while the sidecar
expects this as `configuration`
Fixes #5487
* Rename method to match property
(cherry picked from commit bae6d2b5316f553f39e1f3497b594b121d0bcac0)
=> Add correct @JsonProperty for RegistrationResponse (#5502)

graylog2-server/src/main/java/org/graylog2/inputs/transports/HttpTransport.java
The "HttpContentDecompressor" handler needs to run before the
"HttpObjectAggregator" in the pipeline so the aggregator can handle
compressed requests.
This fixes a 404 response when sending compressed payloads to the input.
Fixes #5143
**Note:** This needs to be cherry-picked into 3.0
=> Fix GELF HTTP input to accept compressed payloads again

graylog2-server/src/main/java/org/graylog2/inputs/transports/netty/HttpHandler.java
Call "#retain()" on the buffer that we pass on to other handlers to
avoid a IllegalReferenceCountException:
Error in Input [GELF HTTP/5c35eca53d274637c3007582] (channel [id:
0xc4d569f2, L:/127.0.0.1:12201 ! R:/127.0.0.1:37774]) (cause
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1)
Fixes #5503
**Note:** This needs to be cherry-picked into 3.0
=> Fix IllegalReferenceCountException in GELF HTTP input

graylog2-server/src/main/java/org/graylog2/inputs/transports/HttpTransport.java
The "HttpContentDecompressor" handler needs to run before the
"HttpObjectAggregator" in the pipeline so the aggregator can handle
compressed requests.
This fixes a 404 response when sending compressed payloads to the input.
Fixes #5143
(cherry picked from commit 7f09ec447b407dc9461aef5e2245f77612b2643c)
=> Fix GELF HTTP input to accept compressed payloads again (#5513)

graylog2-web-interface/src/components/widgets/Widget.jsx
Deleting a widget from a dashboard resulted in `_calculateWidgetSize()` being called endlessly, as the check we had for an empty widget DOM node did not work as expected.
This PR rewrites that check to ensure we can detect this situation and not update the state. Additionally it disables the widget size calculation when a widget is marked as deleted, as it is not needed at that stage.
Fixes #5498
=> Fix endless loop after deleting a widget from a dashboard

graylog2-web-interface/src/components/widgets/WidgetCreationModal.jsx, graylog2-web-interface/src/components/widgets/WidgetCreationModal.test.jsx, graylog2-web-interface/src/components/widgets/configurations/CountWidgetCreateConfiguration.jsx, graylog2-web-interface/src/components/widgets/configurations/QuickValuesHistogramWidgetCreateConfiguration.jsx, graylog2-web-interface/src/components/widgets/configurations/QuickValuesWidgetCreateConfiguration.jsx, graylog2-web-interface/src/components/widgets/configurations/StatisticalCountWidgetCreateConfiguration.jsx
Due to performance improvements in 3.0, components rendered inside a modal are now only mounted when they will be visible. That broke the way that `WidgetCreationModal` extends its initial state with custom configuration set in plugins, as it required components to be mounted when the modal was opened and this is no longer the case. It is also not easy to know when custom components are mounted to get their initial configuration, so we need to change our approach to make this work reliably.
This PR changes how custom create configuration can set their initial configuration. There are two ways of achieving this:
- Set the `initialConfiguration` static property
This is the preferred way of setting initial configuration, and it is used by most of our components extending the widget creation …
=> Fix widget creation modal with custom configuration

graylog2-web-interface/src/components/widgets/Widget.jsx
Deleting a widget from a dashboard resulted in _calculateWidgetSize() being called endlessly, as the check we had for an empty widget DOM node did not work as expected.
This PR rewrites that check to ensure we can detect this situation and not update the state. Additionally it disables the widget size calculation when a widget is marked as deleted, as it is not needed at that stage.
Fixes #5498.
Backport of #5500.
=> Fix endless loop after deleting a widget from a dashboard (#5500)

graylog2-web-interface/src/components/widgets/WidgetCreationModal.jsx, graylog2-web-interface/src/components/widgets/WidgetCreationModal.test.jsx, graylog2-web-interface/src/components/widgets/configurations/CountWidgetCreateConfiguration.jsx, graylog2-web-interface/src/components/widgets/configurations/QuickValuesHistogramWidgetCreateConfiguration.jsx, graylog2-web-interface/src/components/widgets/configurations/QuickValuesWidgetCreateConfiguration.jsx, graylog2-web-interface/src/components/widgets/configurations/StatisticalCountWidgetCreateConfiguration.jsx
* Use JSX to create custom configuration element.
* Fix linter errors
* Fix widget creation modal with custom config
Due to performance improvements in 3.0, components rendered inside a modal
are only mounted when they will be visible. That broke the way that
`WidgetCreationModal` extends its initial state with custom configuration
set in plugins, as it required components to be mounted when the modal was
opened and this is no longer the case. It is also not easy to know when
custom components are mounted to get their initial configuration, so
we need to make this code more robust to make this work reliable.
This commit changes how custom create configuration can set their
initial configuration. There are two ways of achieving this:
- Set the `initialConfiguration` static property
This is …
=> Fix widget creation modal with custom configuration (#5510)

graylog2-server/src/main/java/org/graylog2/inputs/transports/netty/HttpHandler.java
Call "#retain()" on the buffer that we pass on to other handlers to
avoid a IllegalReferenceCountException:
Error in Input [GELF HTTP/5c35eca53d274637c3007582] (channel [id:
0xc4d569f2, L:/127.0.0.1:12201 ! R:/127.0.0.1:37774]) (cause
io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1)
Fixes #5503
(cherry picked from commit 95c117ca4fecd1531a314d90e46cf5eb7629e816)
=> Fix IllegalReferenceCountException in GELF HTTP input (#5514)

graylog2-server/src/main/java/org/graylog2/inputs/transports/UdpTransport.java, graylog2-server/src/main/java/org/graylog2/inputs/transports/netty/ByteBufMessageAggregationHandler.java, graylog2-server/src/main/java/org/graylog2/inputs/transports/netty/EnvelopeMessageAggregationHandler.java, graylog2-server/src/main/java/org/graylog2/inputs/transports/netty/EnvelopeMessageHandler.java, graylog2-server/src/main/java/org/graylog2/inputs/transports/netty/SenderEnvelope.java, graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java, graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/NettyTransport.java
This fixes an issue that has been introduced with the big Netty 4.1
update in PR #4397.
In Netty 3.x we always passed a "MessageEvent" through the channel
pipeline and got the remote address from that object. Since this object
doesn't exist anymore in Netty 4.x, we only pass the message payload's
"ByteBuf" through the pipeline and rely on the "Channel#getRemoteAddress"
method to always return the remote address object.
The problem is that this does indeed work for TCP based channels but it
doesn't work for UDP based channels. For UDP channels the
"#getRemoteAddress()" method always returns "null".
This is probably due to the connection-less nature of UDP.
For UDP transports Netty only creates a single channel. For TCP transports
there is one channel per TCP connection
To fix this we need …
=> Fix missing "source" field for UDP transport based messages (#5512)

graylog2-server/src/main/java/org/graylog2/inputs/transports/AmqpConsumer.java
Before this change, the `AMQPConsumer`, triggered by a connection
shutdown callback, tried to reconnect to the broker, supposedly because
the library did not support auto recovery at the time of implementation.
Current version of the rabbit AMQP client library do support it and in
the version used it is enabled per default. This lead to creating
another connection needlessly, wasting resources and leaving one of the
connections in a state that it is operating on a closed channel,
therefore throwing an exception and NACKing the first incoming
exception, ceasing operation afterwards. Also, stopping an input after it
was reconnected at least once left a number of dangling threads that were
still connected to the broker.
This change is doing these things to improve the situation:
* Enable …
=> Removing own AMQP reconnecting in favor of the library's.

graylog2-web-interface/webpack.config.js
Due to a bug in uglify-js 3.4.9, compressing conditionals during asset minimization is broken, leading to #5450.
This commit disables conditionals compression until we can test it is fixed in a future uglify-js release.
There are several reports in the upstream project, one of them is: https://github.com/mishoo/UglifyJS2/issues/3269
Fixes #5450
=> Fix assets compression on production builds

graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/models/Collector.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/CollectorResource.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/ConfigurationResource.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/ConfigurationVariableResource.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/CollectorService.java, graylog2-web-interface/src/components/sidecars/configuration-forms/CollectorForm.jsx, graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.jsx, graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationVariablesHelper.jsx, graylog2-web-interface/src/components/sidecars/configuration-forms/EditConfigurationVariableModal.jsx, graylog2-web-interface/src/components/sidecars/configurations/CollectorList.jsx, graylog2-web-interface/src/components/sidecars/configurations/CollectorListContainer.jsx, graylog2-web-interface/src/components/sidecars/configurations/CollectorRow.jsx, graylog2-web-interface/src/components/sidecars/configurations/ConfigurationListContainer.jsx, graylog2-web-interface/src/components/sidecars/configurations/ConfigurationRow.jsx, graylog2-web-interface/src/components/sidecars/configurations/CopyCollectorModal.jsx, graylog2-web-interface/src/components/sidecars/configurations/CopyConfigurationModal.jsx, graylog2-web-interface/src/stores/sidecars/CollectorConfigurationsStore.js, graylog2-web-interface/src/stores/sidecars/CollectorsStore.js, graylog2-web-interface/src/stores/sidecars/ConfigurationVariableStore.js
Sidecar validates most entities on the server side. This PR cleans up the code there and brings the API calls in a consistent state. It also adds validations for empty fields. Collector names now are unique per operating systems. This allows to have a `nxlog` collector for linux as well as for windows as an example.
=> Improve Sidecar API validations

graylog2-web-interface/webpack.config.js
The `sourceMap` option should be passed to the `UglifyJsPlugin` configuration: https://webpack.js.org/plugins/uglifyjs-webpack-plugin/#sourcemap
Fixes #5528
=> Enable source maps in production builds

graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/models/Collector.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/CollectorResource.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/ConfigurationResource.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/ConfigurationVariableResource.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/CollectorService.java, graylog2-web-interface/src/components/sidecars/configuration-forms/CollectorForm.jsx, graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.jsx, graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationVariablesHelper.jsx, graylog2-web-interface/src/components/sidecars/configuration-forms/EditConfigurationVariableModal.jsx, graylog2-web-interface/src/components/sidecars/configurations/CollectorListContainer.jsx, graylog2-web-interface/src/components/sidecars/configurations/CollectorRow.jsx, graylog2-web-interface/src/components/sidecars/configurations/ConfigurationListContainer.jsx, graylog2-web-interface/src/components/sidecars/configurations/ConfigurationRow.jsx, graylog2-web-interface/src/components/sidecars/configurations/CopyCollectorModal.jsx, graylog2-web-interface/src/components/sidecars/configurations/CopyConfigurationModal.jsx, graylog2-web-interface/src/stores/sidecars/CollectorConfigurationsStore.js, graylog2-web-interface/src/stores/sidecars/CollectorsStore.js, graylog2-web-interface/src/stores/sidecars/ConfigurationVariableStore.js
* Improve collector validation
* Respect that collectors can exists with the same name if the operating system differs
* To be consistend with other API validation resources:
* Use POST instead of GET
* Return build-in ValidationResult instead of custom ValidationResponse
* Expect full object as validation input instead of single attributes
* Add basic validation for special characters in executable path
* Prevent undefined help string
* Reset collector ID to prevent clones with same name like currently
* Add validation for OS dependent service_type check
* Prevent uncontrolled input warning
* Allow : to fix windows paths
* Adopt CollectorConfiguration to common validation pattern
* Remove unused variable
* Move validation back to CollectorListContainer to keep server access at one place …
=> Improve Sidecar API validations (#5495)

graylog2-web-interface/webpack.config.js
Due to a bug in uglify-js 3.4.9, compressing conditionals during asset
minimization is broken, leading to #5450.
This commit disables conditionals compression until we can test it is fixed
in a future uglify-js release.
There are several reports in the upstream project, one of them is:
https://github.com/mishoo/UglifyJS2/issues/3269
Fixes #5450
Backport of #5527
=> Fix assets compression on production builds (#5527)

graylog2-web-interface/webpack.config.js
The `sourceMap` option should be passed to the `UglifyJsPlugin`
configuration:
https://webpack.js.org/plugins/uglifyjs-webpack-plugin/#sourcemap
Fixes #5528
Backport of #5530
=> Enable source maps in production builds (#5530)

graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
For filebeat use the directory structure under
`/var/lib/graylog-sidecar/collectors/...`
which we will probably reccomend in the future.
For nxlog, stick to the directories provided
by the official package, because it does not create
missing directories on startup.
Refs https://github.com/Graylog2/collector-sidecar/issues/331
=> Change default collector configs

graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
Collectors uniqeness is now checked by combining the name
with the nodeOperatingSystem.
Change the migration to allow two "nxlog" collectors:
One for linux and one for windows.
=> Run default collector migration with nodeOperatingSystem

graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
For filebeat use the directory structure under
`/var/lib/graylog-sidecar/collectors/...`
which we will probably reccomend in the future.
For nxlog, stick to the directories provided
by the official package, because it does not create
missing directories on startup.
(cherry picked from commit 13dd0fff67d95e15f6addc66cadec06c8c61e4ea)
=> Change default collector configs (#5531)

graylog2-server/src/main/java/org/graylog/plugins/beats/Beats2Codec.java, graylog2-server/src/test/java/org/graylog/plugins/beats/Beats2CodecTest.java
This option was added to keep the Beats backwards compatible.
Later it was decided to fork the Beats input altogether,
so we don't have to worry about breaking compatibility.
Therefore invert and enable the Beats prefix option by default
on the new input.
Having the prefix avoids field collisions.
One example is that filebeat would fill the `source` field to the
filename, not to the hostname, which is more Graylog like.
Refs https://github.com/Graylog2/graylog-plugin-beats/pull/29
=> Invert "add beats prefix" option

graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackInstallationPersistenceService.java, graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackService.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupCacheFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupDataAdapterFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/NativeEntity.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/NativeEntityDescriptor.java, graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackInstallationPersistenceServiceTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackServiceTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/DashboardFacadeTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/GrokPatternFacadeTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/LookupCacheFacadeTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/LookupDataAdapterFacadeTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/SidecarCollectorFacadeTest.java, graylog2-server/src/test/resources/org/graylog2/contentpacks/ContentPackInstallationPersistenceServiceTest.json
This PR will protect used content pack entities from removal through uninstall if they are either
still in use bye a other content pack installation, or were on the system before installing a content
pack.
If a content pack would delete all its entities, other installations would stop working, since we 
can't install the same grok pattern twice.
1. Create a grok pattern (as it exists in the default grok pattern)
2. installed default pattern
3. install a content pack using a pattern from the default content pack
4. uninstall the last content pack
5. check that grok pattern is still there
6. Uninstall default grok patterns
7 check that grok pattern is still there 
Fixes: #5399
=> Protect used content pack entities from uninstall

graylog2-server/src/main/java/org/graylog/plugins/beats/Beats2Codec.java, graylog2-server/src/test/java/org/graylog/plugins/beats/Beats2CodecTest.java
This option was added to keep the Beats backwards compatible.
Later it was decided to fork the Beats input altogether,
so we don't have to worry about breaking compatibility.
Therefore invert and enable the Beats prefix option by default
on the new input.
Having the prefix avoids field collisions.
One example is that filebeat would fill the `source` field to the
filename, not to the hostname, which is more Graylog like.
(cherry picked from commit c06363b88e6053a407066cea518758fa7639c05c)
=> Invert "add beats prefix" option (#5537)

graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministrationFilters.jsx, graylog2-web-interface/src/logic/sidecar/SidecarStatusEnum.js
- Use the updated values in the status filter
- Convert string to number before comparing status
Fixes #5471
Backport of #5541
=> Fix collector status filter in admin page (#5541)

graylog2-web-interface/src/components/content-packs/ContentPackEdit.jsx, graylog2-web-interface/src/components/content-packs/ContentPackEntitiesList.test.jsx, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntitiesList.test.jsx.snap, graylog2-web-interface/src/logic/content-packs/ContentPack.js, graylog2-web-interface/src/logic/content-packs/Entity.jsx, graylog2-web-interface/src/pages/CreateContentPackPage.jsx, graylog2-web-interface/src/util/ValueRefHelper.js, graylog2-web-interface/src/util/ValueReferenceData.test.js
Prior to this change, a entity with a parameter as title
did display the parameter name as a title.
This change tries to get the default value of the parameter
to display as title. If no default value is given
the fallback is still the name of the parameter.
Fixes #5332
=> Use default_value of parameter for entity title

graylog2-web-interface/src/legacy/Rickshaw.Graph.Graylog2Selector.js, graylog2-web-interface/src/legacy/result-histogram.js
When a user was searching in "All messages" using a query that returned no results, immediately
followed by a query that did, extracting the timerange for the histogram resulted in an
exception. This happened because graph data was not updated before, due to an apparently
conditional update of the graph data.
This PR is now:
- verifying that the series are present and valid before extracting the timerange
- updating the graph data even if no series were present at the time of the update
Fixes #5548.
Reproducing the issue described in #5548 ensuring that it does not reoccur.
=> Validate series before extracting timerange / update graph data after being empty.

graylog2-web-interface/src/legacy/Rickshaw.Graph.Graylog2Selector.js, graylog2-web-interface/src/legacy/result-histogram.js
* Check if series are present before extracting timerange.
* Also update graph data if no series are present.
(cherry picked from commit 518825aeb04f443367229a049d2ef56a83a7eb4c)
Backport from #5558
=> Validate series before extracting timerange / update graph data after being empty

pom.xml
Changelog: https://netty.io/news/2019/01/21/4-1-33-Final.html
Related changes:
- Allowed IP_FREEBIND option for UDP epoll
- Ensure FlowControlled data frames will be correctly removed from the flow-controller when a write error happens
- Only handle NXDOMAIN as failure when nameserver is authoritive or no the other nameservers are left
- Correctly buffer multiple outbound streams if needed
- Only call handlerRemoved(...) if handlerAdded(...) was called during adding the handler to the pipeline
- Correctly detect and handle CNAME loops
- ChannelInitializer may be invoked multiple times when used with custom EventExecutor
- Loosen bounds check on CompositeByteBuf's maxNumComponents
- Provide a way to cache the internal nioBuffer of the PooledByteBuffer to reduce GC
**Note:** This needs to …
=> Bug fix update to netty 4.1.33

graylog2-web-interface/src/components/content-packs/ContentPackEdit.jsx, graylog2-web-interface/src/components/content-packs/ContentPackEntitiesList.test.jsx, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntitiesList.test.jsx.snap, graylog2-web-interface/src/logic/content-packs/ContentPack.js, graylog2-web-interface/src/logic/content-packs/Entity.jsx, graylog2-web-interface/src/pages/CreateContentPackPage.jsx, graylog2-web-interface/src/util/ValueRefHelper.js, graylog2-web-interface/src/util/ValueReferenceData.test.js
Prior to this change, a entity with a parameter as title
did display the parameter name as a title.
This change tries to get the default value of the parameter
to display as title. If no default value is given
the fallback is still the name of the parameter.
Fixes #5332
=> Use default_value of parameter for entity title 

graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180323150000_AddSidecarUser.java
Try to clarify the purpose of the internal sidecar role, mitigating #5557.
=> Improve internal sidecar role description

graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180323150000_AddSidecarUser.java
Try to clarify the purpose of the internal sidecar role, mitigating #5557.
(cherry picked from commit bbf5c550151876702bcc5c58780e107567e4f388)
=> Improve internal sidecar role description (#5577)

graylog2-web-interface/src/components/visualizations/QuickValuesHistogramVisualization.jsx
Adapt quick values histogram visualization to be able to use it on reports. In this case, we need to enable or disable transitions depending on the value of the `interactive` prop, and use the `onRenderComplete()` prop when the visualization is fully rendered.
=> Add reporting support to quick values histogram

graylog2-server/src/main/java/org/graylog2/grok/GrokPatternService.java, graylog2-server/src/main/java/org/graylog2/grok/InMemoryGrokPatternService.java, graylog2-server/src/main/java/org/graylog2/grok/MongoDbGrokPatternService.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/GrokResource.java, graylog2-server/src/test/java/org/graylog2/grok/MongoDbGrokPatternServiceTest.java
Prior to this change, the unique name validation would
prevent a update of a existing content pack.
This change adds a update function to GrokPatternService
to find a Pattern with a matching ID and uses the
new pattern data to update the grok pattern.
- Created a grok pattern
- Open Edit dialog and saved it without error
- Open Edit dialog changed name and saved it 
- Deleted grok pattern
Fixes #5549
=> Allow updating a grok pattern

graylog2-server/src/main/java/org/graylog/plugins/beats/Beats2Codec.java, graylog2-server/src/main/java/org/graylog2/plugin/Message.java, graylog2-server/src/test/java/org/graylog/plugins/beats/Beats2CodecTest.java, graylog2-server/src/test/resources/org/graylog/plugins/beats/filebeat.json
If the new Beats input was configured to add the
beats type as a prefix to every field (the default),
it would duplicate the entire message field to
`<beats-type>_message.`
Fix this and additionally, keep the `gl2_source_collector` field
from being prefixed. This is needed for the "show messages" button on
the sidecar view.
=> Do not duplicate message in Beats input

graylog2-server/src/main/java/org/graylog/plugins/beats/Beats2Codec.java, graylog2-server/src/main/java/org/graylog2/plugin/Message.java, graylog2-server/src/test/java/org/graylog/plugins/beats/Beats2CodecTest.java, graylog2-server/src/test/resources/org/graylog/plugins/beats/filebeat.json
If the new Beats input was configured to add the
beats type as a prefix to every field (the default),
it would duplicate the entire message field to
`<beats-type>_message.`
Fix this and additionally, keep the `gl2_source_collector` field
from being prefixed. This is needed for the "show messages" button on
the sidecar view.
(cherry picked from commit d64f016373ae4209575c3396776408c6f33d699f)
=> Do not duplicate message in Beats input (#5582)

graylog2-server/src/main/java/org/graylog2/bootstrap/Main.java
Adding the dependency was not enough, we need to register BC,
so it can be used for parsing keys that JCE does not support.
Refs #5216
=> Explicitly register Bouncy Castle as security provider

graylog2-server/src/main/java/org/graylog2/bootstrap/Main.java
Adding the dependency was not enough, we need to register BC,
so it can be used for parsing keys that JCE does not support.
Refs #5216
(cherry picked from commit 38cdacf28f12c5de58ce746851c8632fcbfedfa0)
=> Explicitly register Bouncy Castle as security provider (#5560)

graylog2-server/src/main/java/org/graylog2/indexer/IndexSetValidator.java, graylog2-server/src/test/java/org/graylog2/indexer/IndexSetValidatorTest.java, graylog2-web-interface/src/components/common/TimeUnitInput.jsx, graylog2-web-interface/src/components/common/TimeUnitInput.md, graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.jsx, graylog2-web-interface/src/pages/IndexSetCreationPage.jsx
This PR makes some improvements around how we handle the field type refresh interval for index sets:
- Set a default value in the frontend, fixing #4724 
- Let Moment.js handle durations for us in the frontend
- Restrict time units displayed in the form for this field to only display those that are reasonable
- As too short values may have a performance impact, validate the field in the backend to ensure the refresh interval is one second or longer
=> Fixes for index set field type refresh interval value

graylog2-server/src/main/java/org/graylog2/indexer/IndexSetValidator.java, graylog2-server/src/test/java/org/graylog2/indexer/IndexSetValidatorTest.java, graylog2-web-interface/src/components/common/TimeUnitInput.jsx, graylog2-web-interface/src/components/common/TimeUnitInput.md, graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.jsx, graylog2-web-interface/src/pages/IndexSetCreationPage.jsx
* Fix linter errors
* Add default value to `field_type_refresh_interval`
Use same default value as the server.
Fixes #4724
* Allow restricting units in TimeUnitInput
This allows consumers of the component to only display supported units
in the form.
* Ensure we do not modify the state directly
* Ensure we render the current state in the form
The state is initialized from the props, but changes in the form are
persisted in the state. To ensure any computed value from state is still
correctly rendered, use the state values instead of the props.
* Restrict available units to seconds and minutes
* Rely on moment.duration to get right values
On change, always convert the given value and unit to milliseconds, which
is what the server expects.
For rendering, convert the given time in …
=> Fixes for index set field type refresh interval value (#5595)

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/db/RuleService.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/DashboardFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/PipelineFacade.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/PipelineFacadeTest.java
This PR solves 2 Problems:
- Fixup stream_id after dependency resolution
Prior to this change, a pipeline would search for a rule
with the name of the rule to resolve the entity. Since
the rule reference is the name of the rule.
- Use rule id for reference instead of name in content pack
Prior to this change, a pipeline would search for a rule
with the name of the rule to resolve the entity. Since
the rule reference is the name of the rule.
Creating a content pack with a dashboard linked to a stream and installed it and de-installed it.
Creating a content pack with a pipeline with pipeline rules and installed it and de-installed it.
=> Fix problems with resolving dependencies in content packs

graylog2-server/src/main/java/org/graylog2/streams/StreamRouterEngine.java, graylog2-server/src/test/java/org/graylog2/streams/StreamRouterEngineTest.java
The CONTAINS rule evaluates the match to false when the rule is inverted (I.E. "field does not contain value") and the field is missing (which can be seen in [tests](https://github.com/Graylog2/graylog2-server/blob/0fb0b2ee3de22a1258abe5787e19e79bc9e84eff/graylog2-server/src/test/java/org/graylog2/streams/matchers/ContainsMatcherTest.java#L76-L83)), but because the rule is not in the [`ruleTypesNotNeedingFieldPresence` list](https://github.com/Graylog2/graylog2-server/blob/0fb0b2ee3de22a1258abe5787e19e79bc9e84eff/graylog2-server/src/main/java/org/graylog2/streams/StreamRouterEngine.java#L57) the rule is [not tested when the field doesn't exist](https://github.com/Graylog2/graylog2-server/blob/0fb0b2ee3de22a1258abe5787e19e79bc9e84eff/graylog2-server/src/main/java/org/graylog2/streams/Stream …
=> Add the CONTAINS rule as one not requiring the field to be present

graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180323150000_AddSidecarUser.java
There is no need for the sidecar role to have this permission.
=> Drop `users:list` permission from sidecar role

graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180323150000_AddSidecarUser.java
There is no need for the sidecar role to have this permission.
(cherry picked from commit e5c4d0cef3c4ecb30c4961ca3eaaf77603b5e4fe)
=> Drop `users:list` permission from sidecar role (#5607)

graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorFacade.java
The facade was searching the collector by name only.
We changed the uniqueness constraint to name and OS.
Also drop the half baked consistency check.
Either we check all the parameters of a collector (especially the
config) or nothing.
Refs https://github.com/Graylog2/graylog2-server/pull/5495
Fixes #5599
=> Adjust SidecarCollectorFacade to new name validation

graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorFacade.java
The facade was searching the collector by name only.
We changed the uniqueness constraint to name and OS.
Also drop the half baked consistency check.
Either we check all the parameters of a collector (especially the
config) or nothing.
Refs https://github.com/Graylog2/graylog2-server/pull/5495
Fixes #5599
(cherry picked from commit a8485efec2938c744061b50e5c75629d6d84b770)
=> Adjust SidecarCollectorFacade to new name validation (#5602)

graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.jsx
The fixes in #5595 corrected the code in `IndexSetConfigurationForm` to avoid modifying the React state directly. Creating a clone of the state had an unexpected consequence: the `_updateConfig()` method updates different object keys stored in the `indexSet` state key. When consecutive calls to `_updateConfig()` are made, each of them will create a clone of the state at the time of the call, but that state does not represent the actual current state, since React enqueues changes to the state.
In order to avoid that issue, we make use of the update function to set the state, which guarantees that the current state (including any queued modifications) are passed to the function.
Fixes #5617
=> Fix changing index rotation and retention settings

graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.jsx
The fixes in #5595 corrected the code in `IndexSetConfigurationForm` to
avoid modifying the React state directly. Creating a clone of the state
had an unexpected consequence: the `_updateConfig()` method updates
different object keys stored in the `indexSet` state key. When
consecutive calls to `_updateConfig()` are made, each of them will
create a clone of the state at the time of the call, but that state does
not represent the actual current state, since React enqueues changes to
the state.
In order to avoid that issue, we make use of the update function to set
the state, which guarantees that the current state (including any queued
modifications) are passed to the function.
Fixes #5617
(cherry picked from commit aad8a4d51503155afc3cc03d0c904f237b0c3127)
Backport of #5622
=> Fix changing index rotation and retention settings (#5622)

graylog2-web-interface/src/components/common/TimeUnitInput.jsx, graylog2-web-interface/src/components/common/TimeUnitInput.test.jsx, graylog2-web-interface/src/components/lookup-tables/caches/GuavaCacheFieldSet.jsx, graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterFieldSet.jsx
Lookup table components do not always keep the enabled state, as the `TimeUnitInput` component did that for them before https://github.com/Graylog2/graylog2-server/pull/5077.
This PR introduces a `defaultEnabled` prop, that let consumers use the component in an uncontrolled way, similarly to React inputs.
Fixes #5658
=> Fix checkboxes on lookup tables

graylog2-web-interface/src/components/common/TimeUnitInput.jsx, graylog2-web-interface/src/components/common/TimeUnitInput.test.jsx, graylog2-web-interface/src/components/lookup-tables/caches/GuavaCacheFieldSet.jsx, graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterFieldSet.jsx
Lookup table components do not always keep the enabled state, as the
`TimeUnitInput` component did that for them before.
This commit introduces a `defaultEnabled` prop, that let consumers use
the component in an uncontrolled way, similarly to React inputs.
Fixes #5658
(cherry picked from commit d295e7d7e15094a3f6ad74e3b725e75abd8b10f9)
=> Fix checkboxes on lookup tables (#5666)

graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java, graylog2-server/src/main/java/org/graylog2/shared/security/ShiroSecurityBinding.java, graylog2-server/src/main/java/org/graylog2/shared/security/ShiroSecurityContextFilter.java
Avoid registering ShiroSecurityContextFilter as a DynamicFeature.
Doing so, triggers Jersey to create a ServiceLocator for all
existing (~1600) Resources. [1]
Furthermore, each created ServiceLocator will have its own Guice/HK2 Bridge,
whose JIT resolver cache is cold upon startup and needs to be filled.
Instead of registering the ShiroSecurityContextFilter dynamically, we
register it statically in the JerseyService because every Resource is filtered
through it anyway.
We need to give it a higher priority so it's executed before the authentication filter.
[1]
https://github.com/jersey/jersey/blob/2.25.1/core-server/src/main/java/org/glassfish/jersey/server/model/ResourceMethodInvoker.java#L187
=> Fix slow loading UI after server startup

graylog2-web-interface/src/components/navigation/NavigationLink.jsx, graylog2-web-interface/src/components/navigation/NavigationLink.test.jsx
In #5193, the newly created `NavigationLink` component performs
prefixing the path passed to it with the application prefix. This is
happening although in `Routes.jsx` all routes are already being prefixed
before being exported.
This change is removing the prefixing in `NavigationLink`.
Fixes #5702.
=> Prevent double prefixing paths for navigation items in system menu.

graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/InputsResource.java, graylog2-server/src/main/java/org/graylog2/shared/inputs/InputDescription.java, graylog2-server/src/test/java/org/graylog2/rest/resources/system/inputs/InputsResourceMaskingPasswordsTest.java
* Mask password fields of inputs returned by the REST API.
Before this change, input details returned by the REST API would contain
all configuration fields without any modification. This implies that
password fields are also contained using their original value, showing
configured password for inputs in clear text.
This change now iterates over configuration fields checking for the
presence of password fields and replace their content with `<password
set>` instead of the original value if they are not empty.
Fixes #5408.
* Adding test for actual resource method, including license headers.
* Adding test for complete input list retrievel.
* Adding guard clause for null parameters.
* Using locales for toLowerCase.
* Handling null values in map.
* Do not mask passwords in input config for …
=> Mask password fields of inputs returned by the REST API. (#5432)

graylog2-server/src/main/java/org/graylog2/shared/bindings/GenericInitializerBindings.java, graylog2-server/src/main/java/org/graylog2/system/shutdown/GracefulShutdown.java, graylog2-server/src/main/java/org/graylog2/system/shutdown/GracefulShutdownHook.java, graylog2-server/src/main/java/org/graylog2/system/shutdown/GracefulShutdownService.java, graylog2-server/src/test/java/org/graylog2/system/shutdown/GracefulShutdownServiceTest.java
Services can register themselves with the GracefulShutdownService to
make sure they will be stopped gracefully on server shutdown.
This allows plugins to participate in a graceful server shutdown to
make sure the server is not terminated before the plugin shutdown
routine is done.
=> Add GracefulShutdownService

graylog2-server/src/main/java/org/graylog2/dashboards/DashboardImpl.java, graylog2-server/src/main/java/org/graylog2/migrations/V20180214093600_AdjustDashboardPositionToNewResolution.java, graylog2-server/src/test/java/org/graylog2/migrations/V20180214093600_AdjustDashboardPositionToNewResolutionTest.java
Prior to this change, the migration expected that all postions
have a "width", "heigth", "row" and "col" field.
Some users did not have a "width" or "height" field.
This change will add default values for the fields in the
getPositions functions of DashboardImpl.
Also fix some warnings.
Fixes #5737
- Created a dashboard in 2.5 and removed the "width" and "height" from the position
- Upgraded to 3.0
=> Fix AdjustDashboardPosition Migration

graylog2-web-interface/src/logic/search/queryParser.test.js, graylog2-web-interface/src/logic/search/queryParser.ts
Until now our custom Lucene query parser used for search auto-completion did not support wildcards. This caused the parser to throw exceptions in the background, which in 3.0 could cause the "something went wrong" page to come out, as described in #5719.
This PR adds support for wildcards in the query parser, and also modifies the code throwing the exception, ensuring that no error is thrown if a similar situation occurs.
Fixes #5719
=> Add support of wildcards in query parser

graylog2-server/src/main/java/org/graylog2/inputs/transports/HttpTransport.java
Requests with `Expect: 100-Continue` would lead to an exception and
terminate the request.
This got broken with the netty upgrade, which exchanged the
`HttpChunkedAggregator` to the new `HttpObjectAggregator`.
The aggregator needs to be registered after the `HttpResponseEncoder`
in the ChannelPipeline.
Ref: https://netty.io/4.1/api/io/netty/handler/codec/http/HttpObjectAggregator.html
Fixes #5690
=> Fix HTTP 100 handling in http inputs

graylog2-server/src/main/java/org/graylog2/inputs/transports/netty/HttpHandler.java
We were only responding to the first request on an http keep-alive connection with a 202.
Any following requests would not be answered, leading to a timeout in the client.
Configuring a ChannelFuture for CLOSE_ON_FAILURE did expose the reasonfor the bug:
`io.netty.handler.codec.EncoderException:
java.lang.IllegalStateException: unexpected message type:
DefaultHttpResponse, state: 1`
We ought to use `DefaultFullHttpResponse` instead of `DefaultHttpResponse`.
Also keep the `CLOSE_ON_FAILURE` to make this more robust for future bugs.
Fixes #5720
=> Fix http input keep-alive handling

graylog2-server/src/main/java/org/graylog2/inputs/transports/HttpTransport.java
Requests with `Expect: 100-Continue` would lead to an exception and
terminate the request.
This got broken with the netty upgrade, which exchanged the
`HttpChunkedAggregator` to the new `HttpObjectAggregator`.
The aggregator needs to be registered after the `HttpResponseEncoder`
in the ChannelPipeline.
Ref: https://netty.io/4.1/api/io/netty/handler/codec/http/HttpObjectAggregator.html
Fixes #5690
(cherry picked from commit bc4301f58bf3971540a57b0b65d1c5c331f937de)
=> Fix HTTP 100 handling in http inputs (#5725)

graylog2-server/src/main/java/org/graylog2/inputs/transports/netty/HttpHandler.java
We were only responding to the first request on an http keep-alive connection
with a 202.
Any following requests would not be answered, leading to a timeout in the client.
Configuring a ChannelFuture for CLOSE_ON_FAILURE did expose the reason
for the bug:
`io.netty.handler.codec.EncoderException:
java.lang.IllegalStateException: unexpected message type:
DefaultHttpResponse, state: 1`
We ought to use `DefaultFullHttpResponse` instead of `DefaultHttpResponse`.
Also keep the `CLOSE_ON_FAILURE` to make this more robust for future bugs.
Fixes #5720
(cherry picked from commit 9f34e09602236afb6cecbb0ff80832bbac287aee)
=> Fix http input keep-alive handling (#5728)

graylog2-server/src/main/java/org/graylog2/contentpacks/facades/OutputFacade.java, graylog2-server/src/main/java/org/graylog2/initializers/OutputSetupService.java, graylog2-server/src/main/java/org/graylog2/outputs/MessageOutputFactory.java, graylog2-server/src/main/java/org/graylog2/plugin/GlobalMetricNames.java, graylog2-server/src/main/java/org/graylog2/plugin/PluginModule.java, graylog2-server/src/main/java/org/graylog2/plugin/inject/Graylog2Module.java, graylog2-server/src/main/java/org/graylog2/plugin/outputs/MessageOutput.java, graylog2-server/src/main/java/org/graylog2/shared/journal/KafkaJournal.java, graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackServiceTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/OutputFacadeTest.java, graylog2-server/src/test/java/org/graylog2/outputs/MessageOutputFactoryTest.java, graylog2-server/src/test/java/org/graylog2/shared/journal/KafkaJournalTest.java
The Graylog Server will need several changes in order for the Graylog Forwarder to be implemented.
1) The Graylog Forwarder feature uses the same Journaling capability that exists in the Graylog Server currently. The `KafkaJournal` class has been reworked to allow support for instance-based metric names.
2) Output implementations do not currently have access to the output id. A change has been made that allows the output implementation to access the output instance and therefore the id.
See https://github.com/Graylog2/graylog-plugin-enterprise-integrations/pull/30 for the core Forwarder PR.
=> Server changes for Forwarder

graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
We have to call the outputsMapBinder2() method during startup to always
create the map binder for MessageOutput.Factory2. Otherwise the server
doesn't start when there is no output that is using the factory.
This is fallout from #5670.
=> Fix missing guice bindings for MessageOutput.Factory2

graylog2-web-interface/src/logic/search/queryParser.test.js, graylog2-web-interface/src/logic/search/queryParser.ts
Until now our custom Lucene query parser used for search auto-completion did not support wildcards. This caused the parser to throw exceptions in the background, which in 3.0 could cause the "something went wrong" page to come out, as described in #5719.
This PR adds support for wildcards in the query parser, and also modifies the code throwing the exception, ensuring that no error is thrown if a similar situation occurs.
Fixes #5719
=> Add support of wildcards in query parser (3.0)

graylog2-web-interface/src/components/navigation/NavigationBrand.jsx
Previous PR #5748 for this issue had commented code.
This PR removes commented code only.
Remove commented code
=> Remove commented code

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/GrokMatch.java, graylog2-server/src/main/java/org/graylog2/grok/InMemoryGrokPatternService.java, graylog2-server/src/main/java/org/graylog2/grok/MongoDbGrokPatternService.java, graylog2-server/src/main/java/org/graylog2/inputs/extractors/GrokExtractor.java, graylog2-server/src/main/java/org/graylog2/rest/resources/tools/GrokTesterResource.java, graylog2-server/src/test/java/org/graylog2/inputs/extractors/GrokExtractorTest.java
Prior to this change, a named grok pattern containing a OR like
`(%{INT:login}|%{WORD:login}})`
would result in array like
`[null, found]`
This change will flatten the result (remove the null) and
only print the single left value instead of the array like
syntax:
`found`.
Fixes: #4773 
- Add first grok pattern `{name: "TEST1", pattern: "test1"}`
- Add second pattern `{name; "TEST2",  pattern: "test2"}`
- Add a extractor using the patterns: `(%{TEST1:found}|%{TEST2:found})`
- Send a gelf message containing a message containing `test1` 
- Look that extractor result is `found: test1`
- Send a gelf message containing a message containing `test2` 
- Look that extractor result is `found: test2`
=> Flatten grok pattern result when applied with OR

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/GrokMatch.java, graylog2-server/src/main/java/org/graylog2/grok/InMemoryGrokPatternService.java, graylog2-server/src/main/java/org/graylog2/grok/MongoDbGrokPatternService.java, graylog2-server/src/main/java/org/graylog2/inputs/extractors/GrokExtractor.java, graylog2-server/src/main/java/org/graylog2/rest/resources/tools/GrokTesterResource.java, graylog2-server/src/test/java/org/graylog2/inputs/extractors/GrokExtractorTest.java
Prior to this change, a named grok pattern containing a OR like
`(%{INT:login}|%{WORD:login}})`
would result in array like
`[null, found]`
This change will flatten the result (remove the null) and
only print the single left value instead of the array like
syntax:
`found`.
Fixes: #4773 
- Add first grok pattern `{name: "TEST1", pattern: "test1"}`
- Add second pattern `{name; "TEST2",  pattern: "test2"}`
- Add a extractor using the patterns: `(%{TEST1:found}|%{TEST2:found})`
- Send a gelf message containing a message containing `test1` 
- Look that extractor result is `found: test1`
- Send a gelf message containing a message containing `test2` 
- Look that extractor result is `found: test2`
=> Flatten grok pattern result when applied with OR 

graylog2-web-interface/src/stores/inputs/InputsStore.js
Before this change, the `InputsStore` did not contain a
`getInitialState` function, allowing consumers (especially `connect`) to
retrieve the current state without triggering an update.
This is required by `connect` to get its initial seed. Also it
alleviates the need to ensure that the consumer is listening to the
store _before_ a `list` action is triggered.
=> Allowing to retrieve current state from `InputsStore`.

graylog2-web-interface/src/components/configurationforms/FieldHelpers.jsx
Booleans are always optional and in some cases, the text leads
to confusion.
For example, on a checkbox named `[x] Enable TLS (optional)` the user
could expect that non working TLS will fallback to plaintext,
which is not the case.
=> Do not show an "(optional)" for boolean configuration fields

misc/graylog.conf
Till we can update mongodb-driver-java to a recent version the user needs to escape '+' signs by hand. See https://github.com/Graylog2/graylog2-server/issues/5680 and https://github.com/Graylog2/graylog2-server/pull/5736
=> Add comment about MongoDB username/password escaping

graylog-project-parent/pom.xml, graylog2-server/pom.xml, graylog2-server/src/main/java/org/graylog2/grok/GrokPatternService.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/java/org/graylog2/grok/GrokPatternServiceTest.java, graylog2-server/src/test/java/org/graylog2/inputs/extractors/GrokExtractorTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/grok.txt, pom.xml
To support underscores ("_") in Grok match group names, we had to modify
the java-grok library to use the old regexp engine again.
See: https://github.com/graylog-labs/java-grok/pull/2
This also adds a test for the Grok extractor to make sure that using
underscores works.
Fixes #5704
Fixes #5563
=> Switch back to a repackaged and fixed version of java-grok

graylog-project-parent/pom.xml, graylog2-server/pom.xml, graylog2-server/src/main/java/org/graylog2/grok/GrokPatternService.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/java/org/graylog2/grok/GrokPatternServiceTest.java, graylog2-server/src/test/java/org/graylog2/inputs/extractors/GrokExtractorTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/grok.txt, pom.xml
* Switch back to a repackaged and fixed version of java-grok
To support underscores ("_") in Grok match group names, we had to modify
the java-grok library to use the old regexp engine again.
See: https://github.com/graylog-labs/java-grok/pull/2
This also adds a test for the Grok extractor to make sure that using
underscores works.
Fixes #5704
Fixes #5563
* Fix GrokPatternService#extractPatternNames and add a test for it
* Add missing license header to GrokPatternServiceTest
* Add test for named group with underscore
Prior to this change, there was no test for named groups
with underscores in the FunctionSnippetsTest
This change enhances the grok() test to run with a
named group with underscore.
(cherry picked from commit e642a418a09909b0858b3ba5ba837a8e441a1944)
=> Switch back to a repackaged and fixed version of java-grok (#5800)

graylog2-server/src/test/java/org/graylog2/inputs/extractors/GrokExtractorTest.java, pom.xml
`caputeFlattend` raised a exception when it got a result containing multiple non-null results
and tried to flatten that.
We now will remove all null values and reduce the result to a single value if only a single
value is left.
For some reason the java-grok library was raising this error instead of just removing the null
values.
- Adding a grok extractor with following grok: `%{INT:first} %{INT:second}` without
`named caputure only`
- Send in a log message with "22 23"
- See that no exception was raised
=> Fix problem with captureFlattened

graylog2-server/src/test/java/org/graylog2/inputs/extractors/GrokExtractorTest.java, pom.xml
* Add test for flatten with multiple non-null-values
* Upgrade to fixed version of java grok
and add a addional test case
Fixes #4773
(cherry picked from commit d41e60fe0935edd9277b128a6d2f82c8149513a1)
=> Fix problem with captureFlattened (#5818)

misc/graylog.conf
`transport_email_use_ssl` default value is set to false in the code, this needs to be reflected in the server configuration as well.
See https://github.com/Graylog2/graylog2-server/blob/9e34d4ff9ee08951bbee9f8b788a3c70a7b0949d/graylog2-server/src/main/java/org/graylog2/configuration/EmailConfiguration.java#L43
Update comment in server configuration
=> Fix transport_email_use_ssl to actual default

graylog2-web-interface/src/components/common/Timestamp.jsx, graylog2-web-interface/src/components/common/Timestamp.md
Before this change, passing a number containing a timestamp based on
seconds after epoch resulted in a proper output, but also raised a prop
type validation error.
This change is now adding `number` to be a valid prop type for
`dateTime` and documents the possibility to use seconds after epoch for
`Timestamp`.
=> Make `Timestamp` accept seconds from epoch.

graylog2-web-interface/src/components/bootstrap/BootstrapModalWrapper.jsx, graylog2-web-interface/src/components/users/__snapshots__/UserPreferencesButton.test.jsx.snap
Set default for Modal component to not automatically close when outside of component is clicked.
Closes #5803 
https://react-bootstrap.github.io/components/modal/#modals-props
=> Set Modals to only close with ESC key or Cancel & X buttons

graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/CollectorResource.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/ConfigurationResource.java
These endpoints are used periodically by every sidecar.
It makes sense to have these metrics in case we want
to diagnose a performance bottle neck.
=> Add metrics for sidecar resources

graylog2-web-interface/src/util/DocsHelper.js
To add a Documentation Link to the Reporting overview page as done in [#793](https://github.com/Graylog2/graylog-plugin-enterprise/pull/793) the DocsHelper needs to be adjusted.
=> Add reporting to docs helper

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/GrokExists.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/GrokMatch.java, graylog2-server/src/main/java/org/graylog2/grok/GrokPatternRegistry.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/grok_exists.txt, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/grok_exists_not.txt
Prior to this change, a missing grok pattern would
raise a error in the pipeline processor when using the "grok"
function. But the user would like to able to make one rule
which uses a grok pattern dynamicaly depending on if
a grok pattern exists or not.
This change adds a new function "grok_exists" which will
return true or false depending if a grok pattern exists.
Additionally it will make a entry to the graylog-server.log
if the second argument of the function is true and
the pattern was not found.
- Add a grok pattern named "KONRAD"
- Add a new pipeline rule:
```
rule "grok exists true"
when
grok_exists("KONRAD")
then
debug("grok exists");
end
```
- Check that debug log got raised
- Changed Pattern name and checked that debug log got not raised.
Fixes #5689
=> Add new pipeline function "grok_exists"

bin/graylogctl
Currently doesn't work on FreeBSD as is. Not all distros use /bin/bash either.
/usr/bin/env bash should always point to the correct shell.
Changed ```/bin/bash``` to ```/usr/bin/env bash```.
https://en.wikipedia.org/wiki/Env
Doesn't work on FreeBSD as tested.
```/usr/bin/env``` has been fairly tested. There are implementations on almost every major POSIX environment.
- [X ] My code follows the code style of this project.
=> Fixed shebang path.

graylog2-server/src/main/java/org/graylog2/inputs/transports/KafkaTransport.java
Signed-off-by: Pierre De Paepe <pierre.de-paepe@corp.ovh.com>
This little patch will allow graylog administrators to define a custom Kafka group_id in related input panel.
To avoid update issue, current group "graylog2" remains the default value.
If you have a big Kafka cluster with multiple graylog clusters subscribed on, each time a unhealthy consumer flaps, the rebalancing order is sent to all graylog nodes introducing unecessary stress on log ingestion.
An easy way to avoid it, consists to define for each graylog cluster a specific consumer group name.
In production : ~20 graylog clusters for one kafka.
- [x ] New feature (non-breaking change which adds functionality)
- [x ] My code follows the code style of this project.
- [x ] My change requires a change to the documentation.
=> Allow kafka group.id to be configured

graylog-plugin-archetype/src/main/resources/archetype-resources/pom.xml, graylog-plugin-parent/pom.xml, graylog2-server/pom.xml, graylog2-web-interface/packages/graylog-web-plugin/src/PluginWebpackConfig.js, graylog2-web-interface/webpack.config.js, graylog2-web-interface/webpack.vendor.js
The "build" and "cache" directories are currently located in the project
root of plugins. This change moves them to the "target/web" directory.
That way we don't need any custom configuration to remove these
directories on "mvn clean" and they should also not be indexed by
IntelliJ and consume resources. (most developers exclude the "build" and
"cache" directories in IntelliJ for performance reasons)
=> Move web build and cache directory into target/

graylog-plugin-archetype/src/main/resources/archetype-resources/pom.xml, graylog2-server/pom.xml
This allows us to share test classes in other maven modules like
plugins and avoids copying classes over to other repositories.
(e.g. MongoConnectionRule, ElasticsearchBase)
Also adjust the pom.xml template in the archetype to include the
test-jar dependency.
=> Add "test-jar" goal to maven-jar-plugin configuration

graylog2-server/src/main/java/org/graylog2/migrations/V20180924111644_AddDefaultGrokPatterns.java
Prior to this change, when a user had modfied the a default
grok pattern, the installation would fail. With a cryptic
error message.
This change catches the error and prints a hopefully more useful
error message.
Also: do not use `new Error` which is not catched.
Also: we will write the clusterConfig to avoid running into a already found content pack after every restart.
Fixes #5626 
- Removed Content Pack Installation
- Removed Content Pack
- Removed corresponding cluster config
- Edited one default grok pattern
- Restarted server and looked for the warning message
=> Give usefull message on default grok patterns fail

pom.xml
Changes since netty 4.1.33:
- https://netty.io/news/2019/03/08/4-1-34-Final.html
- https://netty.io/news/2019/04/17/4-1-35-Final.html
- https://netty.io/news/2019/04/30/4-1-36-Final.html
=> Update to netty 4.1.36 and netty-tcnative-boringssl 2.0.25

graylog2-web-interface/src/components/extractors/converters_configuration/LookupTableConverterConfiguration.jsx, graylog2-web-interface/src/components/extractors/extractors_configuration/LookupTableExtractorConfiguration.jsx, graylog2-web-interface/src/components/indices/IndexMaintenanceStrategiesConfiguration.jsx, graylog2-web-interface/src/components/lookup-tables/CacheCreate.jsx, graylog2-web-interface/src/components/lookup-tables/CachePicker.jsx, graylog2-web-interface/src/components/lookup-tables/DataAdapterCreate.jsx, graylog2-web-interface/src/components/lookup-tables/DataAdapterPicker.jsx, graylog2-web-interface/src/components/lookup-tables/__snapshots__/DataAdapterCreate.test.jsx.snap, graylog2-web-interface/src/components/lookup-tables/adapters/DnsAdapterFieldSet.jsx, graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterFieldSet.jsx, graylog2-web-interface/src/components/maps/configurations/GeoIpResolverConfig.jsx
In all these cases the matchProp needs to be set to "label" and not "value"
because the value contains the object ID or another identifier.
After this, the auto-completion is looking at same data that the user
is seeing.
Fixes #5659
=> Fix auto-completion in several drop-down fields

graylog2-web-interface/src/pages/ExtractorsPage.jsx
This change is fixing an issue that is related to the introduction of
its supplied state even during first initialization, leading to an
attempt to merge a duplicate key when mounting the `ExtractorsPage`
component. Removing the `inputs` key in the initial state of that
component is fixing it.
Fixes #5948.
=> Do not initialize `inputs` variable to prevent merging duplicate key in.

graylog2-web-interface/src/pages/StreamOutputsPage.jsx
This change is fixing the address of the link to the global output list
on the stream output page. Before this change, it was a string literal
left over from the migration from play to react years ago.
Additionally, linter hints in that component were fixed.
Fixes #5952.
=> Fix link to global output list on stream output page.

graylog2-web-interface/package.json, graylog2-web-interface/packages/graylog-web-plugin/package.json, graylog2-web-interface/yarn.lock
This update includes security fixes.
<details>
<summary> Vulnerability</summary>
Vulnerable versions: < 3.4.0
jQuery before 3.4.0, as used in Drupal, Backdrop CMS, and other products, mishandles jQuery.extend(true, {}, ...) because of Object.prototype pollution. If an unsanitized source object contained an enumerable proto property, it could extend the native Object.prototype.
</details>
=> Upgrade jquery to 3.4.1

graylog2-server/src/main/java/org/graylog2/database/PaginatedDbService.java
Using the `PaginatedService` with a DTO that utilizes Jackson's JSON
views to customize (de-)serialization e.g. for persistence vs. REST does
not work currently, as a view needs to be passed to MongoJack in order
to enable views processing.
This change is adding a second constructor to `PaginatedService`
allowing consumers to specify a view class as additional parameter.
=> Allow specifying view for `PaginatedService`.

graylog2-web-interface/package.json, graylog2-web-interface/src/components/common/SourceCodeEditor.jsx, graylog2-web-interface/src/components/common/webpack-resolver.js, graylog2-web-interface/webpack/vendor-module-ids.json, graylog2-web-interface/yarn.lock
Replace `react-ace` with `react-ace-builds`.
`react-ace-builds` is an `ace` library without `brace`. `brace` is lacking behind the actual
ace implementation and seems to be not maintained anymore (https://github.com/thlorenz/brace/issues/135), so `react-ace-builds` provides an `ace` implementation for `react` based on `ace-builds`, which is part of the official ace distribution.
=> Replace `react-ace` with `react-ace-builds`.

graylog2-server/src/main/java/org/graylog2/indexer/searches/SearchFailure.java, graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java, graylog2-server/src/test/java/org/graylog2/indexer/searches/SearchFailureTest.java
If you search on a field that is mapped to a numeric,
you won't see the real reason on why this has failed.
I assume the error format has changed in recent ES versions,
and the info is now hidden in the `caused_by` field on shard failures.
For reference, this is the response:
```
{
"took" : 2,
"timed_out" : false,
"_shards" : {
"total" : 64,
"failures" : [
{
"shard" : 0,
"index" : "graylog_0",
"reason" : {
"type" : "query_shard_exception",
"reason" : "failed to create query: {\n [....]  }\n}",
"index" : "graylog_0",
"caused_by" : {
"type" : "number_format_exception",
"reason" : "For input string: \"foo\""
}
}
}
]
},
"hits" : {
"total" : 0,
"max_score" : null,
"hits" : [ ]
}
}
```
=> Also return ES "caused_by" error message for failed searches

graylog2-web-interface/package.json, graylog2-web-interface/src/components/common/Select.jsx, graylog2-web-interface/yarn.lock
Before this change, `react-select` `^v1.0.0-rc.10` was used in core. In
the views, v2 is used due to it allowing to customize its components (in
that case to make them sortable using drag & drop). Therefore this PR
is:
1. bumping the dependency to `2.4.3`
2. updating the `Select` component to make use of it while providing
the same semantics to its consumers
=> Migrating `react-select` from v1 to v2.

graylog2-web-interface/src/components/inputs/CreateInputControl.jsx, graylog2-web-interface/src/pages/CreateExtractorsPage.jsx, graylog2-web-interface/src/pages/EditExtractorsPage.jsx, graylog2-web-interface/src/pages/ExportExtractorsPage.jsx, graylog2-web-interface/src/pages/ImportExtractorsPage.jsx
Before this PR, mounting one of the affected components lead to a
collision when merging the state of the `InputsStore`, as returned by
its `getInitialState` function into the state of the components, because
the `input` key was already defined. This PR is removing the initial
assignment of this key and fixes linter hints.
Fixes #5997.
=> Avoid collisions when merging `InputsStore` state into components state.

graylog2-web-interface/src/components/common/Select.jsx
The `labelKey` & `valueKey` props in `react-select` have become
deprecated and replaced by `getOptionLabel`/`getOptionValue` functions.
This PR is changing our wrapper component to reflect this.
=> Fixing `displayKey`/`valueKey` props in `Select` component.

graylog2-web-interface/src/components/navigation/Navigation.css, graylog2-web-interface/src/components/navigation/Navigation.jsx
Removes two JS warnings/errors
There are two Warnings that show up on almost every page load
```Warning: React does not recognize the `activeKey` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `activekey` instead. If you accidentally passed it from a parent component, remove it from the DOM element.```
and
```Warning: React does not recognize the `activeHref` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `activehref` instead. If you accidentally passed it from a parent component, remove it from the DOM element.```
=> Cleaning up JS Warnings

graylog2-web-interface/src/components/common/Wizard.jsx, graylog2-web-interface/src/components/common/Wizard.md, graylog2-web-interface/src/components/common/Wizard.test.jsx, graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap
This change allows customers of the `Wizard` component to customize its appearance in two different ways:
- The `justified` prop allows the navigation to take the full width of its container
- The `navigationClassName` prop allows consumers to set a CSS class for the navigation, so it is possible to alter the way the navigation looks without changing its code
Screenshot:
=> Wizard component style customization

graylog2-server/src/main/java/org/graylog2/indexer/EventsIndexMapping.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexMappingFactory.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexMappingTemplate.java, graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetConfig.java, graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java, graylog2-server/src/test/java/org/graylog2/indexer/EventsIndexMappingTest.java, graylog2-server/src/test/java/org/graylog2/indexer/IndexMappingFactoryTest.java, graylog2-server/src/test/java/org/graylog2/indexer/MongoIndexSetTest.java, graylog2-server/src/test/java/org/graylog2/indexer/indexset/IndexSetConfigTest.java, graylog2-server/src/test/java/org/graylog2/indexer/indexset/MongoIndexSetServiceTest.java, graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java, graylog2-server/src/test/java/org/graylog2/rest/resources/system/indexer/IndexSetsResourceTest.java, graylog2-server/src/test/java/org/graylog2/streams/StreamMock.java, graylog2-server/src/test/resources/org/graylog2/indexer/indexset/MongoIndexSetServiceTest.json
This introduces index template types so we can install different index mapping templates for different index sets depending on the value of `index_template_type`.
This also adds an "events" index template that will be used for the events/alerting system.
Closes #5884
=> Implement events index template

graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/AbstractInputsResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/InputsResource.java
Allow common Inputs API helper methods to be used in core and the Integrations plugin for AWS.
The getInputSummary() method needs to also be used in the new AWSResource in https://github.com/Graylog2/graylog-plugin-integrations/pull/93 (https://github.com/Graylog2/graylog-plugin-integrations/pull/93/commits/1fc1735b00a2707331cc71542fbc3292f1d1c695). 
Lots of code is required to build this summary, which I did not want to duplicate. This change allows the same method to be used in two resource classes.
=> Establish abstract InputsResource class to allow method reuse

graylog2-server/src/main/java/org/graylog2/indexer/EventsIndexMapping.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping6.java, graylog2-server/src/test/java/org/graylog2/indexer/EventsIndexMappingTest.java
The previous mapping configuration forced all `gl2_*` fields which have
not been mapped explicitly to string/keyword. That means we couldn't
dynamically add new `gl2_*` fields which data types of boolean, long,
date or others.
With this commit we add "match_mapping_type" with value "string" to make
sure that all `gl2_*` string fields will be indexed as keyword instead
of text and others will be mapped automatically by Elasticsearch.
This allows us to index date fields and others with the correct type
without having to create an explicit mapping.
This has been changed for consistency. Our scheduler is using jobs and
not tasks.
=> Index mapping changes

graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/references/ReferenceMapUtils.java, graylog2-server/src/test/java/org/graylog2/contentpacks/model/entities/references/ReferenceMapUtilsTest.java
Prior this change we missed support of maps in list of
a ReferenceMap. This is needed to support configurations
(like DashboardWidget) which can contain a list of maps.
(e.g series when two charts are merged into one)
This change will call toReferenceMap for every list item
which is a map.
Fixes #5742 
Needs backport to 3.0.3
1. create a dashboard containing a merged stack chart
1. create a content pack containing this dashboard
1. install this content pack and change to the dashboard
1. see that the dashboard widget with the merged chart loads as expected
=> Add support for nested maps in list for Content Packs

graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/references/ReferenceMapUtils.java, graylog2-server/src/test/java/org/graylog2/contentpacks/model/entities/references/ReferenceMapUtilsTest.java
Prior this change we missed support of maps in list of
a ReferenceMap. This is needed to support configurations
(like DashboardWidget) which can contain a list of maps.
(e.g series when two charts are merged into one)
This change will call toReferenceMap for every list item
which is a map.
Fixes #5742
(cherry picked from commit a661710024caf2ae08b1677738b0508ea5d3bb7f)
=> Add support for nesed maps in list for Content Packs (#6003)

graylog2-web-interface/src/views/components/TypeSpecificValue.jsx, graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.jsx, graylog2-web-interface/src/views/components/messagelist/MessageFields.jsx, graylog2-web-interface/src/views/components/messagelist/MessageTableEntry.jsx, graylog2-web-interface/src/views/components/messagelist/MessageTableEntry.test.jsx
Before this change, using `Immutable.List#find` to lookup a field type
used the wrong parameter count. Instead of (what the intention was)
passing a default value for cases where the field type is not present,
it was passing the `context`[*] instead. This is fixed and a test is
added.
Fixes Graylog2/graylog-plugin-enterprise#1090.
[*]: https://immutable-js.github.io/immutable-js/docs/#/List/find
=> Handle missing field type of selected field in MessageTableEntry.

graylog2-server/src/main/java/org/graylog/plugins/map/geoip/GeoIpResolverEngine.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/CloneMessage.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreter.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping5.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping6.java, graylog2-server/src/main/java/org/graylog2/indexer/searches/SearchesClusterConfig.java, graylog2-server/src/main/java/org/graylog2/plugin/Message.java, graylog2-server/src/main/java/org/graylog2/plugin/journal/RawMessage.java, graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/DecodingProcessor.java, graylog2-server/src/test/java/org/graylog/plugins/map/geoip/GeoIpResolverEngineTest.java, graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerIT.java
- Create constants for all internal message fields used in the server
- Also document all of them and mark the deprecated ones.
- Added `gl2_receive_timestamp` and `gl2_processing_timestamp` fields
=> Modify index mappings for receive and processing timestamps

graylog2-web-interface/src/views/components/SearchBar.jsx, graylog2-web-interface/src/views/components/searchbar/QueryInput.jsx, graylog2-web-interface/src/views/components/searchbar/QueryInput.test.jsx
Before this change, when leaving the query input without changing the
query (e.g. when copying parts of the query to the clipboard), the
search was refreshed nonetheless.
This change is preventing this. Whenever the query input looses focus,
it is checked for changes and the `onChange` callback is executed only
if there was a change. The `onBlur` callback is triggered regardless of
that.
Fixes #6038.
=> Do not refresh search if query input is blurred, but query is unchanged.

graylog2-web-interface/src/views/components/visualizations/OnZoom.js, graylog2-web-interface/src/views/components/visualizations/XYPlot.jsx, graylog2-web-interface/src/views/components/visualizations/__tests__/XYPlot.test.jsx
This change does the following:
* Extract `onZoom` function from component for easier testing. It can now also be passed as prop, defaulting to the current implementation for backwards compatibility
* Setting `rangemode` for y axis to `tozero`. It sets the range automatically according to the minimum/maximums of the values passed. If the minimum is greater than 0, the lower range of the chart will be set to 0 to ensure that charts with all positive values are aligned
Fixes #6037.
=> Extracting `onZoom` function, using `tozero` for y axis's `rangemode`

graylog2-server/src/test/java/org/graylog2/shared/bindings/providers/OkHttpClientProviderTest.java, pom.xml
This PR is updating OkHttp to 3.14.2.
Any OkHttp version up to 3.12.0 include a vulnerability that allows an attacker doing MitM to bypass certificate pinning. It does require full control of the Graylog server before, as it requires the attacker to control the startup/process space of the Graylog process though.
Changelog: https://github.com/square/okhttp/blob/parent-3.14.2/CHANGELOG.md
Bug Report: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-20200
=> Updating OkHttp from 3.11.0 to 3.14.2.

pom.xml
This change is updating Retrofit from 2.4.0 to 2.6.0. The current version is fixing a XXE vulnerability, described here[[0]]. It most probably has no impact on the product, as we do not use XML in the places where Retrofit is used, but it is unclear if e.g. a MitM could force the Retrofit client to interpret XML and therefore trigger the vulnerability.
The changelog for 2.6.0 is found here[[1]].
[0]: https://nvd.nist.gov/vuln/detail/CVE-2018-1000844
[1]: https://github.com/square/retrofit/blob/parent-2.6.0/CHANGELOG.md
=> Updating retrofit from 2.4.0 to 2.6.0.

graylog2-web-interface/vendor.modules.js, graylog2-web-interface/webpack/vendor-module-ids.json
Either by implicit (by using a component from core that uses them) or
explicit import (by using `c3`/`d3` directly) plugins include `c3`
and/or `d3` in their bundles, leading to unnecessarily huge bundle
sizes.
This PR is adding `c3` and `d3` to the vendor module, effectively
sharing them with plugins consuming those dependencies.
This leads to a size decrease e.g. for the enterprise plugin, while not
leading to bigger bundle sizes for core:
| (sizes in kb) | before | after |
|---------------|--------|-------|
| core          | 37696  | 35048 |
| enterprise    | 18604  | 16264 |
Relative size improvements for the entry size of the enterprise plugin are even better:
| (sizes in bytes)  | before  | after   |
|-------------------|---------|---------|
| enterprise plugin | 2558278 | 2068562 |
=> Including `c3` and `d3` in vendor module.

graylog2-server/src/main/java/org/graylog2/commands/Server.java, graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java, graylog2-server/src/main/java/org/graylog2/plugin/Message.java, graylog2-server/src/main/java/org/graylog2/rest/models/system/processing/ProcessingStatusSummary.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/processing/ClusterProcessingStatusResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/processing/RemoteSystemProcessingStatusResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/processing/SystemProcessingStatusResource.java, graylog2-server/src/main/java/org/graylog2/shared/bindings/GenericInitializerBindings.java, graylog2-server/src/main/java/org/graylog2/shared/buffers/DirectMessageHandler.java, graylog2-server/src/main/java/org/graylog2/shared/buffers/JournallingMessageHandler.java, graylog2-server/src/main/java/org/graylog2/shared/buffers/RawMessageEncoderHandler.java, graylog2-server/src/main/java/org/graylog2/shared/buffers/RawMessageEvent.java, graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/DecodingProcessor.java, graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java, graylog2-server/src/main/java/org/graylog2/system/processing/DBProcessingStatusService.java, graylog2-server/src/main/java/org/graylog2/system/processing/InMemoryProcessingStatusRecorder.java, graylog2-server/src/main/java/org/graylog2/system/processing/MongoDBProcessingStatusRecorderService.java, graylog2-server/src/main/java/org/graylog2/system/processing/ProcessingStatusConfig.java, graylog2-server/src/main/java/org/graylog2/system/processing/ProcessingStatusDto.java, graylog2-server/src/main/java/org/graylog2/system/processing/ProcessingStatusRecorder.java, graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerIT.java, graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesGetAllMessageFieldsIT.java, graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java, graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesIT.java, graylog2-server/src/test/java/org/graylog2/indexer/messages/MockedMessagesTest.java, graylog2-server/src/test/java/org/graylog2/system/processing/DBProcessingStatusServiceTest.java, graylog2-server/src/test/resources/org/graylog2/system/processing/processing-status.json, misc/graylog.conf
This PR introduces two timestamps that will be tracked through the message processing flow.
1. Receive time - this is the point in time the message was received on an input.
1. Processing time - this is the point in time after all message processors have been run and before the message is indexed
Both timestamp are currently not written to Elasticsearch because we need to adjust the index templates to make sure we can store them as date type with a `gl2_` prefix. We will adjust the index templates for 3.1 and start indexing the new timestamps in 3.2.
The receive time will be tracked per Graylog node so we are able to determine if processing is slow or behind. (e.g. peak hours with lots of messages in the journal) This processing status will be used by the new alerting to decide if …
=> Implement receive & processing time tracking

graylog2-web-interface/yarn.lock
Due to recent changes in transitively used packages
(`graylog-web-plugin` & `eslint-config-graylog`), this PR is updating
yarn lockfiles.
Refs Graylog2/graylog2-server#6041, Graylog2/graylog2-server#6042,
Graylog2/graylog2-server#6058, Graylog2/graylog2-server#5978 &
Graylog2/graylog2-server#5977.
=> Updating yarn lockfile.

graylog2-web-interface/packages/eslint-config-graylog/index.js, graylog2-web-interface/packages/eslint-config-graylog/package.json, graylog2-web-interface/yarn.lock
This change is adding the `eslint-plugin-react-hooks` [plugin](https://www.npmjs.com/package/eslint-plugin-react-hooks) to our
ESLint config, which is enforcing the [Rules of Hooks](https://reactjs.org/docs/hooks-rules.html) across React hooks usage.
=> Adding react hooks rules to ESLint config.

graylog2-web-interface/package.json, graylog2-web-interface/src/components/dashboard/AddToDashboardMenu.jsx, graylog2-web-interface/src/components/dashboard/AddToDashboardMenu.test.jsx, graylog2-web-interface/src/components/widgets/WidgetCreationModal.jsx, graylog2-web-interface/src/stores/nodes/NodesStore.js, graylog2-web-interface/test/mock-FetchProvider.js
When implicit/transitive dependencies of a SUT require stores that are not mocked and those stores do remote calls during initialization, promises are instantiated which are rejected asynchronously and - depending on the runtime of all tests - may or may not be rejected in the background. This leads to build failures in some cases (the probability seems to be higher for concurrent build/test runs) which are not even assignable to a specific test (case).
This change is mocking `FetchProvider` globally for jest, so no remote calls can be done using our fetch API. This is a precaution against the scenario described above and also a good indication for anyone writing a test that it is not properly mocked (as remote calls should never happen in test cases).
For most tests/stores this was not a …
=> Mocking FetchProvider globally for tests.

graylog2-server/src/main/java/org/graylog2/inputs/extractors/ExtractorFactory.java, graylog2-server/src/main/java/org/graylog2/inputs/extractors/GrokExtractor.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/InputFacadeTest.java, graylog2-server/src/test/java/org/graylog2/grok/MongoDbGrokPatternServiceTest.java, graylog2-server/src/test/java/org/graylog2/inputs/extractors/GrokExtractorTest.java
Prior to this change, a edit on a grok pattern did not
reflect on the used pattern in GrokExtractors
This change uses the GrokPatternRegistry which is
contains all grok patterns and is connected to the
cluster event bus and reloads when a grok pattern is
edit.
One test needed to be moved since it was testing the
grok pattern service which is not used anymore in the
GrokExtractor directly. There for the test was moved
to the MongoDbGrokPatternServiceTest where it belongs.
Fixes #5833
- Create a GrokExtractor with a GrokPattern
- Edit GrokPattern and send a message to the input
- Check that change on GrokPattern reflects the extractors work
=> Use GrokPatternRegistry to reload saved grok patterns

graylog2-server/src/main/java/org/graylog2/system/processing/ProcessingStatusConfig.java, misc/graylog.conf
Using 5 seconds is not often enough with regard to alert job execution.
Alert job execution checks this data in the database to decide if an
alert job can be executed or not.
=> Reduce processing_status_persist_interval default value to 1 second

graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx, graylog2-web-interface/src/stores/event-definitions/EventDefinitionsStore.js
- Set `alert` flag if at least one notification is configured
- Set `grace_period_ms` to 0 until we add an input for that
=> Adapt to schema changes

graylog2-web-interface/src/views/components/widgets/MessageList.jsx
Only display the pager in message lists, when the amount of messages is bigger
than the page size.
We right now always show a pager, even though we never need it, since the we only
ask for max 150 messages and the page size 150.
=> Dynamic pager in message lists

graylog2-web-interface/src/views/components/CustomPropTypes.js, graylog2-web-interface/src/views/components/aggregationbuilder/AggregationBuilderPropTypes.js, graylog2-web-interface/src/views/components/aggregationbuilder/AggregationControls.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/PivotConfiguration.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/PivotSelect.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/SeriesSelect.jsx, graylog2-web-interface/src/views/components/views/View.jsx, graylog2-web-interface/src/views/components/visualizations/XYPlot.jsx, graylog2-web-interface/src/views/components/widgets/MessageList.jsx, graylog2-web-interface/src/views/components/widgets/WidgetPropTypes.jsx, graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
When using `PropType.instanceOf` in development with HMR or
`loadable-components`, classes are loaded more than once and equality
checks/the `instanceof` operator fails, therefore also the `instanceOf`
prop type. This leads to non-sensical error messages like:
```
checkPropTypes.js:20 Warning: Failed prop type: Invalid prop `config` of type `AggregationWidgetConfig` supplied to `BarVisualization`, expected instance of `AggregationWidgetConfig`.
```
This change is implementing a custom `CustomPropTypes.instanceOf`
predicate, which expects a class as an argument and creates a prop type
matcher. For every invocation, the matcher extracts the prototype chain
(if present) of a given value and checks if the constructor name of the
argument class is included in those of the prototype chain of …
=> Using custom `instanceOf` prop-type in views.

graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.jsx, graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.test.jsx, graylog2-web-interface/src/views/components/messagelist/__snapshots__/CustomHighlighting.test.jsx.snap
Before this change, the configured value of a highlighting rule needed
to be a substring of the field's value only, to make it become
highlighted. This is counter-intuitive, especially for numeric field
values.
This change is changing this so the field value needs to match the
configured rule's value exactly.
Fixes Graylog2/graylog-plugin-enterprise#1118.
=> Apply custom highlighting only if field value matches configured value exactly.

graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.jsx
Stopping the `onClick` event lead to unwanted effects like checkboxes in
the pivot config modal not updating their state anymore.
Fixes #6093.
=> Removing `StopPropagation` wrapper from widget editing modal.

graylog2-web-interface/src/components/event-notifications/event-notification-types/HttpNotificationForm.jsx, graylog2-web-interface/src/components/event-notifications/event-notification-types/HttpNotificationSummary.jsx, graylog2-web-interface/src/components/navigation/Navigation.jsx, graylog2-web-interface/src/stores/event-definitions/EventDefinitionsStore.js, graylog2-web-interface/src/stores/event-notifications/EventNotificationsStore.js
This PR adds a couple of small changes in Events to be merged before the beta release:
- The first beta will ship with the old and new Alerting UI, so we are renaming the navigation entry for the new Alerting from `Next Alerts` to `Events`
- The HTTP JSON body customization feature still needs some work, and we are removing it from the UI for now
---
Edit: Also fixed an issue refreshing data in `EventDefinitionsStore`.
=> Events beta readiness

graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldsForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/field-value-providers/TemplateFieldValueProviderForm.jsx
This PR addresses some shortcomings of the field form inside the Events Definition Wizard:
- Add internal unique IDs, to help React track which components belong to which fields
- Add internal sorting of fields, to avoid components jumping on the page when updating the `Object` which contains all fields in the Events Definition data structure
- Sort fields when first rendering the fields form, avoiding any jumps while editing
- Append underscores to field names if they are not unique. Also avoid updating the object keys (which contain the field names) until the field name input loses the focus
- Set default data type to `string`, as the data type dropwdown is not expected to have more data types for now
Fixes #6127
Needs changes in https://github.com/Graylog2/graylog2-server/pull/6128 to …
=> Fields form improvements

graylog2-web-interface/src/logic/message/MessageFieldsFilter.js
The field should not show up in message details and the fields list, just like the other internal fields.
Refs #6074
Refs #5994
=> Add "gl2_message_id" field to MessageFieldsFilter in the UI

graylog2-web-interface/src/pages/EventsPage.jsx
This PR adds a description to the Events page. It also adds a help link, even if it's not going anywhere at the moment and serves more as a placeholder and reminder that we need to add that in the near future.
=> Add description and help link in Events page

graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationSummary.css, graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationSummary.jsx
On #6130 we added extra options to configure Email Notifications, but those were not displayed in the Notification summary. This PR adds them in the page.
=> Display all email configuration options in summary

graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionSummary.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationList.jsx
This PR takes care of fixing two issues when editing an Event Definition with deleted Notifications:
- In the Notifications step, having a deleted Notification will display a message indicating that we could not find information about the Notification and a button to remove the Notification, as we do with other Notifications
- In the Summary step, ensure the Notification was found on the list before trying to render its summary, and display a message otherwise
=> Display deleted Notifications in Event Definition form

graylog2-web-interface/src/components/events/events/Events.jsx
This change introduces another column in the events overview to show the event key.
=> Show the event key in the event/alerts overview

graylog2-web-interface/src/components/navigation/Navigation.jsx, graylog2-web-interface/src/components/navigation/Navigation.test.jsx, graylog2-web-interface/src/components/navigation/SystemMenu.jsx, graylog2-web-interface/src/components/navigation/SystemMenu.test.jsx
Due to the introduction of #5703, routes in the navigation bar are not
prefixed anymore automatically. Unfortunately this is required for
navigation items coming from plugins, as they have no knowledge about
the configured app path prefix.
This change is now automatically prefixing navigation items coming from
plugins.
Fixes #6149.
=> Prefix plugin navigation item path with app prefix.

graylog2-web-interface/src/pages/ShowMessagePage.jsx, graylog2-web-interface/src/pages/ShowMessagePage.test.jsx, graylog2-web-interface/src/pages/__snapshots__/ShowMessagePage.test.jsx.snap
Before this change, rendering a message generated by an event using the `ShowMessagePage` component, e.g. using the `/messages/{index}/{id}` endpoint failed, due to a missing source input id field in the event message.
This change is fixing this and a couple of other issues with rendering event messages.
Fixes #6142.
=> Fix rendering of events in single message view.

graylog2-server/src/main/java/org/graylog2/alarmcallbacks/EmailAlarmCallback.java
The previous default (`@example.org`) is problematic for use cases where
the email server rejects sender domains which are not validated / owned
by the graylog server owners (e.g. amazon ses).
In our use case users often forgot to empty the value and left the
default in which resulted in notifications which where not sent out.
With this change the default is empty and if I understand the code
correctly the result would be that the default which is set in the
server configuration should be used.
Fired up a test instance and took a look at the empty field value.
Sorry, did not take any :(
=> Set default value for email sender to empty value

graylog-project-parent/pom.xml, graylog2-server/pom.xml, graylog2-server/src/main/java/org/graylog2/rest/models/system/responses/LocalesResponse.java, pom.xml
This PR updates the server code base to support JDK 11.
This also requires updates to a few plugins due to the UUID changes.
There is a warning that is printed on server startup:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.assistedinject.FactoryProvider2$MethodHandleWrapper (file:/home/bernd/.m2/repository/com/google/inject/extensions/guice-assistedinject/4.2.2/guice-assistedinject-4.2.2.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of com.google.inject.assistedinject.FactoryProvider2$MethodHandleWrapper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All …
```
=> Add JDK 11 support

graylog2-web-interface/src/views/components/widgets/WidgetFilterMenu.jsx
Before this change, closing the widget filter menu popover resulted in
it immediately showing again and logging an error to the console. This
was the result of not passing a function for `onChange` to the
`QueryInput` component that returns a Promise.
This change is fixing that by returning a promise from the `onChange`
handler.
Before:
After:
=> Fix closing of widget filter menu.

graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDetailsForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-types/index.js, graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationForm.jsx, graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationForm.jsx, graylog2-web-interface/src/components/event-notifications/event-notification-types/HttpNotificationForm.jsx, graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationForm.jsx, graylog2-web-interface/src/components/event-notifications/event-notification-types/index.js
This PR changes how we handle default configurations from plugins.
Before, plugins had to do it on their own, mostly in the `componentDidMount()` lifecycle state, which is not great place for it and it is also easy to forget. Failing to do so may have ended up in default configuration options not being persisted.
After these changes, plugins can define a `defaultConfig` object, which we set alongside the plugin type. For example, changing the Notification type will get the `defaultConfig` (if any) for the selected type and apply it to the form data. Users can later do changes to those default values.
Applying default configurations on type change also helps us to fix #6185.
=> Improve handling of default configurations in Event Definitions and Notifications

graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationForm.jsx
This setting should default to empty or the value set in the server email server configuration, to avoid users sending emails to an inexistent email address by mistake. Since default settings live for now in the frontend and there is no easy access to email configuration from there, I decided to leave it empty for now.
Fixes #6159
=> Unset default sender

graylog2-web-interface/src/components/widgets/configurations/QuickValuesConfiguration.jsx
`MultiSelect` requires the `options` prop and `QuickValuesConfiguration` was not providing it, causing an error to be thrown.
This commit adds an empty array as `options` to fix the issue.
I also checked in our codebase trying to find any other cases where this happened but I couldn't find any.
Fixes #6187
=> Set Select options prop in QuickValuesConfiguration

graylog2-server/src/main/java/org/graylog2/streams/StreamRouterEngine.java
This change is a performance optimization for the stream router engine.
When matching a message against the configured stream rules, it maintains a blacklist containing streams that have already been processed and are a) either unable to match anymore (in case of an `AND`-matched stream that already has a mismatch) or b) have already matched finally (in case of an `OR`-matched stream that already has one match).
This blacklist contains complete `Stream` objects, which means that a check if the stream of the current rule is already blacklisted (by calling `blacklist.contains(obj)`) is generating hash codes for comparison by iterating over all fields of both streams.
In our case comparing the two stream IDs is enough, as they can be considered unique and a mismatch between the two means …
=> Use stream ids for blacklisting in stream router engine.

graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationForm.jsx
If users open an existing legacy notification where the plugin is
missing, the UI throws an error. This fixes it by checking if the plugin
type exists and showing a warning if it's missing.
=> Fix error when opening legacy notifications and the plugin is missing

graylog2-web-interface/package.json, graylog2-web-interface/webpack.config.js, graylog2-web-interface/webpack.vendor.js, graylog2-web-interface/yarn.lock
uglify-es is no longer supported and uglify-js doesn't have great ES6 support, which requires babel to transpile, but then there is issues with [React's hooks](https://github.com/mishoo/UglifyJS2/issues/3291) so we migrated to Terser, which has latest ES6 support and compiles a smaller, faster, package.
Resolves #6204 
Manually checking reports of broken components and test driving application
=> Replacing uglify with Terser for better ES6 support

graylog2-web-interface/src/components/common/PaginatedList.jsx, graylog2-web-interface/src/components/common/SearchForm.jsx, graylog2-web-interface/src/components/common/TimeUnitInput.jsx, graylog2-web-interface/src/components/events/events/EventDetails.jsx, graylog2-web-interface/src/components/events/events/Events.css, graylog2-web-interface/src/components/events/events/Events.jsx, graylog2-web-interface/src/components/events/events/EventsContainer.jsx, graylog2-web-interface/src/components/events/events/EventsSearchBar.css, graylog2-web-interface/src/components/events/events/EventsSearchBar.jsx
This PR adds the functionality to manually refresh the Alert/Event list.
It additionally refactor the `Events` component to make it more modular and improves the overall styling of the Event search controls.
Fixes #6154
=> Add refresh button to Events page

graylog2-server/src/main/java/org/graylog/scheduler/DBJobTriggerService.java, graylog2-server/src/main/java/org/graylog/scheduler/JobExecutionEngine.java, graylog2-server/src/test/java/org/graylog/scheduler/DBJobTriggerServiceTest.java, graylog2-server/src/test/resources/org/graylog/scheduler/stale-job-triggers.json
This will only cleanup trigger that are owned by the calling server
node. It will fix stale job trigger after an unclean JVM or server
shutdown.
Closes Graylog2/graylog-plugin-enterprise#1139
=> Cleanup stale job trigger on server startup

graylog2-server/src/main/java/org/graylog/events/indices/MoreIndices.java
We now lookup every write index for every stream an event should be
written to.
Also remove info log statement for successful event indexing.
=> Remove hardcoded write index for event indexing

graylog2-server/src/main/java/org/graylog/scheduler/DefaultJobSchedulerConfig.java, graylog2-server/src/main/java/org/graylog/scheduler/JobSchedulerConfig.java, graylog2-server/src/main/java/org/graylog/scheduler/JobSchedulerService.java
- Rename "canRun" to "canStart"
- Add "canExecute"
Also don't run scheduler loop if "canExecute" returns false. In that
case sleep for a while and retry.
(Tests will fail because of missing changes in plugins.)
=> Change JobSchedulerConfig interface

graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationForm.jsx
Only show the warning if a legacy type has been selected but that type cannot be found.
Fixes #6218
=>  Fix issue showing unknown legacy type warning when creating notification

graylog2-web-interface/src/components/event-notifications/event-notification-types/CommonNotificationSummary.css, graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationCommonStyles.css, graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationForm.jsx, graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationSummary.jsx
When selecting a notification from a removed legacy alarm callback plugin in the Event Definition form, going to the summary step results in an error.
This commit fixes the issue by checking if the configuration is defined before accessing it and displaying a message like in #6199.
=> Fix error for missing legacy notification plugins in Event Definition form

graylog2-server/src/main/java/org/graylog2/shared/rest/resources/ProxiedResource.java
Connection errors in ProxiedResource can happen if other nodes in the cluster are restarting. Only log the stack trace if `DEBUG` is enabled for the logger. Otherwise log a one-line message.
<details>
<summary>Example stack trace</summary>
```
2019-07-31 23:37:03,022 WARN : org.graylog2.shared.rest.resources.ProxiedResource - Unable to call http://127.0.0.1:9010/api/system/metrics/multiple on node <38fe132d-0a9a-4194-ae18-73d9fd1e134c>
java.net.ConnectException: Failed to connect to /127.0.0.1:9010
at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265) ~[okhttp-3.14.2.jar:?]
at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183) ~[okhttp-3.14.2.jar:?]
at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224) …
```
=> Avoid logging excessive exceptions in ProxiedResource

bin/graylogctl
Check if -XX:+UseParNewGC option is available
This option was deprecated in java 8 and removed from in java 9.
https://openjdk.java.net/jeps/214
Closes #5444
=> Remove -XX:+UseParNewGC option from jdk

graylog2-web-interface/src/components/alertconditions/AlertConditionsComponent.jsx, graylog2-web-interface/src/components/alertnotifications/AlertNotificationsComponent.jsx, graylog2-web-interface/src/components/alerts/AlertsHeaderToolbar.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.jsx, graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationFormContainer.jsx, graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotifications.jsx, graylog2-web-interface/src/components/events/events/EventDetails.jsx, graylog2-web-interface/src/components/events/events/Events.jsx, graylog2-web-interface/src/components/events/events/EventsContainer.jsx, graylog2-web-interface/src/components/navigation/Navigation.jsx, graylog2-web-interface/src/components/navigation/Navigation.test.jsx, graylog2-web-interface/src/pages/AlertConditionsPage.jsx, graylog2-web-interface/src/pages/AlertNotificationsPage.jsx, graylog2-web-interface/src/pages/AlertsPage.jsx, graylog2-web-interface/src/pages/CreateEventDefinitionPage.jsx, graylog2-web-interface/src/pages/CreateEventNotificationPage.jsx, graylog2-web-interface/src/pages/EditAlertConditionPage.jsx, graylog2-web-interface/src/pages/EditEventDefinitionPage.jsx, graylog2-web-interface/src/pages/EditEventNotificationPage.jsx, graylog2-web-interface/src/pages/EventDefinitionsPage.jsx, graylog2-web-interface/src/pages/EventNotificationsPage.jsx, graylog2-web-interface/src/pages/EventsPage.jsx, graylog2-web-interface/src/pages/NewAlertConditionPage.jsx, graylog2-web-interface/src/pages/NewAlertNotificationPage.jsx, graylog2-web-interface/src/pages/ShowAlertPage.jsx, graylog2-web-interface/src/pages/StreamAlertsOverviewPage.jsx, graylog2-web-interface/src/routing/AppRouter.jsx, graylog2-web-interface/src/routing/Routes.jsx
This PR takes care of preparing the move to the new alerting:
- Updates navigation menu to link Alerts to the new product
- Prefixes legacy alerting URLs to `/legacy/alerts`, so they are still accessible in case they are necessary
- Removes prefix from new Alerting/Events URLs
- Adds a filter in Alerts page to filter Events/Alerts for a stream
- Updates the "Manage Alerts" button in the Streams page to go to Alerts with a filter set for that particular Stream
Fixes #6108
=> Adjust UI for new alerting

graylog2-server/src/main/java/org/graylog/events/EventsModule.java, graylog2-server/src/main/java/org/graylog/events/contentpack/entities/EmailEventNotificationConfigEntity.java, graylog2-server/src/main/java/org/graylog/events/contentpack/entities/EventNotificationConfigEntity.java, graylog2-server/src/main/java/org/graylog/events/contentpack/entities/HttpEventNotificationConfigEntity.java, graylog2-server/src/main/java/org/graylog/events/contentpack/entities/LegacyAlarmCallbackEventNotificationConfigEntity.java, graylog2-server/src/main/java/org/graylog/events/contentpack/entities/NotificationEntity.java, graylog2-server/src/main/java/org/graylog/events/contentpack/facade/NotificationFacade.java, graylog2-server/src/main/java/org/graylog/events/legacy/LegacyAlarmCallbackEventNotificationConfig.java, graylog2-server/src/main/java/org/graylog/events/notifications/EventNotificationConfig.java, graylog2-server/src/main/java/org/graylog/events/notifications/NotificationDto.java, graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailEventNotificationConfig.java, graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationConfig.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/ModelTypes.java
Implement a NotificationFacade and its needed Entities.
EventDefinitions are only use full if the create Alerts with Notifications.
- Exported, Imported and Installed an Content Pack containing a Notification.
- There are still problem with parameters
- Notification should be a dependency to EventDefinition
=> Add Notification to content packs

graylog2-server/src/main/java/org/graylog/events/notifications/NotificationResourceHandler.java, graylog2-server/src/main/java/org/graylog/events/processor/DBEventDefinitionService.java, graylog2-server/src/main/java/org/graylog/events/processor/EventDefinitionDto.java, graylog2-server/src/test/java/org/graylog/events/legacy/LegacyAlertConditionMigratorTest.java
When a notification definition is deleted we need to clean up all events which make use of it.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/1119
=> Remove notification action from event definition on notification delete

graylog2-web-interface/src/components/event-definitions/common/HelpPanel.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/AddNotificationForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/EventConditionForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionSummary.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldsForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/field-value-providers/LookupTableFieldValueProviderFormContainer.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/field-value-providers/LookupTableFieldValueProviderSummary.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationSummary.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterPreview.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterPreviewContainer.jsx, graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.jsx, graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotifications.jsx, graylog2-web-interface/src/components/events/events/EventDetails.jsx, graylog2-web-interface/src/components/events/events/Events.jsx, graylog2-web-interface/src/components/events/events/EventsContainer.jsx, graylog2-web-interface/src/pages/CreateEventDefinitionPage.jsx, graylog2-web-interface/src/pages/CreateEventNotificationPage.jsx, graylog2-web-interface/src/pages/EditEventDefinitionPage.jsx, graylog2-web-interface/src/pages/EditEventNotificationPage.jsx, graylog2-web-interface/src/pages/EventDefinitionsPage.jsx, graylog2-web-interface/src/pages/EventNotificationsPage.jsx, graylog2-web-interface/src/pages/EventsPage.jsx
Authorize pages and components in the UI, hiding elements that a user should not see to avoid leaking any information.
These are the permissions that a user must have in order to see all information in the pages:
```
eventdefinitions:*
eventnotifications:*
streams:read
users:list
extendedsearch:create
extendedsearch:use
lookuptables:read
```
=> Authorize Event pages in UI

.editorconfig
Since I updated IntelliJ to 2019.2, I noticed changed indentation
behavior on line continuations. Instead of the standard 8 characters we
are using everywhere, I now only get 4 characters of indentation. This
is pretty annoying and also doesn't match the "standard" IntelliJ code
style we are using for years.
It looks like IntelliJ is now handling editorconfig files differently
and now supports vendor specific settings.
This change is adding the "ij_continuation_indent_size" IntelliJ
specific editorconfig setting to restore the old behavior of 8
character indent for line continuations.
Example of "broken" line continuation:
The `.lifecyleStatus()` should have been indented with 8 characters.
=> Add "ij_continuation_indent_size" setting to .editorconfig

graylog2-web-interface/src/components/ldap/LdapComponent.jsx
This PR fixes the issue by converting the array into a string and passing that down to `MultiSelect`. 
It also replaces a "fake" `MultiSelect` component with `Select`.
Fixes #6247
=> Fix rendering of LDAP page

graylog2-server/src/main/java/org/graylog2/database/PaginatedDbService.java
Before this change, in `PaginatedDbService#findPaginatedWithQueryFilterAndSort` a single stream was used to filter (based on the query), paginate (based on page size and page number) and determine the number of total items (before pagination). The latter is performed using `Stream#peek`, which has the following characteristics:
1. The docs say: `This method exists mainly to support debugging, where you want to see the elements as they flow past a certain point in a pipeline`
2. `peek` is an intermediate operation on a stream, which means that
a) it's actual execution is driven by the terminal operation of the stream
b) it has the benefit in this case that a single stream execution is able to perform multiple tasks
The code before this PR relies on `peek` being executed for each item on …
=> Avoid using `Stream#peek` for counting items in paginated result set.

graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationFormContainer.jsx
While this is something we want to allow in the future, it's currently not possible to use the nested custom fields of an event in fields for aggregation grouping and aggregation series fields.
Fixes #6236
=> Hide unsupported Streams from Filter Select

graylog2-web-interface/src/components/common/Wizard.jsx, graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap
Prior to this change, the preview page was to wide, which resulted
in a broken view.
This change will only make the lefComponentCols 12 wide if
it is horizontal.
Fixes #6197
=> Fix wizard layot design for content packs

graylog2-web-interface/src/components/common/ConfirmLeaveDialog.jsx, graylog2-web-interface/src/components/common/TimeUnitInput.jsx, graylog2-web-interface/src/components/common/TimeUnitInput.test.jsx, graylog2-web-interface/src/components/common/index.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationSettingsForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/field-value-providers/TemplateFieldValueProviderPreview.css, graylog2-web-interface/src/components/event-definitions/event-definition-form/field-value-providers/TemplateFieldValueProviderPreview.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationFormContainer.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationSummary.css, graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationSummary.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterPreview.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-types/withStreams.jsx, graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.css, graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.jsx, graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationFormContainer.jsx, graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotifications.css, graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotifications.jsx, graylog2-web-interface/src/components/events/events/EventsSearchBar.jsx, graylog2-web-interface/src/pages/CreateEventDefinitionPage.jsx, graylog2-web-interface/src/pages/CreateEventNotificationPage.jsx, graylog2-web-interface/src/pages/EditEventDefinitionPage.jsx, graylog2-web-interface/src/pages/EditEventNotificationPage.jsx, graylog2-web-interface/src/routing/Routes.jsx
These PR contains more improvements from #6155, namely:
- Add confirmations before leaving Event Definition and Notification forms (must run in production to be seen)
- Change position of create buttons to reduce amount of empty space in Event Definition list and Notification list
- Style template preview as other previews
- Allow clearing number inputs
- Allow clearing `TimeUnitInput`s
- Display deleted streams in Filter & Aggregation
- Display stream names in Filter & Aggregation summary
- Use more consistent URL for edit pages
=> More Events UI improvements

graylog2-server/src/main/java/org/graylog/events/contentpack/facade/EventDefinitionFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackable.java
Prior to this change, the correlation config did not add its enterprise
plugin constraint to the constraints list.
This change adds a new function to the ContentPackable constraint:
getPackageName.
This is necessary since the package name of CorrelationConfig is
graylog.plugins.events but we need graylog.plugin.enterprise since
it is the name of the constraint.
=> Implement new getPackageName function for versionConstraints

graylog2-server/src/main/java/org/graylog/events/processor/EventProcessorDependencyCheck.java, graylog2-server/src/main/java/org/graylog2/shared/journal/KafkaJournal.java, graylog2-server/src/main/java/org/graylog2/system/processing/DBProcessingStatusService.java, graylog2-server/src/main/java/org/graylog2/system/processing/InMemoryProcessingStatusRecorder.java, graylog2-server/src/main/java/org/graylog2/system/processing/MongoDBProcessingStatusRecorderService.java, graylog2-server/src/main/java/org/graylog2/system/processing/ProcessingStatusConfig.java, graylog2-server/src/main/java/org/graylog2/system/processing/ProcessingStatusDto.java, graylog2-server/src/main/java/org/graylog2/system/processing/ProcessingStatusRecorder.java, graylog2-server/src/test/java/org/graylog2/system/processing/DBProcessingStatusServiceTest.java, graylog2-server/src/test/resources/org/graylog2/system/processing/processing-status-node-selection-test.json, graylog2-server/src/test/resources/org/graylog2/system/processing/processing-status.json, misc/graylog.conf
Previously we did the processing status record selection based on the
active node list in the cluster. Since that system is pretty aggressive
removing nodes from the database, we needed something else.
Another problem was that nodes which didn't receive any log messages
but are part of the cluster and update their processing status records,
would be included in the earliest post-indexing timestamp computation.
Since these inactive nodes wouldn't receive any log messages, the
timestamp would always be very old and the events system wouldn't
run any jobs. (See #6228)
We are now choosing processing status records where:
- the "updated_at" timestamp has been updated recently (configurable)
- and either the 1 minute journal write rate is larger than a threshold
(configurable)
- or the number …
=> Improve processing status handling to avoid blocking event processing

graylog2-server/src/main/java/org/graylog/events/legacy/LegacyAlertConditionMigrator.java, graylog2-server/src/test/java/org/graylog/events/legacy/LegacyAlertConditionMigratorTest.java, graylog2-server/src/test/resources/org/graylog/events/legacy/legacy-alert-conditions.json
Use default title when `AlarmCallback` or `AlertCondition` title is `null`.
Fixes #6241
=> Migrate Legacy Alerts and Notifications without title

graylog2-server/src/main/java/org/graylog2/inputs/transports/netty/EnvelopeMessageAggregationHandler.java
Before this change, whenever a UDP message came in with a 0 or 1 byte header (smaller than the 2 byte GELF header), the thread handling this message throws an exception in `GELFMessage#getGELFType` which is caught in `EnvelopeMessageHandler#exceptionCaught`. In there, the channel is closed. This is correct for a TCP-based input, as the corresponding TCP-connection would be closed, as each channel corresponds to a TCP connection. This is not the case for UDP pipelines. Closing a channel of a UDP pipeline leads to the handler/thread losing the overall connection to the socket multiplexing. If this happens for a number of times equaling the number of working threads, the whole input stops processing any UDP messages as there is no thread left which is able to receive channel events.
This …
=> Prevent closing of UDP channel in input for messages with bogus GELF header.

pom.xml
Includes fixes for CVE-2019-12086, CVE-2019-12384, CVE-2019-12814,
CVE-2019-14379 and CVE-2019-14439.
See https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.8 for details.
Update to the latest bom for 2.8 which includes the 2.8.11.4 version of
jackson-databind.
=> Security update to jackson-databind 2.8.11.4

graylog2-server/src/main/java/org/graylog2/contentpacks/facades/StreamFacade.java, graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackServiceTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/StreamCatalogTest.java
The StreamFacade will continue to create new legacy alert conditions and
alarm callbacks for now but immediately runs the migration to create
event definitions and notifications for them.
Closes #6261
=> Disable content pack entity creation for legacy conditions and callbacks

graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailSender.java
This PR reduces exceptions in cases of an empty Email receiver list. The lists are already validated in the frontend and the API. So this case indicates a broken setup and we should not retry to send the notification.
Fixes: https://github.com/Graylog2/graylog2-server/issues/6163
=> Dont throw exception on misconfigured email notification

graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessor.java, graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationSearch.java, graylog2-server/src/main/java/org/graylog/events/processor/aggregation/PivotAggregationSearch.java, graylog2-server/src/main/java/org/graylog/events/search/MoreSearch.java, graylog2-server/src/test/java/org/graylog/events/processor/aggregation/AggregationEventProcessorTest.java, graylog2-server/src/test/java/org/graylog/events/processor/aggregation/PivotAggregationSearchTest.java
This PR let the AggregationEventProcessor only throw EventProcessorExceptions to handle failed searches in a better way. Also searches on removed streams should now be handled so that the processor still works on the remaining streams.
Fixes: https://github.com/Graylog2/graylog-plugin-enterprise/issues/1062
=> Improve Event processor exceptions

graylog2-web-interface/src/components/event-definitions/event-definition-form/field-value-providers/LookupTableFieldValueProviderForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationForm.jsx
This PR ensures lists of Fields and Lookup Tables are sorted. Other entities are sorted in the frontend or API already.
Refs #6155
=> Sort entities in alerting forms

graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewDTO.java
This change is adding a `type` field to `ViewDTO` objects defining if
this view is a search or a dashboard. The decision to add a type field
instead of separate classes is based on the following aspects:
* There are very little differences between searches and dashboards:
* Searches do allow only a single Query
* Dashboards contain a list of widgets being shown in display mode
* AutoValue does not allow/discourages inheritance for value classes
* Creating two distinct classes without sharing attributes would
result in mostly duplicated code and the necessity to update both
classes for changes to prevent subtle bugs
* Turning a search into a dashboard is required in future use cases.
Doing this with a single class that differs only in the value of the
`type` attributes allows to just …
=> Adding type field to view DTO to discriminate searches & dashboards.

graylog2-web-interface/src/components/cluster/TrafficGraph.jsx, graylog2-web-interface/src/util/NumberUtils.js
Numeral 2.0 changed the "b" format modifier and we now have to use "ib"
to get the Graylog 3.0 (and earlier) behavior.
Relevant changelog entry:
> Breaking change / Feature: Bytes are now formatted as: b (base 1000) and ib (base 1024)
Switch TrafficGraph.jsx to use NumberUtils instead of using numeral
directly.
Fixes #6175
=> Fix bytes formatting after numeral major update.

graylog2-server/src/main/java/org/graylog/events/contentpack/entities/AggregationEventProcessorConfigEntity.java, graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessorConfig.java, graylog2-server/src/test/java/org/graylog/events/contentpack/facade/EventDefinitionFacadeTest.java
Prior to this change, there was a problem assigning a parameter to a
long typed field of event definition config. The web ui does not
really support long values yet.
This change will replace the ValueRefrence type of the fields
with long.
Created a content pack and tried to add a parameter to disabled fields.
=> Remove ability to add parameters to long typed fields

pom.xml
Includes fixes for CVE-2019-9512, CVE-2019-9514, CVE-2019-9515 and
CVE-2019-9518. (HTTP/2 related issues)
See https://netty.io/news/2019/08/13/4-1-39-Final.html for details.
=> Security update to netty-4.1.39

graylog2-web-interface/src/components/navigation/Navigation.jsx, graylog2-web-interface/src/components/navigation/Navigation.test.jsx, graylog2-web-interface/src/components/navigation/SystemMenu.jsx, graylog2-web-interface/src/components/navigation/SystemMenu.test.jsx
Due to the introduction of #5703, routes in the navigation bar are not
prefixed anymore automatically. Unfortunately this is required for
navigation items coming from plugins, as they have no knowledge about
the configured app path prefix.
This change is now automatically prefixing navigation items coming from
plugins.
Fixes #6149.
(Backported to `3.0`)
=> Prefix plugin navigation item path with app prefix. (3.0)

graylog2-web-interface/src/components/inputs/InputsList.jsx
Fixes #5921
Create some inputs starting with uppercase and lowercase, they were sorted as described in the issue. With this changes the case wont matter in sorting.
=> Ignore case when sorting Inputs

graylog2-server/pom.xml, pom.xml
Downgrade download-maven-plugin to version 1.3.0
until this is fixed:
https://github.com/maven-download-plugin/maven-download-plugin/issues/80
```
[ERROR] Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.4.1:wget (install-headless-shell) on project graylog2-server: Execution install-headless-shell of goal com.googlecode.maven-download-plugin:download-maven-plugin:1.4.1:wget failed: java.lang.ClassNotFoundException: com.googlecode.download.maven.plugin.internal.CachedFileEntry -> [Help 1]
```
=> Fix mvn test / sync versions between server and enterprise

graylog2-web-interface/public/stylesheets/bootstrap-config.json, graylog2-web-interface/src/components/throughput/GlobalThroughput.css
Changed max-height of 340px to 90vh to allow for the dropdown navigation to show as much as possible.
Fixes #6328
=> Increase height of navigation to show collapsable content

graylog2-server/src/main/java/org/graylog2/system/processing/DBProcessingStatusService.java
Using the auto generated one can become a problem with the 127 character
limit in MongoDB if the database name is long.
Fixes #6322
=> Use custom name for the compound index in DBProcessingStatusService

graylog2-server/src/main/java/org/graylog2/inputs/transports/RandomMessageTransport.java, graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/GeneratorTransport.java
A long sleep time for the Random HTTP message generator
will prevent the server from shutting down.
Excplicitely interrupt the AbstractExecutionThreadService runThread
to abort the sleep.
- [x ] Bug fix (non-breaking change which fixes an issue)
=> Don't block server shutdown in FakeHttpMessageInput

graylog2-web-interface/src/views/logic/views/ViewDeserializer.js
Before this change, calling the `ViewActions.load` action from
`ViewDeserializer` was not returning the promise of it, so it was not
waited upon to resolve. This lead to an issue, where loading the view
took longer than toggling the `loaded` status flag in `ShowViewPage`,
leading to rendering components which relied on the view being loaded
already.
This change is now returning the promise received from
`ViewActions.load`, so it is waited on.
Fixes #6346.
=> Wait for `ViewActions.load` in promise chain and still return view.

graylog2-server/src/main/java/org/graylog/plugins/views/search/views/DisplayModeSettings.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewStateDTO.java
This change is adding a `DisplayModeSettings` class which keeps track of widgets being shown in the display mode of a dashboard by recording their positions.
**Note:**
Requires #6266 to be merged before.
=> Adding settings class for display mode to view/query state class.

graylog2-web-interface/src/routing/AppRouter.jsx, graylog2-web-interface/src/views/bindings.jsx, graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
This change prepares the search page for replacement with the views-based search page by registering the new extended search as the default search.
Additionally, it removes the query bar from the extended search, as the search replacement is supposed to have only a single query to resemble the existing search more closely.
=> Replacing existing search page with extended search, removing query bar.

graylog2-web-interface/src/routing/Routes.jsx
Before this change, retrieval of plugin routes using `Routes.pluginRoute('...')` had the following issue:
1. Plugin routes were retrieved once and then stored in `window.pluginRoutes`
2. Every consumer (core or any plugin) needs to import `Routes.jsx` to be able to retrieve a plugin route
3. When the file is imported from a different scope (e.g. core vs plugin, or plugin1 vs. plugin2), the file is evaluated again, performing 1. again.
This means that the contents of `window.pluginRoutes` could be different depending on when an where the module is imported. This could lead to a scenario of:
* Plugin A requires a plugin route of Plugin B at runtime.
* If Plugin B was not loaded before Plugin A, `window.pluginRoutes` does not contain Plugin B's routes if it was only imported from Plugin A …
=> Fix retrieval of registered plugin routes.

graylog2-web-interface/src/routing/AppRouter.jsx, graylog2-web-interface/src/views/bindings.jsx, graylog2-web-interface/src/views/pages/StreamSearchPage.jsx, graylog2-web-interface/src/views/stores/QueryFiltersStore.js
This change is replacing the current stream search with the new views-based extended search. That means that a user going to `Streams` and selecting a stream for search will create a new extended search, having the selected stream preconfigured in the stream filter. From then on, the extended search behaves as any other extended search, which means that this stream can be removed again from the filter or additional streams can be added.
**Note:**
Requires #6268 to be merged before.
=> Replace stream search with new extended search.

graylog2-server/pom.xml, pom.xml
This PR is backporting #6320 to `3.1`.
Downgrade download-maven-plugin to version 1.3.0 until this is fixed:
https://github.com/maven-download-plugin/maven-download-plugin/issues/80
```
[ERROR] Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.4.1:wget (install-headless-shell) on project graylog2-server: Execution install-headless-shell of goal com.googlecode.maven-download-plugin:download-maven-plugin:1.4.1:wget failed: java.lang.ClassNotFoundException: com.googlecode.download.maven.plugin.internal.CachedFileEntry -> [Help 1]
```
(cherry picked from commit fafe8b5653c25f05841565ea0ef607b2b8e4e8dd)
=> Fix mvn test / sync versions between server and enterprise (#6320)

graylog2-web-interface/src/views/Constants.js, graylog2-web-interface/src/views/bindings.jsx, graylog2-web-interface/src/views/components/contexts/ViewTypeContext.jsx, graylog2-web-interface/src/views/components/dashboard/IfDashboard.jsx, graylog2-web-interface/src/views/components/widgets/Widget.jsx, graylog2-web-interface/src/views/hooks/__snapshots__/RequirementsProvided.test.jsx.snap, graylog2-web-interface/src/views/logic/views/View.js, graylog2-web-interface/src/views/pages/DashboardsPage.jsx, graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx, graylog2-web-interface/src/views/pages/NewDashboardPage.jsx, graylog2-web-interface/src/views/pages/NewSearchPage.jsx, graylog2-web-interface/src/views/pages/ShowViewPage.test.jsx, graylog2-web-interface/src/views/stores/StoreTypes.js, graylog2-web-interface/src/views/test/ViewFixtures.js
This change is conditionally rendering the query bar and widget filter icon if the current view is a dashboard. For this, the PR does:
* Add a `ViewTypeContext` React context providing current view type
* Add a `IfDashboard` component for conditional rendering of children
if current view is a dashboard
* Conditionally render the affected elements
**Note:**
Requires #6268, #6270, #6271 to be merged before.
=> Render query bar and widget filter icon if current view is dashboard.

graylog2-web-interface/src/views/logic/views/ViewDeserializer.js
Before this change, calling the `ViewActions.load` action from
`ViewDeserializer` was not returning the promise of it, so it was not
waited upon to resolve. This lead to an issue, where loading the view
took longer than toggling the `loaded` status flag in `ShowViewPage`,
leading to rendering components which relied on the view being loaded
already.
This change is now returning the promise received from
`ViewActions.load`, so it is waited on.
Fixes #6346.
=> Wait for `ViewActions.load` in promise chain and still return view

graylog2-web-interface/src/util/AppConfig.js, graylog2-web-interface/webpack.config.js
This change is adding a simple way to enable frontend features for
development which are disabled per default. The change is two-fold:
* Evaluating a `FEATURES` environment variable which contains a
comma-delimited string of feature names to enable
* Adding a `AppConfig.isFeatureEnabled` function, which returns a
boolean indicating if the given feature is enabled or not. This can be
used in the code to conditionally render parts of the UI.
Notes:
The content of the `FEATURES` can contain multiple features separated by
commas. Additionally, individual feature flags are compared
case-insensitively, so `FEATURES=Time_Travel` will enable the
`time_travel` feature as well.
Example:
If a feature `time_travel` is developed but should not be enabled by
default, developers can do a …
=> Allowing to enable (experimental) frontend features for development.

graylog2-web-interface/src/routing/AppRouter.jsx, graylog2-web-interface/src/views/bindings.jsx
This change disables replacing the existing search/dashboard functionality with the new views-based ones per default, so other developers/users of the `master` branch are not impacted, until existing dashboards are migrated properly. To enable the new functionality, run the development server like this:
```
FEATURES=search_3_2 yarn run start
```
=> Hide replacing search/dashboard functionality behind feature flag.

graylog2-web-interface/src/components/rules/RuleForm.jsx
Prevents redirect to rules list when saving pipeline rules
Fixes #6312 
Create a new rule and save it, with this change the save ok notification will appear but no redirect to rules list will happen.
=> Dont save and close when editing pipeline rules

graylog2-web-interface/package.json, graylog2-web-interface/packages/graylog-web-plugin/package.json, graylog2-web-interface/yarn.lock
This PR is updating the following dependencies:
* `webpack`: `4.27.0` -> `4.39.3`
* `webpack-dev-middleware`: `3.3.0` -> `3.7.1`
* `webpack-dev-server`: `3.1.8` -> `3.8.0`
* `webpack-hot-middleware`: `2.24.0` -> `2.25.0`
* `webpack-merge`: `4.1.4` -> `4.2.2`
* `webpack-cli`: `3.1.1` -> `3.3.7`
=> Updating webpack and related dependencies.

graylog2-server/src/main/java/org/graylog/events/legacy/LegacyAlarmCallbackSender.java, graylog2-server/src/main/java/org/graylog/events/notifications/EventNotificationContext.java, graylog2-server/src/main/java/org/graylog/events/notifications/NotificationResourceHandler.java, graylog2-server/src/main/java/org/graylog/events/notifications/NotificationTestData.java, graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailSender.java, graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotification.java, graylog2-server/src/main/java/org/graylog/events/rest/EventNotificationsResource.java, graylog2-server/src/test/java/org/graylog/events/legacy/LegacyAlertConditionMigratorTest.java, graylog2-server/src/test/java/org/graylog/events/notifications/NotificationResourceHandlerTest.java, graylog2-web-interface/src/actions/event-notifications/EventNotificationsActions.js, graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationForm.jsx, graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationFormContainer.jsx, graylog2-web-interface/src/stores/event-notifications/EventNotificationsStore.js
This change implements the ability to test notifications with a dummy event.
Tests can also be triggered while editing or creating a notification.
Testing from the embedded mode within event creation page is currently not supported.
Fixes #6138
=> Implement Notification Test button

graylog2-web-interface/src/routing/AppRouter.jsx
In #6368, a feature flag was introduced, that enables the new
views-based search. Unfortunately, it was forgotten to add the route
for the existing stream search when the feature flag is disabled, so
without the feature flag it is inaccessible. This PR is fixing this.
=> Fixing existing stream search when feature flag is disabled.

graylog2-web-interface/src/views/components/dashboard/IfDashboard.test.jsx, graylog2-web-interface/src/views/components/dashboard/__snapshots__/IfDashboard.test.jsx.snap, graylog2-web-interface/src/views/components/search/IfSearch.jsx, graylog2-web-interface/src/views/components/search/IfSearch.test.jsx, graylog2-web-interface/src/views/components/search/__snapshots__/IfSearch.test.jsx.snap
Add a component which only renders its children when the
context provides a ViewType of search
Also add unit test for IfDashboard
We need a way to only render components based on which page we are.
=> Add IfSearch component

graylog2-web-interface/src/views/bindings.jsx, graylog2-web-interface/src/views/components/QueryTabs.jsx, graylog2-web-interface/src/views/components/contexts/ViewTypeContext.jsx, graylog2-web-interface/src/views/components/dashboard/IfDashboard.test.jsx, graylog2-web-interface/src/views/components/dashboard/__snapshots__/IfDashboard.test.jsx.snap, graylog2-web-interface/src/views/components/widgets/__snapshots__/Widget.test.jsx.snap, graylog2-web-interface/src/views/logic/views/View.js, graylog2-web-interface/src/views/logic/views/ViewGenerator.js, graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx, graylog2-web-interface/src/views/pages/NewDashboardPage.jsx, graylog2-web-interface/src/views/pages/NewSearchPage.jsx, graylog2-web-interface/src/views/pages/StreamSearchPage.jsx, graylog2-web-interface/src/views/stores/ViewStore.js
Before this change, creating a new search/dashboard or loading one was
explicitly providing the view type by calling the
`ViewTypeContext.Provider` with a static value. This was prone to errors
caused by forgetting to do this in other places, leading to the default
being used.
Instead of this, this PR is now consolidating the context providers to a
single place that takes the view type from the currently loaded view.
=> Providing type of actual view instead of hardcoding one in context provider.

graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.jsx, graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.test.jsx, graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkList.jsx, graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkList.test.jsx, graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkControls.test.jsx.snap, graylog2-web-interface/src/views/logic/ViewLoaderContext.jsx, graylog2-web-interface/src/views/pages/NewSearchPage.jsx
Before there was a unnecessary use of ViewLoaderContext in BookmarkControls.
This PR will remove the ViewLoaderContext from BookmarkControls and uses the
already imported ViewStoreState instead.
=> Remove unnecessary ViewLoaderContext keys and usage

SECURITY.md
This PR is adding the `SECURITY.md` file which contains the Graylog Security Policy which includes information how to report security issues back to the project.
=> Create Graylog Security Policy

graylog2-server/src/main/java/org/graylog2/shared/journal/KafkaJournal.java
If nothing was ever commited to a journal,
the uncommitedMessages gauge always reported `9223372036854775807` (Long.MAX_VALUE)
This happens because committedOffset is initialized as DEFAULT_COMMITTED_OFFSET (Long.MIN_VALUE)
(substracted by 1 underflows the long to Long.MAX_VALUE)
This breaks the idle node detection feature for the processing status,
which would exclude entries that have no messages in the journal.
Steal the code from the `ThrottleStateUpdaterThread`, which already deals with this edge case.
Fixes #6415
refs https://github.com/Graylog2/graylog2-server/pull/6252
=> Fix KafkaJournal metrics on inactive nodes

graylog2-server/src/main/java/org/graylog/plugins/views/search/Query.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/Search.java, graylog2-web-interface/src/views/components/DashboardSearchBar.jsx, graylog2-web-interface/src/views/components/searchbar/DisabledTimeRangeSelector.jsx, graylog2-web-interface/src/views/components/searchbar/TimeRangeOverrideInput.jsx, graylog2-web-interface/src/views/components/searchbar/TimeRangeOverrideTypeSelector.jsx, graylog2-web-interface/src/views/logic/search/SearchExecutionState.js, graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx, graylog2-web-interface/src/views/stores/GlobalOverrideStore.js, graylog2-web-interface/src/views/stores/SearchExecutionStateStore.js
This change allows add a filter that is pushed down (by doing a logical
AND)and to specify a time range that is overriding the time ranges of
all widgets on all tabs. When either a query or an overriding time range
is specified, it is added to the "global override" section of the search
execution state which is kept temporarily (not persisted when saving a
dashboard) and included in the context of each search execution. The
search backend uses it to override all root queries (which are combined
with the widget queries).
That means the final query of a widget is determined like this:
`(override query || root query) + widget query -> final query`
where `+` is a concatenation using an `AND` operator.
=> Applying filters to all dashboard tabs using dashboard search bar.

graylog2-server/src/main/java/org/graylog2/rest/models/system/loggers/responses/SingleSubsystemSummary.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/logs/LoggersResource.java
We have added lots of code to the `org.graylog` package,
which we are missing a lot of useful debugging info from.
=> Set the loglevel for org.graylog2 AND org.graylog

graylog2-web-interface/src/components/common/webpack-resolver.js
Fixes `jest` to allow the `--watch` flag to work again
`yarn test --watch` was failing with an error from dynamically imported Ace dependencies.
Local environment is now testing on the fly
=> Fix webpack-resolver for jest --watch

graylog2-web-interface/src/views/components/searchbar/queryinput/ace-queryinput.css
Before this change, the autocompletion dropdown was 300px wide and
therefore too narrow for longer field names. This change is increasing
its width (lacking a good way to make it relate to the width to the
actual content) to decrease the risk of cutting off field names.
Before:
After:
=> Prevent cutting off field names in auto completion.

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/FieldTypesResource.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/FieldTypesResourceTest.java
Before this change, compound types were created also for these types:
* `text` -> `string{properties=[full-text-search]}`
* `keyword` -> `string{properties=[enumerable]}`
This is incorrect, as these are the same (mapped) types, but vary only
on capabilities.
This change is now merging these two types into a single non-compound
type, with a property set that is the intersection of the given
properties of all merged types.
Fixes #6313.
=> Do not create compound types if types differ by properties.

.github/workflows/rebase.yml
This allows us to automatically rebase by commenting with
```
/rebase
```
on a PR, speeding up the process of maintaining PRs and ensuring they are up to date with the target branch.
=> Adding Github Action for automatic rebase

graylog2-web-interface/webpack.config.js
This change is passing the `FEATURES` variable, which was confined to
the dev env before, to all environments including the production build.
This allows building a production build containing a given feature by
doing something like:
```
FEATURES=time_travel mvn package
```
=> Passing `FEATURES` flag to production build too.

graylog2-web-interface/src/components/lookup-tables/DataAdapterForm.jsx
For implementing a ediatable LocalStore table in the documentation
column of the LocalStoreDataAdapter, the dataAdapterId
needs to be passed there.
Refs https://github.com/Graylog2/graylog-plugin-enterprise/issues/1235
=> Pass dataAdapterId to DocumentationComponent of DataAdapter

graylog2-web-interface/src/views/components/messagelist/PossiblyHighlight.jsx, graylog2-web-interface/src/views/components/messagelist/PossiblyHighlight.test.jsx
Before this change, the `PossiblyHighlight` component which is used to determine if given highlighting rules apply to a message field and its value and generates highlighting areas for the given field value in this case returns `undefined`. This violates a React invariant limiting the result of a component to `React.Node` or `null`.
This change is slightly changing the logic of the affected component and returns `null` in this case.
Fixes #6511.
=> Render `null` for message field if its value is `undefined`.

graylog2-web-interface/src/views/Constants.js, graylog2-web-interface/src/views/bindings.jsx, graylog2-web-interface/src/views/components/views/View.jsx
When using the feature flag for the new search, this PR avoids reusing
the show dashboard route for the show views code. This prevents a double
registration of the same component for `/dashboards/:id`, where only the
order of registration decides which component will be actually used.
=> Use separate routes for show views/show dashboards.

graylog2-web-interface/src/views/components/messagelist/PossiblyHighlight.jsx, graylog2-web-interface/src/views/components/messagelist/PossiblyHighlight.test.jsx
This is a backport of #6512 to `3.1`.
Before this change, the `PossiblyHighlight` component which is used to determine if given highlighting rules apply to a message field and its value and generates highlighting areas for the given field value in this case returns `undefined`. This violates a React invariant limiting the result of a component to `React.Node` or `null`.
This change is slightly changing the logic of the affected component and
returns `null` in this case.
Fixes #6511.
=> Render `null` for message field if its value is `undefined` (3.1).

graylog2-web-interface/src/actions/event-notifications/EventNotificationsActions.js, graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationForm.jsx, graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationFormContainer.jsx, graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotifications.jsx, graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotificationsContainer.jsx, graylog2-web-interface/src/stores/event-notifications/EventNotificationsStore.js
This PR makes some improvements on the test Notification functionality:
- Makes results of test more visible, by rendering them inline instead of using a toaster notification for that
- Display test button on embedded Notifications (that is, while creating a Notification from the Event Definition form)
- Adds a test button in the Notification list, so people can quickly test a Notification without open the edit page
Refs #6366
=> Notification test button improvements

graylog2-web-interface/src/pages/PipelineDetailsPage.jsx, graylog2-web-interface/src/pages/SimulatorPage.jsx
This PR hides both `All events` and `All system events` from Pipelines, since they are not yet supported.
This changes also need to be backported into the 3.1 branch.
Fixes #6454
=> Hide Event Streams from Pipelines

graylog2-server/src/main/java/org/graylog2/system/processing/DBProcessingStatusService.java, graylog2-server/src/test/java/org/graylog2/system/processing/DBProcessingStatusServiceTest.java, graylog2-server/src/test/resources/org/graylog2/system/processing/processing-status-single-active-node.json
We introduced checks to exclude cluster nodes that don't do any input
processing from the processing status.
In cases where there is a very low message rate, these were too strict
and did not report any processing status.
Relax the condition for situations where there is only nodes
with a low ingestion rate in the processing status collection.
Fixes #6453
(cherry picked from commit fe24e0e3035ccc313e7f78af8aa46df301bd22cb)
=> Relax the journal metrics constraint for the processing status (#6469)

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchResource.java, graylog2-server/src/main/java/org/graylog2/indexer/TestIndexSet.java, graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java, graylog2-server/src/test/java/org/graylog2/indexer/searches/SearchesIT.java
* Remove event indices from global search
Filter IndexRanges by the Event index prefix name.
Fixes #6384
* Remove event streams from new search default
Fixes #6384
* Add comment and TODO
* Filter event indices by using IndexSets
This will also work, if the event index prefix settings were changed.
* Fix SearchesIT by turning the index event filter upside down
Instead of having to mock all the IndexSets for the test,
invert the filter and skip event indices only if matching IndexSets have been
found.
Pull in some code from MongoIndexSet into TestIndexSet to make the test
work.
(cherry picked from commit 7bbb761711533ab7ffe7740d07287806826ef600)
=> Remove Event indices from global search default (#6413)

graylog2-server/src/main/java/org/graylog2/rest/models/system/loggers/responses/SingleSubsystemSummary.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/logs/LoggersResource.java
* Set the loglevel for org.graylog2 AND org.graylog
We have added lots of code to the `org.graylog` package,
which we are missing a lot of useful debugging info from.
* Add multiple categories support to logging subsystems
This introduces an API change, but no frontend code uses
the category info yet.
(cherry picked from commit d22244d1ec9302d41c0c0fe5bb2227528c790019)
=> Set the loglevel for org.graylog2 AND org.graylog (#6423)

graylog2-web-interface/src/pages/PipelineDetailsPage.jsx, graylog2-web-interface/src/pages/SimulatorPage.jsx
* Filter event streams in pipelines
Events are not regular messages ingested from an input and at the moment
are not supported in pipelines.
Fixes #6454
* Fix linter errors
(cherry picked from commit e8ee0fb1b08d3c26f637c021e27cc0206246e20c)
=> Hide Event Streams from Pipelines (#6513)

graylog2-server/src/main/java/org/graylog2/system/processing/DBProcessingStatusService.java, graylog2-server/src/main/java/org/graylog2/system/processing/ProcessingStatusDto.java, graylog2-server/src/test/java/org/graylog2/system/processing/DBProcessingStatusServiceTest.java, graylog2-server/src/test/resources/org/graylog2/system/processing/processing-status-disabled-journal.json
If nodes have their journal disabled, return the processing status
results, regardless of their metrics being all 0.
Fixes #6449
(cherry picked from commit f4cda3fff6397b033895d2f0c2c4015d9f21883a)
=> Add journaling_enabled field to processing status (#6472)

graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewStateDTO.java, graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.jsx, graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.test.jsx
Prior to this change, selected_fields attribute was no longer send
from the frontend but the backend was still expecting it.
Saving a view was therefore broken.
Also prior to this change, the context type was not declared for
BookmarkControls, which was leading to a empty context.
When clicking on create or save on a search the request to save failed.
Created a new Search and saved it afterwards again.
=> Fix saving searches

graylog2-server/src/main/java/org/graylog/events/legacy/LegacyAlarmCallbackSender.java, graylog2-server/src/main/java/org/graylog/events/notifications/EventNotificationContext.java, graylog2-server/src/main/java/org/graylog/events/notifications/NotificationResourceHandler.java, graylog2-server/src/main/java/org/graylog/events/notifications/NotificationTestData.java, graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailSender.java, graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotification.java, graylog2-server/src/main/java/org/graylog/events/rest/EventNotificationsResource.java, graylog2-server/src/test/java/org/graylog/events/legacy/LegacyAlertConditionMigratorTest.java, graylog2-server/src/test/java/org/graylog/events/notifications/NotificationResourceHandlerTest.java, graylog2-web-interface/src/actions/event-notifications/EventNotificationsActions.js, graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationForm.jsx, graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationFormContainer.jsx, graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotifications.jsx, graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotificationsContainer.jsx, graylog2-web-interface/src/stores/event-notifications/EventNotificationsStore.js
* Add Notification test Resource
Make jobTrigger Optional for the EventNotificationContext,
to avoid having to create a huge dummy instance to execute
the test.
* Add another notification test resource
This one accepts NotificationDtos directly,
which allows us to live test notifications, while we are editing them.
* Add frontend for notification tests
- The testState is held in the EventNotificationsStore
- The handleTest wrapper is needed to render validation errors
* Keep test notification message on screen
Before this change, the result of testing a notification was displayed
in a toaster message and gone in a few seconds. This change makes the
message to be displayed below the test button until one of the input
changes.
* Add button to test notification from list
This change allows …
=>  Implement Notification Test button (#6366) (#6522) (3.1 backport)

graylog2-web-interface/src/views/components/visualizations/number/NumberVisualization.jsx, graylog2-web-interface/src/views/components/visualizations/number/NumberVisualization.test.jsx
Before this change, the number visualization of the aggregation builder rendered an empty string if the actual value was `0`, related to a type coercion in a conditional meant to catch `null`/`undefined` values.
This change is making that conditional stricted. In addition, it also returns `N/A` instead of `''` for `null`/`undefined` values.
Before:
After:
=> Do not render empty string for `0` value in number visualization.

graylog-plugin-archetype/src/main/resources/archetype-resources/pom.xml
Little syntax fix for our plugin archetype. The syntax for the yarn version tag got unified with the node version tag.
Found while creating an example plugin and using the archetype
I've executed `mvn install` inside the graylog-plugin-archtype dir, created a new plugin skeleton with  `mvn archetype:generate -DarchetypeGroupId=org.graylog -DarchetypeArtifactId=graylog-plugin-archetype` plus the required `-DarchetypeCatalog=local` attribute and run `mvn package` to be sure the build still works.
=> Update plugin archetype yarn version syntax from yarn.version to yarnVersion

graylog2-web-interface/yarn.lock
The sidebar did apperantly update the yarn.lock which was not
commited.
Refs #6467
=> Update yarn.lock after sidebar-merge

graylog2-web-interface/src/components/common/ReactGridContainer.css, graylog2-web-interface/src/components/common/ReactGridContainer.jsx, graylog2-web-interface/src/views/pages/ExtendedSearchPage.css
I had a look at the widget alignment, because they mostly never really had the full width.
Testes the changes with and without the search feature flag
The problem:
=> Fix widget width alignment for search and dashboard page

graylog2-web-interface/src/routing/AppErrorBoundary.jsx, graylog2-web-interface/src/routing/AppRouter.jsx, graylog2-web-interface/src/views/components/Field.jsx, graylog2-web-interface/src/views/components/Field.test.jsx, graylog2-web-interface/src/views/components/Query.jsx, graylog2-web-interface/src/views/components/Query.test.jsx, graylog2-web-interface/src/views/components/Value.jsx, graylog2-web-interface/src/views/components/Value.test.jsx, graylog2-web-interface/src/views/components/contexts/InteractiveContext.js, graylog2-web-interface/src/views/components/dashboard/BigDisplayModeConfiguration.jsx, graylog2-web-interface/src/views/components/dashboard/BigDisplayModeConfiguration.test.jsx, graylog2-web-interface/src/views/components/dashboard/BigDisplayModeHeader.jsx, graylog2-web-interface/src/views/components/dashboard/IfInteractive.jsx, graylog2-web-interface/src/views/components/dashboard/bigdisplay/CycleQueryTab.jsx, graylog2-web-interface/src/views/components/dashboard/bigdisplay/CycleQueryTab.test.jsx, graylog2-web-interface/src/views/components/visualizations/GenericPlot.jsx, graylog2-web-interface/src/views/components/visualizations/number/NumberVisualization.jsx, graylog2-web-interface/src/views/components/visualizations/number/NumberVisualization.test.jsx, graylog2-web-interface/src/views/components/widgets/Widget.jsx, graylog2-web-interface/src/views/components/widgets/__snapshots__/Widget.test.jsx.snap, graylog2-web-interface/src/views/logic/queries/QueryTitle.js, graylog2-web-interface/src/views/logic/queries/QueryTitle.test.jsx, graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx, graylog2-web-interface/src/views/pages/ShowDashboardInBigDisplayMode.jsx, graylog2-web-interface/src/views/stores/ViewStore.js
This PR is adding functionality to show dashboards in a non-interactive,
read-only mode suitable for big displays and unattended setups. It tries
to:
* Maximize usage of screen estate by removing navigation and side bar
* Removes interactive elements of widgets
* Cycles through (configured) tabs of dashboard automatically
* Refreshes the search in configured intervals
Fixes #6401.
=> Showing dashboards in non-interactive big display/tv mode.

graylog2-web-interface/src/routing/AppRouter.jsx, graylog2-web-interface/src/routing/AppRouter.test.jsx
In #6602 the `AppRouter`'s route structure was changed to allow supplying routes from plugins with an explicitly defined `null` value for the `parentComponent`. This enforces hoisting of these routes to the top level of the router so they are not contained within the `App` or other parent components.
Unfortunately the path of the global `AppErrorBoundary` was left in place, erroneously meant to fix a unrelated route matching issue, leading to a ` ` or `/` route to go nowhere.
This change is removing the path specification so ` ` and `/` routes are correctly routed to the `StartPage` component again.
=> Fixing root route in `AppRouter`.

graylog2-web-interface/.gitignore
Add `test/bin` to `graylog2-web-interface/.gitignore`
Added one line to .gitignore in order to ignore the autogenerated file `headless_shell`in there.
It works on my machine.&trade;
=> Add test/bin to .gitignore in graylog2-web-interface

graylog2-web-interface/dev/lintChanges.sh, graylog2-web-interface/package.json
I just had the problem, that the linting for my PR fails because the CI is linting the all the changed files. I thought it is a good idea to have a yarn script for that. I think the CI script will not change in the near future
Possible cons:
- When the CI script changes, we need to adjust this script as well
- As far as I know you have to make the bash script executable by hand (I added a comment inside the script)
- There is maybe a better place than the dev dir. What do you think?
=> Add bash script to execute linting in the same way the CI does

graylog2-web-interface/src/components/common/Select.jsx, graylog2-web-interface/src/views/components/DashboardSearchBar.jsx, graylog2-web-interface/src/views/components/SearchBar.jsx, graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap, graylog2-web-interface/src/views/components/horizontalspacer/HorizontalSpacer.jsx, graylog2-web-interface/src/views/components/searchbar/KeywordTimeRangeSelector.jsx, graylog2-web-interface/src/views/components/searchbar/RefreshControls.css, graylog2-web-interface/src/views/components/searchbar/RefreshControls.jsx, graylog2-web-interface/src/views/components/searchbar/StreamsFilter.jsx, graylog2-web-interface/src/views/components/searchbar/__snapshots__/RefreshControls.test.jsx.snap, graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.css, graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.jsx, graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkControls.test.jsx.snap, graylog2-web-interface/src/views/pages/ExtendedSearchPage.css
Initially I just wanted to add the RefreshControls to the dashboard searchbar. During the layout adjustment I couldn't resist and made the search and dashboard searchbar more responsive. 
To make the layout perfect I would have to rewrite a lot more things, but for now I fixed the general responsiveness and unified some component styles. I know the responsiveness is not that important in general, but I think it was worth the effort. I suspect it is a common scenario to have the search on one half of the screen and something else on the other.
Tested in Chrome, Safari and Firefox.
Before (on a very small screen to show most problems): 
After:
=> Make searchbar reponsive and add refresh controls to dashboard searchbar

graylog2-web-interface/src/views/stores/ViewStore.js, graylog2-web-interface/src/views/stores/ViewStore.test.js
Prior to this change, the ViewStore needed a listener to the create
completed action and did not update the isNew flag when changing from
a new view to a loaded.
This change will remove the listener and implement the setting of isNew
in `load` and `create` actions.
=> Simplify implementation of isNew

graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/series/Percentile.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/searchtypes/pivot/series/PercentileTest.java
Prior to this change, the user was unable to create more than one
percentile metric for same field in aggregation. Since the aggregation
series name was matching on aggregation name and field.
This change will add the percentile to the aggregation name. That way
the user can add more then one percentile aggergation.
Add more than one percentile series
=> Generate unique aggregation ids for multiple percentile metrics

graylog2-server/src/main/java/org/graylog/plugins/map/config/DatabaseType.java, graylog2-server/src/main/java/org/graylog/plugins/map/geoip/MaxmindDataAdapter.java, graylog2-server/src/test/java/org/graylog/plugins/map/geoip/MaxmindDataAdapterTest.java, graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterDocumentation.jsx, graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterFieldSet.jsx, graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterSummary.jsx
Add support for GeoIP2 ASN databases.
Currently Graylog only supports the GeoIP2 city and country databases, but adding ASN support is a simple matter of calling the right method and mapping the fields.
Some users have requested supporting ASN data as well.
There is a basic unit test, which requires placing a suitable GeoIP2 database into the test resources directory (not included in source tree, because of size and license issues).
Grab the databases here: https://dev.maxmind.com/geoip/geoip2/geolite2/ and put the `.mmdb` file directly into `graylog2-server/src/test/resources` for running the tests.
Additionally sanity checks in the UI have been done:
* creating an ASN data adapter
* looking up various well-known addresses and cross checking their ASN and organization name
* looking up …
=> Support MaxMind ASN geo ip database

graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationBrowserResource.java, graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationResource.java, graylog2-server/src/main/resources/swagger/css/screen.css, graylog2-server/src/main/resources/swagger/index.html.template, graylog2-server/src/main/resources/swagger/swagger-ui.js, graylog2-web-interface/src/components/nodes/NodesList.jsx, graylog2-web-interface/src/pages/NodesPage.jsx, graylog2-web-interface/src/routing/Routes.jsx
Usually, the link to the API browser is meant to talk to one specific node only.
In cases where Graylog is served behind a load balancer, the node
specific URL is not reachable.
We autodetect that ( `http_external_uri` != `http_publish_uri` )
and display a "cluster global API browser button".
Since the API browser behind this address might end up talking
to random nodes of the cluster, display a warning box, to make
users aware of this.
Fixes #5920
Refs #2360
Refs https://github.com/Graylog2/graylog2-server/pull/2587
=> Introduce a cluster global API browser button

graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationBrowserResource.java, graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationResource.java, graylog2-server/src/main/resources/swagger/css/screen.css, graylog2-server/src/main/resources/swagger/index.html.template, graylog2-server/src/main/resources/swagger/swagger-ui.js, graylog2-web-interface/src/components/nodes/NodesList.jsx, graylog2-web-interface/src/pages/NodesPage.jsx, graylog2-web-interface/src/routing/Routes.jsx
Usually, the link to the API browser is meant to talk to one specific node only.
In cases where Graylog is served behind a load balancer, the node
specific URL is not reachable.
We autodetect that ( `http_external_uri` != `http_publish_uri` )
and display a "cluster global API browser button".
Since the API browser behind this address might end up talking
to random nodes of the cluster, display a warning box, to make
users aware of this.
Fixes #5920
Refs #2360
Refs https://github.com/Graylog2/graylog2-server/pull/2587
=> Introduce a cluster global API browser button (#6567)

graylog2-web-interface/src/components/users/UserPreferencesButton.test.jsx, graylog2-web-interface/src/components/users/__snapshots__/UserPreferencesButton.test.jsx.snap
<Before this change, the `UserPreferencesButton` test was snapshotting
the instance returned from testing-library directly, including a lot of
internal structure in the code which is likely to change and therefore
break the test in future versions of the library. This change is fixing
this. Additionally, it removes a lot of unnecessary boiler plate.
=> Improving `UserPreferencesButton` tests usage of mocks and snapshots.

graylog2-web-interface/src/views/components/searchbar/StreamsFilter.jsx, graylog2-web-interface/src/views/components/searchbar/StreamsFilter.test.jsx
Before this change, streams options appeared in the order they were received from the backend. This change is now applying natural sorting to the options before displaying them.
Needs backport to `3.1` after merging.
Fixes #6514.
=> Sorting streams options in streams filter.

graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/requests/IndexSetUpdateRequest.java
This would lead to errors in the AddEventIndexSetsMigration
Fixes #6507
=> Don't loose the IndexSet TemplateType when updating

graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/requests/IndexSetUpdateRequest.java
This would lead to errors in the AddEventIndexSetsMigration
Fixes #6507
(cherry picked from commit 10e49748f1f5039ade5d49aa2b9e88940cbc158a)
=> Don't loose the IndexSet TemplateType when updating (#6656)

graylog2-web-interface/src/views/components/aggregationbuilder/EmptyAggregationContent.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/EmptyAggregationContent.test.jsx, graylog2-web-interface/src/views/components/contexts/InteractiveContext.js, graylog2-web-interface/src/views/components/datatable/DataTable.jsx, graylog2-web-interface/src/views/components/datatable/DataTable.test.jsx, graylog2-web-interface/src/views/components/visualizations/GenericPlot.jsx, graylog2-web-interface/src/views/components/visualizations/XYPlot.jsx, graylog2-web-interface/src/views/components/visualizations/__tests__/GenericPlot.test.jsx, graylog2-web-interface/src/views/components/visualizations/number/NumberVisualization.jsx, graylog2-web-interface/src/views/components/visualizations/number/NumberVisualization.test.jsx, graylog2-web-interface/src/views/components/visualizations/pie/PieVisualization.jsx, graylog2-web-interface/src/views/components/visualizations/worldmap/WorldMapVisualization.jsx, graylog2-web-interface/src/views/components/visualizations/worldmap/__tests__/WorldMapVisualization.test.jsx, graylog2-web-interface/src/views/components/widgets/MessageList.jsx, graylog2-web-interface/src/views/components/widgets/MessageList.test.jsx, graylog2-web-interface/src/views/components/widgets/RenderCompletionCallback.jsx, graylog2-web-interface/src/views/logic/singleton.js
In some circumstances, parent components of views widgets need to be
notified when one or more widgets have completed rendering. This change
is implementing the required infrastructure for this by implementing a
`RenderCompletionCallback` context containing a function that is
consumed by widgets and executed after first and subsequent renders.
A widget needs to take care that upon a first meaningful render this
function needs to be called, which is implemented for all currently
existing widgets. All Widgets that do use the `GenericPlot` component
are automatically handled by it.
=> Provide optional render completion callback to views widgets.

graylog2-server/src/main/java/org/graylog2/grok/MongoDbGrokPatternService.java, graylog2-server/src/test/java/org/graylog2/grok/MongoDbGrokPatternServiceTest.java
This ensures the reload of running extractors to use the imported grok
patterns.
=> Publish GrokPatternsUpdatedEvent on pattern import

graylog2-server/src/main/java/org/graylog2/system/processing/DBProcessingStatusService.java
Dropping an index produces a log message in mongodb.
Avoid that by checking whether the old index needs to be dropped.
Fixes #6383
=> Check if old index exists before dropping it

graylog2-server/src/main/java/org/graylog2/grok/MongoDbGrokPatternService.java, graylog2-server/src/test/java/org/graylog2/grok/MongoDbGrokPatternServiceTest.java
This ensures the reload of running extractors to use the imported grok
patterns.
Co-Authored-By: Marco Pfatschbacher <marco@graylog.com>
(cherry picked from commit 142d149fabb922aa8d2ef4102984f9c87dc4b0a3)
=> Publish GrokPatternsUpdatedEvent on pattern import (#6666)

graylog2-server/src/main/java/org/graylog2/system/processing/DBProcessingStatusService.java
Dropping an index produces a log message in mongodb.
Avoid that by checking whether the old index needs to be dropped.
Fixes #6383
(cherry picked from commit 9ad24c1ed7f70a35483e5d0011d6d861d56b9db3)
=> Check if old index exists before dropping it (#6670)

graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchClientConfiguration.java, misc/graylog.conf
This change is bumping the "elasticsearch_max_total_connections" and
"elasticsearch_max_total_connections_per_route" default settings to
avoid message processing stalls.
The default limit of 2 connections per ES server is way too low and can
cause delayed or event blocked message processing.
Example:
With a limit of 2 connections per ES server, 2 index optimization jobs
that are running in parallel will cause message processing to stall until
the optimization jobs are done.
Refs #4637
=> Increase ES client HTTP connection limits

graylog2-web-interface/src/views/components/QueryBar.jsx, graylog2-web-interface/src/views/components/QueryTabs.jsx, graylog2-web-interface/src/views/components/queries/QueryTitle.jsx, graylog2-web-interface/src/views/components/queries/QueryTitle.test.jsx, graylog2-web-interface/src/views/components/queries/QueryTitleEditModal.jsx, graylog2-web-interface/src/views/components/queries/QueryTitleEditModal.test.jsx, graylog2-web-interface/src/views/pages/ExtendedSearchPage.css
This PR changes the way we edit a query tab title. Right now we have to double click on the current query tab title to edit it inline. There are two problems: 
- The user will may not see this option
- The react bootstrap key bindings are causing a strange behaviour when using e.g the arrow keys. The input loses the focus, a new tab will be created, the focus is still on another, not active, tab.
The new way is just another entry in the query tab context menu "Edit Title". Clicking on this entry will open a model containing the title input.
I did some refactoring of the QueryTitle and QueryTabs component in this PR (like adding flow strict). I hope you can still get an overview of the changes.
Added tests for all changes / new functionality
=> Adjust query tab title editing

graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchClientConfiguration.java, misc/graylog.conf
This change is bumping the "elasticsearch_max_total_connections" and
"elasticsearch_max_total_connections_per_route" default settings to
avoid message processing stalls.
The default limit of 2 connections per ES server is way too low and can
cause delayed or event blocked message processing.
Example:
With a limit of 2 connections per ES server, 2 index optimization jobs
that are running in parallel will cause message processing to stall until
the optimization jobs are done.
Refs #4637
(cherry picked from commit d961d873a1386518fa05fae8ebf7299262351cfb)
=> Increase ES client HTTP connection limits (#6675)

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/audit/PipelineProcessorAuditEventTypes.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/db/RuleMetricsConfigDto.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/db/RuleMetricsConfigService.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/events/RuleMetricsConfigChangedEvent.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/ConfigurationStateUpdater.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreter.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/listeners/InterpreterListener.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/listeners/NoopInterpreterListener.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/listeners/RuleMetricsListener.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/RuleResource.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/simulator/SimulatorInterpreterListener.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreterTest.java, graylog2-web-interface/src/actions/rules/RulesActions.jsx, graylog2-web-interface/src/components/rules/RuleList.jsx, graylog2-web-interface/src/components/rules/RuleMetricsConfig.jsx, graylog2-web-interface/src/components/rules/RuleMetricsConfigContainer.jsx, graylog2-web-interface/src/routing/ApiRoutes.js, graylog2-web-interface/src/stores/rules/RulesStore.js
Not having timers for pipeline rules makes it really hard to debug
performance problems. This change adds a new interpreter listener that
tracks rule evaluation ("when" statement) and execution ("then"
statement) timers.
Since tracking timers for lots of rules can be impact processing
performance, the timers are disabled by default. Users can toggle the
rule timers on the rules management page.
Example metrics:
org.graylog.plugins.pipelineprocessor.ast.Rule.5d5161cb2c9287782b2826d5.trace.evaluate.duration
org.graylog.plugins.pipelineprocessor.ast.Rule.5d5161cb2c9287782b2826d5.trace.execute.duration
Closes #5494
(cherry picked from commit 157c9d1b1f177f7993d8ef36212428dc60b9dc38)
=> Implement pipeline rule timers that can be enabled/disabled at runtime

graylog2-web-interface/src/components/layout/Footer.jsx
Before this change, the `Footer` component unconditionally set state in
a promise handler retrieving jvm information from a remote endpoint.
This lead to flaky integration tests due to the component being mounted
and unmounted again immediately after (due to test completion) while the
promise handler has not completed yet, resulting in a rejected promise.
This change now checks if the component is not mounted anymore before
setting state.
=> Do not set state in `Footer` if already unmounted.

graylog2-web-interface/src/components/visualizations/RenderCompletionObserver.jsx, graylog2-web-interface/src/components/widgets/WidgetVisualizationNotFound.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/AggregationBuilder.jsx, graylog2-web-interface/src/views/components/visualizations/GenericPlot.jsx, graylog2-web-interface/src/views/components/visualizations/XYPlot.jsx, graylog2-web-interface/src/views/components/visualizations/__tests__/XYPlot.test.jsx, graylog2-web-interface/src/views/logic/aggregationbuilder/Direction.js, graylog2-web-interface/src/views/logic/widgets/Widget.js
This change is cleaning up some inconsistencies and issues that came up
during the reporting integration:
* `GenericPlot`/`XYPlot` merged layout changes into the sources
itself, leading to subtle bugs with nondeterministic layouts if multiple
widgets are present
* `RenderCompletionObserver` is now used the context for passing the
callback down to its children
* `WidgetVisualizationNotFound` was now calling the render completion
callback to, so rendering will appear as completed in error cases too.
* `Widget` is being exported as singleton to make it properly usable
from plugins if subclasses are present
=> Cleaning up render completion callback handling in some places.

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/FieldTypesResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/PermittedStreams.java, graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/MappedFieldTypesService.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/FieldTypesResourceTest.java, graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/MappedFieldTypesServiceTest.java
This change is adding a `MappedFieldTypesService` which allows its consumer to retrieve mapped field types for a given set of streams. This will be used in several places (reporting, views) to easily access field types in a scope that is limited to a set of streams.
=> Adding service to retrieve mapped field types per stream.

graylog2-web-interface/src/components/field-analyzers/FieldStatistics.jsx
This PR resets the loading state when fetching statistics for a field fails.
@mehrenreich I added you to the reviewers in case you want to take a look as well :)
Refs #5836
=> Reset loading state when loading field statistics fails

graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackend.java, graylog2-server/src/main/java/org/graylog2/indexer/cluster/jest/JestUtils.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendErrorHandlingTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendMultiSearchTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendTestBase.java, graylog2-server/src/test/resources/org/graylog/plugins/views/search/elasticsearch/errorhandling/failureOnQueryLevel.json, graylog2-server/src/test/resources/org/graylog/plugins/views/search/elasticsearch/errorhandling/failureOnSearchTypeLevel.json, graylog2-server/src/test/resources/org/graylog/plugins/views/search/elasticsearch/errorhandling/numericFailureOnSearchTypeLevel.json
Before this change, errors returned from the execution of a `Search` on
a query or search type level were returned as is from ES to the API
consumer, leading to repeating each error for every index it occurs on.
This change is deduplicating errors by only returning distinct
descriptions to the caller.
In the frontend this leads to better readable errors, changing from:
to:
=> Deduplicating query/search type errors before returning them.

graylog2-web-interface/src/views/components/ViewActionsMenu.jsx
Prior to this change, PropTypes would raise a warning
when CurrentUser was not yet fetch from the store, but
ViewActionsMenu was already tried to be rendered.
This change will implement a default CurrentUser
with empty permissions to satisfy PropTypes once and for all.
=> Mute PropTypes warning in ViewActionsMenu

graylog2-web-interface/src/components/navigation/Navigation.jsx, graylog2-web-interface/src/components/navigation/Navigation.test.jsx
If the `search_3_2` feature flag is present, this PR disables the
`Views` navigation menu as it is now replaced by the `Search` and
`Dashboard` functionality.
=> Disable `Views` navigation menu if feature flag for new search is active

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/parser/PipelineRuleParser.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/parser/PipelineRuleParserTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/parser/requiredParameter.txt
* Add parse error handling for missing required parameters when followed by optional parameters
* Set "hasError" when encountering WrongNumberOfArgs error
Fixes #6696
(cherry picked from commit eb392d9180e552723a1b9805c6a06f270a16a18d)
=> Parse error for missing required positional parameters with optional parameters present (#6716)

graylog2-web-interface/src/components/login/LoginForm.jsx, graylog2-web-interface/src/pages/LoginPage.jsx, graylog2-web-interface/src/stores/sessions/SessionStore.js
Extracts login form into its own component, independent from `LoginPage`, and lets one plugin to display an alternative login page.
I decided not to migrate `LoginPage` to a functional component to not pollute the PR with that, but I can also make the change if you consider it appropriate.
---
Update to include how to use a plugin to log into Graylog. I don't see a good place in the code to add this information, so I will leave it here for now.
The plugin needs to register a form component in `loginProviderType` taking care of displaying a form, or button, the user can use to log into Graylog. Only one plugin can do that at the time, so far we don't need to support any number of custom login forms.
The form may talk to an authenticator provided by the plugin API and/or an external system …
=> Pluggable login form

graylog2-web-interface/src/views/Constants.js, graylog2-web-interface/src/views/bindings.jsx, graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.jsx, graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.test.jsx, graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkList.jsx, graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkList.test.jsx, graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkList.test.jsx.snap, graylog2-web-interface/src/views/pages/ShowViewPage.jsx, graylog2-web-interface/src/views/pages/ShowViewPage.test.jsx
Prior this change, after the user loaded a bookmarked search
the id was not shown in the url. So the user could not create
a browser bookmark for that search.
This change adds browserHistory.push at the points where a bookmarked
search will be loaded.
- Add a new bookmark and checked for the ID in the url bar of the browser
- Loaded a old bookmark and checked for the url
- Cleared the view and checked that I got back to `/search`
=> Change url after loading a bookmarked search

graylog2-server/src/main/java/org/graylog/plugins/views/search/Search.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/SearchTest.java
Before this change, `Search#usedStreamIds` only considered the referenced streams of `Query`'s. This led to an omission of permission checks for the search type's stream ids.
This change is now returning the stream ids referenced in the search types of a query as well for `Search#usedStreamIds`.
In addition, it now returns an empty set instead of throwing an exception when performed on a search with an empty set of queries (a pathological case, but returning an empty set seems to be the correct way to handle it).
=> Include streams of search type when returning used streams of search.

graylog2-web-interface/src/pages/StartPage.jsx
This change allow the use of the `back` button to return to previous state after clicking on the Logo in the Header.
Before this change clicking on the `logo` on the header navigated to `/` which redirected to `/search`. This was breaking the `Back` button as the browser tries to go back to `/` which redirects to `/search`.
(#5975)
=> Prevent logo click from breaking back button

graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendUsingCorrectIndicesTest.java
`org.joda.time.DateTimeUtils` is used in various unit tests to override the current time globally. In one of these tests it was forgotten to reset time at the end of the test, which led to failures of a completely unrelated, but also `DateTime`-dependent test (`DBJobTriggerServiceTest->deleteCompleted`). 
Just added one line to the end of the test to reset `DateTime`. Didn't want to add a tear down method, because this was the only test in the class that used the override.
The missing reset has led to consistent failure of the above mentioned unrelated test on my local machine. 
In the future we should remove such overrides and instead inject `now` in classes under test.
Running all backend tests, including the refactored integration tests from the [testcontainers …
=> Reset DateTime at the end of a unit test which globally overrides it

graylog2-web-interface/packages/eslint-config-graylog/index.js
There is a general agreement that any React components that still use `createReactClass` should be rewritten to ES6 classes or functional components.
This PR is adding an ESLint rule forbidding imports of the `create-react-class` module indicating the necessity to rewrite it.
=> Adding ESLint rule to forbid usage of `create-react-class`.

graylog2-web-interface/src/views/components/aggregationbuilder/SortableSelect.jsx
Currently an aggregation builder pivot input loses its focus, after an option got selected.
=> Fix aggregation builder sortable select focus problem

README.markdown
This PR removes the `Miscellaneous` section from the our `README`, as it is outdated and not accurate anymore.
=> Removing outdated "Miscellaneous" section from "README".

graylog2-web-interface/src/views/components/searchbar/QueryInput.jsx, graylog2-web-interface/src/views/components/searchbar/ace-types.js
This PR disables ace's integrated indentation feature, which captures
the tab key to indent text. As this does not make much sense for a
single line input, but does not allow the user to use the keyboard to
jump out of this input and the focus is trapped, this feature is
disabled.
=> Disable ace's indentation for `QueryInput`.

graylog2-web-interface/src/views/components/Select.jsx
When an aggregation builder select dropdown is open and an option is focused, a tab will select the option in the same way the enter key does. We should disable this setting for a more intuitive tab navigation.
=> Disable selecting dropdown value in select when using the tab key

graylog2-server/src/main/java/org/graylog/scheduler/JobSchedulerService.java
When the enterprise login is installed but there is no valid license
for a non-master node, job execution will be disabled. The job scheduler
would log every second that the next loop iteration cannot proceed.
Fixes #6451
Started a slave. Removed the license and added the license again. Logging looked as expected.
=> Reduce amount of log messages when job scheduler execution is disabled

graylog2-web-interface/src/components/lookup-tables/CacheCreate.jsx, graylog2-web-interface/src/components/lookup-tables/CacheForm.jsx, graylog2-web-interface/src/components/lookup-tables/DataAdapterCreate.jsx, graylog2-web-interface/src/components/lookup-tables/DataAdapterForm.jsx, graylog2-web-interface/src/pages/LUTCachesPage.jsx, graylog2-web-interface/src/pages/LUTDataAdaptersPage.jsx, graylog2-web-interface/src/pages/LUTTablesPage.jsx, graylog2-web-interface/src/stores/lookup-tables/LookupTableCachesStore.js, graylog2-web-interface/src/stores/lookup-tables/LookupTableDataAdaptersStore.js, graylog2-web-interface/src/stores/lookup-tables/LookupTablesStore.js
With these change DataAdapter and Cache edit pages will show the
corresponding type chosen for the DataAdapter or Cache.
To show the type as "subtext for Header" (react bootstrap) title for the
form is taken as a prop and rendered inside DataAdapterForm and
CacheForm.
* Get typename from plugin displayName
* Add title props to CacheForm and DataAdapterForm
* Add function to render title with appropriate tag depending on
creation or editing
* Fix linter
Fix #6517
=>  Add type to DataAdapter and Cache edit pages

graylog2-server/src/main/java/org/graylog/plugins/views/search/views/Titles.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewDTO.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewStateDTO.java
This is a small support PR adding:
- `findWidgetById` to `ViewDTO` allowing to extract a widget from a
view by its id
- `findQueryContainingWidgetId` allowing to extract a query
(`ViewStateDTO`) containing a widget by its id
- wrapping the `titles` map of a `ViewStateDTO` instance in a `Titles`
class to decouple title lookup from its internal structure
=> Adding helper methods to `ViewDTO` & `ViewStateDTO` classes.

graylog2-server/src/main/java/org/graylog2/outputs/BenchmarkOutput.java
Change the `BenchmarkOutput.Factory` return type to the actual class.
Otherwise we cannot bind the plugin.
=> Fix BenchmarkOutput

graylog2-web-interface/src/components/extractors/EditExtractorConverters.jsx
This seems to have been broken forever, at least I couldn't find the cause on a quick look at the file.
Before the change, adding an extractor converter didn't add anything to the list of converters, as you can see in the gif:
=> Fix adding new converters to a extractor

graylog2-web-interface/src/pages/NodesPage.jsx, graylog2-web-interface/src/routing/Routes.jsx
Using Routes, will run 'qualifyUrl()' twice.
=> Fix global API browser link

graylog2-web-interface/src/pages/NodesPage.jsx, graylog2-web-interface/src/routing/Routes.jsx
* Fix global API browser link
Using Routes, will run 'qualifyUrl()' twice if a path is used on the
reverse proxy.
Fixes #6823
* Fix review comments
(cherry picked from commit 9d571cee372ef0aa2343b4788303fa387a5f106c)
=> Fix global API browser link (3.1 backport)

graylog2-web-interface/src/views/logic/views/CopyWidgetToDashboard.test.js, graylog2-web-interface/src/views/logic/views/UpdateSearchForWidgets.test.js
Prior to this change, the tests of CopyWidgetToDashboard and
UpdateSearchForWidgets were throwing warnings:
`Unable to find type definition or defaults for search type undefined -
skipping!`
This change will mock the searchTypeDefinition function
to prevent the warning from raising.
=> Fix warnings tests of CopyWidgetToDashboard and UpdateSearchForWidgets

graylog2-server/src/test/java/org/graylog/testing/elasticsearch/ElasticsearchInstance.java
Added the new `withReuse(true)` flag from this new testcontainers
feature: https://github.com/testcontainers/testcontainers-java/pull/1781
In order for this to work developers have to enable reuse in a config file: 
` echo 'testcontainers.reuse.enable=true' > ~/.testcontainers.properties`
Testcontainers uses a hash based on various container properties to determine reusability, so if any of these properties change, a new container is spun up and will be reused next time. Old ones remain running and _have to be cleaned up manually_. While this is the main drawback of this approach, I find it ok, because we don't change these properties too often. People who really hate it can just not enable reuse in their testcontainers config and go on without it.
Our Elasticsearch container needs ~10s …
=> Reuse Elasticsearch container between test runs for integration tests

graylog2-web-interface/src/views/components/aggregationbuilder/SeriesConfiguration.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/SeriesConfiguration.test.jsx
When you are changing the name of a metric inside the aggregation builder, there is currently no way to reset it to the original metric function name. With this PR, you can reset the title, by submitting an empty input.
=> Reset aggregation builder series title to metric function name, on empty title save

graylog2-web-interface/packages/eslint-config-graylog/index.js, graylog2-web-interface/packages/eslint-config-graylog/package.json, graylog2-web-interface/src/stores/StoreTypes.js, graylog2-web-interface/src/views/components/aggregationbuilder/AggregationBuilder.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/AggregationControls.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/pivottypes/AutoTimeHistogramPivot.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/pivottypes/TimeUnitTimeHistogramPivot.jsx, graylog2-web-interface/src/views/components/common/ActionDropdown.jsx, graylog2-web-interface/src/views/components/queries/QueryTitleEditModal.jsx, graylog2-web-interface/src/views/components/searchbar/QueryInput.jsx, graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.jsx, graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkForm.jsx, graylog2-web-interface/src/views/components/views/ShareViewModal.jsx, graylog2-web-interface/src/views/logic/aggregationbuilder/WidgetFormattingSettings.js, graylog2-web-interface/src/views/logic/withPluginEntities.jsx, graylog2-web-interface/src/views/stores/RefreshStore.js, graylog2-web-interface/test/helpers/mocking/AsMock.js, graylog2-web-interface/yarn.lock
Prior to this change, ESLint threw errors for undefined variables in some cases when flow utility types have been used. These required disabling the `no-undef` rule selectively when this was the case.
This PR adds the [`eslint-plugin-flowtype`](https://github.com/gajus/eslint-plugin-flowtype) ESLint plugin, which helps avoiding this. Right now it is using the recommended configuration, further fine-tuning according to our desires can be performed later.
=> Adding `eslint-plugin-flowtype` for proper flow support in ESLint.

graylog2-server/src/main/java/org/graylog2/lookup/LookupTable.java, graylog2-server/src/main/java/org/graylog2/lookup/adapters/DnsLookupDataAdapter.java, graylog2-server/src/main/java/org/graylog2/lookup/adapters/HTTPJSONPathDataAdapter.java, graylog2-server/src/main/java/org/graylog2/lookup/adapters/dnslookup/ADnsAnswer.java, graylog2-server/src/main/java/org/graylog2/lookup/adapters/dnslookup/TxtDnsAnswer.java, graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupResult.java, graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/ObjectMapperProvider.java, graylog2-server/src/test/java/org/graylog2/lookup/adapters/HTTPJSONPathDataAdapterTest.java
Since our current use cases for listValues only need String objects,
and we don't want to complicate the API unneccessarily, don't
implement this as a List of Objects.
The idea is that each DataAdapter should decide which values
make most sense to be in the List, and convert them accordingly.
=> Add stringListValue() support to LookupTables

graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/searchtypes/ESEventList.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/events/EventList.java
This PR is fixing up required changes to the `events` search type which are now required due to the introduction of 5ee5115642dd0c8d6a1f7ed58f68317a9ccda3f0 and 75bd8ca28c2a672a646ea807e5a7acc7c63c81a0. These require a search type:
- to handle an optional `name` argument and pass it through to its
results
- to consume the time range wrapped in a `DerivedTimeRange` instance,
allowing `OffsetRange` instances to be used
=> Adapting Events Search Type to include `name` and new time range.

graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/MessageList.java
In 5ee5115642dd0c8d6a1f7ed58f68317a9ccda3f0 an optional name attribute defined by the caller for a search type, which is passed through to its results, was introduced. To leave it out when it is empty, the `@JsonInclude(NON_EMPTY)` annotation was added. Unfortunately, this also leaves out the `messages` in the result if it is empty, breaking consumer logic which expects it to be present.
This change turns it into `NON_ABSENT` which skips `Optional`s which are empty, but includes empty collections.
=> Include `messages` field if empty in message list search type result.

graylog2-web-interface/src/views/components/visualizations/worldmap/MapVisualization.jsx, graylog2-web-interface/src/views/components/visualizations/worldmap/WorldMapVisualization.jsx
The main problem is, we are passing data ("No metric set" Info) to the `MapVisualization`, even when there are no results. This resulted in an error like `Cannot reduce an empty array`. 
I fixed this case. Because I found initially a solution to prevent the `.reduce` error inside the `MapVisualization`, I've added these changes as well.
=> Fix worldmap error when row pivot is set, metric is not set and the widget result is empty.

graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/searchtypes/ESMessageList.java
Use limit from `MessageList` as is instead of subtracting offset from it which has led to an exception whenever offset exceeds limit (and truncated results when 0 < offset < limit).
This never popped up before, because we had no pagination and offset and limit were hardcoded in the frontend.
I've only tested this manually to not delay our work on pagination. We should write comprehensive integration tests for search execution after the 3.2 release.
=> Fixed ES result size for MessageList with limit

graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessor.java, graylog2-server/src/test/java/org/graylog/events/processor/aggregation/AggregationEventProcessorTest.java
Fixes #6876
This needs to be backported to 3.1.
=> Ensure that aggregation events always have a "source_streams" value

graylog2-server/pom.xml
The jersey-bean-validation dependency is pulling in an older
hibernate-validator transitive dependency. Exclude the older dependency
to enforce the usage of a more recent one.
This unbreaks object validation in our REST API.
Fixes #5402
=> Fix object validation in our REST API

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/StreamCacheService.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/messages/StreamCacheServiceTest.java
Previously we were storing the stream itself in the nameToStream
MultiMap but were using only the id of the stream as the comparator for
the underlying set. This would lead to stale stream objects in that
cache if the cache was updated with a changed stream which was already
cached.
The implementation felt way to complicated for what it was doing. For
the benefit of having clearer semantics we simply reload all streams
when a stream changes. This will put additional load on the database for
cache updating but cache lookup times will stay stable.
Fixes #4954
(cherry picked from commit e9dc74a7cff40506f9c9831d210b905120f745e4)
=> Prevent stale objects in stream cache of route_to_stream function

graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java, graylog2-server/src/main/java/org/graylog2/migrations/V20191121145100_FixDefaultGrokPatterns.java, graylog2-server/src/main/resources/org/graylog2/migrations/V20180924111644_AddDefaultGrokPatterns_Default_Grok_Patterns.json, graylog2-server/src/test/java/org/graylog2/migrations/V20191121145100_FixDefaultGrokPatternsTest.java
The COMMONAPACHELOG grok pattern uses the original date string found in the source to propagate the "timestamp" message field. When the extractor tries to use this value to set the field on the message, it will be ignored, as it is not a proper date.
We adjust the pattern so that it creates a date object which the message accepts as a valid value for the "timestamp" field.
The pattern is fixed in the content pack which is installed automatically for a new graylog setup. For existing setups, a migration is provided which fixes the pattern if it is still in the original, broken state. 
Fixes #1647
Started a fresh graylog setup. Started an existing graylog setup with the original content pack already installed. Both setups ended up with the fixed pattern.
=> Fix "COMMONAPACHELOG" grok pattern.

graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldForm.jsx
Correct module used to import `Icon`. I also did a quick look and it seems all other imports for `Icon` are fine.
Fixes #6884
=> Fix error on adding field to Event Definition

graylog2-web-interface/src/components/metrics/MetricContainer.jsx, graylog2-web-interface/src/logic/metrics/MetricsExtractor.js, graylog2-web-interface/src/stores/metrics/MetricsStore.js
Ensure `MetricsContainer` can handle an empty metrics array with `reduce()` by setting an initial value to the function.
I also fixed linter errors and included basic flow type information for metrics, which lead to fixing another couple things.
Fixes #6864
=> Guard against empty metrics array

graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/AreaVisualizationConfigDTO.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/Interpolation.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/LineVisualizationConfigDTO.java, graylog2-web-interface/src/views/bindings.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/AreaVisualizationConfiguration.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/LineVisualizationConfiguration.jsx, graylog2-web-interface/src/views/components/visualizations/XYPlot.jsx, graylog2-web-interface/src/views/components/visualizations/area/AreaVisualization.jsx, graylog2-web-interface/src/views/components/visualizations/line/LineVisualization.jsx, graylog2-web-interface/src/views/logic/aggregationbuilder/visualizations/AreaVisualizationConfig.js, graylog2-web-interface/src/views/logic/aggregationbuilder/visualizations/BarVisualizationConfig.js, graylog2-web-interface/src/views/logic/aggregationbuilder/visualizations/Interpolation.js, graylog2-web-interface/src/views/logic/aggregationbuilder/visualizations/LineVisualizationConfig.js
The current search offers options to define the interpolation used in
line/area charts. In order to migrate dashboard widgets using these,
this PR adds functionality to define the interpolation used. Due to the
differences between rickshaw/d3 (used in the current search) and plotly
(used in the views), lesser (but still sufficient) interpolation options
can be offered. The mapping looks like this (rickshaw/d3 -> plotly):
* linear -> linear
* step-after -> hv
* cardinal/basis/bundle/monotone -> spline
Requires #6893 to be merged before.
=> Adding interpolation options for line/area visualizations.

graylog2-web-interface/src/views/components/widgets/ErrorWidget.jsx, graylog2-web-interface/src/views/components/widgets/ErrorWidget.test.jsx, graylog2-web-interface/src/views/components/widgets/MessageWidgets.css
Right now the ErrorWidget error list has a big gab to the left. This PR improves all gabs. It also adds flow and a basic unit test.
=> Adjust ErrorWidget layout gabs and add basic component test

graylog2-server/src/main/java/org/graylog2/rest/resources/system/lookup/LookupTableResource.java
While introducing a new Factory2 in PR #6518
we forgot to return the types for data adapters that
use this factory.
This prevented us from creating new HTTPJsonPath Data adapters.
=> Add missing HTTPJsonPath Data adapter type

graylog2-web-interface/src/views/components/aggregationbuilder/AggregationBuilder.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/AggregationBuilder.test.jsx
In 81107aacbc827a4c2d3d207685b4b544541338cb we introduced the capability to set names for search types which are piped through to the results, allowing a widget to generate multiple search types and address the results by name. Searches created before this, result in the search type id being used instead of the name when generating the result object.
Prior to this PR, extracting the effective timerange from the result object incorrectly assumed that it has a `chart` key. This does not hold true for aforementioned searches created before the introduction of the `name` property. This introduced a regression, where a widget relying on the effective timerange failed.
This PR is addressing this, by falling back to the first search type result from the result object for the extraction of the …
=> Fall back to first search type result to extract effective timerange.

graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationForm.jsx
Add `isClearable` option to select, making it really possible to remove the selected option.
Fixes #6933 
This should be backported to 3.1.
=> Make aggregation field clearable

pom.xml
Includes bug fixes and performance improvements.
https://netty.io/news/2019/10/24/4-1-43-Final.html
=> Update to netty 4.1.43 and netty-tcnative-boringssl 2.0.28

.github/PULL_REQUEST_TEMPLATE.md
This PR removes the checkbox saying that all new and existing tests have
passed. This should not be filled by the user, but is determined by our
status checks.
=> Remove "tests have passed" option from PR template.

graylog2-web-interface/.flowconfig
This change is improving our flow config in two ways:
1.) excluding the `node_modules` folder from flow's type checks,
improving runtime by ~40%
2.) including `test` folder completely, instead of only `test/helpers`.
files in `src` have precedence when an absolute import is used and there
is ambiguity.
=> Improve flow config: exclude `node_modules`, include `test` completely.

graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java
When rotating an index, the following details are calculated and stored
in an index range:
* the smallest timestamp (oldest document)
* the largest timestamp (youngest document)
* the set of stream ids contained in documents in this index
For the latter, a terms query is used. Unfortunately, no specific size
was set for it, so it used the default size of 10. This meant that all
index ranges calculated before did not contain more than 10 stream ids.
In the current search, this did not lead to imminent problems. The logic
used to determine the indices which are used for the search was lenient
enough to only consider either the set of stream ids containing the
current stream id or the index being managed by the index set of the
stream.
The new search is stricter and expects the set of stream …
=> Do not limit terms size when determining stream ids contained in index.

graylog2-server/src/main/java/org/graylog/events/notifications/NotificationDto.java, graylog2-server/src/main/java/org/graylog/events/processor/EventDefinitionDto.java, graylog2-server/src/main/java/org/graylog/events/processor/EventProcessorParameters.java, graylog2-server/src/main/java/org/graylog/events/rest/AvailableEntityTypesResource.java, graylog2-server/src/main/java/org/graylog/events/rest/EventDefinitionsResource.java, graylog2-server/src/main/java/org/graylog/events/rest/EventNotificationsResource.java, graylog2-server/src/main/java/org/graylog/events/rest/EventsResource.java, graylog2-server/src/main/java/org/graylog/events/search/EventsSearchParameters.java, graylog2-server/src/main/java/org/graylog/events/search/EventsSearchResult.java, graylog2-server/src/main/java/org/graylog2/rest/models/system/processing/ProcessingStatusSummary.java, graylog2-server/src/main/java/org/graylog2/rest/resources/alarmcallbacks/AlarmCallbackHistoryResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/alarmcallbacks/AlarmCallbacksResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/alarmcallbacks/StreamAlarmCallbackResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/alerts/AlertResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/alerts/AlertConditionsResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/alerts/StreamAlertConditionResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/alerts/StreamAlertResource.java
Most event resources were either missing `@ApiParam` annotations
or their models were not annotated with `@JsonAutoDetect`.
Both are needed to show meaningful model data in swagger.
Also add the word `legacy` to the old alarm callback resources, so API users are less confused.
=> Improve API browser for several resources

graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java
When rotating an index, the following details are calculated and stored
in an index range:
* the smallest timestamp (oldest document)
* the largest timestamp (youngest document)
* the set of stream ids contained in documents in this index
For the latter, a terms query is used. Unfortunately, no specific size
was set for it, so it used the default size of 10. This meant that all
index ranges calculated before did not contain more than 10 stream ids.
In the current search, this did not lead to imminent problems. The logic
used to determine the indices which are used for the search was lenient
enough to only consider either the set of stream ids containing the
current stream id or the index being managed by the index set of the
stream.
The new search is stricter and expects the set of stream …
=> Do not limit terms size when determining stream ids contained in index

graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/AggregationConfigDTO.java, graylog2-web-interface/src/views/bindings.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/AggregationBuilder.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/AggregationControls.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/EventListConfiguration.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/EventListConfiguration.test.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/EventListConfiguration.test.jsx.snap, graylog2-web-interface/src/views/components/visualizations/area/AreaVisualization.jsx, graylog2-web-interface/src/views/components/visualizations/bar/BarVisualization.jsx, graylog2-web-interface/src/views/components/visualizations/line/LineVisualization.jsx, graylog2-web-interface/src/views/components/visualizations/scatter/ScatterVisualization.jsx, graylog2-web-interface/src/views/logic/aggregationbuilder/AggregationWidgetConfig.js, graylog2-web-interface/src/views/logic/aggregationbuilder/WidgetFormattingSettings.js, graylog2-web-interface/src/views/logic/searchtypes/aggregation/PivotConfigGenerator.js, graylog2-web-interface/src/views/logic/searchtypes/aggregation/PivotConfigGenerator.test.js, graylog2-web-interface/src/views/logic/searchtypes/aggregation/__snapshots__/PivotConfigGenerator.test.js.snap, graylog2-web-interface/src/views/logic/searchtypes/events/EventHandler.js, graylog2-web-interface/src/views/logic/searchtypes/events/EventHandler.test.js, graylog2-web-interface/src/views/logic/searchtypes/events/__snapshots__/EventHandler.test.js.snap
A new configuration option is add to the aggregation controls when a timestamp is
selected for rows and the graph is either a bar, line or scatter graph.
When enabled the widget will add a new search type ('events') to the pivot
search type to retrieve all events to the timerange matching the streams the user
is able to see or selected.
The user then sees vertical lines for a timestamp where alerts occurred.
The user can choose a color for the alert annotation.
The user wants to see when an alert occurred and wants to compare it to other data
to draw conclusions from it.
Add a event definition which will produce alerts and configure the rendering of events
on a timebased bar char.
=> Render events in timebased bar, line and scatter charts

graylog2-web-interface/src/components/common/DataTable.jsx, graylog2-web-interface/src/components/common/TypeAheadDataFilter.jsx, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackApplyParameter.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackConstraints.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntityConfig.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstallEntityList.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstallations.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackVersions.test.jsx.snap
Fix DataTable filter to reapply filter after data updates
Before this change when filtering lists (such as pipeline rules) using the filter function, the filter is 'reset' when you perform an action against a selected object. Now the filter is re-applied if data is changed on component update.
Fix (#5965)
=> Fix DataTable filter to reapply filter after data updates

graylog2-web-interface/public/stylesheets/graylog2.less, graylog2-web-interface/src/views/components/DashboardSearchBar.jsx, graylog2-web-interface/src/views/components/Query.jsx, graylog2-web-interface/src/views/components/QueryTabs.jsx, graylog2-web-interface/src/views/components/SearchBar.jsx, graylog2-web-interface/src/views/components/SearchResult.jsx, graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
I just had to deal with the extended search page grid once again, while implementing a new component. I already had a look at the grid in the past, when refactoring the SearchBar layout.
The main issue right now is, that we are using `<Row>` and `<Col>` components without the needed `<Grid>` component. This is also the reason we are using `margin-left: 0; margin-right 0;` for a few rows inside the extended search page.
I just added the `<Grid>` component and some `<Row>` and `<Col>` components, where needed.
This also resolves the padding issue with the parameters box.
Right now we are using the `<Row>` and `<Col>` components mostly inside each component. In this case we need keep in mind to add the outer `<Grid>` component. A different approach is to not use the row and col component …
=> Implement bootstrap grid component for extended search page

graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessor.java, graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessorConfig.java, graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationResult.java, graylog2-server/src/main/java/org/graylog/events/processor/aggregation/PivotAggregationSearch.java, graylog2-server/src/main/java/org/graylog/events/search/MoreSearch.java, graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/Parameter.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/ValueParameter.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/errors/EmptyParameterError.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/errors/ParameterExpansionError.java, graylog2-server/src/main/java/org/graylog2/lookup/LookupTable.java, graylog2-server/src/test/java/org/graylog/events/processor/aggregation/AggregationEventProcessorTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/views/QualifyingViewsServiceTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/views/RequiresParameterSupportTest.java, graylog2-web-interface/src/components/event-definitions/event-definition-form/EditQueryParameterModal.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationFormContainer.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterPreviewContainer.jsx, graylog2-web-interface/src/views/bindings.jsx, graylog2-web-interface/src/views/logic/parameters/LookupTableParameter.js, graylog2-web-interface/src/views/logic/parameters/Parameter.js, graylog2-web-interface/src/views/logic/parameters/ParameterBinding.js, graylog2-web-interface/src/views/logic/parameters/ValueParameter.js, graylog2-web-interface/src/views/logic/views/CopyWidgetToDashboard.Dashboard-Search.fixture.json, graylog2-web-interface/src/views/logic/views/CopyWidgetToDashboard.test.js, graylog2-web-interface/src/views/logic/views/UpdateSearchForWidgets.Search.fixture.json, graylog2-web-interface/src/views/logic/views/UpdateSearchForWidgets.test.js
Using lookup table parameters in event definition queries
allows us to create events in case a condition matches a list
that is fetched via lookup tables.
- Split Parameters into two subtypes:
ValueParameter and LookupTableParameter.
- Allow Parameters without a Binding, since LookupTableParameters don't require one.
- Add queryParameters to AggregationEventProcessorConfig
- If the LUT does return an empty list and there is no default parameter value defined,
just skip running the query and assume that we received no results.
This avoids running queries with an invalid ES query string.
- Add frontend code to create parameters for an event defintion
cf https://github.com/Graylog2/graylog-plugin-enterprise/issues/1195
=> Add support for lookup table backed parameters

graylog2-server/src/main/java/org/graylog/plugins/views/search/QueryResult.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackend.java, graylog2-web-interface/src/components/bootstrap/BootstrapModalForm.jsx, graylog2-web-interface/src/routing/AppErrorBoundary.test.jsx, graylog2-web-interface/src/views/components/WidgetOverrideElements.jsx, graylog2-web-interface/src/views/components/WidgetOverrideElements.test.jsx, graylog2-web-interface/src/views/components/contexts/QueryEditModeContext.jsx, graylog2-web-interface/src/views/components/sidebar/SideBar.test.jsx, graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.jsx, graylog2-web-interface/src/views/logic/QueryResult.js, graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx, graylog2-web-interface/test/helpers/suppressConsole.js, graylog2-web-interface/test/integration-environment.js
This PR adds a new plugin entity (registered as
`views.elements.widgetOverrides`), which is used to render components
when a widget is opened in edit mode. Those components usually return
`null`, but can `throw` a component that is rendered _instead_ of the
actual widget edit component. This allows any plugin to
intercept widget editing to e.g. check the current widget settings and
display a custom edit component for any widget, which supplies
additional functionality. If the component regularly returns controls,
they will be rendered next to the widget edit component, if the
component throws one, it will be inserted modally and a `retry` function
is passed in, which allows restarting the rendering cycle when the need
to display the component modally is not present anymore.
=> Add pluggable elements rendered in widget edit mode.

graylog2-web-interface/src/views/Constants.js, graylog2-web-interface/src/views/bindings.jsx, graylog2-web-interface/src/views/hooks/BindSearchParamsFromQuery.js, graylog2-web-interface/src/views/hooks/BindSearchParamsFromQuery.test.js, graylog2-web-interface/src/views/logic/views/View.js, graylog2-web-interface/src/views/pages/NewSearchPage.jsx, graylog2-web-interface/src/views/pages/StreamSearchPage.jsx, graylog2-web-interface/src/views/pages/index.js
This PR adds support for the existing search URL's in the new search page. We are using the parameters e.g. when clicking on "Show all Messages" in the inputs overview. Besides the query (parameter `q`) we support the time range, e.g.:
`?rangetype=absolute&from=[date]&to=[date]`
`?rangetype=keyword&keyword=[keyword]`
`?rangetype=relative&relative=0`
or just
`?relative=0`
=> Support existing search URLs in new search page

graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/V20191203120602_MigrateSavedSearchesToViews.java, graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/AbsoluteTimeRangeQuery.java, graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/KeywordTimeRangeQuery.java, graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/Query.java, graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/RelativeTimeRangeQuery.java, graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/search/Query.java, graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/search/StreamFilter.java, graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/V20191203120602_MigrateSavedSearchesToViewsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_relative-expected_views.json, graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_with_stream-expected_searches.json, graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_with_stream-expected_views.json, graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_with_stream.json
Prior to this PR, the saved search migration introduced in #6925 did not
consider that saved searches also contain an optional stream id and
failed if it existed.
This PR introduces support for optional stream ids for saved searches
which are constrained to one stream.
=> Including optional stream from saved searches when generating query.

graylog2-web-interface/src/components/navigation/Navigation.jsx, graylog2-web-interface/src/routing/AppRouter.jsx, graylog2-web-interface/src/views/bindings.jsx
This PR rolls back the changes made when introducing the `search_3_2`
feature flag and now defaults to the new search. `Search` & `Dashboard`
menu items are replaced with new search code while the `Views` top
navigation item is removed.
Fixes #6140.
Requires #6924 & #6936 to be merged before.
=> Defaulting to new search.

graylog2-web-interface/src/views/Constants.js, graylog2-web-interface/src/views/components/aggregationbuilder/pivottypes/TimeUnitTimeHistogramPivot.jsx, graylog2-web-interface/src/views/logic/searchtypes/aggregation/PivotConfigGenerator.js, graylog2-web-interface/src/views/logic/searchtypes/aggregation/PivotConfigGenerator.test.js
Before this change, a time-based pivot with an explicit bucketing
interval specified in multiples of months will not be properly mapped to
elasticsearch units. Instead of being mapped to `M` (Months), it will be
mapped to `m` (minutes).
This change is now explicitly mapping between units instead of taking
the first letter of the original unit.
=> Mapping months to `M` instead of `m` for time pivots.

graylog2-web-interface/src/stores/StoreTypes.js, graylog2-web-interface/src/views/components/Query.jsx, graylog2-web-interface/src/views/components/actions/ActionHandler.jsx, graylog2-web-interface/src/views/logic/valueactions/AddToQueryHandler.js, graylog2-web-interface/src/views/logic/valueactions/AddToQueryHandler.test.js, graylog2-web-interface/src/views/logic/valueactions/ExcludeFromQueryHandler.js, graylog2-web-interface/src/views/logic/valueactions/ExcludeFromQueryHandler.test.js, graylog2-web-interface/src/views/logic/valueactions/QueryManipulationHandler.js, graylog2-web-interface/src/views/stores/GlobalOverrideStore.js, graylog2-web-interface/src/views/stores/QueriesStore.js, graylog2-web-interface/src/views/stores/ViewStore.js
Prior to this PR, using the "Exclude from results" value action did not
work properly when used on a dashboard. It was setting the query string
of the current active query, while on dashboards the global override
must be used.
This change is consolidating commonly used functionality to set a new
query string in the `QueryManipulationHandler` class and employs that to
achieve consistent query updating from the "Exclude from results"
action.
Fixes #7004.
=> Consolidating different handling of query strings in searches/dashboards.

graylog2-web-interface/src/views/components/widgets/Widget.jsx, graylog2-web-interface/src/views/components/widgets/Widget.test.jsx
Prior to this change, pressing cancel in the widget edit modal rolled
back changes to the widget's config. Due to the introduction of widget
queries/streams/time ranges which are part of the widget model (and not
in its config, which is contained in a key in the widget model), changes
to these would not have been reverted when clicking cancel.
This PR is now rolling back the complete widget. Before this change,
changes were rolled back only if the configs differed, now this is being
done unconditionally. Due to our logic in the stores cancelling editing
without having made changes will not lead to a search refresh though.
Fixes #7013.
=> Roll back complete widget when pressing cancel in widget edit modal.

graylog2-web-interface/src/views/components/WidgetQueryControls.jsx, graylog2-web-interface/src/views/components/WidgetQueryControls.test.jsx
This change includes the current time range type when changing a time
range parameter for a widget. This forces the `relative` time range type
being set when it is implicitly derived from the absence of a time range
type.
Fixes #7014.
=> Include time range type when changing time range parameter for widget.

UPGRADING.rst
Mention missing support of old dashboards in content packs in the UPGRADING.rst.
Since the structure of views is fundamentally different to the old dashboards
the content packs facade needs to be adjusted to it.
=> Mention missing support for old dashboards in content packs

graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/Widget.java, graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/WidgetConfigResolver.java, graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/V20191125144500_MigrateDashboardsToViewsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/sample_dashboard_installed_from_content_pack.json
Prior to this change, the case of a widget's type field must be in upper
case for its config subclass to be resolved properly. Content packs use
lowercase for these when installing a dashboard, so these dashboards are
not migrated properly.
This PR is adding a custom type resolver for deserializing widget config
subclasses, which is uppercasing type ids before resolving them.
Fixes #7035.
=> Ignore case when deserializing dashboard widgets in migration.

graylog2-web-interface/src/views/logic/queries/Query.js, graylog2-web-interface/src/views/logic/queries/QueryGenerator.js, graylog2-web-interface/src/views/logic/queries/QueryHelper.js, graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.js, graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.test.js
With the introduction of separate queries per widget, widget filters are becoming deprecated. They are usable from the API, but there are no features in the UI enabling to use them. Therefore, this PR changes the `Show documents for value` action to use widget queries instead of widget filters. In addition, it creates a helpful title for the newly created message table.
Fixes #7020.
=> Change `Show documents for value` to use widget query instead of filter

graylog2-web-interface/src/views/bindings.jsx
This change is registering a search type generator for default widgets
(which are also used for migrated unknown 3rd party widgets), which just
returns an empty list.
This is necessary, because otherwise regenerating a search for a
search/dashboard containing an unknown widget fails, as no function
generating search types for this widget can be resolved.
=> Register search type generator for default widget.

graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/FieldChartConfig.java, graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/QuickValuesConfig.java, graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/SearchResultChartConfig.java, graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/SearchResultCountConfig.java, graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/StatsCountConfig.java, graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/WorldMapConfig.java, graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/V20191125144500_MigrateDashboardsToViewsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_minimal_quickvalues_widget-expected_searches.json, graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_minimal_quickvalues_widget-expected_views.json, graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_minimal_quickvalues_widget.json
Prior to this change, widgets with empty query/limit/data table limit/sort order/stacked fields properties could lead to the migration failing.
This PR makes these fields optional and handles them appropriately, e.g.  defining defaults for limits, trends & sort order.
Requires #7036 to be merged before.
=> Handle optional fields when migrating widgets.

graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackend.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendTest.java
This change lifts a restriction where the backend raises an exception
when a search contains a query with an empty set of search types.
Searches like this can be generated for:
1.) new dashboards containing no widgets
2.) dashboards containing only widgets which do not generate search
types (e.g. unknown 3rd party widgets migrated over)
In the first case the resulting error message is only briefly shown to
the user, in the second case all widgets contain this error instead of
showing the "Unknown widget" help text.
=> Allow queries with empty search types.

graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/V20191125144500_MigrateDashboardsToViews.java, graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/sample_dashboard.json
When adding a widget to a dashboard, moving it and deleting it
afterwards, a widget position entity is created that references a
missing widget. The dashboard migration PR fails when encountering
these, due to a NPE when looking up the created view widget.
This PR is fixing this and ignores orphaned widget positions.
=> Handle orphaned widget positions in migration properly.

graylog2-server/src/main/java/org/graylog2/contentpacks/constraints/GraylogVersionConstraintChecker.java
Prior to this change, the version check for content packs in development
failed, since the graylog version had a suffix (like SNAPSHOT or beta-1)
which prevented the check to succeed.
This change will clear the suffix before testing the requirement
(version check).
=> Fix version check of content packs in development

graylog2-web-interface/src/views/components/visualizations/GenericPlot.jsx
This PR fixes: #7049
The reason for the static width, was in in the end the changed widget layout (`display: grid`). While searching for a solution I found the plotly config setting `responsive: true` and it allows these type of flexible containers. We still need the layout setting `autosize: true`, otherwise the charts would have a fixed size.
=> Resize plotly visualizations correctly when changing their width

graylog2-web-interface/src/views/pages/StreamSearchPage.jsx, graylog2-web-interface/src/views/pages/StreamSearchPage.test.jsx
This PR fixes #7016
As described in the issue, we are not refreshing the StreamSearchPage view state when selecting a different stream e.g. inside the message list stream overview.
=> Update StreamSearchPage when current stream id changes

pom.xml
This security update blocks two more gadget types (no CVEs yet) and
fixes a NoClassDefFoundError.
For details see:
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9#micro-patches
=> Security update to jackson-2.9.10.20200103

pom.xml
This is a bug-fix release. One of the important fixes is, that it
removes the dependency on a newer glibc version:
- Remove dependency on GLIBC 2.12 by using syscalls directly
(netty/netty#9797)
For more details see the changelog:
https://netty.io/news/2019/12/18/4-1-44-Final.html
=> Update to netty-4.1.44

graylog2-web-interface/src/views/components/WidgetQueryControls.jsx, graylog2-web-interface/src/views/components/WidgetQueryControls.test.jsx
=> Execute search after resetting global filter inside widget edit modal

graylog2-web-interface/src/components/layout/Footer.jsx, graylog2-web-interface/src/components/layout/Footer.test.jsx
When refactoring the `Footer` component, it was overlooked that the
state of the `SystemStore` is wrapped in an object with another `system`
key and tried to access its contents directly. Thus the footer did not
show the Graylog version and the current hostname.
This change is now adding a props mapper function to the `connect` call
which destructures the store's state properly and adds tests.
Fixes #7076.
=> Destructure result from `SystemStore` properly in `Footer`.

graylog2-web-interface/src/pages/ShowMessagePage.jsx, graylog2-web-interface/src/pages/__snapshots__/ShowMessagePage.test.jsx.snap, graylog2-web-interface/src/views/components/messagelist/MessageDetail.jsx, graylog2-web-interface/src/views/components/messagelist/MessageTableEntry.jsx, graylog2-web-interface/src/views/components/messagelist/NodeName.jsx
Prior to this change, the `NodesStore` triggered a periodic rerendering
of the `MessageDetail` component. This caused a remounting of the
`FieldActions`/`ValueActions` component, resetting the state of
potentially opened drop downs.
This change is decoupling the consumption of the `NodesStore` by
reusing the `LinkToNode` component, keeping the store consumption as
local to rendering as possible.
Fixes #7059.
=> Reducing remounting/-rendering of `MessageDetail` component.

graylog2-web-interface/src/views/components/aggregationbuilder/FullSizeContainer.jsx
As described in #7091, the horizontal scrolling for a datatable with many columns is currently broken. This PR fixes this issue by adding `overflow: hidden;` to the widget container. The datatable already has a `overflow: auto;` and will show the scrollbar dynamically.
While having a look at these changes I identified another problem. In the aggregation builder the scrollbar exists and the user could scroll horizontal in theory, but the scrollbar is not visible, due to some height calculation. I will create another issue for this case, because we need to adjust the aggregation builder layout, I did not fixed this issue with this PR.
I had a look at all other widget types, to make sure this has no side effects.
=> Fix horizontal scrolling for datatable widget

graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/searchtypes/ESMessageList.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/searchtypes/ESMessageListTest.java
Contrary to the old implementation the new search has not respected the
config file setting for query string highlighting in message list
search results. This pr fixes that.
Fixes #7052 
Added unit tests and manually verified that highlighting is only applied, if activated in config.
=> Apply `allow_highlighting` config  to views-based search

graylog2-web-interface/src/views/components/visualizations/worldmap/MapVisualization.jsx
As described in #7095 the worldmap visualization is currently broken. The reason is the missing and [necessary](https://react-leaflet.js.org/docs/en/setup) leaflet css import.
This error did not appeared before, because webpack was still aware of the `leaflet.css`, due to the import inside the old `MapVisualization.jsx`. But in the meantime the old widget is not getting referenced anymore.
=> Add missing leaflet css import for MapVisualization

graylog2-web-interface/src/views/components/widgets/WidgetErrorBoundary.jsx, graylog2-web-interface/src/views/components/widgets/WidgetErrorBoundary.test.jsx
This PR fixes #7107. The Problem was, we are not passing `onChange` to the `WorldMapVisualization`, due to the new `WidgetErrorBoundary` and the usage of `React.cloneElement` inside the `AggregationControls`.
=> Save world map widget viewport on widget save

graylog2-web-interface/src/views/components/aggregationbuilder/AggregationControls.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/DescriptionBox.jsx, graylog2-web-interface/src/views/components/widgets/Widget.jsx
This PR fixes the horizontal scrolling / overflow problem described in #7109 and also the vertical scrolling problem described in #7105 regarding the AggregationBuilder.
It looks like we could also get rid of `MeasureDimensions`, used in `Widget.jsx`, it is just passing the container height to its children, but I don't see any benefit. I am not doing this refactoring inside this PR, because I want to avoid a bigger layout change at this moment.
Tested in Chrome, Firefox and Safari
=> Make configuration section layout in AggregationBuilder more responsive

graylog2-web-interface/src/views/bindings.jsx, graylog2-web-interface/src/views/bindings.test.jsx, graylog2-web-interface/src/views/logic/fieldactions/ChartActionHandler.js, graylog2-web-interface/src/views/logic/fieldactions/ChartActionHandler.test.js
This PR is correcting the conditions for enabling `Aggregate`, `Statistics`, `Add to all tables` & `Remove from all tables` if the current field is a function.
In addition, it changes the `Chart` action to use the function itself as the series for the newly created widget if it was triggered by clicking on a function instead of a field.
Fixes #7089.
=> Disabling field actions if not applicable to current field/function.

graylog2-web-interface/src/actions/configurations/ConfigurationActions.js, graylog2-web-interface/src/pages/ConfigurationsPage.jsx, graylog2-web-interface/src/stores/configurations/ConfigurationsStore.js
Before this change we were using ClusterConfig API to update
Urlwhitelist, result of that audit log shows cluster config event
instead of Urlwhitelist event.
* Add updateWhitelist method to store
* Update ConfigurationsPage to use updateWhitelist when updating
urlwhitelist
=> Use Urlwhitelist API instead of clusterConfig API

graylog2-web-interface/src/views/components/aggregationbuilder/SeriesConfiguration.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/SeriesConfiguration.test.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/SeriesSelect.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/SeriesConfiguration.test.jsx.snap, graylog2-web-interface/src/views/components/datatable/DataTableEntry.jsx, graylog2-web-interface/src/views/components/datatable/DataTableEntry.test.jsx, graylog2-web-interface/src/views/components/datatable/Headers.jsx, graylog2-web-interface/src/views/components/datatable/Headers.test.jsx
As described in #6664, renaming a series causes field type resolution to fail.
This PR fixes a couple of issues around this:
- Adding validation to the series configuration dialog, not allowing the user to give a series an already existing name
- Fixing type resolution in data table headers for renamed series
- Fixing type resolution in data table cells for the values of renamed series
Fixes #6664.
=> Resolve field types correctly for renamed series.

graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/buckets/TimeUnitInterval.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/searchtypes/pivot/buckets/TimeUnitIntervalTest.java
Due to limitations in Elasticsearch, it does not support time unit
bucket intervals with values bigger than 1 for units bigger than days.
Therefore, this PR transparently converts these to days (with multiples
of 7 resp. 30) if the value is bigger than 1, leaving the original unit
otherwise.
In contrast to the initial attempt in #7055, this PR is performing the
change in the backend, transparent to the caller and relieving the
caller from having to do the conversion before.
Fixes #7022.
=> Convert week/month bucket interval to days if value is bigger than 1.

graylog2-web-interface/src/views/components/ViewActionsMenu.jsx, graylog2-web-interface/src/views/components/views/ShareViewModal.jsx, graylog2-web-interface/src/views/components/views/ViewPropertiesModal.jsx
As described in #7018 the word "view" still exists in some dashboard info tests. This PR renames them to "dashboard".
Fixes #7018
=>  Rename view to dashboard for all dashboard related info text

graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchClientConfiguration.java, graylog2-server/src/main/java/org/graylog2/indexer/cluster/jest/JestUtils.java, graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java, graylog2-server/src/main/java/org/graylog2/outputs/ElasticSearchOutput.java, graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerIT.java, graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesGetAllMessageFieldsIT.java, graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java, graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesIT.java, graylog2-server/src/test/java/org/graylog2/indexer/messages/MockedMessagesTest.java, misc/graylog.conf
If we try to bulk index a batch of messages that exceeds the
elastic search `http.max_content_length` setting. (default 100MB)
Elastic will respond with an HTTP 413 Entity Too Large error.
In this case we retry the request by splitting the message batch
in half.
When responding with an HTTP 413 error, the server is allowed to close the connection
immediately. This means that our HTTP client (Jest) will simply report
an IOException (Broken pipe) instead of the actual error.
This can be avoided by sending the request with an Expect-Continue
header, which also avoids sending data that will be discarded later on.
Fixes #5091
Fixes #6965
=> Handle Request Entity Too Large errors in ElasticSearchOutput

graylog2-server/src/main/java/org/graylog/events/notifications/NotificationDto.java, graylog2-server/src/main/java/org/graylog/events/processor/EventDefinitionDto.java, graylog2-server/src/main/java/org/graylog/events/processor/EventProcessorParameters.java, graylog2-server/src/main/java/org/graylog/events/rest/AvailableEntityTypesResource.java, graylog2-server/src/main/java/org/graylog/events/rest/EventDefinitionsResource.java, graylog2-server/src/main/java/org/graylog/events/rest/EventNotificationsResource.java, graylog2-server/src/main/java/org/graylog/events/rest/EventsResource.java, graylog2-server/src/main/java/org/graylog/events/search/EventsSearchParameters.java, graylog2-server/src/main/java/org/graylog/events/search/EventsSearchResult.java, graylog2-server/src/main/java/org/graylog2/rest/models/system/processing/ProcessingStatusSummary.java, graylog2-server/src/main/java/org/graylog2/rest/resources/alarmcallbacks/AlarmCallbackHistoryResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/alarmcallbacks/AlarmCallbacksResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/alarmcallbacks/StreamAlarmCallbackResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/alerts/AlertResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/alerts/AlertConditionsResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/alerts/StreamAlertConditionResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/alerts/StreamAlertResource.java
Most event resources were either missing `@ApiParam` annotations
or their models were not annotated with `@JsonAutoDetect`.
Both are needed to show meaningful model data in swagger.
Fixes #6742
(cherry picked from commit 4fe82c2833d2523fdcb363dbbe0fb75677564032)
=> Improve API browser for several resources (#6955)

graylog2-web-interface/src/views/logic/fieldactions/AggregateActionHandler.js, graylog2-web-interface/src/views/logic/fieldactions/AggregateActionHandler.test.jsx, graylog2-web-interface/src/views/logic/fieldactions/ChartActionHandler.js, graylog2-web-interface/src/views/logic/fieldactions/ChartActionHandler.test.js, graylog2-web-interface/src/views/logic/fieldactions/DuplicateCommonWidgetSettings.js, graylog2-web-interface/src/views/logic/fieldactions/DuplicateCommonWidgetSettings.test.jsx, graylog2-web-interface/src/views/logic/fieldactions/FieldStatisticsHandler.js, graylog2-web-interface/src/views/logic/fieldactions/FieldStatisticsHandler.test.js, graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.js, graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.test.js
Prior to this change, several field actions ("Chart", "Aggregate", "Statistics") and the "Show documents for value" value action did not duplicate the context of the widget they were triggered from, although the user most certainly expects that. This led to differing results.
When a user e.g. clicks on the "Show documents for value" action on a value of a filtered down (or extended through a bigger time range) result, the widget created from the action did not contain the same query/timerange/streams/filter settings but the default ones, and therefore referred to a different set of documents.
This change is creating a shared function which duplicates these settings from a given widget and is supposed to be used by any action that creates a new widget that is supposed to work in the same …
=> Duplicate query/timerange/streams/filter for specific field/value actions.
