Graylog2/graylog2-server

graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchClientConfiguration.java
graylog2-server/src/main/java/org/graylog2/indexer/cluster/jest/JestUtils.java
graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
graylog2-server/src/main/java/org/graylog2/outputs/ElasticSearchOutput.java
graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerIT.java
graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesGetAllMessageFieldsIT.java
graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesIT.java
graylog2-server/src/test/java/org/graylog2/indexer/messages/MockedMessagesTest.java
misc/graylog.conf

If we try to bulk index a batch of messages that exceeds the
elastic search `http.max_content_length` setting. (default 100MB)
Elastic will respond with an HTTP 413 Entity Too Large error.
In this case we retry the request by splitting the message batch
in half.
When responding with an HTTP 413 error, the server is allowed to close the connection
immediately. This means that our HTTP client (Jest) will simply report
an IOException (Broken pipe) instead of the actual error.
This can be avoided by sending the request with an Expect-Continue
header, which also avoids sending data that will be discarded later on.
Fixes #5091
* Move JestClient execution with RequestConfig into JestUtils
* Please forbiddenapi checker
* Correctly handle batches with unevenly sized messages
If we have a batch …

Handle Request Entity Too Large errors in ElasticSearchOutput (#7071)

---

graylog2-server/src/main/java/org/graylog/plugins/beats/BeatsTransport.java
graylog2-server/src/main/java/org/graylog2/Configuration.java
graylog2-server/src/main/java/org/graylog2/inputs/transports/HttpTransport.java
graylog2-server/src/main/java/org/graylog2/inputs/transports/SyslogTcpTransport.java
graylog2-server/src/main/java/org/graylog2/inputs/transports/TcpTransport.java
graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java
graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java
graylog2-server/src/test/java/org/graylog/plugins/beats/BeatsTransportTest.java
graylog2-server/src/test/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransportTest.java
misc/graylog.conf

With the introduction of netty 4 in Graylog 3.0, we changed the default
SslProvider to OpenSSL.
While this gives a better performance, it lacks the ability to disable
TLS protocols that are considered flawed.
Changes to the java security properties are only respected by jdk based
SslProviders (jersey / grizzly in our case).
Introduce a system wide default setting for supported TLS protocols,
with a sane default to TLSv1.2 (and TLSv1.3 if the jdk supports it).
These protocol settings are applied to netty based inputs and
to the webserver.
Changes can be made with a new server setting:
`#enabled_tls_protocols = TLSv1.2,TLSv1.3`
Fixes #6444
PS: This can be tested by using 
`nmap --script ssl-enum-ciphers -p <inputs-port> 127.0.0.1`

Enforce system wide TLS protocol settings

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewSharingResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java

Before this commit none of the endpoints of the affected resources that
included a path parameter worked from the API browser, because the path
parameters weren't properly processed.
Fixes #6860
Swagger annotations for path parameters need to include the parameter name to be preoperly processed in the API browser.
Manual tests from local API browser

Fix Swagger annotations in Views resources

---

graylog2-web-interface/src/components/common/Select.jsx
graylog2-web-interface/src/components/common/Select.test.jsx
graylog2-web-interface/src/components/configurations/decorators/StreamSelect.jsx
graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/BooleanOperatorSelector.jsx
graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/ComparisonExpression.jsx
graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/NumberRefExpression.jsx
graylog2-web-interface/src/components/event-definitions/event-definition-types/__snapshots__/AggregationConditionExpression.test.jsx.snap
graylog2-web-interface/src/components/sidecars/configuration-forms/CollectorForm.jsx
graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.jsx
graylog2-web-interface/src/components/streams/StreamForm.jsx
graylog2-web-interface/src/views/components/aggregationbuilder/SeriesSelect.jsx
graylog2-web-interface/src/views/components/messagelist/decorators/AddDecoratorButton.jsx
graylog2-web-interface/src/views/components/searchbar/StreamsFilter.jsx

During the React Select migration to v2 we missed to replicate the functionality of some props that got removed or renamed, so some features of selects we and plugins relied on were not working as expected in some cases.
This PR fixes all missing functionality I found, and adds some tests to ensure that is currently working. Here is some information on the props adapted in this PR:
- `clearable` was renamed to ` isClearable`. Since the default value for this property in v1 was `true`, I used the same as default
- `disabled` inside the `options` object is no longer supported, we now use `isOptionDisabled` to check if that property is set and disable the `option`
- `inputProps` was removed, we use a custom component to achieve that. All usages of `inputProps` were replaced by `inputId`, …

Complete migration to React Select v2

---

pom.xml

This includes fixes for regressions that have been introduced in 4.1.44.
See full changelog: https://netty.io/news/2020/01/13/4-1-45-Final.html

Update to netty 4.1.45

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/Query.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/timeranges/DerivedTimeRange.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/timeranges/OffsetRange.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/QueryEffectiveTimeRangeTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/timeranges/DerivedTimeRangeTest.java

Prior to this change, time ranges per search type were either overwritten by the global override time range (if present) or "derived" from the search type/query's time range. This led to offset time ranges being overwritten by the global override time range and therefore breaking trending.
This change is now taking the global override time range into account when "deriving" a time range. That means the offset time range checks if a global override time range is present and uses it as reference. If it is absent, it uses its configured source time range.
Fixes #7134.

Use global override time range as reference for offset time ranges.

---

graylog2-web-interface/src/views/components/visualizations/OnZoom.js
graylog2-web-interface/src/views/components/visualizations/OnZoom.test.jsx
graylog2-web-interface/src/views/components/visualizations/XYPlot.jsx
graylog2-web-interface/src/views/stores/GlobalOverrideStore.js

Prior to this change, zooming (dragging a range) on a timeline chart on
a dashboard did nothing, because it set the query's time range which is
not considered on dashboards.
This change is now conditionally setting the global override's time
range if on a dashboard and the query's time range if not. It does this
by checking the view's type in the zoom handler.
Ideally we should instead provide a `DrilldownContext` for all actions,
that provides commonly used actions/states (setting/getting current time
range, query, stream selection), so actions do not determine on their
own which one to pick.

Zoom global override when zooming in timeline chart on dashboard.

---

graylog2-server/src/main/java/org/graylog2/Configuration.java
graylog2-server/src/main/java/org/graylog2/configuration/PathConfiguration.java
graylog2-server/src/main/java/org/graylog2/plugin/KafkaJournalConfiguration.java

Using "#getDataDir()" to initialize the default dir values for the
contentpack and message journal works, but it implies that they
will automatically use the user configured "data_dir" setting. This is
not true because "#getDataDir()" to set the default value will be called
before the configuration is parsed.
Introduce constants for the bin, data and plugin dir and use those as
default values to make it explicit that the default will not change
automatically by setting a custom "data_dir".

Avoid using PathConfiguration#getDataDir() for default path configs

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/Search.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/PermittedStreams.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/SearchTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/PermittedStreamsTest.java

Before this change a ForbiddenException would be thrown every time streams were loaded for users without access to any streams. This was only appropriate during search execution, but not in other places where `PermittedStreams#load` was reused. This had led to wrong 401s from the backend and  confusing behavior of the frontend where such users were often routed to a 404 error page upon 401s.
Fixes #7165
- Removed exception from `PermittedStreams#load` to allow reuse of this
method in places where an exception is not appropriate
- Added exception to `Search#addStreamsToQueriesWithoutStreams` which is
the one place where it's actually needed.
- unit tests

Allow PermittedStreams to load empty lists

---

graylog2-web-interface/src/views/components/sidebar/SideBar.jsx
graylog2-web-interface/src/views/components/sidebar/SideBar.test.jsx

Because the previous search sidebar title "New Search" is sometimes misleading, we are changing it to "Untitled Search"

Rename default search sidebar title from 'New Search' to 'Untitled Search'

---

graylog2-web-interface/src/views/components/EmptyValue.jsx
graylog2-web-interface/src/views/components/datatable/DataTableEntry.jsx
graylog2-web-interface/src/views/components/datatable/DataTableEntry.test.jsx
graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.jsx

In #7108, the behavior of `DataTableEntry` is accidentally changed,
returning `EmptyValue` for everything `null` or `undefined`. This
changes the behavior for deduplicated values.
This PR is restoring the original behavior and adds a test case.
Fixes #7181.

Do not show `Empty Value` for deduplicated values.

---

graylog2-web-interface/src/views/components/dashboard/bigdisplay/CycleQueryTab.test.jsx

Before this change, the `CycleQueryTab` test used real timers to wait
for the component to switch tabs. This made the test very slow and also
resulted in false negatives due to race conditions, making the test
unreliable and slowing down overall test execution.
This PR is changing the test to use fake timers and therefore reduces
execution time immensely. In addition, it does not check
`setInterval`/`clearInterval` usage, but tests for their actual
implications, making the test less dependent on the implementation.
Before:
```
PASS  src/views/components/dashboard/bigdisplay/CycleQueryTab.test.jsx
CycleQueryTab
cycles tabs:
✓ does not return markup (43ms)
✓ should switch to next tab after interval (1009ms)
✓ should switch to first tab if current one is the last (1004ms)
✓ should switch to …
```

Improving `CycleQueryTab` test by using fake timers.

---

graylog2-web-interface/src/views/components/searchbar/AbsoluteTimeRangeSelector.jsx
graylog2-web-interface/src/views/components/searchbar/AbsoluteTimeRangeSelector.test.jsx

Before this change, emptying one of the date fields of the absolute time
range inputs resulted in an error being logged to the browser console,
because it was tried to parse as date.
This PR is checking if the supplied new value is a valid date string
before parsing it.
Fixes #7190.

Do not parse empty value of from/to field as date for absolute ranges.

---

UPGRADING.rst
graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java
graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping5.java
graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping6.java
graylog2-server/src/main/java/org/graylog2/plugin/Message.java
graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerIT.java
graylog2-server/src/test/java/org/graylog2/plugin/MessageTest.java
graylog2-web-interface/src/logic/message/MessageFieldsFilter.js

That field contains the message size that will be accouted for
Enterprise license checks. It can be used to analyze traffic per stream
or similar use cases.
This change adds the new field to all message index templates and writes
the field to indexed messages.
Closes #6838

Add "gl2_accounted_message_size" field to indexed messages

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/DashboardsResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/FieldTypesResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/PivotSeriesFunctionsResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/QualifyingViewsResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SavedSearchesResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewSharingResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
graylog2-server/src/main/java/org/graylog2/rest/resources/dashboards/DashboardWidgetsResource.java
graylog2-server/src/main/java/org/graylog2/rest/resources/dashboards/DashboardsResource.java
graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java
graylog2-server/src/main/java/org/graylog2/rest/resources/search/KeywordSearchResource.java
graylog2-server/src/main/java/org/graylog2/rest/resources/search/RelativeSearchResource.java
graylog2-server/src/main/java/org/graylog2/rest/resources/search/SavedSearchesResource.java

Removed "Enterprise/" prefix for new views endpoints and added "Legacy/" for old ones.
Fixes #7150
Left `DecoratorResource` untouched: https://github.com/Graylog2/graylog2-server/blob/c02f86de0e283dc53aa4ff2ef9f14a833b5cbe43/graylog2-server/src/main/java/org/graylog2/rest/resources/search/DecoratorResource.java#L52
It technically is an old resource but views depend on it and we should move it to the `views` package imo.
Views is not an Enterprise feature anymore and we want to clearly mark the old endpoints as legacy to discourage users from depending on them.
Manual review in local dev environment

Clean up naming of views endpoints in api browser

---

graylog2-web-interface/src/views/stores/CurrentViewStateStore.js
graylog2-web-interface/src/views/stores/CurrentViewStateStore.test.js

As described in #6985 the widget position persists in the view state when deleting a widget. When saving a dashboard the widget position still persists in the database as well.
This PR just removes all positions without a related widget, when updating the widgets.
Fixes #6985

Remove widget position from view state, on widget delete

---

graylog2-web-interface/src/views/actions/QueriesActions.js
graylog2-web-interface/src/views/hooks/BindSearchParamsFromQuery.js
graylog2-web-interface/src/views/hooks/BindSearchParamsFromQuery.test.js
graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.js
graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.test.jsx
graylog2-web-interface/src/views/logic/queries/Query.js
graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
graylog2-web-interface/src/views/pages/ExtendedSearchPage.test.jsx
graylog2-web-interface/src/views/pages/NewSearchPage.jsx
graylog2-web-interface/src/views/stores/QueriesStore.js
graylog2-web-interface/src/views/stores/QueriesStore.test.jsx

The current search has a feature, where the current time range and query
string is synchronized with the URL in the browser. This means that:
- current time range and query string are part of the URL and copying
and replaying the URL allows restoring the state for these
- a change to time range or query string creates a new state in the
history stack, allowing the user to go back and forward between
different states
- going back or forward in the browser history restores the time range
& query string of this specific state
This PR is recreating this functionality for the new search.
Fixes #7144.

Synchronize timerange & query with URL on search page.

---

graylog2-web-interface/src/views/components/sidebar/SideBar.jsx
graylog2-web-interface/src/views/components/sidebar/SideBar.test.jsx

Follow up PR for https://github.com/Graylog2/graylog2-server/pull/7171
A view type specific default title should improve the user experience even more. Thanks @dennisoelkers for the suggestion.

Display view type specific default sidebar title

---

graylog2-web-interface/src/views/components/Select.jsx

The current dropdown menu of the `Select` component sometimes gets cut off and some options are no longer selectable. Here is an example of the aggregation builder:
This PR implements the `Overlay` from `react-overlay` to display the menu independently from its parent containers.
The new menu wrapper also defines a minimum width of 200px, until now a dropdown could be very small, depending on the parent container.
By default the menu has still the width of the related select input.
With these changes we are also breaking long option names.
Before (master):
The user has to scroll horizontally to read the full name, the style is broken, even the list items have a width of 100%. 
After:
In my opinion the second solution it easier to read. Even when long option names, separated by underscores …

Implement overlay for select menu

---

graylog2-web-interface/src/views/components/aggregationbuilder/SortDirectionSelect.jsx

Before this change, the `SortDirectionSelect` placeholder looked like
depending on the resolution.
This only happens for the `SortDirectionSelect`, because we are using `Select` from `react-select` directly instead of our own `Select` component.
Ideally we should use our own `Select` component for the `SortDirectionSelect` as well.

Fix placeholder overflow for SortDirectionSelect

---

graylog2-web-interface/src/views/components/sidebar/NavItem.styles.jsx

I had a look at #7146 (Context menu for fields is off in search sidebar for long field names) and could not really find a dynamic solution.
We are using `react-window` to render only a part of the probably large field list. The related list component needs to render the list items with `position: absolute`. Which means there is no elegant way to define a dynamic width for the list. There is also no way to have list items with a dynamic height, otherwise wrapping the list items would be a possible solution.
Another possible solution, is setting the Dropdown placement to `bottom`. It would fix the described behaviour, but is not working perfectly for list items near the bottom of the browser window. I also prefer a consistent placement of the field action context menu.
The only workaround I …

Increase sidebar field list width

---

graylog2-web-interface/src/views/logic/views/OnSaveAsViewAction.js
graylog2-web-interface/src/views/logic/views/OnSaveAsViewAction.test.js

As described in #7201, currently the user gets redirected to `/views/[viewID]`, after saving a new dashboard. This PR changes the URL to the correct one `/dashboards/[viewID]`.

Redirect to dashboard route instead of view route after saving new dashboard

---

graylog2-server/src/test/java/org/graylog/plugins/views/search/QueryEffectiveTimeRangeTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/db/SearchesCleanUpJobWithDBServicesTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendUsingCorrectIndicesTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/searchtypes/pivot/ESPivotTest.java

This adds a missing `DateTimeUtils.setCurrentMillisSystem()` to avoid
a sporadic test failure in `DBJobTriggerServiceTest`.
The `SearchesCleanUpJobWithDBServicesTest` is using
`DateTimeUtils.setCurrentMillisFixed()` to set the time to a specific
value. This requires the usage of `DateTimeUtils.setCurrentMillisSystem()`
to reset the time to the current time. Otherwise tests running in the
same JVM using the current time might fail.
I noticed that the `DBJobTriggerServiceTest#deleteCompleted` test method
failed from time to time on a new Jenkins worker machine. This is
probably due to a changed execution order because the machine is faster
than the older worker machine. Still, strange that it didn't show up
earlier.

Reset time in SearchesCleanUpJobWithDBServicesTest teardown method

---

UPGRADING.rst

This change is improving the Upgrade Notes, by:
* Adding a note urging the user to take a backup before upgrading
* Listing missing functionality in 3.2.0.

Adding backup note & known missing functionality for search to upgrade notes.

---

graylog2-web-interface/src/components/event-definitions/event-definition-form/EditQueryParameterModal.jsx
graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx
graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationSummary.jsx
graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterForm.jsx

This PR makes some improvements in the UI around support for Lookup Table Parameters in Filter & Aggregation Alerts, and also removes two warnings from the developer console:
- `Warning: Failed prop type: The prop `children` is marked as required in `<<anonymous>>`, but its value is ``null``.`
- `Warning: validateDOMNesting(...): <h5> cannot appear as a descendant of <p>.`
Before:
After:

Fix Alerting Lookup Table Parameters UI

---

graylog2-web-interface/src/components/events/events/EventsContainer.jsx

Store Alert search timerange and Event type (Alert, Event, Both) in
local storage, letting users come back to the page and have the same
settings as last time they were there.
Fixes #6796

Persist Alert search timerange and type

---

graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx
graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpression.jsx
graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/BooleanExpression.jsx
graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/ComparisonExpression.jsx
graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/GroupExpression.jsx
graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/NumberExpression.jsx
graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/NumberRefExpression.jsx
graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionSummary.jsx
graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionsForm.jsx
graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionsFormSummary.jsx
graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationSummary.jsx
graylog2-web-interface/src/components/event-definitions/event-definition-types/__snapshots__/AggregationConditionExpression.test.jsx.snap
graylog2-web-interface/src/logic/alerts/AggregationExpressionValidation.js

Adds frontend validation to multiple aggregation condition. Doing the validation in the backend didn't really work, since a non-valid expression tree won't be parsed by Jackson and can't be validated in a custom way in the same way other configuration is.
This is how it looks like while editing the form:
And this is after the server answers with a 400 error:
Fixes #7149

Add validation to multiple aggregation condition

---

graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkList.jsx
graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkList.test.jsx.snap

The search bookmark list items are currently displaying the titles as a header element. After merging https://github.com/Graylog2/graylog2-server/pull/7069 (which fixes the active state) these items would have a big font size.
The removed `summary` attribute can no longer be defined for saved searches.

Remove not needed header from search bookmark list items

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/Filter.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/Query.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/Search.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchType.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/filter/AndFilter.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/filter/OrFilter.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/filter/QueryStringFilter.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/filter/StreamFilter.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/MessageList.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/events/EventList.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/views/WidgetDTO.java
graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPacksModule.java
graylog2-server/src/main/java/org/graylog2/contentpacks/facades/ViewFacade.java
graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/EventListEntity.java
graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/MessageListEntity.java
graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/PivotEntity.java
graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/QueryEntity.java
graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/SearchEntity.java
graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/SearchTypeEntity.java
graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/WidgetEntity.java
graylog2-server/src/test/java/org/graylog2/contentpacks/facades/ViewFacadeTest.java

This change adds this mapping to the Widget and WidgetEntit
for the DashboardWidget.
For the search types there are now Entities so we can easily
map the streams during creation and installation of the
content pack.
For the query we needed to add a generic Builder access
for the Filter so we could change the Stream id for
a StreamFilter and rebuild the Filter refered in the
QueryEntity and Query.
Prior this change, when creating a content pack containing
views with streams the stream was collected as an dependency
into the content pack but the StreamEntity got a new id.
This id needs to be used in all references of the stream.
Therefore also in the ViewEntity where a streamid is persisted.
Also when installing this content pack the installed
stream has a new ID yet again and the view …

Add mapping of stream ids in view content packs

---

graylog2-web-interface/src/views/components/dashboard/BigDisplayModeConfiguration.jsx
graylog2-web-interface/src/views/components/dashboard/BigDisplayModeConfiguration.test.jsx

This PR fixes the behaviour described in #7211 (allowing negative numbers for refresh and cycle interval) regarding the full screen dashboard config modal, mainly by adding a HTML form element.
I had to adjust the form submit inside the related tests, because submitting the form by triggering a click on the save button results in the following error:
`Not implemented: HTMLFormElement.prototype.submit`.
Fixes #7211

Improve form validation for dashboard full screen config modal

---

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java
graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/lookup/LookupAddStringList.java
graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/lookup/LookupClearKey.java
graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/lookup/LookupRemoveStringList.java
graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/lookup/LookupSetStringList.java
graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/lookup/LookupSetValue.java
graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/lookup/LookupStringList.java
graylog2-server/src/main/java/org/graylog2/lookup/LookupTable.java
graylog2-server/src/main/java/org/graylog2/lookup/LookupTableService.java
graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupDataAdapter.java
graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/lookupAddStringList.txt
graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/lookupClearKey.txt
graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/lookupRemoveStringList.txt
graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/lookupSetStringList.txt
graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/lookupSetValue.txt

This adds the following pipeline functions:
- `lookup_set_value("table-name", "key", "value")`
- `lookup_set_string_list("table-name", "key", ["value1", "value2"])`
- `lookup_add_string_list("table-name", "key", ["value1", "value2"])`
- `lookup_remove_string_list("table-name", "key", ["remove1", "remove2"])`
- `lookup_clear_key("table-name", "key")`

 Add pipeline functions to modify lookup tables

---

graylog2-web-interface/src/components/common/PaginatedList.jsx
graylog2-web-interface/src/components/common/PaginatedList.test.jsx

As described in #7210, the MessageList pagination does not work in the dashboard full screen mode. This PR hides the pagination inside the PaginatedList, when the `InteractiveContext` defines the context as not interactive. We can safely add this to the shared component because the context is by default interactive.
I would prefer to disable the pagination, but the bootstrap component does not support this functionality and we would have to implement all the styles and logic on our own.
Fixes #7210

Hide Pagination in PaginatedList when context is not interactive

---

graylog2-server/src/main/java/org/graylog2/bindings/providers/JestClientProvider.java
graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchClientConfiguration.java
graylog2-server/src/main/java/org/graylog2/configuration/validators/HttpOrHttpsSchemeValidator.java
graylog2-server/src/test/java/org/graylog/testing/elasticsearch/ElasticsearchInstance.java
graylog2-server/src/test/java/org/graylog2/bindings/providers/JestClientProviderTest.java
graylog2-server/src/test/java/org/graylog2/configuration/ElasticsearchClientConfigurationTest.java
misc/graylog.conf

Adds a new elasticsearch_discovery_default_scheme option in graylog config file.
Implements #6280 
During graylog bootstrap ensure http (default scheme) is passed to JestClientProvider when no config provided and the one in the config file is used when specified.

Add elasticsearch_discovery_default_scheme to config

---

graylog2-server/src/main/java/org/graylog2/lookup/LookupTableService.java
graylog2-server/src/test/java/org/graylog2/lookup/LookupTableServiceTest.java

This improves the lookup table value setters to only pass on valid keys and values to the lookup table backends.

Ensure valid keys and values for lookup table value setters

---

graylog2-web-interface/src/views/logic/views/OnSaveViewAction.js
graylog2-web-interface/src/views/logic/views/OnSaveViewAction.test.js
graylog2-web-interface/src/views/stores/ViewStore.js
graylog2-web-interface/src/views/stores/ViewStore.test.js

As described in #7244 editing a dashboards title, description and summary updated the database entry, but not the frontend view state. This PR implements a new `ViewAction` named `updated`. It gets called in `OnSaveViewAction`, before calling the api to update the database entry. It also removes some not needed `ViewActions`
I had a look at other cases where we are using `ViewManagementActions.update`, to check if implementing the new `ViewActions.update` method would make sense, but could not find one.
Fixes #7244

Update current view title, summary and description on view edit

---

graylog2-web-interface/src/views/components/widgets/MessageList.jsx
graylog2-web-interface/src/views/components/widgets/MessageList.test.jsx

As described in #7204 the `MessageList` can display errors, but they don't get cleared after executing a new search.
This PR just resets the error state and adds a test, to check if errors are getting displayed correctly.

Clear MessageList error on search execution

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/Query.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/QueryTest.java
graylog2-web-interface/src/views/stores/GlobalOverrideStore.js

Prior to this change, the globaloverride for timerange was overriden by
the query builder for globaloverride. That way a globaloverride for
query and timerange did not apply the timerange of the override.
Also when disabling the timerange override in the gui the store did
set a plain javascript object instead of a GlobalOverride value class,
with that the Store could not change the timerange of the global
override anymore.
This change will use a common Globaloverride Builder for `hasTimerange`
and `hasQuery` that way the query does not override timerange.
Also when disabling the timerange in the GUI we now only unset the
timerange value of the Globaloverride.
Changed the global override in as many ways as possible.
Fixes #7236

Fix GlobalOverride behavior

---

graylog2-server/src/main/resources/swagger/lib/swagger.js

Bug: If an API endpoint returns an error the api browser becomes unfunctional with `ReferenceError: error is not defined`
If one or more API endpoints return error the API browser does not show any documentation for any of the endpoints or that an error occured with said api endpoints. This is because the JavaScript stops processing due to the reference error.
This is untested. However for the change at line 308 was indirectly verfied by breaking to it in a debugger and examining the objects.  As there is no statusText for the object in line 308 I'm making the assumption there's none for the response object in line 62 either.

Fix reference errors in swagger.js

---

graylog2-server/src/main/java/org/graylog/events/processor/DBEventProcessorStateService.java
graylog2-server/src/main/java/org/graylog2/database/MongoDBUpsertRetryer.java
graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypesService.java
graylog2-server/src/main/java/org/graylog2/system/processing/DBProcessingStatusService.java

This allows us to wrap upsert calls, which will
be retried once more if they produce a DuplicateKeyException.
Fixes #7258

Introduce MongoDBUpsertRetryer

---

graylog2-server/src/main/java/org/graylog2/contentpacks/facades/dashboardV1/EntityConverter.java

While working on https://github.com/Graylog2/graylog2-server/pull/7186
we forgot to include an important fix. Otherwise the server startup will fail with:
```
2020-01-24 16:49:24,408 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): Could not find a suitable constructor in org.graylog2.contentpacks.facades.dashboardV1.EntityConverter. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:
1) Could not find a suitable constructor in org.graylog2.contentpacks.facades.dashboardV1.EntityConverter. Classes must have either one (and only one) constructor annotated …
```

Fix server startup

---

UPGRADING.rst

We reimplemented the CSV export in the user interface, but in the `UPGRADING.rst` is still an entry regarding the removal. This PR removes the related entry.

Remove not needed CSV export info from upgrading doc

---

UPGRADING.rst
graylog2-web-interface/src/views/components/sidebar/SearchResultOverview.jsx
graylog2-web-interface/src/views/components/sidebar/SideBar.test.jsx

The message count, displayed in the sidebar, is currently not working as expected.
E.g. as described here: #6668
We decided to disable the message count, until we've implemented a working solution. The message count can still be displayed by adding a message count widget.

Remove search message count from sidebar

---

graylog2-web-interface/src/views/stores/GlobalOverrideStore.js

As described in #7269 the global time range configured for a dashboard, gets lost when executing the search with a query. This PR fixes the described behaviour, by using the right object key inside the `GlobalOverrideStore`
Fixes #7269

Avoid global override time range reset on dashboard search execution

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/searchtypes/ESMessageList.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/MessageList.java
graylog2-web-interface/src/views/components/widgets/MessageList.jsx
graylog2-web-interface/src/views/components/widgets/MessageList.test.jsx
graylog2-web-interface/src/views/logic/searchtypes/MessageListHandler.js

Prior to these changes using the `MessageList` widget pagination requested messages within a time range which relates to the query. In the context of a dashboard, where each widget has its own time range, this results in a wrong behaviour.
With this PR, the `MessageList` always relates to the effective time range of the related search type.
Fixes #7243

Use effective time range from related search type instead of query in MessageList

---

graylog2-server/src/main/java/org/graylog/events/contentpack/facade/NotificationFacade.java
graylog2-server/src/test/java/org/graylog/events/contentpack/facade/NotificationFacadeTest.java

Fixes issues:
- it's not possible to update Event Notification installed from Content
Pack on fresh GrayLog instance
- notifications doesn't work, server logs show:
ERROR: org.graylog.events.notifications.EventNotificationHandler - Couldnt find job definition for notification <5dfa2847b6730e001230c323>
- properly delete Event Notification with related resources 
#7044
- isolated unit test (`mvn -Dtest=NotificationFacadeTest test`)
- manually tested Content Pack installation on built image
Tests are far from perfect, but I was following pattens from `EventDefinitionFacade` and `EventDefinitionFacadeTest`, so hopefully they are acceptable. 
Closes #7044.

Bugfix proper Event Notification creation using Content Pack

---

graylog2-web-interface/src/views/components/common/EditableTitle.jsx

Before this change, when editing a widget title, updating it was only
triggered upon a form submit event (when pressing enter inside the
widget title input). This lead to confusing behavior as described in
#7266.
This change is now also triggering a change event when the input is
blurred.

Trigger changing widget title on blur.

---

graylog2-web-interface/src/components/lookup-tables/CacheForm.jsx
graylog2-web-interface/src/components/lookup-tables/DataAdapterForm.jsx

This PR fixes the form focus problem described in #7294 
I tried to solve this issue by only using autoFocus, but in the end saw the need for the current workaround.

Only set data adapters / cache form focus, when related type changes

---

graylog2-web-interface/src/views/components/DashboardSearchBar.jsx
graylog2-web-interface/src/views/components/QueryBar.jsx
graylog2-web-interface/src/views/components/QueryTabs.jsx
graylog2-web-interface/src/views/components/SearchBar.jsx
graylog2-web-interface/src/views/components/ViewActionsMenu.jsx

As described in https://github.com/Graylog2/graylog2-server/issues/7248 the white space visible at the bottom of the dashboard searchbar can be confusing:
Having a look at the search searchbar:
we've decided to unify the searchbars. This helps with the white space and the user does not have to get used to the different layout. One part of the restructuring is moving the dashboard actions into the searchbar.
In the last weeks we've already improved the searchbar actions, by implementing related icons. I tried to adopt this for the dashboard searchbar as well.
Dashboard searchbar after the changes:
Fixes https://github.com/Graylog2/graylog2-server/issues/7248

 Unify search and dashboard sidebar

---

graylog2-web-interface/src/views/pages/ShowViewPage.jsx
graylog2-web-interface/src/views/pages/ShowViewPage.test.jsx

Before this change, loading multiple searches consecutively, exporting a
search to a dashboard or saving a dashboard as a new one and navigating
back and forth in the browser history would not trigger reloading the
corresponding searches/dashboards.
This change is now implementing the required check which triggers
reloading a search/dashboard if the id of the current search/dashboard
in the URL changes.
Fixes #7298.
Fixes #7299.

Reload search/dashboard again if id props changes.

---

graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20190127111728_MigrateWidgetFormatSettings.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/ChartColorMapping.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/ChartColorSetting.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/WidgetFormattingSettings.java
graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20190127111728_MigrateWidgetFormatSettingsTest.java
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20190127111728_MigrateWidgetFormatSettings.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20190127111728_MigrateWidgetFormatSettings_withMultipleColorMappings.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20190127111728_MigrateWidgetFormatSettings_without_color_mapping.json
graylog2-web-interface/src/views/logic/aggregationbuilder/WidgetFormattingSettings.js

Prior to this change, the data structure to store
WidgetFormattingSettings did use the "user input" for storing a map.
But mongodb does not allow to store keys with dot in the map.
This change will change the data structure from a map to a list
of objects. That way mongodb does not need to store the keys.
Also add migration to fix existing color charts in mongodbs.
Fixes #7235 
1. Add dashboard with color chart containing a non IP keyname with dots and see that it
does not get saved. 
1. Remove dots from name
1. Run migration
1. Check that chart color still exists and add the dots back to the name which should now successfully be saved.

Change color chart from Map to List of Value Class 

---

graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/FieldChartConfig.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/QuickValuesConfig.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/QuickValuesHistogramConfig.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/SearchResultChartConfig.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/SearchResultCountConfig.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/StackedChartConfig.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/StackedSeries.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/StatsCountConfig.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/WorldMapConfig.java
graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/V20191125144500_MigrateDashboardsToViewsTest.java
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_superfluous_widget_attributes.json

Prior to this change, the dashboard migration was very strict concerning
unexpected properties in dashboard widgets. There are users reporting it
to fail because of those (e.g. an `interval` field in a `QUICKVALUES`
widget).
Therefore, this PR is relaving the widget deserialization classes and
ignores unknown properties. A test case containing all known widget
types with superfluous attributes has been added.

Ignore unknown legacy dashboard widget properties.

---

graylog2-web-interface/package.json
graylog2-web-interface/src/util/DocsHelper.js
graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
graylog2-web-interface/test/mock-Version.js

Due to the new version in the `package.json`, the docs url has changed and the `WidgetQueryControls` test failed.
We've decided to mock the functionality which causes the failing snapshot test/s.

Mock Version.js to avoid failing snaphot tests after version change

---

graylog2-web-interface/src/util/DocsHelper.js
graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap

As suggested by @kyleknighted we should use HTTPS for all our documentation links.
E.g. `http://docs.graylog.org/en/3.2/pages/queries.html` will be `https://docs.graylog.org/en/3.2/pages/queries.html`
We should merge https://github.com/Graylog2/graylog2-server/pull/7308 and rebase this branch first.

Use HTTPS for documentation links

---

UPGRADING.rst

Prior to this change, the feature concerning old dashboard in content
packs was fixed.
This change will remove the line which mentions the missing support.

Remove incorrect line from UPGRADING.rst

---

graylog2-web-interface/src/views/spec/CreateNewDashboard.test.jsx

The `CreateNewDashboard` integration test has proven to be unreliable
under certain conditions (most probably multiple `jest` runs happening
on CI hardware in parallel), leading to false negatives.
This change is increasing the jest timeout for this specific test suite,
hoping to reduce the number of false negatives when run under load.

Increasing jest timeout for integration test.

---

graylog2-web-interface/src/components/outputs/AssignOutputDropdown.jsx

When loading the stream output page, the dropdown for "Assign existing
Output" shows the first existing output as selected. When pressing the
button, an error had been generated because there wasn't an actual
selection.
This change is fixing the AssignOutputDropdown to show the placeholder
by default and disable the "Assign existing Output" button until a
selection has been made.

Fix default selection for stream output assignment

---

graylog2-server/src/main/java/org/graylog2/lookup/adapters/DnsLookupDataAdapter.java
graylog2-server/src/main/java/org/graylog2/lookup/adapters/dnslookup/DnsClient.java
graylog2-server/src/main/java/org/graylog2/shared/utilities/ExceptionUtils.java
graylog2-server/src/test/java/org/graylog2/lookup/adapters/dnslookup/DnsClientTest.java
graylog2-server/src/test/java/org/graylog2/shared/utilities/ExceptionUtilsTest.java

We cannot use "Future#sync()" to wait for the result of the DNS
resolver. This can block forever (until the server gets restarted)
when the DnsNameResolver and the netty event loop gets shut down while a
DNS request is running.
This happened on busy systems that do a lot of DNS lookups and the DNS
lookup data adapter gets restarted while DNS requests are running. (e.g.
by updating the data adapter's configuration)
It can get even worse when multiple processing threads try to lookup the
same hostname or IP address at the same time, using the same lookup
table. One thread is waiting for a response but never returns.
All other processing threads are blocking on the cache lock, waiting on
the other thread to return.
The solution is to not use "Future#sync()" and use "Future#get()" with a …

Fix blocking issue in DNS lookup data adapter

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchDomain.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/ViewPermissions.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/DashboardsResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/QualifyingViewsResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewSharingResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewParameterSummaryDTO.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/ViewPermissionsTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/QualifyingViewsResourceTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/views/QualifyingViewsServiceTest.java
graylog2-web-interface/src/components/users/RolesComponent.jsx
graylog2-web-interface/src/components/users/UserForm.jsx
graylog2-web-interface/src/views/components/ViewActionsMenu.jsx

Before this change, the user/role permissions editor (`System ->
Authentication -> Users`/`System -> Authentication -> Roles`) did show
legacy dashboards only. This prevented the user from managing
existing/adding new permissions of users for new, views-based
dashboards.
This change is now doing the following:
* Use the new `DashboardsStore` to list new, views-based dashboards
when managing user/roles permissions
* Check for `dashboards:read:<id>`/`dashboards:edit:<id>` permissions
when reading/updating dashboards/reading/execution search (and resolving
the views referencing them)
A migration of pre-existing permissions is not required, as the ids of
dashboards stay identical during their migration.

Show/use view-based dashboards in user/role permissions editor.

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchDomain.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/ViewPermissions.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/DashboardsResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/QualifyingViewsResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewSharingResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewParameterSummaryDTO.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/ViewPermissionsTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/QualifyingViewsResourceTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/views/QualifyingViewsServiceTest.java
graylog2-web-interface/src/components/users/RolesComponent.jsx
graylog2-web-interface/src/components/users/UserForm.jsx
graylog2-web-interface/src/views/components/ViewActionsMenu.jsx

Before this change, the user/role permissions editor (`System ->
Authentication -> Users`/`System -> Authentication -> Roles`) did show
legacy dashboards only. This prevented the user from managing
existing/adding new permissions of users for new, views-based
dashboards.
This change is now doing the following:
* Use the new `DashboardsStore` to list new, views-based dashboards
when managing user/roles permissions
* Check for `dashboards:read:<id>`/`dashboards:edit:<id>` permissions
when reading/updating dashboards/reading/execution search (and resolving
the views referencing them)
A migration of pre-existing permissions is not required, as the ids of
dashboards stay identical during their migration.

Show/use view-based dashboards in user/role permissions editor. (3.2)

---

graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/QuickValuesConfig.java
graylog2-server/src/main/java/org/graylog2/contentpacks/facades/dashboardV1/DashboardWidgetConverter.java
graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/WidgetConfig.java
graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/V20191125144500_MigrateDashboardsToViewsTest.java
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_missing_quickvalues_attributes.json

Under some circumstances, the `show_data_table` & `show_pie_chart`
attributes of legacy quick values widgets can be `null`, leading to NPEs
when migrating or installing legacy dashboards.
This PR is now handling the absence of these attributes. If they are
missing, they are handled the following way:
- `show_data_table` is `true` if `show_pie_chart` is missing or
`false` and `false` otherwise, ensuring that at least one of both is created
- `show_pie_charts` is `false` if missing
This logic is identical to the rendering logic of the legacy dashboard
code.
Fixes #7334.

Handling `null` attributes when migrating quickvalues widgets.

---

graylog2-web-interface/src/views/bindings.jsx
graylog2-web-interface/src/views/bindings.valueActions.test.jsx

Prior to this change, the `create extracotr` field action was only
enabled for string values. This lead to the problem that field
from type `text` and `string` (compound) could not be extracted even
though it would work perfectly fine.
This change will remove the check and allows extrator creation for all
field types.
Tested with: string, number and timestamp.

Allow *Create Extractor* for all types

---

graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/QuickValuesConfig.java
graylog2-server/src/main/java/org/graylog2/contentpacks/facades/dashboardV1/DashboardWidgetConverter.java
graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/WidgetConfig.java
graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/V20191125144500_MigrateDashboardsToViewsTest.java
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_missing_quickvalues_attributes.json

Under some circumstances, the `show_data_table` & `show_pie_chart`
attributes of legacy quick values widgets can be `null`, leading to NPEs
when migrating or installing legacy dashboards.
This PR is now handling the absence of these attributes. If they are
missing, they are handled the following way:
- `show_data_table` is `true` if `show_pie_chart` is missing or
`false` and `false` otherwise, ensuring that at least one of both is created
- `show_pie_charts` is `false` if missing
This logic is identical to the rendering logic of the legacy dashboard
code.
Fixes #7334.

Handling `null` attributes when migrating quickvalues widgets. (3.2)

---

graylog2-web-interface/src/views/bindings.jsx
graylog2-web-interface/src/views/bindings.valueActions.test.jsx

Prior to this change, the `create extracotr` field action was only
enabled for string values. This lead to the problem that field
from type `text` and `string` (compound) could not be extracted even
though it would work perfectly fine.
This change will remove the check and allows extrator creation for all
field types.
Tested with: string, number and timestamp.

Allow *Create Extractor* for all types (3.2)

---

graylog2-web-interface/src/components/systemjobs/SystemJobsComponent.jsx

The server may return in some circumstances an empty Map as response to `/api/cluster/jobs`, and that will break the UI. This PR guards against that situation by setting a default value to `reduce`.
Fixes #7329

Guard against empty cluster jobs response

---

graylog2-server/src/main/java/org/graylog/events/notifications/NotificationTestData.java
graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotification.java

When a HTTP event notification fails due to an URL Whitelist error, we now check if the failed event notification was a test-notification. If that's the case, the global system notification showing the whitelist error will be suppressed.
When an HTTP event notification is tested and the whitelist entered was not whitelisted, a sticky system notification would show up, indicating the whitelist error. This system notification was however only meant to be triggered during the execution of "real" alerts.
Quick manual test via the frontend.

Suppress system notification for whitelist error from test alert

---

graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java

Sometimes the message processing doesn't leave us
with a valid DateTime Object at this point.
Fixes #7364
Creating a pipeline rule which sets the timestamp as string:
`set_field("timestamp", to_string($message.timestamp));`

Partly revert timestamp based gl2_message_ids (#7290)

---

graylog2-web-interface/src/views/components/datatable/DataTable.css

As described in https://github.com/Graylog2/graylog2-server/issues/7344 the vertical scrolling in data table widgets does not work with safari. This PR is fixing the problem.
Fixes #7344
Tested the vertical and horizontal data table scrolling in Safari, Chrome and Firefox. Also tested the behaviour inside the aggregation builder.

Fix vertical data table widget scrolling for safari

---

graylog2-web-interface/src/views/components/datatable/DataTable.css

Backport PR for https://github.com/Graylog2/graylog2-server/pull/7352
As described in #7344 the vertical scrolling in data table widgets does not work with safari. This PR is fixing the problem.

Fix vertical data table scrolling for safari (Backport of #7352 for 3.2)

---

graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/V20191203120602_MigrateSavedSearchesToViews.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/AbsoluteTimeRangeQuery.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/KeywordTimeRangeQuery.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/Query.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/RelativeTimeRangeQuery.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/MessagesWidget.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/MessagesWidgetConfig.java
graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/V20191203120602_MigrateSavedSearchesToViewsTest.java
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_absolute-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_keyword-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_relative-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_with_empty_fields-expected_searches.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_with_empty_fields-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_with_empty_fields.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_with_missing_fields-expected_searches.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_with_missing_fields-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_with_missing_fields.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_with_stream-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_without_message_row-expected_searches.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_without_message_row-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_without_message_row.json

Before this change, when a saved search was missing a `fields` property
(which is defining a set of fields being shown in the message list), the
migration would fail.
This change is now making `fields` optional and uses a default set of
fields if absent.
In addition it does:
- explicitly include the `timestamp` field in the field selection
- conditionally select the message row for the newly created message
widget depending on the presence of the `message` field in the original
saved search
Fixes #7362.
Manually creating a saved search with no `fields` property, migrating
it, checking the result.
Adding test cases that reproduce some corner cases.

Handle null `fields` when migrating saved searches.

---

graylog2-server/src/test/java/org/graylog/events/notifications/NotificationResourceHandlerTest.java

Fixes a test which is broken since #7350
Didn't notice because the maven build wasn't executing the tests (see #7376 )

Fix broken event notification test.

---

graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/V20191203120602_MigrateSavedSearchesToViews.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/AbsoluteTimeRangeQuery.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/KeywordTimeRangeQuery.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/Query.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/RelativeTimeRangeQuery.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/MessagesWidget.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/view/MessagesWidgetConfig.java
graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/V20191203120602_MigrateSavedSearchesToViewsTest.java
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_absolute-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_keyword-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_relative-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_with_empty_fields-expected_searches.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_with_empty_fields-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_with_empty_fields.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_with_missing_fields-expected_searches.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_with_missing_fields-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_with_missing_fields.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_with_stream-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_without_message_row-expected_searches.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_without_message_row-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_without_message_row.json

Before this change, when a saved search was missing a `fields` property
(which is defining a set of fields being shown in the message list), the
migration would fail.
This change is now making `fields` optional and uses a default set of
fields if absent.
In addition it does:
- explicitly include the `timestamp` field in the field selection
- conditionally select the message row for the newly created message
widget depending on the presence of the `message` field in the original
saved search
Fixes #7362.
Manually creating a saved search with no `fields` property, migrating
it, checking the result.
Adding test cases that reproduce some corner cases.

Handle null `fields` when migrating saved searches. (3.2)

---

graylog-project-parent/pom.xml
graylog2-server/pom.xml
pom.xml

It looks like this prevents our existing JUnit 4 tests from running correctly. Until we figured out the issue, we revert the change.
Reverts Graylog2/graylog2-server#7319

Revert "Add JUnit 5 with vintage engine alongside JUnit 4"

---

graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/AbsoluteTimeRangeQuery.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/KeywordTimeRangeQuery.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/RelativeTimeRangeQuery.java
graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/V20191203120602_MigrateSavedSearchesToViewsTest.java
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_absolute_with_interval_field-expected_searches.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_absolute_with_interval_field-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_absolute_with_interval_field.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_keyword_with_interval_field-expected_searches.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_keyword_with_interval_field-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_keyword_with_interval_field.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_relative_with_interval_field-expected_searches.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_relative_with_interval_field-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_relative_with_interval_field.json

For saved searches that have been created after changing the interval of
the message histogram on the search page, the migration turning them
into views-based searches fails, due to the unexpected `interval` field.
This PR is ignoring a potentially existing `interval` field, because we
do not rely on manual interval selection anymore. In most of the cases
the interval was selected, because the time range was bigger or smaller
than the default. In 3.2 we offer an automatic interval size selection,
which yields better results (especially when increasing the time range)
than manually selecting one.

Ignoring `interval` field when migrating saved searches.

---

graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/AbsoluteTimeRangeQuery.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/KeywordTimeRangeQuery.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/savedsearch/RelativeTimeRangeQuery.java
graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/V20191203120602_MigrateSavedSearchesToViewsTest.java
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_absolute_with_interval_field-expected_searches.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_absolute_with_interval_field-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_absolute_with_interval_field.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_keyword_with_interval_field-expected_searches.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_keyword_with_interval_field-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_keyword_with_interval_field.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_relative_with_interval_field-expected_searches.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_relative_with_interval_field-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191203120602_MigrateSavedSearchesToViewsSupport/sample_saved_search_relative_with_interval_field.json

For saved searches that have been created after changing the interval of
the message histogram on the search page, the migration turning them
into views-based searches fails, due to the unexpected `interval` field.
This PR is ignoring a potentially existing `interval` field, because we
do not rely on manual interval selection anymore. In most of the cases
the interval was selected, because the time range was bigger or smaller
than the default. In 3.2 we offer an automatic interval size selection,
which yields better results (especially when increasing the time range)
than manually selecting one.

Ignoring `interval` field when migrating saved searches. (3.2)

---

graylog2-web-interface/yarn.lock

fsevents does not provide binaries for node 12 and the package also failed
to build even if the dependencies for node-gyp appeared to be installed.
Fortunately they released a new 1.2.11 version simplifying the module's
compilation.
This change only affects the development server under macOS, so it should be safe to merge.

Upgrade to fsevents v1.2.11 to support node 12

---

graylog2-web-interface/src/views/spec/CreateNewDashboard.test.jsx

When run in parallel, the `CreateNewDashboard` test has turned out to be
flaky. A further attempt to increase the jest timeout for the test suite
did not fundamentally improve the situation.
This change is increasing the timeout for the individual element finders
in the test from the default of 4500ms to 15000ms, hoping to make the
test more reliable.

Increasing timeout for element finders in `CreateNewDashboard` test.

---

graylog2-server/src/main/java/org/graylog2/indexer/retention/strategies/AbstractIndexCountBasedRetentionStrategy.java
graylog2-server/src/test/java/org/graylog2/indexer/retention/strategies/AbstractIndexCountBasedRetentionStrategyTest.java

While testing another archiving change, I noticed that we start archiving from the newest to the oldest index, which isn't the best way to handle things.

Start retention from the oldest index, not the newest

---

graylog2-server/src/main/java/org/graylog2/bootstrap/ServerBootstrap.java
graylog2-server/src/main/java/org/graylog2/configuration/PathConfiguration.java

At runtime, Netty copies its tcnative shared library to `io.netty.native.workdir` which defaults to /tmp.
Some users mount /tmp with a nonexec option, which disallows executable code in /tmp.
Therefore use graylogs `data_dir`/libnative as a new default workdir for netty.
Furthermore, disable the deleteLibAfterLoading feature, since this
confuses the needrestart(1) utility on some Linux distributions. (e.g. Debian)
Fixes #5762

Use graylog data dir for netty tcnative libraries

---

graylog2-server/src/main/java/org/graylog2/bootstrap/ServerBootstrap.java
graylog2-server/src/main/java/org/graylog2/configuration/PathConfiguration.java

At runtime, Netty copies its tcnative shared library to `io.netty.native.workdir` which defaults to /tmp.
Some users mount /tmp with a nonexec option, which disallows executable code in /tmp.
Therefore use graylogs `data_dir`/libnative as a new default workdir for netty.
Furthermore, disable the deleteLibAfterLoading feature, since this
confuses the needrestart(1) utility on some Linux distributions. (e.g. Debian)
Fixes #5762
(cherry picked from commit b334aefd6d2400b13c3e55de464f0537481fe0df)

Use graylog data dir for netty tcnative libraries (#7359)

---

graylog2-server/src/main/java/org/graylog2/system/urlwhitelist/RegexWhitelistEntry.java
graylog2-server/src/test/java/org/graylog2/system/urlwhitelist/UrlWhitelistTest.java

Regex whitelist entries don't compile regexes lazily anymore.
We don't want to rely entirely on the frontend to make sure that only valid expressions are entered. Previously we would accept invalid expressions and end up with a broken whitelist because the pattern would be compiled on demand.
Manual test by sending a regex whitelist entry with `http://localhost/${` as its value via the API.

Guard against illegal regexes in whitelist

---

graylog2-web-interface/src/views/components/queries/QueryTitle.jsx
graylog2-web-interface/src/views/components/queries/QueryTitle.test.jsx
graylog2-web-interface/src/views/logic/views/ViewState.js
graylog2-web-interface/src/views/logic/views/ViewState.test.js

Before this change, duplicating a query tab containing no widgets or
where no widget had been renamed or given a title before, would fail.
This happened because during query tab duplication the map of widget
titles was extracted from a nested titles structure, which - at this
point - does not contain a widget titles map.
In addition, a second error occurs after successfully duplicating a
query tab: the `QueryTitle` component tries to switch to the new query
tab by using the id of the new query supplied by the promise returned by
the duplication action. Unfortunately the duplication action does not
return the query id. Nonetheless, the new query tab is selected, because
of the `ViewStore#createQuery` action being called.
This change is doing two things:a
* Fall back to an empty map if the …

Fix duplicating of query tab if no widget has been renamed.

---

graylog2-web-interface/src/views/components/queries/QueryTitle.jsx
graylog2-web-interface/src/views/components/queries/QueryTitle.test.jsx
graylog2-web-interface/src/views/logic/views/ViewState.js
graylog2-web-interface/src/views/logic/views/ViewState.test.js

Backport of #7397 for 3.2
Original Description:
Before this change, duplicating a query tab containing no widgets or
where no widget had been renamed or given a title before, would fail.
This happened because during query tab duplication the map of widget
titles was extracted from a nested titles structure, which - at this
point - does not contain a widget titles map.
In addition, a second error occurs after successfully duplicating a
query tab: the `QueryTitle` component tries to switch to the new query
tab by using the id of the new query supplied by the promise returned by
the duplication action. Unfortunately the duplication action does not
return the query id. Nonetheless, the new query tab is selected, because
of the `ViewStore#createQuery` action being called.
This change is doing …

Fix duplicating of query tab if no widget has been renamed. (Backport of #7397 for 3.2)

---

graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.js
graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.test.jsx
graylog2-web-interface/src/views/pages/ExtendedSearchPage.test.jsx

Opening the search page, stream search page or loaded search page, results in multiple browser history entries (e.g. `/search` and `/search?q=&rangetype=relative&relative=300`) for the same page. With these changes we are just appending the default query params when needed, but still support using the browser navigation to switch between different states of the current search (e.g. after changing time range).

Improve search url sync, by avoiding unnecessary entries in browser history (3.2)

---

graylog2-web-interface/styleguide.config.js

With https://github.com/Graylog2/graylog2-server/pull/7338 we remove the rickshaw package. This PR removes the related, not needed styleguide css import.

Remove rickshaw css import from styleguide config

---

graylog2-web-interface/src/pages/EditContentPackPage.jsx

Prior to this change, createNewVersionFromRev was called on undefined
because contentPackRevisions was assumed to be in the state after
ContentPacksActions.get was called, but it was not.
This change will use the parameter from then action of the get function
which contains the contentPackRevisions.
Fixes #6690

Fix call of createNewVersionFromRev on undefined

---

graylog2-web-interface/package.json
graylog2-web-interface/yarn.lock

Bumps `react-ace-builds` from `v7.2.4` to `v7.3.1`, therefore updating
`ace-builds` from `v1.4.4` to `v1.4.8`.
Changelogs:
- `react-ace-builds`: https://github.com/manubb/react-ace-builds/blob/local/CHANGELOG.md
- `ace-builds`: https://github.com/ajaxorg/ace-builds/blob/v1.4.8/ChangeLog.txt

Updating `react-ace-builds` to v7.3.1.

---

graylog2-web-interface/src/views/components/messagelist/MessageTableEntry.jsx
graylog2-web-interface/src/views/components/widgets/MessageTable.jsx
graylog2-web-interface/src/views/components/widgets/MessageTable.test.jsx

Prior to this PR, several users reported that under some circumstances
the message list widget raises an exception. Following the stack trace,
it looks like field types might not be available (being `undefined`) and
the `find` method called on it nevertheless, resulting in an exception.
This might be because of either a race condition or a missing/empty API
response.
I was unable to reproduce the error in my development setup while using
the product, even not by delaying the fields types store's response.
Nevertheless, I was able to reproduce it in the added test case, by
deliberately providing an `undefined` `fields` prop, allowing me to fix
the related code lines.
Fixes #7365.

Handle message fields types not being available (on time).

---

graylog2-server/src/main/java/org/graylog2/plugin/DocsHelper.java

The details of the fix,is described in the issue below:
[354](https://github.com/Graylog2/graylog-plugin-integrations/issues/354)
The ipfix link is broken while navigating the links, system -> nodes -> details -> Available Inputs -> documentation.
fix the broken documentation link for IPFIX.
-  tested this locally and is not working in my local, as the version is pointing to 3.3, if I manually
change the version to 3.2 it works.
- needs to be backported to 3.2

fix the link to ipfix docs.

---

graylog2-web-interface/src/pages/EditContentPackPage.jsx

Prior to this change, createNewVersionFromRev was called on undefined
because contentPackRevisions was assumed to be in the state after
ContentPacksActions.get was called, but it was not.
This change will use the parameter from then action of the get function
which contains the contentPackRevisions.
Fixes #6690
(cherry picked from commit 650c729fa2506da95eadcb7e1a7e71530ce02b30)

Fix call of createNewVersionFromRev on undefined (#7442)

---

graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/viewwidgets/Series.java
graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/viewwidgets/SeriesTest.java

The extraction of field names from series widgets' function assumed that field names could contain only alphanumeric characters and underscores.
Actually they may contain `-` and `@` as well.
Fixes #7439

Fix field name extraction in dashboard migration

---

graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/viewwidgets/Series.java
graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/viewwidgets/SeriesTest.java

The extraction of field names from series widgets' function
expression assumed that field names could contain only
alphanumeric characters and underscores.
Actually they may contain `-` and `@` as well.
(cherry picked from commit 27269f2dfe36c12bd88adad661e613660eeb5cca)

Fix field name extraction in dashboard migration (#7448)

---

graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewSharingResourceTest.java

This PR fixes #7472 
The fix uses containsExactlyInAnyOrder instead of containsExactly so that the test is more stable.
For detailed analysis, please refer to #7472

Fix issue 7472 by using containsExactlyInAnyOrder instead of containsExactly

---

graylog2-web-interface/src/components/configurations/decorators/StreamSelect.jsx
graylog2-web-interface/src/views/components/EmptyValue.jsx
graylog2-web-interface/src/views/components/aggregationbuilder/AggregationControls.jsx
graylog2-web-interface/src/views/components/horizontalspacer/HorizontalSpacer.jsx
graylog2-web-interface/src/views/components/sidebar/NavItem.styles.jsx
graylog2-web-interface/src/views/components/sidebar/Sidebar.styles.jsx
graylog2-web-interface/src/views/components/visualizations/number/AutoFontSizer.jsx
graylog2-web-interface/src/views/components/visualizations/number/NumberVisualization.jsx
graylog2-web-interface/src/views/components/visualizations/number/Trend.jsx
graylog2-web-interface/src/views/components/widgets/UnknownWidget.jsx

This PR unifies the type definitions for all styled components by using the StyledComponent type from styled-components instead of React.ComponentType or React.AbstractComponent.

Unify styled-component component type definitions

---

graylog2-web-interface/package.json
graylog2-web-interface/yarn.lock

Fixes security issue https://snyk.io/vuln/SNYK-JS-URLPARSE-543307, which
only affects our development environment.
Upgrading `url-parse` also required upgrading `sockjs-client`, which again
is only used in development.

Bump url-parse to 1.4.7

---

graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/QuickValuesConfig.java
graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/V20191125144500_MigrateDashboardsToViewsTest.java
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_minimal_quickvalues_widget-expected_searches.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_minimal_quickvalues_widget-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/ops_dashboards-expected_searches.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/ops_dashboards-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/quickvalues_widget_with_sort_order-expected_searches.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/quickvalues_widget_with_sort_order-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/quickvalues_widget_with_sort_order.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/sample_dashboard-expected_searches.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/sample_dashboard-expected_views.json

Before this PR, when migrating a quick values widget from a legacydashboard, the sort order is not generated correctly. This has no effect if "Top values" had been selected, but quick values widgets with "Bottom values" selected work in descending order afterwards. This was related to the sort order which is generated using the field name of the quick values widget instead of the `count()` function.
This PR is changing this, so created widgets have the correct sort order.
*Needs to be backported to 3.2.*
Fixes #7476.

Use function instead of field for sort when migrating widgets.

---

graylog2-server/src/main/java/org/graylog2/security/MongoDbSession.java

Cast the value to a Number instead of a Long and then use ".longValue()"
to avoid the exception.
This mostly happened when the session timeout was -1 and MongoDB
returned an integer instead of a long for that.
It has been broken for a long time but it never showed up because the
ExecutorServiceSessionValidationScheduler in shiro didn't catch
exceptions and had no uncaught exception handler.
Since shiro 1.5.0 this has been fixed and we see the ClassCastException
in the graylog logs. (we are still running shiro 1.4.0 in master, I noticed that in #7466)

Fix ClassCastException in MongoDbSession#getTimeout()

---

graylog2-web-interface/package.json
graylog2-web-interface/yarn.lock

This change is updating `plotly.js` from `1.48.1` to `1.52.2`.
- [Release Notes](https://github.com/plotly/plotly.js/releases/tag/v1.52.2)
- [Changelog](https://github.com/plotly/plotly.js/blob/v1.52.2/CHANGELOG.md)
- [Commits](https://github.com/plotly/plotly.js/compare/v1.48.1...v1.52.2)

Update plotly.js to `1.52.2`.

---

graylog2-web-interface/src/views/components/messagelist/MessageTableEntry.jsx
graylog2-web-interface/src/views/components/widgets/MessageTable.jsx
graylog2-web-interface/src/views/components/widgets/MessageTable.test.jsx

Backport of https://github.com/Graylog2/graylog2-server/pull/7419 for 3.2
Prior to this PR, several users reported that under some circumstances
the message list widget raises an exception. Following the stack trace,
it looks like field types might not be available (being `undefined`) and
the `find` method called on it nevertheless, resulting in an exception.
This might be because of either a race condition or a missing/empty API
response.
I was unable to reproduce the error in my development setup while using
the product, even not by delaying the fields types store's response.
Nevertheless, I was able to reproduce it in the added test case, by
deliberately providing an `undefined` `fields` prop, allowing me to fix
the related code lines.
Fixes #7365.

Handle message fields types not being available (on time). (Backport of #7419 for 3.2)

---

graylog2-web-interface/package.json
graylog2-web-interface/yarn.lock

Backport of https://github.com/Graylog2/graylog2-server/pull/7484 for 3.2
This change is updating `plotly.js` from `1.48.1` to `1.52.2`.
- [Release Notes](https://github.com/plotly/plotly.js/releases/tag/v1.52.2)
- [Changelog](https://github.com/plotly/plotly.js/blob/v1.52.2/CHANGELOG.md)
- [Commits](https://github.com/plotly/plotly.js/compare/v1.48.1...v1.52.2)

Update plotly.js to `1.52.2` (Backport of #7484 for 3.2)

---

graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/QuickValuesConfig.java
graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/V20191125144500_MigrateDashboardsToViewsTest.java
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_minimal_quickvalues_widget-expected_searches.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_minimal_quickvalues_widget-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/ops_dashboards-expected_searches.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/ops_dashboards-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/quickvalues_widget_with_sort_order-expected_searches.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/quickvalues_widget_with_sort_order-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/quickvalues_widget_with_sort_order.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/sample_dashboard-expected_searches.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/sample_dashboard-expected_views.json

* Adding test case for correct migration of sorting (top/bottom values).
* Use series function instead of field name for sort.
* Adapting pre-existing test fixtures.
(cherry picked from commit 59b50d9759319be91563dd811e2726fcc6e8cef8)

Use function instead of field for sort when migrating widgets. (#7478) (3.2)

---

graylog2-web-interface/src/views/bindings.enterpriseWidgets.test.jsx
graylog2-web-interface/src/views/bindings.jsx

As described in https://github.com/Graylog2/graylog2-server/issues/7349 the data table is not fully visible in reports.
The reason is the visualization config in `bindings` returns `true` for the prop `needsControlledHeight`. With this PR we are checking the widget type to return `false` if the widget is a data table.
Please have a look at the related PR in the enterprise repo. After merging these changes, we need to create a backport PR for the next bugfix release.
Fixes #7349

Display full height of data tables in reports

---

graylog2-web-interface/src/views/bindings.enterpriseWidgets.test.jsx
graylog2-web-interface/src/views/bindings.jsx

As described in https://github.com/Graylog2/graylog2-server/issues/7349 the data table is not fully visible in reports.
The reason is the visualization config in `bindings` returns `true` for the prop `needsControlledHeight`. With this PR we are checking the widget type to return `false` if the widget is a data table.
Please have a look at the related PR in the enterprise repo. 
Fixes #7349

Display full height of data tables in reports (3.2)

---

graylog2-web-interface/src/views/components/searchbar/completions/FieldNameCompletion.js
graylog2-web-interface/src/views/components/searchbar/completions/FieldNameCompletion.test.jsx

The legacy search suffixed field names in the query input's
auto-completion with a colon, as most users would want to write a value
next, after completing the field name. The new search does not do this
yet.
This change is suffixing all field names suggested for field completion
with a colon.
*Needs to be backported to `3.2`.*
Fixes #7408.

Suffixing field names in auto completion with colon (':').

---

graylog2-web-interface/src/views/components/searchbar/completions/FieldNameCompletion.js
graylog2-web-interface/src/views/components/searchbar/completions/FieldNameCompletion.test.jsx

Backport of https://github.com/Graylog2/graylog2-server/pull/7489 for 3.2
The legacy search suffixed field names in the query input's
auto-completion with a colon, as most users would want to write a value
next, after completing the field name. The new search does not do this
yet.
This change is suffixing all field names suggested for field completion
with a colon.
Fixes #7408.

Suffixing field names in auto completion with colon (':'). (Backport of #7489 for 3.2)

---

graylog2-server/src/main/java/org/graylog2/security/ldap/LdapSettingsImpl.java

When setting a role as additional default group and deleting it while
it is still in the configuration, the backend will fail to resolve the
role name and return a `null` instead. This null element is stored in
MongoDB (and also returned from the API), which causes issues in some
circumstances, like logging in.
Fixes #7431

Filter out null roles in ldap settings

---

graylog2-web-interface/package.json
graylog2-web-interface/yarn.lock

This change is updating `react-plotly.js` from `v2.3.0` to `v2.4.0`.
- [Commits](https://github.com/plotly/react-plotly.js/compare/2.3.0...v2.4.0)

Updating react-plotly.js to v2.4.0.

---

graylog2-web-interface/src/routing/Routes.jsx
graylog2-web-interface/src/views/bindings.jsx
graylog2-web-interface/src/views/bindings.routes.test.jsx

As reported in #7447, the stream search page is not accessible when running the web interface behind a reverse proxy that adds a path prefix. This is related to the plugin route registration, which uses a route helper (`Routes.stream_search(':streamId')`) to ensure path consistency, which qualifies each path returned with the globally configured application path prefix. Unfortunately, all plugin route's are qualified once again before `react-router`'s consumption.
This PR is now exporting unqualified route from the global `Routes` file, which can be used for plugin routes to prevent double qualification.
*Requires a backport for 3.2.*
Fixes #7447.
[Caddy](https://caddyserver.com) has been used, configured as a reverse proxy for the Graylog server with a path prefix of `/gl2`, with a …

Prevent double qualification of route path for stream search page.

---

graylog2-server/src/main/java/org/graylog2/security/ldap/LdapSettingsImpl.java

When setting a role as additional default group and deleting it while
it is still in the configuration, the backend will fail to resolve the
role name and return a `null` instead. This null element is stored in
MongoDB (and also returned from the API), which causes issues in some
circumstances.
Fixes #7431
(cherry picked from commit 4a7ec6c577d0af2eac532c0b3e36048ad57faa6d)

Filter out null roles in ldap settings (#7468)

---

graylog2-server/src/main/java/org/graylog2/users/RoleServiceImpl.java

This avoids running into conflicts when multiple nodes
are bootstrapped simultaneously.

Use upsert to create admin role

---

graylog2-web-interface/styleguide.config.js

Remove two sections from styleguide:
- Inputs: currently contains Graylog Inputs components, which are not common and should probably not be reused in other parts of the application
- Visualizations: After 3.2 this section is almost empty, so either we include new visualizations or we remove the section. I decided on the second option

Clean up styleguide sections

---

graylog2-web-interface/src/views/components/widgets/MessageTable.jsx
graylog2-web-interface/src/views/components/widgets/MessageTable.test.jsx

As described in #6808, the field order in the message list table head can be wrong. This PR fixes the problem by using only an `Immutable.OrderedSet`.
This is the backport PR for 3.2
Fixes #6808.

Fix field order in MessageTable head (3.2)

---

graylog2-web-interface/src/routing/Routes.jsx
graylog2-web-interface/src/views/bindings.jsx
graylog2-web-interface/src/views/bindings.routes.test.jsx

Backport of #7475 for 3.2
As reported in #7447, the stream search page is not accessible when running the web interface behind a reverse proxy that adds a path prefix. This is related to the plugin route registration, which uses a route helper (`Routes.stream_search(':streamId')`) to ensure path consistency, which qualifies each path returned with the globally configured application path prefix. Unfortunately, all plugin route's are qualified once again before `react-router`'s consumption.
This PR is now exporting unqualified route from the global `Routes` file, which can be used for plugin routes to prevent double qualification.
Fixes #7447.
[Caddy](https://caddyserver.com) has been used, configured as a reverse proxy for the Graylog server with a path prefix of `/gl2`, with a …

Prevent double qualification of route path for stream search page. (Backport of #7475 for 3.2)

---

graylog2-web-interface/test/console-warnings-fail-tests.js
graylog2-web-interface/test/console-warnings-fail-tests.test.js
graylog2-web-interface/test/setup-jest.jsx

In preparation of updating to React 16.12.0, the `console.error/warn`
handlers for our tests are improved in this PR to make it easier to add
additional patterns for deprecation warnings that should not be handled
as test failures.

Improve logging for tests, include future react deprecation warning.

---

graylog2-server/src/main/java/org/graylog2/plugin/KafkaJournalConfiguration.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/JournalResource.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/responses/JournalSummaryResponse.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/responses/KafkaJournalConfigurationSummary.java

This fixes the "/api/cluster/<node-id>/journal" API endpoint to not
throw an error anymore.
In #7359 we introduced the PathConfiguration#getNativeLibDir() method
and this broke deserialization of the JournalSummaryResponse because
"#getNativeLibDir" was automatically serialized but couldn't be
deserialized.
This change introduces a new KafkaJournalConfigurationSummary value that
we can serialize and deserialize in the API. Using this also avoids
exposing new fields from Pathconfiguration or KafkaJournalConfiguration
automatically.
This also removes the constructor and jackson annotations in
KafkaJournalConfiguration beacuse they are not needed anymore.
Fixes #7521

Don't expose KafkaJournalConfiguration via the HTTP API

---

graylog2-web-interface/src/pages/LoginPage.jsx

This PR adds grid styling for smaller resolutions to the login form.
Before (<= 990px)
After:

Add login form grid styling for smaller resolutions

---

graylog2-web-interface/src/components/common/JSONValueInput.jsx
graylog2-web-interface/src/components/common/TimeUnitInput.jsx
graylog2-web-interface/src/views/components/aggregationbuilder/pivottypes/TimeUnitTimeHistogramPivot.jsx

At some point in the ThemeProvider build I was getting build errors without the .type in place. It appears those were resolved but type was not removed.
Change componentClass={InputGroup.Button.type} to componentClass={InputGroup.Button}

Remove type from componentClass

---

graylog2-web-interface/yarn.lock

Due to updates of transitive dependencies (from `graylog-web-plugin` & `eslint-config-graylog` packages), the yarn lockfile needs a separate update.
Refs: Graylog2/graylog2-server#7356
Refs: Graylog2/graylog2-server#7355
Refs: Graylog2/graylog2-server#7435
Refs: Graylog2/graylog2-server#7440
Refs: Graylog2/graylog2-server#6813
Refs: Graylog2/graylog2-server#6814

Updating yarn lockfile due to dependency updates.

---

graylog2-web-interface/src/views/components/WidgetQueryControls.test.jsx
graylog2-web-interface/src/views/components/aggregationbuilder/AggregationControls.test.jsx
graylog2-web-interface/src/views/components/dashboard/BigDisplayModeConfiguration.test.jsx
graylog2-web-interface/src/views/components/widgets/WidgetErrorBoundary.test.jsx

The import of `@testing-library/jest-dom` and `@testing-library/jest-dom/extend-expect` is no longer required for a specific test, because the import is now part of `wrappedTestingLibrary.jsx`

Remove not needed @testing-library/jest-dom imports

---

graylog2-web-interface/src/views/components/aggregationbuilder/AggregationControls.jsx
graylog2-web-interface/src/views/components/aggregationbuilder/AggregationControls.test.jsx
graylog2-web-interface/src/views/components/aggregationbuilder/PivotSelect.jsx
graylog2-web-interface/src/views/components/aggregationbuilder/PivotSelect.test.jsx
graylog2-web-interface/src/views/components/datatable/Headers.test.jsx
graylog2-web-interface/src/views/logic/fieldtypes/FieldTypeFor.js
graylog2-web-interface/src/views/logic/fieldtypes/FieldTypeFor.test.js
graylog2-web-interface/src/views/logic/fieldtypes/InferTypeForSeries.js
graylog2-web-interface/src/views/logic/fieldtypes/InferTypeForSeries.test.js
graylog2-web-interface/src/views/stores/FieldTypesStore.js

*This PR requires a backport to `3.2`*
Before this change, there were a couple of places where the absence of
field types (when they have not been fetched from the backend on time or
the backend periodical did not finish its first run yet) caused
exceptions to be thrown in places of the code where full initialization
of field types was expected. Some of these were addressed in #7419, but
obviously not all, according to user reports.
This PR is trying to systematically approach this by having created a
state in the `FieldTypesStore` that provokes these exceptions, then
fixing them in all of the related components. In addition, systematic
improvements to the `FieldTypesStore` were made:
* removing shadowing of `this.all` through the action _and_ the state
variable
* initializing the state …

Handling absence of field types in search components.

---

graylog2-web-interface/src/views/components/aggregationbuilder/AggregationControls.jsx
graylog2-web-interface/src/views/components/aggregationbuilder/AggregationControls.test.jsx
graylog2-web-interface/src/views/components/aggregationbuilder/PivotSelect.jsx
graylog2-web-interface/src/views/components/aggregationbuilder/PivotSelect.test.jsx
graylog2-web-interface/src/views/components/datatable/Headers.test.jsx
graylog2-web-interface/src/views/logic/fieldtypes/FieldTypeFor.js
graylog2-web-interface/src/views/logic/fieldtypes/FieldTypeFor.test.js
graylog2-web-interface/src/views/logic/fieldtypes/InferTypeForSeries.js
graylog2-web-interface/src/views/logic/fieldtypes/InferTypeForSeries.test.js
graylog2-web-interface/src/views/stores/FieldTypesStore.js

Backport of #7538 for 3.2
*This PR requires a backport to `3.2`*
Before this change, there were a couple of places where the absence of
field types (when they have not been fetched from the backend on time or
the backend periodical did not finish its first run yet) caused
exceptions to be thrown in places of the code where full initialization
of field types was expected. Some of these were addressed in #7419, but
obviously not all, according to user reports.
This PR is trying to systematically approach this by having created a
state in the `FieldTypesStore` that provokes these exceptions, then
fixing them in all of the related components. In addition, systematic
improvements to the `FieldTypesStore` were made:
* removing shadowing of `this.all` through the action _and_ the state
variable …

Handling absence of field types in search components. (Backport of #7538 for 3.2)

---

graylog2-server/src/test/java/org/graylog2/plugin/lookup/LookupCacheKeyTest.java

For background information, please refer to #7594 
The fix uses containsExactlyInAnyOrder instead of containsExactly so that the test is more stable.

Use containsExactlyInAnyOrder for better tests

---

graylog2-web-interface/package.json
graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
graylog2-web-interface/yarn.lock

We need to pin `jsdom` with the version 15.2.1, because we had some trouble with a `jsdom` bug in a specific test case, with an older version.
When using the attribute step for an input, the form method `.checkValidity()` always failed.

Pin jsdom version 15.2.1

---

graylog2-web-interface/src/views/components/searchbar/completions/FieldNameCompletion.js
graylog2-web-interface/src/views/components/searchbar/completions/FieldNameCompletion.test.jsx

*Should be backported to `3.2`.*
Before this change, the `_exists_` query operator was not suggested in the autocompletion of the query input in the new search. This change is adding it and completes any value following it with the set of fields.
Fixes #7441.
Refs #6909.

Autosuggest `_exists_` operator in query input of search/dashboard page.

---

graylog2-web-interface/src/views/components/datatable/DataTable.jsx
graylog2-web-interface/src/views/components/datatable/DataTable.test.jsx

*Needs to be backported to `3.2`.*
Before `3.2`, search types did not had a `name` attribute. In 5ee5115 an
optional name attribute defined by the caller was introduced. Views
created before this, did not contain it and search results are scoped
with the search key id instead. This is handled by all visualizations
but the data table.
This leads to views containing data tables not rendering properly in
`3.2`, if they had been created before `3.2`, as reported in #7565.
This change is now adding support and tests for this for the data table.
Fixes #7565.

Support legacy (pre 3.2) search result in data table visualization.

---

graylog2-web-interface/src/views/components/DebugOverlay.jsx
graylog2-web-interface/src/views/components/ViewActionsMenu.jsx
graylog2-web-interface/src/views/components/ViewActionsMenu.test.jsx
graylog2-web-interface/src/views/components/queries/QueryTitleEditModal.jsx
graylog2-web-interface/src/views/components/views/ShareViewModal.jsx
graylog2-web-interface/src/views/components/views/ShareViewModal.test.jsx
graylog2-web-interface/src/views/components/views/ViewPropertiesModal.jsx
graylog2-web-interface/src/views/stores/SearchStore.js

As described in https://github.com/Graylog2/graylog2-server/issues/7229 we are using different modal components. This PR::
- implements `BootstrapModalWrapper` for `DebugOverlay`
- implements `BootstrapModalForm` for `QueryEditTitle`
- implements `BootstrapModalConfirm` for `ShareViewModal`
- Adds test base and modal tests for `ViewActionsMenu`
At first I only worked with references (https://github.com/Graylog2/graylog2-server/commit/5939a1075091dff856e328428ffcbcd471d535c5) but directly mounting the modal components had some disadvantages. E.g. the `ShareViewModal` would do some not needed api requests, when opening any dashboard. Only mounting the modal component when they are visible has manly one disadvantage, the fade out animation will not be shown.

Implement bootstrap modal wrapper components for search related modals

---

graylog2-web-interface/src/views/components/visualizations/ChartData.js
graylog2-web-interface/src/views/components/visualizations/__tests__/ChartData.test.js
graylog2-web-interface/src/views/components/visualizations/__tests__/ChartData.test.withNullAndUndefined.json
graylog2-web-interface/src/views/components/visualizations/__tests__/ChartData.test.withZeros.json

With this PR, chart widgets display pivots with a value of zero. It looks like the one line I've adjusted is the only needed change.
I had a look at all different chart types with different compositions and could not find / think of a case were this could result in an unintended visualization.
Only when all values of e.g. a line chart are zero, the line is. hardly visible:
I thought about starting the y-axis with a negative value, but I would not adjust the current behaviour only for this case. What do you think?

Show pivots with a value of zero in chart widgets

---

graylog2-web-interface/src/components/search/SurroundingSearchButton.jsx
graylog2-web-interface/src/components/search/SurroundingSearchButton.test.jsx
graylog2-web-interface/src/views/components/WidgetGrid.jsx
graylog2-web-interface/src/views/components/contexts/DrilldownContext.jsx
graylog2-web-interface/src/views/components/contexts/DrilldownContextProvider.jsx
graylog2-web-interface/src/views/components/contexts/DrilldownContextProvider.test.jsx
graylog2-web-interface/src/views/components/messagelist/MessageActions.test.jsx
graylog2-web-interface/src/views/hooks/BindSearchParamsFromQuery.js
graylog2-web-interface/src/views/hooks/BindSearchParamsFromQuery.test.js
graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.js
graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.test.jsx
graylog2-web-interface/src/views/logic/queries/Query.js
graylog2-web-interface/src/views/logic/queries/Query.test.jsx
graylog2-web-interface/test/helpers/mocking/index.js

**Note: Requires #7612 to be merged before. Needs a backport for `3.2`.**
This change is adding support for passing a list of stream ids in a search URL which is used to preselect streams for the newly generated search.
In addition, it uses the currently selected streams to generate URLs in the surrounding search button, so after clicking one of its options, the newly opened search also contains the previously selected streams.
Infrastructurally, this PR introduces a `DrilldownContext`, which supplies the current query, timerange & streams to a widget and its actions. It comes with a `DrilldownContextProvider` component, which consumes the related stores to provide an accurate drilldown context, regardless if the current view is a search or a dashboard or if the global override is used on …

Support passing streams for new search in URL.

---

graylog2-server/src/main/java/org/graylog/events/processor/aggregation/PivotAggregationSearch.java
graylog2-server/src/test/java/org/graylog/events/processor/aggregation/PivotAggregationSearchTest.java

We cannot run a query with an empty stream list, because it will
be executed against all known indices in elastic search
and never yield a result.
Thus, like we already do in MoreSearch: If no streams are provided,
use all streams instead.
Fixes #7619

Expand empty streams to default streams for Aggregation Alerting

---

graylog2-web-interface/src/views/bindings.jsx

This PR will rename the field action `Aggregate` to `Show top values`. 
After replacing the old search with the new view [a](https://community.graylog.org/t/rollback-3-2-3-1/13745/3) [lot](https://community.graylog.org/t/rollback-3-2-3-1/13745/7) [of](https://community.graylog.org/t/rollback-3-2-3-1/13745/24) [users](https://community.graylog.org/t/rollback-3-2-3-1/13745/39) could not find the Quick Values
anymore which were not represented by the `Aggregate` button.
But the term ``Aggregate`` is rather confusing as well as quick values. So we decided to rename
the button to `Show top values`. This better represents what will happen.
Open a search and click on a field action and there on `Show top values`.
Fixes #7483

Rename 'Aggregate' field action to 'Show top values'

---

graylog2-server/src/main/java/org/graylog/events/processor/aggregation/PivotAggregationSearch.java
graylog2-server/src/test/java/org/graylog/events/processor/aggregation/PivotAggregationSearchTest.java

We cannot run a query with an empty stream list, because it will
be executed against all known indices in elastic search
and never yield a result.
Thus, like we already do in MoreSearch: If no streams are provided,
use all streams instead.
Fixes #7619

Expand empty streams to default streams for Aggregation Alerting 3.2

---

graylog2-web-interface/src/views/components/visualizations/ChartData.js
graylog2-web-interface/src/views/components/visualizations/__tests__/ChartData.test.js
graylog2-web-interface/src/views/components/visualizations/__tests__/ChartData.test.withNullAndUndefined.json
graylog2-web-interface/src/views/components/visualizations/__tests__/ChartData.test.withZeros.json

Backport of #7605 for 3.2
With this PR, chart widgets display pivots with a value of zero. It looks like the one line I've adjusted is the only needed change.
I had a look at all different chart types with different compositions and could not find / think of a case were this could result in an unintended visualization.

Show pivots with a value of zero in chart widgets (Backport of #7605 for 3.2)

---

graylog2-web-interface/src/views/pages/StreamSearchPage.test.jsx
graylog2-web-interface/src/views/spec/CreateNewDashboard.test.jsx

As described in https://github.com/Graylog2/graylog2-server/issues/7580 some frontend tests are throwing a warning.
This PR is getting rid of the `act()` warnings by combining the related tests with another meaningful test case, which have the state change in mind.
Here is an interesting article, I've read about the topic: https://kentcdodds.com/blog/write-fewer-longer-tests
This PR also fixes the fetch error, by mocking the part which is responsible for the fetch.
Fixes #7580.

Fix act() warning and fetch error in frontend tests

---

graylog2-server/src/main/java/org/graylog2/configuration/PathConfiguration.java

This fixes the "/api/cluster/journal" API endpoint to not throw an error anymore.
In #7359 we introduced the PathConfiguration#getNativeLibDir() method
and this broke deserialization of the JournalSummaryResponse because
"#getNativeLibDir" was automatically serialized but couldn't be
deserialized.
@JsonIgnore this attribute.
Fixes #7521
refs https://github.com/Graylog2/graylog2-server/pull/7526

Fix cluster journal statistic api endpoint

---

graylog2-web-interface/src/components/search/SurroundingSearchButton.jsx
graylog2-web-interface/src/components/search/SurroundingSearchButton.test.jsx
graylog2-web-interface/src/views/components/WidgetGrid.jsx
graylog2-web-interface/src/views/components/contexts/DrilldownContext.jsx
graylog2-web-interface/src/views/components/contexts/DrilldownContextProvider.jsx
graylog2-web-interface/src/views/components/contexts/DrilldownContextProvider.test.jsx
graylog2-web-interface/src/views/hooks/BindSearchParamsFromQuery.js
graylog2-web-interface/src/views/hooks/BindSearchParamsFromQuery.test.js
graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.js
graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.test.jsx
graylog2-web-interface/src/views/logic/queries/Query.js
graylog2-web-interface/src/views/logic/queries/Query.test.jsx
graylog2-web-interface/test/helpers/mocking/index.js

**Note: Requires #7612 to be merged before. Needs a backport for `3.2`.**
This change is adding support for passing a list of stream ids in a search URL which is used to preselect streams for the newly generated search.
In addition, it uses the currently selected streams to generate URLs in the surrounding search button, so after clicking one of its options, the newly opened search also contains the previously selected streams.
Infrastructurally, this PR introduces a `DrilldownContext`, which supplies the current query, timerange & streams to a widget and its actions. It comes with a `DrilldownContextProvider` component, which consumes the related stores to provide an accurate drilldown context, regardless if the current view is a search or a dashboard or if the global override is used on …

Support passing streams for new search in URL (3.2)

---

graylog2-web-interface/src/components/graylog/Popover.jsx
graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkForm.test.jsx.snap

Wrapping Popover with GraylogThemeProvider
It was discovered that `Popover.jsx:7 Uncaught TypeError: Cannot read property 'primary' of undefined` began after #7067 merged

Popover Theme TypeError

---

graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/ESGeneratedQueryContext.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackend.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/FieldTypesLookup.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/searchtypes/ESMessageList.java
graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypesService.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendErrorHandlingTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendGeneratedRequestTestBase.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendUsingCorrectIndicesTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/FieldTypesLookupTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/searchtypes/ESMessageListTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/engine/QueryPlanTest.java
graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypesServiceTest.java
graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/MongoFieldTypeLookupTest.java

**Note: Requires backport to `3.2`.**
Before this change, no `unmapped_type` option was passed to Elasticsearch, when a field was used for sorting retrieved messages. This has the effect that when a field that is being sorted on is not present in all indices, an exception is thrown from ES.
This change is doing these things to address this:
* Providing a map of field types to all search types through the `ESGeneratedQueryContext`, scoped to the effective streams of this search type
* Using field types to look up the type of all fields used sorting
* Adding the `unmapped_type` option to a sort in the `ESMessageList` class, using the retrieved field type for the respective field
Fixes #6490.
(cherry picked from commit ce377d5031f60c6d90aa3d0e42a76ebd4a13594a)
Resolved Conflicts:
- …

Using field type of sort field for unmapped type in message list. (3.2)

---

graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/FieldTypesLookupTest.java
graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkForm.test.jsx.snap

This PR is doing to things to fix the build:
1. In #7569, a PR was merged with a missing license header. Due to its
dependency on a PR in a different repo, it was merged with a red build. This PR is adding the missing license header so the build passes again.
2. In #7074 not all changes of the PR in snapshots were addresses. This PR is updating missed snapshots.

Adding missing license header for `FieldTypesLookup` test/Updating snapshots.

---

graylog2-server/src/main/java/org/graylog2/rest/models/system/sessions/responses/DefaultSessionResponse.java
graylog2-server/src/main/java/org/graylog2/rest/models/system/sessions/responses/DefaultSessionResponseFactory.java
graylog2-server/src/main/java/org/graylog2/rest/models/system/sessions/responses/SessionResponseFactory.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/SessionsResource.java
graylog2-server/src/main/java/org/graylog2/shared/security/SecurityBindings.java

Allow plugins to customize the session creation response, being able to include further information for the user.
The reasoning behind this is to make it easier for the frontend to work with external authentication systems, which may need additional user information available in the server.

Make session response creation pluggable

---

graylog2-web-interface/src/views/pages/NewDashboardPage.test.jsx
graylog2-web-interface/src/views/pages/StreamSearchPage.test.jsx

Follow-up PR for #7630.
As described in #7580 some frontend tests are throwing a warning. The `NewDashboardPage.test.jsx` also throwed an `act()` warning, because the component changed after the test has been finished. I fixed this issue by summarizing the related test cases.

Fix act() warning in NewDashboardPage test by summarizing test case

---

graylog2-web-interface/src/components/search/SearchLink.js
graylog2-web-interface/src/components/search/SearchLink.test.jsx
graylog2-web-interface/src/components/search/SurroundingSearchButton.jsx
graylog2-web-interface/src/components/search/SurroundingSearchButton.test.jsx
graylog2-web-interface/src/views/components/widgets/ReplaySearchButton.jsx
graylog2-web-interface/src/views/components/widgets/ReplaySearchButton.test.jsx
graylog2-web-interface/src/views/components/widgets/Widget.jsx

This change is reimplementing the "Replay search" button for dashboard widgets. When pressed, it creates a new search (opening in a browser tab, so the users does not lose the current context), recreating the context of the widget (query, time range, streams), allowing the user to see the documents going in to the widget's results and/or starting a drilldown.
In addition to what is contained in the backport (#7648), this PR also contains extracting the generation of search URLs to a separate class (`SearchLink`), which is reused in the surrounding search button.
Fixes #7372.

Reimplement "Replay search" button for dashboard widgets.

---

graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
graylog2-web-interface/src/views/pages/ExtendedSearchPage.test.jsx

**Note: This needs a backport to `3.2`.**
Before this change, the `ExtendedSearchPage` component did not register
callbacks for `ViewActions.search.completed` & `SearchActions.refresh`
if the search refresh condition returned `false` on the initial attempt.
The impact of this is that e.g. when the enterprise plugin is installed
and a search page is opened with an initial query that has unregistered
parameters, the callbacks are never registered and therefore from this
point future updates to the search or refresh requests are not handled.
This change is registering callbacks in any case, regardless of the
search refresh condition results.

Registering callbacks even if search refresh condition hooks fail.

---

graylog2-server/src/main/java/org/graylog2/inputs/transports/KafkaTransport.java
graylog2-server/src/main/java/org/graylog2/plugin/configuration/ConfigurationRequest.java
graylog2-server/src/main/java/org/graylog2/plugin/configuration/fields/AbstractConfigurationField.java
graylog2-server/src/main/java/org/graylog2/plugin/configuration/fields/BooleanField.java
graylog2-server/src/main/java/org/graylog2/plugin/configuration/fields/ConfigurationField.java
graylog2-server/src/main/java/org/graylog2/plugin/configuration/fields/TextField.java
graylog2-server/src/main/resources/log4j2.xml
graylog2-web-interface/src/components/configurationforms/ConfigurationForm.jsx

Newer Kafka versions are supported by using the new high level consumer API.
Lucky for us, support for the new API is already included in our currently used Kafka client library. This means we can avoid updating it, and still be compatible with our on-disk journal.
Instead of creating a new Transport class, use a legacy switch to keep supporting older Kafka versions.
Most of this was spearheaded by Muralidhar Basani in #4770
Thank you very much! :-)
To configure the new Kafka client, a list of one or more Kafka brokers needs to be provided.
The legacy one needs to connect to Zookeeper.
Introduce a custom properties field, so users can tweak advanced settings or setup TLS.
Refs https://github.com/Graylog2/graylog2-server/pull/5088
Refs …

Add support for high level Kafka consumer mode (3.2)

---

graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
graylog2-web-interface/src/views/pages/ExtendedSearchPage.test.jsx

Before this change, the `ExtendedSearchPage` component did not register
callbacks for `ViewActions.search.completed` & `SearchActions.refresh`
if the search refresh condition returned `false` on the initial attempt.
The impact of this is that e.g. when the enterprise plugin is installed
and a search page is opened with an initial query that has unregistered
parameters, the callbacks are never registered and therefore from this
point future updates to the search or refresh requests are not handled.
This change is registering callbacks in any case, regardless of the
search refresh condition results.

Registering callbacks even if search refresh condition hooks fail. (3.2)

---

graylog2-web-interface/src/views/bindings.jsx

This PR will rename the field action `Aggregate` to `Show top values`. 
After replacing the old search with the new view [a](https://community.graylog.org/t/rollback-3-2-3-1/13745/3) [lot](https://community.graylog.org/t/rollback-3-2-3-1/13745/7) [of](https://community.graylog.org/t/rollback-3-2-3-1/13745/24) [users](https://community.graylog.org/t/rollback-3-2-3-1/13745/39) could not find the Quick Values
anymore which were not represented by the `Aggregate` button.
But the term ``Aggregate`` is rather confusing as well as quick values. So we decided to rename
the button to `Show top values`. This better represents what will happen.
Open a search and click on a field action and there on `Show top values`.
Fixes #7483

Rename 'Aggregate' field action to 'Show top values' (3.2)

---

graylog2-web-interface/src/views/components/widgets/ReplaySearchButton.jsx
graylog2-web-interface/src/views/components/widgets/ReplaySearchButton.test.jsx
graylog2-web-interface/src/views/components/widgets/Widget.jsx

This change is reimplementing the "Replay search" button for dashboard widgets. When pressed, it creates a new search (opening in a browser tab, so the users does not lose the current context), recreating the context of the widget (query, time range, streams), allowing the user to see the documents going in to the widget's results and/or starting a drilldown.
Fixes #7372.

Reimplement "Replay search" button for dashboard widgets. (3.2)

---

graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.jsx
graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.test.jsx

This PR adds the option in the bookmark controls to share the current search with other users, if the current search has already been saved and if the current user is permitted to edit the current search (the user is either the owner or owns the required permissions).

Adding option to share current search to bookmark controls.

---

graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.jsx
graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.test.jsx

This PR adds the option in the bookmark controls to share the current search with other users, if the current search has already been saved and if the current user is permitted to edit the current search (the user is either the owner or owns the required permissions).

Adding option to share current search to bookmark controls. (3.2)

---

graylog2-server/src/test/java/org/graylog2/shared/bindings/providers/OkHttpClientProviderTest.java

The following tests have proven to be unreliable and caused repeated
build failures, therefore this PR disables them:
- `testFailingProxyConnectionWithoutAuthentication`
- `testSuccessfulProxyConnectionWithoutAuthentication`
Refs: #7643

Ignoring unreliable `OkHttpClientProvider` tests for now.

---

graylog2-server/src/main/java/org/graylog2/utilities/IPSubnetConverter.java

For background information, please refer to #7542 
This PR aims to solve the problem about #7542 
The fix is the use LinkedHashSet instead of HashSet. In this way, the iteration order will not be different any more and the code will be more stable.
The code after the fix has been tested already.

Use LinkedHashSet for a deterministic order

---

graylog2-web-interface/src/util/PermissionsMixin.js

Before this change, `PermissionsMixin` had a default export that was an
object containing two functions. A lot of consumers actually used named
imports for these functions, which is against ES module conventions,
resulting in webpack warnings since we do emit proper modules during
bundling.
This change is now fixing up the exports of `PermissionsMixin` by adding
two named exports for the used functions, but also keeping the default
export intact for consumers importing it.

Making `PermissionsMixin` proper ES6 module.

---

graylog2-web-interface/src/components/bootstrap/BootstrapModalForm.jsx
graylog2-web-interface/src/views/components/dashboard/BigDisplayModeConfiguration.jsx
graylog2-web-interface/src/views/components/dashboard/BigDisplayModeConfiguration.test.jsx

This PR is based on https://github.com/Graylog2/graylog2-server/pull/7574. The mentioned PR pins the `jsdom` version, otherwise the `BigDisplayModeConfiguration.test.jsx` would fail.
As described in #7229 we should unify the different modal implementations. This PR implements the `BootstrapModalForm` for the `BigDisplayModeConfiguration`
This PR is follow-up of: https://github.com/Graylog2/graylog2-server/pull/7571

Implement bootstrap modal form for big display mode configuration modal

---

graylog2-web-interface/src/components/common/Spinner.jsx
graylog2-web-interface/src/components/common/Spinner.test.jsx
graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstallEntityList.test.jsx.snap

With https://github.com/Graylog2/graylog2-server/pull/7539 we removed the `...rest` parameter usage for the spinner component. After working with the current implementation I prefer the dynamic `...rest` parameter usage.
I forgot e.g. about the `className` prop and now adjusting the spinner style with `styled(Spinner)` is not working anymore. This problem is visible when using the pagination of a message list, currently the spinner beside the widget header has no margin.

Reimplement props rest parameter usage for loading spinner component 

---

graylog2-web-interface/src/components/common/DataTable.jsx
graylog2-web-interface/src/components/common/DataTable.test.jsx

To fix issue #5965, we moved some code calculating the effective rows
into `componentDidUpdate`. This unfortunately has the effect that when
we receive new rows in the props, we may try to render an unexisting
row once, before updating the list that is kept in the component's
state, causing #7544.
To avoid that situation, this commit will avoid using `filteredRows`
when the `DataTable` doesn't have any `filterKeys`, that is, when we
don't display a filter. In summary:
- `DataTable` without filter: use rows coming from the props instead of
syncing them in the component state
- `DataTable` with filter: filter takes care of updating the
`filteredRows` state key, but `DataTable` filters out any keys that are
not in `rows`
Fixes #7544

Keep DataTable rows up-to-date

---

graylog2-web-interface/src/views/actions/SearchActions.js
graylog2-web-interface/src/views/components/widgets/MessageList.jsx
graylog2-web-interface/src/views/components/widgets/MessageList.test.jsx
graylog2-web-interface/src/views/stores/SearchStore.js

**Note: Needs a backport to `3.2`.**
As described in https://github.com/Graylog2/graylog2-server/issues/7680 a message list widget with an own search query does not consider the dashboard search query filter when using the widget pagination.
With this PR we are considering the dashboard filter search query on every search re-execution. A search re-execution currently only happens when using the message list pagination.
Fixes #7680
And also fixes #7665

Consider current dashboard query filter and defined parameters when using message list pagination

---

graylog2-web-interface/src/components/ldap/LdapComponent.jsx
graylog2-web-interface/src/components/ldap/LdapGroupsComponent.jsx
graylog2-web-interface/src/components/ldap/TestLdapLogin.jsx

In the LDAP group mapping page, display groups having a mapping configured, regardless if they match the current group configuration or not. This let users remove previously configured mappings if they ever changed their group configuration.
Additionally, add a reminder in the LDAP configuration page to review group mapping after changes in the group configuration are made.
Fixes #7502

Display all LDAP mapped groups

---

graylog2-web-interface/src/components/common/Delayed.jsx
graylog2-web-interface/src/components/common/Delayed.test.jsx
graylog2-web-interface/src/components/common/LoadingIndicator.jsx
graylog2-web-interface/src/components/common/Spinner.jsx
graylog2-web-interface/src/components/common/Spinner.test.jsx
graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstallEntityList.test.jsx.snap
graylog2-web-interface/src/views/components/SearchBar.test.jsx
graylog2-web-interface/src/views/components/SearchResult.test.jsx
graylog2-web-interface/src/views/pages/NewDashboardPage.test.jsx
graylog2-web-interface/src/views/pages/NewSearchPage.test.jsx
graylog2-web-interface/src/views/pages/StreamSearchPage.test.jsx

Before this change, PR #7539 introduced a delay for the `Spinner`
component. This works where only this one is used, but had the effect
that the `LoadingIndicator` component was shown before the `Spinner`
inside is.
This PR is extracting a shared `Delayed` component, which is rendering
its children after the `delay` (in ms) has passed, defaulting to 200ms.
This component is used by `Spinner` and `LoadingIndicator`. The latter
is passing a `delay` of `0` to `Spinner` to avoid delaying rendering
twice.

Making loading indicator on search show up delayed.

---

graylog2-web-interface/src/views/bindings.fieldActions.test.jsx
graylog2-web-interface/src/views/bindings.jsx
graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
graylog2-web-interface/src/views/pages/ExtendedSearchPage.test.jsx

**Note: This PR requires a backport for 3.2**
As described in https://github.com/Graylog2/graylog2-server/issues/7508 field actions like "Show top values / aggregate" are enabled, even when the field is part of the list "UI analysis disabled for fields", which can be configured in System/Configurations.
With these changes we are simply checking if a field is part of the "analysis disabled fields" list, when determining if a field action should be enabled.
Please note, beside the mentioned "Show top values / aggregate" field action I've also added the check for the "Statistics" field action.
We need to merge the related enterprise PR first to avoid the failing test.
Fixes: #7508

Disable "Show top value" and "Statistics" field actions when field analysis is disabled

---

graylog2-web-interface/src/components/ldap/LdapComponent.jsx
graylog2-web-interface/src/components/ldap/LdapGroupsComponent.jsx
graylog2-web-interface/src/components/ldap/TestLdapLogin.jsx

Backport of #7513:
>In the LDAP group mapping page, display groups having a mapping configured, regardless if they match the current group configuration or not. This let users remove previously configured mappings if they ever changed their group configuration.
>
>Additionally, add a reminder in the LDAP configuration page to review group mapping after changes in the group configuration are made.
>
>Fixes #7502

Display all LDAP mapped groups (#7513)

---

graylog2-web-interface/src/views/bindings.fieldActions.test.jsx
graylog2-web-interface/src/views/bindings.jsx
graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
graylog2-web-interface/src/views/pages/ExtendedSearchPage.test.jsx

Backport of #7685 for 3.2
As described in https://github.com/Graylog2/graylog2-server/issues/7508 field actions like "Show top values / aggregate" are enabled, even when the field is part of the list "UI analysis disabled for fields", which can be configured in System/Configurations.
With these changes we are simply checking if a field is part of the "analysis disabled fields" list, when determining if a field action should be enabled.
Please note, beside the mentioned "Show top values / aggregate" field action I've also added the check for the "Statistics" field action.
We need to merge the related enterprise PR first to avoid the failing test.
Fixes: #7508

Disable "Show top value" and "Statistics" field actions when field analysis is disabled (Backport of #7685 for 3.2)

---

graylog2-web-interface/src/components/common/DataTable.jsx
graylog2-web-interface/src/components/common/DataTable.test.jsx

Backport of #7657 for 3.2
> To fix issue #5965, we moved some code calculating the effective rows
into `componentDidUpdate`. This unfortunately has the effect that when
we receive new rows in the props, we may try to render an unexisting
row once, before updating the list that is kept in the component's
state, causing #7544.
>
> To avoid that situation, this commit will avoid using `filteredRows`
when the `DataTable` doesn't have any `filterKeys`, that is, when we
don't display a filter. In summary:
>
>- `DataTable` without filter: use rows coming from the props instead of
syncing them in the component state
>- `DataTable` with filter: filter takes care of updating the
`filteredRows` state key, but `DataTable` filters out any keys that are
not in `rows`
>
>Fixes #7544

Keep DataTable rows up-to-date (#7657)

---

graylog2-web-interface/src/views/components/OverlayDropdown.jsx

As described here: https://github.com/Graylog2/graylog2-server/pull/7631#pullrequestreview-369469482 the overlay dropdown placement can be wrong. This happens when you:
1. Have a widget on the right side of the search page grid
2. Use the context menu
3. Move the widget to the left side
4. Use the context menu again.
This PR fixes the problem by resetting the placement, when the opposite placement is no longer suitable.
**I will create backport for 3.2 once this PR got merged**

Reset dropdown overlay placement, when previously defined opposite placement is no longer suitable

---

graylog2-web-interface/src/components/common/SelectPopover.jsx

Before this change, Sidecar administration change was showing error due to propTypes on Popover inside SelectPopover. Which was used to filter SelectPopover to filter props to be passed to Popover. With these change we are explicitly passing the relevant props to Popover.

Explicitly pass props to Popover in SelectPopover

---

graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.js
graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.test.jsx

**Note: This needs a backport to `3.2`.**
Before this change, if the URL contains a set of streams, but the stream filters changes these to be empty, the `syncWithQueryParameters` function did not remove the `streams` parameter from the URL, but left it intact.
This lead to the last stream showing up again after removing it, because it is still part of the URL and will be added again by `bindSearchParamsFromQuery`. This is described in #7717.
The current PR changes `syncWithQueryParameters` to remove the `streams` query parameter from the URL if the set of current streams is empty.
Fixes #7717.

Remove `streams` parameter from URL if list of streams becomes empty.

---

graylog2-web-interface/src/views/components/OverlayDropdown.jsx

Backport of #7658 for 3.2 
As described here: https://github.com/Graylog2/graylog2-server/pull/7631#pullrequestreview-369469482 the overlay dropdown placement can be wrong. This happens when you:
1. Have a widget on the right side of the search page grid
2. Use the context menu
3. Move the widget to the left side
4. Use the context menu again.
This PR fixes the problem by resetting the placement, when the opposite placement is no longer suitable.
**I will create backport for 3.2 once this PR got merged**

Reset overlay dropdown placement (Backport of #7658 for 3.2)

---

graylog2-web-interface/src/pages/ConfigurationsPage.jsx

Adds `loaded` state wrapper around configuration panel
Renders single `Spinner` until all the configuration options are ready
Configurations panels were suffering from race conditions and very often fail to load.

Add loaded state to Configurations page before rendering

---

graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.js
graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.test.jsx

Before this change, if the URL contains a set of streams, but the stream filters changes these to be empty, the `syncWithQueryParameters` function did not remove the `streams` parameter from the URL, but left it intact.
This lead to the last stream showing up again after removing it, because it is still part of the URL and will be added again by `bindSearchParamsFromQuery`. This is described in #7717.
The current PR changes `syncWithQueryParameters` to remove the `streams` query parameter from the URL if the set of current streams is empty.
Fixes #7717.

Remove `streams` parameter from URL if list of streams becomes empty. (3.2)

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackend.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/IndexLookup.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendErrorHandlingTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendGeneratedRequestTestBase.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendSearchTypeOverridesTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendSearchTypesWithStreamsOverridesTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendTestBase.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchBackendUsingCorrectIndicesTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/IndexLookupTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/engine/QueryPlanTest.java

Previously the lookup of indices for streams and time range was done
in `ElasticsearchBackend` by loading indices, streams, and then finding
matches. It was impossible to reuse this logic elsewhere.
Furthermore this made `ElasticsearchBackend` harder to test, because
a lot of setup was required to make sure that proper index ranges and
streams are loaded during the test.
The corresponding change in the enterprise plugin can be found here: https://github.com/Graylog2/graylog-plugin-enterprise/pull/1498
Note that the Jenkins builds for both PRs will be red, because of this dependency. Both PRs should be merged at the same time.
- Extracts that logic into a separate class `IndexLookup`
- Simplifies tests for `ElasticsearchBackend` accordingly
- Adds tests for `IndexLookup`
- reuse the index …

Extract IndexLookup from ElasticsearchBackend

---

graylog2-web-interface/packages/graylog-web-plugin/package.json
graylog2-web-interface/yarn.lock

This fixes the following error when running "npm install" in
graylog-web-plugin:
```
error: [BABEL] graylog2-web-interface/packages/graylog-web-plugin/src/PluginManifest.js:
Could not find plugin "proposal-numeric-separator". Ensure there is an
entry in ./available-plugins.js for it.
```
Related PR in babel: https://github.com/babel/babel/pull/11201
Fixes #7731

Update babel to 7.8.7 graylog-web-plugin to fix a dependency issue

---

pom.xml

Also bump netty-tcnative-boringssl-static to 2.0.29.
Changelogs:
- https://netty.io/news/2020/02/28/4-1-46-Final.html
- https://netty.io/news/2020/03/09/4-1-47-Final.html
- https://netty.io/news/2020/03/17/4-1-48-Final.html

Update to netty-4.1.48

---

graylog2-web-interface/src/views/logic/views/ViewTransformer.js
graylog2-web-interface/src/views/logic/views/ViewTransformer.search.fixture.json
graylog2-web-interface/src/views/logic/views/ViewTransformer.test.js
graylog2-web-interface/src/views/logic/views/__snapshots__/ViewTransformer.test.js.snap

**Please note: This PR needs a backport for 3.2**
As described in #7732 we are currently not removing the `query_string` from the search queries when exporting a search to a dashboard. This can result in a not visible but invoked search query.
This is maybe also the reason for the following issue: https://github.com/Graylog2/graylog2-server/issues/7701
We still need to write a migration to remove the `query_string` from already exported searches. 
Fixes: #7732

Remove query_string from queries when exporting search to dashboard

---

graylog2-web-interface/src/components/common/SelectPopover.jsx

Use arrow functions to bind methods to `this` in ES class component.
After converting the component in an ES class, some methods were not
binding `this` as expected, causing issues when those methods were
called outside of React's component lifecycle methods.
Fixes #7406

Fix clearing collector configuration

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/MessageList.java

**Note: This PR needs a backport to `3.2`.**
Before this change, the `sort` option for a message list search type was not persisted. This lead to sorting configuration having no effect when storing a search and executing it, only for the synchronous endpoint.
Fixes #7758.

Persist message list search type's sort option.

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/MessageList.java

**This is the backport of #7759 for `3.2`**
Before this change, the `sort` option for a message list search type was not persisted. This lead to sorting configuration having no effect when storing a search and executing it, only for the synchronous endpoint.
Fixes #7758.

Persist message list search type's sort option. (Backport of #7759 for 3.2)

---

graylog2-web-interface/packages/eslint-config-graylog/index.js
graylog2-web-interface/packages/eslint-config-graylog/package.json
graylog2-web-interface/yarn.lock

Please have a look at the changelog for a detailed overview of the important changes: https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/CHANGELOG.md
There are a few rules we may want to discuss:
* prop spreading will no longer be allowed. (I disabled this rule, have a look at the PR comments for a detailed explanation)
* `Object.assign` will be converted to a destructuring assignment. So far I had no problems.
Other changes are:
* `.find(variable => {})` will be `.find((variable) => {})`. Currently `const foo = bar => {}` will already be transformed to `const foo = (bar) => {}`
* `<React.Fragments>` will be `<>`
* PropTypes need to be declared outside the class body
* State initialization needs to be part of the constructor

Update eslint-config-airbnb from 17.1.1 to 18.1.0

---

graylog2-web-interface/src/components/layout/AppContentGrid.jsx
graylog2-web-interface/src/components/layout/AppContentGrid.test.jsx
graylog2-web-interface/src/routing/AppWithoutSearchBar.jsx
graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx

This PR extracts the default app content (bootstrap) grid into a separate component, which can be used e.g.  for the extended search page search area.
The main advantage is, we can adjust the related layout styling , like the default padding, in one place.

Create separate component for the default app content grid

---

graylog2-web-interface/src/views/components/visualizations/GenericPlot.jsx
graylog2-web-interface/src/views/components/visualizations/XYPlot.jsx
graylog2-web-interface/src/views/components/visualizations/__tests__/XYPlot.test.jsx
graylog2-web-interface/src/views/components/visualizations/area/AreaVisualization.jsx
graylog2-web-interface/src/views/components/visualizations/area/__tests__/AreaVisualization.test.jsx
graylog2-web-interface/src/views/components/visualizations/bar/BarVisualization.jsx
graylog2-web-interface/src/views/components/visualizations/heatmap/HeatmapVisualization.jsx
graylog2-web-interface/src/views/components/visualizations/heatmap/__tests__/HeatmapVisualization.test.jsx
graylog2-web-interface/src/views/components/visualizations/line/LineVisualization.jsx
graylog2-web-interface/src/views/components/visualizations/scatter/ScatterVisualization.jsx

There are a few cases where a chart legend is overlapping the x-axis labels.
You can sometimes see this behaviour on the main search page:
I had an extensive look at the available plotly layout settings and could not find a perfectly dynamic solution. In the end I've added a small manual calculation, to create more dynamic layout and reduce the problematic cases to a minimum. This will e.g. fix the problem, visible in the above screenshot.

Improve widget legend positioning

---

graylog2-web-interface/packages/eslint-config-graylog/index.js

With https://github.com/Graylog2/graylog2-server/pull/7586 we've updated the airbnb ESlint config.
One new newly introduced rule is the `react/static-property-placement`. 
The rule enforces that e.g. static attributes like prop types needs to be assigned outside of the class body.
This PR is disabling the rule, because it is has no real benefit and can be obstructive.
There is also a problem in with flow, when `contextType` is getting assigned outside of the class body.

Disable ESlint rule react/static-property-placement

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewSharingResource.java

Before this change, a `POST` to `/views/{id}/share` did not check if the
supplied view sharing configuration in the body is present. This lead
to a NPE further down the stack when persisting the view sharing.
This change now adds the required annotations for the body parameter, checking its presence before handing it over to the `ViewSharingService`, avoiding the NPE and returning a 400 instead of a 500.
Unfortunately this just returns a plain text error message instead of a structured one, looking like this:
```
must not be null (path = ViewSharingResource.create.arg1, invalidValue = null)
```
This should be caught properly and turned into an `ApiError` in a subsequent PR.
Fixes #7688.

Validate view sharing request upon POST.

---

graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerFactory.java

The `NodeInstance` container for api integration test has repeatedly
failed to start in less than 60 seconds on our jenkins runners.
Increased timeout to 120 seconds to avoid failing ci runs.

Increase startup timeout for for test container

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchQueryString.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/events/SearchJobExecutionEvent.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchResource.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchQueryStringTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/SearchResourceTest.java

This change implements creating and posting an event on the local node's
event bus whenever a search job is created and executed. This happens
for both synchronous and asynchronous execution.
Any component in the Graylog server can subscribe on these events and be
notified when the local node is executing a search job. The created
event includes:
- the user executing the search job
- the search job itself (which also includes the search)
- the start of the execution
This is only a notification mechanism. There is no way a subscriber of
the event can take an effect on the search job execution.

Trigger event upon search job creation.

---

graylog2-web-interface/src/views/components/searchbar/queryinput/ace.js
graylog2-web-interface/src/views/components/searchbar/queryinput/webpack-resolver.js

After going back to `react-ace`, we can now use the stock `lucene` mode again, by `import`ing it and remove our custom loader code.
This has the added benefit that the recent `file-loader` update changed the module semantics and resulted in generating a `<script src="[object Module]"></script>` tag.

Reverting to stock lucene mode for `react-ace`.

---

graylog2-server/src/main/java/org/graylog2/inputs/transports/netty/ExceptionLoggingChannelHandler.java
graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java

(copy of https://github.com/Graylog2/graylog2-server/pull/5936)
It's reasonable to let users configure a timeout for keepalive connections but this event should not be logged as an error when the time expires.
The user can configure the GelfHTTPInput to timeout after a certain amount of time. The input also supports tcp keep alive. If both of these settings are enabled ( say timeout after 1 hour and keepalive ) then an error will be logged in the graylog server logs when the persistent connection is terminated by netty ( ``ReadTimeoutException``)
I don't think this timeout should log an error in the internal graylog server logs. 
I saw the read timeout exception messages in the server logs and was worried messages were getting dropped. This change will change the log message to be a …

Prevent read timeout exception

---

graylog2-web-interface/packages/graylog-web-plugin/package.json
graylog2-web-interface/yarn.lock

Version 4.x dropped support for accessing the "chunks" field in
templates. See the discussion in:
https://github.com/jantimon/html-webpack-plugin/issues/1369#issuecomment-604382645
This fixes loading web plugins in a Graylog production build.
Also sync "yarn.lock".

Revert html-webpack-plugin to version 3.2.0 in graylog-web-plugin

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java

Currently only admins are able to delete a view (dashboard / saved search).
With this PR we are allowing all users with view edit rights to delete a view.
This behaviour matches the permissions logic of comparable cases in the application.

Allow view deletion for users with view edit permissions

---

graylog2-web-interface/src/views/components/aggregationbuilder/PivotConfiguration.jsx
graylog2-web-interface/src/views/components/common/EditableTitle.jsx
graylog2-web-interface/src/views/components/widgets/WidgetHeader.jsx

**Note: This requires a backport to `3.2`.**
Before this change, the default action for the form submit event triggered by submitting the `PivotConfiguration`/`EditableTitle` forms was not prevented. This lead to a redirect happening in some browsers (namely Safari), while working as expected on others (Chrome/ium).
This change is now preventing the form submit event to fix this for Safari and others.
Fixes #7806.

Prevent default action for form submit event in `PivotConfiguration`.

---

graylog2-web-interface/src/views/components/aggregationbuilder/PivotConfiguration.jsx
graylog2-web-interface/src/views/components/common/EditableTitle.jsx

Before this change, the default action for the form submit event triggered by submitting the `PivotConfiguration`/`EditableTitle` forms was not prevented. This lead to a redirect happening in some browsers (namely Safari), while working as expected on others (Chrome/ium).
This change is now preventing the form submit event to fix this for Safari and others.
Fixes #7806.

Prevent default action for form submit event in `PivotConfiguration`. (3.2)

---

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/PipelineResource.java
graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/rest/PipelineResourceTest.java

Prior to this change, the stages setter was not called for
the PipelineSource builder for the result of pipeline
parse api endpoint. This led to an 500 server error
and the api endpoint could not be used.
This change will take the parsed stages from the pipeline
and add them to the resulting PipelineSource.
Fixes #7322

Add stages to result of parse pipeline api endpoint result

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
graylog2-web-interface/src/views/components/views/ViewList.jsx

**We need to merge https://github.com/Graylog2/graylog2-server/pull/7817 first, it changes the backend permissions for view deletions. Otherwise the frontend permission check will not match.**
As described in https://github.com/Graylog2/graylog2-server/issues/7730 a user without the permissions to delete a dashboard still sees the `Delete` action in the dashboard action menu.
Fixes: https://github.com/Graylog2/graylog2-server/issues/7730

Only show dashboard delete button for users with correct permissions

---

graylog2-web-interface/src/views/components/searchbar/completions/FieldNameCompletion.js
graylog2-web-interface/src/views/components/searchbar/completions/FieldNameCompletion.test.jsx
graylog2-web-interface/src/views/logic/fieldactions/ChartActionHandler.test.js
graylog2-web-interface/src/views/stores/FieldTypesStore.js
graylog2-web-interface/src/views/stores/ViewMetadataStore.js

The field name completer of the query input is returning different scores depending on if
the current query's stream set or not. For this, it retrieved an array of field names for the current query and iterated over all field names and checked for each field if it is included in that array. This leads to a complexity of `n*m` (where n is the number of total fields, while m is the number of fields in the current query). This lead to performance degrading for a high number of fields.
This PR is changing the code so that whenever the field types set is updated, it creates a map for the field names of the current query. This reduces the check if the field is part of the current query from `n*m` to constant effort (a plain hash lookup).
Refs #7809.

Improve field name completion performance by caching field names.

---

graylog2-server/src/main/java/org/graylog2/bindings/PersistenceServicesBindings.java
graylog2-server/src/main/java/org/graylog2/inputs/persistence/InputStateData.java
graylog2-server/src/main/java/org/graylog2/inputs/persistence/InputStatusRecord.java
graylog2-server/src/main/java/org/graylog2/inputs/persistence/InputStatusService.java
graylog2-server/src/test/java/org/graylog2/inputs/persistence/InputStatusServiceTest.java
graylog2-server/src/test/resources/org/graylog2/inputs/persistence/input-status.json

Migrating the InputStatusService from the enterprise plugins repo to the main repo.
The InputStatusService was created to support Inputs that need to persist state for the duration of their lifecycle.  It was created to allow the Okta input to checkpoint on seen messages in order to avoid duplicate message processing when the input is restarted.
Original PR: https://github.com/Graylog2/graylog-plugin-enterprise-integrations/issues/136
Migrating the InputStatusService from the enterprise plugins repo to the main repo.
The InputStatusService was created to support Inputs that need to persist state for the duration of their lifecycle.  It stores Input state in the new `input_status` MongoDB collection. It was created to allow the Okta input to checkpoint on seen messages in order to avoid …

Migrating InputStatusService

---

graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/QuickValuesConfig.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/QuickValuesHistogramConfig.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/StackedSeries.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/StatsCountConfig.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/WorldMapConfig.java
graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/V20191125144500_MigrateDashboardsToViewsTest.java
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_widgets_missing_query_attributes-expected_searches.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_widgets_missing_query_attributes-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_widgets_missing_query_attributes.json

**Note: This requires a backport to `3.2`.**
This PR is changing the legacy dashboards migration to handle the
`query` field being potentially `null` in more legacy widget types than
expected, by adding a `Nullable` annotation where it was missing and
turning a `null` query into an empty one.
Fixes #7781.

Handle `query` fields being `null` for all legacy dashboard widgets.

---

graylog2-web-interface/src/views/components/WidgetGrid.jsx
graylog2-web-interface/src/views/components/__snapshots__/WidgetGrid.test.jsx.snap

We are currently using the `SizeMe` component inside the `WidgetGrid` to provide the full grid width in px for the `ReactGridContainer`. 
The `ReactGridContainer` is also able to calculate the full width itself by using `WidthProvider` from `react-grid-layout`
(https://github.com/STRML/react-grid-layout/blob/master/lib/components/WidthProvider.jsx),
which means we don't have to use the `SizeMe` component.
Using the `WidthProvider` instead of the `SizeMe` container also fixes a `WorldMap` viewport bug, described here: https://github.com/Graylog2/graylog2-server/issues/7779
Fixes: https://github.com/Graylog2/graylog2-server/issues/7779

Remove not needed SizeMe container from WidgetGrid

---

graylog2-web-interface/src/views/components/QueryTabs.jsx

There is currently an error in the console when opening the dashboard:
```
Warning: Failed prop type: The prop `id` is required to make `Tabs` accessible for users of assistive technologies such as screen readers.
```
This PR adds the required id. The id format is inspired by the format used in the `react-bootstrap` docs:
https://react-bootstrap-v3.netlify.com/components/tabs/

Add required id for dashboard pages tabs menu

---

graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/QuickValuesConfig.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/QuickValuesHistogramConfig.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/StackedSeries.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/StatsCountConfig.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboardwidgets/WorldMapConfig.java
graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/V20191125144500_MigrateDashboardsToViewsTest.java
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_widgets_missing_query_attributes-expected_searches.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_widgets_missing_query_attributes-expected_views.json
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20191125144500_MigrateDashboardsToViewsSupport/dashboard_with_widgets_missing_query_attributes.json

This PR is changing the legacy dashboards migration to handle the
`query` field being potentially `null` in more legacy widget types than
expected, by adding a `Nullable` annotation where it was missing and
turning a `null` query into an empty one.
Fixes #7781.

Handle `query` fields being `null` for all legacy dashboard widgets. (3.2)

---

graylog2-web-interface/package.json
graylog2-web-interface/src/routing/AppRouter.test.jsx
graylog2-web-interface/src/views/components/SearchBar.test.jsx
graylog2-web-interface/src/views/components/WidgetQueryControls.test.jsx
graylog2-web-interface/src/views/components/searchbar/QueryInput.test.jsx
graylog2-web-interface/src/views/spec/CreateNewDashboard.test.jsx
graylog2-web-interface/test/console-warnings-fail-tests.js
graylog2-web-interface/test/console-warnings-fail-tests.test.js
graylog2-web-interface/test/setup-jest.js

In #7524 the logic that manages `console.error/warn` functions and wraps
them in functions turning non-ignored logs into test failures was
extracted into a module, but unfortunately not wired for testing, so it
was ineffective.
This PR is turning this back on and fixes the causes for test failures
related to this.

Reactivate module that turns console.error/warn to test failures.

---

graylog2-server/src/main/java/org/graylog2/bindings/PersistenceServicesBindings.java
graylog2-server/src/main/java/org/graylog2/inputs/persistence/InputStatusService.java
graylog2-server/src/main/java/org/graylog2/inputs/persistence/MongoInputStatusService.java
graylog2-server/src/test/java/org/graylog2/inputs/persistence/MongoInputStatusServiceTest.java

Extracted `InputStatusService` as an interface and renamed the implementation to `MongoInputStatusService`.
By extracting the interface of the input status service, we can bind a default implementation but provide the possibility to bind an alternative implementation in a different context.
The service is not used yet. Temporarily modified another service to have the InputStatusService injected and made sure that the server did still start.

Extract interface of input status service

---

graylog2-web-interface/src/stores/__tests__/connect.test.jsx
graylog2-web-interface/src/stores/connect.jsx

This change provides a `useStore` React hook which can be used in stateless components to consume a store's state. The benefit of this over wrapping a comment with `connect` is that no intermediate wrapper component needs to be created, making this a lightweight alternative.
Its usage looks like this:
```
const ShowRefreshInterval = () => {
const { enabled, interval } = useStore(RefreshStore);
return enabled ? `Refreshing every ${interval}ms` : 'Refresh disabled.';
};
```
It also uses a function mapping the store's state before returning it, if provided:
```
const ShowRefreshInterval = () => {
const interval = useStore(RefreshStore, ({ interval }) => interval;
return `Refreshing every ${interval}ms`;
};
```
`useStore` is properly typed, so if the store is of type `Store<V>` where `V` is …

Provide `useStore` React hook to sync functional component with store state

---

graylog2-web-interface/src/components/bootstrap/BootstrapModalConfirm.jsx
graylog2-web-interface/src/views/components/ViewTypeLabel.js
graylog2-web-interface/src/views/components/ViewTypeLabel.test.jsx
graylog2-web-interface/src/views/components/views/ShareViewModal.jsx
graylog2-web-interface/src/views/components/views/ShareViewModal.test.jsx
graylog2-web-interface/src/views/logic/views/View.js

As described in https://github.com/Graylog2/graylog2-server/issues/7773 the saved search modal displays a dashboard specific description. This PR adds `typeLabel` method for the view class, which can be used wherever we need to display the name of the view type.
Fixes: https://github.com/Graylog2/graylog2-server/issues/7773

Show view type specific description for dashboard and saved searches share modal.

---

graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetService.java
graylog2-server/src/main/java/org/graylog2/indexer/indexset/MongoIndexSetService.java
graylog2-server/src/main/java/org/graylog2/streams/StreamServiceImpl.java

Before this change, calling `StreamService#loadAll` triggered loading of associated outputs and index sets, _both_ resulting in n+1 each.
This change is now placing fetching of outputs and index sets outside the loop iterating over each stream, leaving only simple lookups to be done inside the loop, effectively turning this into a call with a _constant_ number of mongodb queries.
Simple tests on my setup showed an improvement of ~270ms -> ~110ms.  While this is already impressive, I expect a much bigger improvement for setups with a high number of outputs.

Removing n+1's in `StreamService#loadAll` by consolidating external loads

---

graylog2-web-interface/src/stores/indices/IndicesStore.js
graylog2-web-interface/src/stores/nodes/NodesStore.js
graylog2-web-interface/src/stores/systemjobs/SystemJobsStore.js

In #7671, a `shouldComponentUpdate` function for `connect` was
implemented, that prevents a rerendering of its children when the state
supplied by a store did not change. The implication of this is that a
store should always propagate a new object when its state has changed,
instead of mutating its state inline. In the latter case, the consumer
of the state will hold a reference to the previous state that is the
same as the new state, so it will appear to be equal. When implementing
that PR, a search was performed for patterns where a store was assigning
a new value to an instance variable (anything that looks like
`this(\.\w+)+ = .+;`) and patterns like this were changed to create a
new object that is assigned to the instance variable.
Unfortunately patterns where the bracket notation …

Replace mutating state inline in stores with new object creation.

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewsResourceTest.java
graylog2-web-interface/src/views/pages/DashboardsPage.jsx
graylog2-web-interface/src/views/pages/NewDashboardPage.jsx
graylog2-web-interface/src/views/pages/NewDashboardPage.test.jsx
graylog2-web-interface/src/views/spec/CreateNewDashboard.test.jsx

Before this PR, a user with only stream reading permissions
was able to create a dashboard by clicking on the displayed
dashboard button.
With this change, we restrict the creation of dashboards
on the backend and hide the dashboard create button
if the user does not have the needed permissions.
Additionally we only render the dashboards/new page
if the user has the needed permissions.
Fixes #7729

Allow dashboard creation only permitted users

---

graylog2-web-interface/src/stores/nodes/NodesStore.js

In #7864 a usage of `Object.fromEntries` was introduced. Unfortunately
this causes tests to fail on node v10. Luckily this was caught by
@linuspahl. My attempts to configure babel to include the required
transforms for this (by setting `{ targets: { node: true } }`) did not
succeed, but cause other errors. Therefore I decided to replace the
usage with a call to `reduce`, which is less readable, but has the same
outcome.

Replacing usage of `Object.fromEntries` with `reduce`.

---

graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypesService.java
graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/MappedFieldTypesService.java
graylog2-server/src/main/java/org/graylog2/streams/StreamService.java
graylog2-server/src/main/java/org/graylog2/streams/StreamServiceImpl.java
graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/processors/ConfigurationStateUpdaterTest.java
graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/MappedFieldTypesServiceTest.java

Before this change, the performance of the API endpoint allowing to
retrieve field types for a given set of stream IDs was not ideal. The
reason for this is that it reuses the `StreamService#loadByIds` method,
which always loads the complete streams from Mongo, as well as their
associated stream rules, outputs and index sets. The last two are
fetched using inefficient method chains producing n+1 for both, so the
overall complexity of the call is non-linear.
This PR implements a method on the `StreamService` interface, that
returns a set of index set ids for a given set of stream ids. Fetching
these is done by using an `$in` query returning only the index set id
field, so the query performance should be optimal.

Improving runtime for field type retrieval endpoint.

---

graylog2-web-interface/src/components/common/PaginatedList.jsx
graylog2-web-interface/src/components/common/PaginatedList.test.jsx

We are currently not reseting the pagination / active page, when changing the page size. This can lead to a problem described here: https://github.com/Graylog2/graylog2-server/issues/7825
This PR is fixing the problem, by resetting the active page on a page size change.
Fixes: https://github.com/Graylog2/graylog2-server/issues/7825

Reset pagination on page size change

---

graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java
graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20200409083200_RemoveRootQueriesFromMigratedDashboards.java
graylog2-server/src/main/java/org/graylog2/periodical/ConfigurationManagementPeriodical.java
graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20200409083200_RemoveRootQueriesFromMigratedDashboardsTest.java
graylog2-server/src/test/resources/org/graylog/plugins/views/migrations/V20200409083200_RemoveRootQueriesFromMigratedDashboards/sample.json

As described in #7732, a dashboard that was created by exporting a
search to a dashboard, it could have a root query string remaining,
which was not cleared during the export. This could lead to unexpected
results when the query of a widget is changed.
This migration is executing a mongo command that retrieves all searches
which are referenced by views of type `DASHBOARD` and sets all query
strings which are not empty or `*` to an empty string.
Fixes #7750.

Ensure that dashboards have empty root query strings.

---

graylog2-server/src/main/java/org/graylog/plugins/beats/Beats2Codec.java
graylog2-server/src/test/java/org/graylog/plugins/beats/Beats2CodecTest.java
graylog2-server/src/test/resources/org/graylog/plugins/beats/winlogbeat-v7.json

Beats 7.0 changed a lot of their field name schema.
https://www.elastic.co/guide/en/beats/libbeat/7.x/breaking-changes-7.0.html#_field_name_changes
This is a minimal change to extract the hostname from pre-7 and post-7
type beats messages.
Fixes #6501

Add minimal support for Beats > 7.0

---

graylog2-server/src/main/java/org/graylog/plugins/beats/Beats2Codec.java
graylog2-server/src/test/java/org/graylog/plugins/beats/Beats2CodecTest.java
graylog2-server/src/test/resources/org/graylog/plugins/beats/winlogbeat-v7.json

Beats 7.0 changed a lot of their field name schema.
https://www.elastic.co/guide/en/beats/libbeat/7.x/breaking-changes-7.0.html#_field_name_changes
This is a minimal change to extract the hostname from pre-7 and post-7
type beats messages.
Fixes #6501
(cherry picked from commit 5061d81ae01c96e74267b40510ff5fd7be88ffd2)

Add minimal support for Beats > 7.0 (#7879)

---

graylog2-server/src/main/java/org/graylog2/plugin/configuration/fields/AbstractConfigurationField.java
graylog2-server/src/main/java/org/graylog2/plugin/configuration/fields/DropdownField.java
graylog2-server/src/main/java/org/graylog2/plugin/configuration/fields/ListField.java
graylog2-server/src/main/java/org/graylog2/plugin/configuration/fields/NumberField.java

* Supply position parameter to remaining configuration fields
PR #7504 added support to specify an explicit position on configuration fields.
This adds constructors to the remaining configuration fields
that were lacking this option: `DropdownField`, `ListField` and `NumberField`.
* Reduce some duplication
Co-authored-by: Bernd Ahlers <bernd@graylog.com>
(cherry picked from commit 1bccb32cd554ddf761899026910ee9ed4cc536af)

Supply position parameter to remaining configuration fields (#7874)

---

graylog2-web-interface/src/views/components/Field.jsx
graylog2-web-interface/src/views/components/Field.test.jsx

Before this change, the `Field` component did return the physical field
name instead of the effective name (which could be overridden by the
user) if the interactive context is `false`.
This change makes `Field` return the effective name as supplied in the
`children` prop instead.
Fixes #7771.

Returning effective field name in non-interactive context.

---

graylog2-web-interface/src/views/components/SearchBar.jsx
graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
graylog2-web-interface/src/views/components/searchbar/QueryInput.jsx
graylog2-web-interface/src/views/components/searchbar/QueryInput.test.jsx
graylog2-web-interface/src/views/components/searchbar/queryinput/ace-queryinput.css

**Note: This needs #7829 to be merged before.**
This PR is adding back functionality which enables/disables the field
name autocompletion in the query input on the search/dashboards pages if
the user has a user preference for `enableSmartSearch` set which is
`false`.
Fixes #7809.

Enable/disable auto-completion in query input based on user preference.

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/Query.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/Search.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/SearchTest.java

Prior to this change, we filtered the queries with
empty search types. Without this any queries
(which can happen on an completely new dashboard)
the resulting response to the front-end is empty.
Which leads to an loading spinner.
This change will remove the filtering of the queries.
So a search from a search and from a dashboard
are producing the same result.
This is far from ideal since we now produce a
empty result set which is not needed. But this
is the safest option for now.
Fixes #7807
1. Created a empty Dashboard typed in a global query and saw no spinner
2. Same for the search
3. Created a Dashboard with a Message Table and stepped through the pages
4. Add a another widget an did again stepped through the Message Table

Do not filter querys with empty search types

---

graylog2-web-interface/packages/eslint-config-graylog/index.js

When the `eslint-plugin-flowtype` was introduced, it was not considered
that its `recommended` config actually does not activate all rules. This
PR is activating the relevant rules for us. These are:
* [`delimiter-dangle`](https://github.com/gajus/eslint-plugin-flowtype#eslint-plugin-flowtype-rules-delimiter-dangle): making rules for dangling commas consistent (enforce for multilines)
* [`no-weak-types`](https://github.com/gajus/eslint-plugin-flowtype#eslint-plugin-flowtype-rules-no-weak-types): not allowing `Object` or `Function` types, because they are too generic
* [`require-valid-file-annotation`](https://github.com/gajus/eslint-plugin-flowtype#eslint-plugin-flowtype-rules-require-valid-file-annotation): flow header should always be a line comment and `strict` should be true
* …

Improving eslint rules for flow.

---

graylog2-web-interface/src/components/errors/ReportedError.test.jsx

The tests are currently failing on the `master` branch, because `waitForElementToBeRemoved`  is not part of `wrappedTestingLibrary `.
This PR fixes the issue by using `wait` instead of `waitForElementToBeRemoved` for the related test cases.

Remove waitForElementToBeRemoved from ReportedError test

---

graylog2-server/src/main/java/org/graylog2/bindings/providers/DefaultSecurityManagerProvider.java
pom.xml

Since years we get LDAP exception for logins of local users even if the LDAP realm is in the last position. That is not necessary when the local user authentication is successful.
This change includes an Apache Shiro bug fix [SHIRO-747](https://issues.apache.org/jira/browse/SHIRO-747) and configures FirstSuccessfulStrategy to do what the name implies, see [SHIRO-669](https://issues.apache.org/jira/browse/SHIRO-669).
This should fix Graylog2/graylog2-server#2267
This has been testen locally
1. create a local user
2. enable and configure ldap against a non existing ldap server (e.g. localhost:389)
3. login with the created user: this results in an LDAP exception in graylog-server.log
4. reorder realms: move ldap to the end
5. login with created user: no more exception in log file

Fix LDAP exceptions for local user account

---

graylog2-web-interface/src/components/common/SourceCodeEditor.jsx

If documents in the Ace editor are modified on a Windows browser,
it would result in windows style newlines, which Graylog doesn't handle
correctly.
The Ace editor defaults to 'auto' mode, which switches to
windows mode, if the content is pasted on Windows.
It's better to uniformly have unix style newlines everywhere,
thus enforce unix mode as a default for Ace.
Fixes #7889
Fixes https://github.com/Graylog2/collector-sidecar/issues/389

Enforce Unix newlines for Ace editor

---

graylog2-server/src/main/assembly/graylog.xml

Change to relative paths (to .) instead of / to remove assembly warnings
Fix Graylog2/graylog2-server#7920
mvn package doesn't output any warnings any more

Change outputDirectory to non filesystem-root paths

---

graylog2-web-interface/src/views/components/widgets/FieldSortSelect.jsx

The `FieldSortSelect` component uses the `Select` component from
`react-select` directly, without reusing our wrapper. This prevents it
from benefitting from the changes we made in #7818, especially resulting
in higher render times if the number of options is high.

Make `FieldSortSelect` use our `Select` wrapper.

---

graylog2-web-interface/src/util/CreateEvent.js
graylog2-web-interface/src/util/CreateEvent.test.jsx
graylog2-web-interface/src/util/FormsUtils.js
graylog2-web-interface/src/views/components/visualizations/worldmap/MapVisualization.jsx

In Internet Explorer 11, calling `new Event()` raises an exception.
Instead, a new event needs to be created using
`el.createEvent`/`event.initEvent`, the latter being deprecated on all
other major browsers.
This PR is abstracting the uglyness of this circumstance by offering a
`createEvent` function which returns an event after checking if the
`Event` constructor is available, using the other approach if not.
Fixes #7670.
- Running IE11 in a Window VM, testing with Chrome/Safari for the
regular approach.

Work around non-existing `Event` constructor in IE11.

---

pom.xml

Jackson 2.9.10.4 (2.9.10.20200411)
blocks many more gadget types
For details see:
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9#micro-patches

Jackson security update from 2.9.10.2 to 2.9.10.4 (2.9.10.20200411)

---

graylog2-server/src/main/antlr4/org/graylog/plugins/pipelineprocessor/parser/RuleLang.g4

Remove single-quotes around backtick because this is inside a character class ([ ])
Fix Graylog2/graylog2-server#7918
mvn package doesn't output any warnings any more

Change expression for Identifier

---

graylog2-web-interface/src/logic/rest/FetchProvider.js

In #7709, changes were made to the `FetchProvider`, which prevent a
proper error object being handed down to consumers of it, in case of a
server response that is indicating an error.
This change is restoring the original behavior.
Fixes #7964.

Restore proper error returned by `FetchProvider`.

---

graylog2-server/src/main/java/org/graylog/schema/GraylogSchemaFields.java
graylog2-server/src/main/java/org/graylog2/inputs/GraylogSchemaFields.java

The Graylog Security team has created a common schema to use as the basis for future official content packs.  This change will make it easier for new and existing Inputs to re-use the fields defined for the Graylog Schema.
Fields have been tested with the new Okta enterprise plugin.

Create a common list of field names for the Graylog Schema.

---

graylog2-web-interface/src/components/common/SourceCodeEditor.jsx

* Enforce Unix newlines for Ace editor
If documents in the Ace editor are modified on a Windows browser,
it would result in windows style newlines, which Graylog doesn't handle
correctly.
The Ace editor defaults to 'auto' mode, which switches to
windows mode, if the content is pasted on Windows.
It's better to uniformly have unix style newlines everywhere,
thus enforce unix mode as a default for Ace.
Fixes #7889
Fixes https://github.com/Graylog2/collector-sidecar/issues/389
* Add comment
(cherry picked from commit 208a5bc0a01f980ad7811b6fb4fd1a85d118bce7)

Enforce Unix newlines for Ace editor (#7893)

---

graylog2-server/src/main/java/org/graylog2/indexer/cluster/Cluster.java
graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/AbsoluteValueWatermarkSettings.java
graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/ClusterAllocationDiskSettings.java
graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/ClusterAllocationDiskSettingsFactory.java
graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/NodeDiskUsageStats.java
graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/NodeFileDescriptorStats.java
graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/PercentageWatermarkSettings.java
graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/WatermarkSettings.java
graylog2-server/src/main/java/org/graylog2/indexer/cluster/jest/GetAllocationDiskSettings.java
graylog2-server/src/main/java/org/graylog2/notifications/Notification.java
graylog2-server/src/main/java/org/graylog2/periodical/IndexerClusterCheckerThread.java
graylog2-server/src/test/java/org/graylog2/indexer/cluster/ClusterIT.java
graylog2-server/src/test/java/org/graylog2/indexer/cluster/health/ClusterAllocationDiskSettingsFactoryTest.java
graylog2-server/src/test/java/org/graylog2/indexer/cluster/health/NodeDiskUsageStatsTest.java
graylog2-server/src/test/java/org/graylog2/periodical/IndexerClusterCheckerThreadTest.java
graylog2-web-interface/src/logic/notifications/NotificationsFactory.js

Added a disk usage check of the elasticsearch nodes. If cluster allocation thresholds are enabled, it will monitor those settings against all the elasticsearch nodes of the cluster and send notifications visible in graylog UI.
Backport of https://github.com/Graylog2/graylog2-server/pull/7853 for #7810

Show notifications when disk in the Elasticsearch nodes fills up 

---

graylog2-web-interface/src/pages/ContentPacksPage.jsx

Purely cosmetical change for consistent spelling of the term "Content Packs" on this page.
Just looked all wrong, so it triggered me.
N/A text update

use consistent spelling for "Content Packs"

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/export/CommandFactory.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/export/CommandFactoryTest.java

...from MessagesRequest to ExportMessagesCommand
This allows overriding the default chunk size for api requests, which is useful for testing.
This should be easy to verify with a simple curl:
`curl -X POST -H "X-Requested-By: peterchen" -H "Content-Type: application/json"  -u admin:admin -d '{"chunk_size": 1}' localhost:9000/api/views/search/messages`
With a bigger chunk size many (all) messages will appear at once. With a chunk size of 1 you can see single messages popping up in the terminal.

Add missing mapping for chunk size

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/export/ExportMessagesCommand.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/export/MessagesRequest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/export/CommandFactoryTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/export/MessagesRequestTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/export/TestData.java

Default time range was originally a `RelativeRange`. When it was converted to an `AbsoluteRange` it should not have been assigned to a static field any more, because the correct absolute time range must be computed dynamically the moment the request is built.
Instead it was computed once and remained statically set to the original "last five minutes" for all subsequent requests. This commit fixes that.
Kudos @kmerz for finding that. :)

Fix assignment of default timerange for export requests

---

graylog2-web-interface/src/views/components/queries/QueryTitleEditModal.jsx
graylog2-web-interface/src/views/components/queries/QueryTitleEditModal.test.jsx

**This PR needs a backport for 3.3**
With https://github.com/Graylog2/graylog2-server/pull/7748 we've changed the naming for dashboard tabs from "tabs" to "pages". This PR adapts the change for the `QueryEditModal`.

Unify naming for `QueryEditModal` description

---

graylog2-server/src/main/java/org/graylog2/inputs/persistence/MongoInputStatusService.java
graylog2-server/src/test/java/org/graylog2/inputs/persistence/MongoInputStatusServiceTest.java

This is a workaround for the problem described in #7812.
When we receive an "InputDeleted" event, check if the input still exists
in the database. If so, the input has only been stopped and we don't
want to delete our state.
Refs #7812

Add workaround for input event problems in MongoInputStatusService

---

graylog2-server/src/main/java/org/graylog2/shared/bindings/RestApiBindings.java
graylog2-server/src/main/java/org/graylog2/web/DevelopmentIndexHtmlGenerator.java
graylog2-server/src/main/java/org/graylog2/web/IndexHtmlGenerator.java
graylog2-server/src/main/java/org/graylog2/web/ProductionIndexHtmlGenerator.java
graylog2-server/src/main/resources/web-interface/index.html.development.template

The production "index.html" generator is throwing an exception when the
production assets cannot be found on server startup. That means
developers need to run a full maven build including the production web
interface before the development server can start successfully in the IDE.
With this PR we can switch to a different IndexHtmlGenerator
implementation that doesn't require the production web assets to be
present on server startup. (it serves a dummy "index.html" page)
Switching to this implementation requires the "DEVELOPMENT" environment
variable to be set.

Provide a different IndexHtmlGenerator for development

---

graylog2-web-interface/src/views/components/DashboardSearchBar.jsx
graylog2-web-interface/src/views/components/SearchBar.jsx
graylog2-web-interface/src/views/components/WidgetQueryControls.jsx
graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
graylog2-web-interface/src/views/components/searchbar/SearchButton.jsx
graylog2-web-interface/src/views/components/searchbar/TimeRangeDropdownButton.jsx
graylog2-web-interface/src/views/components/searchbar/TimeRangeOverrideTypeSelector.jsx
graylog2-web-interface/src/views/components/searchbar/TimeRangeTypeSelector.jsx
graylog2-web-interface/src/views/components/searchbar/TopRow.jsx
graylog2-web-interface/src/views/components/visualizations/GenericPlot.jsx
graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx

With https://github.com/Graylog2/graylog2-server/pull/7914 we've implemented the `ExtendedSearchPage` styled by using styled components instead of a css file.
This changed the styles scope and resulted in the following problem: https://github.com/Graylog2/graylog2-server/issues/7976
This PR is fixing the issue by extract the styles from the `ExtendedSearchPage` by creating own components for the searchbar `TopRow` and `TimeRangeDropdownButton` and adding the specific styles to the `SearchButton` and `GenericPlot`.
Fixes https://github.com/Graylog2/graylog2-server/issues/7976

Extract styles from `ExtendedSearchPage`

---

graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportModal.jsx
graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportModal.test.jsx
graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportWidgetSelection.jsx

The message field is not a common message list field. When exporting a message list to CSV the message field needs to be added. We are already doing this when exporting a search, but this is currently not working when using the message list selection which is part of the CSV export modal. This PR is fixing the described problem.
Fixes #8001

Include message field as initial field when using CSV export modal widget select.

---

graylog2-web-interface/src/views/components/visualizations/ChartColorContext.js

This PR is ensuring that `ChartColorContext` is exported as singleton,
meaning that plugins and core are always importing the same instance.

Export `ChartColorContext` as singleton.

---

graylog2-web-interface/src/views/components/visualizations/worldmap/MapVisualization.jsx

As described in #7997 a worldmap viewport can change when switching dashboard pages. With this PR we are defining a `key` prop for the `Map` component, which includes the provided height and width. This way we can ensure the map is rerendering on a dimension change.
Fixes #7997

Define key prop for `MapVisualization` to update map on dimension change

---

graylog2-web-interface/src/util/MessagesExportUtils.js
graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportModal.jsx
graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportModal.test.jsx
graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportSettings.jsx
graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportWidgetSelection.jsx
graylog2-web-interface/src/views/components/searchbar/csvexport/startDownload.js

This PR removes the sorting option from the CSV export modal. We've decided to remove this functionality for now, because defining a custom sort will currently result in very slow exports. we We will reimplement the sorting options, once we support [search after](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-request-search-after.html) beside [Elasticsearch's scroll API](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-request-scroll.html).

Remove sort and sort direction select from CSV export modal

---

graylog2-web-interface/src/views/components/common/EditableTitle.jsx

As described in #7998 the widget title is currently sometimes not being saved, when saving a dashboard or saved search. This only happens when a user blurs the widget title input (wit).
This happens because we are not providing an event for the submit handler on blur and `e.preventDefault()`throws an error.
Fixes: #7998

Only cancel default event action on widget title change if event is defined

---

graylog2-web-interface/src/views/components/common/ActionDropdown.jsx
graylog2-web-interface/src/views/components/widgets/Widget.jsx
graylog2-web-interface/src/views/components/widgets/Widget.test.jsx

The CSV export of a widget search result is currently only possible for message tables. With this PR we are hiding the action for all other widget types, instead of disabling the menu item.
- [X ] New feature (non-breaking change which adds functionality)

Hide export to CSV action in widget action menu for aggregations

---

graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx

This PR is fixing the search area scroll issue described here #8003, by adding a calculated height. As discussed this is only a workaround and we will adjust the page layout with the next sidebar layout change. Right now we are defining the height multiple times, with a dynamic layout we don't need to calculate the height manually.
Fixes #8003

Add calculated height for search area to fix scrolling with safari

---

graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportModal.jsx
graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportModal.test.jsx
graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportSettings.jsx
graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportWidgetSelection.jsx
graylog2-web-interface/src/views/components/searchbar/csvexport/ExportStrategy.js

This PR is fixing the bug described in #8035 (CSV export modal does not list every message table configured for a dashboard.) It also adds tests for the described case and implements correct markup for the CSV export form labels. This is a good practice in general and necessary to test the widget select component.
We need to merge https://github.com/Graylog2/graylog2-server/pull/8041 before this PR.

List all message lists from all dashboard pages in CSV export widget select

---

graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportWidgetSelection.jsx

While testing the CSV export I saw the benefits in sorting the widget select options. With this PR we are sorting them alphabetically.
Ideally we should implement a `sortSelectOption` utility function for every comparable case or just sort the select options inside the `Select` component, but these solutions are not suitable right now, concerning the upcoming release.

Sort CSV export widget select options alphabetically

---

graylog2-server/src/main/java/org/graylog/schema/GraylogSchemaFields.java

standardize field names in graylog common schema,  will be used in codecs to map vendor specific fields.
* add a constant field `event_source_product`.
* add 2 new fields `application_sso_signonmode` and `application_sso_target_name`
* there are 5 vendor events.`action`, `description`, `severity`, `outcome`, `outcome_reason`
* there are 5 non-vendor events , `severity description`, `threat suspected`, `transaction type`,`transaction id`, `user type`
Add: Where target.type = "AppInstance": 
https://github.com/Graylog2/graylog-plugin-enterprise-integrations/issues/214

standardize graylog schema field names

---

graylog2-server/src/main/java/org/graylog2/cluster/ClusterConfigServiceImpl.java
graylog2-server/src/main/java/org/graylog2/plugin/cluster/ClusterConfigService.java
graylog2-server/src/test/java/org/graylog2/cluster/ClusterConfigServiceImplTest.java

**Requires Graylog2/graylog-plugin-threatintel#162 to be merged before.**
Previously, the `ClusterConfigService` interface allowed writing a
cluster config object by passing it and extracting the key/type it is
stored as from its class name. This is fine for most use cases, but
makes writing migrations that migrate the structure of a pre-existing
cluster config object non-trivial if separate classes are used for
stability. Those result in different class names, therefore being
persisted with different types than the cluster config object that
should be migrated.
This change is adding a `write(String key, Class<T> payload)` method to
the interface, which allows specifying a custom key for the payload,
therefore making it independent of the class implementing it.

Allow writing cluster config object with custom key.

---

graylog2-server/src/test/java/org/graylog2/migrations/V20161215163900_MoveIndexSetDefaultConfigTest.java

Use containsExactlyInAnyOrder instead of containsExactly
This PR aims for fix #8077
The fix uses containsExactlyInAnyOrder instead of containsExactly so that the test is more stable.
In this way, the test is no more flaky.

Use containsExactlyInAnyOrder instead of containsExactly for more robust tests

---

graylog-project-parent/pom.xml
graylog2-server/pom.xml
graylog2-server/src/main/java/org/graylog2/decorators/LinkFieldDecorator.java
graylog2-server/src/test/java/org/graylog2/decorators/LinkFieldDecoratorTest.java
pom.xml

This PR fixes an issue with [Hyperlink String Field Decorators](https://docs.graylog.org/en/3.1/pages/queries.html#decorators). When a non-link string is included in the message field for a Hyperlink Decorator field, the link is still clickable in stream-specific message tables on the Graylog Search page.
Now, the link is only clickable if the field contains a valid url starting with the protocol scheme `http://` or `https://`.
This change adds the `commons-validator` Java dependency. This allows effective URL validation without the need for reinventing custom regex patters for handle all cases.
Verify that Hyperlink String decorated fields only render a clickable link for real URLs that start with `http://` or `https://` and also that other non-link string are still displayed, but are …

Sanitize Hyperlink String Decorator links

---

graylog2-server/src/main/java/org/graylog2/security/AESTools.java
graylog2-server/src/main/java/org/graylog2/security/ldap/LdapSettingsImpl.java

This change is adding a new static method to our `AESTools` utility class, which generates a new random salt. This method is reused in `LdapLdapSettingsImpl`. It will also be reused in future code changes where the generation of a new salt for encryption is desired.

Extract method to generate new salt for encryption. (3.2)

---

graylog2-server/src/main/java/org/graylog2/security/AESTools.java
graylog2-server/src/test/java/org/graylog2/security/AESToolsTest.java

In the current state, the `AESTools.encrypt/decrypt` methods rely on key
sizes being 16, 24 or 32 bytes. This makes functionality using it with
user-supplied keys fail if their lengths are not exactly that size.
In order to allow arbitrary key sizes, this change is cutting keys if
they are longer than 32 bytes or pads them if they are shorter than the
desired key size. Also, it uses the first of the three key sizes which
can hold as most of the supplied key as possible.

Allow arbitrary key sizes for AESTools.encrypt/decrypt.

---

graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterPreview.jsx

There is currently a bug when the search query in the event wizard does not return any result.
This PR is fixing the `cannot read property .length of undefined` error, but I am not sure why this error did not occurred before. This bug does not exist in 3.3.0-beta.1.

Don't throw error in event wizard when query has no result

---

graylog2-server/src/main/java/org/graylog2/cluster/ClusterConfigServiceImpl.java
graylog2-server/src/main/java/org/graylog2/plugin/cluster/ClusterConfigService.java
graylog2-server/src/test/java/org/graylog2/cluster/ClusterConfigServiceImplTest.java

Previously, the `ClusterConfigService` interface allowed writing a
cluster config object by passing it and extracting the key/type it is
stored as from its class name. This is fine for most use cases, but
makes writing migrations that migrate the structure of a pre-existing
cluster config object non-trivial if separate classes are used for
stability. Those result in different class names, therefore being
persisted with different types than the cluster config object that
should be migrated.
This change is adding a `write(String key, Class<T> payload)` method to
the interface, which allows specifying a custom key for the payload,
therefore making it independent of the class implementing it.

Allow writing cluster config object with custom key. (3.2)

---

graylog2-server/src/main/java/org/graylog2/security/AESTools.java
graylog2-server/src/test/java/org/graylog2/security/AESToolsTest.java

In the current state, the `AESTools.encrypt/decrypt` methods rely on key
sizes being 16, 24 or 32 bytes. This makes functionality using it with
user-supplied keys fail if their lengths are not exactly that size.
In order to allow arbitrary key sizes, this change is cutting keys if
they are longer than 32 bytes or pads them if they are shorter than the
desired key size. Also, it uses the first of the three key sizes which
can hold as most of the supplied key as possible.

Allow arbitrary key sizes for AESTools.encrypt/decrypt. (3.2)

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/export/MessagesRequest.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/export/ResultFormat.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/MessagesResource.java

- Properly annotated MessagesRequest and ResultFormat
- Annotated MessagesResource
Unfortunately it seems impossible to get proper docs for nested json objects working with our current swagger solution. So as for all our other endpoints, the user can see, that a "timerange" parameter can be specified, but not what fields it must have. :/ See #8087
Provide guidance for exports via the API
Verified in local API browser

Export API Docs

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/MessagesResource.java

Although it's deprecated, our API browser supports it, and we don't have anything better. :/

Add API description on MessagesResource

---

graylog2-server/src/main/java/org/graylog/events/configuration/EventsConfiguration.java

Make the newly introduced eventCatchupWindow
optional by setting a proper default with a JsonCreator.

Fix EventsConfiguration migration error

---

graylog2-server/src/main/java/org/graylog/events/configuration/EventsConfiguration.java

Make the newly introduced eventCatchupWindow
optional by setting a proper default with a JsonCreator.
(cherry picked from commit 076ca593d8c9df39eb9164404afcb4c4390fdd59)

Fix EventsConfiguration migration error (#8160)

---

UPGRADING.rst

Added upgrade notes for export mentioning that old endpoints will be removed for 4.0
(cherry picked from commit a31736364a51f337ed432e13cba5f9ecdfc1fb87)

Added upgrade notes for export (#8167)

---

graylog-project-parent/pom.xml
graylog-storage-elasticsearch6/pom.xml
pom.xml

This change is the first in a series aiming to separate our
Elasticsearch-specific implementation code from its consumers. It is
creating a separate maven module that is holding our current
implementation for:
* Indexing Messages
* Searching/aggregation previously indexed Messages
* Index Management
* Cluster health checks and maintenance
The goal of this is to encapsulate and hide version-specific
implementation details, allowing to switch the implementation code in
the future.
Fixes #8154.

Create separate module for ES-specific implementations.

---

graylog2-web-interface/src/components/inputs/NodeOrGlobalSelect.jsx

Prior to this change, the user must select the only existing node when
creating a new input.
This change will refactor the NodeOrGlobalSelect and preselect a node
when only one node is in the cluster.
- Created a  input with only a single node in the cluster
- **NOT TESTED YET** with multiple nodes in the cluster

Preselect node if only one node exists

---

graylog2-web-interface/src/stores/metrics/GlobalThroughputStore.js
graylog2-web-interface/src/stores/metrics/GlobalThroughputStore.test.js

**Note: This PR requires a backport to `3.3`.**
In #8019 a refactoring went wrong introducing a bug that causes global throughputs to not be summed up, but use the throughput of the last node instead.
This change is fixing this by summing up individual node's throughputs again.
Fixes #8172.

Fix summing up individual node throughput metrics.

---

graylog2-web-interface/src/stores/metrics/GlobalThroughputStore.js
graylog2-web-interface/src/stores/metrics/GlobalThroughputStore.test.js

In #8019 a refactoring went wrong introducing a bug that causes global throughputs to not be summed up, but use the throughput of the last node instead.
This change is fixing this by summing up individual node's throughputs again.
Fixes #8172.

Fix summing up individual node throughput metrics. (3.3)

---

full-backend-tests/src/test/java/org/graylog/elasticsearch/e2e/ElasticsearchE2E.java
full-backend-tests/src/test/java/org/graylog/testing/backenddriver/SearchDriver.java
full-backend-tests/src/test/java/org/graylog/testing/fullbackend/BackendStartupIT.java
graylog2-server/src/test/java/org/graylog/testing/completebackend/ApiIntegrationTest.java
graylog2-server/src/test/java/org/graylog/testing/completebackend/GraylogBackend.java
graylog2-server/src/test/java/org/graylog/testing/completebackend/GraylogBackendExtension.java
graylog2-server/src/test/java/org/graylog/testing/completebackend/Lifecycle.java
graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerConfig.java
graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerFactory.java
graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeInstance.java

This PR creates a new end-to-end test, which
- creates a GELF http input
- posts one message
- searches for that message
We want to support new Elasticsearch versions in the future and need to make sure to not break core functionality.
This test is the first step towards adding more end-to-end test of this kind. 
Execution on local machine

Add an end-to-end test for indexing and searching a message 

---

graylog2-web-interface/src/components/common/PaginatedList.jsx

The `PaginatedList` is currently still using the unsafe method `componentWIllReceiveProps`.
We've discussed this circumstance here: https://github.com/Graylog2/graylog2-server/pull/7826#issuecomment-612827854 and decided to refactor this part in a separate PR.
There are different ways to remove `componentWIllReceiveProps`, I've decided to migrate the class component to a functional component and use the `useEffect` hook.

Migrate PaginatedList from class to functional component

---

graylog2-web-interface/src/components/errors/ReportedErrorBoundary.jsx
graylog2-web-interface/src/components/errors/ReportedErrorBoundary.test.jsx
graylog2-web-interface/src/logic/errors/ReportedErrors.js
graylog2-web-interface/src/pages/StreamPermissionErrorPage.test.jsx
graylog2-web-interface/src/pages/UnauthorizedErrorPage.test.jsx
graylog2-web-interface/src/views/logic/views/ViewLoader.js
graylog2-web-interface/src/views/pages/ShowViewPage.test.jsx

When a user tries to view a saved search or dashboard which does not exist, he will be redirected to `/notfound`. With this PR the URL will not change when displaying the not found page in the described scenario.
This PR also:
* adds a fallback to display reported errors with an unknown type
* Improves the `FetchError`s we are using in related tests.

Do not redirect to `/notfound` when viewing a saved search or dashboard which does not exist.

---

graylog2-web-interface/src/views/components/ViewTypeLabel.js
graylog2-web-interface/src/views/components/views/ShareViewModal.jsx

Currently a user does not receive any kind of feedback after sharing a view. This PR implements the common `UserNotification` for the success and error case.
Fixes: #7218

Display user notification after sharing a view

---

graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportModal.test.jsx
graylog2-web-interface/src/views/components/searchbar/csvexport/ExportStrategy.js
graylog2-web-interface/src/views/components/searchbar/csvexport/startDownload.js
graylog2-web-interface/src/views/logic/queries/Query.js
graylog2-web-interface/src/views/logic/queries/SearchType.js
graylog2-web-interface/src/views/logic/searchtypes/messages/MessageSortConfig.js
graylog2-web-interface/src/views/logic/views/View.js

This PR adds a flow type definition for query search types. There are a few more files were we could use this type definition, but these files are currently not using `// @flow`
I want to remove the `searchType: any` declaration in `views/logic/queries/Query` and the `CSVExportModal`.

Create flow type definition for search types

---

graylog2-web-interface/src/views/components/ViewTypeLabel.js

The `ViewTypeLabel` currently has its own implementation for capitalization. This implements the `StringUtils` capitalize method instead.

Use StringUtils to capitalize view type label

---

full-backend-tests/src/test/java/org/graylog/testing/fullbackend/BackendStartupIT.java
graylog-storage-elasticsearch6/pom.xml
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Metadata.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Plugin.java
graylog-storage-elasticsearch6/src/main/resources/META-INF/services/org.graylog2.plugin.Plugin

This PR is adding the required boilerplate to load the Elasticsearch6
storage module as a plugin by reusing the existing plugin loading
mechanism. Therefore it exposes an implementation of the `Plugin`
interface, offering the metadata and the bindings module classes.

Wire Elasticsearch 6 storage module as plugin.

---

graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java
graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping5.java
graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping6.java
graylog2-server/src/test/java/org/graylog2/indexer/IndexMapping5Test.java
graylog2-server/src/test/java/org/graylog2/indexer/IndexMapping6Test.java
graylog2-server/src/test/java/org/graylog2/indexer/IndexMappingTestBase.java
graylog2-server/src/test/resources/org/graylog2/indexer/expected_template5.json
graylog2-server/src/test/resources/org/graylog2/indexer/expected_template6.json

In order to clean up the code and research relevant differences between
different supported Elasticsearch versions, the two classes generating index
mapping templates for ES5 & 6 were refactored and most code was moved
into the abstract base class. Tests were added before to make sure that
the refactoring does not change the logic.

Refactor index mapping templates for ES5 & 6.

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/export/ExportMessagesCommand.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/export/es/ElasticsearchExportBackend.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/export/es/RequestStrategy.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/export/es/SearchAfter.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/export/es/ElasticsearchExportBackendTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/export/es/SearchAfterTest.java

This PR allows exporting events using Search After. 
If only events should be exported, a different tie breaker field will be used (`_id` instead of `gl2_message_id`). If a mix of events and other messages should be exported, events will be ignored and a warning logged.
See #7985
While these workarounds don't immediately solve the problem, they open up possibilities for later:
- We could create a version of the server that uses search after for ourselves or for customers who understand the limitations and still want to use it (e.g., because scrolling takes too long or creates unacceptable load on their ES cluster.
- SearchAfter now can select an appropriate tie breaker based on the streams to be exported. In theory, it should be possible to add in support for old indices that don't …

Workarounds to allow exporting events with Search After

---

graylog2-web-interface/src/views/components/WidgetGrid.jsx
graylog2-web-interface/src/views/components/__snapshots__/WidgetGrid.test.jsx.snap

There is currently a visual bug, when the widget grid content results in a scrollbar:
This bug is appearing, because the widget grid changes its initially calculated width, when its content results in a scrollbar.
This PR is fixing the problem by reimplementing the `SizeMe` component for the `WidgetGrid`, which got removed with https://github.com/Graylog2/graylog2-server/pull/7833
We removed the `SizeMe` container because it fixed a bug with the worldmap widget viewport, but  we've implemented another solution for this problem in the meantime.
While testing this change I found the following edge case. When opening a dashboard page with a worldmap widget and no scrollbar after being on a page with a scrollbar, the widget has a bigger or smaller (depending on the bowser) white padding on …

Fix search widget grid width when its content results in a scrollbar

---

graylog2-web-interface/test/console-warnings-fail-tests.js

Without logging the message it's really hard to find out the actual
error because the Error message doesn't get logged properly.

Log warn/error before throwing an error in console-warnings-fail-tests.js

---

graylog2-server/src/main/java/org/graylog2/bindings/providers/DefaultSecurityManagerProvider.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/SessionsResource.java
graylog2-server/src/main/java/org/graylog2/shared/security/AuthenticationServiceUnavailableException.java
graylog2-server/src/main/java/org/graylog2/shared/security/SessionCreator.java
graylog2-server/src/main/java/org/graylog2/shared/security/ThrowingFirstSuccessfulStrategy.java
graylog2-server/src/test/java/org/graylog2/shared/security/SessionCreatorTest.java

Backport PR #8136 to `cloud-3.3`, so that plugins that depend on it will work.
Please merge https://github.com/Graylog2/graylog-project-internal/pull/28 before merging this PR.

Backport: Add support for more verbose authentication failure

---

graylog2-web-interface/src/components/common/KeyValueTable.jsx
graylog2-web-interface/src/components/common/URLWhiteListInput.jsx
graylog2-web-interface/src/components/lookup-tables/adapters/HTTPJSONPathAdapterFieldSet.jsx
graylog2-web-interface/src/components/lookup-tables/adapters/HTTPJSONPathAdapterFieldSet.test.jsx
graylog2-web-interface/src/components/lookup-tables/adapters/__snapshots__/HTTPJSONPathAdapterFieldSet.test.jsx.snap

Prior to this change, when the user add a new header,
the newly resulting config would be ignored and instead
the old config was passed to the updateConfig function.
This change will use the update config with the new headers.
Also:
- Add test to verify the fix applies
- Fix warning in URLWhiteListInput: Without the fix
the test would throw an warning which would prevent
to pass the test.
- Add testid to KeyValueTable to make it possible to
add new rows in a test.
- Add a new header to a HttpJsonPathDataAdapter
Fixes #8186

Fix adding a new header to Http Json Path Data Adapter

---

graylog2-server/src/main/java/org/graylog2/indexer/messages/IndexBlockRetryAttempt.java
graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesRetryWaitTest.java
graylog2-server/src/test/java/org/graylog2/indexer/messages/MockedMessagesTest.java

We are discarding messages, if an Elasticsearch index is blocked. This PR adds infinite retries for them. Indexing will practically be blocked until the the index block is resolved by an Elasticsearch administrator.
Fixes #8211
- New unit tests
- Manual tests with local Elasticsearch in Docker

Retry messages if target index is read-only

---

graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/MoreSearchAdapterES6.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/MultiSearch.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Scroll.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/SearchesAdapterES6.java
graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/SearchesES6IT.java
graylog2-server/src/main/java/org/graylog/events/search/MoreSearch.java
graylog2-server/src/main/java/org/graylog/events/search/MoreSearchAdapter.java
graylog2-server/src/main/java/org/graylog2/indexer/searches/SearchesAdapter.java

This PR is extracting a `MoreSearchAdapter` interface from the `MoreSearch` class, that allows us to separate the Elasticsearch-specific implementation details from the consumer of that interface. 
Before this change, the `MoreSearch` class was inheriting from the `Searches` class. This relationship was removed, to decouple those classes. The only relevant reuse was the `checkForFailedShards` method, which is now replaced with a reuse of `JestUtils.checkForFailedShards`.
Refs #8155, #8156.

Extract interface from `MoreSearch` class, isolate ES-specific details.

---

graylog2-web-interface/src/components/common/KeyValueTable.jsx
graylog2-web-interface/src/components/common/URLWhiteListInput.jsx
graylog2-web-interface/src/components/lookup-tables/adapters/HTTPJSONPathAdapterFieldSet.jsx
graylog2-web-interface/src/components/lookup-tables/adapters/HTTPJSONPathAdapterFieldSet.test.jsx
graylog2-web-interface/src/components/lookup-tables/adapters/__snapshots__/HTTPJSONPathAdapterFieldSet.test.jsx.snap

**Backport of https://github.com/Graylog2/graylog2-server/pull/8188 for 3.3.1**
Prior to this change, when the user add a new header,
the newly resulting config would be ignored and instead
the old config was passed to the updateConfig function.
This change will use the update config with the new headers.
Also:
- Add test to verify the fix applies
- Fix warning in URLWhiteListInput: Without the fix
the test would throw an warning which would prevent
to pass the test.
- Add testid to KeyValueTable to make it possible to
add new rows in a test.
- Add a new header to a HttpJsonPathDataAdapter
Fixes #8186

Fix adding a new header to Http Json Path Data Adapter (Backport of #8188 for 3.3.1)

---

graylog2-server/src/main/java/org/graylog2/shared/security/ThrowingFirstSuccessfulStrategy.java
graylog2-server/src/test/java/org/graylog2/shared/security/SessionCreatorTest.java

The `ThrowingFirstSuccessfulStrategy` now clears any exception before processing a new authentication request.
When the `ThrowingFirstSuccessfulStrategy` encountered an exception, it wouldn't clear it on subsequent authentication requests. Therefore, if authentication was unsuccessful, it would not return the normal `null` value but rather re-throw the exception from the previous attempt. I came across this bug while looking at https://github.com/Graylog2/graylog2-server/pull/8192.
Tested with the setup described [here](https://github.com/Graylog2/graylog2-server/pull/8192#pullrequestreview-419835681): 
1. Perform a auth request with a wrong password. You'll get an error about wrong credentials.
2. Take down the LDAP server. Perform the same request as in **1.)**. You'll get an error …

Clear exception in auth strategy before all attempts

---

graylog2-web-interface/src/logic/alerts/AggregationExpressionValidation.js

This got changed with the introduction of multiple conditions in 3.2.
The backend treats every value as Double anyhow.

Allow alert conditions with floating numbers

---

graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java
graylog2-server/src/main/java/org/graylog2/indexer/cluster/Cluster.java
misc/graylog.conf

This option was mostly unused since we started using Jest
to communicate with ES.
Migrate the only remaining usage in the Cluster health checker
to to `elasticsearch_socket_timeout`, which is the effective timeout
used for each Jest request.

Remove elasticsearch_request_timeout config option

---

graylog2-web-interface/src/components/lookup-tables/adapters/HTTPJSONPathAdapterFieldSet.test.jsx

The `HTTPJSONPathAdapterFieldSet` test is currently sometimes failing on the master branch, with the warning `An update to URLWhiteListInput inside a test was not wrapped in act(...)`.
This problem can be fixed by unmounting the rendered components in the `HTTPJSONPathAdapterFieldSet` test.

Unmount rendered components in `HTTPJSONPathAdapterFieldSet` test to fix test failure

---

graylog2-web-interface/src/views/components/contexts/HighlightingRulesContext.jsx
graylog2-web-interface/src/views/components/contexts/HighlightingRulesProvider.jsx
graylog2-web-interface/src/views/components/contexts/HighlightingRulesProvider.test.jsx
graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTable.test.jsx.snap
graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTableEntry.test.jsx.snap
graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.jsx
graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.test.jsx
graylog2-web-interface/src/views/components/messagelist/__snapshots__/CustomHighlighting.test.jsx.snap
graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRules.jsx
graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRules.test.jsx
graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx

This PR creates a context for the highlighting rules. Its value is being provided by the `HighlightingRulesProvider` which connects to the `HighlightingRulesStore`.
The `HighlightingRulesProvider` is being used in the `ExtendedSearchPage`, this way we don't need to connect the `HighlightingRulesStore` in `CustomHighlighting` and `HighlightingRules`.
We should reduce the times we call `connect` -> `render` and `connect` -> `shouldComponentUpdate`. Currently `render` is being called over 1000 times and `shouldComponentUpdate` over 600 times on the default search page.
Just removing `connect` from `UserTimezoneTimestamp` (https://github.com/Graylog2/graylog2-server/pull/7836) and `CustomHighlighting` reduces the calls of `connect` -> `render` to ~50 and `connect` -> `shouldComponentUpdate` …

Create separate context for highlighting rules

---

graylog2-server/src/main/java/org/graylog2/shared/security/ThrowingFirstSuccessfulStrategy.java
graylog2-server/src/test/java/org/graylog2/shared/security/SessionCreatorTest.java

Backport of #8272 to the `cloud-3.3` branch.

Backport: Clear exception in auth strategy before all attempts (#8272)

---

graylog2-server/src/main/java/org/graylog2/indexer/cluster/Cluster.java

Just filtering the list of nodes by requesting de nodeRole attribute when querying Elasticsearch and filtering out all those nodes that are not data nodes (that don't include "d" in nodeRole response)
Fixes #8239 
I tested it with an ES cluster with different types of nodes, some acting exclusively as masters for cluster coordination. After this fix, those nodes are no longer included in disk usage stats reporting

Check only data nodes in Elasticsearch disk usage stats

---

graylog2-web-interface/src/components/common/SearchForm.jsx
graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap
graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntitiesList.test.jsx.snap
graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap
graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameterList.test.jsx.snap
graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameters.test.jsx.snap
graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackPreview.test.jsx.snap
graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchList.jsx
graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchList.test.jsx
graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap

Prior to this change, a user needed to click on the search
input after he opened the saved search modal.
This change will give the search input of the saved search
modal focus, so the user needs one click less.

Give search input focus when saved search list is opening

---

graylog2-web-interface/src/logic/alerts/AggregationExpressionValidation.js

* Allow alert conditions with floating numbers
This got changed with the introduction of multiple conditions in 3.2.
The backend treats every value as Double anyhow.
* Use isFinite instead
(cherry picked from commit 6ca165d587c6976a7b2661a38f0c204574b8f3f3)

Allow alert conditions with floating numbers (#8268)

---

graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndexingHelper.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndicesAdapterES6.java
graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/IndexFieldTypePollerES6IT.java
graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/IndicesES6IT.java
graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/IndicesGetAllMessageFieldsES6IT.java
graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/MessagesES6IT.java
graylog2-server/src/main/java/org/graylog2/indexer/MongoIndexSet.java
graylog2-server/src/main/java/org/graylog2/indexer/indices/HealthStatus.java
graylog2-server/src/main/java/org/graylog2/indexer/indices/IndexMoveResult.java
graylog2-server/src/main/java/org/graylog2/indexer/indices/IndexSettings.java
graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java
graylog2-server/src/main/java/org/graylog2/indexer/indices/IndicesAdapter.java
graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
graylog2-server/src/main/java/org/graylog2/periodical/IndexRotationThread.java
graylog2-server/src/test/java/org/graylog2/indexer/MongoIndexSetTest.java
graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerIT.java
graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesGetAllMessageFieldsIT.java
graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesIT.java

This PR is extracting a `IndicesAdapter` interface from the `Indices` class, that allows us to separate the Elasticsearch-specific implementation details from the consumer of that interface.

Extract interface from `Indices` class, isolate ES-specific details.

---

graylog2-server/src/main/java/org/graylog2/indexer/cluster/Cluster.java

**Note: This is a backport of #8247 to `3.3`.**
Just filtering the list of nodes by requesting de nodeRole attribute when querying Elasticsearch and filtering out all those nodes that are not data nodes (that don't include "d" in nodeRole response)

Check only data nodes in Elasticsearch disk usage stats (3.3)

---

graylog2-web-interface/src/components/common/IconButton.jsx
graylog2-web-interface/src/views/components/widgets/ReplaySearchButton.jsx
graylog2-web-interface/src/views/components/widgets/WidgetHorizontalStretch.jsx
graylog2-web-interface/src/views/components/widgets/__snapshots__/Widget.test.jsx.snap

When using the tab navigation, the `WidgetHorizontalStretch` Icon captures the focus twice.
The first focus is on the `IconButton` the second focus is on the `Icon` itself due to the `tabIndex` prop. The same problem exists for the `ReplaySearchButton` because the `IconButton` is wrapped in a link.

Remove not needed tab index from `WidgetHorizontalStretch`

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewsResourceTest.java

Since the replacement of dashboards with view-based ones, we are not
posting an event when a dashboard is deleted anymore. This is important
e.g. for housekeeping of a user's start page.
This change is now adding back posting events whenever a dashboard is
deleted.

Post event when dashboard is deleted.

---

graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/ClusterAdapterES6.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java
graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/ClusterES6IT.java
graylog2-server/src/main/java/org/graylog2/indexer/cluster/Cluster.java
graylog2-server/src/main/java/org/graylog2/indexer/cluster/ClusterAdapter.java
graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/ClusterAllocationDiskSettingsFactory.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexerClusterResource.java
graylog2-server/src/test/java/org/graylog2/indexer/cluster/ClusterIT.java

This change is extracting a `ClusterAdapter` interface from the `Cluster` class containing ES-specific implementation details and creates an implementation class (`ClusterAdapterES6`) containing the current code.
During the extraction most of the signatures were kept intact, besides those which use the ES `Health.Status` class. It was replaced with a very simple own `HealthStatus` enum which is mappable 1:1 with the current implementation of `Health.Status`. It might make sense to move away from colors to more precise identifiers (e.g. "Healthy", "Degraded", "Unhealthy"). Due to the change of the return type of those methods it was also required to change some of the logic in the consumers of these classes, but it was attempted to keep those to a minimum in favor of later refactorings.

Extract interface from `Cluster` class.

---

graylog2-web-interface/packages/eslint-config-graylog/index.js

The ESLint rule [`jsx-a11y/label-has-associated-control`](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/label-has-associated-control.md) requires the following structure for input labels:
```
<label htmlFor="input-id">
The input label
<input id="input-id" />
</label>
```
We are usually not using this structure in our project, more common is:
```
<label htmlFor="input-id">The input label</label>
<input id="input-id" />
```
This PR is adjusting the ESLint rule, to allow either the nested format or the sibling structure.

Define less strict configuration for ESlint rule `jsx-a11y/label-has-associated-control`

---

UPGRADING.rst
graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java
graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java
graylog2-server/src/main/java/org/graylog2/rest/resources/search/KeywordSearchResource.java
graylog2-server/src/main/java/org/graylog2/rest/resources/search/RelativeSearchResource.java
graylog2-server/src/main/java/org/graylog2/rest/resources/sources/SourcesResource.java

In `3.2.0`, the Views API was introduced, offering extensive aggregation
capabilities. Since then, the previous aggregation API was not used by
the frontend anymore.
To free up time spent on maintaining another legacy API, those endpoints
are marked as deprecated and are removed in `4.0`, offering Graylog core
developers the chance to invest time on other parts of the product.
The deprecated endpoints include:
- `/search/universal/(absolute|relative|keyword)/`
- `terms-histogram`
- `histogram`
- `fieldhistogram`
- `stats`
- `termsstats`
- `terms`
- `/sources`
As well as the following methods from the `Searches` class:
- `fieldHistogram`
- `histogram`
- `terms`
- `termsHistogram`
- `termsStats`

Mark legacy aggregation API as deprecated.

---

graylog2-server/src/main/java/org/graylog/schema/AlertFields.java
graylog2-server/src/main/java/org/graylog/schema/ApplicationFields.java
graylog2-server/src/main/java/org/graylog/schema/AssociatedFields.java
graylog2-server/src/main/java/org/graylog/schema/AutonomousSystemFields.java
graylog2-server/src/main/java/org/graylog/schema/DestinationFields.java
graylog2-server/src/main/java/org/graylog/schema/EmailFields.java
graylog2-server/src/main/java/org/graylog/schema/EventFields.java
graylog2-server/src/main/java/org/graylog/schema/FileFields.java
graylog2-server/src/main/java/org/graylog/schema/GeoFields.java
graylog2-server/src/main/java/org/graylog/schema/GraylogSchemaFields.java
graylog2-server/src/main/java/org/graylog/schema/HostFields.java
graylog2-server/src/main/java/org/graylog/schema/HttpFields.java
graylog2-server/src/main/java/org/graylog/schema/NetworkFields.java
graylog2-server/src/main/java/org/graylog/schema/ProcessFields.java
graylog2-server/src/main/java/org/graylog/schema/ServiceFields.java
graylog2-server/src/main/java/org/graylog/schema/SessionFields.java
graylog2-server/src/main/java/org/graylog/schema/SourceFields.java
graylog2-server/src/main/java/org/graylog/schema/ThreatFields.java
graylog2-server/src/main/java/org/graylog/schema/TraceFields.java
graylog2-server/src/main/java/org/graylog/schema/UserFields.java
graylog2-server/src/main/java/org/graylog/schema/VendorFields.java

This change brings the Graylog Schema changes that were made on the 4.0 branch back to the 3.3 branch. These are needed for updates to the Palo Alto plugin.
These schema updates are needed for an update to the Palo Alto plugin which will will be covered in a separate PR.

Merge Graylog Schema changes from 4.0 back to 3.3

---

graylog2-web-interface/src/views/components/ViewActionsMenu.jsx
graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.jsx
graylog2-web-interface/src/views/components/sidebar/SideBar.test.jsx
graylog2-web-interface/src/views/components/sidebar/ViewDescription.jsx
graylog2-web-interface/src/views/components/views/ViewPropertiesModal.jsx

This PR implements the "Edit metadata" action for the saved searches search bar menu, which opens a modal to edit the title, description and summary.
It also:
* renames the "Edit" dashboard search bar action to "Edit metadata"
I think "Edit" is too generic. From a user's perspective: What is going to happen, will a click on the button display the search / widgets in an edit mode?
* adjusts the sidebar view description.
For an ad hoc search, an info will be displayed to save the search as a saved search / dashboard, to add a description / summary. On a dashboard / saved search the view description will include a view type specific placeholder, if a summary or description is not defined.
Regarding the tests for `SavedSearchControls`, I've tried to test if the edit modal opens, when clicking …

Support editing title, description and summary of a saved search

---

graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/AbsoluteValueWatermarkSettings.java
graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/ByteSize.java
graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/ClusterAllocationDiskSettingsFactory.java
graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/NodeDiskUsageStats.java
graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/SIUnitParser.java
graylog2-server/src/test/java/org/graylog2/indexer/cluster/health/ClusterAllocationDiskSettingsFactoryTest.java
graylog2-server/src/test/java/org/graylog2/indexer/cluster/health/SIUnitParserTest.java
graylog2-server/src/test/java/org/graylog2/periodical/IndexerClusterCheckerThreadTest.java

In order to avoid dependencies to specific ES libraries in core, this PR
is replacing the usage of the `ByteSizeValue` class with an own
interface and a stripped down parser (`SIUnitParser`). The class itself
is used only to convert SI units from strings to longs (using the
`getBytes` method) and does not use/provide any ES-specific
functionality.

Replacing usage of `ByteSizeValue` with own, stripped-down class.

---

graylog2-web-interface/src/views/components/widgets/MoveWidgetToTab.jsx
graylog2-web-interface/src/views/components/widgets/MoveWidgetToTabModal.jsx
graylog2-web-interface/src/views/components/widgets/Widget.jsx
graylog2-web-interface/src/views/logic/views/AddNewWidgetsToPositions.js
graylog2-web-interface/src/views/logic/views/AddNewWidgetsToPositions.test.js
graylog2-web-interface/src/views/logic/views/CopyWidgetToDashboard.js
graylog2-web-interface/src/views/logic/views/CopyWidgetToDashboard.test.js
graylog2-web-interface/src/views/logic/views/FindWidgetAndQueryIdInView.js
graylog2-web-interface/src/views/logic/views/MoveWidgetToTab.Dashboard.fixture.json
graylog2-web-interface/src/views/logic/views/MoveWidgetToTab.Search.fixture.json
graylog2-web-interface/src/views/logic/views/MoveWidgetToTab.js
graylog2-web-interface/src/views/logic/views/MoveWidgetToTab.test.js
graylog2-web-interface/src/views/logic/views/UpdateSearchForWidgets.js
graylog2-web-interface/src/views/logic/views/UpdateSearchForWidgets.test.js
graylog2-web-interface/src/views/logic/views/__snapshots__/AddNewWidgetsToPositions.test.js.snap
graylog2-web-interface/src/views/logic/views/__snapshots__/CopyWidgetToDashboard.test.js.snap
graylog2-web-interface/src/views/logic/views/__snapshots__/MoveWidgetToTab.test.js.snap
graylog2-web-interface/src/views/logic/views/__snapshots__/UpdateSearchForWidgets.test.js.snap
graylog2-web-interface/src/views/logic/views/types.js
graylog2-web-interface/src/views/stores/CurrentViewStateStore.js

Add new menu item to widget menu: `Move to Page`. When clicking the user will see a modal
where he can select the target page. Optionally he can decide to keep a copy of the widget
on the current page. After selecting the target page he clicks on `Select`. The widget will
be moved to the new page and the active page will be set to the target query.
A user was able to copy a widget from a search to the first page of a dashboard. But the widget
was stuck now there. There was no possibility to move the widget to a different page of the dashboard.
- Create a dashboard
- create a widget on the first page
- move the widget to a different page
Fixes #8152

Move widget to tab

---

graylog2-web-interface/src/views/components/visualizations/number/AutoFontSizer.jsx

**This PR needs a backport for 3.3.1 (or 3.3.2)**
As described in https://github.com/Graylog2/graylog2-server/issues/7563 the single number widget can flicker when the widget has a small height.
This happened because the font size always changed between `11px` and `10px`. in both cases the defined tolerance did not matched. This PR is fixing the issue by increasing the tolerance. It also refactors the `AutoFontSizer` code style.
The issue is currently not occurring on the master branch, because https://github.com/Graylog2/graylog2-server/pull/8064 changed the widget content height. You can reproduce the error, by checking out the commit `ed8998c3251` and following the steps in the mentioned issue.
Fixes https://github.com/Graylog2/graylog2-server/issues/7563

Prevent single number widget flickering

---

graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/SearchesAdapterES6.java
graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/SearchesAdapterES6Test.java
graylog2-server/src/main/java/org/graylog2/alerts/types/FieldValueAlertCondition.java
graylog2-server/src/main/java/org/graylog2/indexer/results/FieldStatsResult.java
graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java
graylog2-server/src/test/java/org/graylog2/alerts/types/FieldValueAlertConditionTest.java
graylog2-server/src/test/java/org/graylog2/indexer/searches/SearchesIT.java

In order to prevent the `FieldStatsResult` value class from knowing
about the ES result details, its instantiation details are moved to the
storage module.

Moving creation of `FieldStatsResult` to storage module.

---

graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java

bind new IndexToolsAdapter to the ES6 implementation, fails at runtime otherwise due to missing binding

Bind IndexToolsAdapter to ES6 implementation

---

graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/migrations/V20170607164210_MigrateReopenedIndicesToAliasesClusterStateES6.java
graylog2-server/src/main/java/org/graylog2/migrations/V20170607164210_MigrateReopenedIndicesToAliases.java

This PR extracts the dependency on `JestClient` from a migration class (`V20170607164210_MigrateReopenedIndicesToAliases`)
We want to remove all Elasticsearch dependencies from the server core. At the same time we ant to touch old migrations as little as possible, especially if they have no automatic test coverage like this one.
We there fore decided to only extract the technical dependency on `JestClient` by defining a custom interface only for this migration. The logical dependency on the JSON format of the client's response can remain in the migration class, because that should never have to change.
Started server locally and debugged into the code to verify that it runs.

Extract jestclient dependency from migration

---

graylog2-web-interface/src/views/components/contexts/HighlightingRulesContext.jsx
graylog2-web-interface/src/views/components/contexts/HighlightingRulesProvider.jsx
graylog2-web-interface/src/views/components/contexts/HighlightingRulesProvider.test.jsx
graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTable.test.jsx.snap
graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTableEntry.test.jsx.snap
graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.jsx
graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.test.jsx
graylog2-web-interface/src/views/components/messagelist/__snapshots__/CustomHighlighting.test.jsx.snap
graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRules.jsx
graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRules.test.jsx
graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx

**This is a backport of #8276 for 3.3**
This PR creates a context for the highlighting rules. Its value is being provided by the `HighlightingRulesProvider` which connects to the `HighlightingRulesStore`.
The `HighlightingRulesProvider` is being used in the `ExtendedSearchPage`, this way we don't need to connect the `HighlightingRulesStore` in `CustomHighlighting` and `HighlightingRules`.
We should reduce the times we call `connect` -> `render` and `connect` -> `shouldComponentUpdate`. Currently `render` is being called over 1000 times and `shouldComponentUpdate` over 600 times on the default search page.
Just removing `connect` from `UserTimezoneTimestamp` (https://github.com/Graylog2/graylog2-server/pull/7836) and `CustomHighlighting` reduces the calls of `connect` -> `render` to ~50 …

Create separate context for highlighting rules (Backport of #8276 for 3.3)

---

graylog2-web-interface/src/views/components/aggregationbuilder/AggregationBuilderPropTypes.js
graylog2-web-interface/src/views/components/visualizations/ChartData.js
graylog2-web-interface/src/views/components/visualizations/area/AreaVisualization.jsx
graylog2-web-interface/src/views/components/visualizations/bar/BarVisualization.jsx
graylog2-web-interface/src/views/components/visualizations/heatmap/HeatmapVisualization.jsx
graylog2-web-interface/src/views/components/visualizations/line/LineVisualization.jsx
graylog2-web-interface/src/views/components/visualizations/pie/PieVisualization.jsx
graylog2-web-interface/src/views/components/visualizations/scatter/ScatterVisualization.jsx
graylog2-web-interface/src/views/components/visualizations/worldmap/WorldMapVisualization.jsx

This PR unifies the prop type definitions for all visualizations by creating a custom `AggregationResult` prop type for the `data` attribute.
Removing all prop type errors for visualization components.

Unify visualization prop types

---

graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/ScrollResultES6.java

In #8336, the `ScrollResultES6.Factory` was introduced. Unfortunately relevant annotations for assisted injection were forgotten, leading to guice not being able to properly bind it.
This PR is adding the required annotations to fix it.

Fixing `ScrollResultES6` factory's assisted injection annotations.

---

graylog2-web-interface/src/views/components/datatable/MessagesTable.jsx
graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTable.test.jsx.snap

It is currently possible, that the content of a data table is not being displayed in a readable format. This is also a problem, when generating a report:
One solution I thought about is using `word-break: normal;` instead of  `word-break: break-all;`
But this can be a problem when the table contains a value like a very long id.
I also thought about increasing the table width (in the context of reports) but this does not solve the problem, the second column just gets larger.
For now I've just defined a `min-width` for the table columns to slightly increase the readability.

Add min width for data table columns

---

graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java

In a previous PR, the `CountsAdapter` was extracted, but no binding was created, leading to errors whenever the `Counts` class needs to be injected, e.g. the index set details page.
This change is creating the required binding.

Adding missing binding for `CountsAdapter`.

---

graylog2-server/src/test/resources/org/graylog/testing/graylognode/Dockerfile

Otherwise, the test build will fail on systems that still
have an older version of the openjdk image around.
(debian stretch in my case)
Our official docker image has been using buster since the 3.1
release.
For reference:
```
$ docker image ls |grep jdk
openjdk                                         8-jre-slim-buster   778bc46b8d12        4 weeks ago         184MB
openjdk                                         8-jre-slim          54567f06e0e8        17 months ago       204MB
```

Use an openjdk docker image with a fixed debian version

---

.github/workflows/rebase.yml

This change is doing the following:
- updating the `/rebase` action to v1.3.1, to fix a couple of bugs (e.g. returning the error if the rebase failed)
- adding an inline condition to skip the action if no `/rebase` was specified

Update `/rebase` action.

---

graylog2-web-interface/src/components/sidecars/common/OperatingSystemIcon.jsx

This PR is updating the `OperatingSystemIcon` icon props, which changed with https://github.com/Graylog2/graylog2-server/pull/8298

Fix OperationSytemIcon icon props

---

graylog2-web-interface/src/components/common/EntityListItem.jsx
graylog2-web-interface/src/views/components/ViewActionsMenu.jsx

This PR is fixing the prop type errors for the `EntityListItem` prop `contentRow`. It also avoids throwing a prop type error for the `ViewActionsMenu` `view` prop, by removing the `Proptypes.instanceOf` check.
Fixes: #7303

Fixing `ViewActionsMenu` and `EntityListItem` prop type errors

---

graylog2-server/src/main/java/org/graylog/events/notifications/NotificationGracePeriodService.java
graylog2-server/src/test/java/org/graylog/events/processor/notification/NotificationGracePeriodServiceTest.java

If events continue to occur, while notifications are suppressed by an
active grace period, they will constantly reset the grace period timer
and will keep the grace period active.
Regression introduced with bugfix for #8065
Fixes #8365

Don't reset grace period timer while in grace period

---

graylog2-web-interface/src/components/common/LoadingIndicator.jsx

With https://github.com/Graylog2/graylog2-server/pull/8398 I defined a dynamic width for the loading indicator, but forgot to adjust the static positioning.
With this PR we center the loading indicator dynamically.

Dynamically center search page loading indicator

---

graylog2-web-interface/src/views/components/Select.jsx
graylog2-web-interface/src/views/components/aggregationbuilder/NumberVisualizationConfiguration.jsx
graylog2-web-interface/src/views/components/aggregationbuilder/SortSelect.jsx
graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/BarVisualizationConfiguration.test.jsx.snap
graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/SeriesSelect.test.jsx.snap
graylog2-web-interface/src/views/components/widgets/SortDirectionSelect.jsx

We have or own `Select` component for the search, which has e.g. its own styling. There were still a few cases, where we use the `Select` component from `react-select`.

Replace direct imports of react-select select with custom select

---

graylog2-web-interface/src/components/gettingstarted/GettingStarted.jsx
graylog2-web-interface/src/pages/GettingStartedPage.jsx

The getting stared guide currently has two scrollbars, which are always visible. This PR is fixing the problem by implementing a grid layout.
Tested with all mayor browsers and IE11

Fix getting started guide page scroll behaviour

---

graylog2-web-interface/src/views/components/aggregationbuilder/AggregationBuilder.jsx
graylog2-web-interface/src/views/components/datatable/DataTable.test.jsx
graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTable.test.jsx.snap
graylog2-web-interface/src/views/components/visualizations/bar/BarVisualization.jsx
graylog2-web-interface/src/views/components/visualizations/number/NumberVisualization.test.jsx
graylog2-web-interface/src/views/components/visualizations/number/__snapshots__/NumberVisualization.test.jsx.snap
graylog2-web-interface/src/views/components/widgets/Widget.jsx
graylog2-web-interface/src/views/logic/aggregationbuilder/Pivot.js

As described in #7167 a bar chart with a time range and only one search result, results in one very small bar. This PR is fixing the problem by defining a width for the bar. The width can't be defined in px, it has to be the unit of the x axis (in this case ms).
Fixes #7167

 Define bar width if bar chart contains only data for a single date

---

distribution/src/main/assembly/graylog.xml
full-backend-tests/pom.xml
graylog-storage-elasticsearch6/assembly.xml
graylog-storage-elasticsearch6/pom.xml
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/ClusterAdapterES6.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/CountsAdapterES6.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndexFieldTypePollerAdapterES6.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndexToolsAdapterES6.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndicesAdapterES6.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/MessagesAdapterES6.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/MultiSearch.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/NodeAdapterES6.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Scroll.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/jest/GraylogJestRetryHandler.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/jest/JestClientProvider.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/jest/JestUtils.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/migrations/V20170607164210_MigrateReopenedIndicesToAliasesClusterStateES6.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackend.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/export/JestWrapper.java
graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/ClusterES6IT.java
graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/MessagesES6IT.java
graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/ScrollResultES6IT.java
graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/jest/JestClientProviderTest.java
graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/jest/JestUtilsTest.java
graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/testing/ClientES6.java
graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/testing/ElasticsearchInstanceES6.java
graylog2-server/pom.xml
graylog2-server/src/main/java/org/graylog2/bindings/ElasticsearchModule.java

This PR is moving over the remaining classes required to instantiate and wire a Jest client to the storage module. It also moves over maven dependencies for Elasticsearch and Jest. Version properties are still kept in the parent pom, those can be moved over later.
Requires #8361 to be merged before.
Fixes #8155.
Fixes #8156.

Moving Jest infrastructure classes to storage module.

---

graylog2-server/src/main/java/org/graylog/events/notifications/NotificationGracePeriodService.java
graylog2-server/src/test/java/org/graylog/events/processor/notification/NotificationGracePeriodServiceTest.java

If events continue to occur, while notifications are suppressed by an
active grace period, they will constantly reset the grace period timer
and will keep the grace period active.
Regression introduced with bugfix for #8065
Fixes #8365
(cherry picked from commit 026178950e3d9df49e2c9cb24afc9660bbbd62a5)

Don't reset grace period timer while in grace period (#8366)

---

graylog2-web-interface/src/views/components/Field.jsx
graylog2-web-interface/src/views/components/Field.test.jsx
graylog2-web-interface/src/views/components/widgets/MessageTable.jsx

_This PR needs a backport for 3.3_
The head of a message table is currently not being displayed in the non interactive mode (e.g. in the dashboard full screen view).
Displaying the table head is fixing layout problems similar to the problem described here: https://github.com/Graylog2/graylog2-server/pull/8334

Display message table head in non interactive mode

---

graylog2-web-interface/src/views/components/Field.jsx
graylog2-web-interface/src/views/components/Field.test.jsx
graylog2-web-interface/src/views/components/widgets/MessageTable.jsx

_This is a backport of #8385 for 3.3_
The head of a message table is currently not being displayed in the non interactive mode (e.g. in the dashboard full screen view).
Displaying the table head is fixing layout problems similar to the problem described here: https://github.com/Graylog2/graylog2-server/pull/8334

Display message table head in non interactive mode (Backport of #8385 for 3.3)

---

graylog2-web-interface/src/views/components/aggregationbuilder/SortSelect.jsx
graylog2-web-interface/src/views/components/widgets/SortDirectionSelect.jsx

As described in #7198 the value of the sort and sort direction select in the aggregation builder persist when the related row pivot gets removed.
This PR is fixing the issue by defining an empty string for the select value, instead of undefined, when the provided value is empty.
Fixes #7198

Reset aggregation builder sort and sort direction select when related row pivot gets removed

---

graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/ObjectMapperProvider.java
graylog2-server/src/main/java/org/graylog2/utilities/GRN.java
graylog2-server/src/main/java/org/graylog2/utilities/GRNDeserializer.java
graylog2-server/src/main/java/org/graylog2/utilities/GRNKeyDeserializer.java
graylog2-server/src/main/java/org/graylog2/utilities/GRNRegistry.java
graylog2-server/src/main/java/org/graylog2/utilities/GRNType.java
graylog2-server/src/test/java/org/graylog2/utilities/GRNRegistryTest.java
graylog2-server/src/test/java/org/graylog2/utilities/GRNTest.java

GRNs (Graylog Resource Names) are like URNs that we use for internal purposes only
GRN format:
`grn:<cluster>:<tenant>:<scope>:<type>:<entity>`
Examples:
`grn::::stream:000000000001`
`grn:local:0:internal:stream:000000000001`

Add GRN support

---

graylog2-web-interface/src/components/graylog/Tooltip.jsx
graylog2-web-interface/src/views/components/searchbar/AbsoluteTimeRangeSelector.jsx
graylog2-web-interface/src/views/components/searchbar/AbsoluteTimeRangeSelector.test.jsx
graylog2-web-interface/src/views/components/searchbar/DateInputWithPicker.jsx
graylog2-web-interface/src/views/components/searchbar/KeywordTimeRangeSelector.jsx
graylog2-web-interface/src/views/components/searchbar/KeywordTimeRangeSelector.test.jsx
graylog2-web-interface/src/views/components/searchbar/SearchBarForm.jsx
graylog2-web-interface/src/views/components/searchbar/SearchBarForm.test.jsx

With this PR we are displaying an error message when the validation of a time range input in the search bar fails. The error message is being displayed as a tooltip above the input.
It also adds a validation for the absolute time range selector, to throw an error if the date "from" is after the date "to".
Fixes #7191

Display error message for search bar time range inputs

---

full-backend-tests/src/test/java/org/graylog/storage/elasticsearch6/ElasticsearchInstanceES6Factory.java
graylog2-server/src/test/java/org/graylog/testing/completebackend/ElasticsearchInstanceFactory.java
graylog2-server/src/test/java/org/graylog/testing/completebackend/GraylogBackend.java
graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerConfig.java
graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerFactory.java
graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeInstance.java

The server will need a config setting to decide which Elasticsearch driver to bind.
This adds a `version` property to `ElasticsearchInstanceFactory`, the value of which is passed to server as an environment variable.

Pass env var GRAYLOG_ELASTICSEARCH_VERSION to NodeInstance

---

graylog2-web-interface/flow-typed/npm/react-router_vx.x.x.js
graylog2-web-interface/src/stores/inputs/InputTypesStore.js
graylog2-web-interface/src/util/DocsHelper.js

This PR adds some changes to support current work on Forwarder UI:
- Add Flow definition of react-router's Link
- Add `InputTypes` and `InputDescriptions` Flow types
- Add URL to lookup tables in `DocumentationHelper`

Support Forwarder wizard

---

graylog2-server/src/main/java/org/graylog/security/BuiltinCapabilities.java
graylog2-server/src/main/java/org/graylog/security/Capability.java
graylog2-server/src/main/java/org/graylog/security/CapabilityDescriptor.java
graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
graylog2-server/src/main/java/org/graylog/security/DefaultGrantPermissionResolver.java
graylog2-server/src/main/java/org/graylog/security/GrantDTO.java
graylog2-server/src/main/java/org/graylog/security/rest/EntitySharesResource.java
graylog2-server/src/main/java/org/graylog/security/shares/DefaultGranteeService.java
graylog2-server/src/main/java/org/graylog/security/shares/EntitySharePrepareRequest.java
graylog2-server/src/main/java/org/graylog/security/shares/EntitySharePrepareResponse.java
graylog2-server/src/main/java/org/graylog/security/shares/EntityShareRequest.java
graylog2-server/src/main/java/org/graylog/security/shares/EntitySharesService.java
graylog2-server/src/main/java/org/graylog2/utilities/GRNRegistry.java
graylog2-server/src/test/java/org/graylog/security/DBGrantServiceTest.java
graylog2-server/src/test/resources/org/graylog/security/grants.json

- Exclude sharing user in active shares and available grantees. Also add "sharing_user" field to the response.
- Refactor capabilities into an enum and CapabilityDescriptor
Since capabilities are not dynamic, we don't need to use a GRN for them
and can use an enum. Permissions for a capability will be pluggable, but
that's still possible.

Exclude sharing user from active shares and refactor capabilities

---

graylog2-server/src/main/java/org/graylog2/inputs/codecs/SyslogCodec.java
graylog2-server/src/test/java/org/graylog2/inputs/codecs/SyslogCodecTest.java

Currently, when reading Syslog input, incoming messages with `AUTH` and `AUTHPRIV` facility saved as literal field `security/authorization`. This results in losing a distinction between `AUTH` and `AUTHPRIV` facilities. It is based on a straightforward interpretation of https://tools.ietf.org/html/rfc5424#section-6.2.1
`AUTHPRIV` however, could contain more sensitive information so might need to be treated differently in certain cases. 
I am the author and maintainer of https://github.com/wizecore/graylog2-output-syslog
and this PR is an enhancement which corresponds to the following issue: https://github.com/wizecore/graylog2-output-syslog/issues/35
Minor change, tested by building graylog2 server JAR and running it with local distribution. As a result, the new field `facility_num` added …

Write facility_num to facilitate direct translation of facility

---

graylog2-server/src/main/java/org/graylog2/storage/VersionAwareStorageModule.java
graylog2-server/src/main/java/org/graylog2/storage/providers/CountsAdapterProvider.java

`Counts` couldn't be injected into `IndexerOverviewResource`, because we forgot to add a version-aware provider implementation for `CountsAdapter`.

Add missing CountsAdapterProvider

---

graylog2-web-interface/src/components/permissions/EntityShareModal.jsx
graylog2-web-interface/src/components/permissions/EntityShareSettings.jsx
graylog2-web-interface/src/stores/permissions/EntityShareStore.js

Prior to this change, we send the first prepare request with following
payload:
```{ selected_grantee_capabilities: {} }```
But this payload was also send if all grantee where removed, which
mimics the initial prepare request leading to have all removed grantee
back in selected_grantee_capabilities.
This change will adjust the initial request sending a empty object as
payload so the backend can distinguish between "remove all grantee" and
initial prepare request.

Change initial payload for first prepare request

---

graylog-storage-elasticsearch6/pom.xml
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/MessagesAdapterES6.java
graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/MessagesAdapterES6Test.java
graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/MessagesES6IT.java
graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/testing/ClientES6.java
graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/testing/FixtureImporterES6.java
graylog-storage-elasticsearch7/pom.xml
graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Elasticsearch7Module.java
graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MessagesAdapterES7.java
graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ParsedElasticsearchException.java
graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/MessagesES7IT.java
graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/ParsedElasticsearchExceptionTest.java
graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ClientES7.java
graylog2-server/src/main/java/org/graylog2/indexer/messages/ChunkedBulkIndexer.java
graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
graylog2-server/src/main/java/org/graylog2/indexer/messages/MessagesAdapter.java
graylog2-server/src/test/java/org/graylog/testing/elasticsearch/Client.java
graylog2-server/src/test/java/org/graylog/testing/elasticsearch/ElasticsearchInstance.java
graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesBulkIndexRetryingTest.java
graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesIT.java
graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesRetryWaitTest.java
graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesTest.java

This PR is implementing the `MessagesAdapter` for ES7. It also performs quite extensive refactoring of the `Messages` <-> `MessagesAdapter` relationship. 
Before this PR, retrying logic was buried in the `MessagesAdapter#bulkIndex` call. This change is pulling it upwards into the `Messages` class, which is now retrying `bulkIndex` calls for thrown `IOException`s as well as indexing errors (e.g. index blocks due to target indices being read-only or the node being in flood stage). This is implemented by adding an abstraction for indexing errors (`Messages.IndexingError`) which is instantiated by the adapters but evaluated by the `Messages` class which decides how to proceed based on the error type.
Chunk splitting due to excessive payload sizes is still considered to be a concern of the …

Implement `MessagesAdapter` for ES7.

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java

This change is effectively reverting ffecb94e. What seemed to be a good idea then (returning our wrapped exception earlier, from the client) turned out to be breaking the 413 handling as we expect to have access to the raw exception coming from the client there.
Therefore this commit is reverting this change in order to restore functionality, a future change could improve throwing a wrapped exception early again, after fixing its consumers.

Use correct ES exception class in storage adapter.

---

graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java
graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping7.java

In ES7, the `template` field in an index mapping template is deprecated.
This results in these errors whenever a template is created for ES7:
```
2020-07-09 14:46:08,160 WARN : org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient - request [PUT http://localhost:33319/_template/graylog-test-internal?master_timeout=30s] returned 1 warnings: [299 Elasticsearch-7.8.0-757314695644ea9a1dc2fecd26d1a43856725e65 "Deprecated field [template] used, replaced by [index_patterns]"
```
This change is using the correct field name `index_patterns` instead.

Use correct setting name for ES template target.

---

graylog-project-parent/pom.xml
graylog2-server/pom.xml

This allows us to use the Mockito JUnit 5 extension in tests.

Add mockito-junit-jupiter dependency

---

graylog2-web-interface/src/components/common/IfPermitted.jsx
graylog2-web-interface/src/components/common/IfPermitted.test.jsx
graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListConfig.test.jsx.snap
graylog2-web-interface/src/components/navigation/Navigation.jsx
graylog2-web-interface/src/components/navigation/Navigation.test.jsx
graylog2-web-interface/src/components/navigation/SystemMenu.test.jsx
graylog2-web-interface/src/routing/App.jsx

_We need to merge the related enterprise PR first_
This PR implements the `CurrentUserContext` for the `IfPermitted` and `Navigation` component.
We should replace the usage of `CurrentUserStore` step by step. Using the `CurrentUserContext` in `IfPermitted` makes is easier to test components which use `IfPermitted` and the `CurrentUserContext`.

Implement `CurrentUserContext` for `IfPermitted` and `Navigation` component

---

graylog2-web-interface/src/components/common/PageSizeSelect.jsx
graylog2-web-interface/src/components/permissions/EntityShareModal.jsx
graylog2-web-interface/src/components/permissions/EntityShareModal.test.jsx
graylog2-web-interface/src/components/permissions/GranteesList.jsx
graylog2-web-interface/src/components/permissions/GranteesListItem.jsx
graylog2-web-interface/src/logic/permissions/GRN.js

This PR contains the following improvements for the entity share modal:
- rename modal cancel button to "Discard changes'
- rename grantee delete button to "Remove sharing for user x"
- create separate file for GRN generation
- display page size select for grantees list, depending on grantees amount

Further improvements for entity share modal

---

graylog2-server/src/main/java/org/graylog/security/authzroles/AuthzRoleDTO.java
graylog2-server/src/main/java/org/graylog/security/authzroles/AuthzRolesResource.java
graylog2-server/src/main/java/org/graylog/security/authzroles/PaginatedAuthzRolesService.java

Prior to this change, we did not have a paginated access
to all roles and to the roles of a user.
This change is adding a new resource which will query all
roles and the roles of a user.

Create a basic AuthzRole resource

---

graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/IndicesES6IT.java
graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/testing/ClientES6.java
graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ClientES7.java
graylog2-server/src/test/java/org/graylog/testing/elasticsearch/Client.java

Since we won't support ES 5 anymore after 4.0, we can remove this test.
The test stood out, because it would only run for ES version 5, which would never happen after we bumped the default version for integration tests to 6.8. So we decided to remove it entirely.

Remove superfluous es 5 test

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java
graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java

Before this change, a disallowed parameter (alias) was used for remove alias actions during the deflector cycle on ES7. This change removes it and adds a test making sure that deflector cycling works for all storage driver modules.

Fixing remove alias action during deflector cycle for ES7.

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Elasticsearch7Module.java
graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/cluster/ClusterStateApi.java
graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/migrations/V20170607164210_MigrateReopenedIndicesToAliasesClusterStateES7.java
graylog2-server/src/main/java/org/graylog2/migrations/V20170607164210_MigrateReopenedIndicesToAliases.java

In one of our migrations, we are using ES-specific code to determine reopened indices which need migration. We have extracted the ES-specifics into an interface that needs to be implemented by each storage driver module. This PR is adding it for the ES7 module.

Adding ES7 adapter for reopened indices migration.

---

graylog2-web-interface/src/views/components/sidebar/ContentColumn.jsx

The sidebar content column height is currently broken, due to a missing semicolon.

Add missing semicolon for sidebar content column styling.

---

graylog2-web-interface/src/views/components/Field.jsx
graylog2-web-interface/src/views/components/Field.test.jsx
graylog2-web-interface/src/views/components/widgets/MessageTable.jsx
graylog2-web-interface/src/views/components/widgets/MessageTable.test.jsx

**This PR needs a backport for 3.3**
Before https://github.com/Graylog2/graylog2-server/pull/8385 the field names were not being displayed in the message table head, in the non interactive mode. The PR fixed the problem, but introduced a new bug, by displaying the field name twice under some circumstances. (https://github.com/Graylog2/graylog2-server/issues/8500, https://github.com/Graylog2/graylog2-server/issues/8483)
This PR reverts the previous `Field` component changes and fixes the `Field` component usage for the `MessageTable`.
Fixes: #8483

Fix `Field` component usage for `MessageTable` head

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Elasticsearch7Module.java
graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java
graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/RestHighLevelClientProvider.java
graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ElasticsearchInstanceES7.java

Before this PR every instance of `ElasticsearchClient` constructed its own instance of `RestHighLevelClient`. This PR changes that so that `ElasticsearchClient` doesn't have to care about how to construct `RestHighLevelClient`, let alone manage its  lifecycle. Instead a Guice provider was added that is managed as a singleton. That provider also registers a hook on `GracefulShutdownService` to close the client when the server shuts down.
`RestHighLevelClient` should be closed when it's not needed anymore. See https://www.elastic.co/guide/en/elasticsearch/client/java-rest/master/java-rest-high-getting-started-initialization.html
Since it's thread safe and its underlying low level client manages a connection pool, we should only have one instance of it to optimize performance.
Debugged on …

Manage singleton for RestHighLevelClient

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java
graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java

This change is fixing retrieval of index stats and adds a test case for it. Index stats retrieval was broken, due to returning a json node that got prefixed to the `indices` key twice. This was noticed due to the index set stats page showing no indices.

Fix index stats retrieval for ES7.

---

graylog2-server/src/main/java/org/graylog2/rest/ScrollChunkWriter.java

Since `ScrollChunk` is an interface now, `ScrollChunkWriter#isWritable` has to check, if the passed type *implements* `ScrollChunk` instead of checking that it *is* `ScrollChunk`
#8336 turned `ScrollChunk` into an interface, but we forgot to reflect that in `ScrollChunkWriter#isWritable`.

Reflect that ScrollChunk was turned into an interface in ScrollChunkWriter#isWritable 

---

graylog2-web-interface/src/logic/permissions/EntityShareState.fixtures.json
graylog2-web-interface/src/logic/permissions/EntityShareState.js
graylog2-web-interface/src/logic/permissions/__snapshots__/EntityShareState.test.js.snap

Prior to this change, the JSON response of the prepare
request returned missing_permissions_on_dependencies,
but the JSON converter code still expected missing_dependcies.
This change will rename the JSON properties.

Rename missing_dependencies property in JSON response

---

graylog-storage-elasticsearch6/pom.xml
graylog-storage-elasticsearch7/pom.xml

The Elasticsearch driver modules don't need additional declarations for log4 and slf4j, as they only ever run as part of the server process, which will provide them.
In addition two duplicate declarations were removed.

Clean up es module poms

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/SearchRequestFactory.java
graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/SearchRequestFactoryTest.java
graylog2-server/src/test/java/org/graylog2/indexer/EventsIndexMappingTest.java
graylog2-server/src/test/java/org/graylog2/utilities/AssertJsonPath.java

Before this change, a subtle bug was introduced by wrong optional chaining. The effect was that the time range was included in a created search only if the filter query string is present and not a wildcard.
This change is fixing that by streamlining filter creation and addition to the search source builder.

Unconditionally include time range filter in created search for ES7.

---

graylog2-server/pom.xml
graylog2-server/src/main/java/org/graylog2/rest/resources/system/ldap/LdapResource.java
graylog2-server/src/main/java/org/graylog2/security/ldap/LdapConnector.java
graylog2-server/src/main/java/org/graylog2/security/realm/LdapUserAuthenticator.java
graylog2-server/src/test/java/org/graylog2/security/ldap/LdapConnectorSSLTLSIT.java
graylog2-server/src/test/java/org/graylog2/security/ldap/LdapConnectorTest.java
graylog2-server/src/test/java/org/graylog2/security/realm/LdapUserAuthenticatorTest.java
pom.xml

**Note: This needs a backport to `v3.3.x`**
Before this change, SSL certificates used to secure the connection between Graylog and an LDAP server used for authentication over a SSL/TLS-secured connection were not validated, even if the `Allow self-signed certificates` option was left unchecked.
This change is implementing SSL certificate validation by configuring a trust manager that uses the default keystore to validate certificates against. In addition, it consolidates different places where the `LdapConnectionConfig` was created.
Fixes #5906.

Implementing SSL certificate validation for LDAP authentication.

---

graylog-storage-elasticsearch6/pom.xml
graylog-storage-elasticsearch7/pom.xml
graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java
graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ClientES7.java

This should include the latest version of the shaded dependencies from `graylog-shaded` and thus resolve the logging error described in #8509.
`org.apache.logging` had been relocated in previous versions of `graylog-shaded`. This led to a logged error, because multiple instances of `org.apache.logging.log4j.LogManager` were configured. The configuration happens in a static constructor and due to the relocation we had multiple class definitions in multiple packages, which weren't properly configured.
The relocation was removed so that we should only have one properly configured `LogManager` again: https://github.com/Graylog2/graylog-shaded/pull/1.
In addition we added a suffix to the shaded dependencies' version so that we can deploy new artifacts without bumping the underlying version for …

Bump shaded Elasticsearch versions to avoid logging errors

---

graylog2-web-interface/src/views/components/Field.jsx
graylog2-web-interface/src/views/components/Field.test.jsx
graylog2-web-interface/src/views/components/widgets/MessageTable.jsx
graylog2-web-interface/src/views/components/widgets/MessageTable.test.jsx

**Backport for 3.3 of #8570**
Before https://github.com/Graylog2/graylog2-server/pull/8385 the field names were not being displayed in the message table head, in the non interactive mode. The PR fixed the problem, but introduced a new bug, by displaying the field name twice under some circumstances. (https://github.com/Graylog2/graylog2-server/issues/8500, https://github.com/Graylog2/graylog2-server/issues/8483)
This PR reverts the previous `Field` component changes and fixes the `Field` component usage for the `MessageTable`.
Fixes: #8483

Fix `Field` component usage for `MessageTable` head (3.3)

---

graylog2-web-interface/src/components/ldap/LdapComponent.jsx

`untrusted` is closer to the truth

Improve naming

---

graylog2-server/src/main/java/org/graylog/security/authzroles/BuiltinRole.java
graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java
graylog2-server/src/main/java/org/graylog2/migrations/V20200722110800_AddBuiltinRoles.java
graylog2-server/src/main/java/org/graylog2/plugin/security/PluginPermissions.java
graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java

The new permissions system requires a way to
create entities, before they can be shared via grants.
These roles are meant to provide creation rights for
topics that are currently covered with the new grants system.

Add new creator roles

---

graylog2-web-interface/src/components/users/UserCreate/TimezoneFormGroup.jsx

Formik is rerendering every key stroke. But react-select
is rendering rather slow. So we use `FastField` which is
implementing shouldComponentUpdate for that field.
Now react-select is only rendered when necessary.

Fix performance problems with react-select and formik

---

graylog2-server/src/main/java/org/graylog2/Configuration.java
graylog2-server/src/main/java/org/graylog2/shared/security/tls/DefaultTLSProtocolProvider.java
misc/graylog.conf

The default TLS protocol setting introduced with PR #7130
contained TLSv1.3.
TLS1.3 only worked for netty based inputs when openssl was used as a tls
provider.
This change builds the default based on what is supported by the
currently running JRE.
Fixes #7726

Find a better default for `enabled_tls_protocols`

---

graylog2-server/src/main/java/org/graylog2/Configuration.java
graylog2-server/src/main/java/org/graylog2/shared/security/tls/DefaultTLSProtocolProvider.java
misc/graylog.conf

The default TLS protocol setting introduced with PR #7130
contained TLSv1.3.
TLS1.3 only worked for netty based inputs when openssl was used as a tls
provider.
This change builds the default based on what is supported by the
currently running JRE.
Fixes #7726
(cherry picked from commit 90e6b0b)

 Find a better default for `enabled_tls_protocols` (3.3)

---

graylog2-server/src/main/java/org/graylog2/users/PaginatedUserService.java
graylog2-web-interface/src/logic/users/UserOverview.js
graylog2-web-interface/src/pages/UserDetailsPage.jsx

Prior to this change, there was no way to retrive a paginated list of
users by there username. This is needed for the Team Details Page
where we want to display the Users of Team.
Also we add `name` and `description` to UserOverview, which is simply
giving `username` and `fullname`.
This change will also fix everloading UserDetailsPage and a small typo.

Add function to PaginatedUserService to load users by username

---

graylog2-web-interface/src/components/common/Pagination.jsx
graylog2-web-interface/src/components/common/__snapshots__/Pagination.test.jsx.snap
graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap

Updating color usage to render better in dark mode
Dark mode version of Pagination wasn't looking so great
- Page 1 is `active`
- Page 4 is `hovered`
- Previous buttons are `disabled`

Updating Pagination colors to prep for noire

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java
graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/IndicesES7IT.java

We accidentally used the Alias Action `REMOVE_INDEX`, which actually deletes the old index instead of only removing the alias from it:
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html
A little data loss never hurt no one, but this would have been a bit much. :)
Manual testing and new integration test

Avoid deletion of old index in ES7 index alias cycling

---

graylog2-server/src/main/java/org/graylog/events/search/MoreSearch.java

`MoreSearchAdapter#scrollEvents` was accidentally called twice in `MoreSearch#scrollQuery`
This was an oversight in #8197

Remove duplicate method call in MoreSearch

---

graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx

Stop pinned sidebar from overlapping header
Small UI fragment was overlapping `Alert` in the navigation and was visible on hover.

Stop pinned sidebar from overlapping header

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java
graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategy.java
graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategyTest.java

Non-UTC timestamps from `IndicesAdapterES7#indexCreationDate` led to a bug in `TimeBasedRotationStrategy#determineRotationPeriodAnchor` when calculating the new rotation period anchor.
`IndicesAdapterES7#indexCreationDate` was changed to always return UTC dates, just like `IndicesAdapterES6#indexCreationDate` does.
New anchors were always created as UTC. But when the clalculation started from a non-UTC old anchor, this could lead to undesired shifts in date.
Example:
- old anchor (i.e., the index creation date) is `20200731T12:00:00.000+02:00` (CET)
- rotation period is 1 month (`P1M`)
- new anchor would first be calculated as `20200701T00:00:00.000+02:00` (CET)
- conversion to UTC would result in `20200630T22:00:00.000+00:00`
=> Index would be rotated wrongly.
See …

Make IndicesAdapterES7#indexCreationDate return UTC timestamps

---

graylog2-server/src/test/java/org/graylog2/security/ldap/LdapConnectorSSLTLSIT.java

This change is doing two things for the LDAP authenticator SSL/TLS tests:
1. Making them more reliable
Before this change, running the complete test class worked, but running individual tests could result in test failures. This is related to different exception classes being thrown, depending on if a connection was attempted before or not. The real root cause for this is unknown. The exceptions are thrown in two different places:
- When writing the initial packet (`InvalidConnectionException`), or
- When parsing the response (`LdapProtocolErrorException`)
As I was unable to find out the underlying cause, the assertions for failed connections were relaxed. Instead of checking for the exact exception class, we are now checking if an exception was thrown at all.  Together with the positive …

Making LDAP TLS/SSL tests faster and more reliable.

---

graylog2-web-interface/src/views/components/sidebar/description/SearchResultOverview.jsx

With this PR we are displaying a loading spinner for search sidebar execution info, during the search execution.
These changes also fix a prop type warning for the `Timestamp` component.

Display loading spinner for search sidebar execution info, during execution

---

.github/ISSUE_TEMPLATE/bug_report.md

This will be useful once people start using Java >8 more and more.

Add Java version to the issue template

---

graylog2-server/src/test/java/org/graylog2/security/ldap/LdapConnectorSSLTLSIT.java

This change is doing two things for the LDAP authenticator SSL/TLS tests:
1. Making them more reliable
Before this change, running the complete test class worked, but running individual tests could result in test failures. This is related to different exception classes being thrown, depending on if a connection was attempted before or not. The real root cause for this is unknown. The exceptions are thrown in two different places:
- When writing the initial packet (`InvalidConnectionException`), or
- When parsing the response (`LdapProtocolErrorException`)
As I was unable to find out the underlying cause, the assertions for failed connections were relaxed. Instead of checking for the exact exception class, we are now checking if an exception was thrown at all.  Together with the positive …

Making LDAP TLS/SSL tests faster and more reliable. (3.3)

---

graylog2-web-interface/src/actions/users/UsersActions.js
graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationForm.jsx
graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationFormContainer.jsx
graylog2-web-interface/src/components/users/EditRolesForm.jsx
graylog2-web-interface/src/components/users/NewUserForm.jsx
graylog2-web-interface/src/components/users/UserForm.jsx
graylog2-web-interface/src/components/users/UserList.jsx
graylog2-web-interface/src/contexts/CurrentUserContext.jsx
graylog2-web-interface/src/logic/users/User.js
graylog2-web-interface/src/pages/CreateUsersPage.jsx
graylog2-web-interface/src/pages/EditTokensPage.jsx
graylog2-web-interface/src/pages/EditUsersPage.jsx
graylog2-web-interface/src/stores/users/RolesStore.js
graylog2-web-interface/src/stores/users/UsersStore.js
graylog2-web-interface/src/views/components/ViewActionsMenu.jsx
graylog2-web-interface/src/views/components/ViewActionsMenu.test.jsx
graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.jsx
graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.test.jsx
graylog2-web-interface/src/views/components/views/ShareViewModal.jsx
graylog2-web-interface/src/views/components/visualizations/__tests__/XYPlot.test.jsx
graylog2-web-interface/test/fixtures/users.js

This PR implements the `UsersActions` and the `User` class. These changes were needed for the new permission UI, but they also improve the code in `master`.
We are currently not using the new `User` for the `CurrentUserStore` / `CurrentUserContext`. We will add these changes in a follow-up PR.

Implement UsersActions and User class

---

graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java
graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java
graylog2-server/src/main/java/org/graylog2/rest/resources/search/KeywordSearchResource.java
graylog2-server/src/main/java/org/graylog2/rest/resources/search/RelativeSearchResource.java
graylog2-server/src/main/java/org/graylog2/rest/resources/search/SearchResource.java
graylog2-server/src/test/java/org/graylog2/indexer/searches/SearchesIT.java

Fixes #8550 and gets rid of old code responsible for liimiting chunked results for scroll requests. This was made redundant by #8488, which implemented a more precise limiting in the Elasticsearch adapter code.
In order to test this, #8580 should be merged first.

Fix scroll arguments in old search resources

---

graylog2-server/src/main/java/org/graylog/security/authzroles/AuthzRolesResource.java

Prior to this change, there was no way to get a single Role from the
new AuthzRolesResource. But we would like to display a single role
readonly in the frontend.
This change will search for a role by id and return it.

Add get a single role from the AuthzRolesResource

---

graylog2-web-interface/src/actions/users/UsersActions.js
graylog2-web-interface/src/components/users/UserCreate/UserCreate.jsx
graylog2-web-interface/src/components/users/UserCreate/UserCreate.test.jsx
graylog2-web-interface/src/components/users/UsersOverview/UsersFilter.jsx
graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.jsx
graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.test.jsx
graylog2-web-interface/src/pages/UserDetailsPage.jsx
graylog2-web-interface/src/pages/UserEditPage.jsx
graylog2-web-interface/src/pages/UserTokensEditPage.jsx
graylog2-web-interface/src/stores/users/UsersStore.js
graylog2-web-interface/src/stores/users/UsersStore.test.js

This PR removes the state from `UsersStore` which we implemented for the new UserManagement. We've decided to set the result of the `UsersActions` inside the related components as a state instead.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#1697

Remove state from UsersStore

---

graylog2-server/src/main/java/org/graylog2/users/UserOverviewDTO.java

Prior to this change, the users overview would not render
and the resource couldn't return any users when one user
did not have roles.
This change will return an empty set of roles so the
Resource does not break on request.

Fix users overview when the user has no roles

---

graylog2-server/src/main/java/org/graylog2/search/SearchQueryParser.java
graylog2-server/src/test/java/org/graylog2/search/SearchQueryParserTest.java

Prior this change the SearchQueryParser would fail
if null was passed to him since the newly add URLDecoder
was failing.
This change will first check if the query string is empty
or null before performing the url decoding.

Fix SearchQueryParser for null queries

---

graylog2-web-interface/src/components/streams/Stream.jsx
graylog2-web-interface/src/components/streams/StreamControls.jsx

Prior to this change, the EntityShareModal was missing for streams.
This change will add the EntityShareModal for streams.

Add Share Button to streams

---

graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java

This change is preventing the `JestClientProvider` to be constructed as eager singleton. This avoids node discovery being active for the jest client, even if the ES6 module is not used at all.

Construct jest client provider lazily instead of eager.

---

graylog2-server/src/main/java/org/graylog/security/authzroles/AuthzRolesResource.java
graylog2-server/src/main/java/org/graylog2/users/PaginatedUserService.java

Prior this change, there was no way to get all users which had a certain
role assigned. Also the user wanted to add and remove users from the
role.
With this change three new routes were introduced:
- get all users for a role
- add a role to a user
- remove a role from a user

Add missing routes to AuthzRolesResource

---

graylog2-web-interface/src/components/navigation/Navigation.jsx

Prior to this change, the newly add enterprise header badge was moving around with
the Global Throughput indicator. When the indicator was big it was moved
to the left and vice versa.
This change will move the header badge after the Global Throughput.

Reorder Header Badge in Navigation

---

graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java

This reverts commit 557010d3448059261b9caee321a119268ff2f3ad from PR #8703.
Lazy instantiation means that an instance is created every time the class is injected, which is not what we want.
Thanks to @mpfz0r for finding this!
While the reverted PR successfully avoided initializing a `JestClient` and the associated node discovery when it's not needed, because ES 7 is used, it led to the new problem described above. 
To avoid it we should instead manage an instance in `JestClientProvider` the same way we do in `RestHighLevelClientProvider`.
https://github.com/Graylog2/graylog2-server/blob/0c48877a9abff31246605c429320770a684bff7c/graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/RestHighLevelClientProvider.java#L27
Debugged in local dev environment using ES 6.

Revert "Construct jest client provider lazily instead of eager. (#8703)"

---

graylog2-server/src/main/java/org/graylog/grn/GRNModule.java
graylog2-server/src/main/java/org/graylog/grn/providers/ViewGRNDescriptorProvider.java

Rename DashboardGRNDescriptorProvider to ViewGRNDescriptorProvider
since it can be used for both: dashboards and saved searches

Add saved search GRNDescriptorProvider

---

graylog2-web-interface/src/views/components/sidebar/fields/List.jsx

This PR unifies the sidebar field list line-height with our default line-height. Once the line-height is part of our theme, we can use it probably for this case as well.

Unify sidebar field list line-height with default line-height

---

graylog2-web-interface/src/pages/ConfigurationsPage.jsx

Will prevent problem occurring in #8392
The `state.loaded` only checks _if_ there is some config available, not which.
This patch will allow each configuration block to load individually as data comes in.

Fix race conditions on system/configuration

---

graylog2-web-interface/src/components/navigation/ThemeModeToggle.jsx
graylog2-web-interface/src/theme/GraylogThemeProvider.jsx
graylog2-web-interface/src/theme/types.js

Implemented Loading icon in `ThemeModeToggle` during Theme switching
There is a mild delay while Graylog renders the next theme making it appear as if your click did not register.
Double clicking, or clicking while it was loading, would lead to calling the theme you're currently on again.
Apologies about the quality, GIF does not handle the animation well.

Show Spinner while Theme is loading

---

graylog2-server/src/main/java/org/graylog/security/DBGrantService.java

The combination of "grantee", "capability" and "target" must me unique
to avoid the creation of duplicate grant entries.

Add unique compound index on "grants" table

---

graylog2-server/src/main/java/org/graylog/security/permissions/GRNPermission.java
graylog2-server/src/main/java/org/graylog/security/rest/RestResourceWithOwnerCheck.java
graylog2-server/src/main/java/org/graylog2/plugin/database/users/User.java
graylog2-server/src/main/java/org/graylog2/security/InMemoryRolePermissionResolver.java
graylog2-server/src/main/java/org/graylog2/security/realm/MongoDbAuthorizationRealm.java
graylog2-server/src/main/java/org/graylog2/users/UserImpl.java
graylog2-server/src/test/java/org/graylog2/users/UserImplTest.java

Convert WildcardPermission("*") to AllPermission 
WildcardPermissions are not comparable with other types of permissions.
In case of the admin permission "*" we want it to imply also
a GRNPermission, which is used for handling entity ownership.
Having the AllPermission allows a User to "own" every entity
inside Graylog.
Improve error message
Fixes #8727 

Make the admin owner of every entity

---

graylog2-web-interface/src/actions/permissions/EntityShareActions.js
graylog2-web-interface/src/actions/roles/AuthzRolesActions.js
graylog2-web-interface/src/actions/users/UsersActions.js
graylog2-web-interface/src/components/permissions/RolesSelector.jsx
graylog2-web-interface/src/components/roles/RoleEdit/UsersSelector.jsx
graylog2-web-interface/src/components/roles/RolesOverview/ActionsCell.jsx
graylog2-web-interface/src/components/roles/RolesOverview/RolesOverview.jsx
graylog2-web-interface/src/components/users/UserCreate/UserCreate.jsx
graylog2-web-interface/src/components/users/UserCreate/UserCreate.test.jsx
graylog2-web-interface/src/components/users/UserDetails/RolesSection.jsx
graylog2-web-interface/src/components/users/UserDetails/SharedEntitiesSection.jsx
graylog2-web-interface/src/components/users/UserDetails/UserDetails.test.jsx
graylog2-web-interface/src/components/users/UserEdit/PasswordSection.jsx
graylog2-web-interface/src/components/users/UserEdit/RolesSection.jsx
graylog2-web-interface/src/components/users/UserEdit/UserEdit.test.jsx
graylog2-web-interface/src/components/users/UserList.jsx
graylog2-web-interface/src/components/users/UsersOverview/UserOverviewItem/ActionsCell.jsx
graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.jsx
graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.test.jsx
graylog2-web-interface/src/pages/UserDetailsPage.jsx
graylog2-web-interface/src/routing/ApiRoutes.js
graylog2-web-interface/src/stores/permissions/EntityShareStore.js
graylog2-web-interface/src/stores/roles/AuthzRolesStore.js
graylog2-web-interface/src/stores/users/UsersStore.js
graylog2-web-interface/src/stores/users/UsersStore.test.js

This PR:
* implements a cancel button on user and team create page
* removes redirect to users overview after changing password on user edit page.
* displays info in entity share modal when there is no collaborator.
* unifies store method / actions names
Fixes: https://github.com/Graylog2/graylog2-server/issues/8795
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#1733

Unifications for management frontend

---

graylog2-web-interface/src/components/common/HasOwnership.jsx
graylog2-web-interface/src/components/common/HasOwnership.test.jsx
graylog2-web-interface/src/components/common/index.jsx
graylog2-web-interface/src/components/streams/StreamControls.jsx
graylog2-web-interface/src/logic/users/User.js
graylog2-web-interface/src/views/components/SearchBar.test.jsx
graylog2-web-interface/src/views/components/ViewActionsMenu.jsx
graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.jsx
graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.test.jsx
graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchControls.test.jsx.snap
graylog2-web-interface/test/fixtures/users.js

Prior to this change, we always show the entity sharing modal button
even if you were not allowed to see it which would lead into a error
screen.
This change will implement a switching component which decides if a
child will be rendered depending on if the user has ownership over the
entity passed on.

Implement HasOwnership which checks for sharing

---

graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java
graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/jest/JestClientProvider.java

This change is made to avoid initializing a `JestClient` instance when it is not used at all (e.g. when the ES6 storage driver is not used).  Declaring the binding as eager singleton or even with the singleton scope results in an eager call to `JestClientProvider#get`, resulting in a creation of a `JestClient` instance and initializing the node discovery.
To avoid this, this change is removing any singleton declaration for the binding and caches the instance in the provider instead, always returning the same one.

Caching singleton instance of `JestClient` in `JestClientProvider`.

---

graylog2-web-interface/webpack.combined.config.js
graylog2-web-interface/webpack.config.js

Before this change, adding a webpack config override in a plugin's
`webpack.config.js` lead to it being included in the webpack config used
to build the plugin's assets in its own build (producing the plugin's
production artifacts), but overrides were not integrated into the
webpack config used for development (when doing a `yarn start` in the
core repo).
This change is now adding logic to merge the generated plugin webpack
configs together and merges the core config into to generate a final
config including the core config and all plugin's overrides.
**Note:** In a first attempt a multi-compiler (separate compilers for
plugins, using their generated config) config was created. It works, but
unfortunately there is no easy way to sync compiler runs with the core
compiler run and to …

Merge webpack overrides from plugin into core config

---

full-backend-tests/pom.xml
graylog-plugin-archetype/pom.xml
graylog-plugin-parent/graylog-plugin-web-parent/pom.xml
graylog-plugin-parent/pom.xml
graylog-project-parent/pom.xml
graylog2-server/pom.xml
graylog2-web-interface/manifests/package.json
graylog2-web-interface/package.json
graylog2-web-interface/packages/graylog-web-plugin/package.json
integration-tests/pom.xml
pom.xml

Merges the `3.3` branch into `cloud-3.3` after the `3.3.5` release.
/jenkins-pr-deps Graylog2/graylog-plugin-cloud#350

Sync cloud branch after 3.3.5 release

---

graylog2-web-interface/src/views/components/views/ViewList.jsx

Prior to this change, the user needed to go to the Dashboard view/edit
page to add collaborators to a dashboard.
This change is now adding a MenuItem to the dashboard list so the user
can share the dashboard from the over view list. This might be helpful
if a user needs to share a lot of dashboards.
Fixes #8793

Add share button to Dashboard LIst

---

distribution/pom.xml
full-backend-tests/pom.xml

Updating the 'packaging' element from "jar" to "pom" so the submodule doesn't generate an empty jar. Just a bit of minor cleanup. 
The pom for the 'full-backend-tests' modules doesn't need to generate a jar for the work it do. The generated jar just has a few small meta text files in it.

Modify POM for full-backend-tests module to not create an empty jar.

---

graylog2-web-interface/src/views/components/datatable/MessagesTable.jsx

Fix darkmode color of tableheader of data tables

Fix darkmode color of tableheader of data tables

---

graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java
graylog2-server/src/main/java/org/graylog2/migrations/V20200803120800_MigrateRolesToGrants.java
graylog2-server/src/main/java/org/graylog2/security/ldap/LdapSettingsImpl.java
graylog2-server/src/main/java/org/graylog2/system/stats/ClusterStatsService.java
graylog2-server/src/main/java/org/graylog2/users/RoleService.java
graylog2-server/src/main/java/org/graylog2/users/RoleServiceImpl.java
graylog2-server/src/test/java/org/graylog/security/DBGrantServiceTest.java
graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_MigrateRolesToGrantsTest.java
graylog2-server/src/test/java/org/graylog2/users/UserServiceImplTest.java
graylog2-server/src/test/resources/org/graylog2/migrations/V20200803120800_MigrateRolesToGrantsTest.json

This migrates the currently UI configurable roles
for dashboards and streams into grants.
If the permissions of a role are empty after the migration, it gets removed
completely.
If entities has permissions other than read and edit, we don't migrate
it, so we don't end up having permissions on two different places for a
single entity.
Fixes #8594 

Migrate dashboard and stream roles to grants

---

graylog2-web-interface/src/components/roles/RolesOverview/ActionsCell.jsx

With this PR we are informing the user how many users are assigned to a role, in the role delete confirmation dialog.
Fixes: #8754

Show confirmation dialog on role delete with info about assigned users

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/buckets/ESTimeHandler.java
graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivots/buckets/ESTimeHandlerTest.java

The Elasticsearch high-level REST client offers two ways to define the
interval for time-based bucketing, fixed and calendar intervals. Those
can be used for different interval specifications. Before this change,
the fixed interval was used for everything, leading to exceptions being
thrown e.g. when the interval was specified as `1M` (one month). (The
easiest way to reproduce this is to switch the time range to "all
messages" on ES7).
Therefore, this change checks if the given interval matches the ones
suitable for calendar intervals or uses fixed intervals otherwise.

Use correct interval type for time bucketing.

---

graylog2-web-interface/.flowconfig
graylog2-web-interface/src/views/components/sidebar/fields/List.jsx

Previously, flow was not type-checking usage of third party modules in `node_modules`, if no `flow-typed` definition for a module was existant.
This PR is enabling flow type checks for our usage of third party dependencies in `node_modules` by removing the ignore for the directory and instead using it for declarations. This avoids type-checking of all modules in `node_modules`, but uses supplied flow definitions from modules. Flow type definitions from `flow-typed` are still used, but type definitions included in a package take precedence.
This change ignores type definitions for `react-select` & `immutable.js` from their packages right now. In the first case (`react-select`), we need to fix our usage of it in quite a number of cases. A follow-up PR for this will be created. For the …

Enabling flow declarations for `node_modules`.

---

graylog2-web-interface/src/views/components/searchbar/QueryInput.jsx
graylog2-web-interface/src/views/components/searchbar/QueryInput.test.jsx
graylog2-web-interface/src/views/components/searchbar/queryinput/StyledAceEditor.jsx

This PR fixes a problem with long queries where uncontrollable whitespace is being added before the cursor.
In the above screenshot `query` is selected, but it looks like the selected text is `ery  `.
Fixes #8720.

Set font size defined in theme for query input

---

graylog2-web-interface/flow-typed/npm/styled-components_v5.x.x.js
graylog2-web-interface/src/components/graylog/DropdownSubmenu.jsx
graylog2-web-interface/src/views/components/messagelist/MessageFields.jsx
graylog2-web-interface/src/views/components/sidebar/fields/List.jsx
graylog2-web-interface/src/views/components/sidebar/fields/ListItem.jsx

This PR updates the styled-components flow interface definition from v4 to v5. It also includes one manual change which got implemented by @kyleknighted for the official v4 interface definition (https://github.com/flow-typed/flow-typed/pull/3779). This change is not yet part of the official v5 interface definition, but required to fix the [described](https://github.com/flow-typed/flow-typed/issues/3778) flow errors.

Update styled-components flow interface definition from v4 to v5

---

graylog2-server/src/main/java/org/graylog/security/shares/EntitySharesService.java
graylog2-server/src/main/java/org/graylog2/plugin/rest/ValidationResult.java
graylog2-server/src/test/java/org/graylog/security/shares/EntitySharesServiceTest.java

Extend the validation result to contain an `error_context`.
This allows us to add entries that the frontend can parse more easily.
Example:
```
"validation_result": {
"context": {
"selected_grantee_capabilities": [
"grn::::team:5f1015e5619e2c125100c570",
"grn::::user:hans"
]
},
"errors": {
"selected_grantee_capabilities": [
"Removing the following owners <[grn::::team:5f1015e5619e2c125100c570,grn::::user:hans]> will leave the entity ownerless."
]
},
"failed": true
}
```

Don't validate initial share requests // provide validation context

---

graylog2-web-interface/src/actions/users/UsersActions.js
graylog2-web-interface/src/components/users/UserEdit/SettingsSection.jsx
graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx
graylog2-web-interface/src/stores/users/UsersStore.js

Right now the payload for the user create and update request is typed as `any`. This PR adds proper type definitions for the actions and store methods.

Add type definition for user create and update payload

---

graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodical.java
graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodicalTest.java

This change adds a check to the `IndexFieldTypePollerPeriodical` run, which returns early if the current server lifecycle is one that indicates that it's not running properly (either starting up or shutting down).
The check could be generalized into a `ServerStatus#isOperational` predicate if we want to, which could be reused in other places where a check like this is needed.
Having the load balancer override states intermingled with the general server state is irritating, as these are factually orthogonal from each other. Maybe we can separate them to a dedicated variable.
Fixes #8800.

Skip execution of field types poller if server is not running.

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java

This change removes the "only expunge deletes" option from the force merge request, as it contradicts with the "max num segments" option. For every execution of the request, a warning is logged about this, also indicating that while the request is still performed, it might not in future ES versions.
```
2020-08-20 11:56:29,184 WARN : org.graylog.shaded.elasticsearch7.org.elasticsearch.client.RestClient - request [POST https://localhost:9200/graylog2_1/_forcemerge?only_expunge_deletes=true&flush=true&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&ignore_throttled=false&max_num_segments=1] returned 1 warnings: [299 Elasticsearch-7.8.1-b5ca9c58fb664ca8bf9e4057fc229b3396bf3a89 "setting only_expunge_deletes and max_num_segments at the same time is deprecated and will be …
```

Fix invalid options for force merge request during index optimization.

---

graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20200730000000_AddGl2MessageIdFieldAliasForEvents.java
graylog2-server/src/main/java/org/graylog/plugins/views/providers/ExportBackendProvider.java
graylog2-server/src/main/java/org/graylog2/bindings/ElasticsearchModule.java
graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchClientConfiguration.java
graylog2-server/src/main/java/org/graylog2/storage/ElasticsearchVersion.java
graylog2-server/src/main/java/org/graylog2/storage/VersionAwareProvider.java
graylog2-server/src/main/java/org/graylog2/storage/providers/AtomicCache.java
graylog2-server/src/main/java/org/graylog2/storage/providers/ClusterAdapterProvider.java
graylog2-server/src/main/java/org/graylog2/storage/providers/CountsAdapterProvider.java
graylog2-server/src/main/java/org/graylog2/storage/providers/ElasticsearchBackendProvider.java
graylog2-server/src/main/java/org/graylog2/storage/providers/ElasticsearchVersionProvider.java
graylog2-server/src/main/java/org/graylog2/storage/providers/IndexFieldTypePollerAdapterProvider.java
graylog2-server/src/main/java/org/graylog2/storage/providers/IndexToolsAdapterProvider.java
graylog2-server/src/main/java/org/graylog2/storage/providers/IndicesAdapterProvider.java
graylog2-server/src/main/java/org/graylog2/storage/providers/MoreSearchAdapterProvider.java
graylog2-server/src/main/java/org/graylog2/storage/providers/NodeAdapterProvider.java
graylog2-server/src/main/java/org/graylog2/storage/providers/SearchesAdapterProvider.java
graylog2-server/src/main/java/org/graylog2/storage/providers/V20170607164210_MigrateReopenedIndicesToAliasesClusterStateAdapterProvider.java
graylog2-server/src/main/java/org/graylog2/storage/providers/V20200730000000_AddGl2MessageIdFieldAliasForEventsElasticsearchAdapterProvider.java
graylog2-server/src/main/java/org/graylog2/storage/versionprobe/RootResponse.java
graylog2-server/src/main/java/org/graylog2/storage/versionprobe/RootRoute.java
graylog2-server/src/main/java/org/graylog2/storage/versionprobe/VersionProbe.java
graylog2-server/src/main/java/org/graylog2/storage/versionprobe/VersionResponse.java

This change is adding auto-sensing for the Elasticsearch version if the `elasticsearch_version` configuration field is not set. The config field is kept, but optional now. It can be used to explicitly override the chosen Elasticsearch storage driver implementation if auto-sensing fails.
If the config setting is not present, early at startup version probing will be attempted by iterating over the list of configured Elasticsearch nodes and requesting their root resource (`/`). All fields of the response will be ignored, besides the `$.version.number` field, which contains the server version as a string. The first successful attempt where the request succeeds and the retrieved version can be parsed properly will be used to determine the remote version and therefore which storage driver …

Auto-sense Elasticsearch version if no version is set.

---

graylog2-web-interface/src/views/components/common/EditableTitle.jsx

- Style Widget Title edit input
- Stop UI from jumping while editing
/jenkins-pr-deps Graylog2/graylog2-server#8882
In dark mode the Widget EditableTitle is not readable and causes the UI to shift a couple pixels when it converts to an input

Updating widget name edit input

---

graylog-storage-elasticsearch7/assembly.xml
graylog-storage-elasticsearch7/pom.xml
graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/FilteredElasticsearchNodesSniffer.java
graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/RestHighLevelClientProvider.java
graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/FilteredElasticsearchNodesSnifferTest.java

This PR is adding node discovery for Elasticsearch 7. It uses the default `Sniffer` module which hooks into the rest client and replaces the nodes list with the one retrieved from the server.
In addition, this change is reimplementing a feature from Jest that allows to filter the retrieved list of nodes based on a given
`attribute:value` setting in the config file. For this, it implements the `FilteredElasticsearchNodesSniffer` that wraps around the stock `ElasticsearchNodesSniffer` and filters the nodes list it retrieves based on the `elasticsearch_discovery_filter` setting.

Implementing ES node discovery for ES7.

---

graylog2-web-interface/src/components/common/TypeAheadFieldInput.jsx
graylog2-web-interface/src/components/common/TypeAheadInput.jsx
graylog2-web-interface/src/contexts/GlobalStylesProvider.jsx

Adding theme to autocomplete options generated by Typeahead components
Fixes Graylog2/graylog-plugin-enterprise-integrations#353

Theming Typeahead autocomplete options

---

graylog2-server/src/main/java/org/graylog2/Configuration.java
graylog2-server/src/main/java/org/graylog2/periodical/ClusterHealthCheckThread.java

Add an `is_cloud` configuration flag. When enabled, certain in functionality/behavior in Graylog can be disabled or altered as appropriate for running in the Cloud environment.
This PR also skips checks in the `ClusterHeathCheckThread`, which currently only raise a System Notification when no inputs are running on a node. This notification is not appropriate for Cloud, since Forwarders/Forwarder Inputs are used instead of Inputs. So, a node in Graylog Cloud can be healthy when no inputs are running on it.
Enabled the `is_cloud` flag and observed that the system notification is not raised.
Disabled the `is_cloud` flag, and observed that the notification is raised.
Closes https://github.com/Graylog2/graylog-plugin-cloud/issues/359

Add is_cloud flag and disable "No input running" warning

---

graylog2-web-interface/src/components/navigation/Navigation.jsx
graylog2-web-interface/src/components/navigation/Navigation.test.jsx
graylog2-web-interface/src/pages/StartPage.jsx

Prior to this change, the Search Menu Item was only displayd for admins
or users which have searches:absolute', 'searches:relative',
'searches:keyword' permissions.
The mentioned permission could only be add via API requests. Which left
the admin users as the only ones which could really see that Menu Item.
But a user could go to that page either via a link (on the streams page)
or by typing the url manually.
This change will now simply remove this check and always display the
menu item. The search still will only work if the user has read
permissions to a stream.
Fixes #8745
Fixes #8779
Fixes #8921
**Needs backport to 3.3**
1. created a user with only reader permissions
1. loggedin and see the `Search` Menu item, when user clicks on item he sees a Permissions error, since he misses …

Remove permission check for Search Nav Item

---

graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
graylog2-server/src/test/resources/org/graylog/security/shares/EntitySharesServiceTest.json

There should be only one grant per grantee and entity.
Having multiple will even break some of our code.
Better fail early.
Fixes #8927
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#1765

Add unique index for grantee and entity

---

graylog2-web-interface/src/components/navigation/Navigation.jsx
graylog2-web-interface/src/components/navigation/Navigation.test.jsx

This change is adding a check to show the `Enterprise` top navigation item only if the user has the require `licenseinfos:read` permission. If the user does not have this permission, clicking the navigation item would result in a 403 error page.
Fixes #8936.

Do not show `Enterprise` navigation if user is lacking permission

---

pom.xml

Changelogs:
- https://netty.io/news/2020/07/09/4-1-51-Final.html
- https://netty.io/news/2020/09/08/4-1-52-Final.html

Update to Netty 4.1.52 and netty-tcnative-boringssl-static to 2.0.34

---

graylog2-web-interface/src/components/common/EmptyEntity.css
graylog2-web-interface/src/components/common/EmptyEntity.jsx
graylog2-web-interface/src/components/common/EmptyEntity.test.jsx

With this PR we are adding flow type definitions, creating a test and using styled-components for the `EmptyEntity` component.

Add flow type definitions, create test and use styled-components for EmptyEntity

---

graylog2-web-interface/src/components/errors/ErrorPage.jsx
graylog2-web-interface/src/components/errors/ReportedErrorBoundary.test.jsx
graylog2-web-interface/src/components/errors/RouterErrorBoundary.test.jsx
graylog2-web-interface/src/index.jsx
graylog2-web-interface/src/pages/LoadingPage.jsx
graylog2-web-interface/src/pages/LoggedInPage.jsx
graylog2-web-interface/src/pages/LoginPage.jsx
graylog2-web-interface/src/pages/RuntimeErrorPage.test.jsx
graylog2-web-interface/src/pages/ServerUnavailablePage.jsx
graylog2-web-interface/src/pages/StreamPermissionErrorPage.test.jsx
graylog2-web-interface/src/pages/UnauthorizedErrorPage.test.jsx
graylog2-web-interface/src/theme/GlobalThemeStyles.jsx

Removes `GlobalStylesProvider`, replaced with directly using Styled-Components `createGlobalStyles`	where needed
Login/Loading pages and sometimes after an error, the background was not resetting properly.
First we attempted the difficult way, then we realized it was being overthought and went for the simple solution.

Remove GlobalStylesProvider and use createGlobalStyles

---

graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationBrowserResource.java

Prior to this change, the `/api-browser/.*` resource allowed to retrieve static assets used by swagger. Some of these were prefixed with a `global/` prefix, that needs to be stripped away before locating the file. The string replacement used for this was used unbounded (replacing every occurence of the prefix, not just the first one), so it could be used to create URLs containing `..`. The check if the route contains `..` was performed _before_ the string replacement, so it could effectively be used to evade it.
This change is:
1. Replacing _only the first_ occurrence of `global/`
2. Performing the check if the route contains `..` _after_ the replacement and _right before_ the file is tried to be opened.
Fixes #8986.

Fix path traversal in swagger resource.

---

graylog2-server/src/main/java/org/graylog/events/rest/EventDefinitionsResource.java

Since these endpoints don't accept a request body, we can just accept
any content-type. This unbreaks calling these endpoints with our swagger
API browser.
(This should be backported to the 3.3 branch)

Reset Consumes annotation to accept everything for (un)schedule

---

graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationBrowserResource.java

**Note: This is a backport of #8977 to `3.3`.**
Prior to this change, the `/api-browser/.*` resource allowed to retrieve static assets used by swagger. Some of these were prefixed with a `global/` prefix, that needs to be stripped away before locating the file. The string replacement used for this was used unbounded (replacing every occurence of the prefix, not just the first one), so it could be used to create URLs containing `..`. The check if the route contains `..` was performed _before_ the string replacement, so it could effectively be used to evade it.
This change is:
1. Replacing _only the first_ occurrence of `global/`
2. Performing the check if the route contains `..` _after_ the replacement and _right before_ the file is tried to be opened.
Fixes #8986.

Fix path traversal in swagger resource. (3.3)

---

graylog2-web-interface/src/views/logic/views/MoveWidgetToTab.js
graylog2-web-interface/src/views/logic/views/MoveWidgetToTab.test.js
graylog2-web-interface/src/views/logic/views/__snapshots__/MoveWidgetToTab.test.js.snap

Before this change, moving a widget from one dashboard page to another failed if no title had been changed on the dashboard before. This was related to the titles map not being initialized with the `widgets` key.
This PR is now using `getIn` to protect against the absence of the `widgets` key.

Fix moving widget if no titles have been set before.

---

graylog2-server/src/main/java/org/graylog/events/rest/EventDefinitionsResource.java

**This is a backport of https://github.com/Graylog2/graylog2-server/pull/8981 for 3.3**
Since these endpoints don't accept a request body, we can just accept
any content-type. This unbreaks calling these endpoints with our swagger
API browser.

Reset Consumes annotation to accept everything for (un)schedule  (3.3)

---

graylog2-web-interface/src/routing/ApiRoutes.js
graylog2-web-interface/src/stores/permissions/EntityShareStore.js

This PR removes the mock for entities which got shared with a team, because the endpoint exists now.
The data is being used by the team details pages.

Remove mock for entities which got shared with a team

---

graylog2-web-interface/src/components/navigation/Navigation.jsx
graylog2-web-interface/src/components/navigation/Navigation.test.jsx
graylog2-web-interface/src/pages/StartPage.jsx

**This is a backport of #8917 for `3.3`.**
Prior to this change, the Search Menu Item was only displayed for admins or users which have searches:absolute', 'searches:relative', 'searches:keyword' permissions.
The mentioned permission could only be add via API requests. Which left the admin users as the only ones which could really see that Menu Item. 
But a user could go to that page either via a link (on the streams page) or by typing the url manually.
This change will now simply remove this check and always display the menu item. The search still will only work if the user has read permissions to a stream.

Remove permission check for Search Nav Item (3.3)

---

graylog2-server/src/main/java/org/graylog2/notifications/Notification.java
graylog2-web-interface/src/logic/notifications/NotificationsFactory.js

When outputs fail, we can't simply shut them down.  Thus, we need to give the users a clear message about what has happened.  This change adds a new notification type for outputs that are failing so we can do just that.
Change has been tested locally by triggering connection failures in the Enterprise TCP Output

Add new notification type to support failing Enterprise outputs

---

graylog2-server/src/main/java/org/graylog2/notifications/Notification.java
graylog2-web-interface/src/logic/notifications/NotificationsFactory.js

This PR is a backport of #9019 to the `3.3` branch
When outputs fail, we can't simply shut them down.  Thus, we need to give the users a clear message about what has happened.  This change adds a new notification type for outputs that are failing so we can do just that.
See #9019

Merge new notification type to 3.3

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/CountsAdapterES7.java
graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java
graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/SearchRequestFactory.java

Before this change, the count & search requests did not request ES7 to
return the exact number of hits. This is required for us in a lot of
cases, so this change is explicitly enabling it, although it comes with
a small performance hit.
Fixes #8970.

Request tracking exact number of search hits in requests.

---

graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/jest/JestClientProvider.java
graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/jest/JestClientProviderTest.java
graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/testing/ElasticsearchInstanceES6.java
graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/client/ESCredentialsProvider.java
graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchClientConfiguration.java

Prior to this PR, it was not possible to combine Elasticsearch node discovery and authentication. Discovered Elasticsearch nodes must not have authentication enabled, because there was no way to configure credentials for them in Graylog.
This PR adds functionality for the user to supply a default user/password which is used for all discovered nodes. The same user & password must be used across all nodes in the Elasticsearch cluster, as the same user/password is used for every discovered node added to the node list.
The configuration settings are:
`elasticsearch_discovery_default_user`: The default user name
`elasticsearch_discovery_default_password`: The default password
The feature is supported for ES6 & ES7.

Allow specifying default user/password for discovered ES nodes.

---

graylog2-web-interface/src/components/permissions/RolesSelector.jsx
graylog2-web-interface/src/components/users/UserCreate/UserCreate.jsx
graylog2-web-interface/src/components/users/UserDetails/RolesSection.jsx
graylog2-web-interface/src/components/users/UserEdit/RolesSection.jsx

This PR makes the `RolesSelector` reusable by removing the connection to users. This way it can not only be used to assign roles for users but also for teams.
Have a look at the enterprise PR for more information.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#1772

Make RolesSelector reusable by removing the connection to users

---

graylog2-web-interface/src/contexts/StreamsContext.jsx
graylog2-web-interface/src/contexts/StreamsProvider.jsx
graylog2-web-interface/src/pages/LoggedInPage.jsx
graylog2-web-interface/src/pages/UserHasNoStreamAccess.jsx
graylog2-web-interface/src/views/components/IfUserHasAccessToAnyStream.jsx
graylog2-web-interface/src/views/pages/NewSearchPage.jsx
graylog2-web-interface/src/views/pages/NewSearchPage.test.jsx
graylog2-web-interface/src/views/stores/StreamsStore.js

Before this change, the user was seeing a "Missing stream permissions" page, that did not show a helpful error message if the user is not missing the permission for a specific stream, but for any stream at all.
This change is now checking if the user is having any stream permissions at all and shows a better message otherwise.
Fixes #8955.

Show better error message when user has no stream permissions. (3.3)

---

graylog2-server/src/main/java/org/graylog2/search/SearchQueryOperator.java
graylog2-server/src/test/java/org/graylog2/search/SearchQueryOperatorTest.java

Avoids errors when the search query contains regexp meta characters like
`\`.

Quote search query values for regexp operators

---

graylog2-server/src/main/java/org/graylog2/shared/rest/documentation/generator/Generator.java

A simple addition to not return `null` for the `PATCH` HTTP verb.

Add PATCH HTTP verb support to our API documentation generator

---

graylog2-web-interface/src/views/components/WidgetQueryControls.jsx
graylog2-web-interface/src/views/components/WidgetQueryControls.test.jsx
graylog2-web-interface/src/views/components/aggregationbuilder/EventListConfiguration.jsx
graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/EventListConfiguration.test.jsx.snap
graylog2-web-interface/src/views/components/searchbar/SearchBarForm.jsx
graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.jsx
graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.test.jsx
graylog2-web-interface/src/views/components/widgets/SaveOrCancelButtons.jsx
graylog2-web-interface/src/views/components/widgets/Widget.test.jsx

Before this change, a successful change to the timerange/stream selection/query of a widget on a dashboard required submitting the widget's search after the change and before clicking "Save". This was unintuitive and unnecessarily complicated.
This change is now submitting the widget's query form when the user clicks "Save" and the form is dirty, not requiring the user to have submitted the form manually before.
Fixes #7922.

Submit widget query form before saving edit widget modal.

---

UPGRADING.rst
graylog2-server/src/main/java/org/graylog2/grok/GrokPattern.java
graylog2-server/src/main/java/org/graylog2/grok/PaginatedGrokPatternService.java
graylog2-server/src/main/java/org/graylog2/rest/models/system/responses/GrokPatternPageList.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/GrokResource.java
graylog2-server/src/test/java/org/graylog2/rest/resources/system/GrokResourceTest.java
graylog2-web-interface/src/components/common/PaginatedList.jsx
graylog2-web-interface/src/components/grok-patterns/GrokPatternQueryHelper.jsx
graylog2-web-interface/src/components/grok-patterns/GrokPatterns.jsx
graylog2-web-interface/src/routing/ApiRoutes.js
graylog2-web-interface/src/stores/grok-patterns/GrokPatternsStore.js

Add pagination to the grok patterns overview page together with filtering.
A good overview page should have: Search and Pagination.
This PR add pagination and uses the search on the backend site.
The code is mainly copied from lookup table.
The list all API endpoint is kept since it makes sense when using  scripts to avoid stepping
through all dashboards with pages.
Add more than 10 grok patterns and stepped through the pages and searched for patterns.
Created, updated and deleted grok patterns and ensured that table refreshes accordingly.
This PR is based on #5675 and #5679 and must be merged **after** these PRs.

Paginated grok patterns

---

graylog2-web-interface/src/views/components/WidgetQueryControls.jsx
graylog2-web-interface/src/views/components/WidgetQueryControls.test.jsx
graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap
graylog2-web-interface/src/views/components/aggregationbuilder/EventListConfiguration.jsx
graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/EventListConfiguration.test.jsx.snap
graylog2-web-interface/src/views/components/searchbar/SearchBarForm.jsx
graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.jsx
graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.test.jsx
graylog2-web-interface/src/views/components/widgets/SaveOrCancelButtons.jsx
graylog2-web-interface/src/views/components/widgets/Widget.test.jsx

**This is a backport of #8985 for 3.3**
Before this change, a successful change to the timerange/stream selection/query of a widget on a dashboard required submitting the widget's search after the change and before clicking "Save". This was unintuitive and unnecessarily complicated.
This change is now submitting the widget's query form when the user clicks "Save" and the form is dirty, not requiring the user to have submitted the form manually before.
Fixes #7922.

Submit widget query form before saving edit widget modal. (Backport of #8985 for 3.3)

---

graylog2-web-interface/babel.config.js
graylog2-web-interface/src/components/navigation/Navigation.test.jsx
graylog2-web-interface/src/components/navigation/NotificationBadge.test.jsx
graylog2-web-interface/src/components/navigation/SystemMenu.test.jsx
graylog2-web-interface/src/routing/Routes.test.jsx
graylog2-web-interface/src/views/components/aggregationbuilder/SeriesFunctionsSuggester.test.jsx
graylog2-web-interface/src/views/components/visualizations/__tests__/GenericPlot.test.jsx
graylog2-web-interface/src/views/logic/views/OnSaveAsViewAction.test.js
graylog2-web-interface/src/views/logic/views/OnSaveViewAction.test.js
graylog2-web-interface/src/views/pages/ViewManagementPage.test.jsx

This plugin was used before mainly for interop between ancient Typescript parts and core. Recently, it was only needed for tests doing `require()` calls without a `default` suffix (we should get rid of `require` in tests anyway).
This change is removing the plugin and changes test calls.

Remove `add-module-exports` babel plugin.

---

graylog2-web-interface/webpack.config.js
graylog2-web-interface/webpack.vendor.js

Make sure npm scripts which start with 'build' are built in production mode so analysers get production stats.
It allows npm scripts starting with "build" to use production mode in webpack. This is so that analysers get the correct stats and data to work with when analysing bundles.
Currently analysing would result in looking at development builds. This is wrong.
By running `yarn build:analyze`

Run analysers in production mode

---

graylog2-server/pom.xml
graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java

Add support in Jersey for Multipart file uploads. 
This is needed for the file uploads in the Cloud CSV adapter (https://github.com/Graylog2/graylog-plugin-cloud/pull/418). Jersey requires this as described in https://stackoverflow.com/a/30656345/1624052
I would have preferred to make this change applicable to just the Cloud plugin, but I did not see a way to do that.
I clicked around Graylog, and it looks like nothing I noticed has broken.

Add support for multipart server uploads

---

graylog2-web-interface/src/components/streams/StreamComponent.jsx

Prior to this change, when the user was executing a search on streams
which resulted in no streams. The search bar was removed and the user
could not reset the search.
This change will display the Alert which will show that there are no
streams found below the search bar in stead of replacing it.

Fix empty search result in stream

---

graylog2-web-interface/src/actions/permissions/EntityShareActions.js
graylog2-web-interface/src/components/permissions/SharedEntitiesOverview/SharedEntitiesFilter.jsx
graylog2-web-interface/src/components/permissions/SharedEntitiesOverview/SharedEntitiesOverview.jsx
graylog2-web-interface/src/components/users/UserDetails/SharedEntitiesSection.jsx
graylog2-web-interface/src/components/users/UserDetails/UserDetails.jsx
graylog2-web-interface/src/domainActions/permissions/EntityShareDomain.js
graylog2-web-interface/src/routing/ApiRoutes.js
graylog2-web-interface/src/stores/permissions/EntityShareStore.js

Prior to this change, the teams share url was accessed in the core
but we want to strictly avoid having enterprise code leaked into
core.
This change implements the teams share url and action in the
TeamsStore/Action/Domain
Also Fix type on type declaration
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#1785

Move Teams share url to enterprise

---

graylog2-web-interface/src/components/common/Wizard.jsx
graylog2-web-interface/src/components/common/Wizard.test.jsx
graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionForm.jsx

This PR defines the `EventDefinitionFrom` wizard navigation style as the default for all horizontal wizards:
It looks better than the default style, which is being used in two plugins. The default style looks like this:
This PR also improves the responsiveness of the navigation.
Before:
After:
There are some ESLint warnings, but they are not related to this PR.

Unify wizard navigation style

---

graylog2-web-interface/src/components/bootstrap/Input.jsx
graylog2-web-interface/src/components/bootstrap/Input.test.jsx
graylog2-web-interface/src/components/common/FormikInput.jsx
graylog2-web-interface/src/components/common/InputDescription.jsx
graylog2-web-interface/src/components/common/InputDescription.test.jsx
graylog2-web-interface/src/components/common/index.jsx
graylog2-web-interface/src/components/content-packs/ContentPackSelection.jsx
graylog2-web-interface/src/components/content-packs/ContentPackSelection.test.jsx

The `Input` component currently allows defining a help text. We are also using this prop to display errors for an input. This way we always hide the help text when want to display an error. There are many cases where the help text is especially helpful when there is an error.
With this PR we are adding an extra error prop to be able to display both messages at the same time.
This change does not affect the current usage. I already adjusted the `ContentPackSelect` to demonstrate how to apply the change for existing components.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#1790

Add error prop for `Input` to be able to display an error message together with the input help text

---

graylog2-web-interface/src/views/components/aggregationbuilder/PivotConfiguration.jsx
graylog2-web-interface/src/views/components/aggregationbuilder/PivotConfiguration.test.jsx

Before this change, when configuring the settings for a row/column pivot in the widget edit mode, submitting the form resulted in a double submit. First, the pivot config form is submitted and its config is changed. Then, the same submit event is propagated to the overlying widget edit form (as defined in `SearchBarForm`). The `onSubmit` handler in there is submitting the current widget again, but with stale pivot config settings, resulting in a mismatching view/search constellation. This results then in search results not being resolvable, as the widget mapping is based on a stale search.
This change is now preventing the pivot config form submit event to be propagated, therefore limiting its effect to the initial submit only.
Fixes #9087.

Stop pivot config form submit event propagation.

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/DashboardsResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SavedSearchesResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewPermissionChecks.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewPermissionChecksTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewsResourceTest.java

Before this change, the following checks were performed when a saved search/dashboard is listed/opened:
- Does the user have permissions for the saved search/dashboard?
- Is the saved search/dashboard shared with the user?
If one of them holds true, access is permitted. Although the object has an optional `owner` field, its presence and equality with the current user's name is not checked.
This did not cause any issues in general, because the permissions are added dynamically to the current user when a saved search/dashboard is created, so their was no reliance on the existence of an ownership check.
During the migration of legacy saved searches, their owner field was migrated too, but no permissions were added to this user. Therefore, migrated saved searches were visible only to the …

Add ownership check to saved search/dashboard permission checks.

---

graylog2-web-interface/package.json
graylog2-web-interface/yarn.lock

This change is updating `@testing-library/react` to the next major
version. All tests passed before and after.

Updating to @testing-library/react v11.0.4.

---

graylog2-web-interface/src/components/users/UserCreate/PasswordFormGroup.jsx

Prior to this change, the length of th password was checked when the
users submited the user creation. Which means he typed the password
already 2 times.
This change will check the password length from the beginning.
Fixes #8913 

Check password length of user creation before submit

---

graylog2-web-interface/package.json
graylog2-web-interface/packages/graylog-web-plugin/package.json
graylog2-web-interface/yarn.lock

This PR updates a few dependencies with security issues, namely:
- jquery 3.5.1 ([GHSA-jpcq-cgw6-v4j6](https://github.com/advisories/GHSA-jpcq-cgw6-v4j6))
- lodash  4.17.20 ([GHSA-p6mc-m468-83gw](https://github.com/advisories/GHSA-p6mc-m468-83gw))
- elliptic 6.5.3 ([GHSA-vh7m-p724-62c2](https://github.com/advisories/GHSA-vh7m-p724-62c2))
- serialize-javascript 4.0.0 ([GHSA-hxcc-f52p-wc94](https://github.com/advisories/GHSA-hxcc-f52p-wc94))
A couple other dependencies were also updated in the process, although I tried to keep them to the minimum to avoid introducing any issues in the process. I will open additional PRs to update `yarn.lock` files in our plugins.

Update dependencies with security issues

---

graylog2-web-interface/src/views/components/aggregationbuilder/DescriptionBox.jsx
graylog2-web-interface/src/views/components/common/EditableTitle.jsx
graylog2-web-interface/src/views/components/common/EditableTitle.test.jsx
graylog2-web-interface/src/views/components/widgets/FieldSortIcon.jsx

Before these changes there were a few cases were we unintentionally submitted the widget search bar form in the widget edit modal:
- Clicking on the sort icons of a message table
- Clicking on the columns config icon
- Editing the widget title
The form should only be submitted when clicking on the modal "Save" button
Related to https://github.com/Graylog2/graylog2-server/pull/9085 which contains a more detailed description about the on submit behaviour.
This fix also needs to be applied for the master branch.

Prevent unintended search bar form submit in widget edit modal

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/DashboardsResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SavedSearchesResource.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewPermissionChecks.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewPermissionChecksTest.java
graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewsResourceTest.java

Before this change, only user permissions were considered when
permission checks for actions operating on saved searches/dashboards
were performed. This lead to migrated saved searches having an owner,
but these owners were not able to access their migrated saved searches.
With this change, any action is also considering the owner of a saved
search/dashboard before checking permissions. An owner of a saved
search/dashboard is able to perform any action on it. If the current
user is not the owner, user permissions and view sharings are checked,
just as before.

Add ownership check to saved search/dashboard permission checks. (3.3)

---

graylog2-web-interface/src/views/components/aggregationbuilder/DescriptionBox.jsx
graylog2-web-interface/src/views/components/common/EditableTitle.jsx
graylog2-web-interface/src/views/components/common/EditableTitle.test.jsx
graylog2-web-interface/src/views/components/widgets/FieldSortIcon.jsx

**Note:** This PR is a port of #9096 to `master`/`4.0`.
Before these changes there were a few cases were we unintentionally submitted the widget search bar form in the widget edit modal:
- Clicking on the sort icons of a message table
- Clicking on the columns config icon
- Editing the widget title
The form should only be submitted when clicking on the modal "Save" button
Related to https://github.com/Graylog2/graylog2-server/pull/9085 which contains a more detailed description about the on submit behaviour.
This fix also needs to be applied for the master branch.

Prevent unintended search bar form submit in widget edit modal (port of #9096)

---

graylog2-web-interface/src/components/common/TypeAheadInput.jsx

Updated Typeahead overlay to be transparent instead of rendering color
Typeahead inputs not swapping automatically with Theme switch

Fix Typeahead input background color

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MessagesAdapterES7.java
graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ParsedElasticsearchException.java
graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/ParsedElasticsearchExceptionTest.java

Prior to this change, when a message is tried to be ingested into Elasticsearch when the primary shard of an index is unavailable, indexing will fail and the message will be turned into an indexing failure. Most probably, this is not what a user wants. 
In most cases an unavailable primary shard is a) affecting most, if not all indices, b) is a temporary condition. These properties and the similarities to scenarios where a watermark threshold switches indices to read-only do justify a handling of this that attempts retries indefinitely until the condition is resolved. 
While this prevents message loss, it can also cause journal overflow (and causing message loss at the _other_ end of ingestion), while it buys operations time to fix the issue. Due to the watermark scenario, proper sizing …

Retry indexing message if primary shard is not active

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java
graylog2-server/src/test/java/org/graylog2/indexer/cluster/ClusterIT.java

Before this change, the ES7 implementation of `ClusterAdapterES7#health` was inconsistent with the one for ES6. When an empty list was passed as an argument, an exception was thrown, instead of a valid response being returned. The method being called with an empty list can happen if it is called from `Cluster#health`, which retrieves all existing indices for an index set before using `Cluster#allIndexWildcards`, which returns an empty list if these have not been created yet. (E.g. as the consequence of a race condition when starting Graylog from scratch/with an empty ES). From what was seen during fixing this issue, the only relevant consequence is that `IndexRangesMigrationPeriodical` throws an exception and will be rerun during next startup. Usually, this is not an issue, as there are …

Fix handling for health of empty indices in ES7.

---

graylog2-server/src/main/java/org/graylog2/Configuration.java
graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
graylog2-server/src/main/java/org/graylog2/lookup/LookupModule.java

Using CSV adapters in cloud will have different requirements, so this
plugin should not be available.
Fixes https://github.com/Graylog2/graylog-plugin-cloud/issues/437

Hide CSV Adapter in cloud instances

---

full-backend-tests/pom.xml
graylog-plugin-archetype/pom.xml
graylog-plugin-parent/graylog-plugin-web-parent/pom.xml
graylog-plugin-parent/pom.xml
graylog-project-parent/pom.xml
graylog2-server/pom.xml
graylog2-web-interface/manifests/package.json
graylog2-web-interface/package.json
graylog2-web-interface/packages/graylog-web-plugin/package.json
integration-tests/pom.xml
pom.xml

For some reasons there were a lot of conflicts.
When merging this PR, we should probably not squash the changes maybe this will help with the next sync.
/jenkins-pr-deps Graylog2/graylog-plugin-cloud#474

Sync cloud branch after 3.3.8 release

---

graylog2-web-interface/src/components/common/ConfirmLeaveDialog.jsx
graylog2-web-interface/src/components/common/ConfirmLeaveDialog.test.jsx

In #9118, a refactoring was performed that removes passing the current route as a prop to `ConfirmLeaveDialog`. It was erroneously assumed that `withRouter` also supplies the `route` object. This was effectively breaking the dialog that is shown in production when the current route is left (by using the navigation), the current browser tab is closed or reloaded.
This change is now retrieving the current route from the `router.routes` object (the current child route is the last object) and uses it to register the hook called when the current route is left.
In the future (with react-router v5), another refactoring is performed replacing the imperative logic from `ConfirmLeaveDialog` with the usage of the `Prompt` component.

Fixing dialog shown when abandoning changes on current page.

---

graylog2-web-interface/packages/graylog-web-plugin/package.json

This reverts commit d0c5de9387f8d2e18cf0d7105150b8861aff8464.
The upgrade requires a bit more work due to breaking changes in 5.x.

Revert "Bump webpack-merge (#9111)"

---

pom.xml

In #9139 JUnit4 was updated to `v4.13.1` due to a security issue.  Unfortunately, this version number is breaking the version check in the JUnit 5 vintage engine of `v5.6.0` and causes all JUnit5 tests to be silently ignored, although an exception during version parsing is thrown.
This change is now updating JUnit5 to `v5.7.0`. Unfortunately, testcontainers is using `v5.6.2`, effectively overriding the version for `junit-jupiter-api`, breaking `v5.7.0`. Therefore, this change is also updating testcontainers to `v1.15.0-rc2` (unfortunately there is currently no stable version using `v5.7.0`).

Fix JUnit5 vintage engine by updating to v5.7.0.

---

graylog2-web-interface/src/components/common/PaginatedList.jsx
graylog2-web-interface/src/components/common/PaginatedList.test.jsx

Prior to this change, the PaginatedList would use pageSize to caluclate
the amount of pages to show by deviding totalItems by pageSize.
But the code did not check if pageSize is 0 which leads to an NaN.
This change will check if pageSize is 0.
Fixes #9163

Prevent devision by 0 if PaginatedList pageSize prop is 0

---

graylog2-server/src/test/java/org/graylog/testing/elasticsearch/ElasticsearchInstance.java

Starting with testcontainers v1.15.0-rc2, it expects specific images compatible with their Elasticsearch container support to be used with it. Therefore we need to declare the OSS image we are using for integration tests to be compatible.

Declare custom ES image as compatible w/ testcontainers.

---

graylog2-web-interface/package.json
graylog2-web-interface/yarn.lock

In #9131 the `webpack-cli` dependency was updated to v4 for `graylog-web-plugin`. As core has an explicit dependency to it with a pinned version, it needs an explicit update of it to `4.0.0`.

Updating `webpack-cli` to v4.

---

graylog2-web-interface/src/components/users/UsersOverview/SystemAdministratorOverview.jsx

correct typo `can only be edit` -> `can only be edited`

Correct typo on SystemAdminOverview page

---

graylog2-server/src/main/java/org/graylog/events/notifications/EventNotificationModelData.java
graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailSender.java
graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotification.java

Every Event Notification seems to use the same block of code for creating an instance of `EventNotificationModelData`.  This change moves that block of code into a static method in `EventNotificationModelData` and updates existing Event Notifications to use the static method rather than using the same duplicated block of code.
This is being done to ensure that all Event Notifications continue to construct `EventNotificationModelData` consistently as that object grows and evolves.  
This change has been tested locally as part of development of the Script Event Notification plugin.

Refactor repeated code block into method

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/migrations/V20200730000000_AddGl2MessageIdFieldAliasForEventsES7.java
graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/migrations/V20200730000000_AddGl2MessageIdFieldAliasForEventsES7IT.java

Prior to this change, the migration which adds a field alias for pre-existing indices failed if no indices at all existed before.
This change is changing the indices options of the request to ignore unavailable indices or having no indices at all.
Fixes #9148.

Fix message id field alias migration for non-existing indices.

---

graylog2-server/src/main/java/org/graylog/grn/GRNTypes.java

Prior to this change, the dependency resolution which is using the
content pack mechanism tried to find the event notification type with
'event_notification' which is not a registered type in content pack.
This change will rename the type to `notification` so the dependency
resolution via content packs works again.

Rename EventNotification GRNType

---

graylog2-web-interface/src/routing/AppRouter.jsx
graylog2-web-interface/src/routing/AppRouter.test.jsx

Our application router allows plugins to register routes with a `null` parent component, which allows them to be rendered outside of our application chrome. This got broke in #9135, as react-router v5 is now rendering all matching routes (unless `Switch` is used) and the scoping of the `Switch` components and the plugin routes got messed up.
This change is now restoring the original behavior by
a) placing the `RouterErrorBoundary` outside of the `Switch` clause.
b) putting the application chrome components (`App`/`AppWith...`) inside the catch-all route for non-null-parent components.

Fix plugin routes with `null` parent components.

---

graylog2-web-interface/src/components/errors/ErrorPage.jsx

By creating the component once and parameterize it, instead of passing
in a parameter during creation, this avoids errors like:
```
The component sc-global-igkIyx has been created dynamically.
You may see this warning because you've called styled inside another component.
To resolve this only create new StyledComponents outside of any render method and function component.
```

Avoid creating style component inline.

---

graylog2-server/src/main/java/org/graylog2/web/resources/AppConfigResource.java
graylog2-server/src/main/resources/web-interface/config.js.template
graylog2-web-interface/config.js
graylog2-web-interface/src/components/navigation/Navigation.jsx
graylog2-web-interface/src/util/AppConfig.js
graylog2-web-interface/templates/config.js.template
graylog2-web-interface/webpack.combined.config.js
graylog2-web-interface/webpack.config.js

Exposes an `isCloud` flag via `config.js`.
When running in production mode, the flag is mirroring the `is_cloud` server configuration parameter which is by default `false` and has to be enabled explicitly.
When running in development mode (`env DEVELOPMENT=true`), the flag is `false` by default but will be automatically set to `true` when the cloud plugin is present.
When running in a cloud context, certain UI elements need to be different than for an on-premise deployment. With this flag exposed, the UI has an easy way to know about the context.
To see if this works in development mode I altered the `DEV` badge we show in the header. If the cloud context is detected, it now looks like this:
Checked that this works also in the production build by temporarily adding `console.log` debugging …

Expose `isCloud` to frontend

---

graylog2-web-interface/src/logic/permissions/GRN.js

Prior to this change, the dependency resolution which is using the
content pack mechanism tried to find the event notification type with
'event_notification' which is not a registered type in content pack.
This change will rename the type to `notification` so the dependency
resolution via content packs works again.

Rename EventNotification GRNType in frontend

---

graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyPermissionChecker.java
graylog2-server/src/main/java/org/graylog/security/shares/EntitySharesService.java

The initial prepareShare request does not contain any selectedGranteeCapabilities
The way this should be handled is to use the existing activeShares.
Fixes #9200

Use activeShares as a fallback for the dependency permission check

---

graylog2-web-interface/package.json
graylog2-web-interface/packages/graylog-web-plugin/package.json
graylog2-web-interface/vendor.modules.js
graylog2-web-interface/yarn.lock

This PR fixes a few security vulnerabilities from our dependencies.
Dependency updates:
- jquery to 3.5.1 ([GHSA-jpcq-cgw6-v4j6](https://github.com/advisories/GHSA-jpcq-cgw6-v4j6))
- serialize-javascript to 4.0.0 and 5.0.1 ([GHSA-hxcc-f52p-wc94](https://github.com/advisories/GHSA-hxcc-f52p-wc94))
The PR also removes the dependency to `react-addons-pure-render-mixin`, since we didn't use it and required a `node-fetch` version with vulnerabilities:
- node-fetch ([GHSA-w7rc-rwvf-8q5r](https://github.com/advisories/GHSA-w7rc-rwvf-8q5r))
This is the counterpart of #9098 for the master branch.

Fix potential security vulnerabilities from JS dependencies

---

graylog2-server/src/main/java/org/graylog/security/GranteeAuthorizer.java
graylog2-server/src/main/java/org/graylog/security/shares/DefaultGranteeService.java
graylog2-server/src/main/java/org/graylog/security/shares/GranteeService.java
graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java
graylog2-server/src/test/java/org/graylog/testing/TestUserService.java
graylog2-server/src/test/java/org/graylog/testing/TestUserServiceExtension.java
graylog2-server/src/test/java/org/graylog/testing/UserServiceExtension.java
graylog2-server/src/test/java/org/graylog/testing/mongodb/MongoDBExtension.java
graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/RolesToGrantsMigrationTest.java
graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/UserPermissionsToGrantsMigrationTest.java
graylog2-web-interface/src/logic/permissions/GRN.js

Graylog users are visible to other users if the user that is running
the query has `users:read` permissions on certain (or all) users.
The `users:read` permission can be conveniently assigned by using the
new `User Inspector` role.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#1833

Add GranteeService.getVisibleUsers()

---

graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendConfigDetails/EditLinkButton.jsx
graylog2-web-interface/src/pages/AuthenticationBackendEditPage.jsx
graylog2-web-interface/src/routing/Routes.jsx

This PR fixes the url query handling for the `AuthenticationBackendEditPage`. Previously the query param `initialStepKey` was not being used correctly. The query params was also not set correctly on the authentication backend details page.
On the details page we've used:
```
<LinkContianer to={
pathname,
query: {
initialStepKey: stepKey,
}
}>...
```
Due to the the react router upgrade https://github.com/Graylog2/graylog2-server/pull/9135 and the `LinkContainer` changes, `query` is no longer supported when using an object for the `to` prop. We need to use e.g.`to={ ..., search: '?=initialStepKey=the-key', }` instead or attach the query string directly:
```
const url = new URI(pathname)
.search({ initialStepKey: 'the-key })
.toString();
<LinkContianer to={url} />...
```

Fix AuthenticationBackendEditPage url query handling

---

graylog2-web-interface/src/views/components/sidebar/ContentColumn.jsx
graylog2-web-interface/src/views/components/sidebar/fields/FieldsOverview.jsx
graylog2-web-interface/src/views/components/sidebar/fields/List.jsx

This PR is fixing a vertical scrolling bug for the search content column, which occurred when using the `FieldList`.
It also fixes a `FieldList` resizing problem and removes the horizontal scrollbar for pinned sidebars.
Tested with Chrome, Firefox, Safari and IE11

Fix vertical scrolling for search sidebar content column

---

graylog2-web-interface/src/components/event-notifications/event-notification-details/EmailNotificationDetails.jsx
graylog2-web-interface/src/components/event-notifications/event-notification-details/EventNotificationActionLinks.jsx
graylog2-web-interface/src/components/event-notifications/event-notification-details/EventNotificationDetails.jsx
graylog2-web-interface/src/components/event-notifications/event-notification-details/HttpNotificationDetails.jsx
graylog2-web-interface/src/components/event-notifications/event-notification-details/LegacyNotificationDetails.jsx
graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationForm.jsx
graylog2-web-interface/src/components/event-notifications/event-notification-types/index.js
graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotifications.jsx
graylog2-web-interface/src/pages/EditEventNotificationPage.jsx
graylog2-web-interface/src/pages/ShowEventNotificationPage.jsx
graylog2-web-interface/src/pages/index.jsx
graylog2-web-interface/src/routing/AppRouter.jsx
graylog2-web-interface/src/routing/Routes.jsx

This PR implements details pages and the share dialog for event notifications. The share action can be found in the notifications list.
The backend already supports sharing event notifications, these changes are required to support it in the UI as well.

Implement share dialog and details pages for event notifications

---

graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionSummary.jsx
graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionValidationSummary.jsx
graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.jsx
graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationSummary.jsx
graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterPreviewContainer.jsx
graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionEntry.jsx
graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.jsx
graylog2-web-interface/src/pages/EditEventDefinitionPage.jsx
graylog2-web-interface/src/pages/EventDefinitionsPage.jsx
graylog2-web-interface/src/pages/EventNotificationsPage.jsx
graylog2-web-interface/src/pages/EventsPage.jsx
graylog2-web-interface/src/pages/StreamPermissionErrorPage.jsx
graylog2-web-interface/src/pages/ViewEventDefinitionPage.jsx
graylog2-web-interface/src/pages/index.jsx
graylog2-web-interface/src/routing/AppRouter.jsx
graylog2-web-interface/src/routing/Routes.jsx

Add share button to Event Definitions and create a read only page for a user with view permissions.
If a user wants to verify the settings for a event definition (as a revisor) then he needs a read only page.
If a user is missing stream or notification permissions a warning will be displayed but the page otherwise rendered

Event definition share dialog

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java
graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
graylog2-server/src/main/java/org/graylog/security/GrantChangedEvent.java
graylog2-server/src/main/java/org/graylog2/security/realm/MongoDbAuthorizationRealm.java
graylog2-server/src/test/java/org/graylog/security/DBGrantServiceTest.java
graylog2-server/src/test/java/org/graylog/security/shares/EntitySharesServiceTest.java
graylog2-server/src/test/java/org/graylog/security/shares/GranteeSharesServiceTest.java
graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/RolesToGrantsMigrationTest.java
graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/UserPermissionsToGrantsMigrationTest.java
graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/ViewOwnershipToGrantsMigrationTest.java
graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/ViewSharingToGrantsMigrationTest.java

Clear the Shiro authorization cache if grants change
Otherwise the we might run into a race when ownership grants
are created for new entities, but the cache doesn't contain
the new permissions.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#1862

Remove view userpermission

---

distribution/pom.xml

This fixes an error in release builds.
Also switch packaging to pom and skip source, javadoc, install and
deploy.

Don't sign any artifacts in the distribution module

---

graylog2-web-interface/src/views/components/Search.jsx
graylog2-web-interface/src/views/stores/FieldTypesStore.js
graylog2-web-interface/src/views/stores/QueryFiltersStore.js

Before this change, the `FieldTypesStore` returns empty field types for the current query, if the current query has no streams selected (which results in all streams being queried).
This change is now fixing the `QueryFiltersStore` to return queries with an empty filter as well, and fixes the `FieldTypesStore` to return all field types for queries which have an empty filter.
Start a new search. Enter any field name in the query input, see if it states that it is "not in streams" in the auto-completion.

Fix field types of current query if no stream is selected.

---

graylog2-web-interface/src/actions/authentication/AuthenticationActions.js
graylog2-web-interface/src/actions/roles/AuthzRolesActions.js
graylog2-web-interface/src/actions/users/UsersActions.js
graylog2-web-interface/src/components/authentication/BackendDetails/BackendDetails.jsx
graylog2-web-interface/src/components/authentication/BackendDetailsActive/BackendDetailsActive.jsx
graylog2-web-interface/src/components/authentication/BackendDetailsActive/SyncedUsersSection/SyncedUsersSection.jsx
graylog2-web-interface/src/components/authentication/BackendsOverview/BackendsOverview.jsx
graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/BackendWizard.jsx
graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/UserLoginTest.jsx
graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendCreate.jsx
graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendEdit.jsx
graylog2-web-interface/src/components/authentication/useActiveBackend.js
graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationFormContainer.jsx
graylog2-web-interface/src/components/permissions/RolesSelector.jsx
graylog2-web-interface/src/components/roles/RoleEdit/UsersSelector.jsx
graylog2-web-interface/src/components/roles/RolesOverview/RolesOverview.jsx
graylog2-web-interface/src/components/users/UserCreate/UserCreate.jsx
graylog2-web-interface/src/components/users/UserEdit/RolesSection.jsx
graylog2-web-interface/src/domainActions/notifyingAction.js
graylog2-web-interface/src/pages/AuthenticationBackendDetailsPage.jsx
graylog2-web-interface/src/pages/AuthenticationBackendEditPage.jsx
graylog2-web-interface/src/pages/UserTokensEditPage.jsx
graylog2-web-interface/src/stores/authentication/AuthenticationStore.js
graylog2-web-interface/src/stores/roles/AuthzRolesStore.js
graylog2-web-interface/src/stores/users/UsersStore.js

This PR refactors most type definitions for actions which are using the `notifyingAction`. We made sure, that the `notifyingAction` only returns on success and otherwise throws an error. This way all action response type definitions only need to consider the success case. It also simplifies processing the return value of these actions in components.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#1840

Update type definitions for AuthenticationActions, AuthzRolesActions, and UsersActions

---

graylog2-server/src/main/java/org/graylog2/notifications/Notification.java
graylog2-web-interface/src/logic/notifications/NotificationsFactory.js

In some rare circumstances, we may need to shut down a running Input due to persistent failures.  This change adds a new notification type to be used in that case.
This has been tested locally with the Office 365 input.

Add a new notification type for input shutdown due to failures.

---

graylog2-web-interface/src/components/permissions/ShareableEnityURL.jsx

Prior to this change, clicking on the copy to clipboard button would
not work since the clipboard buttone could not find it's container.
This change will save the container in a ref and pass it to the
clipboard as a prop.
Fixes #9254

Fix the shareable link copy button

---

graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.jsx

Prior to this change, the Save button was shown to a user which only had
view permissions to a Saved Search. If he clicked on that button the
result was an error page.
This change will hide the 'Save' and 'Save as' button and shows a
'Create New' button to make clear he has to create a new Search which he
can edit.
Fixes #8894

Saved Search: Hide Save button for missing edit perissions

---

graylog2-server/src/main/java/org/graylog2/indexer/GIMMapping.java
graylog2-server/src/main/java/org/graylog2/indexer/GIMMapping6.java
graylog2-server/src/main/java/org/graylog2/indexer/GIMMapping7.java
graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java
graylog2-server/src/main/java/org/graylog2/indexer/IndexMappingFactory.java
graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetConfig.java
graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/responses/IndexSetSummary.java
graylog2-server/src/test/java/org/graylog2/indexer/GIMMapping6Test.java
graylog2-server/src/test/java/org/graylog2/indexer/GIMMapping7Test.java
graylog2-server/src/test/java/org/graylog2/indexer/GIMMappingTest.java
graylog2-server/src/test/resources/org/graylog2/indexer/expected_gim_template.json
graylog2-server/src/test/resources/org/graylog2/indexer/expected_gim_template6.json
graylog2-server/src/test/resources/org/graylog2/indexer/expected_gim_template7.json

As a Graylog user, I would want to be able to configure an index set to use the Graylog Information Model mapping template, so every new index created in this index set automatically has the proper mappings.
This PR is adding a mapping template class similar to our standard mapping template, which includes the field types and namings as defined in the Graylog Information Model. A new possible value (`generic`) is added for the `index_template_type` field of the index set config, which can be used to enable the usage of this template type for a given index set.

Offer GIM as a template option for index set configs.

---

graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/BackendWizard.jsx
graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/GroupSyncStep.jsx
graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/wizardSteps.jsx
graylog2-web-interface/src/components/authentication/directoryServices/activeDirectory/BackendEdit.jsx
graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendCreate.jsx
graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendEdit.jsx

Previously there was no Finish & Save on the directory service group sync step, if no enterprise plugin exists.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/1858

Display Finish & Save button for the directory service group sync step if no enterprise plugin exists

---

graylog2-web-interface/src/components/authentication/useActiveBackend.js

Previously the active backend fetching was part of an `useEffect` which had unrelated dependencies. This resulted in a loop. This PR is fixing the behaviour by creating an own `useEffect` for the active backend fetching.

Fix active backend fetching on authentication pages

---

graylog2-web-interface/.vscode/settings.json
graylog2-web-interface/src/components/permissions/EntityShareModal.test.jsx
graylog2-web-interface/src/components/permissions/EntityShareSettings.jsx
graylog2-web-interface/src/components/permissions/ShareableEntityURL.jsx
graylog2-web-interface/src/logic/permissions/GRN.js

As described in #9270 the sharable URL displayed inside the share modal is not correct when opening the modal for an entry of an overview, like the dashboards list. With this PR the URL is always based on the `entityGRN` and not the current location.
Fixes #9270

Display correct sharable URL on entity overview pages

---

graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
graylog2-server/src/main/java/org/graylog2/security/MongoDbSession.java

The session activity indicators on the users overview and the user
details page were broken because of the following:
1. The `GET /users/<username>` endpoint didn't load the session
information for the given user
2. The code tried to find the user sessions by username but we recently
switched to user IDs for the principal session key
This change also refactors the session lookup to avoid code duplication
in several places.
Fixes #9175
Fixes #9241

Fix session activity indicator for users

---

graylog2-server/src/main/java/org/graylog2/alarmcallbacks/EmailAlarmCallback.java
graylog2-server/src/main/java/org/graylog2/alarmcallbacks/HTTPAlarmCallback.java
graylog2-server/src/test/java/org/graylog2/alarmcallbacks/HTTPAlarmCallbackTest.java
graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationForm.jsx

This change updates text displayed when creating Legacy Alarm Callbacks to inform the user that they are deprecated and will be removed in a future version of Graylog.
As of Graylog 3.2, Legacy Alarm Callbacks were replaced with the new Notifications feature.  With Graylog 4.0, the final Legacy Alarm Callback (Script Alarm Callback) has been made available as a Notification.  In order to support the desired removal of Legacy Alarm Callbacks from the codebase, we are updating the text associated with Legacy Alarm Callbacks to clearly mark them as deprecated and nudge users to migrate to Notifications.
Verified the UI changes locally

Deprecation notices for Legacy Alarm Callbacks

---

graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/BackendWizard.jsx

Previously it was possible that the directory service payload contains a password with an empty string.
This was the case when a user:
1. Fills out the password input in the server config step
2. Goes to the another step
3. Goes back to the server config step
4. Removes the previously defined password
5. Triggers a connection test
With this PR we ensure that we do not submit an empty string for the password value.
Fixes #9183

Prevent empty string in directory service update and create password payload

---

graylog2-web-interface/src/components/common/DataTable/DataTable.jsx
graylog2-web-interface/src/components/common/DataTable/Filter.jsx
graylog2-web-interface/src/components/common/PaginatedDataTable/Filter.jsx
graylog2-web-interface/src/components/common/PaginatedDataTable/PaginatedDataTable.jsx
graylog2-web-interface/src/components/common/PaginatedDataTable/index.js
graylog2-web-interface/src/components/common/TypeAheadDataFilter.jsx
graylog2-web-interface/src/components/common/index.jsx

This PR adds the `PaginatedDataTable` component to our `common` components directory. The `DataTable` component is only able to display the provided rows. When we have a list which is not getting paginated by the backend, we can't just combine the `DataTable` with the `PaginatedList`. This PR adds a component which handles this use case and ensures that the tables pagination works correctly in combination with the filter.

Implement PaginatedDataTable component

---

graylog2-server/src/main/java/org/graylog/security/shares/EntitySharesService.java
graylog2-server/src/test/java/org/graylog/security/shares/EntitySharesServiceTest.java
graylog2-server/src/test/resources/org/graylog/security/shares/EntitySharesServiceTest.json

Filter the activeShares result so it contains only grantees
that are visible to the requesting user.

Don't expose shares with invisible grantees

---

graylog2-server/src/main/java/org/graylog/security/authzroles/AuthzRolesResource.java
graylog2-web-interface/src/components/roles/RoleEdit/UsersSection.jsx
graylog2-web-interface/src/components/users/UserEdit/RolesSection.jsx

Prior to this change, an admin could remove all roles from a user which
would render the user useless.
This change will check if the roles after a deletion will at least
contain a reader or an admin role and otherwise prevent deletion and
showing a warning.
Fixes #8752

Ensure a user has at least reader or admin role

---

graylog2-web-interface/src/components/graylog/router.jsx
graylog2-web-interface/src/components/rules/Rule.jsx
graylog2-web-interface/src/pages/EventDefinitionsPage.jsx
graylog2-web-interface/src/pages/EventNotificationsPage.jsx
graylog2-web-interface/src/pages/EventsPage.jsx
graylog2-web-interface/src/pages/LUTCachesPage.jsx
graylog2-web-interface/src/pages/LUTDataAdaptersPage.jsx
graylog2-web-interface/src/pages/LUTTablesPage.jsx
graylog2-web-interface/src/pages/PipelineDetailsPage.jsx
graylog2-web-interface/src/pages/PipelinesOverviewPage.jsx
graylog2-web-interface/src/pages/RulesPage.jsx
graylog2-web-interface/src/pages/ShowAlertPage.jsx
graylog2-web-interface/src/pages/SidecarAdministrationPage.jsx
graylog2-web-interface/src/pages/SidecarConfigurationPage.jsx
graylog2-web-interface/src/pages/SidecarsPage.jsx
graylog2-web-interface/src/pages/SimulatorPage.jsx

With https://github.com/Graylog2/graylog2-server/pull/9135 we've added an own implementation of `LinkContainer`, because the `LinkContainer` provided by `react-router-bootstrap` changed its behaviour with a previous update.
Instead of defining `onClick` for its children it transformed them into a link.
With this PR we are adding the functionality that `Buttons` wrapped with `LinkContainer` receive the `active` class, if the target of the `LinkContainer` equals the current pathname.
We are also removing not needed `className="active"` props from `Buttons` wrapped with `LinkContainer`.
There are still some buttons where we need to set this prop manually.
Please note there is a linter warning which is not related to these changes.
Fixes: #9244

Provide active className for Buttons wrapped with LinkContainer if link target equals current pathname

---

graylog2-server/src/test/java/org/graylog2/security/ldap/LdapConnectorSSLTLSIT.java
graylog2-server/src/test/java/org/graylog2/shared/security/SessionCreatorTest.java

Use the `javax.annotation.Nonnull` annotation instead of `org.jetbrains.annotations.NotNull` which is not available in all environments. The same change was made in https://github.com/Graylog2/graylog2-server/pull/9169 and ports the compatible `3.3` file changes over to `cloud-3.3`.
This incorrect import only caused the following error in some environments, such as running the Graylog Server with the [Docker tool](https://github.com/Graylog2/graylog-project-internal/blob/5dbe21d3b37fca04570620bf177a3525e1104fb3/runner/README.md).

Remove Jetbrains NotNull annotation

---

graylog2-server/src/main/java/org/graylog/security/shares/GranteeSharesService.java
graylog2-server/src/main/java/org/graylog2/database/PaginatedList.java
graylog2-server/src/test/java/org/graylog/security/shares/GranteeSharesServiceTest.java

- 'total' should contain the count of all filtered results (ignoring pagination)
- 'grand_total' should contain the count of all results (also ignoring filters)
fixes #9291

Return correct PaginatedList results

---

graylog2-web-interface/src/components/users/UserCreate/UserCreate.jsx

The submit button on the user create form is disabled when the create request is pending.
Previously the submit button never got enabled., if there the request returned a server error:
(Please note, I removed the client side validation  locally to receive this error)
With this PR we are returning the create promise to ensure formik updates `isSubmitting` correctly.

Do not disable user create submit button on server error

---

graylog2-web-interface/src/components/common/HoverForHelp.jsx
graylog2-web-interface/src/components/common/ShareButton.jsx
graylog2-web-interface/src/components/common/ShareButton.test.jsx
graylog2-web-interface/src/components/common/index.jsx
graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionEntry.jsx
graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotifications.jsx
graylog2-web-interface/src/components/permissions/EntityShareModal.jsx
graylog2-web-interface/src/components/permissions/SharingDisabledPopover.jsx
graylog2-web-interface/src/components/streams/Stream.jsx
graylog2-web-interface/src/components/streams/StreamControls.jsx
graylog2-web-interface/src/routing/AppRouter.jsx
graylog2-web-interface/src/routing/Routes.jsx
graylog2-web-interface/src/views/components/DashboardSearchBar.jsx
graylog2-web-interface/src/views/components/ViewActionsMenu.jsx
graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.jsx
graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.test.jsx
graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchControls.test.jsx.snap
graylog2-web-interface/src/views/components/views/ViewList.jsx

Entities like dashboards, streams and event definitions can be shared with the share action. This action is currently part of the entities action menu:
With this PR we are creating an own button for the share actions on the highest level:
Please note, there are unrelated ESlint warnings.
Fixes: #9247

Display entity share buttons next to entity action menu

---

graylog2-web-interface/src/components/users/PermissionsUpdateInfo.jsx
graylog2-web-interface/src/components/users/UserDetails/UserDetails.jsx
graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx
graylog2-web-interface/src/util/DocsHelper.js

With Graylog 4.0 we've update the permissions system. Previously, sharing entities like dashboards and streams has been part of the user edit page, now it can be done with the share button of an entity, which is e.g part of the entities overview page.
With this PR we explain this change on the user edit and details page, so users will understand where they can grant permissions for an entity.
Initially I planned to include the share button component inside the info text, but this way the text would take up even more space.
Fixes: #9249

Display info about permissions update on user edit and details page

---

graylog2-web-interface/src/pages/RolesOverviewPage.jsx

With Graylog 4.0 we've update the permissions system. Previously, granting permissions for an entity like dashboards and streams could be done by using roles. Now roles only grant capabilities like creating dashboards.
With this PR we explain this change on the roles overview page, so users will understand where they can grant permissions for an entity.

Display info about permissions update on roles overview page

---

graylog2-web-interface/src/components/graylog/LinkContainer.test.jsx
graylog2-web-interface/src/components/graylog/router.jsx
graylog2-web-interface/src/components/roles/RolesOverview/ActionsCell.test.jsx

Before this change, the `LinkContainer` component did add an `onClick` handler to its children to perform a route change without reloading the app. This lead to the element being created not having an `href` prop, so clicking on it and opening it in a new tab did not work.
This change is adding an `href` prop containing the value of the `to` prop to its children, so the html element contains a valid target.
Fixes #9298.

Add target as href to `LinkContainer` children.

---

graylog2-web-interface/src/components/users/UserCreate/UserCreate.jsx
graylog2-web-interface/src/components/users/UserCreate/UserCreate.test.jsx

Prior to this change, if a user was creating a user with leading spaces
the leading spaces were stored into the backend and the user would have
to login with this leading spaces.
This change will trim the username input before submiting it to the
server.
Fixes #8593

Trim string of username when creating a user

---

graylog2-web-interface/src/components/users/LoggedInIcon.jsx

Prior to this change, we displayed a red filled cirle to the user if a
user was logged of. This has several disadvantages:
- It is signaling an error
- it is unsuitable for people with a red green weakness.
This change will change the color from red to gray.
Fixes #9240

Use gray to display a logged of user

---

graylog2-web-interface/src/components/common/ErrorAlert.jsx
graylog2-web-interface/src/components/common/ErrorAlert.test.jsx
graylog2-web-interface/src/components/common/index.jsx
graylog2-web-interface/src/components/permissions/RolesSelector.jsx
graylog2-web-interface/src/components/roles/RoleEdit/UsersSection.jsx
graylog2-web-interface/src/components/roles/RoleEdit/UsersSelector.jsx
graylog2-web-interface/src/components/users/UserEdit/RolesSection.jsx

Prior to this change, when we had an runtime error we rendered the error
page to the user even though he might have been able to workarround an
issue.
This change implements a ErrorAlert component which is closable and
which will display an runtime error or warning. It replaces the
warnings already implemented and does also replace the `throw` errors
for users and roles components.
Fixes #8756

Avoid using throw by displaying an Alert

---

graylog2-web-interface/src/components/navigation/SystemMenu.jsx
graylog2-web-interface/src/components/navigation/SystemMenu.test.jsx

Prior to this change, the grok patterns were acutally already
accesisable for users with Reader role, but we hid the Navigation Item.
This change will change the permission check for the grok patterns
navigation item for reader role.

Show grok patterns to users with reader role

---

graylog2-web-interface/src/components/users/UserCreate/UserCreate.jsx

Previously the user create form buttons column had a not needed offset with a window width < 992px:
With this PR we only display the offset when needed:

Fix grid layout for user create form buttons

---

graylog2-server/src/main/java/org/graylog/security/SecurityAuditEventTypes.java

The audit event types for the authentication service resources didn't adhere to the naming convention of `<namespace>:<object>:<action>`.

Fix audit event types for auth service endpoints

---

graylog2-web-interface/src/views/components/sidebar/Sidebar.jsx
graylog2-web-interface/src/views/components/sidebar/Sidebar.test.jsx
graylog2-web-interface/src/views/components/sidebar/SidebarNavigation.jsx

Previously, clicking on the navigation item of an active search sidebar section had no effect.
With this PR we are closing the sidebar in this case. This improves the usability and unifies the behaviour with the Graylog 3.x sidebar.

Close active search sidebar section when clicking on its navigation item

---

graylog2-web-interface/src/views/components/Search.jsx
graylog2-web-interface/src/views/components/searchbar/queryinput/StyledAceEditor.jsx

Previously the search loading indicator was not visible when a modal is being displayed. A result was that a user could not see the indicator while editing the query of a widget.
The loading indicator and the modal already had the correct `z-index`, but the indicator was not visible because it is part of the search grid which had an index of 1. We probably added this index to make sure its content is not being displayed above any overlay. This PR removes this index. It also adjusts the `z-index` of the search query placeholder, to ensure it is not being displayed above an overlay.

Fix z-index of the search loading indicator

---

graylog2-web-interface/src/components/common/PageHeader.jsx
graylog2-web-interface/src/components/common/PageSizeSelect.jsx
graylog2-web-interface/src/components/common/SearchForm.css
graylog2-web-interface/src/components/common/SearchForm.jsx

Previously the layout of pages like the user overview looked slightly broken with a window width < 992px.
This PR is improving the responsiveness by adjusting the SearchForm, PageSizeSelect and PageHeader styling.
Fixes: #8794

Improve SearchForm, PageSizeSelect and PageHeader layout responsiveness

---

graylog2-web-interface/src/components/graylog/LinkContainer.test.jsx
graylog2-web-interface/src/components/graylog/router.jsx

Before this change, all click events on a `LinkContainer` were stopped, including click events with modifier keys (e.g. Ctrl) being held. This prevents browser functionality like Ctrl+Click to open a link in a new tab.
This change is adding a check to the generated `onClick` handler, stopping all processing and stopping the event if a modifier was held during clicking.

Do not stop click events on `LinkContainer` if modifier-keys are used.

---

graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/MessagesAdapterES6.java
graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/MessagesAdapterES6Test.java
graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesIT.java

**Note:** This PR is porting #9065 for ES6.
Prior to this change, when a message is tried to be ingested into Elasticsearch when the primary shard of an index is unavailable, indexing will fail and the message will be turned into an indexing failure. Most probably, this is not what a user wants.
In most cases an unavailable primary shard is a) affecting most, if not all indices, b) is a temporary condition. These properties and the similarities to scenarios where a watermark threshold switches indices to read-only do justify a handling of this that attempts retries indefinitely until the condition is resolved.
While this prevents message loss, it can also cause journal overflow (and causing message loss at the other end of ingestion), while it buys operations time to fix the issue. Due to …

Retry indexing message if primary shard is not active for ES6.

---

graylog2-web-interface/src/components/roles/RoleDetails/RoleDetails.jsx
graylog2-web-interface/src/components/roles/RoleDetails/TeamsSection.jsx
graylog2-web-interface/src/components/roles/RoleEdit/RoleEdit.jsx
graylog2-web-interface/src/components/roles/RoleEdit/TeamsSection.jsx
graylog2-web-interface/src/components/users/UserDetails/TeamsSection.jsx
graylog2-web-interface/src/components/users/UserEdit/TeamsSection.jsx
graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx

This PR implements a `TeamsSection` for the role edit and details page which references the enterprise `RoleTeamsAssignment` component. This way we display all assigned teams on the role details page and allow the team assignment on the role edit page.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#1891

Implement teams management for roles

---

graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java
graylog2-server/src/main/java/org/graylog2/migrations/V20201103145400_LegacyAuthServiceMigration.java
graylog2-server/src/main/java/org/graylog2/notifications/Notification.java
graylog2-web-interface/src/logic/notifications/NotificationsFactory.js
graylog2-web-interface/src/util/DocsHelper.js

This creates a migration to create a new authentication service based on
an existing legacy LDAP/AD configuration.
Since the legacy LDAP/AD configuration doesn't contain all information
we need for a new authentication service, we guess some config fields
and create a system notification to make sure an admin will notice it
and reviews and activates the migrated configuration.
Closes #9078

Add migration for legacy LDAP/AD configuration

---

graylog2-server/src/main/java/org/graylog2/shared/security/tls/DefaultTLSProtocolProvider.java

Previously we only checked the protocols that are enabled by default
instead of checking all available.
This allows the usage of TLSv1.3 in OpenJDK 8u272 and later.
See: https://blog.adoptopenjdk.net/2020/10/adoptopenjdk-8u272-1109-and-1501-available/

Fix JDK TLS protocol detection

---

graylog2-web-interface/src/components/metrics/MetricsComponent.jsx
graylog2-web-interface/src/pages/ShowMetricsPage.jsx
graylog2-web-interface/src/stores/metrics/MetricsStore.js

Ensure we can load the node metrics page, also when it was not possible getting node metrics.
This was tested with the patch included in the issue description:
```
--- a/graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterNodeMetricsResource.java
+++ b/graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterNodeMetricsResource.java
@@ -120,6 +120,9 @@ public class ClusterNodeMetricsResource extends ProxiedResource {
@ApiParam(name = "namespace", required = true)
@PathParam("namespace") String namespace) throws IOException, NodeNotFoundException {
final Response<MetricsSummaryResponse> result = getResourceForNode(nodeId).byNamespace(namespace).execute();
+        if (Math.random() > 0.25) {
+            throw new RuntimeException("YOLO");
+        }
if …
```

Fail graciously when cannot get node metrics

---

graylog2-web-interface/src/components/permissions/GranteeIcon.jsx
graylog2-web-interface/src/components/permissions/GranteesListItem.jsx
graylog2-web-interface/src/logic/permissions/EntityShareState.js
graylog2-web-interface/src/logic/permissions/types.js

Prior to this change, if grantee was not found for the share dialog the
gui threw an error.
This change will display the grantees ID together with an exclamation
icon and a note that this is an error.
Fixes #9355

Display an warning if a grantee was not found

---

graylog2-web-interface/src/components/roles/RoleEdit/RoleEdit.test.jsx
graylog2-web-interface/src/components/roles/RoleEdit/TeamsSection.test.jsx
graylog2-web-interface/src/components/roles/RoleEdit/UsersSection.test.jsx
graylog2-web-interface/src/components/users/UserEdit/PasswordSection.test.jsx
graylog2-web-interface/src/components/users/UserEdit/ProfileSection.test.jsx
graylog2-web-interface/src/components/users/UserEdit/RolesSection.test.jsx
graylog2-web-interface/src/components/users/UserEdit/SettingsSection.test.jsx
graylog2-web-interface/src/components/users/UserEdit/TeamsSection.test.jsx
graylog2-web-interface/src/components/users/UserEdit/UserEdit.test.jsx

Previously the `UserEdit.test.jsx` and `RoleEdit.test.jsx` failed occasionally. The main problem was, that we are doing multiple requests on this page and some of them do not trigger an UI change which can be handled with `screen.findBy*`. We would have to wrap each promise mock in an act in every test, to make sure we handle them correctly. But even in this case some tests would run longer that one second.
With this PR we are splitting the both tests up in multiple files, one for each section.

Improve UserEdit and RoleEdit tests by splitting them up

---

graylog2-web-interface/src/components/authentication/BackendsOverview/BackendsOverviewItem.jsx
graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendCreate.jsx
graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendEdit.jsx
graylog2-web-interface/src/domainActions/authentication/AuthenticationDomain.js

Previously, we've implemented closures for some authentication domain actions, to be able to control the notification, when updating and creating an authentication service. This was necessary because there are cases were we do not want to trigger a notification.
```
AuthenticationDomain.create(backendCreateNotificationSettings)(payload);
```
This is an unusual usage which can be confusing, we now call the authentication actions directly and tigger the user notification inside the create and update component.

Remove unusual domain actions usage in auth backend edit and create component

---

graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx
graylog2-web-interface/src/components/users/UserEdit/UserEdit.test.jsx

Prior to this change, synced (external) users had the profile and
password section on their edit page, which should be in sync with the
configured authentication service and not be managed by graylog itself.
This change will hide these sections so a admin does not change anything
and expects a different password.
Fixes #9222

Hide edit profile and password section for external user

---

graylog2-server/src/main/java/org/graylog2/shared/journal/KafkaJournal.java
graylog2-server/src/test/java/org/graylog2/shared/journal/KafkaJournalTest.java

Previously the journal reader got stuck waiting when reading from an offset that returned an empty result.
In that case the journal reader assumes that it reached the end of the journal and waits for more messages to come in. Once new messages have been written to the journal, the reader is trying again with the same offset.
With a corrupted log segment, reading the same offset will return an empty result again. Even though there are valid messages in new segments after the corrupted one.
This put the journal reader in an infinite loop until the corrupted journal segment gets deleted manually or users delete the complete journal.
The code is now checking if there are more messages after the current read offset when an empty result is received from the read operation. In that case it …

Fix read handling of corrupted journal segments

---

graylog2-web-interface/src/components/permissions/RolesSelector.jsx

The `RolesSelector` previously contained a form and still has a button with `type="submit"`. Because of this type the user and team create form, which use the `RolesSelector`, currently do not submit on enter.
This PR changes the `RolesSelector` button type to `button`.
Fixes: https://github.com/Graylog2/graylog-plugin-enterprise/issues/1911

Change RolesSelector button type from submit to button 

---

graylog2-server/src/main/java/org/graylog2/shared/journal/KafkaJournal.java
graylog2-server/src/test/java/org/graylog2/shared/journal/KafkaJournalTest.java

We noticed a race condition during testing on a live setup. Reverting until it's been fixed.
Reverts Graylog2/graylog2-server#9306

Revert "Fix read handling of corrupted journal segments"

---

graylog-storage-elasticsearch6/pom.xml
graylog-storage-elasticsearch7/pom.xml

Disable deployment for now because we don't need it at the moment.

Enable sources build for ES storage modules

---

graylog2-server/src/main/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/GrantsMetaMigration.java
graylog2-server/src/main/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/UserPermissionsToGrantsMigration.java
graylog2-server/src/test/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/UserPermissionsToGrantsMigrationTest.java
graylog2-server/src/test/resources/org/graylog2/migrations/V20200803120800_GrantsMigrations/MigrateUserPermissionsToGrantsTest.json

Previously we created "search" grants for view permissions in users.
This was not correct because a view can also be a dashboard.
The migration is now lookin up the view in the database and creates a
grant based on the view type.
Fixes #9376

Fix view type detection for user permission migration

---

graylog2-web-interface/src/components/common/InputDescription.jsx

With https://github.com/Graylog2/graylog2-server/pull/9059 we've added the `error` prop for our `Input` component, to be able to display errors next to the help text.
With these changes we've defined a color for help text, to ensure the color does not change when the related `Input` has the prop `bsStyle="error"`.
A side effect is that errors of `Input`'s which still use `help` prop, do not have the correct color:
With this PR we are removing this styling change. 
This also means `Input`'s which already use the new error prop will look like this: 
(The help text has the error color when an error occurs)
But this is still a better solution than the alternative in terms of usability. I had a look at the cases where we use the `help` prop to display an error, but it is not a suitable …

Fix Input error color for Inputs which use the help prop to display errors

---

graylog2-web-interface/src/components/common/ShareButton.jsx
graylog2-web-interface/src/components/common/ShareButton.test.jsx
graylog2-web-interface/src/components/permissions/SharingDisabledPopover.jsx
graylog2-web-interface/src/views/components/ViewActionsMenu.jsx
graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.jsx
graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.test.jsx
graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchControls.test.jsx.snap

As described in https://github.com/Graylog2/graylog2-server/issues/9382 an unsaved search cannot be shared and there is no explanation why it cannot be shared. With this PR we are showing an explanation, that a search / dashboards needs to be saved first.

Display explanation for share button why unsaved searches and dashboards can not be shared

---

graylog2-web-interface/src/components/metrics/MetricsComponent.jsx
graylog2-web-interface/src/pages/ShowMetricsPage.jsx
graylog2-web-interface/src/stores/metrics/MetricsStore.js

Backport of #9316 for 3.3.
Fixes #9315.

Fail graciously when cannot get node metrics (#9316)

---

graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ClientES7.java
graylog2-server/src/test/java/org/graylog/testing/elasticsearch/ElasticsearchInstance.java

Due to the version constraint of "^6.0.0" we only used the OSS container
for ES 6.x.
Adjust ClientES7#existingTemplates to not use a wildcard ("*") argument
when creating the GetIndexTemplatesRequest object.
Using the wildcard argument with no existing index templates returns a
404 from ES and throws an exception.
This fixes the IndicesGetAllMessageFieldsES7IT test when switching to
the OSS container. The regular ES container is automatically creating
indices for x-pack features so there are always existing indices and
index templates. The OSS container doesn't create any indices and
templates by default and so the #existingTemplates call failed with a
404.

Make sure to use the OSS ES container for tests

---

graylog2-server/src/main/java/org/graylog2/rest/resources/system/SessionsResource.java
graylog2-server/src/main/java/org/graylog2/security/realm/HTTPHeaderAuthenticationRealm.java

With this change, we will implicitly create a session, when no session exists yet, but the user has been authenticated based on a trusted header.
This PR also fixes a wrong response to the session validation request.
Fixes #9403 
Tested with the instructions in #9403

Create session when user can be authenticated based on trusted header

---

graylog2-server/src/main/java/org/graylog/events/search/EventsSearchService.java

This ensures that the search result only contains events and not other
message types that might have been stored in the event indices.

Fix EventsSearchService to only filter for event messages

---

graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/BackendWizard.jsx
graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/BackendWizardContext.jsx
graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/GroupSyncStep.jsx
graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/ServerConfigStep.jsx
graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/UserSyncStep.jsx
graylog2-web-interface/src/components/common/FormikInput.jsx
graylog2-web-interface/src/components/common/InputDescription.jsx

Previously backend validation errors in the directory service wizard were just displayed under the current form. With this PR we are displaying a backend validation message as an input validation error. If the error relates to an input which is part of a different wizard step we navigate to the specific step on submit.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#1922

Display backend validation errors next to related input in directory service wizard

---

graylog2-server/src/main/java/org/graylog/security/entities/EntityOwnershipService.java
graylog2-server/src/main/java/org/graylog2/contentpacks/facades/StreamFacade.java
graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java
graylog2-server/src/main/java/org/graylog2/streams/StreamService.java
graylog2-server/src/main/java/org/graylog2/streams/StreamServiceImpl.java
graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/processors/ConfigurationStateUpdaterTest.java
graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackServiceTest.java
graylog2-server/src/test/java/org/graylog2/contentpacks/facades/StreamCatalogTest.java

And remove code that writes user permissions.
While we haven't complete support for grants in the processing layer,
it's cleaner to support ownership with grants now.

Register ownership for streams

---

graylog2-web-interface/src/components/graylog/Popover.jsx
graylog2-web-interface/src/components/graylog/Tooltip.jsx
graylog2-web-interface/src/contexts/CurrentUserPreferencesProvider.jsx
graylog2-web-interface/src/contexts/ThemeAndUserProvider.jsx
graylog2-web-interface/src/pages/LoggedInPage.jsx
graylog2-web-interface/src/theme/GraylogThemeProvider.jsx
graylog2-web-interface/src/theme/UseCurrentThemeMode.jsx

Initially the Theme was being generated before the user was loaded. 
This has been updated by creating a User and Theme context wrapper that we can then reuse as necessary to verify that we can loading in the proper User preferences before generating the theme
Theme would not always load the same one in user preferences consistently and some Popovers and Tooltips were not loading in the same theme as other parts of the app.

Consistently Load the Proper Theme

---

graylog2-web-interface/src/components/authentication/BackendsOverview/BackendsOverview.jsx
graylog2-web-interface/src/components/authentication/BackendsOverview/BackendsOverviewItem.jsx
graylog2-web-interface/src/components/authentication/directoryServices/BackendConfigDetails/ServerConfigSection.jsx
graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/BackendWizard.jsx
graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/BackendWizardContext.jsx
graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/ServerConfigStep.jsx
graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/UserSyncStep.jsx
graylog2-web-interface/src/components/authentication/directoryServices/PrepareInitialWizardValues.js
graylog2-web-interface/src/components/authentication/directoryServices/activeDirectory/BackendCreate.jsx
graylog2-web-interface/src/components/authentication/directoryServices/ldap/BackendCreate.jsx
graylog2-web-interface/src/domainActions/authentication/AuthenticationDomain.js

_This PR is based on https://github.com/Graylog2/graylog2-server/pull/9412 which needs to be merged first_
The title of an authentication backend is currently based on the service type + the server address and can't be configured. 
With this PR we are adding inputs for both fields to the server configuration step. We also display de description in backends overview and on the details page.
With custom titles it will be easier to differentiate between authentication backends.
Fixes https://github.com/Graylog2/graylog2-server/issues/9359

Allow configuring title and description of an authentication backend

---

graylog2-web-interface/src/logic/permissions/EntityShareState.fixtures.json
graylog2-web-interface/src/logic/permissions/EntityShareState.js
graylog2-web-interface/src/logic/permissions/EntityShareState.test.js
graylog2-web-interface/src/logic/permissions/__snapshots__/EntityShareState.test.js.snap

Prior to this change, if a share dialog has a lot of selected grantees
the pagination is shown. With the current ordering new entries to the
selection could be displayed somewhere in the pagination and a user
would not see that he had selected a new entry.
This change will put the new grantees to the beginning of the entity
share modal.
Fixes #8765

We put new selections to the top of selected grantees

---

graylog2-server/src/main/java/org/graylog/security/authzroles/AuthzRolesResource.java
graylog2-server/src/main/java/org/graylog2/users/PaginatedUserService.java
graylog2-web-interface/src/actions/roles/AuthzRolesActions.js
graylog2-web-interface/src/components/roles/RolesOverview/RolesOverview.jsx
graylog2-web-interface/src/components/roles/RolesOverview/RolesOverview.test.jsx
graylog2-web-interface/src/components/roles/RolesOverview/RolesOverviewItem.jsx
graylog2-web-interface/src/components/roles/RolesOverview/UsersCell.jsx
graylog2-web-interface/src/components/users/UserEdit/RolesSection.jsx
graylog2-web-interface/src/logic/roles/Role.js
graylog2-web-interface/src/stores/roles/AuthzRolesStore.js
graylog2-web-interface/src/stores/users/RolesStore.js

This PR will display the users of a role on the roles overview page.
All other overview pages display their relationships. So the user expects to see the users of a role on the roles overviewpage.
Fixes #9219

Show users in roles overview

---

graylog2-web-interface/src/components/authentication/BackendsOverview/BackendsOverviewItem.jsx
graylog2-web-interface/src/components/common/TextOverflowEllipsis.jsx
graylog2-web-interface/src/components/common/index.jsx
graylog2-web-interface/src/components/roles/RolesOverview/RolesOverviewItem.jsx

There are some cases where we want to signal text overflow with an ellipses. This PR creates a shared component and implements it for the description cell in `RolesOverviewItem` and `BackendOverviewItem`.

Create common TextOverflowEllipsis component and implement it for roles and auth backend overview

---

graylog2-server/src/main/java/org/graylog2/security/realm/SessionAuthenticator.java

The session wasn't "touched" if the `X-Graylog-No-Session-Extension`
header was missing.
(And that's what the frontend is doing)
Bug introduced with #9287

Fix condition for session extension

---

graylog2-web-interface/src/routing/AppRouter.jsx

When a plugin route has a parent component we wrap the component with its parent in AppRouter -> renderPluginRoute.
When creating the route we provided the component for the Route component by using the Route component prop.
Because of this combination plugin routes with a parent got newly created every time the AppRouter rendered.
This is not the case when using the render prop of the Route component. Please have a look at the react-router docs for more information.
You can test this change on a dashboard by changing the sidebar pinning (with a non system admin user). Before this change the whole page rerendered sometimes and the sidebar got closed.

Do not create new component for plugin routes with parent on every AppRouter render

---

graylog2-web-interface/src/views/components/sidebar/description/SearchResultOverview.jsx
graylog2-web-interface/src/views/components/sidebar/description/ViewDescription.jsx

Previously we displayed a spinner in the search sidebar section while executing a search.
This spinner was also being displayed when a dashboard had no widgets, since there was no query to execute.
Now we just display a description for both cases:

Use description instead of spinner in search sidebar description section

---

graylog2-web-interface/src/views/components/searchbar/StreamsFilter.jsx
graylog2-web-interface/src/views/components/searchbar/queryinput/StyledAceEditor.jsx

This PR is removing the not needed `z-index` from the `StreamsFilter` and `StyledAceEditor`. Previously they overlaid the sidebar:

Prevent search bar elements from overlaying search sidebar

---

graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
graylog2-web-interface/src/actions/authentication/AuthenticationActions.js
graylog2-web-interface/src/actions/users/UsersActions.js
graylog2-web-interface/src/components/authentication/BackendDetails/SyncedUsersSection/SyncedUsersOverviewItem.jsx
graylog2-web-interface/src/components/authentication/BackendDetails/SyncedUsersSection/SyncedUsersSection.jsx
graylog2-web-interface/src/components/authentication/BackendsOverview/BackendsOverview.jsx
graylog2-web-interface/src/components/users/LoggedInIcon.jsx
graylog2-web-interface/src/components/users/UserDetails/ProfileSection.jsx
graylog2-web-interface/src/components/users/UsersOverview/UserOverviewItem/ActionsCell.jsx
graylog2-web-interface/src/components/users/UsersOverview/UserOverviewItem/StatusCell.jsx
graylog2-web-interface/src/components/users/UsersOverview/UserOverviewItem/UsersOverviewItem.jsx
graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.jsx
graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.test.jsx
graylog2-web-interface/src/domainActions/authentication/AuthenticationDomain.js
graylog2-web-interface/src/domainActions/users/UsersDomain.js
graylog2-web-interface/src/logic/users/User.js
graylog2-web-interface/src/logic/users/UserOverview.js
graylog2-web-interface/src/routing/ApiRoutes.js
graylog2-web-interface/src/stores/authentication/AuthenticationStore.js
graylog2-web-interface/src/stores/users/UsersStore.js
graylog2-web-interface/test/fixtures/users.js

If a user is on vacation a often used routine is to disable a user account. Right now the backend did support disable and enabling a user account but the frontend did not use it.
- Show user enable and disable status in users details page and useroverivew
- Add a enable / disable menu item to a user in the useroverview page
- Also: Add missing permission check in the backend resource
Fixes #9413

Display and manage user account status in the frontend

---

UPGRADING.rst
graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/views/DashboardService.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/ClusterStatsResource.java
graylog2-server/src/main/java/org/graylog2/system/stats/ClusterStatsService.java

Prior to this change, the cluster stats endpoints (`/api/system/cluster/stats` and `/api/system/cluster/stats/elasticsearch`) had two separate issues that prevented it from working:
- (For ES7): The retrieval of stats for ES cluster nodes was missing a mandatory filter argument (now using `*`)
- Retrieving the current count of dashboards was using a `null` field to sort on, which resulted in an exception being thrown by the MongoDB client library
This PR is fixing both of these.
In addition, this PR is marking those endpoints as deprecated and flag them for removal in a future version.
Fixes #9435.

Fix cluster stats endpoints.

---

UPGRADING.rst
graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/views/DashboardService.java
graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java
graylog2-server/src/main/java/org/graylog2/rest/resources/system/ClusterStatsResource.java
graylog2-server/src/main/java/org/graylog2/system/stats/ClusterStatsService.java

**Note:** This is a backport of #9436 to `4.0`.
Prior to this change, the cluster stats endpoints (`/api/system/cluster/stats` and `/api/system/cluster/stats/elasticsearch`) had two separate issues that prevented it from working:
- (For ES7): The retrieval of stats for ES cluster nodes was missing a mandatory filter argument (now using `*`)
- Retrieving the current count of dashboards was using a `null` field to sort on, which resulted in an exception being thrown by the MongoDB client library
This PR is fixing both of these.
In addition, this PR is marking those endpoints as deprecated and flag them for removal in a future version.
Fixes #9435.

Fix cluster stats endpoints. (4.0)

---

graylog2-web-interface/src/components/rules/RuleContext.jsx
graylog2-web-interface/src/components/rules/RuleForm.jsx
graylog2-web-interface/src/stores/rules/RulesStore.js

Prior to this change, if a user was clicking 'Apply' when creating a
rule a new rule was created but the page was still on the new page which
would lead into an error when clicking 'Save & Close' next.
Fixes #7348
Fixes #8660
This change will change the browsers url to the edit page after clicking
apply which will fix the state after coming from a new rule page.
Also it fixes a problem if you come to the rules edit page directly, where the source code was not loaded.

Fix behavior of Apply for new Pipeline Rules

---

graylog2-web-interface/src/components/streams/Stream.jsx
graylog2-web-interface/src/components/streams/StreamControls.jsx

Prior to this change, we completly disabled the `More Actions` of the
`Default Stream` which prevented the user to `Manage Outputs` or to set
the `Default Stream` as Startpage.
This change will only disable the menu items which are not applicable
for the default stream.
Fixes #9433

Show missing menu items for Default Stream

---

graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
graylog2-web-interface/src/components/users/UsersOverview/UserOverviewItem/ActionsCell.jsx

Prior to this change, a logged in user was able to disable himself (if
he had the necessary permissions).
This change will hide the menu item `Enable`/`Disable` for the user
himself.
Add a confirmation dialog for disabling user which explains that
disabling a user also stops its current session.

Prevent disabling your own user account

---

graylog2-web-interface/src/components/streams/Stream.jsx
graylog2-web-interface/src/components/streams/StreamControls.jsx

**This is a backport of https://github.com/Graylog2/graylog2-server/pull/9453 for 4.0**
Prior to this change, we completely disabled the `More Actions` of the
`Default Stream` which prevented the user to `Manage Outputs` or to set
the `Default Stream` as Startpage.
This change will only disable the menu items which are not applicable
for the default stream.

Show missing menu items for Default Stream (Backport for 4.0)

---

graylog2-web-interface/src/components/systemmessages/SystemMessagesComponent.jsx

During a refactoring, the scoping of the `currentPage` variable used to specify the page of system messages which is currently fetched was changed, effectively fixing it to its initial value. This leads to page changes not being reflected for the periodical refresh.
This change is now adjusting the scope and using the value of the current page which is up to date.
Fixes #9454.

Fix scoping of current page in system messages list.

---

graylog2-web-interface/src/components/streams/StreamControls.jsx
graylog2-web-interface/src/components/users/UserEdit/PreferencesSection.jsx
graylog2-web-interface/src/components/users/UserEdit/ProfileSection.jsx

Prior to this change, there was no way to reset a startpage for a user.
This change will add the most minimal solution by adding a Reset
Startpage button to the header of the profile section on the user edit page.
Fix setting the Set as Startpage menuitem for streams.
Refs #9443

Add reset startpage button to profile section of user edit 4.0

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/RestHighLevelClientProvider.java
graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodical.java
graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodicalTest.java

In #9177 we introduced a check to skip the periodical run when the
server is not in RUNNING state. This was added to fix exceptions during
server shutdown by preventing the periodical to run in that state.
Unfortunately this is will delay index field types update by an hour
when the periodical starts for the first time on server startup. The
periodical only runs once an hour by default.
This change is removing the RUNNING state check in the periodical's
run() method. We keep the check in the individual poller jobs. These are
running way more often.
This change also removes the shutdown hook that closes the ES client
during server shutdown. Closing the client connection can cause
exceptions during the server shutdown when the index field type poller
job (and others) run during shutdown and …

Fix index field types update

---

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/RestHighLevelClientProvider.java
graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodical.java
graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodicalTest.java

In #9177 we introduced a check to skip the periodical run when the
server is not in RUNNING state. This was added to fix exceptions during
server shutdown by preventing the periodical to run in that state.
Unfortunately this is will delay index field types update by an hour
when the periodical starts for the first time on server startup. The
periodical only runs once an hour by default.
This change is removing the RUNNING state check in the periodical's
run() method. We keep the check in the individual poller jobs. These are
running way more often.
This change also removes the shutdown hook that closes the ES client
during server shutdown. Closing the client connection can cause
exceptions during the server shutdown when the index field type poller
job (and others) run during shutdown and …

Fix index field types update (#9463)

---

graylog2-web-interface/src/components/systemmessages/SystemMessagesComponent.jsx

**Note:** This is a backport of #9456 to `4.0`.
During a refactoring, the scoping of the `currentPage` variable used to specify the page of system messages which is currently fetched was changed, effectively fixing it to its initial value. This leads to page changes not being reflected for the periodical refresh.
This change is now adjusting the scope and using the value of the current page which is up to date.
Fixes #9454.

Fix scoping of current page in system messages list. (4.0)

---

graylog2-web-interface/src/components/users/UserEdit/RolesSection.jsx
graylog2-web-interface/src/pages/UserEditPage.jsx

**This PR needs a backport for 4.0**
As described in https://github.com/Graylog2/graylog2-server/issues/9469  the roles section on the user edit page is sometimes not getting updated correctly when adding or removing a role. This includes the list of assigned roles and the list of available roles.
This PR fixes the issue by updating the user state correctly.
Refs https://github.com/Graylog2/graylog2-server/issues/9469

Update roles section on user edit page correctly when assigning or removing a role

---

graylog2-server/src/main/java/org/graylog/security/authzroles/AuthzRolesResource.java

Every user has user:edit permissions for himself!
This prevents users from assigning themselves to any role.

Use the correct permission for role assignment

---

graylog2-web-interface/src/components/users/UserEdit/RolesSection.jsx
graylog2-web-interface/src/pages/UserEditPage.jsx

**This is a backport of https://github.com/Graylog2/graylog2-server/pull/9471 for 4.0**
As described in https://github.com/Graylog2/graylog2-server/issues/9469  the roles section on the user edit page is sometimes not getting updated correctly when adding or removing a role. This includes the list of assigned roles and the list of available roles.
This PR fixes the issue by updating the user state correctly.
Refs https://github.com/Graylog2/graylog2-server/issues/9469

Update roles section on user edit page correctly when assigning or removing a role (Backport for 4.0)

---

graylog2-web-interface/src/components/authentication/directoryServices/BackendConfigDetails/GroupSyncSection.jsx
graylog2-web-interface/src/components/authentication/directoryServices/BackendConfigDetails/GroupSyncSection.test.jsx
graylog2-web-interface/test/fixtures/authenticationBackends.js

**This PR needs a backport for 4.0**
The following error https://github.com/Graylog2/graylog2-server/issues/9481 occurs when opening the authentication backend details page without an enterprise plugin. This PR is fixing the error and adding a test for this case.
Fixes: https://github.com/Graylog2/graylog2-server/issues/9481

Fix error in authentication service details group sync section which occurs without an enterprise plugin

---

graylog2-web-interface/src/components/authentication/directoryServices/BackendConfigDetails/GroupSyncSection.jsx
graylog2-web-interface/src/components/authentication/directoryServices/BackendConfigDetails/GroupSyncSection.test.jsx
graylog2-web-interface/test/fixtures/authenticationBackends.js

**This is a backport of https://github.com/Graylog2/graylog2-server/pull/9483**
The following error https://github.com/Graylog2/graylog2-server/issues/9481 occurs when opening the authentication backend details page without an enterprise plugin. This PR is fixing the error and adding a test for this case.
Refs: https://github.com/Graylog2/graylog2-server/issues/9481

Fix error in authentication service details group sync section which occurs without an enterprise plugin (Backport for 4.0)

---

graylog2-server/src/main/resources/log4j2.xml

We don't use the apache library anymore.
Refs #8984

Remove logging config for apache ldap client

---

graylog2-web-interface/src/views/spec/CreateNewDashboard.test.jsx

The new license header has been added at the top of the file. Jest
requires the pragma to be at the top, though.
(This needs a backport to the 4.0 branch once it's merged.)

Make sure jest-environment pragma is at the top of the file

---

graylog2-web-interface/package.json
graylog2-web-interface/src/pages/UserHasNoStreamAccess.test.tsx
graylog2-web-interface/test/setup-jest.js
graylog2-web-interface/tsconfig.json

**Note:** This PR requires #9411 to be merged before.
This PR contains the required change to parse TypeScript files in jest.  It uses the `babel-parser` with the TypeScript preset just as we do for webpack. It is activated implicitly for `.ts(x)` files by removing the `transform` clause from the jest config in `package.json`. The [Jest docs](https://jestjs.io/docs/en/getting-started) say:
```
Note: babel-jest is automatically installed when installing Jest and will automatically transform files if a babel configuration exists in your project. To avoid this behavior, you can explicitly reset the transform configuration option:
```
Therefore, removing the `transform` section implicitly tells Jest to just use the babel config which uses the TypeScript preset.

Support TypeScript in Jest.

---

graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java

This change is improving one of the `IndicesIT` tests, as it has turned out to be flaky when it is executed at the brink of a second. In this case, the reference date (e.g. `2020-11-12T09:01:37.999Z`) is not equal to the actual one (e.g. `2020-11-12T09:01:38.000Z`), even when ignoring milliseconds. Therefore, this change is changing the assertion to check if those two dates are close enough to each other with a delta of one second.

Improve `IndicesIT` test by using delta when comparing dates.

---

graylog2-web-interface/packages/eslint-config-graylog/package.json

This PR changes the license info of the `eslint-config-graylog` `package.json` to SSPL.
See the following links for more details:
- https://www.graylog.org/post/graylog-announces-4-0-release-of-its-log-management-platform
- https://www.graylog.org/post/graylog-v4-0-licensing-sspl

Change eslint-config-graylog package.json license to SSPL

---

graylog2-server/src/main/java/org/graylog/schema/ApplicationFields.java
graylog2-server/src/main/java/org/graylog/schema/AssociatedFields.java
graylog2-server/src/main/java/org/graylog/schema/AutonomousSystemFields.java
graylog2-server/src/main/java/org/graylog/schema/ContainerFields.java
graylog2-server/src/main/java/org/graylog/schema/DestinationFields.java
graylog2-server/src/main/java/org/graylog/schema/EventFields.java
graylog2-server/src/main/java/org/graylog/schema/GeoFields.java
graylog2-server/src/main/java/org/graylog/schema/GraylogSchemaFields.java
graylog2-server/src/main/java/org/graylog/schema/HashFields.java
graylog2-server/src/main/java/org/graylog/schema/HostFields.java
graylog2-server/src/main/java/org/graylog/schema/HttpFields.java
graylog2-server/src/main/java/org/graylog/schema/NetworkFields.java
graylog2-server/src/main/java/org/graylog/schema/PolicyFields.java
graylog2-server/src/main/java/org/graylog/schema/RuleFields.java
graylog2-server/src/main/java/org/graylog/schema/SourceFields.java
graylog2-server/src/main/java/org/graylog/schema/UserFields.java

This is a backport of the latest Graylog Schema updates from the `master` branch to the `3.3` branch.
The main purpose of backporting this change to `3.3` is to fix the `HttpFields.HTTP_XFF` value
For details, see #9524

Updates to Graylog Schema (#9524)

---

graylog2-web-interface/src/views/components/WidgetQueryControls.jsx

Updates the `WidgetQueryControls` search bar to use the new `TimeRangeDisplay` component to output the chosen dates

DateTimePicker: Add updated TimeRangeDisplay to WidgetQueryControls

---

graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java
graylog2-server/src/test/java/org/graylog/security/entities/EntityDependencyResolverTest.java
graylog2-server/src/test/resources/org/graylog/security/entities/EntityDependencyResolverTest.json

* Avoid NPE when resolving broken dependencies
If an entity contains a dependency to a no longer existing
object, we'd throw an NPE when trying to resolve the object's title.
- Return a replacement string if the title can't be resolved.
- Add a unit test for the EntityDependencyResolver
Fixes #9525
* Add missing license
(cherry picked from commit 1a356bfd6c0a38951ddbfbff33aa38a31c9e06ad)

Avoid NPE when resolving broken dependencies (#9558)

---

graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionEntry.jsx
graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionEntry.test.jsx

As described in https://github.com/Graylog2/graylog2-server/issues/9579 the event definitions share button is currently only enabled for admins. This PR is fixing the `ShareButton` props and adds tests to ensure that also owners of event definitions are able to share them.
Please note, this bug got already fixed in the `master` branch, but we should still create an upstream PR to add the new tests.
Fixes: https://github.com/Graylog2/graylog2-server/issues/9579

Fix event definitions share button permissions check and add tests

---

graylog2-web-interface/src/components/authentication/BackendDetails/SyncedUsersSection/SyncedUsersSection.jsx

As described in https://github.com/Graylog2/graylog2-server/issues/9574 the pagination of the synced users overview on the authentication service details page is currently broken. This PR is fixing the problem by providing the correct `onChange` prop for the `PaginatedList`.
Please note, this bug got already fixed in the master branch.
Fixes: #9574

Fix pagination of synced users overview on authentication service details page

---

graylog2-web-interface/src/components/common/FormikFormGroup.tsx
graylog2-web-interface/src/components/common/PaginatedDataTable/PaginatedDataTable.tsx

This PR is extending the `PaginatedDataTable` and `FormikFormGroup` prop type definitions.
We need some of these changes for a TypeScript migration PR.

Extend `PaginatedDataTable` and `FormikFormGroup` prop type definitions

---

graylog2-web-interface/src/pages/SidecarsPage.jsx

**Please note this PR needs a backport for 4.0, we should close the referenced issue, when we merge the backport**
As described in https://github.com/Graylog2/graylog2-server/issues/9555 the link for the graylog-sidecar user tokens page on the sidecars page is currently broken. The tokens page URL is now based on the user id but we still used the username.

Fix link for graylog-sidecar user tokens on sidecars page.

---

graylog2-web-interface/src/components/navigation/SystemMenu.jsx
graylog2-web-interface/src/components/nodes/NodeOverview.jsx
graylog2-web-interface/src/components/nodes/NodesActions.jsx
graylog2-web-interface/src/logic/notifications/NotificationsFactory.jsx
graylog2-web-interface/src/routing/AppRouter.jsx
graylog2-web-interface/src/util/conditional/filterMenuItems.js
graylog2-web-interface/src/util/conditional/filterValueActions.js
graylog2-web-interface/src/util/conditional/filterValueActions.test.js
graylog2-web-interface/src/views/bindings.jsx
graylog2-web-interface/src/views/bindings.routes.test.jsx
graylog2-web-interface/src/views/bindings.valueActions.test.jsx

Inputs on cloud will be managed through forwarders instead of `system/inputs`
Hide / disable features that allow access to these parts on cloud.
See https://github.com/Graylog2/graylog-plugin-cloud/issues/99
Tested in the cloud environment
External:

Hide inputs and related on cloud

---

graylog2-web-interface/src/theme/GlobalThemeStyles.jsx

**This PR needs a backport for 4.0**
This PR unifies the basic `textarea` styles like font, background and border color with the bootstrap text area styles.
This fixes e.g. the scratchpad background color in dark mode (https://github.com/Graylog2/graylog2-server/issues/9607).
I thought about adding the `form-control` class to the scratchpad textarea, but this would make it harder to overwrite styles like the font color. Another benefit of this solution is that we do not have to remember this class when adding new `textarea`s.
We should also consider implementing the same change for the  `input` and `select` element selector. I did not include this change in this PR to reduce the amount of possible side effects, which becomes relevant when creating the backport for 4.0.

Unify basic `<textarea />`styles with bootstrap text area styles

---

graylog2-web-interface/src/pages/SidecarsPage.jsx

**This is a backport of https://github.com/Graylog2/graylog2-server/pull/9605 for 4.0**
As described in https://github.com/Graylog2/graylog2-server/issues/9555 the link for the graylog-sidecar user tokens page on the sidecars page is currently broken. The tokens page URL is now based on the user id but we still used the username.
Fixes https://github.com/Graylog2/graylog2-server/issues/9555

Fix link for graylog-sidecar user tokens on sidecars page (4.0)

---

graylog2-web-interface/src/theme/GlobalThemeStyles.jsx

**This is a backport of https://github.com/Graylog2/graylog2-server/pull/9608 for 4.0**
This PR unifies the basic `textarea` styles like font, background and border color with the bootstrap text area styles.
This fixes e.g. the scratchpad background color in dark mode (https://github.com/Graylog2/graylog2-server/issues/9607).
I thought about adding the `form-control` class to the scratchpad textarea, but this would make it harder to overwrite styles like the font color. Another benefit of this solution is that we do not have to remember this class when adding new `textarea`s.
We should also consider implementing the same change for the  `input` and `select` element selector. I did not include this change in this PR to reduce the amount of possible side effects, which becomes relevant when …

Unify basic `<textarea />`styles with bootstrap text area styles (4.0)

---

graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionEntry.test.jsx
graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionEntry.test.tsx
graylog2-web-interface/test/fixtures/eventDefinition.ts

This PR adds basic tests for the event definitions share button. This includes creating an event definition fixture.
We've added tests while fixing a related bug for 4.0 https://github.com/Graylog2/graylog2-server/pull/9603

Add tests for event definitions share button

---

graylog2-server/src/main/java/org/graylog/events/rest/EventsResource.java
graylog2-server/src/main/java/org/graylog/events/search/EventsSearchParameters.java

Avoids an NPE when executing a search without payload.

Use empty EventSearchParameters in EventsResource by default

---

graylog2-web-interface/src/components/errors/ReportedErrorBoundary.test.tsx
graylog2-web-interface/src/pages/StreamPermissionErrorPage.test.tsx
graylog2-web-interface/src/pages/UnauthorizedErrorPage.test.tsx

In some tests we unmocked the `FetchProvider`, to be able to import the `FetchError`. Both classes shared the same file. This was not the best solution, because it resulted in the following `console.error`s when running these tests. 
```
There was an error fetching a resource: getaddrinfo ENOTFOUND undefined. Additional information: Not available
```
We recently created a separate file for the `FetchError`, which means unmocking the `FetchProvider` is no longer necessary.

Remove no longer needed `FetchProvider` unmocking in error pages tests

---

graylog2-web-interface/src/components/navigation/SystemMenu.jsx
graylog2-web-interface/src/routing/AppRouter.jsx

Because having authentication page on cloud at the moment does not make any sense, we need to hide them for now until we'll handle user management.
Needs https://github.com/Graylog2/graylog2-server/pull/9587 (so wait before merging)
See https://github.com/Graylog2/graylog-plugin-cloud/issues/102 and https://github.com/Graylog2/graylog-plugin-cloud/issues/555
Disable the auth pages for now because they are broken on cloud at the moment.
By navigating

Hide authentication pages on cloud

---

graylog2-web-interface/webpack.combined.config.js

Before this change, running `devServer` without `disable_plugins` made it use a glob (`../../graylog-plugin-*/**/webpack.config.js`) to find webpack configs of all plugins in the filesystem. This lead to issues when plugins are merely existing in the fs but are not supposed to be used. (e.g. from a previous `graylog-project` checkout)
After this change, `devServer` looks for a `web-modules.json` file (which is generated by `graylog-project` upon checkout) and uses the plugins referenced in there instead of the glob. If the file is not present, it will fall back to the old behavior of using a glob. If `web-modules.json` is regenerated while the dev server is running, it needs a restart to pick up the changes.
This PR allows it to switch between different manifests using different
sets of …

Use plugins from web modules file in dev build.

---

graylog2-web-interface/src/pages/UserHasNoStreamAccess.test.tsx
graylog2-web-interface/src/routing/ApiRoutes.d.ts
graylog2-web-interface/src/stores/StoreTypes.ts
graylog2-web-interface/src/types.d.ts
pom.xml

Extend the license formatter configuration to handle TypeScript files.

Extend license formatter for TypeScript

---

graylog2-web-interface/src/views/components/common/UserTimezoneTimestamp.jsx
graylog2-web-interface/src/views/components/common/UserTimezoneTimestamp.test.tsx
graylog2-web-interface/webpack/vendor-module-ids.json

Starting with 3.2.0, we did not display microseconds in the message table for timestamps anymore. While a microsecond timestamp is shown when message details are expanded, it is also highly useful in the collapsed table.
This PR is changing the timestamp format used and includes microseconds again.
Fixes #9604.

Include microseconds in timestamps.

---

graylog2-server/src/main/java/org/graylog2/shared/messageq/pulsar/PulsarMessageQueueWriter.java

The goal is to retry sending messages indefinitely until it succeeds. We don't want to give up on trying because we *have* to send it. Otherwise the message would be lost because we are unable to put it somewhere safe other than pulsar.
By disabling the send timeout, the pulsar producer will keep trying to send it and transparently performs reconnection attempts if the connection is broken.
The pulsar client's behaviour, if the upstream broker is unreachable, and also under adverse network conditions, appears to be satisfying. I tested stopping and restarting the broker as well as letting upstream connections and downstream connections time out during operation.
As expected, downstream connection timeouts resulted in duplicate messages being delivered. If this becomes a problem, we could …

Handle Pulsar upstream connectivity issues

---

graylog2-web-interface/src/views/components/common/UserTimezoneTimestamp.test.tsx

Prior to this change, we missed to add a license to a new frontend test.
This change will add this missing license

Fix missing license header in newly commited file

---

graylog2-web-interface/src/views/components/Search.tsx

When a user which is missing the `clusterconfigentry:read` permission is starting a search, the `ViewAdditionalContextProvider` tries to read a key from a non-existing (because it cannot be retrieved due to the lack of the permission) object. This results in an exception being thrown.
This change is using optional chaining to handle the absence of the config object gracefully.
Fixes #9591.
The `SearchConfigStore` was manipulated to return an object missing the `searchesClusterConfig` key. Without this change, this results in an exception, with the change in place, it does not.

Handling unavailable `searchesClusterConfig`.

---

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreter.java
graylog2-server/src/main/java/org/graylog2/messageprocessors/MessageFilterChainProcessor.java
graylog2-server/src/main/java/org/graylog2/outputs/BenchmarkOutput.java
graylog2-server/src/main/java/org/graylog2/outputs/DiscardMessageOutput.java
graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/DecodingProcessor.java
graylog2-server/src/main/java/org/graylog2/shared/messageq/MessageQueueAcknowledger.java
graylog2-server/src/main/java/org/graylog2/shared/messageq/kafka/KafkaMessageQueueAcknowledger.java
graylog2-server/src/main/java/org/graylog2/shared/messageq/pulsar/PulsarMessageQueueAcknowledger.java
graylog2-server/src/main/java/org/graylog2/shared/messageq/pulsar/PulsarMessageQueueReader.java
graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreterTest.java
graylog2-server/src/test/java/org/graylog2/messageprocessors/MessageFilterChainProcessorTest.java

Log exception instead of throwing it in `acknowledge()`
We don't know how to recover from it anyhow.
So instead of handling that exception everywhere, keep it simple.

Use MessageQueueAcknowledger instead of Journal

---

graylog2-web-interface/src/components/navigation/SystemMenu.jsx
graylog2-web-interface/src/routing/AppRouter.jsx

On cloud we do not need to have sidecars, so this disables the pages altogether.
We need not make sidecars available for the cloud environment.
On cloud env
Fixes https://github.com/Graylog2/graylog-plugin-cloud/issues/101

Hide sidecars on cloud

---

graylog2-server/src/main/java/org/graylog2/rest/resources/system/SessionsResource.java
graylog2-server/src/main/java/org/graylog2/security/realm/HTTPHeaderAuthenticationRealm.java
graylog2-server/src/main/java/org/graylog2/security/realm/SessionAuthenticator.java

If the username in the HTTPHeaderAuth request changes,
we need to destroy the session.
Fixes https://github.com/Graylog2/graylog-plugin-auth-sso/issues/35

Verify session against http auth header

---

graylog2-web-interface/src/actions/streams/StreamsActions.jsx
graylog2-web-interface/src/components/configurations/DecoratorsConfig.tsx
graylog2-web-interface/src/components/streams/StreamControls.jsx
graylog2-web-interface/src/components/users/StartpageFormGroup.tsx
graylog2-web-interface/src/components/users/UserCreate/StartpageFormGroup.jsx
graylog2-web-interface/src/components/users/UserDetails/SettingsSection.tsx
graylog2-web-interface/src/components/users/UserEdit/SettingsSection.test.tsx
graylog2-web-interface/src/components/users/UserEdit/SettingsSection.tsx
graylog2-web-interface/src/components/users/UserEdit/UserEdit.tsx
graylog2-web-interface/src/stores/streams/StreamsStore.ts
graylog2-web-interface/src/stores/users/StartpageStore.js
graylog2-web-interface/src/views/stores/DashboardsStore.ts

Make startpage configureable in settings section of a user
Add two selects one for the type `dashboard` / `stream` and one for the list of available options.
For normal users we as entity share resource for a list of dashboards or streams and for admin users
we ask dashboards resource and stream resource.
If a user lost a view permission for the selected startpage we show a warning message.
Refs #9443

Add startpage to the Settings Section of a user

---

graylog2-web-interface/src/actions/users/UsersActions.js
graylog2-web-interface/src/components/graylog/Panel.jsx
graylog2-web-interface/src/components/users/CreateTokenForm.jsx
graylog2-web-interface/src/components/users/TokenList.css
graylog2-web-interface/src/components/users/TokenList.jsx

- Extract create token form into a component that we can reuse
- Update Token type definition
- Remove default `expanded` value from `Panel`, since that threw an error in the console log: https://github.com/react-bootstrap/react-bootstrap/blob/v0.33.1/src/Panel.js#L99-L101
/jenkins-pr-deps Graylog2/graylog-plugin-cloud#620

Support for better integration of Token creation from Forwarder wizard

---

graylog2-web-interface/src/components/lookup-tables/DataAdapterForm.jsx

These changes add a new `isFormExternalyValidated`  state to  `DataAdapterForm` to allow children component to control (disable or enable) the form submit button.
/jenkins-pr-deps Graylog2/graylog-plugin-cloud#617
For the CSV File upload plugin, this allows the submit button to be disabled when the file is being uploaded.
- [] Bug fix (non-breaking change which fixes an issue)

  Add state to disable or enable submit form in DataAdapterForm

---

graylog2-web-interface/src/pages/EnterprisePage.jsx

We do not want to show the request enterprise form on cloud because it doesn't really make any sense to.
If a user on cloud requests a call for enterprise it's not correct
By enabling cloud and looking if the form is gone
Fixes https://github.com/Graylog2/graylog-plugin-cloud/issues/100

Hide enterprise request form on cloud

---

graylog2-web-interface/src/components/users/TimeoutUnitSelect.tsx

The form which imports the `TimeoutUnitSelect` is now using `onChange` to update its state.
The `TimeoutUnitSelect` state and ref handling is no longer needed.

Simplify `TimeoutUnitSelect` by removing no longer needed state handling

---

graylog2-web-interface/src/components/permissions/EntityShareModal.tsx
graylog2-web-interface/src/components/permissions/EntityShareSettings.tsx
graylog2-web-interface/src/components/permissions/GranteesSelector.test.tsx
graylog2-web-interface/src/components/permissions/GranteesSelector.tsx

Previously we used the `GranteesSelector` select ref to get the component props and state when saving the entity share modal. This is not a good practice. We need to access the state to check if the "Add collaborator" form got submitted when a user tries to save the share modal. If the "Add collaborator" form is not empty we display a confirm dialog.
With these changes we are just using the `GranteesSelector` form state. We get all other necessary information from the entity share state.

Refactor the way we access the `GranteesSelector` state in `EntityShareModal` on save.

---

graylog2-web-interface/config.js
graylog2-web-interface/devServer.js
graylog2-web-interface/package.json
graylog2-web-interface/yarn.lock

I still had this in my tree from the time we disabled CORS by default a few months ago.
This uses an express proxy middleware to forward all `/api` requests to the server backend. (similar to the "proxy" feature in [webpack-dev-server](https://webpack.js.org/configuration/dev-server/#devserverproxy))
This could simplify the development setup because CORS doesn't need to be enabled anymore.
What do you @Graylog2/frontend folks think? (I am also fine with discarding it :wink:)

Let devServer proxy all "/api" requests to the server API

---

graylog2-web-interface/src/components/users/TokenList.jsx
graylog2-web-interface/src/components/users/TokenList.test.jsx
graylog2-web-interface/src/pages/UserTokensEditPage.jsx

This PR adds the following changes to the Token list:
- Replace [`TableList`](https://graylog2.github.io/frontend-documentation/#!/TableList) with [`ControlledTableList`](https://graylog2.github.io/frontend-documentation/#!/ControlledTableList), which gives us more flexibility to customize how to display tokens
- Add last access information to each Token, helping users to know which Tokens may not be used
- Display Token information after creation, making it easier to copy it
Refs: https://github.com/Graylog2/graylog-plugin-cloud/issues/570

Improvements in Token list

---

graylog2-web-interface/src/components/navigation/Navigation.jsx

`Nav` passes some props to each one of its children, so using a div
as wrapper means that React logs a warning in the browser console log on
each render, see:
https://github.com/Graylog2/graylog2-server/pull/9729#issuecomment-741892217
Since `GlobalThroughput` returns a `NavItem` and accepts props, we can
pass the `disabled` prop to style it when it is not a link, and also
remove the warning from the console.
Refs #9729

Remove div wrapping GlobalThroughput in cloud

---

graylog2-web-interface/src/components/cluster/TrafficGraph.tsx

Before these changes, when hovering value on the outgoing traffic chart the value was not rounded like below: 
With these changes, the value is rounded to two decimal like the example below: 
fixes #8418

Round traffic value on hover in Outgoing traffic chart

---

graylog2-web-interface/src/components/common/URLWhiteListFormModal.tsx
graylog2-web-interface/src/components/streamrules/StreamRuleForm.test.tsx
graylog2-web-interface/src/components/streamrules/StreamRuleForm.tsx
graylog2-web-interface/src/stores/__tests__/connect.test.tsx
graylog2-web-interface/src/stores/connect.tsx
graylog2-web-interface/src/views/components/DashboardSearchBar.tsx
graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.tsx
graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchList.test.tsx
graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchList.tsx
graylog2-web-interface/src/views/components/widgets/Widget.test.tsx
graylog2-web-interface/src/views/components/widgets/Widget.tsx

This PR improves the type inference when using `connect` for a component which also uses `defaultProps`.  Previously we had a problem in the following case:
Component has a prop `exampleProp`. This prop is defined as required in the component `Prop` type, but has a default value. Since it has a default value, the `PropType`s are defining the prop as optional. When we use this component the `exampleProp` is required. With this PR the `exampleProp` is typed as optional.
There is still one case were we do not infer the props perfectly. If the mentioned `exampleProp` is an object and the TypeScript type defines its values as required, we can't define a `PropType` definition which defines as the prop optional, but the attributes are required. With the current inference all attributes are typed …

Improving `connect` type inference regarding component `propTypes` and `defaultProps`.

---

graylog2-web-interface/src/views/components/common/ActionDropdown.test.tsx
graylog2-web-interface/src/views/components/common/ActionDropdown.tsx

The `ActionDropdown` manipulates the `onSelect` prop of its children, to close the dropdown when `onSelect` is being executed. This is currently not working, when a child is wrapped in an element like `IfDashboard`.
With this PR we also apply this manipulation to the children of the `ActionDropdown` children, if the main child does not have an `onSelect` prop.

Fix `ActionDropdown` toggle on child select, if child is wrapped in another element

---

graylog2-web-interface/src/views/components/widgets/MessageList.test.tsx
graylog2-web-interface/src/views/components/widgets/MessageList.tsx
graylog2-web-interface/src/views/components/widgets/MessageTable.test.tsx
graylog2-web-interface/src/views/components/widgets/MessageTable.tsx

Before this change, the field sort icons used to change sorting of a message table were shown in edit mode only. Most users are used to change sorting outside of edit mode by clicking an icon next to the field name in the table header.
This change is showing sorting icons outside of the edit mode too, but not in non-interactive contexts.

Always show field sort icons in message table.

---

graylog2-server/src/main/java/org/graylog2/storage/versionprobe/VersionProbe.java

My machine is running elastic `7.9.3-SNAPSHOT`
which couldn't be parsed and prevented the server to start.
- Use the semver parser instead of a hand rolled version which
cannot deal with prerelease tags
- Also, avoid throwing an exception at this point, which forever blocks
the AtomicCache. I guess we don't complete the Future in this case.

Fix version probe for ES snapshot versions

---

graylog2-web-interface/src/views/components/widgets/MessageList.jsx
graylog2-web-interface/src/views/components/widgets/MessageList.test.jsx
graylog2-web-interface/src/views/components/widgets/MessageTable.jsx
graylog2-web-interface/src/views/components/widgets/MessageTable.test.jsx

**Note:** This is a backport of #9757 to `3.3`.
Before this change, the field sort icons used to change sorting of a message table were shown in edit mode only. Most users are used to change sorting outside of edit mode by clicking an icon next to the field name in the table header.
This change is showing sorting icons outside of the edit mode too, but not in non-interactive contexts.

Always show field sort icons in message table. (3.3)

---

graylog2-web-interface/src/views/components/widgets/MessageList.jsx
graylog2-web-interface/src/views/components/widgets/MessageList.test.jsx
graylog2-web-interface/src/views/components/widgets/MessageTable.jsx
graylog2-web-interface/src/views/components/widgets/MessageTable.test.jsx

**Note:** This is a backport of #9757 to `4.0`.
Before this change, the field sort icons used to change sorting of a message table were shown in edit mode only. Most users are used to change sorting outside of edit mode by clicking an icon next to the field name in the table header.
This change is showing sorting icons outside of the edit mode too, but not in non-interactive contexts.

Always show field sort icons in message table. (4.0)

---

graylog2-server/src/main/java/org/graylog2/rest/models/alarmcallbacks/requests/AlertReceivers.java
graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java

The new paginated endpoint in StreamResource is using mongojack to
deserialize the database objects. In some setups the AlertReceivers
object in the database might not be complete.
Change AlertReceivers to use defaults for missing values.
Fixes #9637
This needs to be cherry picked into 4.0 once it's merged.

Fix deserialization of incomplete AlertReceivers objects

---

graylog2-web-interface/src/stores/PaginationTypes.ts
graylog2-web-interface/src/stores/nodes/NodesStore.ts
graylog2-web-interface/src/stores/streams/StreamsStore.ts

Prior to this change, we set the eslint config that
it does not bother us with camelcase warnings.
This change was proudly presented by sed:
`git grep -l camelcase | xargs sed -i '/camelcase/d'`

Remove remaining eslint-disable-camelcase comments

---

graylog2-server/src/main/java/org/graylog2/rest/models/users/responses/TokenSummary.java
graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
graylog2-web-interface/src/actions/users/UsersActions.js
graylog2-web-interface/src/components/users/TokenList.jsx
graylog2-web-interface/src/components/users/TokenList.test.jsx
graylog2-web-interface/src/stores/users/UsersStore.js

Remove tokens from the list tokens resource and the token list page. This means that users will only be able to see (and copy) tokens when they are created. If a token is lost, the user will need to create another one.
Please note that this only fixes the issue for cloud. We will need to port it to other branches along with other cloud-specific changes.
Fixes #9124

Only display tokens immediately after creation

---

graylog2-server/src/main/java/org/graylog2/jersey/PrefixAddingModelProcessor.java
graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java
graylog2-server/src/main/java/org/graylog2/shared/rest/HideOnCloud.java
graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationBrowserResource.java
graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationResource.java
graylog2-server/src/test/java/org/graylog2/jersey/PrefixAddingModelProcessorTest.java

This PR adds an annotation for REST resources that let us mark resources that should be available in on-premise setups but not on cloud. It also uses that annotation to mark the `DocumentationResource` and `DocumentationBrowserResource` as hidden on cloud.
There probably is a better way to do this, but I could not find it with my (little) knowledge in that part of our stack, so I'm open for suggestions if you have any!
Fixes https://github.com/Graylog2/graylog-plugin-cloud/issues/91

Hide API browser and API docs when running on cloud

---

graylog2-web-interface/src/views/components/searchbar/__snapshots__/SearchBarForm.test.tsx.snap
graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteRangeField.test.tsx
graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteRangeField.tsx
graylog2-web-interface/src/views/components/searchbar/date-time-picker/RelativeTimeRangeSelector.tsx
graylog2-web-interface/src/views/components/searchbar/date-time-picker/__snapshots__/AbsoluteRangeField.test.tsx.snap
graylog2-web-interface/src/views/components/searchbar/date-time-picker/__snapshots__/AbsoluteTimeRangeSelector.test.tsx.snap

Allows for using number inputs so time can be driven with keyboard up/down buttons.

Update Absolute time inputs to use number instead of text

---

graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewDTO.java
graylog2-server/src/main/java/org/graylog2/contentpacks/facades/ViewFacade.java
graylog2-web-interface/src/views/stores/QueryIdsStore.js
graylog2-web-interface/src/views/stores/ViewStore.test.ts
graylog2-web-interface/src/views/stores/ViewStore.ts

Prior to this change, a dashboard installed by a content pack had a
tabs in a random order. Since we cannot change the order of the tabs
this is quite inconvinient for the user.
This change will do mutiple steps to fix that:
- Use a LinkedHashMap to ensure the order stays fix during content pack
creation.
- Instead of using the serach QueryIds we use the views QueryIds which
we previously fixed in the order.
- When loading a view and selecting the activeQuery we also use the
view.state queryids instead of the search ones.
Fixes #8264
1. Create a Dashboard
1. Create multiple Tabs with names [ 1, 2, 3, 4, 5 ]
1. Create a content pack with this Dashboard
1. Install that dashboard
1. Ensure the tabs order is still the same.

Fix order of tabs in dashboard after install
