Graylog2/graylog2-server

graylog2-server/src/main/java/org/graylog2/alerts/types/FieldValueAlertCondition.java, graylog2-server/src/main/java/org/graylog2/alerts/types/MessageCountAlertCondition.java, graylog2-server/src/main/java/org/graylog2/dashboards/widgets/FieldChartWidget.java, graylog2-server/src/main/java/org/graylog2/dashboards/widgets/QuickvaluesWidget.java, graylog2-server/src/main/java/org/graylog2/dashboards/widgets/SearchResultChartWidget.java, graylog2-server/src/main/java/org/graylog2/dashboards/widgets/SearchResultCountWidget.java, graylog2-server/src/main/java/org/graylog2/dashboards/widgets/StatisticalCountWidget.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexHelper.java, graylog2-server/src/main/java/org/graylog2/indexer/InvalidRangeFormatException.java, graylog2-server/src/main/java/org/graylog2/indexer/InvalidRangeFormatExceptionMapper.java, graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java, graylog2-server/src/main/java/org/graylog2/rest/InvalidRangeFormatExceptionMapper.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/KeywordSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/RelativeSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/SearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/sources/SourcesResource.java, graylog2-server/src/test/java/org/graylog2/alerts/types/FieldValueAlertConditionTest.java, graylog2-server/src/test/java/org/graylog2/alerts/types/MessageCountAlertConditionTest.java
This change set adds InvalidRangeFormatExceptionMapper and removes the individual
handling of InvalidRangeFormatExceptions throughout the code.
=> Refactor handling of InvalidRangeFormatException

graylog2-plugin-interfaces/src/main/java/org/graylog2/plugin/inputs/Extractor.java, graylog2-radio/src/main/java/org/graylog2/radio/users/NullUserServiceImpl.java, graylog2-server/src/main/java/org/graylog2/bundles/BundleService.java, graylog2-server/src/main/java/org/graylog2/dashboards/DashboardService.java, graylog2-server/src/main/java/org/graylog2/dashboards/DashboardServiceImpl.java, graylog2-server/src/main/java/org/graylog2/inputs/InputService.java, graylog2-server/src/main/java/org/graylog2/inputs/InputServiceImpl.java, graylog2-server/src/main/java/org/graylog2/streams/OutputImpl.java, graylog2-server/src/main/java/org/graylog2/streams/OutputService.java, graylog2-server/src/main/java/org/graylog2/streams/OutputServiceImpl.java, graylog2-server/src/main/java/org/graylog2/streams/StreamRuleService.java, graylog2-server/src/main/java/org/graylog2/streams/StreamRuleServiceImpl.java, graylog2-server/src/main/java/org/graylog2/streams/StreamService.java, graylog2-server/src/main/java/org/graylog2/streams/StreamServiceImpl.java, graylog2-server/src/main/java/org/graylog2/system/stats/ClusterStats.java, graylog2-server/src/main/java/org/graylog2/system/stats/ClusterStatsService.java, graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java, graylog2-shared/src/main/java/org/graylog2/shared/users/UserService.java
Add some interesting counts to ClusterStats.
=> Count von Count

bin/graylogctl, bin/radioctl, graylog2-bootstrap/src/main/java/org/graylog2/bootstrap/CmdLineTool.java, graylog2-bootstrap/src/main/java/org/graylog2/bootstrap/ServerBootstrap.java, graylog2-plugin-interfaces/src/test/java/org/graylog2/plugin/BaseConfigurationTest.java, graylog2-radio/misc/graylog2-radio.conf, graylog2-radio/src/main/java/org/graylog2/radio/Configuration.java, graylog2-server/src/main/java/org/graylog2/Configuration.java, graylog2-server/src/main/java/org/graylog2/ESTimestampFixup.java, graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java, misc/graylog2.conf
@lennartkoopmann asked me to move the default config file locations. They are now in `/etc/graylog/server` and `/etc/graylog/radio`. (like in the OS packages) The new documentation will refer to the new locations.
Please review, thanks!
=> Change config file locations

graylog2-inputs/src/main/java/org/graylog2/inputs/transports/AmqpConsumer.java, graylog2-inputs/src/main/java/org/graylog2/inputs/transports/AmqpTransport.java
=> Add AMQP transport config option for discarding messages on error.

graylog2-plugin-interfaces/src/main/java/org/graylog2/plugin/MessageSummary.java, graylog2-plugin-interfaces/src/test/java/org/graylog2/plugin/MessageSummaryTest.java
Also add tests.
As discussed in https://github.com/Graylog2/graylog2-server/issues/923#issuecomment-76977158 with @kroepke.
Fixes #976
=> Add hasField() and getField() methods to MessageSummary.

graylog2-radio/src/main/java/org/graylog2/radio/rest/resources/system/inputs/InputsResource.java
If the input was paused, the input from the input state should be used.
Create a new one otherwise.
This was noticed because the input stats haven't been updated after a
Radio input got paused/resumed.
Fixes Graylog2/graylog2-web-interface#1122.
=> Use input from the input state in launchExisting() for radio.

graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java
=> Also cloning alarm callbacks when cloning a stream.

graylog2-plugin-interfaces/src/main/java/org/graylog2/plugin/inputs/MessageInput.java, graylog2-shared/src/main/java/org/graylog2/shared/buffers/processors/DecodingProcessor.java
refs Graylog2/graylog2-web-interface#1106
=> Issue 1106 unused metrics

graylog2-shared/src/main/java/org/graylog2/shared/initializers/GroovyShellSetupService.java, integration-tests/pom.xml, pom.xml
Painless (backward-compatible) dependency updates.
=> Dependency updates

graylog2-plugin-interfaces/src/main/java/org/graylog2/plugin/database/users/User.java, graylog2-rest-client/src/main/java/org/graylog2/restclient/models/User.java, graylog2-server/src/main/java/org/graylog2/users/UserImpl.java
In order to make user preferences available to all users (including the admin), I moved them from the `UsersController` in the web interface to the `User` model.
Refs https://github.com/Graylog2/graylog2-web-interface/pull/1204
=> Move default user preferences into User model

graylog2-inputs/src/main/java/org/graylog2/inputs/gelf/kafka/GELFKafkaInput.java, graylog2-inputs/src/main/java/org/graylog2/inputs/raw/kafka/RawKafkaInput.java, graylog2-inputs/src/main/java/org/graylog2/inputs/syslog/kafka/SyslogKafkaInput.java, graylog2-shared/src/main/java/org/graylog2/shared/bindings/MessageInputBindings.java
This PR adds Kafka-based inputs for GELF, Syslog, and Raw/Plaintext.
Closes #322
=> Implement {GELF,Raw,Syslog} Kafka inputs

graylog2-inputs/src/main/java/org/graylog2/inputs/codecs/GelfChunkAggregator.java, graylog2-inputs/src/test/java/org/graylog2/inputs/codecs/GelfChunkAggregatorTest.java
=> track metrics for the gelf chunk manager

graylog2-inputs/src/main/java/org/graylog2/inputs/transports/AmqpConsumer.java, graylog2-inputs/src/main/java/org/graylog2/inputs/transports/AmqpTransport.java
Add AMQP heartbeat timeout to input configuration.
=> Fix issue 1010

graylog2-server/src/main/java/org/graylog2/indexer/Deflector.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexHelper.java, graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java, graylog2-server/src/main/java/org/graylog2/indexer/ranges/CreateNewSingleIndexRangeJob.java, graylog2-server/src/main/java/org/graylog2/indexer/ranges/RebuildIndexRangesJob.java, graylog2-server/src/main/java/org/graylog2/periodical/IndexRetentionThread.java, graylog2-server/src/main/java/org/graylog2/periodical/IndexRotationThread.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndicesResource.java, graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesTest.java, graylog2-server/src/test/resources/org/graylog2/indexer/indices/IndicesTest.json
=> Get rid of NoSuchElementException if index alias doesn't exist

graylog2-server/pom.xml, graylog2-server/src/test/java/org/graylog2/utilities/date/NaturalDateParserTest.java, pom.xml
Fixes #1226, refs joestelmach/natty#49
=> Upgrade to natty 0.11

graylog2-radio/src/main/java/org/graylog2/radio/users/NullUserServiceImpl.java, graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java, graylog2-server/src/main/java/org/graylog2/users/UserImpl.java, graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java, graylog2-server/src/test/java/org/graylog2/users/UserServiceImplTest.java, graylog2-server/src/test/resources/org/graylog2/users/UserServiceImplTest.json, graylog2-shared/src/main/java/org/graylog2/shared/users/UserService.java
=> Implement UserService#delete(String) to delete 1 or more users by username

graylog2-plugin-interfaces/src/main/java/org/graylog2/plugin/inputs/MessageInput.java, graylog2-plugin-interfaces/src/main/java/org/graylog2/plugin/inputs/transports/NettyTransport.java
=> Extend warning about SO_RCVBUF size to UDP inputs

graylog2-inputs/src/main/java/org/graylog2/inputs/codecs/gelf/GELFMessageChunk.java, graylog2-inputs/src/main/java/org/graylog2/inputs/random/generators/FakeHttpRawMessageGenerator.java, graylog2-inputs/src/test/java/org/graylog2/inputs/codecs/gelf/GELFMessageChunkTest.java, graylog2-plugin-interfaces/src/main/java/org/graylog2/plugin/BaseConfiguration.java, graylog2-plugin-interfaces/src/main/java/org/graylog2/plugin/KafkaJournalConfiguration.java, graylog2-rest-client/src/main/java/org/graylog2/restclient/models/api/results/MessageResult.java, graylog2-rest-client/src/test/java/org/graylog2/restclient/models/api/results/MessageResultTest.java, graylog2-server/src/main/java/org/graylog2/Configuration.java, graylog2-server/src/main/java/org/graylog2/buffers/Buffers.java, graylog2-server/src/main/java/org/graylog2/inputs/InputServiceImpl.java, graylog2-server/src/main/java/org/graylog2/system/stats/mongo/MongoProbe.java, graylog2-server/src/test/java/org/graylog2/alerts/types/FieldContentValueAlertConditionTest.java, graylog2-server/src/test/java/org/graylog2/shared/journal/KafkaJournalTest.java, graylog2-shared/src/main/java/org/graylog2/shared/bindings/Hk2GuiceBridgeJitInjector.java, graylog2-shared/src/main/java/org/graylog2/shared/bindings/providers/SystemOkHttpClientProvider.java, graylog2-shared/src/main/java/org/graylog2/shared/journal/KafkaJournal.java, graylog2-shared/src/main/java/org/graylog2/shared/rest/documentation/generator/Generator.java, graylog2-shared/src/main/java/org/graylog2/shared/system/stats/fs/FsStats.java, graylog2-shared/src/main/java/org/graylog2/shared/system/stats/os/JmxOsProbe.java, graylog2-shared/src/main/java/org/graylog2/shared/system/stats/os/SigarOsProbe.java, graylog2-shared/src/main/java/org/graylog2/shared/system/stats/process/JmxProcessProbe.java, pom.xml
This PR adds additional code checks to the "Pedantic" build profile using the [Error Prone](http://errorprone.info/) project.
=> Add checks with Error Prone to "Pedantic" build profile

graylog2-rest-client/src/main/java/org/graylog2/restclient/models/UniversalSearch.java, graylog2-rest-client/src/main/java/org/graylog2/restclient/models/api/responses/FieldStatsResponse.java, graylog2-rest-models/src/main/java/org/graylog2/rest/models/search/responses/FieldStatsResult.java, graylog2-server/src/main/java/org/graylog2/alerts/types/FieldValueAlertCondition.java, graylog2-server/src/main/java/org/graylog2/dashboards/widgets/FieldChartWidget.java, graylog2-server/src/main/java/org/graylog2/dashboards/widgets/StackedChartWidget.java, graylog2-server/src/main/java/org/graylog2/dashboards/widgets/StatisticalCountWidget.java, graylog2-server/src/main/java/org/graylog2/indexer/results/FieldHistogramResult.java, graylog2-server/src/main/java/org/graylog2/indexer/results/FieldStatsResult.java, graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/KeywordSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/RelativeSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/SearchResource.java, graylog2-server/src/test/java/org/graylog2/alerts/types/FieldValueAlertConditionTest.java, graylog2-server/src/test/java/org/graylog2/indexer/searches/SearchesTest.java
support only calculating the field aggregations that are required when computing a widget value
=> add field cardinality to numeric field statistics

graylog2-inputs/src/main/java/org/graylog2/inputs/transports/TcpTransport.java
=> Add TCP keepalive configuration option for TCP transports

graylog2-server/src/main/java/org/graylog2/alerts/AlertServiceImpl.java, graylog2-server/src/main/java/org/graylog2/alerts/types/FieldContentValueAlertCondition.java, graylog2-server/src/main/java/org/graylog2/alerts/types/FieldValueAlertCondition.java, graylog2-server/src/test/java/org/graylog2/alerts/types/FieldContentValueAlertConditionTest.java
Fixes Graylog2/graylog2-web-interface#1546
=> Prevent creation of invalid alert conditions

graylog2-bootstrap/pom.xml, graylog2-inputs/pom.xml, graylog2-plugin-interfaces/pom.xml, graylog2-plugin-interfaces/src/main/java/org/graylog2/plugin/streams/Stream.java, graylog2-radio/pom.xml, graylog2-rest-client/pom.xml, graylog2-rest-client/src/main/java/org/graylog2/restclient/models/Stream.java, graylog2-rest-client/src/main/java/org/graylog2/restclient/models/StreamService.java, graylog2-rest-client/src/main/java/org/graylog2/restclient/models/api/responses/streams/StreamSummaryResponse.java, graylog2-rest-models/pom.xml, graylog2-rest-models/src/main/java/org/graylog2/rest/models/streams/requests/UpdateStreamRequest.java, graylog2-rest-routes/pom.xml, graylog2-server/pom.xml, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java, graylog2-server/src/main/java/org/graylog2/streams/StreamImpl.java, graylog2-server/src/main/java/org/graylog2/streams/StreamRouterEngine.java, graylog2-server/src/test/java/org/graylog2/streams/StreamMock.java, graylog2-shared/pom.xml, integration-tests/pom.xml, integration-tests/src/test/java/integration/streams/StreamsTest.java, pom.xml
This PR adds the ability to update the matching type for existing streams.
=> Feature: Stream OR-Operator UI requirements

graylog2-plugin-interfaces/src/main/java/org/graylog2/plugin/inputs/Extractor.java, graylog2-rest-client/src/main/java/org/graylog2/restclient/models/Extractor.java, graylog2-server/src/main/java/org/graylog2/inputs/extractors/ExtractorFactory.java, graylog2-server/src/main/java/org/graylog2/inputs/extractors/JsonExtractor.java, graylog2-server/src/test/java/org/graylog2/inputs/extractors/JsonExtractorTest.java
Add a JSON extractor which can parse arbitrary JSON from other fields and expand them into the GELF message.
Closes #632
=> JSON Extractor

graylog2-server/src/main/java/org/graylog2/inputs/converters/TokenizerConverter.java, graylog2-server/src/test/java/org/graylog2/inputs/converters/TokenizerConverterTest.java
Reference: https://github.com/Graylog2/graylog2-server/issues/1359
=> Modify tokenizer to handle single and double quote

graylog2-server/src/main/java/org/graylog2/outputs/OutputRegistry.java, graylog2-server/src/main/java/org/graylog2/streams/OutputServiceMJImpl.java
=> Remove output from OutputRegistry when destroying it

graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
=> Retry bulk indexing messages on timeout

graylog2-server/src/main/java/org/graylog2/alerts/types/FieldValueAlertCondition.java, graylog2-server/src/main/java/org/graylog2/dashboards/widgets/StatisticalCountWidget.java, graylog2-server/src/main/java/org/graylog2/indexer/results/FieldStatsResult.java, graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/SearchResource.java, graylog2-server/src/test/java/org/graylog2/alerts/types/FieldValueAlertConditionTest.java
Returns NaN for invalid field types
=> Enable fieldstats for non-numeric fields

graylog2-server/src/main/java/org/graylog2/periodical/IndexRetentionThread.java
Since the index range information is stored directly inside the Elasticsearch indices themselves, recalculating them after index rotation is unnecessary. Before the change, this was necessary for housekeeping in the MongoDB "index_ranges" collection.
=> Do not recalculate index ranges on index rotation

graylog2-server/src/main/java/org/graylog2/streams/StreamRouterEngine.java, graylog2-server/src/test/java/org/graylog2/streams/StreamRouterEngineTest.java
=> Add missing short-circuit to stream router engine

graylog2-server/src/main/java/org/graylog2/indexer/ranges/EsIndexRangeService.java, graylog2-server/src/test/java/org/graylog2/indexer/ranges/EsIndexRangeServiceTest.java
In order to prevent potentially long-running cluster-level operations (like setting a write block on an index), the EsIndexRangeService#save() method now checks, whether an identical index range has already been stored for the index and skips saving the new but identical index range in this case.
=> Optimization: Only save changed index ranges

graylog2-server/src/main/java/org/graylog2/bundles/BundleImporter.java, integration-tests/src/test/java/integration/BaseRestTestHelper.java, integration-tests/src/test/java/integration/system/bundles/ContentPackStreamsTest.java, integration-tests/src/test/resources/integration/system/bundles/create-content-pack-with-streams.json
=> Fix Stream#MatchingType handling when applying content packs

graylog2-server/src/main/java/org/graylog2/indexer/Deflector.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/IndexRangesResource.java
=> Add resources to show/recalculate index range for single index

graylog2-server/src/main/java/org/graylog2/inputs/extractors/JsonExtractor.java, graylog2-server/src/test/java/org/graylog2/inputs/extractors/JsonExtractorTest.java
=> Ingore fields with null values in JsonExtractor

graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
=> Add missing role assignment when updating user

graylog2-server/src/main/java/org/graylog2/outputs/GelfOutput.java, graylog2-server/src/test/java/org/graylog2/outputs/GelfOutputTest.java
=> Fix extraction of message level in GelfOutput

graylog2-rest-client/src/main/java/org/graylog2/restclient/models/UsageStatsConfigurationResponse.java, graylog2-rest-client/src/main/java/org/graylog2/restclient/models/UsageStatsOptOutState.java, graylog2-rest-client/src/main/java/org/graylog2/restclient/models/UsageStatsService.java, graylog2-rest-models/src/main/java/org/graylog2/rest/models/system/usagestats/UsageStatsOptOutState.java
Depends on Graylog2/graylog-plugin-anonymous-usage-statistics#10.
=> Add rest-client parts for usage stats opt-out

graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndicesResource.java
Closing or deleting an index via the Graylog REST API doesn't require a recalculation of index range information for all indices any more.
=> Remove unnecessary complete index range recalculation

graylog2-inputs/src/main/java/org/graylog2/inputs/codecs/GelfChunkAggregator.java
=> Prevent NPE in GelfChunkAggregator#checkForCompletion()

misc/graylog2.conf
=> Load grok patterns content pack by default

graylog2-rest-client/src/main/java/org/graylog2/restclient/models/IndexService.java, graylog2-rest-routes/src/main/java/org/graylog2/restroutes/internal/RouteClassGenerator.java
This PR adds support for recalculating a single index range to graylog2-rest-client.
Refs #1451, refs #1455
=> Recalculate single index range

graylog2-server/src/main/java/org/graylog2/bindings/providers/EsClientProvider.java, graylog2-server/src/main/java/org/graylog2/indexer/elasticsearch/GlobalTimeoutClient.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/SearchResource.java
=> keep additional counters about performed search requests

graylog2-rest-models/src/main/java/org/graylog2/rest/models/system/DisplayGettingStarted.java, graylog2-server/src/main/java/org/graylog2/gettingstarted/GettingStartedState.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/GettingStartedResource.java
Support REST APIs for determining whether or not to show the getting started guide for this server version.
=> Getting started dismiss state

graylog2-shared/src/main/java/org/graylog2/shared/initializers/RestApiService.java, graylog2-shared/src/main/java/org/graylog2/shared/rest/CORSFilter.java
- answer OPTIONS requests early
- include Access-Control-Max-Age header to allow caching the CORS preflight in browser that support this
this greatly reduces the number of requests necessary to request data for the UI
=> improve CORS performance

graylog2-server/src/main/java/org/graylog2/security/ldap/LdapConnector.java
=> Support isMemberOf attribute of Sun Directory Server

graylog2-server/src/main/java/org/graylog2/shared/initializers/RestApiService.java, graylog2-server/src/main/java/org/graylog2/shared/rest/documentation/generator/Generator.java, graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationResource.java, graylog2-server/src/main/resources/swagger/swagger-ui.js
Without this, REST resources from plugins will not show up in the API browser.
=> Fix REST API browser with plugins

graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java, graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
This makes some indexing related methods reusable.
=> Improve indexing methods reusability

graylog2-server/src/main/java/org/graylog2/messageprocessors/MessageFilterChainProcessor.java, graylog2-server/src/test/java/org/graylog2/messageprocessors/MessageFilterChainProcessorTest.java
The implementation of `MessageFilterChainProcessor` has only been running messages through message filters until the first filter succeeded and didn't filter out the message (i. e. the default case) due to the early `return` statement inside the inner loop (iterating over the message filters).
=> Fix message iteration in MessageFilterChainProcessor

graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterSystemJobResource.java, graylog2-web-interface/src/actions/systemjobs/SystemJobsActions.jsx, graylog2-web-interface/src/routing/jsRoutes.js, graylog2-web-interface/src/stores/systemjobs/SystemJobsStore.js
- Add new /cluster/jobs/{jobId} REST endpoint.
- Add getJob() function to SystemJobsStore.
- Add new getJob() action to SystemJobsActions.
=> Make it possible to get a cluster system job by job ID

graylog2-web-interface/src/logic/rest/FetchProvider.js
This is a very small but significant change to the `FetchProvider` which fetches resources via http and returns promises to its callers. The default fetch strategy is to do an authenticated call to the server using the previously established session token. When this is done too early or too late at a point where no session is established, they will fail. To prevent this, this change checks if a session is existing before doing call, returning a new promise that is waiting for a session to be properly established before resolving it.
=> Delay authenticated fetches until session has been established.

graylog2-server/src/main/java/org/graylog2/inputs/random/generators/FakeHttpRawMessageGenerator.java
The purpose of the code change is to add time fields for event deduplication, first seen, last seen and time bucket association.
=> Updated Random Message Generator with time fields

graylog2-server/src/main/resources/swagger/lib/swagger.js
=> Fix Accept header for non-json endpoints in swagger ui

graylog2-server/src/main/java/org/graylog2/indexer/retention/strategies/ClosingRetentionStrategyConfig.java, graylog2-server/src/main/java/org/graylog2/indexer/retention/strategies/DeletionRetentionStrategy.java, graylog2-server/src/main/java/org/graylog2/indexer/retention/strategies/DeletionRetentionStrategyConfig.java, graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/MessageCountRotationStrategyConfig.java, graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/SizeBasedRotationStrategyConfig.java, graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategyConfig.java, graylog2-server/src/main/java/org/graylog2/periodical/ConfigurationManagementPeriodical.java, graylog2-server/src/main/java/org/graylog2/rest/models/system/indices/RetentionStrategies.java, graylog2-server/src/main/java/org/graylog2/rest/models/system/indices/RetentionStrategySummary.java, graylog2-server/src/main/java/org/graylog2/rest/models/system/indices/RotationStrategies.java, graylog2-server/src/main/java/org/graylog2/rest/models/system/indices/RotationStrategySummary.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indices/RetentionStrategyResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indices/RotationStrategyResource.java
This PR adds the capabilities to dynamically set and configure the rotation and retention strategies through the Graylog REST API.
=> Configurable rotation/retention strategy (REST API)

graylog2-web-interface/src/pages/ShowMetricsPage.jsx, graylog2-web-interface/src/stores/metrics/MetricsStore.js
=> Only load full namespace on demand, not when nodes collection updates.

graylog2-web-interface/src/pages/ConfigurationsPage.jsx, graylog2-web-interface/src/stores/configurations/ConfigurationsStore.js
The provided config components will show up at System/Configurations.
=> Allow plugins to provide system configuration components

graylog2-web-interface/src/components/streams/StreamComponent.jsx, graylog2-web-interface/src/components/streams/StreamList.jsx, graylog2-web-interface/src/pages/StreamsPage.jsx
It's about time that we do this, so here it goes.
=> Add stream filters to streams page

graylog2-server/src/main/java/org/graylog2/messageprocessors/MessageFilterChainProcessor.java, graylog2-server/src/main/java/org/graylog2/messageprocessors/MessageProcessorDescriptor.java, graylog2-server/src/main/java/org/graylog2/messageprocessors/MessageProcessorModule.java, graylog2-server/src/main/java/org/graylog2/messageprocessors/MessageProcessorsConfig.java, graylog2-server/src/main/java/org/graylog2/messageprocessors/MessageProcessorsConfigWithDescriptors.java, graylog2-server/src/main/java/org/graylog2/messageprocessors/OrderedMessageProcessors.java, graylog2-server/src/main/java/org/graylog2/plugin/PluginModule.java, graylog2-server/src/main/java/org/graylog2/plugin/messageprocessors/MessageProcessor.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/MessageProcessorsResource.java, graylog2-server/src/test/java/org/graylog2/messageprocessors/OrderedMessageProcessorsTest.java, graylog2-web-interface/src/actions/configurations/ConfigurationActions.js, graylog2-web-interface/src/components/configurations/MessageProcessorsConfig.jsx, graylog2-web-interface/src/pages/ConfigurationsPage.jsx, graylog2-web-interface/src/stores/configurations/ConfigurationsStore.js
- Add MessageProcessor.Descriptor interface
- Refactor config object
- Add REST endpoints for message processors configuration
- Add UI to enable/disable processors and to re-order them
- Change active processors order when the config changes
=> Add REST API endpoints and UI to configure message processors

graylog2-server/src/main/java/org/graylog2/shared/plugins/PluginLoader.java, graylog2-server/src/main/java/org/graylog2/web/PluginAssets.java, graylog2-web-interface/package.json
Fix problems loading plugins with `graylog-project`, as the class loader could not figure out which `module.json` file to load.
=> Fix shadow module.json

graylog2-server/pom.xml, graylog2-server/src/main/java/org/graylog2/dashboards/widgets/DashboardWidget.java, graylog2-server/src/main/java/org/graylog2/filters/blacklist/BlacklistIpMatcherCondition.java, graylog2-server/src/main/java/org/graylog2/filters/blacklist/BlacklistPatternCondition.java, graylog2-server/src/main/java/org/graylog2/grok/GrokPattern.java, graylog2-server/src/main/java/org/graylog2/shared/security/AccessTokenAuthToken.java, graylog2-server/src/main/java/org/graylog2/shared/security/SessionIdToken.java, graylog2-server/src/main/java/org/graylog2/shared/security/ldap/LdapEntry.java, graylog2-server/src/main/java/org/graylog2/users/RoleImpl.java, graylog2-server/src/test/java/org/graylog2/dashboards/widgets/DashboardWidgetTest.java, graylog2-server/src/test/java/org/graylog2/filters/blacklist/BlacklistFieldEqualityConditionTest.java, graylog2-server/src/test/java/org/graylog2/filters/blacklist/BlacklistPatternConditionTest.java, graylog2-server/src/test/java/org/graylog2/grok/GrokPatternTest.java, graylog2-server/src/test/java/org/graylog2/shared/security/AccessTokenAuthTokenTest.java, graylog2-server/src/test/java/org/graylog2/shared/security/SessionIdTokenTest.java, graylog2-server/src/test/java/org/graylog2/shared/security/ldap/LdapEntryTest.java, graylog2-server/src/test/java/org/graylog2/users/RoleImplTest.java, pom.xml
This PR adds some simple tests for the `equals()` methods of multiple value classes using EqualsVerifier.
http://www.jqno.nl/equalsverifier/
=> Add tests for equals() methods of multiple value classes

graylog2-server/src/main/java/org/graylog2/Configuration.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/KeywordSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/RelativeSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/SavedSearchesResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/SearchResource.java, graylog2-server/src/main/java/org/graylog2/users/RoleServiceImpl.java, graylog2-server/src/test/java/org/graylog2/indexer/IndexHelperTest.java, graylog2-server/src/test/java/org/graylog2/rest/resources/search/SearchResourceTest.java, misc/graylog2.conf
Backport of query range limit from #1806 to Graylog 1.3.x.
=> Implement simple query time range limit for Graylog 1.3.x

graylog2-web-interface/src/components/messageloaders/RecentMessageLoader.jsx, graylog2-web-interface/src/pages/SearchPage.jsx, graylog2-web-interface/src/routing/ApiRoutes.js, graylog2-web-interface/src/stores/search/UniversalSearchStore.js
Apparently we completely forgot to pass the sorting parameters to the server, so it wasn't working at all. Fixes #2028
=> Fix search result sorting on web interface

graylog2-inputs/src/main/java/org/graylog2/inputs/codecs/GelfChunkAggregator.java, graylog2-inputs/src/main/java/org/graylog2/inputs/codecs/gelf/GELFMessageChunk.java, graylog2-inputs/src/test/java/org/graylog2/inputs/codecs/GelfChunkAggregatorTest.java
Backport of #1986 to Graylog 1.3.x.
=> Backport of GELF chunk handler fix for Graylog 1.3.x

graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterSystemJobResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/jobs/RemoteSystemJobResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/jobs/SystemJobResource.java, graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java, graylog2-web-interface/src/actions/systemjobs/SystemJobsActions.jsx, graylog2-web-interface/src/components/systemjobs/SystemJob.jsx, graylog2-web-interface/src/routing/ApiRoutes.js, graylog2-web-interface/src/stores/systemjobs/SystemJobsStore.js
Exposes the existing cancellation of system jobs via the REST API and in the UI component for system jobs.
=> Expose cancellation of system jobs in REST API and UI

graylog2-web-interface/src/components/navigation/HelpMenu.jsx
=> Remove links to problem/question forms

graylog2-server/src/main/java/org/graylog2/indexer/results/ScrollResult.java
the first scroll chunk was discarded when writing the response
remember the initial search response and return the initial hits to avoid dropping data
fixes #2126
=> the async csv export writer dropped the first chunk

UPGRADING.asciidoc
=> how to delete the legacy index_range type

graylog2-server/src/main/java/org/graylog2/security/AESTools.java, graylog2-server/src/main/java/org/graylog2/security/ldap/LdapSettingsService.java, graylog2-server/src/main/java/org/graylog2/security/ldap/LdapSettingsServiceImpl.java, graylog2-server/src/test/java/org/graylog2/security/ldap/LdapSettingsServiceImplTest.java, graylog2-server/src/test/resources/org/graylog2/security/ldap/LdapSettingsServiceImplTest-invalid-password.json, graylog2-server/src/test/resources/org/graylog2/security/ldap/LdapSettingsServiceImplTest.json
=> Make LdapSettingsService#load() return null in case of wrong password secret

graylog2-server/src/main/java/org/graylog2/rest/resources/system/logs/LoggersResource.java, graylog2-server/src/test/java/org/graylog2/rest/resources/system/logs/LoggersResourceTest.java
=> Fix changing log level via REST API

graylog2-server/src/main/java/org/graylog2/rest/models/system/sessions/requests/SessionCreateRequest.java, graylog2-server/src/main/java/org/graylog2/security/ldap/LdapConnector.java, graylog2-server/src/main/java/org/graylog2/security/realm/LdapUserAuthenticator.java, graylog2-server/src/test/java/org/graylog2/security/ldap/LdapConnectorTest.java, graylog2-server/src/test/java/org/graylog2/security/realm/LdapUserAuthenticatorTest.java
=> Forbid empty passwords when using LDAP

graylog2-server/src/main/java/org/graylog2/rest/RestTools.java, graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationResource.java, graylog2-server/src/main/java/org/graylog2/web/resources/AppConfigResource.java, graylog2-server/src/test/java/org/graylog2/rest/RestToolsTest.java
=> Fix base URI for API documentation

misc/graylog.conf
additional to the needed update in the documentation i had created a note in the graylog.conf about extra partitions for the journal
ref: https://github.com/Graylog2/graylog2-server/issues/2348
=> added Information for journal partitions

graylog2-web-interface/src/components/metrics/Metric.jsx
=> Fix formatting metric names including more than one namespace prefix.

graylog2-web-interface/src/components/indices/ClosedIndexDetails.jsx
=> Display "Delete index" button for closed indices

graylog2-web-interface/.eslintrc, graylog2-web-interface/package.json
This PR is updating a few web if dependencies which seem to be safe for updating.
=> Web If: Updating a few dependencies which are safe to update.

graylog2-web-interface/src/components/users/UserForm.jsx
Fixes issue where external users got the password change form.
Fixes #2124
=> Add missing attributes to user state in UserForm

graylog2-web-interface/public/stylesheets/graylog2.less, graylog2-web-interface/src/components/search/ResultTable.jsx
Let search results table scroll on overflow, and fix some styling issues while doing so.
Fixes #2464
=> Improve overflow behaviour on search results table

graylog2-web-interface/src/components/authentication/AccessTokenConfig.js, graylog2-web-interface/src/components/authentication/MongoDbPasswordConfig.jsx, graylog2-web-interface/src/components/authentication/MongoDbSessionConfig.js, graylog2-web-interface/src/components/authentication/RootUserConfig.js
some of the pages will probably get actual content for 2.1.0-final but for now a placeholder text that looks nicer is good enough
=> improve styling and wording a bit for authentication providers

graylog2-server/src/main/java/org/graylog2/auditlog/AuditLogModule.java, graylog2-server/src/main/java/org/graylog2/plugin/PluginModule.java
Closes Graylog2/graylog-plugin-auditlog#4
=> Add helper method to add AuditLogAppenders

graylog2-web-interface/package.json
Security vulnerability: https://nodesecurity.io/advisories/55
=> Upgrade to moment 2.14.1

graylog2-server/src/main/java/org/graylog2/grok/GrokPatternRegistry.java
the server cache is necessary because the named captures support needs a separately compiled regex
so far the cache is only used by the grok function in the pipeline processor
fixes Graylog2/graylog-plugin-pipeline-processor#59
=> support "only named captures" for pipeline grok function

graylog2-web-interface/public/stylesheets/graylog2.less, graylog2-web-interface/src/components/authentication/AuthProvidersConfig.jsx, graylog2-web-interface/src/components/authentication/AuthenticationComponent.css, graylog2-web-interface/src/components/authentication/AuthenticationComponent.jsx, graylog2-web-interface/src/components/authentication/LegacyLdapConfig.js, graylog2-web-interface/src/components/ldap/LdapComponent.jsx, graylog2-web-interface/src/components/ldap/LdapGroupsComponent.jsx, graylog2-web-interface/src/components/users/EditRolesForm.jsx, graylog2-web-interface/src/components/users/NewUserForm.jsx, graylog2-web-interface/src/components/users/RoleList.jsx, graylog2-web-interface/src/components/users/RolesComponent.jsx, graylog2-web-interface/src/components/users/UserForm.jsx, graylog2-web-interface/src/components/users/UserList.css, graylog2-web-interface/src/components/users/UserList.jsx, graylog2-web-interface/src/pages/AuthenticationPage.jsx, graylog2-web-interface/src/pages/CreateUsersPage.jsx, graylog2-web-interface/src/pages/EditUsersPage.jsx, graylog2-web-interface/src/pages/RolesPage.jsx, graylog2-web-interface/src/stores/ldap/LdapGroupsStore.js, graylog2-web-interface/src/stores/ldap/LdapStore.js
This PR contains several fixes and improvements to authentication pages:
- Fix issue #2572
- Simplify `AuthenticationComponent`
- Use local styles to avoid clashes with other global styles
- Unify UI across all components involved in the new authentication page
- Other small improvements
=> Authentication improvements

graylog2-server/src/main/java/org/graylog2/decorators/DecoratorBindings.java, graylog2-server/src/main/java/org/graylog2/decorators/SyslogSeverityMapperDecorator.java, graylog2-server/src/test/java/org/graylog2/decorators/SyslogSeverityMapperDecoratorTest.java
Maps Syslog level numbers to their severity names.
Replaces Graylog2/graylog-plugin-pipeline-processor#55
=> Add Syslog severity mapper decorator

graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java
=> Fix NPE in Indices#checkForReopened(IndexMetaData)

graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/DecodingProcessor.java
This fixes an edge case where the journal grows when there is only one
input and no message can be decoded.
Fixes #2627
=> Mark message offset as committed in case of a decoding error

graylog2-server/src/main/java/org/graylog2/bindings/PeriodicalBindings.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexFailureImpl.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexFailureServiceImpl.java, graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java, graylog2-server/src/main/java/org/graylog2/periodical/IndexFailuresPeriodical.java
=> Add back storing of index failures in MongoDB

graylog2-web-interface/src/components/messageloaders/RawMessageLoader.jsx
In some cases it is necessary to get a message with an input ID.
(i.e. pipeline simulator)
Refs #2610
=> Allow selecting an input ID in RawMessageLoder to add to the parsed message

graylog2-web-interface/src/components/visualizations/QuickValuesVisualization.jsx
the others group did not take into account the other document groups which were outside of the first 45 "other" buckets
this led to incorrect rendering of pie chart slices
fixes #2639
=> use proper other count for pie chart slices

graylog2-web-interface/src/components/common/SearchForm.jsx, graylog2-web-interface/src/components/common/index.jsx
Adds a generic search form component.
I need this for another component I am working on to implement a simple search.
=> Add a generic search form component

graylog2-server/src/main/java/org/graylog2/plugin/BaseConfiguration.java, graylog2-server/src/test/java/org/graylog2/plugin/BaseConfigurationTest.java, graylog2-server/src/test/java/org/graylog2/plugin/ToolsTest.java
=> Ensure that rest_transport_uri can override the URI scheme of rest_listen_uri

graylog2-server/src/main/java/org/graylog2/decorators/DecoratorImpl.java, graylog2-web-interface/src/components/search/Decorator.jsx, graylog2-web-interface/src/components/search/DecoratorSidebar.jsx
=> Return "id" instead of "_id" for message decorators

graylog2-web-interface/src/components/common/SearchForm.jsx
This is needed to be able to add more buttons and other elements.
=> Allow child elements in the search form

graylog2-web-interface/src/pages/SearchPage.jsx
If search parameters change, cancel promise first.
Fixes #2799.
=> Check in SearchPage if search is in progress, reuse promise then.

graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesTest.java, pom.xml
Upgrade the internal ES node to Elasticsearch 2.4.0 and Jackson 2.8.2.
* https://www.elastic.co/blog/elasticsearch-2-4-0-released
* https://www.elastic.co/guide/en/elasticsearch/reference/2.4/release-notes-2.4.0.html
=> Upgrade to Elasticsearch 2.4.0

graylog2-web-interface/package.json, graylog2-web-interface/templates/index.html.template, graylog2-web-interface/templates/module.json.template, graylog2-web-interface/webpack.config.js
As blueimp is not the default anymore, also converting the templates to ejs.
=> Updating html-webpack-plugin to 2.22.0.

graylog2-server/src/test/java/org/graylog2/configuration/MongoDbConfigurationTest.java
* https://jira.mongodb.org/browse/JAVA-2220
* https://jira.mongodb.org/browse/JAVA-2245
* https://groups.google.com/forum/#!topic/graylog2/LpoDQfGWe3A
Refs #2853
=> Add test case for IPv6 address in "mongodb_uri"

graylog2-web-interface/src/util/DocsHelper.js
in 2.1 this page moved to configuration/load_balancers.html
=> update LOAD_BALANCERS in DocsHelper

graylog-plugin-parent/pom.xml
This adds some more properties and maven plugins to the graylog-plugin-parent which is used by multiple plugins.
=> Add more properties and plugins to graylog-plugin-parent

graylog2-server/src/test/java/org/graylog2/inputs/TestHelper.java, graylog2-server/src/test/java/org/graylog2/inputs/codecs/gelf/GELFMessageTest.java
Add missing unit tests for #2895.
=> Add unit tests for #2895

pom.xml
Just regular dependency updates for Graylog 2.2.x.
=> Dependency updates for Graylog 2.2.x

pom.xml
https://www.elastic.co/blog/elasticsearch-2-4-1-released
=> Upgrade to Elasticsearch 2.4.1

graylog2-server/src/main/java/org/graylog2/bindings/PeriodicalBindings.java, graylog2-server/src/main/java/org/graylog2/bindings/providers/BundleImporterProvider.java, graylog2-server/src/main/java/org/graylog2/bundles/BundleExporter.java, graylog2-server/src/main/java/org/graylog2/bundles/BundleImporter.java, graylog2-server/src/main/java/org/graylog2/bundles/Stream.java, graylog2-server/src/main/java/org/graylog2/periodical/DefaultStreamMigrationPeriodical.java, graylog2-server/src/main/java/org/graylog2/plugin/streams/Stream.java, graylog2-server/src/main/java/org/graylog2/plugin/streams/StreamRuleType.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/responses/StreamResponse.java, graylog2-server/src/main/java/org/graylog2/streams/StreamImpl.java, graylog2-server/src/main/java/org/graylog2/streams/StreamRouterEngine.java, graylog2-server/src/main/java/org/graylog2/streams/StreamRuleImpl.java, graylog2-server/src/main/java/org/graylog2/streams/config/DefaultStreamCreated.java, graylog2-server/src/main/java/org/graylog2/streams/matchers/AlwaysMatcher.java, graylog2-server/src/test/java/org/graylog2/periodical/DefaultStreamMigrationPeriodicalTest.java, graylog2-server/src/test/java/org/graylog2/streams/StreamMock.java, graylog2-server/src/test/java/org/graylog2/streams/StreamRuleMatcherFactoryTest.java, graylog2-server/src/test/java/org/graylog2/streams/matchers/AlwaysMatcherTest.java, graylog2-web-interface/src/components/streamrules/HumanReadableStreamRule.jsx, graylog2-web-interface/src/components/streamrules/StreamRuleForm.jsx
This PR introduces the "always matches" stream rule and a periodical creating a "default stream" in Graylog, which contains all newly ingested messages.
Refs #2880
=> Create Default stream

graylog2-server/src/test/java/org/graylog2/inputs/syslog/tcp/SyslogOctetCountFrameDecoderTest.java
Add unit test to ensure syslog messages >=2048 bytes are supported with the `SyslogOctetCountFrameDecoder`.
=> Test if syslog messages >=2048 bytes are supported

graylog2-server/src/main/java/org/graylog2/audit/AuditEventTypes.java, graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetConfig.java, graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetService.java, graylog2-server/src/main/java/org/graylog2/indexer/indexset/MongoIndexSetService.java, graylog2-server/src/main/java/org/graylog2/indexer/indexset/events/IndexSetCreatedEvent.java, graylog2-server/src/main/java/org/graylog2/indexer/indexset/events/IndexSetDeletedEvent.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexSetsResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/responses/IndexSetResponse.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/responses/IndexSetSummary.java, graylog2-server/src/main/java/org/graylog2/shared/rest/resources/RestResource.java, graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java, graylog2-server/src/test/java/org/graylog2/indexer/indexset/MongoIndexSetServiceTest.java, graylog2-server/src/test/java/org/graylog2/rest/resources/system/indexer/IndexSetsResourceTest.java, graylog2-server/src/test/resources/org/graylog2/indexer/indexset/MongoIndexSetServiceTest.json
Make index sets configurable via Graylog REST API
Refs #2880
=> Make index sets configurable via Graylog REST API

graylog-plugin-archetype/src/main/resources/archetype-resources/pom.xml, pom.xml
- Fix `<scm/>` config in parent pom.xml
- Adjust maven archetype
- Skip maven deploy by default
- Add `<distributionManagement/>`
- Add `<repositories/>`
=> Fix scm in server pom and adjust archetype

graylog2-server/src/main/java/org/graylog2/rest/resources/search/SearchResource.java
=> Use response status 500 if search failed but wasn't syntax error

graylog2-web-interface/src/legacy/analyzers/fieldcharts.js
When user modifies the statistical function for a field graph, change its description to reflect that change.
Fixes #2985
=> Update statistical function in field graph description

graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/DecodingProcessor.java
Closes #3025
(cherry picked from commit 4aceeb7747612411fd4f9d3b837bff0e383b1f5b)
=> Improve logging in DecodingProcessor

graylog2-server/src/main/java/org/graylog2/inputs/codecs/gelf/GELFMessage.java, graylog2-server/src/test/java/org/graylog2/inputs/TestHelper.java, graylog2-server/src/test/java/org/graylog2/inputs/codecs/gelf/GELFMessageTest.java
Closes #3022
(cherry picked from commits 1cd3566 and 3f838bc)
=> Support all ZLIB compression levels for GELF messages

graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java
Closes #3016
(cherry picked from commit 27f126bc2caaaf054d3ec16982e53924ade8e746)
=> Fix NPE in Indices#numberOfMessages(String)

graylog2-server/src/main/java/org/graylog2/security/realm/LdapUserAuthenticator.java
Closes #3017
(cherry picked from commit 9e401e648f11f30e4e584009b70a536affcd643f)
=> Only create new LdapConnectionConfig if LDAP is enabled

graylog2-server/src/main/java/org/graylog2/streams/StreamRuleService.java, graylog2-server/src/main/java/org/graylog2/streams/StreamRuleServiceImpl.java, graylog2-server/src/main/java/org/graylog2/streams/StreamServiceImpl.java
Closes #3024
(cherry picked from commit d7d70d45f3d205a0416c0d156dec41d8534de65f)
=> Prevent n+1 query loading for Stream Rules

graylog2-web-interface/src/legacy/analyzers/fieldcharts.js, graylog2-web-interface/src/routing/ApiRoutes.js
Closes #3028
(cherry picked from commit 45e7f81e2d5fa295f5a7884809efa685d7e09804)
=> Calculate cardinality on field graphs

graylog2-web-interface/src/legacy/analyzers/fieldcharts.js
Closes #3029
(cherry picked from commit 997772cd12e105f28be74874f4eff234881d2ffe)
=> Update stats function in field graph description

graylog2-web-interface/src/components/common/LoadingIndicator.css, graylog2-web-interface/src/components/common/LoadingIndicator.jsx, graylog2-web-interface/src/components/search/SearchResult.jsx, graylog2-web-interface/src/components/search/SearchSidebar.jsx
Closes #3031
(cherry picked from commit 8470fc1682744a9c4bb0e9c09c7bf30f2abc473c)
=> Improved search indicators

graylog2-web-interface/src/components/field-analyzers/FieldQuickValues.jsx, graylog2-web-interface/src/components/field-analyzers/FieldStatistics.jsx, graylog2-web-interface/src/components/search/SearchResult.jsx
Closes #3030
(cherry picked from commit 277af6921e8aa9211d9a2a0899bfe8ad855ecd2c)
=> Fix field analyzers loading when search changes

graylog2-web-interface/src/components/search/SearchBar.jsx
Closes #3032
(cherry picked from commit 9984ddf47ce84e1b45f9ce069879182a2ef24f81)
=> Close search query autocompletion on enter

graylog2-web-interface/src/pages/SearchPage.jsx, graylog2-web-interface/src/pages/StreamSearchPage.jsx
Closes #3033
(cherry picked from commit 2c43b0779958d959f436648f90552f52973fa24a)
=> Refresh stream search when stream changes

pom.xml
=> Upgrade to Joda-Time 2.9.5

graylog2-web-interface/package.json, pom.xml
=> Update Joda-Time and moment-timezone

graylog2-web-interface/src/components/field-analyzers/FieldQuickValues.jsx, graylog2-web-interface/src/components/field-analyzers/FieldStatistics.jsx, graylog2-web-interface/src/components/search/SearchBar.jsx, graylog2-web-interface/src/components/search/SearchResult.jsx, graylog2-web-interface/src/pages/SearchPage.jsx, graylog2-web-interface/src/routing/AppWithSearchBar.jsx
=> Search button does not always trigger a new search

graylog2-server/src/main/java/org/graylog2/streams/StreamServiceImpl.java
=> Reduce verbosity of StreamServiceImpl when loading streams

graylog2-server/src/main/java/org/graylog2/inputs/transports/KafkaTransport.java
Fixes issue #3095 
Ran against Kafka cluster with null messages.
=> Check for null messages in KafkaTransport

graylog2-server/src/main/java/org/graylog2/periodical/DefaultIndexSetMigrationPeriodical.java
=> Remove obsolete DefaultStreamCreated marker in DefaultIndexSetMigrationPeriodical

graylog2-server/src/main/java/org/graylog2/migrations/V20160929120500_CreateDefaultStreamMigration.java, graylog2-server/src/main/java/org/graylog2/plugin/streams/Stream.java, graylog2-server/src/main/java/org/graylog2/rest/models/streams/requests/UpdateStreamRequest.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/requests/CreateStreamRequest.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/responses/StreamResponse.java, graylog2-server/src/main/java/org/graylog2/streams/StreamImpl.java, graylog2-server/src/main/java/org/graylog2/streams/StreamRouterEngine.java, graylog2-server/src/main/java/org/graylog2/streams/StreamServiceImpl.java, graylog2-server/src/test/java/org/graylog2/streams/StreamMock.java, graylog2-server/src/test/java/org/graylog2/streams/StreamRouterEngineTest.java, graylog2-web-interface/src/components/streams/StreamForm.jsx, graylog2-web-interface/src/stores/streams/StreamsStore.ts
=> Allow to remove message from default stream

graylog2-web-interface/src/components/streams/Stream.jsx
This change was missing from the earlier PR.
Most of the actions are not allowed for the default stream, so we don't want to render elements that lead to error messages.
=> remove update buttons/actions from UI for the default stream

graylog2-server/src/main/java/org/graylog2/indexer/IndexHelper.java, graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/KeywordSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/RelativeSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/SearchResource.java, graylog2-server/src/test/java/org/graylog2/indexer/IndexHelperTest.java, graylog2-server/src/test/java/org/graylog2/indexer/searches/SearchesTest.java
=> filter indices to search in according to stream filter

UPGRADING.rst, graylog2-server/src/main/java/org/graylog2/indexer/IndexHelper.java, graylog2-server/src/main/java/org/graylog2/indexer/MongoIndexSetRegistry.java, graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java, graylog2-server/src/main/java/org/graylog2/indexer/ranges/EsIndexRange.java, graylog2-server/src/main/java/org/graylog2/indexer/ranges/EsIndexRangeService.java, graylog2-server/src/main/java/org/graylog2/indexer/ranges/IndexRange.java, graylog2-server/src/main/java/org/graylog2/indexer/ranges/IndexRangeService.java, graylog2-server/src/main/java/org/graylog2/indexer/ranges/LegacyMongoIndexRangeService.java, graylog2-server/src/main/java/org/graylog2/indexer/ranges/MongoIndexRange.java, graylog2-server/src/main/java/org/graylog2/indexer/ranges/MongoIndexRangeService.java, graylog2-server/src/main/java/org/graylog2/indexer/ranges/RebuildIndexRangesJob.java, graylog2-server/src/main/java/org/graylog2/indexer/searches/IndexRangeStats.java, graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java, graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java, graylog2-server/src/main/java/org/graylog2/migrations/V20161130141500_DefaultStreamRecalcIndexRanges.java, graylog2-server/src/test/java/org/graylog2/indexer/IndexHelperTest.java, graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesTest.java, graylog2-server/src/test/java/org/graylog2/indexer/ranges/MongoIndexRangeServiceTest.java, graylog2-server/src/test/java/org/graylog2/indexer/searches/IndexRangeStatsTest.java, graylog2-server/src/test/java/org/graylog2/indexer/searches/SearchesTest.java
=> Store streams with index ranges

graylog2-server/src/main/java/org/graylog2/streams/StreamRouterEngine.java
=> don't warn when removing the default stream multiple times

graylog2-server/src/main/java/org/graylog2/alarmcallbacks/AlarmCallbackConfiguration.java, graylog2-server/src/main/java/org/graylog2/alarmcallbacks/AlarmCallbackConfigurationAVImpl.java, graylog2-server/src/main/java/org/graylog2/alarmcallbacks/AlarmCallbackConfigurationServiceMJImpl.java, graylog2-server/src/main/java/org/graylog2/alarmcallbacks/AlarmCallbackHistoryImpl.java, graylog2-server/src/main/java/org/graylog2/migrations/V20161125142400_EmailAlarmCallbackMigration.java, graylog2-server/src/main/java/org/graylog2/rest/models/alarmcallbacks/AlarmCallbackSummary.java, graylog2-server/src/main/java/org/graylog2/rest/models/alarmcallbacks/requests/CreateAlarmCallbackRequest.java, graylog2-server/src/main/java/org/graylog2/rest/resources/alarmcallbacks/AlarmCallbacksResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/alarmcallbacks/StreamAlarmCallbackResource.java, graylog2-server/src/test/java/org/graylog2/alarmcallbacks/AlarmCallbackConfigurationServiceMJImplTest.java, graylog2-server/src/test/java/org/graylog2/migrations/V20161125161400_AlertReceiversMigrationTest.java, graylog2-web-interface/src/components/alertconditions/AlertConditionsComponent.jsx, graylog2-web-interface/src/components/alertnotifications/AlertNotification.jsx, graylog2-web-interface/src/components/alertnotifications/AlertNotificationsComponent.jsx, graylog2-web-interface/src/components/alertnotifications/CreateAlertNotificationInput.jsx
This adds support for titles in alarm callbacks and allows setting them from the UI.
Fixes #3146
=> Add alarm callback titles

graylog2-web-interface/src/components/alertnotifications/AlertNotification.jsx
=> Include current title in edit notification form

graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/requests/CloneStreamRequest.java
Also use those given options on the new (cloned) stream.
Fixes #3162
=> Adapt clone API request to accept index set options

graylog2-web-interface/webpack/vendor-module-ids.json
=> Sync vendor-module-ids.json file

graylog2-server/src/main/java/org/graylog2/users/UserImpl.java, graylog2-web-interface/src/stores/users/StartpageStore.js
Since 2.1 it was not possible to reset the user's start page. This PR fixes that issue (#3164).
=> Fix resetting user's start page

graylog2-web-interface/webpack.combined.config.js
Get the plugin name from the package.json file or the parent directory name instead of just splitting the path and taking a "random" element.
Also do not include webpack configurations from the node_modules and target directories.
=> Fix loading of web plugins in development mode

graylog2-web-interface/src/components/alerts/Alert.css, graylog2-web-interface/src/components/alerts/Alert.jsx, graylog2-web-interface/src/components/alerts/AlertTimeline.css, graylog2-web-interface/src/components/alerts/AlertTimeline.jsx, graylog2-web-interface/src/components/alerts/AlertsComponent.jsx, graylog2-web-interface/src/pages/ShowAlertPage.jsx
This PR includes some improvements in alert pages:
- Most changes suggested in #3199
- Add refresh button to alert list, so it is possible to check if something new came in without a reload
- Add navigation buttons into alert details page
- Fix margins, as suggested in #3201
=> Alerts UI improvements

graylog2-server/src/main/java/org/graylog2/migrations/V20161130141500_DefaultStreamRecalcIndexRanges.java
Getting the default index set might not work if you are running with a 2.2.0-beta.2 state before commit 460cac6af.
=> Fix V20161130141500_DefaultStreamRecalcIndexRanges

graylog2-server/src/main/java/org/graylog2/security/MongoDBSessionService.java, graylog2-server/src/main/java/org/graylog2/security/MongoDBSessionServiceImpl.java, graylog2-server/src/main/java/org/graylog2/security/MongoDbSessionDAO.java
=> Fix NPE in MongoDbSessionDAO#doDelete()

graylog2-server/src/main/java/org/graylog2/commands/journal/AbstractJournalCommand.java
=> Add missing AuditBindings to journal commands

graylog2-web-interface/src/logic/notifications/NotificationsFactory.js
=> Add space in processing limit notification

graylog2-server/src/main/java/org/graylog2/streams/StreamServiceImpl.java
Otherwise the alerts will be unresolved forever.
Fixes #3200
=> Resolve alerts from deleted alert conditions

graylog2-web-interface/src/components/alertconditions/AlertCondition.jsx, graylog2-web-interface/src/components/alertconditions/AlertConditionSummary.jsx, graylog2-web-interface/src/components/alertconditions/ConditionAlertNotifications.jsx
More alert UI refinements. Refs #3178
=> Alert UI changes

graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexerOverviewResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndicesResource.java
=> Remove 2.2 todo comments which are already done

graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategy.java, graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategyTest.java
=> Save anchor and last rotation in TimeBasedRotationStrategy depending on IndexSet

graylog2-server/src/main/java/org/graylog2/indexer/MongoIndexSet.java
=> Remove stray whitespace in MongoIndexSet

graylog2-server/src/main/java/org/graylog2/periodical/IndexRangesMigrationPeriodical.java, graylog2-web-interface/src/logic/notifications/NotificationsFactory.js
we now list the index sets that need fixing, because the maintenance menu is only accessible for each index set individually
fixes #3368
This is how it looks now:
=> add more detail to index range system notification

graylog2-web-interface/src/components/search/SearchBar.jsx
=> Reset keyword content after changing range type

graylog2-web-interface/src/components/streams/StreamForm.jsx
Also remove `index_set_id` from default props because it's not a prop.
=> Use the default index set by default in stream create form

graylog2-server/src/main/java/org/graylog2/bundles/BundleExporter.java, graylog2-server/src/main/java/org/graylog2/bundles/BundleImporter.java, graylog2-server/src/main/java/org/graylog2/bundles/Input.java
=> Retain input and stream IDs in content packs

graylog2-server/src/main/java/org/graylog2/rest/resources/system/ClusterResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/ClusterStatsResource.java, graylog2-web-interface/src/routing/ApiRoutes.js, graylog2-web-interface/src/stores/sessions/ServerAvailabilityStore.js
=> Add missing authentication to ClusterResource and ClusterStatsResource

graylog2-server/src/test/java/org/graylog2/decorators/DecoratorServiceImplTest.java, graylog2-server/src/test/resources/org/graylog2/decorators/DecoratorServiceImplTest.json, graylog2-web-interface/src/components/search/Decorator.jsx
=> Send "stream" property when updating a decorator

graylog2-web-interface/src/components/common/TableList.jsx, graylog2-web-interface/src/components/outputs/AssignOutputDropdown.jsx, graylog2-web-interface/src/components/outputs/Output.jsx, graylog2-web-interface/src/components/outputs/OutputList.jsx, graylog2-web-interface/src/components/search/ShowQueryModal.jsx, graylog2-web-interface/src/components/source-tagging/SourceType.jsx, graylog2-web-interface/src/components/streams/CreateStreamButton.jsx, graylog2-web-interface/src/components/streams/StreamComponent.jsx, graylog2-web-interface/src/components/streams/StreamThroughput.jsx, graylog2-web-interface/src/components/usagestats/UsageStatsOptIn.jsx, graylog2-web-interface/src/components/usagestats/UsageStatsOptOut.jsx, graylog2-web-interface/src/components/users/EditRole.jsx, graylog2-web-interface/src/components/users/PermissionSelector.jsx, graylog2-web-interface/src/components/users/RoleList.jsx, graylog2-web-interface/src/components/visualizations/QuickValuesVisualization.jsx
This commit reformat the code of some old components by:
- Using ES2015 modules
- Adding prop types
- Fixing linter errors
- Removing 'use strict' declaration
=> Reformat old components

graylog2-server/src/main/java/org/graylog2/alerts/types/FieldContentValueAlertCondition.java, graylog2-server/src/main/java/org/graylog2/alerts/types/MessageCountAlertCondition.java, graylog2-server/src/main/java/org/graylog2/dashboards/widgets/strategies/QuickvaluesWidgetStrategy.java, graylog2-server/src/main/java/org/graylog2/dashboards/widgets/strategies/SearchResultChartWidgetStrategy.java, graylog2-server/src/main/java/org/graylog2/dashboards/widgets/strategies/SearchResultCountWidgetStrategy.java, graylog2-server/src/main/java/org/graylog2/dashboards/widgets/strategies/StatisticalCountWidgetStrategy.java, graylog2-server/src/main/java/org/graylog2/dashboards/widgets/strategies/StreamSearchResultCountWidgetStrategy.java
* Individual factory methods for AlertConditions
* AssistedInject for WidgetStrategies
Refs #3488
Refs #3493
=> Fix too eager removals during cleanup

graylog2-web-interface/src/pages/SystemOutputsPage.jsx
=> Add missing whitespace in SystemOutputsPage

graylog2-web-interface/package.json, graylog2-web-interface/src/components/search/SearchBar.jsx, graylog2-web-interface/webpack/vendor-module-ids.json
Updating some web dependencies which are safe to update.
=> Update web dependencies

graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetConfig.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/responses/IndexSetSummary.java, graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.jsx
=> Ensure that index_prefix is lower case

graylog2-server/src/main/java/org/graylog2/plugin/inputs/MessageInput.java
=> Make map in MessageInput#asMap() mutable

graylog2-web-interface/src/components/search/MessageTablePaginator.jsx, graylog2-web-interface/src/components/visualizations/GraphVisualization.jsx, graylog2-web-interface/src/components/visualizations/HistogramVisualization.jsx, graylog2-web-interface/src/components/visualizations/QuickValuesVisualization.jsx
This PR is removing a number of inclusions of the static jquery/bootstrap assets, although jquery itself is not used in the component.
=> Removing a number of static script jquery/bootstrap requires.

graylog2-web-interface/src/components/alertnotifications/AlertNotification.jsx
This is a port of #3537 to the `2.2` branch.
Fixes #3534
(cherry picked from commit 0a3b8819590a073a74bafbae5524b8964f842f7f)
=> Wait until notification types are loaded (#3537)

graylog2-web-interface/src/stores/users/UsersStore.ts
While migrating to webpack 2 and some experimentation with exporting
semantics, a change of the exports of the UsersStore slipped in. This
change is reverting that.
Fixes #3556.
=> Fixing exports of UsersStore, which were accidentally changed.

graylog2-server/src/main/java/org/graylog2/inputs/extractors/JsonExtractor.java, graylog2-server/src/test/java/org/graylog2/inputs/extractors/JsonExtractorTest.java
=> Support replacing whitespace in nested keys for JSON extractor

graylog2-web-interface/src/stores/systemmessages/SystemMessagesStore.js
Refs #3632
Fixes #3628 
(cherry picked from commit 41be1686f3e08e1fc0a5ce81f43d338826a8d023)
=> Prevent session extension for polling system messages

graylog2-server/src/main/java/org/graylog2/indexer/retention/strategies/AbstractIndexCountBasedRetentionStrategy.java
backport of https://github.com/Graylog2/graylog2-server/pull/3637
=> Prevent NPE due to race between rotation and retention threads (#3637)

graylog2-web-interface/src/stores/systemjobs/SystemJobsStore.js
Refs #3625
Fixes #3587
(cherry picked from commit 4ded9e7a2f477f7657a01ee217794b00ee6f9e69)
=> Prevent session extension in SystemJobsStore

graylog2-web-interface/src/components/search/SearchResult.jsx
Fixes #3650
I will backport the change to 2.2.3 once the PR is merged.
=> Render loading indicator on no results page

graylog2-web-interface/src/components/dashboard/EditDashboardModal.jsx, graylog2-web-interface/src/components/streamrules/StreamRuleForm.jsx, graylog2-web-interface/src/components/streams/StreamForm.jsx
This small PR gives some elements better names, so we can identify them more easily in selenium-based tests.
=> Adding helpful name tags to input elements to aid finding them in tests.

graylog2-server/src/main/java/org/graylog2/alerts/AlertScanner.java, graylog2-server/src/main/java/org/graylog2/alerts/AlertService.java, graylog2-server/src/main/java/org/graylog2/alerts/AlertServiceImpl.java, graylog2-server/src/test/java/org/graylog2/alerts/AlertScannerTest.java, graylog2-server/src/test/java/org/graylog2/alerts/AlertServiceImplTest.java
Fixes #3579, backport of #3676
=> Comply with grace condition when repeat alert notifications is enabled

graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/util/KeyUtil.java, graylog2-server/src/main/java/org/graylog2/web/resources/WebInterfaceAssetsResource.java
Due to a custom finalizer, FileInputStream and FileOutputStream instances will only get
cleaned up when the garbage collector does a full GC run.
In order to (defensively) reduce the GC pressure induced by File{In,Out}putStream instances,
this change set changes their usage to a less problematic variant whenever possible.
Reference: https://www.cloudbees.com/blog/fileinputstream-fileoutputstream-considered-harmful
=> Clean up usages of File{In,Out}putStream

graylog2-server/src/main/java/org/graylog2/database/validators/OptionalStringValidator.java, graylog2-server/src/main/java/org/graylog2/inputs/InputImpl.java, graylog2-server/src/test/java/org/graylog2/database/validators/LimitedOptionalStringValidatorTest.java, graylog2-server/src/test/java/org/graylog2/database/validators/OptionalStringValidatorTest.java
=> Fix OptionalStringValidator and validations for extractors

graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupResult.java, graylog2-web-interface/src/components/common/TimeUnit.jsx, graylog2-web-interface/src/components/common/index.jsx, graylog2-web-interface/src/components/lookup-tables/Cache.jsx, graylog2-web-interface/src/components/lookup-tables/ConfigSummary.css, graylog2-web-interface/src/components/lookup-tables/DataAdapter.jsx, graylog2-web-interface/src/components/lookup-tables/adapters/CSVFileAdapterSummary.jsx, graylog2-web-interface/src/components/lookup-tables/caches/GuavaCacheSummary.jsx, graylog2-web-interface/src/components/lookup-tables/caches/NullCacheSummary.jsx
This change also adds a simple component for displaying TimeUnit values from the API.
=> Improve cache and adapter summary pages

graylog2-server/src/main/java/org/graylog2/lookup/adapters/CSVFileDataAdapter.java, graylog2-server/src/main/java/org/graylog2/plugin/utilities/FileInfo.java
this allows reusing some of the functionality across plugins, to avoid reinventing the code all over the place
=> extract FileInfo into top level plugin namespace

graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java
Supporting https://github.com/Graylog2/graylog-plugin-anonymous-usage-statistics/pull/23.
=> Introduce total searches counter used by anonymous usage statistics.

UPGRADING.rst, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indices/RetentionStrategyResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indices/RotationStrategyResource.java, graylog2-web-interface/src/actions/indices/IndicesConfigurationActions.js, graylog2-web-interface/src/stores/indices/IndicesConfigurationStore.js
The list of available rotation/retention strategies is still needed.
=> Revert parts of #3724 to unbreak editing index sets

graylog2-server/src/main/java/org/graylog2/lookup/LookupTableService.java, graylog2-server/src/main/java/org/graylog2/lookup/adapters/CSVFileDataAdapter.java, graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupResult.java
Introduces a single value for `LookupResult`.
=> Lookup single values

graylog2-server/src/main/java/org/graylog2/bindings/providers/BundleImporterProvider.java, graylog2-server/src/main/java/org/graylog2/bundles/BundleImporter.java, graylog2-server/src/main/java/org/graylog2/inputs/InputServiceImpl.java, graylog2-server/src/main/java/org/graylog2/inputs/converters/ConverterFactory.java, graylog2-server/src/main/java/org/graylog2/inputs/converters/LookupTableConverter.java, graylog2-server/src/main/java/org/graylog2/inputs/extractors/ExtractorFactory.java, graylog2-server/src/main/java/org/graylog2/inputs/extractors/LookupTableExtractor.java, graylog2-server/src/main/java/org/graylog2/lookup/LookupTableService.java, graylog2-server/src/main/java/org/graylog2/plugin/inputs/Converter.java, graylog2-server/src/main/java/org/graylog2/plugin/inputs/Extractor.java, graylog2-server/src/main/java/org/graylog2/rest/models/tools/requests/LookupTableTestRequest.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/ExtractorsResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/tools/LookupTableTesterResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/tools/responses/LookupTableTesterResponse.java, graylog2-web-interface/src/components/extractors/EditExtractorConfiguration.jsx, graylog2-web-interface/src/components/extractors/EditExtractorConverters.jsx, graylog2-web-interface/src/components/extractors/converters_configuration/LookupTableConverterConfiguration.jsx, graylog2-web-interface/src/components/extractors/converters_configuration/index.jsx, graylog2-web-interface/src/components/extractors/extractors_configuration/LookupTableExtractorConfiguration.jsx, graylog2-web-interface/src/components/extractors/extractors_configuration/index.jsx, graylog2-web-interface/src/routing/ApiRoutes.js, graylog2-web-interface/src/stores/tools/ToolsStore.ts, graylog2-web-interface/src/util/ExtractorUtils.jsx
This adds an extractor and a converter that can use lookup tables.
=> Add extractor and converter for lookup tables

graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java
The query string wasn't used to build a proper Elasticsearch query but was used
directly in the Elasticsearch request.
=> Fix Searches#scroll(...)

graylog2-web-interface/src/logic/search/UniversalSearch.js
=> Import jQuery to avoid reference errors on sources page

graylog2-server/src/main/java/org/graylog2/indexer/results/SearchResult.java, graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java, graylog2-server/src/test/java/org/graylog2/alerts/types/FieldContentValueAlertConditionTest.java, graylog2-server/src/test/java/org/graylog2/indexer/results/SearchResultTest.java, graylog2-server/src/test/java/org/graylog2/indexer/searches/SearchesTest.java
=> Fix pagination and offset/total hits in Searches

graylog2-server/src/main/java/org/graylog2/indexer/searches/Sorting.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/RelativeSearchResource.java
Closes #3735
This PR is merely a rebase of #3735 on current `master`.
=> Added sort order to terms API call

graylog2-web-interface/src/components/outputs/Output.jsx
=> Hide 'Delete from stream' button if stream is undefined

graylog2-web-interface/src/components/lookup-tables/CacheForm.jsx, graylog2-web-interface/src/components/lookup-tables/DataAdapterForm.jsx, graylog2-web-interface/src/components/lookup-tables/LookupTableForm.jsx, graylog2-web-interface/src/util/ObjectUtils.js
the new forms did not implement componentWillReceiveProps and hung on to the old state when re-rendered.
fixes #3764
=> implement componentWillReceiveProps to properly set form state

graylog2-server/src/main/java/org/graylog2/decorators/DecoratorBindings.java, graylog2-server/src/main/java/org/graylog2/decorators/LookupTableDecorator.java, graylog2-server/src/test/java/org/graylog2/decorators/LookupTableDecoratorTest.java
=> Add Lookup Table search result decorator

graylog2-server/src/main/java/org/graylog2/alarmcallbacks/EmailAlarmCallback.java, graylog2-server/src/test/java/org/graylog2/alarmcallbacks/EmailAlarmCallbackTest.java
=> Add admin user to list of receivers in EmailAlarmCallback

graylog2-server/src/main/java/org/graylog2/search/SearchQuery.java, graylog2-server/src/main/java/org/graylog2/search/SearchQueryField.java, graylog2-server/src/main/java/org/graylog2/search/SearchQueryOperator.java, graylog2-server/src/main/java/org/graylog2/search/SearchQueryOperators.java, graylog2-server/src/main/java/org/graylog2/search/SearchQueryParser.java, graylog2-server/src/test/java/org/graylog2/search/SearchQueryParserTest.java
Extracted from the enterprise product.
=> Add search system for objects in MongoDB

graylog2-server/src/main/java/org/graylog2/bindings/providers/JestClientProvider.java
This change enables preemptive authentication towards Elasticsearch
nodes whose URIs contain credentials. This way we save half of the
requests which are otherwise bounced back before authentication is
tried.
=> Use preemptive authentication for Elasticsearch if credentials are given

graylog2-web-interface/src/components/lookup-tables/DataAdapter.jsx, graylog2-web-interface/src/components/lookup-tables/LookupTable.jsx, graylog2-web-interface/src/pages/LUTDataAdaptersPage.jsx, graylog2-web-interface/src/pages/LUTTablesPage.jsx
Fixes a problem where the lookup result of a previous adapter shows up on a different one.
=> Keep lookup-result state locally

graylog2-server/src/main/java/org/graylog2/lookup/dto/CacheDto.java, graylog2-server/src/main/java/org/graylog2/lookup/dto/DataAdapterDto.java, graylog2-server/src/main/java/org/graylog2/lookup/dto/LookupTableDto.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/lookup/LookupTableResource.java, graylog2-web-interface/src/components/lookup-tables/CachesOverview.jsx, graylog2-web-interface/src/components/lookup-tables/DataAdaptersOverview.jsx, graylog2-web-interface/src/components/lookup-tables/LookupTablesOverview.jsx, graylog2-web-interface/src/components/lookup-tables/Overview.css
This makes the existing search forms for lookup tables, data adapters and caches work.
Closes #3843
=> Enable search for lookup tables, data adapters and caches

graylog2-server/src/main/java/org/graylog2/bundles/BundleExporter.java, graylog2-server/src/main/java/org/graylog2/bundles/BundleImporter.java, graylog2-server/src/main/java/org/graylog2/bundles/LookupTableBundle.java, graylog2-server/src/main/java/org/graylog2/lookup/LookupDefaultMultiValue.java, graylog2-server/src/main/java/org/graylog2/lookup/LookupDefaultSingleValue.java, graylog2-server/src/main/java/org/graylog2/lookup/LookupDefaultValue.java, graylog2-server/src/main/java/org/graylog2/lookup/LookupTable.java, graylog2-server/src/main/java/org/graylog2/lookup/LookupTableService.java, graylog2-server/src/main/java/org/graylog2/lookup/adapters/HTTPJSONPathDataAdapter.java, graylog2-server/src/main/java/org/graylog2/lookup/dto/LookupTableDto.java, graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupResult.java, graylog2-server/src/main/java/org/graylog2/rest/models/system/lookup/LookupTableApi.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/lookup/LookupTableResource.java, graylog2-server/src/test/java/org/graylog2/lookup/LookupDefaultMultiValueTest.java, graylog2-server/src/test/java/org/graylog2/lookup/LookupDefaultSingleValueTest.java, graylog2-web-interface/src/actions/lookup-tables/LookupTablesActions.js, graylog2-web-interface/src/components/common/JSONValueInput.jsx, graylog2-web-interface/src/components/common/index.jsx, graylog2-web-interface/src/components/lookup-tables/LookupTable.jsx, graylog2-web-interface/src/components/lookup-tables/LookupTableCreate.jsx, graylog2-web-interface/src/components/lookup-tables/LookupTableForm.jsx, graylog2-web-interface/src/pages/LUTTablesPage.jsx, graylog2-web-interface/src/stores/lookup-tables/LookupTablesStore.js
This adds default values for lookup tables.
=> Add default values for lookup tables

graylog2-server/src/main/java/org/graylog2/rest/resources/streams/alerts/StreamAlertConditionResource.java, graylog2-web-interface/src/components/alertconditions/AlertCondition.jsx, graylog2-web-interface/src/components/alertconditions/EditAlertConditionForm.jsx
=> Use correct permission check for deleting alert conditions

graylog2-server/src/main/java/org/graylog2/lookup/adapters/CSVFileDataAdapter.java, graylog2-web-interface/src/components/lookup-tables/adapters/CSVFileAdapterFieldSet.jsx, graylog2-web-interface/src/components/lookup-tables/adapters/CSVFileAdapterSummary.jsx
=> Add case-insensitive lookup config option to CSVFileDataAdapter

graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/AbstractRotationStrategy.java, graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategyTest.java
* Improve error messages emitted in AbstractRotationStrategy
* Assure that index set configuration is not null
Refs #3990
(cherry picked from commit b594affc992f4535e50eb330da9ab610a21e0f60)
=> Improve error messages emitted in AbstractRotationStrategy

graylog2-web-interface/src/components/lookup-tables/Cache.jsx
=> Remove TODO item from lookup cache details page

graylog2-web-interface/src/components/lookup-tables/Cache.jsx
=> Remove TODO item from lookup cache details page (#4007)

graylog2-web-interface/src/legacy/analyzers/fieldcharts.js
(cherry picked from commit e412164eff811b0f4b06ea7b3b81e30c4bae6b9e)
=> Removing superfluous quote to unbreak legend for stacked charts. (#3996)

graylog2-server/src/main/java/org/graylog2/shared/utilities/ExceptionUtils.java, graylog2-server/src/test/java/org/graylog2/shared/utilities/ExceptionUtilsTest.java
Guard against NPE exception in ExceptionUtils#formatMessageCause
fixes #4003
=> Issue 4003

graylog2-server/src/main/java/org/graylog2/shared/utilities/ExceptionUtils.java, graylog2-server/src/test/java/org/graylog2/shared/utilities/ExceptionUtilsTest.java
fix NPE in ExceptionUtils#formatCauseMessage
backport for #4003
=> Issue 4003 2.3

graylog2-server/src/main/java/org/graylog2/inputs/codecs/GelfCodec.java, graylog2-server/src/test/java/org/graylog2/inputs/codecs/GelfCodecTest.java
=> Relax GELF codec by accepting strings for "timestamp"

graylog2-server/src/main/java/org/graylog2/inputs/codecs/GelfCodec.java, graylog2-server/src/test/java/org/graylog2/inputs/codecs/GelfCodecTest.java
Because every fucking GELF library seems to be broken. 😠
=> Allow empty/blank "short_message" field if "message" exists

graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java, graylog2-server/src/test/java/org/graylog2/indexer/searches/SearchesTest.java
Refs 4069
Fixes #4068
(cherry picked from commit 1aa1ba29db4bbc29b7e734f065e6d2c2c5d40bb1)
=> Fix search requests with selected fields by using source filtering

graylog2-server/src/main/java/org/graylog2/security/MongoDBSessionServiceImpl.java, graylog2-server/src/main/java/org/graylog2/security/MongoDbSession.java
Refs #4070
(cherry picked from commit 89cb8660c1f47eab3b2c82c9cc6687fb6b4bc017)
=> Add missing index for "session_id" in "sessions" collection

graylog2-server/src/main/java/org/graylog2/lookup/adapters/DSVHTTPDataAdapter.java
This change is correcting the order of parameters for the `DSVParser` class used by the `DSVHTTPDataAdapter`.
=> Correcting order of constructor parameters for DSVParser.

graylog2-server/src/main/java/org/graylog2/lookup/adapters/CSVFileDataAdapter.java, graylog2-server/src/test/java/org/graylog2/lookup/adapters/CSVFileDataAdapterTest.java, graylog2-server/src/test/resources/org/graylog2/lookup/adapters/CSVFileDataAdapterTest.csv
=> Allow to use the same column for key and value in CSVFileDataAdapter

UPGRADING.rst
The old options got removed and the user has to change her config to the new one.
=> Change wording from "deprecated" to "removed"

graylog2-web-interface/src/components/navigation/Navigation.jsx
=> Fix permission check for System / Authentication menu item

graylog2-web-interface/src/components/field-analyzers/FieldQuickValues.jsx
Fixes #4215 
Note: This needs to be cherry picked into 2.4
=> Always show spinner when loading data from the server

misc/graylog.conf
I realized after questions in the community and training sessions that ppl. tend to change the elasticsearch setting in the configuration file and ask why they are not changed after a restart of graylog. 
My intention here is that ppl can actually read where to find the setting in the web interface. It might be technical not 100% correct (I did not checked that) but it will point the ppl to the point where they can change them in a running Graylog environment.
=> updated default/example graylog.conf

graylog2-web-interface/src/components/field-analyzers/QuickValuesOptionsForm.jsx
Closes #4082
Note: This needs to be merged into 2.4 as well
=> Mention that stacked fields requires Elasticsearch >=5

graylog2-web-interface/package.json, graylog2-web-interface/src/components/loggers/LogLevelDropdown.jsx, graylog2-web-interface/src/components/loggers/LogLevelMetrics.jsx, graylog2-web-interface/src/components/loggers/LoggingSubsystem.jsx, graylog2-web-interface/src/components/metrics/MetricDetails.jsx, graylog2-web-interface/src/components/metrics/MetricsComponent.jsx
We can use Lodash and the native String API for what we use this dependency.
=> Remove string dependency

graylog2-web-interface/src/components/users/__snapshots__/UserPreferencesButton.test.js.snap
Update test snapshot with changes from #4311.
=> Fix JS tests

graylog2-web-interface/src/components/widgets/WidgetVisualizationNotFound.jsx
Also improve the wording a bit.
=> Add onRenderComplete to WidgetVisualizationNotFound

graylog2-web-interface/src/pages/GettingStartedPage.jsx, graylog2-web-interface/src/routing/ApiRoutes.js, graylog2-web-interface/src/routing/App.jsx, graylog2-web-interface/src/routing/AppRouter.jsx, graylog2-web-interface/src/routing/AppWithGlobalNotifications.jsx
Rebase of https://github.com/Graylog2/graylog2-server/pull/4389 against 2.4.
=> Do not show global notifications in 404 page (#4389)

graylog2-web-interface/src/components/cluster/GraylogClusterOverview.jsx
We don't need the incoming and decoded traffic graphs anymore.
=> remove some traffic graphs

.github/no-response.yml
Reverts Graylog2/graylog2-server#4464
=> Revert "Enabling No Response bot for repository."

graylog2-server/src/main/java/org/graylog2/Configuration.java, graylog2-server/src/test/java/org/graylog2/ConfigurationTest.java
=> Propery handle node ID file validation for missing files

pom.xml
Fixes #4232
(cherry picked from commit 4c957a04c678333e09f8c14ba7e25772ecdcf5ab)
=> Upgrade to Jest 2.4.11+jackson (#4400)

UPGRADING.rst
Some information about the big plugin merge.
=> Add plugin merge notes to UPGRADING.rst

graylog2-server/src/main/java/org/graylog2/cluster/NodeImpl.java
=> Fix potential NPE in NodeImpl

graylog2-server/src/main/java/org/graylog2/security/AccessTokenImpl.java, graylog2-server/src/main/java/org/graylog2/security/AccessTokenService.java, graylog2-server/src/main/java/org/graylog2/security/AccessTokenServiceImpl.java, graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java, graylog2-server/src/test/java/org/graylog2/users/UserServiceImplTest.java
Delete all user access tokens when deleting the user
Fixes #4565 
1. Create a user (web interface)
2. Create multiple access tokens for the new user (web interface)
3. Delete the user (web interface)
4. Verify the user and the access tokens are deleted from the mongo db.
=> Remove all access tokens of a user when the user is deleted

graylog2-server/src/main/java/org/graylog2/bindings/PeriodicalBindings.java, graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java, graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java, graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/FieldType.java, graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/FieldTypeDTO.java, graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/FieldTypeLookup.java, graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/FieldTypeMapper.java, graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/FieldTypes.java, graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/FieldTypesModule.java, graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePoller.java, graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodical.java, graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypes.java, graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypesDTO.java, graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypesService.java, graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/MongoFieldTypeLookup.java, graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetConfig.java, graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java, graylog2-server/src/main/java/org/graylog2/indexer/indices/jobs/SetIndexReadOnlyAndCalculateRangeJob.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/requests/IndexSetUpdateRequest.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/responses/IndexSetSummary.java, graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/FieldTypeMapperTest.java, graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerIT.java, graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypesServiceTest.java, graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/MongoFieldTypeLookupTest.java, graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java, graylog2-server/src/test/resources/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerIT.json, graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.jsx, graylog2-web-interface/src/components/indices/IndexSetDetails.jsx, misc/graylog.conf
This PR introduces a system to collect and expose field type information for Elasticsearch indices.
=> Collect and expose index field type information

graylog2-server/src/main/java/org/graylog2/shared/ServerVersion.java
=> Update codename for 3.0.0

graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java, graylog2-server/src/main/java/org/graylog2/commands/journal/AbstractJournalCommand.java, graylog2-server/src/main/java/org/graylog2/commands/journal/JournalShow.java, graylog2-server/src/main/java/org/graylog2/configuration/ExposedConfiguration.java, graylog2-server/src/main/java/org/graylog2/configuration/PathConfiguration.java, graylog2-server/src/main/java/org/graylog2/plugin/BaseConfiguration.java, graylog2-server/src/main/java/org/graylog2/plugin/KafkaJournalConfiguration.java, graylog2-server/src/main/java/org/graylog2/shared/journal/KafkaJournal.java, graylog2-server/src/main/java/org/graylog2/shared/system/stats/fs/JmxFsProbe.java, graylog2-server/src/main/java/org/graylog2/shared/system/stats/fs/SigarFsProbe.java, graylog2-server/src/test/java/org/graylog2/configuration/ExposedConfigurationTest.java, graylog2-server/src/test/java/org/graylog2/shared/journal/KafkaJournalTest.java
* Consolidate naming of configuration settings (all with "_dir" suffix)
* Move path-related settings into `PathConfiguration`
* Consolidate `PluginLoaderConfig` with `PathConfiguration`
* Add new settings to `ExposedConfiguration`
* Add new settings to `JmxFsProbe` and `SigarFsProbe`
=> Change proposals for #4657

graylog2-web-interface/src/components/common/Wizard.css, graylog2-web-interface/src/components/common/Wizard.jsx, graylog2-web-interface/src/components/common/Wizard.md, graylog2-web-interface/src/components/common/Wizard.test.jsx, graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap, graylog2-web-interface/src/components/common/index.jsx
Add new wizard component which will allow a step by step
configuration.
For some more complex configurations it is easier for a user to have a step by step
guide through the configuration. This component should help the developer to create
such a step by step configuration
Add a test which covers all functionallity
=> Add new Wizard Component to common

graylog2-web-interface/src/components/dashboard/DashboardList.jsx, graylog2-web-interface/src/components/dashboard/DashboardListPage.jsx
Remove unused prop from `DashboardList`, alongside with the non-existing method we were passing to it.
=> Clean-up DashboardList

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/RegexReplace.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/regexReplace.txt
Fixes Graylog2/graylog-plugin-pipeline-processor#171
=> Add `regex_replace()` function to replace parts of strings backed by regular expressions

graylog2-web-interface/src/components/search/SearchBar.jsx
Cherry pick of https://github.com/Graylog2/graylog2-server/pull/4743 for 3.0.
Fixes #2285
=> Maintaining saved search id across search execution

graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java, graylog2-server/src/main/java/org/graylog2/bindings/providers/DefaultStreamProvider.java, graylog2-server/src/main/java/org/graylog2/streams/DefaultStreamChangeHandler.java, graylog2-server/src/main/java/org/graylog2/streams/StreamServiceImpl.java, graylog2-server/src/test/java/org/graylog2/streams/StreamServiceImplTest.java
2.4 backport of https://github.com/Graylog2/graylog2-server/pull/4752
=> Make sure to reload the default stream if it has been changed 2.4 backport

graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/OkHttpClientProvider.java, graylog2-server/src/test/java/org/graylog2/shared/bindings/providers/OkHttpClientProviderTest.java, misc/graylog.conf
Fixes #4594
Refs #4750
(cherry picked from commit eec520f92acfe69ed6bc86b1bb259bfe07cc59de)
=> Implement HTTP proxy server authentication in OkHttpClientProvider

graylog2-server/src/main/java/org/graylog2/audit/AuditEventTypes.java, graylog2-server/src/main/java/org/graylog2/grok/GrokPatternService.java, graylog2-server/src/main/java/org/graylog2/grok/InMemoryGrokPatternService.java, graylog2-server/src/main/java/org/graylog2/grok/MongoDbGrokPatternService.java, graylog2-server/src/main/java/org/graylog2/rest/models/system/grokpattern/requests/GrokPatternTestRequest.java, graylog2-server/src/main/java/org/graylog2/rest/models/system/responses/GrokPatternList.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/GrokResource.java, graylog2-server/src/test/java/org/graylog2/grok/InMemoryGrokPatternServiceTest.java, graylog2-server/src/test/java/org/graylog2/rest/resources/system/GrokResourceTest.java, graylog2-web-interface/src/components/grok-patterns/EditPatternModal.jsx, graylog2-web-interface/src/components/grok-patterns/EditPatternModal.test.jsx, graylog2-web-interface/src/components/grok-patterns/GrokPatterns.jsx, graylog2-web-interface/src/components/grok-patterns/__snapshots__/EditPatternModal.test.jsx.snap, graylog2-web-interface/src/routing/ApiRoutes.js, graylog2-web-interface/src/stores/grok-patterns/GrokPatternsStore.ts
Add helpful error messages and add a test grok pattern button.
Creating or editing grok patterns was hard for a unknowleged user.
The form did not have help text and you could not test your grok patterns.
Provieded wrong or broken grok patterns and saw the errors.
Add sample data and tested grok patterns with it.
Fixes: #4548
=> Grok editor

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/Replace.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/strings.txt
Closes #4705
Refs Graylog2/graylog-plugin-pipeline-processor#171
=> Add `replace()` function to replace occurrences of a string

pom.xml
Fixes #4804
Refs #4805
Refs searchbox-io/Jest#592
Refs graylog-labs/Jest@55ad3d51b7a4a73e6fa7c46e1957565e63bc423e
(cherry picked from commit 11cad1fad3e7b144bbd091bdc59c1bfd1a1fd1c7)
=> Upgrade to Jest 2.4.13+jackson

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/urls/UrlDecode.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/urls/UrlEncode.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/urls.txt
=> Add URL encode/decode functions `urlencode()` and `urldecode()`

graylog2-server/pom.xml, graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java, graylog2-server/src/main/java/org/graylog2/plugin/rest/ApiError.java, graylog2-server/src/main/java/org/graylog2/plugin/rest/DetailedError.java, graylog2-server/src/main/java/org/graylog2/plugin/rest/GenericError.java, graylog2-server/src/main/java/org/graylog2/plugin/rest/ValidationApiError.java, graylog2-server/src/main/java/org/graylog2/rest/GenericErrorCsvWriter.java, graylog2-server/src/main/java/org/graylog2/rest/NotFoundExceptionMapper.java, graylog2-server/src/main/java/org/graylog2/rest/QueryParsingExceptionMapper.java, graylog2-server/src/main/java/org/graylog2/rest/ScrollChunkWriter.java, graylog2-server/src/main/java/org/graylog2/rest/ValidationExceptionMapper.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/responses/QueryParseError.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/responses/SearchError.java, graylog2-server/src/main/java/org/graylog2/shared/rest/exceptionmappers/AnyExceptionClassMapper.java, graylog2-server/src/main/java/org/graylog2/shared/rest/exceptionmappers/BadRequestExceptionMapper.java, graylog2-server/src/main/java/org/graylog2/shared/rest/exceptionmappers/JacksonPropertyExceptionMapper.java, graylog2-server/src/main/java/org/graylog2/shared/rest/exceptionmappers/JsonProcessingExceptionMapper.java, graylog2-server/src/main/java/org/graylog2/shared/rest/exceptionmappers/WebApplicationExceptionMapper.java, graylog2-server/src/test/java/org/graylog2/plugin/rest/exceptionmappers/JsonProcessingExceptionMapperTest.java, graylog2-server/src/test/java/org/graylog2/rest/GenericErrorCsvWriterTest.java, graylog2-server/src/test/java/org/graylog2/rest/ValidationExceptionMapperTest.java
=> Add body writer for serializing errors (GenericError et al) as CSV

graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/InputsResource.java
Before this change it was possible to terminate any input for every
authenticated user. This change introduces a check for the
`inputs:terminate:<input id>` permission before terminating an input.
Might be backported to `2.4`.
Fixes #4858.
=> Check for permission before terminating input.

graylog2-server/src/main/java/org/graylog2/rest/resources/system/logs/LoggersResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/tools/LookupTableTesterResource.java, graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java
* Add missing LOOKUP_TABLES_READ permission check
Fixes #4861
* Check permissions for recent log messages API endpoint
Fixes #4859
=> Add missing permission checks

graylog2-web-interface/src/components/common/TypeAheadInput.jsx, graylog2-web-interface/src/components/search/QueryInput.ts
Escape content of templates used to draw Typeahead suggestions.
=> Escape typeahead templates content

graylog2-web-interface/src/stores/lookup-tables/LookupTableDataAdaptersStore.js, graylog2-web-interface/src/stores/lookup-tables/LookupTablesStore.js
Fixes #4816 
Created a csv file like in the issue description, and verified with the new code the query string params are URI encoded.
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the code style of this project.
- [x ] I have read the **CONTRIBUTING** document.
- [x ] All new and existing tests passed.
=> Encode URI query string params in DataAdapters query

graylog2-web-interface/src/components/content-packs/ContentPackConstraints.jsx, graylog2-web-interface/src/pages/ConfigurationsPage.jsx
This removes two stray `console.log` lines in the UI code.
=> Remove debug console.log

graylog2-web-interface/src/components/common/DataTable.jsx, graylog2-web-interface/src/components/common/DataTable.md
This is useful if you need to sort on a nested property in an object.
Example:
```js
<DataTable sortBy={entity => entity.type.name} ... />
```
=> Add sortBy function prop to DataTable

graylog2-server/src/main/java/org/graylog2/contentpacks/facades/CollectorConfigurationFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/CollectorFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/DashboardFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/GrokPatternFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/InputFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupCacheFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupDataAdapterFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/LookupTableFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/OutputFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/PipelineFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/PipelineRuleFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/StreamFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/NativeEntity.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/NativeEntityDescriptor.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/CollectorFacadeTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/DashboardFacadeTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/GrokPatternFacadeTest.java, graylog2-server/src/test/resources/org/graylog2/contentpacks/ContentPackInstallationPersistenceServiceTest.json
Add the origin entity id to the installation model. 
With that the installed entity has a relation with the entity from which it was created from the
content pack.
Installed a new content pack and took a look in the database.
=> Add entityId to NativeEntityDescriptor

graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180323150000_AddSidecarUser.java, graylog2-server/src/main/java/org/graylog2/migrations/MigrationHelpers.java
In existing migrations, a pattern of checking for the existence of users
and roles, creating them if nonexistent was repeatedly used by copying
the identical code. This change is consolidating these helper functions
to make them usable for all migrations.
=> Consolidate migration helpers to ensure existence of users and roles.

graylog2-web-interface/src/components/sidecars/sidecars/SidecarStatus.jsx
=> Use IDs as keys to render all collector status

graylog2-web-interface/src/actions/sidecars/SidecarsAdministrationActions.js, graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministrationContainer.jsx, graylog2-web-interface/src/components/sidecars/common/StatusIndicator.jsx, graylog2-web-interface/src/components/sidecars/sidecars/SidecarStatus.jsx, graylog2-web-interface/src/stores/sidecars/SidecarsAdministrationStore.js
Currently a stopped collector is not shown in the web UI. This PR adds the stopped state.
=> Add Sidecar stopped state

graylog2-web-interface/src/components/common/Select.jsx, graylog2-web-interface/src/logic/alerts/AlertsAnnotator.js
Some changes necessary to test MessageList in enterprise plugin:
- use 'import' for css
- remove unused Store
To test MessageList in enterprise-plugin, there a small changes necessary to
make it easier.
=> Changes to test MessageList

graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.jsx
This PR fixes a few issues we had in the Collector Configuration form:
- Validate that the configuration template is set
- Fix setting default configuration template
- Ask user before resetting the configuration template, after the selected collector changes
=> Collector Configuration form improvements

graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupResult.java
=> Add comment explaining what the LookupResult.ttl field is for

graylog2-server/src/main/java/org/graylog2/audit/AuditEventTypes.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/contentpacks/ContentPackResource.java
Remove auditlog events of content packs which are no longer needed.
With the new content packs some actions are not used any longer.
=> Remove unused content pack auditlog events

graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPacksModule.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorConfigurationFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/SidecarCollectorFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/ModelTypes.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/SidecarCollectorConfigurationEntity.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/SidecarCollectorEntity.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/SidecarCollectorFacadeTest.java
Collector was renamed to SidecarCollector. 
To make it easier
to find relating code the corresponding content pack code
was renamed as well.
Created, edited and deleted a content pack with collectors.
=> Rename Collector*Entity and *Facade to SidecarColloector

graylog2-web-interface/src/components/sidecars/configuration-forms/CollectorForm.jsx, graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.jsx, graylog2-web-interface/src/components/sidecars/configuration-forms/SourceViewModal.jsx
=> Enable collector template preview on new configurations

graylog2-web-interface/webpack/UniqueChunkIdPlugin.js, graylog2-web-interface/webpack/UniqueChunkIdPlugin.test.js, graylog2-web-interface/webpack/__snapshots__/UniqueChunkIdPlugin.test.js.snap
This is a follow-up to #5127, adding the missing tests.
=> Add missing tests for UniqueChunkIdPlugin.

graylog2-server/src/main/java/org/graylog2/plugin/rest/ApiError.java, graylog2-server/src/main/java/org/graylog2/plugin/rest/DetailedError.java, graylog2-server/src/main/java/org/graylog2/plugin/rest/ValidationApiError.java
=> Remove "AutoValue_" prefix from API error JSON

graylog2-web-interface/styleguide.config.js
=> Manually add store injection to UI documentation

graylog2-web-interface/package.json, graylog2-web-interface/packages/graylog-web-plugin/package.json, graylog2-web-interface/packages/graylog-web-plugin/yarn.lock, graylog2-web-interface/webpack/vendor-module-ids.json, graylog2-web-interface/yarn.lock
This change is upgrading the dependencies to:
* webpack 4.19.1: [CHANGELOG](https://github.com/webpack/webpack/releases)
* webpack-dev-middleware 3.3.0: [CHANGELOG](https://github.com/webpack/webpack-dev-middleware/blob/master/CHANGELOG.md)
* webpack-dev-server 3.1.8: [CHANGELOG](https://github.com/webpack/webpack-dev-server/blob/master/CHANGELOG.md)
* webpack-hot-middleware 2.24.0
* webpack-merge 4.1.4: [CHANGELOG](https://github.com/survivejs/webpack-merge/blob/master/CHANGELOG.md)
* uglifyjs-webpack-plugin to 2.0.0: [CHANGELOG](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/CHANGELOG.md)
=> Updating dependencies to webpack 4.19.1.

graylog2-web-interface/src/components/navigation/Navigation.jsx, graylog2-web-interface/src/components/navigation/NotificationBadge.jsx, graylog2-web-interface/src/components/navigation/NotificationBadge.test.jsx, graylog2-web-interface/src/components/navigation/__snapshots__/NotificationBadge.test.jsx.snap
Currently, checking for notifications updates the whole navigation bar
periodically.
This change extracts the notification badge into an own component,
isolates updating it and prevents unnecessary updates if the number of
notifications has not changed.
=> Isolate notification badge updates.

graylog2-server/pom.xml, graylog2-server/src/main/java/org/graylog2/lookup/LookupModule.java, graylog2-server/src/main/java/org/graylog2/lookup/adapters/DnsLookupDataAdapter.java, graylog2-server/src/main/java/org/graylog2/lookup/adapters/dnslookup/ADnsAnswer.java, graylog2-server/src/main/java/org/graylog2/lookup/adapters/dnslookup/DnsAnswer.java, graylog2-server/src/main/java/org/graylog2/lookup/adapters/dnslookup/DnsClient.java, graylog2-server/src/main/java/org/graylog2/lookup/adapters/dnslookup/DnsClientNotRunningException.java, graylog2-server/src/main/java/org/graylog2/lookup/adapters/dnslookup/DnsLookupType.java, graylog2-server/src/main/java/org/graylog2/lookup/adapters/dnslookup/PtrDnsAnswer.java, graylog2-server/src/main/java/org/graylog2/lookup/adapters/dnslookup/TxtDnsAnswer.java, graylog2-server/src/test/java/org/graylog2/lookup/adapters/dnslookup/DnsClientTest.java, graylog2-web-interface/src/components/lookup-tables/adapters/DnsAdapterDocumentation.jsx, graylog2-web-interface/src/components/lookup-tables/adapters/DnsAdapterFieldSet.jsx, graylog2-web-interface/src/components/lookup-tables/adapters/DnsAdapterSummary.jsx, graylog2-web-interface/src/components/lookup-tables/adapters/index.js
Add DNS Lookup adaptor to graylog2-server repository.
=> Add DNS Lookup adaptor to graylog2-server repository

graylog2-web-interface/src/components/sidecars/configuration-forms/IncludesHelper.jsx
After changes in store to add pagination support, the component was not storing the information it needed to render.
Fixes #5101
=> Fix configurations load in includes helper

pom.xml
This change is bumping the `node` version used to build our web assets to the most recent LTS one, the `yarn` version to the most recent stable one.
Changelogs:
* `node`: [v8.12.0](https://github.com/nodejs/node/blob/v8.12.0/doc/changelogs/CHANGELOG_V8.md)
* `yarn`: [v1.10.1](
https://github.com/yarnpkg/yarn/releases/tag/v1.10.1)
=> Bumping node version to current LTS, yarn to most recent stable.

graylog2-web-interface/yarn.lock
With yarn upgrade the `integrity` attribute was add to `yarn.lock`.  This PR add the missing attributes.
=> Add changes to yarn.lock which happend with yarn upgrade

graylog2-server/src/test/resources/org/graylog2/contentpacks/ContentPackInstallationPersistenceServiceTest.json
Broken tests have been introduced in https://github.com/Graylog2/graylog2-server/pull/5141.
=> Fix failing content pack tests

graylog2-server/src/main/java/org/graylog2/streams/OutputServiceImpl.java, graylog2-server/src/test/java/org/graylog2/streams/OutputServiceImplTest.java, graylog2-server/src/test/resources/org/graylog2/streams/single-output.json
Before this change, due to a mistake in a former PR (#4753), updating an
output was using the wrong field to find the corresponding document to
be modified. This lead to a successfull request, but no changes were
done in the database.
This was fixed and the old behavior was restored. Additionally, instead
of returning the old object from the database and back to the API, the
new, modified one is returned and upserting is explicitly disabled.
=> Fixing editing outputs from web and REST API.

graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackInstallationPersistenceService.java, graylog2-server/src/main/java/org/graylog2/rest/models/system/contenpacks/responses/ContentPackList.java, graylog2-server/src/main/java/org/graylog2/rest/models/system/contenpacks/responses/ContentPackMetaData.java, graylog2-server/src/main/java/org/graylog2/rest/models/system/contenpacks/responses/ContentPackMetadata.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/contentpacks/ContentPackResource.java, graylog2-server/src/test/java/org/graylog2/rest/resources/system/contentpacks/ContentPackResourceTest.java, graylog2-web-interface/src/components/content-packs/ContentPackDetails.jsx, graylog2-web-interface/src/components/content-packs/ContentPackDetails.test.jsx, graylog2-web-interface/src/components/content-packs/ContentPackParameterList.jsx, graylog2-web-interface/src/components/content-packs/ContentPackPreview.jsx, graylog2-web-interface/src/components/content-packs/ContentPackStatus.jsx, graylog2-web-interface/src/components/content-packs/ContentPacksList.jsx, graylog2-web-interface/src/components/content-packs/ContentPacksList.test.jsx, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackDetails.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameterList.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameters.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackPreview.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap, graylog2-web-interface/src/pages/ContentPacksPage.jsx, graylog2-web-interface/src/stores/content-packs/ContentPacksStore.jsx
* Fix inconsistent button size. (Fixes #5188)
* Add a "Create and Download" Button (Fixes #5189)
* Hide description well when no description was entered (Fixes #5186)
* Show Intalled badge in content pack list (Fixes #5191)
=> Small fixes to content packs regarding UX

graylog2-web-interface/webpack/vendor-module-ids.json
=> Update vendor-module-ids after latest upgrades

graylog2-server/src/main/java/org/graylog2/indexer/indices/stats/IndexStatistics.java
Use the correct fields for indexing and merges.
**Attention:** This needs to be cherry-picked into 2.5 once merged.
=> Fix index stats collection

graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
In the previous attempt to fix the "show collector messages" button,
I got confused with the names and swapped them.
=> Fix gl2_source_collector field for default collector

graylog2-server/src/main/java/org/graylog2/indexer/indices/stats/IndexStatistics.java
Use the correct fields for indexing and merges.
(cherry picked from commit 229b11edc8350ff899d64cd9ee29ad20682e7f58)
=> Fix index stats collection (#5226)

graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
Prevent user details data leak by restricting user details endpoints to the user itself and the administrators
Fixes #5068 
Using an administrator credentials query any user endpoint /api/users/{username} and get the user details back.
Using a regular user query any other user (included admins) endpoints and get a forbidden error.
=> Limit user details to self and admins in API

graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
Fixes #5068
(cherry picked from commit 6d80b741d0bf9b42562f30c5dcaabc344641c60a)
=> Limit user details to self and admins in API (#5079)

graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
After #5079, only the system admin user was allowed to see all user
details.
This change also allows other admin users to do the same, while still
blocking regular users to see anything but their own user details.
I tested this change in the following scenarios:
- Reader user cannot see another user details
- Reader user can see its own details
- Admin user can see another user details
- Admin user can see system admin details
- System admin can see another user details
Fixes #5325.
This needs to be cherry-picked into 2.5.
=> Add permissions to all admins to see user details

pom.xml
=> Update to jest-2.4.15+jackson to fix an issue with field terms

graylog2-web-interface/src/components/common/SourceCodeEditor.jsx
Number.isNan(Infinity) is false. Compare against Infinity instead.
=> Fix react CSS warning

graylog2-web-interface/src/components/content-packs/ContentPackDetails.test.jsx, graylog2-web-interface/src/components/content-packs/ContentPackEdit.jsx, graylog2-web-interface/src/components/content-packs/ContentPackEdit.test.jsx, graylog2-web-interface/src/components/content-packs/ContentPackEntitiesList.test.jsx, graylog2-web-interface/src/components/content-packs/ContentPackInstall.test.jsx, graylog2-web-interface/src/components/content-packs/ContentPackParameterList.test.jsx, graylog2-web-interface/src/components/content-packs/ContentPackParameters.jsx, graylog2-web-interface/src/components/content-packs/ContentPackPreview.jsx, graylog2-web-interface/src/components/content-packs/ContentPackPreview.test.jsx, graylog2-web-interface/src/components/content-packs/ContentPackSelection.jsx, graylog2-web-interface/src/components/content-packs/ContentPackSelection.test.jsx, graylog2-web-interface/src/components/content-packs/ContentPackVersions.jsx, graylog2-web-interface/src/components/content-packs/ContentPackVersions.test.jsx, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackDetails.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackPreview.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackVersions.test.jsx.snap, graylog2-web-interface/src/logic/content-packs/ContentPack.js, graylog2-web-interface/src/logic/content-packs/ContentPack.test.js, graylog2-web-interface/src/logic/content-packs/ContentPackRevisions.js, graylog2-web-interface/src/logic/content-packs/ContentPackRevisions.jsx, graylog2-web-interface/src/pages/CreateContentPackPage.jsx, graylog2-web-interface/src/pages/EditContentPackPage.jsx, graylog2-web-interface/src/pages/ShowContentPackPage.jsx, graylog2-web-interface/src/stores/content-packs/ContentPacksStore.jsx
Replace the big content pack hash with a value class.
Value classes help to ensure default values, encapsulate accessors and help find bugs while writing code.
Clicked (hopefully) through all scenarios.
=> Create value classes for Content Packs

graylog2-web-interface/src/components/search/MalformedSearchQuery.jsx
The response body contains no further error details in this case.
Fixes #5350
=> Fix search query error with invalid time keyword query

graylog2-server/src/main/java/org/graylog2/contentpacks/facades/InputFacade.java, graylog2-server/src/main/java/org/graylog2/inputs/extractors/LookupTableExtractor.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/InputFacadeTest.java, graylog2-server/src/test/resources/org/graylog2/contentpacks/inputs.json
Add `resolveNatvieEntity` and `resolveForInstallation` to InputFacade
The Input has a dependency to LookupTables via Extractors.  
Fixes #5105 
Created, installed and uninstalled a content pack with a Input with a lookup table.
=> Add dependency resolution to InputFacade

graylog2-server/src/main/java/org/graylog2/audit/AuditEventTypes.java, graylog2-server/src/main/java/org/graylog2/bindings/providers/JestClientProvider.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping6.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexMappingFactory.java, graylog2-server/src/main/java/org/graylog2/indexer/cluster/jest/RequestResponseLogger.java, graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java, graylog2-server/src/main/java/org/graylog2/migrations/V20170607164210_MigrateReopenedIndicesToAliases.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexTemplatesResource.java, graylog2-server/src/test/java/org/graylog2/indexer/IndexMappingFactoryTest.java, pom.xml
=> Port ES 6 support from 2.5 branch

graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackService.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/GrokPatternFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/InputFacade.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/GrokPatternEntity.java, graylog2-server/src/main/resources/org/graylog2/migrations/V20180924111644_AddDefaultGrokPatterns_Default_Grok_Patterns.json, graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackServiceTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/GrokPatternFacadeTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/InputFacadeTest.java
I also changed the following:
- Formatted the default grok pattern content pack JSON file
- Fixed a small issue with opening legacy content packs
Fixes #5220
=>  Remove possibility to use parameters for name/pattern in GrokPatternEntity

graylog2-server/src/test/java/org/graylog2/rest/resources/system/contentpacks/CatalogResourceTest.java
=> Fix CatalogResourceTest#resolveEntities test

graylog2-server/src/main/java/org/graylog2/contentpacks/facades/StreamFacade.java
Alert conditions an be plugins so we need to check for constraints.
=> Include alert condition constraints in stream facade

graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministration.jsx
Link from the configuration label to the configuration edit page
=> Improve Sidecar administration view

graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministration.jsx
Link from the configuration label to the configuration edit page
(cherry picked from commit 0fb0b2ee3de22a1258abe5787e19e79bc9e84eff)
=> Improve Sidecar administration view (#5457)

graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
We don't ship filebeat in the linux sidecar packages anymore.
Adopt the path to the elastic beats package.
(cherry picked from commit fd481b4e75e405a809f36f2a303482c11baa0560)
=> Change default linux filebeat path

graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministrationFilters.jsx, graylog2-web-interface/src/logic/sidecar/SidecarStatusEnum.js
- Use the updated values in the status filter
- Convert string to number before comparing status
Fixes #5471
=> Fix collector status filter in admin page

graylog2-web-interface/src/components/content-packs/ContentPackVersions.jsx, graylog2-web-interface/src/components/content-packs/ContentPacksList.jsx, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackVersions.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
Prior to this change, the delete action was prior the
create new version and install after create new version.
This change will change the order of drop downs to:
- Show
- Install
- Create New Verison
- Divider
- Delete
Fixes: #5239
=> Change order of drop down menues

pom.xml
Changelog: https://netty.io/news/2019/01/21/4-1-33-Final.html
(cherry picked from commit e917996e4d6d46722b6632387b97697bfaf98961)
=> Bug fix update to netty 4.1.33 (#5569)

graylog2-server/src/main/java/org/graylog/plugins/sidecar/permissions/SidecarRestPermissions.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/AdministrationResource.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/CollectorResource.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/ConfigurationResource.java
Fixes some typos in REST permissions.
Fixes #5211
=> Fix Sidecar REST permissions

graylog2-server/src/main/java/org/graylog/plugins/sidecar/permissions/SidecarRestPermissions.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/AdministrationResource.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/CollectorResource.java, graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/ConfigurationResource.java
* Fix typos
* Fix rest permissions
* Rename permissions to prevent name collision with old collector plugin
* Fix more REST permissions
(cherry picked from commit 022dca4d4afebd597599a27c0bccab25f8076e49)
Backport of #5604
=> Fix Sidecar REST permissions (#5604)

graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/ConfigurationService.java, graylog2-web-interface/src/components/sidecars/configuration-forms/TemplatesHelper.jsx
Fixes https://github.com/Graylog2/collector-sidecar/issues/338#event-2115417218
=> Remove unused template variables

misc/graylog.conf
=> must me > must be

misc/graylog.conf
Refs #5680
(cherry picked from commit 0e013b8991ce3c93d08cd42e1622efa683f41d6d)
=> Add comment about MongoDB username/password escaping (#5764)

graylog2-server/src/main/java/org/graylog2/contentpacks/facades/OutputFacade.java, graylog2-server/src/main/java/org/graylog2/initializers/OutputSetupService.java, graylog2-server/src/main/java/org/graylog2/outputs/MessageOutputFactory.java, graylog2-server/src/main/java/org/graylog2/plugin/GlobalMetricNames.java, graylog2-server/src/main/java/org/graylog2/plugin/PluginModule.java, graylog2-server/src/main/java/org/graylog2/plugin/inject/Graylog2Module.java, graylog2-server/src/main/java/org/graylog2/plugin/outputs/MessageOutput.java, graylog2-server/src/main/java/org/graylog2/shared/journal/KafkaJournal.java, graylog2-server/src/test/java/org/graylog2/contentpacks/ContentPackServiceTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/OutputFacadeTest.java, graylog2-server/src/test/java/org/graylog2/outputs/MessageOutputFactoryTest.java, graylog2-server/src/test/java/org/graylog2/shared/journal/KafkaJournalTest.java
Backport of #5670 
Needed for checks in https://github.com/Graylog2/graylog-plugin-enterprise-integrations/pull/56 to pass.
=> Forwarder server changes (backport)

graylog2-web-interface/checkProductionBuild.js, graylog2-web-interface/package.json
In #5853 the default location for web assets was changed. Unfortunately,
#5894 was merged before the required changes to adapt to this were
incorporated.
This PR is changing the default build directory from `build` to
`target/web/build`.
=> Changing default build directory for production web asset health check.

graylog2-server/src/main/java/org/graylog2/migrations/V20180924111644_AddDefaultGrokPatterns.java
Prior to this change, when a user had modfied the a default
grok pattern, the installation would fail. With a cryptic
error message.
This change catches the error and prints a hopefully more useful
error message.
Also: do not use `new Error` which is not catched.
Also: we will write the clusterConfig to avoid running into a already found content pack after every restart.
Fixes #5626 
- Removed Content Pack Installation
- Removed Content Pack
- Removed corresponding cluster config
- Edited one default grok pattern
- Restarted server and looked for the warning message
=> Give useful message on default grok patterns fail

graylog2-web-interface/src/components/lookup-tables/adapters/DnsAdapterFieldSet.jsx
=> Fixed typo in DnsAdapterFieldSet UI

graylog2-server/src/main/java/org/graylog2/rest/models/system/indexer/responses/ShardRouting.java
Remove unused import as noticed in https://github.com/Graylog2/documentation/issues/391#issuecomment-495540592
=> Remove unused import

graylog2-web-interface/public/stylesheets/bootstrap-config.json, graylog2-web-interface/public/stylesheets/graylog2.less, graylog2-web-interface/src/components/navigation/HelpMenu.jsx, graylog2-web-interface/src/components/navigation/Navigation.css, graylog2-web-interface/src/components/navigation/Navigation.jsx, graylog2-web-interface/src/components/navigation/UserMenu.jsx, graylog2-web-interface/src/components/throughput/GlobalThroughput.css, graylog2-web-interface/src/components/throughput/GlobalThroughput.jsx, graylog2-web-interface/src/stores/metrics/GlobalThroughputStore.js
Closes #5851 
Tested in all latest browsers Chrome, Firefox, Safari, and MS Edge
=> Fixing Multiple Navigation Concerns

graylog-project-parent/pom.xml, graylog2-server/pom.xml, pom.xml
Due to the impending views integration into core, this PR is already merging missing required Maven dependencies, namely jdot & streamex.
=> Merging jdot & streamex dependencies required by views into core.

README.markdown
=> Add job opening text

graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java, graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetConfig.java, graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java, graylog2-server/src/main/java/org/graylog2/migrations/V20190705071400_AddEventIndexSetsMigration.java, graylog2-server/src/main/java/org/graylog2/plugin/streams/Stream.java
This adds:
- Default events stream + index set
- Default system events stream + index -set
Closes #6085
=> Add migration to create events and system-events index sets and streams

graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotifications.jsx, graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotificationsContainer.jsx, graylog2-web-interface/src/stores/event-definitions/EventDefinitionsStore.js, graylog2-web-interface/src/stores/event-notifications/EventNotificationsStore.js
This PR adds inputs to support the newly introduced filter in Event Notifications.
=> Add UI for Event Notifications filter

graylog2-web-interface/src/stores/event-definitions/EventDefinitionsStore.js
Only merge after the events change got merged!
=> Change path in EventDefinitionsStore

graylog2-web-interface/src/views/components/SearchResult.jsx, graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx
Before this change, remainders of the static message table
(`showMessages` & `onToggleMessages`) were instantiated in
`ExtendedSearchPage` and passed down. Those were used nowhere, so this
PR removes them, fixes linter hints and turns `SearchResult` into a
functional component.
=> Removing static message table artifacts.

graylog2-web-interface/src/components/common/TimeUnitInput.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionSummary.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationList.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationSettingsForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.css, graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.jsx, graylog2-web-interface/src/stores/event-definitions/EventDefinitionsStore.js
Adds components to set and display the grace period parameter in the Event Definition Form.
Implements #6081.
=> Event grace period UI

graylog-project-parent/pom.xml, graylog2-server/pom.xml, graylog2-server/src/main/java/org/graylog2/plugin/Message.java, graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java, pom.xml
See Message.FIELD_GL2_MESSAGE_ID documentation and the referenced issue
for more details.
Closes #5994
=> Generate a value for the "gl2_message_id" field for each new message

graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationForm.jsx
In the form to configure a Filter & Aggregation Event Definition, we need to update the configuration when the type changes from "Aggregation" to "Filter", to ensure the aggregation options are deleted from the Event Definition configuration.
This PR additionally stores the previous Aggregation configuration temporarily in the state, allowing users to recover the options if they changed the type accidentally.
=> Reset Event Definition configuration when type changes

graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationForm.jsx
This adds sender, subject and body template.
=> Add more configuration options to email notification form

graylog2-server/src/main/java/org/graylog2/shared/ServerVersion.java
Update release code name for 3.1. Welcome Quantum Dog!
=> Update code name for 3.1

graylog2-web-interface/src/components/bootstrap/BootstrapModalWrapper.jsx, graylog2-web-interface/src/components/users/__snapshots__/UserPreferencesButton.test.jsx.snap
* Set Modals to only close with ESC key or Cancel & X buttons
* Update snapshot
(cherry picked from commit 3a6bf9f52154af3455c28e3195b75c606ecc1c1d)
=> Set Modals to only close with ESC key or Cancel & X buttons (#5823)

graylog2-web-interface/src/components/inputs/CreateInputControl.jsx
Check for `inputConfiguration` in the PluginStore to provide a unique Input experience for specific pluggable integrations.
Related PR: https://github.com/Graylog2/graylog-plugin-integrations/pull/142
Allows us to provide a unique experience for specific Inputs
=> Check for Plugin inputConfiguration before opening Inputs modal

graylog2-web-interface/src/components/common/ConfirmLeaveDialog.jsx
=> Adding styleguidist comments to ConfirmLeaveDialog

graylog2-web-interface/src/actions/event-notifications/EventNotificationsActions.js, graylog2-web-interface/src/components/configurationforms/ConfigurationForm.jsx, graylog2-web-interface/src/components/configurationforms/ConfigurationFormField.jsx, graylog2-web-interface/src/components/configurationforms/index.jsx, graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationForm.css, graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationForm.jsx, graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationFormContainer.jsx, graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationSummary.jsx, graylog2-web-interface/src/components/event-notifications/event-notification-types/LegacyNotificationSummaryContainer.jsx, graylog2-web-interface/src/components/event-notifications/event-notification-types/index.js, graylog2-web-interface/src/stores/event-notifications/EventNotificationsStore.js
This adds the required UI components to manage legacy alarm callbacks in the new notification system.
Refs #5878
=> Add UI for legacy notification support

graylog2-web-interface/src/components/throughput/GlobalThroughput.css, graylog2-web-interface/src/components/throughput/GlobalThroughput.jsx
Adding "in" and "out" prefixes to header throughput component to add some context to the what the values represent
@mehrenreich requested a little more context to the Header Throughput component
=> Header throughput value context

graylog2-server/src/main/java/org/graylog2/system/processing/MongoDBProcessingStatusRecorderService.java
Don't try to persist the processing statusldata when the server is
shutting down. This avoids sporadic MongoDB driver exceptions when the
service tries to persist the data while the DB driver is shutting down.
The service now also subscribes to the event bus to get the shutdown
signal as early as possible.
=> Improve shutdown handling of processing status recorder

pom.xml
Changes:
- https://netty.io/news/2019/06/28/4-1-37-Final.html
- https://netty.io/news/2019/07/24/4-1-38-Final.html
=> Update netty to 4.1.38

graylog2-server/src/main/java/org/graylog2/database/PaginatedDbService.java
`findPaginatedWithQueryAndSort` used MongoDBs `limit` function,
which treats `limit(0)` as unlimited.
Change the stream filter to do the same.
=> Change findPaginatedWithQueryFilterAndSort limit semantics

graylog2-server/src/main/java/org/graylog/events/configuration/EventsConfiguration.java, graylog2-server/src/main/java/org/graylog/events/configuration/EventsConfigurationProvider.java, graylog2-server/src/main/java/org/graylog/events/notifications/EventNotificationExecutionJob.java, graylog2-server/src/main/java/org/graylog/events/notifications/EventNotificationService.java, graylog2-server/src/main/java/org/graylog/events/processor/aggregation/PivotAggregationSearch.java, graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java, graylog2-server/src/main/java/org/graylog2/migrations/V20190730000000_CreateDefaultEventsConfiguration.java, graylog2-server/src/test/java/org/graylog/events/EventsConfigurationTestProvider.java, graylog2-server/src/test/java/org/graylog/events/processor/aggregation/PivotAggregationSearchTest.java, graylog2-web-interface/src/actions/configurations/ConfigurationActions.js, graylog2-web-interface/src/components/configurations/EventsConfig.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationSettingsForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.jsx, graylog2-web-interface/src/pages/ConfigurationsPage.jsx, graylog2-web-interface/src/stores/configurations/ConfigurationsStore.js
Adds system configurations for the Events module. The three options are:
Search Timeout: ES queries should be interrupted at some point
Notification retry period: In case of an error notifications are retried
Notification default backlog size: The default value for backlogs in notifications is used as a fallback in case of a configuration error as well as the default value for new event definitions
Closes https://github.com/Graylog2/graylog-plugin-enterprise/issues/1063
=> Events system configuration

graylog2-server/src/main/java/org/graylog/events/processor/EventDefinition.java, graylog2-server/src/main/java/org/graylog/events/processor/EventProcessorConfig.java, graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessorConfig.java, graylog2-server/src/main/java/org/graylog/events/rest/EventDefinitionsResource.java, graylog2-server/src/test/java/org/graylog/events/processor/aggregation/AggregationEventProcessorConfigTest.java, graylog2-server/src/test/resources/org/graylog/events/processor/aggregation/aggregation-processors.json
Without this, any use with event definition create permission could
configure alerts for any stream.
=> Check stream permissions in aggregation event definition

graylog2-web-interface/src/pages/EditEventDefinitionPage.jsx, graylog2-web-interface/src/pages/EditEventNotificationPage.jsx, graylog2-web-interface/src/stores/event-definitions/EventDefinitionsStore.js, graylog2-web-interface/src/stores/event-notifications/EventNotificationsStore.js
=> Handle 404s in Event Definitions and Notifications

graylog2-server/src/main/java/org/graylog/events/processor/aggregation/PivotAggregationSearch.java
(cherry picked from commit 78fc14322ba7989db6efce353087282ee1a28bee)
MIssing commit for PR https://github.com/Graylog2/graylog2-server/pull/6284
=> Warn the user about missing streams in event definitions

graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
Fixes https://github.com/Graylog2/collector-sidecar/issues/350
=> Add default filebeat collector config for windows

misc/graylog.conf
=> Add events index prefix settings to graylog.conf

graylog2-web-interface/src/views/test/ViewFixtures.js
This change is adding helpers for fixture construction (starting with
simple views) which can be used in tests. Wrapping this in an
indirection helps to prevent having to change fixtures in all places
when unrelated changes to the structure of the related models were made.
=> Adding fixture-helpers for view-related tests.

graylog2-web-interface/src/components/field-analyzers/FieldStatistics.jsx
Fixes incorrect `this.props` destruct
=> Fixing incorrect prop destruct

graylog2-web-interface/src/components/common/Select.jsx
Fixes an issue where the `Select` component had a fixed height that would break the layout.
Fixes #6450
=> Fix height of Select component

graylog2-web-interface/src/views/Constants.js, graylog2-web-interface/src/views/components/DashboardSearchBar.jsx, graylog2-web-interface/src/views/components/WidgetGrid.jsx, graylog2-web-interface/src/views/components/WidgetQueryControls.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/AggregationBuilder.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/FullSizeContainer.jsx, graylog2-web-interface/src/views/components/contexts/WidgetContext.jsx, graylog2-web-interface/src/views/components/searchbar/TimeRangeOverrideInput.jsx, graylog2-web-interface/src/views/components/searchbar/TimeRangeOverrideTypeSelector.jsx, graylog2-web-interface/src/views/components/sidebar/AddWidgetButton.jsx, graylog2-web-interface/src/views/components/visualizations/XYPlot.jsx, graylog2-web-interface/src/views/components/visualizations/bar/BarVisualization.jsx, graylog2-web-interface/src/views/components/visualizations/line/LineVisualization.jsx, graylog2-web-interface/src/views/components/visualizations/scatter/ScatterVisualization.jsx, graylog2-web-interface/src/views/components/visualizations/worldmap/__tests__/WorldMapVisualization.test.jsx, graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.css, graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.jsx, graylog2-web-interface/src/views/components/widgets/Widget.jsx, graylog2-web-interface/src/views/logic/creatoractions/CreateCustomAggregation.js, graylog2-web-interface/src/views/logic/queries/QueryGenerator.js, graylog2-web-interface/src/views/stores/WidgetStore.js
This change includes the UI-related code for allowing per-widget
query/timerange/streams selection overrides.
Requires #6446 to be merged before.
=> Include query, time range & streams selection when editing widget on dashboard

graylog2-server/src/main/java/org/graylog/events/search/MoreSearch.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchResource.java, graylog2-server/src/main/java/org/graylog2/indexer/TestIndexSet.java, graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java, graylog2-server/src/test/java/org/graylog2/indexer/searches/SearchesIT.java
=> Remove Event indices from global search default

graylog2-web-interface/src/components/bootstrap/__snapshots__/Input.test.jsx.snap, graylog2-web-interface/src/components/graylog/Button.jsx, graylog2-web-interface/src/theme/teinte.js, graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkList.test.jsx.snap, graylog2-web-interface/src/views/components/sidebar/AddWidgetButton.test.jsx, graylog2-web-interface/src/views/hooks/__snapshots__/RequirementsProvided.test.jsx.snap
- Reverts to old colors
- Adds active state
During development we will keep button colors as consistent as possible with the current color scheme.
Added active state to Button so we can theme based on the prop
=> Button Theme active state and current colors

pom.xml
- https://netty.io/news/2019/09/25/4-1-42-Final.html
- https://netty.io/news/2019/09/12/4-1-41-Final.html
- (there was no 4.1.40 release)
=> Update to netty 4.1.42

graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationHelper.jsx, graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationVariablesHelper.jsx, graylog2-web-interface/src/components/sidecars/configuration-forms/EditConfigurationVariableModal.jsx
Fixes bug in Sidecar Configuration that was introduced during previous linting
=> Fixing issue with Sidecar Configuration

graylog2-web-interface/flow-typed/npm/styled-components_v4.x.x.js
This PR is adding flow types for `styled-components`, required to use it
in flow-typed components.
=> Adding flow types for `styled-components`.

graylog2-server/src/test/java/org/graylog/plugins/views/search/views/ViewRequirementsTest.java
Changes containsExactly to containsOnly, which "verifies that the actual map contains only the given entries and nothing else, in any order"
Fixes #6561 
It passes the unit tests and does not assume the order of iterations.
=> Fix #6561 by making tests more robust

graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.jsx, graylog2-web-interface/src/views/components/searchbar/bookmark/BookmarkControls.test.jsx
This change will pass the correct type to the ViewAction.create
function.
Prior to this change, the button was not passing the new view type
so when clicking on the button a error was raised.
=> Fix the bookmark button to clear current view

graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
This fixes a small syntax bug in the default Windows Filebeat configuration.
=> Fix default Filebeat config for Windows hosts

graylog2-web-interface/src/components/content-packs/ContentPackDownloadControl.jsx
* Fixes https://github.com/Graylog2/graylog2-server/issues/6540
* User Experience
=> Fix ContentPack Modal Dialog Title

graylog2-server/src/main/java/org/graylog/plugins/map/config/DatabaseType.java, graylog2-server/src/main/java/org/graylog/plugins/map/geoip/MaxmindDataAdapter.java, graylog2-server/src/test/java/org/graylog/plugins/map/geoip/MaxmindDataAdapterTest.java, graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterDocumentation.jsx, graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterFieldSet.jsx, graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterSummary.jsx
(cherry picked from commit 4f4db4c6bac59d8c5aa106b5fcb24862a3562ad2)
=> Add support for MaxMind ASN geo ip database (#6623)

graylog2-web-interface/src/components/events/events/Events.jsx, graylog2-web-interface/src/components/graylog/Alert.jsx, graylog2-web-interface/src/components/graylog/bootstrap-import.js, graylog2-web-interface/src/components/graylog/index.js, graylog2-web-interface/src/components/graylog/styles/button.js, graylog2-web-interface/src/components/graylog/variants/bsStyle.js, graylog2-web-interface/src/theme/GraylogThemeContext.jsx, graylog2-web-interface/src/theme/index.js, graylog2-web-interface/src/theme/index.test.js, graylog2-web-interface/src/views/components/searchbar/KeywordTimeRangeSelector.test.jsx
Updating `Alert` component to be themed
=> Themed Alert

graylog2-web-interface/src/components/nodes/NodesList.jsx, graylog2-web-interface/src/pages/NodesPage.jsx
Also remove unused import in NodesPage component.
Refs #6567
=> Fix prop-types in NodesList component

graylog2-server/src/main/java/org/graylog/events/legacy/LegacyAlertCondition.java
(cherry picked from commit 3bc5f40f073d29a7b355f502b6add5a4ebfd9bc3)
=> Report actual configured backlog size in LegacyAlertCondition (#6580)

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/debug/MetricCounterIncrement.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/metricCounter.txt
(cherry picked from commit b404d3199ffd3e158b831bcf386e77975fe01c65)
=> Add metric_counter_inc pipeline function (#6633)

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/Length.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/stringLength.txt
* Add length function for determining string length, based on characters or bytes
* add license header
(cherry picked from commit a0f9d69482261cb7f479b9444d837618864aa76d)
=> Add length function for determining strings (#6635)

graylog2-web-interface/src/components/graylog/Alert.md, graylog2-web-interface/src/components/graylog/Button.md, graylog2-web-interface/src/components/graylog/DropdownButton.md, graylog2-web-interface/src/components/graylog/SplitButton.md, graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkControls.test.jsx.snap, graylog2-web-interface/styleguide.config.js
Adds `components/graylog` to the Styleguide component library
Adds ThemeProvider wrapper to Styleguide library
=> Tying themeable components into styleguide library

graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEditParameter.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap, graylog2-web-interface/src/components/graylog/HelpBlock.jsx, graylog2-web-interface/src/components/graylog/HelpBlock.md, graylog2-web-interface/src/components/graylog/bootstrap-import.js, graylog2-web-interface/src/components/graylog/index.js, graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap, graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/ColumnPivotConfiguration.test.jsx.snap, graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/SeriesConfiguration.test.jsx.snap
- Themed `HelpBlock` component
- Related: Graylog2/graylog-plugin-enterprise/pull/1282
=> Themed HelpBlock Component

graylog2-web-interface/src/components/field-analyzers/FieldStatistics.jsx
* Reset loading state when fetching stats failed
Refs #5836
* Show loading state when adding stats for new field
When the Field Statistics table is displayed, adding a new field does
not display any loading state, which may result confusing if the request
takes some time. This change introduces a spinner like the one we use
when adding statistics for the first field.
(cherry picked from commit 03aa8aa13cabf5fbb4d4261502755ff5dc1974f5)
=> Reset loading state when loading field statistics fails (#6307)

graylog2-web-interface/src/components/common/SelectPopover.jsx
Fixes `Icon` import location
Resolves lint errors
Component wouldn't render due to improper import
=> Fixing Icon import & lint

graylog2-web-interface/src/pages/StartPage.jsx
* destructure permissions from state.
=> Make destructuring consistant for the state in startPage

graylog2-web-interface/src/components/pipelines/StageForm.jsx
* Add a function to check if rule is not already in stage rules
* Filter rules list before formatting for select
(#5896)
=> Pipeline rules already appended to stage should not appear in dropdown 

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
I hope that with this updated issue templates the submitted issues are more specific and contain more useful information.
At least the users need to think about what they want to submit and do not get the same text for everything what result many times in only partly used skeletons.
=> updated issue templates bug/feature

graylog2-web-interface/src/components/graylog/Modal.jsx, graylog2-web-interface/src/components/graylog/Modal.md, graylog2-web-interface/src/components/graylog/bootstrap-import.js, graylog2-web-interface/src/components/graylog/index.js, graylog2-web-interface/src/views/components/searchbar/bookmark/__snapshots__/BookmarkList.test.jsx.snap
=> Themed Modal component

graylog2-web-interface/src/components/graylog/Table.jsx, graylog2-web-interface/src/components/graylog/Table.md, graylog2-web-interface/src/components/graylog/bootstrap-import.js, graylog2-web-interface/src/components/graylog/index.js, graylog2-web-interface/src/theme/GraylogThemeContext.jsx
=> Themed Table Component

graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEditParameter.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap, graylog2-web-interface/src/components/graylog/HelpBlock.jsx, graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap, graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/ColumnPivotConfiguration.test.jsx.snap, graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/SeriesConfiguration.test.jsx.snap
Remove necessity to generate styles on every render and just generate once
Hopefully help Enterprise plugin from generating new classNames every test
=> Cleanup HelpBlock

graylog2-web-interface/src/components/common/SearchForm.md, graylog2-web-interface/src/components/common/SelectPopover.md
Fixes rendering error in style-guide from missing import
=> Fixing SearchForm styleguide example error

graylog2-web-interface/src/components/common/SelectPopover.jsx
Updates the `SelectPopover` to use "correct" propTypes so that it does not crash due to instead finding a styled component
Pages like Sidecar administration would crash due to improperly rendering component
=> Update SelectPopover to fix render failure

graylog2-server/src/main/java/org/graylog/scheduler/JobSchedulerService.java
When the enterprise plugin is installed but there is no valid license
for a non-master node, job execution will be disabled. The job scheduler
would log every second that the next loop iteration cannot proceed.
It will now log only when the state of the config changes.
Fixes #6451
(cherry picked from commit 9a47813f0b9bbe3bbacf545dba4e29ffa8982080)
=> Reduce amount of log messages when job scheduler execution is disabled

graylog2-web-interface/src/components/configurationforms/ConfigurationWell.jsx, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackDetails.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackPreview.test.jsx.snap, graylog2-web-interface/src/components/extractors/ExtractorExampleMessage.jsx, graylog2-web-interface/src/components/graylog/Well.jsx, graylog2-web-interface/src/components/graylog/Well.md, graylog2-web-interface/src/components/graylog/bootstrap-import.js, graylog2-web-interface/src/components/graylog/index.js, graylog2-web-interface/src/components/streamrules/StreamRuleForm.jsx, graylog2-web-interface/src/views/components/dashboard/DashboardWidgetHeader.jsx
=> Themed Well component

pom.xml
Also update the frontend-maven-plugin to 1.8.0.
=> Update to nodejs 12.13.1 and yarn 1.19.2

.github/PULL_REQUEST_TEMPLATE.md
There is a need for the option "Refactoring" in the "Types of changes" section in the PR template. What do you think? We can also discuss the order and the description.
=> Add refactoring as a type of change for the pull request template

graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap, graylog2-web-interface/src/components/graylog/Nav.jsx, graylog2-web-interface/src/components/graylog/styles/nav-tabs.js, graylog2-web-interface/src/components/navigation/__snapshots__/NotificationBadge.test.jsx.snap, graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
Changed `Tabs` component border color
General feedback was that the burgundy color was too strong. I have used a similar color to `link` that highlights the Tabs now as seen in the screen shot
=> Lighter Tabs border color

graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessor.java, graylog2-server/src/test/java/org/graylog/events/processor/aggregation/AggregationEventProcessorTest.java
Fixes #6876
(cherry picked from commit 022b517f3450b536d1b5147086d25cfb8b2116bd)
=> Ensure that aggregation events always have a "source_streams" value (3.1)

graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackVersions.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap, graylog2-web-interface/src/components/graylog/NavDropdown.md, graylog2-web-interface/src/components/graylog/styles/menuItem.js, graylog2-web-interface/src/components/search/__snapshots__/MessageTableEntry.test.jsx.snap, graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap, graylog2-web-interface/src/views/components/searchbar/__snapshots__/RefreshControls.test.jsx.snap
Updating `NavDropdown` disabled menu item style
Hover and Disabled styles were too similar
=> Update disabled Dropdown style

graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionForm.css
Updates the styles in the Wizard bar on while creating Alerts
Recent component changes left these custom styles a little busted
=> Update Alert Wizard styles

graylog2-server/pom.xml, graylog2-server/src/test/java/org/graylog2/contentpacks/model/entities/references/ValueReferenceTest.java
This PR fixes #6907 
It uses [JSONassert](https://github.com/skyscreamer/JSONassert) to make the tests not flaky any more. 
#6907 should explain this well.
=> Fix tests by using JSONAssert equals

graylog2-server/src/main/java/org/graylog2/contentpacks/ContentPackService.java, graylog2-server/src/main/java/org/graylog2/contentpacks/EntityDescriptorIds.java, graylog2-server/src/main/java/org/graylog2/contentpacks/facades/PipelineFacade.java, graylog2-server/src/main/java/org/graylog2/plugin/streams/Stream.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/PipelineFacadeTest.java, graylog2-server/src/test/resources/org/graylog2/contentpacks/pipeline_processor_pipelines_default_stream.json
This pull request prevents the content pack exporter from exporting clones of default streams when including pipelines that are connected to e.g. "All messages".
This closes #5439 and #5616.
In the project I'm working we intend to bootstrap a graylog container from scratch without any manual configuration for consistent production deployments and automated updates. This requires us to include out "entrypoint pipeline" on "All messages" for initial routing. Currently this is not possible, as the import will fail.
As of now the changes have been tested in a local test environment.
There is a test failure, at least on my system, that has been there before I changed anything and still failes. It would be great of someone else could verify. I updated the PipelineFacade test, but I haven't …
=> Allow pipelines connected to "All messages" in content packs

pom.xml
Contains fixes for several CVEs
See the following page for details:
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9.10
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.9#micro-patches
=> Security update to jackson 2.9.10.20191020

graylog2-web-interface/flow-typed/npm/styled-components_v4.x.x.js
Needed for #6926 
Updates styled-components flow-typed to latest version from  https://github.com/flow-typed/flow-typed/blob/bac16db19f39527a6c770fa476d8e17921e48d1d/definitions/npm/styled-components_v4.x.x/flow_v0.104.x-/styled-components_v4.x.x.js
=> Update styled-components flow typing to latest

graylog2-web-interface/src/views/components/visualizations/number/Trend.jsx, graylog2-web-interface/src/views/components/visualizations/number/Trend.test.jsx
Clean up rendering of `Trend` and updated tests to check for props
Testing directly for the rendered styles was leading to a bad time when some variables were adjusted in future branches. This renders the same output but instead tests for the prop being passed to the styled-component
imported the same constants and verified against prop
=> Update Trend render and test

graylog2-server/src/test/java/org/graylog2/migrations/MigrationHelpersTest.java
I was investigating #6979 but ran out of time. Since I already wrote the missing test class for MigrationHelpers, I didn't want to delete it. :wink: 
Refs #6979
=> Add missing test for MigrationHelpers class

graylog2-web-interface/flow-typed/npm/styled-components_v4.x.x.js
Updated to use proper flow typing for components with functional returns
=> Update styled-components flow typing

graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.js, graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.test.js
This change adds copying of time range & streams settings of original
widget when the "Show Documents for value" action is used on a value of
a widget on a dashboard.
Fixes #7040.
=> Copy time range & streams of widget for "Show documents" on dashboard.

graylog2-web-interface/src/components/graylog/Alert.jsx, graylog2-web-interface/src/components/graylog/FormGroup.jsx, graylog2-web-interface/src/components/graylog/Label.jsx, graylog2-web-interface/src/components/graylog/ListGroupItem.jsx, graylog2-web-interface/src/components/graylog/Nav.jsx, graylog2-web-interface/src/components/graylog/Panel.jsx, graylog2-web-interface/src/components/graylog/Popover.jsx, graylog2-web-interface/src/components/graylog/ProgressBar.jsx, graylog2-web-interface/src/components/graylog/Table.jsx, graylog2-web-interface/src/components/graylog/styles/badge.js, graylog2-web-interface/src/components/graylog/styles/button.js, graylog2-web-interface/src/components/graylog/styles/menuItem.js, graylog2-web-interface/src/components/graylog/styles/nav-tabs.js, graylog2-web-interface/src/components/graylog/variants/bsStyle.js, graylog2-web-interface/src/theme/index.js, graylog2-web-interface/src/theme/util/contrastingColor.js, graylog2-web-interface/src/theme/util/contrastingColor.test.js, graylog2-web-interface/src/theme/util/index.js, graylog2-web-interface/src/theme/util/readableColor.js, graylog2-web-interface/src/views/components/visualizations/number/Trend.jsx
Organizes the theme utilities all into one directory
Adds to `theme` object and updated usage of utils
`readableColor` is not yet used, but it will be in future PRs
Organization and prep for #6862
=> Organizing theme utilities

graylog2-web-interface/src/views/bindings.jsx, graylog2-web-interface/src/views/components/views/View.jsx
Prior to this change, the dashboard list generated a generic
`/views/<id>` link for each dashboard, while searches generated a
`/search/<id>` link. This is confusing and inconsistent for users.
This PR is changing this to generated `/dashboards/<id>` link for
dashboards.
=> Generate specific link for each entity on dashboard list.

pom.xml
This fixes an issue where containers haven't been cleaned up properly
after the tests are done.
Full changelog:
https://github.com/testcontainers/testcontainers-java/releases/tag/1.12.4
Fixes #7078
=> Update to testcontainers-1.12.4

graylog2-web-interface/src/stores/configurations/ConfigurationsStore.js
This PR corrects an error message including a reference to "Search config" that I saw after merging #7122.
=> Fix error message wording from #7122

graylog2-web-interface/src/views/components/datatable/DataTableEntry.jsx, graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTableEntry.test.jsx.snap, graylog2-web-interface/src/views/logic/aggregationbuilder/Series.js, graylog2-web-interface/src/views/logic/queries/QueryHelper.js, graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.js, graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.test.js
Prior to this change, only field:value pairs were added to the value path of a value in a data table. This led to empty/incomplete queries being generated from the "Show documents for value" action.
This change is now adding functions to the value path as well if they refer to a field. A function like this generates a `_exists_:<field>` clause, so all documents containing this field match.
Fixes #7103.
Fixes #7104.
=> Add current function to value path.

graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/searchtypes/pivot/ESPivot.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/searchtypes/pivot/ESPivotTest.java
Prior to this change, the effective time range of the pivot was used for
the search type's result only if the result contains no documents
(causing the min/max aggregations to return `null`). This led to the
effective time range for the pivot search type being the
smallest/largest timestamp of its documents, instead of the
beginning/end of the supplied time range.
This PR is now changing this behavior to do one of these:
- If the effective time range of the search type is set to "All
messages" and the search returns documents, the effective time range of
the result is the smallest/largest timestamp of the result set
- If the effective time range of the search type is set to "All
messages" and the search returns no documents, the effective time range
of the result is set to unix epoch …
=> Fixing effective time range in pivot search type results.

graylog2-web-interface/src/views/components/aggregationbuilder/PivotConfiguration.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/pivottypes/TimeUnitTimeHistogramPivot.jsx
Prior to this change, the user could enter any values for the manual
time bucket interval of a date pivot, including invalid numbers, values
less or equal than 0 or floats.
This PR is adding validation to the input, checking for being an integer
and greater than 0 before submitting.
Fixes #7195.
=> Validating value for interval to be an integer and greater than 0.

graylog2-web-interface/src/components/common/Scratchpad.jsx
- Changes `Scratchpad` font to monospace
- Disabled browser integrated spellcheck
Developer ask
=> Monospace Scratchpad

graylog2-web-interface/yarn.lock
Fixes security issue in set-value:
https://github.com/advisories/GHSA-4g88-fppr-53pp
=> Bump set-value to 2.0.1

graylog2-web-interface/src/views/components/sidebar/SideBar.jsx, graylog2-web-interface/src/views/components/sidebar/SideBar.test.jsx
As described in #7241 a sidebar section should close itself when clicking on the related title.
Fixes #7241
=> Close nav item section when clicking on nav item title

graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java
Previously the timestamp part of the "gl2_message_id" was the processing
time. Since we have the actual message event time after processing, we
want to use that one.
We also now check if the field has been set already. If that's the case,
we don't overwrite it. (forwarder use case)
Refs #6711
=> Conditionally set "gl2_message_id" and use message timestamp

graylog2-web-interface/src/views/bindings.jsx, graylog2-web-interface/src/views/components/datatable/DataTable.css, graylog2-web-interface/src/views/components/widgets/MessageTable.jsx
- Improves table styles in reports
- Adds space in series description for aggregations
- Adds flag to control whether widget container should have a fixed width or not
=> Improvements in rendering reports

graylog2-web-interface/src/components/content-packs/ContentPackSelection.jsx, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap
=> Use inclusive language in UI for content packs

graylog2-web-interface/src/components/graylog/Alert.jsx, graylog2-web-interface/src/components/graylog/Alert.md, graylog2-web-interface/src/components/graylog/variants/bsStyle.js
Use the correct Alert `bsStyle` variant options
- Some common variant styles not available to Boostrap Alerts were being generated
- Updated rendered link color within Alert
=> Alert variants

graylog2-web-interface/src/views/components/OverlayDropdown.jsx, graylog2-web-interface/src/views/components/Value.css, graylog2-web-interface/src/views/components/Value.jsx, graylog2-web-interface/src/views/components/actions/ValueActions.jsx, graylog2-web-interface/src/views/components/datatable/DataTableEntry.jsx, graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTableEntry.test.jsx.snap
Dynamically place the dropdown on the opposite side if not enough room
Dropdown on right side can disappear off of edge
=> Dashboard widget action dropdown position

graylog2-server/src/main/java/org/graylog2/lookup/adapters/DnsLookupDataAdapter.java, graylog2-server/src/main/java/org/graylog2/lookup/adapters/dnslookup/DnsClient.java, graylog2-server/src/main/java/org/graylog2/shared/utilities/ExceptionUtils.java, graylog2-server/src/test/java/org/graylog2/lookup/adapters/dnslookup/DnsClientTest.java, graylog2-server/src/test/java/org/graylog2/shared/utilities/ExceptionUtilsTest.java
=> Backport: Fix blocking issue in DNS lookup data adapter (#7325)

graylog2-web-interface/src/routing/AppFacade.jsx
Updating deprecated createReactClass to functional React component 
Every update to AppFacade causes a lint failure because of using `createReactClass`, this solves that
=> Update AppFacade to functional component

graylog2-web-interface/src/components/streamrules/CollapsibleStreamRuleList.jsx, graylog2-web-interface/src/components/streamrules/HumanReadableStreamRule.jsx, graylog2-web-interface/src/components/streamrules/StreamRule.jsx, graylog2-web-interface/src/components/streamrules/StreamRuleList.jsx, graylog2-web-interface/src/components/streamrules/StreamRulesEditor.jsx, graylog2-web-interface/src/components/streams/Stream.jsx, graylog2-web-interface/src/components/streams/StreamMetaData.jsx, graylog2-web-interface/src/theme/styles/globalStyles.jsx
Updates the Stream Rule notification to use proper colors and tweak some general layout issues.
Closes #7279
=> Stream alert panel

graylog2-web-interface/src/stores/tools/ToolsStore.js
Before this fix adding a not valid regex character to a url whitelist entry caused an error and a page reload
on validation check
* Url encode the regex value before send it to the server for validation
#7357
- [*] Bug fix (non-breaking change which fixes an issue)
- [*] My code follows the code style of this project.
- [*] I have read the **CONTRIBUTING** document.
=> Fix issue with regex whitelist validation error

graylog2-web-interface/src/components/systemjobs/SystemJobsComponent.jsx
* Refactor SystemJobsComponent
* Avoid error when system jobs response has no nodes
Guard against an empty system jobs object by setting a default value in
the reduce function.
Refs #7329
Cherry-pick of #7332 for 3.2.
=> Guard against empty cluster jobs response (#7332)

graylog2-web-interface/src/components/common/ConfirmLeaveDialog.test.jsx, graylog2-web-interface/src/flow/css-modules.js, graylog2-web-interface/src/flow/css-useable-modules.js, graylog2-web-interface/src/views/components/SearchBarWithStatus.test.jsx, graylog2-web-interface/src/views/components/common/ActionDropdown.jsx, graylog2-web-interface/src/views/components/common/WindowLeaveMessage.jsx, graylog2-web-interface/src/views/components/datatable/DataTableEntry.test.jsx, graylog2-web-interface/src/views/components/messagelist/PossiblyHighlight.jsx, graylog2-web-interface/src/views/components/searchbar/RefreshControls.jsx, graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRule.jsx, graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRules.jsx, graylog2-web-interface/src/views/components/widgets/WidgetColorContext.jsx, graylog2-web-interface/src/views/stores/ViewSharingStore.test.js
This PR removes not needed FlowFixMe comments.
=> Remove no longer needed FlowFixMe for imports from core

pom.xml
Tested locally that tests still work.
=> Bump testcontainers version to 1.12.5

graylog2-web-interface/src/components/gettingstarted/GettingStarted.jsx, graylog2-web-interface/src/theme/styles/globalStyles.jsx
The getting started guide has a fixed height, this can result in not fully visible content.
This PR implements a dynamic height and also:
* Removes minHeight calculation
* Implements styled components
* Improves position for guide dismiss button
=> Display getting started guide with full height

graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap, graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionForm.css, graylog2-web-interface/src/components/graylog/Nav.jsx, graylog2-web-interface/src/components/navigation/__snapshots__/NotificationBadge.test.jsx.snap
Fixing rendered colors in Wizard tabs
=> Fixing Event Definitions tab colors

UPGRADING.rst, misc/graylog.conf
=> Add note about password_secret being the same on all nodes

misc/graylog.conf
=> Extend description for password_secret in graylog.conf example config

graylog2-web-interface/package.json, graylog2-web-interface/yarn.lock
This change is updating `flow` from `v0.117.0` to `v0.119.1`.
=> Updating flow to 0.119.1.

graylog2-web-interface/babel.config.js, graylog2-web-interface/src/injection/CombinedProvider.js, graylog2-web-interface/src/stores/search/SearchStore.ts, graylog2-web-interface/src/util/URLUtils.js, graylog2-web-interface/tsconfig.json
The other day I noticed that [code splitting](https://webpack.js.org/guides/code-splitting/)  broke somewhere between `3.1` and `3.2`. Bisecting the issue identified f4e4bd12eb789661529567fba5de7ac74401d2f5 as having caused it, although it is a generally unrelated change. Debugging it, it turned out that webpack turns `import()` calls to CommonJS `require()`'s for no apparent reason. Instead of tracing this further, I decided to take a shortcut that enables things we wanted to anyway and changed the module format that babel emits from CommonJS to proper ES6 (by toggling `modules` from `'cjs'` to `false`). This retains all `import()` calls, therefore reenabling code splitting again. It also enables tree shaking, leading to further size reductions.
It also leads to changes of the default …
=> Re-enable code splitting, add tree shaking for webpack.

graylog2-web-interface/src/views/components/OverlayDropdown.jsx, graylog2-web-interface/src/views/components/Value.css, graylog2-web-interface/src/views/components/Value.jsx, graylog2-web-interface/src/views/components/actions/ValueActions.jsx, graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTableEntry.test.jsx.snap
Backport of #7305 for 3.2
Dynamically place the dropdown on the opposite side if not enough room
Dropdown on right side can disappear off of edge
=> Dashboard widget action dropdown position (Backport of #7305 for 3.2)

graylog2-web-interface/src/pages/LoginPage.jsx
- Rewrites `createReactClass` as functional component
- Adds promise `.cancel()` on unmount
Component was using older ES5 code and also was causing warnings of state being set on an unmounted component.
=> LoginPage as functional component & canceled promise

graylog2-web-interface/src/pages/ConfigurationsPage.jsx
=> Unbreak ConfigurationPage for Events System

graylog2-web-interface/src/components/graylog/Pagination.jsx, graylog2-web-interface/src/components/graylog/Panel.jsx, graylog2-web-interface/src/util/constants.js, graylog2-web-interface/src/util/deprecationNotice.js, graylog2-web-interface/test/console-warnings-fail-tests.js
Replace `console.warn` with a dedicated `deprecationNotice` utility
Wrap the console.warn with `gl2DevMode` so that they don't render outside of dev
=> Wrap Deprecation Notice Utility

graylog2-web-interface/src/stores/configurations/ConfigurationsStore.js
- create setConfigurationState and use cloneDeep to update
- Update methods to use setConfigurationState before propagateChanges
Before this change saving a configuration update on configuration page wasn't updating the overview on the same page because the different configuration were held in the same object inside the configurationStore. Resulting in the the connect function did not see change when a key of that object were updated. 
With these change we make sure to create a new object cloned from the current configuration and and set it back as configuration object after updating.
fixes #7760
=> Use spread object creation to copy configurations before update

graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap, graylog2-web-interface/src/components/graylog/ListGroupItem.jsx, graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap, graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap, graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap, graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap, graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap
Updating colors to not be terrible
- Closes #7784
BEFORE  
AFTER
=> Updating colors to use on hover

graylog2-web-interface/src/components/graylog/Panel.jsx
Found that some Panel header colors weren't rendering well
Before:  
After:
=> Update Panel Header Color

graylog2-web-interface/yarn.lock
Updating `yarn.lock`
- https://github.com/Graylog2/graylog-plugin-integrations/pull/443
- https://github.com/Graylog2/graylog-plugin-enterprise-integrations/pull/137
- https://github.com/Graylog2/graylog-plugin-enterprise/pull/1507
- https://github.com/Graylog2/graylog-plugin-threatintel/pull/159
- https://github.com/Graylog2/graylog-plugin-aws/pull/340
- https://github.com/Graylog2/graylog-plugin-collector/pull/146
=> yarn.lock update

graylog2-server/src/test/java/org/graylog2/shared/bindings/providers/OkHttpClientProviderTest.java
The `OkHttpClientProviderTest` test suite was producing test failures
every now and then, requiring to restart the build unnecessarily.
This change is disabling this specific test suite until someone has time
to fix it.
=> Ignore `OkHttpClientProviderTest` test suite.

graylog2-web-interface/.flowconfig
Since the last babel update (#7551), it supports transpiling [optional chaining](https://tc39.es/proposal-optional-chaining/) as well as [nullish coalescing](https://tc39.es/proposal-nullish-coalescing/).
This change is enabling support for these in flow, which otherwise would flag these as errors.
=> Enable support for optional chaining & nullish coalescing in flow.

graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap, graylog2-web-interface/src/components/graylog/Tab.jsx, graylog2-web-interface/src/components/graylog/Tooltip.jsx, graylog2-web-interface/src/components/graylog/bootstrap-import.js, graylog2-web-interface/src/components/graylog/index.js, graylog2-web-interface/src/components/graylog/styles/nav-tabs.js, graylog2-web-interface/src/components/navigation/__snapshots__/NotificationBadge.test.jsx.snap, graylog2-web-interface/src/components/rules/RuleHelper.jsx, graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap, graylog2-web-interface/src/pages/ShowDashboardPage.css, graylog2-web-interface/src/theme/GlobalThemeStyles.jsx, graylog2-web-interface/src/views/components/Query.jsx, graylog2-web-interface/src/views/components/QueryTabs.jsx, graylog2-web-interface/src/views/components/WidgetGrid.jsx, graylog2-web-interface/src/views/components/__snapshots__/WidgetGrid.test.jsx.snap, graylog2-web-interface/src/views/components/queries/QueryTitle.jsx, graylog2-web-interface/src/views/components/widgets/WidgetFrame.jsx, graylog2-web-interface/src/views/components/widgets/__snapshots__/Widget.test.jsx.snap, graylog2-web-interface/src/views/pages/ExtendedSearchPage.css, graylog2-web-interface/src/views/pages/ExtendedSearchPage.jsx, graylog2-web-interface/yarn.lock
- Organizing global styles
- Updated styles for Tab/Tabs component
Generally clearing out of old code, organizing global stuff to their components, etc
=> Global Styles Cleanup Act 4

graylog2-web-interface/flow-typed/npm/react-dom_v16.x.x.js, graylog2-web-interface/package.json, graylog2-web-interface/src/stores/connect.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/AggregationBuilder.jsx, graylog2-web-interface/src/views/logic/searchtypes/aggregation/PivotConfigGenerator.js, graylog2-web-interface/src/views/logic/searchtypes/events/EventHandler.js, graylog2-web-interface/src/views/stores/QueriesStore.test.jsx, graylog2-web-interface/yarn.lock
This PR is updating flow to v0.122.0. It is including the required
package updates as well as fixing new type errors. The most important
change is including typedefs for `react-dom`, as they are not part of
flow anymore.
=> Updating flow to v0.122.0.

graylog2-web-interface/src/actions/users/PreferencesActions.js, graylog2-web-interface/src/contexts/CurrentUserPreferencesProvider.jsx, graylog2-web-interface/src/contexts/CurrentUserPreferencesProvider.test.jsx, graylog2-web-interface/src/contexts/UserPreferencesContext.js, graylog2-web-interface/src/injection/registerBuiltinStores.js, graylog2-web-interface/src/pages/LoggedInPage.jsx, graylog2-web-interface/src/stores/users/CurrentUserStore.jsx, graylog2-web-interface/src/stores/users/PreferencesStore.js, graylog2-web-interface/test/helpers/mocking/CombinedProviderMock.js, graylog2-web-interface/test/helpers/mocking/index.js
This PR is providing a context containing user preferences (right now
untyped key/value pairs) that can be consumed by react components. A
default provider taking preferences from the currently logged in user
was created and employed in the `LoggedInPage` component so it is
available everywhere after a user's login.
In addition, the `PreferencesStore` is turned into using proper Reflux
actions and the `CurrentUserStore` listens to the action to save
preferences in order to reload its state after it has completed. This
makes changing preferences of a user effective in the `CurrentUserStore`
immediately.
=> Provide global context for current user preferences.

graylog2-web-interface/src/routing/App.jsx, graylog2-web-interface/src/theme/GlobalThemeStyles.jsx, graylog2-web-interface/src/views/components/OverlayDropdown.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/DescriptionBox.jsx, graylog2-web-interface/src/views/components/common/ActionDropdown.jsx, graylog2-web-interface/src/views/components/datatable/MessagesTable.jsx, graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTable.test.jsx.snap
Replacing hardcoded HEX color values to use theme values.
So all parts of the app are themeable
=> Moving All Hex Colors breakdown 4/6

graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListConfig.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntitiesList.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstallations.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameterList.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameters.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackUploadControls.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackVersions.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap, graylog2-web-interface/src/components/graylog/Modal.jsx, graylog2-web-interface/src/components/graylog/ProgressBar.jsx, graylog2-web-interface/src/components/graylog/__snapshots__/ProgressBar.test.jsx.snap, graylog2-web-interface/src/components/grok-patterns/__snapshots__/EditPatternModal.test.jsx.snap, graylog2-web-interface/src/components/indices/ShardRoutingOverview.jsx, graylog2-web-interface/src/components/inputs/InputThroughput.jsx, graylog2-web-interface/src/components/layout/Footer.jsx, graylog2-web-interface/src/components/metrics/MetricsList.jsx, graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap, graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap
Replacing hardcoded HEX color values to use theme values.
So all parts of the app are themeable
=> Moving All Hex Colors breakdown 2/6

graylog2-web-interface/src/theme/docs/Colors.jsx, graylog2-web-interface/src/theme/docs/Colors.md, graylog2-web-interface/src/theme/docs/Details.md, graylog2-web-interface/src/theme/docs/ThemeProvider.md, graylog2-web-interface/src/theme/docs/Utilities.md, graylog2-web-interface/styleguide.config.js
Updates documentation on how to use Styled Components
Updated click to copy color swatches not require two clicks
More developer information and reduced click fatigue
=> Updating Theme documentation

graylog2-server/src/main/java/org/graylog2/plugin/Message.java, graylog2-server/src/main/java/org/graylog2/shared/buffers/ProcessBuffer.java
Refs https://github.com/Graylog2/graylog2-server/pull/7199
Fixes #7937
=> Don't truncate Messages in ProcessBuffer Dumper

pom.xml
For details on netty:
https://netty.io/news/2020/04/22/4-1-49-Final.html
For details on netty-tcnative:
https://github.com/netty/netty-tcnative/commits/netty-tcnative-parent-2.0.30.Final
=> Update netty to 4.1.49 and netty-tcnative to 2.0.30

graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchForm.jsx, graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchForm.test.jsx.snap
This change is stopping the event triggered by the "Save" button in the
`SavedSearchForm` component. If it is not stopped, in the current
implementation it will trigger submitting the search controls form,
executing the current search.
=> Prevent form submit event leaking out of `SavedSearchForm`.

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/FirstNonNull.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/firstNonNull.txt
Adds a new function `first_non_null` to pipeline processor that accepts a list as unique parameter and returns the first non null value found in that list. Returns an empty string if none found.
Fixes #7895
=> Add firstNonNull function to pipeline processor

graylog2-server/src/main/java/org/graylog2/shared/ServerVersion.java
Updating codename for 3.3-beta release. 
Changing codename for 3.3-beta release. 
- [X ] New feature (non-breaking change which adds functionality)
- [X ] My code follows the code style of this project.
- [X ] I have read the **CONTRIBUTING** document.
=> update codename for 3.3-beta

graylog2-web-interface/src/components/bootstrap/__snapshots__/Input.test.jsx.snap, graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListForm.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackApplyParameter.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEditParameter.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackVersions.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap, graylog2-web-interface/src/components/event-definitions/event-definition-types/__snapshots__/AggregationConditionExpression.test.jsx.snap, graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternFilter.test.jsx.snap, graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap, graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap, graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap, graylog2-web-interface/src/theme/variants/teinte.js, graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap, graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/SeriesConfiguration.test.jsx.snap, graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTable.test.jsx.snap, graylog2-web-interface/src/views/components/searchbar/__snapshots__/RefreshControls.test.jsx.snap, graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchForm.test.jsx.snap, graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap, graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap, graylog2-web-interface/src/views/components/widgets/__snapshots__/Widget.test.jsx.snap
Updating variant light and dark colors to generate based on `gray` shades.
Keep the colors more in range of the theme and needing broader spectrum in shades.
###Before
=> Color variant adjust

graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
Update failing snapshot tests.
=> Update snapshot which is failing the build

graylog2-web-interface/src/views/components/datatable/MessagesTable.jsx, graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTable.test.jsx.snap, graylog2-web-interface/src/views/components/widgets/MessageTable.jsx
- Darken color used in search results
Previous #7971 PR made search result sub-text hard to read
=> Search Result data darken

graylog2-web-interface/src/theme/GlobalThemeStyles.jsx
- Using `theme.color.global.textDefault` as the default text color
Theme All the Things
=> Global Text Color using Theme

graylog2-web-interface/src/components/event-definitions/common/HelpPanel.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/EventConditionForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterPreview.jsx, graylog2-web-interface/src/components/graylog/Panel.jsx, graylog2-web-interface/src/components/graylog/Panel.md
- Have Alerts & Events render new Panels instead of DeprecatedPanels
- `How many Events will Filter & Aggregation create?` click to open works again
Panels kept looking not so great, updating to help
=> Update panel usage

graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/AbstractInputsResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/InputStatesResource.java
(cherry picked from commit d2f19f92ac226c031cbd2824a121647a9039e7a8)
=> Mask passwords in input config returned from /system/inputstates (#8031)

graylog2-server/src/main/java/org/graylog2/security/AESTools.java, graylog2-server/src/main/java/org/graylog2/security/ldap/LdapSettingsImpl.java
This change is adding a new static method to our `AESTools` utility
class, which generates a new random salt. This method is reused in
`LdapLdapSettingsImpl`. It will also be reused in future code changes
where the generation of a new salt for encryption is desired.
=> Extract method to generate new salt for encryption.

graylog2-server/src/main/java/org/graylog/schema/GraylogSchemaFields.java
remove unused field `FIELD_THREAT_DETECTED`
=> remove unused fields

graylog2-server/src/main/java/org/graylog/freeenterprise/FreeEnterpriseService.java, graylog2-server/src/main/java/org/graylog/freeenterprise/FreeLicenseAPIClient.java, graylog2-web-interface/src/pages/EnterprisePage.jsx
use a headline and slightly smaller font
fix a whitespace issue
convert to new URL for trial requests, requires merge of license server first
improve logging of service: lower to debug and don't double log exception in case of problems
=> mostly cosmetic changes to free trial license request page

graylog2-web-interface/src/components/common/Select.jsx, graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListForm.test.jsx.snap, graylog2-web-interface/src/components/event-definitions/event-definition-form/FieldForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationConditionExpressions/NumberRefExpression.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-types/AggregationForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-types/__snapshots__/AggregationConditionExpression.test.jsx.snap
This PR is doing two things to improve rendering for the event
definition UI:
1. Use `defaultCompare` instead of `naturalSort`
2. Add and use option for `Select` component to not strip
accents/diacritics
Fixes #7752.
=> Improve rendering performance of field selects in event definition UI.

graylog2-web-interface/src/components/bootstrap/__snapshots__/Input.test.jsx.snap, graylog2-web-interface/src/components/configurations/__snapshots__/UrlWhiteListForm.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackApplyParameter.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEditParameter.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackVersions.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap, graylog2-web-interface/src/components/event-definitions/event-definition-types/__snapshots__/AggregationConditionExpression.test.jsx.snap, graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternFilter.test.jsx.snap, graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap, graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap, graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap, graylog2-web-interface/src/theme/GlobalThemeStyles.jsx, graylog2-web-interface/src/theme/docs/Colors.jsx, graylog2-web-interface/src/theme/docs/Colors.md, graylog2-web-interface/src/theme/variants/teinte.js, graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap, graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/SeriesConfiguration.test.jsx.snap, graylog2-web-interface/src/views/components/datatable/__snapshots__/DataTable.test.jsx.snap, graylog2-web-interface/src/views/components/searchbar/__snapshots__/RefreshControls.test.jsx.snap, graylog2-web-interface/src/views/components/searchbar/queryinput/StyledAceEditor.jsx, graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchForm.test.jsx.snap, graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap, graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap, graylog2-web-interface/src/views/components/widgets/__snapshots__/Widget.test.jsx.snap
- Updating variant colors that reverted at some point from https://github.com/Graylog2/graylog2-server/pull/7971
- Fixing Search Query input highlight color
- Updating positioning of Query Input to center with search button
Needed more shades of variants and somehow I managed to revert previous changes to the variants. Also, the current updates to the Search Query input made highlighted text difficult to read.
=> Query ace styles

pom.xml
For details on netty:
https://netty.io/news/2020/05/13/4-1-50-Final.html
=> Update netty to 4.1.50

graylog2-server/src/main/java/org/graylog2/decorators/LinkFieldDecorator.java
Should improve performance a tid bit
=> Make UrlValidator a Singleton

UPGRADING.rst
Added upgrade notes for export mentioning that old endpoints will be removed for 4.0
=> Added upgrade notes for export

graylog2-web-interface/src/theme/index.js, graylog2-web-interface/src/theme/utils/colorLevel.js, graylog2-web-interface/src/theme/utils/contrastingColor.js, graylog2-web-interface/src/theme/utils/index.js, graylog2-web-interface/src/theme/utils/opacify.js, graylog2-web-interface/src/theme/utils/readableColor.js, graylog2-web-interface/src/views/components/searchbar/queryinput/StyledAceEditor.jsx
Follow up to **_Moving theme utils to GraylogThemeProvider #8092_** which needs to merge first. Adds increased typing coverage to theme utilities
Cleanup the codes!
=> Theme utils typing

graylog-storage-elasticsearch6/pom.xml, graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerFactory.java, graylog2-server/src/test/resources/api-it-tests.properties
As we are now building a separate storage module that is holding
implementations for interfaces encapsulating ES-specific functionality,
we need to ensure that this module is present at runtime. This is
relevant for our dockerized integration tests as well.
This PR is ensuring that the storage module is mounted into the docker
container into the plugin directory so it is loaded during startup.
=> Include storage module in Graylog setup of integration tests.

graylog2-server/src/main/java/org/graylog/plugins/views/search/export/es/SearchAfter.java
=> Fixed import

graylog2-server/src/main/java/org/graylog2/indexer/messages/IndexBlockRetryAttempt.java, graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java, graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesRetryWaitTest.java, graylog2-server/src/test/java/org/graylog2/indexer/messages/MockedMessagesTest.java
* Draft solution for retrying index failures due to flood stage reached (WIP)
- Added additional retry loop in `Messages`. While it's not ideal to complicate the indexing code further, this error case can't be included in the existing retry logic, because the we have to modify the next request to only include items that have failed due to this particular error
- Added a simple test to `MockedMessagesTest`
* Add test verifying that other errors occurring in same chunk as index block errors are not retried
* Treat retried index block errors that fail differently as persistent failures
* Reuse `com.github.rholder.retry.WaitStrategy` for index block retries
* add license headers
* Keep using milliseconds-based waiting for `BULK_REQUEST_RETRYER`
...but go with seconds-based for index block …
=> Retry messages if target index is read-only - 3.3 (#8245)

graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
This PR fixes an oversight in pr #8245, which led to tons of misleading
warnings.
=> Fix unconditional warning

graylog2-server/src/test/java/org/graylog2/security/realm/LdapUserAuthenticatorTest.java
This was an oversight in the recently merged PR
=> Fix LdapUserAuthenticatorTest

graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20200204122000_MigrateUntypedViewsToDashboards/Widget.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/rest/PipelineResourceTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/export/es/ElasticsearchExportBackendTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/export/es/SearchAfterTest.java, graylog2-server/src/test/java/org/graylog2/system/urlwhitelist/UrlWhitelistServiceTest.java
This change is fixing a couple of import statements, where the wrong
classes are imported. The used classes are repackaged/shaded versions of
guava, which could break if the internal structure of the dependency is
changed or the dependency itself is removed.
=> Fixing erroneous imports.

graylog2-server/src/main/java/org/graylog/plugins/cef/input/CEFAmqpInput.java, graylog2-server/src/main/java/org/graylog/plugins/cef/input/CEFKafkaInput.java, graylog2-server/src/main/java/org/graylog/plugins/cef/input/CEFTCPInput.java, graylog2-server/src/main/java/org/graylog/plugins/cef/input/CEFUDPInput.java
Change Input names. Delete "Input" from name.
Fixes #7345
--
--
=> Change Input names (fix 7345 issue)

graylog-storage-elasticsearch6/pom.xml, graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/CountsAdapterES6.java, graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/CountsES6IT.java, graylog2-server/src/main/java/org/graylog2/indexer/counts/Counts.java, graylog2-server/src/main/java/org/graylog2/indexer/counts/CountsAdapter.java, graylog2-server/src/test/java/org/graylog2/indexer/counts/CountsIT.java
In order to move all ES-specific implementation details to a separate module, this change is extracting an interface for these from the `Counts` class.
=> Extract interface from `Counts` class to encapsulate ES-specifics

graylog2-server/src/main/java/org/graylog2/shared/security/RestrictToMasterFilter.java
=> Log the rejected URL within RestrictToMasterFilter

graylog-storage-elasticsearch6/pom.xml, graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Module.java, graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/NodeAdapterES6.java, graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/NodeAdapterES6Test.java, graylog2-server/src/main/java/org/graylog2/indexer/cluster/NodeAdapter.java, graylog2-server/src/test/java/org/graylog2/indexer/cluster/NodeTest.java, graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerIT.java, graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesGetAllMessageFieldsIT.java, graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
In order to move all ES-specific implementation details to a separate module, this change is extracting an interface for these from the `Node` class.
=> Extracting interface from `Node` class to encapsulate ES-specifics

graylog2-web-interface/src/components/graylog/Navbar.jsx, graylog2-web-interface/src/components/graylog/styles/nav-tabs.js, graylog2-web-interface/src/theme/GraylogThemeProvider.jsx, graylog2-web-interface/src/theme/breakpoints.js, graylog2-web-interface/src/theme/docs/Utilities.md, graylog2-web-interface/src/theme/index.js, graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchForm.test.jsx.snap
rename `theme.breakpoint` to `theme.breakpoints` and add to ThemeProvider so it's available via the theme instead of as an import
Cleaning up code
=> Breakpoint to breakpoints

graylog2-web-interface/src/components/search/MessageFieldDescription.jsx
Fixes broken styled-component render
`Loading component failed: can't access property "withConfig", n(...).default.spa is undefined`
=> Spa is nice, but span works better

graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndexHelper.java, graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/MoreSearchAdapterES6.java, graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/SearchesAdapterES6.java, graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/SortOrderFactory.java, graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/SortOrderMapper.java, graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackend.java, graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/export/ElasticsearchExportBackend.java, graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/IndexHelperTest.java, graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/SearchesES6IT.java, graylog2-server/src/main/java/org/graylog2/indexer/searches/Sorting.java
This PR is performing a couple of smaller cleanups to advance
encapsulating ES-specific details in the storage module. It does:
- move the remaining usage of `SortOrder` to storage module
- remove an unused method
- move `IndexHelper` class to ES module
=> Minor cleanups to encapsulate ES-specifics in storage module.

graylog-storage-elasticsearch6/pom.xml, graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/SearchesAdapterES6.java, graylog2-server/src/main/java/org/graylog2/indexer/searches/ScrollCommand.java, graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java, graylog2-server/src/main/java/org/graylog2/indexer/searches/SearchesAdapter.java
This change is aiming to improve the reusability of the `scroll` method
by introducing an overloaded variant taking a `ScrollCommand` parameter,
which offers a range of (partially optional) parameters used to
customize the output content and formatting of `scroll`.
=> Generalising `scroll` method by introducing a `ScrollCommand`.

graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndexToolsAdapterES6.java, graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/SearchesAdapterES6.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexToolsAdapter.java, graylog2-server/src/main/java/org/graylog2/indexer/searches/ScrollCommand.java
This PR is introducing a `IndexToolsAdapter`, which offers functionality to count, analyze and scroll documents contained in the given indices, including the ability to filter by stream. These methods might be refactored away by consolidating them with present interfaces (which do not currently allow filtering by a given set of streams).
=> Introducing index tools adapter

graylog2-web-interface/src/views/components/visualizations/number/AutoFontSizer.jsx
**This is a backport of #8291 for 3.3**
As described in https://github.com/Graylog2/graylog2-server/issues/7563 the single number widget can flicker when the widget has a small height.
This happened because the font size always changed between `11px` and `10px`. in both cases the defined tolerance did not matched. This PR is fixing the issue by increasing the tolerance. It also refactors the `AutoFontSizer` code style.
The issue is currently not occurring on the master branch, because https://github.com/Graylog2/graylog2-server/pull/8064 changed the widget content height. You can reproduce the error, by checking out the commit `ed8998c3251` and following the steps in the mentioned issue.
Fixes https://github.com/Graylog2/graylog2-server/issues/7563
=> Prevent single number widget flickering (Backport of #8291 for 3.3)

graylog2-server/src/test/java/org/graylog/testing/elasticsearch/BulkIndexRequest.java, graylog2-server/src/test/java/org/graylog/testing/elasticsearch/Client.java, graylog2-server/src/test/java/org/graylog2/indexer/counts/CountsIT.java
This change adds a `bulkIndex` functionality to the ES test client,
which allows tests to bulk index fixtures in a driver-agnostic way (the
`Client` class will prospectively be turned into an interface implemented by
each driver).
=> Support bulk indexing through test client in integration tests.

graylog2-web-interface/packages/eslint-config-graylog/index.js, graylog2-web-interface/yarn.lock
Adds rules for `import/order` to eslint for consistent import organization
`eslint --fix` can clean up import organization to be more consistent
```jsx
import UserNotification from 'util/UserNotification';
import history from 'util/History';
import React from 'react';
import createReactClass from 'create-react-class';
import PropTypes from 'prop-types';
import Reflux from 'reflux';
import naturalSort from 'javascript-natural-sort';
import { Col, Row, Button } from 'components/graylog';
import { Input } from 'components/bootstrap';
import styles from '../CreateAlertConditionInput.styles.css';
import { Select, Spinner } from 'components/common';
import { AlertConditionForm } from 'components/alertconditions';
import Routes from 'routing/Routes';
import CombinedProvider from …
```
=> Adding import/order rule to eslint config

graylog2-web-interface/src/theme/docs/Colors.md, graylog2-web-interface/src/theme/docs/Utilities.md
Update [`Colors` and `Utilities`](https://graylog2.github.io/frontend-documentation/#!/Theming%20Details/) sections to use proper `colors` object.
=> Update Colors documentation

full-backend-tests/pom.xml, graylog-plugin-archetype/pom.xml, graylog-plugin-parent/graylog-plugin-web-parent/pom.xml, graylog-plugin-parent/pom.xml, graylog-project-parent/pom.xml, graylog2-server/pom.xml, graylog2-server/src/main/java/org/graylog/events/notifications/NotificationGracePeriodService.java, graylog2-server/src/test/java/org/graylog/events/processor/notification/NotificationGracePeriodServiceTest.java, graylog2-web-interface/manifests/package.json, graylog2-web-interface/package.json, graylog2-web-interface/packages/graylog-web-plugin/package.json, graylog2-web-interface/src/views/components/Field.jsx, graylog2-web-interface/src/views/components/Field.test.jsx, graylog2-web-interface/src/views/components/widgets/MessageTable.jsx, integration-tests/pom.xml, pom.xml
Merging latest changes after the release of `3.3.2`
=> Merge latest 3.3 changes into cloud-3.3

graylog2-web-interface/packages/eslint-config-graylog/index.js, graylog2-web-interface/packages/eslint-config-graylog/package.json, graylog2-web-interface/yarn.lock
Adding rules to insert blank lines:
- before a `return`
- after a block of assignments (`const`, `let`)
- except if the const/let is multiple lines long
- After 'block-like' structures such as `if`, `functions`, etc...
- Integrated [eslint-plugin-jest-formatting](https://www.npmjs.com/package/eslint-plugin-jest-formatting) for test formatting
`--fix` ran in another PR https://github.com/Graylog2/graylog2-server/pull/8400
`eslint --fix` can insert required blank lines to be more consistent and improve readability.
```jsx
const ConfirmLeaveDialog = ({ question, router, route }) => {
const handleLeavePage = (e) => {
if (AppConfig.gl2DevMode()) {
return null;
}
e.returnValue = question;
return question;
};
const routerWillLeave = () => {
return handleLeavePage({});
};
useEffect(() => { …
```
=> Adding padding-line-between-statements to eslint

graylog2-web-interface/src/components/graylog/ProgressBar.jsx, graylog2-web-interface/src/components/graylog/__snapshots__/ProgressBar.test.jsx.snap
Destructure default attributes into `bar` variable.
Closes #8420
=> Issue 8420 bugfix

graylog2-web-interface/flow-typed/npm/react-router_vx.x.x.js, graylog2-web-interface/src/stores/inputs/InputTypesStore.js, graylog2-web-interface/src/util/DocsHelper.js
* Add flow declaration for react-router Link
* Add URL for lookup tables documentation
* Add flow types to InputTypesStore
=> Backport Support Forwarder wizard (#8397)

graylog2-server/src/main/java/org/graylog/security/BuiltinCapabilities.java, graylog2-server/src/main/java/org/graylog/security/CapabilityDTO.java, graylog2-server/src/main/java/org/graylog/security/DBGrantService.java, graylog2-server/src/main/java/org/graylog/security/DefaultGrantPermissionResolver.java, graylog2-server/src/main/java/org/graylog/security/GrantDTO.java, graylog2-server/src/main/java/org/graylog/security/SecurityModule.java, graylog2-server/src/main/java/org/graylog/security/rest/EntitySharesResource.java, graylog2-server/src/main/java/org/graylog/security/shares/EntitySharePrepareRequest.java, graylog2-server/src/main/java/org/graylog/security/shares/EntitySharePrepareResponse.java, graylog2-server/src/main/java/org/graylog/security/shares/EntityShareRequest.java, graylog2-server/src/main/java/org/graylog/security/shares/EntitySharesService.java, graylog2-server/src/main/java/org/graylog2/utilities/GRNRegistry.java, graylog2-server/src/test/java/org/graylog/security/DBGrantServiceTest.java, graylog2-server/src/test/resources/org/graylog/security/grants.json
We updated our concepts for roles and capabilities.
=> Rename "role" to "capability"

graylog2-server/src/main/java/org/graylog/schema/VendorFields.java
This is required to keep the Graylog Schema in code in sync with the documented Graylog Schema and to support new fields used in the Okta plugin.
=> Add new Vendor fields to the Graylog Schema

graylog2-server/src/main/java/org/graylog/schema/VendorFields.java
Merge Vendor field changes from 4.0 branch to 3.3
=> Add new Vendor fields to the Graylog Schema (#8471)

graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java, graylog2-server/src/test/java/org/graylog2/users/UserServiceImplTest.java
The frontend code gets the current user permissions
from the UsersResource.
We also need to add the permissions from grants
for the frontend to function.
=> Return permissions from Grants to the frontend

graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/NodeES6IT.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Elasticsearch7Module.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/NodeAdapterES7.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/NodeES7IT.java, graylog2-server/src/test/java/org/graylog2/indexer/cluster/NodeIT.java
This change is doing the following:
- Implementing a `NodeAdapter` for ES7
- Adding an abstract integration test (`NodeIT`)
- Implementing this integration test for ES6 & ES7
=> Implement `NodeAdapter` for ES7.

graylog2-server/src/main/java/org/graylog/schema/VendorFields.java, graylog2-web-interface/flow-typed/npm/react-router_vx.x.x.js, graylog2-web-interface/src/stores/inputs/InputTypesStore.js, graylog2-web-interface/src/util/DocsHelper.js
Merges latest server backports in `3.3` into `cloud-3.3`
=> Merge latest server 3.3 changes into cloud-3.3

graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap, graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionForm.jsx, graylog2-web-interface/src/components/graylog/Nav.jsx, graylog2-web-interface/src/components/graylog/styles/nav-tabs.js, graylog2-web-interface/src/components/navigation/__snapshots__/NotificationBadge.test.jsx.snap, graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
Updated color usage on Wizard nav
Wizard Nav had some inconsistencies in hover effects, from transition timing, to hovering over different areas would lead to different elements changing.
=> Update Nav & Wizard Nav color usage

full-backend-tests/pom.xml, graylog-project-parent/pom.xml, graylog-storage-elasticsearch6/pom.xml, graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/IndicesES6IT.java, graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/MessagesES6IT.java, graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/testing/ClientES6.java, graylog-storage-elasticsearch7/pom.xml, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/ClusterES7IT.java, graylog2-server/pom.xml, graylog2-server/src/test/java/org/graylog/testing/elasticsearch/ElasticsearchInstance.java, graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
This PR is consolidating the `maven-failsafe-plugin` configs used to run integration tests (`*IT.java`). In the same step, it enables it for both storage driver modules.
=> Enabling integration tests for storage driver modules.

graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx, graylog2-web-interface/src/components/users/UsersOverview/UserOverviewItem/ActionsCell.jsx, graylog2-web-interface/src/components/users/UsersOverview/UsersFilter.jsx, graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.jsx, graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.test.jsx, graylog2-web-interface/src/pages/UserDetailsPage.jsx, graylog2-web-interface/src/pages/UserEditPage.jsx, graylog2-web-interface/src/stores/users/UsersStore.js, graylog2-web-interface/src/stores/users/UsersStore.test.js
=> Import UsersActions from UsersStore instead of actions/users/UsersActions

graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/MoreSearchAdapterES6.java, graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Scroll.java, graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/ScrollResultES6.java, graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/SearchesAdapterES6.java, graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/ScrollResultES6IT.java, graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/SearchesES6IT.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Elasticsearch7Module.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Scroll.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ScrollResultES7.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Search.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/SearchRequestFactory.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/SearchesAdapterES7.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/SortOrderMapper.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/TimeRangeQueryFactory.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/SearchesES7IT.java, graylog2-server/src/main/java/org/graylog2/indexer/results/ScrollResult.java, graylog2-server/src/main/java/org/graylog2/indexer/searches/ScrollCommand.java, graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java, graylog2-server/src/test/java/org/graylog2/indexer/searches/SearchesIT.java
**Note: Requires #8482 to be merged before.**
This change is implementing the `SearchesAdapter` for ES7, creates bindings and implements the abstract integration test for it. It also includes the required classes to generate `ScrollResult` & `ScrollResult.ScrollChunk` instances.
=> Implement `SearchesAdapter` for ES7.

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Elasticsearch7Module.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MoreSearchAdapterES7.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ResultMessageFactory.java
**Note: Requires #8488 to be merged before.**
This PR is implementing the `MoreSearchAdapter` used for event
searching/scrolling, for Elasticsearch 7. The scroll method is reusing
the `Scroll` class, offering all required capabilities.
Options for future refactorings:
- Rename `MoreSearch(Adapter)` to `EventSearch(Adapter)` to
communicate its responsibility
- Enhance `SearchConfig` with an optional `streams` field and reuse it
in the `eventSearch` method
=> Implement event searching/scrolling for ES7.

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndexToolsAdapterES7.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Scroll.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/SearchCommand.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/SearchRequestFactory.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/SearchesES7IT.java, graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java
This PR is implementing the `IndexToolsAdapter` for ES7.
=> Implementing `IndexToolsAdapter` for ES7.

graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndexFieldTypePollerAdapterES6.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Elasticsearch7Module.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndexFieldTypePollerAdapterES7.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/mapping/FieldMappingApi.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/IndexFieldTypePollerES7IT.java
This PR is implementing the `IndexFieldTypePollerAdapter` for ES7, required to retrieve field types periodically.
=> Implement `IndexFieldTypePollerAdapter` for ES7.

graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndicesAdapterES6.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java, graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java, graylog2-server/src/main/java/org/graylog2/indexer/indices/IndicesAdapter.java
This PR just does a bunch of small clean ups in `Indices.java` and the related adapters.
=> Clean up Indices class

graylog2-web-interface/src/components/common/Pagination.test.jsx, graylog2-web-interface/src/views/components/contexts/SearchPageLayoutProvider.test.jsx, graylog2-web-interface/src/views/components/searchbar/SearchBarForm.test.jsx
With https://github.com/Graylog2/graylog2-server/pull/8427 we've the updated the `testing-library`. With the new version calling `cleanup` in no longer needed. This PR removes the remaining cleanups which got implemented after creating the update PR.
=> Remove remaining testing library cleanups

graylog2-web-interface/src/components/permissions/EntityShareModal.test.jsx, graylog2-web-interface/src/components/users/UserCreate/PasswordFormGroup.jsx, graylog2-web-interface/src/components/users/UserEdit/PasswordSection.jsx, graylog2-web-interface/src/components/users/UserEdit/SettingsSection.jsx, graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx, graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.test.jsx
=> Implement change password section for new user edit page

graylog2-web-interface/src/components/users/UserManagementLinks.jsx, graylog2-web-interface/src/pages/UserDetailsPage.jsx, graylog2-web-interface/src/pages/UserEditPage.jsx, graylog2-web-interface/src/pages/UserTokensEditPage.jsx, graylog2-web-interface/src/pages/index.jsx, graylog2-web-interface/src/routing/AppRouter.jsx
Beside creating a new page to edit user tokens, this PR creates a separate component for user management "sub menu".
=> Implement edit tokens page for new user management

graylog2-web-interface/src/actions/roles/AuthzRolesActions.js, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap, graylog2-web-interface/src/components/permissions/ShareableEnityURL.jsx, graylog2-web-interface/src/components/users/PaginatedItem.jsx, graylog2-web-interface/src/components/users/PaginatedItemOverview.jsx, graylog2-web-interface/src/components/users/UserEdit/RolesSection.jsx, graylog2-web-interface/src/components/users/UserEdit/RolesSelector.jsx, graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx, graylog2-web-interface/src/logic/roles/Role.js, graylog2-web-interface/src/stores/roles/AuthzRolesStore.js
Add Roles selection to User Edit
=> Roles in user edit

graylog2-web-interface/src/components/users/UserDetails/TeamSection.jsx, graylog2-web-interface/src/components/users/UserDetails/UserDetails.jsx, graylog2-web-interface/src/components/users/UserEdit/TeamsSection.jsx, graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx
Add Teams Section to the UserDetails and UserEdit page.
#8573 needs to be merged first.
=> Teams edit

graylog2-web-interface/src/components/common/PaginatedList.jsx, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap, graylog2-web-interface/src/components/users/LoggedInIcon.jsx, graylog2-web-interface/src/components/users/UserDetails/MainDetailsGrid.jsx, graylog2-web-interface/src/components/users/UserEdit/PasswordSection.jsx, graylog2-web-interface/src/components/users/UserEdit/ProfileSection.jsx, graylog2-web-interface/src/components/users/UserEdit/SettingsSection.jsx, graylog2-web-interface/src/components/users/UserManagementLinks.jsx, graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.jsx, graylog2-web-interface/src/pages/UserEditPage.jsx, graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap, graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap
Further improvements for new user management ui.
=> Further improvements for new user management ui

graylog2-server/src/main/java/org/graylog/schema/DestinationFields.java, graylog2-server/src/main/java/org/graylog/schema/EventFields.java, graylog2-server/src/main/java/org/graylog/schema/GeoFields.java, graylog2-server/src/main/java/org/graylog/schema/HostFields.java, graylog2-server/src/main/java/org/graylog/schema/HttpFields.java, graylog2-server/src/main/java/org/graylog/schema/NetworkFields.java, graylog2-server/src/main/java/org/graylog/schema/PolicyFields.java, graylog2-server/src/main/java/org/graylog/schema/SourceFields.java, graylog2-server/src/main/java/org/graylog/schema/UserFields.java, graylog2-server/src/main/java/org/graylog/schema/VendorFields.java
Merging Graylog Schema changes from 4.0 back to 3.3
=> Latest updates to Graylog Schema (#8358)

graylog2-web-interface/src/components/content-packs/ContentPacksList.jsx, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap
Update `select` to `Select` in ContentPacksList page size selector
Current select is not rendering properly in dark mode - illegible
=> ContentPacksList pagination pageSizeSelector colors

graylog2-web-interface/src/components/common/InteractableModal.jsx, graylog2-web-interface/src/components/common/Scratchpad.jsx
Updated color usage on Scratchpad
Moved description to footer `OverlayTrigger` `Tooltip`
Getting things ready for future dark theme
=> Scratchpad Colors

graylog2-web-interface/src/components/streamrules/StreamRulesEditor.jsx
- Replacing hex colors with colors from theme
Theme All The Things!
=> Remove hex colors from Stream Rules Editor

graylog2-web-interface/src/theme/GlobalThemeStyles.jsx
- Theme colors for `code` elements
- Theme colors for `pre` elements
=> theme code & pre elements

graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap, graylog2-web-interface/src/components/graylog/Panel.jsx, graylog2-web-interface/src/components/graylog/styles/nav-tabs.js, graylog2-web-interface/src/components/navigation/__snapshots__/NotificationBadge.test.jsx.snap, graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap
Updating Panel styles to use `default` as the default bsStyle instead of ignoring them and rendering generic Bootstrap styles.
Noticed that theming wasn't working properly in Pipeline Rules sidebar Panel
=> Panel styles with default bsStyle

graylog2-web-interface/src/components/support/SmallSupportLink.jsx
Updating layout and colors of `SmallSupportLink`
Colors were still hardcoded & layout was a little off.
=> Update colors & layout of SmallSupportLink

graylog2-web-interface/src/components/graylog/Alert.jsx, graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap
Updating Alert colors for noire support
theme all the things
=> Update Alert colors

graylog2-web-interface/src/components/common/ControlledTableListHeader.jsx, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap, graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministration.css, graylog2-web-interface/src/components/sidecars/administration/CollectorsAdministration.jsx, graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap, graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap
Updating colors for ListGroup header & buttons
=> Update header of Sidecar Administration ListGroup

graylog2-server/src/main/java/org/graylog/events/processor/DBEventDefinitionService.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java, graylog2-server/src/main/java/org/graylog/security/DBGrantService.java, graylog2-server/src/main/java/org/graylog/security/entities/EntityOwnershipService.java, graylog2-server/src/test/java/org/graylog/security/entities/EntityOwnershipServiceTest.java
=> Unregister entity ownersip upon delete

graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap, graylog2-web-interface/src/components/graylog/Nav.jsx, graylog2-web-interface/src/components/navigation/__snapshots__/NotificationBadge.test.jsx.snap
Changing up some color variables for better dark mode support
Dark mode was rendering incorrect colors
- Fields is `active`
- Event Details is `hover`
=> Updating Wizard nav color for noire

graylog2-web-interface/src/components/common/PageSizeSelect.jsx, graylog2-web-interface/src/components/common/PaginatedList.test.jsx, graylog2-web-interface/src/components/common/TimezoneSelect.jsx, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap, graylog2-web-interface/src/components/users/LegacyTimeoutInput.jsx, graylog2-web-interface/src/components/users/NewUserForm.jsx, graylog2-web-interface/src/components/users/TimeoutUnitSelect.jsx, graylog2-web-interface/src/components/users/UserForm.jsx, graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap, graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap
Fix frontend linter warnings for current permissions feature branch.
=> Fix permissions linter warnings

graylog2-web-interface/src/actions/permissions/EntityShareActions.js, graylog2-web-interface/src/components/common/SearchForm.jsx, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEntitiesList.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameterList.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameters.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackPreview.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap, graylog2-web-interface/src/components/permissions/EntityShareModal.jsx, graylog2-web-interface/src/components/permissions/EntityShareSettings.jsx, graylog2-web-interface/src/components/users/PaginatedItem.jsx, graylog2-web-interface/src/components/users/UserDetails/SharedEntitiesOverview.jsx, graylog2-web-interface/src/components/users/UserDetails/SharedEntitiesSection.jsx, graylog2-web-interface/src/components/users/UserDetails/UserDetails.jsx, graylog2-web-interface/src/components/users/UserEdit/RolesSection.jsx, graylog2-web-interface/src/stores/permissions/EntityShareStore.js, graylog2-web-interface/src/stores/users/UsersStore.js, graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap, graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap
Please have a look at the commit message for more details
=> Further improvements for user management ui and entity share modal

graylog2-web-interface/src/components/graylog/Navbar.jsx
This PR unifies the navigation dropdown text color with navigation text color.
=> Unify navigation dropdown text color with navigation text color

graylog2-web-interface/src/theme/breakpoints.js, graylog2-web-interface/src/theme/colors.js, graylog2-web-interface/src/theme/fonts.js, graylog2-web-interface/src/theme/index.js, graylog2-web-interface/src/theme/utils/index.js
Adding `themePropTypes` to theme
A PropType to reference for components using `withTheme`
=> Theme PropTypes

graylog2-server/src/main/java/org/graylog/grn/GRNRegistry.java, graylog2-server/src/main/java/org/graylog/security/DBGrantService.java, graylog2-server/src/main/java/org/graylog/security/rest/EntitySharesResource.java, graylog2-server/src/main/java/org/graylog/security/shares/DefaultGranteeService.java, graylog2-server/src/main/java/org/graylog/security/shares/EntityShareResponse.java
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#1676
=> Use GRNs instead of Strings in AvailableGrantee model

graylog2-server/src/main/java/org/graylog/grn/GRNTypes.java, graylog2-web-interface/src/views/components/ViewTypeLabel.js, graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.jsx, graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.test.jsx, graylog2-web-interface/src/views/components/sidebar/ContentColumn.jsx
Implement EntityShareModal for saved searches.
Sharing a saved search is currently not possible, because the type search is not supported yet.
=> Implement EntityShareModal for saved searches

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Elasticsearch7Module.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/RestHighLevelClientProvider.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/client/ESCredentialsProvider.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ElasticsearchInstanceES7.java
This change is adding a credentials provider for the rest client for ES7
connections that contains the authentication details for configured
connections. This allows the ES7 storage driver module to connect to
authenticated ES nodes.
=> Providing credentials for ES7 connections requiring authentication.

graylog2-web-interface/src/components/common/PageHeader.jsx, graylog2-web-interface/src/components/support/SupportLink.jsx, graylog2-web-interface/src/components/users/navigation/UserActionLinks.jsx, graylog2-web-interface/src/components/users/navigation/UserOverviewLinks.jsx, graylog2-web-interface/src/pages/UserCreatePage.jsx, graylog2-web-interface/src/pages/UserDetailsPage.jsx, graylog2-web-interface/src/pages/UserEditPage.jsx, graylog2-web-interface/src/pages/UserTokensEditPage.jsx, graylog2-web-interface/src/pages/UsersOverviewPage.jsx, graylog2-web-interface/src/routing/Routes.jsx, graylog2-web-interface/src/theme/GlobalThemeStyles.jsx
_All checks should pass after https://github.com/Graylog2/graylog2-server/pull/8705 got merged_
* Add subaction for PageHeader
* Define flow types for PageHeader
* Create UserOverviewLinks and UserActionLinks component to unify subnavigation
* Make plugin routes accessible
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#1696
=> Improve user management subnavigation

graylog2-web-interface/src/components/users/UsersOverview/UsersFilter.jsx, graylog2-web-interface/src/components/users/UsersQueryHelper.jsx
Prior to this change, the query helper for users query was inside
of UsersFilter, but it was also needed on other places.
This change extracts the Helper component for reuseablitity.
=> Extract Users query helper

graylog2-web-interface/src/components/common/SourceCodeEditor.jsx
Updating colors on SourceCodeEditor toolbar buttons
=> Updated SourceCodeEditor toolbar button colors

graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap, graylog2-web-interface/src/components/graylog/ListGroupItem.jsx, graylog2-web-interface/src/components/graylog/Popover.jsx, graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternFilter.test.jsx.snap, graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap, graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap, graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap, graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchForm.test.jsx.snap, graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap, graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap
ListGroupItem and Popover styles needed a little adjusting from more recent theme variable changes
Theme All The Things!
=> Popover listgroupitem styles

graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20200730000000_AddGl2MessageIdFieldAliasForEvents.java, graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchClientConfiguration.java, graylog2-server/src/main/java/org/graylog2/configuration/converters/MajorVersionConverter.java, graylog2-server/src/main/java/org/graylog2/configuration/validators/ElasticsearchVersionValidator.java, graylog2-server/src/main/java/org/graylog2/storage/VersionAwareProvider.java, graylog2-server/src/main/java/org/graylog2/storage/providers/ClusterAdapterProvider.java, graylog2-server/src/main/java/org/graylog2/storage/providers/CountsAdapterProvider.java, graylog2-server/src/main/java/org/graylog2/storage/providers/ElasticsearchBackendProvider.java, graylog2-server/src/main/java/org/graylog2/storage/providers/IndexFieldTypePollerAdapterProvider.java, graylog2-server/src/main/java/org/graylog2/storage/providers/IndexToolsAdapterProvider.java, graylog2-server/src/main/java/org/graylog2/storage/providers/IndicesAdapterProvider.java, graylog2-server/src/main/java/org/graylog2/storage/providers/MessagesAdapterProvider.java, graylog2-server/src/main/java/org/graylog2/storage/providers/MoreSearchAdapterProvider.java, graylog2-server/src/main/java/org/graylog2/storage/providers/NodeAdapterProvider.java, graylog2-server/src/main/java/org/graylog2/storage/providers/SearchesAdapterProvider.java, graylog2-server/src/main/java/org/graylog2/storage/providers/V20170607164210_MigrateReopenedIndicesToAliasesClusterStateAdapterProvider.java, graylog2-server/src/main/java/org/graylog2/storage/providers/V20200730000000_AddGl2MessageIdFieldAliasForEventsElasticsearchAdapterProvider.java, graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20200730000000_AddGl2MessageIdFieldAliasForEventsTest.java
After this change, we are using a `Version` object instead of a plain `String` for the Elasticsearch version in use, allowing us to do better comparisons e.g. in migrations.
=> Use proper `Version` object to track ES version.

graylog2-web-interface/src/components/support/SupportLink.jsx
`SmallSupportLink` got styled, but `SupportLink` never did.
=> SupportLink IconStack colors & flow-typing

graylog-storage-elasticsearch6/pom.xml, graylog-storage-elasticsearch7/pom.xml
This PR is bumping the ES dependencies used to the newest shaded
versions to enable the usage of relocated source jars.
=> Bumping ES dependencies to allow using relocated source jars.

graylog2-web-interface/src/theme/GlobalThemeStyles.jsx
Adding default styles for `input`s that aren't `Inputs` or `FormControl`
=> Global input Styles

graylog2-web-interface/src/components/users/TimeoutInput.jsx, graylog2-web-interface/src/components/users/TimeoutUnitSelect.jsx, graylog2-web-interface/src/components/users/timeoutConstants.js
Updating layout in User Authentication for Timeout inputs.
Using `Select` component like the rest of the page
Regular select looked odd in a sea of Select component
=> Update styles in TimeoutInput for User Auth

graylog2-web-interface/src/views/components/visualizations/GenericPlot.jsx
Adding in theme color variables so it will work properly in dark mode
=> Graph Theming

graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java, graylog2-server/src/main/java/org/graylog/security/entities/EntityOwnershipService.java
=> Distinguish ownership registration between dashboard and saved search

graylog2-web-interface/src/components/navigation/InactiveNavItem.jsx, graylog2-web-interface/src/components/navigation/Navigation.jsx, graylog2-web-interface/src/components/navigation/__snapshots__/NotificationBadge.test.jsx.snap
Remove background on the Header Nav Badges during hover and focus
The `InactiveNav` component is still responding to `hover` and `focus`
=> Fix Header Nav Badge background hover

graylog2-web-interface/src/actions/roles/AuthzRolesActions.js, graylog2-web-interface/src/components/navigation/SystemMenu.jsx, graylog2-web-interface/src/components/navigation/SystemMenu.test.jsx, graylog2-web-interface/src/components/roles/RolesOverview/ActionsCell.jsx, graylog2-web-interface/src/components/roles/RolesOverview/RolesFilter.jsx, graylog2-web-interface/src/components/roles/RolesOverview/RolesOverview.jsx, graylog2-web-interface/src/components/roles/RolesOverview/RolesOverviewItem.jsx, graylog2-web-interface/src/components/roles/RolesOverview/index.js, graylog2-web-interface/src/components/roles/RolesQueryHelper.jsx, graylog2-web-interface/src/pages/RolesOverviewPage.jsx, graylog2-web-interface/src/pages/index.jsx, graylog2-web-interface/src/routing/ApiRoutes.js, graylog2-web-interface/src/routing/AppRouter.jsx, graylog2-web-interface/src/routing/Routes.jsx, graylog2-web-interface/src/stores/roles/AuthzRolesStore.js
* Including route, page, and nav item
We need to merge https://github.com/Graylog2/graylog2-server/pull/8705 + the related enterprise PR first.
=> Implement new roles overview

graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.jsx
=> Fix UsersOverview pagination reset

graylog2-web-interface/src/components/navigation/Navigation.jsx, graylog2-web-interface/src/components/navigation/UserMenu.jsx, graylog2-web-interface/src/components/users/UserDetails/UserDetails.jsx, graylog2-web-interface/src/components/users/UserDetails/UserDetails.test.jsx, graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx, graylog2-web-interface/src/components/users/UserEdit/UserEdit.test.jsx, graylog2-web-interface/src/components/users/UserManagementLinks.jsx, graylog2-web-interface/src/components/users/navigation/UserOverviewLinks.jsx
The navbar has a profile link which directs the user to his profile
page. Dependening on his role and permissions he can edit this profile
accordingly.
To make sure he can only see what he is allowed to see and to make
sure he does not get errors from missing permissions IfPermitted
components will now filter the sections.
Fixes #8748 
=> User profile link

graylog2-web-interface/src/components/common/__snapshots__/Wizard.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackApplyParameter.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackDetails.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackEdit.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackInstall.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackParameters.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackPreview.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPackSelection.test.jsx.snap, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap, graylog2-web-interface/src/components/graylog/Row.jsx, graylog2-web-interface/src/components/grok-patterns/__snapshots__/GrokPatternInput.test.jsx.snap, graylog2-web-interface/src/components/login/__snapshots__/LoginBox.test.jsx.snap, graylog2-web-interface/src/components/lookup-tables/__snapshots__/DataAdapterCreate.test.jsx.snap, graylog2-web-interface/src/components/users/__snapshots__/PermissionSelector.test.jsx.snap, graylog2-web-interface/src/components/users/__snapshots__/TokenList.test.jsx.snap, graylog2-web-interface/src/pages/__snapshots__/ShowMessagePage.test.jsx.snap, graylog2-web-interface/src/views/components/__snapshots__/WidgetQueryControls.test.jsx.snap, graylog2-web-interface/src/views/hooks/__snapshots__/RequirementsProvided.test.jsx.snap
I adjusted the Row border mainly for the noir version, the change does (on purpose) not really change the teint version.
Teint version (before):
Teint version (after):
Noir version (before):
Noir version (after):
=> Adjust Row border color

graylog2-web-interface/src/views/components/visualizations/GenericPlot.jsx
Updated colors of Graph titles
Graph X and Y axis titles were difficult to read in Noir
=> Update title colors for Graphs

graylog2-web-interface/src/components/notifications/Notification.jsx
Updated styles for Notification close button
Button in Notification was difficult to see
=> Update button styles on Notification

graylog2-web-interface/src/components/common/PageSizeSelect.jsx, graylog2-web-interface/src/components/content-packs/__snapshots__/ContentPacksList.test.jsx.snap, graylog2-web-interface/src/components/permissions/EntityShareModal.jsx, graylog2-web-interface/src/components/permissions/EntityShareSettings.jsx, graylog2-web-interface/src/components/permissions/GranteesList.jsx, graylog2-web-interface/src/components/users/UserCreate/UserCreate.jsx, graylog2-web-interface/src/components/users/UserCreate/UserCreate.test.jsx, graylog2-web-interface/src/components/users/UsersOverview/UserOverviewItem/LoggedInCell.jsx, graylog2-web-interface/src/components/users/UsersOverview/UserOverviewItem/UsersOverviewItem.jsx, graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchList.test.jsx.snap, graylog2-web-interface/src/views/components/widgets/__snapshots__/CopyToDashboardForm.test.jsx.snap
This is a collection of small UI improvements for the Permissions / management components. Please have look at the commit messages for a list of all changes.
=> Permissions / management UI improvements

graylog2-web-interface/src/components/common/Wizard.test.jsx, graylog2-web-interface/src/components/common/__snapshots__/Pagination.test.jsx.snap, graylog2-web-interface/src/components/graylog/__snapshots__/ProgressBar.test.jsx.snap, graylog2-web-interface/src/components/login/__snapshots__/LoginBox.test.jsx.snap, graylog2-web-interface/src/pages/__snapshots__/ShowMessagePage.test.jsx.snap, graylog2-web-interface/src/views/components/aggregationbuilder/__snapshots__/EventListConfiguration.test.jsx.snap, graylog2-web-interface/src/views/components/visualizations/number/Trend.test.jsx, graylog2-web-interface/src/views/components/widgets/__snapshots__/Widget.test.jsx.snap, graylog2-web-interface/test/wrappedEnzyme.jsx, graylog2-web-interface/test/wrappedTestingLibrary.jsx
_Accidentally merged #8075 early - recreating PR_
Use [jest-styled-components](https://github.com/styled-components/jest-styled-components) in all tests.
Needs Enterprise snapshot update:
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#1567
Each time a snapshot changes from a styled-component update, it just generates a new className, just causing noise in the PRs.
This will render out the CSS instead of the className so that we can review what was actually changed in the render snapshot
=> Jest styled components

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MessagesAdapterES7.java, graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesIT.java
This change is using the configured system-wide `ObjectMapper` instance to serialize the body of new messages supposed to be bulk indexed by Elasticsearch when creating the request. This change is required for ES7, as it does not allow configuring a custom `ObjectMapper` instance to be used for serialization, in contrast to `Jest` which is used for ES6.
=> Serialize body of new messages using object mapper for ES7.

graylog2-server/src/main/java/org/graylog/security/shares/GranteeSharesService.java
=> Return correct total number in PaginatedList

graylog2-web-interface/src/components/common/PaginatedItemOverview/PaginatedItem.jsx, graylog2-web-interface/src/components/common/PaginatedItemOverview/PaginatedItemOverview.jsx, graylog2-web-interface/src/components/graylog/__mocks__/Tooltip.jsx, graylog2-web-interface/src/components/permissions/RolesSelector.jsx, graylog2-web-interface/src/components/roles/RoleDetails/RoleDetails.test.jsx, graylog2-web-interface/src/components/roles/RoleDetails/UsersSection.jsx, graylog2-web-interface/src/components/roles/RoleEdit/RoleEdit.test.jsx, graylog2-web-interface/src/components/roles/RoleEdit/UsersSelector.jsx, graylog2-web-interface/src/components/roles/RolesOverview/ActionsCell.jsx, graylog2-web-interface/src/components/roles/RolesOverview/ActionsCell.test.jsx, graylog2-web-interface/src/components/roles/RolesOverview/RolesOverview.test.jsx, graylog2-web-interface/src/components/users/UserDetails/UserDetails.test.jsx, graylog2-web-interface/src/components/users/UserEdit/UserEdit.test.jsx, graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.test.jsx, graylog2-web-interface/test/fixtures/roles.js, graylog2-web-interface/test/fixtures/sharedEntities.js, graylog2-web-interface/test/fixtures/userOverviews.jsx
This PR contains a few tests which are commented out, because it fails occasionally. I will fix this problem in a follow-up PR.
Fixes: https://github.com/Graylog2/graylog2-server/issues/8757
Fixes: https://github.com/Graylog2/graylog2-server/issues/8760
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#1754
=> Add more tests for user and roles management UI

graylog2-web-interface/package.json, graylog2-web-interface/src/components/common/SortableList.jsx, graylog2-web-interface/yarn.lock
- Bump `react-dnd` from 7.7.0 to 11.1.3
- Bump `react-dnd-html5-backend` from 2.6.0 to 11.1.3
https://github.com/Graylog2/graylog2-server/pull/8731
https://github.com/Graylog2/graylog2-server/pull/8254
=> react-dnd & react-dnd-html5-backend library updates

graylog2-server/src/main/java/org/graylog/security/DefaultGrantPermissionResolver.java, graylog2-server/src/main/java/org/graylog/security/GrantPermissionResolver.java, graylog2-server/src/main/java/org/graylog/security/GrantsAuthorizingRealm.java, graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java, graylog2-server/src/test/java/org/graylog2/users/UserServiceImplTest.java
=> Retrieve roles from GrantPermissionResolver

graylog2-web-interface/src/components/common/Wizard.jsx
This PR adds flow type definitions for the Wizard component.
=> Add flow type definitions for Wizard

graylog2-server/src/test/java/org/graylog2/security/ldap/LdapConnectorSSLTLSIT.java
StartTLS does not work against the SSL port
=> Use correct port for StartTLS

graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java, graylog2-server/src/main/java/org/graylog2/plugin/DocsHelper.java, graylog2-server/src/main/java/org/graylog2/shared/UI.java, graylog2-server/src/main/java/org/graylog2/storage/UnsupportedElasticsearchException.java, graylog2-server/src/main/java/org/graylog2/storage/providers/ElasticsearchVersionProvider.java, graylog2-server/src/main/java/org/graylog2/storage/versionprobe/ElasticsearchProbeException.java, graylog2-server/src/main/java/org/graylog2/storage/versionprobe/VersionProbe.java
Before this change, connecting against an unsupported ES node or failing to probe the version of the running cluster resulted in a messy guice exception. This change is throwing more specific exceptions in providers and catching them in `CmdLineTool`, adding helpful error messages and document links and bailing out in these case.
=> Provide helpful error messages for ES misconfiguration/errors.

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Elasticsearch7Module.java
In #8514, the ES7 implementation for the `IndexToolsAdapter` was created, but forgot to be bound. This change is catching up on that.
=> Bind `IndexToolsAdapter` for ES7.

graylog2-web-interface/src/contexts/StreamsContext.jsx, graylog2-web-interface/src/contexts/StreamsProvider.jsx, graylog2-web-interface/src/pages/LoggedInPage.jsx, graylog2-web-interface/src/pages/UserHasNoStreamAccess.jsx, graylog2-web-interface/src/views/components/IfUserHasAccessToAnyStream.jsx, graylog2-web-interface/src/views/pages/NewSearchPage.jsx, graylog2-web-interface/src/views/pages/NewSearchPage.test.jsx, graylog2-web-interface/src/views/stores/StreamsStore.js
Before this change, the user was seeing a "Missing stream permissions" page, that did not show a helpful error message if the user is not missing the permission for a specific stream, but for any stream at all.
This change is now checking if the user is having any stream permissions at all and shows a better message otherwise.
Fixes #8955.
=> Show better error message when user has no stream permissions.

graylog2-web-interface/src/pages/ConfigurationsPage.jsx
=> Fix race conditions on system/configuration

graylog2-web-interface/src/components/pipelines/ProcessingTimelineComponent.jsx
Add `title` attribute to Pipeline Title Link so full Pipeline name is visible on hover
Fixes #9014
=> Adding title attr to Pipeline Title Link

graylog2-web-interface/src/components/pipelines/ProcessingTimelineComponent.jsx
Add `title` attribute to Pipeline Title Link so full Pipeline name is visible on hover
Fixes #9014
=> Adding title attr to Pipeline Title Link (3.3)

graylog2-web-interface/packages/eslint-config-graylog/index.js
This change is enabling the ESLint plugin checking the [Rules of Hooks](https://reactjs.org/docs/hooks-rules.html).
=> Enable ESLint Rules of Hooks.

graylog2-web-interface/src/components/graylog/Label.jsx, graylog2-web-interface/src/components/inputs/InputStateBadge.jsx
The colors of warning and danger were effectively swapped for what the UI is trying to present to the User. Updated the colors, but the text itself could probably use some massaging in the future.
Sort of fixes #9036
=> Input Status Labels

graylog2-web-interface/yarn.lock
This change is solely updating the browserslist DB, so we are building against the most recent database of target browsers. This should not affect our build, as we are not using a browserslist query, it just removes the warning.
=> Update browserslist DB.

graylog-storage-elasticsearch7/pom.xml, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/RestHighLevelClientProvider.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ElasticsearchInstanceES7.java
This change is implementing request/response compression for Elasticsearch 7. It also requires an update of the client library to 7.9.1, as it now includes transparent decompression for both the high- and the low-level-client.
`elasticsearch_compression_enabled` has been set to `true` in the config file. Basic indexing/search/cluster management functionality has been tested after server restart.
=> Implementing compression for Elasticsearch 7.

graylog2-web-interface/package.json, graylog2-web-interface/packages/graylog-web-plugin/package.json, graylog2-web-interface/src/logic/notifications/NotificationsFactory.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/PivotConfiguration.jsx, graylog2-web-interface/src/views/components/aggregationbuilder/PivotConfiguration.test.jsx, graylog2-web-interface/yarn.lock
Merges 3.3 into cloud-3.3. This time with the right base branch :)
=> Sync cloud branch with current 3.3. branch
