graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.jsx, graylog2-web-interface/src/views/components/widgets/Widget.jsx, graylog2-web-interface/src/views/components/widgets/Widget.test.jsx, graylog2-web-interface/src/views/logic/views/Actions.js
This change is fixing some places where `browserHistory` from `react-router` was used directly. Initially, they were just replace with `util/History`, but then it was decided to use actions instead, which lend themselves for cleaner interfaces, centralisation of routing logic and better testing.
=> Use abstraction instead of `browserHistory`.

graylog2-server/src/main/java/org/graylog2/streams/StreamServiceImpl.java
Streams contain references to their outputs by storing an array of output ids in their documents. If the outputs which are referenced by these IDs get missing, the server will fail to start (see Graylog2/graylog2-server#9012). This happens, because instead of the output `null` is returned from an identity map during output lookup.
This change is doing two things:
- ensure that the output list a stream is initialized with does not contain `null` values
- logs a warning that a stream is referencing a missing output
Fixes #9012.
=> Prevent NPEs if streams are referencing missing outputs.

full-backend-tests/pom.xml, graylog-plugin-archetype/pom.xml, graylog-plugin-parent/graylog-plugin-web-parent/pom.xml, graylog-plugin-parent/pom.xml, graylog-project-parent/pom.xml, graylog2-server/pom.xml, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/DashboardsResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SavedSearchesResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewPermissionChecks.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewsResource.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewPermissionChecksTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewsResourceTest.java, graylog2-web-interface/manifests/package.json, graylog2-web-interface/package.json, graylog2-web-interface/packages/graylog-web-plugin/package.json, graylog2-web-interface/src/views/components/aggregationbuilder/DescriptionBox.jsx, graylog2-web-interface/src/views/components/common/EditableTitle.jsx, graylog2-web-interface/src/views/components/common/EditableTitle.test.jsx, graylog2-web-interface/src/views/components/widgets/FieldSortIcon.jsx, integration-tests/pom.xml, pom.xml
Merges 3.3 into cloud-3.3, also bumping the Graylog version to 3.3.8-SNAPSHOT
=> Sync cloud branch with current 3.3 branch

graylog2-web-interface/src/pages/AuthenticationPage.jsx
In #9118 a change slipped in that removes the registration of
authentication components (it is moved in a future PR to the `AppRouter`
component). This leads to the "Change Provider Order" subsection of the
System/Authentication page to have blank table cells, as well as the
subnavigation on the left showing short identifiers.
This change is now putting the registration back in to fix this.
=> Re-register authentication components.

graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java, graylog2-server/src/test/java/org/graylog2/users/UserServiceImplTest.java
Use the correct userFactory.create() method
=> Don't create User objects with random objectIDs

graylog2-server/src/main/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/GrantsMetaMigration.java, graylog2-server/src/main/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/ViewOwnerShipToGrantsMigration.java
=> Only run GrantsMigrations once

graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendQueryStringDecoratorsTest.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendQueryStringDecoratorsTest.java, graylog2-server/src/test/java/org/graylog2/security/ldap/LdapConnectorSSLTLSIT.java, graylog2-server/src/test/java/org/graylog2/shared/security/SessionCreatorTest.java
In some of our tests usages of IntelliJ's `@NotNull` annotation have slipped in. This change is removing them and replacing them with `javax.annotation.Nonnull`.
=> Remove IntelliJ's `@NotNull` annotations.

graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/ServerConfigStep.jsx, graylog2-web-interface/src/pages/AuthenticationBackendDetailsPage.jsx, graylog2-web-interface/src/pages/AuthenticationOverviewPage.jsx, graylog2-web-interface/src/pages/AuthenticationPage.jsx
This PR fixes various console warnings which occured in the permissions UI.
=> Fix permissions UI console warnings

graylog2-server/src/main/java/org/graylog/grn/GRNModule.java, graylog2-server/src/main/java/org/graylog/grn/GRNTypes.java, graylog2-web-interface/src/logic/permissions/GRN.js
Plus some frontend pieces
Also: Rename the GRN type from `notification` to `event_notification`
for consistency.
=> Add missing EventNotificationGRNDescriptorProvider

graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodical.java, graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodicalTest.java
Before this change, the scheduled index field type poller run might be performed when the server is halting (or in any state that is not running). This could lead to the run being started when the ES client is already shut down.
This change is now doing a check in the scheduled run just as in #8818 for the general periodical run. The check was consciously not inlined to the `IndexFieldTypePoller` class, to keep it decoupled from the server's lifecycle.
=> Skip scheduled index field type poller run if server is not running.

graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java, graylog2-server/src/main/java/org/graylog2/users/events/UserDeletedEvent.java
This allows plugins to react to user deletions.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#1847
=> Publish a UserDeletedEvent on user deletion

graylog2-server/src/main/java/org/graylog/security/DefaultPermissionAndRoleResolver.java, graylog2-server/src/main/java/org/graylog/security/PermissionAndRoleResolver.java, graylog2-server/src/main/java/org/graylog/security/SecurityModule.java, graylog2-server/src/main/java/org/graylog2/security/realm/MongoDbAuthorizationRealm.java, graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java, graylog2-server/src/test/java/org/graylog2/users/UserServiceImplTest.java
Refs Graylog2/graylog-plugin-enterprise#1764
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#1851
=> Rename GrantPermissionResolver to PermissionAndRoleResolver

graylog2-server/src/main/java/org/graylog/security/DBGrantService.java, graylog2-server/src/main/java/org/graylog/security/rest/GrantsOverviewResource.java, graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java
This will be helpful for debugging permission issues.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#1852
=> Add /authz/grants-overview endpoint

graylog2-web-interface/src/pages/SidecarsPage.jsx
This change was missing in the user management refactoring.
=> Fix route to user tokens page

distribution/pom.xml
This unbreaks the project build.
=> Revert jar -> pom packaging change in distribution

graylog2-web-interface/package.json, graylog2-web-interface/packages/graylog-web-plugin/package.json, graylog2-web-interface/yarn.lock
Recently, `webpack-cli` was upgraded to v4.x. It was found out, that it contains a regression that causes failing builds (e.g. due to a missing npm dependency) do not result in a non-zero error code, effectively preventing build pipelines to abort in an error case. While this seems to be fixed in a PR (webpack/webpack-cli#1971), it is not included in any released version at this time.
Therefore this change is downgrading `webpack-cli` to the most recent 3.x version. As we do not rely on any changes in 4.x, we can safely go back to have a version which is working as expected for the upcoming release of Graylog 4.x. During the next development iteration we can retry the upgrade of `webpack-cli`, hoping that these kinds of issues had been ironed out by then.
=> Downgrading webpack-cli to v3.3.12.

graylog2-web-interface/src/pages/UserHasNoStreamAccess.jsx, graylog2-web-interface/src/views/pages/ShowViewPage.test.jsx
This small change is using a different layout for the page a user is
redirected to when a search is started, but the user does not have
access to any stream. Before this change, it was the error page layout,
which indicates to the user that this an error and not a condition.
After this change, a friendlier variant is used.
Fixes #9174.
=> Show friendlier page when user has no stream access.

graylog2-web-interface/src/views/components/visualizations/GenericPlot.jsx
=> Use proper colors for pie chart outer labels

graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
=> Add deleteForGrantee() to DBGrantService

graylog2-server/src/main/java/org/graylog2/bindings/PeriodicalBindings.java, graylog2-server/src/main/java/org/graylog2/notifications/Notification.java, graylog2-server/src/main/java/org/graylog2/periodical/ESVersionCheckPeriodical.java, graylog2-server/src/main/java/org/graylog2/storage/VersionAwareProvider.java, graylog2-server/src/main/java/org/graylog2/storage/providers/ElasticsearchVersionProvider.java, graylog2-server/src/main/java/org/graylog2/storage/versionprobe/VersionProbe.java, graylog2-server/src/test/java/org/graylog2/periodical/ESVersionCheckPeriodicalTest.java, graylog2-web-interface/src/logic/notifications/NotificationsFactory.js, graylog2-web-interface/src/util/DocsHelper.js
Starting with 4.x, the ES version is probed during startup and the code corresponding to the major version is bound. If ES is upgraded to a different major version while Graylog is running, the ES code bound might not be compatible to the ES version running. This can result in indexing/search errors.
To inform users about this condition, this PR is adding a periodical running every 30 seconds, which probes for the current ES version and compares it against the one probed initially during startup. If both are incompatible, a system notification is raised. If they are compatible, it is fixed. If either the version is overridden manually or no version can be probed, no change is performed (although an error is logged in the latter case).
An initial idea was to start the periodical with a …
=> Check periodically if running ES is compatible with initial ES version.

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewPermissionChecks.java
This PR makes a couple of `ViewPermissionChecks` methods public, which can be reused from other packages or plugins to check if a user is eligible for actions on a view.
=> Make view permission check methods public.

graylog2-web-interface/src/components/navigation/NavigationBrand.jsx, graylog2-web-interface/src/components/users/UserEdit/UserEdit.test.jsx
Resolves the issue of the logo floating away after some recent Router upgrades
Fixes a test that fails on some versions of `node`
=> Fixing logo floating away and failing test on master

full-backend-tests/pom.xml, full-backend-tests/src/test/java/org/graylog/elasticsearch/e2e/ElasticsearchE2E.java, full-backend-tests/src/test/java/org/graylog/elasticsearch/e2e/ElasticsearchE2EES6.java, full-backend-tests/src/test/java/org/graylog/elasticsearch/e2e/ElasticsearchE2EES7.java, full-backend-tests/src/test/java/org/graylog/plugins/views/MessagesResourceES6IT.java, full-backend-tests/src/test/java/org/graylog/plugins/views/MessagesResourceES7IT.java, full-backend-tests/src/test/java/org/graylog/plugins/views/MessagesResourceIT.java, full-backend-tests/src/test/java/org/graylog/storage/elasticsearch7/ElasticsearchInstanceES7Factory.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ElasticsearchInstanceES7.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/FixtureImporterES7.java, graylog2-server/src/test/java/org/graylog/testing/graylognode/MavenPackager.java, graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerFactory.java
Before this change, the tests in the `full-backend-tests` module did rung against ES6 only. This change is adding support for ES7 as well.
In addition, it reenables the tests by changing the packaging type back to `jar`.
=> Run against ES7 in full backend tests as well.

graylog2-server/src/main/java/org/graylog/security/DBGrantService.java, graylog2-server/src/main/java/org/graylog/security/shares/DefaultGranteeService.java, graylog2-server/src/main/java/org/graylog/security/shares/GranteeService.java, graylog2-server/src/main/java/org/graylog/security/shares/GranteeSharesService.java, graylog2-server/src/test/java/org/graylog/security/DBGrantServiceTest.java, graylog2-server/src/test/java/org/graylog/security/shares/GranteeSharesServiceTest.java
Refs Graylog2/graylog-plugin-enterprise#1718
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#1885
=> Include grants for "everyone" in entities for user overview

graylog2-server/src/main/java/org/graylog/security/authzroles/PaginatedAuthzRolesService.java, graylog2-server/src/main/java/org/graylog2/database/PaginatedDbService.java, graylog2-server/src/main/java/org/graylog2/shared/users/UserService.java, graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java, graylog2-server/src/test/java/org/graylog/security/authzroles/PaginatedAuthzRolesServiceTest.java, graylog2-server/src/test/java/org/graylog/testing/TestUserService.java, graylog2-server/src/test/java/org/graylog2/users/UserServiceImplTest.java
This is required for an upcoming change.
Other changes:
- Add `PaginatedAuthzRolesService#findByIds`
- Make `PaginatedDbServbice#asImmutableList` protected
=> Add UserService#loadByIds to get all users for the given IDs

graylog2-server/src/main/java/org/graylog/security/UserContext.java, graylog2-server/src/main/java/org/graylog2/rest/RestTools.java, graylog2-server/src/main/java/org/graylog2/shared/rest/RestAccessLogFilter.java, graylog2-server/src/main/java/org/graylog2/shared/security/ShiroAuthorizationFilter.java
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#1896
=> Missed a few places when converting username to userId

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ViewPermissionChecks.java
Pulls https://github.com/Graylog2/graylog2-server/pull/9295 into the `cloud-3.3` branch to fix a compilation error with the enterprise plugin.
Now that https://github.com/Graylog2/graylog-plugin-enterprise/pull/1879 has been merged, the enterprise plugin won't compile anymore with the `cloud-3.3` branch checked out.
=> Sync cloud with 3.3

graylog2-web-interface/src/views/components/datatable/DataTable.jsx, graylog2-web-interface/src/views/components/datatable/DataTableEntry.jsx, graylog2-web-interface/src/views/components/datatable/DataTableEntry.test.jsx, graylog2-web-interface/src/views/components/messagelist/FormatNumber.js, graylog2-web-interface/src/views/components/messagelist/IsNumeric.js, graylog2-web-interface/src/views/components/messagelist/IsNumeric.test.js, graylog2-web-interface/src/views/components/messagelist/PossiblyHighlight.jsx, graylog2-web-interface/src/views/components/visualizations/XYPlot.jsx, graylog2-web-interface/src/views/components/visualizations/__tests__/XYPlot.test.jsx, graylog2-web-interface/src/views/components/visualizations/area/__tests__/AreaVisualization.test.jsx, graylog2-web-interface/src/views/components/visualizations/number/NumberVisualization.jsx, graylog2-web-interface/src/views/components/visualizations/number/NumberVisualization.test.jsx
Before this change, numbers in data tables and plots were formatted differently. Numbers in plots were using a point to separate 1000s, data tables did not contain any separators. This was inconsistent and suboptimal concerning readability.
This change is adding a number formatter/changes plotly's tickformat, so numbers are formatted consistently using a decimal comma for 1000s and a decimal point for floating point numbers.
Only values coming from functions/series are reformatted. This is because these are generally quantitative units, which might not hold true for message fields (e.g. `ingest_time_year` containing years, or `http_status_code` containing literals representing status codes).
A dashboard was created, containing:
- a number widget with a plain series
- a number widget with …
=> Format numbers in data table/plots with decimal comma.

graylog2-server/src/main/java/org/graylog/security/authzroles/AuthzRolesResource.java, graylog2-server/src/main/java/org/graylog/security/rest/EntitySharesResource.java, graylog2-server/src/main/java/org/graylog/security/rest/GrantsOverviewResource.java, graylog2-web-interface/src/routing/ApiRoutes.js
- Change "/shares" to "/authz/shares"
- Change "/authzRoles" to "/authz/roles"
- Update Api annotation descriptions
- Update two paths inside the AuthzRolesResource
Closes #9080
=> Refactor resource paths for consistency

graylog2-web-interface/src/util/UserNotification.css, graylog2-web-interface/src/util/UserNotification.js
Add `Click to Close` to UserNotification banner
Fixes #9251
=> Adding "Click to Close" to UserNotification

graylog2-server/src/main/java/org/graylog/events/notifications/DBNotificationService.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java, graylog2-server/src/main/java/org/graylog/security/authzroles/AuthzRoleDTO.java, graylog2-server/src/main/java/org/graylog/security/authzroles/PaginatedAuthzRolesService.java, graylog2-server/src/main/java/org/graylog/security/entities/EntityOwnershipService.java, graylog2-server/src/main/java/org/graylog2/streams/StreamServiceImpl.java, graylog2-server/src/test/java/org/graylog/security/authzroles/PaginatedAuthzRolesServiceTest.java, graylog2-server/src/test/java/org/graylog/security/entities/EntityOwnershipServiceTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/StreamCatalogTest.java, graylog2-server/src/test/java/org/graylog2/streams/StreamServiceImplTest.java
- Cleanup grants for streams, searches and event notifications
- Remove role from users on role deletion
Fixes #8857
Fixes #9349
=> Cleanup role and grant references

pom.xml
We have been using a release candidate before.
=> Update from RC to final version of testcontainers 1.15.0

graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
=> Don't allow modifications of email and full name for external users

graylog2-server/src/main/java/org/graylog/schema/GraylogSchemaFields.java, graylog2-server/src/main/java/org/graylog2/plugin/Message.java
This change is changing the check for fields which are exempt from traffic accounting to include fields used in Graylog Illuminate.
Fixes #9361.
=> Exempt Illuminate Fields from Traffic Accounting.

graylog2-server/src/main/java/org/graylog/security/DBGrantService.java, graylog2-server/src/main/java/org/graylog/security/rest/GrantsOverviewResource.java
This makes it easier to work with the result.
=> Use List instead of Set to keep default sort order of grants

graylog2-server/src/main/java/org/graylog2/security/UserSessionTerminationListener.java, graylog2-server/src/main/java/org/graylog2/shared/security/SecurityBindings.java
Subscribe to "UserChangedEvent" and terminate active sessions when a
user is deleted or disabled.
=> Terminate active sessions for disabled users

bin/graylogctl, graylog2-server/src/test/resources/org/graylog/testing/graylognode/Dockerfile
=> Enable jdk.tls.acknowledgeCloseNotify by default

bin/graylogctl, graylog2-server/src/test/resources/org/graylog/testing/graylognode/Dockerfile
Fixes #9445
(cherry picked from commit 4d0cf3dda77dd4d0e566f096b4e2fcccf96334c6)
=> Enable jdk.tls.acknowledgeCloseNotify by default (#9446)

graylog2-server/src/main/java/org/graylog/security/rest/EntitySharesResource.java
=> Remove unused endpoint

graylog2-web-interface/manifests/package.json, graylog2-web-interface/packages/graylog-web-plugin/package.json
This needs to be backported to the 4.0 branch as well.
=> Some more license fixes for SSPL

graylog2-web-interface/packages/eslint-config-graylog/index.js, graylog2-web-interface/packages/eslint-config-graylog/package.json
**Note:** This PR requires #9411 to be merged before.
This PR is doing the required changes to support linting TypeScript files with ESLint. It adds the matching parser for `.ts(x)` files and adds its rules.
Also, it employs the `recommended` rule set for TypeScript files. Some rules from core are extended with specific TypeScript versions, so the core ones must be disabled. More information can be found [here](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#i-am-using-a-rule-from-eslint-core-and-it-doesnt-work-correctly-with-typescript-code).
=> Support TypeScript in ESLint.

graylog2-web-interface/src/pages/SystemOverviewPage.jsx
Hides ES cluster info and systems jobs from system overview
https://github.com/Graylog2/graylog-plugin-cloud/issues/96
By inspecting the outcome
=> Hide ES cluster info and system jobs on systems overview page

README.markdown
Fix the license badge and remove the travis badge. (it seems to be unreliable)
=> Fix badges in README

graylog2-server/src/main/java/org/graylog2/shared/UI.java
=> Fix incorrect Commercial support link

graylog2-server/src/main/java/org/graylog2/shared/UI.java
=> Backport: Fix incorrect Commercial support link 

UPGRADING.rst
=> Update UPGRADING for 4.0

UPGRADING.rst
Co-authored-by: Marco Pfatschbacher <marco@graylog.com>
(cherry picked from commit 03952b644b47d10f3b6e1bbf954ca01745e21020)
=> Update UPGRADING for 4.0 (#9472)

graylog2-web-interface/dev/lintChanges.sh
Before this changes, the script used for the `yarn lint:changes` script
was filtering out non-js(x) files. This change is now adding ts(x) files
as well.
=> Include TypeScript files in `lintChanges` script.

graylog2-web-interface/yarn.lock
This PR is updating the yarn lockfile after a couple of TS-related PRs
where it was missed.
=> Updating yarn lockfile after TS changes.

graylog2-web-interface/tsconfig.json
This change is adding the `downlevelIteration` compiler flag, which
enables us to treat objects implementing the iterator interface as
arrays. A common use case is e.g.:
```
const dedup = [...new Set(23, 42, 17, 23)];
```
=> Enable Downlevel Iteration for TypeScript.

graylog2-server/src/main/java/org/graylog/schema/ApplicationFields.java, graylog2-server/src/main/java/org/graylog/schema/AssociatedFields.java, graylog2-server/src/main/java/org/graylog/schema/AutonomousSystemFields.java, graylog2-server/src/main/java/org/graylog/schema/ContainerFields.java, graylog2-server/src/main/java/org/graylog/schema/DestinationFields.java, graylog2-server/src/main/java/org/graylog/schema/EventFields.java, graylog2-server/src/main/java/org/graylog/schema/GeoFields.java, graylog2-server/src/main/java/org/graylog/schema/GraylogSchemaFields.java, graylog2-server/src/main/java/org/graylog/schema/HashFields.java, graylog2-server/src/main/java/org/graylog/schema/HostFields.java, graylog2-server/src/main/java/org/graylog/schema/HttpFields.java, graylog2-server/src/main/java/org/graylog/schema/NetworkFields.java, graylog2-server/src/main/java/org/graylog/schema/PolicyFields.java, graylog2-server/src/main/java/org/graylog/schema/RuleFields.java, graylog2-server/src/main/java/org/graylog/schema/SourceFields.java, graylog2-server/src/main/java/org/graylog/schema/UserFields.java
Updates to the Palo Alto input as well as ongoing work by the Security Team have led to several changes to the Graylog Schema.  This PR updates the schema constants based on those changes.
=> Updates to Graylog Schema

graylog2-server/src/main/java/org/graylog/schema/ApplicationFields.java, graylog2-server/src/main/java/org/graylog/schema/AssociatedFields.java, graylog2-server/src/main/java/org/graylog/schema/AutonomousSystemFields.java, graylog2-server/src/main/java/org/graylog/schema/ContainerFields.java, graylog2-server/src/main/java/org/graylog/schema/DestinationFields.java, graylog2-server/src/main/java/org/graylog/schema/EventFields.java, graylog2-server/src/main/java/org/graylog/schema/GraylogSchemaFields.java, graylog2-server/src/main/java/org/graylog/schema/HashFields.java, graylog2-server/src/main/java/org/graylog/schema/HostFields.java, graylog2-server/src/main/java/org/graylog/schema/HttpFields.java, graylog2-server/src/main/java/org/graylog/schema/NetworkFields.java, graylog2-server/src/main/java/org/graylog/schema/PolicyFields.java, graylog2-server/src/main/java/org/graylog/schema/RuleFields.java, graylog2-server/src/main/java/org/graylog/schema/SourceFields.java, graylog2-server/src/main/java/org/graylog/schema/UserFields.java
This is a backport of the latest Graylog Schema updates from the `master` branch to the `4.0` branch.
For details, see #9524
=> Updates to Graylog Schema (#9524)

graylog2-server/src/main/java/org/graylog/security/SecurityModule.java, graylog2-server/src/main/java/org/graylog/security/authservice/AuthServiceAuthenticator.java, graylog2-server/src/main/java/org/graylog/security/authservice/AuthServiceBackend.java, graylog2-server/src/main/java/org/graylog/security/authservice/AuthServiceResult.java, graylog2-server/src/main/java/org/graylog/security/authservice/AuthServiceToken.java, graylog2-server/src/main/java/org/graylog/security/authservice/AuthenticationDetails.java, graylog2-server/src/main/java/org/graylog/security/authservice/backend/ADAuthServiceBackend.java, graylog2-server/src/main/java/org/graylog/security/authservice/backend/LDAPAuthServiceBackend.java, graylog2-server/src/main/java/org/graylog/security/authservice/backend/MongoDBAuthServiceBackend.java, graylog2-server/src/main/java/org/graylog2/plugin/PluginModule.java, graylog2-server/src/main/java/org/graylog2/security/StaticOrderedAuthenticatingRealms.java, graylog2-server/src/main/java/org/graylog2/security/realm/AuthenticatingRealmModule.java, graylog2-server/src/main/java/org/graylog2/security/realm/BearerTokenRealm.java, graylog2-server/src/main/java/org/graylog2/security/realm/UsernamePasswordRealm.java, graylog2-server/src/main/java/org/graylog2/shared/security/SessionCreator.java, graylog2-server/src/main/java/org/graylog2/shared/security/TypedBearerToken.java
Port of #9493 from `cloud-4.0` to `master`
Because #9493 was not merged as a squashed commit, I had to create a squashed commit of the already merged changes. Please do a quick scan if everything is in included.
Port of #9493 
Smoke test if logging in via LDAP still works.
=> Implement token-based authentication #9493 (ported)

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7Test.java, graylog-storage-elasticsearch7/src/test/resources/nodes-response-without-host-field.json
In some ES implementations, the nodes API response is missing the `host`
field. Before this change, parsing it resulted in an NPE.
This change is now handling the absence of this field gracefully and
returns an empty optional.
=> Handle missing `host` field in ES' nodes API response.

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7Test.java, graylog-storage-elasticsearch7/src/test/resources/nodes-response-without-host-field.json
**Note:** This is a backport of #9596 to `4.0.`.
In some ES implementations, the nodes API response is missing the `host` field. Before this change, parsing it resulted in an NPE.
This change is now handling the absence of this field gracefully and returns an empty optional.
=> Handle missing `host` field in ES' nodes API response. (4.0)

graylog2-web-interface/src/components/users/PermissionsUpdateInfo.jsx, graylog2-web-interface/src/components/users/TimeoutInput.jsx, graylog2-web-interface/src/components/users/UserCreate/EmailFormGroup.jsx, graylog2-web-interface/src/components/users/UserCreate/FullNameFormGroup.jsx, graylog2-web-interface/src/components/users/UsersOverview/SystemAdministratorOverview.jsx, graylog2-web-interface/src/pages/RolesOverviewPage.jsx
=> Backport: A few minor wording adjustments for the new Users pages

graylog2-web-interface/src/components/navigation/SystemMenu.jsx, graylog2-web-interface/src/components/navigation/SystemMenu.test.jsx, graylog2-web-interface/src/components/nodes/NodeOverview.jsx, graylog2-web-interface/src/components/nodes/NodesActions.jsx, graylog2-web-interface/src/components/streams/StreamControls.jsx, graylog2-web-interface/src/components/streams/StreamForm.jsx, graylog2-web-interface/src/logic/notifications/NotificationsFactory.js, graylog2-web-interface/src/pages/SystemOverviewPage.jsx, graylog2-web-interface/src/routing/AppRouter.jsx, graylog2-web-interface/src/util/conditional/HideOnCloud.js, graylog2-web-interface/src/util/conditional/filterMenuItems.js, graylog2-web-interface/src/util/conditional/filterValueActions.js, graylog2-web-interface/src/util/conditional/filterValueActions.test.js, graylog2-web-interface/src/util/conditional/withHideOnCloud.jsx, graylog2-web-interface/src/views/bindings.jsx, graylog2-web-interface/src/views/bindings.routes.test.jsx, graylog2-web-interface/src/views/bindings.valueActions.test.jsx, graylog2-web-interface/src/views/spec/CreateNewDashboard.test.jsx
=> Sync cloud 3.3

distribution/pom.xml, full-backend-tests/pom.xml, graylog-plugin-archetype/pom.xml, graylog-plugin-parent/graylog-plugin-web-parent/pom.xml, graylog-plugin-parent/pom.xml, graylog-project-parent/pom.xml, graylog-storage-elasticsearch6/pom.xml, graylog-storage-elasticsearch7/pom.xml, graylog2-server/pom.xml, graylog2-web-interface/manifests/package.json, graylog2-web-interface/package.json, graylog2-web-interface/packages/graylog-web-plugin/package.json, graylog2-web-interface/src/pages/SidecarsPage.jsx, graylog2-web-interface/src/theme/GlobalThemeStyles.jsx, pom.xml
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#1951,Graylog2/graylog-plugin-cloud#613
=> Sync cloud branch after bump to 4.0.2-SNAPSHOT

graylog2-web-interface/.editorconfig
This will enable editors to automatically use the correct indentation for `tsx` files too.
As discussed earlier we have to setup Intellij and other IDEs to adhere to our indentation style
Because we had discussions earlier that we needed to provide documentation on how to setup Intellij and this will do that automatically
Using in the IDE
=> Fix indenting in .editorconfig for TypeScript

graylog2-web-interface/yarn.lock
With https://github.com/Graylog2/graylog2-server/pull/9601 we removed the remainders of flow, which includes some flow related packages. This is a follow-up PR to update the `yarn.lock` file
=> Updating `yarn.lock` regarding flow removal.

graylog2-web-interface/src/components/navigation/SystemMenu.jsx, graylog2-web-interface/src/components/nodes/NodeMaintenanceDropdown.jsx, graylog2-web-interface/src/routing/AppRouter.jsx
Fixes https://github.com/Graylog2/graylog-plugin-cloud/issues/98
Logging should not be accessible to cloud users. Alarm levels could be set later on by Ops.
=> Hide logging page on cloud

graylog2-web-interface/src/views/components/messagelist/MessageDetail.jsx
These change load check function and Received by component from cloud plugin
It will then check if the message Node is a local node, If not it will display the Received By section using the loaded component.
/jenkins-pr-deps Graylog2/graylog-plugin-cloud#611
=> Load cloud plugin and display ForwarderReceivedBy

graylog2-web-interface/src/pages/SidecarsPage.jsx
=> Fix missing buttons on SidecarsPage

graylog2-web-interface/src/pages/SidecarsPage.jsx
**This is a backport of #9678 for 4.0**
Fixes #9677 for 4.0
=> Fix missing buttons on SidecarsPage (4.0)

graylog2-web-interface/src/@types/reflux/index.d.ts, graylog2-web-interface/src/actions/roles/AuthzRolesActions.ts, graylog2-web-interface/src/stores/__tests__/connect.test.tsx, graylog2-web-interface/src/stores/nodes/NodesStore.ts, graylog2-web-interface/src/views/components/Search.test.tsx, graylog2-web-interface/src/views/logic/singleton.ts, graylog2-web-interface/src/views/pages/ViewManagementPage.tsx, graylog2-web-interface/src/views/stores/RefreshStore.ts, graylog2-web-interface/src/views/stores/SearchConfigStore.ts, graylog2-web-interface/src/views/stores/StreamsStore.ts, graylog2-web-interface/src/views/stores/ViewManagementStore.ts
This PR is adding typing for `reflux`. Before this PR, we were adding type information to the actions and stores created with reflux for a number of cases.
This PR is adding a custom declaration for reflux. The `@types/reflux` package is not available for our version and would interfere with the way we typed reflux before. Therefore this change is tying our existing typing into the module declaration.
=> Adding custom typing for reflux.

graylog2-server/src/main/java/org/graylog2/shared/journal/KafkaMessageQueueReader.java, graylog2-server/src/main/java/org/graylog2/shared/messageq/AbstractMessageQueueReader.java, graylog2-server/src/main/java/org/graylog2/shared/messageq/pulsar/PulsarMessageQueueReader.java, graylog2-server/src/main/java/org/graylog2/system/shutdown/GracefulShutdown.java
Extracts lifecycle handling for message queue readers into abstract class.
Adds lifecycle handling of Pulsar message queue reader.
=> Lifecycle handling for Pulsar message queue reader

graylog2-server/src/main/java/org/graylog2/plugin/BaseConfiguration.java, graylog2-server/src/main/java/org/graylog2/shared/messageq/pulsar/PulsarMessageQueueReader.java, graylog2-server/src/main/java/org/graylog2/shared/messageq/pulsar/PulsarMessageQueueWriter.java, graylog2-server/src/main/java/org/graylog2/shared/messageq/pulsar/PulsarServiceUrlValidator.java, graylog2-server/src/test/java/org/graylog2/shared/messageq/pulsar/PulsarServiceUrlValidatorTest.java
For reference: https://pulsar.apache.org/docs/en/client-libraries-java/#connection-urls
=> Make Pulsar service URL configurable

graylog2-web-interface/src/components/common/LinkToNode.jsx, graylog2-web-interface/src/components/navigation/Navigation.jsx, graylog2-web-interface/src/components/navigation/Navigation.test.jsx, graylog2-web-interface/src/components/navigation/SystemMenu.jsx, graylog2-web-interface/src/components/search/MessageDetail.jsx, graylog2-web-interface/src/routing/AppRouter.jsx
Will disable nodes page and components linking to it.
On cloud we don't want to show node details just yet, so we need to disable them for now.
By running through the code finding mentions of the nodes page and disabling them.
Fixes https://github.com/Graylog2/graylog-plugin-cloud/issues/97
=> Hide nodes page and disable navigation on cloud

graylog2-web-interface/src/views/components/searchbar/SearchBarForm.test.tsx, graylog2-web-interface/src/views/components/searchbar/SearchBarForm.tsx, graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteRangeField.test.tsx, graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteRangeField.tsx, graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteTimeRangeSelector.test.tsx, graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteTimeRangeSelector.tsx, graylog2-web-interface/src/views/components/searchbar/date-time-picker/KeywordTimeRangeSelector.test.tsx, graylog2-web-interface/src/views/components/searchbar/date-time-picker/KeywordTimeRangeSelector.tsx, graylog2-web-interface/src/views/components/searchbar/date-time-picker/RelativeTimeRangeSelector.test.tsx, graylog2-web-interface/src/views/components/searchbar/date-time-picker/RelativeTimeRangeSelector.tsx, graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx, graylog2-web-interface/src/views/components/visualizations/OnZoom.ts, graylog2-web-interface/src/views/stores/GlobalOverrideStore.ts, graylog2-web-interface/src/views/stores/QueriesStore.ts
Updating some of the variable names that were discussed.
Please let me know if you see any others we should modify
=> Date Time Picker variable renaming

graylog2-web-interface/src/views/components/widgets/MessageList.tsx
This PR is fixing the constructor signature of the `MessageList` component, fixing prop inference.
=> Fixing `MessageList` constructor signature.

graylog2-server/src/main/java/org/graylog2/storage/providers/AtomicCache.java
Otherwise this can block forever
=> Complete AtomicCache Future when Exceptions occur

graylog2-web-interface/src/stores/PaginationTypes.ts, graylog2-web-interface/src/util/URLUtils.js
Prior to this change, we defined DEFAULT_PAGINATION for every
list a new.
This change will define DEFAULT_PAGINATION on a central point for
pagination.
Fix use of this in URLUtils
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#793
=> Move DEFAULT_PAGINATION to central point

graylog2-web-interface/src/views/components/DashboardSearchBarForm.tsx, graylog2-web-interface/src/views/components/searchbar/SearchBarForm.tsx
Adding standard validation to DashboardSearchbarForm
=> Date Time Picker DashboardSearchForm validation 

graylog2-web-interface/src/views/components/DashboardSearchBarForm.tsx, graylog2-web-interface/src/views/components/searchbar/SearchBarForm.tsx, graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx
Fixes `dirty` flag from being true after cancelling Dashboard DTP
=> Adding DashboardSearchBarForm validation

graylog2-web-interface/packages/jest-preset-graylog/package.json, graylog2-web-interface/src/views/components/DashboardSearchBar.tsx, graylog2-web-interface/src/views/components/Search.test.tsx, graylog2-web-interface/src/views/components/aggregationbuilder/PivotSelect.test.tsx, graylog2-web-interface/src/views/components/aggregationbuilder/SeriesSelect.test.tsx, graylog2-web-interface/src/views/components/datatable/DataTable.test.tsx, graylog2-web-interface/src/views/components/searchbar/QueryInput.test.tsx, graylog2-web-interface/src/views/components/searchbar/StreamsFilter.test.tsx, graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRule.test.tsx, graylog2-web-interface/src/views/components/visualizations/XYPlot.tsx, graylog2-web-interface/src/views/components/visualizations/__tests__/GenericPlot.test.tsx, graylog2-web-interface/src/views/components/visualizations/worldmap/__tests__/WorldMapVisualization.test.tsx, graylog2-web-interface/src/views/components/widgets/WidgetColorContext.test.tsx, graylog2-web-interface/src/views/logic/valueactions/SelectExtractorType.test.tsx, graylog2-web-interface/yarn.lock
This PR is adding typing for `enzyme` and fixes some related issues in tests.
Requires #9650 to be merged before.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#1984
=> Typing `enzyme`.

graylog2-web-interface/package.json, graylog2-web-interface/src/views/components/searchbar/__snapshots__/SearchBarForm.test.tsx.snap, graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteRangeField.test.tsx, graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteRangeField.tsx, graylog2-web-interface/src/views/components/searchbar/date-time-picker/DisabledTimeRangeSelector.tsx, graylog2-web-interface/src/views/components/searchbar/date-time-picker/RelativeTimeRangeSelector.tsx, graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx, graylog2-web-interface/src/views/components/searchbar/date-time-picker/__snapshots__/AbsoluteRangeField.test.tsx.snap, graylog2-web-interface/src/views/components/searchbar/date-time-picker/__snapshots__/AbsoluteTimeRangeSelector.test.tsx.snap, graylog2-web-interface/yarn.lock
Adds content for Dashboard `No override` state
=> Updating "No Override" content of Date Time Picker on Dashboard

graylog2-web-interface/src/util/DocsHelper.js, graylog2-web-interface/src/views/components/searchbar/date-time-picker/KeywordTimeRangeSelector.tsx
Adding some documentation to the Keyword tab to explain its usage
=> DateTime Picker Keyword Tab Help Content

graylog2-web-interface/src/components/users/UserCreate/UserCreate.jsx, graylog2-web-interface/src/components/users/UserEdit/PasswordSection.jsx, graylog2-web-interface/src/components/users/UserEdit/ProfileSection.jsx
Server change required to integrate Cloud UI specific user creation form field.
/jenkins-pr-deps Graylog2/graylog-plugin-cloud#654
=> Cloud user management integration

graylog2-web-interface/packages/jest-preset-graylog/package.json, graylog2-web-interface/yarn.lock
Updating @testing-library/react to v11.2.3
=> Updating @testing-library/react to v11.2.3

pom.xml
This release contains a few Docker fixes which might help with the problems we see on our CI infrastructure.
See: https://github.com/testcontainers/testcontainers-java/releases/tag/1.15.1
=> Update to testcontainers 1.15.1

pom.xml
This updates nodejs to the latest LTS version and yarn to the latest v1 version.
=> Update nodejs to 14.15.4 and yarn to 1.22.5

graylog2-web-interface/src/views/components/SearchBar.tsx, graylog2-web-interface/src/views/components/__snapshots__/SearchBar.test.tsx.snap, graylog2-web-interface/src/views/components/searchbar/TimeRangeDisplay.tsx, graylog2-web-interface/src/views/components/searchbar/date-time-picker/__snapshots__/AbsoluteTimeRangeSelector.test.tsx.snap
Reverting location of Live Update component
=> DateTimePicker: moving live update

graylog-storage-elasticsearch6/pom.xml, graylog-storage-elasticsearch6/src/main/resources/org.graylog.graylog-storage-elasticsearch6/graylog-plugin.properties, graylog-storage-elasticsearch7/pom.xml, graylog-storage-elasticsearch7/src/main/resources/org.graylog.graylog-storage-elasticsearch7/graylog-plugin.properties
This change is making the ES storage modules to use the shared class
loader. This allows us to reuse the interfaces they provide in other
plugins.
=> Share ES storage modules with other plugins at runtime.

graylog2-web-interface/src/logic/local-storage/Store.js
Not only allow the use of local storage, but also session storage.
To allow not only storage in localStorage, but also sessionStorage. This to prevent tabs overwriting each other's browser stored data
In browser
=> Allow using SessionStorage

graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.test.tsx
=>  Add test for TimeRangeDropdown

graylog2-server/src/main/java/org/graylog2/periodical/IndexerClusterCheckerThread.java
Before this change, when the flood stage for ES was reached on multiple
nodes, creating a system notification raised an exception periodically,
because the code tries to mutate a list in place which is in fact
immutable.
This PR is now changing this behavior and creates a new list, so it can
effectively deal with immutable lists as well.
=> Fix disk watermark notifications for multiple hosts.

graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
**Note:** This is a simplified version of #9971 for `3.3`.
Prior to this PR, if one of the write targets in a bulk indexing request is an alias with zero or multiple targets, indexing failed and messages were silently dropped. This results in an error type being returned from ES different to the ones we handled before. Before this we had:
- requests failing completely: due to general errors (e.g. networking errors), indicated by an `IOException` being thrown and no response being returned
- requests failing partially (one or all individual bulk items failing): due to specific errors (e.g. mapping errors), with no exception being thrown and returning a response which contains error states for individual bulk items
In this case, we have a different scenario, where the request fails in …
=> Retrying bulk indexing if target alias has invalid target(s). (3.3)

pom.xml
This will configure Maven to retry deployments to oss.sonatype.org in the event of any network connectivity issues or intermittent server errors. 
Sometimes the deployment to sonatype fails when we run the release job. This offers some small degree of mitigation against this, depending on the issue.
=> Retry failed deployments to sonatype.org.

graylog2-web-interface/packages/eslint-config-graylog/index.js, graylog2-web-interface/packages/eslint-config-graylog/package.json, graylog2-web-interface/src/components/authentication/BackendCreate/ServiceSelect.test.tsx, graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.test.tsx, graylog2-web-interface/src/routing/Routes.test.jsx, graylog2-web-interface/src/views/components/SearchResult.test.jsx, graylog2-web-interface/src/views/components/sidebar/Sidebar.test.jsx, graylog2-web-interface/src/views/components/visualizations/OnZoom.test.tsx, graylog2-web-interface/yarn.lock
This PR adds the `eslint-plugin-import` module and adds its `recommended` rule preset to our ESLint config files matching `*.test.[jt]sx?`. The module contains useful rules to enforce code quality for tests. In the future, we might enable additional rules (e.g. the `style` preset or individual ones). More details about the rules can be found [here](https://www.npmjs.com/package/eslint-plugin-jest#rules).
=> Use jest plugin for ESLint.

graylog2-web-interface/src/views/logic/fieldtypes/FieldType.ts
This PR is slightly improving the types for field type properties by
making them const and preventing the repetition of keys.
=> Improving typing of field type properties.

graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java, graylog2-server/src/main/java/org/graylog2/shared/rest/resources/RestResource.java, graylog2-server/src/main/java/org/graylog2/shared/users/UserManagementService.java, graylog2-server/src/main/java/org/graylog2/users/UserImpl.java, graylog2-server/src/main/java/org/graylog2/users/UserManagementServiceImpl.java, graylog2-server/src/test/java/org/graylog2/rest/resources/users/UsersResourceTest.java
Server changes required for https://github.com/Graylog2/graylog-plugin-cloud/pull/735
/jenkins-pr-deps Graylog2/graylog-plugin-cloud#735
=> Server changes for Cloud #732

graylog2-server/src/main/java/org/graylog2/security/MongoDbSession.java, graylog2-server/src/test/java/org/graylog2/security/MongoDbSessionTest.java
Port of #10020 to `master`.
See #10020
Smoke test: logged user in and checked that the active session was detected on `/system/users`
=> Forward-Port: Handle multiple principals in mongoDB session (#10020)

graylog2-server/src/main/java/org/graylog/grn/GRNTypes.java, graylog2-server/src/main/java/org/graylog/security/BuiltinCapabilities.java, graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyPermissionChecker.java, graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java
=> Add missing GRN type for outputs

graylog2-web-interface/src/components/common/Section/SectionComponent.tsx, graylog2-web-interface/src/components/common/Select.tsx, graylog2-web-interface/src/components/common/SortableList.jsx, graylog2-web-interface/src/components/common/SortableListItem.jsx
Prior to this change, some commonly used widgets missed some adjustments
so they are more usable.
- Add className to SectionComponent so it can be styled with
'StyledComponent'
- Add Props to Select to adjust placement and size of its menu
- Add CustomRender method for SortableListItem so we can add a button to
a list item.
=> Adjustments needed for enterprise widgets

graylog2-web-interface/src/components/search/MessageField.jsx, graylog2-web-interface/src/components/search/MessageFieldDescription.jsx, graylog2-web-interface/src/stores/search/UniversalSearchStore.js, graylog2-web-interface/src/views/Constants.ts, graylog2-web-interface/src/views/components/MigrateFieldCharts.tsx, graylog2-web-interface/src/views/components/messagelist/MessageField.tsx, graylog2-web-interface/src/views/components/messagelist/MessageTableEntry.tsx, graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportModal.tsx, graylog2-web-interface/src/views/components/widgets/MessageTable.tsx, graylog2-web-interface/src/views/logic/widgets/MessagesWidget.ts, graylog2-web-interface/src/views/logic/widgets/MessagesWidgetConfig.ts
This PR is adding a constant for the message/source fields, which are used in a couple of places throughout the product. This helps us to centralize changes, in case we would like to change the field names or make them configurable.
=> Adding message/source field constant.

graylog2-web-interface/src/pages/SidecarAdministrationPage.jsx
Point to the correct page in the documentation as described here: #9140
Fixes #9140
=> Fix documentation link for sidecars

graylog2-web-interface/src/views/components/visualizations/number/Trend.test.tsx, graylog2-web-interface/src/views/components/visualizations/number/Trend.tsx
This change is doing a couple of changes to the `Trend` component:
- Refactor the internal logic for background calculation to avoid duplication of color classes
- Migrates tests to `testing-library`
- Changes negative trend color to be consistently red
=> Refactoring `Trend` component to avoid duplication of color classes.

graylog2-server/src/main/java/org/graylog/plugins/views/search/Exportable.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchType.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/export/CommandFactory.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/MessageList.java, graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportModal.test.tsx, graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportModal.tsx, graylog2-web-interface/src/views/components/widgets/Widget.test.tsx, graylog2-web-interface/src/views/components/widgets/Widget.tsx, graylog2-web-interface/src/views/logic/views/View.ts, graylog2-web-interface/src/views/logic/widgets/MessagesWidget.ts, graylog2-web-interface/src/views/logic/widgets/Widget.ts
Prior to this change, exporting capability was hard-coded to the message table. This change is now making it possible for all widgets, whose `isExportable` property is `true`. This allows us to gradually implement exporting capabilities for other widgets as well.
=> Enable export for exportable widgets.

graylog2-web-interface/src/components/users/UserDetails/ProfileSection.tsx, graylog2-web-interface/src/components/users/UserDetails/UserDetails.test.tsx
These changes add the first and last name field to the UserDetails page
=>  Add first and last name to userDetails

graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportModal.test.tsx, graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportModal.tsx, graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportSettings.tsx
This PR is refactoring the CSV export dialog to make use of formik. This
helps us to extend the form dynamically when extending it to support
other widgets than the message table.
=> Migrate CSV export dialog to use formik.

graylog2-web-interface/src/components/login/LoginForm.jsx
Puts the `required` attributes on the login form's input elements to allow for quick validation of the login credentials.
Fixes #8137
When submitting login without username and password an error arises. Adding `required` attributes to inputs prevents login from happening without the correct credentials.
=> Add `required` attributes to login inputs to allow login validation

graylog2-web-interface/src/views/components/DashboardSearchBar.tsx, graylog2-web-interface/src/views/components/SearchBar.tsx, graylog2-web-interface/src/views/components/WidgetQueryControls.tsx, graylog2-web-interface/src/views/components/searchbar/TimeRangeDisplay.tsx, graylog2-web-interface/src/views/components/searchbar/TimeRangeDropdownButton.tsx, graylog2-web-interface/src/views/components/searchbar/TimeRangeInput.test.tsx, graylog2-web-interface/src/views/components/searchbar/TimeRangeInput.tsx, graylog2-web-interface/src/views/components/searchbar/TimeRangeTypeSelector.tsx
This PR is attempting to improve reusability of the time range picker component by:
- Renaming the component to `TimeRangeInput` to make its intention clearer
- Push flex directives into the component so it does not require outside styling for alignment of the summary and the button
- Add test suite to cover basic functionality
- Adding two test ids for the time range summary to aid in testing
=> Improve reusability of time range picker component.

graylog2-server/src/main/java/org/graylog/plugins/map/config/DatabaseType.java, graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IPLocationDatabaseAdapter.java, graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IPinfoASN.java, graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IPinfoIPLocationDatabaseAdapter.java, graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IPinfoStandardLocation.java, graylog2-server/src/main/java/org/graylog/plugins/map/geoip/MaxMindIPLocationDatabaseAdapter.java, graylog2-server/src/main/java/org/graylog/plugins/map/geoip/MaxmindDataAdapter.java, graylog2-server/src/test/java/org/graylog/plugins/map/geoip/MaxmindDataAdapterTest.java, graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterFieldSet.jsx, graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterSummary.jsx
Add support for the standard location and ASN IPinfo database files.
=> Support IPinfo database files in GeoIP lookup data adapter

graylog2-server/src/main/java/org/graylog/plugins/map/config/DatabaseType.java, graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IPLocationDatabaseAdapter.java, graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IPinfoASN.java, graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IPinfoIPLocationDatabaseAdapter.java, graylog2-server/src/main/java/org/graylog/plugins/map/geoip/IPinfoStandardLocation.java, graylog2-server/src/main/java/org/graylog/plugins/map/geoip/MaxMindIPLocationDatabaseAdapter.java, graylog2-server/src/main/java/org/graylog/plugins/map/geoip/MaxmindDataAdapter.java, graylog2-server/src/test/java/org/graylog/plugins/map/geoip/MaxmindDataAdapterTest.java, graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterFieldSet.jsx, graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterSummary.jsx
Backport of #10183.
Smoke test to prove that I could create both a location and an ASN data adapter.
=> Backport: Support IPinfo database files in GeoIP lookup data adapter (#10183)

graylog2-web-interface/package.json, graylog2-web-interface/yarn.lock
This PR is removing the explicite `webpack` dependency in favor of the transitive one from `graylog-web-plugin`. This reduces installation effort and keeps version numbers consistent.
=> Removing explicit `webpack` dependency in favor of transitive one.

graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterFieldSet.jsx
Port https://github.com/Graylog2/graylog2-server/pull/10211 to `cloud-4.0`
=> Backport: Remove trailing parenthesis for DB types (#10183)

graylog2-web-interface/src/components/navigation/Navigation.jsx
A quick back port to solve #10188 
Also including an extra fix for Enterprise as a bonus: https://github.com/Graylog2/graylog-plugin-enterprise/pull/2116
Enterprise page will break for regular users, best to hide enterprise altogether.
=> Back port: Do not show navigation if user is lacking permission

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchResource.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/SearchResourceTest.java
Before this change, it was not possible to create a search over the API
with an empty or `null` id. This change is fixing this. In case of an
absent id, a new one is assigned by the database and returned in the
response.
=> Allow creating Search without (or null) id.

graylog2-web-interface/packages/graylog-web-plugin/package.json, graylog2-web-interface/src/views/components/queries/QueryTitle.test.tsx, graylog2-web-interface/src/views/components/widgets/MessageList.test.tsx, graylog2-web-interface/src/views/logic/searchtypes/SearchTypesGenerator.test.ts, graylog2-web-interface/src/views/logic/views/GenerateNextPosition.test.ts, graylog2-web-interface/src/views/stores/CurrentViewStateStore.test.ts, graylog2-web-interface/yarn.lock
This PR is updating TypeScript to the most recent version (v4.2.3) and
fixes a couple of smaller typing issues detected by it.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#2119
=> Updating TypeScript to v4.2.3

graylog2-server/src/main/java/org/graylog2/inputs/random/generators/FakeHttpRawMessageGenerator.java
This makes it easier to detect lost messages
=> Add an increasing sequence_nr to Random HTTP message generator

graylog2-web-interface/package.json, graylog2-web-interface/packages/eslint-config-graylog/package.json, graylog2-web-interface/packages/graylog-web-plugin/package.json, graylog2-web-interface/packages/jest-preset-graylog/package.json, graylog2-web-interface/yarn.lock
This PR is doing a batch update of several dependencies to their v7.13.x (or most recent) versions.
=> Updating babel to v7.13.x.

graylog2-web-interface/src/components/configurationforms/__snapshots__/BooleanField.test.tsx.snap, graylog2-web-interface/src/components/configurationforms/__snapshots__/DropdownField.test.tsx.snap, graylog2-web-interface/src/components/configurationforms/__snapshots__/ListField.test.tsx.snap, graylog2-web-interface/src/components/configurationforms/__snapshots__/NumberField.test.tsx.snap, graylog2-web-interface/src/components/configurationforms/__snapshots__/TextField.test.tsx.snap, graylog2-web-interface/yarn.lock
When #10131 was merged, it contained some stale snapshots due to #10077 being merged in the meantime.
This PR updates those snapshots to fix tests.
=> Updating snapshots of configuration form components.

graylog2-web-interface/src/components/graylog/Tab.jsx, graylog2-web-interface/src/components/graylog/styles/nav-tabs.js, graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx
Updated Tab border and background colors
Fixed DTP Popover alignment
Tabs were oddly colored that didn't match rest of layout
=> Update tab styles and popover positioning for DateTimePicker

graylog2-web-interface/yarn.lock
This PR is performing a periodic browserslist db.
=> Updating browsers list db.

graylog2-web-interface/src/components/graylog/OverlayTrigger.tsx, graylog2-web-interface/src/components/sidecars/common/StatusIndicator.jsx
Addresses issues provided in #10208
Fixes tooltip and overlay `hide` method.
=> Fix OverlayTrigger in Sidecars

graylog2-server/src/main/java/org/graylog2/lookup/adapters/dsvhttp/HTTPFileRetriever.java
This change adds two new methods to the HTTPFileRetriever to retrieve data from a URL as `byte[]` rather than as a `String`.  This is needed to properly unzip downloads which may be zipped.
This change has been tested locally with the zipped URLhaus data set
=> Add file bytes option to HTTPFileRetriever

graylog2-web-interface/src/views/components/aggregationwizard/PropagateValidationState.tsx, graylog2-web-interface/src/views/components/aggregationwizard/WidgetConfigForm.test.tsx, graylog2-web-interface/src/views/components/aggregationwizard/WidgetConfigForm.tsx, graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.test.tsx, graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.tsx, graylog2-web-interface/src/views/components/widgets/SaveOrCancelButtons.tsx, graylog2-web-interface/src/views/components/widgets/Widget.tsx
This PR is introducing a `ValidationStateContext` which is used to propagate the validation state (valid or not) from the edit component to the `EditWidgetFrame` component. It provides a value and a setter for this.
In addition, a `PropagateValidationState` component is introduced, which is used in the aggregation wizard to read formik's validation state and propagates it to the context.
=> Disable 'Save' button in edit mode if aggregation wizard has errors.

graylog2-web-interface/src/components/sidecars/common/ColorLabel.tsx
Rebuild `ColorLabel` to use Theme utilities 
Resolves https://github.com/Graylog2/graylog2-server/issues/10217
=> Rebuild & Type ColorLabel

graylog2-web-interface/src/components/extractors/MessageLoader.jsx, graylog2-web-interface/src/components/graylog/Label.jsx, graylog2-web-interface/src/components/outputs/CreateOutputDropdown.jsx, graylog2-web-interface/src/components/permissions/RolesCell.tsx, graylog2-web-interface/src/components/systemjobs/SystemJob.jsx
Updating elements to properly render theme colors
Resolves https://github.com/Graylog2/graylog-plugin-enterprise/issues/2145
=> Update Component usage to properly render Theme

graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/AggregationElementType.ts, graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/GroupByElement.test.ts, graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/GroupByElement.ts, graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/MetricElement.test.ts, graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/MetricElement.ts, graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/ElementConfigurationSection.test.tsx, graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/ElementConfigurationSection.tsx, graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/GroupByConfiguration.tsx, graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/MetricsConfiguration.tsx
Add a trash icon button to remove configuration sections from AggregationWizzard.
=> Remove button for aggregation wizard section

graylog2-server/src/main/java/org/graylog2/rest/MoreMediaTypes.java
This PR is simply adding the NDJSON (newline-delimited JSON) media types
to our companion class.
=> Add NDJSON media type.

distribution/pom.xml, full-backend-tests/pom.xml, graylog-plugin-archetype/pom.xml, graylog-plugin-parent/graylog-plugin-web-parent/pom.xml, graylog-plugin-parent/pom.xml, graylog-project-parent/pom.xml, graylog-storage-elasticsearch6/pom.xml, graylog-storage-elasticsearch7/pom.xml, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/RestHighLevelClientProvider.java, graylog2-server/pom.xml, graylog2-server/src/main/java/org/graylog2/periodical/ContentPackLoaderPeriodical.java, graylog2-web-interface/manifests/package.json, graylog2-web-interface/package.json, graylog2-web-interface/packages/graylog-web-plugin/package.json, graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionSummary.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.jsx, graylog2-web-interface/src/views/components/visualizations/number/Trend.jsx, pom.xml
Update `cloud-4.0` with the latest `4.0` changes.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#2185,Graylog2/graylog-plugin-enterprise-integrations#531,Graylog2/graylog-plugin-integrations#797,Graylog2/graylog-plugin-cloud#844
=> Sync cloud 4.0

graylog2-server/src/main/java/org/graylog2/lookup/adapters/CSVFileDataAdapter.java, graylog2-server/src/main/java/org/graylog2/lookup/adapters/LookupDataAdapterValidationContext.java, graylog2-server/src/test/java/org/graylog2/lookup/adapters/CSVFileDataAdapterTest.java
Port https://github.com/Graylog2/graylog2-server/pull/10391 to `cloud-4.0`
=> Cloud port: Use AllowedAuxiliaryPathChecker in File path UI validation #10391

graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx
Remove unnecessary media query
Fixes #10464
=> Fix broken DTP layout on small resolutions

graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.sort.test.tsx, graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/SortElement.ts, graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/Sort.tsx
With this PR we are adding unit tests to test the aggregation sort configuration in the aggregation wizard. These tests are comparable with the tests we wrote for other aggregation elements in `components/aggregationwizard/__tests__`.
=> Creating tests for aggregation sort configuration.

graylog2-web-interface/package.json, graylog2-web-interface/src/logic/rest/FetchProvider.test.ts, graylog2-web-interface/src/logic/rest/FetchProvider.ts, graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.tsx, graylog2-web-interface/yarn.lock
This change is fixing an issue introduced in the transition to the native fetch API, which left out setting the `Accept` header in the
generated request. The value for the header was tracked in a private field of the `Builder` class, but never set for the client.
Note: This PR is also adding `@types/express`, which transitively adds `@types/qs`, resulting in an necessary change in `WidgetFocusProvider`.
=> Add `Accept` header in `FetchProvider`.

graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java, graylog2-server/src/main/java/org/graylog/plugins/views/ViewsModule.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SeriesDescription.java, graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.metric.test.tsx, graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/Metric.tsx, graylog2-web-interface/src/views/stores/AggregationFunctionsStore.ts
This change is adding human-readable aggregation function descriptions.
This allows us to show better names in the frontend for aggregation
functions.
Before:
After:
=> Add human-readable aggregation function descriptions.

graylog2-server/src/main/java/org/graylog2/plugin/rest/ValidationResult.java
This allows us to use it in a Builder like pattern
=> Make working with ValidationResults a bit more pleasant

graylog2-web-interface/src/components/common/Select.tsx, graylog2-web-interface/src/components/common/Spinner.tsx
This change is performing minor typing changes, namely:
- Extending the `ComponentsProp` which defines which `react-select`
components can be overridden, so the container can be customized
- Making the `delay` prop optional. In case it's absent, 200ms will be
used
=> Minor typing changes for `Select` and `Spinner`.

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreter.java, graylog2-web-interface/src/components/simulator/SimulationResults.jsx
Prior to this change, when a execption was thrown in the when block of a
pipeline rule, the user could not know which rule was causing the error.
This change will add an log.error to clarify which rule caused the
trouble and also adds the message which was processed at the moment.
```
2021-04-29 14:39:44,423 ERROR:
org.graylog.plugins.pipelineprocessor.processors.PipelineInterpreter -
This exception was caused by "failing rule"/608aa0122efce1354f715e6c:
source: acme.org | message: 2021-04-29T12:39:44.422Z DELETE
/posts/45326/edit [204] 104ms { controller: PostsController |
sequence_nr: 19 | ingest_time: 2021-04-29T12:39:44.422Z | resource:
/posts/45326/edit | ticks: 20178941558627 | took_ms: 104 |
ingest_time_minute: 39 | gl2_source_input: 5f4dfb5069be46153b9a9a1c |
ingest_time_second: 44 …
```
=> Enhance error message for exception in pipeline rule

graylog2-web-interface/src/components/common/ClipboardButton.jsx, graylog2-web-interface/src/components/graylog/Tooltip.jsx, graylog2-web-interface/src/components/search/MessageDetail.jsx, graylog2-web-interface/src/views/components/messagelist/MessageActions.tsx
`Copy ID` button was larger than others in Message Preview
fixes #10201
=> ClipboardButton button resize & update

graylog2-web-interface/src/components/graylog/Popover.jsx, graylog2-web-interface/src/views/components/WidgetQueryControls.tsx, graylog2-web-interface/src/views/components/searchbar/TimeRangeInput.tsx, graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.test.tsx, graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx
Offer secondary placement using prop `position` which can be `bottom` (default) or `right` which is useful for areas with minimal spacing on the left side of the button, such as Widget editing.
Resolves #10522
=> Use same colors for arrows on each side

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/FieldTypesForStreamsRequest.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/FieldTypesResource.java, graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/MappedFieldTypesService.java, graylog2-server/src/main/java/org/graylog2/plugin/indexer/searches/timeranges/RelativeRange.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/FieldTypesResourceTest.java, graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/MappedFieldTypesServiceTest.java, graylog2-web-interface/src/views/bindings.enterpriseWidgets.test.tsx, graylog2-web-interface/src/views/bindings.fieldActions.test.tsx, graylog2-web-interface/src/views/bindings.routes.test.tsx, graylog2-web-interface/src/views/bindings.valueActions.test.tsx, graylog2-web-interface/src/views/components/Search.dashboard.test.tsx, graylog2-web-interface/src/views/components/Search.test.tsx, graylog2-web-interface/src/views/components/Search.tsx, graylog2-web-interface/src/views/components/WidgetComponent.tsx, graylog2-web-interface/src/views/components/WidgetGrid.test.jsx, graylog2-web-interface/src/views/components/contexts/WidgetFieldTypesContextProvider.test.tsx, graylog2-web-interface/src/views/components/contexts/WidgetFieldTypesContextProvider.tsx, graylog2-web-interface/src/views/components/export/ExportModal.test.tsx, graylog2-web-interface/src/views/components/export/ExportModal.tsx, graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.test.tsx, graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchControls.test.tsx.snap, graylog2-web-interface/src/views/components/sidebar/fields/FieldsOverview.test.jsx, graylog2-web-interface/src/views/components/sidebar/fields/FieldsOverview.tsx, graylog2-web-interface/src/views/components/widgets/Widget.test.tsx, graylog2-web-interface/src/views/components/widgets/WidgetActionsMenu.test.tsx, graylog2-web-interface/src/views/logic/fieldtypes/useFieldTypes.ts, graylog2-web-interface/src/views/logic/queries/useCurrentQuery.ts, graylog2-web-interface/src/views/spec/CreateNewDashboard.it.tsx, graylog2-web-interface/src/views/stores/FieldTypesStore.ts, graylog2-web-interface/test/integration-environment.js
This PR is improving field types retrieval for the search. Prior to this PR, all field types for the current set of streams were retrieved. This could lead to issues when a field type has conflicting types across all indices, because restricting the time range to indices where the field type is consistent would not help, as the field type in the UI would still be a compound type.
This PR is now passing the current time range of the search/widget along with the field types retrieval query, so only relevant field types are retrieved. This helps with correctness _and_ performance of field types retrieval.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#2219
=> Limit field types retrieval to timerange of query.

graylog2-web-interface/src/components/common/Select.tsx, graylog2-web-interface/src/components/configurationforms/__snapshots__/ListField.test.tsx.snap, graylog2-web-interface/src/components/graylog/FormGroup.jsx
Our form components consider the validation state when being used inside a
`FormGroup`. Before this change our common `Select` component was an
exception. With this change we are updating the styling (mainly the border) accordingly.
=> Style common `Select` based on `FormGroup` validation state.

graylog2-server/src/main/java/org/graylog2/shared/security/ShiroRequestHeadersBinder.java
(cherry picked from commit 126a4ad0b2e19d057b32f8c7c95829c3049b3982)
=> Change back REQUEST_HEADERS access to public 4.0 backport (#10621)

graylog2-web-interface/src/pages/LoginPage.jsx
=> Ability to switch login methods

graylog2-server/src/main/java/org/graylog2/contentpacks/model/ModelId.java, graylog2-server/src/main/java/org/graylog2/decorators/Decorator.java, graylog2-server/src/main/java/org/graylog2/rest/models/alarmcallbacks/AlarmCallbackResult.java, graylog2-server/src/main/java/org/graylog2/rest/models/system/metrics/responses/MetricsSummaryResponse.java, graylog2-server/src/main/java/org/graylog2/shared/rest/documentation/generator/Generator.java
This PR is aiming to improve the generated swagger specs by extracting inline models and recursively generate typings for them. Before this change, there were a couple of scenarios where we did not generate a schema for a used type, but instead a string literal was used:
**Before:**
Through these changes, we can now resolve these type names and generate inline schemas which can be used to display the structure of a type:
**After:**
This change does not make type introspection for swagger perfect, there are still remaining cases where no useful type information is handed out, but it improves significantly for the majority of cases.
=> Better swagger specs through extracting inline models.

graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/RestHighLevelClientProvider.java
A builder was replaced by another builder instead of augmenting the existing one with another config, so already configured options were lost. 
fixes #10716
has been tested manually
=> Fix for Mute ES Deprecation Warnings, builder was created the wrong way

graylog2-web-interface/src/views/spec/CreateNewDashboard.it.tsx
This PR is mocking search query parsing in the frontend integration test, as it was causing false negatives periodically, due to runaway promise rejections after test teardown.
=> Quick-fixing reliability of frontend integration test.

graylog2-web-interface/src/pages/LoggedInPage.jsx, graylog2-web-interface/src/routing/App.tsx
Prior to this PR, an instance of the `QueryClient` used by `react-query` was provided below the `App` component. This is too late for some scenarios, e.g. the big display mode.
This PR is pulling up provisioning of the `QueryClient` to happen from the `LoggedInPage`.
Fixes #10770.
=> Pull up query client provider in component tree.

graylog2-web-interface/src/views/components/searchbar/TimeRangeInput.test.tsx
In #10782 new test cases for the `TimeRangeInput` were introduced.  Unfortunately, those were not using the component wrapper created in the test, but the component directly. This lead to tests failing later, when the component required a formik context which is not present in these tests.
This PR is fixing this issue by using the wrapper component in these tests as well.
=> Using correct component in `TimeRangeInput` test.

graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightForm.tsx, graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingColorForm.tsx
This PR contains a collection of improvements for the highlighting rule validation. 
- Validate on mount
- Validate if coloring type is defined and if coloring type is suitable for field type (gradient coloring can only be defined for numeric fields)
- Only disable gradient color type and select static color type by default.
Fixes: https://github.com/Graylog2/graylog2-server/issues/10794
=> Improving validation rules and initial values for highlighting rule form.

graylog2-server/src/main/java/org/graylog2/Configuration.java, graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchClientConfiguration.java
This is a minor change moving the `elasticsearch_mute_deprecation_warnings` configuration flag from the general configuration module to the ES-client one, in order to keep related configuration settings together.
=> Move config setting to disable ES warnings to ES-client config module.

graylog2-server/src/main/java/org/graylog2/security/encryption/EncryptedValueService.java
=> Return null when no encryptedValue is set

graylog2-web-interface/src/components/authentication/directoryServices/BackendWizard/BackendWizardContext.tsx, graylog2-web-interface/src/components/authentication/types.d.ts, graylog2-web-interface/src/logic/authentication/AuthenticationBackend.ts, graylog2-web-interface/src/logic/authentication/okta/types.ts
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#2364
=> Update Team sync backend types to use Okta related fields

graylog2-web-interface/src/pages/LoginPage.jsx
This allows us to handle errors on the plugin code, show information about it and fallback to the regular login form.
Fixes Graylog2/graylog-plugin-enterprise#2363
Changes should be backported into 4.1.
=> Add error boundary to plugin authentication form

graylog2-web-interface/packages/eslint-config-graylog/index.js
With this PR we are configuring the [ESLint rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-spacing.md) `react/jsx-curly-spacing`, to ensure we always disallow spaces inside of curly braces in JSX expressions. We already disallow the usage of spaces inside of curly braces in JSX attributes.
Before this change it was possible to use spaces in JSX expressions in different ways.   For example:
`<Component>{ condition && 'Content'}</Component>`
or
`<Component>{ condition && 'Content' }</Component>`
 With this ESLint rule we are enforce the following notation:
`<Component>{condition && 'Content'}</Component>`
Tested by running `yarn lint --fix`, to see if errors would be fixed correclty.
=> Configure ESLint rule to disallow spaces inside curly braces in JSX expressions.

graylog2-server/src/main/resources/prometheus-exporter.yml
Backporting https://github.com/Graylog2/graylog2-server/pull/10964
=>  Missing Forwarder gRPC server-side metrics

graylog2-web-interface/packages/jest-preset-graylog/package.json, graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.test.tsx, graylog2-web-interface/src/views/components/widgets/Widget.aggregations.test.tsx, graylog2-web-interface/yarn.lock
This change is replacing the previously used Jest types (`@types/jest`)
with the official ones (`@jest/types`), supporting Jest 27.
Unfortunately, the `setSystemTime` function is not part of the type
signatures, so a `@ts-expect-error` directive is added to a) silence the
error, b) throw an error when this is fixed upstream.
=> Use proper Jest types.

graylog2-web-interface/src/domainActions/authentication/AuthenticationDomain.tsx, graylog2-web-interface/src/domainActions/authentication/HTTPHeaderAuthConfigDomain.tsx, graylog2-web-interface/src/domainActions/notifyingAction.tsx, graylog2-web-interface/src/domainActions/permissions/EntityShareDomain.tsx, graylog2-web-interface/src/domainActions/roles/AuthzRolesDomain.tsx, graylog2-web-interface/src/domainActions/users/UsersDomain.ts
Previously, using `notifyingAction` required assigning a return type to
the generated function. This change is improving type signatures so
these can be left out.
=> Simplifying usage of `notifyingAction`.

graylog2-server/src/main/java/org/graylog/schema/DestinationFields.java, graylog2-server/src/main/java/org/graylog/schema/EventFields.java, graylog2-server/src/main/java/org/graylog/schema/GeoFields.java, graylog2-server/src/main/java/org/graylog/schema/HostFields.java, graylog2-server/src/main/java/org/graylog/schema/SourceFields.java
Per discussions with the Security & Content Team, this PR adds new fields to the Graylog Schema to support VPC flow logs.  This change also deprecates some older fields and adds their newer replacements.
=> Add new fields needed for VPC flow logs

graylog2-server/src/main/java/org/graylog/failure/DefaultFailureHandlingConfiguration.java, graylog2-server/src/main/java/org/graylog/failure/FailureHandlingConfiguration.java, graylog2-server/src/main/java/org/graylog/failure/ProcessingFailure.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreter.java, graylog2-server/src/main/java/org/graylog2/shared/bindings/GenericBindings.java, graylog2-server/src/test/java/org/graylog/failure/FailureBatchTest.java, graylog2-server/src/test/java/org/graylog/failure/FailureHandlingServiceTest.java, graylog2-server/src/test/java/org/graylog/failure/FailureSubmissionServiceTest.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreterTest.java
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/2515
=> Store index processing failures processing failure routing review comments

graylog2-server/src/main/java/org/graylog2/rest/resources/system/SessionsResource.java, graylog2-server/src/main/java/org/graylog2/security/MongoDbSessionDAO.java, graylog2-server/src/main/java/org/graylog2/security/UserSessionTerminationService.java, graylog2-server/src/main/java/org/graylog2/security/realm/SessionAuthenticator.java, graylog2-server/src/main/java/org/graylog2/shared/security/SecurityBindings.java
Please let me merge the PR after approval. Thanks!
=> Backport #11080 and #11081 (3.3)

graylog2-server/src/main/java/org/graylog2/security/UserSessionTerminationService.java
This avoids an error log message when trying to get a session that has
already expired.
=> Handle expired sessions in UserSessionTerminationService

graylog2-server/src/main/java/org/graylog2/streams/StreamDTO.java
This info is enriched when the Autovalue object is constructed
=> Add is_editable field to StreamDTO

graylog2-web-interface/src/stores/streams/StreamsStore.ts
As described in #11091 using the stream overview pagination will reset the search. This bug occurred because we are updating the list state based on the response of the streams request. Unfortunately we were not extracting the query properly from the response.
=> Fixing streams overview query handling.

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/debug/Debug.java, graylog2-server/src/main/java/org/graylog2/inputs/random/generators/FakeHttpRawMessageGenerator.java, graylog2-server/src/main/java/org/graylog2/shared/bindings/GenericBindings.java
- Inherit serviceBinder from Graylog2Module 
- Remove testing code
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#2591
=> Fix open TODOS

graylog2-server/src/main/java/org/graylog2/system/traffic/TrafficCounterService.java
=> ApiError on /system/cluster/traffic

graylog2-web-interface/src/views/components/Search.tsx, graylog2-web-interface/src/views/components/sidebar/ContentColumn.tsx, graylog2-web-interface/src/views/components/sidebar/Sidebar.test.tsx, graylog2-web-interface/src/views/components/sidebar/Sidebar.tsx, graylog2-web-interface/src/views/logic/views/View.ts, graylog2-web-interface/src/views/logic/views/ViewTitle.ts, graylog2-web-interface/src/views/pages/NewSearchPage.test.tsx, graylog2-web-interface/src/views/pages/SearchPage.tsx, graylog2-web-interface/src/views/pages/StreamSearchPage.test.tsx
With this change, we are including the title of the current search/dashboard in the document's title, showing it in the title/tab bar of the browser. This helps the user to e.g. find the desired tab.
=> Include title of current search/dashboard in document title.

graylog2-web-interface/src/components/sidecars/sidecars/SidecarStatus.jsx
This removes an unnecessary comma from `SidecarStatus`.
I thought a gnat was on my screen.
It has not (aside from making sure the check completed).
=> Remove a trailing comma from 'SidecarStatus'.

graylog2-web-interface/src/components/navigation/Navigation.test.tsx, graylog2-web-interface/src/components/navigation/Navigation.tsx
Prior to this PR, any change to the URL would trigger rerendering the complete top level navigation. This is particularly noticeable when operating the search page which tracks part of its state in the URL.
This change is now decoupling this, by pushing parts of the state down to the relevant consumer components, avoiding rerendering of the complete navigation
=> Avoid unnecessary rerendering navigation when location changes.

graylog2-server/src/main/java/org/graylog2/periodical/TrafficCounterCalculator.java
Make calculation fields of TrafficCounterCalculator volatile.
close #11248
=> Fix potential race condition in traffic calculation

graylog2-web-interface/src/stores/event-definitions/FilterPreviewStore.js
=> Improve error message wording in FilterPreviewStore.js

graylog2-web-interface/src/components/graylog/Accordion.test.tsx
Fixing eslint issues in Accordion.test.tsx
=> Linting Accordion.test.tsx

graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessor.java
When an event definition doesn't have any streams configured, this
previously resulted in an empty "source_streams" field in the event
which allowed all users to see the event.
To fix it, we are now using the same way to compute the "source_streams"
for filter events that we are using for aggregation events.
Fixes #11301
(cherry picked from commit cfe478eb01a09af38878de8a8fe36f90bb8f4264)
=> Ensure filter events have "source_streams" set (#11303)

graylog2-web-interface/src/pages/ShowMessagePage.test.tsx, graylog2-web-interface/src/pages/ShowMessagePage.tsx, graylog2-web-interface/src/pages/__snapshots__/ShowMessagePage.test.tsx.snap, graylog2-web-interface/src/views/logic/fieldtypes/useFieldTypes.ts
Prior to this change, the page showing a single message's details was
missing two contexts which were previously set up by the `MessageList`
component/the views pages. Missing those resulted in an exception being
thrown by the watchlist message augmentation relying on these.
This change is now adding these back. It is also doing some slight
refactoring of the `ShowMessagePage` component by extracting two hooks
for brevity.
Fixes #11349.
=> Provide necessary contexts for single message details page.

graylog2-server/src/main/java/org/graylog2/system/stats/mongo/DatabaseStats.java, graylog2-server/src/main/java/org/graylog2/system/stats/mongo/MongoProbe.java
Fixes #11350
(cherry picked from commit 28b32874a75f21a167be208bd86a92a1e59103e9)
=> Fix system stats with MongoDB >= 4.4 (#11357)

graylog2-web-interface/yarn.lock
Ran `npx browserslist@latest --update-db`
Received stylelint error
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
```
=> Updating stylelint browserslist

.github/workflows/fix-linter-hints.yml
This is a follow-up to #11387, correcting the author mail address too.
=> Correcting author email of linter job

graylog2-server/src/main/java/org/graylog/plugins/views/search/Search.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/export/ResultFormat.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ExecutionState.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/MessagesResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchResource.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/SearchTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ExecutionStateTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/SearchResourceTest.java, graylog2-server/src/test/resources/org/graylog/plugins/views/search/views/execution-state.json
The current implementation of ExecutionState is represented as Map<String, Object> type, which is hard to read, understand, test and refactor. We'd like to have a class that describes possible values better, in a type-safe manner. 
Fixes #7464.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#2719
Adapted all existing tests that already use the ExecutionState values. They should cover expected behavior and if they succeed, it means that the new class corresponds to the original map.
=> Refactor ExecutionState in backend to class #7464

graylog2-server/src/main/java/org/graylog2/periodical/Periodicals.java
There is nothing time consuming being called.
=> Remove unneeded Stopwatch for Periodical shutdown

graylog2-server/src/main/java/org/graylog2/cluster/leader/LeaderElectionService.java, graylog2-server/src/main/java/org/graylog2/cluster/leader/MongoLeaderElectionService.java, graylog2-server/src/main/java/org/graylog2/cluster/leader/StaticLeaderElectionService.java, graylog2-server/src/main/java/org/graylog2/system/shutdown/GracefulShutdown.java
=> Give up leader lock at server shutdown

graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.test.tsx
Prior to this change, the `Absolute tab has Accordion` test of the `TimeRangeDropdown` test suite repeatedly timed out. This change is now extending its timeout, until the underlying performance issues are fixed.
=> Extend timeout for test.

graylog2-server/src/test/java/org/graylog/testing/mongodb/MongoDBContainer.java, graylog2-server/src/test/java/org/graylog2/migrations/V2018070614390000_EnforceUniqueGrokPatternsTest.java
MongoDB 3.6 is EOL since April 21
Adopt EnforceUnqieGrokPatternsTest to new more detailed Exception
message.
=> Update MongoDBContainer to version 4.0

graylog2-server/src/main/java/org/graylog/grn/GRNRegistry.java, graylog2-server/src/main/java/org/graylog/security/shares/DefaultGranteeService.java, graylog2-server/src/main/java/org/graylog2/users/UserAndTeamsConfig.java, graylog2-web-interface/src/actions/configurations/ConfigurationActions.js, graylog2-web-interface/src/components/common/InputDescription.tsx, graylog2-web-interface/src/components/configurations/PermissionsConfig.tsx, graylog2-web-interface/src/pages/ConfigurationsPage.test.tsx, graylog2-web-interface/src/pages/ConfigurationsPage.tsx, graylog2-web-interface/src/stores/configurations/ConfigurationsStore.ts
Backport #11620
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#2970
- [] Bug fix (non-breaking change which fixes an issue)
=> Backport Option to configure sharing of entities (#11620)

graylog2-server/src/main/java/org/graylog/grn/GRNRegistry.java, graylog2-server/src/main/java/org/graylog/security/shares/DefaultGranteeService.java, graylog2-server/src/main/java/org/graylog2/users/UserAndTeamsConfig.java, graylog2-web-interface/src/actions/configurations/ConfigurationActions.js, graylog2-web-interface/src/components/common/InputDescription.tsx, graylog2-web-interface/src/components/configurations/PermissionsConfig.tsx, graylog2-web-interface/src/pages/ConfigurationsPage.test.tsx, graylog2-web-interface/src/pages/ConfigurationsPage.tsx, graylog2-web-interface/src/stores/configurations/ConfigurationsStore.ts
Backport #11620
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#2972
=>  backport config sharing

full-backend-tests/src/test/java/org/graylog/elasticsearch/e2e/ElasticsearchE2E.java, full-backend-tests/src/test/java/org/graylog/plugins/views/SearchSyncIT.java, full-backend-tests/src/test/java/org/graylog/testing/fullbackend/BackendStartupIT.java, full-backend-tests/src/test/java/org/graylog/testing/utils/SearchUtils.java
Safer logic for message presence check. 
Due to the recent changes in the test scope (method->class), the tests now share the same ES state. Each test has to count with the fact that its stored messages are not the only messages in the index.
=> Fixed search sync test

graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetConfig.java, graylog2-server/src/main/java/org/graylog2/indexer/indexset/IndexSetService.java, graylog2-server/src/main/java/org/graylog2/indexer/indexset/MongoIndexSetService.java
Backport https://github.com/Graylog2/graylog2-server/pull/11619 to the `4.2` branch.
=> Backport: IndexSetService enhancements needed to fix Illuminate index set upgrade issue

graylog2-server/src/test/java/org/graylog/testing/containermatrix/annotations/ContainerMatrixTest.java
Adding `@Testable` makes selecting a single method for testing inside IntelliJ IDEA possible.
https://github.com/Graylog2/graylog-plugin-enterprise/pull/2985 should be merged first but is not a requirement.
=> Added support to pick up a single method for testing in the IDE

graylog2-server/src/test/java/org/junit/platform/engine/support/hierarchical/ContainerMatrixHierarchicalTestEngine.java
Replace the `terminated` overall status for one lifecycle execution batch with a success/fail/error status
Before:
After:
=> Set overall lifecycle status for test execution

graylog2-server/src/main/java/org/graylog2/plugin/inputs/MessageInput.java
Addresses https://github.com/Graylog2/graylog2-server/pull/11373#discussion_r759582185
=> Add JavaDoc to describe onlyOnePerCluster()

graylog2-web-interface/packages/eslint-config-graylog/package.json, graylog2-web-interface/yarn.lock
This PR is updating `typescript-eslint` to v5.5.0, so it supports our typescript version properly.
=> Updating `typescript-eslint` to v5.

graylog2-web-interface/packages/eslint-config-graylog/index.js
This PR is updating the rule name referenced in our ESLint preset, which
got changed when updating `eslint-plugin-testing-library` in #11522.
=> Updating outdated rule reference in ESLint preset.

full-backend-tests/src/test/java/org/graylog/elasticsearch/e2e/ElasticsearchE2E.java, full-backend-tests/src/test/java/org/graylog/plugins/views/MessagesResourceIT.java, full-backend-tests/src/test/java/org/graylog/plugins/views/SearchMetadataIT.java, full-backend-tests/src/test/java/org/graylog/plugins/views/SearchSyncIT.java, full-backend-tests/src/test/java/org/graylog/plugins/views/TimeLimitIT.java, full-backend-tests/src/test/java/org/graylog/plugins/views/ViewsResourceIT.java, full-backend-tests/src/test/java/org/graylog/shared/system/stats/SystemStatsIT.java, full-backend-tests/src/test/java/org/graylog/testing/fullbackend/BackendStartupIT.java, full-backend-tests/src/test/java/org/graylog/testing/fullbackend/MongoDBFixturesWithClassLifecycleIT.java, full-backend-tests/src/test/java/org/graylog/testing/fullbackend/MongoDBFixturesWithVMLifecycleIT.java, graylog2-server/src/test/java/org/graylog/testing/containermatrix/ContainerMatrixTestEngine.java, graylog2-server/src/test/java/org/graylog/testing/containermatrix/annotations/ContainerMatrixTestsConfiguration.java, graylog2-server/src/test/java/org/graylog/testing/containermatrix/discovery/IsContainerMatrixTestClass.java, graylog2-server/src/test/java/org/junit/jupiter/engine/descriptor/ContainerMatrixTestsDescriptor.java, graylog2-server/src/test/java/org/junit/jupiter/engine/discovery/ContainerMatrixClassSelectorResolver.java, graylog2-server/src/test/java/org/junit/platform/engine/support/hierarchical/ContainerMatrixHierarchicalTestEngine.java
Lifecycle.VM and mongofixtures were not working reliably => fixed it
Also default Tests are with Lifecycle.VM and the full Matrix
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/2990
=> Fix for mongoFixtures in Lifecycle.VM, change default to test against full Matrix

graylog2-server/src/main/java/org/graylog2/Configuration.java, graylog2-server/src/main/java/org/graylog2/cluster/leader/AutomaticLeaderElectionService.java, graylog2-server/src/main/java/org/graylog2/cluster/lock/MongoLockService.java, graylog2-server/src/test/java/org/graylog2/ConfigurationTest.java, graylog2-server/src/test/java/org/graylog2/cluster/leader/AutomaticLeaderElectionServiceTest.java
Addresses https://github.com/Graylog2/graylog2-server/pull/11373#discussion_r756355725
=> Rename leader_election_lock_ttl to lock_service_lock_ttl

graylog2-web-interface/src/views/components/sidebar/fields/FieldTypeIcon.tsx
Prior to this PR, a field with type `ip` was shown with a question mark in the search's sidebar. This change is now adding an appropriate icon.
Fixes #11699.
Before:
After:
=> Adding icon for `ip` field type.

.github/workflows/build.yml
Allow maven to retry downloading dependencies during builds in github actions.
We are encountering following errors sometimes:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project graylog2-server: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile failed: Plugin org.apache.maven.plugins:maven-compiler-plugin:3.7.0 or one of its dependencies could not be resolved: Could not transfer artifact com.google.errorprone:error_prone_core:jar:2.3.1 from/to central (https://repo.maven.apache.org/maven2): transfer failed for https://repo.maven.apache.org/maven2/com/google/errorprone/error_prone_core/2.3.1/error_prone_core-2.3.1.jar: Connection reset -> [Help 1]
Error:  
Error:  To see …
```
=> Configure maven to retry downloading dependencies in github builds

graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/CollectingQueryParserTokenManager.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/ImmutableToken.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/LuceneQueryParser.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/ParsedQuery.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/ParsedTerm.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/QueryValidationServiceImpl.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/TermCollectingQueryParser.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/parser/LuceneQueryParserTest.java
Report correctly repeated unknown fields or invalid operators
Fixes #11712
Added one unit test
=> Fix repeating tokens reporting in query validation

graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/OpensearchInstance.java, graylog2-server/src/test/java/org/graylog/testing/containermatrix/SearchServer.java, graylog2-server/src/test/java/org/graylog/testing/elasticsearch/SearchServerInstance.java
=> Disable log4j message lookups in IT ES containers, update OpenSearch

pom.xml
(cherry picked from commit dac749f10cc387a28c384135b20b2cbf31fcb600)
(cherry picked from commit b62dbf3a3e5aeb8dae6ae4f2fcc9e23663cf9557)
=> update log4j from 2.16.0 to 2.17.0 (#11857)

graylog2-server/src/main/java/org/graylog2/configuration/converters/JavaDurationConverter.java, graylog2-server/src/test/java/org/graylog2/configuration/converters/JavaDurationConverterTest.java
=> Backport JavaDurationConverter to 4.2

graylog2-web-interface/src/views/components/DashboardSearchBar.test.tsx
Prior to this PR, one `DashboardSearchBar` test was already on the verge of hitting the configured timeout. With the changes introduced in #11769 which added another wait in this test, we are now running into a timeout every once in a while.
This change is now extending the timeout from 5 to 10s to prevent this.  In addition, we are investigating how to make the dashboard search bar faster.
=> Extending timeout for dashboard searchbar test.

graylog2-web-interface/package.json, graylog2-web-interface/yarn.lock
This PR is updating `puppeteer` to `v13.0.0`.
=> Updating `puppeteer` to v13.0.0.

graylog2-web-interface/packages/eslint-config-graylog/index.js
In #10556, the airbnb eslint ruleset was updated, including a couple of
transitive dependencies. This resulted in unwanted changes for our code
style (see f25892a6cfa5bc2f057d34c7600d147360b4c447).
This PR is now disabling newly-introduced/changed rules to restore the
previous code style. Minor adjustments may follow in a future PR.
=> Disabling newly-introduced ESLint rules for now.

graylog2-web-interface/src/components/common/CustomFontAwesomeIcon.tsx, graylog2-web-interface/src/components/common/Icon.jsx, graylog2-web-interface/src/components/common/__snapshots__/Pagination.test.jsx.snap, graylog2-web-interface/src/components/configurationforms/__snapshots__/ListField.test.tsx.snap, graylog2-web-interface/src/views/components/dashboard/__snapshots__/BigDisplayModeConfiguration.test.tsx.snap, graylog2-web-interface/src/views/components/queries/QueryTitle.test.tsx
Our `Icon` component is pulling in huge external dependencies, ending up as part of our `app` entry bundle. This PR is creating an indirection allowing to load the customized font awesome icon component asynchronously. This leads to a 25% size reduction (minified + gzipped from 1mb to ~750kb) of the `app` entry bundle.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#3025
=> Loading actual icon component asynchronously.

graylog2-web-interface/src/components/common/ExpandableListItem.tsx
This is a tiny PR improving the typings for the `ExpandableListItem`
component. The component allows to pass through props to the `Checkbox`
component which it uses internally, but these props are not included in
the `Props` type of `ExpandableListItem`. This leads to type failures
when a prop for `Checkbox` is passed through. This PR is now merging in
the props of the `Checkbox` component.
=> Include `Checkbox` props in `ExpandableListItem` props.

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/QueryValidationResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/CollectingQueryParserTokenManager.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/LineCountingCharStream.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/TokenLineCounter.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/ValidationMessage.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/parser/LuceneQueryParserTest.java
Backend support for multiline validation requested in #6530
=> Support for multiline in lucene query parser tokens

graylog2-server/src/test/java/org/graylog2/plugin/inputs/util/ConnectionCounterTest.java
This saves us from the trouble of finding
a usable and stable IP address on github action runners.
Refs https://github.com/actions/virtual-environments/issues/3185
=> Convert ConnectionCounterTest to using Mock Channels

full-backend-tests/src/test/java/org/graylog/plugins/views/SuggestionResourceIT.java, graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/QuerySuggestionsES6.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/QuerySuggestionsES7.java
This PR adds typo correction to the existing suggestions infrastructure
When there are no prefix suggestions, we check if there is any typo-correction suggestion and provide it (POTS->POST) 
Implements #11503
Added integration test
=> Suggest typo corrections for queries

graylog2-web-interface/src/views/components/aggregationwizard/visualization/VisualizationElement.ts, graylog2-web-interface/src/views/components/datatable/bindings.tsx, graylog2-web-interface/src/views/components/visualizations/area/bindings.tsx, graylog2-web-interface/src/views/components/visualizations/bar/bindings.tsx, graylog2-web-interface/src/views/components/visualizations/bindings.tsx, graylog2-web-interface/src/views/components/visualizations/heatmap/bindings.tsx, graylog2-web-interface/src/views/components/visualizations/line/bindings.tsx, graylog2-web-interface/src/views/components/visualizations/number/bindings.tsx, graylog2-web-interface/src/views/components/visualizations/pie/bindings.tsx, graylog2-web-interface/src/views/components/visualizations/scatter/bindings.tsx, graylog2-web-interface/src/views/components/visualizations/worldmap/bindings.tsx, graylog2-web-interface/src/views/logic/views/CopyWidgetToDashboard.ts, graylog2-web-interface/src/views/types.ts
Prior to this PR, the general views types were in a `types.d.ts` file.  These do provide types, but are not type-checked themselves. This leads to type errors being silently introduced.
This PR is renaming the file to enable type-checking and adds/adjusts a couple of types.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#3101
=> Enabling type checking for general views types.

graylog2-server/src/main/java/org/graylog/plugins/views/search/Query.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/Search.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchType.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ExecutionGlobalOverride.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ExecutionState.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ExecutionStateGlobalOverride.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchTypeExecutionState.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/MessageList.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/events/EventList.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/Pivot.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/QueryTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/SearchTest.java
This PR aims to provide fully type-safe execution state class. It continues in the previous execution state refactoring. 
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#3043
=> Execution state global override refactoring

graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewStateDTO.java
This is a small PR to provide a helper function that allows retrieving
the query title if it is existing.
=> Adding helper function to retrieve query title.

graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewStateDTO.java
=> Code cleanup in the ViewStateDTO class (simpler optional logic)

.github/dependabot.yml
This PR is adding the `stylelint-config-graylog` package to the
dependabot config, so security/dependency updates are created.
=> Adding stylelint package to dependabot.

graylog2-web-interface/package.json, graylog2-web-interface/src/components/content-packs/ContentPackDetails.jsx, graylog2-web-interface/yarn.lock
This PR is updating `marked` to version 4.0.10 in order to address to
vulnerabilities resulting in catastrophic backtracking:
- https://github.com/advisories/GHSA-5v2h-r2cx-5xgj
- https://github.com/advisories/GHSA-rrrm-qjm4-v8hf
=> Updating marked to 4.0.10 (4.2).

graylog2-web-interface/package.json, graylog2-web-interface/src/components/content-packs/ContentPackDetails.jsx, graylog2-web-interface/yarn.lock
This PR is updating `marked` to version 4.0.10 in order to address to
vulnerabilities resulting in catastrophic backtracking:
- https://github.com/advisories/GHSA-5v2h-r2cx-5xgj
- https://github.com/advisories/GHSA-rrrm-qjm4-v8hf
=> Updating marked to 4.0.10 (4.1).

graylog2-web-interface/package.json, graylog2-web-interface/src/components/content-packs/ContentPackDetails.jsx, graylog2-web-interface/yarn.lock
This PR is updating `marked` to version 4.0.10 in order to address to
vulnerabilities resulting in catastrophic backtracking:
- https://github.com/advisories/GHSA-5v2h-r2cx-5xgj
- https://github.com/advisories/GHSA-rrrm-qjm4-v8hf
=> Updating marked to 4.0.10 (4.0).

graylog2-server/src/main/java/org/graylog/plugins/views/search/views/Position.java
There are older dashboards which were created with a `Position` containing float attributes. `Position` expects them to be integer, resulting in exceptions when parsing these.
This PR makes parsing more tolerant and accepts any number, returning the integer part.
=> Making deserialization of `Position` more tolerant.

graylog2-web-interface/src/components/common/ExternalLink.tsx, graylog2-web-interface/src/components/common/Icon.tsx, graylog2-web-interface/src/components/common/IconButton.tsx, graylog2-web-interface/src/components/common/Spinner.tsx, graylog2-web-interface/src/views/components/searchbar/SearchButton.tsx, graylog2-web-interface/src/views/components/searchbar/date-time-picker/AbsoluteTimeInput.tsx, graylog2-web-interface/src/views/components/sidebar/NavItem.tsx, graylog2-web-interface/src/views/components/sidebar/Sidebar.tsx, graylog2-web-interface/src/views/components/sidebar/sidebarSections.tsx, graylog2-web-interface/src/views/components/widgets/FieldSortIcon.tsx, graylog2-web-interface/src/views/components/widgets/UnknownWidget.tsx
With this PR we are migrating the `Icon` component to TypeScript. This enables autocompletion for props like `size` and `name`. It also helps us to avoid unexpected behaviours. In one case we used the prop `bsSize` instead of `size`.
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/3138
=> Migrate `Icon` component to TypeScript.

graylog2-web-interface/src/components/navigation/Navigation.tsx, graylog2-web-interface/src/pages/SecurityPage.tsx, graylog2-web-interface/src/pages/index.jsx, graylog2-web-interface/src/routing/AppRouter.tsx, graylog2-web-interface/src/routing/Routes.ts
- Adds placeholder route for new security app plugin
- Adds placeholder page for new security app plugin
This provides the navigational adjustments to the core application for
the introduction of the security app plugin.
Needed to get navigational items in place for the new product.
Tested locally and ran unit tests.
=> Routing and navigation for Graylog Security product

graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/QueryValidationServiceImpl.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/SubstringMultilinePosition.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/ValidationMessage.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/validation/SubstringMultilinePositionTest.java
Use the existing validation to warn about undefined query parameters.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/3103
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#3106
=> Custom validation handling for undeclared parameters

graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/QueryValidationServiceImpl.java
This PR solves problem [#3000](https://github.com/Graylog2/graylog-plugin-enterprise/issues/3000), where the validation positions were wrong. This was caused by query validation executed on aready decorated queries. The position was based on the decorated, not the original query.
The validation now uses the original query instead of the decorated, avoiding the problem with different validation positions between original and decorated queries.
Fixes [#3000](https://github.com/Graylog2/graylog-plugin-enterprise/issues/3000)
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#3156
Added integration test
=> Fix validation positions for queries with enterprise params

graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java
This change reverts one line back, so there is a MultiBinder correctly bound  by Guice. With the previous change, the Integration Tests got broken. The problem is not obvious on Jenkins because the containers are still started so the runtime is not changing. And the errors are not propagated to fail the test.
This can be replicated by e.g. running `MessageResourceIT` from the IDE.
```
2022-02-01 15:32:59,589 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for java.util.Set<org.graylog2.migrations.V20201103145400_LegacyAuthServiceMigration$MigrationModule> was bound.
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:
1) [Guice/MissingImplementation]: No …
```
=> Revert MultiBinder back to previous settings

full-backend-tests/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
This change fixes the server lifecycle so these tests don't crash with other tests.
=> Fix Lifecycle for IndicesIT 

.github/workflows/update-browserslist-db.yml
This PR is adding a github action that runs every 14 days, trying to update the browserslist db and create a PR with the changes.
=> Add github action to update browserslist db every 14 days.

graylog2-web-interface/yarn.lock
This PR is updating the browserslist db used to the most recent version.
=> Updating browserslist db to 1.0.30001303.

graylog2-web-interface/package.json
This PR is removing several version pins for transitive dependencies which have become obsolete.
=> Removing unused version pins.

graylog2-web-interface/package.json
This PR is removing the `sockjs-client` dependency, because it is unused.
=> Removing unused `sockjs-client` frontend dependency.

graylog2-server/src/main/java/org/graylog2/bootstrap/ServerBootstrap.java, pom.xml
As the title suggests. Selenium is used in the Enterprise Plugin but the update has to be done here.
=> Update Guava to 31.0.1 for Selenium 4.2.1 to work

full-backend-tests/src/test/java/org/graylog/plugins/views/QueryValidationResourceIT.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/QueryValidationResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/LuceneQueryParser.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/ParsedTerm.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/QueryValidationServiceImpl.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/TermCollectingQueryVisitor.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/parser/LuceneQueryParserTest.java
Fixed edge cases for query validation, refactored query visitor for safer and more generic handling of query types.
Fixes #12128. Additionally this PR handles also lowercase _not_ operator, which should be also written uppercase, as AND and OR operators.
Added unit and integration tests
=> Fix some edge cases in query validation

graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/LineCountingCharStream.java
Removed forgotten stdout debu logging in lucene query parsing.
=> Removed forgotten stdout debug logging

graylog2-server/src/main/java/org/graylog2/storage/SearchVersion.java
adds a quick check to use in ElasticSearch OR OpenSearch logic elsewhere in code
adds a quick check to use in ElasticSearch OR OpenSearch logic elsewhere in code
cleans up boolean logic when dealing with ES vs OS branches
=> Adds isElasticsearch function

graylog2-server/src/main/java/org/graylog2/Configuration.java, graylog2-server/src/main/java/org/graylog2/database/PersistedServiceImpl.java, graylog2-server/src/main/java/org/graylog2/inputs/Input.java, graylog2-server/src/main/java/org/graylog2/inputs/InputImpl.java, graylog2-server/src/main/java/org/graylog2/inputs/InputService.java, graylog2-server/src/main/java/org/graylog2/inputs/InputServiceImpl.java, graylog2-server/src/main/java/org/graylog2/inputs/PersistedInputsImpl.java, graylog2-server/src/main/java/org/graylog2/plugin/inputs/MessageInput.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/InputStatesResource.java, graylog2-server/src/main/java/org/graylog2/shared/inputs/InputLauncher.java, graylog2-server/src/main/java/org/graylog2/shared/inputs/PersistedInputs.java, misc/graylog.conf
Backport for:
- #11362
- #11771
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#3258
This backport is requiered for:
- Graylog2/forwarder#27
- Graylog2/forwarder#28
=> Manually stopped inputs do not auto-restart - backport

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchTypeExecutionState.java
Fix `after` DTO mapping for log view scrolling.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/3233
=> Fix log view scrolling up

graylog2-web-interface/src/components/navigation/SystemMenu.jsx, graylog2-web-interface/src/routing/AppRouter.tsx
For https://github.com/Graylog2/graylog-plugin-cloud/issues/1005 we need to re-enable sidecars in cloud. So disabling the system menu item and pages is not needed anymore.
Checked the menu and pages if they loaded. Need to actually test if it works with the backend. And probably needs documentation updates.
=> Re-enable sidecars on cloud

full-backend-tests/src/test/java/org/graylog/testing/fullbackend/BackendStartupIT.java, full-backend-tests/src/test/java/org/graylog/testing/fullbackend/MongoDBFixturesWithClassLifecycleIT.java, full-backend-tests/src/test/java/org/graylog/testing/fullbackend/MongoDBFixturesWithVMLifecycleIT.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/ContainerizedGraylogBackend.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/GraylogBackend.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/RunningGraylogBackend.java, graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeInstance.java, graylog2-server/src/test/resources/org/graylog/testing/graylognode/Dockerfile
Add the output of the server log from the Docker container if an integration test fails
=> Add the output of the server log from the Docker container if an integration test fails

graylog2-web-interface/src/components/common/URLWhiteListInput.tsx, graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationForm.jsx, graylog2-web-interface/src/components/event-notifications/event-notification-types/HttpNotificationForm.jsx
=> Disable HTTP Notification submit when url field have error

graylog2-web-interface/src/components/grok-patterns/BulkLoadPatternModal.jsx
These changes use `onSubmitForm` props to fix grok pattern from file import form.
fix:  #12314
=> Fix GROK pattern from file import form 

graylog2-web-interface/src/views/components/sidebar/create/AddWidgetButton.tsx
Fixes enterprise issue https://github.com/Graylog2/graylog-plugin-enterprise/issues/3296
Adds text, that a log view is an enterprise feature.
=> Added additional text that log view is an enterprise feature

graylog2-server/src/main/java/org/graylog2/cluster/leader/FakeLeaderElectionModule.java, graylog2-server/src/main/java/org/graylog2/cluster/leader/FakeLeaderElectionService.java
Provide a leader election service that always returns true. 
This is needed when leader election is not required / possible, e.g. the Forwarder.
=> Always true LeaderElectionModule

graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
Migrations should not need to deal with the leader election at all.
=> Use FakeLeaderElectionModule for Migration command

graylog2-server/src/main/java/org/graylog2/shared/security/AccessTokenAuthToken.java, graylog2-server/src/main/java/org/graylog2/shared/security/SessionIdToken.java
See related issue for details
Resolves Graylog2/graylog-plugin-enterprise#3418
=> graylog-plugin-enterprise/issues/3418

graylog2-server/src/main/java/org/graylog2/shared/security/AccessTokenAuthToken.java, graylog2-server/src/main/java/org/graylog2/shared/security/SessionIdToken.java
=> backport graylog-plugin-enterprise/issues/3418 to 4.2

graylog2-server/src/main/java/org/graylog2/shared/security/AccessTokenAuthToken.java, graylog2-server/src/main/java/org/graylog2/shared/security/SessionIdToken.java
=> backport graylog-plugin-enterprise/issues/3418 to 4.1

graylog2-server/src/main/java/org/graylog2/shared/security/AccessTokenAuthToken.java, graylog2-server/src/main/java/org/graylog2/shared/security/SessionIdToken.java
=> backport graylog-plugin-enterprise/issues/3418 to 3.3

graylog2-server/src/main/java/org/graylog2/shared/security/AccessTokenAuthToken.java, graylog2-server/src/main/java/org/graylog2/shared/security/SessionIdToken.java
=> backport graylog-plugin-enterprise/issues/3418 to 4.0

.github/workflows/reviewbot.yml
This PR is adding a new github action running for PRs, which is supposed to replace our current frontend linter job. It is supperior in a way that it creates a PR review when it finds linter hints, adding review comments for the hints it found at their respective locations.
In this initial PR the action is added for PRs with a branch starting with `reviewbot` to avoid interrupting our general PR workflow.
=> Adding reviewbot to actions for testing.

graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/QueryValidationServiceImpl.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/fields/UnknownFieldsIdentifier.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/MessagesResourceTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/validation/fields/UnknownFieldsIdentifierTest.java
Unknown fields identification moved to a separate class and given its own unit test.
QueryValidationServiceImpl class does not have single responsibility.
=> Unknown fields identification moved to a separate class. 

.github/workflows/reviewbot.yml
Prior to this change, only the HEAD commit was checked out. In order to
determine the delta, we need the complete git history.
=> Increase fetch depth for PR review action.

graylog2-server/src/main/java/org/graylog/security/shares/EntitySharesService.java
Small typo fix: `avialable` -> `available`
Just noticed this, and cleaning it up.
The PR build will provide sufficient testing. Please just make sure the new spelling is correct.
=> Fix typo avialable -> available

graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
Minor improvement to Graylog2/graylog2-server#12418 so we are not sensitive to case in the role name check.
=> graylog-plugin-enterprise/issues/3419 errata for 4.0

graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180323150000_AddSidecarUser.java, graylog2-server/src/main/java/org/graylog2/migrations/MigrationHelpers.java, graylog2-server/src/main/java/org/graylog2/plugin/database/users/User.java, graylog2-server/src/main/java/org/graylog2/rest/models/users/requests/ChangeUserRequest.java, graylog2-server/src/main/java/org/graylog2/rest/models/users/requests/CreateUserRequest.java, graylog2-server/src/main/java/org/graylog2/rest/models/users/responses/UserSummary.java, graylog2-server/src/main/java/org/graylog2/rest/resources/roles/RolesResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/SessionsResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java, graylog2-server/src/main/java/org/graylog2/users/RoleServiceImpl.java, graylog2-server/src/main/java/org/graylog2/users/UserImpl.java, graylog2-server/src/main/java/org/graylog2/users/UserOverviewDTO.java, graylog2-server/src/test/java/org/graylog2/rest/models/users/responses/UserSummaryTest.java, graylog2-server/src/test/java/org/graylog2/rest/resources/users/UsersResourceTest.java, graylog2-web-interface/src/components/users/UserCreate/ServiceAccountFormGroup.tsx, graylog2-web-interface/src/components/users/UserCreate/UserCreate.tsx, graylog2-web-interface/src/components/users/UserDetails/SettingsSection.tsx, graylog2-web-interface/src/components/users/UserEdit/SettingsSection.test.tsx, graylog2-web-interface/src/components/users/UserEdit/SettingsSection.tsx, graylog2-web-interface/src/logic/users/User.ts
See https://github.com/Graylog2/graylog-plugin-enterprise/issues/3419 for details
=> graylog-plugin-enterprise/issues/3419 backport to 4.2

graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180323150000_AddSidecarUser.java, graylog2-server/src/main/java/org/graylog2/migrations/MigrationHelpers.java, graylog2-server/src/main/java/org/graylog2/plugin/database/users/User.java, graylog2-server/src/main/java/org/graylog2/rest/models/users/requests/ChangeUserRequest.java, graylog2-server/src/main/java/org/graylog2/rest/models/users/requests/CreateUserRequest.java, graylog2-server/src/main/java/org/graylog2/rest/models/users/responses/UserSummary.java, graylog2-server/src/main/java/org/graylog2/rest/resources/roles/RolesResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/SessionsResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java, graylog2-server/src/main/java/org/graylog2/users/RoleServiceImpl.java, graylog2-server/src/main/java/org/graylog2/users/UserImpl.java, graylog2-server/src/main/java/org/graylog2/users/UserOverviewDTO.java, graylog2-server/src/test/java/org/graylog2/rest/models/users/responses/UserSummaryTest.java, graylog2-server/src/test/java/org/graylog2/rest/resources/users/UsersResourceTest.java, graylog2-web-interface/src/components/users/UserCreate/ServiceAccountFormGroup.tsx, graylog2-web-interface/src/components/users/UserCreate/UserCreate.tsx, graylog2-web-interface/src/components/users/UserDetails/SettingsSection.tsx, graylog2-web-interface/src/components/users/UserEdit/SettingsSection.test.tsx, graylog2-web-interface/src/components/users/UserEdit/SettingsSection.tsx, graylog2-web-interface/src/logic/users/User.ts, graylog2-web-interface/test/fixtures/users.ts
See https://github.com/Graylog2/graylog-plugin-enterprise/issues/3419 for details
=> graylog-plugin-enterprise/issues/3419 backport to 4.1

graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180323150000_AddSidecarUser.java, graylog2-server/src/main/java/org/graylog2/migrations/MigrationHelpers.java, graylog2-server/src/main/java/org/graylog2/plugin/database/users/User.java, graylog2-server/src/main/java/org/graylog2/rest/models/users/requests/CreateUserRequest.java, graylog2-server/src/main/java/org/graylog2/rest/models/users/responses/UserSummary.java, graylog2-server/src/main/java/org/graylog2/rest/resources/roles/RolesResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/SessionsResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java, graylog2-server/src/main/java/org/graylog2/shared/users/ChangeUserRequest.java, graylog2-server/src/main/java/org/graylog2/users/RoleServiceImpl.java, graylog2-server/src/main/java/org/graylog2/users/UserImpl.java, graylog2-server/src/main/java/org/graylog2/users/UserOverviewDTO.java, graylog2-server/src/test/java/org/graylog2/rest/models/users/responses/UserSummaryTest.java, graylog2-server/src/test/java/org/graylog2/rest/resources/users/UsersResourceTest.java, graylog2-web-interface/src/components/users/UserCreate/ServiceAccountFormGroup.tsx, graylog2-web-interface/src/components/users/UserCreate/UserCreate.tsx, graylog2-web-interface/src/components/users/UserDetails/SettingsSection.tsx, graylog2-web-interface/src/components/users/UserEdit/SettingsSection.test.tsx, graylog2-web-interface/src/components/users/UserEdit/SettingsSection.tsx, graylog2-web-interface/src/logic/users/User.ts
See https://github.com/Graylog2/graylog-plugin-enterprise/issues/3419 for details
=> graylog-plugin-enterprise/issues/3419 backport to 4.3 RC

graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/PreflightCheckService.java
(cherry picked from commit c015938fa0a0c03a3937bd41cabd2bfe395763da)
=> Log cause of failed preflight check

graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/QueryValidationServiceImpl.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/QueryValidator.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/ValidationContext.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/fields/UnknownFieldsIdentifier.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/fields/UnknownFieldsValidator.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/MessagesResourceTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/validation/TestValidationContext.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/validation/fields/UnknownFieldsIdentifierTest.java
Introduced a QueryValidation interface, that could be implemented by several validators, each handling a small portion of the complex validation. Adapted UnknownFieldsIdentifier to implement this interface.
=> QueryValidator interface, unknown fields adapted

graylog2-web-interface/packages/jest-preset-graylog/jest-preset.js, graylog2-web-interface/packages/jest-preset-graylog/package.json, graylog2-web-interface/yarn.lock
With the introduction of the session cookie authentication in the frontend, the `jest-localstorage-mock` module has become obsolete, therefore this PR removes it.
=> Removing now unneeded `jest-localstorage-mock` module.

graylog2-web-interface/devServer.js
It allows the backend API to take control over the `config.js` we request in the frontend. This way we can truely communicate settings saved on the backend to the frontend.
For cloud there are a couple of settings from enviroment variables which are communicated to the frontend through the `config.js` file. It's quite a hasle to change the `config.js` file manually and revert the file back before committing.
By visiting `localhost:8080/config.js` and checking if the API version is served.
=> feat: proxy request for localhost:8080/config.js to backend API

graylog2-web-interface/package.json, graylog2-web-interface/src/components/common/URLWhiteListFormModal.tsx, graylog2-web-interface/src/components/configurations/UrlWhiteListForm.tsx, graylog2-web-interface/src/components/content-packs/ContentPackEntitiesList.test.jsx, graylog2-web-interface/src/components/content-packs/ContentPackParameterList.test.jsx, graylog2-web-interface/src/components/content-packs/ContentPackParameters.test.jsx, graylog2-web-interface/src/components/content-packs/ContentPackSelection.test.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterForm.jsx, graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterPreviewContainer.jsx, graylog2-web-interface/src/logic/content-packs/ContentPack.js, graylog2-web-interface/src/logic/generateId.ts, graylog2-web-interface/src/views/components/actions/ActionHandler.tsx, graylog2-web-interface/src/views/components/aggregationwizard/grouping/GroupingElement.ts, graylog2-web-interface/src/views/components/aggregationwizard/sort/SortElement.ts, graylog2-web-interface/src/views/components/sidebar/create/AddWidgetButton.tsx, graylog2-web-interface/src/views/logic/Widgets.ts, graylog2-web-interface/src/views/logic/queries/Query.ts, graylog2-web-interface/src/views/logic/queries/QueryGenerator.ts, graylog2-web-interface/src/views/logic/searchtypes/SearchTypesGenerator.ts, graylog2-web-interface/src/views/logic/searchtypes/aggregation/PivotConfigGenerator.ts, graylog2-web-interface/src/views/logic/views/CopyWidgetToDashboard.test.ts, graylog2-web-interface/src/views/logic/views/MoveWidgetToTab.test.ts, graylog2-web-interface/src/views/logic/views/UpdateSearchForWidgets.test.ts, graylog2-web-interface/src/views/logic/widgets/Widget.ts, graylog2-web-interface/src/views/stores/WidgetStore.ts, graylog2-web-interface/yarn.lock
This PR is updating the `uuid` used to generate ids in multiple places to the newest version. For this, we need to change the way the package is imported. In order to reduce future effort to update (or replace) the uuid generation module, this PR is creating a central, reusable id generator function (`generateId`), which is encapsulating the id generation algorithm and the used package.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#3476
=> Extract reusable id generator function, update `uuid` to `v8.x.x`.

graylog2-web-interface/src/components/common/FormikFormGroup.tsx
Back-port of add-rows-prop-to-formikformgroup
Back-port of add-rows-prop-to-formikformgroup
=> Add missing rows prop to FormikFormGroup for textarea inputs (#12509)

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ValidationMessageDTO.java
Error title gets created by back-end from validation type, so that front-end can use it when visualizing validation messages.
Error title was missing after recent round of refactoring.
Type a few wrong search queries, like "omg:omg" and "timestamp:text".
Open the validation message component to notice that title was missing before this change and it present now.
You can also test it on the REST API level, using "search/validate" endpoint.
=> Validation REST API : Error title created by back-end from val. type

graylog2-web-interface/src/components/users/UserCreate/UserCreate.test.tsx, graylog2-web-interface/src/components/users/UserCreate/UserCreate.tsx
The user creation tests had some commented out test cases which needed fixing. This PR is cleaning up the tests and the related component a bit and puts these test cases in place again.
=> Improve tests for user creation.

graylog2-web-interface/package.json, graylog2-web-interface/yarn.lock
This PR is updating Font Awesome packages. These are comprised of multiple, individual packages which cannot be updated separately through `dependabot`, so this PR is combining the updates.
=> Updating font awesome packages.

graylog2-web-interface/src/components/bootstrap/BootstrapModalForm.jsx
With this change it will be possible to display e.g. a loading spinner for the submit button in the `BootstrapModalForm`.
=> Allow defining a component for submit button content in `BootstrapModalForm`.

UPGRADING.md
=> Release note: input restart behavior

UPGRADING.md
Documents Graylog2/graylog2-server#12337
=> Release note for input encoding

graylog2-server/src/main/java/org/graylog2/shared/rest/resources/ProxiedResource.java
=> Make authenticationToken method public (4.3)

graylog2-server/src/main/java/org/graylog2/shared/rest/resources/ProxiedResource.java
changes access to method for getting an auth token from HTTP headers
part of a fix for issue where illuminate bundles could no longer be installed using an auth token
=> Make authenticationToken method public

graylog2-web-interface/src/components/configurations/UrlWhiteListForm.tsx, graylog2-web-interface/src/contexts/FormWarningsProvider.tsx, graylog2-web-interface/src/hooks/useIsMountedRef.test.ts, graylog2-web-interface/src/hooks/useIsMountedRef.ts
With this PR we are creating a simple hook which determines if a component is mounted. We need this information in a few cases, e.g. to avoid the `Can't perform a React state update on an unmounted component.` warning.
=> Create hook to determine if a component is mounted.

graylog2-server/src/test/java/org/graylog/testing/completebackend/ContainerizedGraylogBackend.java, graylog2-server/src/test/java/org/graylog/testing/containermatrix/ContainerMatrixTestEngine.java, graylog2-server/src/test/java/org/graylog/testing/containermatrix/annotations/ContainerMatrixTestsConfiguration.java, graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerConfig.java, graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerFactory.java, graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeInstance.java, graylog2-server/src/test/java/org/junit/jupiter/engine/descriptor/ContainerMatrixTestsDescriptor.java, graylog2-server/src/test/java/org/junit/platform/engine/support/hierarchical/ContainerMatrixHierarchicalTestEngine.java
Added support for FeatureFlags in Integration Tests
There are cases, such as Anomaly Detection Endpoints, that require FeatureFlags.   These changes allow testing of endpoints that require feature flags.
Added Integration Test for Anomaly Detection--still in progress ( [Feature Flags Support](https://github.com/Graylog2/graylog-plugin-enterprise/pull/3645) )
=> Added support for FeatureFlags in Integration Tests

graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/references/ValueReference.java, graylog2-server/src/test/java/org/graylog2/contentpacks/model/entities/references/ValueReferenceTest.java
Added `ofNullable` methods to avoid repeated null checks all around the codebase.
=> Multiple reporting frequencies

graylog2-web-interface/src/components/cluster/GraylogClusterOverview.tsx
Backport to `4.3` for Graylog2/graylog2-server#12751
=> Check permissions for EnterpriseTrafficGraph (4.3 backport)

graylog2-web-interface/babel.config.js, graylog2-web-interface/package.json, graylog2-web-interface/yarn.lock
This PR is removing the `@babel/plugin-proposal-class-properties` module, due to it becoming obsolete through the inclusion of the proposal in [Babel 7.14.0](https://babeljs.io/blog/2021/04/29/7.14.0#new-class-features-enabled-by-default).
/jenkins-pr-deps Graylog2/graylog-plugin-integrations#1045,Graylog2/graylog-plugin-enterprise-integrations#814
=> Remove class properties proposal babel plugin.

graylog2-web-interface/src/views/components/DashboardSearchBar.pluggableControls.test.tsx, graylog2-web-interface/src/views/components/DashboardSearchBar.tsx, graylog2-web-interface/src/views/components/SearchBar.pluggableControls.test.tsx, graylog2-web-interface/src/views/components/SearchBar.tsx, graylog2-web-interface/src/views/components/WidgetQueryControls.pluggableControls.test.tsx, graylog2-web-interface/src/views/components/WidgetQueryControls.tsx, graylog2-web-interface/src/views/components/searchbar/PluggableSearchBarControls.tsx, graylog2-web-interface/src/views/components/searchbar/pluggableSearchBarControlsHandler.ts, graylog2-web-interface/src/views/components/searchbar/pluggableSearchBarControlsHelper.test.tsx, graylog2-web-interface/src/views/logic/queries/Query.ts, graylog2-web-interface/src/views/logic/views/__snapshots__/ViewTransformer.test.ts.snap, graylog2-web-interface/src/views/stores/SearchStore.ts, graylog2-web-interface/src/views/types.ts
_Please note this PR needs to be merged together with https://github.com/Graylog2/graylog-plugin-enterprise/pull/3609_
With this PR pluggable search bar controls are able to update the current query on submit.
For this functionality it was necessary change the interface of pluggable search bar controls.
Before this change a pluggable search bar control had just generic `useInitialValues` and `onSubmit` methods.
Instead they now have specific methods for searches and dashboard widgets. This separation was necessary, because we need to work with the current query on the search page and the widget, when editing a dashboard widget.
The dashboard widget specific functionality is also required for https://github.com/Graylog2/graylog-plugin-enterprise/issues/3647
/jenkins-pr-deps …
=> Allow extending current query with pluggable search bar controls, on submit.

graylog2-server/src/main/java/org/graylog/plugins/views/search/searchfilters/model/InlineQueryStringSearchFilter.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/searchfilters/model/ReferencedQueryStringSearchFilter.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/searchfilters/model/UsedSearchFilter.java
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#3665
Necessary model changes to solve BE part of : https://github.com/Graylog2/graylog-plugin-enterprise/issues/3402
=> UsedSearchFilter negation is now possible and can be persisted.

graylog2-server/src/main/java/org/graylog/plugins/map/geoip/MaxMindIpLocationResolver.java, graylog2-server/src/test/java/org/graylog/plugins/map/geoip/MaxMindIpLocationResolverTest.java
=> Backported GeoIP Processor Bug Fix to 4.3

.github/dependabot.yml, graylog2-web-interface/babel.config.js, graylog2-web-interface/package.json, graylog2-web-interface/packages/babel-preset-graylog/.gitignore, graylog2-web-interface/packages/babel-preset-graylog/index.js, graylog2-web-interface/packages/babel-preset-graylog/package.json, graylog2-web-interface/packages/graylog-web-plugin/package.json, graylog2-web-interface/webpack.config.js, graylog2-web-interface/yarn.lock
This PR is creating a `babel-preset-graylog` package in order to share our babel config and the related versions across core and plugins.
=> Adding separate package for shared babel config.

.github/workflows/fix-linter-hints.yml, .github/workflows/update-browserslist-db.yml, .github/workflows/updating-lockfile.yml
This PR is adding the `workflow_dispatch` event to the jobs which are running periodically to
- fix linter hints
- update the yarn lockfile
- update the browsersdb
allowing us to run them on demand in addition to the configured schedule.
=> Allow running workflows on demand.

graylog2-server/src/main/java/org/graylog2/shared/system/stats/fs/OshiFsProbe.java, graylog2-server/src/main/java/org/graylog2/shared/system/stats/os/OshiOsProbe.java
Backport of #12821 to 4.3
Resolves #12855
=> Prevent divide-by-zero exceptions in preflight checks (#12821)

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/PipelineResource.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/RuleResource.java
Adds exception handling to PipelineResource.java and RuleResource.java to return a HTTP `400` client error indicating invalid input.
When in Illuminate development mode, validation checks are performed for new pipeline and rule titles. If a title is deemed to be invalid an `IllegalArgumentException` is thrown in the `OnDiskService` calsses. This PR handles that case by throwing a `BadRequestException`, returning a HTTP `400` client error to the user.
Related to graylog2-server in https://github.com/Graylog2/graylog2-server/pull/12729
and https://github.com/Graylog2/graylog-plugin-enterprise/pull/3633
The changes made to enable in app Illuminate development can result in `IllegalArgumentException` being thrown in response when a user attempts to create or update invalid pipelines or rules. …
=> Adds Exception Handling to Pipeline/Rule Resources to Return Valid Response Type

graylog2-server/src/main/java/org/graylog/metrics/prometheus/PrometheusExporter.java, graylog2-server/src/test/java/org/graylog/metrics/prometheus/PrometheusExporterTest.java
* refactoring of PrometheusExporter for graylog forwarder
* add missing license header
* remove unnecessary pom change
* fix forbidden api call
* rollback config changes
=> refactoring of PrometheusExporter for graylog forwarder (#12764)

full-backend-tests/src/test/java/org/graylog2/indexer/indices/IndicesIT.java, graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndicesAdapterES6.java, graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/blocks/JestBlockSettingsParser.java, graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/blocks/JestBlockSettingsParserTest.java, graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/testing/ClientES6.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/blocks/BlockSettingsParser.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/blocks/BlockSettingsParserTest.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ClientES7.java, graylog2-server/src/main/java/org/graylog2/bindings/PeriodicalBindings.java, graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java, graylog2-server/src/main/java/org/graylog2/indexer/indices/IndicesAdapter.java, graylog2-server/src/main/java/org/graylog2/indexer/indices/blocks/IndicesBlockStatus.java, graylog2-server/src/main/java/org/graylog2/notifications/Notification.java, graylog2-server/src/main/java/org/graylog2/periodical/IndexBlockCheck.java, graylog2-server/src/test/java/org/graylog/testing/elasticsearch/Client.java, graylog2-web-interface/src/logic/notifications/NotificationsFactory.jsx
Backporting #12290 to solve #10930 on 4.3.x version.
This PR is planned to be merged to 4.3.3, so please merge it **AFTER 4.3.2 has been released**!
See #10930.
=> Notification is presented if any active writing index is blocked (4.3.x).

graylog2-web-interface/src/components/bootstrap/Input.jsx, graylog2-web-interface/src/components/common/InputDescription.tsx
With this PR it will be possible to define a `className` for the `InputDescription` component.
=> Allow extending `InputDescription` style.

graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexSetValidator.java, graylog2-server/src/main/java/org/graylog2/indexer/retention/strategies/UnknownRetentionStrategyConfig.java, graylog2-server/src/main/java/org/graylog2/plugin/indexer/retention/RetentionStrategyConfig.java, graylog2-server/src/main/java/org/graylog2/rest/models/system/indices/RetentionStrategies.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexSetsResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indices/RetentionStrategyResource.java, graylog2-server/src/test/java/org/graylog2/indexer/IndexSetValidatorTest.java, graylog2-server/src/test/java/org/graylog2/migrations/V20161116172100_DefaultIndexSetMigrationTest.java, misc/graylog.conf
Backport #12299 to 4.3
See Graylog2/graylog-plugin-cloud#1006 for details.
=> Config option to set upper limit for index retention period

graylog2-web-interface/src/components/indices/IndexMaintenanceStrategiesConfiguration.jsx, graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.test.tsx, graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.tsx, graylog2-web-interface/src/components/indices/Types.ts, graylog2-web-interface/src/components/indices/retention/ClosingRetentionStrategyConfiguration.jsx, graylog2-web-interface/src/components/indices/retention/ClosingRetentionStrategySummary.jsx, graylog2-web-interface/src/components/indices/retention/DeletionRetentionStrategyConfiguration.jsx, graylog2-web-interface/src/components/indices/retention/DeletionRetentionStrategySummary.jsx, graylog2-web-interface/src/components/indices/retention/NoopRetentionStrategyConfiguration.jsx, graylog2-web-interface/src/components/indices/retention/NoopRetentionStrategySummary.jsx, graylog2-web-interface/src/components/indices/rotation/MessageCountRotationStrategyConfiguration.jsx, graylog2-web-interface/src/components/indices/rotation/MessageCountRotationStrategySummary.jsx, graylog2-web-interface/src/components/indices/rotation/SizeBasedRotationStrategyConfiguration.jsx, graylog2-web-interface/src/components/indices/rotation/SizeBasedRotationStrategySummary.jsx, graylog2-web-interface/src/components/indices/rotation/TimeBasedRotationStrategyConfiguration.jsx, graylog2-web-interface/src/pages/IndexSetConfigurationPage.jsx, graylog2-web-interface/src/pages/IndexSetCreationPage.tsx, graylog2-web-interface/src/stores/indices/IndicesConfigurationStore.ts
Backport #12515 
ref Graylog2/graylog-plugin-enterprise#3734,  Graylog2/graylog2-server#12905
=> Backport Show max retention period warning when it is set

.github/workflows/no-response.yml
This change is replacing the [no response app](https://github.com/probot/no-response) with a [github action](https://github.com/lee-dohm/no-response) as it is not recommended to be used anymore.
=> Replace no response app with action.

graylog2-web-interface/CONTRIBUTING.md, graylog2-web-interface/README.md
Before this change, we were maintaining our frontend conventions in our corporate wiki. We decided to move them to our repository instead. The maintenance via git is preferred by many developers and this way it is also accessible for open source users.
With this PR we are also restructuring and extending the convention list, please have a look at the commit history for more information.
=> Adding documentation about frontend conventions.

graylog2-web-interface/src/util/copyToClipboard.ts, graylog2-web-interface/src/views/bindings.tsx, graylog2-web-interface/src/views/components/messagelist/MessageActions.tsx, graylog2-web-interface/src/views/logic/fieldactions/CopyFieldToClipboard.ts, graylog2-web-interface/src/views/logic/valueactions/CopyValueToClipboard.ts
This PR is adding simple functionality to be able to:
- copy a field value
- copy a field name
- from message details, copy all fields
to the clipboard.
Fixes #4673
Fixes #12824
=> Adding simple actions to copy field name/value/message fields to clipboard.

graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivot/ESPivot.java, graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivot/ESPivotBucketSpecHandler.java, graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivot/buckets/ESDateRangeHandler.java, graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivot/buckets/ESTimeHandler.java, graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivot/buckets/ESValuesHandler.java, graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivots/ESPivotTest.java, graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivots/buckets/ESTimeHandlerTest.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/ESPivot.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/ESPivotBucketSpecHandler.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/buckets/ESDateRangeHandler.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/buckets/ESTimeHandler.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/buckets/ESValuesHandler.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivots/ESPivotTest.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivots/buckets/ESTimeHandlerTest.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/BucketSpecHandler.java
Unused parameter removed from the complex list of method params.
There was an unused parameter passed across different handlers in pivot-related classes, which can be safely removed, increasing readability of the code.
=> Unused parameter removed from the complex list of method params.

graylog2-web-interface/src/views/components/widgets/MessageList.test.tsx, graylog2-web-interface/src/views/components/widgets/MessageList.tsx, graylog2-web-interface/src/views/components/widgets/MessageTable.tsx, graylog2-web-interface/src/views/types.ts
With this PR we are refactoring the way we reset the scroll position in the `MessageList` widget. Resetting the scroll position is necessary, when the current page of the pagination changes. 
Previously we used the id of the first message in the list as a key for the list container component. This was not a good solution, instead we are now using a ref to reset the scroll position when necessary.
With this PR we are also migrating the `MessageList` component to a functional component, to be able to use hooks and we are migrating the related test from enzyme to react-testing-library.
=> Improve the way we reset scrolling in the `MessageList` widget.

graylog2-web-interface/src/views/types.ts
With this PR we are adding further attributes for the search filter type.
=> Extend search filter type

graylog2-web-interface/src/pages/IndexSetConfigurationPage.jsx
Before this change editing, `indexSet` from indexSet detail page was throwing an error. 
fix #12997
=>  fix issue when editing indexSet from details

graylog2-server/src/main/java/org/graylog2/rest/models/tools/responses/PageListResponse.java
Minor change: elements on a page are stored in List
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#3857
=> Minor change: elements on a page are stored in List

graylog2-web-interface/package.json, graylog2-web-interface/yarn.lock
This PR is making sure that the most recent version of `moment` (2.29.4) is used consistently. Prior to this PR, moment plugins were using an older version of `moment`, resulting in type errors when trying to update it.
Also, before this change an explicit dependency to `moment` existed, which is unnecessary due to `graylog-web-plugin` installing a more recent version.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#3859
=> Using consistent version of `moment`.

graylog2-web-interface/src/pages/IndexSetConfigurationPage.jsx
(cherry picked from commit a62e5ebb95e03dacdf572d261914b1b3204b4fdc)
=> fix issue when editing indexSet from details 4.3 backport(#13000) 

graylog2-server/src/main/java/org/graylog/plugins/map/geoip/GeoIpResolverEngine.java, graylog2-server/src/test/java/org/graylog/plugins/map/geoip/GeoIpResolverEngineTest.java
Backport of #13094 resolving #12909
See  #13094 and #12909
=> 4.3 Backport: Use legacy Geo IP fields if GIM schema enforcement is disabled (#13094)

graylog2-server/src/main/java/org/graylog/plugins/map/MapWidgetModule.java, graylog2-server/src/main/java/org/graylog/plugins/map/config/GeoIpResolverConfig.java, graylog2-server/src/main/java/org/graylog/plugins/map/geoip/GeoIpDbFileChangeMonitorService.java, graylog2-server/src/main/java/org/graylog/plugins/map/geoip/GeoIpDbFileChangedEvent.java, graylog2-server/src/main/java/org/graylog/plugins/map/geoip/processor/GeoIpProcessor.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/GeoIpResolverConfigValidator.java, graylog2-web-interface/src/components/maps/configurations/GeoIpResolverConfig.tsx
closes #13075 
This code change adds a service to monitor changes to the GeoIP database files such that the `GeoIpProcessor` can rebuild the `GeoIpResolverEngine` then such changes are detected.
Changing the GeoIP database files on the file system causes errors as `GeoIpProcessor` continues to run with the old files.
End-to-end testing.
=> Add service to monitor changes to GeoIP database files

graylog2-server/src/main/java/org/graylog/api/GenerateApiDefinition.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ExportJobsResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/FieldTypesResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/MessagesResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/search/KeywordSearchResource.java, graylog2-server/src/main/java/org/graylog2/shared/rest/documentation/generator/Generator.java, graylog2-web-interface/packages/jest-preset-graylog/jest-preset.js, graylog2-web-interface/src/generator/Api.ts, graylog2-web-interface/src/generator/__tests__/__snapshots__/parse.test.ts.snap, graylog2-web-interface/src/generator/__tests__/emit.test.ts, graylog2-web-interface/src/generator/__tests__/parse.test.ts, graylog2-web-interface/src/generator/__tests__/sample-api.json, graylog2-web-interface/src/generator/emit.ts, graylog2-web-interface/src/generator/parse.ts, graylog2-web-interface/src/routing/request.ts, graylog2-web-interface/src/views/components/searchbar/completions/FieldValueCompletion.test.ts, graylog2-web-interface/src/views/components/searchbar/completions/FieldValueCompletion.ts
This PR is addressing a couple of quirks discovered for the generated backend API types:
- Using pre-configured object mapper for JSON schema generation.
Properly snake-cases property names of DTOs.
- Fixing types for `Headers`, allowing string-arrays (e.g. for `Accept`)
- Using parameter names from `(Query|Header|Form)Param` annotations.
- Sanitize variable names generated from query parameters. 
E.g. `import-strategy` becomes `importStrategy`, while leaving query parameter name intact.
- Fixing parsing of `additional_properties`, e.g. types for List/Map values.
- Avoid serializing models which are not referenced (to prevent TS errors for declared, but unused types)
This PR also includes a good example for replacing `fetch`-usages with function stubs in …
=> Improve quality of backend API TypeScript types.

graylog2-web-interface/packages/graylog-web-plugin/package.json
Due to all usages of `javascript-natural-sort` having been replaced in #12944, we can now safely remove the package dependency as well.
=> Removing `javascript-natural-sort` dependency.

graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/SetField.java
Backport of #13132 
(cherry picked from commit cc3e8252865e4d2b8fc02ed20922f5d5bf2a4211)
=> Backport to 4.3: Add default param to set_field function

.github/workflows/reviewbot.yml
Prior to this PR, reviewbot was run when a PR was opened or pushed to.  This lead a corner case where the description of a PR was edited, a PR dependency was added/removed and reviewbot was not picking up when the run was retriggered. This is intentional, as retriggering a run is always performed with a snapshot of the initial run, therefore not containing updates to the PR body.
This PR is now fixing this by triggering a rerun of reviewbot when the PR body is edited.
=> Also run reviewbot when PR was edited.

graylog2-server/src/main/java/org/graylog2/Configuration.java, graylog2-server/src/main/java/org/graylog2/bootstrap/ServerBootstrap.java, misc/graylog.conf
* add flag ignore_migration_failures
* improve log message
(cherry picked from commit 32dbccf21328b4c6b465f002eae0b6fdb7433efd)
=> add flag ignore_migration_failures (#13137)

graylog2-web-interface/webpack.config.js
This PR is changing the webpack config to enforce the usage of the `babel-preset-graylog` to be loaded from core, so a consistent set of dependencies is used.
=> Enforcing usage of `babel-preset-graylog` from core.

graylog2-web-interface/src/components/search/SearchLink.ts, graylog2-web-interface/src/logic/assertUnreachable.ts, graylog2-web-interface/src/routing/useQuery.ts, graylog2-web-interface/src/views/hooks/BindSearchParamsFromQuery.ts, graylog2-web-interface/src/views/logic/NormalizeSearchURLQueryParams.ts, graylog2-web-interface/src/views/logic/TimeRange.test.ts, graylog2-web-interface/src/views/logic/TimeRange.ts
This PR is starting to consolidate time range related functionality in a separate `TimeRange` module. It is starting with functions to transform search query time ranges (time ranges passed as query parameters in URLs) to time range instances and vice versa. In future PRs, additional functions and types related to time ranges will be moved to this module.
=> Consolidating time range functions in module.

graylog2-web-interface/src/components/users/UserCreate/UserCreate.test.tsx, graylog2-web-interface/src/components/users/UserCreate/UserCreate.tsx, graylog2-web-interface/src/components/users/UserCreate/UsernameFormGroup.tsx
Before we were loading all the users to validate if a username exists now we are using the api call loadByUsername which directly checks if there is a user with that username.
#13066
=> Fix/#13066 Validate username without loading all the users

graylog2-web-interface/src/components/common/KeyValueTable.css, graylog2-web-interface/src/components/common/KeyValueTable.jsx, graylog2-web-interface/src/logic/authentication/okta/types.ts
Backport #12624 to 4.2. It is needed by the linked dependent PR.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#3926
=> Backport PR 12624 to 4.2

graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerFactory.java
Fix configuration property `transport_email_from_email` used in our container matrix tests for report delivery.
=> Fixed reporting from email address in matrix tests

pom.xml
Update the gRPC libs to the most recent version
=> Bump gRPC to version 1.48.1

graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategy.java, graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategyConfig.java, graylog2-server/src/main/java/org/graylog2/migrations/V20151210140600_ElasticsearchConfigMigration.java, graylog2-server/src/main/java/org/graylog2/migrations/V20190705071400_AddEventIndexSetsMigration.java, graylog2-server/src/test/java/org/graylog2/indexer/IndexSetValidatorTest.java, graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategyConfigTest.java, graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategyTest.java, graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.test.tsx, graylog2-web-interface/src/components/indices/Types.ts, graylog2-web-interface/src/components/indices/rotation/TimeBasedRotationStrategyConfiguration.jsx
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/3937
Backport of #13099
=> skip index rotation on empty index (#13099)

graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/DiskJournalPreflightCheck.java
If you use it, please be aware of:
https://sbg.technology/2018/07/10/kafka-nfs/
https://gqlxj1987.github.io/2019/05/26/kafka-on-k8s/
=> Keep allowing the journal on NFS

graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewDTO.java
Code cleanup, related to https://github.com/Graylog2/graylog-plugin-enterprise/pull/3985
=> tests code cleanup

graylog2-web-interface/src/components/common/HoverForHelp.tsx, graylog2-web-interface/src/stores/users/CurrentUserStore.ts, graylog2-web-interface/src/views/components/searchbar/PluggableSearchBarControls.tsx, graylog2-web-interface/src/views/components/searchbar/SearchFilterBanner.tsx
With this PR we are adding a more detailed description of the search filter feature for the explanation we display in the search bar.
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/3974
=> Improve explanation of search filter feature in search bar.

UPGRADING.md, graylog2-server/src/test/resources/org/graylog/testing/graylognode/Dockerfile
Just small additions:
- Upgrading document needed info about Java 17
- Dockerfiles for testing needed updates
=> Small additions to follow up the switch to Java 17

graylog2-web-interface/src/hooks/useScopePermissions.ts
Fix the bug https://github.com/Graylog2/graylog2-server/issues/13361 which is visible on `/system/lookuptables/create`.
=> fix: use scope permissions toUpperCase call on undefined

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/QueryValidationResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ValidationModeDTO.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ValidationRequestDTO.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ValidationTypeDTO.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/ValidationMode.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/ValidationRequest.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/validators/FieldValueTypeValidator.java
Preparation for the validation of search filters. More details in the https://github.com/Graylog2/graylog-plugin-enterprise/pull/4018 PR.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#4018
Added integration tests
=> Validation mode for search filters implemented

graylog2-web-interface/src/views/components/searchbar/queryvalidation/validateQuery.ts
To be able to handle query validation for search filters we are adding new query parameter
=> Update validation query type

graylog2-server/src/main/java/org/graylog2/inputs/misc/jsonpath/JsonPathInput.java
Add the word "value" to the input name, in order to clarify that the input can only target JSON primitive value nodes (numbers, strings etc.) and not object and array nodes. See discussion [in https://github.com/Graylog2/graylog2-server/issues/13344](https://github.com/Graylog2/graylog2-server/issues/13344#issuecomment-1245250795) for more info.
Starting the server and verifying that new and existing inputs are correctly renamed.
=> Adjust name of JSON path input

graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ElasticsearchInstanceES7.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/OpenSearch13Instance.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/OpenSearchContainer.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/OpenSearch2Metadata.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/testing/OpenSearchContainer.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/testing/OpenSearchInstance.java, graylog2-server/src/test/java/org/graylog/testing/elasticsearch/TestableSearchServerInstance.java
Just fixed naming of several classes so it's OpenSearch in correct camelcase everywhere. And other minor refactorings.
=> (O|o)pensearch -> (O|o)penSearch

graylog2-web-interface/src/pages/ShowMessagePage.test.tsx, graylog2-web-interface/src/pages/ShowMessagePage.tsx, graylog2-web-interface/src/views/hooks/useIsLocalNode.ts
Backport the PR https://github.com/Graylog2/graylog2-server/pull/12485 to fix the error message on the message page with message delivered by a Forwarder
Fix: https://github.com/Graylog2/graylog-plugin-cloud/issues/1039
=> Backport for 4.3: Do not show error on messages from Forwarder in show single message page #12485

graylog2-web-interface/src/views/components/widgets/MessageTable.tsx
Add sticky header to MessageTable
fix: #10936
=> Add sticky header to MessageTable

graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterFieldSet.jsx, graylog2-web-interface/src/components/maps/adapter/index.js
Backport PR https://github.com/Graylog2/graylog2-server/pull/12466
Changes descriptions for MaxMind data adapter to also include IPInfo
Sebastian asks for backporting the PR to 4.3
- [] New feature (non-breaking change which adds functionality)
=> [backport] change text of maxmind to include IPInfo

graylog2-web-interface/package.json, graylog2-web-interface/src/components/common/PageHeader.tsx, graylog2-web-interface/src/theme/GlobalThemeStyles.js, graylog2-web-interface/src/theme/fonts.ts, graylog2-web-interface/yarn.lock
This this PR we are installing the font DM Sans and define it for the navigation and headlines.
=> Implement new navigation and headline font.

graylog2-web-interface/src/components/bootstrap/NavDropdown.jsx, graylog2-web-interface/src/components/bootstrap/NavItem.tsx, graylog2-web-interface/src/components/bootstrap/Navbar.jsx, graylog2-web-interface/src/components/bootstrap/index.js, graylog2-web-interface/src/components/common/router.tsx, graylog2-web-interface/src/components/navigation/Navigation.test.tsx, graylog2-web-interface/src/components/navigation/Navigation.tsx, graylog2-web-interface/src/components/navigation/NavigationLink.test.jsx, graylog2-web-interface/src/components/navigation/SystemMenu.jsx
Before this PR we were not displaying an indicator in the navigation for the active page. The problem was that we were not providing the `active` class for the `NavItem` and `NavDropdown` component.
=> Fixing active state in main navigation.

graylog2-web-interface/src/views/components/widgets/MessageTable.tsx
I didn't find a particular reason to keep the fixed width for the source column, so I decided just to remove this styles
fix: [#13007](https://github.com/Graylog2/graylog2-server/issues/13007)
=> Remove fixed width for source column

UPGRADING.md
=> Backport archiving deletion job

graylog2-web-interface/src/components/cluster/GraylogClusterOverview.test.tsx, graylog2-web-interface/src/components/cluster/GraylogClusterOverview.tsx, graylog2-web-interface/src/stores/cluster/ClusterTrafficStore.test.ts, graylog2-web-interface/src/stores/cluster/ClusterTrafficStore.ts
Introduce days selection to select different time frames for the outgoing traffic graph.
Checkout https://github.com/Graylog2/graylog2-server/issues/12502
=> feat: add days selection for outgoing traffic utilisation

graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/DataTableVisualizationConfigDTO.java
Configuration for data table visualization in aggregations
Required to support front-end changes.
=> Configuration for data table visualization in aggregations

graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/QueryValidationServiceImpl.java
=> Backport: Fix regex exception in query validation 

graylog2-web-interface/src/components/authentication/BackendsOverview/BackendsOverview.tsx, graylog2-web-interface/src/components/roles/RolesOverview/RolesOverview.tsx, graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.tsx, graylog2-web-interface/src/views/components/views/DashboardList.tsx, graylog2-web-interface/src/views/pages/DashboardsPage.tsx
As described here https://github.com/Graylog2/graylog2-server/issues/13618 some entity lists don't refresh on delete so this PR fixes that.
https://github.com/Graylog2/graylog2-server/issues/13618
=> Fix #13618: Entity lists do not refresh after deleting item

graylog2-web-interface/src/components/enterprise/ProductLink.tsx
Remove a wrong prop on the ProductLink component to fix the console error on the License page.
=> Fix license page console error.

graylog2-server/src/main/java/org/graylog2/rest/resources/system/lookup/LookupTableResource.java
Use inline validation instead of method level validation for LUTs Caches and Data Adapters for error message consistency.
During validation, some fields were being checked at the method level before the resource function call. In this case if validation failed, validation would not be performed on the other fields and the format of the returned errors was not consistent.
Fixes: https://github.com/Graylog2/graylog2-server/issues/13623
Fixes: https://github.com/Graylog2/graylog2-server/issues/13623
Locally in development environment by sending valid and invalid payloads through the LUTs, Caches, and Data Adapters `validate` endpoints.
=> Use inline validation for LUTs, Caches, and Data Adapters for error message consistency

graylog2-web-interface/src/views/components/datatable/Headers.test.tsx, graylog2-web-interface/src/views/components/datatable/Headers.tsx
Prior to this PR, an `unknown` field type was provided for column pivot header values. This lead to e.g. timestamps not being formatted properly.
This PR is now changing this. In addition, it turns functions in the `Headers` component into functional components.
=> Provide correct type for column pivot header values.

graylog2-server/src/main/java/org/graylog2/lookup/caches/CaffeineLookupCache.java, graylog2-server/src/main/java/org/graylog2/plugin/lookup/LookupResult.java
Handle error message from lookup for Graylog2/graylog-plugin-cloud#1046
=> Pass through error message from lookup

graylog2-server/src/main/java/org/graylog2/rest/resources/system/TrafficResource.java, graylog2-server/src/main/java/org/graylog2/system/traffic/TrafficCounterService.java, graylog2-server/src/test/java/org/graylog2/system/traffic/TrafficCounterServiceTest.java
Backport https://github.com/Graylog2/graylog2-server/pull/13633 to the `4.3` branch.
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/4171
=> Add include today count traffic option (4.3)

UPGRADING.md
backport of Graylog2/graylog-plugin-enterprise#4113
=> backport archive retention configs

graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/MessagesAdapterOS2.java
Same logic and same error codes used as in the ES7 implementation.
Existing integration tests
=> Fix Opensearch2 batch splitting in case of TOO_MANY_REQUESTS err

UPGRADING.md, misc/graylog.conf
Upgrade notes updated, new property added to sample config file
=> Upgrade notes updated, new property added to sample config file

UPGRADING.md, graylog2-server/src/main/java/org/graylog2/Configuration.java
Moving archive configuration to archive plugin configuration. 
Graylog2/graylog-plugin-enterprise#4218
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#4218
Enterprise configuration shouldn't be available  over here.
Locally with max set, default set and later on overwriting it via ui
=> move archive configs to plugin configuration

graylog2-server/src/main/java/org/graylog2/bindings/PeriodicalBindings.java, graylog2-server/src/main/java/org/graylog2/migrations/MigrationsModule.java, graylog2-server/src/main/java/org/graylog2/migrations/V19700101000000_GenerateClusterId.java
Co-authored-by: Maxwell Anipah <maxwell.anipah@graylog.com>
Co-authored-by: Maxwell <98284293+kodjo-anipah@users.noreply.github.com>
Co-authored-by: Matthias Oesterheld <33032967+moesterheld@users.noreply.github.com>
(cherry picked from commit 81056fd37ecaf01ee51a98cbe3447b9ed155ae59)
Backport for https://github.com/Graylog2/graylog2-server/pull/13629
=> generate cluster id in migration instead of periodical (#13629)

.github/workflows/fix-linter-hints.yml
This PR is adding a step to our automated linter hint fixing job which parses the generated report, extracts the count of errors and warnings and ingests them to our internal instance, so we can track progression of code quality over time.
=> Track problem count from linter job.

graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterJournalResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterLoadBalancerStatusResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterLoggersResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterNodeMetricsResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterSystemJobResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterSystemPluginResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterSystemProcessingResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterSystemResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterSystemShutdownResource.java, graylog2-server/src/main/java/org/graylog2/shared/rest/resources/ProxiedResource.java, graylog2-server/src/test/java/org/graylog2/rest/resources/cluster/ClusterLookupTableResourceTest.java
=> Backport: fail fast if proxied requests would miss auth info

graylog2-web-interface/src/views/components/messagelist/MessageFields.tsx
This change is increasing the contrast for the message details by changing the font color from `gray40` to `global.textDefault`.
=> Increasing contrast for field names/values in message details.

graylog2-web-interface/src/components/streams/Stream.jsx
disable "Pause Stream" button for default stream
fixes #13575
=> disable "Pause Stream" button for default stream

UPGRADING.md, graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.tsx
And mention restrictions in the upgrade notes.
/nocl
=> Improve help text for sidecar tags

graylog2-web-interface/src/components/rules/RuleContext.tsx, graylog2-web-interface/src/components/rules/RuleForm.jsx
=> Fix Pipeline rule description not saved

changelog/unreleased/pr-13873.toml, graylog2-server/src/main/java/org/graylog2/inputs/transports/KafkaTransport.java, graylog2-server/src/main/java/org/graylog2/plugin/configuration/fields/TextField.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/inputs/AbstractInputsResource.java, graylog2-web-interface/src/components/configurationforms/ConfigurationWell.jsx, graylog2-web-interface/src/components/configurationforms/types.ts
=> Backport: Add text field attribute to hide sensitive input config

graylog2-web-interface/src/components/extractors/ExtractorSortModal.jsx
=> Fix Extractor order can't be changed

graylog2-server/src/main/java/org/graylog2/rest/resources/HelloWorldResource.java
=> Prefer  endpoint when */* accept header is used

graylog2-server/src/test/java/org/graylog/security/authservice/ldap/UnboundLDAPConnectorTestTLSIT.java, graylog2-server/src/test/java/org/graylog/testing/ldap/OpenLDAPContainer.java, graylog2-server/src/test/resources/org/graylog/testing/ldap/ldif/nested-groups.ldif
* Specify custom ldif on container creation
* Add groupOfUniqueNames to test LDIF
(cherry picked from commit 1754f3dcfde1366c89c198c9956a263f3019751f)
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/4326
/nocl
=> Backport: LDAP testcontainer: specify custom LDIF on container creation

graylog2-server/src/main/java/org/graylog2/shared/utilities/StringUtils.java, graylog2-server/src/test/java/org/graylog2/shared/utilities/StringUtilsTest.java
A test in the enterprise plugin failed because the used OSHI.format function is prone to locale-problems. Fixing the test would mean setting/resetting the locale which I find rather unfortunate. As we have replaced the `String.format()`because of the same problem everywhere in our code, I thought a replacement is a better idea. 
/nocl
=> Added a function that prints a human readable byte count

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/MetricToSeriesSpecMapper.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/MetricsToSeriesSpecMapper.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/MetricsToSeriesSpecMapperTest.java
Generics complexity removed.
/nocl
Extremely recursive generics are way to complex.
=> Generics complexity removed

graylog2-web-interface/src/components/streams/StreamActions.tsx
This PR is fixing a TS error in the `master` branch which occurs because I merged two PRs at the same time.
- https://github.com/Graylog2/graylog2-server/pull/13887
- https://github.com/Graylog2/graylog2-server/pull/14021
The error would have occurred in https://github.com/Graylog2/graylog2-server/pull/13887 if I had rebases after merging https://github.com/Graylog2/graylog2-server/pull/14021
/nocl
=> Fixing TS error in `StreamsActions` component.

graylog-plugin-archetype/src/main/resources/archetype-resources/webpack.config.js
At some point we change the interface of the `PluginWebpackConfig` function. With this PR we are updating its usage in the `graylog-plugin-archetype`
/nocl
=> Update usage of `PluginWebpackConfig` in webpack config of `graylog-plugin-archetype`.

graylog2-web-interface/package.json, graylog2-web-interface/packages/graylog-web-plugin/src/PluginManifest.js, graylog2-web-interface/webpack.config.js
This PR is implementing `esbuild-loader` so we can make use of the improved performance of `esbuild` during bundling.
```
yarn build  192.80s user 3.71s system 296% cpu 1:06.38 total
```
```
yarn build  38.77s user 1.81s system 156% cpu 25.961 total
```
The `target` specification is what `browserslist` generates for the `defaults` setting right now as a start. There is no direct integration for it in `esbuild-loader` yet, but writing one is a simple task for a follow-up PR.
Another follow-up could be removing `babel-loader` etc. if we decide that we do not need it anymore.
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-collector/pull/214
/nocl
=> Use `esbuild` to transpile frontend assets.

graylog2-web-interface/src/components/authentication/BackendsOverview/BackendsOverview.tsx, graylog2-web-interface/src/logic/rest/FetchProvider.test.ts, graylog2-web-interface/src/logic/rest/FetchProvider.ts, graylog2-web-interface/src/routing/request.ts, graylog2-web-interface/src/stores/authentication/AuthenticationStore.ts, graylog2-web-interface/src/stores/permissions/EntityShareStore.ts, graylog2-web-interface/src/stores/pipelines/PipelinesStore.ts, graylog2-web-interface/src/stores/rules/RulesStore.ts, graylog2-web-interface/src/stores/streams/StreamsStore.ts, graylog2-web-interface/src/stores/users/PreferencesStore.ts, graylog2-web-interface/src/stores/users/UsersStore.ts, graylog2-web-interface/src/views/components/searchbar/queryvalidation/types.ts, graylog2-web-interface/src/views/components/searchbar/queryvalidation/validateQuery.test.ts, graylog2-web-interface/src/views/components/searchbar/queryvalidation/validateQuery.ts, graylog2-web-interface/src/views/components/widgets/WidgetActionsMenu.test.tsx, graylog2-web-interface/src/views/pages/DashboardsPage.test.tsx, graylog2-web-interface/src/views/stores/DashboardsStore.ts, graylog2-web-interface/src/views/stores/SearchMetadataStore.ts
This PR is typing the `fetch`/`FetchProvider` function/class. We can now provide the type of the response as a generic parameter like this:
```
const response = await fetch<ResponseType>(....);
```
It also fixes the resulting fallout from properly propagating types through promise chains.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#4317,Graylog2/graylog-plugin-enterprise-integrations#930
/nocl
=> Typing `fetch`/`FetchProvider`.

full-backend-tests/src/test/java/org/graylog/plugins/views/aggregations/SearchAggregationsIT.java, full-backend-tests/src/test/java/org/graylog/plugins/views/aggregations/SearchWithAggregationsSupportingMissingBucketsIT.java, graylog2-server/src/test/java/org/graylog/testing/containermatrix/SearchServer.java
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#4384
/nocl
=> Set Opensearch 2.4 as the default version for integration tests

full-backend-tests/src/test/java/org/graylog/plugins/views/ScriptingApiResourceIT.java
This has already been addressed in the main branch but maybe we don't want to backport the whole PR that included this change. But to not have a flaky test that creates problems during release/backports for bugs etc. I created this small PR.
/nocl
=> Improved Scripting API Test stability

changelog/unreleased/pr-14063.toml, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java
=> Fix indexer connectivity check (#14063)

changelog/unreleased/pr-14063.toml, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/ClusterAdapterOS2.java
=> Backport: Fix indexer connectivity check (#14063)

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/ScriptingApiResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/AggregationSpecToPivotMapper.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/AggregationTabularResponseCreator.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/MessagesSpecToMessageListMapper.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/MessagesTabularResponseCreator.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/QueryParamsToFullRequestSpecificationMapper.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/SearchRequestSpecToSearchMapper.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/TabularResponseCreator.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/request/AggregationRequestSpec.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/request/MessagesRequestSpec.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/request/SearchRequestSpec.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/response/ResponseEntryDataType.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/response/ResponseEntryType.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/response/ResponseSchemaEntry.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/QueryParamsToFullRequestSpecificationMapperTest.java, graylog2-web-interface/src/routing/request.ts
Scripting API can now not only provide aggregations, but also list of messages.
/nocl
It is relatively simple to add this feature on top of what has been prepared so far.
=> Scripting api/quering data

graylog2-web-interface/src/components/login/LoginChrome.tsx
Prior to this PR, public notifications shown on login were displayed too narrow. This PR is fixing this.
/nocl
=> Fixing width of login notifications.

graylog2-server/src/main/java/org/graylog2/rest/resources/entities/EntityAttribute.java, graylog2-server/src/main/java/org/graylog2/rest/resources/entities/EntityDefaults.java, graylog2-server/src/main/java/org/graylog2/rest/resources/entities/EntitySettings.java, graylog2-server/src/main/java/org/graylog2/rest/resources/entities/FilterOption.java, graylog2-server/src/main/java/org/graylog2/rest/resources/entities/Sorting.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/responses/StreamPageListResponse.java
This PR is adding entity metadata to the streams endpoint. It is adding new fields to the response:
- `attributes`: a list of attributes of the entity this endpoint describes and if they are sortable and/or filterable
- `settings`: the default settings for this entity, including:
- `attributes`: which attributes should be displayed by default
- `sort`: which sort is used by default when none is specified
This allows dynamic introspection and discovery of capabilities as well as constructing an initial state by consumers.
/nocl
=> Adding entity metadata for streams.

full-backend-tests/src/test/java/org/graylog/plugins/views/QueryValidationResourceIT.java, full-backend-tests/src/test/java/org/graylog/plugins/views/ScriptingApiResourceIT.java, full-backend-tests/src/test/java/org/graylog/testing/utils/SearchUtils.java
The heading says it all :-)
/nocl
=> integration test for scripting api messages

graylog2-web-interface/src/components/common/EntityDataTable/ColumnsVisibilitySelect.tsx, graylog2-web-interface/src/components/common/EntityDataTable/EntityDataTable.test.tsx, graylog2-web-interface/src/components/common/EntityDataTable/EntityDataTable.tsx, graylog2-web-interface/src/components/common/EntityDataTable/types.ts, graylog2-web-interface/src/components/streams/StreamsOverview/StreamsOverview.tsx
Please note, this PR is based on https://github.com/Graylog2/graylog2-server/pull/14066 which needs to be merged first.
With this PR we are implementing the option to select which columns you want to display for the streams overview.
Fixes https://github.com/Graylog2/graylog2-server/issues/13853
/nocl
=> Allow selecting which columns should be displayed for streams overview.

changelog/unreleased/issue-12996.toml
=> Changelog entry for #12996

graylog2-web-interface/package.json, graylog2-web-interface/yarn.lock
This PR is updating the following packages together (avoiding a type error that occurs when updating separately):
- `@fortawesome/fontawesome-svg-core`
- `@fortawesome/free-brands-svg-icons`
- `@fortawesome/free-regular-svg-icons`
- `@fortawesome/free-solid-svg-icons`
/nocl
=> Updating font awesome icons to `6.2.1`.

full-backend-tests/src/test/java/org/graylog/plugins/views/ScriptingApiResourceIT.java
This change modifies the check of the results so that the order (which is not part of the test) in the result set is not important.
/nocl
/fixes #14144
=> Fix ScriptingAPIResourceIT test failure

changelog/unreleased/issue-13874.toml, graylog2-web-interface/src/components/sidecars/common/CloneMenuItem.tsx
=> Backport PR: Fix Clone Action of Configuration is out of place (#13899)

graylog2-web-interface/src/pages/StreamEditPage.tsx
This is a tiny change removing the guillemets on the "Manage Stream Rules" page, replacing them with regular quotation marks.
/nocl
=> Fixing up quotation on stream rule edit page.

changelog/unreleased/issue-14142.toml, graylog-project-parent/pom.xml, graylog2-server/pom.xml, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/FieldTypeValidationImpl.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/validation/FieldTypeValidationTest.java, pom.xml
Fixes https://github.com/Graylog2/graylog2-server/issues/14142
CIDR format of the IP requires some special handling in the query validation 
Added unit tests
=> Query validation can handle CIDR format of IP

changelog/unreleased/issue-14142.toml, graylog-project-parent/pom.xml, graylog2-server/pom.xml, graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/FieldTypeValidationImpl.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/validation/FieldTypeValidationTest.java, pom.xml
**Note:** This is a backport of #14204 to `5.0`.
CIDR format of the IP requires some special handling in the query validation
Fixes #14142
=> Query validation can handle CIDR format of IP (`5.0`)

graylog2-web-interface/package.json
This PR is removing `babel-loader` as it has been replaced with `esbuild-loader`.
Babel itself is still in use for tests and scripts.
/nocl
=> Removing `babel-loader`.

pom.xml
Bumping the client version to 4.8.1 because of some missing features in 4.7
/nocl
=> Bumping the Mongo client to 4.8.1

graylog2-web-interface/src/components/lookup-tables/LookupTableView.tsx, graylog2-web-interface/src/components/navigation/UserMenu.tsx
This PR is making a couple of elements easier to find in tests:
- The user menu gets a proper label, making it easy to find even if
the full name of the user is not known
- The inputs for the keys to purge and to lookup on the lookup tables
page are made distinct
/nocl
=> Improve finding elements from Tests

full-backend-tests/src/test/java/org/graylog/plugins/views/ScriptingApiResourceIT.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/errors/ResultWindowLimitError.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/errors/SearchTypeErrorParser.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/ScriptingApiResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/AggregationTabularResponseCreator.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/MessagesTabularResponseCreator.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/QueryFailedException.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/TabularResponseCreator.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/request/MessagesRequestSpec.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/errors/SearchTypeErrorParserTest.java
Checking if the sum of size and from does not exceed ES/OS limits.
/nocl
=> Checking if the sum of size and from does not exceed ES/OS limits

graylog2-web-interface/src/components/common/PaginatedList.tsx
_Note: This is a backport of #14141 for 5.0_
React to changes to query params.
/nocl
Adds a hook to react when query params changes.
Manual
=> fix(14108): React to changes on query params. (Backport of #14141 for 5.0)

changelog/unreleased/issue-6486.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/dates/DateConversion.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/dateConversion.txt
=> Evaluate timezone argument in to_date() pipeline function

full-backend-tests/src/test/java/org/graylog/plugins/views/ScriptingApiResourceIT.java, full-backend-tests/src/test/java/org/graylog/plugins/views/ViewsResourceIT.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/GraylogApis.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/Users.java
Adding some convenience methods to reduce boilerplate code.
/nocl
=> Integration Tests API enhancements

AUTHORS
/nocl
Make `AUTHORS` file say the truth.
Was looking for something else and noticed this file. Fixed it!
* Not at all.
=> Fix AUTHORS file

manifest.mf
/nocl
Removing bizarre file in root folder I stumbled over when looking for something else.
It solves the problem that I created this file 13 years ago and it doesn't do anything. Just cleaning up behind myself! 🕊️ 
* Not at all
=> Delete manifest file

changelog/unreleased/pr-14283.toml, graylog2-web-interface/src/components/authentication/BackendsOverview/BackendsFilter.tsx, graylog2-web-interface/src/components/authentication/BackendsOverview/BackendsOverview.tsx, graylog2-web-interface/src/components/common/SearchForm.jsx
Relates to https://github.com/Graylog2/graylog2-server/issues/13023
=> Fix non-stop loading indicator issue in authentication backends

changelog/unreleased/pr-14354.toml, graylog2-server/src/main/java/org/graylog/plugins/sidecar/services/ConfigurationService.java, graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java, graylog2-server/src/main/java/org/graylog2/bindings/providers/SecureFreemarkerConfigProvider.java, graylog2-server/src/test/java/org/graylog/plugins/sidecar/collectors/ConfigurationServiceTest.java, graylog2-server/src/test/java/org/graylog2/contentpacks/facades/SidecarCollectorConfigurationFacadeTest.java, pom.xml
- https://freemarker.apache.org/docs/versions_2_3_30.html
- https://freemarker.apache.org/docs/versions_2_3_31.html
(cherry picked from commit 69bde48cfea6348283aacced6feda38f883353ac)
=> Update to freemarker 2.3.31 and use a more secure default configuration

graylog2-web-interface/src/components/notifications/Notification.test.tsx, graylog2-web-interface/src/stores/notifications/NotificationsStore.ts
Add the notifications count to the Notification store state. 
/nocl
fix #14360
=> Fix notification count badge

graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/TestSearchUser.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/TestableFixedViewResolver.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewsResourceTest.java
This PR tries to make the ViewResourceTest more readable, easier to understand, modify and extend
/nocl
=> Refactored ViewResourceTest, removed most of the mocks, immutability

graylog2-server/src/main/java/org/graylog/events/search/MoreSearch.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/IndexRangeContainsOneOfStreams.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/IndexLookup.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/IndexRangeContainsOneOfStreamsTest.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/IndexLookupTest.java
Index lookup refactoring:
1. Moving tests to JUnit5.
2. Removing unnecessary stubbing.
3. Removing complex code structures that were prepared just for tests.
4. Minor optimizations (new collections created when needed, not upfront, etc. )
5. More explicit variable naming here and there.
/nocl
By re-running all unit tests in graylog-server.
=> Index lookup refactoring

graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/SearchResourceTest.java
Test code cleanup, removed dead code, refactored to cleaner usage of mocks.
/nocl
=> SearchResourceTest cleanup

graylog2-server/src/main/java/org/graylog2/lookup/db/DBCacheService.java, graylog2-server/src/main/java/org/graylog2/lookup/db/DBDataAdapterService.java, graylog2-server/src/main/java/org/graylog2/lookup/db/DBLookupTableService.java
Co-authored-by: Ryan <103449971+ryan-carroll-graylog@users.noreply.github.com>
Backport of #14364 
/nocl
=> 5.0 Backport: Add postBulkUpdate to cache, data adapter, and lookup table DB services

graylog2-server/src/main/java/org/graylog2/rest/resources/entities/FilterOption.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java
Fixes minor issues with Entity List:
1. Proper field id for status ("disabled").
2. Filter option contains MongoDB value, so that FE can create proper filter.
/nocl
=> Proper field id for status. Filter option contains MongoDB value.

changelog/unreleased/issue-8506.toml, graylog2-web-interface/src/components/common/SearchForm.jsx, graylog2-web-interface/src/views/components/AdaptableQueryTabs.test.tsx, graylog2-web-interface/src/views/components/AdaptableQueryTabs.tsx, graylog2-web-interface/src/views/components/AdaptableQueryTabsConfiguration.tsx, graylog2-web-interface/src/views/components/common/ActionDropdown.tsx, graylog2-web-interface/src/views/components/queries/QueryActionDropdown.tsx, graylog2-web-interface/src/views/components/queries/QueryTitle.test.tsx, graylog2-web-interface/src/views/components/queries/QueryTitle.tsx, graylog2-web-interface/src/views/components/widgets/CopyToDashboardForm.test.tsx, graylog2-web-interface/src/views/components/widgets/CopyToDashboardForm.tsx, graylog2-web-interface/src/views/components/widgets/WidgetActionsMenu.test.tsx, graylog2-web-interface/src/views/components/widgets/WidgetActionsMenu.tsx, graylog2-web-interface/src/views/logic/views/Actions.ts, graylog2-web-interface/src/views/logic/views/CopyPageToDashboard.Dashboard-Search.fixture.json, graylog2-web-interface/src/views/logic/views/CopyPageToDashboard.Dashboard-View.fixture.json, graylog2-web-interface/src/views/logic/views/CopyPageToDashboard.test.ts, graylog2-web-interface/src/views/logic/views/CopyPageToDashboard.ts, graylog2-web-interface/src/views/logic/views/CopyWidgetToDashboard.ts, graylog2-web-interface/src/views/logic/views/__snapshots__/CopyPageToDashboard.test.ts.snap, graylog2-web-interface/src/views/types.ts
With this PR we are implementing the option to copy a dashboard page to another dashboard. The UI looks and works similar to the "Copy widget to dashboard" functionality on a search page.
When a user copies a page to a dashboard, we are generating new ids for the query and widgets and redirect to the new dashboard. When there are parameters configured for the source dashboard, we copy them as well.
Fixes #8506
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/4522
=> Implement option to copy dashboard page to a different dashboard.

changelog/unreleased/pr-14437.toml, graylog2-server/src/main/java/org/graylog/metrics/prometheus/PrometheusExporterHTTPServer.java
JVM metrics are exposed to Prometheus for better monitoring.
closes Graylog2/graylog-plugin-enterprise#4393
=> expose jvm metrics to prometheus

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/DashboardsResource.java, graylog2-web-interface/src/views/components/dashboard/hooks/useDashboards.ts
Dashboard supported via Entity List.
Fixes #14289.
/nocl
=> Dashboard supported via Entity List

graylog2-server/src/main/java/org/graylog2/indexer/retention/strategies/AbstractIndexRetentionStrategy.java, graylog2-server/src/main/java/org/graylog2/indexer/retention/strategies/ClosingRetentionStrategy.java, graylog2-server/src/main/java/org/graylog2/indexer/retention/strategies/DeletionRetentionStrategy.java, graylog2-server/src/main/java/org/graylog2/indexer/retention/strategies/NoopRetentionStrategy.java, graylog2-server/src/test/java/org/graylog2/indexer/retention/strategies/AbstractIndexRetentionStrategyTest.java
Extend abstract retention class to handle time-based config.
/nocl
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#4572
=> Timebased retention

graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/SmartRotationStrategy.java, graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/SmartRotationStrategyTest.java, misc/graylog.conf
=> Implement smart index rotation strategy

changelog/unreleased/pr-14409.toml, graylog2-server/src/main/java/org/graylog2/streams/StreamRouterEngine.java, graylog2-server/src/main/resources/prometheus-exporter.yml, graylog2-server/src/test/java/org/graylog2/streams/StreamRouterEngineTest.java
=> Reduce logging and add metric for stream warning (5.0)

graylog2-web-interface/src/views/logic/NormalizeSearchURLQueryParams.ts, graylog2-web-interface/src/views/logic/queries/QueryGenerator.ts, graylog2-web-interface/src/views/logic/views/UseCreateSavedSearch.ts, graylog2-web-interface/src/views/logic/views/ViewGenerator.ts, graylog2-web-interface/src/views/logic/views/ViewStateGenerator.ts, graylog2-web-interface/src/views/pages/NewSearchPage.test.tsx, graylog2-web-interface/src/views/pages/NewSearchPage.tsx
This PR is fixing an issue introduced in #14368. It takes the streams specified in URL parameters into account when creating the initial view, instead of relying on the streams being updated later when processing hooks.
Fixes #14493.
/nocl
=> Including stream(s) when extracting initial parameters from URL.

graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexSetValidator.java, graylog2-server/src/test/java/org/graylog2/indexer/IndexSetValidatorTest.java
=> Add rotation/retention validations

graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardsOverview.test.tsx, graylog2-web-interface/src/views/components/dashboard/DashboardsOverview/DashboardsOverview.tsx, graylog2-web-interface/src/views/components/dashboard/hooks/useDashboards.ts, graylog2-web-interface/src/views/components/widgets/CopyToDashboardForm.test.tsx, graylog2-web-interface/src/views/components/widgets/WidgetActionsMenu.test.tsx
This PR is implementing the required FE changes for https://github.com/Graylog2/graylog2-server/pull/14448
We are now displaying columns in the dashboards overview based on API response.
Fixes: https://github.com/Graylog2/graylog2-server/issues/14289
/nocl
=> Display columns in dashboards overview based on API response.

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/DashboardsResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SavedSearchesResource.java
Missing Metadata attribute added to the responses, so it can be shown correctly in the FE.
/nocl
=> Adding the "Favorite" Attribute to Metadata when getting Dashboards/Searches

graylog2-server/src/main/java/org/graylog2/indexer/IndexSetValidator.java, graylog2-server/src/main/java/org/graylog2/indexer/retention/strategies/AbstractIndexRetentionStrategy.java, graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingStrategy.java, graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingStrategyConfig.java, graylog2-server/src/test/java/org/graylog2/indexer/IndexSetValidatorTest.java, graylog2-server/src/test/java/org/graylog2/indexer/retention/strategies/AbstractIndexRetentionStrategyTest.java, graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingRotationAndRetentionTest.java, graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingStrategyTest.java
`index_lifetime_soft` -> `index_lifetime_min`
`index_lifetime_hard` -> `index_lifetime_max`
This explains better on how these settings are meant to be used.
/nocl
=> Rename index_lifetime hard/soft to min/max

changelog/unreleased/pr-14567.toml, graylog2-web-interface/src/views/components/searchbar/saved-search/BulkActions.test.tsx, graylog2-web-interface/src/views/components/searchbar/saved-search/BulkActions.tsx, graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchesList.tsx
This PR is implementing a bulk delete action for dashboards. It uses the API endpoint which has been introduced with https://github.com/Graylog2/graylog2-server/pull/14476.
Fixes https://github.com/Graylog2/graylog2-server/issues/14189 https://github.com/Graylog2/graylog2-server/issues/8330
=> FE: Implement saved searches bulk delete.

graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java, graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/EntityExcerpt.java
Search Filters are the first type of entities that are allowed to have no title. So the resolver has to be fixed to allow this.
/nocl
=> Allowing Entities to have no Title in Excerpts

graylog2-server/src/main/java/org/graylog2/rest/resources/entities/preferences/EntityListPreferencesResource.java
Entity List preferences do not need audit log. 
It has been confirmed with Kay.
TODO removed.
/nocl
=> Entity List preferences do not need audit log. TODO removed.

graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewDTO.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewSummaryService.java, graylog2-server/src/main/java/org/graylog2/database/PaginatedDbService.java
Title as secondary sort for Dashboards and Saved Searches.
/nocl
Required by FE.
=> Title as secondary sort for Dashboards and Saved Searches

graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingStrategy.java, graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedSizeOptimizingStrategyTest.java
=> Handle "indefinite" leeway with NoopRetention

graylog2-server/src/main/java/org/graylog/events/rest/EventsResource.java
Simpler endpoint for FE to get single event by ID.
/nocl
Requested by Maksym for Basic Alerting Integration Task.
=> Simpler endpoint for FE to get single event by ID

graylog2-web-interface/src/components/bootstrap/MenuItem.tsx, graylog2-web-interface/src/components/common/DropdownMenu.tsx, graylog2-web-interface/src/components/streams/StreamsOverview/StreamActions.tsx
With this PR we are disabling the delete action for the default stream again. The underlying bug has not been release yet.
We are also improving the styling.
Before:
After:
/nocl
=> Disable delete action for default stream

changelog/unreleased/pr-14631.toml, graylog2-server/src/main/java/org/graylog/scheduler/schedule/CronJobSchedule.java
Backport of fix for issue Graylog2/graylog-plugin-enterprise#4311.
=> Handle short timezone IDs 

graylog2-web-interface/src/views/components/DashboardActionsMenu.tsx, graylog2-web-interface/src/views/components/WidgetGrid.tsx, graylog2-web-interface/src/views/components/aggregationwizard/grouping/GroupingConfiguration.tsx, graylog2-web-interface/src/views/components/aggregationwizard/grouping/configuration/FieldComponent.tsx, graylog2-web-interface/src/views/components/aggregationwizard/metric/MetricConfiguration.tsx, graylog2-web-interface/src/views/components/common/EditableTitle.tsx, graylog2-web-interface/src/views/components/datatable/DataTableEntry.tsx, graylog2-web-interface/src/views/components/queries/QueryTitle.tsx, graylog2-web-interface/src/views/components/searchbar/RefreshControls.tsx, graylog2-web-interface/src/views/components/views/ViewHeader.tsx, graylog2-web-interface/src/views/components/widgets/WidgetHeader.tsx
This PR is adding some useful identifiers to elements commonly used in e2e tests.
/nocl
=> Giving elements better titles to find them in tests.

graylog2-web-interface/docs/package.json, graylog2-web-interface/docs/yarn.lock
This PR is reverting the `react-styleguidist` update from #14665. It requires React 18 compatibility for operation, which we cannot provide at this point.
/nocl
=> Revert styleguidist update.

graylog2-web-interface/src/views/components/messagelist/MessageField.tsx, graylog2-web-interface/src/views/components/messagelist/MessageTableEntry.tsx, graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightForm.tsx
This is a small PR adding test ids to specific elements, helping us in E2E tests to find them in a maintainable way.
/nocl
=> Adding test ids for elements in message tables/highlighting.

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/DashboardsResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SavedSearchesResource.java, graylog2-server/src/main/java/org/graylog2/database/filtering/DbFilterParser.java, graylog2-server/src/main/java/org/graylog2/rest/resources/entities/EntityAttribute.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java, graylog2-server/src/main/java/org/graylog2/search/DbFieldMappingCreator.java, graylog2-server/src/main/java/org/graylog2/search/SearchQueryField.java, graylog2-server/src/main/java/org/graylog2/search/SearchQueryParser.java, graylog2-server/src/main/java/org/graylog2/utilities/date/MultiFormatDateParser.java, graylog2-server/src/test/java/org/graylog2/database/filtering/DbFilterParserTest.java, graylog2-server/src/test/java/org/graylog2/search/DbFieldMappingCreatorTest.java, graylog2-server/src/test/java/org/graylog2/search/SearchQueryParserTest.java, graylog2-server/src/test/java/org/graylog2/utilities/date/MultiFormatDateParserTest.java, graylog2-web-interface/src/components/common/EntityDataTable/EntityDataTable.tsx, graylog2-web-interface/src/components/common/EntityDataTable/types.ts, graylog2-web-interface/src/stores/PaginationTypes.ts
PR implementing the following ideas of filtering and searching improvements:
1. SEARCH_FIELD_MAPPING concept is gone in resources using entity lists, it can be deducted from improved "attributes" field.
2. Boolean type added, so that it can be supported in searching and filtering.
3. Parsing of string value representation moved to Type enum.
4. Attribute's title can be used to filter/search without any additional tricks (i.e. if attribute "title" has title="Name", you can search using the notation of "name:stream_title").
5. Type of attribute is no longer a String, existing Type enum is used.
/nocl
Additional unit tests have been added.
=> Filtering and searching improvements

graylog2-web-interface/packages/eslint-config-graylog/index.js, graylog2-web-interface/packages/eslint-config-graylog/package.json
This PR is adding the ESLint plugin for `react-query`. So far it contains only [two rules](https://tanstack.com/query/v4/docs/react/eslint/eslint-plugin-query), but especially the exhaustive deps rule is very useful.
/nocl
=> Adding ESLint plugin for `react-query`.

graylog2-web-interface/src/logic/permissions/GRN.test.ts, graylog2-web-interface/src/logic/permissions/GRN.ts
There was a typo in tenant in the GRN classes for the FE. This PR fixes the typo.
/nocl
=> Fixed typo in tenant

graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/DashboardsResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SavedSearchesResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewSummaryService.java, graylog2-server/src/main/java/org/graylog2/database/filtering/DbFilterExpressionParser.java, graylog2-server/src/main/java/org/graylog2/database/filtering/DbQueryCreator.java, graylog2-server/src/main/java/org/graylog2/rest/resources/streams/StreamResource.java, graylog2-server/src/main/java/org/graylog2/search/SearchQuery.java, graylog2-server/src/main/java/org/graylog2/streams/PaginatedStreamService.java, graylog2-server/src/test/java/org/graylog2/database/filtering/DbFilterExpressionParserTest.java, graylog2-server/src/test/java/org/graylog2/database/filtering/DbQueryCreatorTest.java
Refactoring in the resource and service methods of Entities that use Entity Lists.
Unit tests added.
Filter expressions are now present not only in Streams, but also Saved Searches and Dashboards.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#4735
/nocl
Avoid code duplication, increase unit test coverage, move some specific pieces of code outside of Resource classes.
=> Refactoring. Saved Searches and Dashboards with filters.

changelog/unreleased/pr-14749.toml, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/ScriptingApiResource.java, graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config
This PR is enabling the simple search/scripting API (previously in preview) by default, making it generally available.
=> Enabling simple search/scripting API by default.

graylog2-server/src/main/java/org/graylog2/inputs/InputService.java, graylog2-server/src/main/java/org/graylog2/inputs/InputServiceImpl.java, graylog2-server/src/main/resources/log4j2.xml
Backport https://github.com/Graylog2/graylog2-server/pull/14515 to `5.0`.
/nocl
Contains server changes for https://github.com/Graylog2/graylog-plugin-enterprise-integrations/pull/1005.
=> Server changes to support Azure multi-node capability (5.0)

.github/workflows/fix-linter-hints.yml
With this PR we are extending the github action which fixes auto-fixable ESLint hints periodically. It is now also fixing auto-fixable Styllint hints.
Related to https://github.com/Graylog2/graylog2-server/pull/11332
/nocl
=> Fix auto-fixable Stylelint hints periodically.

graylog2-web-interface/src/generator/__tests__/parse.test.ts, graylog2-web-interface/src/logic/permissions/EntityShareState.test.ts, graylog2-web-interface/src/views/components/visualizations/__tests__/ChartData.test.ts, graylog2-web-interface/src/views/logic/ExpandRows.test.ts, graylog2-web-interface/src/views/logic/views/CopyPageToDashboard.test.ts, graylog2-web-interface/src/views/logic/views/CopyWidgetToDashboard.test.ts, graylog2-web-interface/src/views/logic/views/MoveWidgetToTab.test.ts, graylog2-web-interface/src/views/logic/views/UpdateSearchForWidgets.test.ts, graylog2-web-interface/src/views/logic/views/ViewTransformer.test.ts, graylog2-web-interface/test/helpers/readJsonFixture.ts
This PR contains a simple refactoring. We are creating a helper function for tests to read JSON fixtures. Before this change we were often repeating code when reading a fixture.
/nocl
=> Create helper function for tests to read JSON fixtures.

graylog2-web-interface/src/views/components/dashboard/DashboardPropertiesModal.tsx
Prior to this PR, after editing the search/dashboard's metadata, a new search execution was triggered, although unnecessary. This is caused by the form submit event bubbling up to the search bar controls form.
This change is now stopping the form submit event in the view properties modal on submit.
/nocl
=> Stop event propagation to avoid search execution when editing metadata.

graylog2-web-interface/src/views/logic/slices/searchExecutionSlice.ts
This PR is fixing an issue where declaring a parameter with a default value leads to an exception. This is caused by creating the binding in a wrong way.
/nocl
=> Fixing usage of default value for parameters.

changelog/unreleased/pr-14670.toml, graylog2-server/src/main/java/org/graylog2/lookup/adapters/CSVFileDataAdapter.java, graylog2-server/src/test/java/org/graylog2/lookup/adapters/CSVFileDataAdapterTest.java
Backport https://github.com/Graylog2/graylog2-server/pull/14670 to `4.3`.
=> Improve CSV File Adapter error handling (4.3)

changelog/unreleased/pr-14670.toml, graylog2-server/src/main/java/org/graylog2/lookup/adapters/CSVFileDataAdapter.java, graylog2-server/src/test/java/org/graylog2/lookup/adapters/CSVFileDataAdapterTest.java
Backport https://github.com/Graylog2/graylog2-server/pull/14670 to `5.0`.
=> Improve CSV File Adapter error handling (5.0)

graylog2-web-interface/src/components/common/InputDescription.tsx, graylog2-web-interface/src/components/common/ReadOnlyFormGroup.tsx, graylog2-web-interface/src/components/users/UserEdit/ProfileSection.tsx
_Please note, this PR needs to be emerged together with https://github.com/Graylog2/graylog-plugin-enterprise/pull/4747_
Before:
After:
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/4747
/nocl
=> Improve margin of username on user profile edit page.

UPGRADING.md, changelog/unreleased/pr-14424.toml, graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java
And adopt the new default mentioned in UPGRADING.md
=> Rename a few time size optimizing rotation/retention settings

graylog2-web-interface/src/views/components/Search.tsx, graylog2-web-interface/src/views/components/widgets/useCurrentSearchTypesResults.ts, graylog2-web-interface/src/views/logic/slices/viewSelectors.ts
Prior to this change, the `useCurrentSearchTypesResults` hook was throwing an exception when trying to extract search results for a search type which has not completed loading yet. This change is fixing this, returning `undefined` in this case.
/nocl
=> Handle missing search results in `useCurrentSearchTypesResults`.

data-node/src/test/java/org/graylog/datanode/integration/DatanodeSecuritySetupIT.java, full-backend-tests/src/test/java/org/graylog/plugins/views/FavoritesIT.java, full-backend-tests/src/test/java/org/graylog/plugins/views/ScriptingApiResourceIT.java, full-backend-tests/src/test/java/org/graylog/plugins/views/StartPageIT.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/GraylogApis.java, graylog2-server/src/test/java/org/junit/platform/engine/support/hierarchical/ContainerMatrixHierarchicalTestEngine.java
Added preemptive authentication to the requests in IT tests to hopefully make the tests more stable.
/nocl
=> Add Preemptive Auth to IT Tests

graylog2-web-interface/src/components/streamrules/StreamRule.jsx, graylog2-web-interface/src/stores/streams/StreamRulesStore.ts
Currently the edit stream rule modal does not close when clicking the "Update rule" submit button.
This PR is fixing the problem.
Fixes https://github.com/Graylog2/graylog2-server/issues/14831
/nocl
=> Close edit stream rule modal on submit.

pom.xml
The DataNode should not get built when building the forwarder.
/nocl
=> Added a profile so the DataNode can be skipped for the Forwarder

graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.corevisualizations.test.tsx, graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.sort.test.tsx, graylog2-web-interface/src/views/components/widgets/Widget.aggregations.test.tsx
Tests for the aggregation wizard are showing instabilities when Jenkins is under load. Therefore this PR is increasing timeouts for them.
/nocl
=> Extending timeouts for aggregation wizard tests.

graylog2-server/src/main/java/org/graylog2/rest/resources/entities/preferences/model/EntityListPreferences.java, graylog2-server/src/test/java/org/graylog2/rest/resources/entities/preferences/service/EntityListPreferencesServiceImplTest.java
Null instead of zero for per_page field if it is missing.
/nocl
Needed by FE.
Manually and with new test.
=> Null instead of zero for per_page field if it is missing

graylog2-web-interface/src/components/event-definitions/constants.ts, graylog2-web-interface/src/components/event-definitions/event-definitions/BulkActions.tsx, graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionActions.tsx, graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionsContainer.tsx, graylog2-web-interface/src/components/event-definitions/hooks/useEventDefinitions.ts, graylog2-web-interface/src/components/event-notifications/event-notifications/BulkActions.tsx, graylog2-web-interface/src/components/event-notifications/event-notifications/Constants.ts, graylog2-web-interface/src/components/event-notifications/event-notifications/EventNotificationsContainer.tsx, graylog2-web-interface/src/components/event-notifications/hooks/useEventNotifications.ts, graylog2-web-interface/src/components/streams/StreamsOverview/StreamsOverview.tsx
We recently implemented some changes for the `EntityDataTable` at the same time we were implementing the component for the event definitions and notifications overview. With this PR we are updating the usage by:
- displaying only one page size select per overview
- displaying the bulk actions as a dropdown
- persisting layout changes (sort and page size)
- fixing the static width of the priority column
/nocl
=> Update `EntityDataTable` usage in event definitions and notifications overview.

changelog/unreleased/pr-14762.toml, graylog2-web-interface/src/views/components/messagelist/NodeName.tsx
**Note:** This PR should be backported to `5.0`.
Prior to this PR, clicking on the link to a node did open its details page after doing a full page refresh. This is inconsistent with other parts of the product and disrupts the user flow due to a longer loading time.
This change is now making sure that we are using the internal router to get to the new page.
=> Avoid opening node details in new tab.

changelog/unreleased/issue-14827.toml, graylog2-web-interface/src/components/bootstrap/styles/menuItem.js, graylog2-web-interface/src/components/common/DropdownMenu.tsx, graylog2-web-interface/src/components/common/EntityFilters/ActiveFilter.tsx, graylog2-web-interface/src/components/common/EntityFilters/ActiveFilters.tsx, graylog2-web-interface/src/components/common/EntityFilters/Constants.ts, graylog2-web-interface/src/components/common/EntityFilters/CreateFilterDropdown.tsx, graylog2-web-interface/src/components/common/EntityFilters/EntityFilters.test.tsx, graylog2-web-interface/src/components/common/EntityFilters/EntityFilters.tsx, graylog2-web-interface/src/components/common/EntityFilters/FilterConfiguration.tsx, graylog2-web-interface/src/components/common/EntityFilters/FitlersForQueryParams.test.ts, graylog2-web-interface/src/components/common/EntityFilters/configuration/StaticOptionsList.tsx, graylog2-web-interface/src/components/common/EntityFilters/configuration/SuggestionsList.tsx, graylog2-web-interface/src/components/common/EntityFilters/hooks/useFilterValueSuggestions.ts, graylog2-web-interface/src/components/common/OverlayDropdown.tsx, graylog2-web-interface/src/components/common/OverlayDropdownButton.tsx, graylog2-web-interface/src/stores/PaginationTypes.ts
With this PR we are implementing a new filter for the streams overview. It is now possible to filter the streams by index set.
Fixes https://github.com/Graylog2/graylog2-server/issues/14827
=> Implement index set filter for streams overview.

graylog2-web-interface/package.json, graylog2-web-interface/yarn.lock
This PR is removing the `terser-webpack-plugin`, as it has been replaced with ESBuild in #14071 & #14072.
/nocl
=> Removing `terser-webpack-plugin`.

graylog2-web-interface/src/pages/LUTDataAdaptersPage.jsx
This PR is fixing fallout from #12911 by passing the required parameter to a callback in order to restore a redirect after a successful creation of a data adapter.
/nocl
=> Fixing redirect after data adapter creation.

graylog2-server/src/test/java/org/graylog2/shared/bindings/providers/ParameterizedHttpClientProviderTest.java
=> Use correct junit 5 annotation to disable test

graylog2-web-interface/src/pages/StreamOutputsPage.jsx, graylog2-web-interface/src/pages/StreamOutputsPage.tsx
This PR is fixing an error on the stream output page. The error has been introduced with https://github.com/Graylog2/graylog2-server/pull/14865.
To test the fix you need to click on the "Manage Outputs" action for a stream in the streams overview.
/nocl
=> Fix error which occurred when rendering stream output page.

graylog2-web-interface/webpack.config.js
This PR is adding a more aggressive chunking strategy for the web asset build. leading to smaller entry chunks by splitting out more modules.
/nocl
=> Use more aggressive chunking for web assets.

graylog2-web-interface/src/components/lookup-tables/CacheTableEntry.tsx, graylog2-web-interface/src/components/lookup-tables/CachesOverview.jsx, graylog2-web-interface/src/components/lookup-tables/DataAdaptersOverview.jsx, graylog2-web-interface/src/components/lookup-tables/LUTTableEntry.tsx, graylog2-web-interface/src/components/lookup-tables/LookupTablesOverview.jsx
Some updates to LUT, Caches and Data Adapters index views
/nocl
A regular backport was not possible here because the code has change significantly around this views. This PR only includes the most pressing fixes to these 3 views.
1. Overflow on x axis
2. Delete caches
3. Show search results when search initiated in a page other than 1
Fix some of the most annoying issues with these 3 views
Manually
=> backport updates to LUT Caches and Data Adapters index views

changelog/unreleased/issue-4889.toml, graylog2-server/src/main/java/org/graylog2/rest/resources/HelloWorldResource.java, graylog2-server/src/test/java/org/graylog2/rest/resources/HelloWorldResourceTest.java
Resolves Graylog2/graylog-plugin-enterprise#4889
See linked issue for details
=> Fix issue Graylog2/graylog-plugin-enterprise/issues/4889

graylog2-web-interface/package.json, graylog2-web-interface/src/components/common/SearchForm.tsx, graylog2-web-interface/src/index.tsx, graylog2-web-interface/src/stores/event-definitions/FilterPreviewStore.js, graylog2-web-interface/src/stores/extractors/ExtractorsStore.js, graylog2-web-interface/src/stores/system/SystemStore.js, graylog2-web-interface/src/views/logic/slices/executeSearch.ts
Due to the general maturity of the native `Promise` implementations, we now safely get rid of `bluebird`.
/nocl
=> Removing `bluebird`.

graylog2-web-interface/package.json, graylog2-web-interface/packages/graylog-web-plugin/package.json
This PR is removing the `react-bootstrap` dependency from the internal `graylog-web-plugin` package, as it is only required in core and not in all plugins.
/nocl
=> Remove `react-bootstrap` from `graylog-web-plugin`.

graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/PreflightAssetsResource.java, graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/PreflightConstants.java, graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/PreflightWebModule.java, graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/web/resources/PreflightAssetsResource.java, graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/web/resources/PreflightResource.java, graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/web/resources/PreflightStatusResource.java
This PR is adding a REST resource serving the static web assets for the Preflight UI. It is moving the status resource which was previously serving `/` to `/api/status` in order to avoid conflicts.
/nocl
=> Adding Preflight REST resource serving web assets.

graylog2-web-interface/src/routing/AppRouter.test.tsx, graylog2-web-interface/src/routing/AppRouter.tsx
This PR is making sure that orphan routes (plugin routes which have a parent component of `null`) are will wrapped with global context providers.
/nocl
=> Wrap orphan routes with global providers.

data-node/src/main/java/org/graylog/datanode/management/CommandLineProcess.java, data-node/src/test/java/org/graylog/datanode/management/CommandLineProcessTest.java
The OpenSearch process should use its bundled JVM version.
/nocl
=> Don't pass JAVA_HOME environment variable to OpenSearch process

graylog2-server/src/main/java/org/graylog2/shared/system/stats/os/OshiOsProbe.java
1.Fixed when using OSHI library to get cpu load is always 0.
2.Fixed getting CPU frequency could be negative because CPU frequency could exceed Int max value.
=> Fixed some issues with OshiOsProbe

graylog2-web-interface/src/routing/AppRouter.tsx
Fix for inputs route in cloud environment. The #12911 PR disabled the enabled route again.  
/nocl
=> fix inputs ui route in cloud

changelog/unreleased/pr-15198.toml, data-node/pom.xml, data-node/src/main/java/org/graylog/datanode/Configuration.java
Update Opensearch distributed with Datanode from 2.4.1 to 2.5.0
Existing set of unit and integration tests
=> Update opensearch in datanode to 2.5.0

graylog2-server/src/main/java/org/graylog2/security/AccessTokenServiceImpl.java
/nocl Nothing changed
Removing debug log statement that was forgotten from a prior PR
=> Remove debug log statement

graylog2-server/src/test/java/org/graylog2/inputs/codecs/EncodingTest.java, pom.xml
Bumping the Surefire version to 3.0.0
/nocl
Mainly to fix the Forkstarter bug that happens once in a while and is supposed to be solved with v3.
=> Bumping Surefire to 3.0.0

changelog/unreleased/issue-15209.toml, graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionFormContainer.tsx
Fixes https://github.com/Graylog2/graylog2-server/issues/15209
=> Fix: Unable to add custom field when creating event definition

changelog/unreleased/issue-14767.toml
=> Fix changelog syntax

pom.xml
/nocl
see: #15213 for motivation etc.
=> Bump Failsafe Plugin to 3.0.0

graylog2-server/src/main/java/org/graylog/grn/GRNTypesModule.java
Add missing fallback providers for last_opened and favorites.
fixes: #15271 
/nocl
=> Add fallback grn providers for last_opened and favorites

graylog2-web-interface/src/hooks/useEventDefinition.tsx
This pr adds a handler to data mapping if  there is no specific aggregation config in ED 
fix: https://github.com/Graylog2/graylog2-server/issues/15262
/nocl
=> Fix replay search when ED type is Event Correlation

graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchesList.tsx, graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchesModal.test.tsx
This PR is fixing a problem which occurs when changing the page size on the saved searches overview.
Please have a look at https://github.com/Graylog2/graylog2-server/issues/15268 for more information.
Fixes https://github.com/Graylog2/graylog2-server/issues/15268
/nocl
=> Fix page size change on saved searches overview.

graylog2-server/src/main/java/org/graylog2/rest/models/system/sessions/responses/SessionValidationResponse.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/SessionsResource.java
When a browser has basic auth information stored for the current URL, the web interface will bail out due to the session validation endpoint returning a 500. This PR is fixing it by handling the optional session and returning a proper response.
/nocl
=> Handle authenticated user with no session in session validation endpoint.

graylog2-web-interface/src/components/event-definitions/replay-search/hooks/useAttributeComponents.tsx, graylog2-web-interface/src/hooks/useEventById.tsx, graylog2-web-interface/src/hooks/useEventDefinition.test.tsx, graylog2-web-interface/src/hooks/useEventDefinition.tsx, graylog2-web-interface/src/views/logic/views/UseCreateViewForEvent.ts, graylog2-web-interface/src/views/logic/views/UseCreateViewForEventDefinition.ts, graylog2-web-interface/src/views/pages/EventDefinitionReplaySearchPage.test.tsx, graylog2-web-interface/src/views/pages/EventDefinitionReplaySearchPage.tsx, graylog2-web-interface/src/views/pages/EventReplaySearchPage.test.tsx, graylog2-web-interface/src/views/pages/EventReplaySearchPage.tsx
This PR add handlers in case when ED doesn't exist.  
fix: https://github.com/Graylog2/graylog2-server/issues/15150
/nocl
=> Add fallbacks in case when ED doesnt exist

changelog/unreleased/issue-15030.toml, graylog2-server/src/main/java/org/graylog/plugins/views/search/export/CommandFactory.java
Adds the timezone to an export command if it was supplied in the REST call.
fixes #15030
=> Add Timezone to Export Command

UPGRADING.md
The `Field type refresh interval` index set default setting was incorrectly mapped to the `index_field_type_periodical_full_refresh_interval` `server.conf` value in the initial implementation of Global Index Set defaults (see https://github.com/Graylog2/graylog2-server/pull/13018). This mismapping was fixed in https://github.com/Graylog2/graylog2-server/pull/14842, where the defaults code was changed to reference the correct hard-coded default in `IndexSetConfig. DEFAULT_FIELD_TYPE_REFRESH_INTERVAL`. 
There is currently no `server.conf` value for the `IndexSetConfig.DEFAULT_FIELD_TYPE_REFRESH_INTERVAL` constant. I think we are too late in the 5.1 release cycle to be adding new `server.conf` properties, so I have opened https://github.com/Graylog2/graylog2-server/issues/15320 to request …
=> Index set defaults: Remove incorrect Field type refresh interval property from upgrading instructions

graylog2-web-interface/src/views/logic/valueactions/createEventDefinition/hooks/hookHelpers.ts
fix: https://github.com/Graylog2/graylog2-server/issues/15347
/nocl
=> Add escape while building search query for event definition creation

graylog2-server/src/main/java/org/graylog2/bootstrap/ServerBootstrap.java, graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/PreflightWebModule.java, graylog2-server/src/main/resources/org/graylog2/featureflag/feature-flag.config
/nocl
Disable preflight web by default with feature flag
=> Set default off for preflight web feature flag

graylog2-server/src/main/java/org/graylog2/database/DbEntity.java, graylog2-server/src/main/java/org/graylog2/database/suggestions/MongoEntitySuggestionService.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/contentpacks/titles/EntityTitleService.java, graylog2-server/src/test/java/org/graylog2/database/dbcatalog/DbEntitiesScannerTest.java, graylog2-server/src/test/java/org/graylog2/database/suggestions/MongoEntitySuggestionServiceTest.java, graylog2-server/src/test/java/org/graylog2/rest/resources/system/contentpacks/titles/EntityTitleServiceTest.java
Typo in DbEntity's constants fixed.
/nocl
=> Typo in DbEntity's constants fixed

graylog2-web-interface/src/components/content-packs/ContentPackEntitiesList.jsx
fixes #15015 
/nocl since this does not affect any released versions
local dev env
=> Only display a single ContentPackEntity modal at once

graylog2-web-interface/src/views/logic/valueactions/createEventDefinition/CreateEventDefinitionModal.tsx
fix: https://github.com/Graylog2/graylog2-server/issues/15376
/nocl
=> Add onClose to onContinueConfigurationClick in CreateEventDefinitionModal

changelog/unreleased/issue-4774.toml, graylog2-web-interface/src/pages/SystemOverviewPage.jsx
This PR fix showing Index Failure on on the Cloud.
fix Graylog2/graylog-plugin-enterprise#4774
=> Show Index Failures on Cloud

graylog2-server/src/main/java/org/graylog2/bindings/PeriodicalBindings.java, graylog2-server/src/main/java/org/graylog2/cluster/lock/MongoLockService.java, graylog2-server/src/main/java/org/graylog2/configuration/TelemetryConfiguration.java, graylog2-server/src/main/java/org/graylog2/database/indices/MongoDbIndexTools.java, graylog2-server/src/main/java/org/graylog2/telemetry/cluster/TelemetryClusterInfoPeriodical.java, graylog2-server/src/main/java/org/graylog2/telemetry/cluster/db/DBTelemetryClusterInfo.java, graylog2-server/src/main/java/org/graylog2/telemetry/rest/TelemetryResource.java, graylog2-server/src/main/java/org/graylog2/telemetry/rest/TelemetryResponseFactory.java, graylog2-server/src/main/java/org/graylog2/telemetry/rest/TelemetryService.java, graylog2-server/src/main/java/org/graylog2/telemetry/user/db/DBTelemetryUserSettingsService.java, graylog2-server/src/main/java/org/graylog2/telemetry/user/db/TelemetryUserSettingsDto.java, graylog2-server/src/main/java/org/graylog2/web/resources/AppConfigResource.java, graylog2-server/src/test/java/org/graylog2/telemetry/rest/TelemetryServiceTest.java, graylog2-server/src/test/java/org/graylog2/telemetry/rest/TelemetryServiceWithDbTest.java
This PR improves the performance when collecting node telemetry data and tries to fix the following issue: #15266 
/nocl
=> telemetry performance improvement: save and use telemetry node data from db

changelog/unreleased/pr-15400.toml, graylog2-server/src/main/java/org/graylog2/system/jobs/SystemJobManager.java, graylog2-server/src/test/java/org/graylog2/system/jobs/SystemJobManagerTest.java
This is a backport of https://github.com/Graylog2/graylog2-server/pull/15400
=> Fix concurrency issue in SystemJobManager (#15400)

UPGRADING.md
5.1 changes how Sigma rules can be imported from Git by adding the option to import rules from repositories other than the official Sigma HQ repo. This information should prepare users for these changes. 
/nocl
=> Add Sigma Repository information to UPGRADING.md

graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ElasticsearchInstanceES7.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/OpenSearch13Instance.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/RunningElasticsearchInstanceES7.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/testing/OpenSearchInstance.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/ContainerizedGraylogBackend.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/GraylogBackend.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/RunningGraylogBackend.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/apis/GraylogApis.java, graylog2-server/src/test/java/org/graylog/testing/elasticsearch/SearchServerInstance.java
Added logging the console output of the search-server in case of a failing test so that we have better chances to find the root of the flaky tests.
/nocl
=> Added logging from  indexer docker container for failing Integration Tests

graylog2-server/src/main/java/org/graylog2/shared/rest/resources/csp/CSP.java
**Note:** This requires a backport to `5.1`.
This PR is allowing loading images from `data:`-URLs in our content security policy. Previously, only loading images from `'self'` was allowed.
Fixes #15430.
/nocl Fixing regression introduced in development.
=> Allow loading images from `data:` URL in CSP.

graylog2-server/src/main/java/org/graylog2/shared/rest/resources/csp/CSP.java
**Note:** This is a backport of #15431 to `5.1`.
This PR is allowing loading images from `data:`-URLs in our content security policy. Previously, only loading images from `'self'` was allowed.
Fixes #15430.
/nocl Fixing regression introduced in development.
=> Allow loading images from `data:` URL in CSP. (`5.1`)

changelog/unreleased/pr-14851.toml
Add changelog entry for https://github.com/Graylog2/graylog2-server/pull/14851
/nocl
=> Added changelog to 14851 pr

changelog/unreleased/issue-15259.toml, graylog2-web-interface/src/components/event-definitions/event-definitions/BulkActions.tsx
fixes https://github.com/Graylog2/graylog2-server/issues/15259
=> Fix: BulkActions dialog not closing after clicking on Confirm

changelog/unreleased/pr-15409.toml, graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/FieldTypeMapper.java
This PR is introducing specific field types for the streams, node and input metadata fields in messages. These are mapped from physical types whenever the field name of the type matches our convention for those fields.
=> Introducing specific field types for streams and source input & node.

graylog2-web-interface/src/views/pages/StreamSearchPage.test.tsx, graylog2-web-interface/src/views/pages/StreamSearchPage.tsx
In #15444 creating a search for a new saved search/dashboard was made explicit. Unfortunately, creating the search for a new stream search (a saved search scoped to a specific stream) was not adjusted, leading to the stream search page not loading properly.
This PR is changing this by making search creation explicit for the stream search page as well.
/nocl Fixing a regression introduced in development.
=> Create search before loading stream search page. (`5.1`)

changelog/unreleased/pr-15480.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/PipelineRuleService.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/RuleResource.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/simulator/RuleSimulator.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/rest/RuleResourceTest.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/simulator/RuleSimulatorTest.java, graylog2-web-interface/src/components/rules/RuleForm.tsx
part of #15490 
Improvements for the mini simulator on the rule creation page. 
Extracting logic so that we can reuse it in the rule builder ui
Now allowing to input json.  So its possible to copy a message from the search page and paste it as an example.
=> accept json to simulate rules

graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/testing/DatanodeInstance.java
=> Wait for healthy cluster when starting datanode in matrix tests

misc/datanode.conf
Config location setting present in default datanode.conf file.
/nocl
Limit a surprise of a new config property
=> Config location setting present in default datanode.conf file

graylog2-web-interface/src/views/components/messagelist/NodeName.tsx, graylog2-web-interface/src/views/components/sidebar/fields/FieldTypeIcon.tsx
This PR is adding icons for the newly introduced field types `streams`, `node` & `input`. The icon for the `streams` type has been previously used for the node summary in message details, this has been aligned with the new icon for the `node` type now.
/nocl
=> Adding icons for new streams/input/node field types.

graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerFactory.java
Increasing the timeout from 120 to 600 seconds to solve sporadic build errors on Jenkins that are very probably happening because the workers are just not fast enough/are under too much load.
/nocl
=> Increasing GL Container Startup in Tests

graylog2-server/pom.xml, graylog2-server/src/main/java/org/graylog2/configuration/TelemetryConfiguration.java, graylog2-server/src/main/java/org/graylog2/telemetry/rest/TelemetryResponseFactory.java, graylog2-server/src/test/java/org/graylog2/telemetry/rest/TelemetryServiceTest.java, graylog2-server/src/test/java/org/graylog2/telemetry/rest/TelemetryServiceWithDbTest.java
fixes Graylog2/graylog-plugin-enterprise#5194
changes:
- don't flatten `plugin` and `search_cluster` section
- replace `.` separator with `_`
/nocl
=> telemetry event renaming

changelog/unreleased/pr-15556.toml, graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java, graylog2-server/src/main/java/org/graylog2/configuration/IndexSetsDefaultConfiguration.java, graylog2-server/src/main/java/org/graylog2/indexer/IndexSetValidator.java, graylog2-server/src/main/java/org/graylog2/rest/models/system/indices/RotationStrategies.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indexer/IndexSetDefaultsResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/indices/RotationStrategyResource.java, graylog2-server/src/test/java/org/graylog2/indexer/IndexSetValidatorTest.java, graylog2-web-interface/src/components/common/RangeInput.tsx, graylog2-web-interface/src/components/indices/IndexSetConfigurationForm.tsx, graylog2-web-interface/src/components/indices/Types.ts, graylog2-web-interface/src/components/indices/rotation/TimeBasedSizeOptimizingStrategyConfiguration.tsx, graylog2-web-interface/src/hooks/useTimeSizeOptimizingFixedLeeway.ts, graylog2-web-interface/src/stores/indices/IndicesConfigurationStore.ts
backport of https://github.com/Graylog2/graylog2-server/pull/15556
=> add max leeway configuration and validation (#15556)

graylog2-server/pom.xml, graylog2-server/src/main/java/org/graylog2/configuration/TelemetryConfiguration.java, graylog2-server/src/main/java/org/graylog2/telemetry/rest/TelemetryResponseFactory.java, graylog2-server/src/test/java/org/graylog2/telemetry/rest/TelemetryServiceTest.java, graylog2-server/src/test/java/org/graylog2/telemetry/rest/TelemetryServiceWithDbTest.java
=> Telemetry event renaming 5.1 backport

graylog2-server/src/main/java/org/graylog/security/certutil/CertConstants.java, graylog2-server/src/main/java/org/graylog/security/certutil/keystore/storage/KeystoreMongoStorage.java, graylog2-server/src/main/java/org/graylog2/cluster/certificates/CertificatesService.java, graylog2-server/src/main/java/org/graylog2/cluster/certificates/NodeCertificate.java, graylog2-server/src/test/java/org/graylog2/cluster/certificates/CertificatesServiceTest.java
Fixed CertificateService.
/nocl
The bug blocks Jan's progress on data-node.
With additional test.
=> Fixed CertificateService. Added a new test.

data-node/src/main/java/org/graylog/datanode/configuration/ConfigurationProvider.java, data-node/src/main/java/org/graylog/datanode/configuration/TlsConfigurationSupplier.java, data-node/src/main/java/org/graylog/datanode/configuration/certificates/CertificateMetaData.java, graylog2-server/src/main/java/org/graylog/security/certutil/CertConstants.java, graylog2-server/src/main/java/org/graylog/security/certutil/CertutilCert.java, graylog2-server/src/main/java/org/graylog/security/certutil/CertutilHttp.java
Data node/otp reencryption preparation.
/nocl
This tiny refactoring will simplify the implementation of decryption of existing certificates and re-encryption with OTP.
Data-node was started manually, to check it is still able to run in secure mode, after changes have been made to the code.
=> Data node/otp reencryption preparation

data-node/src/main/java/org/graylog/datanode/configuration/ConfigurationProvider.java, data-node/src/main/java/org/graylog/datanode/configuration/RootCertificateFinder.java, data-node/src/main/java/org/graylog/datanode/configuration/TruststoreCreator.java, data-node/src/test/java/org/graylog/datanode/configuration/TruststoreCreatorTest.java
Refactoring and additional tests
/nocl
1. Use constants more.
2. Use general exceptions more.
3. Add missing test.
4. Prefer char[] over String as passwords.
=> Refactoring and additional tests

README.markdown
We missed updating this file, so let's align the description with the rest of our messaging.
fixes #15620
=> Change project description

data-node/src/main/java/org/graylog/datanode/bootstrap/preflight/DataNodePreflightGeneratePeriodical.java, graylog2-server/src/main/java/org/graylog/security/certutil/csr/CertificateAndPrivateKeyMerger.java, graylog2-server/src/main/java/org/graylog/security/certutil/keystore/storage/SmartKeystoreStorage.java, graylog2-server/src/test/java/org/graylog/security/certutil/csr/CertificateAndPrivateKeyMergerTest.java
CertificateAndPrivateKeyMerger:
1. uses the same password for a key and a keystore,
2. receives unit test,
3. gets slightly refactored to not have a dependency on storage class (easier testing).
/nocl
First part of incoming password problems solutions.
=> Fixed password bug

graylog2-web-interface/src/preflight/components/ConfigurationWizard/CertificateProvisioning.test.tsx
These changes will hopefully improve the `CertificateProvisioning.test`, which has been flaky.
/nocl
=> Avoid state update on an unmounted component in `CertificateProvisioning.test`.

changelog/unreleased/pr-15614.toml, full-backend-tests/src/test/java/org/graylog/plugins/views/SuggestionResourceIT.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/QuerySuggestionsES7.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SuggestionsResource.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/suggestions/SuggestionEntryDTO.java, graylog2-server/src/main/java/org/graylog2/cluster/NodeImpl.java, graylog2-server/src/main/java/org/graylog2/cluster/NodeService.java, graylog2-server/src/main/java/org/graylog2/cluster/NodeServiceImpl.java, graylog2-server/src/test/java/org/graylog2/cluster/TestNodeService.java, graylog2-web-interface/src/views/components/searchbar/completions/FieldValueCompletion.test.ts, graylog2-web-interface/src/views/components/searchbar/completions/FieldValueCompletion.ts
This PR is implementing functionality which returns optional titles in search query suggestions when a field of an advanced field type (`streams`, `input`, `node`) is used. This title is shown in the frontend to help the user understand the meaning of the suggestions.
Fixes Graylog2/graylog-plugin-enterprise#4515.
=> Include titles of advanced field types in suggestions.

changelog/unreleased/pr-15682.toml, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/ShannonEntropy.java, graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/StringEntropy.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java, graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/strings/ShannonEntropyTest.java, graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/stringEntropy.txt
Add a new `string_entropy` pipeline function, which supports the ability to calculate the entropy of the characters that make up an input string.
The current implementation uses Shannon Entropy for the entropy calculation. Shannon Entropy is a common method for quantifying the randomness/sameness of the types within a collection of entities. If all entities are all the same type, then the entropy is 0. As more and more types are introduced, the entropy increases. This Java implementation applies a Shannon Entropy calculation to characters within a string.
Examples:
- Input: [1111], Entropy: 0
- Input: [5555555555], Entropy: 0.0
- Input: [5555555555], Entropy: 0.0
- Input: [1555555555], Entropy: 0.47
- Input: [1111155555], Entropy: 1.0
- Input: [1234567890], Entropy: 3.32
- Input: …
=> Add string_entropy pipeline function

data-node/src/main/java/org/graylog/datanode/bootstrap/preflight/DataNodePreflightGeneratePeriodical.java, graylog2-server/src/main/java/org/graylog/security/certutil/cert/CertificateChain.java, graylog2-server/src/main/java/org/graylog/security/certutil/cert/storage/CertChainMongoStorage.java, graylog2-server/src/main/java/org/graylog/security/certutil/cert/storage/CertChainStorage.java, graylog2-server/src/main/java/org/graylog/security/certutil/csr/CertificateAndPrivateKeyMerger.java, graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/GraylogPreflightGeneratePeriodical.java, graylog2-server/src/test/java/org/graylog/security/certutil/cert/CertificateChainTest.java, graylog2-server/src/test/java/org/graylog/security/certutil/cert/storage/CertChainMongoStorageTest.java, graylog2-server/src/test/java/org/graylog/security/certutil/csr/CertificateAndPrivateKeyMergerTest.java
Storing and merging the whole certificate chain.
/nocl
So far only signed certificate was stored, without intermediate and root CAs.
New tests have been added.
=> Storing and merging the whole certificate chain.

changelog/unreleased/issue-15609.toml, graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java, graylog2-server/src/main/java/org/graylog2/security/MongoDBSessionService.java, graylog2-server/src/main/java/org/graylog2/security/MongoDBSessionServiceImpl.java, graylog2-server/src/main/java/org/graylog2/security/MongoDbSessionDAO.java
=> update user session timeout on configuration change (`5.1`)

data-node/src/main/java/org/graylog/datanode/management/OpensearchCommandLineProcess.java, data-node/src/main/java/org/graylog/datanode/management/OpensearchProcessImpl.java, data-node/src/main/java/org/graylog/datanode/management/OpensearchRestClient.java
=> Opensearch cleanup in datanode

data-node/src/main/java/org/graylog/datanode/bindings/ServerBindings.java, graylog2-server/src/main/java/org/graylog/security/certutil/CertutilCa.java, graylog2-server/src/main/java/org/graylog/security/certutil/keystore/storage/SinglePasswordKeystoreContentMover.java, graylog2-server/src/test/java/org/graylog/security/certutil/keystore/storage/KeystoreFileStorageTest.java, graylog2-server/src/test/java/org/graylog/security/certutil/keystore/storage/SinglePasswordKeystoreContentMoverTest.java
KeyStoreContentMover improved and tested.
/nocl
Limit assumptions we have on keystore format.
Have the mover tested with unit tests.
With additional unit tests.
=> KeyStoreContentMover improved and tested

graylog2-web-interface/packages/graylog-web-plugin/package.json
This reverts PR #15705.
The `react-router` update is reverted, because it introduces a bug related to feature detection of React 18's transition API. A PR to fix this upstream already exists, but is not yet released. Therefore the dependency is downgraded until a version fixing it is released.
/nocl
=> Revert "Bump react-router-dom (#15705)"

graylog2-server/src/main/java/org/graylog2/outputs/BlockingBatchedESOutput.java
Fixes RejectedExecutionExceptions on server shutdown.
- Cancel the task instead of shutting down the executor
- Rename the field from "flushService" to "daemonScheduler"
/nocl (the issue wasn't present in any release)
=> Don't shutdown the injected daemon scheduler on ES output shutdown

graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/web/resources/PreflightResource.java, graylog2-web-interface/src/preflight/components/ConfigurationWizard/CACreateForm.test.tsx, graylog2-web-interface/src/preflight/components/ConfigurationWizard/CACreateForm.tsx, graylog2-web-interface/src/preflight/components/ConfigurationWizard/CertificateProvisioning.test.tsx, graylog2-web-interface/src/preflight/components/ConfigurationWizard/CertificateProvisioning.tsx
Fixes minor missing step changes and the missing state transferred to the FE for connectivity checking.
/nocl
=> DataNode: FE changes missing step changes/state

graylog2-server/src/main/java/org/graylog/security/certutil/keystore/storage/KeystoreFileStorage.java, graylog2-server/src/main/java/org/graylog/security/certutil/keystore/storage/KeystoreMongoStorage.java, graylog2-server/src/main/java/org/graylog2/cluster/certificates/CertificatesService.java, graylog2-server/src/test/java/org/graylog/security/certutil/keystore/storage/KeystoreFileStorageTest.java, graylog2-server/src/test/java/org/graylog2/cluster/certificates/CertificatesServiceTest.java
Deprecated code removal.
/nocl
Does not exist in Jan's code anymore, can be safely removed.
=> Deprecated code removal

graylog2-web-interface/CONTRIBUTING.md
With this PR we are adding a new section to the web interface `CONTRIBUTING` doc for conventions which are especially important to know. For now it includes a section about how to handle session timeouts in the frontend.
/nocl
=> Describe session timeout behaviour in `CONTRIBUTING` doc.

graylog2-server/src/main/java/org/graylog/plugins/views/startpage/StartPageService.java
We do not grab titles for each item on "Last Opened" list anymore, we do it only for the items on the page that is displayed (5 elements by default).
/nocl
See #15697 for a great description of the problem.
This PR has a potential of fixing it.
Manually.
=> Performance optimization

data-node/pom.xml, data-node/src/test/java/org/graylog/datanode/testinfra/DatanodeContainerizedBackend.java
/nocl
Trigger mvn package before building docker container for datanode integration tests
=> Run MavenPackager before integration tests in datanode

graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchesModal.tsx
This PR is adding a title for the saved searches modal to make it easier to understand its intention for users who are seeing it for the first time.
/nocl
=> Adding title for saved searches modal.

changelog/unreleased/pr-15750.toml, graylog2-server/src/main/java/org/graylog2/configuration/validators/RotationStrategyValidator.java
backport of https://github.com/Graylog2/graylog2-server/pull/15750
=> add time size based rotation to validator (#15750)

graylog2-server/src/main/java/org/graylog/aws/AWSModule.java
Skip binding CloudTrail input on Forwarder startup. This input is not available in the Forwarder. See: 
https://github.com/Graylog2/graylog2-server/blob/424d928a49d75549f4a1ed4cb01ec4fedbafbae7/graylog2-server/src/main/java/org/graylog/aws/inputs/cloudtrail/CloudTrailInput.java#L76-L78
/nocl
Closes https://github.com/Graylog2/forwarder/issues/106.
Applied this change in a `main` checkout of the Forwarder with `master` checked out for all submodule. Forwarder startup is successful.
=> Skip binding CloudTrail input in Forwarder

graylog2-web-interface/src/logic/authentication/okta/types.ts
Backport #15792
/nocl
/jpd Graylog2/graylog-plugin-enterprise#5390
=> Backport add okta type 

full-backend-tests/src/test/java/org/graylog/plugins/views/ScriptingApiResourceIT.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/mapping/MetricToSeriesSpecMapper.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/request/Metric.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/request/PercentageConfiguration.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/scriptingapi/validation/MetricValidator.java
Adding the Percentage metric to the Simple Scripting API.
/nocl
because it's an addition to the not yet released Metric and does not IMHO need it's separate changelog
TODO: maybe add option to show percentage value instead of float?
=> Adding percentage to Aggregations in Simple Scripting API

graylog2-web-interface/docs/fetch-mock.js, graylog2-web-interface/styleguide.config.js
This PR is introducing a mock for `window.fetch` in the frontend component gallery/style guide to avoid exceptions being thrown due to attempts to fetch from the (unreachable) API.
/nocl
=> Mock `fetch` in frontend docs.

graylog-project-parent/pom.xml, graylog2-server/pom.xml, pom.xml
Enables authentication with IAM for AWS MSK.
See https://github.com/aws/aws-msk-iam-auth
/nocl For now we only need this internally
=> Add aws-msk-iam-auth

graylog2-server/src/test/java/org/graylog2/lookup/adapters/dnslookup/DnsResolverPoolTest.java
=> Add missing license header to DnsResolverPoolTest

changelog/unreleased/pr-15869.toml, graylog2-web-interface/src/components/users/StartpageFormGroup.tsx, graylog2-web-interface/src/components/users/UserEdit/SettingsSection.tsx
The input was not validated before this change so you could leave the entity field empty which could be confusing.
fixes #15578
manually
=> User has to select an entity if he selects a Start Page type

graylog2-web-interface/src/components/login/LoginChrome.tsx
**Note:** This needs a backport to `5.1`.
This PR is decreasing the z-index of the login background so it does not cover the public notifications shown on the login page.
Fixes #15884.
/nocl
=> Decreasing z-index of login background.

graylog2-web-interface/src/logic/telemetry/TelemetryProvider.tsx, graylog2-web-interface/src/logic/telemetry/TelemetrySettingsConfig.tsx
Backport handle opt in/out capturing 
/nocl
ref #15743
=> Backport handle opt in/out capturing (#15743)

changelog/unreleased/issue-15707.toml, full-backend-tests/src/test/java/org/graylog/plugins/views/ScriptingApiResourceIT.java, graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/ESPivotBucketSpecHandler.java, graylog-storage-opensearch2/src/main/java/org/graylog/storage/opensearch2/views/searchtypes/pivot/OSPivotBucketSpecHandler.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/SeriesSpec.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/series/StdDev.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/series/SumOfSquares.java, graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/series/Variance.java
Fixes #15707.
See #15707.
Manually.
=> Sorting on metrics like variance or std deviation is now possible

.github/dependabot.yml
This PR is starting to add groups for dependencies which should be updated together. It is using the newly introduced dependabot functionality, as described here: https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/
/nocl
=> Adding groupings for dependencies.

graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchesModal.tsx
These changes are required for e2e tests.
/nocl
=> Improve accessibility of saved searches overview.

changelog/unreleased/issue-15678.toml, graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailEventNotificationConfig.java, graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailSender.java, graylog2-server/src/test/java/org/graylog/events/notifications/types/EmailSenderTest.java, graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationForm.jsx
With this PR we are including a "Alert Replay" link in the template for alert mail notifications.
Fixes https://github.com/Graylog2/graylog2-server/issues/15678
=> Include link to replay an alert in alert mail notification template.

.github/dependabot.yml
This PR is grouping depdendency updates for `@typescript-eslint`.
/nocl
=> Grouping dependency updates for `@typescript-eslint`.

changelog/unreleased/pr-15869.toml, graylog2-web-interface/src/components/users/StartpageFormGroup.tsx, graylog2-web-interface/src/components/users/UserEdit/SettingsSection.tsx
**Please note:** This is a backport of https://github.com/Graylog2/graylog2-server/pull/15869 for 5.1.
The input was not validated before this change so you could leave the entity field empty which could be confusing.
fixes #15578
manually
=> User has to select an entity if he selects a Start Page type (backport of #15869 for `5.1`)

graylog2-server/src/main/java/org/graylog2/commands/journal/AbstractJournalCommand.java, graylog2-server/src/main/java/org/graylog2/commands/journal/JournalDecode.java
Add missing guice bindings.
Refs #14222 
Refs #14459
/nocl
=> Fix journal show and journal decode command

graylog2-web-interface/src/index.tsx, graylog2-web-interface/src/logic/rest/FetchProvider.ts, graylog2-web-interface/src/routing/AppFacade.tsx
This PR is supporting Graylog2/graylog-plugin-enterprise#5457 by:
- Allowing `fetchPeriodically` to provide a custom type parameter for the response
- Pulling up the `LoginQueryClientProvider` and making sure it never gets unmounted so there is always a `QueryClient` provided
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#5457
/nocl
=> Support migrating public notifications to `react-query`.

graylog2-web-interface/src/components/event-definitions/replay-search/EventInfoBar.test.tsx, graylog2-web-interface/src/views/components/DashboardSearchBar.pluggableControls.test.tsx, graylog2-web-interface/src/views/components/Search.test.tsx, graylog2-web-interface/src/views/components/SearchBar.pluggableControls.test.tsx, graylog2-web-interface/src/views/components/WidgetQueryControls.pluggableControls.test.tsx, graylog2-web-interface/src/views/components/aggregationwizard/AggregationWizard.test.tsx, graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.corevisualizations.test.tsx, graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.sort.test.tsx, graylog2-web-interface/src/views/components/export/ExportModal.test.tsx, graylog2-web-interface/src/views/components/export/ExportSettings.test.tsx, graylog2-web-interface/src/views/components/sidebar/redo/RedoNavItem.test.tsx, graylog2-web-interface/src/views/components/sidebar/undo/UndoNavItem.test.tsx, graylog2-web-interface/src/views/components/widgets/Widget.test.tsx, graylog2-web-interface/src/views/test/testPlugins.ts, graylog2-web-interface/src/views/test/testViewsPlugin.ts
This PR is cleaning up plugin loading in tests by:
- Offering `usePlugin` function for convenience/using it in tests
- Replacing construction of custom views reducers with `useViewsPlugin`
/nocl
=> Cleaning up plugin loading in tests.

graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/validators/UnknownFieldsValidator.java, graylog2-server/src/main/java/org/graylog2/plugin/Message.java, graylog2-server/src/test/java/org/graylog/plugins/views/search/validation/validators/UnknownFieldsValidatorTest.java
Special field _index is validated correctly.
Fixes #15988.
/nocl
See #15988.
Manually.
Unit tests have been added as well.
=> Special field _index is validated correctly

graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/MessagesBatchES7IT.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ClientES7.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/Elasticsearch7InstanceBuilder.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/Elasticsearch7InstanceProvider.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ElasticsearchInstanceES7.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/OpenSearch13Instance.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/OpenSearch13InstanceBuilder.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/OpenSearch13InstanceProvider.java, graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/RunningElasticsearchInstanceES7.java, graylog-storage-elasticsearch7/src/test/resources/META-INF/services/org.graylog.testing.completebackend.SearchServerInterfaceProvider, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/MessagesBatchOS2IT.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/testing/ClientOS2.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/testing/DatanodeInstance.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/testing/DatanodeInstanceBuilder.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/testing/DatanodeInstanceProvider.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/testing/OpenSearchInstance.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/testing/OpenSearchInstanceBuilder.java, graylog-storage-opensearch2/src/test/java/org/graylog/storage/opensearch2/testing/OpenSearchInstanceProvider.java, graylog-storage-opensearch2/src/test/resources/META-INF/services/org.graylog.testing.completebackend.SearchServerInterfaceProvider, graylog2-server/src/test/java/org/graylog/testing/completebackend/ContainerizedGraylogBackend.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/SearchServerBuilder.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/SearchServerInstanceFactoryByVersion.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/SearchServerInstanceProvider.java, graylog2-server/src/test/java/org/graylog/testing/completebackend/SearchServerInterfaceProvider.java, graylog2-server/src/test/java/org/graylog/testing/elasticsearch/SearchServerInstance.java, graylog2-server/src/test/java/org/graylog/testing/elasticsearch/TestableSearchServerInstance.java
Using ServiceLoader infrastructure to create Instances instead of an instantiation by name. 
By name was especially error prone if we want to add new features.
/nocl
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/5512
=> Using ServiceLoader infrastructure to create ES/OS instances in Tests

graylog2-server/src/test/java/org/graylog/testing/mongodb/MongoDBContainer.java
Print a warning, if `getContainerInfo()` returns null.
/nocl 
This resulted in a NPE that failed the test but gives no hint on what happened - and if this is even a problem. So we print a warning insted.
=> Show warning in output, if no Info object is returned by TestContainers

graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/RunningElasticsearchInstanceES7.java, graylog2-server/src/test/java/org/graylog/testing/elasticsearch/ContainerCacheKey.java, graylog2-server/src/test/java/org/graylog/testing/elasticsearch/SearchServerInstance.java, graylog2-server/src/test/java/org/graylog/testing/elasticsearch/TestableSearchServerInstance.java
=> Caching of containers in tests takes heapsize into account

graylog2-web-interface/src/views/components/aggregationwizard/FieldSelect.tsx, graylog2-web-interface/src/views/components/aggregationwizard/grouping/configuration/FieldComponent.tsx, graylog2-web-interface/src/views/components/aggregationwizard/metric/MetricConfiguration.tsx, graylog2-web-interface/src/views/components/widgets/FieldsConfiguration.tsx
With this PR we are mainly moving logic from `FieldSelect` component which determines if field is qualified to the components which implement the `FieldSelect`.
These changes are required for https://github.com/Graylog2/graylog-plugin-enterprise/pull/5432
/nocl
=> Extract logic from `FieldSelect` component which determines if field is qualified.

full-backend-tests/src/test/java/org/graylog/plugins/views/MessagesResourceIT.java
Adds an integration test for setting a timezone on export.
fixes #15338 
/nocl
This is a test ;-)
=> Adding IT Test for Timezone in Export

graylog2-server/src/main/java/org/graylog/scheduler/DBCustomJobDefinitionService.java
I moved the class `DBCustomJobDefinitionService` into the regular server packages because I want to use it in a non-enterprise context and the class itself is not enterprise functionality.
I have not moved the test class because the tests are dependent on enterprise functionality.
/nocl
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/5540
=> Move DBCustomJobDefinitionService into server package

graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/web/resources/PreflightResource.java, graylog2-server/src/main/java/org/graylog2/rest/resources/system/ClusterResource.java, graylog2-server/src/main/java/org/graylog2/utilities/uri/TransportAddressSanitizer.java, graylog2-server/src/test/java/org/graylog2/utilities/uri/TransportAddressSanitizerTest.java
Transport address sanitized in 2 more places. Functionality slighthly reimplemented, moved to a separate class and unit-tested.
/nocl
Fixes #16055.
With new unit tests.
=> Transport address sanitized in 2 more places. 

misc/archiver.conf
/nocl
part of https://github.com/Graylog2/graylog-plugin-enterprise/issues/5428 https://github.com/Graylog2/graylog-plugin-enterprise/issues/5227
Adding example configuration for prometheus exporter
=> add prometheus example configuration for archiver

changelog/unreleased/issue-12165.toml
=> Fix syntax error in changelog/unreleased/issue-12165.toml

changelog/unreleased/issue-12165.toml
(cherry picked from commit 85708270a850ad2a8c16c499659881cd778affe6)
/nocl
=> Fix syntax error in changelog/unreleased/issue-12165.toml (#16069)

changelog/unreleased/pr-16072.toml, graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterAggregationForm.jsx
=> fix event definition enable state for filter & aggregation

graylog2-web-interface/src/views/components/sidebar/NavItem.tsx, graylog2-web-interface/src/views/components/sidebar/Sidebar.test.tsx, graylog2-web-interface/src/views/components/sidebar/SidebarNavigation.tsx, graylog2-web-interface/src/views/components/sidebar/redo/RedoNavItem.tsx, graylog2-web-interface/src/views/components/sidebar/undo/UndoNavItem.tsx
With this PR we are improving the sidebar navigation titles.
/nocl
=> Improve sidebar navigation titles.
