- graylog2-server/src/main/java/org/graylog/scheduler/JobSchedulerService.java
- graylog2-server/src/main/java/org/graylog2/plugin/ServerStatus.java
This change adds an interruptible implementation to wait for the server
reaching the RUNNING state. The new method is then used in the
JobSchedulerService. Upon shutdown, the execution thread of the
JobSchedulerService is interrupted so that the service can
properly terminate.
The JobSchedulerService blocks in its run method until the server
reaches the running state. It cannot be unblocked even when interrupting
the execution thread. So if one of the other services fails during
startup, the service manager is unable to shutdown the
JobSchedulerService.
Fixes #8742 
Manually tested with the following steps:
1. Make the `JerseyService` fail on startup by setting the following `graylog.conf`:
```
http_bind_address = 255.255.255.255:9999
```
2. Start the Graylog server. Without the fix, the …
> Unblock JobSchedulerService on shutdown

- graylog2-web-interface/src/components/users/UserDetails/UserDetails.jsx
- graylog2-web-interface/src/components/users/UserEdit/SettingsSection.jsx
- graylog2-web-interface/src/components/users/UserEdit/SettingsSection.test.jsx
- graylog2-web-interface/src/components/users/UserEdit/UserEdit.jsx
Prior to this change, the user was not able to change his own timezone
settings since they were hidden to him.
This change will show the settings to the user so he can edit them.
Fixes #9813
> Show timezone setting to the user

- graylog2-server/src/main/java/org/graylog2/plugin/PluginModule.java
This let plugins decide which extensions to register when the Graylog configuration is not yet available. See https://github.com/Graylog2/graylog-plugin-integrations/pull/657#issuecomment-736662717 for more information.
Refs https://github.com/Graylog2/graylog-plugin-cloud/issues/619
> Add isCloud helper method on plugin module

- pom.xml
Add common Okta version to parent POM so that the same version can be used across all plugins.
Initially, this will be used to solve a version conflict between the Enterprise Integrations and Cloud plugin usages of the Okta SDK.
This change has no affect on functionality until it is subsequently used within plugins.
> Add common Okta version to parent POM

- graylog2-server/src/main/java/org/graylog/events/contentpack/entities/EmailEventNotificationConfigEntity.java
- graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailEventNotificationConfig.java
- graylog2-server/src/main/java/org/graylog/events/notifications/types/EmailSender.java
- graylog2-server/src/test/java/org/graylog/events/notifications/NotificationDtoTest.java
- graylog2-server/src/test/resources/org/graylog/events/contentpack/facade/NotificationFacadeTest.json
- graylog2-web-interface/src/components/event-notifications/event-notification-details/EmailNotificationDetails.jsx
- graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationForm.jsx
- graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationSummary.jsx
Added a new html body field in email notification form so users can send html emails. 
- If html body is set the emails will be multi-part emails with both plaintext and html parts (if plaintext body is left empty it will use default template). 
- If only plaintext body is set, it will behave like before (only plaintext email)
- If both are empty a form validation error will appear to at least fill one of them.
Implements #4569 
I configured an event definition and a new email notification with html body and forced the event to trigger
> Add HTML emails compatibility for alerts notifications

- graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/HeatmapVisualizationConfigDTO.java
- graylog2-web-interface/src/views/bindings.tsx
- graylog2-web-interface/src/views/components/aggregationbuilder/HeatmapVisualizationConfiguration.tsx
- graylog2-web-interface/src/views/components/visualizations/ChartData.ts
- graylog2-web-interface/src/views/components/visualizations/heatmap/HeatmapVisualization.tsx
- graylog2-web-interface/src/views/components/visualizations/heatmap/__tests__/HeatmapVisualization.test.tsx
- graylog2-web-interface/src/views/logic/aggregationbuilder/AggregationWidgetConfig.ts
- graylog2-web-interface/src/views/logic/aggregationbuilder/visualizations/HeatmapVisualizationConfig.ts
Plotly provides a list of predefined colorscales for its Heatmap. Instead of hard coding a single color scale
we should provide that list to the use so he can use a colorscale matching to his data.
Also it is often useful to define the range of the scale. For example if we have 100 data points in the range from 1 to 10
and 2 data points in the range 60 to 70, the range of the colorscale is defined from 1 to 70. The 100 data points are now invisible.
If the user now selects the data range from 1 to 11 the 2 data point 2 with 60 and 70 will now still look out but the rest is more
readable.
- Add a select where we list the colorscales poltly accepts
- Add a Min and Max field so the user can enter the range of the scale
- Add Autoscale which enables of disables the Min, Max fields
- Add a …
> Use plotlys colorscales for Heatmap Aggregation

- graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.test.tsx
- graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.tsx
Prior to this change, we did not save the state
of the focused widget in the url.
This change will sync the focused widget id with the
url so a user can copy and past the state to another
user.
1. Focus a widget
2. Copy url
3. open a new tab 
4. paste url
Fixes #9728
> Save focused widget id in url

- graylog2-web-interface/yarn.lock
Provides a fix for the following security issue: https://github.com/advisories/GHSA-3329-pjwv-fjpg
Backport of #9857 for 4.0
> Bump urijs to 1.19.5 in 4.0

- graylog2-web-interface/src/components/content-packs/ContentPacksList.jsx
The `PageSizeSelect` component passes an event as argument to its `onChange` function but but we were expecting a string containing a number. This change fixes that by extracting the value from the received event.
Fixes #9629
> Fix page size change selector in Content Pack list

- graylog2-web-interface/src/components/navigation/SystemMenu.jsx
- graylog2-web-interface/src/components/navigation/SystemMenu.test.tsx
The current permission requirement in systems menu does not reflect the sidecars permissions.
At the moment for users to see the sidecars menu item in the systems menu, you'd need to have `inputs:edit`. `sidecars:read` would be plenty enough to see this menu item.
As mentioned in #7474 a user with sidecar related permission should be able to see the sidecar menu item.
After a brief discussion with @mpfz0r we decided that changing the permission to `sidecars:read` would be good.
By creating a user with `sidecars:read` as a permission and logging in with that account.
> Change permission for sidecars in systems menu

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackend.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendErrorHandlingTest.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendGeneratedRequestTestBase.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendQueryStringDecoratorsTest.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendTest.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendUsingCorrectIndicesTest.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/QueryPlanTest.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackend.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendErrorHandlingTest.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendGeneratedRequestTestBase.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendQueryStringDecoratorsTest.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendTest.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendUsingCorrectIndicesTest.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/QueryPlanTest.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/QueryStringParser.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/QueryBackend.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/QueryEngine.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/QueryParser.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/QueryStringParserTest.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/engine/QueryParserTest.java
**Note:** This PR needs to be backported to `3.3` and `4.0`.
Before this change, a user could write or generate a query string that contains two `$` characters in unrelated places (e.g. because a field name or value contains it), leading to an undeclared parameter being incorrectly identified. An example for this is a query string of
```
foo:bar$ AND some:$value
```
This PR is fixing the regex used to identify parameters in query strings. The regex is now checking for two `$` enclosing a group of alphanumerical (`a-z`, `A-Z`, `0-9` & `_`) characters instead of a group of _any_ characters. This also matches the description in the frontend, which was already showing this specification although it was not enforced like this in the backend.
This PR (for `master`) also includes a refactoring …
> Fix pattern used to identify parameters in search/dashboard query strings.

- graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/QueryStringParser.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/QueryStringParserTest.java
Before this change, a user could write or generate a query string that contains two `$` characters in unrelated places (e.g. because a field name or value contains it), leading to an undeclared parameter being incorrectly identified. An example for this is a query string of
```
foo:bar$ AND some:$value
```
This PR is fixing the regex used to identify parameters in query strings. The regex is now checking for two `$` enclosing a group of alphanumerical (`a-z`, `A-Z`, `0-9` & `_`) characters instead of a group of _any_ characters. This also matches the description in the frontend, which was already showing this specification although it was not enforced like this in the backend.
Fixes #9497.
> Fix pattern used to identify parameters in search/dashboard query strings. (3.3)

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackend.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendErrorHandlingTest.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendGeneratedRequestTestBase.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendQueryStringDecoratorsTest.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendTest.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendUsingCorrectIndicesTest.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/QueryPlanTest.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackend.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendErrorHandlingTest.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendGeneratedRequestTestBase.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendQueryStringDecoratorsTest.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendTest.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendUsingCorrectIndicesTest.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/QueryPlanTest.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/QueryStringParser.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/QueryBackend.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/QueryEngine.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/QueryParser.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/QueryStringParserTest.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/engine/QueryParserTest.java
**Note:** This PR is the backport to  `4.0`.
Before this change, a user could write or generate a query string that contains two `$` characters in unrelated places (e.g. because a field name or value contains it), leading to an undeclared parameter being incorrectly identified. An example for this is a query string of
```
foo:bar$ AND some:$value
```
This PR is fixing the regex used to identify parameters in query strings. The regex is now checking for two `$` enclosing a group of alphanumerical (`a-z`, `A-Z`, `0-9` & `_`) characters instead of a group of _any_ characters. This also matches the description in the frontend, which was already showing this specification although it was not enforced like this in the backend.
This PR (for `master`) also includes a refactoring that extracts a …
> Fix pattern used to identify parameters in search/dashboard query strings

- graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.test.tsx
- graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.tsx
Prior to this change, when the URL contained a widget id which was not
part of the current widget set an error occured.
This change will check if the widget id of the URL belongs to an
existing widget before setting the focusedWidget.
- Open Search
- Focus widget and change id in the URL
- Reload page
Fixes #9881
> Do not set invalid widget id as a focused widget

- pom.xml
Backporting https://github.com/Graylog2/graylog2-server/pull/9900 to cloud-4.0 branch. 
This release contains a few Docker fixes which might help with the problems we see on our CI infrastructure.
See: https://github.com/testcontainers/testcontainers-java/releases/tag/1.15.1
> Update to testcontainers 1.15.1

- graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/QueryBackend.java
- graylog2-server/src/main/java/org/graylog2/plugin/indexer/searches/timeranges/RelativeRange.java
This change is implementing functionality to support an alternative way to use relative time ranges. Instead of a `range` property that defines the length of the range in seconds going backwards from now, it allows defining `from` and `to` properties defining the endpoints of a range in relation to `now`. This allows e.g. defining a range that goes from 5 minutes ago to 1 minute ago by specifying a relative range as:
```
{
"type": "relative",
"from": 300,
"to": 60
}
```
Fixes #9898.
> Supporting `from` and `to` properties in relative time ranges.

- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/MessagesResource.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/MessagesResourceTest.java
Prior to this change, if a user had read access to a dashboard via role
or direct permission the csv export failed for this dashboard, since the
permission test was testing on 'VIEW' where the role and permission had 'DASHBOARD'.
This change will use a new funtion introduced just for this case.
- Create a dashboard containing a message table
- Assign dashboard to a role with read permission
- Assign role to a reader user
- Login as reader user and export the table as CSV
> Fix csv export for shared dashboards.

- graylog2-server/src/main/java/org/graylog2/indexer/cluster/jest/GraylogJestRetryHandler.java
- graylog2-server/src/test/java/org/graylog2/indexer/cluster/jest/GraylogJestRetryHandlerTest.java
Before this change, the retry strategy used for ES requests did not retry for instances of `SocketTimeoutException`, raised in case of read timeouts. This resulted in exceptions being raised when individual nodes were not responding and node discovery was not used. This was e.g. being noticable when performing searches and 1 of 3 nodes was failing, so every 3rd search request was timing out and returning an error instead of being retried and successful and just taking longer.
This change is adding this class to the exceptions being retried, so any request that goes out to a node which is not responding on time is retried.
> Retry read timeouts for Elasticsearch. (3.3)

- graylog2-web-interface/src/components/content-packs/ContentPacksList.jsx
This is a backport of https://github.com/Graylog2/graylog2-server/pull/9875 for 4.0.
The `PageSizeSelect` component passes an event as argument to its `onChange` function but but we were expecting a string containing a number. This change fixes that by extracting the value from the received event.
Refs #9629
> Fix page size change selector in Content Pack list (4.0)

- graylog2-web-interface/src/components/pipelines/Pipeline.jsx
- graylog2-web-interface/src/components/pipelines/Stage.jsx
- graylog2-web-interface/src/components/pipelines/StageForm.jsx
Check if selected stage number already exists in pipeline, displaying an error in that case and not allowing to submit the form. This will prevent users of accidentally overriding one of their existing stages.
Additionally improve the initial suggestion for new stages. Before we always displayed `0` when creating a stage, now we base that value in the existing stages for the pipeline.
Fixes #6806
Backport of #9911 for 4.0
> Do not allow selecting same pipeline stage twice

- graylog2-server/src/main/java/org/graylog2/indexer/Constants.java
- graylog2-server/src/main/java/org/graylog2/indexer/ConstantsES7.java
- graylog2-server/src/main/java/org/graylog2/indexer/EventsIndexMapping.java
- graylog2-server/src/main/java/org/graylog2/indexer/GIMMapping.java
- graylog2-server/src/main/java/org/graylog2/indexer/GIMMapping6.java
- graylog2-server/src/main/java/org/graylog2/indexer/GIMMapping7.java
- graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java
- graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping7.java
- graylog2-server/src/main/java/org/graylog2/plugin/Tools.java
- graylog2-server/src/main/java/org/graylog2/plugin/utilities/date/NaturalDateParser.java
- graylog2-server/src/test/java/org/graylog2/indexer/EventsIndexMappingTest.java
- graylog2-server/src/test/resources/org/graylog2/indexer/expected_gim_template6.json
- graylog2-server/src/test/resources/org/graylog2/indexer/expected_gim_template7.json
- graylog2-server/src/test/resources/org/graylog2/indexer/expected_template5.json
- graylog2-server/src/test/resources/org/graylog2/indexer/expected_template6.json
- graylog2-server/src/test/resources/org/graylog2/indexer/expected_template7.json
**Note: This should be backported to `4.0`.**
Before this change, the pre-ES7 date format specifiers were reused for ES7 to define the format of date fields in index mapping templates.
Unfortunately, this results in warnings being returned in responses to searches operating on date fields, due to a [breaking change introduced in ES7](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#_joda_based_date_formatters_are_replaced_with_java_ones).
This change is now splitting up the date format specifiers and uses joda syntax for ES6 and `java.time` syntax for ES7. In addition, the overly lax exposition of the date format specifiers from the `Tools` class was locked down to prevent them leaking into new places.
**Question:** When this change is used in …
> Fix date format specifiers in index mapping templates.

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/jest/GraylogJestRetryHandler.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/jest/GraylogJestRetryHandlerTest.java
**Note:** This is a backport of #9852 to `4.0`.
Before this change, the retry strategy used for ES requests did not retry for instances of `SocketTimeoutException`, raised in case of read timeouts. This resulted in exceptions being raised when individual nodes were not responding and node discovery was not used. This was e.g. being noticable when performing searches and 1 of 3 nodes was failing, so every 3rd search request was timing out and returning an error instead of being retried and successful and just taking longer.
This change is adding this class to the exceptions being retried, so any request that goes out to a node which is not responding on time is retried.
> Retry read timeouts for Elasticsearch. (4.0)

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/jest/GraylogJestRetryHandler.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/jest/GraylogJestRetryHandlerTest.java
Before this change, the retry strategy used for ES requests did not retry for instances of `SocketTimeoutException`, raised in case of read timeouts. This resulted in exceptions being raised when individual nodes were not responding and node discovery was not used. This was e.g. being noticable when performing searches and 1 of 3 nodes was failing, so every 3rd search request was timing out and returning an error instead of being retried and successful and just taking longer.
This change is adding this class to the exceptions being retried, so any request that goes out to a node which is not responding on time is retried.
> Retry read timeouts for Elasticsearch.

- graylog2-server/src/main/java/org/graylog2/indexer/Constants.java
- graylog2-server/src/main/java/org/graylog2/indexer/ConstantsES7.java
- graylog2-server/src/main/java/org/graylog2/indexer/EventsIndexMapping.java
- graylog2-server/src/main/java/org/graylog2/indexer/GIMMapping.java
- graylog2-server/src/main/java/org/graylog2/indexer/GIMMapping6.java
- graylog2-server/src/main/java/org/graylog2/indexer/GIMMapping7.java
- graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping.java
- graylog2-server/src/main/java/org/graylog2/indexer/IndexMapping7.java
- graylog2-server/src/main/java/org/graylog2/plugin/Tools.java
- graylog2-server/src/main/java/org/graylog2/plugin/utilities/date/NaturalDateParser.java
- graylog2-server/src/test/java/org/graylog2/indexer/EventsIndexMappingTest.java
- graylog2-server/src/test/resources/org/graylog2/indexer/expected_gim_template6.json
- graylog2-server/src/test/resources/org/graylog2/indexer/expected_gim_template7.json
- graylog2-server/src/test/resources/org/graylog2/indexer/expected_template5.json
- graylog2-server/src/test/resources/org/graylog2/indexer/expected_template6.json
- graylog2-server/src/test/resources/org/graylog2/indexer/expected_template7.json
**Note: This is a backport of #9873 to `4.0`**
Before this change, the pre-ES7 date format specifiers were reused for ES7 to define the format of date fields in index mapping templates.
Unfortunately, this results in warnings being returned in responses to searches operating on date fields, due to a [breaking change introduced in ES7](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-7.0.html#_joda_based_date_formatters_are_replaced_with_java_ones).
This change is now splitting up the date format specifiers and uses joda syntax for ES6 and `java.time` syntax for ES7. In addition, the overly lax exposition of the date format specifiers from the `Tools` class was locked down to prevent them leaking into new places.
**Question:** When this change is used in …
> Fix date format specifiers in index mapping templates. (4.0)

- graylog2-web-interface/src/views/components/searchbar/date-time-picker/TabKeywordTimeRange.tsx
- graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx
Disable `Apply` button until keyword is fully parsed
Fix issue where blank keyword was being sent to API
> DateTimePicker: Validate Keyword

- graylog2-web-interface/src/components/common/SourceCodeEditor.jsx
- graylog2-web-interface/src/components/sidecars/configuration-forms/CollectorForm.jsx
- graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.jsx
When editing pipeline rules, the default value of the `<SourceCodeEditor />` component overwrote the value set in the editor by the context.
This PR fixes that issue.
Fixes #9250
Fixes #9252
Bug fixing
Tested in Chrome and Firefox
> Fix SourceCode editor combined with pipeline rules

- graylog2-web-interface/src/components/streamrules/StreamRuleForm.tsx
**Please note: This PR needs a backport for 4.0**
Before this change we were mutating the `StreamRuleForm` state on input changes directly which resulted in a strange behaviour.
One result was that the `StreamRuleForm` did not reset after creating a stream rule, even though the component is unmounting correctly.
Fixes #9956.
> Fixing stream rule form state update on input change.

- graylog2-server/src/main/java/org/graylog2/plugin/indexer/searches/timeranges/RelativeRange.java
- graylog2-server/src/test/java/org/graylog2/plugin/indexer/searches/timeranges/RelativeRangeTest.java
Recently, support for specifying relative `from`/`to` values for the relative range was implemented. This PR allows to omit the `to` parameter, defaulting to an implicit value of `0` or `now`. This makes the relative range `from`-notation semantically identical to specifying `range`.
> Supporting specifying implicit `to` for relative range.

- graylog2-web-interface/src/components/streamrules/StreamRuleForm.jsx
_This is a backport of https://github.com/Graylog2/graylog2-server/pull/9968 for 4.0_
Before this change we were mutating the `StreamRuleForm` state on input changes directly which resulted in a strange behaviour.
One result was that the `StreamRuleForm` did not reset after creating a stream rule, even though the component is unmounting correctly.
> Fixing stream rule form state update on input change (4.0).

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/MessagesAdapterES6.java
- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/jest/JestUtils.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/testing/ClientES6.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ParsedElasticsearchException.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/ParsedElasticsearchExceptionTest.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ClientES7.java
- graylog2-server/src/main/java/org/graylog2/indexer/ElasticsearchException.java
- graylog2-server/src/main/java/org/graylog2/indexer/IndexNotFoundException.java
- graylog2-server/src/main/java/org/graylog2/indexer/InvalidWriteTargetException.java
- graylog2-server/src/main/java/org/graylog2/indexer/messages/InvalidWriteTargetException.java
- graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
- graylog2-server/src/test/java/org/graylog/testing/elasticsearch/Client.java
- graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesIT.java
Prior to this PR, if one of the write targets in a bulk indexing request is an alias with zero or multiple targets, indexing failed and messages were silently dropped. This results in an error type being returned from ES different to the ones we handled before. Before this we had:
- requests failing completely: due to general errors (e.g. networking errors), indicated by an `IOException` being thrown and no response being returned
- requests failing partially (one or all individual bulk items failing): due to specific errors (e.g. mapping errors), with no exception being thrown and returning a response which contains error states for individual bulk items
In this case, we have a different scenario which also differs between the ES version involved:
- for ES6, no exception is being thrown, …
> Retrying bulk indexing if target alias has invalid target(s).

- graylog2-web-interface/src/components/common/SourceCodeEditor.jsx
- graylog2-web-interface/src/components/sidecars/configuration-forms/CollectorForm.jsx
- graylog2-web-interface/src/components/sidecars/configuration-forms/ConfigurationForm.jsx
**Note:** This is a backport of #9929 to `4.0`.
When editing pipeline rules, the default value of the `<SourceCodeEditor />` component overwrote the value set in the editor by the context.
This PR fixes that issue.
Fixes #9250
Fixes #9252
> Fix SourceCode editor combined with pipeline rules (4.0)

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/MessagesAdapterES6.java
- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/jest/JestUtils.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/testing/ClientES6.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ParsedElasticsearchException.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/ParsedElasticsearchExceptionTest.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ClientES7.java
- graylog2-server/src/main/java/org/graylog2/indexer/ElasticsearchException.java
- graylog2-server/src/main/java/org/graylog2/indexer/IndexNotFoundException.java
- graylog2-server/src/main/java/org/graylog2/indexer/InvalidWriteTargetException.java
- graylog2-server/src/main/java/org/graylog2/indexer/messages/InvalidWriteTargetException.java
- graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
- graylog2-server/src/test/java/org/graylog/testing/elasticsearch/Client.java
- graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesIT.java
**Note:** This is a backport of #9971 to `4.0`.
Prior to this PR, if one of the write targets in a bulk indexing request is an alias with zero or multiple targets, indexing failed and messages were silently dropped. This results in an error type being returned from ES different to the ones we handled before. Before this we had:
- requests failing completely: due to general errors (e.g. networking errors), indicated by an `IOException` being thrown and no response being returned
- requests failing partially (one or all individual bulk items failing): due to specific errors (e.g. mapping errors), with no exception being thrown and returning a response which contains error states for individual bulk items
In this case, we have a different scenario which also differs between the ES version …
> Retrying bulk indexing if target alias has invalid target(s). (4.0)

- graylog2-web-interface/src/views/components/DashboardSearchBar.test.tsx
This PR adds two basic tests for the `DashboardSearchBar` component.
We already have similar tests for the `SearchBar` component and should test the related functionality for the `DashboardSearchBar` as well.
> Adding more basic tests for `DashboardSearchBar`.

- graylog2-web-interface/src/views/logic/views/Actions.ts
Prior to this change, when loading the new dashboard containing the
previous search we used a not qualified route, which did not take the
prefix in account.
This change will use `Routes` to set the new pathname for history.push.
- Setup a nginx as described in the issue #9989
- Used the graylog without frontend devserver
- `yarn build` and restarting the backend server
- going to `http://localhost/graylog` and clicking there on `Export to Dashboard`
Fixes #9989
> Fix export to dashboard when graylog is behind a proxy

- pom.xml
Backport https://github.com/Graylog2/graylog2-server/pull/9966 to 4.0 branch.
This will configure Maven to retry deployments to oss.sonatype.org in the event of any network connectivity issues or intermittent server errors.
Sometimes the deployment to sonatype fails when we run the release job. This offers some small degree of mitigation against this, depending on the issue.
Tested this by:
- Customizing my Maven settings.xml to override the distributionManagement tag and making it use my internal Nexus instance instead of oss.sonatype.org.
- Configuring the repositories in Nexus to be read-only, so that Maven can pull artifacts but uploads will time out.
- Mapped oss.sonatype.org in my /etc/hosts file to 127.0.0.1 (just in case).
> Add deployment retry.

- pom.xml
Backport https://github.com/Graylog2/graylog2-server/pull/9966 to 3.3 branch.
This will configure Maven to retry deployments to oss.sonatype.org in the event of any network connectivity issues or intermittent server errors.
Sometimes the deployment to sonatype fails when we run the release job. This offers some small degree of mitigation against this, depending on the issue.
Tested this by:
- Customizing my Maven settings.xml to override the distributionManagement tag and making it use my internal Nexus instance instead of oss.sonatype.org.
- Configuring the repositories in Nexus to be read-only, so that Maven can pull artifacts but uploads will time out.
- Mapped oss.sonatype.org in my /etc/hosts file to 127.0.0.1 (just in case).
> Retry failed deployments to sonatype.org. (#9966)

- graylog2-web-interface/src/components/common/Select.test.jsx
- graylog2-web-interface/src/components/common/Select.tsx
Prior to this change, the value part of options passed to the `Select` component must be strings. For non-numeric strings, upon selecting an option an exception was thrown due to `.split()` being called on something that does not implement it.
This PR is fixing this, by testing if the selected value is a string or not, avoiding `split` in case it is not.
> Allow non-string options in Select component.

- graylog2-web-interface/packages/eslint-config-graylog/index.js
During the centralisation of the jest config module (#9548), we removed the `--ext` parameter to eslint in our yarn script definitions.  Unfortunately, this makes eslint to lint `.js`, `.ts` & `.tsx` files only, due to eslint using `js` per default and merging it with `ts`/`tsx` from the `overrides` section of the `eslint-config-graylog` module.
In order to include `jsx` files again, this PR adds an empty `overrides` section including `js` & `jsx` explicitly to the `eslint-config-graylog` module.
> Include all file extensions in lint runs.

- graylog2-web-interface/src/components/common/CopyToClipboardCapture.tsx
- graylog2-web-interface/src/components/common/index.tsx
This PR adds a component called `CopyToClipboardCapture` which allows to format content on copy before it gets stored in the clipboard. The component receives a function (`formatSelection`) which gets called every time the user copies encapsulated content (`children`).
We need this functionality for the following case. When a grid is styled with `display: flex;` or `display: grid;` and a user copies a row, each cell is being separated by a line break. With this component we are able to remove the line breaks when necessary.
> Creating common component `CopyToClipboardCapture` which allows to format content on copy

- graylog2-web-interface/src/components/common/Spinner.tsx
This PR reimplements the gap between the text and icon of the loading spinner. It is now defined by a margin instead of the space character.
Before:
the loading spinner
After:
> Fixing gap between loading spinner icon and text

- graylog2-web-interface/webpack.config.js
This will address the issue raised by @kyleknighted in #10023
Like before, some modules where being imported with generated classnames in develop target. I disabled it here and it solved the issue.
@dennisoelkers I am not totally sure why the options were different for develop, but maybe you know more about this and how this solution might be wrong.
Fixes #10023
CSS modules were imported incorrectly and got generated classnames
By looking up the DatePicker and fixing the imported CSS classes.
> Import CSS modules as global to prevent rewriting classnames

- graylog2-web-interface/packages/eslint-config-graylog/index.js
While the ESLint rule `jest/expect-expect` is generally useful, it falls short in a couple of cases:
- Using `testing-library`'s `find*` (e.g. `findByText`) functions to wait for the appearance of a qualifying element, which is an assertion in it self
- Bundling `expect` calls in a custom `expectFoo` function
Both cases do not satisfy the rule. This is changed through this PR,which adds `expect*` as well as `findBy*` to the list of accepted function names.
> Improving ESLint rule `jest/expect-expect`.

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndicesAdapterES6.java
- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/jest/JestUtils.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java
- graylog2-server/src/main/java/org/graylog2/indexer/MongoIndexSet.java
- graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java
- graylog2-server/src/main/java/org/graylog2/indexer/indices/IndicesAdapter.java
- graylog2-server/src/main/java/org/graylog2/indexer/ranges/MongoIndexRangeService.java
- graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
- graylog2-server/src/test/java/org/graylog2/indexer/ranges/MongoIndexRangeServiceTest.java
When one or more ES nodes are in flood stage, cycling the deflector fails due to not being able to create a new index and toggling the deflector alias. During this step, the code waits for a new index to be created and healthy. Unfortunately, the `waitForRecovery` method used internally does not deal properly with indices being red. The response we are receiving when querying the health of a red index is set to unsuccessful, triggering our abstracted error handling mechanism which is throwing an exception instead of passing through the `red` health state.
This change is now using a different, less safe way of executing the health query request and returning the response as is. This allows waiting for recovery on red indices and timing out instead of throwing an exception.
> Fix waiting for recovery for red indices.

- graylog2-web-interface/packages/eslint-config-graylog/index.js
Before this change, jest plugin for ESLint accepted only stand-alone calls to `findBy*` as expectations. This change makes it accept calls to `screen.findBy*` and `(screen.)findAllBy*` as well, therefore not raising the `expect-expect` hint.
> ESLint: Support `screen.findBy*` as expectation in tests.

- graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
This shouldn't have been released and can cause a
high load on MongoDB.
Fixes #10043
> Remove development grants migration

- graylog2-server/src/main/java/org/graylog/security/DBGrantService.java
This shouldn't have been released and can cause a
high load on MongoDB.
Fixes #10043
(cherry picked from commit 40fbb82d47f3df0924a2e5a5c320ff4447e46b00)
> Remove development grants migration (#10044)

- pom.xml
Note that siv-mode 1.4.0+ offers significant performance improvements, reducing CPU load during encryption/decryption
Increased dependency version
I'm the maintainer behind siv-mode and am convinced that you want this change. Since this is a server product, [reducing CPU load](https://github.com/cryptomator/siv-mode/issues/15) during complex computations should be in your interest.
Furthermore a cryptographic primitive got replaced by a JCE-provided version. This simplifies security audits.
API didn't change and upstream project has high test coverage.
> Bumped siv-mode to 1.4.1

- graylog2-web-interface/src/components/common/ColorPicker.jsx
- graylog2-web-interface/src/views/components/visualizations/ChartColorContext.ts
- graylog2-web-interface/src/views/components/visualizations/ColorMapper.ts
- graylog2-web-interface/src/views/components/visualizations/Colors.ts
- graylog2-web-interface/src/views/components/visualizations/GenericPlot.tsx
- graylog2-web-interface/src/views/components/visualizations/PlotLegend.test.tsx
- graylog2-web-interface/src/views/components/visualizations/PlotLegend.tsx
- graylog2-web-interface/src/views/components/visualizations/XYPlot.tsx
- graylog2-web-interface/src/views/components/visualizations/__tests__/GenericPlot.test.tsx
- graylog2-web-interface/src/views/components/visualizations/__tests__/XYPlot.test.tsx
- graylog2-web-interface/src/views/components/visualizations/area/AreaVisualization.tsx
- graylog2-web-interface/src/views/components/visualizations/bar/BarVisualization.tsx
- graylog2-web-interface/src/views/components/visualizations/line/LineVisualization.tsx
- graylog2-web-interface/src/views/components/visualizations/pie/PieVisualization.tsx
- graylog2-web-interface/src/views/components/widgets/MeasureDimensions.tsx
- graylog2-web-interface/src/views/components/widgets/WidgetColorContext.test.tsx
- graylog2-web-interface/src/views/components/widgets/WidgetColorContext.tsx
The user wants to be able to change the query not only from the query bar and message list, but also from a aggregation widget.
For that the legend which is displaying the fields values is a good starting point.
- Create our own custom plot legend so we can handle the onClick event for color hint and the value separably
- To provide the colors for the charts we introduce a ColorMapper which will take care of the default colors and saved colors 
Fixes #6612 
Fixes #7207 by keeping track of field to color map thoughout the session
> Custom chart legend

- graylog2-web-interface/package.json
- graylog2-web-interface/packages/jest-preset-graylog/jest-preset.js
- graylog2-web-interface/test/configure-testing-library.js
Before this change, we were using default timeouts for frontend tests. These are:
- 5s for each jest test
- 1s for async wait utils in testing-library
On lower-end machines (e.g. github actions), these timeouts are sometimes too aggressive. Instead of raising timeouts in general, we want to raise timeouts only for specific environments.
Therefore, this PR allows passing a `TIMEOUT_MULTIPLIER` environment variable to the `yarn test` run. It is being parsed as a number (either int or float) and applied to the defaults.
E.g. `TIMEOUT_MULTIPLIER=2 yarn test` results in:
- 10s for each jest test
- 2s for async wait utils in testing-library
It also works the other way, `TIMEOUT_MULTIPLIER=0.5 yarn test` results in:
- 2.5s for each jest test
- 0.5s for async wait utils in testing-library …
> Allow passing timeout multiplier for frontend tests.

- graylog2-web-interface/src/components/common/Timestamp.jsx
- graylog2-web-interface/src/views/components/TypeSpecificValue.tsx
- graylog2-web-interface/src/views/components/Value.test.jsx
- graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.tsx
- graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRule.tsx
Prior this PR we did not support highlighting for Timestamps and booleans.
- Use `render` component for booleans in Typespecific value so the highlighting will be used.
- Same for timestamps, but here we need to pass the render function to the Timestamp component
- For timestamps we need to take care of the highlighting length since the compared string is shorter then
the rendered timestamp.
- Highlight a timestamp
- Highlight a boolean
- Ensure they are not treated as numbers
Fixes #9835 
#9634 needs to be merged first and then this PR needs a rebase!
> Add support for Highlighting for Timestamps and Booleans

- graylog2-web-interface/src/views/actions/SearchActions.ts
- graylog2-web-interface/src/views/components/widgets/MessageList.tsx
- graylog2-web-interface/src/views/logic/search/GlobalOverride.ts
- graylog2-web-interface/src/views/stores/SearchStore.ts
The type definition for the search type options in `GlobalOverride` currently only consider properties for a paginated list.
`{ limit: number, offset: number }`
This PR is adds a type definition for a scroll parameter.
`{ after: [any] }`
We need this new type definition for a search type which uses a scroll position instead of pagination to receive the messages for a specific position in a list.
> Defining generic type definition for `GlobalOverride` search type options.

- .github/workflows/build.yml
This test is making use of #10058 to double the test timeouts used for
jest/testing-library on Github Actions.
> Doubling test timeouts for github build.

- graylog2-server/src/main/java/org/graylog/plugins/views/search/views/formatting/highlighting/GradientColor.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/views/formatting/highlighting/HighlightingColor.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/views/formatting/highlighting/HighlightingRule.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/views/formatting/highlighting/LegacyColorDeserializer.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/views/formatting/highlighting/StaticColor.java
- graylog2-web-interface/package.json
- graylog2-web-interface/src/components/bootstrap/InputWrapper.jsx
- graylog2-web-interface/src/theme/utils/contrastingColor.ts
- graylog2-web-interface/src/views/Constants.ts
- graylog2-web-interface/src/views/components/contexts/HighlightingRulesProvider.test.tsx
- graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.test.tsx
- graylog2-web-interface/src/views/components/messagelist/Highlight.tsx
- graylog2-web-interface/src/views/components/messagelist/PossiblyHighlight.tsx
- graylog2-web-interface/src/views/components/sidebar/highlighting/ColorPreview.tsx
- graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightForm.test.tsx
- graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightForm.tsx
- graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingColorForm.test.tsx
- graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingColorForm.tsx
- graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRule.test.tsx
- graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRule.tsx
- graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRules.test.tsx
- graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightingRules.tsx
- graylog2-web-interface/src/views/components/sidebar/highlighting/Scale.ts
- graylog2-web-interface/src/views/logic/aggregationbuilder/WidgetFormattingSettings.ts
- graylog2-web-interface/src/views/logic/views/formatting/highlighting/HighlightingColor.ts
- graylog2-web-interface/src/views/logic/views/formatting/highlighting/HighlightingRule.ts
- graylog2-web-interface/src/views/stores/HighlightingRulesStore.ts
- graylog2-web-interface/yarn.lock
This change is making the color for a value highlighting configurable.  It allows the user to choose between a static color (for all field types) or a gradient (for numeric fields). If the gradient option is selected, it requires the user to select a gradient and defined upper/lower bounds for the field values (as we cannot infer them at this point). It offers the same gradients we do offer for the heatmap visualization.
The change does not require a migration for existing highlights. If a highlight color contains a string, it will be converted into a `StaticColor` silently.
**Notes:**
- This PR includes previously missing types for `chroma-js` and fixes one related error
- This PR includes `@testing-library/user-event` to make testing easier
> Adding static/gradient color options to value highlighting.

- graylog2-web-interface/src/components/common/IconButton.tsx
- graylog2-web-interface/src/views/components/sidebar/ContentColumn.tsx
- graylog2-web-interface/src/views/components/sidebar/Sidebar.tsx
- graylog2-web-interface/src/views/components/widgets/__snapshots__/Widget.test.tsx.snap
Prior to this change, we handled the z-index for the sidebar in way that
it was hard to add new z-index for widgets.
Also we could not disable a icon button.
This change raise the z-index for the sidebar so widget have a little
space for their own z-index without jumping out of the overlay.
Add IconButton disable prop.
> Adjustments for enterprise widget

- graylog2-server/src/main/java/org/graylog2/security/MongoDbSession.java
- graylog2-server/src/test/java/org/graylog2/security/MongoDbSessionTest.java
A Shiro subject may have multiple principals, with the first principal being the "primary principal" and in our case that's the user ID.
This changes checks if we have multiple principals in a session and returns the first principal when looking up a user ID.
Once merged, we should forward-port this to the `master` branch.
The principals collection may be used to transport additional attributes of a subject from the authorization service into the session. Treating the string representation of the principals collection as the user ID is wrong in this case.
Fixes Graylog2/graylog-plugin-cloud#705
> Handle multiple principals in mongoDB session

- graylog2-server/src/main/java/org/graylog2/periodical/IndexerClusterCheckerThread.java
**Note:** This is a backport of #9960 to `3.3`.
Before this change, when the flood stage for ES was reached on multiple nodes, creating a system notification raised an exception periodically, because the code tries to mutate a list in place which is in fact immutable.
This PR is now changing this behavior and creates a new list, so it can effectively deal with immutable lists as well.
> Fix disk watermark notifications for multiple hosts. (3.3)

- graylog2-web-interface/src/components/rules/RuleContext.jsx
- graylog2-web-interface/src/components/rules/RuleForm.jsx
This PR fixes #9341
The pipeline rule context and source code editor didn't play well together. In some instances the source code of pipeline rules was not loaded into the source code editor.
Because of the nature of how the context and source code editor were implemented it sometimes didn't work correctly.
It problem lies in the way the rule values are set on the source code editor. After debugging I came to the conclusion that the source code editor was not loaded, but the rule source had and thus wanted to update a non-existing source code editor.
This fix will trigger the context to apply the rule source on the source code editor should it load after the rule has been loaded.
I am using `useState` to get the desired effect. It's a bit weird, but it retriggers the effects inside the …
> Fix race condition pipeline

- graylog2-web-interface/package.json
- graylog2-web-interface/packages/jest-preset-graylog/package.json
- graylog2-web-interface/packages/jest-preset-graylog/src/setup-files/mock-FetchProvider.js
- graylog2-web-interface/src/stores/users/UsersStore.test.ts
- graylog2-web-interface/yarn.lock
This PR is updating jest and related packages to v26. It requires two minor changes to prevent tests from failing:
- When mocking a dependency from a setup file, it looks like the function supplied to `jest.fn` is not used. This lead to `fetch` returning `undefined` instead of a promise, leading to test failures in a couple of places. This was changed by using a plain function, not wrapped with `jest.fn`.
- The `UsersStore` relied on `fetch` being a mocked function, so `fetch` was mocked explicitly again in the test itself.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#2051
> Updating jest to v26.

- graylog2-server/src/main/java/org/graylog/plugins/views/search/filter/StreamFilter.java
- graylog2-web-interface/src/views/hooks/BindSearchParamsFromQuery.test.ts
- graylog2-web-interface/src/views/logic/queries/Query.ts
Prior to this change,  if the user focused or unfocused a widget a
search was executed, since the code assumed the streams filters changed.
This change will cleanup the filters we get from the backend (it
included title and other filters which where set to null).
Also to compare the new streams filter and the old one the need to be
from the same object type. So we enusre that the new streams filter is
also containing immutable list and not an array.
- Focus and unfocus a widget
- ensure no search gets executed
Fixes #9467
Fixes #8421
> Don't execute a search when focusing or unfocusing a widget

- graylog2-web-interface/src/theme/GlobalThemeStyles.jsx
These Changes add `:focus `color to` <a>` tag.
Okta widget form has a help link with `:focus` state with color not handled by our global style. Because of that browser style is applied instead resulting in an unreadable purple color.
Before :
After
/jenkins-pr-deps Graylog2/graylog-plugin-cloud#721
> Add link focus state color

- pom.xml
This release of testcontainers has a fix for an issue where the Ryuk container hangs forever. It could possibly help with our CI hangs. 
https://github.com/testcontainers/testcontainers-java/releases/tag/1.15.2
> Update testcontainers to 1.15.2.

- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java
- graylog2-server/src/main/java/org/graylog2/configuration/DurationCastedToIntegerValidator.java
- graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java
**Note:** This PR requires a backport to `4.0`.
Prior to this change, the force merge request which is used during the index optimization job did not supply a timeout for ES7. This leads to the default timeout (60s) being used, which is too short in most cases.
While this might not result in the force merge request being cancelled ([details](https://github.com/Graylog2/graylog2-server/issues/10054#issuecomment-778460239)), it leads to unnecessarily logging of misleading errors.
This PR is supplying the configured timeout to the request.
Fixes #10054.
> Provide a timeout for request when optimizing index in ES7.

- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java
- graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
**Note:** This PR should be backported to `4.0`.
Prior to this change, the `Indices#numberOfMessages` implementation for ES7 was using the same JSON path as in ES6, although the structure of the response has changed. This, in combination with an overly relaxed parsing of the response lead to the method always returning 0.
The consequence of this is that any configured count-based rotation policy was never triggered, due to the threshold never being crossed.
This PR is adding a test for the method, fixes the JSON path and makes sure that if the node is not found, it will raise an exception instead of returning 0.
> Fixing counting of messages in index for ES7.

- graylog2-web-interface/src/components/graylog/OverlayTrigger.tsx
- graylog2-web-interface/src/views/components/searchbar/saved-search/__snapshots__/SavedSearchControls.test.tsx.snap
Updated styles within OverlayTrigger to stop line break regression.
Added ability for `trigger` prop to function
Updated version of OverlayTrigger would cause line breaks where there should not be one.
`trigger` prop was not used other than defaultProps, so functionality was added.
> Update styling of OverlayTrigger to not break lines

- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java
- graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
**Note:** This is a backport of #10092 to `4.0`.
Prior to this change, the `Indices#numberOfMessages` implementation for ES7 was using the same JSON path as in ES6, although the structure of the response has changed. This, in combination with an overly relaxed parsing of the response lead to the method always returning 0.
The consequence of this is that any configured count-based rotation policy was never triggered, due to the threshold never being crossed.
This PR is adding a test for the method, fixes the JSON path and makes sure that if the node is not found, it will raise an exception instead of returning 0.
> Fixing counting of messages in index for ES7. (4.0)

- graylog2-web-interface/src/components/configurationforms/BooleanField.jsx
- graylog2-web-interface/src/components/configurationforms/DropdownField.jsx
- graylog2-web-interface/src/components/configurationforms/ListField.jsx
- graylog2-web-interface/src/components/configurationforms/NumberField.jsx
- graylog2-web-interface/src/components/configurationforms/TextField.jsx
Before this change, components for auto-generated configuration forms did not associate their labels and inputs correctly, setting different values for the label's `for` attribute and the input's `id`. This represents a usability issue, and also throw errors when testing these components with `react-testing-library`'s `getByLabelText` method.
This PR ensures all auto-generated labels and inputs are connected through the same id values.
Refs Graylog2/graylog-plugin-cloud#741
> Set right input IDs and references

- graylog2-web-interface/packages/graylog-web-plugin/package.json
- graylog2-web-interface/yarn.lock
In recent weeks, we have seen build instabilities for the `graylog-web-plugin` module, where the build contains an empty `lib` directory, no files from the `src` dir were transpiled, but `yarn install` succeeded.
The causes for this were:
- The `preinstall` task erroneously catching build errors (the `||` clause was meant to suppress build errors when no `src` dir is present, which should not happen anymore)
- Installing inconsistent `babel` dependencies. `@babel/preset-env` was pinned to a specific version, while others had wider version specifiers. This lead to situations where incompatible versions were installed.
To address these issues, this change is:
1.) Preventing silent build errors in `graylog-web-plugin` by improving the `preinstall` task
2.) Pinning `babel` dependencies to …
> Improve build stability of `graylog-web-plugin` module.

- graylog2-web-interface/src/views/components/DashboardSearchBar.test.tsx
- graylog2-web-interface/src/views/components/DashboardSearchBar.tsx
- graylog2-web-interface/src/views/components/SearchBar.test.tsx
- graylog2-web-interface/src/views/components/SearchBar.tsx
- graylog2-web-interface/src/views/components/WidgetQueryControls.tsx
- graylog2-web-interface/src/views/components/searchbar/TimeRangeDisplay.test.tsx
- graylog2-web-interface/src/views/components/searchbar/TimeRangeDisplay.tsx
- graylog2-web-interface/src/views/components/searchbar/TimeRangeTypeSelector.tsx
We improved the search date time picker recently. Currently a user needs to click on the blue button to open the date time picker. With this change clicking on the selected date time range (in this case "From: 5 minutes ago - Until: now") will also toggle the date time picker.
This change will make it slightly easier to open the date time picker which speeds up the process.
> Toggling date time picker when clicking on date time in search bar.

- graylog2-web-interface/src/views/components/widgets/MessageTable.tsx
The message table now has a height of 28px, which is the minimum due to the height of the sort icon buttons.
Reducing the header height provides more space for the message table rows.
> Reducing height of message table header.

- graylog2-web-interface/src/views/components/widgets/Widget.tsx
With this PR we are providing the id of the active query for each widget as a component prop.
We need to know this id for a specific widget type.
> Providing active query id for each widget on search page.

- graylog2-server/src/main/java/org/graylog/grn/GRNTypes.java
- graylog2-server/src/main/java/org/graylog/security/BuiltinCapabilities.java
- graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyPermissionChecker.java
- graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java
* Add missing GRN type for outputs
Fixes #10088
* Add output permissions to the capabilities
Without this, the dependency check doesn't run properly
because it filters out any permission that isn't handled via grants.
That's another bug we should be fixing..
* Add TODO comment
* Hide some dependencies that are not relevant for sharing entities
* Use Set instead of List for ignored dependcies lookup
(cherry picked from commit 8eec5db77ce28e8819f6ace3f8d92b28bd937883)
> Add missing GRN type for outputs (#10089)

- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java
- graylog2-server/src/main/java/org/graylog2/configuration/DurationCastedToIntegerValidator.java
- graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java
**Note:** This is a backport of #10065 to `4.0`.
Prior to this change, the force merge request which is used during the index optimization job did not supply a timeout for ES7. This leads to the default timeout (60s) being used, which is too short in most cases.
While this might not result in the force merge request being cancelled ([details](https://github.com/Graylog2/graylog2-server/issues/10054#issuecomment-778460239)), it leads to unnecessarily logging of misleading errors.
This PR is supplying the configured timeout to the request.
Fixes #10054.
> Provide a timeout for request when optimizing index in ES7. (4.0)

- graylog2-web-interface/packages/eslint-config-graylog/index.js
- graylog2-web-interface/packages/eslint-config-graylog/package.json
- graylog2-web-interface/src/components/graylog/LinkContainer.test.jsx
- graylog2-web-interface/src/views/components/aggregationbuilder/PivotConfiguration.test.jsx
- graylog2-web-interface/src/views/components/common/EditableTitle.test.jsx
- graylog2-web-interface/yarn.lock
This change is adding the required plugins and activates the presets to put proper rules for the usage of Testing-Library in place. It is using the `recommended` & `react` presets as well as the `no-debug` rule being added explicitly.
Further details for the rules:
* [Testing-Library](https://www.npmjs.com/package/eslint-plugin-testing-library#supported-rules)
> Add ESLint rules for Testing-Library.

- graylog2-web-interface/src/views/components/contexts/WidgetFocusContext.tsx
- graylog2-web-interface/src/views/components/widgets/ExtraWidgetActions.test.tsx
- graylog2-web-interface/src/views/components/widgets/ExtraWidgetActions.tsx
- graylog2-web-interface/src/views/components/widgets/Types.ts
- graylog2-web-interface/src/views/components/widgets/Widget.tsx
This PR adds functionality to support pluggable widget actions. These can be added conditionally to the action dropdown present for each widget. The key used to register widget actions is `views.widgets.actions`, the type for the actions looks like this:
```javascript
type WidgetAction = {
type: string, // arbitrary string, just used to differentiate actions (e.g. `dummy-action`)
title: (w: Widget) => string, // Generates the title
isHidden?: (w: Widget) => boolean, // Determines if the action is hidden or not (optional, defaults to `false`)
action: (w: Widget, contexts: Contexts) => unknown, // The action which is triggered upon click
};
type Contexts = {
widgetFocusContext: WidgetFocusContextType,
};
```
The actual action is called with the current widget and an extendable object …
> Support pluggable widget actions.

- graylog2-server/src/main/java/org/graylog/plugins/views/search/Search.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchExecutionGuard.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/SearchExecutionGuardTest.java
Prior to this change, the user needed additional access to `All Events`
and `All system events` to search with Event Annotation.
This change will change the streams used to check for permission.
Instead of effective streams which contains the Event Streams,
we use the streams the user has access to. We will filter with these
streams later the result of the Event Streams request.
Fixes #8260
> Allow user access to event annotation for streams he has access to

- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java
- graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
In #10065, an attempt was made to introduce timeout handling for ES7 for the force merge request performed by the index optimization job. This made things much worse, by trying to copy a `RequestConfig` instance that is `null` in this situation. This results in an NPE and is aborting the index optimization job before it can perform any action.
This change is now checking if the `RequestConfig` instance is `null` and instantiates a new one in this case instead of trying to copy it.
Fixes #10117.
> Prevent NPE in index optimization job.

- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java
- graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
**Note:** This is a backport of #10118 to `4.0`.
In #10065, an attempt was made to introduce timeout handling for ES7 for the force merge request performed by the index optimization job. This made things much worse, by trying to copy a `RequestConfig` instance that is `null` in this situation. This results in an NPE and is aborting the index optimization job before it can perform any action.
This change is now checking if the `RequestConfig` instance is `null` and instantiates a new one in this case instead of trying to copy it.
Fixes #10117.
> Prevent NPE in index optimization job. (4.0)

- graylog2-web-interface/src/components/common/Select.tsx
Fixes #7166
Right now the remove button is a custom one which overwrites the one `react-select` uses. This PR will revert to using `react-select` remove button, but keeping our CSS changes.
By measuring the distance of the icon and spacing.
> Use default remove icon for `react-select`

- distribution/pom.xml
- full-backend-tests/pom.xml
- graylog-plugin-archetype/pom.xml
- graylog-plugin-parent/graylog-plugin-web-parent/pom.xml
- graylog-plugin-parent/pom.xml
- graylog-project-parent/pom.xml
- graylog-storage-elasticsearch6/pom.xml
- graylog-storage-elasticsearch7/pom.xml
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java
- graylog2-server/pom.xml
- graylog2-server/src/main/java/org/graylog/grn/GRNTypes.java
- graylog2-server/src/main/java/org/graylog/security/BuiltinCapabilities.java
- graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyPermissionChecker.java
- graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java
- graylog2-server/src/main/java/org/graylog2/configuration/DurationCastedToIntegerValidator.java
- graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java
- graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
- graylog2-web-interface/manifests/package.json
- graylog2-web-interface/package.json
- graylog2-web-interface/packages/graylog-web-plugin/package.json
- pom.xml
Update `cloud-4.0` with the latest `4.0` changes.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#2070,Graylog2/graylog-plugin-enterprise-integrations#477,Graylog2/graylog-plugin-integrations#748,Graylog2/graylog-plugin-cloud#749
> Sync cloud 4.0

- .github/dependabot.yml
This PR is adding the required config to track dependencies for `jest-preset-graylog` in dependabot.
In addition, it replaces the usage of the `ready-for-review` label (which is generally superseded by using the `draft` status in github) with the `dependencies` label (which indicates a mere dependency change in a PR).
> Adding `jest-preset-graylog` to dependabot config.

- graylog2-web-interface/src/views/components/visualizations/PlotLegend.tsx
- graylog2-web-interface/src/views/components/visualizations/number/Trend.tsx
The report generation is using the chrome print to pdf functionallity
which will turn all backgrounds in css to white.
We add an !important to the css rule (and explain why) and add the
magical webkit rule which tells chrome to keep the background as it is.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/1997
> Fix rendering of trend color in report generation

- graylog2-web-interface/src/components/users/UsersOverview/UsersOverview.test.tsx
The `UsersOverview.test` is currently failing often because of a timeout. One reason are `OverlayTrigger` changes we merged recently. We will improve the `OverlayTrigger` in another iteration, mocking the component in the `UsersOverview.test` should help us with the tests in the short term.
> Mocking `OverlayTrigger` in `UsersOverview.test` to reduce duration of test execution.

- graylog2-web-interface/src/views/bindings.tsx
Prior to this change, all widgets had the same width in a report.
This change will give message list a broader width so it has more space
to show big messages.
> Add report styling for a widget

- graylog2-web-interface/src/components/graylog/Modal.jsx
- graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.global.lazy.css
- graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.tsx
Before this change the initial widget container `clientHeight` equaled the `scrollHeight` because the lazy loaded css defined `height: 100%` for the modal container, which is necessary for the correct `clientHeight`.
We can remove this css file because we defined `height: 100%` for the modal content by default, the styling is not required and we will adjust / restyle the related components soon.
> Fixing initial height of widget container in edit mode by removing lazy loaded css.

- graylog2-web-interface/src/views/logic/views/CopyWidgetToDashboard.Search-View.fixture.json
- graylog2-web-interface/src/views/logic/views/CopyWidgetToDashboard.ts
- graylog2-web-interface/src/views/logic/views/ViewState.ts
- graylog2-web-interface/src/views/logic/views/__snapshots__/CopyWidgetToDashboard.test.js.snap
Prior to this change, the function which copys the widget from the
search to the dashboard was missing to copy the title if a title exists.
This change will add a function which will add a possible new title of
the new widget to the dashboard.
Fixes #10003
> Copy widget title when copying widget to dashboard

- pom.xml
Finally fixed 'illegal reflective access' warnings with Java 9 or later.
https://github.com/google/guice/issues/1133
Full changelog:
https://github.com/google/guice/wiki/Guice501
> Update guice to 5.0.1

- graylog2-web-interface/src/views/components/datatable/DataTableEntry.tsx
- graylog2-web-interface/src/views/components/datatable/Headers.tsx
Prior to this change, numeric values where render just like the rest of
field types. But this makes it increasingly hard to read the values,
especially if the numbers are getting bigger. In a first step
@dennisoelkers introduced digig grouping.
This change will use monospace font for numeric values and align the
text on the right side so bigger numbers are easier to read.
- Add a aggregation with big numbers
- hava look on the numbers
Refs #7831
> Style DataTableEntries for numeric values

- graylog2-web-interface/devServer.js
- graylog2-web-interface/src/util/AppConfig.js
- graylog2-web-interface/webpack.config.js
This makes is possible to let the DEV web interface talk to a different backend server.
> Make webpack /api proxy host and port configurable

- graylog2-web-interface/package.json
- graylog2-web-interface/src/routing/loadAsync.tsx
- graylog2-web-interface/src/views/components/SearchBar.test.tsx
This PR is a minor optimization to remove the need for an external dependency like `loadable-components` and using stock React functionality instead.
The web app was build and tested in the browser while looking at the network tab to ensure that code splitting is still working.
> Replace `loadable-components` with `React.lazy`.

- graylog2-web-interface/src/components/common/ReactGridContainer.jsx
- graylog2-web-interface/src/views/components/Query.tsx
- graylog2-web-interface/src/views/components/WidgetComponent.tsx
- graylog2-web-interface/src/views/components/WidgetContainer.tsx
- graylog2-web-interface/src/views/components/WidgetGrid.jsx
- graylog2-web-interface/src/views/components/sidebar/ContentColumn.tsx
- graylog2-web-interface/src/views/components/sidebar/Sidebar.tsx
Previously on widget focus we replaced the `WidgetGrid` with the selected widget. This way the widget got unmounted and lost its state. As described in https://github.com/Graylog2/graylog2-server/issues/10099 this was a problem for e.g. the message table, which stores information like the current page in its state.
With this PR we are only changing the widget and widget grid style on widget focus. This way not only the selected widgets keeps its focus, but also all other widgets. They also do no loose e.g. their scroll position.
While working on these changes I tried out different approaches. E.g. I tried to change the widget position and the react grid layout row height, when a widget is being focused. But all these approaches were more complex and had more side effects than the current …
> Preventing widget unmount on widget focus.

- graylog2-web-interface/src/components/maps/adapter/MaxmindAdapterFieldSet.jsx
Remove the trailing parenthesis for IPInfo database types.
> Remove trailing parenthesis for IPInfo database types

- graylog2-server/src/main/java/org/graylog2/plugin/PluginModule.java
- graylog2-server/src/main/java/org/graylog2/plugin/inject/Graylog2Module.java
- graylog2-server/src/main/java/org/graylog2/shared/bindings/PluginBindings.java
- graylog2-server/src/main/java/org/graylog2/web/PluginUISettingsProvider.java
- graylog2-server/src/main/java/org/graylog2/web/resources/AppConfigResource.java
- graylog2-server/src/main/resources/web-interface/config.js.template
Some plugins have dynamic UI settings data that needs to be provided to the UI at startup time via inclusion in the generated config.js file.  This change adds a new `PluginUISettingsProvider` interface and a method for binding instances of that interface such that the data they provide will be included when the config.js file is generated at server startup.
This is a re-do of #10063 
This change has been tested locally using an in-development Enterprise plugin.
> Add support for dynamic data from UI plugins to be included in generated config.js

- graylog2-web-interface/src/views/components/ExportSettingsContext.tsx
- graylog2-web-interface/src/views/components/ExportSettingsContextProvider.tsx
- graylog2-web-interface/src/views/components/WidgetComponent.tsx
- graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportModal.test.tsx
- graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportModal.tsx
- graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportSettings.test.tsx
- graylog2-web-interface/src/views/components/searchbar/csvexport/CSVExportSettings.tsx
- graylog2-web-interface/src/views/components/searchbar/csvexport/CustomExportSettings.tsx
- graylog2-web-interface/src/views/components/searchbar/csvexport/Fixtures.ts
- graylog2-web-interface/src/views/components/searchbar/csvexport/startDownload.ts
This PR is adding functionality to support custom settings for the CSV export provided by widget-specific components, by:
- Allowing to define an `exportComponent` in a widget definition. This component is rendered in the export dialog if a widget of this definition's type is exported.
- Providing an `ExportSettingsContext` per widget which allows tracking custom export settings derived from the current widget's state. This can be used to communicate between a widget component (and/or its visualization) and the custom export settings components which are part of the export dialog.
- When the export dialog is submitted, the `customSettings` key of the form's state is merged into the export request. This allows custom export components to override parts of the export dialog.
> Support custom settings in CSV export dialog.

- graylog2-web-interface/package.json
- graylog2-web-interface/src/routing/loadAsync.tsx
- graylog2-web-interface/src/views/components/SearchBar.test.tsx
This reverts commit f8a32f0f31b95a432c621a9cff9b8e001950882a.
The previous change introduced some issues with component structure
mounting, leading to route changes unmounting and remounting the
complete component tree.
> Revert "Replace `loadable-components` with `React.lazy`. (#10138)"

- graylog2-web-interface/src/views/components/searchbar/TimeRangeInput.test.tsx
This PR is just fixing the name of the `TimeRangeInput` test.
> Fixing name of `TimeRangeInput` test.

- pom.xml
Update Netty dependency to the latest version. 
This was recently done in https://github.com/Graylog2/gelfclient/pull/52, so the same update is being done in the graylog2-server core while we're looking at this.
> Update Netty to the latest version

- graylog2-server/src/main/java/org/graylog2/periodical/ContentPackLoaderPeriodical.java
This fixes the automatic content pack installation when using the
"content_packs_auto_install" config option.
The ContentPackService#installContentPack expects a username as third
argument, not a user ID. We've been using "local:admin" which is the
local admin's pseudo user ID. UserService#load has a special case for the
local admin user but is expecting Configuration#getRootUsername to be
used and not "local:admin".
So the user service tried to find a user with name "local:admin" in the
database instead of returning the special admin user object.
That fails with:
`Caused by: java.lang.IllegalStateException: Cannot load user <local:admin> from db`
The ContentPackLoaderPeriodical is now using
Configuration#getRootUsername instead of hard coding "local:admin".
Fixes …
> Fix content-pack auto installation

- graylog2-server/src/main/java/org/graylog/plugins/views/search/export/CommandFactory.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/export/MessagesRequest.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/export/ResultFormat.java
This PR is adding an optional `timerange` parameter to the request used to export a single widget's searchtype. If it is not present, the export will still use the widget's timerange (or the one from its query, if it's absent).
> Adding optional timerange parameter to export request.

- graylog2-web-interface/docs/StyleGuideWrapper.tsx
- graylog2-web-interface/src/theme/GraylogThemeProvider.tsx
- graylog2-web-interface/src/theme/UseCurrentThemeMode.tsx
- graylog2-web-interface/src/theme/constants.ts
- graylog2-web-interface/src/theme/docs/Colors.md
- graylog2-web-interface/src/theme/docs/Utilities.md
- graylog2-web-interface/styleguide.config.js
Before this change the `GraylogThemeProvider` implementation of the style guide always used the browser setting for the theme mode. Since the style guide components expect / are configured for the `teint` theme mode, we need to override this theme provider setting.
Beside fixing the initial theme setting for the style guide, this PR is also:
- fixing the theme usage in `Utilities.md`
- updating and reimplementing `Colors.md`
> Fixing theme usage in style guide.

- graylog2-web-interface/src/views/Constants.ts
- graylog2-web-interface/src/views/components/searchbar/TimeRangeInput.test.tsx
- graylog2-web-interface/src/views/components/searchbar/TimeRangeInput.tsx
- graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx
This change is introducing an optional `validTypes` prop for the `TimeRangeInput` component, which allows filtering which time range type tabs are shown. If it is not present, all tabs are shown per default.
> Allow filtering valid time range types in time range picker.

- graylog2-web-interface/packages/eslint-config-graylog/index.js
- graylog2-web-interface/src/views/components/Value.test.jsx
Previously, `jest-each` was the go to way to create parameterized tests. Starting with Jest 23, it has been integrated into the jest core.  In order to have proper typing, linting and less dependencies, `it.each` should be used instead of `each` from `jest-each`. This PR is removing one last usage of `jest-each` and adds an ESLint rule that forbids importing `jest-each`.
> Forbid usage of `jest-each` module.

- graylog2-server/src/main/java/org/graylog2/buffers/Buffers.java
- graylog2-server/src/main/java/org/graylog2/indexer/healing/FixDeflectorByDeleteJob.java
- graylog2-server/src/main/java/org/graylog2/indexer/healing/FixDeflectorByMoveJob.java
- graylog2-server/src/main/java/org/graylog2/initializers/BufferSynchronizerService.java
- graylog2-server/src/main/java/org/graylog2/plugin/buffers/Buffer.java
- graylog2-server/src/main/java/org/graylog2/plugin/buffers/EventBuffer.java
When the server shuts down, it drains the process buffer and the output buffer and only then continues with the shutdown sequence.
This change adds the input buffer to the list of buffers to be drained and waited upon during server shutdown.
When elasticsearch is down, we skip buffer draining, because we don't want to wait for the process and output buffers to be empty (which wouldn't happen). This made a small refactoring of the buffer synchronizer necessary so that we can still wait for the input buffer to be drained in that case.
Must only be merged after Graylog2/graylog-plugin-cloud#793 is merged.
Should be forward-ported to `master`.
Draining the input buffer is usually a really fast operation. Once no more events are added to the buffer, it will be empty pretty much instantly …
> Drain input buffer when shutting down server

- full-backend-tests/src/test/java/org/graylog/testing/fullbackend/BackendStartupIT.java
Remove the Collector and AWS plugins from the list of expected Cloud plugins. They were removed from the manifests in https://github.com/Graylog2/graylog-project-internal/pull/58
Fixes this failing integration test:
```
[2021-03-16T10:58:59.494Z] [ERROR]   BackendStartupIT.loadsDefaultPlugins:66 
[2021-03-16T10:58:59.494Z] Expecting:
[2021-03-16T10:58:59.494Z]   <["Elasticsearch 7 Support",
[2021-03-16T10:58:59.494Z]     "Threat Intelligence Plugin",
[2021-03-16T10:58:59.494Z]     "Elasticsearch 6 Support"]>
[2021-03-16T10:58:59.494Z] to contain exactly in any order:
[2021-03-16T10:58:59.494Z]   <["Threat Intelligence Plugin",
[2021-03-16T10:58:59.494Z]     "Collector",
[2021-03-16T10:58:59.494Z]     "AWS plugins",
[2021-03-16T10:58:59.494Z]     "Elasticsearch 6 Support", …
```
> Remove the Collector and AWS plugins from the list of expected Cloud plugins

- graylog2-web-interface/src/views/components/DashboardSearchBar.test.tsx
- graylog2-web-interface/src/views/components/SearchBar.test.tsx
- graylog2-web-interface/src/views/components/searchbar/SearchButton.test.tsx
- graylog2-web-interface/src/views/components/searchbar/SearchButton.tsx
- graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.test.tsx
When the search configuration did not change clicking on the search button did not trigger a new search execution.
When the state of the search is not dirty the search was not executed since no change on the search was found.
Now in stead of submitting a new search we call `SearchActions.refresh` when the state of the form is not dirty.
- Perfoming searches with dirty and clean state
- On dashboard and search
> Search not executing when form state is clean

- graylog2-web-interface/package.json
- graylog2-web-interface/yarn.lock
- Bump elliptic to 6.5.4, fixing https://github.com/advisories/GHSA-r9p9-mrjm-926w
- Bump urijs to 1.19.6, fixing https://github.com/advisories/GHSA-p6j9-7xhc-rhwp
> Bump cloud web dependencies with security updates

- .github/dependabot.yml
I propose that we change Dependabot to run at a less active time. 
This makes Dependabot check for updates at 2am CET (8pm CST/6pm PST).
Reference:
https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#scheduletime
The Dependabot PRs are starting to back up the CI system a bit. Rescheduling it to 2am CET would let the jobs run without impacting developers.
> Move dependabot schedule to less active time.

- graylog2-web-interface/src/views/components/widgets/MessageTable.tsx
Reverted `overflow-y: hidden` that was defaulted in Bootstrap styles
While we don't fully support mobile views, we should not intentionally break them either.
Resolves #8920
> Fixes small resolution MessageTable scroll

- graylog2-server/pom.xml
This has been resolved with version 3.2.2
https://commons.apache.org/proper/commons-collections/javadocs/api-3.2.2/org/apache/commons/collections/functors/InvokerTransformer.html
WARNING: from v3.2.2 onwards this class will throw an
UnsupportedOperationException when trying to serialize or de-serialize
an instance to prevent potential remote code execution exploits.
> Remove workaround for apache commons vulnerability

- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/RestHighLevelClientProvider.java
**Note:** This PR needs a backport to `4.0`.
This change is avoiding eager initialization of the ES7 client (and sniffer) in its provider class. Instead, it is initializing a memoized supplier, which returns the same instance upon repeated invocation.
This avoids initializing the client and the sniffer unnecessarily when the ES7 module is not in use.
In a future improvement, we could safeguard against this by determining the ES version earlier and include the ES6/ES7/... guice module only if the module is active. This is beyond the scope of this bugfix PR.
> Initialize ES7 client and sniffer lazily.

- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/RestHighLevelClientProvider.java
**Note:** This is a backport of #10264 to `4.0`.
This change is avoiding eager initialization of the ES7 client (and sniffer) in its provider class. Instead, it is initializing a memoized supplier, which returns the same instance upon repeated invocation.
This avoids initializing the client and the sniffer unnecessarily when the ES7 module is not in use.
In a future improvement, we could safeguard against this by determining the ES version earlier and include the ES6/ES7/... guice module only if the module is active. This is beyond the scope of this bugfix PR.
The backport has been tested manually (startup of 4.0, creation of the changed class)
> Initialize ES7 client and sniffer lazily. (4.0)

- graylog2-web-interface/src/views/bindings.routes.test.tsx
- graylog2-web-interface/src/views/bindings.tsx
This change allows enabling the new aggregation builder UI which is currently in development using a feature flag. It is enabled by running the dev server like this:
```
FEATURES=aggregation-wizard yarn start
```
If not `FEATURES` environment variable is specified, the current UI will be used.
Previously, a manual change to the bindings file was required to enable the new UI. This leads to having to stash and pop the changes all the time when switching branches.
> Enable in-development aggregation wizard using feature flag.

- graylog2-web-interface/src/views/components/MigrateFieldCharts.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/AggregationWizard.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/WidgetConfigForm.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.groupBy.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/AggregationElementType.ts
- graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/GroupByElement.test.ts
- graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/GroupByElement.ts
- graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/MetricElement.ts
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/FieldSelect.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/GroupBy.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/GroupBy/Direction.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/GroupBy/FieldComponent.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/GroupBy/Time.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/GroupByConfiguration.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/Metric.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/MetricsConfiguration.tsx
- graylog2-web-interface/src/views/components/datatable/DataTable.test.tsx
- graylog2-web-interface/src/views/components/visualizations/__tests__/XYPlot.test.tsx
- graylog2-web-interface/src/views/components/visualizations/area/__tests__/AreaVisualization.test.tsx
- graylog2-web-interface/src/views/logic/aggregationbuilder/Pivot.ts
- graylog2-web-interface/src/views/logic/searchtypes/aggregation/PivotConfigGenerator.ts
- graylog2-web-interface/src/views/logic/searchtypes/aggregation/PivotGenerator.test.ts
- graylog2-web-interface/src/views/logic/searchtypes/aggregation/PivotGenerator.ts
- graylog2-web-interface/src/views/logic/searchtypes/aggregation/__snapshots__/PivotConfigGenerator.test.ts.snap
This PR extends the new aggregation controls by:
- Implementing the components to configure the different group by options.
- When editing an existing widget, transforming the configured row & column pivots and the column rollup option for the group by form elements.
- Updating the widget config row & column pivots and column rollup option after submitting the group by settings.
Overview of the different configuration options:
To finish this implementation we need to:
> Support configuration of group by / row & column pivots in new aggregation controls.

- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.groupBy.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/GroupBy/FieldComponent.tsx
Prior to this change, the frontend included the old form values in the
request to the backend when applying a new config. For example if the
field type changed from time to value, we do not need the interval
values anymore but only the limit form value.
This change will set the old values to undefined before setting the new
default values.
- Edit a histogram widget
- Change the GroupBy from `timestamp` to a value fieldtype like `action`
- Apply those changes
> Unset old group by form values when changing the type of the field

- graylog2-server/src/main/java/org/graylog2/configuration/PathConfiguration.java
- graylog2-server/src/main/java/org/graylog2/configuration/converters/SortedPathSetConverter.java
- graylog2-server/src/main/java/org/graylog2/lookup/AllowedAuxiliaryPathChecker.java
- graylog2-server/src/main/java/org/graylog2/lookup/LookupModule.java
- graylog2-server/src/main/java/org/graylog2/lookup/adapters/CSVFileDataAdapter.java
- graylog2-server/src/test/java/org/graylog2/configuration/PathConfigurationTest.java
- graylog2-server/src/test/java/org/graylog2/configuration/converters/SortedPathSetConverterTest.java
- graylog2-server/src/test/java/org/graylog2/lookup/AllowedAuxiliaryPathCheckerTest.java
- graylog2-server/src/test/java/org/graylog2/lookup/adapters/CSVFileDataAdapterTest.java
Restores the ability to use the CSV File lookup adapter in Cloud with added protections for where files can be lookup up from (porting #10244 to `cloud-4.0`).
Closes https://github.com/Graylog2/graylog-plugin-cloud/issues/790
The CSV File adapter is needed for content packs (specifically Illuminate). Adding it back to Cloud allows the content packs to be installed and used.
Started the app, and verified that the CSV File adapter can be used. Also, smoke-tested to verify that the patch checking from #10244 is working.
> Restore ability to use the CSV File adapter in Cloud

- graylog2-web-interface/src/views/logic/views/UseLoadView.ts
- graylog2-web-interface/src/views/pages/NewDashboardPage.tsx
- graylog2-web-interface/src/views/stores/SearchExecutionStateStore.ts
This change is making sure that a dashboard which has been exported from
a search loads properly if one of the (load/execute) hooks fails. There
were two issues which are fixed in this change:
1. The view was immediately recreated in the `NewDashboardPage` after
taken from state, due to a rerendering of the `NewDashboardPage`
2. The `HookComponent` returned by `useLoadView` was not cleared after
a successful retry.
This change is fixing these issues, ensuring that a search exported to a
dashboard loads fine, e.g. if containing parameters.
> Fixing loading lifecycle for exported dashboards with failing load hooks.

- graylog-storage-elasticsearch6/pom.xml
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/testing/ElasticsearchInstanceES6.java
- graylog-storage-elasticsearch6/src/test/resources/elasticsearch.properties
- graylog-storage-elasticsearch7/pom.xml
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ElasticsearchInstanceES7.java
renamed DEFAULT_VERSION to ES_VERSION so it's not misleading (you can't set it to sth. different)
removed properties from pom
removed property file and loading
Fixes #8283
There should only be one version in the src. 
I ran the IT-tests
> Remove Unnecessary Elasticsearch Version Props from Integration Tests

- graylog2-server/src/main/java/org/graylog2/plugin/Version.java
- graylog2-web-interface/src/components/layout/Footer.jsx
- graylog2-web-interface/src/components/layout/Footer.test.jsx
- graylog2-web-interface/src/components/layout/StandardFooter.jsx
- graylog2-web-interface/src/util/Version.js
- graylog2-web-interface/src/util/Version.test.jsx
This PR adds some features to support https://github.com/Graylog2/graylog-plugin-cloud/issues/295:
- Plugins can now set a git commit ID in their versions by providing a `properties` file
- Allow plugins to customize the page footer
- Add more flexibility to `Version.js`, so consumers can decide which parts of the version use
> Support for displaying cloud version number

- graylog2-web-interface/src/views/components/visualizations/heatmap/HeatmapVisualization.tsx
- graylog2-web-interface/src/views/components/visualizations/heatmap/__tests__/HeatmapVisualization.test.tsx
Prior to this change, if the default value was set with the smallest
value and the provided data was empty, we raised an stacktraced.
This change will ensure the empty data does not get accessed where
nothing is defined.
Create a HeatmapVisualization and select a timerange without data.
> Fix HeatmapVisualization with empty data and smallest default value

- graylog2-web-interface/src/views/components/aggregationwizard/AggregationWizard.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/WidgetConfigForm.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/AggregationElementType.ts
- graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/GroupByElement.ts
- graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/MetricElement.ts
- graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/SortElement.ts
- graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/VisualizationElement.ts
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/Sort.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/SortConfiguration.tsx
- graylog2-web-interface/src/views/logic/aggregationbuilder/AggregationWidgetConfig.ts
- graylog2-web-interface/src/views/logic/aggregationbuilder/SortConfig.ts
This PR is adding the sorting section to the aggregation wizard, which allows the user to configure a sorting of the displayed values by selecting from a list of configured metrics and fields which are in use by the aggregation.
This PR is also slightly changing the `toConfig` signatures. Instead of passing around an `AggregationWizardConfig`, its `Builder` is used. The main reason is that `Builder.build` is performing some validation (checking if the configured sorts do match the configured pivots) that rely on the object being complete before it's built, but it also has some performance benefits by avoiding unneeded object/builder creations.
Fixes #9740.
> Add sorting to aggregation wizard.

- graylog2-web-interface/src/views/components/widgets/ExtraWidgetActions.test.tsx
- graylog2-web-interface/src/views/components/widgets/ExtraWidgetActions.tsx
- graylog2-web-interface/src/views/components/widgets/Types.ts
Prior to this change, actions introduced by plugins where not able to be
disabled by the plugin.
This change will add a interface to check if the rendered action should
be disabled or not.
Tested with Enterprise plugin
> Add posibility to disable actions from plugin

- graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionSummary.jsx
- graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.jsx
Prior to this change, the permissions check was broken for notification
when displaying the event definition summary or edit it.
This change will fix the template string which was missing a colon.
Special kudos to @mpfz0r 
- Create a user which has only a reader role
- Share a stream with the created user
- Share a notification with the created user
- Create a event definition where stream and notification is used
- Share the event definition with the user
- Log in as user and have look at the event definition, where you should be able to see the notification without error.
> Fix permission check for notifcations in event definitions

- graylog2-web-interface/src/components/event-definitions/event-definition-form/EventDefinitionSummary.jsx
- graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.jsx
Prior to this change, the permissions check was broken for notification
when displaying the event definition summary or edit it.
This change will fix the template string which was missing a colon.
Special kudos to @mpfz0r
(cherry picked from commit b49ce7b0801bf0d2e84da346cb284737f878151e)
> Fix permission check for notifcations in event definitions (#10380)

- graylog2-web-interface/packages/jest-preset-graylog/jest-preset.js
- graylog2-web-interface/packages/jest-preset-graylog/src/setup-files/mock-IntersectionObserver.js
- graylog2-web-interface/src/views/components/aggregationwizard/AggregationWizard.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/ElementsConfiguration.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/ElementsConfigurationActions.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/ElementConfigurationContainer.tsx
With this PR we are displaying the "Apply Changes" button of the element configuration column as sticky. We want to ensure that the user does not have to scroll to be able to submit the configuration changes.
I've displayed a box shadow for the actions row which includes the "Apply changes" button.
Otherwise it is harder to understand which content can be scrolled. We are hiding this box shadow, when the user scrolled to the very bottom. I've used an `IntersectionObserver` to check if the user scrolled to the bottom. It has many benefits over an `onScroll` solution. Not only in terms of performance, we also do not need to worry about updating the styling when the user resizes the browser.
Before this change:
After this change:
> Always show elements configuration actions in aggregation builder, by positioning them as sticky.

- graylog2-web-interface/templates/index.html.template
Adding the lang attribute to the html tag declares the language of the web application. This will assist the browser and enable support for e.g. hyphenation. (https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens)
> Adding `lang="en"` to html tag, to declare the language of the web application.

- graylog2-web-interface/src/views/components/DashboardSearchBar.test.tsx
- graylog2-web-interface/src/views/components/DashboardSearchBar.tsx
- graylog2-web-interface/src/views/components/SearchBar.test.tsx
- graylog2-web-interface/src/views/components/SearchBar.tsx
Prior to this change, a page which was displaying a widget in edit mode,
the page was rendering two Save buttons. Also the complexity of states
to handle on each of the controls was not worth the gain.
This change will hide the view controls on dashboard and the saved
search controls on a search.
- Edit a widget and see the controls disappear
Fixes #10337
> Hide save and load controls when editing a widget

- graylog2-web-interface/src/components/common/Select.tsx
- graylog2-web-interface/src/components/configurationforms/__snapshots__/ListField.test.tsx.snap
With this PR we are defining the theme input placeholder color for the `Select` component.
Before (slightly different input and select placeholder color):
After:
> Defining theme input placeholder color for common `Select` component.

- graylog2-web-interface/package.json
- graylog2-web-interface/src/logic/rest/FetchProvider.ts
- graylog2-web-interface/src/polyfill.js
- graylog2-web-interface/src/views/stores/SearchStore.test.ts
- graylog2-web-interface/test/integration-environment.js
- graylog2-web-interface/yarn.lock
This PR is replacing our usage of the `superagent` & `superagent-bluebird-promise` dependencies with the native [`fetch API`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API).
When we started to migrate the Graylog Web Interface to an SPA, there was no native API that allowed us to communicate with the REST API in a friendly way. Therefore we employed `superagent` to handle this task for us. This has changed in the way that the fetch API is now around for quite some time and allows us to do everything that `superagent` does, without an external dependency.
As we do want to support IE11 now, we need to provide a `fetch` as well as a `Promise` polyfill for now. These are added and imported at startup. If we decide to drop support for IE11, we can easily remove those again.
This …
> Replace superagent with native fetch API.

- graylog2-web-interface/src/views/components/aggregationwizard/AggregationWizard.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/ElementsConfiguration.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/ElementsConfigurationActions.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/AggregationElementType.ts
- graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/GroupByElement.ts
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/ElementConfigurationContainer.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/ElementConfigurationContainer.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/ElementConfigurationSection.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/GroupByConfiguration.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/MetricsConfiguration.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/SortConfiguration.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/VisualizationConfiguration.tsx
We've recently updated the aggregation builder layout, the config options are now displayed on the left side of the visualization.
In comparison with the previous implementation (where every config option had a fixed position) it is now slightly harder to identify the position aggregation element.
With this PR we are simplifying the identification by adjusting the layout as follows:
We are also:
- replacing the "Add an element section" buttons with the plus icon next to the title, to reduce the height of each aggregation element.
- Changing the position of the "Rollup columns" option.
> Simplify identification of each aggregation element in aggregation builder.

- graylog2-server/src/main/java/org/graylog2/lookup/adapters/CSVFileDataAdapter.java
- graylog2-server/src/main/java/org/graylog2/lookup/adapters/LookupDataAdapterValidationContext.java
- graylog2-server/src/test/java/org/graylog2/lookup/adapters/CSVFileDataAdapterTest.java
Use the [AllowedAuxiliaryPathChecker](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog2/lookup/AllowedAuxiliaryPathChecker.java#L30) (and therefore the `allowed_auxiliary_paths` server configuration file parameter) for the CSV Lookup adapter UI validation for the File path field. This ensures that the user cannot use the UI validation on the File path field to inspect if arbitrary directories and files exist on the file system in the Cloud context as described in https://github.com/Graylog2/graylog-plugin-cloud/issues/830. The AllowedAuxiliaryPathChecker was already being used in the process of starting the CSV File adapter (see https://github.com/Graylog2/graylog2-server/pull/10244), and this adds the same check for the UI validation. …
> CSV File adapter: Use AllowedAuxiliaryPathChecker in File path UI validation

- graylog2-web-interface/src/components/search/MessageDetailsTitle.jsx
This change needs to be backported to 4.0/cloud-4.0.
Fixes #10200
> Reduce label size in MessageDetailsTitle

- graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/VisualizationElement.ts
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/VisualizationConfiguration.tsx
- graylog2-web-interface/src/views/components/visualizations/area/bindings.tsx
- graylog2-web-interface/src/views/components/visualizations/bar/bindings.tsx
- graylog2-web-interface/src/views/components/visualizations/line/bindings.tsx
- graylog2-web-interface/src/views/components/visualizations/scatter/bindings.tsx
- graylog2-web-interface/src/views/types.d.ts
This change is introducing a `capabilities` field for a visualization type, which can be used to describe which optional features a given visualization supports. The valid keys for this field are implemented through an interface, so it can be extended from plugins through declaration merging.
These capabilities are effectively used in this PR to disable event annotations for heatmap/single number/pie chart/world map visualizations, which do not support displaying event annotations.
> Disable event annotation option if visualization does not support it.

- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java
- graylog2-web-interface/src/components/indexers/IndexerClusterHealthSummary.jsx
This PR makes makes two changes in the way we report ES cluster health status and handle it in the web interface.
First, it fixes an inconsistency in the returned case for the health status between Elasticsearch versions. This is what the API returned before the changes, now it will use lower case in both cases:
**ES6**
`GET /api/system/indexer/cluster/health`
```
{"status":"green","shards":{"active":60,"initializing":0,"relocating":0,"unassigned":0}}
```
**ES7**
`GET /api/system/indexer/cluster/health`
```
{"status":"GREEN","shards":{"active":10,"initializing":0,"relocating":0,"unassigned":0}}
```
Additionally, it ensures the UI works in a case independent way, so the correct status is displayed regardless of the returned case.
Fixes #10407 
This PR needs to be backported into 4.0.
> Fix case inconsistencies with ES cluster health status

- graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java
Previously there was no way to find out which messages failed in
processing and where they failed.
This change adjusts the log levels in ProcessBufferProcessor to allow
stack trace and message content logging on DEBUG level.
Refs #10319
This should be backported to 4.0 and 3.3 once it has been merged.
> Log failed messages and full stack trace on processing errors

- .github/workflows/build.yml
This change is temporarily disabling the Github Actions build if the current PR is not from a fork. For these, we have a Jenkins run. For forks, we do not run that one, so we should at least have a Github Actions build.
The reason for disabling Github Actions is that we are seeing test failures for no reason repeatedly. It looks like there is some kind of resource exhaustion that leads to not being able to bind a port reliably. We do not see this for our Jenkins builds.
The way this is implemented was a bit of trial and error, due to being unable to find precise information on the structure of the `github.base_ref` variable in the official Github Actions docs. It looks like it's `master` for non-forks and `Graylog2:master` for forks. Therefore I am skipping the build if it's not the …
> Disabling Github Actions if PR is not from fork.

- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.corevisualizations.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/VisualizationElement.ts
- graylog2-web-interface/src/views/components/visualizations/area/bindings.tsx
- graylog2-web-interface/src/views/components/visualizations/bar/bindings.tsx
- graylog2-web-interface/src/views/components/visualizations/heatmap/bindings.tsx
- graylog2-web-interface/src/views/components/visualizations/line/bindings.tsx
- graylog2-web-interface/src/views/components/visualizations/pie/bindings.tsx
- graylog2-web-interface/src/views/components/visualizations/scatter/bindings.tsx
- graylog2-web-interface/src/views/components/visualizations/validations.ts
- graylog2-web-interface/src/views/types.d.ts
This PR introduces a validation-specific `validate` function in the `VisualizationType`, which allows raising validation errors when this visualization is selected in the aggregation builder wizard.
This allows us to validate that the specific requirements for a given visualization are satisfied. This is used to check if:
- At least one metric is configured for area/bar/line/pie charts/scatter plot/heatmap
- At least two groupings are configured, at least one row and at least one column one for the heatmap
If at least one constraint is not fulfilled, submitting the current configuration is disabled and a validation error is shown.
This is supposed to help guiding the user to a working configuration and creates a space to display helpful information what is missing/misconfigured.
> Validate visualization-specific constraints in aggregation builder.

- graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java
Previously there was no way to find out which messages failed in
processing and where they failed.
This change adjusts the log levels in ProcessBufferProcessor to allow
stack trace and message content logging on DEBUG level.
Refs #10319
(cherry picked from commit 6f38abf881d80fec16c1b61c29661e9b355a8e35)
> Log failed messages and full stack trace on processing errors (#10421)

- graylog2-web-interface/src/views/components/aggregationwizard/WidgetConfigForm.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.corevisualizations.test.tsx
- graylog2-web-interface/src/views/components/visualizations/area/bindings.tsx
- graylog2-web-interface/src/views/components/visualizations/bar/bindings.tsx
- graylog2-web-interface/src/views/components/visualizations/heatmap/bindings.tsx
- graylog2-web-interface/src/views/components/visualizations/line/bindings.tsx
- graylog2-web-interface/src/views/components/visualizations/number/bindings.tsx
- graylog2-web-interface/src/views/types.d.ts
This PR is setting defaults for the interpolation/barmode config options for the area/bar/line charts. These options are mandatory, but are not required to show an initial chart, so defining defaults for them allows the user to get faster initial results while still allowing to tweak them.
> Using better defaults for area/bar/line charts.

- graylog2-web-interface/src/views/actions/SearchActions.ts
- graylog2-web-interface/src/views/components/Search.test.tsx
- graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.tsx
- graylog2-web-interface/src/views/stores/SearchStore.ts
Prior to this change, whenever a search was executed the search was
executed for all widgets, regardless if they are seen or not.
This change will add a SearchAction which sets a filter by which the
search types will be filtered before beeing send to the server.
This filter will be set from the widget focus provider when ever a
widget gets focused or edited.
- Set a widget into focus and execute a search
- Check the result via webconsole
Fixes #10250 
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#2192
> Execute search only for focused widget

- graylog2-server/src/main/java/org/graylog2/indexer/SetIndexReadOnlyJob.java
- graylog2-server/src/main/java/org/graylog2/indexer/indices/jobs/OptimizeIndexJob.java
- graylog2-server/src/main/java/org/graylog2/indexer/indices/jobs/SetIndexReadOnlyAndCalculateRangeJob.java
- graylog2-server/src/main/java/org/graylog2/indexer/ranges/CreateNewSingleIndexRangeJob.java
The SetIndexReadOnlyJob, SetIndexReadOnlyAndCalculateRangeJob,
OptimizeIndexJob and CreateNewSingleIndexRangeJob jobs
might throw an exception when running "indices.isClosed(indexName)" when
the index doesn't exist anymore.
Some of these jobs are executed with a delay so it might happen that the
index retention already deleted the index when these jobs are started.
This adds a "indices.exist(indexName)" check at the very beginning.
> Don't run index jobs for missing indices

- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java
- graylog2-web-interface/src/components/indexers/IndexerClusterHealthSummary.jsx
* Use consistent case for ES cluster health status
The cluster health status on ES6 was a lowercase string but on ES7 is
uppercase. This change transforms the status in ES7 into a lowercase
string.
* Make IndexerClusterHealthSummary case independent
The component made comparisons of ES cluster health status in a case
dependent way, causing #10407. This change ensures all comparisons
are done in a case independent way.
Fixes #10407
(cherry picked from commit b8f9cad7588a91f85cd8c58f8ef4ab04738b1b87)
Backport of #10428
> Fix case inconsistencies with ES cluster health status (#10428)

- graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java
We previously added an exception to ignore outputs when sharing streams.
This is also required for sharing dashboards because output dependencies
might get pulled in transitively via streams.
Fixes Graylog2/graylog-plugin-enterprise#2131
This needs to be backported to 4.0 once it has been merged.
> Adjust entity dependency resolver to ignore outputs for dashboards

- graylog2-web-interface/package.json
- graylog2-web-interface/packages/jest-preset-graylog/jest-preset.js
- graylog2-web-interface/packages/jest-preset-graylog/package.json
- graylog2-web-interface/yarn.lock
This PR adds `jest-junit` to enable reporting frontend test results to a `junit.xml` which can be picked up by jenkins to display test results properly. This helps us to identify failing tests quicker, instead of having to scroll through the console log of a build.
> Add `jest-junit` for frontend test reporting.

- graylog2-web-interface/packages/eslint-config-graylog/index.js
- graylog2-web-interface/packages/eslint-config-graylog/package.json
- graylog2-web-interface/yarn.lock
This PR is adding the `eslint-plugin-compat` plugin to our ESLint rule set, which points out usage of browser APIs, which are not supported by our current set of supported browsers (determined by the browserlist query in `package.json`, currently the default). 
This helps us to avoid usages of APIs which are e.g. not supported (fully) in IE11 and gives us early indications for missing polyfills.
A followup issue resulting from this is the installation of an `IntersectionObserver` polyfill, as it is not supported natively on IE11.
> Add `eslint-plugin-compat` to our ESLint rule set.

- graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java
We previously added an exception to ignore outputs when sharing streams.
This is also required for sharing dashboards because output dependencies
might get pulled in transitively via streams.
Fixes Graylog2/graylog-plugin-enterprise#2131
(cherry picked from commit 5606787097f68c87da4c33f6e89a4fb59a747205)
> Adjust entity dependency resolver to ignore outputs for dashboards (backport)

- SECURITY.md
This change is updating supported version numbers in our security policy. We should include this step in our checklist for new major/minor releases.
> Updating version numbers in Security policy

- graylog2-web-interface/src/logic/rest/FetchProvider.test.ts
- graylog2-web-interface/src/logic/rest/FetchProvider.ts
Prior to this change, the fetch provider was always trying to parse a json body
even if the body was empty. This failed of course.
This change will check if the body is empty before trying to parse the
response body.
- Create a content pack and don't get an error when click on the final create
- Delete a content pack and don't get an error when clicking on confirm
> Fix fetch provider with empty response body

- graylog2-web-interface/src/stores/__tests__/connect.test.tsx
- graylog2-web-interface/src/stores/connect.tsx
- graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.test.tsx
This PR is separating the store registration and the props mapping logic
in the `useStore` custom hook. This is avoiding a bug where passing a
props mapper function as an inline arrow function leads to missed state
updates.
Passing a props mapper function as a constant (either by extracting it
to a constant scoped outside of the component calling `useStore`, or
using `useCallback` if it is using props/state from the component) is
still recommended, but merely for performance reasons and not for
correctness.
> Separate `useStore` store registration and props mapping logic.

- graylog2-server/src/main/java/org/graylog/security/authservice/backend/LDAPAuthServiceBackend.java
- graylog2-server/src/main/java/org/graylog/security/authservice/ldap/UnboundLDAPConnector.java
Some users want to use the same attribute (e.g. "cn") for different
config settings. (e.g. name and full name)
Also don't skip the unique ID attribute when collecting user attributes.
This is an issue when the same attribute is used for the unique
attribute and another config setting (note recommended) because the
attribute will be missing from user details.
Adjust the LDAP login test output to use a special key for the unique ID
attribute to avoid confusion because of the base64 encoded value.
Fixes #10069
This needs to be backported to 4.0 once it has been reviewed, tested and merged.
> Allow using the same LDAP attribute for different config settings

- graylog2-web-interface/src/views/components/visualizations/worldmap/MapVisualization.jsx
Prior to this change, we used a prop to pass the interactive context
value to the MapVisualization component. But this prop was never set so
the defaultProp (true) was used.
This change will remove the prop and use the InteractiveContext.Consumer
directly just like in GenericPlot, to ensure interactive is always set
correctly.
- Create a world map on a dashboard
- Add this world map widget alone on a report
- Render the report
Needs backport to 4.0.x and perhaps more.
> Fix rendering of WorldMapVisualization in reports

- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/Sort.tsx
Before this change naming a metric, which is being selected as a field for a sort element, "emptied" the related sort field select.
Before defining a metric name:
After defining a metric name:
With this change the selected sort field option will always show the correct label:
I tried to write a test for this case, but we can't  test it easily, because it is only a visual bug and the form state is still correct.
Testing if a `react-select` component displays the correct label for the selected option is not possible, as far as I know.
> Update name of selected aggregation sort field correctly, when naming related metric.

- graylog2-server/src/main/java/org/graylog/security/authservice/backend/ADAuthServiceBackend.java
Adjust the AD login test output to use a special key for the unique ID
attribute to avoid confusion because of the base64 encoded value.
Similar to the change in #10437.
Fixes #10069
This should be backported to 4.0 once it has been merged.
> Adjust ADAuthServiceBackend login test output

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndicesAdapterES6.java
- graylog2-server/src/main/java/org/graylog2/indexer/MongoIndexSet.java
- graylog2-server/src/test/java/org/graylog2/indexer/MongoIndexSetTest.java
**Note:** This PR requires a backport to `4.0.`.
This PR is making a couple of changes to support the + character in index set prefixes. The required changes were:
- Properly URL encode `+` in names when creating the index template
- Quote `+` when creating the regular expression used to match indices     against the prefix
When an index set is configured with a `+` in the index set prefix, all kinds of issues show up, making it effectively unusable. Indices are not identified to belong to this index set, creation of new indices for this index set do not have the proper index template.
> Support + in index set prefixes.

- graylog2-server/src/main/java/org/graylog/security/authservice/backend/ADAuthServiceBackend.java
- graylog2-server/src/main/java/org/graylog/security/authservice/backend/LDAPAuthServiceBackend.java
- graylog2-server/src/main/java/org/graylog/security/authservice/ldap/UnboundLDAPConnector.java
Some users want to use the same attribute (e.g. "cn") for different
config settings. (e.g. name and full name)
Also don't skip the unique ID attribute when collecting user attributes.
This is an issue when the same attribute is used for the unique
attribute and another config setting (note recommended) because the
attribute will be missing from user details.
Adjust the LDAP login test output to use a special key for the unique ID
attribute to avoid confusion because of the base64 encoded value.
Fixes #10069
(cherry picked from commit 7e64e6a8113ee66b0afdadda81df107884848a80)
> Allow using the same LDAP attribute for different config settings (#10437)

- graylog2-web-interface/src/components/common/ConfirmLeaveDialog.tsx
Prior to this change, the route leave prompt asking the user for confirmation if the current view is dirty and the route is left was unconditionally triggered for any route history action. This means it is also triggered when query parameters are being added to the current URL.
With the introduction of the focused mode and its use during widget editing, this lead to the phenomenon that the prompt was always triggered when a widget on an unsaved dashboard was focused, e.g. for editing.
This change is now adding a check to the `Prompt` component used to generate the confirmation prompt, checking if the new location is a different path than the current one. Therefore it is not triggered if only the query parameters are changing.
> Fixing route leave prompt for focused mode on dashboards.

- graylog2-web-interface/src/views/bindings.tsx
This change is toggling the feature flag used for the new aggregation
builder wizard. It removes the `aggregation-wizard` feature flag and
introduces the `legacy-aggregation-wizard` feature flag. The new
aggregation builder wizard is now active by default. If the old
aggregation builder ui is desired, the `legacy-aggregation-wizard` can
be used like this to enable it:
```
FEATURES=legacy-aggregation-wizard yarn start
```
> Make new aggregation builder wizard the new default.

- graylog2-web-interface/package.json
- graylog2-web-interface/src/pages/ConfigurationsPage.jsx
- graylog2-web-interface/src/pages/ConfigurationsPage.test.tsx
- graylog2-web-interface/src/pages/ConfigurationsPage.tsx
- graylog2-web-interface/src/pages/configurations/ConfigletContainer.tsx
- graylog2-web-interface/src/pages/configurations/PluginConfigRows.tsx
- graylog2-web-interface/src/views/types.d.ts
- graylog2-web-interface/yarn.lock
Before this change, an individual core or plugin configuration element could raise an error and render the whole configurations page unusable.
This PR is adding an error boundary which is used to contain errors from each configuration element. If a single configuration element throws an error, a fallback component will be rendered instead, showing the actual error. In case of the plugin configuration elements, the config type (an fqcn) will be shown instead of the title. This gives at least an indication where the error is coming from. The rest of the page is still usable in case of an individual configuration element failing.
In addition, a general overhaul of the `ConfigurationsPage` was performed, migrating it to TypeScript and turning it into a functional component. Also, some quirks …
> Wrap system configuration elements in error boundary.

- .github/workflows/build.yml
Due to the underlying issue being fixed (see actions/virtual-environments#3186), we can now reenable Github Actions for all builds.
> Reenable Github Actions.

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndicesAdapterES6.java
- graylog2-server/src/main/java/org/graylog2/indexer/MongoIndexSet.java
- graylog2-server/src/test/java/org/graylog2/indexer/MongoIndexSetTest.java
**Note:** This is a backport of #10392 to `4.0`.
This PR is making a couple of changes to support the + character in index set prefixes. The required changes were:
- Properly URL encode `+` in names when creating the index template
- Quote `+` when creating the regular expression used to match indices     against the prefix
When an index set is configured with a `+` in the index set prefix, all kinds of issues show up, making it effectively unusable. Indices are not identified to belong to this index set, creation of new indices for this index set do not have the proper index template.
> Support + in index set prefixes. (4.0)

- graylog2-web-interface/package.json
- graylog2-web-interface/src/polyfill.js
- graylog2-web-interface/yarn.lock
We've recently started using the IntersectionObserver API. https://github.com/Graylog2/graylog2-server/pull/10379
This PR implements the required polyfill to support browser like IE11.
Tested with IE11. Please note, we need to adjust the aggregation builder layout to fully support IE11. I will implement these changes in a follow-up PR.
Fixes https://github.com/Graylog2/graylog2-server/issues/10449
> Implement `IntersectionObserver` polyfill.

- graylog2-web-interface/src/views/components/Search.dashboard.test.tsx
- graylog2-web-interface/src/views/components/Search.tsx
Before this change we displayed the dashboard pages tabs when focusing or editing a widget.
Now we are hiding them in the two mentioned cases. This change has some benefits:
- we provide more space for the widget frame which is especially helpful when editing a widget on smaller screens.
- it is slightly easier to differentiate between a focused widget and unfocused widget.
- the layout for a focused widget is more clear.
Please note, I created a separate test file (`Search.dashboard.test.tsx`) to test the dashboard related functionality. It can be a suitable place for further dashboard related tests. For example when we hide the dashboard on widget edit.
Fixes #10493
> Do not display dashboard pages tabs when focusing a widget.

- graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.tsx
Before this change we displayed the pluggable view header elements at the top
of the search page and at the top of the aggregation builder.
This was necessary because we previously displayed the aggregation builder in a
modal. Now were we display the aggregation builder inline, below the
search bar, we no longer need to display them in the aggregation builder
as well.
> Do not display pluggable view header elements in aggregation builder.

- graylog2-web-interface/src/views/components/Search.dashboard.test.tsx
- graylog2-web-interface/src/views/components/Search.tsx
As described in https://github.com/Graylog2/graylog2-server/issues/10213 we've recently changed the way we are displaying the aggregation builder (widget edit mode). It is no longer being displayed in a modal but inline below the search bar. To display a cleaner layout and to provide more space for the aggregation builder, we decided to hide the dashboard search bar on widget edit. This especially benefits screens with a smaller height.
Before (without active dashboard filter):
After (without active dashboard filter):
Refs https://github.com/Graylog2/graylog2-server/issues/10213
> Do not display dashboard search bar when editing a widget.

- graylog2-web-interface/src/components/common/TextOverflowEllipsis.tsx
- graylog2-web-interface/src/contexts/ThemeAndUserProvider.jsx
- graylog2-web-interface/src/contexts/TimeLocalizeContext.tsx
- graylog2-web-interface/src/contexts/TimeLocalizeProvider.test.tsx
- graylog2-web-interface/src/contexts/TimeLocalizeProvider.tsx
- graylog2-web-interface/src/views/components/searchbar/TimeRangeDisplay.tsx
- graylog2-web-interface/src/views/components/widgets/TimerangeInfo.test.tsx
- graylog2-web-interface/src/views/components/widgets/TimerangeInfo.tsx
- graylog2-web-interface/src/views/components/widgets/Widget.tsx
- graylog2-web-interface/src/views/components/widgets/WidgetFrame.jsx
- graylog2-web-interface/src/views/logic/queries/TimeRangeToString.ts
Display the configured time range of a widget in dashboards.
Having a different time range for each widget configured on a dashboard, can make it hard to remember those settings.
So we now display that information in the footer of the widget.
- Create a widget
- Set relative/absolute/keyword timerange
- Check the result in the dashboard
> Timerange Info for dashboard widgets

- graylog2-web-interface/src/views/components/widgets/FieldSortSelect.test.tsx
- graylog2-web-interface/src/views/components/widgets/FieldSortSelect.tsx
This PR is replacing the select component for the `FieldSortSelect`. UI
wise there is not a big difference between these components and in the
future we want to rely on only one `Select` component. The common select
component can also be tested more easily with `react-select-event`,
which will help us with the `react-select` update.
With this PR we are also removing the option to clear the `FieldSortSelect`, since it did had no effect.
> Replacing `views/Select` with `common/Select` in `FieldSortSelect`.

- graylog2-server/pom.xml
- graylog2-web-interface/jest.it.config.js
- graylog2-web-interface/package.json
- graylog2-web-interface/src/views/spec/CreateNewDashboard.it.tsx
This PR is implementing some structural changes that separate runs for unit and integration tests in the frontend. This allows us to:
- prevent rejected promises from integration tests leaking to other tests, causing false negatives
- tune timeouts separately, as integration tests tend towards requiring higher timeout due to the increased complexity
It works by defining a second jest configuration file with a different test file name spec and defaulting to the integration test environment.
This means that:
- unit tests still should be named `*.(test|spec).[jt]s(x)?` (and all `.[jt]s(x)?` files in the `__tests__` folder)
- integration tests should be named `*.it.[jt]s(x)?`
The expected end result is to make the frontend tests run more reliable without having to disable the …
> Separate integration and unit tests in frontend.

- graylog2-server/src/main/java/org/graylog2/indexer/MongoIndexSet.java
- graylog2-server/src/test/java/org/graylog2/indexer/MongoIndexSetTest.java
**Note:** This needs to be backported to `4.0`.
In #10392 we added quoting for the patterns used to identify if an index is managed by an index set. This works fine unless `IndexSetConfig#indexMatchPattern` is defined. The index match pattern can contain special characters and regex terms deliberately, which must not be quoted. The index match pattern is currently used by archiving, which lead to it not being able to identify indices belonging to the restored archives index set.
This PR is removing quoting for the index match pattern. Any usage of the index match pattern must ensure that all special characters are quoted properly.
In a future PR I would suggest that the index match pattern can not be set through the REST API. It is currently not exposed through the frontend, the only use …
> Do not quote index match pattern for index management check pattern.

- graylog2-web-interface/src/views/components/widgets/TimerangeInfo.test.tsx
- graylog2-web-interface/src/views/components/widgets/TimerangeInfo.tsx
We've recently implemented a time range info for dashboard widgets https://github.com/Graylog2/graylog2-server/pull/10508. This PR is fixing a runtime error which occurred when no search types exist.
This is the case when a filter with an undeclared parameter is being applied.
It also fixes another runtime error which occurred after creating a new widget, because it was not yet listen in the search widget mapping.
> Do not throw error on dashboards with undeclared query parameters or on widget creation.

- graylog2-web-interface/package.json
Decreasing the number of workers used for frontend tests to improve build time and stability. 
Set the number of workers in the Jest worker pool to 50%.
This will help reduce the number of intermittent timeouts in frontend tests.
> Decrease Jest workers used to optimize build time.

- graylog2-server/src/main/java/org/graylog2/indexer/MongoIndexSet.java
- graylog2-server/src/test/java/org/graylog2/indexer/MongoIndexSetTest.java
In #10392 we added quoting for the patterns used to identify if an index is managed by an index set. This works fine unless `IndexSetConfig#indexMatchPattern` is defined. The index match pattern can contain special characters and regex terms deliberately, which must not be quoted. The index match pattern is currently used by archiving, which lead to it not being able to identify indices belonging to the restored archives index set.
This PR is removing quoting for the index match pattern. Any usage of the index match pattern must ensure that all special characters are quoted properly.
Fixes Graylog2/graylog-plugin-enterprise#2216.
> Do not quote index match pattern for index management check pattern. (4.0)

- graylog2-web-interface/src/components/common/ReactGridContainer.jsx
- graylog2-web-interface/src/components/graylog/Row.tsx
- graylog2-web-interface/src/components/layout/Footer.tsx
- graylog2-web-interface/src/components/layout/PageContentLayout.tsx
- graylog2-web-interface/src/components/login/__snapshots__/LoginBox.test.jsx.snap
- graylog2-web-interface/src/pages/__snapshots__/ShowMessagePage.test.tsx.snap
- graylog2-web-interface/src/views/components/DashboardSearchBar.tsx
- graylog2-web-interface/src/views/components/SearchBar.tsx
- graylog2-web-interface/src/views/components/SearchBarContainer.tsx
- graylog2-web-interface/src/views/components/SearchResult.tsx
- graylog2-web-interface/src/views/components/widgets/EditMessageList.tsx
- graylog2-web-interface/src/views/components/widgets/WidgetFrame.jsx
This PR includes the following changes to reduce the search page layout margins:
- reducing global footer padding and search page footer margin.
- reducing widget paddings.
- reducing search bar and dashboard search bar paddings.
- reducing page content layout and bottom margin of content rows.
This way:
- smaller widget display more content.
- the widget edit mode displays more controls on screens with a comparable small height.
Before:
After:
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#2217
> Reduce search page layout margins to provide more space for content

- graylog2-web-interface/src/components/graylog/ListGroupItem.jsx
- graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.tsx
- graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchList.test.tsx
- graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchList.tsx
- graylog2-web-interface/src/views/stores/SavedSearchesStore.ts
This PR contains a collection of smaller improvements for the saved search overview:
- Displaying the saved search summary.
- Displaying a loading spinner while loading saved searches.
- Only displaying "not found" info when API returned no saved searches, before this change we displayed the info while loading searches.
- Using default page sizes and increasing default page size from 5 to 10.
- Fixing floating of page size select, it was part of the first list item.
- Displaying selected saved search as active.
For these improvements I decided to implement the following refactorings:
- Transforming `SavedSearchesList` from class component to functional component.
- Moving the list state from the `SavedSearchesStore` to the `SavedSearchesList`
Fixes: #10130
> Collection of smaller improvements for saved searches overview

- graylog2-web-interface/src/stores/roles/AuthzRolesStore.ts
- graylog2-web-interface/src/stores/users/PreferencesStore.ts
Usernames may contain some URL reserved characters that may break API calls. This PR fixes those instances where we were not yet encoding usernames.
For what I could see, this only affects roles and user preferences API requests.
Fixes #10530
The fix needs to be backported into 4.0.
> Encode usernames used in URLs

- graylog2-web-interface/src/stores/roles/AuthzRolesStore.js
- graylog2-web-interface/src/stores/users/PreferencesStore.js
Usernames may contain some URL reserved characters that may break API
calls. This PR fixes those instances where we were not yet encoding
usernames.
Fixes #10530, backport of #10566
> Encode usernames used in URLs - 4.0

- graylog2-web-interface/src/logic/rest/CancellablePromise.test.ts
- graylog2-web-interface/src/logic/rest/CancellablePromise.ts
- graylog2-web-interface/src/logic/rest/FetchProvider.ts
Prior to this change, we rely in our code on the cancellbale promise
interface from bluebird promise. But we want to use the native promise
implementation.
This change will add a wrapper class arround the promise from native
`window.fetch` which will set a cancel flag which can be accessed later
to check if a promise was cancelled.
This does not mean the then chain will be stopped. This cannot be done
with the native promise implementation. But we can check if someone
wants us to ignore the result.
Fixes #10488
- Go to the grok patterns page and see the grok patterns load again.
> Implement Cancellable Promise

- graylog2-web-interface/src/views/components/aggregationwizard/WidgetConfigForm.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/SortElement.test.ts
- graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/SortElement.ts
Prior to this change, the user could configure sort elements on the
aggregation widget. But it either had not effect or it only broke the
visualization on timebase graphic charts.
This change will introduce a validaton to check if the sort element was
introduced together with a non table visualization and a timebase row
groupby.
- Add a sorting to a histogram
Fixes #10416
> Add validation that a sort does not work on timebased charts

- graylog2-web-interface/src/logic/errors/FetchError.ts
- graylog2-web-interface/src/logic/rest/FetchProvider.test.ts
- graylog2-web-interface/src/logic/rest/FetchProvider.ts
Through the transition from superagent to the native fetch API (#10342), a different behavior for request errors was introduced. A non-successful request does not trigger a promise rejection automatically, so an additional `catch` call in the promise chain is required in order to handle e.g. session expirations (which result in a 401 for subsequent requests) properly.
This change is correcting handling of errored responses, adds tests and cleans up the `FetchError` class by removing explicit `console.error` calls in its constructor, leaving this to the environment for uncaught promise rejections, but adding proper `name` & `message` fields so the class cleanly extends the `Error` type.
> Handle session expiration properly in frontend.

- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/GroupByConfiguration.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/MetricsConfiguration.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/SortConfiguration.tsx
By default `validateOnChange` of the `Formik` and `FieldArray` component is
`true`. One side effect is that the custom validate method is being
executed twice when changing any value. With this change we are only
executing the validation once, by setting `validateOnChange` to `false`
for the `FieldArray`s.
This change will improve the experience when typing text into an input, because the input is more responsive.
> Do not execute validation of widget config form twice when changing value of field inside `FieldArray`.

- graylog2-server/src/main/java/org/graylog2/buffers/processors/OutputBufferProcessor.java
This PR simply counts down the latch where it was missed to do so.
During investigation of https://github.com/Graylog2/graylog2-server/issues/10168 it turned out
that, IF at least one of non-default Outputs was requested to shut down,
THEN all available instances of `OutputBufferProcessor` get blocked (for
the period configured in `output_module_timeout`) while waiting for the
non-default Outputs to hand over a message down the flow.
It causes troubles in the following discovered scenarios:
1) an Output is deleted from a stream
2) Output's configuration is changed, what implies Output's restart
As result it leads to the default Output (ES Output) getting blocked
until the lock is released after reaching `output_module_timeout`. It
explains 'the visualization stops showing messages' …
> Blocked OutputBufferProcessor on Output update / removal

- graylog2-server/src/main/java/org/graylog2/shared/rest/RequestIdFilter.java
- graylog2-server/src/main/java/org/graylog2/shared/security/ShiroRequestHeadersBinder.java
The ShiroRequestHeadersBinder needs to run before the
ShiroAuthenticationFilter.
Otherwise the X-Graylog-No-Session-Extension header is
not set to the ThreadContext and thus a user session
will be extended by periodical UI requests.
Also ensure removal of request headers from ThreadContext.
Fixes #10577
Co-authored-by: Bernd Ahlers <bernd@graylog.com>
(cherry picked from commit 3de64e993e9c4d7992899a037e46919fe67b49b6)
> Change RequestFilter ordering (#10578)

- graylog2-web-interface/packages/jest-preset-graylog/jest-preset.js
- graylog2-web-interface/packages/jest-preset-graylog/src/timeouts.js
- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.groupBy.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.sort.test.tsx
- graylog2-web-interface/src/views/spec/CreateNewDashboard.it.tsx
- graylog2-web-interface/test/configure-testing-library.js
In a couple of places we need to set custom timeouts for jest tests. In these cases we should take the `TIMEOUT_MULTIPLIER` env variable into account. In order to avoid having to handle that over and over again (parsing, validating, applying it), this change is adding two functions to the `jest-preset-graylog` module:
- `timeoutMultiplier()`: returning the raw multiplier, `1.0` if not
set or not parseable
- `applyTimeoutMultiplier(x: number)`: applies the configured timeout
multiplier to any given timeout
The latter function should be used in tests to apply the multiplier to any custom timeout override.
> Centralize timeout multiplier handling in tests.

- graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/aggregation/AutoIntervalDTO.java
- graylog2-web-interface/src/views/components/visualizations/line/bindings.tsx
- graylog2-web-interface/src/views/logic/aggregationbuilder/visualizations/LineVisualizationConfig.ts
Prior to this PR, when editing the "Messages over time" widget of the "Sources" dashboard, the user immediately ends up in a state where validation is failing due to missing `scaling` and `interpolation` values. Those are missing in the widget we generated in the migration in the first place. Any further editing of the widget results in a valid widget.
This PR is returning a default value (`1.0`) for scaling in the backend if the factor is absent. In addition, when editing a widget with a line chart visualization, it's interpolation value is assigned a default value for the form values if it (or the complete visualization config) is missing.
Fixes #10546.
> Use default values for scaling & interpolation if absent.

- graylog2-web-interface/src/views/components/searchbar/date-time-picker/RelativeRangeSelect.tsx
- graylog2-web-interface/src/views/components/searchbar/date-time-picker/RelativeRangeValueInput.tsx
- graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.test.tsx
- graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx
- graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimerangeDropdown.relativeTimeRange.test.tsx
- graylog2-web-interface/test/fixtures/searchClusterConfig.ts
Before this change it was not possible to temporary empty the relative
range value inputs. When a user tried to remove all numbers, we
automatically inserted a 1. We mainly did this because we are always
updating the form state `onChange`. If we would define for example
`undefined` for the relative range value, we would loose the
information which range type is selected. The range type is
being inferred based on the time range form value.
For example if the form state value for the relative range is 300, the
`RelativeRangeSelect` displays: 5 (range value) minutes (range type).
With this PR we are implementing a separate state for the `RelativeRangeSelect` which controls the
relative range inputs. We are still updating the form state
`onChange`. Every time the form state changes we are …
> Allow emptying relative range value inputs in date time picker when entering new value.

- graylog2-server/src/main/java/org/graylog2/shared/security/ShiroRequestHeadersBinder.java
In https://github.com/Graylog2/graylog2-server/pull/10578 we changed the `REQUEST_HEADERS` `public` access modifier to `private`, causing the cloud master build to fail, since one of the classes uses that constant in its code. This PR reverts that change to fix the build.
> Change back REQUEST_HEADERS access to public

- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.corevisualizations.test.tsx
- graylog2-web-interface/src/views/components/visualizations/heatmap/bindings.tsx
Prior to this change, the defaultValue was required to be set
for a heatmap. But there is no technical reason for that.
This change will set the required field to false and adjust the tests.
> Do not require a defaultValue to be set in Heatmap

- graylog2-web-interface/src/components/messageloaders/RawMessageLoader.tsx
- graylog2-web-interface/src/components/simulator/SimulationResults.jsx
This PR fixes the code formatting Inputs in `RawMessageLoader`, ensuring it does not throw an error while formatting Inputs and that it works as before, even if the `inputs` prop is now an `ImmutableJS.Map` object.
Fixes #10663
> Fix loading of Pipeline simulator page

- graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java
- graylog2-server/src/main/java/org/graylog2/bootstrap/Main.java
- graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java
Our defaults (even with TLS 1.2 and 1.3 only)
were still susceptible to LOGJAM, LUCKY13 and a possible DoS attack.
We programatically use secure defaults for the JDK and for Netty with OpenSSL
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/2202
> Use more secure TLS default ciphers

- graylog2-web-interface/src/components/common/Select.tsx
With this PR we are fixing two problems with the createble select (`common/Select` component with `allowCreate` props):
-  Display "Create value" option label correctly when using `displayKey` select prop.
- Prevent loosing focus when removing content of creatable select input.
Before this change it was possible to loose the react creatable select focus
after removing its content, because we updated the component state unnecessarily.
With this change we ensure that we only update the state when necessary.
> Fix creatable select focus and "create value" option label problem.

- graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.test.tsx
- graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.tsx
When introducing functionality, which limits search execution to the widget which is currently edited, a change was added that performs a search execution when leaving edit mode. Unfortunately the condition which was used to determine if widget editing is left was too broad, so it is performed whenever the widget focusing state changes. This leads to e.g. double search execution when loading a new/saved search.
This PR is changing the condition to check if the previous state indicates widget editing mode and does not perform a new search execution otherwise.
> Prevent unnecessary search execution when unfocusing widget.

- graylog2-web-interface/package.json
- graylog2-web-interface/src/components/content-packs/ContentPackDownloadControl.jsx
- graylog2-web-interface/src/components/streamrules/StreamRuleForm.test.tsx
- graylog2-web-interface/src/pages/ConfigurationsPage.test.tsx
- graylog2-web-interface/src/stores/users/UsersStore.ts
- graylog2-web-interface/src/util/URLUtils.test.ts
- graylog2-web-interface/src/util/URLUtils.ts
- graylog2-web-interface/src/views/bindings.enterpriseWidgets.test.tsx
- graylog2-web-interface/src/views/bindings.fieldActions.test.tsx
- graylog2-web-interface/src/views/bindings.routes.test.tsx
- graylog2-web-interface/src/views/bindings.tsx
- graylog2-web-interface/src/views/bindings.valueActions.test.tsx
- graylog2-web-interface/src/views/components/SearchResult.test.jsx
- graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.tsx
- graylog2-web-interface/src/views/components/messagelist/MessageTableEntry.test.tsx
- graylog2-web-interface/src/views/components/searchbar/TimeRangeInput.test.tsx
- graylog2-web-interface/src/views/components/searchbar/date-time-picker/TabRelativeTimeRange.test.tsx
- graylog2-web-interface/src/views/components/widgets/MessageTable.test.tsx
- graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.ts
- graylog2-web-interface/src/views/logic/fieldactions/AddToAllTablesActionHandler.test.ts
- graylog2-web-interface/src/views/logic/views/ViewStateGenerator.ts
- graylog2-web-interface/src/views/stores/WidgetStore.ts
- graylog2-web-interface/yarn.lock
We are adding credentials to backend API-links in a couple of places to allow the browser to retrieve files directly from the backend. This happens by setting the session id as username, the literal string `session` as password.
This works fine, unless the backend API prefix is a relative URL. In this case invalid URLs are being generated. This makes it impossible for developers to test functionality like this using e.g. `devServer.js`.
This PR is changing this by:
- checking if `AppConfig.gl2ServerUrl()` is a relative URL. If it is, it will be qualified by using scheme, hostname & port from `window.location
- creating a `qualifyUrlWithSessionCredentials` function which can be used to augment any given backend API endpoint with current session credentials. This allows us to centralize …
> Fix and centralize qualifying relative URLs with credentials.

- graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/MetricElement.ts
- graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/SortElement.ts
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/GroupByConfiguration.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/MetricsConfiguration.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/SortConfiguration.tsx
Before this change the widget config form validation was not being
executed when removing an aggregation element. This is only the case
when we define `validateOnChange` for the related `FormikArray` component.
We recently disabled `validateOnChange` for the `FormikArray`s (#10574), because a side effect
was that the validation is being executed twice, when changing a related
input. Because of this conditions the most pragmatic approach is using
`setFieldValue` instead of the `FomikArray` method `remove`. I also
tried defining a `validationSchema` for the form, but it has the same
side effects.
Fixes #10679
> Fix widget config form validation on aggregation element remove.

- graylog2-server/src/test/java/org/graylog/testing/graylognode/MavenPackager.java
Skipping the assembly step improves test time but it's required to
properly build e.g. the jar of the `graylog-storage-elasticsearch7`
module.
Before this change you could end up with broken tests by performing the following steps:
1. `$ mvn clean compile -DskipTests=true -Dskip.web.build -Dforbiddenapis.skip=true -Dmaven.javadoc.skip=true`
1. Run `BackendStartupIT` from your IDE
You'll notice that the test fails because the server doesn't start. The logs show the following error:
```
java.lang.ClassNotFoundException: org.graylog.shaded.elasticsearch7.org.elasticsearch.action.search.SearchResponse
```
> Don't skip assembly step in full backend tests

- graylog2-server/src/main/java/org/graylog2/lookup/LookupTableService.java
- graylog2-server/src/main/java/org/graylog2/lookup/events/AdapterSharedStoresUpdated.java
As detailed in #10665, for DataAdapters where only a single instance is regularly refreshing the contents, we need a way to invalidate the lookuptable caches on all cluster nodes. Otherwise the non-master nodes in the cluster would still run with stale caches and report false lookup values.
This change adds that capability with the `AdapterSharedStoresUpdated` event type.
This has been tested in my local development environment.  Verified that when a Data Adapter sends an `AdapterSharedStoresUpdated` event on the event bus, all other nodes clear the appropriate lookup table caches.
> Add cluster-wide lookup table cache purge

- graylog2-web-interface/src/components/streams/StreamComponent.jsx
Prior to this change, if a user was on page 2 on the stream overview and
he was searching for an item on the first page, nothing was shown.
This change we reset the page when sending the search request which is
the correct behavior.
Fixes #10639 
- Got to Streams Overview
- Go to the second page
- Search for a stream from the first page
> Reset page when searching on steam overview

- graylog2-web-interface/src/components/content-packs/ContentPackSelection.jsx
Prior to this change, when doing a filter on the content pack entity
selection the group selection would still select all entities in the
group.
Now only the filtered entities will be add to the selection.
Fixes #10727
> Group selection on filtered content pack entities

- graylog2-web-interface/src/views/components/visualizations/PlotLegend.test.tsx
- graylog2-web-interface/src/views/components/visualizations/PlotLegend.tsx
Prior to this change, we always displayed the plot legend. But this is
taking valuable space and the description should already mention what is
displayed.
This change tests if there is only one element to display and hides the
plotlegend otherwise. If the widget is in edit mode the plot legend will always be shown so the user can edit the color.
Fixes #10581
- Created a aggregation with only one metric and row pivot
- Added another aggregation with one metric, a row pivot and a column pivot.
> Hide PlotLegend with only one element

- graylog2-web-interface/src/views/components/WidgetComponent.tsx
In #10562, we introduced a more specific way to retrieve field types according to a timerange and stream selection. This is being used to fetch more precise field types for widgets on dashboards. Unfortunately, the `WidgetFieldTypesContextProvider` was used unconditionally to wrap all widgets, even if the current context is that of a Saved Search and not a Dashboard. On Saved Searches, field types are always the same due to the identical root query, therefore we do not need to fetch field types for each individual widget.
This PR is conditionally wrapping the widget component with the widget-specific field types provider if on a dashboard, and a fragment if on a search. This reduces the amound of overall field type requests.
> Avoid fetching widget field types if not on dashboard.

- graylog2-web-interface/src/components/cluster/TrafficGraph.tsx
Prior this change, we displayed the timestamps on the graph in the
timezone of the browser. That was because we gave plotly unix timestamps
without timezone information.
This change will use ISOString format to give plotly the desired
timezone (UTC). This leads to the effect that now time will be
displayed. Which is okay since it should describe a daily summary.
Fixes #10051
> Fix date format in outgoing traffic graphs

- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/MessageExportFormatFilter.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/MessageExportFormatFilterTest.java
The code accidentally matched API browser requests because the path
matching wasn't explicit enough.
This change adds the "api/" prefix to the checked target path and also
switches from "contains" to "endsWith".
> Fix request path matching in MessageExportFormatFilter

- graylog2-web-interface/src/views/components/TypeSpecificValue.tsx
- graylog2-web-interface/src/views/components/Value.tsx
- graylog2-web-interface/src/views/components/messagelist/decoration/ValueRenderer.ts
The `ValueRenderer` type is mainly being used for the `DecoratedValue`
component. The `DecoratedValue` component is using the `type`
prop. Removing the prop makes it easier to reuse the component.
> Removing not needed `type` attribute from message list `ValueRenderer` type

- graylog2-server/src/main/java/org/graylog/security/DefaultPermissionAndRoleResolver.java
- graylog2-server/src/main/java/org/graylog/security/permissions/CaseSensitiveWildcardPermission.java
- graylog2-server/src/main/java/org/graylog2/migrations/V20200803120800_GrantsMigrations/GrantsMetaMigration.java
- graylog2-server/src/main/java/org/graylog2/security/InMemoryRolePermissionResolver.java
- graylog2-server/src/main/java/org/graylog2/security/realm/MongoDbAuthorizationRealm.java
- graylog2-server/src/main/java/org/graylog2/security/realm/RootAccountRealm.java
- graylog2-server/src/main/java/org/graylog2/users/UserImpl.java
- graylog2-server/src/main/java/org/graylog2/users/UserServiceImpl.java
- graylog2-server/src/test/java/org/graylog2/rest/models/users/responses/UserSummaryTest.java
- graylog2-server/src/test/java/org/graylog2/users/UserImplTest.java
- graylog2-server/src/test/java/org/graylog2/users/UserServiceImplTest.java
When introducing the new permissions system in 4.0
we started using object instead of string permissions.
We did not notice that WildcardPermissions are by default case insensitive.
For most cases that didn't make a difference,
but returning the self-editing permissions to a user with a
non-lowercase name would change from something like
`users:edit:HORST` to `users:edit:horst`
Which would break the frontend permission checks
for these cases.
-> Introduce a new `CaseSensitiveWildcardPermission` class
that changes this default.
Fixes: https://github.com/Graylog2/graylog2-server/issues/10700
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#2257
> Make all WildcardPermission case sensitive

- graylog2-web-interface/src/components/streams/StreamList.jsx
Prior to this change, the backend send the streams in alphabetical order
but with regard of case sensitivity. The frontend would then sort the
streams again without case sensitivity which resulted in unsorted
looking streams.
This change will remove the second sorting on the frontend side and rely
on the backend sorting.
Fixes #10639 second part
> Fix sorting of stream overview page

- graylog2-web-interface/src/views/components/aggregationbuilder/AggregationBuilder.tsx
- graylog2-web-interface/src/views/components/aggregationbuilder/AggregationControls.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/AggregationWizard.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/AggregationWizard.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/Visualization.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/WidgetConfigForm.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.groupBy.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.metric.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.sort.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.visualization.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/VisualizationConfigurationOptions.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/configurationFields/InputField.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/configurationFields/NumericField.tsx
- graylog2-web-interface/src/views/components/visualizations/worldmap/WorldMapVisualization.tsx
- graylog2-web-interface/src/views/components/visualizations/worldmap/__tests__/WorldMapVisualization.test.tsx
- graylog2-web-interface/src/views/components/visualizations/worldmap/bindings.tsx
- graylog2-web-interface/src/views/types.d.ts
As described in https://github.com/Graylog2/graylog2-server/issues/10671 the center and zoom level of a map visualization is not being saved anymore, when editing the widget. This error occured because we were maintaining the complete widget config in the `WidgetConfigForm` state. The `WidgetConfigForm` was only responsible for the configuration of aggregation elements (left column in the aggregation wizard builder).
With this PR we are also wrapping the visualization with the `WidgetConfigForm` in the aggregation wizard builder.
The visualization component can update the visualization config by calling the provided `onVisualizationConfigChange` prop. 
We are also:
- implementing the following inputs for the world map visualiztion config form: zoom, center x, center Y.
- adjusting the …
> Fixing world map viewport changes by maintaining related visualization config state in `WidgetConfigForm`.

- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/FieldTypesForStreamsRequest.java
- graylog2-web-interface/src/views/logic/fieldtypes/useFieldTypes.ts
This PR is fixing an issue with the `useFieldTypes` hook being used to retrieve field types for widgets in case where the widget has no custom time range. In these cases a `timerange` of `null` is passed, resulting in a 400 being returned by the backend and no field types being shown in the widget edit form.
This PR is doing two things to improve this:
- Filter out the `timerange` prop from the request if it is `null`
- Accept `null` values for `timerange` and `streams` in the backend
> Fix handling of null timerange when retrieving field types.

- graylog2-web-interface/src/routing/App.tsx
As described in #10756 the content of the aggregation builder can
disappear in Safari. While it is not completely clear what triggers this
behaviour, we can fix it by ensuring that the page content container
always obtains the maximum height.
> Ensure that page content container obtains maximum height (relevant for Safari).

- graylog2-web-interface/src/components/errors/ReportedErrorBoundary.test.tsx
- graylog2-web-interface/src/components/errors/RouterErrorBoundary.test.tsx
- graylog2-web-interface/src/components/errors/RuntimeErrorBoundary.test.tsx
- graylog2-web-interface/src/pages/ConfigurationsPage.test.tsx
- graylog2-web-interface/src/pages/StreamPermissionErrorPage.test.tsx
- graylog2-web-interface/src/pages/UnauthorizedErrorPage.test.tsx
- graylog2-web-interface/src/views/components/WidgetOverrideElements.test.tsx
- graylog2-web-interface/src/views/components/aggregationbuilder/AggregationControls.test.tsx
- graylog2-web-interface/src/views/components/aggregationbuilder/PivotSelect.test.tsx
- graylog2-web-interface/src/views/components/widgets/MessageTable.test.tsx
- graylog2-web-interface/test/fixtures/configurations.ts
- graylog2-web-interface/test/helpers/suppressConsole.ts
This PR is improving the `suppressConsole` usage in tests by:
- wrapping only the necessary code with `suppressConsole`. Before this change the `StreamPermissionErrorPage.test` and `ConfigurationsPage.test` failed silently because the `expect` call was part of the `suppressConsole` callback.
-  always returning a Promise when using `suppressConsole`. In the `ConfigurationsPage.test` we are throwing an error after changing the component state when rendering the component. To handle this error properly we have to wait with the reset of `console.error` until we display the error message.
- always using `await` when using `suppressConsole`. This is now necessary to ensure we are resetting `console.error` in time. But it also ensures that the test fails when we have to use a check (like …
> Improve `suppressConsole` usage in frontend tests and fix two silently failing tests.

- graylog2-web-interface/src/views/components/searchbar/TimeRangeDropdownButton.test.tsx
- graylog2-web-interface/src/views/components/searchbar/TimeRangeDropdownButton.tsx
Before this change we've updated the time range with e.g. `{ from: 300 }`.
This resulted in an error when selecting the `All Time` option.
We are now using the following format: `{ range: 300 }`. With this
format we are updating the time range in the same way like the `TimeRangeDropdown`.
Refs: https://github.com/Graylog2/graylog2-server/pull/10740
- x ] My code follows the code style of this project.
> Use correct time range format when selecting relative range preset in search bar.

- graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchClientConfiguration.java
- graylog2-server/src/main/java/org/graylog2/storage/providers/ElasticsearchVersionProvider.java
- graylog2-server/src/main/java/org/graylog2/storage/versionprobe/VersionProbe.java
- misc/graylog.conf
Adds two parameters to the Elasticsearch (ES) version probe:
- elasticsearch_version_probe_attempts
- elasticsearch_version_probe_delay
If Graylog can not connect to ES on the first try, it retries according to the given parameters.
Especially in container environments, you can not always be sure that all services come up or are ready in a certain order. Graylog is resilient in regard to this problem regarding MongoDB and if you have disabled ES version probing. 
If you want to probe for the ES version and the ES-instance is not ready to connect, this PR adds that you can retry for a certain amount of tries and also specify the interval to wait between connection attempts.
fixes #10580
manually, so far
> With configured Version-probing, wait for ES to come up if not available straight away

- graylog2-server/src/main/java/org/graylog2/inputs/transports/HttpPollTransport.java
Fix for issue #9941 
As the ScheduledExecutorService stops any further execution when it received an Exception once, a HTTP response other than 2XX should be logged, but no exception should be thrown.
Additionally a return was missing in the Throttling section of this transport class.
Changed RuntimeException to LOG.error-statement to allow further executions of the scheduled task.
Fix for issue #9941
> Prevent HTTPPollTransport from stopping on non 2XX

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndicesAdapterES6.java
- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/indices/GetSingleAlias.java
- graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java
- graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
Prior to this change, retrieving the index sets (and their wildcards) containing reopened indices was broken, due to a number of issues.
This PR is fixing:
- retrieving the list of targets for an index wildcard
- checking if an index set wildcard contains reopened indices
This unbreaks the indices overview page after multiple indices were restored.
Fixes #10572.
> Fix handling of reopened indices and their aliases.

- graylog2-web-interface/package.json
- graylog2-web-interface/src/views/components/aggregationwizard/AggregationWizard.tsx
- graylog2-web-interface/src/views/components/visualizations/ColorMapper.ts
- graylog2-web-interface/src/views/components/visualizations/GenericPlot.tsx
- graylog2-web-interface/src/views/components/visualizations/PlotLegend.tsx
- graylog2-web-interface/src/views/components/visualizations/area/AreaVisualization.tsx
- graylog2-web-interface/src/views/components/visualizations/bar/BarVisualization.tsx
- graylog2-web-interface/src/views/components/visualizations/line/LineVisualization.tsx
- graylog2-web-interface/src/views/components/visualizations/scatter/ScatterVisualization.tsx
- graylog2-web-interface/src/views/logic/searchtypes/events/EventHandler.test.ts
- graylog2-web-interface/src/views/logic/searchtypes/events/EventHandler.ts
- graylog2-web-interface/src/views/logic/searchtypes/events/__snapshots__/EventHandler.test.ts.snap
Before the change the event annotation color was not stable from the
beginning since it was not taking its color from the color mapper.
This PR will use the color mapper to add the color of the event
annotation.
Fixes #10340
- Create a histogram
- activate event annotation
- change the color of the event annotation
> Use ColorMapper for event annotations

- graylog2-web-interface/src/views/components/WidgetQueryControls.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/AggregationWizard.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/ElementsConfigurationActions.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/WidgetConfigForm.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/WidgetConfigForm.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.corevisualizations.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.groupBy.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.metric.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.sort.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.visualization.test.tsx
- graylog2-web-interface/src/views/components/contexts/ValidationStateContext.tsx
- graylog2-web-interface/src/views/components/contexts/ValidationStateProvider.tsx
- graylog2-web-interface/src/views/components/contexts/WidgetEditApplyAllChangesContext.tsx
- graylog2-web-interface/src/views/components/contexts/WidgetEditApplyAllChangesProvider.tsx
- graylog2-web-interface/src/views/components/searchbar/SearchBarForm.tsx
- graylog2-web-interface/src/views/components/searchbar/StreamsFilter.jsx
- graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.tsx
- graylog2-web-interface/src/views/components/widgets/SaveOrCancelButtons.tsx
- graylog2-web-interface/src/views/components/widgets/Widget.aggregations.test.tsx
- graylog2-web-interface/src/views/components/widgets/Widget.test.tsx
- graylog2-web-interface/src/views/components/widgets/Widget.tsx
- graylog2-web-interface/test/fixtures/searches.ts
Before this change we were only saving changes, when clicking on the “Save” button in the aggregation builder, which already have been applied by clicking the:
- search submit button, for widget search controls changes (on a dashboard)
- “Apply changes” button, for widget aggregation element changes.
With this PR we are always saving every valid search control and aggregation element change, when the user is saving the widget. Furthermore we:
- Renamed the aggregation elements “Apply Changes” button to “Update preview” and unified the background color with the search controls submit button.
- Renamed the widget edit “Save” button to “Apply Changes”
This way it is easier to understand what effect each button has.
Fixes: https://github.com/Graylog2/graylog2-server/issues/10560
> Always apply all widget changes when saving aggregation builder.

- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.corevisualizations.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/VisualizationElement.ts
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/ElementConfigurationContainer.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/VisualizationConfiguration.tsx
When changing the visualization type of a widget from any visualization that does not support event annotations to one that does, the event annotation checkbox becomes unusable. This is due to it being initialized with a value of `undefined`, which makes it work in an uncontrolled way. Toggling it afterwards provides a value, switching it over to a _controlled_ input, making future toggling impossible.
This change makes sure that a valid value is always passed to the checkbox, even if it's current state is `undefined`.
Fixes #10772.
> Prevent event annotation checkbox to go uncontrolled.

- graylog2-web-interface/src/components/common/ReactGridContainer.jsx
Before this change it was possible to resize and drag widgets in the widget grid when the grid is "locked", like in the dashboard full screen mode. With this change we ensure that widgets can not be dragged or resized when the widget grid is locked.
> Disable widget resizing and dragging when widget grid is locked.

- graylog2-web-interface/src/views/components/searchbar/TimeRangeDropdownButton.tsx
- graylog2-web-interface/src/views/components/searchbar/TimeRangeInput.test.tsx
- graylog2-web-interface/src/views/components/searchbar/TimeRangeInput.tsx
This PR is introducing a `showPresetDropdown` prop for the `TimeRangeInput` component, allowing to show/hide the preset dropdown button. This is useful when this component is reused in places where it is used to select a time range, but it is not desired for the change to have an immediate effect.
> Allow hiding preset dropdown of date time picker.

- graylog2-web-interface/src/views/components/aggregationbuilder/EmptyAggregationContent.tsx
This PR is fixing the layout of the empty aggregation content shown when
a new aggregation with empty configuration is added. Prior to this PR,
the widget's time range was not shown at the bottom right of the frame
on a dashboard and the content was not properly centered. This is fixed
in this PR.
Before:
After:
> Fixing layout of empty aggregation.

- graylog2-web-interface/src/views/components/AdaptableQueryTabs.tsx
- graylog2-web-interface/src/views/components/WidgetContainer.tsx
- graylog2-web-interface/src/views/components/widgets/WidgetHeader.jsx
Before this change the widget focus / edit container had a higher `z-index` than:
- the sidebar overlay
- the search bar streams filter
This PR is fixing both problems by defining a lower `z-index` for the widget focus.
Tested with Chrome, Safari , Firefox and IE11 (because we added the `WidgetActionDropdown` in an IE11 related PR.)
> Reduce `z-index` of widget focus container to fix stack order problem with sidebar and search bar streams filter.

- graylog2-web-interface/src/components/common/Select.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.corevisualizations.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.groupBy.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.metric.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.sort.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.visualization.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/FieldSelect.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/Metric.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/Sort.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/VisualizationConfiguration.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/configurationFields/SelectField.tsx
- graylog2-web-interface/src/views/components/widgets/Widget.aggregations.test.tsx
- graylog2-web-interface/src/views/components/widgets/Widget.test.tsx
**Please note, this Pr is based on https://github.com/Graylog2/graylog2-server/pull/10672 which needs to be merged first.**
Before this change a menu of an element configuration select could
be cut off by their container. Opening a menu resulted in a scroll bar when
the select is at the bottom of the aggregation elements column and the
dropdown is too large.
With this change we are displaying the dropdown in a portal to display it
independently from the container. We are also defining the option `menuPlacement="auto"` for each aggregation element select, for a more dynamic placement.
I tried using aggregation wizard container for the select portals instead of using `document.body`. But it resulted in a strange placement of the menus
Using the aggregation wizard container would make the …
> Improving overflow of select menus in aggregation elements column of aggregation wizard.

- graylog2-server/src/main/java/org/graylog2/lookup/adapters/dsvhttp/HTTPFileRetriever.java
Currently, when the `HTTPFileRetriever` includes the `If-Modified-Since` header and the file has not been changed, it returns `null` and fails to close the OkHttp `Response`.  This change ensures the `Response` object gets closed on any non-successful HTTP response code, including 304 Not Modified.
Tested locally by setting the URLhaus data adapter to refresh on a 2 minute interval, guaranteeing a 304 response.  Verified in the debugger that the OkHttp `Response` object was being closed and that there were no warning log messages about leaked connections.
> Close response on all non-successful response codes

- graylog2-web-interface/src/views/components/AdaptableQueryTabs.tsx
- graylog2-web-interface/src/views/components/QueryTabs.tsx
This is a tiny styling fix that just cleans up styling and through this adds a pixel of space below the query tabs in order to prevent its lower border overlapping with the widget borders below it.
Before:
After:
> Adding a pixel of space below query tabs.

- graylog2-web-interface/src/views/stores/ViewStore.ts
With this change we are defining the active query based on `view.search.queries` instead on `view.state`.
This way we can ensure that the active query (responsible for the active dashboard page) is always the first query.
Fixes https://github.com/Graylog2/graylog2-server/issues/10787
> Always define first search query as active query when loading view.

- graylog2-server/src/main/java/org/graylog2/storage/versionprobe/Error.java
- graylog2-server/src/main/java/org/graylog2/storage/versionprobe/ErrorResponse.java
- graylog2-server/src/main/java/org/graylog2/storage/versionprobe/VersionProbe.java
Prior to this PR, the error messages of version probe request responses returning a non-200 were silently swallowed. This prevented being able to find out e.g. if an authentication error during version probing happened.
This change is now parsing the error response which is returned by ES, passing the error message to a custom error consumer during version probing. This leads to better error messages, e.g. for an authentication error:
```
2021-06-04 11:51:58,133 ERROR: org.graylog2.storage.versionprobe.VersionProbe - Unable to retrieve version from Elasticsearch node localhost:9200: Error response: type: security_exception - reason: unable to authenticate user [elastic] for REST request [/]
2021-06-04 11:51:58,215 ERROR: org.graylog2.storage.versionprobe.VersionProbe - Unable to retrieve …
```
> Improving error logging for failed version probe requests.

- UPGRADING.rst
Added a description for the changed default behavior with Elasticsearch on startup: now it retries in a given interval until a connection can be made if version probe is enabled.
Doc was missing in the already merged PR
> Updated UPGRADING.rst for new Elasticsearch behavior: retry connecting on startup

- graylog2-server/src/main/java/org/graylog/metrics/prometheus/PrometheusExporterConfiguration.java
- misc/graylog.conf
The previous port has been grabbed by someone else in the meantime. The
new port has been added to the Prometheus default port allocations wiki
page now.
> Update Prometheus exporter default port

- graylog2-server/src/main/java/org/graylog2/rest/RestTools.java
- graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationBrowserResource.java
- graylog2-server/src/main/java/org/graylog2/shared/rest/resources/documentation/DocumentationResource.java
- graylog2-server/src/main/java/org/graylog2/web/DevelopmentIndexHtmlGenerator.java
- graylog2-server/src/main/java/org/graylog2/web/ProductionIndexHtmlGenerator.java
- graylog2-server/src/main/java/org/graylog2/web/resources/AppConfigResource.java
- graylog2-server/src/main/resources/swagger/lib/shred.bundle.js
Prior to this change, all web interface assets as well as all URLs going to the backdend REST API were qualified according from the following data points, in order of precedence:
- The `X-Graylog-Server-URL` header of the request
- The `http_external_uri` config setting
- The `http_publish_uri` config setting
The result of this is used as the "effective external URI".
While this helps us supporting a couple of scenarios where the Graylog server is accessed through a reverse proxy, it also produces issues when naming schemes are different internally and externally and access from both directions is desired. The only scenario which works in these cases is configuring a valid `http_publish_uri`/`http_external_uri` for internal and using the `X-Graylog-Server-URL` on the proxy for external …
> Use relative URLs for web interface assets served by Graylog server and backend API.

- graylog2-web-interface/src/views/components/Search.tsx
- graylog2-web-interface/src/views/components/SearchResult.tsx
- graylog2-web-interface/src/views/components/messagelist/HighlightMessageInQuery.test.tsx
- graylog2-web-interface/src/views/components/messagelist/HighlightMessageInQuery.tsx
- graylog2-web-interface/src/views/logic/hooks/SearchRefreshCondition.ts
- graylog2-web-interface/src/views/stores/ViewMetadataStore.ts
This PR is avoiding rendering the `SearchResult` component if the `hasErrors` flag is set. This flag is introduced in this PR and is set by the function which handles the response of the search parsing call.  This can be used e.g. to avoid showing the rendering result when there are undeclared parameters present.
> Introducing `hasErrors` flag and prevent showing search result if set.

- pom.xml
This bumps our bouncycastle dependencies to the most recent version.
Prevents downgrading of transitive bouncycastle dependencies e.g. in https://github.com/Graylog2/graylog-plugin-enterprise/pull/2278.
> Update bouncycastle to version 1.69

- graylog2-web-interface/src/components/common/Pagination.tsx
- graylog2-web-interface/src/components/common/__snapshots__/Pagination.test.jsx.snap
- graylog2-web-interface/src/views/components/WidgetContainer.tsx
Before this change it was possible that the active item of the message
table pagination is still visible when focusing a different widget.
This change is fixing the problem by slightly increasing the widget
focus container and reducing the pagination z-index.
Fixes: https://github.com/Graylog2/graylog2-server/issues/10793
> Adjust widget focus and pagination z-index to fix stacking problem.

- graylog2-web-interface/src/views/components/searchbar/RangePresetDropdown.test.tsx
- graylog2-web-interface/src/views/components/searchbar/RangePresetDropdown.tsx
Before this change we called the `onChange` prop of the `RangePresetDropdown` when selecting the `Configure Ranges` link, which is part of the dropdown. As a result we defined:
- an invalid time range for the search bar form when selecting a relative range preset.
- the range "0 Days" for a range in the date time picker.
With this change we are only opening the configuration page when clicking on `Configure Ranges`.
Fixes #10835
> Do not set time range when selecting `Configure Ranges` option in `RangePresetDropdown`.

- graylog2-web-interface/src/views/components/AdaptableQueryTabs.tsx
- graylog2-web-interface/src/views/components/QueryBar.test.tsx
- graylog2-web-interface/src/views/components/QueryBar.tsx
- graylog2-web-interface/src/views/components/queries/QueryTitle.tsx
In #10739, the queries/query id structures were changed to ordered sets.  Unfortunately, this change was not reflected in the code that handles closing dashboard tabs, so it called `indexOf` which is not present on an ordered set.
This change is now fixing this by converting the set of indices to an indexed sequence before calling `indexOf`. In addition, it disables the menu item to close a dashboard tab if there is only a single dashboard tab present.
Fixes #10834.
> Fix closing dashboard tabs.

- graylog2-web-interface/src/views/components/visualizations/heatmap/bindings.tsx
Prior to this change, if the user switched back from using min and max
values to auto scale the auto scale setting was ignored and instead min
and max were still used.
That is because plolty does not know of a auto scale option but only the
absense of min and max.
This change will clear the values min and max when auto scale is used.
- Edit a heatmap to use min and max instaed of auto scale
- switched back to auto scale
- 
- profit
> Heatmap: Clear min and max on auto scale use

- graylog2-web-interface/src/views/components/messagelist/decorators/DecoratorSummary.jsx
Prior to this change, the decorator action menu was cut off to the left
side in the Message Table edit modus. The problem exists since we
display the edit modus in focus mode.
This change will remove the `pullRight` prop from the drop down
component to let the menu open up to the right side.
Fixes #10841
> Decorator action menu cut off

- graylog2-web-interface/src/views/components/visualizations/PlotLegend.test.tsx
- graylog2-web-interface/src/views/components/visualizations/PlotLegend.tsx
Prior to this change, the Plot legend would render the column roll-up
label as Value action and with that the user would get a menu offered
which would not really make sense.
This change will try to find out if the label it renders is a series
function and will not render it with Value Actions.
This fixes also a problem that when multiple series where selected by
the user the value actions did got presented even though they were
broken.
If the series function will be renamed to a value which exists in the
chart as a value, the value is not clickable and the plot legend will
only display the label one time (as does plotly renders the it).
Fixes #10840
> Do not render column roll-up label as value action in PlotLegend

- graylog2-web-interface/src/views/components/visualizations/PlotLegend.test.tsx
- graylog2-web-interface/src/views/components/visualizations/PlotLegend.tsx
- graylog2-web-interface/src/views/components/visualizations/pie/PieVisualization.tsx
Prior to this change, we wanted to hide the legend if only one label
was presented to the user. The evaluation of that state did not take
into account that the pie chat needs to always show the labels.
This change will add a neverHide flag to the PlotLegend component and
that flag will be used by the PieChart component.
This PR also adds field value actions for the pie chart legend.
Fixes #10837
Refs https://github.com/Graylog2/graylog2-server/issues/6612
- Create a Pie Chart with top values widget and see that the Legend is presented
- The histogram still does not show the legend
> Do not hide legends for pie charts

- graylog2-web-interface/src/views/components/messagelist/decorators/AddDecoratorButton.jsx
- graylog2-web-interface/src/views/components/messagelist/decorators/DecoratorSummary.jsx
- graylog2-web-interface/src/views/components/messagelist/decorators/PopoverHelp.tsx
- graylog2-web-interface/src/views/components/messagelist/decorators/decoratorStyles.css
This change is fixing minor styling/theming issues in the decorator configuration components. When adding a decorator, the configuration box was not themed properly, resulting in poor contrast if the dark theme is active. The help box was misaligned, resulting in being cut off.
Before:
After:
Fixes: https://github.com/Graylog2/graylog2-server/issues/10553
> Fixing minor styling/theming issues in decorator configuration.

- graylog2-web-interface/src/util/conditional/HideOnCloud.test.tsx
- graylog2-web-interface/src/util/conditional/HideOnCloud.tsx
We recently wrapped some menu items in the system menu dropdown with the `HideOnCloud` component.
One side effect was that we no longer closed the dropdown when selecting any wrapped menu item.
The reason:
When defining a child for the `react-bootstrap` component `NavDropdown`, the child automatically receives props like `active`, `onKeyDown`, `onSelect`. By wrapping a menu item in the system menu drop down with `HideOnCloud`, the component `HideOnCloud` receives these props, but not its children.
This PR is fixing the bug by forwarding the props.
Fixes: https://github.com/Graylog2/graylog2-server/issues/10830
> Always close system menu when selecting link in system menu dropdown.

- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.groupBy.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.metric.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.sort.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/GroupByElement.test.ts
- graylog2-web-interface/src/views/components/aggregationwizard/aggregationElements/GroupByElement.ts
As described in https://github.com/Graylog2/graylog2-server/issues/10858 it is currently not possible to remove all groupings of an aggregation element. This error occurred because we removed the `goupby` key of the `WidgetConfigForm` state when removing all groupings. We are only considering aggregation element changes on submit when its key exists in the form state.
I thought about a solution which ensures we are not having a similar problem in the future, e.g. when adding an aggregation element. But I could not find a good one, since I prefer to only consider aggregation element changes when their key exists in the form sate. Currently we can just ensure this error is not occurring for our existing aggregation elements, by writing a unit test for each one.
Fixes …
> Fixing deletion of all groupings of an aggregation.

- graylog2-web-interface/src/views/components/visualizations/number/Trend.test.tsx
- graylog2-web-interface/src/views/components/visualizations/number/Trend.tsx
Prior to this PR, if the value of the previous time range used for trend calculation returns a value of `0`, the trend was shown as `+0 / +0%`, due to a wrong check in the calculation (it checks if `previous` is set, but does a simple truthyness check which fails if `previous === 0`).
This PR fixes this and also adds conditional rendering of absolute and relative trend parts depending on if difference / difference in percent are finite or not. In addition, a tooltip is added that show the absolute previous value.
Before:
After:
(relative trend is left out if `previous` is `0`, because the difference in percent results in `NaN`)
> Fixing trend calculation in numeric vis if previous value is 0.

- graylog2-web-interface/src/stores/__tests__/EqualityCheck.fixtures.ts
- graylog2-web-interface/src/views/logic/aggregationbuilder/AggregationWidgetConfig.ts
- graylog2-web-interface/src/views/logic/aggregationbuilder/visualizations/NumberVisualizationConfig.ts
- graylog2-web-interface/src/views/logic/aggregationbuilder/visualizations/VisualizationConfig.ts
- graylog2-web-interface/src/views/stores/isEqualForSearch.test.tsx
Prior to this PR, when enabling only the boolean `trend` setting of a numeric visualization and nothing else, we did not generate a new search and the `trend` search type was not retrieved. This lead to empty trending information. The root cause of this was that we generally leave out the `visualization` and `visualizationConfig` keys of an aggregation config when determining equality to decide if we need a new search or not.
This change is now implementing `equalsForSearch` methods in the `VisualizationConfig` classes (defaulting to return `true`, as visualization configs should generally not need to generate a new search) and in `NumberVisualizationConfig` (returning a boolean depending on the presence and value of the `trend` setting of both configs). Also, the `visualizationConfig` …
> Generate new search when only `trend` setting is changed.

- graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.test.tsx
- graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.tsx
Prior to this change, we did only update all searches after we left the
focus mode from editing. But when we switched a message table to a log
view and unfocused the log view other widgets were not part of the newly
generated search result.
This change will update all widgets after leaving the unfocusing mode.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/2359
> Always update all widgets after unfocusing

- graylog2-web-interface/src/components/permissions/SharedEntitiesOverview/SharedEntitiesFilter.tsx
- graylog2-web-interface/src/logic/permissions/mocked.tsx
**Please note: we need backport this bugfix to 4.0**
Before this change we provided the wrong query parameter value when
filtering the shared entities overview by saved searches.
As a result the API response was always empty, when applying this filter.
Fixes: https://github.com/Graylog2/graylog2-server/issues/10878
> Fixing shared entities overview filter for saved searches.

- UPGRADING.rst
- graylog2-server/src/main/java/org/graylog2/indexer/searches/Searches.java
Pre 4.x, a limit of `0` was interpreted as `no_limit` in the legacy-API. This changed in the background to `-1` for other functionality in 4.0
For the legacy-API, this PR changes the semantics back.
For the following legacy-API endpoints, some of the underlying search-methods have been tagged as ``@deprecated``.
``/search/universal/absolute*`` 
``/search/universal/keyword*``     
``/search/universal/relative*`` 
fixes #9817
> NO_LIMIT was 0 pre 4.x and is now -1 in Legacy API

- graylog2-web-interface/src/views/components/WidgetQueryControls.tsx
- graylog2-web-interface/src/views/components/searchbar/SearchBarForm.tsx
- graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeLivePreview.tsx
- graylog2-web-interface/src/views/components/widgets/Widget.aggregations.test.tsx
As described in https://github.com/Graylog2/graylog2-server/issues/10885 there is currently a bug, when updating the time range of a dashboard widget by using the "Apply Changes" button. This bug does not occur when a user applies the time range changes, by executing the search first.
The bug occurred because we were not normalizing the widget time range correctly. This PR by always normalizing the dashboard widget time range, no matter if the changes are being applied by clicking on the search or "Apply Changes" button.
Fixes: https://github.com/Graylog2/graylog2-server/issues/10885
> Always normalize dashboard widget time range correctly when updating widget.

- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MessagesAdapterES7.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ElasticsearchInstanceES7.java
Between ES 7.8.0 and 7.10.1, the error messages returned by the server for these case:
- a message cannot be ingested to an index because the index/cluster is in flood stage
- a message cannot be ingested to an alias, because the alias is missing a target
have changed. Therefore our error checking code does not identify these cases as being retriable, resulting in message loss.
This PR addresses these cases and adds the changed error messages in addition to the previous ones in order to support both versions.
This circumstance could have been detected if our integration tests would have used newer versions of ES for testing. Therefore, the ES version for the tests was bumped. In the future, we should complete our plans to run integration tests against a matrix of versions, including …
> Adjusting to changed error messages in ES7 for flood stage/missing alias target

- graylog2-server/src/main/java/org/graylog2/shared/buffers/DirectMessageHandler.java
- graylog2-server/src/main/java/org/graylog2/shared/buffers/JournallingMessageHandler.java
- graylog2-server/src/main/java/org/graylog2/shared/buffers/RawMessageEvent.java
Even though the input ring buffer is capped, the unreleased references occupy memory which could be used otherwise. The fix covers both scenarios: with and without journalling.
> Releasing objects retained by RawMessageEvents

- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/MessagesAdapterES7.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ElasticsearchInstanceES7.java
**Note:** This is a backport of #10889 to `4.0`.
Between ES 7.8.0 and 7.10.1, the error messages returned by the server for these case:
- a message cannot be ingested to an index because the index/cluster is in flood stage
- a message cannot be ingested to an alias, because the alias is missing a target
have changed. Therefore our error checking code does not identify these cases as being retriable, resulting in message loss.
This PR addresses these cases and adds the changed error messages in addition to the previous ones in order to support both versions.
This circumstance could have been detected if our integration tests would have used newer versions of ES for testing. Therefore, the ES version for the tests was bumped. In the future, we should complete our plans to run integration …
> Adjusting to changed error messages in ES7 for flood stage/missing alias target (4.0)

- graylog2-server/src/main/resources/prometheus-exporter.yml
Fixes #10904 
Replaces hyphens with underscores in the default core [prometheus-exporter.yml](https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/resources/prometheus-exporter.yml) mappings file.
> Replace hyphens with underscored in metric names

- graylog2-server/src/main/java/org/graylog/security/authservice/test/AuthServiceBackendTestService.java
Provide a user-friendly error message when testing the connection to an auth service backend.
Avoid logging an exception, when the service is merely misconfigured.
This is related to PR [enterprise/2403](https://github.com/Graylog2/graylog-plugin-enterprise/pull/2403)
> Improve error logging for auth service connection test

- graylog2-server/src/main/java/org/graylog2/streams/StreamDTO.java
Streams have a `matching_type` field, which got introduced in version `1.2.0` with https://github.com/Graylog2/graylog2-server/commit/a7bac4a1f05c823fd4c8487eeb0116319d35cfae. 
Streams which have been created before that wouldn't have that field set in MongoDB. This is gracefully handled by adding a default value, when the field is missing.
When pagination was added to the streams page in version `4.0.0` it wasn't considered that very old records could have the field missing. This would break the "streams" page.
This PR aims at fixing that by setting a default value for `matching_type` when de-serializing a stream from MongoDB for pagination.
Fixes #10514
> Set default value for matchingType in StreamDTO

- graylog2-web-interface/src/components/common/ControlledTableListHeader.jsx
- graylog2-web-interface/src/components/graylog/ListGroupItem.jsx
**Please note this PR needs a backport for 4.1**
In the past we had to adjust the structure of our `ListGroupItem` component, to be able to easily create a reference.
This resulted in a UI bug in the saved searches list and comparable lists. https://github.com/Graylog2/graylog2-server/pull/10809. Although we fixed this bug, the bugfix introduced another UI problem for lists like the content packs overview.
Before:
This PR is adjusting the `ListGroupItem` styling in a way that works for all different list types. After:
Fixes: https://github.com/Graylog2/graylog2-server/issues/10884
I tested the different list types with chrome, safari and firefox.
> Fixing floating of `ListGroupItem`s in `ListGroup`.

- graylog2-web-interface/src/views/components/datatable/MessagesTable.jsx
- graylog2-web-interface/src/views/components/widgets/MessageTable.tsx
Before this change the message table and data table widget had some not need spacings.
Removing these spacings unifies the styling with other widgets and for different browser.
Before: 
After:
Fixes https://github.com/Graylog2/graylog2-server/issues/7429
> Removing not needed spacings in data table and message table widget.

- graylog2-web-interface/src/components/permissions/SharedEntitiesOverview/SharedEntitiesFilter.jsx
- graylog2-web-interface/src/logic/permissions/mocked.js
_This is a backport of #10880 for 4.0._
Before this change we provided the wrong query parameter value when
filtering the shared entities overview by saved searches.
As a result the API response was always empty, when applying this filter.
Refs: https://github.com/Graylog2/graylog2-server/issues/10878
> Fixing shared entities overview filter for saved searches. (Backport of #10880 for 4.0)

- graylog2-web-interface/src/views/components/common/EditableTitle.tsx
Before this change it was that the widget header elements are displayed in three rows, depending on the widget title length.
With this change we ensure that all elements are displayed "inline".
Before:
After:
> Always display widget title in line with drag handle and widget actions.

- graylog2-web-interface/packages/jest-preset-graylog/jest-preset.js
- graylog2-web-interface/packages/jest-preset-graylog/src/setup-files/mock-moment-timezone.js
- graylog2-web-interface/src/views/components/widgets/Widget.aggregations.test.tsx
Before this change it was possible that `moment.tz.guess()` returns a different time zone, when running the frontend tests, depending the environment (e.g. local dev environment vs. GitHub actions).
To avoid this problem in the future we are now mocking the moment time zone for all tests.
> Mock moment time zone for all tests.

- graylog2-web-interface/src/components/common/Select.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/FieldSelect.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/Metric.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/Sort.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/VisualizationConfiguration.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/configurationFields/SelectField.tsx
**Please note:  This PR needs to be merged together with https://github.com/Graylog2/graylog-plugin-enterprise/pull/2399**
With this PR we are changing the default for the `menuPlacement` prop of the common `Select` component from `bottom` to `auto`. When a select menu can not be displayed at the bottom of a select, because of the browser window height, it will be display at the top instead.
Before (opening menu creates a scroll bar):
After: 
Tested with different use cases.
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/2399
> Configure more dynamic default menu placement for `Select` component.

- graylog2-web-interface/src/views/components/widgets/WidgetActionsMenu.tsx
With this PR we are changing the placement of the widget edit action. The widget edit action is now a widget action icon instead of a menu item in the widget action menu. This way the user needs less clicks to edit a widget.
We are also changing the position of the widget stretch icon, mainly to keep the placement of most other icons consistent when focusing a widget (and hiding the stretch icon).
Before:
After:
> Display widget edit action as action icon instead of menu item in widget actions dropdown.

- graylog2-web-interface/src/components/event-definitions/event-definition-form/NotificationsForm.jsx
Users that do not have **Alerts Manager** role assigned but have instead **Event Definition Creator** and **Event Notification Creator** assigned are not able to choose a notification because the permission **eventnotifications:read** is missing.
As both roles (**Alerts Manager** and **Event Notification Creator**) have the permission **eventnotifications:create** this will allow users with with the roles **Event Definition Creator** and **Event Notification Creator** to choose a notification
1. create user with roles Reader, User Inspector, Event Definition Creator and Event Notification Creator
2. create a notification
3. create an event definition
4. choose a notification
Needs backport to 4.0.x
> Fix permission check for notifications in event definitions for non alert managers

- graylog2-web-interface/src/views/Permissions.js
- graylog2-web-interface/src/views/bindings.tsx
As described in https://github.com/Graylog2/graylog2-server/issues/9904 we migrated the legacy views permissions defined in https://github.com/Graylog2/graylog2-server/blob/master/graylog2-server/src/main/java/org/graylog/plugins/views/migrations/LegacyViewsPermissions.java but some of them still exist in the frontend code.
With this PR we are removing the legacy views permissions. There are still some legacy permissions in `event-definition-types/FilterForm` which will be removed with https://github.com/Graylog2/graylog2-server/pull/10933
Fixes: https://github.com/Graylog2/graylog2-server/issues/9904
> Removing legacy usage view permissions `extendedsearch:use` and `view:use` in the frontend.

- graylog2-web-interface/packages/eslint-config-graylog/index.js
- graylog2-web-interface/src/polyfill.js
This PR adds the `IntersectionObserver` polyfill to the polyfill list of the `eslint-config-graylog` package. Without this change ESLint does not know about the `IntersectionObserver` polyfill and throws a warning, because of the [compat/compat](https://github.com/amilajack/eslint-plugin-compat/blob/master/docs/rules/compat.md) rule.
> Include `IntersectionObserver` polyfill in `eslint-config-graylog` polyfill list.

- misc/graylog.conf
Add a sample configuration for the `allowed_auxiliary_paths` configuration property in the default `graylog.conf` file, which was originally added in https://github.com/Graylog2/graylog2-server/pull/10244
Documentation has also been provided in https://github.com/Graylog2/documentation/pull/1185.
This configuration property was discussed yesterday in the context of investigating a Cloud-related issue. I thought that it would be good to provide a sample configuration and documentation for this property, so that others can see a description for the property and an example for how to configure it.
No testing needed. Just static file changes in the default `graylog.conf`, which are commented out. 
- [*] My code follows the code style of this project.
- [*] My change requires a change to the …
> Add allowed_auxiliary_paths to default server.conf file

- graylog2-server/src/main/resources/swagger/lib/shred.bundle.js
**Note:** This needs to be backported to `4.1`.
When only a relative URL is provided for the API, the scheme is `undefined` in the API browser when making requests. This leads to defaulting to HTTP, even if the API browser is accessed via HTTPS.
This PR is changing this to use the protocol of the current location if the scheme is missing.
Fixes #10952.
> Use protocol of current url for api browser, if scheme is missing.

- .github/dependabot.yml
This change is disabling automatic rebasing for dependabot's update PRs.  The motivation for this is to reduce the number of running builds on our CI due to rebased PRs, whenever one of the package management configuration files are touched. Most of these rebases are unnecessary, especially for PRs which take longer to review.
In order to trigger a rebase manually for PRs, a simple
```
@dependabot rebase
```
as a PR comment is enough.
> Disable automatic rebasing for dependency update PRs.

- graylog2-server/src/main/resources/prometheus-exporter.yml
While coping with https://github.com/Graylog2/forwarder/issues/32 it turned out that the Forwarder gRPC server-side metrics are declared with a wrong package name resulting into having no metrics for the gRPC calls. This PR addresses this issue and also removes irrelevant Forwarder client-side metrics.
> Missing Forwarder gRPC server-side metrics

- graylog2-web-interface/src/views/components/visualizations/heatmap/bindings.tsx
Prior to this change, some user expierenced problems with heat maps when
the heat map did not have a visualization config.
This change will provide a default if no visualization config was
persisted.
Fixes #10928
Fixes #10967
> Provide default if no visualization config was provided for Heatmap

- graylog2-server/src/main/java/org/graylog/plugins/beats/BeatsTransport.java
- graylog2-server/src/main/java/org/graylog/security/authservice/ldap/UnboundLDAPConnector.java
- graylog2-server/src/main/java/org/graylog2/Configuration.java
- graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java
- graylog2-server/src/main/java/org/graylog2/bootstrap/ServerBootstrap.java
- graylog2-server/src/main/java/org/graylog2/commands/Server.java
- graylog2-server/src/main/java/org/graylog2/configuration/TLSProtocolsConfiguration.java
- graylog2-server/src/main/java/org/graylog2/inputs/transports/HttpTransport.java
- graylog2-server/src/main/java/org/graylog2/inputs/transports/SyslogTcpTransport.java
- graylog2-server/src/main/java/org/graylog2/inputs/transports/TcpTransport.java
- graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java
- graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java
- graylog2-server/src/main/java/org/graylog2/shared/security/tls/DefaultTLSProtocolProvider.java
- graylog2-server/src/test/java/org/graylog/plugins/beats/BeatsTransportTest.java
- graylog2-server/src/test/java/org/graylog/security/authservice/ldap/UnboundLDAPConnectorTest.java
- graylog2-server/src/test/java/org/graylog/security/authservice/ldap/UnboundLDAPConnectorTestTLSIT.java
- graylog2-server/src/test/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransportTest.java
The changes made in #10653 also apply to cases where Graylog
uses TLS as a client.
This makes it impossible to create TLS connections
to legacy software that is only supporting old and insecure ciphers.
Most prominently ES 6.8.x
This changes gives the user the possiblity to re-enable old cipher
suites by changing our default and allowing TLS protocols < 1.2.
This can be done with the `enabled_tls_protocols` setting.
E.g. by setting `enabled_tls_protocols=TLSv1.1, TLSv1.2`
This change had to introduce a separate configuration bean,
to avoid triggering anything that might initialize the default SSLContext.
As for example would the MongoDBConfiguration.validat() method do.
Fixes #10944
/jenkins-pr-deps  Graylog2/graylog-plugin-enterprise#2427,Graylog2/graylog-plugin-enterprise-integrations#58 …
> Only restrict TLS to secure ciphers with TLS1.2 or greater

- graylog2-server/src/main/resources/swagger/lib/shred.bundle.js
**Note:** This is a backport of #10953 to `4.1`.
When only a relative URL is provided for the API, the scheme is `undefined` in the API browser when making requests. This leads to defaulting to HTTP, even if the API browser is accessed via HTTPS.
This PR is changing this to use the protocol of the current location if the scheme is missing.
Fixes #10952.
> Use protocol of current url, if scheme is missing. (4.1)

- graylog2-server/src/main/java/org/graylog/plugins/beats/BeatsTransport.java
- graylog2-server/src/main/java/org/graylog/security/authservice/ldap/UnboundLDAPConnector.java
- graylog2-server/src/main/java/org/graylog2/Configuration.java
- graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java
- graylog2-server/src/main/java/org/graylog2/bootstrap/ServerBootstrap.java
- graylog2-server/src/main/java/org/graylog2/commands/Server.java
- graylog2-server/src/main/java/org/graylog2/configuration/TLSProtocolsConfiguration.java
- graylog2-server/src/main/java/org/graylog2/inputs/transports/HttpTransport.java
- graylog2-server/src/main/java/org/graylog2/inputs/transports/SyslogTcpTransport.java
- graylog2-server/src/main/java/org/graylog2/inputs/transports/TcpTransport.java
- graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java
- graylog2-server/src/main/java/org/graylog2/shared/initializers/JerseyService.java
- graylog2-server/src/main/java/org/graylog2/shared/security/tls/DefaultTLSProtocolProvider.java
- graylog2-server/src/test/java/org/graylog/plugins/beats/BeatsTransportTest.java
- graylog2-server/src/test/java/org/graylog/security/authservice/ldap/UnboundLDAPConnectorTest.java
- graylog2-server/src/test/java/org/graylog/security/authservice/ldap/UnboundLDAPConnectorTestTLSIT.java
- graylog2-server/src/test/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransportTest.java
The changes made in #10653 also apply to cases where Graylog
uses TLS as a client.
This makes it impossible to create TLS connections
to legacy software that is only supporting old and insecure ciphers.
Most prominently ES 6.8.x
This changes gives the user the possiblity to re-enable old cipher
suites by changing our default and allowing TLS protocols < 1.2.
This can be done with the `enabled_tls_protocols` setting.
E.g. by setting `enabled_tls_protocols=TLSv1.1, TLSv1.2`
This change had to introduce a separate configuration bean,
to avoid triggering anything that might initialize the default SSLContext.
As for example would the MongoDBConfiguration.validat() method do.
Fixes #10944
Remove explicitly enabled legacy TLS protocols from the disabledAlgorithms filter
Otherwise enabling TLSv …
> Only restrict TLS to secure ciphers with TLS1.2 or greater (4.1 backport)

- graylog2-server/pom.xml
This removes the jersey-media-json-jackson dependency to avoid duplicate registration of two Jackson JSON modules for Jersey.
We currently run into problems in some setups where HTTP requests use `com.fasterxml.jackson.jaxrs.base.ProviderBase` on deserialization of the request and `org.glassfish.jersey.jackson.internal.jackson.jaxrs.base.ProviderBase` on serialization of the response.
See #10906 for example. In this specific issue the `pretty=true` flag to prettify the JSON response didn't work on some nodes but worked on others. Here on the way in the `com.fasterxml.jackson.jaxrs.cfg.ObjectWriterInjector` was modified to enable pretty printing but when serializing the response the code was querying `org.glassfish.jersey.jackson.internal.jackson.jaxrs.cfg.ObjectWriterInjector` and found …
> Fix issue with duplicate Jackson JSON modules

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndicesAdapterES6.java
The call to `ensureIndexTemplate` is removed in `IndicesAdapterES6.create()`
The call has been removed because it's a double call, it's also called in `create` in `Indices.class`. 
Manual check that it's actually called twice before removal and only called once after removal.
I also checked the ES7 implementation for comparison.
> Removed double call with ES6: check for Index Template

- graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterSystemShutdownResource.java
- graylog2-server/src/main/java/org/graylog2/rest/resources/system/RemoteSystemShutdownResource.java
- graylog2-server/src/main/java/org/graylog2/rest/resources/system/SystemShutdownResource.java
- graylog2-server/src/main/java/org/graylog2/shared/security/RestPermissions.java
Deprecates the API endpoints used to shut down a node.
- Adds deprecation annotations to discourage usage in the code
- Removes Swagger annotations to hide the endpoints in the API browser
- Logs a warning when the endpoints are called
- Returns a warning message in the API response where applicable
Refs #10668
> Deprecate shutting a node down via the API

- graylog2-server/src/main/java/org/graylog2/lookup/LookupTableService.java
This adjusts the event handler for AdapterSharedStoresUpdated events to
only purge cache entries for changed data adapters instead of purging
all entries from the cache.
> Avoid global lookup cache purge on shared store update

- graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/debug/Debug.java
- graylog2-server/src/main/java/org/graylog2/lookup/LookupModule.java
- graylog2-server/src/main/java/org/graylog2/lookup/LookupTableConfigService.java
- graylog2-server/src/main/java/org/graylog2/lookup/LookupTableService.java
- graylog2-server/src/main/java/org/graylog2/lookup/db/DBLookupTableConfigService.java
Create a `LookupTableConfigService` interface and use it in `LookupTableService` to make it possible to create a `LookupTableService` instance that doesn't depend on the database.
Also make the constructor in the `Debug` pipeline function public to allow the creation of custom instances.
> Make LookupTableService database independent 

- graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java
A search can reference a stream, which can reference an output.
We don't care for these permissions when sharing a search.
Fixes #11021
> Also exclude outputs from search dependencies

- graylog2-web-interface/src/views/logic/queries/IsAllMessagesRange.ts
Prior to this change, the backend raised an error if a user switch the
timerange from 'from -> to' to 'All time' since 'to' was still send to
the server, which the server refuesed to accept.
This change will change the check where the submitted timerange is
checked to be 'All Time'
Before we did not see the timerange as 'All Time' if 'to' was still set,
but to would have been unset AFTER it acknowleged the time range a s
'All Time'.
Fixes #10920.
- set timerange with from and to
- checked 'All time'
- applied the settings
- started a search
> Do not set 'to' when setting TimeRange to 'All Time'

- graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java
A search can reference a stream, which can reference an output.
We don't care for these permissions when sharing a search.
Fixes #11021
(cherry picked from commit 83d352046122d31c076f2f7ee6cb98b00c51f27b)
> Also exclude outputs from search dependencies (#11023)

- graylog2-web-interface/src/views/logic/views/CopyWidgetToDashboard.ts
- graylog2-web-interface/src/views/types.d.ts
Prior to this change, there was no way to copy plugin information of a
widget to a dashboard, when copying the widget.
This change will add a new hook which provides the possibility to copy
additional things for the widget to a dashboard.
- Create widget in a Search with a parameter
- Copy this widget to a Dashboard
Fixes:  #10846
> Add new hook to CopyWidgetToDashboard

- graylog2-web-interface/src/views/components/QueryBar.test.tsx
- graylog2-web-interface/src/views/components/QueryBar.tsx
- graylog2-web-interface/src/views/components/QueryTabs.tsx
- graylog2-web-interface/src/views/components/Search.tsx
- graylog2-web-interface/src/views/components/contexts/DashboardPageContext.tsx
- graylog2-web-interface/src/views/components/contexts/DashboardPageContextProvider.test.tsx
- graylog2-web-interface/src/views/components/contexts/DashboardPageContextProvider.tsx
- graylog2-web-interface/src/views/components/contexts/WidgetFocusProvider.tsx
- graylog2-web-interface/src/views/components/queries/QueryTitle.tsx
- graylog2-web-interface/src/views/pages/NewSearchPage.test.tsx
- graylog2-web-interface/src/views/pages/SearchPage.tsx
- graylog2-web-interface/src/views/pages/StreamSearchPage.test.tsx
- graylog2-web-interface/src/views/stores/QueriesStore.ts
- graylog2-web-interface/src/views/stores/ViewStore.ts
Implement context which updates the URL of the browser when changing the page of a Dashboard.
A user wants to be able to send a dashboard with a certain page tab open to a colleague.
Fixes #10552  
I stumbled into a problem here when `SizeMe` returned undefined. We checked if `SizeMe` is returning a value and if not did not render the children but instead returned `null`. This did not seem to work any longer. But when returning `<div />` instead everything is turning out fine.
The assumption is, that since we return `null` there will be no rerendering. :man_shrugging: 
- Switch pages
- Create new Page
- Close Page
- Focus a widget in a 2nd page and reload
> Issue 10552 dashboard page context

- graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
Prior to this change, the creation of an bulk request retryer failed
with an exception if the connection to elasitc search 7 could not be
established. Since the Exection was wrapped in a new elastsic search
execption.
This change will check if the error which causes the retryer to be
executed is an IOException and  will not raise a new execption, but
instead retries in configured time.
Fixes #11045
> Fix retrying indexing when connection failed to elastic search 7

- graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewSummaryService.java
- graylog2-server/src/main/java/org/graylog2/database/PaginatedDbService.java
Prior to this change, when returning the list of saved searches the
pagination info always had a count of zero.
This change will remove the seemingly unnecessary construction of
PagianationList with empty arrays.
Fix calculation of grand_total for dashboard and saved searches
- Retrieve List of dashboards and saved searches and check for correct count and grand total.
> Zero count for saved searches list

- graylog2-server/src/main/java/org/graylog2/rest/resources/cluster/ClusterLoggersResource.java
- graylog2-server/src/main/java/org/graylog2/rest/resources/system/logs/RemoteLoggersResource.java
We currently only support changing entire subsystems on the entire cluster.
For debugging specific problems it might help to change the loglevel
of classes under a certain package name.
E.g.:
`$ http --json --auth admin:admin put https://172.16.1.1:9000/api/cluster/system/loggers/org.graylog.plugins.events/level/DEBUG  X-Requested-By:httpie`
> Add cluster wide Loggers endpoint

- graylog2-server/src/main/java/org/graylog2/inputs/random/generators/FakeHttpRawMessageGenerator.java
This change moves the timestamp creation for the random http message
generator to an earlier point in the processing stack.
Previously the timestamp was created _after_ the message was read from
the journal.
When testing situations where we want to make sure we don't lose any
messages, it is desirable to have messages as a continous flow which is easliy visible
in the histogram.
This change moves the timestamp into the GeneratorState which is
created _before_ the message is written into the disk journal.
This way we don't get a spike of messages with the same timestamp, if
they are read from a bigger disk journal backlog.
Before:
After:
> Create random http message timestamps early

- graylog2-server/src/test/java/org/graylog/testing/completebackend/DefaultPluginJarsProvider.java
- graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerFactory.java
Some JARs may not exist in a certain environment. Trying to mount these causes problems for the Jenkins Workspace. 
Refer to https://github.com/Graylog2/graylog2-server/pull/10277 for the details and how we initially solved this on the Cloud branch. 
Now that Cloud and Master branches have merged, we achieve the same result by simply ignoring any non-existant JARs (rather than having a Cloud-specific configuration).
> Reimplement #10277: some JARs may not exist in a certain manifest

- graylog2-server/src/main/java/org/graylog/plugins/views/search/views/widgets/messagelist/MessageListConfigDTO.java
- graylog2-web-interface/src/views/components/export/ExportModal.test.tsx
- graylog2-web-interface/src/views/components/export/Fixtures.ts
- graylog2-web-interface/src/views/components/messagelist/MessageTableEntry.test.tsx
- graylog2-web-interface/src/views/components/messagelist/MessageTableEntry.tsx
- graylog2-web-interface/src/views/components/widgets/EditMessageList.tsx
- graylog2-web-interface/src/views/components/widgets/FieldSortIcon.test.tsx
- graylog2-web-interface/src/views/components/widgets/MessageTable.tsx
- graylog2-web-interface/src/views/logic/Widgets.ts
- graylog2-web-interface/src/views/logic/fieldactions/AddMessageTableActionHandler.ts
- graylog2-web-interface/src/views/logic/widgets/MessagesWidgetConfig.ts
Recently we implemented message summaries for messages in the message table widget https://github.com/Graylog2/graylog2-server/pull/11058. With this PR we are extending the message table widget config to make this option configurable. This way users can control if messages in the message table widget should also display a summary.
Similar to the message summary row we are now displaying checkbox in the message table widget edit mode, which allows controlling this option.
Fixes #11042
> Add config option for message table widget to control display of message summaries.

- graylog2-server/src/main/java/org/graylog2/database/PaginatedList.java
Before the change the PaginatedList was storing the pagination info on
creation. But the size of the list could alter later on without updating
the page info.
This change will now create the pageinfo on access which will lead to a
fresh count number.
> Lazily compute page info for PaginatedList

- graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java
- graylog2-server/src/main/java/org/graylog2/database/PaginatedDbService.java
- graylog2-server/src/main/java/org/graylog2/database/PaginatedList.java
Prior to this change, when returning the list of saved searches
or dashboards the pagination info always had a count of zero
and the combined result of dashboards and saved searches count in
grand_total.
This PR will slightly change the pagination api so grand total also can
have a DBQuery which will be based on the type (search / dashboard) and
will initiate the newly created PaginatedList with the correct count.
- Retrive a list of saved searches and check the count and grand total
- Same for dashboards
> Fix returning count and grand_total of views

- graylog2-web-interface/src/stores/streams/StreamsStore.ts
**This is a backport of https://github.com/Graylog2/graylog2-server/pull/11100 for 4.1**
As described in #11091 using the stream overview pagination will reset the search. This bug occurred because we are updating the list state based on the response of the streams request. Unfortunately we were not extracting the query properly from the response.
> Fixing streams overview query handling (backport of #11100 for 4.1)

- graylog2-server/src/main/java/org/graylog/failure/DefaultFailureHandler.java
- graylog2-server/src/main/java/org/graylog/failure/Failure.java
- graylog2-server/src/main/java/org/graylog/failure/FailureCause.java
- graylog2-server/src/main/java/org/graylog/failure/FailureHandlingService.java
- graylog2-server/src/main/java/org/graylog/failure/FailureSubmissionQueue.java
- graylog2-server/src/main/java/org/graylog/failure/FailureSubmissionService.java
- graylog2-server/src/main/java/org/graylog/failure/IndexingFailure.java
- graylog2-server/src/main/java/org/graylog/failure/IndexingFailureCause.java
- graylog2-server/src/main/java/org/graylog/failure/ProcessingFailure.java
- graylog2-server/src/main/java/org/graylog/failure/ProcessingFailureCause.java
- graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreter.java
- graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
- graylog2-server/src/main/java/org/graylog2/plugin/Message.java
- graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java
- graylog2-server/src/test/java/org/graylog/failure/DefaultFailureHandlerTest.java
- graylog2-server/src/test/java/org/graylog/failure/FailureBatchTest.java
- graylog2-server/src/test/java/org/graylog/failure/FailureHandlingServiceTest.java
- graylog2-server/src/test/java/org/graylog/failure/FailureSubmissionQueueTest.java
- graylog2-server/src/test/java/org/graylog/failure/FailureSubmissionServiceTest.java
- graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreterTest.java
- graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesBulkIndexRetryingTest.java
- graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesIT.java
- graylog2-server/src/test/java/org/graylog2/indexer/messages/MessagesTest.java
- graylog2-server/src/test/java/org/graylog2/logmessage/MessageTest.java
As discussed with the team:
1. One processing error should be associated with one failure. All processing errors are collected via `Message#addProcessingError` and handled later in `ProcessBufferProcessor`.
2. As for now we focus on the pipeline processing errors only.
3. The list of the failure fields is refined and their content reviewed.
[graylog-plugin-enterprise/issue-2127] Storing indexing/processing failures
> Meaningful failure content

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/ClusterAdapterES6.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/cat/CatApi.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/cat/NodeResponse.java
- graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/NodeDiskUsageStats.java
- graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/NodeRole.java
- graylog2-server/src/main/java/org/graylog2/periodical/IndexerClusterCheckerThread.java
- graylog2-server/src/test/java/org/graylog2/indexer/cluster/health/NodeDiskUsageStatsTest.java
- graylog2-server/src/test/java/org/graylog2/indexer/cluster/health/NodeRoleTest.java
- graylog2-server/src/test/java/org/graylog2/periodical/IndexerClusterCheckerThreadTest.java
Fetches an ES node's roles along with its stats and uses the roles to filter nodes when issuing low diskspace warnings.
Fixes #11074 
* Used https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docker.html#docker-compose-file to start a multi-node cluster.
* Modified the docker-compose file to alter node roles
* Changed cluster settings during runtime with
```
$ curl -X PUT "localhost:9200/_cluster/settings?pretty" -H 'Content-Type: application/json' -d'
{
"transient" : {
"cluster.routing.allocation.disk.watermark.low" : "1%"
}
}
'
```
* Observed watermark notifications in Graylog for the nodes holding data.
- [z] My code follows the code style of this project.
> Exclude non-data nodes from ES floodgate checks

- graylog2-server/src/main/antlr4/org/graylog/plugins/pipelineprocessor/parser/RuleLang.g4
- graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/ast/Stage.java
- graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/parser/PipelineRuleParser.java
- graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreter.java
- graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/PipelineResource.java
- graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/PipelineSource.java
- graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/StageSource.java
- graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/parser/PipelineRuleParserTest.java
- graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreterTest.java
- graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/processors/StageIteratorTest.java
- graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/rest/PipelineResourceTest.java
- graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/rest/PipelineSourceTest.java
- graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/rest/StageSourceTest.java
- graylog2-server/src/test/java/org/graylog2/contentpacks/facades/PipelineFacadeTest.java
- graylog2-web-interface/src/components/pipelines/Stage.tsx
- graylog2-web-interface/src/components/pipelines/StageForm.tsx
- graylog2-web-interface/src/logic/pipelines/SourceGenerator.js
- graylog2-web-interface/src/stores/pipelines/PipelinesStore.ts
This allows users to define a stage with the following to make sure the
next stage is executed even when no rule in the declared stage matches.
```
pipeline "title"
stage 0 match pass
rule "test-1"
stage 1 match all
rule "test-2"
end
```
If the "test-1" rule in stage 0 doesn't match, the pipeline interpreter
will still execute  stage 1.
> Add "match pass" guard for pipeline stages

- graylog2-web-interface/src/views/logic/queries/IsAllMessagesRange.ts
**This is a backport of https://github.com/Graylog2/graylog2-server/pull/11017 for 4.1**
Prior to this change, the backend raised an error if a user switch the
timerange from 'from -> to' to 'All time' since 'to' was still send to
the server, which the server refuesed to accept.
This change will change the check where the submitted timerange is
checked to be 'All Time'
Before we did not see the timerange as 'All Time' if 'to' was still set,
but to would have been unset AFTER it acknowleged the time range a s
'All Time'.
Fixes #10920.
- set timerange with from and to
- checked 'All time'
- applied the settings
- started a search
> Do not set 'to' when setting TimeRange to 'All Time' (4.1 backport)

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/ClusterAdapterES6.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ClusterAdapterES7.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/cat/CatApi.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/cat/NodeResponse.java
- graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/NodeDiskUsageStats.java
- graylog2-server/src/main/java/org/graylog2/indexer/cluster/health/NodeRole.java
- graylog2-server/src/main/java/org/graylog2/periodical/IndexerClusterCheckerThread.java
- graylog2-server/src/test/java/org/graylog2/indexer/cluster/health/NodeDiskUsageStatsTest.java
- graylog2-server/src/test/java/org/graylog2/indexer/cluster/health/NodeRoleTest.java
- graylog2-server/src/test/java/org/graylog2/periodical/IndexerClusterCheckerThreadTest.java
* Fetch node roles from ES cat API
Fetch the node roles, parse them and attach them to the node stats.
* Rename some roles and add "holds data" attribute
* Trigger disk usage warnings for data holding ES nodes only
Fixes #11074
(cherry picked from commit 809c0a74c42b46101e07fbb6b228f6086bd2ee5a)
> Exclude non-data nodes from ES floodgate checks (#11106)

- graylog2-web-interface/src/components/events/events/Events.jsx
- graylog2-web-interface/src/components/graylog/Tooltip.jsx
The `Tooltip` component offers a `show` prop that will decide if the tooltip is rendered or not, with a default value of `false`. However, when introducing that prop and its default value we did not update all usages of the component, which use `OverlayTrigger` to decide when to display or hide the `Tooltip`, and therefore they expect the `Tooltip` to be visible as default when rendered.
This PR changes the default value of `show` to `true`, ensurig `Tooltip`s are shown by default but still having the possibility of hiding a `Tooltip` with a prop if needed.
Fixes #10975
> Display Tooltips by default

- graylog2-web-interface/src/views/components/Search.test.tsx
- graylog2-web-interface/src/views/components/Search.tsx
With this PR we are including the current user in the `ActionContext`. We are currently using the `ActionContext` for example when we check if a value action should be displayed. By including the current user, we can consider the user permissions in these checks.
We already have a `CurrentUserContext` which provides the user, but I preferred to extend the `ActionContext`, this way we do not have to add the current user manually, whenever we check e.g. if a value action should be displayed.
> Include current user in `ActionContext`.

- graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewSummaryService.java
- graylog2-server/src/main/java/org/graylog2/database/PaginatedDbService.java
- graylog2-server/src/main/java/org/graylog2/database/PaginatedList.java
Prior to this change, when returning the list of saved searches the
pagination info always had a count of zero.
This change will remove the seemingly unnecessary construction of
PagianationList with empty arrays.
- Use the saved searches end point and check the pagination info
Needs backport to 4.1
> Fix returning count of saved searches list

- graylog2-web-interface/src/logic/pipelines/SourceGenerator.js
Prior to this change, the creation of pipelines was broken
since we did not check if a stage actually exists.
This change will check if a stage exists and otherwise will
fallback to 'all'.
Fixes #11141
- Created a new pipeline
- Edited the newly created pipeline
> Provide default stage for new pipeline

- graylog2-web-interface/src/views/bindings.fieldActions.test.tsx
- graylog2-web-interface/src/views/bindings.valueActions.test.tsx
- graylog2-web-interface/src/views/components/actions/Action.test.tsx
- graylog2-web-interface/src/views/components/actions/ActionHandler.test.tsx
- graylog2-web-interface/src/views/components/actions/ActionHandler.tsx
- graylog2-web-interface/src/views/components/messagelist/Highlight.test.tsx
- graylog2-web-interface/src/views/logic/ActionContext.tsx
- graylog2-web-interface/src/views/logic/fieldactions/AddMessageCountActionHandler.ts
- graylog2-web-interface/src/views/logic/fieldactions/AddToAllTablesActionHandler.ts
- graylog2-web-interface/src/views/logic/fieldactions/AddToTableActionHandler.ts
- graylog2-web-interface/src/views/logic/fieldactions/AggregateActionHandler.ts
- graylog2-web-interface/src/views/logic/fieldactions/ChartActionHandler.ts
- graylog2-web-interface/src/views/logic/fieldactions/FieldActionHandler.ts
- graylog2-web-interface/src/views/logic/fieldactions/FieldStatisticsHandler.ts
- graylog2-web-interface/src/views/logic/fieldactions/RemoveFromAllTablesActionHandler.ts
- graylog2-web-interface/src/views/logic/fieldactions/RemoveFromTableActionHandler.ts
- graylog2-web-interface/src/views/logic/valueactions/AddToQueryHandler.ts
- graylog2-web-interface/src/views/logic/valueactions/ExcludeFromQueryHandler.ts
- graylog2-web-interface/src/views/logic/valueactions/HighlightValueHandler.ts
- graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.test.ts
- graylog2-web-interface/src/views/logic/valueactions/ShowDocumentsHandler.ts
- graylog2-web-interface/src/views/logic/valueactions/ValueActionHandler.ts
- graylog2-web-interface/src/views/types.d.ts
- graylog2-web-interface/test/fixtures/externalValueActions.ts
This PR is a followup to #11126. During review the weak typing of the `ActionContexts` type became apparent. It consisted of an indexer signature with an `any` type for its contents, resulting in the lack of types for all consumers of it.
This PR is attempting to change this by turning it into an explicitly typed interface, declared in the `views/types` module. An `interface` is used instead of a `type` to allow declaration merging. This makes it possible to extend the `ActionContexts` type through plugins.
Existing field/value actions/handlers are being adjusted accordingly.  A couple of types (`ActionHandler`, `ActionHandlerCondition`, ...) are made generic, with the generic type declaring the type of the context provided. This allows us to narrow down the context type to the context …
> Improving typing of field/value action contexts.

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndicesAdapterES6.java
- graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
**Note:** This needs a backport to `4.0` and `4.1`.
Prior to this PR, we fixed a couple of issues related to index sets with a plus in their names (or any other character that requires special URL encoding) in #10392. One additional source of error was not found, which prevents resolving the deflector alias to the current index name on ES6.
This error leads to index cycling not working, due to receiving `null` for the current deflector target and passing that as the old index to the cycle alias method, which constructs an ES-command which atomically removes the old alias mapping and creates the new one. Due to the alias target which needs to be removed, the overall command fails, resulting in the complete index cycling to fail.
This change is now applying proper URL encoding in the …
> Fixing resolving alias target for index sets with plus in prefix on ES6.

- graylog2-server/src/main/java/org/graylog/failure/FailureSubmissionQueue.java
- graylog2-server/src/main/resources/prometheus-exporter.yml
Migrated the `IndexFailuresPeriodical` size metric. The change is not
backward-compatible (it was decided to rename the metric, since the old
name doesn't represent the actual nature of that metric).
Also 2 more metrics were exposed to monitor performance of
failure handling (`failure_queue_submitted_failures` vs
`failure_queue_consumed_failures`)
[graylog-plugin-enterprise/issue-2127] Storing indexing/processing failures
> Failure queue metrics

- graylog2-web-interface/src/util/conditional/filterValueActions.test.ts
- graylog2-web-interface/src/views/components/actions/Action.test.tsx
- graylog2-web-interface/src/views/components/actions/ActionHandler.tsx
- graylog2-web-interface/src/views/components/actions/ActionMenuItem.tsx
- graylog2-web-interface/src/views/logic/fieldactions/FieldActionHandler.ts
- graylog2-web-interface/src/views/logic/valueactions/ValueActionHandler.ts
**Note:** Requires #11144 to be merged before.
This PR is creating separate types for handler-based and external link field/value actions in an attempt to clarify their usage und purpose. This is supposed to ensure that an action can either lead to an external link or be handled by a custom function/component. For the latter, it makes sure that either a function or a component is passed.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#2568
> Introduce separate type for external link actions.

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndicesAdapterES6.java
- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/indices/GetSingleAlias.java
- graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java
- graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
**Note:** backport from #11142, also backports #10757, verified that #10544 has been backported
Prior to this PR, we fixed a couple of issues related to index sets with a plus in their names (or any other character that requires special URL encoding) in #10392. One additional source of error was not found, which prevents resolving the deflector alias to the current index name on ES6.
This error leads to index cycling not working, due to receiving `null` for the current deflector target and passing that as the old index to the cycle alias method, which constructs an ES-command which atomically removes the old alias mapping and creates the new one. Due to the alias target which needs to be removed, the overall command fails, resulting in the complete index cycling to fail.
This change is …
> Fixing resolving alias target for index sets with plus in prefix on ES6 in 4.0 (backport of #11142)

- graylog2-web-interface/src/views/components/AdaptableQueryTabs.tsx
- graylog2-web-interface/src/views/components/common/WindowLeaveMessage.tsx
Prior to this change, the tab/page titles were set during render in some cases. This results in a newly loaded existing dashboard being flagged as dirty immediately.
This change is now assigning page names based on the index in the queries list instead of setting the title explicitly.
Fixes #11156.
> Assign page titles dynamically instead of setting them during render.

- graylog2-server/src/main/java/org/graylog/failure/FailureSubmissionQueue.java
- graylog2-server/src/main/java/org/graylog/failure/FailureSubmissionService.java
- graylog2-server/src/main/java/org/graylog2/indexer/messages/Indexable.java
- graylog2-server/src/main/java/org/graylog2/plugin/Message.java
- graylog2-server/src/test/java/org/graylog/failure/FailureSubmissionServiceTest.java
To avoid scenarios in which we try to handle a failed failure in a loop, 
another guiding property was added to the `Indexable` interface to indicate
whether a concrete `Indexable` should be picked by the failure handling
framework in case of exception.
> No failure handling loops

- graylog2-server/src/main/java/org/graylog2/plugin/system/NodeId.java
- graylog2-server/src/main/java/org/graylog2/system/traffic/TrafficCounterService.java
This addresses #9559: Mongo will save field names with embedded dot characters, but it cannot properly update or retrieve them. As a result, retrieving traffic metrics may lead to an IOException.
Solution: escape the problematic characters "$" and "." when saving the field name. 
At this time we do not ever retrieve and expose the field name; but an unescape method is provided in case we do.
As of version 5.0, Mongo also has [built-in support](https://docs.mongodb.com/manual/core/dot-dollar-considerations/#field-names-with-periods--.--and-dollar-signs----) for this issue; however, MongoJack library only supports versions up to 4.x.
> /system/cluster/traffic: Support dots in nodeId field name

- graylog2-web-interface/src/actions/lookup-tables/LookupTablesActions.js
- graylog2-web-interface/src/components/event-definitions/event-definition-form/EditQueryParameterModal.jsx
- graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterForm.jsx
- graylog2-web-interface/src/components/lookup-table-parameters/LookupTableParameterEdit.tsx
- graylog2-web-interface/src/components/lookup-tables/types.ts
- graylog2-web-interface/src/stores/lookup-tables/LookupTablesStore.js
- graylog2-web-interface/src/views/components/WithSearchStatus.tsx
- graylog2-web-interface/src/views/logic/parameters/LookupTableParameter.ts
- graylog2-web-interface/src/views/logic/search/Search.ts
- graylog2-web-interface/test/fixtures/lookupTables.ts
- graylog2-web-interface/test/fixtures/parameters.ts
With this PR we are creating a shared component for the lookup table parameter form components, to improve their reusability.
Currently we are using this component e.g. in the event definition form. While the  new `LookupTableEdit` component expects to receive a `LookupTableParameter` class, we are using JSON for the parameter inside the event definition form and had to adjust the code accordingly.
We are also implementing some smaller changes for lookup table parameter. We are:
-  no longer creating an empty binding when creating a lookup table parameter, since this parameter type has no binding.
- improving the parts which check if the lookup table parameter binding is required.
- creating fixtures for value parameters and lookup tables.
> Creating shared component for lookup table parameter form components.

- graylog2-web-interface/src/views/components/common/EditableTitle.tsx
- graylog2-web-interface/src/views/components/widgets/WidgetHeader.tsx
Prior to this change, a widget's title was always shown in full, even when there was not enough space, leading to unwanted line breaks and even taking over space of the actual visualization.
This change is now implementing shortening of the widget's title and adding an ellipsis when the available space is exceeded.
Before:
After:
> Shorten widget titles with ellipsis when overflowing available space.

- graylog2-web-interface/src/views/components/widgets/WidgetActionsMenu.tsx
With this PR we are reducing the margin between widget actions.
Before: 
After: 
It looks slightly better and the widget title receives more space, which is especially beneficial for small widgets.
> Reduce margin between widget actions.

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndicesAdapterES6.java
- graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
**Note:** This is a backport from #11142 
Prior to this PR, we fixed a couple of issues related to index sets with a plus in their names (or any other character that requires special URL encoding) in #10392. One additional source of error was not found, which prevents resolving the deflector alias to the current index name on ES6.
This error leads to index cycling not working, due to receiving `null` for the current deflector target and passing that as the old index to the cycle alias method, which constructs an ES-command which atomically removes the old alias mapping and creates the new one. Due to the alias target which needs to be removed, the overall command fails, resulting in the complete index cycling to fail.
This change is now applying proper URL encoding in the `resolveAlias` …
> Fixing resolving alias target for index sets with plus in prefix on ES6 in 4.1 (backport of #11142)

- graylog2-web-interface/src/components/events/events/Events.jsx
- graylog2-web-interface/src/components/graylog/Tooltip.jsx
Backport of https://github.com/Graylog2/graylog2-server/pull/11130 for 4.1.
* Show Tooltips by default
The `Tooltip` component offers a `show` prop that will decide if the
tooltip is rendered or not. At the moment we always use `Tooltip` with
`OverlayTrigger`, so the tooltip will already be displayed conditionally
and we expect that it will be rendered by default (or so do most of our
usages of the component).
This change reverses the default value for the `show` prop, so it is
still possible to hide a Tooltip if needed, but by default it will be
displayed on screen.
Fixes #10975
* Display event priority tooltip on hover and focus
(cherry picked from commit d2d2dbb5a2637f590809489270e53473dcc72041)
> Display Tooltips by default (#11130)

- graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/EvaluationContext.java
- graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/ast/expressions/Expression.java
- graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreter.java
- graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreterTest.java
For "historical" reasons `NumericExpression` and `LogicalExpression` both
bypass the concept of "override `evaluateUnsafe` - call `evaluate`" (which
is by default implemented within `Expression`), what in its turn leads to
evaluation exceptions being **_propagated_**, instead of being converted to an
evaluation error and stored in `EvaluationContext#evalErrors`.
This fix "duplicates" the evaluation exception handling logic for
LogicalExpression(s), so that those errors become discoverable by the
failure handling framework.
To trigger a rule condition evaluation error for a rule below send a message 
with a string value inside the `randomLong` field:
```
rule "Broken Condition"
when
to_double($message.randomLong * $message.randomLong) > 0.0
then
set_field("randomLong_sqr", …
```
> Handling rule condition evaluation exceptions

- graylog2-server/src/main/java/org/graylog/failure/DefaultFailureHandler.java
- graylog2-server/src/main/java/org/graylog2/plugin/Message.java
- graylog2-server/src/test/java/org/graylog/failure/DefaultFailureHandlerTest.java
Processing errors should still be rare cases in regular message
processing. Better save the memory for messages without errors.
> Lazy initialize processingErrors list

- graylog2-web-interface/src/@types/graylog-web-plugin/index.d.ts
- graylog2-web-interface/src/routing/GlobalContextProviders.tsx
With https://github.com/Graylog2/graylog2-server/pull/11164 we introduced plugable global context providers. This PR is adding a description for the plugin store export. We are also removing a not needed character which got added with the referenced PR.
> Add description for `globalContextProviders` in plugin store.

- graylog2-web-interface/package.json
- graylog2-web-interface/packages/jest-preset-graylog/jest-preset.js
With #10435 we installed and configured `jest-junit` for frontend test reporting. Since we configured the jest reporters in the `jest-preset-graylog` we are also generating a `junit.xml` when running  `yarn test` in a plugin. which includes this package. 
With this PR we are using the `target` dir for the `junit.xml` by default.
> Configure `target` directory as default for `jest-junit` output.

- graylog2-web-interface/src/stores/nodes/NodesStore.ts
**Note:** This needs a backport to `4.1`.
This change fixes an issue that occurs when immediately expanding the
message details of an arbitrary message on the search page. This is
caused by the `MessageDetail` calling `isLocalNode`, which is currently
an alias for `NodesStore.getNode()`. If the nodes store was not
initialized (has not retrieved an initial nodes list) before this,
`NodesStore.getNode` throws an exception as it is accessing
`this.nodes[id]`.
Fixes #11089.
Manually tested. It is pretty easy to reproduce the initial error as
described in #11089 by loading the search page and clicking the mouse
button repeatedly during loading in a place where a message row will
appear. Doing this, will lead to the message table widget showing the
exception that was thrown. Applying this …
> Fix race condition in message details related to uninitialized nodes store.

- graylog2-web-interface/src/stores/nodes/NodesStore.ts
**This is a backport of #11207 for 4.1**
**Note:** This needs a backport to `4.1`.
This change fixes an issue that occurs when immediately expanding the
message details of an arbitrary message on the search page. This is
caused by the `MessageDetail` calling `isLocalNode`, which is currently
an alias for `NodesStore.getNode()`. If the nodes store was not
initialized (has not retrieved an initial nodes list) before this,
`NodesStore.getNode` throws an exception as it is accessing
`this.nodes[id]`.
Fixes #11089.
Manually tested. It is pretty easy to reproduce the initial error as
described in #11089 by loading the search page and clicking the mouse
button repeatedly during loading in a place where a message row will
appear. Doing this, will lead to the message table widget showing the …
> Fix race condition in message details related to uninitialized nodes store (backport of #11207 for 4.1)

- graylog2-web-interface/src/@types/graylog-web-plugin/index.d.ts
- graylog2-web-interface/src/stores/nodes/NodesStore.ts
- graylog2-web-interface/src/views/components/messagelist/MessageDetail.tsx
This change is a follow-up to #11207. This PR was fixing the symptoms of the underlying issue, but not the reason. Prior to it, we were expecting the nodes list to be present in the `NodesStore`, which does not necessarily have to be the case, depending on timing. Unfortunately, this check was performed synchronously, so there was no way to just wait for the nodes list to arrive before returning a result.
This change is now making the `isLocalNode` check return a `Promise<boolean>` instead, allowing us to wait for the nodes list in case of its absence.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#2646
> Checking if input node is local asynchronously in message details.

- graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
- graylog2-server/src/main/java/org/graylog2/security/UserSessionTerminationService.java
- graylog2-server/src/main/java/org/graylog2/users/GrantsCleanupListener.java
- graylog2-server/src/test/java/org/graylog2/users/GrantsCleanupListenerTest.java
Upon deletion of a user, clears all grants for users which are not present in the DB anymore.
We scanning the complete grants table and remove all grants that are orphaned. This way we keep a clean grants table even if previously some grants have been missed before. This saves us from writing an additional migration.
I considered using raw mongodb queries and some batching to reduce the number of queries but I think we are fine using the higher level APIs to query for users and delete the grants.
I wouldn't expect any systems with user/grant numbers at such a high level that this could become a problem.
#10385 
Smoke test by creating grants for users/teams and checking which grants get removed when a user is deleted.
> Clear grants when user is deleted

- graylog2-server/src/main/java/org/graylog2/shared/messageq/AbstractMessageQueueAcknowledger.java
- graylog2-server/src/main/java/org/graylog2/shared/messageq/MessageQueueAcknowledger.java
- graylog2-server/src/main/java/org/graylog2/shared/messageq/localkafka/LocalKafkaMessageQueueAcknowledger.java
- graylog2-server/src/test/java/org/graylog2/shared/messageq/localkafka/LocalKafkaMessageQueueAcknowledgerTest.java
A message queue ID may be `null` if the message is not originating from the message queue but was generated during processing, e.g. as part of a pipeline rule.
To fix this for all message queues at once, a new `AbstractMessageQueueAcknowledger` class has been added which implementations can derive from.
Fixes #11143
Also see https://github.com/Graylog2/graylog-plugin-cloud/pull/963
Manual smoke test with disk based journal and Kafka journal (cloud).
> Allow null message queue ids

- graylog2-server/src/main/java/org/graylog2/inputs/transports/UdpTransport.java
- graylog2-server/src/main/java/org/graylog2/plugin/inputs/transports/AbstractTcpTransport.java
We were previously warning when the receive buffer size reported
by netty wasn't exactly matching the receive buffer size that was
configured. However, as the OS can choose to overprovision the buffer,
we shouldn't warn if the reported buffer size is exceeding the expected
buffer size.
With this change, we are only warning when the reported buffer size is
smaller than what we were expecting, as this is the problematic case
worth warning the user about.
Fixes #7720
> Fix warning about receive buffer size

- graylog2-web-interface/src/views/components/aggregationbuilder/AggregationBuilder.tsx
- graylog2-web-interface/src/views/components/datatable/DataTable.tsx
- graylog2-web-interface/src/views/components/visualizations/area/AreaVisualization.tsx
- graylog2-web-interface/src/views/components/visualizations/bar/BarVisualization.tsx
- graylog2-web-interface/src/views/components/visualizations/heatmap/HeatmapVisualization.tsx
- graylog2-web-interface/src/views/components/visualizations/line/LineVisualization.tsx
- graylog2-web-interface/src/views/components/visualizations/number/NumberVisualization.tsx
- graylog2-web-interface/src/views/components/visualizations/pie/PieVisualization.tsx
- graylog2-web-interface/src/views/components/visualizations/scatter/ScatterVisualization.tsx
- graylog2-web-interface/src/views/components/visualizations/worldmap/WorldMapVisualization.tsx
This PR is doing a minor refactoring for retrieval of the typed charts rows in visualization. Previously, it required some type hints (`as Rows`), which are obsolete now and consolidate the extraction of the `chart` key vs. results stored as `id` keys..
> Consolidate rows retrieval for charts and improve its typing.

- pom.xml
Our version is quite ancient and doesn't support compiling with Java 11
Changelog: https://github.com/policeman-tools/forbidden-apis/wiki/Changes
> Update forbiddenapis checker from 2.5 to 3.1

- graylog2-web-interface/src/stores/nodes/NodesStore.ts
- graylog2-web-interface/src/views/components/messagelist/FormatReceivedBy.test.tsx
- graylog2-web-interface/src/views/components/messagelist/FormatReceivedBy.tsx
- graylog2-web-interface/src/views/components/messagelist/MessageDetail.tsx
- graylog2-web-interface/src/views/components/messagelist/NodeName.tsx
Prior to this change, #11225 introduced an issue that results in an exception being thrown when no plugin is present implementing the `isLocalNode` function.
This change is now handling the absence of a plugin for it and adds tests.
> Fix exception being thrown for message details if plugin is missing.

- graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterForm.jsx
With this PR we are adjusting the permissions check for the undeclared parameters info in the event definitions filter step.
The undeclared parameters info appears, when the filter search query contains an undeclared parameter:
Before this change we only displayed this info for users with the following permissions:
```
[
'streams:read',
'extendedsearch:create',
'extendedsearch:use',
];
```
The `extendedsearch` permissions are legacy view permissions which are no longer supported. Related issue: https://github.com/Graylog2/graylog2-server/issues/9904. This did not caused a bug, because only admin users were (and are) able to define query parameters.
Because these query parameters are only usable, when a user has access to lookup tables, we are now:
- only displaying the undeclared …
> Display info for undeclared parameters in event definitions filter step only if user has `lookuptables:read` permission.

- graylog2-web-interface/src/views/components/widgets/WidgetHeader.tsx
This PR is fixing the positioning of the widget loading spinner in widget headers. We are displaying the spinner for example while loading a page in the message table widget.
Before:
After:
> Fixing positioning of loading spinner in widget header.

- graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
- graylog2-server/src/main/java/org/graylog2/security/UserSessionTerminationService.java
- graylog2-server/src/main/java/org/graylog2/users/GrantsCleanupListener.java
- graylog2-server/src/test/java/org/graylog2/users/GrantsCleanupListenerTest.java
* Add comment for currently unused DELETED user account status
* Cleanup grants when user is deleted
(cherry picked from commit da5eb6ba8136946cb4a8f112b1087f396630c79f)
Fixes #10385
> Clear grants when user is deleted (#11121)

- graylog2-server/src/main/java/org/graylog2/events/ClusterEvent.java
- graylog2-server/src/main/java/org/graylog2/events/ClusterEventPeriodical.java
- graylog2-server/src/test/java/org/graylog2/events/ClusterEventPeriodicalTest.java
Prior to this change, an event that is posted to the cluster event bus was written to the unterlying collection and picked up from there in another thread which posts it to the server event bus. This could result in minor, but significant delays between production and consumption of the event.
This change is now doing two things:
- a locally produced event is pushed to the server event bus immediately
- the local node id is added to the set of consumers of the event, avoiding double processing of the event
> Publish locally produced cluster event immediately on server bus.

- graylog2-web-interface/src/views/components/sidebar/NavItem.tsx
It is currently possible to hover over and click on a sidebar tooltip.
As described in https://github.com/Graylog2/graylog2-server/issues/10836 this can be counterintuitive in some cases.
With this PR we are hiding the sidebar tooltip, one the user no longer hovers over the navigation item.
Fixes: #10836
> Only display sidebar tooltip when hovering over sidebar navigation item.

- .github/workflows/build.yml
The setup-java action now supports caching natively.
See: https://github.blog/changelog/2021-08-30-github-actions-setup-java-now-supports-dependency-caching/
> Simplify maven caching in GitHub action workflow

- graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.test.tsx
- graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchControls.tsx
Users need the `dashboards:create` permission to be able to create dashboards. Before this change we displayed the search action "Export to dashboard" for all users. Now we are only displaying the action for users who have the required permission.
Fixes: #9465
> Hide search action "Export to dashboard" for users who do not have the permission to create dashboards.

- graylog2-server/src/test/java/org/graylog/testing/graylognode/MavenPackager.java
This adds the '-V' command line parameter to the mvn build that's run by the MavenPackager.
Adding '-V' makes sure that you can find JDK version mismatches more easily while testing e.g. from within IntelliJ IDEA.
Has been tested by running a test from within IDEA and checking the output in the console.
> mvn print version on internal builds with MavenPackager

- UPGRADING.rst
- graylog2-server/src/main/java/org/graylog2/plugin/utilities/date/NaturalDateParser.java
- graylog2-server/src/test/java/org/graylog2/plugin/utilities/date/NaturalDateParserTest.java
When Natty does not parse any times, only dates, the start of day/end of day should be aligned to the given day(s).
e.g. "yesterday" is currently parsed exactly into the same times as "last 24 hours" - which is not what the user expects.
Manual tests in the GUI.
Added more tests to the existing NaturalDateParserTest Unit-tests
> NaturalDateParser, add alignment to start/end of day

- graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/views/ViewServiceTest.java
see #11020 for initial motivation and description
An error was found in ViewSummaryService calculating counts. ViewSummaryService originated as a copy from ViewService - which consequently suffered from the same error.
- Use the API endpoints for dashboards & cluster-stats that execute the modified searches
Needs backport to 4.1 (see #11151)
> Fix counts in ViewService

- graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java
see #11020 for initial motivation and description, see #11147 for original PR
An error was found in ViewSummaryService calculating counts. ViewSummaryService originated as a copy from ViewService - which consequently suffered from the same error.
- Use the API endpoints for dashboards & cluster-stats that execute the modified searches
> Fix counts in ViewService  (backport of #11147 for 4.1)

- full-backend-tests/src/test/java/org/graylog/elasticsearch/e2e/ElasticsearchE2E.java
- full-backend-tests/src/test/java/org/graylog/elasticsearch/e2e/ElasticsearchE2EES6.java
- full-backend-tests/src/test/java/org/graylog/elasticsearch/e2e/ElasticsearchE2EES7.java
- graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerConfig.java
Always add the GELF HTTP port to the Elastic container config in Integration Tests.
The current integration tests suffer from incorrect caching of container instances. Changing this problem is generally addressed with #11011 - but for a simple workaround right now, the GELF port is always added to the config.
Tests that failed are now green.
> Always add the GELF HTTP port to the Elastic mapped ports in ITs

- graylog2-server/src/test/java/org/graylog/testing/completebackend/GraylogBackend.java
- graylog2-server/src/test/java/org/graylog/testing/elasticsearch/ElasticsearchInstance.java
- graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeInstance.java
This change ensures that all testcontainers and created networks get removed after all the test finish
Register a shutdown hook that closes or started resources
Without this change, after each test-suite run there remain a docker network and an elastic container running. With repeated suite runs it consumes all RAM of the machine and crashes.
Run the integration tests several times (may be from your IDE) and observe outputs of following commands:
```
watch docker ps
watch docker network ls
```
Before the change, you should be able to see that both running containers and networks accumulate with each run and are not stopped. After the change you shouldn't see any new networks and no running elastic containers.
This is the state after 4 successful test-suite runs, you can see 4 elastic …
> Trigger cleanup of containers and networks after all IT tests finished

- graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/KeywordRangeEntity.java
- graylog2-server/src/main/java/org/graylog2/plugin/indexer/searches/timeranges/KeywordRange.java
- graylog2-server/src/main/java/org/graylog2/plugin/utilities/date/NaturalDateParser.java
- graylog2-server/src/main/java/org/graylog2/rest/resources/search/KeywordSearchResource.java
- graylog2-server/src/main/java/org/graylog2/rest/resources/tools/NaturalDateTesterResource.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/timeranges/DerivedTimeRangeTest.java
- graylog2-server/src/test/java/org/graylog2/contentpacks/facades/ViewFacadeTest.java
- graylog2-server/src/test/java/org/graylog2/indexer/searches/SearchesIT.java
- graylog2-server/src/test/java/org/graylog2/indexer/searches/timeranges/TimeRangesTest.java
- graylog2-web-interface/src/logic/datetimes/DateTime.ts
- graylog2-web-interface/src/routing/ApiRoutes.ts
- graylog2-web-interface/src/stores/tools/ToolsStore.ts
- graylog2-web-interface/src/views/components/searchbar/date-time-picker/TabKeywordTimeRange.test.tsx
- graylog2-web-interface/src/views/components/searchbar/date-time-picker/TabKeywordTimeRange.tsx
- graylog2-web-interface/src/views/hooks/BindSearchParamsFromQuery.ts
- graylog2-web-interface/src/views/logic/queries/Query.ts
Added the timezone as a parameter to the keyword-search.
Added the timezone as a parameter to the NaturalDateParser
Fixes: #7796
Manual tests
> Respect User TimeZone in Keyword Search

- graylog2-web-interface/package.json
- graylog2-web-interface/src/stores/isDeepEqual.ts
- graylog2-web-interface/yarn.lock
Performing deep equal comparisons of props may be expensive, specially when comparing React elements passed as children. This gets even worse during development, since React elements will include additional debugging information that also needs to be compared. In my analysis, this caused the tab freezes in the Pipeline Rules page described in #8657.
This PR customises the deep comparison in `isDeepEqual.ts`, using [`react-fast-compare`](https://github.com/FormidableLabs/react-fast-compare) to compare React elements.
You can find performance profiles below but I thought it may be interesting to see a gist of them without all the hassle of loading them, so here are some captures of the critical moment. Before the change:
After the change:
<details>
<summary>Performance profiles</summary> …
> Improve performance when comparing React elements

- full-backend-tests/src/test/java/org/graylog/plugins/views/SearchSyncIT.java
- full-backend-tests/src/test/resources/org/graylog/plugins/views/minimalistic-request.json
- graylog2-server/src/main/java/org/graylog/plugins/views/search/Query.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/Search.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchResource.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/MessageList.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/events/EventList.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/Pivot.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/QueryTest.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/SearchResourceTest.java
- graylog2-server/src/test/java/org/graylog/testing/graylognode/NodeContainerConfig.java
The goal of this PR is to simplify search API (/api/views/search/sync) request needed to obtain a basic response.  
The first obvious road block are the IDs (both MongoDB ObjectId and UUIDs) in the request structure. Currently they are autogenerated by the frontend. But for any REST/CLI usage they are not necessary and may be generated by the backend itself. They are generated only if not provided, so there is no need to adapt the current frontend logic now. 
Completely empty requests ends with no error message and NPEs in the backend, so there need to be validation adapted. 
The (empty) query and default 300s relative time range can be provided by default, the frontend does the same.
Fixes #11234, #6663
Without these UUIDs, a simple request may now look like this:
```
{
"queries":[
{ …
```
> Simplify search requests, provide default values

- graylog2-web-interface/src/views/logic/views/ViewDeserializer.ts
- graylog2-web-interface/src/views/logic/views/ViewLoader.ts
- graylog2-web-interface/src/views/pages/ShowViewPage.test.tsx
- graylog2-web-interface/src/views/stores/ViewStore.test.ts
- graylog2-web-interface/src/views/stores/ViewStore.ts
Prior to this change, when a `page` parameter was part of the url when
loading a dashboard, the sequence was like this:
- loading the dashboard
- activating the first page during load
- parsing the URL
- activating the page id specified in the URL (if present)
This leads to unwanted visual artifacts, the first page will be shown
shortly before switching to the selected page. To avoid this, this PR is
now passing the query part of the URL to the view loader, which will
activate a specified page id right when loading the dashboard.
> Selecting dashboard page specified in URL immediately at load.

- graylog2-web-interface/src/views/components/widgets/LoadingWidget.tsx
- graylog2-web-interface/src/views/components/widgets/MessageWidgets.css
With https://github.com/Graylog2/graylog2-server/pull/11244 we are now rendering the search page widgets while we are executing the search for the first time after loading the page. Previously we were not rendering the widgets and just displaying one loading spinner. We are now displaying a loading indicator for each widget, while we are executing the search initially:
With this PR we are unifying the loading indicator:
Since the previous one was not animated and differed from our default indicator, it could create the wrong impression that the search execution was not successful and it is necessary to re-execute the search.
I tired different versions for example with the text "Updating search results...", but this simple version seems to be the best one.
> Unify widget loading indicator.

- graylog2-web-interface/src/views/components/WidgetGrid.tsx
This change is effectively reverting a small change performed in #11244, which changed our way of using `react-grid-layout` by passing widget coordinates through widget props instead of a global positions object.
Unfortunately, the `getDerivedStateFromProps` method in the `ReactGridLayout` component does not take the content of the `children` props into account when determining if a new layout needs to be calculated, just the children's keys. This leads to the fact that we cannot update widget positions "from the outside" when passing coordinates through children props.
Therefore, this change is using a global positions map again, making sure that it's aligned with the current state of widgets by retrieving it in one central point in the code.
> Passing positions to grid again, instead of through widgets.

- graylog2-server/src/main/java/org/graylog2/periodical/TrafficCounterCalculator.java
Fixes #11248
(cherry picked from commit abda5498aef442a75b7916a10376e40796c0ba3e)
> Make calculation fields of TrafficCounterCalculator volatile

- graylog2-web-interface/src/components/common/ReactGridContainer.tsx
We recently changed the way we position widgets in the widget
grid, by using CSS transforms instead of `position: fixed;`. This
affected the sticky position of the message augmentations. 
To fix this bug we decided to disable `useCSSTransforms` for the grid  for now.
> Fixing positioning of message augmentations.

- graylog2-web-interface/src/components/nodes/BufferUsage.jsx
- graylog2-web-interface/src/components/nodes/BufferUsage.tsx
During work on #11317, it was discovered that node metrics might be missing, returning in an exception being thrown in the `BufferUsage` component.
In order to fix, the following steps were taken:
- the component was converted into a functional component
- metrics subscription was wrapped in a `useEffect`-block, returning a function that unsubscribes (previously no unsubscribing happened)
- a guard was introduced that short-circuits to a spinner if node metrics are missing
- the component was typed
> Fixing issue in `BufferUsage` component when node metrics are missing.

- graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessor.java
When an event definition doesn't have any streams configured, this
previously resulted in an empty "source_streams" field in the event
which allowed all users to see the event.
To fix it, we are now using the same way to compute the "source_streams"
for filter events that we are using for aggregation events.
Fixes #11301
This needs to be backported to 4.1 and 4.0.
> Ensure filter events have "source_streams" set

- graylog2-web-interface/src/components/permissions/EntityShareModal.test.tsx
- graylog2-web-interface/src/stores/connect.tsx
- graylog2-web-interface/src/views/components/widgets/TimerangeInfo.test.tsx
- graylog2-web-interface/src/views/pages/ViewManagementPage.test.tsx
Prior to this PR, the `useStore` logic to connect a component with a store looked like this:
1. retrieve current state from store and set it in state
2. register listener on store which updates state upon store updates
This could lead to a race condition in some scenarios, where between 1.  & 2. a store update is happening, which is not processed by the `useStore` hook due to no being registered to the store at this time.
In order to prevent this, a 3rd step is added to `useStore`'s logic:
3. retrieve current state from store again and set it in state
This helps ups keeping up with potential store updates between 1. & 2.  In addition, it does not necessarily mean that an additional rerendering of the component is triggered, if the state retrieved in 1. and 3. is shallowly equal (due to …
> Retrieve store state 2nd time after registration to avoid race condition

- graylog2-server/src/test/java/org/graylog/testing/ldap/OpenLDAPContainer.java
- pom.xml
Updating the testcontainers dependency to 1.16.0.
We are seeing intermittent test failures in Jenkins like:
`08:17:32  org.testcontainers.containers.ContainerLaunchException: Container startup failed`
We've seen similar issues in the past, and they were resolved by updating testcontainers. This error disappeared for a long time, but now it is back. I would like to see if this resolves the issue. If we need to dig deeper, it will also help to be on the latest version.
> Update testcontainers to 1.16.0.

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/jest/JestUtils.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java
- graylog2-server/src/main/java/org/graylog2/indexer/ElasticsearchException.java
- graylog2-server/src/main/java/org/graylog2/indexer/MasterNotDiscoveredException.java
- graylog2-server/src/main/java/org/graylog2/indexer/messages/Messages.java
**Note:** _This PR contains problematic terminology (`master`) in the description as well as the code. This was a conscious decision, as this terminology is used specifically in the underlying technology (ES). Using different terminology in our product would obscur the underlying details, making it more difficult/impossible to debug this. Hopefully, this terminology will be replaced soon (see elastic/elasticsearch#67833), allowing us to replace the wording in our code as well without creating confusion._
Prior to this PR, when the connected ES cluster was without an elected "master" node, all indexing attempts would fail without being retried and messages are discarded.
This PR is now parsing the errors we are returning and creates a structured exception (`MasterNotDiscoveredException`) …
> Retry indexing if ES cluster is without coordinator.

- .github/workflows/fix-linter-hints.yml
This PR creates a github actions job which runs periodically (starting with every 8h), running `lint --fix` to find and fix new linter hints which can be auto-fixed.
This is particularly useful as long as we do not enforce auto-fixing in PRs, as well as due to eslint rule updates introducing new, auto-fixable hints in the existing codebase.
> Adding job to fix linter hints periodically.

- graylog2-server/src/main/java/org/graylog/events/processor/aggregation/AggregationEventProcessor.java
When an event definition doesn't have any streams configured, this
previously resulted in an empty "source_streams" field in the event
which allowed all users to see the event.
To fix it, we are now using the same way to compute the "source_streams"
for filter events that we are using for aggregation events.
Fixes #11301
(cherry picked from commit cfe478eb01a09af38878de8a8fe36f90bb8f4264)
> Ensure filter events have "source_streams" set (#11303)

- .github/workflows/fix-linter-hints.yml
Allow the linter step in the github workflow to exit with non-zero
return code.
> Allow linter step to exit with non-zero return code.

- graylog2-server/src/main/java/org/graylog2/inputs/codecs/GelfCodec.java
This gives a user more context when debugging incomplete
GELF messages, where the source IP is not enough.
[HS #553887549]
> Add a trace log for invalid GELF messages

- graylog2-server/src/main/java/org/graylog2/system/stats/mongo/DatabaseStats.java
- graylog2-server/src/main/java/org/graylog2/system/stats/mongo/MongoProbe.java
The "numExtents" value got removed in MongoDB 4.4.
Fixes #11350
*Note:* This should be backported to 4.1.
> Fix system stats with MongoDB >= 4.4

- .github/workflows/fix-linter-hints.yml
This small change is adding author information, so commits do not show up as belonging to @linuspahl. It also enables that the branch is deleted after merge.
> Adding author to lint job, deleting branch after merge.

- graylog2-web-interface/src/logic/rest/FetchProvider.ts
Graylog server API returns JSON responses also when doing a plaintext
request. Sometimes though, it is possible that we get an empty response
from the server, which will throw an error when trying to parse the JSON
response using the JS `fetch` API.
Since the default response can read a JSON response from the server and
already handles the situation described above, this commit replaces the
custom response handler for plaintext responses with the default one.
Fixes #11343
> Handle empty responses on plaintext requests

- .github/workflows/fix-linter-hints.yml
This PR is doing simple changes to the linter workflow, in order to fix
the author's mail address and a typo in the description.
> Fixing mail address and typo in PR body.

- graylog2-server/src/main/java/org/graylog2/rest/resources/tools/NaturalDateTesterResource.java
- graylog2-web-interface/src/views/components/searchbar/date-time-picker/TabKeywordTimeRange.tsx
**This is a backport of #11386 for 4.2**
Prior to this change, a refactoring introduced in #11194 lead to the server not being able to generate a preview for a keyword time range, because the response class was not serializable due to missing `@JsonProperty` annotations, which were added in this PR.
Additionally, the keyword preview was constantly updating due to the component rerendering and field-level validation being triggered, resulting in an infinite loop. The reason why this did not happen before are unclear. To address this, validation was changed to happen only if the keyword has changed, plus an initial validation being forced.
Fixes #11385.
> Fix keyword time range validation and time range preview. (backport of #11386 for 4.2)

- graylog2-web-interface/src/components/common/HoverForHelp.tsx
- graylog2-web-interface/src/components/graylog/OverlayTrigger.tsx
- graylog2-web-interface/src/views/components/actions/ActionHandler.tsx
- graylog2-web-interface/src/views/components/actions/ActionMenuItem.test.tsx
- graylog2-web-interface/src/views/components/actions/ActionMenuItem.tsx
With this PR it is now possible to display a help for action menu items. This can be useful to describe why an item is disabled.
> Allow displaying help text for `ActionMenuItem`s.

- graylog2-web-interface/src/components/common/HoverForHelp.tsx
- graylog2-web-interface/src/components/graylog/OverlayTrigger.tsx
- graylog2-web-interface/src/views/components/actions/ActionHandler.tsx
- graylog2-web-interface/src/views/components/actions/ActionMenuItem.test.tsx
- graylog2-web-interface/src/views/components/actions/ActionMenuItem.tsx
_This is a backport of https://github.com/Graylog2/graylog2-server/pull/11389 for 4.2_
With this PR it is now possible to display a help for action menu items. This can be useful to describe why an item is disabled.
> Allow displaying help text for `ActionMenuItem`s. (backport of #11389 for 4.2)

- graylog2-web-interface/src/pages/IndexSetPage.tsx
Fixes the index count on `IndexSetPage`.
Previously, `_totalIndexCount` was counting the keys of the `indexerOverview` response (introduced w/ #10401; [specifically this](https://github.com/Graylog2/graylog2-server/pull/10401/files#diff-e80e8ae830a0552545b2659d7a199aa7274ac4ffa50f68a7f0d2c822a99133d2R110-R114)), rather than the response's `indices` key.  This PR updates that function so it counts the right thing.
Fixes #11375.
It hasn't been tested.
> Fix index count on IndexSetPage

- graylog2-web-interface/src/views/components/aggregationwizard/FieldSelect.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.groupBy.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.metric.test.tsx
**Note:** This PR requires a backport to `4.2`.
Prior to this change, the options list used for the field select of the aggregation wizard was based on the "all" field types list. That one includes field types for all streams a user has access to.  Unfortunately, this list of streams is lacking e.g. the indexing failure stream. This can lead to problems like the one described in #11404.
This change is now generating the field options list from the field types of the currently selected query.
Fixes #11404.
> Use query fields instead of all fields for aggregation wizard's field select

- graylog2-web-interface/src/views/components/aggregationwizard/FieldSelect.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.groupBy.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.metric.test.tsx
This is a backport of https://github.com/Graylog2/graylog2-server/pull/11405 for 4.2
Prior to this change, the options list used for the field select of the aggregation wizard was based on the "all" field types list. That one includes field types for all streams a user has access to.  Unfortunately, this list of streams is lacking e.g. the indexing failure stream. This can lead to problems like the one described in #11404.
This change is now generating the field options list from the field types of the currently selected query.
Fixes #11404.
> Use query fields instead of all fields for aggregation wizard's field select (backport of #11405 fro 4.2)

- graylog2-server/src/main/java/org/graylog2/lookup/LookupTableService.java
**Note:** This PR needs a backport to `4.2`.
The call that loads all tables linked to a cache has been placed near the actual recreation of these tables to make sure that the contents of that variable are current.
For the Watchlist functionality, a migration script had been created that imports and installs a ContentPack. After installation, 3 keys are to be created in a lookup table. This fails sometimes due to a possible race condition that occurs that saving the cache and the lookup table during import fires an update event on the EventBus but due to the ordering of the code and the runtime during the cache recreation, the lookup table never gets started properly.
> Fixed Race Condition with CP Installation and Caches/LUTs

- graylog2-server/src/main/java/org/graylog2/lookup/LookupTableService.java
**This is a backport of #11413 for 4.2**
The call that loads all tables linked to a cache has been placed near the actual recreation of these tables to make sure that the contents of that variable are current.
For the Watchlist functionality, a migration script had been created that imports and installs a ContentPack. After installation, 3 keys are to be created in a lookup table. This fails sometimes due to a possible race condition that occurs that saving the cache and the lookup table during import fires an update event on the EventBus but due to the ordering of the code and the runtime during the cache recreation, the lookup table never gets started properly.
> Fixed Race Condition with CP Installation and Caches/LUTs (backport of #11413 to 4.2)

- graylog2-web-interface/src/pages/IndexSetPage.tsx
**Note:** This is a backport of #11395 to `4.2`.
Fixes the index count on `IndexSetPage`.
Previously, `_totalIndexCount` was counting the keys of the `indexerOverview` response (introduced w/ #10401; [specifically this](https://github.com/Graylog2/graylog2-server/pull/10401/files#diff-e80e8ae830a0552545b2659d7a199aa7274ac4ffa50f68a7f0d2c822a99133d2R110-R114)), rather than the response's `indices` key.  This PR updates that function so it counts the right thing.
Fixes #11375.
It hasn't been tested.
> Fix index count on IndexSetPage (4.2)

- graylog2-web-interface/src/pages/IndexSetPage.tsx
**Note:** This is a backport of #11395 to `4.1`.
Fixes the index count on `IndexSetPage`.
Previously, `_totalIndexCount` was counting the keys of the `indexerOverview` response (introduced w/ #10401; [specifically this](https://github.com/Graylog2/graylog2-server/pull/10401/files#diff-e80e8ae830a0552545b2659d7a199aa7274ac4ffa50f68a7f0d2c822a99133d2R110-R114)), rather than the response's `indices` key.  This PR updates that function so it counts the right thing.
Fixes #11375.
It hasn't been tested.
> Fix index count on IndexSetPage (4.1)

- graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterPreview.css
This PR sets a maximum height for the body of the [event definition `FilterPreview`](https://github.com/Graylog2/graylog2-server/blob/a6968ad92689815fa3a61af25d9d0d22df43178a/graylog2-web-interface/src/components/event-definitions/event-definition-types/FilterPreview.jsx#L104)'s panel (i.e. the list of matching messages).
When an event definition's filter matches messages with large `message` content everything below the Filter section gets pushed down, requiring scrolling or jumping down.
Fixes #7886.
Verified the filter preview's panel body (containing the message list) went up to the max height, with scrolling when it was exceeded.
**Before:**
**After:**
> Limit height of event definition filter preview

- graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodical.java
- graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodicalTest.java
Without this a non-master node would start polling index field types for
newly created index sets. The periodical doesn't get started on
non-master nodes, but due to the implementation of the periodicals
system the class gets instantiated and thus subscribed to the event bus.
Fixes #11504
> Add guard checks to event bus subscriptions in index field type poller

- graylog2-web-interface/src/pages/ShowMessagePage.test.tsx
- graylog2-web-interface/src/pages/ShowMessagePage.tsx
**Note:** This needs to be backported to `4.2`.
Prior to this PR, when using a message permalink to view a single message, field types were retrieved for all streams the message belongs to, although the user potentially has access only to a subset of the streams. This can lead to the backend returning a `403` in case the user does not have access to all streams of the message. If this happens, the error page is shown instead of the single message page.
Fixes #11540.
> Fetch field types only for streams the user has access to.

- graylog2-web-interface/src/pages/ShowMessagePage.test.tsx
- graylog2-web-interface/src/pages/ShowMessagePage.tsx
This is a backport of https://github.com/Graylog2/graylog2-server/pull/11541 for 4.2
Prior to this PR, when using a message permalink to view a single message, field types were retrieved for all streams the message belongs to, although the user potentially has access only to a subset of the streams. This can lead to the backend returning a `403` in case the user does not have access to all streams of the message. If this happens, the error page is shown instead of the single message page.
Fixes #11540.
> Only fetch allowed streams for field types in message permalink (backport of #11541 for 4.2)

- graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/MappedFieldTypesService.java
- graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/MappedFieldTypesServiceTest.java
**Note:** This needs to be backported to `4.1` and `4.2`.
Prior to this change, a physical field type of `keyword` and a physical type of `text` were being merged into a logical field type of `string` with a `compound` property. This is not correct, as it is not really a compound type. All we need to do in this case is create the set of shared properties for identical logical types.
This is fixing an issue where a user cannot aggregate on a field which is a `keyword` in one index and a `text` field in another.
> Avoid creating compound type for identical physical types but diff. properties

- graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/MappedFieldTypesService.java
- graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/MappedFieldTypesServiceTest.java
**Note:** backport of #11535 
Prior to this change, a physical field type of `keyword` and a physical type of `text` were being merged into a logical field type of `string` with a `compound` property. This is not correct, as it is not really a compound type. All we need to do in this case is create the set of shared properties for identical logical types.
This is fixing an issue where a user cannot aggregate on a field which is a `keyword` in one index and a `text` field in another.
> Avoid creating compound type for identical physical types but diff. properties (backport to 4.2)

- graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/MappedFieldTypesService.java
- graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/MappedFieldTypesServiceTest.java
**Note:** backport of #11535 
Prior to this change, a physical field type of `keyword` and a physical type of `text` were being merged into a logical field type of `string` with a `compound` property. This is not correct, as it is not really a compound type. All we need to do in this case is create the set of shared properties for identical logical types.
This is fixing an issue where a user cannot aggregate on a field which is a `keyword` in one index and a `text` field in another.
> Avoid creating compound type for identical physical types but diff. properties (backport to 4.1)

- graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java
- graylog2-server/src/main/java/org/graylog2/bootstrap/ServerBootstrap.java
- graylog2-server/src/main/java/org/graylog2/bootstrap/commands/MigrateCmd.java
The `io.netty.native.workdir` property always points to `data/libnative`
because the configuration hasn't been parsed at that stage.
Explicitly parse a PathConfiguration bean and pass it into the
beforeStart() method.
Fixes #11543
> Adhere to data_dir setting for netty libnative

- graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java
- graylog2-server/src/main/java/org/graylog2/bootstrap/ServerBootstrap.java
The `io.netty.native.workdir` property always points to `data/libnative`
because the configuration hasn't been parsed at that stage.
Explicitly parse a PathConfiguration bean and pass it into the
beforeStart() method.
Fixes #11543
(cherry picked from commit 6f903e3344e2107e3de849f8ef40fe8c164f0578)
> Adhere to data_dir setting for netty libnative (4.2 backport)

- graylog2-server/src/main/java/org/graylog2/system/traffic/TrafficCounterService.java
- graylog2-server/src/test/java/org/graylog2/system/traffic/TrafficCounterServiceTest.java
* Fix sliding window datetime borders
* Fix "to" in "#clusterTrafficOfLastDays" to include data up until now
* Add test for TrafficCounterService
* Add assertions for the "from" and "to" values
Co-authored-by: Marius Sturm <marius@graylog.com>
(cherry picked from commit 83ca06b1d5fbc36d12ad0418a7c34430427df279)
> Fix sliding window date time boundaries

- full-backend-tests/src/test/java/org/graylog/plugins/views/TimeLimitIT.java
- full-backend-tests/src/test/java/org/graylog/testing/backenddriver/SearchDriver.java
- full-backend-tests/src/test/resources/org/graylog/plugins/views/cluster-search-config-reset.json
- full-backend-tests/src/test/resources/org/graylog/plugins/views/cluster-search-config.json
- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackend.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendMultiSearchTest.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendQueryStringDecoratorsTest.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendSearchTypeOverridesTest.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendSearchTypesWithStreamsOverridesTest.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendTest.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendUsingCorrectIndicesTest.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/QueryPlanTest.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackend.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendMultiSearchTest.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendQueryStringDecoratorsTest.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendSearchTypeOverridesTest.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendSearchTypesWithStreamsOverridesTest.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendTest.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendUsingCorrectIndicesTest.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/QueryPlanTest.java
- graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchExecutionGuard.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/QueryBackend.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/QueryEngine.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/SearchConfig.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/SearchConfigProvider.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/errors/IllegalTimeRangeException.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchResource.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/exceptionmappers/IllegalTimeRangeExceptionMapper.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/SearchExecutionGuardTest.java
This change prevents executing queries with time range out of allowed time range limit if any is configured. It adds the backend validation and complements the already existing frontend validation of the time range.
Extended SearchExecutionGuard to check time range limit configuration and validate time range of every executed query.
Fixes #9487
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#2738
Added unit test. Manually verified on localhost:8080/search?q=&rangetype=relative&relative=2592000 with a very low time range limit configured.
> Backend validation of search query time range limit #9487

- UPGRADING.md
- graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java
- graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodical.java
- graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerPeriodicalTest.java
- misc/graylog.conf
Refactoring of the index field type poller periodical.
The goal is that we can stop running the periodical on one node and start it on another node. In the previous version, the periodical was starting and maintaining separate scheduled threads, which would keep running, even if we would stop executing the periodical.
After the refactoring, the periodical only maintains the previous execution of each individual poll to determine if an index set needs polling at any given time. If we stop running the periodical, no polling will happen until we start running it again.
As suggested by @bernd
> Refactor index field type polling

- graylog2-server/src/main/java/org/graylog2/commands/Server.java
- graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java
- graylog2-server/src/main/java/org/graylog2/configuration/validators/RotationStrategyValidator.java
- graylog2-server/src/main/java/org/graylog2/indexer/rotation/RotationStrategyBindings.java
- graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/AbstractRotationStrategy.java
- graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/MessageCountRotationStrategy.java
- graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/SizeBasedRotationStrategy.java
- graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategy.java
- graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategyConfig.java
- graylog2-server/src/main/java/org/graylog2/migrations/V20151210140600_ElasticsearchConfigMigration.java
- graylog2-server/src/main/java/org/graylog2/migrations/V20190705071400_AddEventIndexSetsMigration.java
- graylog2-server/src/main/java/org/graylog2/plugin/indexer/rotation/RotationStrategy.java
- graylog2-server/src/main/java/org/graylog2/rest/resources/system/indices/RotationStrategyResource.java
- graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/MessageCountRotationStrategyTest.java
- graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/RotationStrategyValidatorTest.java
- graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/SizeBasedRotationStrategyTest.java
- graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategyConfigTest.java
- graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategyTest.java
- graylog2-server/src/test/java/org/graylog2/migrations/V20161116172100_DefaultIndexSetMigrationTest.java
- graylog2-server/src/test/java/org/graylog2/periodical/IndexRotationThreadTest.java
- graylog2-web-interface/src/components/indices/IndexMaintenanceStrategiesConfiguration.jsx
- graylog2-web-interface/src/components/indices/Types.ts
- graylog2-web-interface/src/components/indices/rotation/TimeBasedRotationStrategyConfiguration.jsx
- graylog2-web-interface/src/pages/IndexSetConfigurationPage.jsx
- graylog2-web-interface/src/pages/IndexSetCreationPage.jsx
- graylog2-web-interface/src/pages/IndexSetCreationPage.tsx
- graylog2-web-interface/src/stores/indices/IndexSetsStore.ts
- graylog2-web-interface/src/stores/indices/IndicesConfigurationStore.js
- graylog2-web-interface/src/stores/indices/IndicesConfigurationStore.ts
- misc/graylog.conf
Provides the ability to 
- optionally configure a global time limit for time-based index rotation
- optionally limit the available set of rotation strategies
See linked issue for details.
resolves Graylog2/graylog-plugin-cloud#972
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#2887
> Configuration options for rotation strategies

- graylog2-server/src/main/java/org/graylog2/plugin/utilities/date/NaturalDateParser.java
- graylog2-server/src/test/java/org/graylog2/plugin/utilities/date/NaturalDateParserTest.java
We already included the parsing of "last {year | month | week}" as a special case in the NaturalDateParser due to Natty being incompatible for cases like these. Now we also include "this {year | month | week}".
Has been tested manually. As it is using the same underlying code, I hope this is sufficient.
- [] My change requires a change to the documentation.
> Add "this {year | month | week}" to NaturalDateParser to align year/month/week correctly

- graylog2-web-interface/src/routing/withLocation.tsx
- graylog2-web-interface/src/views/hooks/BindSearchParamsFromQuery.ts
- graylog2-web-interface/src/views/logic/NormalizeSearchURLQueryParams.test.ts
- graylog2-web-interface/src/views/logic/NormalizeSearchURLQueryParams.ts
- graylog2-web-interface/src/views/logic/NormalizeSearchURLQueryParmas.ts
- graylog2-web-interface/src/views/logic/queries/QueryGenerator.ts
- graylog2-web-interface/src/views/logic/views/UseCreateSavedSearch.ts
- graylog2-web-interface/src/views/logic/views/ViewGenerator.ts
- graylog2-web-interface/src/views/pages/NewSearchPage.test.tsx
- graylog2-web-interface/src/views/pages/NewSearchPage.tsx
- graylog2-web-interface/src/views/pages/StreamSearchPage.test.tsx
- graylog2-web-interface/src/views/pages/StreamSearchPage.tsx
- graylog2-web-interface/src/views/stores/ViewStore.ts
Before this change we we created two searches, when opening the default or stream search page via a URL with search query params like: `?q=http_method:GET&rangetype=relative&relative=300`. This was not the case when opening a saved search. This problem occurred because we were creating a search with the default search query first and another one with the search settings provided by the URL query params.
Please note, this bug still exists when the URL query params contain a stream filter. Fixing this bug will require more complex changes, which we should implement in a follow-up PR.
> Avoid not needed search creation on default and stream search page

- graylog2-server/src/main/java/org/graylog/failure/FailureSubmissionService.java
Move the checks that don't require asking a service to the beginning.
This way, we only check the configuration for messages that have
errors and can be handled.
> Improve submitProcessingErrors() checking order

- graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
- graylog2-server/src/main/java/org/graylog2/bootstrap/commands/MigrateCmd.java
- graylog2-server/src/main/java/org/graylog2/commands/Server.java
The cloud plugin gets its Configuration dependency injected.
Duplicating the configuration and disabling the journal
did not affect the cloud plugin. Thus two MessageQueue implementations
were bound.
```
1) [Guice/BindingAlreadySet]: MessageQueueReader was bound multiple times.
Bound at:
1  : PluginModule.bindMessageQueueImplementation(PluginModule.java:376)
\_ installed by: ServerBindings -> MessageQueueModule
2  : PluginModule.bindMessageQueueImplementation(PluginModule.java:376)
\_ installed by: PluginBindings -> GraylogCloudModule
```
Simply disabling the journal on the configuration bean ensures
that both modules receive the same setting.
Also, remove uneeded configuration field from MigrateCmd.
> Fix migrate command for running with cloud plugin

- graylog2-web-interface/src/views/logic/widgets/Widget.ts
**Note:** This requires a backport to `4.2`.
Prior to this PR we were using the default locales when converting widget types to lower case. For the turkish language, this can lead to certain characters being changed in an unexpected way.
This PR is now using the `en` locale explicitly when lowercasing the widget type.
Thanks to @supahgreg for his work in #11601.
Fixes #11596.
> Use english locale explicitly when finding widget subclass.

- graylog2-web-interface/src/views/components/visualizations/area/bindings.tsx
**Note:** This should be backported to `4.2` and `4.1`.
Prior to this PR, when converting an area chart config to the form state of the aggregation wizard, we were expecting the config to be present.  It seems like there a circumstances where the aggregation wizard's visualization config is `null`. In these cases, editing an aggregation widget throws an exception.
This change is now handling missing visualization configs more gracefully, returning an empty setting for the interpolation of an area chart.
Fixes #11611.
> Handle missing area chart config more gracefully.

- graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ProcessorFunctionsModule.java
- graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/lookup/LookupStringListContains.java
Adding a new pipeline rule.
If you have a key in a lookup-table that contains a list of strings (e.g. ip-addresses), I found no solution to check for containment of an IP from e.g. a message-field.
Adding this method makes it usable for watchlists just like the existing lookup for events/alerts.
> new Pipeline Rule: Check for a value in a StringList in a key in a LookupTable

- graylog2-web-interface/src/views/logic/widgets/Widget.ts
_This is a backport of #11637 for `4.2`._
Prior to this PR we were using the default locales when converting widget types to lower case. For the turkish language, this can lead to certain characters being changed in an unexpected way.
This PR is now using the `en` locale explicitly when lowercasing the widget type.
Thanks to @supahgreg for his work in #11601.
Fixes #11596 for `4.2`.
> Use english locale explicitly when finding widget subclass. (backport of #11637 for 4.2)

- graylog2-web-interface/src/views/logic/widgets/Widget.ts
_This is a backport of #11637 for `4.1`._
Prior to this PR we were using the default locales when converting widget types to lower case. For the turkish language, this can lead to certain characters being changed in an unexpected way.
This PR is now using the `en` locale explicitly when lowercasing the widget type.
Thanks to @supahgreg for his work in #11601.
Fixes #11596 for `4.1`.
> Use english locale explicitly when finding widget subclass. (backport of #11637 for 4.1)

- graylog2-web-interface/src/views/components/visualizations/area/bindings.tsx
_This is a backport of #11610 for `4.2`._
Prior to this PR, when converting an area chart config to the form state of the aggregation wizard, we were expecting the config to be present.  It seems like there a circumstances where the aggregation wizard's visualization config is `null`. In these cases, editing an aggregation widget throws an exception.
This change is now handling missing visualization configs more gracefully, returning an empty setting for the interpolation of an area chart.
Fixes #11611 for `4.2`.
> Handle missing area chart config more gracefully. (backport of #11610 for 4.2)

- graylog2-web-interface/src/views/components/visualizations/area/bindings.tsx
_This is a backport of #11610 for `4.1`._
Prior to this PR, when converting an area chart config to the form state of the aggregation wizard, we were expecting the config to be present.  It seems like there a circumstances where the aggregation wizard's visualization config is `null`. In these cases, editing an aggregation widget throws an exception.
This change is now handling missing visualization configs more gracefully, returning an empty setting for the interpolation of an area chart.
Fixes #11611 for `4.1`.
> Handle missing area chart config more gracefully. (backport of #11610 for 4.1)

- full-backend-tests/src/test/java/org/graylog/plugins/views/SearchMetadataIT.java
- full-backend-tests/src/test/resources/org/graylog/plugins/views/minimalistic-request-with-undeclared-parameter.json
- full-backend-tests/src/test/resources/org/graylog/plugins/views/mongodb-stored-searches-for-metadata-endpoint.json
- graylog2-server/src/main/java/org/graylog/plugins/views/ViewsBindings.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/Query.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/Search.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchDomain.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchExecutor.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchMetadataResource.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchResource.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/SearchDomainTest.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/SearchExecutorTest.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/SearchResourceExecutionTest.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/SearchResourceTest.java
In this PR, actual search execution is decoupled and encapsulated in a `SearchExecutor` class, which was previously existing as a thin abstraction in `enterprise`, which has been transferred over to core.  This allows us to centralize preparations, validations and enforcing domain constraints in a single place, as well was encouraging reuse in REST resources (and other places) which need to execute searches.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#2950
> Decoupling search execution from REST resources.

- graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/json/JsonParse.java
- graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/json/JsonUtils.java
- graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/JsonUtilsTest.java
Adds a new optional parameter to the `parse_json` pipeline function. The parameter specifies the maximum parse depth - we ignore any nodes that are more deeply nested.
See related issues for details and use case.
Resolves Graylog2/graylog2-server#9021
> JSON parsing: add shallow parsing up to a certain path depth

- graylog2-server/src/main/java/org/graylog/plugins/views/search/Parameter.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/Search.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/ValueParameter.java
Avoid json serialization and deserialization when applying parameter bindings to parameters
Cleaner and simpler code
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#2953
> Parameter binding: execution state refactored

- graylog2-server/src/main/java/org/graylog/failure/FailureSubmissionService.java
Move the checks that don't require asking a service to the beginning.
This way, we only check the configuration for messages that have
errors and can be handled.
(cherry picked from commit 05e354722cc3e465d7fb25d4c76409406d45bd18)
> Improve submitProcessingErrors() checking order (#11602)

- full-backend-tests/src/test/java/org/graylog/plugins/views/SearchSyncIT.java
- full-backend-tests/src/test/java/org/graylog/testing/backenddriver/SearchDriver.java
- full-backend-tests/src/test/resources/org/graylog/plugins/views/minimalistic-request-with-streams.json
- graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchJob.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/QueryDTO.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/QueryDTOv2.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchDTO.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchDTOv2.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchJobDTO.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchMetadataResource.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchResource.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/SearchDomainTest.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/SearchResourceExecutionTest.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/SearchResourceTest.java
The major goal of this PR is to separate the structures used to interact with the search execution API from the entities used internally. For this, the `Search` and `Query` structures are decoupled from the REST API by introducing `SearchDTO` & `QueryDTO` classes. This allows us to:
- change the structure of the internally used entities while keeping the request format of the API stable
- implement different versions of the API without having to change the underlying search engine used
Intentionally, not the complete class hierarchy is duplicated as DTOs.  This should be done when changes are implemented which affects structures which are deeper in the class hierarchy, but would involve a lot of unnecessary churn initially.
In addition, a sample v2 of the search execution API is …
> Introducing DTOs for Search API, selecting version via content negotiation.

- graylog2-web-interface/src/pages/ShowMessagePage.test.tsx
- graylog2-web-interface/test/WrappingContainer.jsx
When using `react-query` in a component, it is necessary to setup `react-query`s `QueryClientProvider` when testing the component. With this PR we are including our `DefaultQueryClientProvider` in the `WrappingContainer`. We use the `WrappingContainer` to wrap all components which are being rendered with the `render` method provided by `wrappedTestingLibrary` and the `mount` method provided by `wrappedEnzyme`.
This way we no longer have to setup the `QueryClientProvider` again in any unit test.
_Please review this PR together with the related enterprise PR._
>  Always wrap components in tests with `react-query`s `QueryClientProvider`.

- graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java
- graylog2-server/src/main/java/org/graylog/security/entities/EntityDescriptor.java
- graylog2-server/src/main/java/org/graylog/security/shares/DefaultGranteeService.java
- graylog2-server/src/main/java/org/graylog/security/shares/EntityShareResponse.java
- graylog2-server/src/main/java/org/graylog/security/shares/EntitySharesService.java
- graylog2-server/src/main/java/org/graylog/security/shares/Grantee.java
- graylog2-server/src/main/java/org/graylog/security/shares/GranteeService.java
- graylog2-server/src/main/java/org/graylog/security/shares/GranteeSharesService.java
- graylog2-server/src/test/java/org/graylog/security/entities/EntityDependencyResolverTest.java
- graylog2-server/src/test/java/org/graylog/security/shares/EntitySharesServiceTest.java
- graylog2-web-interface/src/components/permissions/SharedEntitiesOverview/SharedEntitiesOverviewItem/OwnersCell.test.tsx
- graylog2-web-interface/src/components/permissions/SharedEntitiesOverview/SharedEntitiesOverviewItem/OwnersCell.tsx
- graylog2-web-interface/src/logic/permissions/GRN.tsx
- graylog2-web-interface/src/logic/permissions/types.tsx
**Note:** This requires a backport to `4.1` and `4.2`.
Prior to this PR, displaying a user's shares when an entity existed which is shared with `Everyone` as owner resulted in an exception being thrown, due to the frontend code not handling the grantee's type properly when rendering a summary of the owner.
This is being fixed in this PR. In addition, an inconsistent mapping of the grantee type is addressed, which resulted in `global` grantee's being returned with a type of `builtin-type` instead.
Fixes #11697.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#2977
> Displaying global (shared with everyone) grant on shares page properly.

- graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java
- graylog2-server/src/main/java/org/graylog/security/entities/EntityDescriptor.java
- graylog2-server/src/main/java/org/graylog/security/shares/DefaultGranteeService.java
- graylog2-server/src/main/java/org/graylog/security/shares/EntityShareResponse.java
- graylog2-server/src/main/java/org/graylog/security/shares/EntitySharesService.java
- graylog2-server/src/main/java/org/graylog/security/shares/Grantee.java
- graylog2-server/src/main/java/org/graylog/security/shares/GranteeService.java
- graylog2-server/src/main/java/org/graylog/security/shares/GranteeSharesService.java
- graylog2-server/src/test/java/org/graylog/security/entities/EntityDependencyResolverTest.java
- graylog2-server/src/test/java/org/graylog/security/shares/EntitySharesServiceTest.java
- graylog2-web-interface/src/components/permissions/SharedEntitiesOverview/SharedEntitiesOverviewItem/OwnersCell.test.tsx
- graylog2-web-interface/src/components/permissions/SharedEntitiesOverview/SharedEntitiesOverviewItem/OwnersCell.tsx
- graylog2-web-interface/src/logic/permissions/GRN.tsx
_This is a backport of #11698 for 4.2_
Prior to this PR, displaying a user's shares when an entity existed which is shared with `Everyone` as owner resulted in an exception being thrown, due to the frontend code not handling the grantee's type properly when rendering a summary of the owner.
This is being fixed in this PR. In addition, an inconsistent mapping of the grantee type is addressed, which resulted in `global` grantee's being returned with a type of `builtin-type` instead.
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/2981
> Displaying global (shared with everyone) grant on shares page properly. (backport of #11698 for 4.2)

- graylog2-server/src/main/java/org/graylog/security/entities/EntityDependencyResolver.java
- graylog2-server/src/main/java/org/graylog/security/entities/EntityDescriptor.java
- graylog2-server/src/main/java/org/graylog/security/shares/DefaultGranteeService.java
- graylog2-server/src/main/java/org/graylog/security/shares/EntityShareResponse.java
- graylog2-server/src/main/java/org/graylog/security/shares/EntitySharesService.java
- graylog2-server/src/main/java/org/graylog/security/shares/Grantee.java
- graylog2-server/src/main/java/org/graylog/security/shares/GranteeService.java
- graylog2-server/src/main/java/org/graylog/security/shares/GranteeSharesService.java
- graylog2-server/src/test/java/org/graylog/security/entities/EntityDependencyResolverTest.java
- graylog2-server/src/test/java/org/graylog/security/shares/EntitySharesServiceTest.java
- graylog2-web-interface/src/components/permissions/SharedEntitiesOverview/SharedEntitiesOverviewItem/OwnersCell.test.tsx
- graylog2-web-interface/src/components/permissions/SharedEntitiesOverview/SharedEntitiesOverviewItem/OwnersCell.tsx
- graylog2-web-interface/src/logic/permissions/GRN.tsx
_This is a backport of #11698 for 4.1_
Prior to this PR, displaying a user's shares when an entity existed which is shared with `Everyone` as owner resulted in an exception being thrown, due to the frontend code not handling the grantee's type properly when rendering a summary of the owner.
This is being fixed in this PR. In addition, an inconsistent mapping of the grantee type is addressed, which resulted in `global` grantee's being returned with a type of `builtin-type` instead.
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/2982
> Displaying global (shared with everyone) grant on shares page properly. (backport of #11698 for 4.1)

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackend.java
- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/ESMessageList.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackend.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/ESMessageList.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/elasticsearch/ElasticsearchQueryString.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/BackendQuery.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/QueryParser.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/QueryTest.java
I moved queryString() into BackendQuery Interface.
This change removes a lot of necessary typecasts where they seem uncomfortable. 
The reasoning is, that for the foreseeable future, we'll always have a string-based query language for the backends. If this changes, there will be a lot more and fundamental changes than the - now typecasted - occurences.
There were no tests, the compiler would have shown any mistake.
> add queryString() to BackendQuery Interface

- graylog2-server/src/main/java/org/graylog2/configuration/converters/JavaDurationConverter.java
- graylog2-server/src/test/java/org/graylog2/configuration/converters/JavaDurationConverterTest.java
The main problem with the previous implementation was, that
it would parse jadconfig type 'value+unit' fromats like `10s`
But reproduce the Duration as ISO8601 strings: `PT10S`
When dumping a graylog configuration, these values couldn't be parsed anymore.
-> Change the converter to accept both formats which uses joda Period as conversion helper.
-> Add unit test
> Improve the JavaDurationConverter

- graylog2-server/src/main/java/org/graylog2/bindings/MongoDBModule.java
- graylog2-server/src/main/java/org/graylog2/bindings/ServerBindings.java
- graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java
- graylog2-server/src/main/java/org/graylog2/bootstrap/ServerBootstrap.java
- graylog2-server/src/main/java/org/graylog2/commands/Server.java
If the MongoDB isn't reachable during server startup,
the server will hang for about 60min before exiting with an error.
This is due to the fact, that Guice will not abort instantly when it
hits an error. For each dependency that needs a mongodb connection
a new attempt is made. The default connection timeout is 30s.
A way to improve this, is to test the mongodb connection
early during startup:
- Extract MongoDB Binding into separate MongoDBModule
- Add another hook into the CmdLineTool run() sequence
that is called after the configuration is parsed, but before
the full guice injector is created.
- Request one MongoConnection in beforeInjectorCreation() so we
can get an early exception at startup.
> Fail early if mongodb is unavailable

- graylog2-server/src/main/java/org/graylog2/cluster/leader/AutomaticLeaderElectionService.java
- graylog2-server/src/test/java/org/graylog2/cluster/leader/AutomaticLeaderElectionServiceTest.java
> Give up leader status instantly if lock renewal fails

- graylog2-web-interface/package.json
- graylog2-web-interface/yarn.lock
This PR is performing an intermediate step to address vulnerabilities in existing transitive dependencies. Those cannot be updated directly due to being used by dependencies. Therefore their versions are pinned using the `resolutions` field in `package.json`.
In addition, the `webpack-dev-server` dependency is removed. It was pulling in a couple of outdated, vulnerable dependencies and is not currently in use (due to `devServer.js` using the `webpack-dev-middleware`) directly.
AFAICS none of the vulnerabilities have introduced a vulnerability in the product itself.
> Updating vulnerable deps by pinning versions explicitly.

- graylog2-server/src/main/java/org/graylog2/bootstrap/ServerBootstrap.java
- graylog2-server/src/main/java/org/graylog2/cluster/leader/AutomaticLeaderElectionService.java
- graylog2-server/src/main/java/org/graylog2/cluster/leader/LeaderElectionModule.java
- graylog2-server/src/main/java/org/graylog2/cluster/leader/LeaderElectionService.java
- graylog2-server/src/main/java/org/graylog2/cluster/leader/StaticLeaderElectionService.java
- graylog2-server/src/main/java/org/graylog2/commands/Server.java
- graylog2-server/src/main/java/org/graylog2/system/shutdown/GracefulShutdown.java
- Convert all LeaderElectionService into a true guava Service.
- Remove the LeaderElectionService from the ServiceManager
so we can shutdown it independently and thus very late
in the shutdown sequence.
- Move unlock handling into Service#shutdown() hook.
This is simpler than to have a separate and confusing
giveUpLeader() method.
> Refactor LeaderElectionService start / shutdown

- graylog2-web-interface/src/views/actions/SearchActions.ts
- graylog2-web-interface/src/views/components/widgets/MessageList.test.tsx
- graylog2-web-interface/src/views/stores/SearchStore.ts
In a plugin we need to cancel the promise. the cancel method is only
available for the `CancellablePromise`. A `CancellablePromise` is being
used when working with the `FetchProvider`.
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/2976
> Use `CancellablePromise` type instead of `Promise` to type result of `SearchActions.reexecuteSearchTypes`.

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/export/ElasticsearchExportBackend.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/export/ElasticsearchExportBackend.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/export/ElasticsearchExportBackendIT.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/export/CommandFactory.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/export/ExportMessagesCommand.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/export/MessagesRequest.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/export/ResultFormat.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/permissions/SearchUser.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/MessagesResource.java
This PR adds support for user-defined TimeZone in exports. This allows the api request to contain an optional `time_zone` field which is then used to format timestamps. If none is specified, the time zone of the user is used.
Fixes #9546 
Added integration test, additionally manually verified via API calls (see screenshot bellow)
> Add backend support for user-defined TZ in exports

- graylog2-web-interface/src/components/common/ConfirmDialog.tsx
This PR updates the propTypes of the ConfirmDialog component to allow for a string or React element as the child of the confirmation button and cancel button.
This change is needed for https://github.com/Graylog2/graylog-plugin-enterprise/pull/3005
> Update PropTypes of ConfirmDialog for btnConfirmText and btnConfirmCancelText

- graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/strings/KeyValue.java
- graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/functions/FunctionsSnippetsTest.java
- graylog2-server/src/test/resources/org/graylog/plugins/pipelineprocessor/functions/keyValue.txt
The "key_value" pipeline function can now handle quoted values that
contain the configured "delimiter". (by default whitespace)
Example:
The value extracted from "key='a value'" will now be "a value" instead
of "a".
Fixes #11731
Fixes #4751
**Note:** We might want to backport this to 4.2
> Improve "key_value" pipeline function to handle quoted values

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/ESMessageList.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/ESMessageList.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/MessageList.java
- graylog2-server/src/main/java/org/graylog2/rest/resources/search/AbsoluteSearchResource.java
- graylog2-server/src/main/java/org/graylog2/rest/resources/search/KeywordSearchResource.java
- graylog2-server/src/main/java/org/graylog2/rest/resources/search/RelativeSearchResource.java
- graylog2-server/src/main/java/org/graylog2/rest/resources/search/SearchResource.java
- graylog2-server/src/test/java/org/graylog2/rest/resources/search/SearchResourceTest.java
Prior to this PR, the legacy search API was using a separate code path to retrieve search results from ES. In order to benefit from further development, it should use our current search engine.
This PR is using the refactorings performed in #11594 & #11646 to reuse the `SearchExecutor` in the legacy search API. This is performed for the REST methods returning plain results (without scrolling).
> Migrate legacy search API to use current search engine.

- graylog2-server/src/main/java/org/graylog2/plugin/Message.java
- graylog2-server/src/main/java/org/graylog2/plugin/inputs/Extractor.java
- graylog2-server/src/test/java/org/graylog2/plugin/MessageTest.java
- graylog2-server/src/test/java/org/graylog2/plugin/inputs/ExtractorTest.java
* Fix regression when using date converter #11495
* get tests passing
* Run timestamp fallback conversion
If the converter fails for a timestamp value,
run the fallback timestamp conversion, to ensure that a Message
always has a valid timestamp.
* Add tests
* Improve gl2_processing_error message
Showing only the details is not helpful in some cases.
* Improve converter code
We don't need to call removeField before addField.
It will just overwrite the value anyway.
This avoids having to recalculate the message size twice.
Only null values don't get set. Those we need to remove explicitly.
* adjust test to new processing error output
* improve comments
Co-authored-by: Marco Pfatschbacher <marco@graylog.com>
(cherry picked from commit d12d84668242858bdd10d1930e11ec4f604302a2)
> Fix extractor date converters (#11750) (4.2 backport)

- bin/graylogctl
- graylog2-server/src/test/resources/org/graylog/testing/graylognode/Dockerfile
- pom.xml
Apache Log4j2 JNDI features do not protect against attacker controlled
LDAP and other JNDI related endpoints.
- Configure log4j2.formatMsgNoLookups=true by default
- Update log4j to 2.15.0
Details: https://logging.apache.org/log4j/2.x/security.html
> Fixes for log4j CVE-2021-44228

- bin/graylogctl
- graylog2-server/src/test/resources/org/graylog/testing/graylognode/Dockerfile
- pom.xml
Apache Log4j2 JNDI features do not protect against attacker controlled
LDAP and other JNDI related endpoints.
- Configure log4j2.formatMsgNoLookups=true by default
- Update log4j to 2.15.0
Details: https://logging.apache.org/log4j/2.x/security.html
(cherry picked from commit eb0296dff8537f0f188e8c31c82454a963e9e30c)
> Fixes for log4j CVE-2021-44228 (#11786)

- UPGRADING.md
- graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/messages/DropMessage.java
- graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreter.java
- graylog2-server/src/test/java/org/graylog/plugins/pipelineprocessor/processors/PipelineInterpreterTest.java
`drop_message` has 2 purposes:
- prevent the message from being stored in ES
- improve performance by short-circuiting pipeline processing 
The current implementation does not do a good job on the latter. We are excessively conservative about avoiding unexpected side-effects between pipelines that process the same message. As a result, `drop_message` rarely achieves significant performance gains; and resulting metrics are often confusing to users.
We define the behavior more strictly now - which should also be more intuitive to users:
When `drop_message` is called, we complete processing of that stage; as well as all stages up to that stage number in other pipelines (for that message). Any subsequent stages are skipped, across all pipelines.
Resolves #4855
> Stop processing further stages after drop_message

- graylog2-web-interface/src/views/components/searchbar/SearchBarAutocompletions.test.ts
- graylog2-web-interface/src/views/components/searchbar/SearchBarAutocompletions.ts
Currently we are only using synchronous functions to generate auto completions for the query bar query input.
With this PR it will be possible to create `Completer` with an asynchronous `getCompletions` method.
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/3002
> Implement support for asynchronous search bar query input auto completions.

- graylog2-web-interface/src/views/components/searchbar/queryvalidation/validateQuery.test.ts
- graylog2-web-interface/src/views/components/searchbar/queryvalidation/validateQuery.ts
With this change we are using ISO 8601 for times in an absolute
time range. The API expects this format and will throw an
error when using a different format.
> Normalize time range when validating search query.

- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java
- graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
**Note:** This needs a backport to `4.1` and `4.2`.
During index rotation checks, we are also checking if the current deflector alias points to more than one index. If that is the case (for whatever reason), we are trying to repair it by removing the older target. For ES6 this was working before, for ES7 we are using the wrong alias command in the request.
This PR is now fixing the command used and adds an integration test to verify that it is working as expected.
> Fixing issue when auto-fixing deflector alias with multiple targets

- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java
- graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
**Note:** Backport from #11781
During index rotation checks, we are also checking if the current deflector alias points to more than one index. If that is the case (for whatever reason), we are trying to repair it by removing the older target. For ES6 this was working before, for ES7 we are using the wrong alias command in the request.
This PR is now fixing the command used and adds an integration test to verify that it is working as expected.
> Fixing issue when auto-fixing deflector alias with multiple targets (backport to 4.2)

- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java
- graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
**Note:** backport from #11781
During index rotation checks, we are also checking if the current deflector alias points to more than one index. If that is the case (for whatever reason), we are trying to repair it by removing the older target. For ES6 this was working before, for ES7 we are using the wrong alias command in the request.
This PR is now fixing the command used and adds an integration test to verify that it is working as expected.
> Fixing issue when auto-fixing deflector alias with multiple targets (backport to 4.1)

- pom.xml
From Log4j 2.16.0, support for lookups in log messages has been removed for security reasons.
CVE-2021-44228 has shown the JNDI has significant security issues.
2.16.0 disables JNDI by default.
https://logging.apache.org/log4j/2.x/changes-report.html#a2.16.0
> Update Log4J to 2.16.0

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndexFieldTypePollerAdapterES6.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndexFieldTypePollerAdapterES7.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/mapping/FieldMappingApi.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/IndexFieldTypePollerES7IT.java
- graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/FieldTypeDTO.java
- graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/FieldTypeMapper.java
- graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/MappedFieldTypesService.java
- graylog2-server/src/main/java/org/graylog2/indexer/fieldtypes/MongoFieldTypeLookup.java
- graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/FieldTypeMapperTest.java
- graylog2-server/src/test/java/org/graylog2/indexer/fieldtypes/IndexFieldTypePollerIT.java
Prior to this PR, generating field types relied solely on the type literal returned by the indexer and other properties of the index mapping were not considered. This could lead to e.g. the `source` field, which is mapped as a `text` field, but with `fielddata` enabled, to be mapped as a `string` field which is not `enumerable`.
This change is now taking the `fielddata` property into account. If it is present (therefore explicitly requested), the resulting type will be `enumerable`. If it is not present, it is up to the mapped type if it is `enumerable` or not (e.g. for `keyword` being `enumerable` anyway).
We are relying more and more on field types and their properties to decide if certain functionalities in the frontend (enabling aggregations, providing suggestions etc.) are active or …
> Consider fielddata for field types, making them enumerable if enabled.

- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchFilterDeprecationWarningsInterceptor.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/ElasticsearchFilterDeprecationWarningsInterceptorTest.java
`elasticsearch_mute_deprecation_warnings = true` doesn't work for the warning about "system indices" because of a typo that omits a space between "direct" and "access". The warning in question, in full, reads: `299 Elasticsearch-7.15.2-93d5a7f6192e8a1a12e154a2b81bf6fa7309da0c "this request accesses aliases with names reserved for system indices: [.security], but in a future major version, direct access to system indices and their aliases will not be allowed`.
Fixes issue #9822.
Not tested, but confirmed that the Elasticsearch error message has *always had a space in it*, by reviewing the `git blame` from the [deprecation commit](https://github.com/elastic/elasticsearch/commit/91f4b58bf71249cf81562bd6069c64aafa46591b) to HEAD in the elasticsearch repository: …
> Fix typo in deprecation warnings filter

- graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ips/IpAddress.java
**Note:** Due to the simplicity of this fix, we should consider backporting it to `4.1` and `4.2`.
Prior to this PR, when a message had an instance of an `IpAddress` (added through a pipeline rule) in one of its fields, indexing that message results in an infinite recursion due to trying to serialize `IpAddress#getAnonymized` (which returns a new, "anonymized" instance of itself and another attempt to serialize that one is started). What is even worse, there is no way to recover from this than deleting the complete journal. All further message indexing will stall until this is resolved.
An example rule to trigger this could look like this:
```
rule "Adding IP field"
when
true
then
set_field("client_ip", to_ip("192.168.1.42"));
end
```
This PR is now marking `IpAddress#getAnonymized` to be …
> Prevent infinite recursion when serializing `IpAddress`.

- graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/OkHttpClientProvider.java
- graylog2-server/src/test/java/org/graylog2/shared/bindings/providers/OkHttpClientProviderTest.java
Graylog resolves `http_proxy_uri` only once on startup. This forces customers to restart GL when they have changed the DNS; and prevents dynamic proxy configuration.
We now resolve the proxy address at the time of usage, rather than at startup.
Resolves #6377
> Perform dynamic proxy lookup

- pom.xml
From Log4j 2.16.0, support for lookups in log messages has been removed for security reasons.
CVE-2021-44228 has shown the JNDI has significant security issues.
2.16.0 disables JNDI by default.
https://logging.apache.org/log4j/2.x/changes-report.html#a2.16.0
(cherry picked from commit dd24b85cd1bbe1d8504d4670f6b0c394b41cc2d9)
> Update Log4J to 2.16.0 (#11814)

- graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ips/IpAddress.java
(cherry picked from commit a306d4b79255ef7e4e9b635148dea724ee84a850)
> Prevent infinite recursion when serializing `IpAddress`. (#11736)

- graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/functions/ips/IpAddress.java
(cherry picked from commit a306d4b79255ef7e4e9b635148dea724ee84a850)
> Prevent infinite recursion when serializing `IpAddress`. (4.1 backport)

- graylog-project-parent/pom.xml
- pom.xml
The following rules are active:
- Require maven version >= 3.6.0
- Require a unix platform (this includes macOS and Linux)
- Require Java version 1.8
- Add banned dependencies
/jenkins-pr-deps Graylog2/graylog-plugin-threatintel#210,Graylog2/graylog-plugin-enterprise-integrations#698
> Add and configure maven enforcer plugin

- pom.xml
From Log4j 2.17.0, fix string substitution recursion and limit JNDI to the java protocol only
CVE-2021-45105  - https://logging.apache.org/log4j/2.x/security.html
https://logging.apache.org/log4j/2.x/changes-report.html#a2.17.0
> update log4j from 2.16.0 to 2.17.0

- graylog-project-parent/pom.xml
- graylog2-server/src/main/java/org/graylog/metrics/prometheus/PrometheusExporterHTTPServer.java
- graylog2-server/src/main/java/org/graylog2/periodical/GarbageCollectionWarningThread.java
The `internalRuntimeForbidden` option got removed in forbiddenapis
version 3.0. It got replaced with the `jdk-non-portable` bundled
signature.
Also use the `commons-io.version` property to select the correct
`commons-io-unsafe` bundled signature.
> Replace removed `internalRuntimeForbidden` for forbiddenapis

- graylog2-server/src/main/java/org/graylog2/plugin/Version.java
This updates our Version class to keep any existing build metadata
instead of overwriting it with the Git revision.
**Note:** This PR must be backported to the 4.2 branch.
> Preserve build metadata in graylog version

- graylog2-server/src/main/java/org/graylog2/lookup/LookupTableService.java
Opens up LookupTableService a bit to allow for easier extending. Just adds a handful of getter methods and changes a couple private modifiers to protected to allow for subclass visibility.
Allows for an IlluminateLookupTableService to extend the existing service, take advantage of existing code, and apply Illuminate-specific logic on top
locally in a development environment
> Opens up LookupTableService for extension

- pom.xml
Fixes CVE-2021-44832  (https://logging.apache.org/log4j/2.x/security.html#CVE-2021-44832)
which is not critical, because it requires an attacker that can modify your local
log4j logging configuration.
> Update Log4J to 2.17.1

- pom.xml
Fixes CVE-2021-44832  (https://logging.apache.org/log4j/2.x/security.html#CVE-2021-44832)
which is not critical, because it requires an attacker that can modify your local
log4j logging configuration.
(cherry picked from commit 242f8266902a03353e700eae7430339b6baef6b4)
> Update Log4J to 2.17.1 (4.2 backport)

- pom.xml
Fixes CVE-2021-44832  (https://logging.apache.org/log4j/2.x/security.html#CVE-2021-44832)
which is not critical, because it requires an attacker that can modify your local
log4j logging configuration.
(cherry picked from commit 242f8266902a03353e700eae7430339b6baef6b4)
> Update Log4J to 2.17.1 (4.1 backport)

- graylog2-server/src/main/java/org/graylog2/plugin/Message.java
- graylog2-server/src/main/java/org/graylog2/plugin/inputs/Extractor.java
- graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java
- graylog2-server/src/test/java/org/graylog2/plugin/MessageTest.java
- graylog2-server/src/test/java/org/graylog2/plugin/inputs/ExtractorTest.java
With #11149 we introduced a change that ensured that a message will
have a valid DateTime as the timestamp field.
The conversion or fallback (plus recording errors) was performed when
setting the `timestamp` field.
This caused problems (#11495) with date converters on extractors.
They work by first assiging the non-converted timestamp string to the
message, and then use this string in the date converter.
A fix for this was done in #11750
However, looking at another user's issue with a json extractor
(https://github.com/Graylog2/graylog2-server/issues/11495#issuecomment-996536075)
made me rethink the previous approach.
Our processing works by mutating a Message object and thus passing field
values from one processing step to another.
Enforcing a DateTime object on the timestamp field in …
> Perform message timestamp conversion after processing

- graylog2-server/src/main/java/org/graylog2/plugin/Message.java
- graylog2-server/src/main/java/org/graylog2/plugin/inputs/Extractor.java
- graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/ProcessBufferProcessor.java
- graylog2-server/src/test/java/org/graylog2/plugin/MessageTest.java
- graylog2-server/src/test/java/org/graylog2/plugin/inputs/ExtractorTest.java
With #11149 we introduced a change that ensured that a message will
have a valid DateTime as the timestamp field.
The conversion or fallback (plus recording errors) was performed when
setting the `timestamp` field.
This caused problems (#11495) with date converters on extractors.
They work by first assiging the non-converted timestamp string to the
message, and then use this string in the date converter.
A fix for this was done in #11750
However, looking at another user's issue with a json extractor
(https://github.com/Graylog2/graylog2-server/issues/11495#issuecomment-996536075)
made me rethink the previous approach.
Our processing works by mutating a Message object and thus passing field
values from one processing step to another.
Enforcing a DateTime object on the timestamp field in …
> Perform message timestamp conversion after processing (#11884) (4.2 backport)

- graylog2-web-interface/package.json
- graylog2-web-interface/src/components/common/Portal.test.tsx
- graylog2-web-interface/src/components/common/Portal.tsx
- graylog2-web-interface/src/components/common/SortableList/SortableListItem.tsx
- graylog2-web-interface/src/components/common/index.tsx
- graylog2-web-interface/src/views/components/aggregationbuilder/ConfigurableElement.jsx
- graylog2-web-interface/src/views/components/aggregationbuilder/DescriptionBox.jsx
- graylog2-web-interface/src/views/components/common/PortaledPopover.tsx
- graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchForm.test.tsx
- graylog2-web-interface/src/views/components/searchbar/saved-search/SavedSearchForm.tsx
- graylog2-web-interface/yarn.lock
With this PR we are replacing the library `react-portal`, since it is no longer being maintained.
This will make it easier to upgrade to react v17.
Instead of the `Portal` component provided by `react-portal` we are now using our own `Portal` component, which is just a wrapper for `react-dom`s `createPortal`.
> Replace `react-portal` with native react portals.

- graylog2-web-interface/package.json
- graylog2-web-interface/yarn.lock
There are not so many important changes between `9.2.1` and `9.5.0` (https://github.com/securingsincity/react-ace/blob/main/CHANGELOG.md ), but I tested the newer version recently and see no disadvantage in upgrading the package.
> Bump react-ace from 9.2.1 to 9.5.0

- graylog2-web-interface/packages/eslint-config-graylog/index.js
Fixing the `react/jsx-no-constructed-context-values` linter hints results in performance improvements. These improvements are not so relevant when writing tests. Disabling this rule for tests makes it easier to write them.
> Disable ESLint rule `react/jsx-no-constructed-context-values` for tests.

- graylog2-server/src/main/java/org/graylog/plugins/pipelineprocessor/rest/SimulatorResource.java
- graylog2-server/src/main/java/org/graylog2/rest/models/messages/responses/ChangedField.java
- graylog2-server/src/main/java/org/graylog2/rest/models/messages/responses/DecorationStats.java
- graylog2-server/src/test/java/org/graylog2/rest/models/messages/responses/SimulationResultsTest.java
- graylog2-web-interface/src/components/simulator/SimulationChanges.jsx
The diff of fields added, removed, and changed during pipeline simulation is now created on the back end as opposed to the front end 
Related to Graylog2/graylog-plugin-enterprise#2880. Generating pre/post-processing diffs on the back end makes it easier to unit test. Also logically it just makes more sense to create the diff on the back end vs front end. 
Ran Graylog locally in my development environment, set up a pipeline to change, add, and remove fields from a message, and confirmed that the output on the front end is correct based on the pre/post processed message. Also tested hitting Illuminate sim from command line with help from Michael to ensure all added, removed, and changed fields return properly.
> Moves simulation diff logic to backend

- graylog2-web-interface/src/views/logic/views/UseLoadView.tsx
- graylog2-web-interface/src/views/pages/NewSearchPage.test.tsx
Before this change we were just throwing an in some cases error when loading a view, but not displaying the
error message in a way it can be read by the user.
> Display error page when error occures while loading a view.

- graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
- graylog2-server/src/main/java/org/graylog2/shared/users/ChangeUserRequest.java
- graylog2-server/src/main/java/org/graylog2/shared/users/UserManagementService.java
- graylog2-server/src/main/java/org/graylog2/users/UserManagementServiceImpl.java
User profile data is store in the DB. In the case of external users in the cloud we also sync changes back to the Identity Provider (i.e. Okta). However, we only want to do this when changing attributes that are actually managed by the IP.
Pass the `ChangeUserRequest` object to the `UserManagementService`, so it can determine whether a sync is needed.
> Pass ChangeUserRequest to user mgmt service

- graylog2-web-interface/src/components/streams/StreamForm.jsx
These changes enable selecting Index Sets when using Stream form in Cloud. 
fix https://github.com/Graylog2/graylog-plugin-cloud/issues/988
> Allow Index Set selection on stream in Cloud

- graylog2-web-interface/package.json
- graylog2-web-interface/src/components/common/ElementDimensions.test.tsx
- graylog2-web-interface/src/components/common/ElementDimensions.tsx
- graylog2-web-interface/src/components/common/index.tsx
- graylog2-web-interface/src/views/components/QueryBar.test.tsx
- graylog2-web-interface/src/views/components/QueryTabs.tsx
- graylog2-web-interface/src/views/components/Search.dashboard.test.tsx
- graylog2-web-interface/src/views/components/WidgetGrid.test.tsx
- graylog2-web-interface/src/views/components/WidgetGrid.tsx
- graylog2-web-interface/src/views/components/sidebar/fields/List.tsx
- graylog2-web-interface/src/views/components/visualizations/number/NumberVisualization.test.tsx
- graylog2-web-interface/src/views/components/visualizations/number/NumberVisualization.tsx
- graylog2-web-interface/test/setup-jest.js
- graylog2-web-interface/yarn.lock
With https://github.com/Graylog2/graylog2-server/pull/11933 we implemented a hook to get the current dimensions of an element by using the `ResizeObserver` interface.
With this PR we are creating the common component `ElementDimensions` which implements this hook and which replaces the `SizeMe` component from `react-sizeme`.  `react-sizeme` is not using the `ResizeObserver` interface and has a slightly lower performance.
Since the `useElementDimensions` hook is working with a ref, the `ElementDimensions` component behaves slightly different than the `SizeMe` component. `ElementDimensions` is rendering a `div`, which is not the case when using the `SizeMe` component.
For our current use cases this is fine and in most cases we can just do the following: `const ParentComponent = …
> Replace `react-sizeme` with own implementation which has a slightly better performance.

- graylog2-web-interface/src/components/nodes/NodeMaintenanceDropdown.jsx
- graylog2-web-interface/src/components/nodes/NodesActions.jsx
Currently, node-specific API Browser links don't match up with the base URL that gets set when [`graylog2-server/src/main/resources/swagger/index.html.template`](https://github.com/Graylog2/graylog2-server/blob/4dd8d8740fa387ee37b23954c6d13877d6680b79/graylog2-server/src/main/resources/swagger/index.html.template) is rendered.  This results in the API Browser appearing to reload or refresh when a user clicks a link due to the transition from `/api-browser` to `/api-browser/`.
This PR updates up the node-specific API Browser links to match that page's base URL (i.e. adds a trailing `/`), and also deals with some `react/destructuring-assignment` linter errors.
Fixes #11802.
1. Clicked the node-specific links to load  `/api-browser/`, and then confirmed clicking anchor links didn't result in …
> Align Graylog node API Browser links with latter's base URL.

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/Elasticsearch6Plugin.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/testing/ElasticsearchInstanceES6.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/Elasticsearch7Plugin.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/ElasticsearchInstanceES7.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/OpensearchInstance.java
- graylog2-server/src/main/java/org/graylog/plugins/views/migrations/V20200730000000_AddGl2MessageIdFieldAliasForEvents.java
- graylog2-server/src/main/java/org/graylog2/configuration/converters/MajorVersionConverter.java
- graylog2-server/src/main/java/org/graylog2/periodical/ESVersionCheckPeriodical.java
- graylog2-server/src/main/java/org/graylog2/storage/SearchVersion.java
- graylog2-server/src/main/java/org/graylog2/storage/versionprobe/VersionProbe.java
- graylog2-server/src/test/java/org/graylog/plugins/views/migrations/V20200730000000_AddGl2MessageIdFieldAliasForEventsTest.java
- graylog2-server/src/test/java/org/graylog2/configuration/validators/DetectedSearchVersionValidatorTest.java
- graylog2-server/src/test/java/org/graylog2/indexer/EventsIndexMappingTest.java
- graylog2-server/src/test/java/org/graylog2/indexer/IndexMappingFactoryTest.java
- graylog2-server/src/test/java/org/graylog2/indexer/IndexMappingTest.java
- graylog2-server/src/test/java/org/graylog2/indexer/cluster/NodeTest.java
- graylog2-server/src/test/java/org/graylog2/periodical/ESVersionCheckPeriodicalTest.java
- graylog2-server/src/test/java/org/graylog2/storage/SearchVersionTest.java
Removed the unnecessary org.graylog2.plugin.Version dependency (and its eager `CURRENT_CLASSPATH` init) from the SearchVersion class.
Majority of the `SearchVersion` usages accessed the underlying `com.github.zafarkhaja.semver.Version`, not the `org.graylog2.plugin.Version` and the `org.graylog2.plugin.Version` served only as a wrapper.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#3125
Existing test suite that covers the usage on many places.
> SearchVersion cleanup and refactoring

- .github/workflows/build.yml
We are still experiencing timeouts during maven builds running on github infrastructure. @dennisoelkers discovered this https://github.com/actions/virtual-environments/issues/1499#issuecomment-689467080, which should help. 
This PR adds a workaround for the connections, configuring various http options that should prevent the issue.
> Attempt to fix timeout issues in github builds

- graylog2-web-interface/src/contexts/StreamsContext.tsx
This is needed for the enterprise\security plugin to be able to use the
singleton StreamsContext
- StreamsContext is now wrapped in our singleton method.
- Needed so that the enterprise plugin can consume the StreamsContext without creating a new one.
- Tested locally and unit tests ran.
> StreamsContext singleton wrapper

- graylog2-web-interface/src/util/StringUtils.test.ts
- graylog2-web-interface/src/util/StringUtils.ts
- graylog2-web-interface/src/views/components/ViewTypeLabel.test.tsx
- graylog2-web-interface/src/views/components/ViewTypeLabel.ts
- graylog2-web-interface/src/views/components/messagelist/PossiblyHighlight.tsx
- graylog2-web-interface/src/views/components/sidebar/description/ViewDescription.tsx
- Adds the `toTitleCase` function the StringUtils which converts a string to title case based on string separator.
- It also adds unit tests for the file that covers the new functionality and old existing functionality.
- This also contains conversion to Typescript.
This was needed functionality for a separate component in
enterprise-plugins.
- Needed string functionality for a feature in the enterprise-plugin
- The frontend unit test suite was run
> StringUtils toTitleCase and upgrade to TS

- graylog2-web-interface/src/util/DocsHelper.js
- graylog2-web-interface/src/views/components/searchbar/queryvalidation/QueryValidation.test.tsx
- graylog2-web-interface/src/views/components/searchbar/queryvalidation/QueryValidation.tsx
With https://github.com/Graylog2/graylog2-server/pull/11534 we are now validating the search query and display an explanation when there is an error.
Currently the popover for the explanations contains just a link for the search query language documentation.
With this PR we are now displaying an error specific documentation link. The supported error types are `Parse Exception`, `Invalid Operator` and `Unknown field`.
Please note, the documentation does not yet include the sections for the related explanations. But we can already merge this PR, since the error specific documentation links are still pointing to https://docs.graylog.org/docs/query-language.
Fixes: https://github.com/Graylog2/graylog2-server/issues/11849
> Display error specific documentation links for query input validation.

- graylog2-web-interface/src/components/common/ExpandableList.tsx
This change for the `ExpandableList` component is necessary to style the component with `styled-components`.
> Allow overwriting `ExpandableList` styles.

- full-backend-tests/src/test/java/org/graylog/plugins/views/SearchSyncIT.java
- full-backend-tests/src/test/resources/org/graylog/plugins/views/mongodb-stored-searches-for-execution-endpoint.json
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ExecutionStateGlobalOverride.java
Prior to this change, the `keep_search_types`/`search_types` properties were not deserialized properly, because a collection builder was used. Jackson seems to be unable to use these for properties, so additional builder methods were added for these.
> Fixing deserialization of global override.

- full-backend-tests/src/test/java/org/graylog/plugins/views/SuggestionResourceIT.java
- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/QuerySuggestionsES6.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/QuerySuggestionsES7.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/suggestions/SuggestionRequest.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/engine/suggestions/SuggestionResponse.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SuggestionsResource.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/suggestions/SuggestionsDTO.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/suggestions/SuggestionsRequestDTO.java
Allow controlling the size param, requesting a specified count of suggestions (with default 10 and max 100). Additionally, the response now contains the `sum_other_docs_count`, indicating how many documents with the requested fields exist out of the suggestion(=aggregation) scope. If the value is zero, the provided suggestions cover all possible values.
> Suggestions size param, other docs count

- graylog2-web-interface/src/views/components/searchbar/queryvalidation/validateQuery.test.ts
- graylog2-web-interface/src/views/components/searchbar/queryvalidation/validateQuery.ts
Currently we do not catch server errors when validating a search query,
which can affect the search bar validation and lead to unexpected behaviours.
We are now displaying a user notification and returning status: 'OK' in
this case. By returning this status we can avoid unexpected behaviours.
Before this change we had a problem when using undeclared parameters in a search query, which results in a server error.
In another PR we will handle undeclared parameters differently and return common validation errors. This way we will handle "undeclared parameter" errors like other validation errors.
> Improve handling of server errors when validating a search query.

- graylog2-web-interface/src/views/components/searchbar/completions/FieldValueCompletion.test.ts
- graylog2-web-interface/src/views/components/searchbar/completions/FieldValueCompletion.ts
Please note, this PR needs be tested together with https://github.com/Graylog2/graylog2-server/pull/11959 or after the PR has been merged.
As described in https://github.com/Graylog2/graylog2-server/issues/11850 we are currently only fetching the 10 most important field value suggestions after writing the field name in a search query.
With this PR we are now fetching 30 suggestions and we are refetching the suggestions when the user continues typing in a more specific field value prefix. We only fetch more suggestions, when we did not fetched all suggestions with the first request.
We are also displaying spelling corrections slightly different than suggestions which are just based on the field value prefix. These corrections include the currently defined field value name in their caption. …
> Improve fetching of field value suggestions which are being displayed for the search query input.

- graylog2-web-interface/src/components/common/BrowserTime.test.tsx
- graylog2-web-interface/src/components/common/BrowserTime.tsx
- graylog2-web-interface/src/components/common/RelativeTime.test.tsx
- graylog2-web-interface/src/components/common/RelativeTime.tsx
- graylog2-web-interface/src/components/common/index.tsx
- graylog2-web-interface/src/components/indexers/IndexerFailure.jsx
- graylog2-web-interface/src/components/indices/IndexRangeSummary.jsx
- graylog2-web-interface/src/components/indices/IndexSummary.jsx
- graylog2-web-interface/src/components/nodes/JournalDetails.jsx
- graylog2-web-interface/src/components/nodes/RestApiOverview.jsx
- graylog2-web-interface/src/components/notifications/Notification.jsx
- graylog2-web-interface/src/components/pipelines/PipelineDetails.tsx
- graylog2-web-interface/src/components/rules/RuleListEntry.tsx
- graylog2-web-interface/src/components/sidecars/sidecars/SidecarRow.jsx
- graylog2-web-interface/src/components/systemjobs/SystemJob.jsx
- graylog2-web-interface/src/components/times/TimesList.jsx
- graylog2-web-interface/src/components/users/TokenList.test.jsx
- graylog2-web-interface/src/components/users/TokenList.tsx
- graylog2-web-interface/src/components/users/UsersOverview/UserOverviewItem/LoggedInCell.tsx
Please note:
- this PR needs to be tested together with https://github.com/Graylog2/graylog-plugin-enterprise/pull/3121
With https://github.com/Graylog2/graylog2-server/pull/11986 we added date time utility functions. With this PR are creating the `RelativeTime` and `BrowserTime` components which are basically just wrapper for these utility functions.
Before this change the `Timestamp` component was responsible for displaying relative times and times based on the user time zone. In a follow-up PR we will refactor the `Timestamp` in a way it will only be responsible to display a time based on the user time zone. This way we can separate the concerns.
> Implement new components to display times relatively and based on the browser time zone.

- graylog2-server/src/main/java/org/graylog2/plugin/inputs/codecs/NullCodec.java
- graylog2-server/src/main/java/org/graylog2/shared/buffers/processors/DecodingProcessor.java
This codec always returns a null Message.
Can be used in situations where we don't need a real codec or a message should be simply dropped after decoding.
> Move NullCodec to server

- graylog2-web-interface/src/views/components/searchbar/QueryInput.test.tsx
- graylog2-web-interface/src/views/components/searchbar/QueryInput.tsx
- graylog2-web-interface/src/views/components/searchbar/queryvalidation/QueryValidation.test.tsx
- graylog2-web-interface/test/fixtures/queryValidationState.ts
This PR is fixing two bugs for the query input where an action provided for the `QueryInput` worked with outdated references:
- the `completers`, before this change they references an outdated version of the selected time range and streams.
- the `onExecute` action, before this change this function referenced an outdated an outed version of the `error` prop.
Before this change we tried to configure the editor, by using the relevant editor prop, like
- `onLoad` for the initial configuration
- `completers` for the custom completers
- `commands` for the custom commands
Unfortunately this is not an option when defining data which relies on external data, like `error`, `timeRange` and `streams`. In this case the reference for the external data is not up to date, whenever the ace editor is …
> Ensure query input editor always references the latest provided data.

- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/ClusterES6IT.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/IndexFieldTypePollerES6IT.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/IndicesGetAllMessageFieldsES6IT.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/MessagesES6IT.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/NodeES6IT.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/ScrollResultES6IT.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/SearchesES6IT.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/testing/ElasticsearchBaseTestIT.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/testing/ElasticsearchInstanceES6.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/export/ElasticsearchExportBackendScrollingIT.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/export/ElasticsearchExportBackendSearchAfterIT.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/OpensearchInstance.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/testing/RunningElasticsearchInstanceES7.java
- graylog2-server/src/test/java/org/graylog/testing/completebackend/ContainerizedGraylogBackend.java
- graylog2-server/src/test/java/org/graylog/testing/completebackend/GraylogBackend.java
- graylog2-server/src/test/java/org/graylog/testing/completebackend/RunningGraylogBackend.java
- graylog2-server/src/test/java/org/graylog/testing/containermatrix/ContainerMatrixTestEngine.java
- graylog2-server/src/test/java/org/graylog/testing/elasticsearch/SearchServerInstance.java
- graylog2-server/src/test/java/org/graylog/testing/elasticsearch/TestableSearchServerInstance.java
- graylog2-server/src/test/java/org/junit/jupiter/engine/descriptor/ContainerMatrixTestWithRunningESMongoTestsDescriptor.java
- graylog2-server/src/test/java/org/junit/jupiter/engine/descriptor/ContainerMatrixTestsDescriptor.java
- graylog2-server/src/test/java/org/junit/platform/engine/support/hierarchical/ContainerMatrixHierarchicalTestEngine.java
A new type of GraylogBackend has been created to support faster testing of Integration Tests during development of said tests.
`GRAYLOG_TEST_WITH_RUNNING_ES_AND_MONGODB=true`
Motivation is, that you want to be able to test Integration Tests easily during development of said tests. The process of running the test in the IDE is time consuming because all of the packages and images are created and started. This is naturally what you want during full builds with maven or while running the CI - but not while you're creating the test in development.
You can now add an ENV-var while running the test from the IDE and test with an existing, running GL Backend and running ES and Mongo Containers.
- You need a running ES7 and MongoDB on their standard ports (either locally installed or Docker …
> ContainerMatrixTests running against existing Instances

- graylog2-web-interface/src/components/alarmcallbacks/AlarmCallbackHistory.jsx
- graylog2-web-interface/src/components/alerts/Alert.jsx
- graylog2-web-interface/src/components/alerts/AlertMessages.jsx
- graylog2-web-interface/src/components/common/Timestamp.test.tsx
- graylog2-web-interface/src/components/common/Timestamp.tsx
- graylog2-web-interface/src/components/content-packs/ContentPackInstallView.jsx
- graylog2-web-interface/src/components/events/events/Events.jsx
- graylog2-web-interface/src/components/indexers/IndexerFailure.jsx
- graylog2-web-interface/src/components/indices/IndexRangeSummary.jsx
- graylog2-web-interface/src/components/nodes/SystemInformation.jsx
- graylog2-web-interface/src/components/sidecars/configuration-forms/ImportsViewModal.jsx
- graylog2-web-interface/src/components/sidecars/sidecars/SidecarStatusFileList.jsx
- graylog2-web-interface/src/components/times/TimesList.jsx
- graylog2-web-interface/src/pages/ShowAlertPage.jsx
- graylog2-web-interface/src/views/components/DashboardSearchBar.test.tsx
- graylog2-web-interface/src/views/components/Value.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/__tests__/AggregationWizard.metric.test.tsx
- graylog2-web-interface/src/views/components/datatable/DataTable.test.tsx
- graylog2-web-interface/src/views/components/datatable/DataTableEntry.test.tsx
- graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.test.tsx
- graylog2-web-interface/src/views/components/messagelist/CustomHighlighting.tsx
- graylog2-web-interface/src/views/components/messagelist/MessagePreview.test.tsx
- graylog2-web-interface/src/views/components/messagelist/MessageTableEntry.test.tsx
- graylog2-web-interface/src/views/components/sidebar/Sidebar.test.tsx
- graylog2-web-interface/src/views/components/sidebar/description/SearchResultOverview.tsx
- graylog2-web-interface/src/views/components/widgets/MessageTable.test.tsx
Please note this PR needs to be tested together with https://github.com/Graylog2/graylog-plugin-enterprise/pull/3122
With this PR we are refactoring the `Timestamp` component. With this change we are unifying the way we display most timestamps in the UI.
Before these changes the component was also responsible for displaying a time relatively and based on the browser time zone. Now its main responsibility is displaying times based on the user time zone. It is still possible to define a custom time zone, when needed.
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/3122
> Simplify `Timestamp` component and unify format of timestamps displayed in the UI.

- graylog2-web-interface/src/components/common/Spinner.tsx
The `Spinner` component has a `margin-right` for the spinner icon, which creates space between the icon and the text.
With this PR we are not setting the margin, when there is no text.
> Only display margin between loading spinner icon and text when text is provided.

- graylog2-web-interface/src/contexts/UserDateTimeProvider.test.tsx
- graylog2-web-interface/src/contexts/UserDateTimeProvider.tsx
We are using the `UserDateTimeContext` to display times based on the user time zone. In some cases it can be useful to be able to control this timezone. For example if you want to display all times on a page in a specific timezone.
By overriding the timezone in the `UserDateTimeProvider` we are changing the timezone for all displayed times.
> Allow overriding user timezone in `UserDateTimeProvider`.

- graylog2-web-interface/src/views/components/defaultTitle.ts
- graylog2-web-interface/src/views/components/useWidgetResults.ts
- graylog2-web-interface/src/views/types.ts
For some widget export helper functions we are now only typing the data we are really using.
Before this change these functions expected a complete `Widget`.
With the less complex types they are more flexible because we do not need provide a complete widget to satisfy TypeScript.
> Define more flexible widget export types.

- graylog2-web-interface/packages/eslint-config-graylog/index.js
- graylog2-web-interface/src/components/common/SourceCodeEditor.jsx
- graylog2-web-interface/src/components/pipelines/Pipeline.tsx
- graylog2-web-interface/src/components/search/MessageDetail.jsx
- graylog2-web-interface/src/pages/ConfigurationsPage.tsx
- graylog2-web-interface/src/pages/EditExtractorsPage.jsx
- graylog2-web-interface/src/pages/ExportExtractorsPage.jsx
- graylog2-web-interface/src/pages/ImportExtractorsPage.jsx
- graylog2-web-interface/src/views/components/messagelist/FormatReceivedBy.tsx
- graylog2-web-interface/src/views/components/messagelist/MessageActions.tsx
- graylog2-web-interface/src/views/components/messagelist/MessageDetail.tsx
This PR is disabling the [`react/destructuring-assignment`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/destructuring-assignment.md) rule. While destructuring props is still encouraged, it does not make sense to enforce this for legacy code which is otherwise working well. In addition, it does produce unwanted errors in some cases while providing very little benefits for most situations.
> Do not enforce destructuring assignments in linter.

- graylog2-web-interface/src/components/common/BrowserTime.test.tsx
- graylog2-web-interface/src/components/common/BrowserTime.tsx
- graylog2-web-interface/src/components/common/RelativeTime.test.tsx
- graylog2-web-interface/src/components/common/RelativeTime.tsx
- graylog2-web-interface/src/components/common/Timestamp.test.tsx
- graylog2-web-interface/src/components/common/Timestamp.tsx
We recently refactored the `Timestamp`, and implemented the `RelativeTime` and `BrowserTime` components to unify the way we display times in the UI.
One part of the refactoring was replacing the usage of the `logic/DateTime` class. The class constructor used the current time by default when no date time has been provided. With this PR we are now also using the current time by default for the mentioned components.
This is also fixing a bug, since the current implementation throws an error (`Date time null is not valid.`) when the date time for these components is not defined. This happened on the system overview page because the `started_at` field of system jobs can be null.
> Use current time per default for the `Timestamp`, `RelativeTime` and `BrowserTime` component when `dateTime` prop is not defined.

- full-backend-tests/src/test/java/org/graylog/plugins/views/QueryValidationResourceIT.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/ParsedTerm.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/QueryValidationServiceImpl.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/TermCollectingQueryVisitor.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/ValidationMessage.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/parser/LuceneQueryParserTest.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/validation/ValidationMessageTest.java
Code cleanup + removed the original query from parsing exception message (see the screenshot bellow)
- Cleaner approach to term key token (the key is always only one token, we don't need a list for that).
- The failed parsing of query triggered a huge warning message when the query was long. We don't need to repeat the whole query, as the user already sees it in the UI anyway.
Adapted unit and integration tests
> Lucene query parser code cleanup

- graylog2-web-interface/src/views/components/searchbar/completions/FieldNameCompletion.test.ts
- graylog2-web-interface/src/views/components/searchbar/completions/FieldNameCompletion.ts
This PR is improving field names indexing performance in the field names completion class, which is happening every time the field types store is refreshed.
Prior to this PR, a `reduce` call was used, subsequently merging objects into each other. For large numbers of fields, this is creating excessive load. A simpler way using `Object.fromEntries` is now being used, which is creating the object from the given array in a linear way.
In addition, a couple of cleanups are performed. These should not be part of backport PRs.
Refs #11930.
As this issue results from users with performance issues for a high number of fields, I ingested messages adding up to a number of 25000 fields being present. After that, loading the initial search page was profiled. Before the change it took about 30s, …
> Improve indexing field names performance for field name completion.

- graylog2-server/src/main/java/org/graylog2/plugin/Version.java
In a cloud dev environment the version info for the cloud
is missing. This makes it hard to see other messages
in the server log.
> Don't print a stacktrace for missing version files

- graylog2-web-interface/src/components/common/Icon.tsx
Fixes https://github.com/Graylog2/graylog2-server/issues/12131
Fixes https://github.com/Graylog2/graylog2-server/issues/12166
During investigation I found that Icon component doesn't expect some necessary props.  
So I checked in the code which props we try to use and add them to the Icon  component
As component doesn't expect a lot of props we are not able to handle events when we use Icon component
[](https://github.com/Graylog2/graylog2-server/issues/12131 )
> Add props onClick, onMouseEnter, onMouseLeave, onFocus, tabIndex, title to Icon component

- graylog2-web-interface/src/contexts/UserDateTimeContext.ts
- graylog2-web-interface/src/contexts/UserDateTimeProvider.tsx
- graylog2-web-interface/src/util/DateTime.ts
- graylog2-web-interface/src/views/components/aggregationbuilder/AggregationBuilder.tsx
- graylog2-web-interface/src/views/components/defaultTitle.ts
- graylog2-web-interface/src/views/components/visualizations/ChartData.ts
- graylog2-web-interface/src/views/components/visualizations/TransformKeys.ts
- graylog2-web-interface/src/views/components/visualizations/XYPlot.tsx
- graylog2-web-interface/src/views/components/visualizations/__tests__/ChartData.test.ts
- graylog2-web-interface/src/views/components/visualizations/__tests__/TransformKeys.fixtures.ts
- graylog2-web-interface/src/views/components/visualizations/__tests__/TransformKeys.test.ts
- graylog2-web-interface/src/views/components/visualizations/__tests__/XYPlot.test.tsx
- graylog2-web-interface/src/views/components/visualizations/area/AreaVisualization.tsx
- graylog2-web-interface/src/views/components/visualizations/area/__tests__/AreaVisualization.test.tsx
- graylog2-web-interface/src/views/components/visualizations/bar/BarVisualization.tsx
- graylog2-web-interface/src/views/components/visualizations/heatmap/HeatmapVisualization.tsx
- graylog2-web-interface/src/views/components/visualizations/heatmap/__tests__/HeatmapVisualization.test.tsx
- graylog2-web-interface/src/views/components/visualizations/line/LineVisualization.tsx
- graylog2-web-interface/src/views/components/visualizations/pie/PieVisualization.tsx
- graylog2-web-interface/src/views/components/visualizations/scatter/ScatterVisualization.tsx
- graylog2-web-interface/src/views/components/visualizations/useChartData.ts
- graylog2-web-interface/src/views/components/visualizations/useEvents.ts
- graylog2-web-interface/src/views/components/visualizations/worldmap/WorldMapVisualization.tsx
- graylog2-web-interface/src/views/components/visualizations/worldmap/__tests__/WorldMapVisualization.test.tsx
- graylog2-web-interface/src/views/logic/searchtypes/events/EventHandler.test.ts
- graylog2-web-interface/src/views/logic/searchtypes/events/EventHandler.ts
Prior to this PR, the transformation pipeline for chart data was accessing the `CurrentUserStore` directly to extract the current user's timezone and apply it to timestamps in chart data.
This PR is now changing this to use the `UserDateTimeContext`. This also makes it possible to override the timezone through a context provider.
Fixes: https://github.com/Graylog2/graylog2-server/issues/11341
> Use formatter from user's date time context in charts.

- graylog2-web-interface/src/views/components/export/ExportModal.tsx
fix #12006 
In `_getInitialWidgetFields` function, which map the Array of selected fields, instead of Immutable Set use OrderSet. 
We used Immutable function Set to transform Array into Immutable Set structure. Immutable Set doesn't keep an order which was in the array. Due to that we had unexpected sorting order  in  input of selected fields.
> Change Set to OrderSet in ExportModal.tsx to keep order of the columns

- graylog2-server/src/main/java/org/graylog2/plugin/periodical/Periodical.java
A periodical implementation could return null
for getLogger() and that would abort a scheduled periodical forever.
Mark getLogger() as @Nonnull and also provide a fallback logger.
> Improve Periodical exception handling

- graylog2-server/src/main/java/org/graylog2/plugin/inject/Graylog2Module.java
Always register ViewResolvers as singletons.
Ensures that a single instance is instantiated at server-startup time, versus an additional instance each time the map is injected, which can cause initialization operations to be repeated each time ViewsResource methods accessed.
Tested to ensure that view resolvers are still properly injected into ViewsResource.
> Always register ViewResolvers as singletons

- graylog2-server/src/main/java/org/graylog2/database/PaginatedDbService.java
- graylog2-server/src/main/java/org/graylog2/notifications/Notification.java
- graylog2-web-interface/src/logic/notifications/NotificationsFactory.js
Add a notification type for archiving errors. 
This is used in the related Enterprise PR https://github.com/Graylog2/graylog-plugin-enterprise/pull/3148.
See https://github.com/Graylog2/graylog-plugin-enterprise/issues/3127 for details.
> Add a notification for archiving errors

- graylog2-server/src/main/java/org/graylog2/grok/GrokPatternService.java
- graylog2-server/src/main/java/org/graylog2/grok/InMemoryGrokPatternService.java
- graylog2-server/src/main/java/org/graylog2/grok/MongoDbGrokPatternService.java
- graylog2-server/src/main/java/org/graylog2/rest/resources/system/GrokResource.java
- graylog2-server/src/test/java/org/graylog2/grok/InMemoryGrokPatternServiceTest.java
- graylog2-server/src/test/java/org/graylog2/grok/MongoDbGrokPatternServiceTest.java
- graylog2-server/src/test/java/org/graylog2/inputs/extractors/GrokExtractorTest.java
- graylog2-server/src/test/java/org/graylog2/rest/resources/system/GrokResourceTest.java
- graylog2-web-interface/src/components/grok-patterns/BulkLoadPatternModal.jsx
- graylog2-web-interface/src/stores/grok-patterns/GrokPatternsStore.ts
Adds an option to update Grok patterns on bulk import if they already exist.
This effectively provides three options when performing bulk imports:
1. Abort import if there is a name conflict with any of the patterns already present in graylog. This is the default.
2. If there is a name conflict, update the pattern with that name in graylog with the new pattern provided in the import.
3. Drop all existing patterns in graylog before importing the new set of patterns.
The dialog for importing patterns now shows these options.
Before:
After:
Fixes https://github.com/Graylog2/graylog2-server/issues/11109
> Allow bulk update of Grok patterns

- graylog2-web-interface/src/views/components/visualizations/ChartData.ts
- graylog2-web-interface/src/views/components/visualizations/XYPlot.tsx
- graylog2-web-interface/src/views/components/visualizations/__tests__/ChartData.test.simple.sourceMatcher.result.json
- graylog2-web-interface/src/views/components/visualizations/__tests__/XYPlot.test.tsx
In #11639, plotly.js was updated to v2.x. Starting with this release, two changes were made: hover templates defaulting to exponential notation and the `hovermode` defaulting to `closest`, showing only a single, unified tooltip on hover.
This PR is now restoring the original behavior by explicitly soecifying `hovermode` and `yhoverformat` for plots.
Fixes #11917.
> Using decimal/float representation of y values, showing x/y hovers.

- graylog2-web-interface/src/views/logic/views/MoveWidgetToTab.ts
- graylog2-web-interface/src/views/logic/views/__snapshots__/MoveWidgetToTab.test.ts.snap
This change is making sure that when a widget is moved to a different dashboard page (without copying it), it will keep its id. This avoids any issues with referential integrity when the widget is referenced somewhere else by id (e.g. reporting).
Nothing changes when the widget is copied instead of being moved. The source widget will stay as is (keeping its id) and the new widget will get a new, random id. This way any references will stay intact, referencing the old widget.
> Ensure that widget keeps id when moved to another dashboard page.

- graylog2-web-interface/src/views/components/searchbar/completions/FieldNameCompletion.test.tsx
- graylog2-web-interface/src/views/components/searchbar/completions/FieldNameCompletion.ts
This PR is improving field names indexing performance in the field names completion class, which is happening every time the field types store is refreshed.
Prior to this PR, a `reduce` call was used, subsequently merging objects into each other. For large numbers of fields, this is creating excessive load. A simpler way using `Object.fromEntries` is now being used, which is creating the object from the given array in a linear way.
Refs #11930.
As this issue results from users with performance issues for a high number of fields, I ingested messages adding up to a number of 25000 fields being present. After that, loading the initial search page was profiled. Before the change it took about 30s, afterwards less than 4s.
> Improving generating initial field name index. (4.2)

- graylog2-web-interface/src/views/components/searchbar/completions/FieldNameCompletion.test.tsx
- graylog2-web-interface/src/views/components/searchbar/completions/FieldNameCompletion.ts
This PR is improving field names indexing performance in the field names completion class, which is happening every time the field types store is refreshed.
Prior to this PR, a `reduce` call was used, subsequently merging objects into each other. For large numbers of fields, this is creating excessive load. A simpler way using `Object.fromEntries` is now being used, which is creating the object from the given array in a linear way.
Refs #11930.
As this issue results from users with performance issues for a high number of fields, I ingested messages adding up to a number of 25000 fields being present. After that, loading the initial search page was profiled. Before the change it took about 30s, afterwards less than 4s.
> Improving generating initial field name index. (4.1)

- graylog2-web-interface/src/views/components/export/ExportModal.tsx
**Note:** This is a backport of #12180 to `4.2`.
Fixes #12006.
In `_getInitialWidgetFields` function, which map the Array of selected fields, instead of Immutable Set use OrderSet. 
We used Immutable function Set to transform Array into Immutable Set structure. Immutable Set doesn't keep an order which was in the array. Due to that we had unexpected sorting order  in  input of selected fields.
> Change Set to OrderSet in ExportModal.tsx to keep order of the columns (4.2)

- graylog2-web-interface/src/views/components/export/ExportModal.tsx
**Note:** This is a backport of #12180 to `4.1`.
Fixes #12006.
In `_getInitialWidgetFields` function, which map the Array of selected fields, instead of Immutable Set use OrderSet. 
We used Immutable function Set to transform Array into Immutable Set structure. Immutable Set doesn't keep an order which was in the array. Due to that we had unexpected sorting order  in  input of selected fields.
> Change Set to OrderSet in ExportModal.tsx to keep order of the columns (4.1)

- graylog2-web-interface/src/util/URLUtils.ts
**Note:** This should be backported to `4.1` as well.
Prior to this change, when generating URLs from the frontend that directly link to the API (e.g. for downloading exports, reports, etc.), it was checked if the browser supports embedding crendentials in the URL. This check was written at a time when MS Edge was not based on Chromium yet. Therefore it was assuming that it does not support it.
This has changed, therefore the check for Edge is removed. The whole logic will vanish with the introduction of session cookies, therefore a further revamp is not necessary.
> Support credentials in URLs for MS Edge.

- graylog2-web-interface/src/views/logic/views/MoveWidgetToTab.ts
- graylog2-web-interface/src/views/logic/views/__snapshots__/MoveWidgetToTab.test.ts.snap
_This is a backport of #12185 for 4.1_
This change is making sure that when a widget is moved to a different dashboard page (without copying it), it will keep its id. This avoids any issues with referential integrity when the widget is referenced somewhere else by id (e.g. reporting).
Nothing changes when the widget is copied instead of being moved. The source widget will stay as is (keeping its id) and the new widget will get a new, random id. This way any references will stay intact, referencing the old widget.
> Fix/ensure widget keeps id when moved (backport of #12185 for 4.1)

- graylog2-web-interface/src/util/URLUtils.ts
**This is a backport of https://github.com/Graylog2/graylog2-server/pull/12194 for 4.1**
Prior to this change, when generating URLs from the frontend that directly link to the API (e.g. for downloading exports, reports, etc.), it was checked if the browser supports embedding crendentials in the URL. This check was written at a time when MS Edge was not based on Chromium yet. Therefore it was assuming that it does not support it.
This has changed, therefore the check for Edge is removed. The whole logic will vanish with the introduction of session cookies, therefore a further revamp is not necessary.
> Support credentials in URLs for MS Edge. (backport of #12194 for 4.1)

- graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightForm.tsx
**This is a backport of https://github.com/Graylog2/graylog2-server/pull/12188 for 4.1**
Change `_isRequire` rule to recognize only `""`, `undefined`, `null` as unfilled.
When the user highlights some field with a `false` or  `0` value the form recognizes this value as not filled. Due to that we see an error that field is required
> Fix/highlighting bool message field in a dashboard/issue (backport of #12188 for 4.1)

- graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightForm.tsx
_This is a backport of https://github.com/Graylog2/graylog2-server/pull/12188 for 4.2_
Change `_isRequire` rule to recognize only `""`, `undefined`, `null` as unfilled.
When the user highlights some field with a `false` or  `0` value the form recognizes this value as not filled. Due to that we see an error that field is required
> Fix/highlighting bool message field in a dashboard/issue (backport of #12188 for 4.2)

- full-backend-tests/src/test/java/org/graylog/testing/utils/GelfInputUtils.java
- graylog2-server/src/test/java/org/graylog/testing/completebackend/README.md
- graylog2-server/src/test/java/org/graylog/testing/containermatrix/ContainerMatrixTestEngine.java
- Added GRAYLOG_TEST_WITH_RUNNING_ES_AND_MONGODB documentation and better parsing
- Do not create GELF input in IT if there is already one existing (useful in combination with the :point_up: flag)
The `GRAYLOG_TEST_WITH_RUNNING_ES_AND_MONGODB` had no documentation in README and has been quite hard to discover and use. Additionally, its value parsing now handles boolean values, so it's easier to enable/disable the feature in tests.
Additionally, the gelf input utils verify, that there is already an input listening on the default gelf port. If yes, no additional input will be created. This prevents adding more and more inputs in case of running tests against existing developer instance.
The utils are heavily used in the integration tests, so any problem there would be discovered by the …
> Integration tests: GRAYLOG_TEST_WITH_RUNNING_ES_AND_MONGODB fixes

- graylog2-web-interface/src/pages/RuntimeErrorPage.jsx
During the report generation the backend needs to know if a FE error occurred. In that case, we can prematurely terminate the waiting logic and correctly propagate the FE exception and its stacktrace. This PR adds an unique ID so we can recognize the error in the page easily. 
This PR completes changes started in https://github.com/Graylog2/graylog-plugin-enterprise/pull/3240
> Add render-error id to the error message

- graylog2-web-interface/src/views/components/DashboardSearchBar.tsx
- graylog2-web-interface/src/views/components/SearchBar.tsx
- graylog2-web-interface/src/views/components/WidgetQueryControls.tsx
- graylog2-web-interface/src/views/components/searchbar/ValidateOnParameterChange.test.tsx
- graylog2-web-interface/src/views/components/searchbar/ValidateOnParameterChange.tsx
Recently we implemented the search query validation. When an error in a query exists we disable the submit and display an error explanation. This currently results in a bug when working with parameters, because we display an error for undeclared parameters, but we do not validate the query again, when a parameter gets declared or when a user adds parameter bindings.
> Validate search query on parameter changes.

- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/SearchRequestFactory.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/SearchRequestFactoryTest.java
Our use cases for scroll queries are:
- Archinving
- Alerting
- CSV log export
Unconditionally activating highlighting makes no sense,
is more expensive and might also cause errors on big documents,
if they exceed `index.highlight.max_analyzed_offset`
This is only needed for ES7 / OpenSearch support.
Our ES6 client never had scroll highlighting enabled.
> Disable search highlighter for scroll queries

- graylog2-web-interface/src/views/components/export/ExportModal.test.tsx
- Add a new test case to check the column order while exporting. In some cases, while data transforming (f.e. if you use Immutable Set with more than 8 items) the sorting might not be as in the initial array
- add `triggerFormSubmit` fn to reuse login in  several test cases 
- refactor elint error recording to `queryBy*`, `getBy*` usage
> Add new test case for ExportModal.test.tsx, add triggerFormSubmit, refactor eslint error

- graylog2-web-interface/src/contexts/UserDateTimeProvider.test.tsx
- graylog2-web-interface/src/util/DateTime.test.ts
- graylog2-web-interface/src/util/DateTime.ts
Before this change we were throwing an error when providing an invalid date for the `DateTime` utils.
This "fail early" approach makes the usage of invalid dates more obvious, but it introduced bugs like: https://github.com/Graylog2/graylog2-server/issues/12193
We are now just tracking an error in the console instead. 
Fixes: https://github.com/Graylog2/graylog2-server/issues/12193
> Do no throw errors for invalid dates.

- graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightForm.test.tsx
- graylog2-web-interface/src/views/components/sidebar/highlighting/HighlightForm.tsx
- graylog2-web-interface/src/views/logic/views/formatting/highlighting/HighlightingRule.ts
fix #11985 
Change `_isRequire` rule to recognize only `""`, `undefined`, `null` as unfilled.
When the user highlights some field with a `false` or  `0` value the form recognizes this value as not filled. Due to that we see an error that field is required
> Change _isRequire validation to accept false and 0 values in HighlightForm

- graylog2-server/src/main/java/org/graylog2/rest/models/system/sessions/responses/DefaultSessionResponseFactory.java
With the implementation of the cookie auth in #11788 we encountered a bug #12220 that prevents log-in for never expiring sessions. 
Cookies generally don't allow unlimited TTL, they always require a `maxAge` value. The common workaround is to set this value to the very distant future. This PR does exactly that - for never-expiring session configuration it sets the cookie to be valid for 10 years from the moment of login. It's rather a workaround and we should think about removing the non-expiring functionality generally, as we can't implement it correctly.
Fixes #12220 
**TODO** add an integration test!
> Hotfix for never-expiring session validity #12220

- graylog2-web-interface/src/components/bootstrap/BootstrapModalForm.jsx
- graylog2-web-interface/src/util/DocsHelper.js
- graylog2-web-interface/src/views/components/searchbar/queryvalidation/QueryValidation.test.tsx
- graylog2-web-interface/src/views/components/searchbar/queryvalidation/QueryValidation.tsx
- graylog2-web-interface/src/views/components/searchbar/queryvalidation/types.ts
- graylog2-web-interface/src/views/components/searchbar/queryvalidation/validateQuery.ts
- graylog2-web-interface/src/views/types.ts
- graylog2-web-interface/test/fixtures/queryValidationState.ts
**_Please note: This PR needs to be merged after: https://github.com/Graylog2/graylog2-server/pull/12192_**
With this PR it will be possible to render plugable components inside the query validation error explanation. This allows rendering components for plugin specific errors.
We are also updating the query validation state type based on the changes we implemented with
> Render plugable components in query validation error explanation and adjust query validation type.

- graylog2-server/src/main/java/org/graylog2/system/shutdown/GracefulShutdown.java
During shutdown, at first, set the load balancer status to "DEAD" and then pause for the configured load balancer recognition period. Only after that trigger the lifecycle change to "HALTING".
Previously, we would start with triggering the lifecycle change to "HALTING" prior to pausing for load balancer recognition. This would set the load balancer status to "DEAD" but at the same time, any service listening for the lifecycle change to "HALTING" would already take action and potentially shut down.
While in most cases this shouldn't be a problem, it is e.g. for the server-side of the cloud forwarder which runs as a service and stops accepting messages when server shutdown is detected. With this change, the load balancer status is set now set to "DEAD" ahead of time.
> Wait for node balancer recognition period before triggering "HALTING" lifecycle

- graylog2-web-interface/src/views/components/TypeSpecificValue.tsx
- graylog2-web-interface/src/views/components/WidgetQueryControls.test.tsx
- graylog2-web-interface/src/views/components/messagelist/MessageDetail.tsx
- graylog2-web-interface/src/views/components/searchbar/WidgetTimeRangeOverride.tsx
- graylog2-web-interface/src/views/components/widgets/TimerangeInfo.tsx
With https://github.com/Graylog2/graylog2-server/pull/11994 we unified the format of most timestamps in the UI (`YYYY-MM-DD HH:mm:ss`). One unintentional change was that we no longer display milliseconds for timestamps in the message table widget.
With this PR we are reverting this change. We are also making sure we:
- we display milliseconds for the widget time range info, which will be displayed on dashboards after configuring a time range in the dashboard search bar.
- we display the time range override in the widget edit mode in the user time zone. This time range override is also visible  after configuring a time range in the dashboard search bar.
> Display milliseconds for all date times on search page.

- graylog2-server/src/main/java/org/graylog2/configuration/ElasticsearchConfiguration.java
- graylog2-server/src/main/java/org/graylog2/configuration/validators/RotationStrategyValidator.java
- graylog2-server/src/main/java/org/graylog2/rest/models/system/indices/RotationStrategies.java
- graylog2-server/src/main/java/org/graylog2/rest/resources/system/indices/RotationStrategyResource.java
- graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/RotationStrategyValidatorTest.java
Fixes #12246
Rotation strategies are returned in the same order in /system/indices/rotation/strategies endpoint.
TimeBasedRotationStrategy is the first/default one if nothing is configured in graylog.conf file.
Validator for "enabled_index_rotation_strategies" will not allow to put duplicates in this property.
Every time the Create Index Set page was opened, the Index Rotation Configuration gets randomly selected from provided 3 options. It was caused by the fact that back-end returned the strategies in random order.
1. Open the System -> Indices page
2. Click on the Create Index Set button
3. Verify which rotation strategy is selected
4. Refresh the page and verify again what strategy is pre-selected now
> Fix a problem with a random rotation strategy order

- graylog2-web-interface/packages/eslint-config-graylog/index.js
We have some ESLint rule overrides for frontend (unit) tests in our `eslint-config-graylog` package. With this PR we are also applying these specific rules for integration tests.
> Apply test specific ESLint rules also for integration tests.

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivot/ESPivot.java
- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivots/ESPivotTest.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/ESPivot.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivots/ESPivotTest.java
Fixes #12236.
After this change, we start using proper time range in the search response when search has not results.
Aggregations are not used to fetch time range in that situation, but time range from the pivot is used instead.
It has been discovered in #12236.
When we have no results in search response, we still used to obtain time range from aggregations, namely **"timestamp-min"** and **"timestamp-max"**. Those aggregations behaved differently in different versions of ES. The most problematic approach was visible in ES7, when they contained +/- Infinity, resulting in extremely strange time range used:
> from: "292278994-08-17T07:12:55.807Z"
> to: "-292275055-05-16T16:47:04.192Z"
In ES6 everything seemed to work, but I changed the code there to have the same approach used in both …
> Using proper time range when search has not results.

- graylog2-web-interface/src/views/components/searchbar/TimeRangeInput.test.tsx
- graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.test.tsx
- graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimeRangeDropdown.tsx
- graylog2-web-interface/src/views/components/searchbar/date-time-picker/TimerangeDropdown.relativeTimeRange.test.tsx
- graylog2-web-interface/src/views/components/widgets/Widget.aggregations.test.tsx
_Please note: This PR needs to be merged together with https://github.com/Graylog2/graylog-plugin-enterprise/pull/3283_
Before this change the default time range in the date time picker was not based on the user time zone.
You can test this by selecting a dashboard, opening the date time picker in the search bar and selecting the "absolute" tab. Of course you need to be logged in with a user who has a configured time zone.
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/3283
> Create default absolute time range in date time picker based on user time zone.

- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/SearchRequestFactory.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/SearchRequestFactoryTest.java
Our use cases for scroll queries are:
- Archinving
- Alerting
- CSV log export
Unconditionally activating highlighting makes no sense,
is more expensive and might also cause errors on big documents,
if they exceed `index.highlight.max_analyzed_offset`
(cherry picked from commit 3bb5207c60bfdd8c0f31886eb499d6a6dddd9a48)
> Disable search highlighter for scroll queries (#12225) (4.2 backport)

- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/SearchRequestFactory.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/SearchRequestFactoryTest.java
Our use cases for scroll queries are:
- Archinving
- Alerting
- CSV log export
Unconditionally activating highlighting makes no sense,
is more expensive and might also cause errors on big documents,
if they exceed `index.highlight.max_analyzed_offset`
(cherry picked from commit 3bb5207c60bfdd8c0f31886eb499d6a6dddd9a48)
> Disable search highlighter for scroll queries (#12225) (4.1 backport)

- graylog2-server/src/main/java/org/graylog/plugins/views/search/db/SearchesCleanUpJob.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewResolver.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/db/SearchesCleanUpJobTest.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/db/SearchesCleanUpJobWithDBServicesTest.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewsResourceTest.java
Adjusts search cleanup logic in [SearchesCleanUpJob.java](https://github.com/Graylog2/graylog2-server/pull/12280/files#diff-f9658be5e836517c7def7ffe2dc9825a00b0e314140c983298e72794db483c79) to prevent the deletion of search ids which are referenced by view resolvers. Previously, when this cleanup job would run (once every 4 days by default) and delete searches which might have been associated with view resolvers.
Core Graylog server changed needed for https://github.com/Graylog2/graylog-plugin-enterprise/pull/3308.
Tested to ensure that view resolver searches are not deleted when the corresponding IDs are returned from the `ViewResolver.getSearchIds()` method.
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/3308
> Prevent deletion of ViewResolver searches

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndicesAdapterES6.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java
- graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java
- graylog2-server/src/main/java/org/graylog2/indexer/indices/IndicesAdapter.java
ES assigns a UUID to each index. This information is useful e.g. to resolve situations where an index name is re-used. 
We expose the UUID via `Indices.getIndexId()`
> Expose ES index UUID

- graylog2-web-interface/src/views/components/searchbar/completions/FieldValueCompletion.test.ts
- graylog2-web-interface/src/views/components/searchbar/completions/FieldValueCompletion.ts
- graylog2-web-interface/src/views/components/searchbar/queryinput/QueryInput.tsx
In some cases we display suggestions for field values in the search query, e.g. for query strings like:
`http_method:` and `http_method:POS`
After every query string change we check if we should open the query input autocomplete (we are calling `shouldShowCompletions` of every defined completer class). Opening the autocomplete triggers the actual fetching of completions (we are calling `getCompletions` of every defined completer class).
This PR is improving the logic by:
- not calling `getCompletions` on the initial render
- making sure `shouldShowCompletions` of the `FieldValueCompleter` does not return true for a query string  like `http_method:POST` where `http_method` is the currently selected token.
This change is fixing https://github.com/Graylog2/graylog2-server/issues/12165. In …
> Improve fetching of query field value suggestions.

- graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchDomain.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewResolver.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/views/ViewService.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/SearchDomainTest.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/db/SearchesCleanUpJobTest.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/ViewsResourceTest.java
The `SearchDomain hasReadPermissionFor()` method is responsible for verifying that the current user is authorized to view the search record for the provided `ViewDTO`. Support for external view resolvers was added in https://github.com/Graylog2/graylog2-server/pull/12089. However, when implemented, support for authorizing search access for resolved views was not added, so resolved views were not accessible for non-admin users.
This PR adjusts the `SearchDomain hasReadPermissionFor()` logic to also query search records for resolved views, which subsequently allows permissions checks to be completed for them. 
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/3315
This is needed to fix a bug for Graylog Security. See …
> Add support for checking resolved view permissions

- graylog2-server/src/main/java/org/graylog/plugins/views/search/errors/MissingEnterpriseLicenseException.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/errors/UnboundParameterError.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ValidationTypeDTO.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/QueryValidationServiceImpl.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/ValidationType.java
Adapted query validation logic to catch https://github.com/Graylog2/graylog2-server/issues/12271
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#3303
Fixes #12271
> Fix validation of enterprise params without license

- graylog2-server/src/test/resources/org/graylog/testing/graylognode/Dockerfile
If Jenkins is under high load, sometimes report generation takes longer than the default 180 seconds so we set a higher timeout in the Dockerfile for integration testing.
The Dockerfile is part of the regular graylog2-server, so this is an additional change with enterprise PR #3289
> Upped Timeout for Report Generation in Integration Tests

- graylog2-web-interface/src/components/common/Select.tsx
This PR is avoiding to pass `undefined` to `react-select`, as it would effectively turn it into an uncontrolled component, leading to the component not clearing its value when the state change was triggered externally. Instead, we are passing an empty array.
Fixes #12263
> Avoid passing `undefined` value to react-select.

- graylog2-web-interface/src/util/DocsHelper.js
- graylog2-web-interface/src/views/components/searchbar/queryvalidation/QueryValidation.tsx
- graylog2-web-interface/test/fixtures/queryValidationState.ts
This PR is updating the identifier we use in the frontend for the query validation parsing error type.
This is necessary, because we changed the id in the backend recently.
Based on this identifier we display error type specific documentation links.
> Update identifier for query validation parsing error type.

- graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.test.tsx
- graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.ts
_Please note, we need to create a backport for this bugfix._
As described in https://github.com/Graylog2/graylog2-server/issues/11388 the search URL params are currently not being updated, when selecting a time range by dragging over a histogram.
There are a few linter warnings in the related files, which I did not fixed, to ensure we do not introduce new bugs with this bugfix.
Fixes https://github.com/Graylog2/graylog2-server/issues/11388
> Update search URL params when selecting a time range in histogram.

- graylog2-web-interface/src/views/components/SearchResult.test.tsx
- graylog2-web-interface/src/views/components/SearchResult.tsx
Before this change we were hiding the search results, when a search refresh hooks sets an error. This is currently the case for parameter errors, e.g. when a parameter needs to be declared.
This can be confusing for users, but it can also result in disappearing changes, when editing a widget, as described in https://github.com/Graylog2/graylog-plugin-enterprise/issues/3281.
This solution is not fixing all related problems, for example if you remove a parameter on a dashboard, which is being used in a widget query, we display the "Undeclared parameter" warning, but it is still not possible to remove the parameter name from the widget query. In every case it is an improvement.
Before: 
After:
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/3281
> Do not hide search results when search refresh hook sets an error, but display overlay.

- graylog2-web-interface/src/views/hooks/BindSearchParamsFromQuery.test.ts
- graylog2-web-interface/src/views/logic/NormalizeSearchURLQueryParams.test.ts
- graylog2-web-interface/src/views/logic/queries/Query.test.ts
- graylog2-web-interface/src/views/logic/queries/Query.ts
This PR is fixing a bug which caused multiple search creations and executions when opening the search page and when executing a search. This affected the following requests:
- `/views/search/metadata`
- `http://localhost:8080/api/views/search`
- `/api/views/search/[search-id]/execute`
Before this change the deep equal check inside `BindSearchParamsFromQuery` always returned false, because the filter of the existing query was `null` and filter of the possible new query was `undefined`. Of course, only when no query filter has been defined.
> Fixing bug which resulted in multiple search creations and executions.

- graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.test.tsx
- graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.ts
_This is a backport of #12306 for 4.2_
As described in https://github.com/Graylog2/graylog2-server/issues/11388 the search URL params are currently not being updated, when selecting a time range by dragging over a histogram.
There are a few linter warnings in the related files, which I did not fixed, to ensure we do not introduce new bugs with this bugfix.
Fixes https://github.com/Graylog2/graylog2-server/issues/11388
> Update search URL params when selecting a time range in histogram. (backport of #12306 for 4.2)

- full-backend-tests/src/test/java/org/graylog2/indexer/indices/IndicesIT.java
Adding a simple integration test for getIndexId() to ensure it works against the supported platforms.
> Integration test for getIndexId()

- graylog2-server/src/main/java/org/graylog2/commands/Server.java
The ClusterConfigValidatorModule introduced a dependency,
through the GeoIpResolverConfigValidator which breaks the migration command.
```
2022-03-17 16:05:09,624 ERROR: org.graylog2.bootstrap.CmdLineTool - Guice error (more detail on log level debug): No implementation for org.graylog.plugins.map.geoip.GeoIpResolverFactory was bound.
Exception in thread "main" com.google.inject.CreationException: Unable to create injector, see the following errors:
1) [Guice/MissingImplementation]: No implementation for GeoIpResolverFactory was bound.
Requested by:
1  : GeoIpVendorResolverService.<init>(GeoIpVendorResolverService.java:33)
\_ for 1st parameter
at GeoIpResolverConfigValidator.<init>(GeoIpResolverConfigValidator.java:48)
\_ for 1st parameter
at …
```
> Don't exclude the MapWidgetModule when running the migrations command

- graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.test.tsx
- graylog2-web-interface/src/views/hooks/SyncWithQueryParameters.ts
_This is a backport of #12306 for 4.1_
As described in https://github.com/Graylog2/graylog2-server/issues/11388 the search URL params are currently not being updated, when selecting a time range by dragging over a histogram.
There are a few linter warnings in the related files, which I did not fixed, to ensure we do not introduce new bugs with this bugfix.
Fixes https://github.com/Graylog2/graylog2-server/issues/11388
> Update search URL params when selecting a time range in histogram. (backport of #12306 for 4.1)

- graylog2-server/src/main/java/org/graylog/plugins/views/search/errors/EmptyParameterError.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ValidationTypeDTO.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/QueryValidationServiceImpl.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/ValidationType.java
This PR does two things, both related to the validation of enterprise params:
* Handling of empty lookup params with correct type and query positions highlighted
* Change validation errors of empty params to WARNING instead of ERROR
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#3316
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/3297 (makes the problem more obvious and provides better error messages)
Added integration test (see the related PR in the enterprise repo)
(:point_up: old screenshot, now it will be only yellow warning, not red error)
> Better validation error for empty lookup param

- graylog2-web-interface/src/views/components/WithSearchStatus.tsx
Fixes: #12261 
In the current implementation, we block submit button when we have at least one undeclared parameter in `SearchMetadataStore`. 
```
const _disableSearch = (undeclaredParameters, parameterBindings, usedParameters) => {
const bindingsMap = getParameterBindingsAsMap(parameterBindings);
const missingValues = usedParameters.filter((param) => (param.needsBinding && !param.optional)).map((p) => bindingsMap.get(p.name)).filter((value) => !trim(value));
return undeclaredParameters.size > 0 || missingValues.size > 0;
};
....
{
searchMetadata: SearchMetadataStore,
executionState: SearchExecutionStateStore,
configurations: SearchConfigStore,
},
({ searchMetadata, executionState, configurations }) => ({
isDisabled: _disableSearch(searchMetadata.undeclared, …
```
> Remove condition which block search button when are undeclared params

- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ExecutionState.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ExecutionStateGlobalOverride.java
This PR is fixing (de-)serialization for the `ExecutionState`/`ExecutionStateGlobalOverride` classes. They were missing required annotations for properties which are nullable (for deserialization) or should be serialized.
Missing these lead to exporting searches/search types containing parameters to fail. The reason for this is that the created export job was missing the parameter bindings due to them not being serialized properly.
Fixes Graylog2/graylog-plugin-enterprise#3327
> Fixing serialization of execution state for export jobs.

- graylog2-web-interface/webpack.vendor.js
This PR is disabling the [`sideEffects`](https://webpack.js.org/configuration/optimization/#optimizationsideeffects) option in webpack's config for the vendor bundle (only). Prior to this change, it was not possible for webpack to detect which modules inside the vendor bundle were used by plugins. This lead to some modules being left out of the bundle which are actually usedr, leading to module resolution errors at runtime.
> Fixing tree shaking for vendor bundle.

- graylog2-server/src/main/java/org/graylog2/bootstrap/CmdLineTool.java
- graylog2-server/src/main/java/org/graylog2/bootstrap/ServerBootstrap.java
- graylog2-server/src/main/java/org/graylog2/shared/bindings/IsDevelopmentBindings.java
- graylog2-server/src/main/java/org/graylog2/shared/bindings/RestApiBindings.java
- graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/IsDevelopmentServerProvider.java
- graylog2-server/src/main/java/org/graylog2/web/IndexHtmlGeneratorProvider.java
This PR provides an injectable (as "isDevelopmentServer") boolean that indicates if the Graylog server is run in development (through the `DEVELOPMENT` system property). The flag can then be used to change the server's behavior depending on if it's run in development or not, e.g. if it should provide frontend assets or not.
> Provide injectable flag indicating if server is in development.

- graylog2-server/src/main/java/org/graylog2/shared/security/AccessTokenAuthToken.java
- graylog2-server/src/main/java/org/graylog2/shared/security/SessionIdToken.java
Note: @patrickmann had created the initial round of backports (all mentioned in the original issue https://github.com/Graylog2/graylog-plugin-enterprise/issues/3418), but it appears that the `4.3` backport was missed, so I am creating it now.
> backport graylog-plugin-enterprise/issues/3418 to 4.3 

- graylog2-web-interface/src/util/AppConfig.ts
- graylog2-web-interface/webpack.config.js
The GRAYLOG_API_URL environment variable was used for two development
features:
- Configuring the proxy backend for the development web server
(devServer.js)
- Configuring the backend URL for the user interface (AppConfig.ts)
The latter will break cookie authentication when GRAYLOG_API_URL is set
because the URL might point to a different host than the web interface.
That prevents the cookie to be used for requests to the backend due to
the same-origin policy.
This commit removes the handling of the environment variable in the UI.
The development web server proxy backend can still be configured using
the variable.
> Remove UI support for the GRAYLOG_API_URL environment variable

- graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/TermCollectingQueryVisitor.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/parser/LuceneQueryParserTest.java
Fixes #12425.
Description with screenshot is provided in the #12425 issue.
After this fix, you can safely type "logni~" and you will get results with "login" text, fuzziness works!
Type a fuzzy query string (i.e. smth~) in the search bar and notice the error is shown on the bottom of the screen.
see #12425
> Fuzzy operator does not break query validation anymore.

- graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/TermCollectingQueryVisitor.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/parser/LuceneQueryParserTest.java
Backporting PR #12428, fixing issue #12425 on 4.3.
> Fuzzy operator does not break query validation anymore (4.3)

- graylog2-web-interface/src/views/components/visualizations/number/AutoFontSizer.tsx
- graylog2-web-interface/src/views/components/visualizations/number/NumberVisualization.tsx
Prior to this PR, the number visualization of the search did not properly center the values it displays. Values were slightly misaligned towards the top of the widget.
This change is now making sure that values in a number visualization are always centered vertically and horizontally.
Before:
After:
> Center value in number visualization properly.

- graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
Minor improvement to the [main PR](https://github.com/Graylog2/graylog2-server/pull/12405) so we are not sensitive to case in the role name check.
> graylog-plugin-enterprise/issues/3419 errata

- full-backend-tests/src/test/java/org/graylog/plugins/views/QueryValidationResourceIT.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/ImmutableToken.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/LuceneQueryParser.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/ParsedQuery.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/ParsedTerm.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/QueryValidationServiceImpl.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/TokenCollectingQueryParser.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/parser/LuceneQueryParserTest.java
There was a bug in our detection of invalid operators that used terms, not parsed tokens. Tokens have more knowledge of the context and reflect the quoted text, so they are the correct place to look for invalid operators. 
Before:
After:
Added integration test
> Fix parsing of invalid search operators

- .github/workflows/updating-lockfile.yml
Prior to this change, the auto-fixing linter job was also committing changes to the yarn lockfile whenever they existed. This was unintuitive.
This change is now resetting the yarn lockfile, making sure it is not part of the generated PR. In addition, it is adding a second job which is solely generating PRs for updating the yarn lockfile.
> Separating linter/lockfile housekeeping jobs.

- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/Sort.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/elementConfiguration/SortConfiguration.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/sort/SortConfiguration.test.tsx
_Please note, this is a backport of #12427 for 4.1_
Before this PR, when adding a new sort to an aggregation, the field select showed a value of `-1`. This was due to an incorrect lookup of the current field's value in the component.
This change is now fixing this, showing an empty select for a new sort.
> Show empty field select for newly created sort in aggregation. (backport of #12427 for 4.1)

- graylog2-server/src/main/java/org/graylog2/bootstrap/preflight/PreflightCheckService.java
A failing preflight check was not logged but only written to STDERR.
This leads to the server stopping without any indication whatsoever of what might have caused it if you look only at the log file.
This PR adds the missing logging.
Steps to reproduce (prior to applying this PR):
* Start the server with a functioning journal
* Make the journal directory unwritable, e.g. with `chmod u-w journal`
* Start graylog again and notice that it stops again with the last line of the log file being something like ```2022-04-12 10:33:09,112 INFO : org.graylog2.bootstrap.preflight.SearchDbPreflightCheck - Connected to (Elastic/Open)Search version <Elasticsearch:7.10.2>```
> Log cause of failed preflight check

- graylog2-web-interface/src/components/bootstrap/BootstrapModalForm.jsx
_Please note, this PR is a backport of #12465 for 4.3 and should be merged together with https://github.com/Graylog2/graylog-plugin-enterprise/pull/3463_
With https://github.com/Graylog2/graylog2-server/pull/12189 we changed the way the `BootstrapModalForm` is being submitted. Instead of using `type="submit"` for the submit button we called the `onSubmit` action directly. Before the mentioned change, the form submit could influence a parent form, when using formik, by setting its `isSubmitting` attribute. This problem occurred when declaring a parameter, by clicking on the "declare parameter" button in the query validation popover.
Changing the way we submit the form resulted in other problems (https://github.com/Graylog2/graylog2-server/issues/12314 and …
> Revert changes in `BootstrapModalForm` and reimplement `type="submit"` for submit button. (backport of #12465 for 4.3)

- graylog2-web-interface/src/views/components/aggregationwizard/sort/SortConfiguration.test.tsx
- graylog2-web-interface/src/views/components/aggregationwizard/sort/SortConfiguration.tsx
_Please note, this is a backport of #12427 for 4.3_
Before this PR, when adding a new sort to an aggregation, the field select showed a value of `-1`. This was due to an incorrect lookup of the current field's value in the component.
This change is now fixing this, showing an empty select for a new sort.
> Show empty field select for newly created sort in aggregation. (backport of #12427 for 4.3)

- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchFilterDeprecationWarningsInterceptor.java
Opensearch slightly reworded a deprecation warning that we are filtering, so the filter is not working for the new message format and the logs get polluted. This PR adds the reworded message.
I think, this should be backported into the 4.3 release branch.
- [] New feature (non-breaking change which adds functionality)
- [] Refactoring (non-breaking change)
- [] Breaking change (fix or feature that would cause existing functionality to change)
> Added reworded OS Deprecation Warning

- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchFilterDeprecationWarningsInterceptor.java
Opensearch slightly reworded a deprecation warning that we are filtering, so the filter is not working for the new message format and the logs get polluted. This PR adds the reworded message.
backport of #12470
> Added reworded OS Deprecation Warning (backport of #12470)

- graylog2-web-interface/src/components/bootstrap/BootstrapModalForm.jsx
_Please note, this PR needs a backport for 4.3 and should be merged together with https://github.com/Graylog2/graylog-plugin-enterprise/pull/3462_
With https://github.com/Graylog2/graylog2-server/pull/12189 we changed the way the `BootstrapModalForm` is being submitted. Instead of using `type="submit"` for the submit button we called the `onSubmit` action directly. Before the mentioned change, the form submit could influence a parent form, when using formik, by setting its `isSubmitting` attribute. This problem occurred when declaring a parameter, by clicking on the "declare parameter" button in the query validation popover.
Changing the way we submit the form resulted in other problems (https://github.com/Graylog2/graylog2-server/issues/12314 and …
> Revert changes in `BootstrapModalForm` and reimplement `type="submit"` for submit button

- graylog2-web-interface/src/components/common/ConfirmDialog.tsx
- graylog2-web-interface/src/components/common/index.tsx
Fix `ConfirmDialog` close behaviour via `X` button (or pressing `ESC` or clicking on the background).
The UX is broken when using the `ConfirmDialog` and pressing the `X` button on the right, top. This also affect the keyboard shortcut ESC and clicking on the background.
Fix #12479
> Fix ConfirmDialog close behaviour via `X` button (or pressing `ESC` or clicking on the background)

- graylog2-web-interface/src/pages/SecurityPage.tsx
Fix for security page error when enterprise plugin isn't installed.
Addresses an error when the enterprise plugin isn't installed. When a user navigates to the security page without the enterprise plugin installed it will render correctly.
Before this when a user went to the security page it would error because it was trying to use a link from the plugin routes. Now if the enterprise plugin isn't installed it falls back to link to the enterprise information page.
Tested locally with the enterprise plugin removed, enterprise plugin installed but no security license and with enterprise plugin installed with security license active.
> Fix security tools placeholder route error

- graylog2-web-interface/src/routing/Routes.test.ts
- graylog2-web-interface/src/routing/Routes.ts
In #12468 `urijs` was updated. With this version, the [parsing of URLs starting with a double slash](https://github.com/medialize/URI.js/blob/gh-pages/CHANGELOG.md#11911-april-3rd-2022) (e.g. `//search`) has changed, interpreting the first path of the path as hostname (in this example `search`). This led to application routes being messed up with when the application prefix is `/`, swallowing the first part of the path, e.g. turning `/gettingstarted` into `/`.
This has lead to a particularly bad condition, resulting in repeated redirection to `/` when trying to redirect to the getting started page after logging in.
This change is now fixing the way application routes are being prefixed and normalized. The `qualifyUrls` function in the `routing/Routes` module is now returning proper …
> Fixing route prefixing after `urijs` update.

- graylog2-web-interface/src/pages/SecurityPage.tsx
Backport of #12475
Addresses an error when the enterprise plugin isn't installed. When a user navigates to the security page without the enterprise plugin installed it will render correctly.
Now if the enterprise plugin isn't installed it falls back to link to the
enterprise information page.
Before this when a user went to the security page it would error because
it was trying to use a link from the plugin routes. 
Tested locally
> Backport: Fix security tools placeholder route error

- graylog2-server/src/main/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategy.java
- graylog2-server/src/main/java/org/graylog2/periodical/IndexRotationThread.java
- graylog2-server/src/test/java/org/graylog2/indexer/rotation/strategies/TimeBasedRotationStrategyTest.java
The time-based rotation strategy remembers the last time an index was rotated in order to calculate the next rotation point.
When a node loses the leader state, it will stop being responsible for index rotation. The time-based rotation strategy, however, because it is a singleton, will still reference the last rotation times.
If for any reason, the node becomes leader again after a while, it will be unaware of any previous index rotations and will make a rotation decision based on stale data. If any rotations have happened in between, triggered by the other node, the now new leader will immediately rotate the index.
This is a rare scenario to happen, so I don't think this is critical. But nevertheless good to fix.
The proper way to fix this would be to remove the state from the rotation …
> Reset time based rotation strategy after leader change

- graylog2-web-interface/src/views/components/DashboardSearchBar.tsx
- graylog2-web-interface/src/views/components/WidgetQueryControls.tsx
- graylog2-web-interface/src/views/components/searchbar/PluggableSearchBarControls.test.tsx
With https://github.com/Graylog2/graylog2-server/pull/12441 we are now displaying pluggable search bar controls for the search bar on the default search page.
With this PR we are also rendering the pluggable search bar controls for dashboards and the widget edit mode.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/3401
> Implement pluggable search bar controls for dashboards and widget edit mode.

- graylog2-web-interface/src/views/actions/QueriesActions.ts
- graylog2-web-interface/src/views/components/DashboardSearchBar.test.tsx
- graylog2-web-interface/src/views/components/DashboardSearchBar.tsx
- graylog2-web-interface/src/views/components/Search.test.tsx
- graylog2-web-interface/src/views/components/Search.tsx
- graylog2-web-interface/src/views/components/SearchBar.test.tsx
- graylog2-web-interface/src/views/components/SearchBar.tsx
- graylog2-web-interface/src/views/components/WidgetQueryControls.tsx
- graylog2-web-interface/src/views/components/WithSearchStatus.tsx
- graylog2-web-interface/src/views/components/searchbar/SearchButton.test.tsx
- graylog2-web-interface/src/views/components/searchbar/SearchButton.tsx
- graylog2-web-interface/src/views/components/widgets/EditWidgetFrame.test.tsx
- graylog2-web-interface/src/views/logic/widgets/Widget.ts
- graylog2-web-interface/src/views/stores/QueriesStore.ts
- graylog2-web-interface/src/views/stores/SearchStore.ts
**Please note**, this PR needs to be merged together with https://github.com/Graylog2/graylog-plugin-enterprise/pull/3451
Before this change we were not reexecuting the search on enter press (in the query input or streams select), when the form values did not changed.
This was only the case when clicking on the search submit button. The reason, when there is no change:
- the search submit button did not triggered a form submit, but `SearchActions.refresh`, which triggered the rexecution.
- pressing enter in e.g. the query input triggered a search submit, which updates the query. Updating the current query also triggers a search submit, but only when the query actually changed.
With this PR we are:
- always submitting the search form, when clicking on the search submit button.
- we are …
> Always execute search, when pressing enter in search bar form.

- graylog2-server/pom.xml
- graylog2-web-interface/checkProductionBuild.js
This PR is removing support in `checkProductionBuild.js` to use our custom headless shell binary built for reporting. It is outdated and using it has no benefit, as the `puppeteer` package comes with a binary on its own.
> Removing usage of custom headless shell for build asset smoke test.

- graylog2-web-interface/src/components/common/FormikFormGroup.tsx
The `FormikFormGroup` component supports a `textarea` type but does not allow for a `rows` prop to be provided. This adds support for it. 
The `FormikFormGroup` component supports a `textarea` type but does not allow for a `rows` prop to be provided. This adds support for it. 
Created a FormikFormGroup with `type=textarea` and assigned a `row` value and saw the input properly displayed
> Adds missing rows prop to FormikFormGroup for textarea inputs

- graylog2-server/src/main/java/org/graylog/plugins/sidecar/migrations/V20180212165000_AddDefaultCollectors.java
- graylog2-server/src/main/java/org/graylog/plugins/sidecar/rest/resources/CollectorResource.java
- graylog2-web-interface/src/components/sidecars/configuration-forms/CollectorForm.jsx
Adds missing validation and config options for Darwin and FreeBSD.
They were already supported, but it was not possible to configure them.
Fixes https://github.com/Graylog2/collector-sidecar/issues/377
> Support config of sidecars on Darwin and FreeBSD

- full-backend-tests/src/test/java/org/graylog/plugins/views/QueryValidationResourceIT.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/QueryValidationResource.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/ValidationMessageDTO.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/CollectingQueryParserTokenManager.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/FixedBooleanQuery.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/LuceneQueryParser.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/TermCollectingQueryVisitor.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/TokenCollectingQueryParser.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/ValidationMessage.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/validators/FieldValueTypeValidator.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/elasticsearch/parser/LuceneQueryParserTest.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/validation/LuceneQueryParserTest.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/validation/TokenCollectingQueryParserTest.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/validation/ValidationMessageTest.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/validation/fields/UnknownFieldsIdentifierTest.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/validation/validators/InvalidOperatorsValidatorTest.java
The lucene query parser doesn't provide any connection between parsed (sub)queries and tokens used. This PR adds such a connection, which is later used to map key and value tokens, used for validation highlighting in queries. 
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/3491
It's refactoring, relies on existing tests covering the functionality.
For the query `timestamp:$param$ OR $param$ AND something` the assignments are:
```
Query timestamp:param(TermQuery) contains following tokens: timestamp,:,$param$,OR
Query _default_:param(TermQuery) contains following tokens: $param$,AND
Query _default_:something(TermQuery) contains following tokens: something
```
and after substitution (param=aaaa):
```
Query timestamp:aaaa(TermQuery) contains following tokens: …
```
> Map query tokens to subqueries

- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/NodeAdapterES7.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/NodeAdapterES7Test.java
Version check only fetches necessary parts of the response, not the whole JSON. Unit tests for version check have been added.
NodeAdapterES7 had no unit tests. I've added them.
NodeAdapterES7 used to grab the whole JSON, despite needing only 1-2 fields. "filter_path" request parameter has been used to limit the size of response.
Tested on Opensearch and Elasticsearch, with debugger and looking in the startup logs for messages like this one:
`Connected to (Elastic/Open)Search version <Elasticsearch:7.10.2>`
> Version check only fetches necessary parts of the response.

- graylog2-web-interface/src/views/logic/queries/TimeRangeToString.ts
This change is fixing a subtle issue when creating a human-readable duration for a time range through the `readableRange` function.  Prior to this change, that function used two different reference dates when calculating the length of a duration by calling `moment()` repeatedly.  One call happened when declaring the `dateAgo` variable, the other when calculating the diff between current time (which is another `moment()` call) and `dateAgo`. When the first and the second call are across a secound boundary, this could lead to the calculation being slightly off.  E.g. when the first call is happening at `12:00:00.999` and the second one at `12:05:01.000`, the function would return `5 minutes 1 second ago`. This also results in test failures happening for timings like that where the test …
> Fixing usage of multiple reference dates for human readable duration.

- graylog2-server/src/main/java/org/graylog2/jackson/DeserializationProblemHandlerModule.java
- graylog2-server/src/main/java/org/graylog2/jackson/JsonSubTypePropertyDefaultValue.java
- graylog2-server/src/main/java/org/graylog2/jackson/MissingTypeIdDeserializationProblemHandler.java
- graylog2-server/src/main/java/org/graylog2/shared/bindings/providers/ObjectMapperProvider.java
- graylog2-server/src/test/java/org/graylog2/jackson/JsonSubTypePropertyDefaultValueTest.java
The annotation can be used for JsonSubTypes use cases to provide a
default type value for documents that are missing the field.
See the javadoc of the JsonSubTypePropertyDefaultValue annotation for
more details.
> Introduce a JsonSubTypePropertyDefaultValue annotation

- graylog2-web-interface/src/views/components/Value.tsx
- graylog2-web-interface/src/views/components/visualizations/PlotLegend.tsx
- graylog2-web-interface/src/views/components/visualizations/pie/PieVisualization.tsx
- graylog2-web-interface/src/views/components/visualizations/pie/__tests__/PieVisualization.test.tsx
- graylog2-web-interface/src/views/components/visualizations/pie/__tests__/fixtures.ts
- graylog2-web-interface/src/views/logic/queries/useCurrentQueryId.ts
**Note:** This PR is a backport of #12545 to `4.3`.
This PR is fixing an issue where the field name which is used for the legend of a pie chart is taken from the wrong pivot. It happens when there is both at least one row and at least one column pivot defined for a pie chart. In that case, the field name is taken from the row pivot instead of the column pivot. 
This PR is now making the field mapping strategy in the `PlotLegend` component overridable, defaulting to the one which matches the chart data for most visualizations and use the mirrored one for pie charts.
Fixes https://github.com/Graylog2/graylog2-server/issues/12510.
> Using correct field for pie chart legends. (`4.3`)

- UPGRADING.md
- graylog2-server/src/main/java/org/graylog2/system/activities/SystemMessageServiceImpl.java
Mongo DB collection `system_messages` grows indefinitely. There is little point in storing years worth of old system messages. 
We now cap the size of collection, just as we do for e.g. `index_failures` collection.
**Note:** you cannot delete documents from a capped collection. Users will no longer be able trim the collection by deleting a subset of documents.
Resolves Graylog2/graylog2-server#6118
> Limit size of system_messages collection

- graylog2-server/src/main/java/org/graylog/events/contentpack/entities/HttpEventNotificationConfigEntity.java
- graylog2-server/src/main/java/org/graylog/events/notifications/EventNotificationConfig.java
- graylog2-server/src/main/java/org/graylog/events/notifications/NotificationResourceHandler.java
- graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotification.java
- graylog2-server/src/main/java/org/graylog/events/notifications/types/HTTPEventNotificationConfig.java
- graylog2-server/src/test/java/org/graylog/events/notifications/NotificationDtoTest.java
- graylog2-web-interface/src/components/common/URLWhiteListInput.tsx
- graylog2-web-interface/src/components/event-notifications/event-notification-details/HttpNotificationDetails.jsx
- graylog2-web-interface/src/components/event-notifications/event-notification-form/EventNotificationForm.jsx
- graylog2-web-interface/src/components/event-notifications/event-notification-types/HttpNotificationForm.jsx
Customers sometimes need to provide a basic auth string or API key in the HTTP notification event request.
We offer the following options:
* basic auth: specified string will be added as a base64-encoded authorization header 
* API key: the provided key name and value will be added as a query parameter
Resolves Graylog2/graylog-plugin-integrations#769
> HTTP event notification with basic auth or API key

- graylog2-web-interface/src/views/components/Value.tsx
- graylog2-web-interface/src/views/components/visualizations/PlotLegend.tsx
- graylog2-web-interface/src/views/components/visualizations/pie/PieVisualization.tsx
- graylog2-web-interface/src/views/components/visualizations/pie/__tests__/PieVisualization.test.tsx
- graylog2-web-interface/src/views/components/visualizations/pie/__tests__/fixtures.ts
- graylog2-web-interface/src/views/logic/queries/useCurrentQueryId.ts
**Note:** This PR is a backport of #12545 to `4.2`.
This PR is fixing an issue where the field name which is used for the legend of a pie chart is taken from the wrong pivot. It happens when there is both at least one row and at least one column pivot defined for a pie chart. In that case, the field name is taken from the row pivot instead of the column pivot. 
This PR is now making the field mapping strategy in the `PlotLegend` component overridable, defaulting to the one which matches the chart data for most visualizations and use the mirrored one for pie charts.
Fixes https://github.com/Graylog2/graylog2-server/issues/12510.
> Using correct field for pie chart legends. (`4.2`)

- graylog2-server/src/test/java/org/graylog/testing/containermatrix/SearchServer.java
- graylog2-server/src/test/java/org/graylog/testing/containermatrix/annotations/ContainerMatrixTestsConfiguration.java
Instead of testing a matrix of ES/OS and Mongo, we test with Mongo 4 and OpenSearch 1.3 per default.
Alternative version: #12569
This reduces build time on Jenkins significantly. (Approx. 30-40min reduction)
> Reduce matrix for faster integration tests

- graylog2-server/src/main/java/org/graylog2/inputs/transports/HttpTransport.java
- graylog2-server/src/test/java/org/graylog2/inputs/transports/HttpTransportConfigTest.java
Backport https://github.com/Graylog2/graylog2-server/pull/11529 to the `4.3` branch for inclusion in the `4.3.0` major release.
> Add Enable Bulk Receiving option for HTTP Gelf input (4.3 backport)

- graylog2-web-interface/src/views/components/searchbar/queryvalidation/QueryValidation.test.tsx
- graylog2-web-interface/src/views/components/searchbar/queryvalidation/QueryValidation.tsx
- graylog2-web-interface/src/views/components/searchbar/queryvalidation/types.ts
- graylog2-web-interface/src/views/components/searchbar/queryvalidation/validateQuery.ts
- graylog2-web-interface/test/fixtures/queryValidationState.ts
_Please note, this PR needs to be merged together with https://github.com/Graylog2/graylog-plugin-enterprise/pull/3534_
Before this change it was possible that old validation explanations were not being removed. This happen because we used the error message as a key for the list items. Because of recent changes this attribute is no longer a uniq one.
We are now using the index as a key, while this can be problematic in some cases, it is not a problem in this case because the list items have no state.
You can reproduce the bug by:
1. paste the following query: `GET or timestamp:"test test test"`
2. open the query validation explanation
3. remove `GET or`
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/3534
> Always clear query validation explanations.

- graylog2-web-interface/src/views/components/datatable/DataTableEntry.tsx
This PR is turning the `_column` function into a separate component.  Prior to it, the `_column` function called `useMemo` after #12528 was introduced, which lead to it being called conditionally resulting in different numbers of calls between rerenders, leading to an exception being thrown.
> Avoiding calling `useMemo` outside of component.

- graylog2-web-interface/src/views/components/DashboardSearchBar.test.tsx
With this PR we are mocking the `QueryInput` in the `DashboardSearchBar.test`, because the test case `should call SearchActions.refresh and set global override on submit when there are changes` is a flaky test.
Here is an example of its failure: https://jenkins.ci.torch.sh/job/Graylog-Snapshots/job/graylog2-server/job/master/2200/console
This test case is the only test case in this file which takes so much time, improving the performance of the `QueryInput`, by reducing the amount of rerenders is not helping with the long runtime. Mocking this component is reducing the runtime by ~70%.
> Mock `QueryInput` in `DashboardSearchBar.test` to reduce its runtime.

- graylog2-web-interface/src/hooks/useSearchPageLayout.ts
- graylog2-web-interface/src/pages/SecurityPage.tsx
- graylog2-web-interface/src/routing/Routes.ts
- graylog2-web-interface/src/views/components/Search.tsx
- graylog2-web-interface/src/views/components/ViewActionsMenu.test.tsx
- graylog2-web-interface/src/views/components/ViewActionsMenu.tsx
- graylog2-web-interface/src/views/components/contexts/SearchPageLayoutContext.test.tsx
- graylog2-web-interface/src/views/components/contexts/SearchPageLayoutContext.tsx
- graylog2-web-interface/src/views/components/contexts/SearchPagePreferencesContext.tsx
- graylog2-web-interface/src/views/components/contexts/SearchPagePreferencesProvider.test.tsx
- graylog2-web-interface/src/views/components/contexts/SearchPagePreferencesProvider.tsx
- graylog2-web-interface/src/views/components/contexts/SearchPagePreferencesState.tsx
- graylog2-web-interface/src/views/components/sidebar/ContentColumn.tsx
- graylog2-web-interface/src/views/components/sidebar/Sidebar.tsx
- graylog2-web-interface/src/views/types.ts
This change is needed to allow for the customization of the `Search` components' layout.
The first iteration allows hiding the sideNav and defining which viewActionMenu buttons are displayed.
* Adds layout configuration context for the `Search` component.
* This refactors the `SearchPageConfigContext` component to SearchPageLayoutContext
and all the SearchPageLayout domain components to SearchPagePreferences. This was done to prevent confusion about the domains these components are acting upon.
* This refactors the `SearchPageLayoutContext` into multiple components
to be more in line with our current approach to managing contexts and hooks.
* Renames "Analyst Tools" back to "Security" for routing purposes.
* Wrap both new contexts in `singleton()`
* Match file name to default export in
* …
> Feature/extend search page customization (#12600)

- graylog2-web-interface/src/views/components/searchbar/completions/FieldValueCompletion.test.ts
- graylog2-web-interface/src/views/components/searchbar/completions/FieldValueCompletion.ts
**Note:** This needs a backport to `4.3`.
Prior to this change, field value suggestions (existing field values which are suggested in the query input when a user is wring a query) were not escaped when the user selects one to be added to the query string. This could lead to invalid queries being produced (e.g. when the field contains a windows pathname).
This change is now adding escaping to those suggestions being produced by the field value completion. A more general solution in the `SearchBarAutoCompletions` class could be implemented at a later time, but as this change aims towards being integrated into the upcoming release, it tries to fix this issue in the least intrusive way.
Fixes #12667.
> Escape field value suggestions before adding them to query.

- UPGRADING.md
New config parameter retentionTime was added which accepts integer and deletes archives after specified number of days.
Default value is 0, which means the feature is turned off.
When value is changed the user will get a confirmation screen before proceeding with saving.
Documents issue: https://github.com/Graylog2/graylog-plugin-enterprise/issues/3514
> Archiving deletion job

- graylog2-web-interface/src/components/common/KeyValueTable.css
- graylog2-web-interface/src/components/common/KeyValueTable.jsx
- graylog2-web-interface/src/logic/authentication/okta/types.ts
Introduce new string `claims` to `OidcBackendConfig` and `OidcBackendConfigJson`.
And improve the `KeyValueTable` component (fix the dark mode):
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/3544
> chore: add claims string type to OidcBackendConfig and improve the KeyValueTable component

- graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionEntry.test.tsx
- graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionEntry.tsx
- graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.jsx
- graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionsContainer.jsx
- graylog2-web-interface/src/stores/event-definitions/EventDefinitionsStore.js
Addresses  Issue  #8017
Allows for the duplication of an event definition through the dropdown menu on the event definitions list page.
It also includes updates to clear our Eslint errors and warnings. Specifically around switching to the use of our confirm modal rather than relying on `window.confirm`
NOTE: This is not a complete refactor, considering the scope of the functionality it seemed unreasonable to wholesale update to our modern practices. Instead an issue will be created and addressed next cycle to actually upgrade to TS and ReactQuery.
To correct issue #8017 
Tested locally visually and unit tests ran.
> Allow cloning of existing event definitions

- graylog2-web-interface/src/components/enterprise/ProductLink.tsx
- graylog2-web-interface/src/pages/EnterprisePage.jsx
These changes load the `EntrepriseProductLink` and use it to render the `request link` when the enterprise plugin is installed that allows hiding the link when the license is valid.
fix Graylog2/graylog-plugin-enterprise#3606
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#3612
> Hide request when license valid

- graylog2-web-interface/src/pages/ShowMessagePage.test.tsx
- graylog2-web-interface/src/pages/ShowMessagePage.tsx
- graylog2-web-interface/src/views/hooks/useIsLocalNode.ts
Before these changes, opening the show single message page with a message coming from a Forwarder displayed an error, since we tried to fetch a local Input that actually belonged to a Forwarder.
To fix the issue we now use the `isLocalNode` function to decide whether the message was received on a local node directly (and we should therefore try to fetch the Input) or through a Forwarder.
Fixes https://github.com/Graylog2/graylog-plugin-enterprise/issues/3472
> Do not show error on messages from Forwarder in show single message page

- graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/LuceneQueryParser.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/MessagesResourceTest.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/validation/LuceneQueryParserTest.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/validation/QueryValidationServiceImplTest.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/validation/TestValidationContext.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/validation/ValidationMessageTest.java
Fixes #12725 
Query validation (Lucene Parser) takes into consideration so-called leading-wildcard setting from the config.
Even if clients set allow_leading_wildcard_searches = true in the config, validation returned errors when a query with leading wildcard was used.
1. Change **allow_leading_wildcard_searches** flag to true or false, restart the server.
2. Enter some queries starting with * or ? (foo:*bar or ?hatver...)
> Query validation (Lucene Parser) takes into account leading-wildcard setting.

- graylog2-server/src/main/java/org/graylog/events/event/EventProcessorEventFactory.java
- graylog2-server/src/main/java/org/graylog/util/Hostname.java
- graylog2-server/src/main/java/org/graylog/util/HostnameProvider.java
Previously we looked up the local Graylog node in MongoDB to get the
stored hostname. This can fail when MongoDB isn't reachable, or the node
is overloaded, and its entry in the "nodes" collection in the database is
gone.
This change introduces a Hostname class and a provider to retrieve the
local hostname without talking to the database.
> Improve hostname retrieval in EventProcessorEventFactory

- SECURITY.md
This change is solely updating the security policy in order to remove the overly specific version matrix which would require updates for every release.
> Updating security policy to remove need for maintenance.

- graylog2-web-interface/src/components/common/PublicNotifications.test.tsx
- graylog2-web-interface/src/components/common/PublicNotifications.tsx
Don't render notification when `isActive` is set to `false`.
Issue: https://github.com/Graylog2/graylog-plugin-enterprise/issues/3477
> fix: don't render inactive notifications

- graylog2-server/src/main/java/org/graylog2/contentpacks/constraints/PluginVersionConstraintChecker.java
- graylog2-server/src/test/java/org/graylog2/contentpacks/constraints/PluginVersionConstraintCheckerTest.java
The existing implementation had troubles with `-SNAPSHOT` version of the plugin and failed in tests. Using `Semver::withClearedSuffixAndBuild` to clear the suffix helps and we are doing the same operation in other checkers as well. So it's consistent with the rest of the codebase.
> Relaxed plugin version constraint

- graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/BucketSpec.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/buckets/DateRangeBucket.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/buckets/Time.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/buckets/Values.java
Field becomes a property of the BucketSpec interface. Because of that you won't have to cast to implementing class instance if you want to access "field" property. Field has been already present in all of the implementations, so it has been safe to move it to the interface.
> Field becomes a property of the BucketSpec interface.

- README.markdown
This is a very small change to our README which does:
- add a build badge showing the status of the Github action building the repo
- adding a reference to our channel on the libera network
> Adding build badge and info about libera.

- full-backend-tests/src/test/java/org/graylog/shared/system/stats/SystemStatsIT.java
- graylog2-server/src/test/java/org/graylog/testing/completebackend/ContainerizedGraylogBackend.java
- graylog2-server/src/test/java/org/graylog/testing/completebackend/TestLicenseImporter.java
- graylog2-server/src/test/java/org/graylog/testing/containermatrix/ContainerMatrixTestEngine.java
- graylog2-server/src/test/java/org/graylog/testing/containermatrix/annotations/ContainerMatrixTestsConfiguration.java
- graylog2-server/src/test/java/org/graylog/testing/mongodb/MongoDBFixtureImporter.java
- graylog2-server/src/test/java/org/junit/jupiter/engine/descriptor/ContainerMatrixTestClassDescriptor.java
- graylog2-server/src/test/java/org/junit/jupiter/engine/discovery/ContainerMatrixClassSelectorResolver.java
- graylog2-server/src/test/java/org/junit/platform/engine/support/hierarchical/ContainerMatrixHierarchicalTestEngine.java
Imports the license as a fixture and not via REST to prevent any race conditions during container startup.
/jenkins-pr-deps https://github.com/Graylog2/graylog-plugin-enterprise/pull/3495
> Add enterprise license as fixture

- graylog2-server/src/main/java/org/graylog/plugins/map/geoip/GeoLocationInformation.java
- graylog2-server/src/main/java/org/graylog/plugins/map/geoip/MaxMindIpLocationResolver.java
- graylog2-server/src/test/java/org/graylog/plugins/map/geoip/GeoLocationInformationTest.java
- graylog2-server/src/test/java/org/graylog/plugins/map/geoip/MaxMindIpLocationResolverTest.java
Updated MaxMindIpLocationResolver to use null-safe method to create GeoLocationInformation instance.
closes #12788 
Addresses a NullPointerException error caused in MaxMind Geo IP Information loader when the returned object contains null longitude/latitude fields.
To address the issue, a new method was added to GeoLocationInformation to create an instance from a Location, Country, and City object.  All the parameters as well as the needed fields from each parameter are checked for null.
The error prevents the entire message from being processed.
A new unit test was added to test that no exception is thrown if the MaxMind database reader returns null city response fields, or if any of the required response fields themselves have null fields.
> Added factory method to GeoLocationInformation to create instance with null checks

- pom.xml
Rev the okta SDK version to latest 8.2.1.
Amazingly I did not need to fix any breaking changes.
Resolves Graylog2/graylog-plugin-enterprise#3486
See https://github.com/okta/okta-sdk-java/releases
> Bump okta SDK version to 8.2.1

- full-backend-tests/src/test/java/org/graylog/plugins/views/SearchSyncIT.java
- full-backend-tests/src/test/java/org/graylog/testing/backenddriver/SearchDriver.java
- full-backend-tests/src/test/resources/org/graylog/plugins/views/search-with-three-empty-queries-v2.json
- full-backend-tests/src/test/resources/org/graylog/plugins/views/search-with-three-empty-queries.json
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchDTO.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchDTOv2.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchResource.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/SearchResourceExecutionTest.java
**Note:** This PR should be backported to `4.3`.
With the introduction of the `SearchDTO` class, which is meant to decouple internal data structures from REST requests/responses, a simple `Set` was used for queries. Unfortunately, the implementation for the `Set` used during deserialization does not preserve insertion order, leading to a different order when this `SearchDTO` is returned back to the caller after saving. The order of the queries set is used in the frontend to order the query tabs, so it relies on a stable ordering.
Therefore, this PR is making the type of the `queries` property more specific, by defining it as `LinkedHashSet`, which does preserve insertion order.
Obviously, the approach of relying on the ordering of elements in the set is not ideal. It does not communicate …
> Use ordered query set for consistent tab ordering.

- full-backend-tests/src/test/java/org/graylog/plugins/views/SearchSyncIT.java
- full-backend-tests/src/test/java/org/graylog/testing/backenddriver/SearchDriver.java
- full-backend-tests/src/test/resources/org/graylog/plugins/views/search-with-three-empty-queries-v2.json
- full-backend-tests/src/test/resources/org/graylog/plugins/views/search-with-three-empty-queries.json
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchDTO.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchDTOv2.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/rest/SearchResource.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/rest/SearchResourceExecutionTest.java
**Note:** Backport to `4.3` from #12833 
With the introduction of the `SearchDTO` class, which is meant to decouple internal data structures from REST requests/responses, a simple `Set` was used for queries. Unfortunately, the implementation for the `Set` used during deserialization does not preserve insertion order, leading to a different order when this `SearchDTO` is returned back to the caller after saving. The order of the queries set is used in the frontend to order the query tabs, so it relies on a stable ordering.
Therefore, this PR is making the type of the `queries` property more specific, by defining it as `LinkedHashSet`, which does preserve insertion order.
Obviously, the approach of relying on the ordering of elements in the set is not ideal. It does not communicate the fact …
> Use ordered query set for consistent tab ordering. (backport to 4.3 from #12833)

- .github/workflows/reviewbot.yml
This PR is enabling reviewbot for all PRs. Previously, it was enabled only on selected branches (`reviewbot/...`) for testing. Now that it has matured, it is enabled for all PRs, replacing the previous, jenkins-based linter job.
Reviewbot is running linter jobs for files which have changed in this PR. Any linter hints related to the changed code will be returned as checks annotations, showing up in the "Files changed" section of the PR and the status check will fail. For now, merging the PR will not be blocked though. Linter hints can be acceptable, if they have not been introduced in this PR and fixing them is beyond the scope of it (e.g.  for a bugfix PR that should be as non-intrusive as possible).
If the current PR should not be checked for linter hints, adding `[review skip]`, `[no …
> Enabling reviewbot for all PRs.

- graylog2-server/src/main/java/org/graylog2/shared/system/stats/fs/OshiFsProbe.java
- graylog2-server/src/main/java/org/graylog2/shared/system/stats/os/OshiOsProbe.java
Avoid blocking preflight on divide-by-zero exceptions. 
This just handles the divide by zero exceptions, without attempting to address the file system incompatibilities that are causing them. Not ideal, but if we are not even using a particular stat (e.g. percentage of unused inodes) then we should avoid blocking on it, when encountering some unexpected flavor of file system.
See linked issues for details.
Resolves #12820, #12818
> Prevent divide-by-zero exceptions in preflight checks

- graylog2-web-interface/src/components/common/PaginatedList.tsx
With this PR we are also forwarding the `hideFirstAndLastPageLinks` and `hidePreviousAndNextPageLinks` props to the `Pagination` component.
This is necessary for changes in https://github.com/Graylog2/graylog-plugin-enterprise/pull/3666
> Extending props of `PaginatedList` component.

- graylog2-server/src/main/java/org/graylog2/rest/resources/users/UsersResource.java
- graylog2-web-interface/src/components/event-notifications/event-notification-types/EmailNotificationFormContainer.jsx
- graylog2-web-interface/src/components/users/UserCreate/UserCreate.tsx
- graylog2-web-interface/src/stores/users/UsersStore.ts
As described in #12453, creating an email notification can be slow when there are a lot of users. This is due to the amount of work required to build the full set of user objects, particularly computing the set of permissions assigned to each user. Since we are only interested in the list of user emails, we should avoid fetching extraneous data.
The same thing applies to the user creation form, which fetches existing users to ensure uniqueness.
This PR adds the following optional query parameters to the `api/users` endpoint:
- include_sessions (default: true): if false, do not check current session information for users
- include_permissions (default: true): if false, do not return any permissions data
By calling `api/users?include_permissions=false&include_sessions=false` we speed up …
> Optimize populating of user dropdown

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackend.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackend.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendGeneratedRequestTestBase.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendSearchTypeOverridesTest.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/SearchType.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/MessageList.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/events/EventList.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/searchtypes/pivot/Pivot.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/views/WidgetDTO.java
- graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/EventListEntity.java
- graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/MessageListEntity.java
- graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/PivotEntity.java
- graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/SearchTypeEntity.java
- graylog2-server/src/main/java/org/graylog2/contentpacks/model/entities/WidgetEntity.java
Added filters field for Search Filters in proper model classes and their content pack equivalents (both in "widget" and "search type" families of model classes).
Search Filters from search types are now used by ES Backend during query generation.
Fixes #12848
Front-end wants to be able to use search filters on each widget/search type level. 
As Front-end is not yet done, you have to invoke search execution REST call manually, adding "filters" part in both the query itself and nested "search types". You can observe that results for different "search types" differ, depending on used "filters". You can observe that filters from the query itself and its "search types" are combined.
The existing tests have been also upgraded to test this feature automatically.
/jenkins-pr-deps …
> Search Filters usage in Widgets

- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchFilterDeprecationWarningsInterceptor.java
In PR #11810 is stated, that the message _always had a space_ in it, I started out without it. Now #12786 shows a problem that the given message was not filtered. What I first thought to be a typo during development is probably slightly different messages in ES 7.x versions - even if _git blame_ tells otherwise.
The filter can now work with both messages.
fixes #12786 
**Note: backport from #12787**
> Fix ES7 Warning Message Filter (backport to 4.3 from #12787)

- graylog2-web-interface/src/components/common/HoverForHelp.tsx
This PR is extending the `HoverForHelp` component in a way it can be used to display errors.
The `HoverForHelp` component displays an icon, which displays a help text when hovering over it.
> Implement error version for `HoverForHelp` component.

- graylog-storage-elasticsearch6/src/test/java/org/graylog/storage/elasticsearch6/views/ElasticsearchBackendTest.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendSearchTypeOverridesTest.java
- graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendTest.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/searchfilters/model/InlineQueryStringSearchFilter.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/searchfilters/model/ReferencedQueryStringSearchFilter.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/searchfilters/model/UsedSearchFilter.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/QueryTest.java
- graylog2-server/src/test/java/org/graylog2/contentpacks/model/entities/QueryEntityTest.java
Implementation of persistent disabled state for search filters.
Search Filters used in Searches have an additional flag - "disabled", to reflect that.
Front-end wants to persist and retrieve disabled Search Filters as well. 
Via Rest API, by adding and removing "disabled" flag on filters.
/jenkins-pr-deps Graylog2/graylog-plugin-enterprise#3698
> Implementation of persistent disabled state for search filters.

- graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitionEntry.tsx
- graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.jsx
- graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.test.tsx
- graylog2-web-interface/src/components/event-definitions/event-definitions/EventDefinitions.tsx
In #12706 the `renderEmptyContent` function in the `EventDefinition` component was declared [static](https://github.com/Graylog2/graylog2-server/pull/12706/files#diff-d63bb8afd1773532c36f162acb5111a8895e2c48a315ca72abb6f1b2a70dea66R53).
Unfortunately, the actual call was not changed from [`this.renderEmptyContent()` to `EventDefinition.renderEmptyContent()`](https://github.com/Graylog2/graylog2-server/pull/12706/files#diff-d63bb8afd1773532c36f162acb5111a8895e2c48a315ca72abb6f1b2a70dea66R77).
This PR is now fixing that, but differently. Instead of using a function to render the content, it is wrapped in a small stateless component itself (in aec544b418d9754993c41612c4b8f9e749f4c3ec). In addition, the component is turned into a function component (7929068a8edf7a8b6ea0a8874871fd81b5b3d952), …
> Fixing event definitions page when no event definitions exist.

- graylog2-web-interface/src/components/common/TextOverflowEllipsis.tsx
With this PR it will be possible to overwrite the `TextOverflowEllipsis` styling, e.g. like this: `styled(TextOverflowEllipsis)`.
i also tried adding the `as` / `forwardedAs` prop, but had some strange TS problem, I could not resolve easily.
> Allow overwriting `TextOverflowEllipsis` style.

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/views/searchtypes/pivot/ESPivot.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/views/searchtypes/pivot/ESPivot.java
Removed wrong log message when all aggregations are on columns on Pivot.
While the first commit contains only bug fix, the second one provides some refactoring that became possible.
The screenshot shows the situation - when you configure Pivot aggregations to contain columns only, there will be a "No aggregations generated for..." message sent to the log. It is a bug, aggregations are generated and there should be no information like that in the logs. 
Replicate configuration similar to the one present on the screenshot.
Check if there is no more debug-level log message present.
> Removed wrong log message when all aggregations are on columns on Pivot.

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/jest/JestUtils.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/ElasticsearchClient.java
- graylog2-server/src/main/java/org/graylog2/indexer/BatchSizeTooLargeException.java
When ES throws an exception due to batch size too large we now generate a custom exception to improve code maintainability.
> Custom exception when ES batch size too large

- graylog2-server/src/main/java/org/graylog/plugins/map/geoip/GeoIpResolverEngine.java
- graylog2-server/src/test/java/org/graylog/plugins/map/geoip/GeoIpResolverEngineTest.java
Closes #12904 
Added Graylog Schema Enforcement check to GeoIpResolverEngine when selecting field name prefix to add to message.
If the user has opted not to enforce the Graylog Schema, we want to scan ALL fields for possible IP addresses, as well as add original field name as the prefix for the Geo message field.  For example, given the field `source_ip`, with Graylog Schema Enforcement Off, the field added for the **Country Name** should be `source_ip_geo_country` (with the original field name as the prefix).  However, with enforcement on, the field name should be `source_geo_country`.
Without checking for schema enforcement on field prefix generation, the user's message fields will be modified in an unexpected/undesired way when enforcement is turned off.
1. Turn Graylog Schema …
> Added Graylog Schema Enforcement check to GeoIpResolverEngine when selecting field name prefix to add to message

- graylog-storage-elasticsearch6/src/main/java/org/graylog/storage/elasticsearch6/IndicesAdapterES6.java
- graylog-storage-elasticsearch7/src/main/java/org/graylog/storage/elasticsearch7/IndicesAdapterES7.java
- graylog2-server/src/main/java/org/graylog2/indexer/indices/Indices.java
- graylog2-server/src/test/java/org/graylog2/indexer/indices/IndicesTest.java
Whenever there are mo "Active Write Indices" and GL is running against OpenSearch, checking "Index Block Status" in "IndexBlockCheck" periodical will end up with an exception.
It turns out that there is a subtle difference in API between OpenSearch (https://opensearch.org/docs/latest/opensearch/rest-api/index-apis/get-settings/#url-parameters) and ES (https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-get-settings.html#get-index-settings-api-path-params). ES interprets no indices in URL as "_all" option, OpenSearch breaks. 
From now on, with both search engines, we will simply not check index block status if no indices are provided as input.
1. Avoiding error on OpenSearch.
2. Searching for blocks in all indices in Elasticsearch in case no indices provided was not the …
> Stopped asking for index block status when list of indices in empty

- full-backend-tests/src/test/java/org/graylog/plugins/views/QueryValidationResourceIT.java
- graylog2-server/src/main/java/org/graylog/plugins/views/search/validation/FieldTypeValidationImpl.java
- graylog2-server/src/test/java/org/graylog/plugins/views/search/validation/FieldTypeValidationTest.java
All queries from documentation are tested for successful validation.
Fixes #12780
Additionally, two small problems have been fixed: we used to have validation warnings while using proper numeric operands (i.e. ">=") and proper dates (as presented in the screenshot). It is not the case anymore. 
We need to be sure that all the queries used in documentation actually pass the validation phase.
Unit and integration tests have been added.
> All queries from documentation are tested for successful validation.

- graylog-project-parent/pom.xml
- graylog2-server/pom.xml
- graylog2-server/src/main/java/org/graylog/scheduler/JobSchedule.java
- graylog2-server/src/main/java/org/graylog/scheduler/JobScheduleStrategies.java
- graylog2-server/src/main/java/org/graylog/scheduler/schedule/CronJobSchedule.java
- graylog2-server/src/main/java/org/graylog/scheduler/schedule/IntervalJobSchedule.java
- graylog2-server/src/main/java/org/graylog/scheduler/schedule/OnceJobSchedule.java
- graylog2-server/src/test/java/org/graylog/scheduler/JobScheduleStrategiesTest.java
- graylog2-server/src/test/java/org/graylog/scheduler/schedule/CronJobScheduleTest.java
- pom.xml
So far we supported only once and interval strategies. For a future migration of the reporting to the generic scheduler, we'll need a strategy that allows configuration, that will be represented as a cron expression.
Added CronJobSchedule implementation of the JobSchedule strategy.
Preparing infrastructure for the migration of reporting
Added unit tests to all new functionality
> Add cron expression as a scheduler strategy

- graylog2-web-interface/src/components/permissions/SharingDisabledPopover.tsx
I added a new function getReadableType in SharingDisabledPopover to convert the entity type to a readable text which for now it only replaces the underscore (_) with a space
To avoid showing text in snake case because it is not very readable
fix #10827
> Fix/#10827 SharingDisabledPopover displays readable entity types

- graylog2-web-interface/src/views/components/searchbar/queryinput/BasicQueryInput.tsx
- graylog2-web-interface/src/views/components/searchbar/queryinput/QueryInput.tsx
With this PR it will be possible to define an `id` for the `textarea` of the `QueryInput`.
This way it will be possible to connect a label with input. For example like this:
```
<label htmlFor="query-input-id">A label</label>
<QueryInput inputId="query-input-id" />
```
Before this change clicking on the label had no effect, in the described case.
The `QueryInput` already has a `name` attribute, but it is being used for the id of the `textarea` container.
> Allow defining `id` for `QueryInput` textarea.

- graylog2-server/src/main/java/org/graylog2/rest/models/tools/responses/PageListResponse.java
Generic PageListResponse class is introduced.
Across our code base, we have a lot of very similar classes for a pagination response (i.e. StreamPageListResponse, ReportPageList, SearchFilterPageListResponse). They differ only by the name of the property containing elements on the page.
If we are fine with unifying the name of that property, we can get rid of those classes.
Even if we are not, it is a good idea to have a tool that would prevent us from introducing more classes like that in the future.
This small PR is a groundwork in that direction - it contains generic class for page list response.
No need to test it now.
> Generic PageListResponse class introduced

- graylog2-web-interface/src/theme/GlobalThemeStyles.js
With this PR we are defining `max-width: 100%;` for all `textarea` inputs.
Currently it is possible to break the layout when changing the size of a `textarea`. This affects almost all `textarea`s.
It is possible that the previous behaviour might be helpful for `textarea`s which are very small by default, but I am not aware of any case in the application.
> Define `max-width: 100%;` for all `textarea` inputs.

- graylog2-web-interface/src/components/indices/IndexDetails.tsx
This PR ensures index detail shard numbers (segments, open search contexts, and deleted messages) are formatted.
The linter items are unrelated to this, but I took a stab at fixing the `react/no-unstable-nested-components` error.
When purging some documents I noticed that, unlike other numbers in the index overview, the "deleted messages" number wasn't formatted, making it a bit difficult to read.
Manually replaced the values with some numbers and checked that they were properly formatted.
**Before:**
**After:**
> Format index detail shard numbers
